- java/code/src/com/suse/manager/matcher/MatcherJsonIO.java
- java/code/src/com/suse/manager/matcher/MatcherRunner.java
- java/code/src/com/suse/manager/webui/services/subscriptionmatching/SubscriptionMatchProcessor.java
- java/code/src/com/suse/manager/webui/services/subscriptionmatching/test/SubscriptionMatchProcessorTest.java
- java/code/src/com/suse/matcher/json/MatchJson.java
- java/spacewalk-java.changes
Review commit-by-commit please.
- Derive the log level from the 'debug' config option and pass it to matcher.
- Align the data transfer object to the current version of matcher: remove the `confirmed` flag from `JsonMatch` .
No difference.
- @mcalmer: I couldn't find any documentation about setting log level in gatherer - is there any?
- No tests: untestable
> Pass the log level to matcher

- testsuite/documentation/cucumber-steps.md
- testsuite/features/qam/reposync/srv_sync_qam_products.feature
- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/step_definitions/xmlrpc_common.rb
Adding a step to authorize as admin and then go to the Setup Wizard > Products page.
QAM scenarios were using `Given I am on the Admin page`, but this step was removed in the Uyuni branch here https://github.com/uyuni-project/uyuni/pull/1518/ . That wasn't ported to 4.0, where we were developing the QAM automated tests since last month. Now that moving to 4.1, we find that this method doesn't exist, and it didn't exist in Uyuni.
- Creating a new step definition to wrap the actions to login and go to Products page
- In addition, I fixed some wrong identation.
No difference.
- No documentation needed, it is already documented.
- QAM Tests using it
- Manager 4.1 https://github.com/SUSE/spacewalk/pull/12364 …
> Adding step definition to go to products page after authorized as admin (Port from Spacewalk)

- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/features/secondary/min_centos_openscap.feature
- testsuite/features/secondary/min_salt_openscap_audit.feature
- testsuite/features/secondary/min_ubuntu_openscap.feature
- testsuite/features/secondary/trad_centos_client.feature
This PR increases some timeouts.
Seen on 4.1 PRV:
* 499 seconds to build docker image, almost as much as the 500 seconds allocated
* 301 seconds to perform openscap scan, more than the 250 seconds allocated
4.1: SUSE/spacewalk#12373
4.0: SUSE/spacewalk#12374
3.2: SUSE/spacewalk#12360 and SUSE/spacewalk#12375
> Longer docker and openscap timeouts

- backend/satellite_exporter/satexport.py
- backend/server/handlers/sat/auth.py
- backend/server/handlers/xmlrpc/proxy.py
- backend/spacewalk-backend.changes
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/spacewalk-java.changes
- susemanager/susemanager.changes
- susemanager/yast/susemanager_cert.rb
- susemanager/yast/susemanager_manager.rb
- susemanager/yast/susemanager_reqs.rb
Fixes some uses of "Satellite", and others
- 'proxy' refers to SUSE Manager Proxy not to some random HTTP proxy, or any other kind of proxy. Make that explicit.
- Uppercase where needed
- Use PRODUCT_NAME and VENDOR_NAME intead of SUSE Manager and SUSE, and replace Satellite with PRODUCT_NAME
This will impact translations.
Before:
After: …
> Fix strings, mostly old "Satellite" ocurrences

- testsuite/features/secondary/trad_config_channel.feature
This PR adapts configuration tests to the files available on official images.
Ports:
* 3.2: #12396
* 4.0: #12395
* 4.1: #12394
> There's no /etc/sysconfig/cron on official images

- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/features/step_definitions/salt_steps.rb
Adapt to official images - 2
* (piggyback) 600s are enough for building containers according to statistics at SUSE/spacewalk#12360
* better test of contents of `/etc/vconsole.conf`
Ports:
* 3.2: SUSE/spacewalk#12404
* 4.0: SUSE/spacewalk#12403
* 4.1: SUSE/spacewalk#12402
> Adapt official images 2

- java/code/src/com/redhat/rhn/frontend/taglibs/list/CSVTag.java
- java/spacewalk-java.changes
- web/html/src/core/spa/spa-engine.js
- web/spacewalk-web.changes
Prevent Single Page Application engine to be applied to non-navigation links.
**Known issue**: after this patch the URL still gets overwritten by the link `href` value, even if it is not intended to.
No difference.
- No tests:
Fixes https://github.com/SUSE/spacewalk/issues/12216
> Force disable SPA for non-navigation links (bsc#1175512)

- testsuite/features/step_definitions/command_steps.rb
This fixes PR #2554
There was an error in the regular expression for ubuntu : probably a byproduct of factorizing too much :smile_cat: .
Thanks to @juliogonzalez and @mbologna for the long debugging session and finding the issue :clap: .
Ports:
* 3.2: not affected
* 4.0: SUSE/spacewalk#12415
* 4.1: SUSE/spacewalk#12414
> Fix regexp that changes ubuntu's repositories

- web/html/src/core/spa/spa-engine.js
- web/spacewalk-web.changes
https://bugzilla.suse.com/show_bug.cgi?id=1176512
When clicking the "Create" or "Delete" button in CLM the `navigation` event object has an empty `event` field . This leads to undefined type of error that's shown to the user. 
This PR checks if the `navigation.event` field is defined.
No difference.
Fixes #
> Fix JavaScript error caused by SPA navigation event with empty event field (bsc#1176503)

- susemanager-utils/testing/automation/push-to-obs.sh
- susemanager-utils/testing/docker/scripts/push-to-obs.sh
Change submission scripts to allow package lists. Required to generate patches for Uyuni, but also could be useful in the future if for some reason we want to submit individual packages.
2obs jobs would require changes.
For Uyuni we now have https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-master-2obs-patch
One caveat (that I hope we'll never have): if the list of packages is looong enough, the 
No difference.
https://github.com/uyuni-project/uyuni/wiki/Releasing-Uyuni-patches
- No tests: Changing part of the testing stuff.
None …
> Change submission scripts to allow package lists

- testsuite/features/secondary/min_salt_formulas_advanced.feature
- testsuite/features/step_definitions/salt_steps.rb
This PR aimes to fix a testsuite issue retrieving pillar data, which is not up to date sometimes when we save the formula.
Also, prevents an error handling the output text from salt.
No difference.
- No tests 
Need ports
> QA: Refresh the pillar data before retrieve values, after save the formula with changes

- susemanager-utils/testing/docker/master/uyuni-master-root/add_packages.sh
This PR fixes the cobbler cli test (`cobbler_cli_direct_test.py`). The `hardlink` package is needed by the cli test and was missing.
No difference.
No documentation needed: Just a bugfix
No tests: Just a bugfix
> Fix Cobbler cli test

- .github/workflows/rubocop.yml
Fix broken Ruby style checks at uyuni PRs.
Use Rubocop v0.83.0, i.e., the version useed to generate .rubocop_todo.yml.
See https://github.com/SUSE/spacewalk/issues/12456
No ports: only for Uyuni.
> Testsuite: Fix rubocop version for PR checks

- testsuite/features/step_definitions/command_steps.rb
Refactoring a step definition to fix a rubocop warning.
No difference.
- No tests
That needs port, in 4.0 and 4.1, it will go altogether with a previous refactor.
> Fixing Rubopcop warning about ConditionalAssignment style

- web/html/javascript/susemanager-sp-migration.js
- web/spacewalk-web.changes
see the commit msg.
We likely have many other occurences of this problem in the codebase, but that's for later.
- No documentation needed: bug
- No tests: legacy JS - no tests
https://github.com/SUSE/spacewalk/issues/12427
> Fix the jQuery selector in SP Migration page

- testsuite/features/step_definitions/salt_steps.rb
Make rubocop happy by:
* not using parentheses when calling length with no arguments
* having shorter blocks
Ports:
* 3.2: SUSE/spacewalk#12467
* 4.0: SUSE/spacewalk#12463
* 4.1: SUSE/spacewalk#12462
> Make rubocop happy

- client/tools/spacewalk-koan/test/test_merge_rd.py
This PR fixes the spacewalk-koan test. The test needs `/etc/fstab` which does not exist in the docker container.
See https://ci.suse.de/view/Manager/view/Manager-4.1/job/manager-4.1-spacewalk-koan/105/console
No difference.
- No documentation needed: No customer changing change.
- No tests: Change to tests.
> Fix for spacewalk-koan test

- java/code/src/com/redhat/rhn/taskomatic/core/TaskomaticDaemon.java
- java/spacewalk-java.changes
Improves logging in case of a fatal Taskomatic startup error
No difference.
- No documentation needed: small enhancement
Fixes #
> Log exception trace on fatal Taskomatic startup error

- susemanager-utils/testing/docker/master/uyuni-master-cobbler/add_packages.sh
- susemanager-utils/testing/docker/master/uyuni-master-root/add_packages.sh
This PR fixes the cobbler cli test (`cobbler_cli_direct_test.py` in `manager-Head-Cobbler-Tests`). The `hardlink` package is needed by the cli test and was missing. 
Furthermore it reverts #2607. @brejoc and I found out that the `hardlink` package should be added in a different place.
No difference.
No documentation needed: Just a bugfix
No tests: Just a bugfix
> Fix cobbler testsuite failure

- schema/spacewalk/common/data/rhnChannelArch.sql
- schema/spacewalk/common/data/rhnChannelPackageArchCompat.sql
- schema/spacewalk/common/data/rhnChildChannelArchCompat.sql
- schema/spacewalk/common/data/rhnCpuArch.sql
- schema/spacewalk/common/data/rhnPackageArch.sql
- schema/spacewalk/common/data/rhnPackageUpgradeArchCompat.sql
- schema/spacewalk/common/data/rhnServerArch.sql
- schema/spacewalk/common/data/rhnServerChannelArchCompat.sql
- schema/spacewalk/common/data/rhnServerPackageArchCompat.sql
- schema/spacewalk/common/data/rhnServerServerGroupArchCompat.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.1-to-susemanager-schema-4.2.2/120-arm64.sql
DB schema extension for Debian10-Minions on cpuarch=aarch64,osarch=arm64, Issue #2548
modified:   schema/spacewalk/common/data/rhnChannelArch.sql
modified:   schema/spacewalk/common/data/rhnChannelPackageArchCompat.sql
modified:   schema/spacewalk/common/data/rhnChildChannelArchCompat.sql
modified:   schema/spacewalk/common/data/rhnCpuArch.sql
modified:   schema/spacewalk/common/data/rhnPackageArch.sql
modified:   schema/spacewalk/common/data/rhnPackageUpgradeArchCompat.sql
modified:   schema/spacewalk/common/data/rhnServerArch.sql
modified:   schema/spacewalk/common/data/rhnServerChannelArchCompat.sql
modified:   schema/spacewalk/common/data/rhnServerPackageArchCompat.sql
modified:   schema/spacewalk/common/data/rhnServerServerGroupArchCompat.sql
modified: …
> DB schema extension for Debian10-Minions on cpuarch=aarch64,osarch=arm64, Issue #2548

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
- java/code/src/com/redhat/rhn/manager/content/test/smallBase/product_tree.json
- java/code/src/com/redhat/rhn/manager/content/test/smallBase/productsUnscoped.json
- java/spacewalk-java.changes
Installer Update channels are optional, but they are added by default when a product gets synced.
This cause exceptions when the channel is not available (e.g. when fromdir is used).
The existing method getAvailableRepositories() were only checking mandatory channels. As soon as
all mandatory channels are available, the whole products with its optional channels where marked as available too.
This change add a filter and remove all optional channels which are not available from the output.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/12445 …
> Uyuni installer updates optional

- java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java
- java/spacewalk-java.changes
When scheduling an sp migration after a dry run through
Events -> History -> Select successful dry run -> Click run migration
an ISE was thrown if the channel is a cloned channel.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/12389
> Fix SPMigration after dry run if channel is cloned (bsc#1176307)

- java/code/src/com/suse/manager/virtualization/VirtManagerSalt.java
- java/code/src/com/suse/manager/virtualization/test/TestVirtManager.java
- java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualGuestsController.java
- java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualNetsController.java
- java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualPoolsController.java
- java/code/src/com/suse/manager/webui/controllers/virtualization/test/VirtualGuestsControllerTest.java
- java/code/src/com/suse/manager/webui/services/iface/VirtManager.java
- java/code/src/com/suse/manager/webui/services/pillar/test/MinionVirtualizationPillarGeneratorTest.java
- java/code/src/com/suse/manager/webui/templates/virtualization/guests/show.jade
- java/code/src/com/suse/manager/webui/templates/virtualization/nets/show.jade
- java/code/src/com/suse/manager/webui/templates/virtualization/pools/show.jade
- java/spacewalk-java.changes
- web/html/src/manager/virtualization/HypervisorCheck.js
- web/html/src/manager/virtualization/guests/list/guests-list.js
- web/html/src/manager/virtualization/guests/list/guests-list.renderer.js
- web/html/src/manager/virtualization/nets/list/nets-list.js
- web/html/src/manager/virtualization/nets/list/nets-list.renderer.js
- web/html/src/manager/virtualization/pools/list/pools-list.js
- web/html/src/manager/virtualization/pools/list/pools-list.renderer.js
- web/spacewalk-web.changes
The user could add the virtualization entitlement and have none or part
of the dependencies set up on the virtualization host. A message will
indicate that the libvirt python binding (and thus the salt virt module)
is missing.
Also warn the user if the KVM or Xen modules are not loaded. This could
mean that they have been installed but the system still needs a reboot.
Screenshot if there is no libvirt python binding:
Screenshot if no running hypervisor can be found:
- No documentation needed: only error display
- No tests:  costly to cover automatically. These warning may also help debugging some of the testsuite issues related to nested KVM.
Fixes https://github.com/SUSE/spacewalk/issues/11997 …
> Warn user about missing hypervisor or libvirt binding

- testsuite/features/init_clients/buildhost_bootstrap.feature
- testsuite/features/init_clients/min_centos_salt.feature
- testsuite/features/init_clients/min_ubuntu_salt.feature
- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_bootstrap_negative.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/features/secondary/min_bootstrap_xmlrpc.feature
- testsuite/features/secondary/min_centos_ssh.feature
- testsuite/features/secondary/min_empty_system_profiles.feature
- testsuite/features/secondary/min_salt_mgrcompat_state.feature
- testsuite/features/secondary/min_ubuntu_ssh.feature
- testsuite/features/secondary/minssh_bootstrap_xmlrpc.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
- testsuite/features/secondary/srv_custom_system_info.feature
- testsuite/features/secondary/srv_menu.feature
- testsuite/features/secondary/trad_centos_client.feature
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/docker_steps.rb
- testsuite/features/support/commonlib.rb
Drop internal details on the web UI structure from Cucumber, and other minor changes.
Consistently, use step "I am on the System Overview page" when appropriate.
Prefer step "I follow the left menu ..." over step "I navigate to ..."
- testsuite/features/step_definitions/common_steps.rb
Add steps "I wait until the image build is completed"
and "I am on the new image page".
Move stuff for os image build here.
- testsuite/features/secondary/buildhost_osimage_build_image.feature:
Use the new steps.
- Manager-3.2: https://github.com/SUSE/spacewalk/pull/12437
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/12436
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/12435
> Testsuite: Hide internal details from Cucumber

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
As discussed in #2599, `target="_new"` has not been a part of the HTML spec for quite a long time now. Most browsers support it for legacy purposes, but it would be better to have `target="_blank" rel="noreferrer noopener"`. The latter addition is a security consideration, please see [the related MDN article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target) for more details.
No difference.
- No documentation needed: no visible or behavioral changes.
- No tests: no behavioral changes.
> Update deprecated link target attributes

- java/conf/rhn_java.conf
- java/spacewalk-java.spec
Define a different set of languages for Uyuni and SUSE Manager. For SUSE Manager only `en_EN` and `cn_CZ` will be supported initially.
No difference.
- No documentation needed: This is just automating something that was going to be done manually before the next SUSE Manager major release.
Packages to verify the result:
https://build.opensuse.org/project/show/home:juliogonzalezgil:branches:systemsmanagement:Uyuni:Master
https://build.suse.de/project/show/home:juliogonzalezgil:branches:Devel:Galaxy:Manager:Head (I could not build for SLE15SP2 at OBS as some packages from SLE15SP2 that are only build dependencies were missing)
- No tests: Cucumber testsuite should probably check this.
Fixes https://github.com/SUSE/spacewalk/issues/12284 …
> Enable different languages for Uyuni and SUSE Manager

- .github/workflows/java-checkstyle.yml
Try to pull fresh salt-netapi-client in github actions
No difference.
- No documentation needed: test fix
- No tests: test fix
> Exclude salt-netapi-client from action cache

- search-server/spacewalk-search/spacewalk-search.changes
- search-server/spacewalk-search/src/config/search/rhn_search_daemon.conf
Addresses #2436. Documentation was correct but code was not.
https://www.uyuni-project.org/uyuni-docs/uyuni/large-deployments/tuning.html#rhn-search-java-maxmemory reported 512 MB
No difference.
- No documentation needed: **documentation was correct, aligning implementation to it**
- No tests: **covered, tuning**
Fixes #2436
Supersedes #2513
Tracks https://github.com/SUSE/spacewalk/pull/12531
> Search daemon: default to reasonable max heap size

- java/code/webapp/WEB-INF/pages/rhnpackage/packagedetail.jsp
- java/spacewalk-java.changes
https://bugzilla.suse.com/show_bug.cgi?id=1176603
On a package page on the dashboard, clicking on the Download button doesn't download the package: it will reload the page with another URL - the one with the package location - but it won't download it. 
No difference.
https://github.com/SUSE/spacewalk/issues/12459
> Fix the links for downloading the binaries in the package details UI (bsc#1176603)

- web/html/src/manager/admin/config/monitoring-admin.js
- web/spacewalk-web.changes
https://bugzilla.suse.com/show_bug.cgi?id=1176172
Link to documentation in Admin -> Manager Configuration -> Monitoring was wrong.
No difference.
- No documentation needed: small bugfix
- No tests: cosmetic issue
https://github.com/SUSE/spacewalk/issues/12447
> Fix link to documentation in Admin -> Manager Configuration -> Monitoring (bsc#1176172)

- java/code/src/com/redhat/rhn/frontend/xmlrpc/activationkey/ActivationKeyHandler.java
This PR refreshes API docs for the `activationkey` namespace, in particular in regard of add-on system types which changed in the UI but changes are not reflected in the API yet.
No difference.
- No documentation needed: **this is a documentation change itself**
- No tests: **we do not test docs**
> ActivationKeyHandler: refresh API docs

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Add two missing packages to bootstrap data for Ubuntu 20.04
Port of https://github.com/SUSE/spacewalk/pull/12538
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/12538
> Ubuntu bootstrap repo modify

- .github/workflows/java-checkstyle.yml
This patch reverts commit c76f1e1ca2d891b14bcb7cc51eabbcba1791a775 to re-enable caching of the dependencies for the checkstyle workflow after a problem with one of the cached libraries not being updated.
No difference.
- No documentation needed, only CI is affected.
- No tests needed, only CI is affected.
Reverts #2642.
> Re-enable caching for the checkstyle workflow

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/susemanager-schema.spec
- spacewalk/admin/spacewalk-admin.changes
- spacewalk/admin/spacewalk-service.systemd
Print info messages about doing a database schema upgrade to inform the admin that it might take longer.
I did not find a better way as systemd does not let you print on the console. Showing progress is not possible.
Other ideas as showing a webpage is not possible either as apache is stopped.
Starting a different webserver just for this sounds a bit like overkill to me.
More ideas are welcome.
No difference.
- No documentation needed: **we just print additional info on the terminal**
- No tests: **just an info message added**
Fixes https://github.com/SUSE/spacewalk/issues/11923
Tracks https://github.com/SUSE/spacewalk/pull/12555 …
> add message about schema upgrade running

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
python-cryptograpy now has new requirements at least on SP4 and SP5.
```
Package python-packaging is not included in bootstrap repository for SLE12SP5, which causes bootstrap of SLE12SP5 traditional client to fail as you can see bellow:
4 Problems:
Problem: nothing provides python-packaging needed by python-cryptography-2.1.4-7.28.2.x86_64
Problem: nothing provides python-packaging needed by python-cryptography-2.1.4-7.28.2.x86_64
Problem: nothing provides python-packaging needed by python-cryptography-2.1.4-7.28.2.x86_64
Problem: nothing provides python-packaging needed by python-cryptography-2.1.4-7.28.2.x86_64
```
If I check at a SLE12SP5 JeOS image:
This PR adds the missing packages to the bootstrap scripts for SLE12 >= SP1.
I verified that all packages I am adding are available for …
> Fix SLE12 >= SP1 JeOS bootstrap issues (bsc#1176913)

- java/code/src/com/redhat/rhn/frontend/action/user/CreateUserAction.java
- java/code/src/com/redhat/rhn/manager/user/CreateUserCommand.java
- java/code/webapp/WEB-INF/pages/user/create/usercreate.jsp
- java/spacewalk-java.changes
This fixes 2 issues one where any password validation during user creation with the web ui was ignored (this should only happen on browsers that don't support the input field maxlength attribute. And second the error message when trying to create a with a password exceeding the max length.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/12509
> Fix usercreation 

- .github/workflows/java-checkstyle.yml
This should help to enforce a fresh cache for the checkstyle workflow in order to fix the [checkstyle runs on master](https://github.com/uyuni-project/uyuni/actions?query=workflow%3A%22Java+checkstyle%22).
No difference.
- No documentation needed, only affects CI.
- No tests needed, only affects CI.
Fixes hopefully the checkstyle workflow caching issue.
> Change the cache key to enforce a clean cache

- client/rhel/spacewalk-client-tools/src/up2date_client/rpcServer.py
- client/rhel/spacewalk-client-tools/src/up2date_client/up2dateErrors.py
Fixed by rephrasing messages in a product-neutral way.
No difference.
- No tests: no tests there
> Fix the broken module dependencies introduced by parametrizing product string

- susemanager-utils/susemanager-sls/salt/channels/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
When yum has disabled plugins, Uyuni cannot work properly. Enable them during bootstrapping
No difference.
- No documentation needed: **should work as described**
Fixes https://github.com/SUSE/spacewalk/issues/10579
Tracks https://github.com/SUSE/spacewalk/pull/12576 https://github.com/SUSE/spacewalk/pull/12577
> Ensure yum plugin is enabled

- scripts/translation/update-all-translation-strings.sh
Add spacecmd to translation update tool
No difference.
- No tests: **internal tooling**
> add spacecmd

- testsuite/features/qam/smoke_tests/smoke_tests.template
Fix a step name.
It completes: https://github.com/SUSE/spacewalk/pull/12601
- Manager-4.1
> QAM: add missing 'a' at step

- java/code/src/com/redhat/rhn/frontend/xmlrpc/activationkey/XmlRpcActivationKeysHelper.java
- susemanager-utils/susemanager-sls/src/doc/uyuni_config_execution_module_doc.txt
- susemanager-utils/susemanager-sls/src/doc/uyuni_config_state_module_doc.txt
- susemanager-utils/susemanager-sls/src/examples/uyuni_config_hardcode.sls
- susemanager-utils/susemanager-sls/src/modules/uyuni_config.py
- susemanager-utils/susemanager-sls/src/states/uyuni_config.py
- susemanager-utils/susemanager-sls/src/tests/test_state_uyuni_config.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- testsuite/features/secondary/srv_user_configuration_salt_states.feature
- testsuite/features/upload_files/salt/setup_users_configuration.sls
- testsuite/features/upload_files/salt/teardown_users_configuration.sls
Add support for activation keys on the salt configuration modules.
No difference.
- [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pull/577)
Fixes https://github.com/SUSE/spacewalk/issues/12495
Tracks:
Needs backport to 4.1
> Salt configuration modules for Activation Keys

- susemanager-utils/testing/docker/master/uyuni-master-root/Dockerfile
As uyuni-master acts as templates for SUSE Manager container, add a hint about special handling of container-suseconnect which exist in SLES containers
No difference.
- No tests: **tooling only**
> add hint about container-suseconnect in Dockerfile for SLES

- susemanager-utils/susemanager-sls/src/doc/uyuni_config_state_module_doc.txt
- susemanager-utils/susemanager-sls/src/states/uyuni_config.py
- susemanager-utils/susemanager-sls/src/tests/test_state_uyuni_config.py
Follow up PR of: https://github.com/uyuni-project/uyuni/pull/2666
No difference.
- No documentation needed: follow up pr
Fixes https://github.com/SUSE/spacewalk/issues/12495
> salt config state: activation key absent accepts name

- client/tools/spacewalk-koan/Makefile.spacewalk-koan
Takes care of ownership for spacewalk-koan test output files.
This fixes problems with have now that we wipe workspaces on the Jenkins jobs, before cloning repositories.
As the spacewalk-koan tests run inside a docker container and they generate files on a folder that's a bind mount, such files are owned by root from the docker host POV, so the Jenkins user can't remove them.
So this fix basically adds two scripts, before and after running the test, to generate a list of files created during testing, and adjust the ownership.
No difference.
- No documentation needed: Test fixes
- Text fixes
None, but this needs backporting to SUSE Manager 4.1 and 4.0. …
> Take care of ownership for spacewalk-koan test output files

- testsuite/features/qam/smoke_tests/smoke_tests.template
Port of  https://github.com/SUSE/spacewalk/pull/12628
Not all the systems gave a text "Reboot completed" after they finish successfully a reboot. Form the systems currently deployed in qam environment, only CentOS provide it. So, we need to use a text more generic for all our systems.
Example:
No difference.
- Cucumber test changed
Need ports:
- Manager-4.1:  https://github.com/SUSE/spacewalk/pull/12628
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/12638
> [Port] QAM: Find generic text to match after reboot

- testsuite/.rubocop_todo.yml
- testsuite/features/step_definitions/common_steps.rb
Print commands output if bootstrap with script fails
Ports:
* 4.1: SUSE/spacewalk#12633
* 4.0: SUSE/spacewalk#12634
* 3.2: SUSE/spacewalk#12636
> More debug output if bootstrap fails

- testsuite/features/secondary/buildhost_docker_auth_registry.feature
- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/secondary/min_bootstrap_ssh_key.feature
- testsuite/features/step_definitions/docker_steps.rb
- testsuite/features/support/commonlib.rb
Drop internal details from Cucumber
Mimic the way how the users navigate the UI.
- testsuite/features/secondary/buildhost_osimage_build_image.feature:
Rewrite the step that navigates to the kiwi image store.
Navigate to image build/list like users do (i.e. by menu clicks).
- testsuite/features/support/commonlib.rb (compute_image_url):
Delete this function.
- testsuite/features/step_definitions/docker_steps.rb:
Mimic how users navigate os images.
Deleted unused steps.
- testsuite/features/secondary/min_bootstrap_ssh_key.feature:
Hide systems page url from cucumber.
https://github.com/SUSE/spacewalk/issues/12540
- Manger-4.1: 
- Manager-4.0: 
- Manager-3.2:  …
> Testsuite: Minor refactor on kiwi images navigation steps

- java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java
- java/spacewalk-java.changes
Boot image pillar generated after build of PXE OS image contains local path, which is used for storing the image on Branch Server.
Until now, the path was based on boot image name. This caused conflicts when an image was rebuilt with new kernel but the image version stayed unchanged (we recommend to increase image version in such situations, but we do not enforce it).
This PR adds build id to the path, so new directory is used for each build.
No difference.
- partially covered by OpenQA tests
Fixes # https://github.com/SUSE/spacewalk/issues/11811 …
> Include build id in boot image local path

- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/step_definitions/docker_steps.rb
Add closing double quote around the argument in one step.
- https://github.com/SUSE/spacewalk/issues/12540
It fixes a commit from:  https://github.com/uyuni-project/uyuni/pull/2680/
(No port needed for Manager-4.0)
- Manager-3.2: https://github.com/SUSE/spacewalk/pull/12661
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/12660
> Testsuite: Add missing quote in one step

- testsuite/features/core/proxy_branch_network.feature
- testsuite/features/core/proxy_register_as_minion_with_gui.feature
- testsuite/features/core/proxy_register_as_minion_with_script.feature
- testsuite/features/core/proxy_register_as_trad_with_script.feature
Package `expect` is no more needed only for retail setup, but also for client bootstrapping via script. As a result it is necessary to move its installation to more generic features, which are these providing proxy setup in this case. 
Current state of things can cause failure of bootstrap of client via bootstrap script if no private network is specified (which is specific for retail setup).
No difference.
- No documentation needed: **testsuite**
Tracks https://github.com/SUSE/spacewalk/pull/12653 …
> Testsuite - move expect package installation to different feature

- testsuite/features/qam/add_activation_keys/add_activation_key.template
- testsuite/features/qam/add_custom_repositories/add_ceos6_repositories.feature
- testsuite/features/qam/add_custom_repositories/add_ceos7_repositories.feature
- testsuite/features/step_definitions/navigation_steps.rb
Port of https://github.com/SUSE/spacewalk/pull/12664
- Fixing mount path on CentOS
- Unchecking the metadataSigned option on CentOS mounted DVD
- Including extra repos in the activation keys
No difference.
- No tests 
Ports needed:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/12664
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/12666
> QAM: Fixing mount path on CentOS and including extra repos in the activation keys

- java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualGuestsController.java
- web/html/src/manager/virtualization/HypervisorCheck.js
- web/html/src/manager/virtualization/guests/list/guests-list.js
Fix visual annoyance introduced by  https://github.com/uyuni-project/uyuni/pull/2611
The missing virtualization hypervisor message should only be shown for Salt systems, not traditional ones.
No difference.
- No documentation needed: just hiding a message when not needed
- No tests: hard to test
> Only show the missing hypervisor error message on Salt systems

- .github/workflows/java-checkstyle.yml
- java/buildconf/ivy/obs-maven-config.yaml
- susemanager-utils/testing/automation/java-checkstyle.sh
- susemanager-utils/testing/automation/java-unittests-pgsql.sh
The latest obs-to-maven doesn't depend on osc anymore. However this
introduces a few changes in the configuration file.
No difference.
- No documentation needed: tooling
- No tests: tooling change
- Requires: https://github.com/uyuni-project/obs-to-maven/pull/3
> Update configuration for latest obs-to-maven

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/HandlerFactory.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/PowerManagementOperationFailedException.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/provisioning/powermanagement/PowerManagementHandler.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerPowerCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerPowerSettingsUpdateCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerUnregisteredPowerSettingsUpdateCommand.java
- java/spacewalk-java.changes
- testsuite/features/secondary/srv_power_management.feature
- testsuite/features/secondary/srv_xmlrpc_power_management.feature
- testsuite/features/step_definitions/xmlrpc_common.rb
- testsuite/features/support/xmlrpc_powermanagement.rb
- testsuite/run_sets/secondary.yml
Implement XMLRPC interface for Power Management.
There are 2 use cases:
1. we have an existing registered system
2. we just created a cobbler system record for an initial installation (system.createSystemRecord(...))
No difference.
- XMLRPC docs are autogenerated
Fixes https://github.com/SUSE/spacewalk/issues/9860
Tracks 
> powermanagement xmlrpc api

- testsuite/features/secondary/buildhost_osimage_build_image.feature
We disable repositories on branch server only if we have a branch server.
But we were re-enabling them in all cases.
Thanks @cbosdo for the catch.
Ports:
* 4.1: SUSE/spacewalk#12705
* 4.0: SUSE/spacewalk#12706
* 3.2: SUSE/spacewalk#12707
> Add missing tags

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Add LTSS to SLE12SP1/2/3/4 to the bootstrap repository definitions (bsc#1177524) 
After we merged https://github.com/uyuni-project/uyuni/pull/2655, two packages come from LTSS, so without the PID the bootstrap repository creation fails:
```
Temporary output repo path: /srv/www/htdocs/pub/repositories/sle/12/3/bootstrap.tmp/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
ERROR: package 'python-asn1crypto' not found
ERROR: package 'python-packaging' not found
```
Validated by @lkotek for SLE12SP3 LTSS
No difference.
- No documentation needed: Bigfix
- No tests: We still don't cover all clients.
https://github.com/SUSE/spacewalk/issues/12710 …
> Add LTSS to SLE12SP1/2/3/4 (bsc#1177524)

- java/code/src/com/suse/manager/webui/controllers/ImageBuildController.java
- java/spacewalk-java.changes
Fix: reinspecting a container image (bsc#1177092)
Regression of uyuni-project/uyuni#2108
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/12604
>  Fix: reinspecting a container image (bsc#1177092)

- testsuite/features/upload_files/salt/teardown_users_configuration.sls
correct the teardown state apply on cucumber test which had the wrong activation key name.
No difference.
- No documentation needed: correct cucumber test
- No tests: correct cucumber test
Fixes #
Tracks # Backport to manager 4.1
> uyuni configuration state cucumber test bug

- backend/satellite_tools/xmlSource.py
- backend/spacewalk-backend.changes
This addresses the following error:
```
Importing:  ERROR: Encountered IntegrityError:
null value in column "checksum" violates not-null constraint
```
In some cases, the `md5sum` backwards-compatibility attribute might be present but None. This patch conditionally filters out such attributes.
No difference.
- No tests: **there is no Cucumber coverage for ISS, adding it is a major separate topic**
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1177235
> Prevent IntegrityError during mgr-inter-sync execution (bsc#1177235)

- testsuite/features/profiles/Makefile
- testsuite/features/profiles/internal_prv/Docker/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/authprofile/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/serverhost/Dockerfile
Update the Docker profile used at Provo to use the new network: minima-mirror.mgr.prv.suse.net
> Fix docker registry URL at Provo

- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerDistroHelper.java
- java/spacewalk-java.changes
Renaming an autoinstall distro changed the name in the db but not in Cobbler (bsc#1175876) resulting in an error at autoinstall time:
```
trace:java.lang.NullPointerException
at com.suse.manager.webui.services.SaltServerActionService.autoinstallInitAction(SaltServerActionService.java:1699)
at com.suse.manager.webui.services.SaltServerActionService.callsForAction(SaltServerActionService.java:381)
at com.suse.manager.webui.services.SaltServerActionService.executeForRegularMinions(SaltServerActionService.java:484)
at com.suse.manager.webui.services.SaltServerActionService.execute(SaltServerActionService.java:470)
at com.redhat.rhn.taskomatic.task.MinionActionExecutor.execute(MinionActionExecutor.java:125)
at com.redhat.rhn.taskomatic.task.RhnJavaJob.execute(RhnJavaJob.java:88)
at …
```
> Bugfix: renaming autoinstall distro didn't change the name of the Cobbler distro (bsc#1175876)

- susemanager-utils/susemanager-sls/modules/runners/mgrk8s.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Fix a corner case in which the pod status are empty
No difference.
- No documentation needed: internal
- No tests: Salt runner
> Fix: do not break when pod status is empty (bsc#1161903)

- susemanager/rhn-conf/rhn_server_susemanager.conf
- susemanager/susemanager.changes
Using auto flush slow down the repo building process a lot. In addition it removed special crafted bootstrap repos.
The downsides of `flush = on` are bigger than with `flush = off` so we decided to change the default.
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/597
- Already covered
Tracks https://github.com/SUSE/spacewalk/pull/12712
> Disable flush

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/template/StringResource_sk.xml
- java/conf/rhn_java.conf
- java/spacewalk-java.changes
- testsuite/features/secondary/srv_distro_cobbler.feature
- testsuite/features/secondary/srv_power_management.feature
- testsuite/features/secondary/srv_power_management_redfish.feature
- testsuite/features/secondary/srv_xmlrpc_power_management.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/upload_files/Redfish-Mockup-Server/AUTHORS.md
- testsuite/features/upload_files/Redfish-Mockup-Server/CHANGELOG.md
- testsuite/features/upload_files/Redfish-Mockup-Server/LICENSE.md
- testsuite/features/upload_files/Redfish-Mockup-Server/README.md
- testsuite/features/upload_files/Redfish-Mockup-Server/redfishMockupServer.py
- testsuite/features/upload_files/Redfish-Mockup-Server/requirements.txt
- testsuite/features/upload_files/Redfish-Mockup-Server/rfSsdpServer.py
- testsuite/run_sets/secondary.yml
Enable Redfish power management by default
No difference.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/12767
Fixes https://github.com/SUSE/spacewalk/issues/9866
> enable redfish by default

- .github/workflows/java-checkstyle.yml
This patch reverts commit 4552dc2b5cb62071e29aa6756e61c8a2f424055e: As `obs-to-maven` does no longer rely on `osc`, we can go back to run this workflow for each PR, and it should even work for PRs created from forks. Additionally it would run after changes to `*.java` files are pushed to master, i.e. after a PR is merged that contains Java code.
If this proves to be working fine it should be a full replacement of the Jenkins checkstyle job that could then be disabled in a subsequent step.
No difference.
- No documentation needed, only CI is affected.
- No tests needed, only CI is affected.
No links for this PR.
If you …
> Run the checkstyle workflow on all PRs

- testsuite/features/qam/add_custom_repositories/add_ubuntu2004_repositories.feature
- testsuite/features/qam/init_clients/ubuntu2004_minion.feature
- testsuite/features/qam/init_clients/ubuntu2004_ssh_minion.feature
- testsuite/features/support/constants.rb
- testsuite/features/support/env.rb
- testsuite/features/support/twopence_init.rb
- testsuite/run_sets/qam_add_custom_repositories.yml
- testsuite/run_sets/qam_init_clients.yml
This PR adds running of Ubuntu 20.04 to QAM test suite.
Fixes SUSE/spacewalk#12765.
Ports:
* 4.1: SUSE/spacewalk#12787
* 4.0: SUSE/spacewalk#12788
* 3.2: no QAM
> Add Ubuntu 20.04 for QAM

- testsuite/features/step_definitions/common_steps.rb
When the command output contains non-ascii Unicode characters and we
give to `puts` an array `arr = [cmd_output, cmd_ret_code]`, then
Cucumber might be not able to dump the json file.
Instead of arr use arr.to_s as `puts` argument (spacewalk#12739).
Give to `puts` the string representation of the array.
https://github.com/SUSE/spacewalk/issues/12739
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/12784
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/12783
> Prevent from unescaped special chars in the stdout

- testsuite/features/support/env.rb
Based on the answer written here https://stackoverflow.com/questions/57700388/how-to-set-unexpectedalertbehaviour-in-selenium-python as when reloading a page we were experiencing an unexpected alert which wasn't caught, I changed one option to another into the chromedriver options.
On this PR, we will instead include both, as apparently in some cases the previous option was functional.
No difference.
- No tests
Need ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/12662
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/12798 …
> QA: Re-adding unexpectedAlertBehaviour into our chromedriver options

- testsuite/features/step_definitions/security_steps.rb
Fix cucumber test context path
No difference.
- No documentation needed: nothing to document
- No tests: cucumber test fix
Fixes #
Tracks # https://github.com/SUSE/spacewalk/pull/12804
> Adjust css location path test

- testsuite/features/step_definitions/common_steps.rb
Having these quotes in the output break some Cucumber formatters; when
this happen, the testsuite reporter is not created, and no e-mail is
sent.
- testsuite/features/step_definitions/common_steps.rb
https://github.com/SUSE/spacewalk/issues/12739
Continuation of  https://github.com/uyuni-project/uyuni/pull/2724
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/12813
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/12814
> Replace unicode quotes at stdout with single quotes

- testsuite/features/step_definitions/common_steps.rb
Remove unicode expressions like \xHH from the stdout.
Escaping the initial slash is not enough: the Cucumber formatter
still find them and it crashes.
Replace unicode \xHH with ?.
https://github.com/SUSE/spacewalk/issues/12739
Continuation of https://github.com/uyuni-project/uyuni/pull/2732
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/12815
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/12816
> Testsuite: Drop unicode \xHH from stdout

- java/code/src/com/redhat/rhn/taskomatic/TaskomaticApi.java
- java/code/src/com/redhat/rhn/taskomatic/task/SSHMinionActionExecutor.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/manager/webui/services/test/SaltServerActionServiceTest.java
- java/conf/rhn_java.conf
- java/spacewalk-java.changes
- schema/spacewalk/common/data/rhnTaskoBunch.sql
- schema/spacewalk/common/data/rhnTaskoTask.sql
- schema/spacewalk/common/data/rhnTaskoTemplate.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.2-to-susemanager-schema-4.2.3/200-minionSSHActionExecutor.sql
Port of https://github.com/SUSE/spacewalk/pull/12522
Use a separate taskomatic job to execute actions on SSH minions. The normal MinionActionExecutor will schedule the SSH actions as separate jobs.
The number of concurrent SSH executions can be controlled using the configuration parameter `taskomatic.com.redhat.rhn.taskomatic.task.SSHMinionActionExecutor.parallel_threads` (default 1).
The total number of Taskomatic worker threads must also be increased: `org.quartz.threadPool.threadCount=20 + <parallel ssh threads>`
No difference.
- uyuni-project/uyuni-docs#612
Tracks SUSE/spacewalk#12522
If you …
> Separate executor for ssh minion actions to allow parallel execution (bsc#1173199)

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- utils/spacewalk-common-channels
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Enable ppc64le for CentOS7 and CentOS8:
- Add the channels to `spacewalk-common-channels`
- Create the bootstrap repository definitions
No difference.
- Documentation issue was created: https://github.com/uyuni-project/uyuni-docs/pull/625
- No tests: Not automated, we only support automation for x86_64 for now.
Fixes https://github.com/SUSE/spacewalk/issues/12504
FIxes https://github.com/SUSE/spacewalk/issues/12505
Partially addresses https://github.com/SUSE/spacewalk/issues/12506
> Enable ppc64le for CentOS7 and CentOS8

- client/rhel/mgr-daemon/mgr-daemon.changes
- client/rhel/mgr-daemon/mgr-daemon.spec
With selinux set to enforcing removing of mgr-daemon confuses systemd.
A daemon reload is required which was prevented by a check for package was updated.
No difference.
- No documentation needed: **internal only**
Fixes https://github.com/SUSE/spacewalk/issues/12823
Tracks https://github.com/SUSE/spacewalk/pull/12833
> Fix mgr daemon remove with selinux

- java/code/src/com/suse/manager/clusters/ClusterManager.java
- java/code/src/com/suse/manager/clusters/ClusterProviderParameters.java
- java/code/src/com/suse/manager/clusters/test/ClusterManagerTest.java
- java/code/src/com/suse/manager/clusters/test/cluster.upgrade.success.json
- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/webui/controllers/clusters/ClustersController.java
- java/code/src/com/suse/manager/webui/controllers/clusters/templates/upgrade.jade
- java/code/src/com/suse/manager/webui/services/iface/SystemQuery.java
- java/code/src/com/suse/manager/webui/services/impl/SaltService.java
- java/code/src/com/suse/manager/webui/services/test/TestSystemQuery.java
- java/code/src/com/suse/manager/webui/utils/salt/custom/ClusterOperationsSlsResult.java
- java/code/src/com/suse/manager/webui/utils/salt/custom/ClusterUpgradePlanSlsResult.java
- java/manager-build.xml
- java/spacewalk-java.changes
- susemanager-utils/cluster-providers/caasp/uyuni-cluster-provider-caasp/metadata/metadata.yml
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- web/html/src/manager/clusters/shared/api/use-clusters-api.js
- web/html/src/manager/clusters/upgrade-cluster/upgrade-cluster-plan.js
- web/html/src/manager/clusters/upgrade-cluster/upgrade-cluster.js
- web/html/src/manager/clusters/upgrade-cluster/upgrade-cluster.renderer.js
- web/spacewalk-web.changes
Adds support for showing the cluster upgrade plan as the first step in the cluster upgrade flow.
This is targeted post-GMC.
Before:
- upgrade plan was not shown
After:
Fixes # …
> Show cluster upgrade plan in the cluster upgrade UI

- testsuite/features/core/proxy_branch_network.feature
As we fixed on the product side, we don't need to configure manually, on the bind formula, the settings for dnssec-validation.
No difference.
Ports:
Manager-4.0 https://github.com/SUSE/spacewalk/pull/12843
Manager-4.1 https://github.com/SUSE/spacewalk/pull/12842
> QA: On bind formula we don't need dnssec settings anymore

- spacewalk/setup/salt/susemanager.conf
- spacewalk/setup/spacewalk-setup.changes
From: https://docs.saltstack.com/en/3001/ref/configuration/master.html#sock-pool-size
"sock_pool_size
Default: 1
To avoid blocking waiting while writing a data to a socket, we support
socket pool for Salt applications. For example, a job with a large
number of target host list can cause long period blocking waiting. The
option is used by ZMQ and TCP transports, and the other transport
methods don't need the socket pool by definition. Most of Salt tools,
including CLI, are enough to use a single bucket of socket pool. On the
other hands, it is highly recommended to set the size of socket pool
larger than 1 for other Salt applications, especially Salt API, which
must write data to socket concurrently."
This PR introduces this parameter by default, as we use the Salt API extensively and …
> Set sock_pool_size master option by default

- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes
Add --force to mgr-create-bootstrap-repo to enforce generation even when some products are not synchronized.
Case:
When a Product goes EOL, SUSE provide for some Long Term Support Service (LTSS) a customer need to pay for.
Not every customer has it.
But some packages are maintained in service pack independent repositories and the required dependencies may
only be available in the LTSS repositories.
Problem:
- We need to add the LTSS product to products required to generate the bootstrap repos. Customers who do not have LTSS do not have access to it.
- Packages which are available only in LTSS now will always cause errors when generating bootstrap repos
- Customers who do not have LTSS, cannot see the item anymore as LTSS is now mandatory. New Bootstrap repos cannot be created.
Solution:
- …
> Enforce to create bootstrap repo

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
Change Note about Power Management types.
Update to https://github.com/uyuni-project/uyuni/pull/2698
Part of https://github.com/SUSE/spacewalk/pull/12835
> change note about IPMI is the only supported power management type

- spacewalk/admin/salt-secrets-config.py
- spacewalk/admin/spacewalk-admin.changes
It prevents a stack trace when the Salt API certificate is removed from the trust anchors directory (which happens when migrating from 3.2 straight to 4.1)
No difference.
- No tests: **we do not test migrations automatically**
Fixes https://bugzilla.suse.com/1177435
Tracks https://github.com/SUSE/spacewalk/pull/12729
> salt-secrets-config: make check more robust (bsc#1177435)

- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
This PR uses `@long_test` tag for:
- creating the OS image
- the Retail tests
I'm not a big fan of this tag, but if we switch to individual functionality checkboxes, we can change it into `@vm_pxe_install`, `@os_build_image`, etc.
* 4.1: SUSE/spacewalk#12853
* 4.0:
> Use @long_test tag for more long tests

- testsuite/features/step_definitions/common_steps.rb
Support for QAM mirror as MU Repo URL
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/12854
- Manager-4.1  https://github.com/SUSE/spacewalk/pull/12855
> QAM: Prepare repo name, when coming from a mirror

- testsuite/features/secondary/min_ubuntu_openscap_audit.feature
This PR adapts openscap definitions path for Ubuntu 20.04.
To be noted: we still use 16.04 data (see issue SUSE/spacewalk#12860 for details).
See also SUSE/susemanager-ci#148 for the infrastructure part.
Ports:
* 4.1: SUSE/spacewalk#12861
* 4.0: SUSE/spacewalk#12862
> Path has changed on Ubuntu 20.04

- testsuite/features/secondary/min_ubuntu_openscap_audit.feature
Fix openSCAP on Ubuntu 20.04.
```
root@suma-41-min-ubuntu2004:~# oscap info /usr/share/xml/scap/ssg/content/ssg-ubuntu1604-xccdf.xml
Document type: XCCDF Checklist
Checklist version: 1.1
Imported: 2018-07-26T16:58:28
Status: draft
Generated: 2018-07-26
Resolved: true
Profiles:
Title: Profile for ANSSI DAT-NT28 Restrictive Level
Id: anssi_np_nt28_restrictive
Title: Standard System Security Profile for Ubuntu 16
Id: standard
Title: Profile for ANSSI DAT-NT28 High (Enforced) Level
Id: anssi_np_nt28_high
Title: Profile for ANSSI DAT-NT28 Minimal Level
Id: anssi_np_nt28_minimal
Title: Profile for ANSSI DAT-NT28 Average (Intermediate) Level
Id: anssi_np_nt28_average
Referenced check files:
ssg-ubuntu1604-oval.xml
system: http://oval.mitre.org/XMLSchema/oval-definitions-5
ssg-ubuntu1604-ocil.xml …
```
> Correct profile for openSCAP

- testsuite/features/secondary/min_ubuntu_openscap_audit.feature
Fix Ubuntu 20.04 openscap test
Ports:
* 4.1: SUSE/spacewalk#/12867
* 4.0: SUSE/spacewalk#/12868
> Correct link name

- backend/test/docker-backend-tools-tests.sh
This PR adds `-v` to nosetests execution in order to get a detailed output and names of satetille tools unit tests execution:
Before this  PR:
```console
......10:26:28 Channel Label does not exist.
.........10:26:28 Could not figure out which credentials to use for this URL: http://example.com/?credentials=bad_creds_with_underscore
...10:26:28 Could not figure out which credentials to use for this URL: http://example.com/?credentials=testcreds
..................10:26:28 ======================================
10:26:28 | Channel: chann_1
10:26:28 ======================================
10:26:28 Sync of channel started.
10:26:28 ======================================
10:26:28 | Channel: chann_2
10:26:28 ======================================
10:26:28 Sync of channel started.
10:26:28 Total …
```
> Run nosetests for satellite_tools unit tests with verbose output

- testsuite/features/reposync/srv_sync_products.feature
Do not try to disable SUSE Manager beta client tools.
Uyuni has its own client tools; head only uses beta tools during
beta testing.
> Testsuite: do not try to disable a missing product

- testsuite/features/step_definitions/common_steps.rb
This channel is not present in the Uyuni case.
> Testsuite: Do not assume SLE-Manager-Tools15-Updates channel is present

- testsuite/features/step_definitions/salt_steps.rb
Refactor cleanup step for salt minions.
We use `systemd` in all our salt minions, thus no need to use `rcsalt-minion` for SUSE minions
and `systemd` for the rest. 
- Manager-4.0: 
- Manager-4.1: 
> Testsuite: Refactor cleanup step for salt minions

- java/code/src/com/suse/manager/reactor/messaging/test/virt.guest.definition.xml
- java/code/src/com/suse/manager/virtualization/GuestDiskDef.java
- java/code/src/com/suse/manager/webui/controllers/virtualization/test/VirtualGuestsControllerTest.java
- java/code/src/com/suse/manager/webui/controllers/virtualization/test/virt.vm.info.json
- java/spacewalk-java.changes
- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minxen_guests.feature
- testsuite/features/step_definitions/command_steps.rb
- web/html/src/manager/virtualization/guests/GuestProperties.js
- web/spacewalk-web.changes
At least for Xen the disks of volume types aren't supported but
converted by Salt into their file or block equivalents. In order to show
the selected volume and pool when possible, try to get those
informations from Salt's virt.vm_info output.
No difference.
- No documentation needed: fixes VM disks infos for Xen
> Show pool/volume informations where possible

- testsuite/features/step_definitions/navigation_steps.rb
This PR rescue the Capybara:ModalNotFound exception (which is used to raise problems in both cases: alert messages and modal dialogs) when we expect an alert message to be confirmed but it is not shown.
This issue starts to happen when added a new option in the Chrome driver, to automatically accept unhandled alert messages, as when we reload the page, it is randomly showing an alert and we couldn't catch it properly. So, adding this option it is also auto-accepting the unique alert message implementation in our product, which is expected when we are cleaning values from a formula. Ideally this alert message should be converted to a modal dialog, so we can distinguish the alert messages and auto-accept them, and the modal dialogs and accept them manually. …
> QA: Rescue from Capybara::ModalNotFound (#12899)

- backend/server/action/distupgrade.py
- backend/spacewalk-backend.changes
- java/code/src/com/redhat/rhn/domain/action/dup/DistUpgradeActionDetails.hbm.xml
- java/code/src/com/redhat/rhn/domain/action/dup/DistUpgradeActionDetails.java
- java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/distupgrade/DistUpgradeManager.java
- java/code/src/com/redhat/rhn/manager/distupgrade/test/DistUpgradeManagerTest.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/webapp/WEB-INF/pages/systems/spmigration/channel-details.jspf
- java/code/webapp/WEB-INF/pages/systems/spmigration/spmigration-confirm.jsp
- java/code/webapp/WEB-INF/pages/systems/spmigration/spmigration-setup.jsp
- java/code/webapp/WEB-INF/struts-config.xml
- java/spacewalk-java.changes
- schema/spacewalk/common/tables/rhnActionDup.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.1.9-to-susemanager-schema-4.1.10/001-rhnActionDup-add-alllow-vendor-change.sql
- schema/spacewalk/upgrade/susemanager-schema-4.2.2-to-susemanager-schema-4.2.3/001-rhnActionDup-add-alllow-vendor-change.sql
- susemanager-utils/susemanager-sls/salt/distupgrade/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This is a port of spacewalk pr 12584
Spacewalk issue #11331 
This adds support for allow vendor change during dist upgrades.  You can now enable vendor change in the UI during a single action, or via the api.  
Also hangs on this: https://github.com/openSUSE/zypp-plugin-spacewalk/pull/43 (merged)
and this: https://github.com/saltstack/salt/pull/58560#pullrequestreview-497272067  (merged)
or this: https://github.com/openSUSE/salt/pull/284
Before:
After:
- https://github.com/uyuni-project/uyuni-docs/issues/571
Fixes # …
> Allow vendor change during dist upgrades

- testsuite/features/core/allcli_sanity.feature
- testsuite/features/step_definitions/command_steps.rb
This PR checks that we can reach SUSE updates server via the HTTP proxy, when there is one.
Ports:
* 4.1:
* 4.0:
> New sanity check: HTTP proxy

- testsuite/features/step_definitions/command_steps.rb
Follow-up of #2771 : do not use a hash in sanity check, because it would be time-limited.
> Do not use a hash

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/webapp/WEB-INF/pages/common/fragments/kickstart/schedule/advanced.jspf
- java/code/webapp/WEB-INF/pages/common/fragments/kickstart/schedule/kernel-options.jspf
- java/spacewalk-java.changes
The advanced page for autoinstallation provide the special settings which only work with tranditional clients.
For salt we do not have the mapping of cobbler network device settings to special kernel options.
If this is needed, the user can provide directly the required options into the kernel options field.
This PR show only the Kernel Options fields when the system is a salt client.
Before:
After:
- https://github.com/SUSE/spacewalk/issues/12915
Fixes https://github.com/SUSE/spacewalk/issues/12802
Tracks https://github.com/SUSE/spacewalk/pull/12929 …
> Salt autoinst advanced options

- susemanager-utils/cluster-providers/caasp/uyuni-cluster-provider-caasp/uyuni-cluster-provider-caasp.changes
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Move changelog entry from susemaneger-sls to uyuni-cluster-provider
No difference.
- No documentation needed: not needed
Fixes #
> Move changelog entry from susemaneger-sls to uyuni-cluster-provider

- testsuite/features/support/env.rb
Temporary increase from 60 s to 180 s read_timeout for http requests.
This test is failing at head and uyuni; at these two branches the
power management functions are taking longer than expected
(~ 100 s the reboot).
- testsuite/features/support/env.rb
This workaround is only needed for Uyuni and head.
https://github.com/SUSE/spacewalk/issues/12928
> Testsuite: add workaround for issue at IPMI functions test

- schema/spacewalk/Makefile
In which directory I need to create a new DB schema migration file?
Answer:
```
$> cd schema/spacewalk/
$> make newmigration 
New migration file at upgrade/susemanager-schema-4.2.2-to-susemanager-schema-4.2.3/new.sql
```
No difference.
- No documentation needed: **internal tooling**
- No tests: **internal tooling**
> Helper to create new DB migration file in right directory

- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_bootstrap_negative.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/features/secondary/min_bootstrap_ssh_key.feature
- testsuite/features/secondary/min_bootstrap_xmlrpc.feature
- testsuite/features/secondary/min_salt_mgrcompat_state.feature
- testsuite/features/secondary/min_ssh_tunnel.feature
- testsuite/features/secondary/minssh_bootstrap_xmlrpc.feature
- testsuite/features/step_definitions/salt_steps.rb
Recently we updated our step definition to clean up minion's content, once we deleted the system from SUSE Manager.
We simplified it by using the `systemctl` command to stop the salt-minion service in all kinds of minions, while before we were using a different command for SLE minions. This change, cause a problem in our tests, as sometimes on SLE clients we stopped the service at the same time that SUMA was acting on it. In order to fix it, I changed the `run` command to another command that retries several times until it gives a successful result. Also, this step only removes the information from the cache, so it needs a rename to don't cause confusion. By the way, I use the verb "clean up" instead of the noun "cleanup" as it was before.
In addition, I would like to keep (commented) a …
> QA: Make sure we stop salt-minion service on clean-up

- java/code/src/com/suse/manager/webui/controllers/DownloadController.java
- java/code/src/log4j.properties
- java/spacewalk-java.changes
- Log errors on token verify.
- check for expired tokens (exceptional case only as we automatically renew them)
No difference.
- No tests: **debugging messages only**
Tracks https://github.com/SUSE/spacewalk/pull/12949 https://github.com/SUSE/spacewalk/pull/12947
> Improve token checking

- testsuite/features/step_definitions/command_steps.rb
When the proxy was offering NTLM authentication, the sanity check was still passing, even though NTLM authentication was broken there. This is because:
"Basic is the default authentication method curl uses with proxies."
This PR tries to make curl pick strongest auth method as explained in the RFC.
See SUSE/spacewalk#12940 .
* 4.1:
* 4.0:
> Pick safest auth method offered by HTTP proxy

- testsuite/features/support/env.rb
This additional option inside the chrome driver will allow using of non-compliance W3C actions. This is necessary in order to use the latest versions of chromium and chromedriver with the new image for our controller component Leap15.2 JeOS
No difference.
- No tests
> QA: Disable the constraint to use only W3C compliance actions in Chrome

- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/redhat/rhn/manager/system/test/SystemManagerMockTest.java
- java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
- java/code/src/com/suse/manager/webui/services/iface/SaltApi.java
- java/code/src/com/suse/manager/webui/services/iface/SystemQuery.java
- java/code/src/com/suse/manager/webui/services/impl/SaltService.java
- java/code/src/com/suse/manager/webui/services/impl/runner/MgrUtilRunner.java
- java/code/src/com/suse/manager/webui/services/test/TestSaltApi.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/modules/runners/mgrutil.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Port of https://github.com/SUSE/spacewalk/pull/12428
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/2233
Tracks https://github.com/SUSE/spacewalk/pull/12428
> Remove hostname from /var/lib/salt/.ssh/known_hosts when deleting system (bsc#1176159)

- testsuite/features/qam/init_clients/ceos6_client.feature
- testsuite/features/qam/init_clients/ceos6_minion.feature
- testsuite/features/qam/init_clients/ceos6_ssh_minion.feature
- testsuite/features/qam/init_clients/ceos7_client.feature
- testsuite/features/qam/init_clients/ceos7_minion.feature
- testsuite/features/qam/init_clients/ceos7_ssh_minion.feature
- testsuite/features/qam/init_clients/ceos8_minion.feature
- testsuite/features/qam/init_clients/ceos8_ssh_minion.feature
- testsuite/features/secondary/min_centos_openscap_audit.feature
- testsuite/features/secondary/trad_centos_client.feature
- testsuite/features/secondary/trad_migrate_to_minion.feature
- testsuite/features/secondary/trad_migrate_to_sshminion.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/constants.rb
Get rid of traditional stack package installation if we are not in a traditional client. It applies to CI testsuite and also to QAM Testsuite.
Note: I remove `m2crypto` and `hwdata` as OpenSCAP dependencies to install, because it must be part of the dependencies for spacewalk-oscap to be installed automatically by zypper/yum.
No difference.
- No documentation needed 
> Get rid of traditional stack package installation if we are not in a traditional client

- java/code/src/com/suse/manager/reactor/SaltReactor.java
- java/code/src/com/suse/manager/reactor/messaging/ImageSyncedEventMessage.java
- java/code/src/com/suse/manager/reactor/messaging/ImageSyncedEventMessageAction.java
- java/code/src/com/suse/manager/reactor/messaging/test/ImageSyncedEventMessageActionTest.java
- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java
- java/code/src/com/suse/manager/webui/services/test/SaltStateGeneratorServiceTest.java
- java/code/src/com/suse/manager/webui/utils/salt/custom/ImageSyncedEvent.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/modules/engines/mgr_events.py
- susemanager-utils/susemanager-sls/modules/pillar/suma_minion.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This adds functionality for adding and removing "synced" flag for each image in each branch, based on salt events emitted by image-sync formula.
It also limits visibility of image pillars to buildhost org only.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/10577 and https://github.com/SUSE/spacewalk/issues/12388
Depends on https://github.com/uyuni-project/retail/pull/67
> Maintain list of synced images in pillar

- backend/satellite_exporter/handlers/non_auth_dumper.py
- backend/satellite_tools/satsync.py
- backend/satellite_tools/xmlWireSource.py
- backend/spacewalk-backend.changes
This PR fixes an issue when running `mgr-inter-sync` to sync a channel in which there are packages that have the same NEVRA (name-epoch-version-release-arch) but have different checksum.
Currently, when this situation happens, `mgr-inter-sync` produces errors when downloading the packages:
```console
[...]
15:38:08 Error: file /var/spacewalk/packages/NULL/00b/ColPack-devel/1.0.9-2.1/x86_64/00b5bbc2d48aa83001b2716333a3110e802eeeaf203070ef48c8aefc0a3b825e/ColPack-devel-1.0.9-2.1.x86_64.rpm has wrong size. Expected 33830 bytes, got 33828 bytes
15:38:08     Fetch unsuccessful: ColPack-devel-1.0.9-2.1.x86_64.rpm
15:38:08 Error: file /var/spacewalk/packages/NULL/f37/hdf/4.2.11-2.1/x86_64/f376f495863322d151c81379c0278262637097f9cba301fd3567921c782c6558/hdf-4.2.11-2.1.x86_64.rpm has wrong size. …
```
> ISS: Differentiate packages with same nevra but different checksum (bsc#1178195)

- testsuite/features/support/constants.rb
Fixing a mistake on the list of rpms. Missing white space.
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/12857
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/13005
> QA: Fixing a mistake on the list of rpms

- reporting/reports/data/system-history
- reporting/spacewalk-reports.changes
**It adds "hostname" field to the report**
One more column in the output of `spacewalk-report`
- No documentation needed: **reports are not described at column detail**
- No tests: **no test infra for spacewalk-report at this time**
None
> Added hostname field in system-history report

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
Found error messages in the logs that these two strings were not available.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/13008
> add two missing translation strings for task status report

- testsuite/features/qam/init_clients/ceos6_client.feature
- testsuite/features/qam/init_clients/ceos6_minion.feature
- testsuite/features/qam/init_clients/ceos6_ssh_minion.feature
- testsuite/features/qam/init_clients/ceos7_client.feature
- testsuite/features/qam/init_clients/ceos7_minion.feature
- testsuite/features/qam/init_clients/ceos7_ssh_minion.feature
- testsuite/features/qam/init_clients/ceos8_minion.feature
- testsuite/features/qam/init_clients/ceos8_ssh_minion.feature
- testsuite/features/qam/init_clients/proxy.feature
- testsuite/features/qam/init_clients/sle11sp4_client.feature
- testsuite/features/qam/init_clients/sle11sp4_minion.feature
- testsuite/features/qam/init_clients/sle11sp4_ssh_minion.feature
- testsuite/features/qam/init_clients/sle12sp4_client.feature
- testsuite/features/qam/init_clients/sle12sp4_minion.feature
- testsuite/features/qam/init_clients/sle12sp4_ssh_minion.feature
- testsuite/features/qam/init_clients/sle15_client.feature
- testsuite/features/qam/init_clients/sle15_minion.feature
- testsuite/features/qam/init_clients/sle15_ssh_minion.feature
- testsuite/features/qam/init_clients/sle15sp1_client.feature
- testsuite/features/qam/init_clients/sle15sp1_minion.feature
- testsuite/features/qam/init_clients/sle15sp1_ssh_minion.feature
- testsuite/features/qam/init_clients/ubuntu1604_minion.feature
- testsuite/features/qam/init_clients/ubuntu1604_ssh_minion.feature
- testsuite/features/qam/init_clients/ubuntu1804_minion.feature
- testsuite/features/qam/init_clients/ubuntu1804_ssh_minion.feature
- testsuite/features/qam/init_clients/ubuntu2004_minion.feature
- testsuite/features/qam/init_clients/ubuntu2004_ssh_minion.feature
- testsuite/features/step_definitions/salt_steps.rb
This PR creates a new step definition to clean up all the related of salt and salt-minion from a VM.
We want this to remove possible conflicting packages when a VM is deployed using sumaform.
For now, we can only use it in QAM bootstraps, as is the only environment where we have synced repositories that provides the necessary packages for salt and salt-minion, once they are removed.
WARN: It might be that we need to clean more stuff let by sumaform. For now only cleanning salt and salt-minion.
Related card https://github.com/SUSE/spacewalk/issues/11332
No difference. …
> QAM: Clean up the VMs deployed using sumaform (#12999)

- java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
- java/spacewalk-java.changes
This PR makes `SaltSSHService.java` to use the correct eauth module and credentials when dealing with the Salt API.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/12963
> Use correct eauth module and credentials for Salt SSH calls (bsc#1178319)

- java/code/src/com/redhat/rhn/domain/kickstart/RepoInfo.java
- java/spacewalk-java.changes
Port of https://github.com/SUSE/spacewalk/pull/12335
No difference.
Fixes #
> Fix repo url of AppStream in generated RHEL/Centos 8 kickstart file (bsc#1175739) 

- java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/reactor/messaging/test/action.chain.one.chunk.json
- java/code/src/com/suse/manager/reactor/messaging/test/action.chain.salt.error.json
- java/code/src/com/suse/manager/webui/services/SaltActionChainGeneratorService.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/salt/actionchains/start.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Port of https://github.com/SUSE/spacewalk/pull/12827
No difference.
Fixes #
> Sync state modules when starting action chain execution (bsc#1177336)

- java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
- java/spacewalk-java.changes
This PR makes `SaltSSHService.java` to use the correct eauth module and credentials when dealing with the Salt API.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/12963
> Uyuni-2020.09: Use correct eauth module and credentials for Salt SSH calls (bsc#1178319)

- java/code/src/com/suse/manager/webui/websocket/RemoteMinionCommands.java
- java/spacewalk-java.changes
When `htmlify()` does replacements, it will typically add more characters as it remove.
So we need to calculate the number of characters to truncate based on the HTML version of the message.
No difference.
- No tests: 
Fixes https://github.com/SUSE/spacewalk/issues/13033
Tracks https://github.com/SUSE/spacewalk/pull/13035 https://github.com/SUSE/spacewalk/pull/13036
> Fix truncate messages

- spacewalk/admin/spacewalk-admin.changes
- spacewalk/admin/spacewalk-admin.spec
When installing without docs, it **does** install the LICENSE
No difference.
Before:
`rpm -qpL spacewalk-admin-*.rpm`
returns nothing
After:
`rpm -qpL spackwalk-admin-*.rpm`
returns
`/usr/share/licenses/spacewalk-admin/LICENSE`
Tested with a local checkout of https://build.opensuse.org/package/show/systemsmanagement:Uyuni:Master/spacewalk-admin, applying the same change and then running the command within opensuse/leap:15.2 docker container.
- No documentation needed: This is an implementation detail, no impact on the user
Fixes #12923
If …
> use the license macro to mark the LICENSE in the package

- spacecmd/spacecmd.changes
- spacecmd/spacecmd.spec
Fix spacecmd on debian
No difference.
- No documentation needed: spec
- No tests: spec
> Fix: make spacecmd build on Debian

- testsuite/features/qam/add_custom_repositories/add_mu_repository.template
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/support/commonlib.rb
Refactor to handle multiple repositories per client.
Related card: https://github.com/SUSE/spacewalk/issues/13016
No difference.
Ports:
Manager-4.1
Manager-4.0
> QAM: Refactor to handle multiple repositories per client

- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
Found the following in the logs:
```
2020-11-08 10:38:48,557 [DefaultQuartzScheduler_Worker-2] INFO  com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing action: 381
2020-11-08 10:38:48,653 [DefaultQuartzScheduler_Worker-2] ERROR com.redhat.rhn.taskomatic.task.MinionActionExecutor - Executing a task threw an exception: java.util.NoSuchElementException
2020-11-08 10:38:48,653 [DefaultQuartzScheduler_Worker-2] ERROR com.redhat.rhn.taskomatic.task.MinionActionExecutor - Message: No value present
2020-11-08 10:38:48,653 [DefaultQuartzScheduler_Worker-2] ERROR com.redhat.rhn.taskomatic.task.MinionActionExecutor - Cause: null
2020-11-08 10:38:48,653 [DefaultQuartzScheduler_Worker-2] ERROR com.redhat.rhn.taskomatic.task.MinionActionExecutor - Stack …
```
> Fix optional no such elem exception

- java/code/src/com/redhat/rhn/frontend/action/common/DownloadFile.java
- java/spacewalk-java.changes
Port of https://github.com/SUSE/spacewalk/pull/12965
For autoinstalling a SUSE system we need the media.1/products file. This is synced for vendor channels but not copied when we create clones of the channels.
When performing an autoinstallation and the channel does not have a media product, we should check the original channel .
If none it has it, we fallback to the linked media.
No difference.
> Get mediaproducts for cloned channels

- java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
- java/spacewalk-java.changes
Introduce an endpoint (`system.listInstalledPackages`) that reports package architecture label.
Previously, we had an endpoint (`system.listPackages`) that reported architecture **name**, which is useless in other endpoints (they return/accept arch label). This PR does **NOT** remove this endpoint, as it would break backwards compatibility.
Moreover: get rid of one unused query.
No difference.
- xmlrpc doc
Tracks SUSE/spacewalk#12589
> XMLRPC: Report architecture label in the list of installed packages

- client/rhel/dnf-plugin-spacewalk/po/Makefile
- client/rhel/dnf-plugin-spacewalk/po/Makevars
- client/rhel/dnf-plugin-spacewalk/po/dnf-plugin-spacewalk.pot
No difference.
- No documentation needed: i18n
- No tests: i18n
https://github.com/SUSE/spacewalk/issues/12328
> Internationalization of dnf-plugin-spacewalk

- java/code/src/com/redhat/rhn/domain/product/test/SUSEProductTestUtils.java
- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/distupgrade/test/DistUpgradeManagerTest.java
- java/spacewalk-java.changes
When doing a SP Migration we call `isProductAvailable()` . This method check if the customer has subscriptions for
a possible target product. In case he has, but it is just not synced, we show can show him the target and he
can sync the missing channels from SCC.
But in case of an ISS Slave this check hide all target products as we do not sync `sccRepositoryAuth` data to the slave.
This PR disable the isMirrorable test when we are on an ISS Slave.
No difference.
- No documentation needed: **should now work like documented**
Port of https://github.com/SUSE/spacewalk/pull/13047 …
> Fix sp migration on iss slave

- rel-eng/build-packages-local-obs.sh
N/A
Adds an optional parameter to the package build local script so that we can build packages that are in build.opensuse.org.
Before:
When calling `./build-packages-local-obs.sh -h`
there was no osc_api argument
After:
When calling `./build-packages-local-obs.sh -h`
you should see the optional argument osc_api
Before:
When calling
```
mkdir /tmp/obs
cd /tmp/obs
osc checkout systems:management:Uyuni:Master spacewalk-admin
cd -
./build-packages-local-obs.sh --osc_project_wc=/tmp/obs/systemsmanagement:Uyuni:Master --repository=openSUSE_Leap_15.2 --packages=spacewalk-admin --osc_api=https://build.opensuse.org
```
you should see an error
after:
same command, but no error and the package is built in /tmp/....
- No tests: This …
> Be able to select API when building packages locally

- java/spacewalk-java.changes
Add missing changelog entry for: Remove expiration date from ics files (bsc#1177892)
> Ics file expiration date changelog entry

- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
obs-to-maven use now velocity from Leap.
No difference.
- No tests: **for devel only**
> use velocity from Leap

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
- spacewalk/certs-tools/update-ca-cert-trust.sh
Case: a user had installed CA certificates under the RedHat path on a SUSE system. This caused the scripts to call the wrong tool and do not create the tust store correctly.
This PR improve the detection of the correct directory and tool to call.
No difference.
- No documentation needed: **should now behave like expected**
Fixes https://github.com/SUSE/spacewalk/issues/12632
Tracks https://github.com/SUSE/spacewalk/pull/13073 https://github.com/SUSE/spacewalk/pull/13074
> Improve updating ca trust store

- .github/PULL_REQUEST_TEMPLATE.md
Remove java checkstyle from PR template. Java checkstyle is now in github actions.
No difference.
Before:
See the option in the PR template
```
```
After:
You should not see the option in the PR template
- No documentation needed: This is for CI
- No tests: this actually removes a test
Tracks https://github.com/SUSE/spacewalk/issues/12892
> Remove java checkstyle from PR template

- backend/common/rhnException.py
- backend/satellite_tools/messages.py
- backend/satellite_tools/satsync.py
- backend/server/rhnChannel.py
- client/rhel/spacewalk-client-tools/rhn_register.desktop.in
- client/rhel/spacewalk-client-tools/src/up2date_client/rhnregGui.py
- spacecmd/src/spacecmd/api.py
- spacecmd/src/spacecmd/kickstart.py
- spacecmd/src/spacecmd/package.py
Some strings escaped my attention in the first round.
Used the following command to find the occurences in the POT files:
`git grep -i '^[^#].*\(satellite\|redhat\|red hat\|rhn\)' \*.pot`
There are still some string occurences, that don't pass the above grep, but I
believe they shouldn't appear in the UI/they would need some refactoring to be
removed.
> Uyunify missing translations

- testsuite/features/finishing/allcli_debug.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/twopence_init.rb
Small refactor to extract logs from all the active nodes in our testsuite. In that way, we fix the current failure on the QAM test suite at the same time that we don't need to worry if we add more clients to the list of nodes.
No difference.
> QA: Refactor extraction of logs to support QAM clients

- java/code/src/com/suse/manager/reactor/messaging/BatchStartedEventMessageAction.java
- java/spacewalk-java.changes
"Minion is down" message is misleading. The minion could indeed be turned off, but it could also be any other kind of network problem.
Change it to "Minion is down or cannot be contacted." like in other parts of Uyuni
- No tests: I did a grep and it should not break the test suite
Ports:
* 4.1: SUSE/spacewalk#13104
* 4.0: SUSE/spacewalk#13103
> Change message "Minion is down" to be more accurate

- backend/common/suseLib.py
- backend/satellite_tools/repo_plugins/uln_src.py
- backend/satellite_tools/repo_plugins/yum_src.py
- backend/satellite_tools/spacewalk-uln-resolver
- backend/spacewalk-backend.changes
- java/code/src/com/redhat/rhn/manager/channel/repo/BaseRepoCommand.java
- java/code/src/com/redhat/rhn/manager/channel/test/BaseRepoCommandTest.java
- java/spacewalk-java.changes
This PR fixes broken ULN reposync plugin and also addresses other related ULN issues:
- Allow `spacewalk-repo-sync` to deal with `uln://` repositories URLs and successfully sync ULN repos.
- Successfully propagate HTTP proxy settings to dealing with ULN repos.
- Fix web UI and API to allow creating custom ULN repositories with `uln://` URLs.
Thanks a lot to @scomcd for the help on testing these changes against the real ULN network.
@scomcd I'll provide you some more notes at https://github.com/uyuni-project/uyuni/issues/2359 so you can give a test to the Python parts (reposync + http proxy). Thanks in advance! 
@parlt91 - Could you please also give a review to the Java changes? Thanks!
**I've marked this as [WIP] since I want to wait for a final feedback from @scomcd before merging**
No …
> Successfully manage and sync ULN repositories

- java/code/src/com/redhat/rhn/domain/contentmgmt/modulemd/Module.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/modulemd/ModuleInfo.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/validation/ModularDependencyValidator.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/validation/test/ModularDependencyValidatorTest.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/DependencyResolutionResult.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/DependencyResolver.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/DependencyResolverTest.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/MockModulemdApi.java
- java/spacewalk-java.changes
- web/html/src/manager/content-management/list-filters/list-filters.js
- web/spacewalk-web.changes
In the current implementation, there is no indication of whether additional modules are enabled as dependencies. This PR adds a message to the filters pane on the CLM project page to display the actual list of enabled modules, including any dependencies.
Port of: https://github.com/SUSE/spacewalk/pull/13037
Before:
After:
- No documentation needed: no change in functionality
> Report resolved module dependencies on CLM project UI

- testsuite/features/secondary/min_centos_openscap_audit.feature
Use an XML that is available in the CentOS minion for the openscap scan.
- Manager-4.0:  https://github.com/SUSE/spacewalk/pull/13121
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13120
> Testsuite: Use an xml available in the centos minion

- testsuite/features/qam/init_clients/ceos7_client.feature
- testsuite/features/secondary/trad_centos_client.feature
Also use an available xml for trad/qam centos tests
- testsuite/features/secondary/trad_centos_client.feature
- testsuite/features/qam/init_clients/ceos7_client.feature
No ports needed
It completes: https://github.com/uyuni-project/uyuni/pull/2848
> Testsuite: Also use an available xml for trad/qam centos tests

- client/rhel/dnf-plugin-spacewalk/po/es.po
WebLate will not allow me to create the component unless there is at least one .po file for one translation. Weird.
No difference.
Before:
After:
- No tests are needed
Fixes spacewalk #12238
> Add dnf-plugin-spacewalk Spanish gettext catalog

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_bn_IN.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_ca.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_cs.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_de.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_es.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_fr.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_gu.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_hi.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_it.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_ja.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_ko.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_pa.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_pt_BR.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_ru.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_sk.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_ta.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_uk.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_zh_CN.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_zh_TW.xml
This reverts commit a493ea7140074e3a2eff275622695ee4930010f3 and removes
the proper strings instead.
See this line using the string:
https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemDetailsEditAction.java#L312
No difference.
- No documentation needed: l10n cleanup fix
- No tests: actually fixes broken cucumber tests
Fixes #
> Fix "Remove some unused strings"

- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/step_definitions/common_steps.rb
Fix errors at srv_content_lifecycle tests about unclickable buttons.
Search for the text messages in the specific environment where
they appear.
Wait until a target button is enabled before to click it.
- testsuite/features/secondary/srv_content_lifecycle.feature:
Ensure we search for the expected text in the right environment.
Add step to wait a custom number of seconds until a target string
shows up in the target envitonment.
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13168
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13167
> Testsuite: Fix srv_content_lifecycle tests

- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
Fix unclickable button error at proxy_retail_pxeboot_and_mass_import.feature
This error seems related to the recent update of the chromedriver
(See https://stackoverflow.com/questions/62003082/elementnotinteractableexception-element-not-interactable-element-has-zero-size#answer-62137766)
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13186
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13185
> Testsuite: scroll up to help Selenimum driver to find the button

- testsuite/features/qam/init_clients/ceos6_client.feature
- testsuite/features/qam/init_clients/ceos7_client.feature
- testsuite/features/secondary/min_centos_openscap_audit.feature
- testsuite/features/secondary/min_salt_openscap_audit.feature
- testsuite/features/secondary/min_ubuntu_openscap_audit.feature
- testsuite/features/secondary/trad_centos_client.feature
- testsuite/features/secondary/trad_migrate_to_minion.feature
- testsuite/features/secondary/trad_migrate_to_sshminion.feature
- testsuite/features/secondary/trad_openscap_audit.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/support/constants.rb
The result of the openSCAP audit may list many not applicable rules. They make the test for passing rules difficult as they may start on page 2. This PR uses the filter button to focus on the passing rules.
Now we will install all needed packages from the test suite, instead of a mixture of sumaform and the test suite (see uyuni-project/sumaform#801). This PR adapts.
The list of packages to install for openSCAP tests was wrong, For example, the CentOS traditional client is both a CentOS client and a traditional client. Constant package lists were not fit for this, this PR computes the list dynamically.
This PR also cleans up the generated reports, the installed packages and the enabled repositories at the end to make these tests idempotent.
Ports:
* 4.1: SUSE/spacewalk#13187 …
> Fix openSCAP results

- testsuite/features/core/allcli_sanity.feature
- testsuite/features/step_definitions/command_steps.rb
Use new locations for Docker profiles after refactoring by @mcalmer (internal NUE, internal PRV, ..).
Fixes #13148
Ports:
* 4.0: SUSE/spacewalk#13157
* 4.1: SUSE/spacewalk#13156
> Sanity tests for new location of Docker profiles

- testsuite/features/support/commonlib.rb
Now, head uses sles15sp3o; update code to pick up the right JeOS image for head.
- testsuite/features/support/commonlib.rb:
Consider 'sles15sp3o' in the `case` expression.
Delete unneeded nil-check.
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13204
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13203
> Testsuite: Use the right JeOS image

- susemanager-utils/susemanager-sls/src/modules/mgractionchains.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Calls saltutil.sync_{modules,states} before starting action chains
No difference.
- No tests: already tested
Tracks https://github.com/SUSE/spacewalk/issues/12682
> Fix: sync before start action chains (bsc#1177336) 

- testsuite/features/secondary/min_salt_openscap_audit.feature
Forgotten port from 4.1. See https://github.com/SUSE/spacewalk/pull/13197/files#diff-1f77b3883b9418ea4417282aa5e9cdfcc96ecbfda94ce7eff59259b9c357744a .
> Let SUSE Manager know openSCAP packages are installed

- testsuite/features/step_definitions/command_steps.rb
Prevent special chars in the output xml files.
Otherwise, they break the `minidom` parser and the CI won't send
the mail with the results.
- testsuite/features/step_definitions/command_steps.rb:
Do not pass `--force-color` option to the `salt-call`.
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13225
> Testsuite: prevent special chars in the output xml files

- testsuite/features/profiles/Makefile
- testsuite/features/profiles/internal_prv/Docker/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/authprofile/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/serverhost/Dockerfile
We are moving the internal docker registry to a new vm
No difference.
- No documentation needed: internal infrastructure
- No tests: we need to see that tests still pass
Fixes #
Tracks # https://github.com/SUSE/spacewalk/issues/13060
> Move internal registry to registry.mgr.prv.suse.net

- susemanager-utils/mgr-libmod/mgr-libmod.changes
- susemanager-utils/mgr-libmod/mgrlibmod/mllib.py
`MlModuleNotFound` exception is expected to have a list of stream objects as additional data with the key `"streams"`. If the key is missing in the data, the exception cannot be handled correctly. This PR makes sure that the `MlModuleNotFound` exception always has this data.
https://bugzilla.suse.com/1179257
Fixes https://github.com/uyuni-project/uyuni/issues/2906
> Fix 'module not found' exception handling in mgr-libmod (bsc#1179257)

- spec-tree/perl-Term-Completion/perl-Term-Completion.spec
- Added latest Spacewalk Project changes (updates URLs to https)
- Added explicit perl(Term::Completion::Path) provision. 
- Re-added and documented chagnes from 2018-02-10.
No difference.
Before:
After:
Fixes #
Tracks # **add downstream PR, …
> Perl term completion

- spec-tree/perl-Mail-RFC822-Address/perl-Mail-RFC822-Address.spec
- Added latest Spacewalk Project changes for perl-Mail-RFC822-Address. (Updated source URL and removed per Perl build requirement).
- Re-added and documented reverted changes from 2018-02-10.
No difference.
- No tests: Automatic test on build.
Upstream # https://github.com/spacewalkproject/spacewalk/tree/master/spec-tree/perl- …
> Perl mail rfc822 address: Integrated Spacewalk Project changes.

- client/tools/mgr-osad/mgr-osad.changes
- client/tools/mgr-osad/mgr-osad.spec
- Python fixes.
- Removed RHEL5 specifics.
No difference.
- No tests: Will be tested during build.
Fixes #
> mgr-osad: Python fixes. Removal of RHEL5

- backend/server/rhnChannel.py
- backend/server/rhnServer/server_class.py
- backend/spacewalk-backend.changes
This PR fixes an issue happening during a re-registration of a traditional client, caused by a wrong handling of "suse products" by `server.change_base_channel` function. We know that this happens on the context of re-registering a SUSE Manager Proxy that was previously 3.2 and now is 4.1.
```console
Exception Handler Information
File "/usr/lib/python3.6/site-packages/spacewalk/server/apacheRequest.py", line 135, in call_function
response = func(*params)
File "/usr/share/rhn/server/handlers/xmlrpc/registration.py", line 528, in new_system
architecture, data)
File "/usr/share/rhn/server/handlers/xmlrpc/registration.py", line 324, in create_system
newserv.change_base_channel(release, suse_products=suse_products) 
File …
```
> Do not raise TypeError when changing base channel during trad registration (bsc#1178704)

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-form.js
- web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-view.js
- web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment.utils.js
- web/spacewalk-web.changes
When creating a Content Environment in the web UI, we display 'Name'
field, that we use as both name and label of the new Environment, which
lead to confusion.
Fixed by displaying text inputs for both 'Name' and 'Label'.
Before:
After:
https://github.com/uyuni-project/uyuni-docs/pull/699
- no tests
Tracks https://github.com/SUSE/spacewalk/issues/12448
> Allow specifying both name and label of new Content Environment (bsc#1176411)

- uyuni/base/uyuni-base.spec
license macro not defined in RHEL6
- failed to define it. OBS seems not to like it
No difference.
- No tests: **fix building**
> license macro not defined in RHEL6

- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_bootstrap_negative.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/features/secondary/min_bootstrap_ssh_key.feature
- testsuite/features/secondary/min_bootstrap_xmlrpc.feature
- testsuite/features/secondary/min_salt_mgrcompat_state.feature
- testsuite/features/secondary/min_ssh_tunnel.feature
- testsuite/features/secondary/minssh_bootstrap_xmlrpc.feature
- testsuite/features/step_definitions/salt_steps.rb
This PR removes code that has been added long ago to deal with problem of unaccepted Salt keys reappearing all the time.
Such keys appear on SUSE Manager server with deleted minions when:
* `salt-minion` service is restarted on the minion
* the minion reboots
The proper fix to this problem is to fix the issue in the product: 
https://bugzilla.suse.com/show_bug.cgi?id=1179288
This PR has been tested with success on 4.1 branch:
https://ci.suse.de/view/Manager/view/Manager-4.1/job/manager-4.1-cucumber-NUE/205/parameters/
Ports:
* 4.0: SUSE/spacewalk#13265
* 4.1: SUSE/spacewalk#13263
> Remove salt cleanup when unregistering

- backend/satellite_tools/repo_plugins/yum_src.py
- backend/spacewalk-backend.changes
This PR "quotes" the proxy settings when building the URL that is going to be used by Zypper when dealing with RPM repositories in `spacewalk-repo-sync` in order to avoid issues when proxy settings contains specials characters, i.a. `%` or `&`.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/13200
> Quote the proxy settings to be used by Zypper (bsc#1179087)

- testsuite/features/core/first_settings.feature
- testsuite/features/step_definitions/command_steps.rb
This PR changes the testsuite to use different credentials for the configured HTTP Proxy in order to test that proxy passwords with special characters like `%` or `&` are properly pass to Zypper.
This requires https://github.com/uyuni-project/uyuni/pull/2918 to be merged.
No difference.
- No documentation needed: **testsuite changes**
- No tests: **testsuite changes**
> Testsuite: Use different user for testsuite HTTP proxy

- projects/python-gzipstream/python-gzipstream.changes
- projects/python-gzipstream/python-gzipstream.spec
- Added Python 3 build for RHEL7+
- Generalised Python.
- Removed duplicate Python 3 package.
- "Prettified" spec.
No difference.
- No tests: Tested by automatic build.
Build tested for
CentOS 6
CentOS 7
CentOS 8
Fedora 31
Fedora 32
Fedora 33
Fedora Rawhide
OpenSUSE Leap 15.2
Fixes #
> python-gzipstream: Added Python 3 build for RHEL7+. Housekeeping

- uyuni/base/uyuni-base.spec
Disabled debug package building on "empty" file. RHEL fails on empty debug package.
No difference.
- No tests: Tested during automatic build
Build tested OK on
CentOS 6-8
Fedora 31-rawhide
Leap 15.2
Fixes #
> uyuni-base: Disabled debug package build

- testsuite/features/qam/add_custom_repositories/add_ceos6_repositories.feature
- testsuite/features/qam/add_custom_repositories/add_ceos7_repositories.feature
When we changed our internal qam mirror fqdn, we missed to update the testsuite code.
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13139
> [Port] QAM: Change the fqdn of the QAM Mirror (#13139)

- java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
- java/spacewalk-java.changes
- web/html/src/core/channels/api/use-mandatory-channels-api.js
- web/spacewalk-web.changes
CLM "add sources" panel is stuck with "Loading" when the mandatory channels API returns an error. This should not prevent users from working with CLM. This change fixes the API to go out of loading state when the request finishes with any result.
https://bugzilla.suse.com/1178839
Port of https://github.com/SUSE/spacewalk/pull/13150
> Fix mandatory channels JS API to finish loading in case of error (bsc#1178839)

- testsuite/features/qam/add_custom_repositories/add_mu_repository.template
- testsuite/features/step_definitions/common_steps.rb
Fix creation of MU repositories. We were missing a step in the loop, to go back to the Repositories page.
No difference.
- No documentation needes
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13141
> [Port] QAM: Fix creation of MU repositories (#13141)

- testsuite/features/qam/add_custom_repositories/add_ubuntu1604_repositories.feature
Fix parent channel on Ubuntu 16 custom channels
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13143
> [Port] QAM: Fix parent channel on Ubuntu 16 custom channels (#13143)

- testsuite/features/qam/init_clients/sle11sp4_ssh_minion.feature
- testsuite/features/qam/init_clients/sle12sp4_ssh_minion.feature
- testsuite/features/qam/init_clients/sle15_ssh_minion.feature
- testsuite/features/qam/init_clients/sle15sp1_ssh_minion.feature
Remove workaroung dmidecode in SLES nodes
Related to : https://github.com/SUSE/spacewalk/issues/12775
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13146
> [Port] QAM: Remove workaroung dmidecode in SLES nodes (#13146)

- testsuite/features/support/commonlib.rb
Replace slash by underscore, generating the repository name
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13297
> [Port] QAM: Replace slash by underscode, generating the repo name

- susemanager-sync-data/additional_products.json
- susemanager-sync-data/susemanager-sync-data.changes
Add product definitions for Debian 9 AMD64 and Debian 10 AMD64
No difference.
- No documentation needed: **Issue already exists**
- No tests: **just data**
Fixes https://github.com/SUSE/spacewalk/issues/12497
Tracks https://github.com/SUSE/spacewalk/pull/13181
> Support debian  add product data

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Debian 9 and Debian 10 got official product IDs and this PR change now the bootstrap repo metadata to use them.
Port of https://github.com/SUSE/spacewalk/pull/13295
No difference.
- General Documentation issue exists for Debian 9/10
Tracks https://github.com/SUSE/spacewalk/pull/13295
> Debian bootstrap repo data

- java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
- java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
- java/spacewalk-java.changes
When listing system duplicates by ip address, we don't take docker interfaces in account.
We already handle libvirt interfaces (like `virbrX`) and this PR extends this mechanism to docker interfaces.
(No UI change, only the dupes are not reported).
Fixes https://github.com/uyuni-project/uyuni/issues/2703
Tracks https://github.com/SUSE/spacewalk/issues/12930
> Ignore docker network interfaces when reporting list of systems duplicated by IP address

- projects/ssl-cert-check/spacewalk-ssl-cert-check.changes
- projects/ssl-cert-check/spacewalk-ssl-cert-check.spec
Modified SPEC file to work with RHEL8.
No difference.
- No tests: Tested during automatic build
Tested successful build on CentOS 7+ and LEAP 15.2
Fixes #
> ssl-cert-check: Added RHEL to the Python 3 build.

- spacewalk/spacewalk-setup-jabberd/include/manage_database
- spacewalk/spacewalk-setup-jabberd/spacewalk-setup-jabberd.changes
- spacewalk/spacewalk-setup-jabberd/spacewalk-setup-jabberd.spec
- Updated SPEC to work on RHEL.
- Generalised manage_database (to work with RHEL)
No difference.
Tested build successful on CentOS8, LEAP 15.2, Fedora 31-33
Fedora Rawhide fails. (Also CentOS <= 7)
Fixes #
> spacewalk-setup-jabberd: Updated SPEC and manage_database.

- search-server/spacewalk-search/spacewalk-search.changes
- search-server/spacewalk-search/spacewalk-search.spec
- Added RHEL8 build support.
No difference.
- No tests: Tested by automatic build.
Build tested successfully on CentOS 8 and LEAP 15.2
Fixes #
> spacewalk-search: Added RHEL8 build support

- suseRegisterInfo/suseRegisterInfo.changes
- suseRegisterInfo/suseRegisterInfo.spec
Adapted for RHEL builds.
No difference.
- No tests: Tested during auto-build process.
Build tested successfully on CentOS 7+, Fedora 31+, LEAP 15.2
Fixes #
> suseRegisterInfo: Added RHEL support

- web/html/src/utils/test-utils/setup.js
Fix incorrect import in Javascript unit test setup. This somehow flew under my radar last time.
No difference.
- No documentation needed: Bugfix, no visual.
- No tests: Fixes tests.
> Fix incorrect import

- susemanager-frontend/susemanager-nodejs-sdk-devel/package.json
- susemanager-frontend/susemanager-nodejs-sdk-devel/susemanager-nodejs-sdk-devel.changes
- susemanager-frontend/yarn.lock
Fix vul GHSA-gxr4-xjj5-5px2
No difference.
- No tests: 
Fixes # https://github.com/SUSE/spacewalk/issues/13309
Tracks #
> Upgrade jQuery version - vul GHSA-gxr4-xjj5-5px2

- spacewalk/certs-tools/spacewalk-certs-tools.changes
- spacewalk/certs-tools/spacewalk-certs-tools.spec
Added RHEL8 build support.
Minor simplification of the SPEC file.
No difference.
- No tests: Tested during automated build.
Tested the build successfully on CentOS 8, Fedora 31+, LEAP 15.2
Fixes #
> spacewalk-cert-tools: Added RHEL8 build and simplified SPEC file.

- java/conf/cobbler/snippets/minion_script
- java/conf/cobbler/snippets/redhat_register_using_salt
- java/spacewalk-java.changes
Port of https://github.com/SUSE/spacewalk/pull/13087
> Fix the activation key handling from kickstart profile (bsc#1178647)

- web/html/src/components/table/Table.test.js
- web/html/src/components/table/TableDataHandler.js
- web/html/src/utils/data-providers/simple-data-provider.js
- web/spacewalk-web.changes
Fix loading indicator for tables using `SimpleDataProvider`
No difference.
- No documentation needed: Fix
- No tests: Fix
Fixes https://github.com/SUSE/spacewalk/issues/12799
> Fix loading indicator for tables using SimpleDataProvider

- uyuni/base/uyuni-base.spec
Otherwise the current code doesn't build for SLE11 on SUSE manager.
Tested for CentOS6 at https://build.opensuse.org/package/rdiff/home:juliogonzalezgil:branches:systemsmanagement:Uyuni:Master:CentOS6-Uyuni-Client-Tools/uyuni-base?linkrev=base&rev=2 https://build.opensuse.org/package/show/home:juliogonzalezgil:branches:systemsmanagement:Uyuni:Master:CentOS6-Uyuni-Client-Tools/uyuni-base
Ping @sbluhm for awareness.
No difference.
- No tests: covered already by OBS
None
> Use generic code for the uyuni-base SPEC license file

- uyuni/base/uyuni-base.spec
Otherwise SLE11 fails to build for SUSE Manager with:
```
[   78s] ... checking for files with abuild user/group
[   78s]   abuild abuild /usr/share/doc/packages/uyuni-base-common
[   78s]   abuild abuild /usr/share/doc/packages/uyuni-base-common/LICENSE
```
Tested at:
- https://build.suse.de/package/show/home:juliogonzalezgil:branches:Devel:Galaxy:Manager:Head:SLE11-SUSE-Manager-Tools/uyuni-base
- https://build.opensuse.org/package/show/home:juliogonzalezgil:branches:systemsmanagement:Uyuni:Master:CentOS6-Uyuni-Client-Tools/uyuni-base
No difference.
- No tests: Tested by OBS
Fixes # …
> uyunu-base: place the license below defattr

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/spacewalk-java.changes
Change the message for reactivation key so that it's valid for both traditional and salt clients.
If the user needs more information about the reactivation keys, they refer to the detailed documentation, that is available under the info icon.
Before:
After (text change):
https://github.com/uyuni-project/uyuni-docs/pull/712
- No tests: just changed a message
https://github.com/SUSE/spacewalk/issues/13068
> Generalize the message for reactivation keys

- web/html/src/components/picker/recurring-event-picker.js
- web/html/src/manager/state/recurring-states-edit.js
- web/spacewalk-web.changes
Fix the help icons in the recurring states edit menu to link to an unavailable page.
In fact they should not lead to anything just provide some information displayed
through the icons title.
No difference.
- No tests: 
Fixes https://github.com/SUSE/spacewalk/issues/13324
> Fix question mark explanations for Recurring States

- testsuite/features/qam/init_clients/ubuntu1604_minion.feature
- testsuite/features/qam/init_clients/ubuntu1604_ssh_minion.feature
- testsuite/features/qam/init_clients/ubuntu1804_minion.feature
- testsuite/features/qam/init_clients/ubuntu1804_ssh_minion.feature
- testsuite/features/qam/init_clients/ubuntu2004_minion.feature
- testsuite/features/qam/init_clients/ubuntu2004_ssh_minion.feature
Port of https://github.com/SUSE/spacewalk/pull/13356
Related Card: #13346
Select the proxy to bootstrap our Ubuntu SSH Minions
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13356
> [Port] QAM: Add proxy to our Ubuntu SSH Minions (#13356)

- java/code/src/com/suse/manager/reactor/utils/RhelUtils.java
- java/code/src/com/suse/manager/reactor/utils/test/RhelUtilsTest.java
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_centos2.json
- java/spacewalk-java.changes
When detecting Expanded Support, we parse redhat-release to get the version number.
But in case of CentOS image was used to install the server, we do not read redhat-release but centos-release file.
This PR implement a fallback when redhat-release value does not exist and parse centos-release value as second try.
(Oracle Linux is not a valid base for Expanded Support. So it can be ignored)
Port of https://github.com/SUSE/spacewalk/pull/13354
No difference. …
> Fallback to centos when redhat release is empty

- reporting/spacewalk-reports.changes
- reporting/spacewalk-reports.spec
- Added RHEL/Fedora to Python3 builds.
No difference.
Tested successful builds on CentOS 6+, LEAP 15.2, Fedora 31+
Fixes #
> spacewalk-reports: Added RHEL/Fedora to Python3 builds.

- spacewalk/package/spacewalk.changes
- spacewalk/package/spacewalk.spec
Removed SUSE PXE boot requirement for non-SUSE systems.
No difference.
Fixes #
> Removed SUSE PXE boot requirement for non-SUSE systems.

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/commonlib.rb
This PR:
- explains better how "targetted assassinations" of reposyncs work,
both in terms of workflow of the test suite and of implementation
- adds safety net for SLES 15 SP2 and SLES 12 SP5 which we already use, or will use, in our test suite
- does not add safety net for auto-installation if we don't perform it
- removes possible duplicates from the list for faster execution
In 4.0 and 4.1 versions, it also adds a bugfix that was not backported (`15SP2` versus `15-SP2`).
Fixes SUSE/spacewalk#12895
Ports:
* 4.0: SUSE/spacewalk#13348
* 4.1: SUSE/spacewalk#13349
> Better safety net mechanism

- testsuite/features/core/srv_docker.feature
This PR is related to https://github.com/uyuni-project/uyuni/pull/2224, and will skip the `Create an image store without credentials` test scenario if the registry is not available.
This will prevent the following error when the registry is not available:
No difference.
- No documentation needed: This is just a test fix
- Cucumber test was fixed/improved
Tracks https://github.com/SUSE/spacewalk/pull/13358
Tracks https://github.com/SUSE/spacewalk/pull/13359
> Skip image store test if registry is not available

- proxy/proxy/pm/rhn_package_manager.py
- proxy/proxy/spacewalk-proxy.changes
During python3 porting we overlooked a compare of string with bytes.
No difference.
- No tests
Fixes https://github.com/uyuni-project/uyuni/issues/2473
Tracks
> Fix py3 proxy package manager

- testsuite/features/reposync/srv_enable_sync_products.feature
- testsuite/features/reposync/srv_sync_channels.feature
- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/support/commonlib.rb
get_gpg_key expect a node and not a host string
forward port changes from 4.1 branch to use newer products for synchronization
No difference.
- No tests: **fix tests**
> get_gpg_keys expect a node

- java/spacewalk-java.spec
Using maven generated package result in a different jar name.
No difference.
- No tests: **build details**
> use generated jar name

- java/buildconf/ivy/obs-maven-config.yaml
jakarta-commons-el => apache-commons-el from Leap
apache-commons-jexl use package from Leap instead of own build one.
No difference.
- No tests: **internal**
> Fix maven to obs after pkg rename

- testsuite/features/reposync/srv_check_installer_updates.feature
- testsuite/features/reposync/srv_sync_channels.feature
- testsuite/features/reposync/srv_sync_products.feature
Port of https://github.com/SUSE/spacewalk/pull/13376
This PR fixes multiple failures in testsuite core's setup and synchronizes products uses by testsuite.
Tracks https://github.com/SUSE/spacewalk/pull/13376
> Testsuite - sync product changes with 4.1 branch

- testsuite/features/reposync/srv_sync_channels.feature
Port of https://github.com/SUSE/spacewalk/pull/13384
> Testsuite - fix typo in module name

- testsuite/features/support/client_stack.rb
It fixes get_gpg_keys function
- testsuite/features/support/client_stack.rb:
Get the host and pass it as argument to get_os_version.
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13385
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13386
> Testsuite: Fix get_gpg_keys function

- testsuite/features/step_definitions/common_steps.rb
Test for a selected product can be made faster (do not search in the page twice) and more robuts (current test fails in certain conditions).
Ports:
* 4.1: SUSE/spacewalk#13381
* 4.0: SUSE/spacewalk#13383
> Faster and more robust checkbox test

- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/support/client_stack.rb
Pass the right type for the first argument
Add a 2nd optional arg with the target from where to obtain the GPG keys ($server, default).
Fixes https://github.com/uyuni-project/uyuni/pull/2986
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13393
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13392
> Add second arg head

- web/html/src/manager/shared/menu/menu.js
A very small change in preparation for https://github.com/SUSE/spacewalk/issues/13208.  
The Typescript parser is not happy about the `>>` in `<span>></span>` template, making the markup explicit with `&gt;` fixes the issue.  
This is the only instance of such an issue I could find.  
No difference.
- No tests: No functional change.
Related: https://github.com/SUSE/spacewalk/issues/13208
> Make menu markup explicit

- .github/workflows/javascript-unit-tests.yml
As I learned in the review meeting, frontend unit tests are currently not run against PRs.  
This is an initial implementation for the action.  
I could use some help with integrating `actions/cache@v2` for dependencies similar to `java-checkstyle`, I'm not that familiar with the tool.   
Perhaps @renner could give a helping hand?  
Also, I'm not sure how to correctly integrate with the test rerunner bot.
Other than that, I tested it on my own fork and it seems to work as intended.
No difference.
- No documentation needed: Workflow setup, no user facing changes.
- Unit tests were added to the pipeline.
Fixes: https://github.com/SUSE/spacewalk/issues/13382 …
> WIP: Github action for Javascript unit tests

- java/code/src/com/redhat/rhn/frontend/strings/database/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
Not sure how this could happen, but we had duplicates in our translations.
This PR cleans them up.
No difference.
> remove duplicate trans-units

- java/code/src/com/suse/manager/webui/controllers/login/templates/login.jade
- java/code/webapp/WEB-INF/decorators/layout_bare.jsp
- java/code/webapp/WEB-INF/decorators/layout_c.jsp
- java/code/webapp/WEB-INF/decorators/layout_equals.jsp
- java/spacewalk-java.changes
Add the `lang` attribute to our `<html>` tags
No difference.
- No tests: 
Fixes https://github.com/SUSE/spacewalk/issues/13234
> Add lang attribute to html tags

- testsuite/features/secondary/srv_xmlrpc_activationkey.feature
- testsuite/features/step_definitions/xmlrpc_common.rb
- testsuite/features/support/xmlrpc_activationkey.rb
This PR fix two XML-RPC issues:
-  As we refactored the activation key API handler, we need to refactor the scenarios for get_details and set_details
- On the login method for the action chain API handler, we missed a instantiation
No difference.
> Fix XML-RPC tests

- java/spacewalk-java.spec
Fix `salt_user_group` being set to `root` which caused minion bootstrapping to fail due to permission issues.
No difference.
- No tests: Needs to pass existing tests.
Related test runs: https://ci.suse.de/view/Manager/view/Manager-Head/job/manager-Head-cucumber-NUE/1046/testReport/
> Fix permission issue in Salt user group

- web/html/src/manager/login/login.js
Small things that caught my eye when working on https://github.com/uyuni-project/uyuni/pull/2927.
The effect can be replaced with [`autofocus`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefautofocus). Using `tabindex` with a greater value than 0 can [break accessibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) so I would suggest we remove it.  
Thoughts?  
No difference. Tab indexing has changed, but this would be more widely user friendly.
- No documentation needed: No visual difference.
- No tests: No visual difference. …
> Simplify login page inputs

- testsuite/features/support/commonlib.rb
This PR adds beta tools and server apps repos to do not kill list for repo synchronization.
https://github.com/SUSE/spacewalk/issues/13284
> Testsuite - add beta tools to do not kill list

- schema/spacewalk/susemanager-schema.changes
Fixes issue when allow vendor change column sql file is in the an older schema directory. 
https://bugzilla.suse.com/show_bug.cgi?id=1179759
#13388 
port of https://github.com/SUSE/spacewalk/pull/13416
Port of # **remove rest of file if this is a port**
No difference.
Before:
After:
- No tests: 
Fixes #
> Move dist upgrade allow vendor change sql to newer directory

- backend/spacewalk-backend.changes
- backend/spacewalk-backend.spec
SPEC file update:
- Source0 URL
- Python3 as build requirement.
No difference.
- No tests: Tested during automatic package build.
Manually built successfully on LEAP15.2, CentOS8
> spacewalk-backend: SPEC file update Python3 build requirements/Source0

- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes
- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.spec
- tftpsync/susemanager-tftpsync/susemanager-tftpsync.changes
- tftpsync/susemanager-tftpsync/susemanager-tftpsync.spec
Modified the tftpsync packages to build on RHEL.
No difference.
susemanager-tftpsync-recv built on LEAP15.2, CentOS8
susemanager-tftpsync: CentOS7+, Fedora32+,LEAP15.2
> tftpsync: Enhanced for RHEL8

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/susemanager-schema.spec
Use versioned Python2 for RHEL8 and Fedora.
No difference.
Built successfully on CentOS6-8, LEAP15.2 and Fedora32. Fails on Fedora33/Rawhide due to Perl.
> susemanager-schema: Use versioned Python2 for RHEL8 and Fedora.

- java/spacewalk-java.spec
Updated some jar names for HREL8 due to package rebuild on OBS.
No difference.
- No tests: Tested during auto-build.
Manually tested successfully on CentOS8 and LEAP15.2
> spacewalk-java: Updated RHEL8 jars

- testsuite/features/step_definitions/xmlrpc_common.rb
Fixing a mistake in the step
```
Given(/^I am logged in via XML\-RPC powermgmt as user "([^"]*)" and password "([^"]*)"$/) do |luser, password|
@powermanagenent_api = XMLRPCPowermanagementTest.new($server.ip)
@powermanagenent_api.login(luser, password)
@system_api.login(luser, password)  # <------ THIS SHOULDN'T BE HERE
end
```
No difference.
Tracks # https://github.com/SUSE/spacewalk/pull/13443
> QA: Fix XML-RPC common step

- testsuite/features/secondary/srv_xmlrpc_activationkey.feature
- testsuite/features/secondary/srv_xmlrpc_channel.feature
- testsuite/features/secondary/srv_xmlrpc_user.feature
- testsuite/features/step_definitions/xmlrpc_common.rb
Fixing a mistake in the step, as a further step of the scenarios of powermgmt depends on system api
```
Given(/^I am logged in via XML\-RPC powermgmt as user "([^"]*)" and password "([^"]*)"$/) do |luser, password|
@powermanagenent_api = XMLRPCPowermanagementTest.new($server.ip)
@powermanagenent_api.login(luser, password)
end
```
Also adding a small refactor to fix another dependency of step issue.
No difference.
Tracks # https://github.com/SUSE/spacewalk/pull/13444 …
> Fix XML-RPC powermgmt login of system api (#13444)

- backend/satellite_tools/repo_plugins/deb_src.py
- backend/satellite_tools/repo_plugins/yum_src.py
- backend/spacewalk-backend.changes
- java/code/src/com/redhat/rhn/frontend/action/channel/manage/repo/RepoDetailsAction.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/repo/InvalidRepoLabelException.java
- java/code/src/com/redhat/rhn/manager/channel/repo/BaseRepoCommand.java
- java/code/src/com/redhat/rhn/manager/channel/test/BaseRepoCommandTest.java
- java/spacewalk-java.changes
This PR makes fixes some issues we have in `spacewalk-repo-sync` when dealing with custom DEB repositories that contains non-valid characters on its label (like `/`).
The summary of changes is:
- Add validation to custom repository label (same as channel name): allow uppercase, spaces, slashes, etc.
- Fix `deb_src` reposync plugin to use a sanitized "repository label" when building the repository cache root path.
- Fix `yum_src` reposync plugin to use a sanitized "repository label" (instead of channel label) when building the repository cache root path.
These are the current regex we use for validation:
```java
CHANNEL_NAME_REGEX = "^[a-zA-Z\\d][\\w\\d\\s\\-\\.\\'\\(\\)\\/\\_]*$"
CHANNEL_LABEL_REGEX = "^[a-z\\d][a-z\\d\\-\\.\\_]*"
REPO_LABEL_REGEX = …
```
> Use sanitized repo label to build reposync repo cache path (bsc#1179410)

- testsuite/features/secondary/min_action_chain.feature
- testsuite/features/support/env.rb
PR https://github.com/uyuni-project/uyuni/pull/2921 assumed that E2E tests are executed from the `/root` location on the `controller` node.
If `CI` is running E2E tests from a different location, we will need to adapt accordingly.
This PR assumes that E2E tests are executed from `/root/spacewalk/testsuite/` location.
No difference.
- No documentation needed: just fixing tests
> Fix "working directory" on cucumber tests that rely on downloaded files

- testsuite/features/reposync/srv_sync_products.feature
PR unselects `SUSE Manager Tools 15 x86_64 (BETA)` so only released client tools are used.
https://github.com/SUSE/spacewalk/issues/13284
> Testsuite - do not use beta client tools for SLE15

- testsuite/features/reposync/srv_sync_products.feature
Fix of https://github.com/uyuni-project/uyuni/pull/3017
> Testsuite - fix beta client tools deselection

- spacecmd/po/Makevars
- spacecmd/spacecmd.changes
- spacecmd/src/bin/spacecmd
- spacecmd/src/spacecmd/activationkey.py
- spacecmd/src/spacecmd/api.py
- spacecmd/src/spacecmd/configchannel.py
- spacecmd/src/spacecmd/cryptokey.py
- spacecmd/src/spacecmd/custominfo.py
- spacecmd/src/spacecmd/distribution.py
- spacecmd/src/spacecmd/errata.py
- spacecmd/src/spacecmd/group.py
- spacecmd/src/spacecmd/i18n.py
- spacecmd/src/spacecmd/kickstart.py
- spacecmd/src/spacecmd/misc.py
- spacecmd/src/spacecmd/org.py
- spacecmd/src/spacecmd/package.py
- spacecmd/src/spacecmd/repo.py
- spacecmd/src/spacecmd/report.py
- spacecmd/src/spacecmd/scap.py
- spacecmd/src/spacecmd/schedule.py
- spacecmd/src/spacecmd/shell.py
- spacecmd/src/spacecmd/snippet.py
- spacecmd/src/spacecmd/softwarechannel.py
- spacecmd/src/spacecmd/ssm.py
- spacecmd/src/spacecmd/system.py
- spacecmd/src/spacecmd/user.py
- spacecmd/src/spacecmd/utils.py
Make use of new `_N` method for spacecmd's `logging.*` messages.
The `_N` method is returning the same string passed as argument
No difference.
- No documentation needed: internal strings
- No tests: already present
> Fix: don't translate spacecmd logging

- testsuite/config/cucumber.yml
The default Cucumber profile must have some content, otherwise it fails.
No difference.
Fixes #
> QA: Fix default Cucumber profile

- uyuni/common-libs/common/rhn_deb.py
- uyuni/common-libs/uyuni-common-libs.changes
* Section seems to optional for Debian packages (Recommended) so not every Debian package has that. Later on all missing keys get added anyway. So it's added if it is there.
* Re-raising without the actual error is not working. Error information are now being passed.
No difference.
- No documentation needed: Just a fix.
- No tests: …
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1179555
> Section is optional and fix for re-raise

- testsuite/features/reposync/srv_sync_channels.feature
This PR adds tag for SUSE Manager specific scenario and removes `List all products for Uyuni` scenario as this is fully covered by the steps from previous one (`List all products for SUSE Manager`) and also is specific for SUSE Manager again.
> Testsuite - remove duplicity scenario and use tag for suma specific one

- java/code/src/com/redhat/rhn/frontend/xmlrpc/configchannel/ConfigChannelHandler.java
- java/spacewalk-java.changes
- spacecmd/po/de.po
- spacecmd/po/es.po
- spacecmd/po/it.po
- spacecmd/po/ja.po
- spacecmd/po/pt.po
- spacecmd/po/pt_BR.po
- spacecmd/po/sk.po
- spacecmd/po/spacecmd.pot
- spacecmd/po/zh_CN.po
- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/configchannel.py
- testsuite/features/secondary/min_state_config_channel.feature
- testsuite/features/step_definitions/command_steps.rb
With this PR, users will be able to set the "Revision Number" when updating `init.sls` via CLI:
```
spacecmd> configchannel_updateinitsls ... -r <revision>
```
Or via API:
```
configchannel.updateInitSls(..., <revision>)
```
Note that this is already supported by the WebUI, so we are only adapting the CLI and API accordingly.
No difference.
- No documentation needed: The API documentation, which is acessible via "Help > API" on the left menu, is automatically generated.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1179566 (Partially)
If you need to …
> Allow to specify 'Revision' when updating 'init.sls' via CLI or API

- java/code/src/com/redhat/rhn/frontend/xmlrpc/saltkey/SaltKeyHandler.java
- java/code/src/com/suse/manager/utils/SaltKeyUtils.java
- java/spacewalk-java.changes
The bahavior of the saltKey API was not behaving like described.
No difference.
- No documentation needed: **already covered**
Tracks https://github.com/SUSE/spacewalk/pull/13418
> Add saltkey to api

- java/code/webapp/WEB-INF/pages/configuration/overview/localfilelist.jsp
Fix broken bubble message style
The bubble message is now aligned with the other "sister" page the [`globalfilelist.jsp`](https://github.com/uyuni-project/uyuni/blob/master/java/code/webapp/WEB-INF/pages/configuration/overview/globalfilelist.jsp#L20)
Before:
After:
- No documentation needed: simple broken style fix
- No tests:  simple broken style fix
Fixes #
Tracks # TODO for SUSE Manager 4.1
> Fix broken bubble message style in localfilelist.jsp

- testsuite/features/step_definitions/xmlrpc_common.rb
According to documentation[1], attribute name is `faultString` instead of `fault_string`.
Failure example:
[1] https://ruby-doc.org/stdlib-2.2.10/libdoc/xmlrpc/rdoc/XMLRPC/FaultException.html
No difference.
- No documentation needed: Just fixing E2E tests code.
- No tests: Just fixing E2E tests code.
> Fix access to fault string attribute of XMLRPC::FaultException

- tftpsync/susemanager-tftpsync-recv/configure-tftpsync.sh
- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes
Parsing commandline options in configure-tftpsync.sh was broken
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13465
Tracks https://github.com/SUSE/spacewalk/pull/13474 https://github.com/SUSE/spacewalk/pull/13475
> Tftpsync fix option parsing

- java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProjectFactory.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/test/ContentProjectFactoryTest.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/EnvironmentResponse.java
- java/spacewalk-java.changes
- web/html/src/components/panels/CreatorPanel.js
- web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-lifecycle.js
- web/html/src/manager/content-management/shared/type/project.type.js
- web/spacewalk-web.changes
Fix for https://bugzilla.suse.com/1179552
Before:
After:
Fixes https://github.com/SUSE/spacewalk/issues/13337
> Prevent deletion of CLM environments if they're attached to a kickstart profile (bsc#1179552)

- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/reactor/messaging/test/packages.profileupdate.allversions.json
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/spacewalk-java.changes
With the newer output format, `pkg.info_installed` sometimes returns duplicate entries having the same NEVRA for a package. Since it's not an issue from SUMA's perspective, this update lets SUMA ignore the additional entries and continue the process.
- Unit tests were adapted
Port of: https://github.com/SUSE/spacewalk/pull/13377
> Ignore duplicate NEVRAs in package profile update (bsc#1176018)

- java/code/src/com/redhat/rhn/frontend/xmlrpc/configchannel/ConfigChannelHandler.java
- java/spacewalk-java.changes
- testsuite/features/secondary/min_config_state_channel_xmlrpc.feature
- testsuite/features/step_definitions/xmlrpc_common.rb
- testsuite/features/support/xmlrpc_configchannel.rb
With this PR, users will be able to provide "init.sls file contents" when creating a new state config channel via XML-RPC.
**Motivation:** Allow "inter server sync" to create an `init.sls` with contents and "revision 1".
No difference.
- No documentation needed: The API documentation, which is acessible via "Help > API" on the left menu, is automatically generated.
Fixes: https://github.com/SUSE/spacewalk/issues/13345
> Allow to specify file contents when creating state channel via API

- testsuite/Gemfile
- testsuite/documentation/static-run.md
- testsuite/features/support/env.rb
- testsuite/features/support/twopence_init.rb
Add support to debug using a browser (skip headless mode)
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> Add support to debug using a browser (skip headless mode)

- client/tools/mgr-cfg/mgr-cfg.changes
- client/tools/mgr-cfg/mgr-cfg.spec
- Updated Python definitions for RHEL8.
- Quoted text comparisons as words are not supported anymore.
No difference.
Manually tested successfully on CentOS6+, LEAP 15.2, Fedora32+
> mgr-cfg: Updated Python definitions for RHEL8 and quoted text comparisons.

- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
Follow-up of https://github.com/uyuni-project/uyuni/pull/3039
This PR makes the algorithm more deterministic.
- No documentation needed:fix
> Take the later package on resolving duplicate NEVRAs in package profile update

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
- java/spacewalk-java.changes
The debian repo format has not one single file which must be available and can be used to test if a repo is available.
To fix the detection multiple files are now tested. Only one must be available.
Added a patch to speedup repository syncing while skipping OES checks in the main loop.
This cause HEAD requests for every OES repo which take a long time.
But OES is tested in an extra function by just testing one credential.
This speedup repository syncing from ~3 Minutes to ~30 Seconds
No difference.
- No documentation needed: **fix a bug**
Fixes https://github.com/SUSE/spacewalk/issues/13374
Fixes https://github.com/SUSE/spacewalk/issues/13488
Tracks https://github.com/SUSE/spacewalk/pull/13503 https://github.com/SUSE/spacewalk/pull/13504 …
> Fix deb repo detection

- testsuite/features/secondary/minssh_salt_install_package.feature
Restore idempotency in one test.
Bring back the system to the initial state.
- testsuite/features/secondary/minssh_salt_install_package.feature:
Remove the installed package and refresh the package list.
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13505
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13506
> Testsuite: Restore idempotency

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/webapp/WEB-INF/decorators/layout_c.jsp
- java/spacewalk-java.changes
This PR improves misleading UI message that is displayed on systems with modules activated.
Note that the original issue suggests including a link for the documentation, but since that requires access to **user docs locale**, which requires a refactor on multiple legacy `jsp` actions, I'm suggesting not including that in this PR.
Before:
After:
- No documentation needed: This PR only improves an existing UI message.
- No tests: This PR only improves an existing UI message.
Fixes: https://github.com/SUSE/spacewalk/issues/13326 …
> Improve misleading UI message displayed on systems with modules activated

- spacewalk/setup/bin/spacewalk-setup
- spacewalk/setup/lib/Spacewalk/Setup.pm
- spacewalk/setup/spacewalk-setup.changes
- Dynamic truststore location for SUSE and RHEL.
- Dynamic document root location for SUSE and RHEL.
No difference.
- No tests: I don't know how to create tests for this.
Manually verified the installation still working on physical CentOS8 and LEAP15.2 system.
> spacewalk-setup: Added dynamic path for trust store and doc root.

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
On the overview page, we expect to have as installed product a concrete version for SLES systems.
We were looking for "X-SPy" while we display "X SPy" so we tweak the scenario to fix this concrete use case, without touching the general expected value for the get_osversion method.
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/13524
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13523
> QA: Fixing the expected value for the OS version in the overview page

- testsuite/features/support/env.rb
When we run our tests not using the headless option, the browser opened expects that we click on a button to ignore certificate errors. To avoid it, we will pass an extra parameter in the options of chrome driver.
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/13527
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13526
> QA: Chromedriver should ignore certificate errors

- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/secondary/allcli_software_channels_dependencies.feature
- testsuite/features/secondary/srv_distro_cobbler.feature
- testsuite/features/step_definitions/common_steps.rb
We recently upgraded the product SLES15 to SLES15 SP2, in our repo sync stage.
Some of our scenarios were expecting for SLES15 channel names, so this PR fix is replacing these names with the new names.
No difference.
Fixes #
> QA: Fixing UI checks expecting old SLE15 channels

- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/spacewalk-java.changes
This fixes a race condition where setting the picked up time again after the reboot has already been started could lead to the boot time being earlier then the pickup time of the action triggering the reboot.
No difference.
Fixes #https://github.com/SUSE/spacewalk/issues/12590
> fix reboot action race condition (bsc#1177031)

- testsuite/features/step_definitions/common_steps.rb
without this commit, the uyuni head testuite is
failing, because it expects to have all recommended channels.
Testsuite should not stumble into the `./features/step_definitions/common_steps.rb:551:in` error anymore, since all recommended channels are checked accordingly.
uyuni branch only
> Checked server-app-module in uyuni head testsuite

- backend/server/importlib/backend.py
- backend/server/importlib/backendOracle.py
- backend/server/rhnServer/server_packages.py
- backend/spacewalk-backend.changes
Adding new extratag keys during reposync can fail with 
```
duplicate key value violates unique constraint "rhn_pkg_extra_tag_key_idx"
DETAIL:  Key (name)=(Cnf-Extra-Commands) already exists.
```
This result in failed imports of a bunch of packages. To improve the creation of new keys, this PR declare lookup and insert functions and make use of it in the import code.
Second case found while inserting into rhnPackageKey.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/3040
Tracks https://github.com/SUSE/spacewalk/pull/13545 …
> Improve extra key handling

- projects/perl-Satcon/bin/satcon-deploy-tree.pl
- projects/perl-Satcon/perl-Satcon.changes
- spacewalk/admin/rhn-config-satellite.pl
- spacewalk/admin/spacewalk-admin.changes
- spacewalk/setup/bin/spacewalk-make-mount-points
- spacewalk/setup/bin/spacewalk-setup
- spacewalk/setup/spacewalk-setup.changes
- susemanager/bin/mgr-setup
- susemanager/susemanager.changes
- susemanager/susemanager.spec
- uyuni/base/uyuni-base.changes
- uyuni/base/uyuni-base.spec
- web/spacewalk-web.changes
- web/spacewalk-web.spec
uyuni-base: Removed RHEL specific folder rights from SPEC file.
Added RHEL Apache group to perl-Satcon.
Added RHEL Apache group to spacewalk-admin.
Added RHEL Apache group to spacewalk-setup scripts.
Added RHEL Apache group to mgr-setup.
Added variable folder location (javascript/vendors) to susemanager.
Fixed variable folder location in spacewalk-html.
No difference.
No documentation needed: No functional change.
- No tests: Not sure whether necessary. The code lines have been individually tested manually on CentOS 8 and LEAP15.2. Installation has been verified on CentOS 8 (not Leap though). …
> Fixed RHEL setup routine.

- testsuite/features/core/allcli_sanity.feature
- testsuite/features/core/first_settings.feature
This PR moves the check for running services to sanity checks.
Spotted when trying to work on card SUSE/spacewalk#4965 (make core features lighter).
Ports:
* 4.0: SUSE/spacewalk#13553
* 4.1: SUSE/spacewalk#13552
> Move services tests to sanity checks

- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
https://github.com/uyuni-project/uyuni/pull/2998/ removed code that could lead to a race condition for reboot in case event processing is slow. This code was not needed in case of a single reboot action but it looks like reboot inside of action chains currently relies on picked up status being set at this point.
No difference.
- No tests
Fixes SUSE/spacewalk#13535
> fix action chains reboot

- testsuite/features/step_definitions/common_steps.rb
Addresses this (seen on 4.1 with SLES minion):
```
And I wait until onboarding is completed for "sle_minion" 4m 44s 624msShow Error -
Timeout after 250 seconds (Timeout.timeout): Text 'Hardware List Refresh' is still visible (RuntimeError)
```
Let a long, fixed, timeout for the `Hardware List Refresh`, no matter which operating system runs on the minion.
Ports:
* 4.0: SUSE/spacewalk#13578
* 4.1: SUSE/spacewalk#13577
> Leave more time for Hardware List Refresh on all platforms

- testsuite/features/step_definitions/common_steps.rb
Give Ubuntu enough time to bootstrap
Fixes https://github.com/uyuni-project/uyuni/pull/3077
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13584
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13585
> Testsuite: Give Ubuntu enough time to bootstrap

- uyuni/base/uyuni-base.changes
- uyuni/base/uyuni-base.spec
httpd as installation prerequisite for RHEL and Fedora to ensure that the apache user is available for permission setting inthe spec file.
No difference.
- No tests: Tested during automatic build process.
Manually tested build successfully on CentOS6-8, Leap 15.2, Fedora 32-Rawhide.
Fixes #
> uyuni-base: Added Apache as installation prerequisite

- web/html/src/.storybook/preview-head.html
Fix storybook
No difference.
- No documentation needed: fixing a sort of documentation is documentation after all
- No tests: story book is not tested
Fixes # https://github.com/SUSE/spacewalk/issues/13491
> Fix storybook missing t() definition

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/package.py
- spacecmd/tests/test_package.py
With this PR, the spacecmd package_details and package_search commands will now allow to specify multiple package names on "non-advanced" search, e.g.: `spacecmd -- package_details zypper apparmor`.
```
server:~ # spacecmd -- package_details zypper | grep 'Name:' | sort | uniq | wc -l
INFO: Connected to https://server.tf.local/rpc/api as admin
2
server:~ # spacecmd -- package_details apparmor | grep 'Name:' | sort | uniq | wc -l
INFO: Connected to https://server.tf.local/rpc/api as admin
5
server:~ # spacecmd -- package_details name:zypper name:apparmor | grep 'Name:' | sort | uniq | wc -l
INFO: Connected to https://server.tf.local/rpc/api as admin
7
server:~ # spacecmd -- package_details zypper apparmor | grep 'Name:' | sort | uniq | wc -l
INFO: Connected to …
```
> spacecmd: support multiple package names on "package_details" command

- spacewalk/admin/salt-secrets-config.py
- spacewalk/admin/spacewalk-admin.changes
- spacewalk/admin/spacewalk-admin.spec
- spacewalk/admin/spacewalk.target
- Added salt-secrets-config to the default service list.
- Updated salt certificate script to variable certificate path and message on failing update-ca-certificates.
- Updated source URL in spec file.
No difference.
- No documentation needed: no functional changes
- No tests: tested during automatic build.
Manual tests of code segments done on Leap 15.2 and CentOS 8.
Build tested successfully for CentOS 7/8 and Leap 15.2. Installation tested successfully on CentOS 8
Fixes #
> spacewalk-admin: Fixed salt certificate creation.

- java/code/src/com/redhat/rhn/domain/rhnpackage/PackageEvr.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/kickstart/KickstartScheduleCommand.java
- java/code/src/com/redhat/rhn/manager/rhnpackage/PackageManager.java
- java/code/src/com/redhat/rhn/manager/rhnpackage/test/PackageManagerTest.java
This PR has some missed additions to the recent version compare refactoring using the PackageEvr.compareTo instead of some custom vercmp while its special null handling has been moved to the call sites.
No difference.
- No tests: The existing tests for the custom vercmp was temporarily adjusted to run against the PackageEvr.compareTo while doing the same special null handling the call sites do now. All the test still passed but since it really does not test any non test code anymore they were removed as version compare already has its own tests. …
> replace custom vercmp function with PackageEvr.compareTo

- susemanager-utils/susemanager-sls/src/tests/test_state_mgrcompat.py
This PR fixes the tests for `mgrcompat` module that are currently failing due a change on the expected deprecation behavior of Salt 3002. 
No difference.
- No documentation needed: **tests changes**
> Adapt tests for "mgrcompat" module after deprecation changes

- java/code/src/com/redhat/rhn/manager/distupgrade/test/DistUpgradeManagerTest.java
- schema/spacewalk/common/tables/suseMdKeyword.sql
- schema/spacewalk/common/tables/suseProductChannel.sql
- schema/spacewalk/common/tables/suseUpgradePath.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/802-add-missing-uq-index.sql
During the development of "ISS Revamp: Data dumper implementation #12968" we found some tables with missing unique key constraints.
This PR will add a unique index to the following tables:
- suseproductchannel
- susemdkeyword
- suseupgradepath
No difference.
- No documentation needed, schema changes.
- No tests. Adding missing unique index.
Fixes https://github.com/SUSE/spacewalk/issues/13517
Tracks:
- Port to Manager 4.1 https://github.com/SUSE/spacewalk/pull/13591 …
> add missing unique index on suse tables

- proxy/proxy/httpd-conf/spacewalk-proxy.conf
- proxy/proxy/spacewalk-proxy.changes
This reverts https://github.com/uyuni-project/uyuni/pull/3076 as it generates this problem:
```
Exception: E: Failed to fetch https://suma-41-pxy.mgr.prv.suse.net:443/rhn/manager/download/dists/test-channel-deb-amd64/main/binary-amd64/Packages  404  Not Found [IP: 10.84.220.162 443
```
> Revert "Fix: slow refresh Ubuntu repos via SUMa proxy (bsc#1176906)"

- spacewalk/config/spacewalk-config.changes
- spacewalk/config/spacewalk-config.spec
- Fixed apache group for RHEL.
- Updated Source URL in SPEC.
No difference.
- No documentation needed: no functional changes
- No tests: tested during automatic build.
Build tested successfully on CentOS8/Leap15.2
> spacewalk-config: Fixed Apache group for RHEL.

- spacewalk/spacewalk-setup-jabberd/include/manage_database
- spacewalk/spacewalk-setup-jabberd/spacewalk-setup-jabberd.changes
Fixes database setup query detection.
Message during `zypper in spacealk-setup-jabberd`:
`Error: database setup query missing (/usr/share/jabberd/db-setup.sqlite)`
No difference.
- No tests: unsure how to test.
> spacewalk-setup-jabberd: Fix database setup query detection.

- web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-form.js
- web/spacewalk-web.changes
`Name` and `Label` inputs are required on the `Environment Lifecycle` form, so we should display the corresponding `*` sign.
Before:
After:
- No documentation needed: This is only a visualization improvement.
- No tests: This is only a visualization improvement.
Fixes https://github.com/SUSE/spacewalk/issues/13514
> CLM: Mark required inputs in the 'Environment Lifecycle' form

- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/secondary/srv_distro_cobbler.feature
- testsuite/features/step_definitions/command_steps.rb
No difference.
Before:
After:
Fixes # …
> Fixing the "label" error, typos, and removing unused code

- backend/spacewalk-backend.changes
- backend/wsgi/wsgiRequest.py
When copying headers from parent requests in the proxy we can get also the `Transfer-Encoding` header field which may be set to `chunked`. Using this as input for WSGI to return a result to the client cause timeout issues as it does not handle correctly (at least not when setting it from external).
The proxy code remove this header already for successful responses, but in case of an error (404 Not Found) that header was still present.
This PR remove the Transfer Encoding header just before sending it back to the client.
Fixes #2241
Tracks SUSE/spacewalk#13618 …
> Drop Transfer-Encoding header from proxy respone (bsc#1176906)Master wsgi drop chuncked transfer encoding

- web/spacewalk-web.spec
Port of the fix uncovered in https://github.com/SUSE/spacewalk/pull/13412, namely https://github.com/SUSE/spacewalk/pull/13412/commits/c904c590dfc0e42f9594cc63889a2d629d1b5671
Requiring nodejs is redundant because nodejs-packaging [already requires it](https://build.opensuse.org/package/view_file/systemsmanagement:Uyuni:Master:Other/nodejs-packaging/nodejs-packaging.spec?expand=1).
No difference.
- No tests: Needs to pass existing tests.
Related: https://github.com/SUSE/spacewalk/pull/13412 …
> Remove redundant nodejs requirement

- testsuite/features/secondary/min_salt_software_states.feature
Co-author Eric Bischoff <ebischoff@suse.com>
Without this patch, the sle_minion with killed
salt-minion will not have it restarted if some
steps fail prior to that step.
No difference.
Before:
After:
- No …
> Moved salt minion restarting to another scenario

- .github/workflows/javascript-unit-tests.yml
- .github/workflows/typescript-compilation.yml
Adds Typescript type checking and compilation to Github Actions so we have better confidence in the type safety of every PR.
No difference.
- Github Action was added
Fixes: https://github.com/SUSE/spacewalk/issues/13502
> Add Typescript compilation & type checking to Github Actions

- java/buildconf/ivy/ivy-suse.xml
This patch updates the jade4j library and initially pulls it from [my OBS home repository](https://build.opensuse.org/project/show/home:j_renner:branches:systemsmanagement:Uyuni:Master:Other) for CI testing. When the updated library has been submitted to [the official Uyuni OBS project](https://build.opensuse.org/project/show/systemsmanagement:Uyuni:Master:Other) it will be resolved from there.
Version 1.2.5 is the jade4j version that is used for [the latest release of spark-template-jade](https://github.com/perwendel/spark-template-engines/blob/master/spark-template-jade/pom.xml#L36).
No difference.
- No documentation needed, everything should behave exactly as before.
- No tests needed, everything should behave exactly as before.
Fixes https://github.com/SUSE/spacewalk/issues/13283 …
> Update the jade4j library (1.0.7 -> 1.2.5)

- backend/server/importlib/packageImport.py
- backend/spacewalk-backend.changes
The table in the database to store the changelog has a varchar column of
128 to store the author name. Thus, the sync fails if, for some reason,
the author name has more chars. This commits changes the code to truncate
the author name in 128 chars.
Before:
Changelog author was not truncate. Allowing name with more than 128 chars
After:
The changelog author is truncated in 128 chars
Fixes https://github.com/SUSE/spacewalk/issues/13541 …
> Truncate author name in the changelog

- java/code/src/com/redhat/rhn/manager/audit/CVEAuditManager.java
- java/code/src/com/redhat/rhn/manager/audit/test/CVEAuditManagerTest.java
- java/code/src/com/redhat/rhn/testing/ErrataTestUtils.java
- java/spacewalk-java.changes
The specific CVE audit query `list_systems_by_patch_status` and `list_images_by_patch_status` merges server package data from both affected and non-affected systems. If the system is not affected, all the package related data (including EVR) is filled with nulls. But since epoch is a non-mandatory field, it can be null in both cases.
With the recent update to `PackageEvr`, the code assumes that an epoch is always present in an EVR, and ignores the rest of it if it is not. This causes an NPE down the line.
This fix checks the version to determine if we have an EVR instead.
Fixes: https://bugzilla.suse.com/1180893
Fixes: bugzilla.suse.com/1180893
To be ported to Manager-4.1, Manager-4.0
If you need …
> Fix: CVE audit results for affected and patched entries (bsc#1180893)

- testsuite/features/qam/reposync/srv_sync_qam_products.feature
Fixing a typo calling a step definition when syncing our QAM products
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13662
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/13661
> QAM: Fixing step def. typo on RES8 product sync

- .github/workflows/javascript-lint.yml
Add Javascript lint to Github Actions, tested on my own fork and works as expected.
Once this gets merged, it would make sense to remove the corresponding job from Jenkins for Uyuni, I'm not familiar with the process for that.
No difference.
- No tests: linter integration.
Fixes: https://github.com/SUSE/spacewalk/issues/13403
> Add Javascript lint to Github Actions

- web/html/src/manager/content-management/shared/components/panels/sources/channels/channels-selection.js
- web/spacewalk-web.changes
Fix JS type check in CLM project form
> Fix JS type check in CLM project form

- susemanager-sync-data/additional_products.json
- susemanager-sync-data/susemanager-sync-data.changes
CentOS 6 is EOL and the mirror list was removed. Change the URLs to vault.centos.org
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13615
Tracks https://github.com/SUSE/spacewalk/pull/13671 https://github.com/SUSE/spacewalk/pull/13672
> Change centos6 urls

- utils/spacewalk-common-channels
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Repository URLs must be unique inside of an org. When different channels use the same repository url this lead into
an error in spacewalk-common-channels.
This PR query existing repository URLs and re-use repositories if they already exists.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/12008
Tracks
> Reuse repos for common channels

- java/code/src/com/redhat/rhn/common/validator/ValidatorResult.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/validation/ContentPropertiesValidator.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/EnvironmentApiController.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/FilterApiController.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectApiController.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ValidationUtils.java
- java/code/src/com/suse/manager/webui/utils/gson/ResultJson.java
- java/spacewalk-java.changes
- web/html/src/components/input/Form.js
- web/html/src/components/input/InputBase.js
- web/html/src/components/panels/CreatorPanel.js
- web/html/src/manager/content-management/create-project/create-project.js
- web/html/src/manager/content-management/list-filters/appstreams/select-input.js
- web/html/src/manager/content-management/list-filters/filter-edit.js
- web/html/src/manager/content-management/list-filters/filter-form.js
- web/html/src/manager/content-management/project/project.js
- web/html/src/manager/content-management/shared/api/use-lifecycle-actions-api.js
- web/html/src/manager/content-management/shared/components/panels/build/build.js
- web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-form.js
- web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-lifecycle.js
- web/html/src/manager/content-management/shared/components/panels/filters-project/filters-project.js
- web/html/src/manager/content-management/shared/components/panels/promote/promote.js
- web/html/src/manager/content-management/shared/components/panels/properties/properties-create.js
- web/html/src/manager/content-management/shared/components/panels/properties/properties-edit.js
- web/html/src/manager/content-management/shared/components/panels/properties/properties-form.js
- web/html/src/manager/content-management/shared/components/panels/sources/sources.js
This PR introduces the infrastructure to implement and display server-side validation errors at the field-level.
This PR also makes usage of that infrastructure on `Content LifeCycle Management` forms, which can be used as an example (separate commits for easier review).
A new `errors` field was added to the response format, to represent **field-level input errors**, see the following example:
```
{
"success":false,
"messages":[
"Global message will be shown in a popup"
],
"errors":{
"filter_name":[
"Field-level error message that will be displayed next to the 'filter_name' input"
]
},
"data":null
}
```
Those new "field errors" can be added via `addFieldError`:
```
ValidatorResult result = new ValidatorResult();
result.addFieldError(<field_name>, <message_key>);
```
Note that the way we …
> Server side field-level validations infrastructure (and usage on CLM)

- backend/satellite_tools/repo_plugins/Makefile
- backend/satellite_tools/repo_plugins/yum_dnf_src.py
- backend/satellite_tools/repo_plugins/yum_src.py
- backend/satellite_tools/reposync.py
- backend/spacewalk-backend.changes
- backend/spacewalk-backend.spec
- Parameterised apache owners in `backend/satellite_tools/reposync.py` and `backend/satellite_tools/repo_plugins/yum_src.py`
- Forcing URLGrabber version < 4 (see #3113).
- Added yum_dnf_src plugin.
Working features:
- Basic reposync (i.e. CentOS8 and SUSE Leap repositories)
Not implemented features:
- `ContentSource` Options: `insecure` and `interactive` are ignored.
- Creating kickstartable tree fails (see #3134).
- Test cases (see section test cases below).
Unverified features:
- Proxy
- HTTP Headers
- Not all expected features have been tested.
- Some of the functionality might still need alignment (additional logic, correct folder locations,...)
No difference.
- No tests: As the dnf module requires an actual repository to load, this …
> reposync: Add yum_dnf_src plugin.

- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/step_definitions/common_steps.rb
Without this patch, the testsuite is going to always fail because there was the field label added. Accordingly, <promote> buttons aren't dev_name-* or qa_name-* anymore, but dev_label-* and qa_label-*.
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/13647 
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13642 
> Changing xpath for "promote" button in common_steps

- testsuite/features/qam/reposync/srv_sync_qam_products.feature
Related card: https://github.com/SUSE/spacewalk/issues/11333
This PR fixes the issue of syncing LTSS channels, as they are not available as sub-products on the WebUI, but just as optional channels. So they must be synced from a console command.
@paususe @mcalmer should we consider this an enhancement in our WebUI?
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QAM: LTSS updates channel can't be synced from the WebUI

- testsuite/features/qam/reposync/srv_sync_qam_products.feature
Related card https://github.com/SUSE/spacewalk/issues/13372
Synchronize Ubuntu 20.04 at QAM environment
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QAM: Add Ubuntu 20.04 product sync

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/900-centos6-vault.sql
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Update CentOS6 URLs to use vault.centos.org. Required after CentOS6 EoL, as it's not available anymore at mirrorlist.centos.org
After applying the SQL script:
```
| External - Uyuni Client Tools for CentOS 6 (i386)               | N               | 2021-01-18 13:13:57.288531+01 | 2021-01-18 13:13:57.288531+01
537 |      1 |     500 | https://vault.centos.org/centos/6/os/i386/                                                                                                                                                                                                           
| External - CentOS 6 (i386)                                      | N               | 2021-01-18 13:13:56.899931+01 | 2021-01-18 13:13:56.899931+01
538 |      1 |     500 | …
```
> Update CentOS6 URLs to use vault.centos.org

- java/code/src/com/suse/manager/webui/controllers/SSOController.java
- java/code/src/com/suse/manager/webui/controllers/login/LoginController.java
- java/code/src/com/suse/manager/webui/controllers/test/LoginControllerTest.java
- java/spacewalk-java.changes
Some variables needed for rendering the Jade login template were added after the introduction of SSO (e.g. `webTheme`).
Back in the day, the needed variables for SSO were only in `SparkApplicationHelper`. Now, login with SSO gets an ISE because the
Jade compiler cannot find model variables that were added.
This PR unifies the code path for non-SSO and SSO fixes the problem above while also unifies the code paths for non-SSO and SSO to
avoid the problem in the future.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1181048
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13680
Tracks https://github.com/SUSE/spacewalk/pull/13688 …
> Fix: login gets an ISE when SSO is enabled (bsc#1181048)

- backend/satellite_tools/reposync.py
- backend/spacewalk-backend.changes
- java/code/src/com/redhat/rhn/domain/channel/Channel.java
- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/redhat/rhn/domain/channel/RepoMetadata.hbm.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
- java/code/src/com/redhat/rhn/manager/channel/CloneChannelCommand.java
- java/code/src/com/redhat/rhn/manager/channel/test/CloneChannelCommandTest.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerChannelAlignmentTest.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/ModularDataCleanup.java
- java/spacewalk-java.changes
- schema/spacewalk/common/data/rhnTaskoTask.sql
- schema/spacewalk/common/data/rhnTaskoTemplate.sql
- schema/spacewalk/upgrade/susemanager-schema-4.2.2-to-susemanager-schema-4.2.3/210-channel-modular-data-cleaunp-job.sql
- utils/spacewalk-manage-channel-lifecycle
- utils/spacewalk-utils.changes
The modular metadata (`modules.yaml`) is shared between cloned channels: Whenever we clone a channel, we skip cloning the metadata and instead serve it from the original when requested from clients (`DownloadFile`, `DownloadController`).
With this approach, the following scenario is problematic:
- we sync a vendor channel `A`
- we clone it into `B`
- next day, the vendor channel `A` receives new modular metadata, so we update it
- when a client requests modular metadata for the *clone* `B`, it gets metadata for `A`
- this is a problem since:
- the new modular information doesn't need to be correct for the clone
- (and mainly) the checksum of the `modules.yaml` in the `repomd.xml` of `B` is not matching the new `modules.yaml`, thus leading to `dnf` errors
The fix is in 2 places:
- …
> Fix modular data handling for cloned channels

- testsuite/features/qam/reposync/srv_sync_qam_products.feature
On RES8 product, SCC removed the architecture from the description text.
This caused a problem matching with the step written for that purpose in our test suite.
This PR get rid of the architecture text from the description text.
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13695
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/13696
> QAM: Fix selection of RES8 product in Product Wizard

- testsuite/features/step_definitions/salt_steps.rb
This is a port of https://github.com/SUSE/spacewalk/pull/13714
> added zypper refresh before zypper in

- java/code/src/com/redhat/rhn/frontend/action/configuration/files/FileDetailsAction.java
- java/code/src/com/redhat/rhn/frontend/dto/ConfigRevisionDto.java
- java/code/webapp/WEB-INF/pages/common/fragments/configuration/files/details.jspf
- java/code/webapp/WEB-INF/pages/configuration/files/comparerevision.jsp
- java/code/webapp/WEB-INF/pages/configuration/files/manage.jsp
- java/spacewalk-java.changes
Relative times should have a tooltip with the absolute time value.
Those tooltips were missing on configuration files.
Before:
---
---
After:
---
---
- No documentation needed: We are only adding a missing tooltip
- No tests: we are not testing tooltips
Fixes: https://github.com/uyuni-project/uyuni/issues/2803
Fixes: https://github.com/SUSE/spacewalk/issues/13082
> Display absolute timestamps for configuration files

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
Localization message `erratalist.jsp.noerrata` was duplicated, as reported in logs:
```
2021-01-20 15:32:14,855 [main] WARN  com.redhat.rhn.common.localization.XmlResourceBundleParser - Duplicate message key found in XML Resource file: erratalist.jsp.noerrata
```
This PR removes the duplicate message key.
No difference.
- No documentation needed: Not visible to the end-user
- No tests: Just removing a duplicate message key
No open issue
> Remove duplicate localization message key

- web/spacewalk-web.changes
- web/spacewalk-web.spec
Added build requirements for node.
No difference.
- No documentation needed: No changes
- No tests: Tested during package build process.
Build of CentOS 8 verified. Leap 15.2 not due to test system issues.
> Updated 'node' requirements.

- web/spacewalk-web.changes
Fixes the discussion here: https://github.com/uyuni-project/uyuni/pull/3143#discussion_r560040254
No difference.
Fixes: https://github.com/uyuni-project/uyuni/pull/3143#discussion_r560040254
> Revert node changelog entries

- backend/satellite_tools/repo_plugins/yum_src.py
- backend/satellite_tools/reposync.py
- backend/spacewalk-backend.changes
- Fixed kickstart download path (just.adding repo url if no protocol is included).
- Fixed an URLGrabber error handling class.
No difference.
- No tests: 
Fixes #3134 #2583 
> Fixed Kickstart and URLGrabber error handling.

- .github/workflows/javascript-build.yml
Add the frontend application build step to Github Actions, with this change we should be 100% on par with everything that used to run in Jenkins on PRs.
No difference.
Fixes: https://github.com/SUSE/spacewalk/issues/13703
> Add Javascript build to Github Actions

- susemanager-frontend/susemanager-nodejs-sdk-devel/package.json
- susemanager-frontend/yarn.lock
- web/html/src/.babelrc
- web/html/src/manager/admin/config/monitoring-admin.js
- web/html/src/manager/clusters/index.js
- web/html/src/manager/content-management/index.js
- web/html/src/manager/content-management/shared/components/panels/sources/channels/channels-selection.js
- web/html/src/manager/index.js
- web/html/src/manager/virtualization/ListTab.js
- web/html/src/manager/virtualization/pools/list/pools-list.js
- web/html/src/manager/visualization/data-tree.js
- web/html/src/manager/visualization/hierarchy.js
- web/html/src/manager/visualization/ui/hierarchy-view.js
- web/html/src/manager/visualization/utils.js
- web/html/src/utils/test-utils/setup.js
Fix build issues as shown in https://ci.nue.suse.com/view/Manager/view/Manager-Head/job/manager-Head-2obs/23381/console
Hardcoding the `.js` extension is unnecessary and breaks when we have Typescript files as well. Also add optional chaining for production.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13730
> Fix incorrect import paths, add missing Babel plugin

- testsuite/features/secondary/min_centos_openscap_audit.feature
Use the right client for this feature.
- testsuite/features/secondary/min_centos_openscap_audit.feature:
Replace "sle_minion" with "ceos_minion" in the first scenario.
It fixes https://github.com/uyuni-project/uyuni/pull/2894
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13728
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13729
> Testsuite: Use the right client for this feature

- utils/spacewalk-common-channels
- utils/spacewalk-utils.changes
spacewalk-common-channels:
The arch name is sometimes written a bit exotic. Translate it to a more normal string compartible with the values used in the config file
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/2838
> Fix arch in spacewalk common channels

- utils/spacewalk-common-channels.ini
Fixes:
- wrong use of %(arch) macro
- missing arch in channel names for multi arch channel definitions 
No difference.
> fix arch macro and missing arch definition in channel names

- web/html/src/manager/content-management/shared/components/panels/sources/channels/channels-selection.js
The cucumber steps handling select fields need to have an id on the
`ReactSelect` component to tell those apart from regular select
components. Add it in the `selectedBaseChannel` since that one is not
using our `Select` wrapper component.
No difference.
- No documentation needed: no UI diff
- No tests: fixes cucumber tests
Fixes #
> Add id to selectedBaseChannel Select for testability

- java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
- java/spacewalk-java.changes
Fixes a query that still used the old EVR_T constructor syntax
No difference.
- No tests:
Fixes https://github.com/SUSE/spacewalk/issues/13770
> fix query using old EVR_T constructor (bsc#1181422)

- testsuite/features/step_definitions/datepicker_steps.rb
It fixes failures on install a package with staging, i.e., the features:
`Install a package on the Ubuntu minion with staging enabled`
`min_salt_install_with_staging.feature`
- testsuite/features/step_definitions/datepicker_steps.rb:
Ensure the timepicker is present before manipulate it.
- Manager-3.2: https://github.com/SUSE/spacewalk/pull/13795
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13794
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13793
> Testsuite: Fix install packages with staging

- java/code/src/com/redhat/rhn/domain/action/script/ScriptRunAction.java
- java/spacewalk-java.changes
When clicking `view/download raw script output` in a remote command
execution event summary it links to the SSM Overview Remote command tab.
instead it should open a new tab with the raw output to view/download.
No difference.
Before:
After:
Fixes https://github.com/SUSE/spacewalk/issues/13567
> Open raw output in new tab for ScriptRunAction

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/702-debvercmp.sql
Speedup the schema migration by using sub-selects in the cleanup query
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/13810
> use sub selects for EVR cleanup to speedup the query (bsc#1181116)

- web/html/src/manager/systems/ssm/ssm-subscribe-channels.js
- web/html/src/tsconfig.json
- web/html/src/utils/json.test.js
- web/html/src/utils/json.ts
- web/spacewalk-web.changes
Channel subscription via SSM was not sending the `childChannelActions` field in the server request due to the fact that `JSON.stringify` does not convert `Map`fields.
With this PR, channel subscription via SSM will no longer ignore child channels:
A complete list of steps to reproduce the issue can be found in https://bugzilla.suse.com/show_bug.cgi?id=1181520
Before:
After:
- No documentation needed: This is just a bugfix, feature is already documented.
Fixes https://github.com/SUSE/spacewalk/issues/13809 …
> Channel subscription via SSM ignores the child channel

- testsuite/features/secondary/trad_migrate_to_minion.feature
- testsuite/features/secondary/trad_migrate_to_sshminion.feature
We have such errors
```
Feature:Migrate a traditional client into a Salt minion
Scenario:Cleanup: register minion again as traditional client
And I install the traditional stack utils on "sle_client"
FAIL: zypper --non-interactive install -y spacewalk-client-tools spacewalk-check spacewalk-client-setup 
mgr-daemon mgr-osad mgr-cfg-actions returned 8. output : Loading repository data...
(...)
File './noarch/python3-spacewalk-client-tools-4.1.8-411.2.13.devel41.noarch.rpm' not found on medium
```
that can happen when the tools are rebuilt while we test.
This PR does a `zypper refresh` (or equivalent) just before reinstalling traditional stack packages.
Ports:
* 4.0: SUSE/spacewalk#13791 SUSE/spacewalk#13803
* 4.1: SUSE/spacewalk#13790 SUSE/spacewalk#13802 …
> zypper ref before reinstalling traditional stack packages

- testsuite/Rakefile
- testsuite/features/build_validation/smoke_tests/smoke_tests.template
This PR adds a remote command scenario for the traditional clients of a Build Validation test suite.
Also, it removes a deprecated rake task, as we renamed everything from qam to build_validation, as it's a more generic name that involves Maintenance Updates testing and new major/minor versions testing (which also use Maintenance Incidence mechanism in order to provide the un-released packages)
No difference.
Ports:
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13778
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13777 …
> QAM: Implementing remote command for traditional client

- testsuite/features/support/commonlib.rb
Due to a limitation in the size of a repository label, we are forced to truncate the autogenerated label name in our QAM test suite step.
Example:
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/13806
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13805
> Fix: Truncate the repository label to 64 chars

- testsuite/features/build_validation/init_clients/ceos6_client.feature
As we use Sumaform to deploy our environment, and Sumaform change the default repository Centos-Base.repo from the CentOS6 system, as it was deprecated recently, we need to update our scenario to enable the new repositories created from cloud-init thanks to Sumaform.
Related to : https://github.com/SUSE/spacewalk/issues/13658
No difference.
Ports:
- Manager-4.1
- Manager-4.0
> QAM: Renaming CentOS6-Base repositories to enable

- testsuite/features/core/srv_create_activationkey.feature
- testsuite/features/init_clients/min_centos_salt.feature
- testsuite/features/init_clients/min_ubuntu_salt.feature
- testsuite/features/init_clients/sle_client.feature
- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/features/secondary/min_ssh_tunnel.feature
- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minxen_guests.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
- testsuite/features/secondary/srv_manage_activationkey.feature
- testsuite/features/secondary/trad_baremetal_discovery.feature
- testsuite/features/secondary/trad_migrate_to_minion.feature
- testsuite/features/secondary/trad_migrate_to_sshminion.feature
- testsuite/features/secondary/trad_ssh_tunnel.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/xmlrpc_common.rb
- testsuite/run_sets/secondary_parallelizable.yml
Move all scenarios related to activation keys that are not used to set up a client to secondary features.
I took the occasion to rename all testsuite-wide activation keys to `KEY`, and the ones from secondary feature to `TEST`.
I had to remove one scenario from migration features because it was using two keys to check for an old bug.
Ports:
* 4.0: SUSE/spacewalk#13820
* 4.1: SUSE/spacewalk#13818
> Make the core features lighter - activation keys

- client/rhel/yum-rhn-plugin/yum-rhn-plugin.changes
- client/rhel/yum-rhn-plugin/yum-rhn-plugin.spec
Updates SPEC file to build on RHEL8.
No difference.
- No tests: tested during autobuild.
- Build tested successfully for CentOS6+, Fedora 32+, Leap15.2.
> yum-rhn-plugin: Added RHEL8 build.

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/package.py
- spacecmd/src/spacecmd/softwarechannel.py
- spacecmd/tests/test_package.py
This PR fixes an issue that is causing duplicated results when using multiple search criteria on `package_details`, `package_listdependencies`, and `package_listerrata` commands.
This PR also fixes the "advanced search" on the `package_listinstalledsystems` command.
```
server:~ # spacecmd -- package_details name:zypper | grep 'Name:' | wc -l
INFO: Connected to https://server.tf.local/rpc/api as admin
8
server:~ # spacecmd -- package_details name:zypper name:an_invalid_package | grep 'Name:' | wc -l
INFO: Connected to https://server.tf.local/rpc/api as admin
16
```
```
server:~ # spacecmd -- package_details name:zypper | grep 'Name:' | wc -l
INFO: Connected to https://server.tf.local/rpc/api as admin
8
server:~ # spacecmd -- package_details name:zypper name:an_invalid_package | grep …
```
> spacecmd: Fix package details duplicated results

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/package.py
With this PR, all `spacecmd package_*` commands that support **"advanced package search"** will document it on `--help`:
- `package_search`
- `package_details`
- `package_listinstalledsystems`
- `package_listerrata`
- `package_listdependencies`
```
spacecmd {SSM:0}> package_search --help
package_search: Find packages that meet the given criteria
usage: package_search NAME|QUERY
Example: package_search kernel
Advanced Search:
Available Fields: name, epoch, version, release, arch, description, summary
Example: name:kernel AND version:2.6.18 AND -description:devel
-----------------------------------------------------------------------------------------------------------
spacecmd {SSM:0}> package_details --help
package_details: Show the details of a software package
usage: package_details …
```
> spacecmd: Document "advanced search" on package commands that support it

- spacewalk/config/etc/httpd/conf.d/zz-spacewalk-www.conf
- spacewalk/config/spacewalk-config.changes
Improve SSL log information by adding return code value and total time to process (in milis)
Before: 
[29/Jan/2021:22:02:28 +0000] 192.168.122.1 TLSv1.3 TLS_AES_256_GCM_SHA384 "POST /rhn/manager/frontend-log HTTP/1.1" 42 "https://hub-server.tf.local/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
After:
[29/Jan/2021:22:02:28 +0000] 192.168.122.1 TLSv1.3 TLS_AES_256_GCM_SHA384 "POST /rhn/manager/frontend-log HTTP/1.1" 42 "https://hub-server.tf.local/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" 200 T43
No difference.
- No documentation needed: changes in log information
- No tests: changes in log information
Fixes …
> Increase apache ssl log information

- testsuite/features/support/env.rb
- testsuite/features/support/twopence_init.rb
Port of https://github.com/SUSE/spacewalk/pull/13838
No difference.
Fixes #13581
Tracks #https://github.com/SUSE/spacewalk/pull/13838
> Add definition of 15sp2 and 15sp3 to twopence

- java/code/src/com/redhat/rhn/domain/action/ActionChain.hbm.xml
- java/code/src/com/redhat/rhn/domain/action/ActionChain.java
- java/code/src/com/redhat/rhn/domain/action/ActionFactory.java
- java/code/src/com/redhat/rhn/domain/action/ActionStatus.java
- java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemHistoryEventAction.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/schedule/ScheduleHandler.java
- java/code/src/com/redhat/rhn/manager/action/ActionManager.java
- java/code/src/com/redhat/rhn/manager/action/test/ActionManagerTest.java
- java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/manager/webui/utils/salt/custom/ScheduleMetadata.java
- java/code/src/com/suse/manager/webui/websocket/VirtNotifications.java
- schema/spacewalk/common/tables/rhnActionChain.sql
- schema/spacewalk/upgrade/susemanager-schema-4.2.6-to-susemanager-schema-4.2.7/900-actionchaindispatch.sql
This PR adds error handling when the actionchain module `mgractionchains` is not present on a minion. Before this would not complete the actions and only a later cleanup task would set them to failed. Now those actions will be set to failed directly with the proper error message.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/12826
> improved actionchain error handling

- testsuite/features/step_definitions/salt_steps.rb
Ubuntu (16.04, 18.04, and 20.04) uses `salt-common` instead of `salt`.
Ports:
* 4.0: SUSE/spacewalk#13855
* 4.1: SUSE/spacewalk#13854
> Fix Salt package name on Ubuntu

- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes
- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.spec
Switch to use macros for differences between SUSE and RedHat package names.
As some other SUSE packages use `httpd` as provides we require buildservice tricks to get around this.
So let's be explicite in what we really require in this case.
No difference.
> Precise apache dependency

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml
- java/code/src/com/redhat/rhn/manager/rhnpackage/test/PackageManagerTest.java
- java/spacewalk-java.changes
When creating the package list for a system we should only return package ids of packages from channels which are assigned to the system. Otherwise we might show debian 9 package for debian 10 systems.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13772
Tracks https://github.com/SUSE/spacewalk/pull/13866 https://github.com/SUSE/spacewalk/pull/13867
> Fix system pkg listing

- testsuite/features/core/srv_create_activationkey.feature
Fix small side effect of activation keys refactoring
We already test the virtualization enablement in the virtualization tests, no need to have it in core too.
Ports:
* 4.0: SUSE/spacewalk#13884
* 4.1: SUSE/spacewalk#13883
> We test virtualization host enablement elsewhere

- java/code/src/com/suse/manager/reactor/messaging/RegistrationUtils.java
- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/reactor/messaging/test/README.md
- java/code/src/com/suse/manager/reactor/messaging/test/packages.profileupdate.debian.json
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/spacewalk-java.changes
Debian 9/10 were not found as Installed Products. The detection of these products were missing.
No difference.
Before:
After:
Fixes https://github.com/SUSE/spacewalk/issues/13875
Tracks https://github.com/SUSE/spacewalk/pull/13874
> Detect debian products

- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- Don't raise error if we can't disable a tool repo
- Prevent to raise an error if the tool repo can't be disabled
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13873
> QAM: Fix Package States access and prevent to raise an error if the tool repo can't be disabled 

- testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature
Fix: CLM scenario on QAM missed a step to set a label.
Note: CI scenarios are ok, they contain the step already.
No difference.
- No documentation needed 
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13876
> [Port] QAM: CLM scenario needs to set a label text (#13876)

- testsuite/features/build_validation/init_clients/ceos6_client.feature
- testsuite/features/build_validation/init_clients/ceos7_client.feature
Fix CentOS6 repositories filename to be disabled.
Fix how to handle client tools repositories, and not fail the command if doesn't found the repo.
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13871
> QAM: Fix CentOS6 repos, fix tools repos (#13871)

- web/conf/rhn_web.conf
- web/spacewalk-web.changes
Rollback WebUI version to 2021.01
No difference.
- [x ] **DONE**
- Documentation issue was created: Request submitted to @jcayouette on rocket.chat. Willl be ready by the end of the day
- No tests: Just a rollback on the WebUI version
None
> Rollback WebUI version to 2021.01

- testsuite/features/build_validation/init_clients/sle11sp4_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle12sp4_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp1_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp2_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp3_ssh_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/secondary/minssh_bootstrap_xmlrpc.feature
- testsuite/features/step_definitions/common_steps.rb
This PR does two things:
- it removes reference to bsc#1124634. Since this is an INVALID bug, I prefer we do not mention it.
We need this scenario because of the way SUSE products work starting with SLES 15, that's all.
- it moves navigation steps from the ruby implementation to the feature. Rationale:
* makes test suite execution easier to follow (more details)
* it makes reading and understanding of scenario easier
* it makes debugging easier when it fails at one of these steps
* it is better if all our scenarios more or less follow a common pattern
Tested to work in 4.1 branch.
Ports:
* 4.0: SUSE/spacewalk#13894
* 4.1: SUSE/spacewalk#13893
> Do not hide navigation steps in implementation

- testsuite/features/support/env.rb
Get rid of BUILD_VALIDATION env. variable
As both QAM and BV needs a json to provide the MI repos, we have enough by checking the existence of this file, as we did before introducing this variable. This variable was only introduced because I wrongly understood that BVs like Alpha, Betas and GMCs will not have MI repos.
No difference.
Ports:
- Manager-4.1
- Manager-4.0
> QAM: Get rid of BUILD_VALIDATION env. variable

- testsuite/features/profiles/Kiwi/POS_Image-JeOS6_40/config.xml
- testsuite/features/profiles/Kiwi/POS_Image-JeOS6_head/config.xml
PR updates currently used kiwi profiles for SLE12 to SP5.
> Testsuite - updated kiwi profiles

- java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
- java/spacewalk-java.changes
- schema/spacewalk/common/data/rhnServerGroupTypeFeature.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.6-to-susemanager-schema-4.2.7/100-enable-audit-for-salt.sql
Openscap auditing was already working for salt systems in the single system details view.
But it was missing in SSM.
The reason was, that we use different ACLs for testing the capability. We have now added the `ftr_system_audit`
capability to salt entitled systems.
This PR also restrict the audit capability to default salt minions. Salt SSH minions do not get it as openscap auditing will not
work.
No difference.
After:
Fixes https://github.com/SUSE/spacewalk/issues/10253
Tracks https://github.com/SUSE/spacewalk/pull/13895 https://github.com/SUSE/spacewalk/pull/13896 …
> Scap for minions in ssm

- backend/server/handlers/xmlrpc/Makefile
PR https://github.com/uyuni-project/uyuni/pull/3122 removed `abrt` from xmlrpc, but `spacewalk-backend` build was not updated acordingly.
This PR fixes the following issue on OBS:
```
[  235s] make[3]: Entering directory '/home/abuild/rpmbuild/BUILD/spacewalk-backend-git-84.3957aa0/server/handlers/xmlrpc'
[  235s] make[3]: *** No rule to make target 'abrt.py', needed by 'all'.  Stop.
```
No difference.
> Fix spacewalk-backend build after abrt removal

- java/code/src/com/suse/manager/webui/controllers/utils/AbstractMinionBootstrapper.java
- java/code/src/com/suse/manager/webui/controllers/utils/test/RegularMinionBootstrapperTest.java
- java/code/src/com/suse/manager/webui/controllers/utils/test/SSHMinionBootstrapperTest.java
- java/code/src/com/suse/manager/webui/services/pillar/MinionGeneralPillarGenerator.java
- java/code/src/com/suse/manager/webui/services/pillar/test/MinionPillarManagerTest.java
- java/spacewalk-java.changes
Origin server hostname is useful e.g. for setting up monitoring in environments
where Prometheus server is installed on the minion registered on the
proxy. The name _origin server_ always refers to the server where Uyuni server is installed.
Partially fixes https://bugzilla.suse.com/1180439
No difference.
- [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pull/772)
- [Follow-up Documentation PR](https://github.com/uyuni-project/uyuni-docs/pull/797)
Fixes # SUSE/spacewalk#13543
> Add origin server hostname to Salt pillar data (bsc#1180439)

- java/code/src/com/redhat/rhn/common/util/FileUtils.java
- java/spacewalk-java.changes
This PR fixes a race condition that happens on scenarios where there are lot of SSH minions and SSH actions being executed. When the SSH workers from Java are managing SSH actions for minions, involving "salt-ssh", those workers generates the custom roster file to be used and starts the "salt-ssh" subprocess.
When there are lot of actions happening at the same time it might happen that those roster files created by the SSH workers are not yet synced on the filesystem at the time the corresponding "salt-ssh" subprocess tries to read that roster file. If that's the case, the "salt-ssh" can stuck or raise a 500 error:
```
2020-12-05 21:45:00,469 [Thread-10925] ERROR com.redhat.rhn.taskomatic.task.SSHPush - com.suse.salt.netapi.exception.SaltException: Response code: 500 …
```
> Ensure new files are synced just after writing them (bsc#1175660)

- testsuite/features/support/client_stack.rb
This PR fixes get_gpg_key function.
Ports:
* 4.0: SUSE/spacewalk#13918
* 4.1: already done in Kostas' PR.
> Fix get_gpg_key function

- java/buildconf/LICENSE.txt
No difference.
Before:
After:
- [X ] **DONE**
Fixes #
Tracks # **add …
> update license year

- testsuite/features/step_definitions/command_steps.rb
The current sles15sp3o image at the CI doesn't ship `pidof`; use `pgrep`
instead which is available.
- testsuite/features/step_definitions/command_steps.rb:
Replace pidof with pgrep.
- Manager4-.1: https://github.com/SUSE/spacewalk/pull/13923
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13924
> Testsuite: Replace pidof with pgrep

- web/html/src/manager/admin/config/monitoring-admin.tsx
Fix a couple of spelling mistakes in monitoring-admin.js
No difference.
Before:
After:
Fixes #
Tracks # **add downstream PR, if …
> Fix a couple of spelling mistakes in monitoring-admin.js

- backend/common/repo.py
- backend/spacewalk-backend.changes
Checking for `Release` but requesting `InRelease` afterwards is just wrong.
No difference.
Fixes #
Tracks https://github.com/SUSE/spacewalk/pull/13938
> Fix typo in debrepo handling

- backend/server/handlers/xmlrpc/queue.py
- backend/spacewalk-backend.changes
The string conversion was made for python2. With python3 we produce a byte string. Until Postgresql 12 inserting a byte string into a TEXT column just worked and we got a human readable text. But with postgresql 13, it store an ASCII representation of the string.
This PR does the conversion correct using utility function of rhn.i18n.
No difference.
Before:
After:
> Fix action result string format

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Fix bootstrap of JeOS SLE15 clients, as python3-dbus-python and dependencies are not available and do not work.
No difference.
- No tests: QAM testsuite covers it
Fix for https://github.com/SUSE/spacewalk/issues/13951 (master)
Tracks https://github.com/SUSE/spacewalk/pull/13954
> Add python3-dbus-python and dependencies to SLE15 bootstrap repos (bsc#1182071)

- testsuite/features/build_validation/init_clients/ceos6_ssh_minion.feature
- testsuite/features/build_validation/init_clients/ceos7_ssh_minion.feature
- testsuite/features/build_validation/init_clients/ceos8_ssh_minion.feature
- testsuite/features/build_validation/init_clients/disabled/ubuntu2004_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle11sp4_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle12sp4_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp1_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp2_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp3_ssh_minion.feature
- testsuite/features/build_validation/init_clients/ubuntu1604_ssh_minion.feature
- testsuite/features/build_validation/init_clients/ubuntu1804_ssh_minion.feature
- testsuite/features/step_definitions/command_steps.rb
This PR adds a comment about a workaround we do for SSH minions. We import the GPG key manually.
If https://bugzilla.suse.com/show_bug.cgi?id=1181847 is not a bug, but a feature, then this comment will need to be ajusted again in a separate PR.
Ports:
* 4.0: SUSE/spacewalk#13934
* 4.1: SUSE/spacewalk#13933
> Importing GPG keys manually on SSH minion could be a workaround

- testsuite/features/step_definitions/xmlrpc_common.rb
* print contents of chain list for debugging
* remove unused step `there should be no more my action chain`
Ports:
* 4.0:
* 4.1:
> Various test suite debugging helpers

- testsuite/features/secondary/srv_content_lifecycle.feature
In step `And I should see a "Build (4)" text`, the text `Build(6)` appears, because we have two extra channels:
* SLE-Manager-Tools12-BETA-Pool
* SLE-Manager-Tools12-BETA-Updates
This PR adapts the test. It will need to be reverted when we branch to 4.2.
No ports, HEAD only.
> We have 2 BETA channels in HEAD

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Adss bootstrap data for SLE15SP3
No difference.
- No documentation needed: this is an internal change to make sle15sp3 work (fixes an issue, is not a new feature)
- No tests: SLE15SP3 clients can be bootstrapped. I assume this is covered by our current testsuite already.
fixes https://github.com/SUSE/spacewalk/issues/13819
fixes bsc#1182008
> add bootstrap data for SLE 15 SP3 products

- java/code/src/com/redhat/rhn/common/db/datasource/xml/ErrataCache_queries.xml
- java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerChannelAlignmentTest.java
- java/code/src/com/redhat/rhn/manager/errata/cache/UpdateErrataCacheCommand.java
- java/code/src/com/redhat/rhn/manager/errata/cache/test/RetractedPatchesCacheManagerTest.java
- schema/spacewalk/upgrade/susemanager-schema-4.2.5-to-susemanager-schema-4.2.6/013-ignore-retracted-pkgs-in-newest-pkgs-view.sql
Make sure the following caches are aligned correctly when dealing with retracted patches:
- `rhnServerNeeded`
- `rhnChannelNewestPackage`
The changes are also relevant for non-CLM scenarios.
Review commit-by-commit.
TODO
No difference.
- No documentation needed: more or less a bugfix :smile:
> Handle the caches update correctly for retracted patches in CLM

- backend/server/handlers/xmlrpc/queue.py
In rare cases we saw execptions like this:
```
File "/usr/lib/python3.6/site-packages/<CENSORED!>/server/apacheRequest.py", line 135, in call_function
response = func(*params)
File "/usr/share/rhn/server/handlers/xmlrpc/queue.py", line 488, in submit
rmsg = "%s [%s]" % (UnicodeType(message), UnicodeType(rcode))
TypeError: string argument without an encoding
```
Introduced by https://github.com/uyuni-project/uyuni/pull/3252 .
No difference. …
> fix type mapping

- web/html/src/manager/images/image-import.tsx
This PR fixes all `no-useless-concat` eslint warnings.
**Before**
```
$ yarn lint
...
warning: Unexpected string concatenation of literals (no-useless-concat) at manager/images/image-import.tsx:271:63:
...
42 warnings found.
```
**After**
```
$ yarn lint
...
41 warnings found.
```
No difference.
> eslint: Unexpected string concatenation of literals (no-useless-concat)

- client/rhel/rhnlib/rhn/SSL.py
- client/rhel/rhnlib/rhn/connections.py
- client/rhel/rhnlib/rhnlib.changes
- client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes
- client/rhel/spacewalk-client-tools/src/bin/rhn_check.py
- client/rhel/spacewalk-client-tools/src/up2date_client/rhncli.py
- client/rhel/spacewalk-client-tools/src/up2date_client/rhnregGui.py
- client/rhel/spacewalk-client-tools/src/up2date_client/rhnserver.py
- client/tools/mgr-osad/mgr-osad.changes
- client/tools/mgr-osad/mgr-osad.spec
- client/tools/mgr-osad/src/jabber_lib.py
- proxy/installer/rhn-proxy-activate.py
- proxy/installer/spacewalk-proxy-installer.changes
- proxy/proxy/rhnProxyAuth.py
- proxy/proxy/spacewalk-proxy.changes
Change rhnlib SSL implementation to use python ssl instead of pyOpenSSL. This brings us better SAN support and
better hostname matching during SSL handshake.
No difference.
Issue: https://github.com/SUSE/spacewalk/issues/13902
Tracks https://github.com/SUSE/spacewalk/pull/13988 https://github.com/SUSE/spacewalk/pull/13989
> Traditional stack change ssl implementation

- client/rhel/spacewalk-client-tools/spacewalk-client-tools.spec
- client/tools/mgr-osad/mgr-osad.spec
- proxy/proxy/spacewalk-proxy.spec
Adapts the three packages to the new rhnlib version that will include the changes for the ssl implementation from #3250
No difference.
No tests: Media install tests will test the change.
Related: https://github.com/SUSE/spacewalk/issues/13902
Tracks: https://github.com/SUSE/spacewalk/pull/13994 and https://github.com/SUSE/spacewalk/pull/13996
> Require the next rhnlib version that will come after #3250 is merged

- web/html/src/TYPESCRIPT_MIGRATION.md
Cherry-pick Typescript migration docs update.  
This is already present in a larger PR, but if anyone wants to start working with Typescript today, would be nice to have this information large and center.
No difference.
> Cherry-pick migration doc update

- web/html/src/components/panels/CreatorPanel.js
- web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-lifecycle.js
- web/html/src/manager/content-management/shared/components/panels/properties/properties-edit.js
- web/spacewalk-web.changes
On CLM, use the `edit` icon for editing and the `add` icon for adding, instead of always using the `add` icon.
No difference.
Before:
After:
- No documentation needed: Just changing an icon
- No tests: Not applicable 
> Usage of "edit" icon on Content Lifecycle Management

- testsuite/features/secondary/min_centos_openscap_audit.feature
- testsuite/features/secondary/min_salt_openscap_audit.feature
- testsuite/features/secondary/min_ubuntu_openscap_audit.feature
- testsuite/features/secondary/trad_openscap_audit.feature
- testsuite/features/step_definitions/command_steps.rb
This PR makes sure to zypper ref before we install openscap packages, in order to avoid:
```
And I install OpenSCAP dependencies on "sle_client" 
(...)
Media source 'http://download.suse.de/ibs/Devel:/Galaxy:/Manager:/Head:/SLE15-SUSE-Manager-Tools/images/repo/SLE-15-Manager-Tools-POOL-x86_64-Media1/' does not contain the desired medium
```
It also temporarily adds debugging information to understand why we get:
```
When I refresh packages list via spacecmd on "ubuntu_minion"
And I wait until refresh package list on "ubuntu_minion" is finished
Then spacecmd should show packages "virgo-dummy-1.0" installed on "ubuntu_minion"
package virgo-dummy-1.0 is not installed (RuntimeError)
```
Ports:
* 4.0:
* 4.1:
> Openscap dependencies metadata

- proxy/proxy-html/spacewalk-proxy-html.spec
Fix `.spec` file based on [build error output](https://build.opensuse.org/package/live_build_log/systemsmanagement:Uyuni:Master/spacewalk-proxy-html/openSUSE_Leap_15.2/x86_64)
No difference.
- 
- No tests: 
Fixes #
> Fix spec file

- testsuite/features/step_definitions/command_steps.rb
Package installation failed silently. We need to know what happens. Add debug code.
> log package command and result

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Salt 3002.2 requires python3-distro. SLE 15, Ubuntu 20.04, Debian 10 and RES8 do not have python3-distro in the bootstrap repository yet.
No difference.
- No documentation needed: Only ensures Salt 3002 from bootstrap repos is installable
- No tests: Only bootstrap_data was touched, no test needed
> Add python3-distro to bootstrap repo definitions

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/step_definitions/navigation_steps.rb
We were not selecting the system properly from the list when deploying configuration files in a system.
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13914
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/14019
> QAM: Fix the deploy of config files, selecting the system

- web/po/Makefile
Currently, we only generate the po files based on `.js` files, we should however include all of the following file extensions: `.js`, `.jsx`, `.ts`, `.tsx`  
This PR addresses that issue (and also the fact that the makefile couldn't be used on macOS because of the hardcoded paths).
No difference.
Fixes: https://github.com/SUSE/spacewalk/issues/13970
> Add Typescript support to the po makefile

- testsuite/features/build_validation/init_clients/sle11sp4_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle12sp4_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp1_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp2_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp3_ssh_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/secondary/minssh_bootstrap_xmlrpc.feature
- testsuite/features/step_definitions/navigation_steps.rb
In our QAM and BV tests, we have a long list of package states in the table, so we need to first filter by name to be able to remove one of them.
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/14015
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/14018
> Filter by package state name

- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/support/client_stack.rb
This PR refreshes metadata properly:
* CentOS and Ubuntu are not traditional clients anymore, no need to `rhn_check` first
* on all traditional clients, there's no need to `rhn_check` first anyway, this is orthogonal to refreshing metadata
* on Ubuntu and debian, it's `apt_get` and not `yum`
It also removes useless code: `client_is_zypp` would always return `true`, because `$client` always uses `zypper`.
(I think SLE 11 SP3 was using `yum` but that client is long dead and buried :latin_cross: )
Ports:
* 4.0
* 4.1
> Fix metadata steps

- testsuite/features/step_definitions/command_steps.rb
This PR adds more debug info to check package was installed as announced
> Even more debug info

- java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
- java/spacewalk-java.changes
Enhance the SystemHandler  and add more schedule states API calls.
Call Highstate for multiple systems and call an individual list of states for one or multiple systems.
No difference.
- XMLRPC API doc added
> Enhance state api

- java/code/src/com/redhat/rhn/frontend/events/test/SsmPowerManagementActionTest.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerPowerSettingsUpdateCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerSystemCreateCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerVirtualSystemCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/test/CobblerPowerCommandTest.java
- java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
- java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualGuestsController.java
- java/spacewalk-java.changes
When creating a virtual machine cobbler profile, the activation key is
created for the virtualization host since the VM doesn't exist yet.
In order to avoid the VM to be registered as a reactivation of its host,
don't generate the reactivation key.
No difference.
> VM Autoinstallation: don't create re-activation key

- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_40/config.xml
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_41/config.sh
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_41/config.xml
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_41/images.sh
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_41/root/etc/multipath.conf
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_41/root/etc/sysconfig/bootloader
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_41/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_41/root/etc/systemd/system/install-local-bootloader.service
- testsuite/features/support/commonlib.rb
PR updates kiwi profile for head and creates separate profile used for 4.1 and 4.0 testsuite.
JeOS7 template for SLE15SP3 was tested and proved to be working.
https://github.com/SUSE/spacewalk/issues/13655
> Testsuite - add new testsuite profile for kiwi images

- backend/server/rhnVirtualization.py
- backend/spacewalk-backend.changes
- java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
- java/code/src/com/redhat/rhn/domain/server/VirtualInstance.java
- java/code/src/com/redhat/rhn/domain/server/VirtualInstanceInfo.hbm.xml
- java/code/src/com/redhat/rhn/domain/server/VirtualInstanceInfo.java
- java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java
- java/code/src/com/suse/manager/reactor/messaging/LibvirtEngineDomainLifecycleMessageAction.java
- java/code/src/com/suse/manager/reactor/messaging/test/LibvirtEngineDomainLifecycleMessageActionTest.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/virtualization/VirtManagerSalt.java
- java/code/src/com/suse/manager/virtualization/test/VirtManagerSaltTest.java
- java/spacewalk-java.changes
- schema/spacewalk/common/tables/rhnVirtualInstanceInfo.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.7-to-susemanager-schema-4.2.8/001-rename-memory-size.sql
- web/html/src/manager/virtualization/guests/list/guests-list.js
Displaying the memory amount of a VM in the virtualization page is fine... as long as the VM is not registered as a system. The fun comes when registering the VM because Uyuni gets a different memory amount coming from the guest OS during the hardware update.
In order to always display the memory amount allocated on the host, the virtualization page now gets the memory value from `salt.vm_info`.
No difference.
- No documentation needed: displayed value fix
Fixes # …
> VM memory display fix

- branding/css/tables.less
- web/html/src/.eslintrc.js
- web/html/src/components/dialog/ModalLink.tsx
- web/html/src/components/panels/CreatorPanel.tsx
- web/html/src/components/table/Header.tsx
- web/html/src/components/table/SearchPanel.tsx
- web/html/src/manager/clusters/cluster/cluster-overview.tsx
- web/html/src/manager/content-management/list-filters/appstreams/appstreams.js
- web/html/src/manager/content-management/list-filters/filter-edit.tsx
This PR fixes all `anchor-is-valid` eslint warnings.
**Before**
```
$ yarn lint
...
warning: The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md (jsx-a11y/anchor-is-valid) at components/table/Header.tsx:44:9:
...
42 warnings found.
```
**After**
```
$ yarn lint
...
37 warnings found.
```
Learn more: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md
No difference.
- No tests: already …
> eslint: The href attribute requires a valid value to be accessible (anchor-is-valid)

- java/code/src/com/redhat/rhn/frontend/action/user/CreateUserAction.java
- java/code/src/com/redhat/rhn/manager/user/CreateUserCommand.java
- java/spacewalk-java.changes
This fixes an issue when creating a user with pam authentication where no password is provided. In this case there will be a dummy password generated to get though struts from validation. Later There is again validation checking the password against the configured requirements. This validation can fail since the dummy password is a constant length hash that won't always fit the configured requirements. This fix disabled the seconds password requirements validation for said dummy password but keeps it in place for all other cases.
No difference.
- No tests
Fixes #https://github.com/SUSE/spacewalk/issues/13355 …
> disable password validation on user creation with empty password and pam enabled. (bsc#1179579)

- susemanager-utils/susemanager-sls/salt/channels/channels.repo
- susemanager-utils/susemanager-sls/salt/channels/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Ubuntu 18.04 has an initial version of apt which does not support auth.conf.d directory. 
The first working version seems to be 1.6.10.
Check the apt version to decide whenever we want to use the feature or not.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/3281
Tracks 
> Detect working apt with auth.conf.d

- proxy/proxy-html/spacewalk-proxy-html.spec
Final fix for `spacewalk-proxy-html.spec`. Build tested on both SUSE-Manager and Uyuni build service environment.
No difference.
- No tests:
Fixes #
> Master modernize proxy homepage

- testsuite/documentation/cucumber-steps.md
- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/secondary/trad_cve_audit.feature
- testsuite/features/step_definitions/navigation_steps.rb
On top of:
* Fix the deploy of config files, selecting the system #3289
* Filter by package state name #3227 
this PR:
* restores the step `I enter "..." as the filtered system name` which was destroyed by accident
* avoids using series of steps in step definitions (clarity of feature, easier debugging)
* removes duplicated step `I check the row with the "..." hostname`
Ports:
* 4.0: SUSE/spacewalk#14031
* 4.1: SUSE/spacewalk#14032
> Filtered systems and packages

- testsuite/features/step_definitions/command_steps.rb
This PR reverts output added to test suite for debugging purposes.
It also changes `code` to `_code` for unused return codes.
HEAD only.
> Revert added debug output

- testsuite/features/step_definitions/command_steps.rb
Use the latest `tftpboot-installation` package: it seems this could be the reason of the failure seen when installing the VM.
No difference.
- No documentation needed: test fix
> testsuite: use the latest tftpboot-installation package

- testsuite/features/step_definitions/command_steps.rb
PR fixes the way package list refresh is handled by `spacecmd` in testsuite. 
We need to wait for all package refreshes to be completed.
> Testsuite - fix of package refresh by spacecmd

- testsuite/features/step_definitions/common_steps.rb
https://github.com/uyuni-project/uyuni/pull/3282 changed a href into a button and we match with an xpath on it.
Adapt to let the test work again.
No difference.
> href was changed to a button

- testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature
- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/secondary/trad_cve_audit.feature
Found more links which changed into buttons in PR https://github.com/uyuni-project/uyuni/pull/3282
I wonder if this was really a good idea to do it.
@ricardoasmarques @ncounter @Etheryte - I wonder if this was intended or we we better rollback this change?
See examples below
The column header texts are not links anymore, but buttons.:
Here the right side actions `Attach/Detach Sources`, `Attach/Detach Filter`, etc are now also buttons: …
> more links changed to buttons

- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_40/config.xml
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_head/config.xml
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_40/config.xml
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_41/config.sh
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_41/config.xml
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_41/images.sh
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_41/root/etc/multipath.conf
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_41/root/etc/sysconfig/bootloader
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_41/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_41/root/etc/systemd/system/install-local-bootloader.service
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_40/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_head/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_40/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_41/config.sh
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_41/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_41/images.sh
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_41/root/etc/multipath.conf
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_41/root/etc/sysconfig/bootloader
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_41/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_41/root/etc/systemd/system/install-local-bootloader.service
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_head/config.xml
PR https://github.com/uyuni-project/uyuni/pull/3260 added a new Kiwi profile description for SUMA 4.1, but forgot to generate them for the special environments.
This PR fix this problem
No difference.
> Generate new kiwi image profiles

- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
Even when specified `List<Long>` as input parameter, redstone XMLRPC lib give us `XmlRpcArray<Integer>`.
`containsAll` or `removeAll` on a Long list does not match.
To fix this, we have to specify `List<Integer>` as input parameter and convert it to `List<Long>` .
Bug introduced with https://github.com/uyuni-project/uyuni/pull/3234
No difference.
> XMLRPC does not know Long and comparing long with int result into errors

- susemanager-frontend/susemanager-nodejs-sdk-devel/susemanager-nodejs-sdk-devel.changes
- susemanager-frontend/susemanager-nodejs-sdk-devel/susemanager-nodejs-sdk-devel.spec
- web/spacewalk-web.spec
That package has about 40000 files in the node_modules folder, and it takes about 1.5h for rpmbuild to go over them on most IBS / OBS workers.
The speedup idea is to reduce the number of files by grouping them in an archive. That archive is then uncompressed when building the `spacewalk-web` package where it is actually used.
No difference.
- No documentation needed: rpm build speedup
- No tests:  rpm build speedup
> Speed up susemanager-nodejs-sdk-devel RPM build

- web/html/src/components/datetimepicker.tsx
- web/html/src/components/formulas/FormulaComponentGenerator.tsx
This PR removes unused variables in frontend code, which reduces the number of `eslint` warnings.
No difference.
> Remove unused variables in frontend code

- web/html/src/components/formula-selection.tsx
In https://github.com/uyuni-project/uyuni/pull/3242, I introduced a regression in the checkbox logic in formula selection: https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-master-cucumber-NUE/1223/testReport/(root)/Setup%20SUSE%20Manager%20for%20Retail%20branch%20network/Enable_the_branch_network_formulas_on_the_branch_server/
Essentially, the problem boils down to the existing code relying on `"1" == 1` in non-strict Javascript.  
This PR fixes the problem.
Before: checkbox not checking
After: checkbox checking …
> Fix bugged checkbox in formula-selection

- web/html/src/manager/systems/bootstrap/bootstrap-minions.js
- web/spacewalk-web.changes
Files generated on M$ Windows can contain these line terminators.
No difference.
bugfix
- No tests
https://github.com/SUSE/spacewalk/issues/14090
> Replace CRLF in ssh priv key when bootstrapping (bsc#1182685)

- backend/server/repomd/view.py
- backend/spacewalk-backend.changes
This is related to serving comps.xml and modules.yaml files to
traditional clients. If the files weren't opened in the binary mode,
yum/dnf on clients was not working correctly (yum on CentOS7 was failing
silently, dnf on RHEL8 reported an error) and the following line appeared in
the SUMA apache error log, when client tried to download the file:
`TypeError: file like object yielded non string type`
Fixed by opening the files as binary. Then I noticed, we do this for the cached
files already (see db7f3a9f26141a3f27e17c8d0afd88b9fe851bf3).
No difference.
bugfix
No tests here AFAIK
Tracks https://github.com/SUSE/spacewalk/issues/11926 …
> Open repomd files as binary (bsc#1173893)

- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/step_definitions/salt_steps.rb
Ensure we use the latest Salt version available after the SP migration.
After the SP migration, the Salt version installed in the
SLE minion is the one from SCC; instead, we want to
test the latest Salt version available.
- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
Install the latest Salt version in the SP migrated minion.
Combine the two steps checking the result of the SP migration in just one.
- testsuite/features/step_definitions/salt_steps.rb: Step definitions.
Fixes https://github.com/SUSE/spacewalk/issues/14030
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/14051
and https://github.com/SUSE/spacewalk/pull/14078 …
> Testsuite: Ensure we get the lastest Salt after SP migration

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
Reactivation key can now be set in bootstrap script or passed as
environmental variable to the script.
Reactivation key is saved as `management_key` in susemanager.conf.
No difference.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/13942
Fixes https://github.com/SUSE/spacewalk/issues/13958 …
> Add reactivation key support to bootstrap script

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.7-to-susemanager-schema-4.2.8/500-rhnbuild-version.sql
The field 'version' in rhnActionImageBuild is a VARCHAR(128)
Initially, the field was called 'tag' and it was a VARCHAR(30).
Then the field was changed to a VARCHAR(128) in:
https://github.com/SUSE/spacewalk/commit/26e579530a0c332ef3c3ba04624c2c52b873e2e3#diff-52648bc84fdf1a8d6b28731a95979a144fba64064ffb6a84f7212e5bb541d95eR28
but the migration for this change was missing.
The field is now called 'version'.
> Fix: provide migration for rhnActionImageBuild

- testsuite/features/reposync/srv_sync_channels.feature
- testsuite/features/reposync/srv_sync_products.feature
Change client tools products names to match SCC, related to https://bugzilla.suse.com/show_bug.cgi?id=1152503#c20 and https://github.com/SUSE/spacewalk/issues/14079
No difference.
- No documentation needed: **Changed to match already products in GUI, testsuite changes**
Fixes https://github.com/SUSE/spacewalk/issues/14079
> Change client tools products names in CI to match SCC

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/content/MgrSyncUtils.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
- java/code/src/com/redhat/rhn/manager/content/test/MgrSyncUtilsTest.java
- java/spacewalk-java.changes
To be able to use Uyuni with a local mirror we had to improve the conversion of http URLs to local Files.
This fixes two problems:
1. Ubuntu/Debian URLs which requires multiple subdirs to work. supporting apt-mirror standard config
2. map mirrorlist using query parameters into a path (centos case)
No difference.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/14071
Fixes https://github.com/SUSE/spacewalk/issues/13719
Fixes https://github.com/SUSE/spacewalk/issues/13432
Tracks https://github.com/SUSE/spacewalk/pull/14126 https://github.com/SUSE/spacewalk/pull/14127
If you …
> improve fromdir with better mapping of URL to local files

- client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes
- client/rhel/spacewalk-client-tools/src/up2date_client/up2dateUtils.py
When the product detection failed, the raised exception is swallowed somehow in the deep of python code.
Write a log message that the info does not get lost and the user get a hint what is wrong.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/14136
> Log product detection error

- testsuite/features/step_definitions/salt_steps.rb
Clean up the sumaform repositories for proxy VM deployed with it.
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/14143
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/14144
> QA: Clean up the sumaform repositories for proxy host

- testsuite/features/step_definitions/navigation_steps.rb
Fix a wrongly renamed step definition.
So we keep:
```
When(/^I enter the package for "([^"]*)" as the filtered package name$/) do |host|
step %(I enter "#{PACKAGE_BY_CLIENT[host]}" as the filtered package name)
end
When(/^I enter "([^"]*)" as the filtered package name$/) do |input|
find("input[placeholder='Filter by Package Name: ']").set(input)
end
```
And we have as a new step, for last supported feature, like that:
```
When(/^I enter "([^"]*)" as the filtered package states name$/) do |input|
find("input[placeholder='Search package']").set(input)
end
```
Screenshot of the section called when we use "package name" filter:
Screenshot of the section called when we use "package states name" filter:
No difference.
Ports:
- Manager-4.0 …
> [Port] Fix: Wrong renaming of a step

- testsuite/features/step_definitions/command_steps.rb
Fix how we handle the step to wait that a channel is fully syncronized. 
No difference.
Ports:
- Manager-4.1
- Manager-4.0
> QA: Fix the step to wait the channel sync.

- web/html/src/utils/test-utils/index.js
Fix async issues with the unit test command `type()`.
No difference.
> Update test-utils `type()`

- schema/spacewalk/common/tables/suseCredentials.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.8-to-susemanager-schema-4.2.9/100-password-length.sql
This commit increases the password length for the susecredentials table.
Without this commit, the error of password length overflown in the
database field is happening when using a JWT Token (760 chars) as the
password.
No difference.
Tracks TBD
- [] **DONE**
> Fix: increase password length in the database (bsc#1182687)

- java/code/src/com/redhat/rhn/domain/channel/Channel.hbm.xml
- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/redhat/rhn/domain/channel/test/ChannelFactoryTest.java
- java/code/src/com/redhat/rhn/frontend/action/channel/manage/ChannelPackagesBaseAction.java
- java/spacewalk-java.changes
The `Software > Manage > Channels > $CHANNEL > Packages > Add | Compare` pages were performing many queries for each "Channel"  in the dropdown, each time the `View Packages` button was clicked, which causes a `Request timeout` on environments with many channels.
This PR will obtain all channels (including children), check permissions, and sort in a single query to improve the performance of those pages.
No difference.
Fixes: https://github.com/SUSE/spacewalk/issues/13117 …
> Reduce the number of queries used to obtain the list of channel

- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/salt/channels/debiankeyring.sls
- susemanager-utils/susemanager-sls/salt/channels/gpg-keys.sls
- susemanager-utils/susemanager-sls/salt/channels/init.sls
- susemanager-utils/susemanager-sls/salt/ssh_bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
When bootstrapping salt minions via salt-ssh, we use a different bootstrap state which do not work on GPG keys like the
standard bootstrap state.
This PR extract now the GPG key handling from various files, combine them in a new state file and include it from various places incl. the ssh bootstrap state.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13922
Tracks https://github.com/SUSE/spacewalk/pull/14169 https://github.com/SUSE/spacewalk/pull/14170 …
> Gpg key for ssh minion

- testsuite/features/support/env.rb
It fixes a few environment variable checks.
Terracumber sets them as the strings 'true' or 'false'.
At Ruby, `if 'false'` returns truthy.
- testsuite/features/support/env.rb:
Check explicitely for either 'true' or 'false'.
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/14044
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/14045
> Testsuite: Fix check for env. vars set by terracumber

- backend/satellite_tools/satsync.py
- backend/spacewalk-backend.changes
Opening RPM files in text mode with Python3 can lead to
UnicodeDecodeErrors.
RPMs are now being opened in binary mode instead.
No difference.
https://bugzilla.suse.com/show_bug.cgi?id=1181274
> Opening RPM file in binary mode

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minxen_guests.feature
This is a minor improvement, to avoid log out/log it for each scenario on the Xen tests.
As currently, the step we as starting almost every scenario has implicit the step that logs in.
``` 
Given(/^I am on the "([^"]*)" page of this "([^"]*)"$/) do |page, host|
steps %(
Given I am on the Systems overview page of this "#{host}"
And I follow "#{page}" in the content area
)
end
```
```
Given(/^I am on the Systems overview page of this "([^"]*)"$/) do |host|
system_name = get_system_name(host)
steps %(
Given I am on the Systems page
When I follow "#{system_name}"
And I wait until I see "System Status" text
)
end
``` 
```
Given(/^I am on the Systems page$/) do
steps %(
When I am authorized as "admin" with password "admin"
And I follow the left menu "Systems > Overview"
And I wait until I see …
```
> QA: Avoid log out/log in on every scenario of kvm/xen tests

- java/code/src/com/redhat/rhn/domain/server/Server.java
- java/code/src/com/redhat/rhn/domain/server/ServerFQDN.hbm.xml
- java/code/src/com/redhat/rhn/domain/server/ServerFQDN.java
- java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemHardwareAction.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/NoSuchFQDNException.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
- java/code/webapp/WEB-INF/pages/systems/sdc/hardware.jsp
- java/code/webapp/WEB-INF/struts-config.xml
- java/spacewalk-java.changes
- schema/spacewalk/common/tables/rhnServerFQDN.sql
- schema/spacewalk/postgres/tables/rhnServerFQDN_index.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.8-to-susemanager-schema-4.2.9/701-rhn_server_fqdn.sql
- testsuite/features/secondary/min_salt_minion_details.feature
With this PR, it will now be possible to set/get the primary FQDN of a given system (via WebUI or XMLRPC-API).
**XMLRPC-API**
- The existing `system.getNetworkForSystems` method will now return a new `fqdn` field with the primary FQDN
- A new `system.setPrimaryFqdn` method has been added to set the primary FQDN of a given system
**WEBUI**
- The primary FQDN of a given systems can ve visualized/set via `System > Details > Hardware` page.
**Schema**
- The primary FQDN is stored in a new `is_primary` column on the `rhnServerFqdn` table
Before:
After:
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/13759
Fixes …
> Allow setting system primary FQDN via WebUI or XMLRPC-API

- testsuite/features/reposync/srv_wait_for_reposync.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/env.rb
- testsuite/run_sets/build_validation_reposync.yml
- testsuite/run_sets/refhost.yml
- testsuite/run_sets/reposync.yml
- testsuite/run_sets/virtualization.yml
This PR waits for all reposyncs to finish, even when we are in Build Validation case
Solves SUSE/spacewalk#14055
Ports:
* 4.0: SUSE/spacewalk#14176
* 4.1: SUSE/spacewalk#14175
> Wait for reposync, including in Build Validation

- .github/workflows/update_translations.yml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_bn_IN.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ca.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_cs.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_de.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_es.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_fr.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_gu.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_hi.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_it.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ja.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ko.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_pa.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_pt_BR.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ru.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_sk.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ta.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_uk.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_zh_CN.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_zh_TW.xml
- scripts/translation/update-all-translation-strings.sh
- scripts/translation/xliffmerger.py
This improves multiple things (see the commits one-by-one):
- make xliff merger a bit more silent, when there are no changes
- propagate an error from the xliff merger to the update all translations script
- propagate errors from xliff merger outside of the translation script (error in it should make the automation fail)
- remove the duplicate key in translation files `erratalist.jsp.noerrata` (we might need a validator job to prevent these situations in the future)
- when running the translation automation, cancel all pending runs of it
I've added multiple reviewers, so it'd be enough if you just review the part that belongs to your focus area. …
> Improve translation automation

- susemanager-utils/mgr-libmod/mgr-libmod.changes
- susemanager-utils/mgr-libmod/mgrlibmod/mllib.py
- susemanager-utils/mgr-libmod/tests/data/not_found.json
- susemanager-utils/mgr-libmod/tests/test_libmodapi.py
In `list_modules` output, every `module` dict has a list of `streams` implemented as a Set. Since Set is not serializable, it cannot be output as JSON. This PR changes the type of the `streams` to be a list instead.
See: https://bugzilla.suse.com/1182492
Port of https://github.com/SUSE/spacewalk/pull/14048
> Fix JSON serialization in function 'list_modules' of mgr-libmod (bsc#1182492)

- client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes
- client/rhel/spacewalk-client-tools/src/up2date_client/hardware.py
(review commit-by-commit - there is some small refactoring as well)
We use `python-dmidecode` to get various hardware info on traditional clients. The problem is, that it doesn't behave well on systems that have kernel lockdown feature enabled (i.e. when `Secure boot enabled and kernel locked down` appears in the `dmesg` output).
Whereas current (plain) `dmidecode` works on such systems, `python-dmidecode` does not as it relies on reading `/dev/mem`, which seems to be restricted.
The best solution would be to align `python-dmidecode` to the latest `dmidecode` codebase, but `python-dmidecode` seems to be a inactive project since some years and aligning wourd require too much effort.
Likewise, backporting just the `/dev/mem` from `dmidecode` to `python-dmidecode` doesn't seem to be an …
> Fallback to sysfs when reading info from python-dmidecode fails (bsc#1182603, bsc#1173893)

- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/step_definitions/command_steps.rb
Port of spacewalk PR#
This adds the allow vendor change option to the SP migration cucumber tests for the sle minion + ssh minion. 
No difference.
Before:
After:
- No documentation needed:  
- 
Fixes #
> Add vendor change option to SP migration cucumber tests 

- testsuite/features/core/srv_admin_preferences.feature
- testsuite/run_sets/build_validation_core.yml
- testsuite/run_sets/core.yml
This PR aims to fix a corner case happening when we have more elements in a list than the maximum per page in a list, so if we look for an element hidden on the next page, we must first filter by this element and then look for it.
The improvement, to prevent this extra filter step is to increase the page size by 100.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/14149
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/14184
> QA: Change the default page size

- backend/common/rhnLog.py
- susemanager/etc/logrotate.d/susemanager-tools
- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes
- susemanager/susemanager.spec
* make mgr-create-bootstrap-repo log into a new separate directory /var/log/rhn/mgr-create-bootstrap-repo/ (for reviewers: the directory is created by `rhnLog.initLOG`)
* `log`-rotate those files by day.
NOTE: one minor problem: existing users that upgrade the package will not have the already existing files in /var/log/rhn/mgr-create-bootstrap-repo.* cleaned up.
Reviewers: is cleaning up those files needed? (Maybe in the specfile)
No difference.
- No documentation needed: https://github.com/uyuni-project/uyuni-docs/blob/master/modules/reference/pages/command-line-tools.adoc does not mention log location
- No tests: already covered by Cucumber
Fixes https://github.com/SUSE/spacewalk/issues/12990 …
> Feat: add logrotate conf for mgr-create-bootstrap-repo

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minxen_guests.feature
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/support/env.rb
Hold the browser session (and page) between Cucumber scenarios, but not between Cucumber Features.
Bonus:
This also fixes a problem in XEN/KVM tests, that were opening a graphical console in full-screen mode in a new tab and not taking into account to close the tab, coming back to the previous page before end the scenario. 
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/14188
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/14187 …
> QA: Hold the browser session and page between scenarios

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minxen_guests.feature
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/support/env.rb
Reverts uyuni-project/uyuni#3361
I tried it first, and apparently, it was good, but I was wrong.
I will need to think deeper about this change. It's very disruptive.
Revert this before https://github.com/uyuni-project/uyuni/pull/3371, please
> Revert "QA: Hold the browser session and page between scenarios"

- rel-eng/uyuni-check-version
Evaluate spacewalk-java API versions at uyuni-check-version. That way we'll know when we need to me
No difference.
- [z] **DONE**
- No documentation needed: The script itself is already documented at https://github.com/uyuni-project/uyuni/wiki/Releasing-Uyuni-versions
- No tests: Releasing tools
None
> Evaluate spacewalk-java API versions at uyuni-check-version

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/misc.py
Fixes spacecmd compat with Python3:
```
spacecmd {SSM:0}> report_duplicates
ERROR: 'dict_values' object has no attribute 'count'
```
This is because `dict_values` returns a view - fix is to convert to a list.
Also checked if there were other occurrences of this problem:
```
% rg "return .*\.values()" -l
src/spacecmd/misc.py OK
src/spacecmd/softwarechannel.py OK
```
> Fix: python3 compat

- testsuite/features/reposync/srv_wait_for_reposync.feature
This PR fixes a previous PR where we introduced the `continuous_integration` tag.
Ports:
* 4.0: SUSE/spacewalk#14209
* 4.1: SUSE/spacewalk#14210
> Fix CI cucumber tag

- testsuite/features/step_definitions/command_steps.rb
In the context of Build Validation test suite, do not timeout when reposyncs take a lot of time, as this is expected.
Ports:
* 4.0: SUSE/spacewalk#14231
* 4.1: SUSE/spacewalk#14232
> No timeout for BV reposyncs

- utils/spacewalk-common-channels
- utils/spacewalk-utils.changes
Complete the fix arch handling in spacewalk-common-channels
Without this:
```
uyuni-server:~ # spacewalk-common-channels opensuse_leap15_2-aarch64
SUSE Manager username: admin
SUSE Manager password: 
File "/usr/bin/spacewalk-common-channels", line 347, in <module>
base_info['summary'], CHANNEL_ARCH[base_info['arch']],
KeyError: 'aarch64'
```
With this:
```
uyuni-server:~ # spacewalk-common-channels opensuse_leap15_2-aarch64
SUSE Manager username: admin 
SUSE Manager password: 
uyuni-server:~ # 
```
And the channel and repo gets added, and I am able to launch a reposync
No difference.
- No tests: No arm coverage for now.
Tracks https://github.com/uyuni-project/uyuni/issues/2130 …
> Complete the fix arch handling in spacewalk-common-channels

- java/code/src/com/suse/manager/virtualization/VirtManagerSalt.java
- java/code/src/com/suse/manager/virtualization/test/TestVirtManager.java
- java/code/src/com/suse/manager/virtualization/test/VirtManagerSaltTest.java
- java/code/src/com/suse/manager/virtualization/test/virt.features.json
- java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualNetsController.java
- java/code/src/com/suse/manager/webui/services/iface/VirtManager.java
- java/code/src/com/suse/manager/webui/templates/virtualization/nets/show.jade
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/src/grains/virt.py
- susemanager-utils/susemanager-sls/src/tests/mockery.py
- susemanager-utils/susemanager-sls/src/tests/test_grains_virt.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- web/html/src/manager/virtualization/ListTab.js
- web/html/src/manager/virtualization/nets/list/nets-list.js
- web/html/src/manager/virtualization/nets/list/nets-list.renderer.js
- web/spacewalk-web.changes
Add a warning in the UI if the salt minion doesn't support virtual network creation or editing
Warning in the UI as shown in the screenshot:
- No documentation needed: no need to document a warning
- No cucumber test added, but the warning will help understanding the failures on current Uyuni
> Virt network: add warning if Salt feature is missing

- web/html/src/manager/virtualization/nets/list/nets-list.js
Follow up of PR #3387 improving a warning message
Difference is too tiny to document.
- No documentation needed: message reworded
- No tests: message reworded
> Improve virtual network feature warning message

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/spacewalk-java.changes
Changing logging - better messages and do not spam the logs with a standard configuration.
As we now have to test a lot of URL where it is expected that some are not available we cannot log a "failed" anymore with a warning. Changed this to debug.
No difference.
- No tests: **just logging**
Tracks https://github.com/SUSE/spacewalk/pull/14182
> Accessible better logging

- .github/labeler.yml
Adding some new labels on the GitHub action Labeler.
The main purpose of these new labels is to identify better which part of the product could have an impact due to the PR changes.
No difference.
- No tests
Nothing to be ported to Manager-4.1, until we clarify if we have support for GitHub actions there.
> Adding new labels

- testsuite/features/build_validation/init_clients/sle11sp4_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle12sp4_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp1_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp2_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp3_ssh_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/secondary/minssh_bootstrap_xmlrpc.feature
Sometimes, we try to remove the package too fast, before the package is shown, and it causes that when we iterate through the list of elements in the list, the package still not there.
To avoid it, we will wait for a text during a timeout.
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Make sure that a package state is shown before continue

- testsuite/features/step_definitions/navigation_steps.rb
Speed up select step definition, by using a different method to identify if we have to React component or not, that will not wait default timeout of 10 seconds.
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Speed up select step definition

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
Filter by Non-Critical patches before selecting the first, so we skip Kernel patches.
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Filter by Non-Critical patches before select the first

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Add universe security repositories to spacewalk-common-channels
No difference.
- PR: https://github.com/uyuni-project/uyuni-docs/pull/849
- No tests: The testsuite does not test the list of repositories, as long as packages can install.
Related: https://github.com/SUSE/spacewalk/issues/14138
> Add universe security repositories to spacewalk-common-channels

- .github/workflows/add_pr_reviewer.yml
- .github/workflows/changelog_checker.yml
checkout v1 has a bug which makes it not finding the latest git
reference and fail.
updating to v2 should fix it.
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>
No difference.
- No tests
No issue was created.
> Update github actions checkout

- testsuite/features/support/client_stack.rb
GPG key for SLE11 doesn't contain string with information about service pack version. 
This change prevents failure of bootstrap in case of SLE11SP4 systems in QAM testsuite.
https://github.com/SUSE/spacewalk/issues/14194
Tracks https://github.com/SUSE/spacewalk/pull/14256
> Testsuite - gpg key name for SLE11 corrected #14277

- testsuite/features/init_clients/sle_ssh_minion.feature
This scenario should not be needed since round about a year now.
Adding the products to the package state was dropped in https://github.com/uyuni-project/uyuni/pull/2158
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/14287
> delete scenario which delete product package from package state

- testsuite/features/build_validation/reposync/srv_wait_for_product_reposync.feature
- testsuite/features/reposync/srv_wait_for_reposync.feature
- testsuite/features/support/env.rb
- testsuite/run_sets/build_validation_reposync.yml
This PR simplifies the waiting for reposync, by dropping the @build_validation and @continuous_integration tags.
Ports:
* 4.0: SUSE/spacewalk#14295
* 4.1: SUSE/spacewalk#14296
> BV: refactor waits for reposync

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/suse/manager/webui/controllers/utils/AbstractMinionBootstrapper.java
- java/code/src/com/suse/manager/webui/controllers/utils/CommandExecutionException.java
- java/spacewalk-java.changes
In some cases, the `sudo ls` command we run to check ownership of Salt's `known_hosts` file fails with some error. Currently SUMA reports these errors incorrectly as wrong ownership/permissions. This PR adds deeper logging to provide more detailed information on the command execution.
See: https://bugzilla.suse.com/1182487
**Case in hand:** `sudo` command cannot be executed because of some misconfiguration in the `sudoers` file.
Before:
After:
rhn_web_ui.log:
```
ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - com.suse.manager.webui.controllers.utils.CommandExecutionException: Error running command: sudo /usr/bin/ls -la /var/lib/salt/.ssh/known_hosts
Process exited with code: 1
STDERR: sudo: sorry, you must have a tty to run sudo
``` …
> Log shell command output on failure when checking known_hosts file permissions

- spacewalk/setup/share/server.xml.xsl
- spacewalk/setup/spacewalk-setup.changes
Tomcat tuning parameters to prevent rare errors in high load scenarios.
AJP is a TCP-based protocol for fast communication between httpd and Tomcat, and it is used at every http request that involves the Java stack.
There is an optional watchdog mechanism to kill AJP connections if they are inactive for too long.
The JVM might not respond to such keepalive messages if it's too loaded, or during GC pauses. The keepalive time is configurable via the `keepAliveTimeout` `server.xml` variable:
https://tomcat.apache.org/tomcat-8.5-doc/config/http.html
We did not set it, so it got the default value, which is equal to `connectionTimeout`. We did set `connectionTimeout` to 20s to prevent AJP connection runaways (which were observed, for example, under QUALYS scans hammering the Server).
When this …
> Prevent several AJP errors (bsc#1179271)

- .github/workflows/add_pr_reviewer.yml
- .github/workflows/changelog_checker.yml
This PR reverts commit eb3f1f310080f9c8e6d5329c69cefe53ad79b99e introduced in PR https://github.com/uyuni-project/uyuni/pull/3399 because it breaks the `changelog check` with the following error:
No difference.
> Revert "Update github actions checkout"

- testsuite/features/build_validation/create_bootstrap_repositories/srv_create_bootstrap_repositories.feature
- testsuite/features/step_definitions/command_steps.rb
Adds new step in testsuite and uses it before we create the bootstrap repos to avoid any conflicts with packages that have same version but different hash.
No difference.
Fixes #
Tracks 4.1: https://github.com/SUSE/spacewalk/pull/14329
4.0: https://github.com/SUSE/spacewalk/pull/14330
> Add new step clean up all bootstrap repositories on the server

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Add bootstrap repository definition for SUSE Manager Proxy 4.2 (bsc#1183645)
No difference.
- No tests: Cucumber does not create bootstrap repos
Fixes https://github.com/SUSE/spacewalk/issues/14324
> Add bootstrap repository definition for SUSE Manager Proxy 4.2 (bsc#1183645)

- java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemGroup_queries.xml
- java/spacewalk-java.changes
Speed up the system groups page by removing the `NOT MATERIALIZED` hint to prevent Postgres from recomputing the query at every use.
We observed a **36x speedup** on a particular user case bsc#1182132.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13965
> Speedup system groups page

- testsuite/features/secondary/srv_push_package.feature
- testsuite/features/step_definitions/common_steps.rb
- testsuite/run_sets/core.yml
- testsuite/run_sets/refhost.yml
- testsuite/run_sets/secondary_parallelizable.yml
- testsuite/run_sets/sle-updates.yml
- testsuite/run_sets/virtualization.yml
Move push_package feature from core to secondary
The changes have been tested
https://github.com/SUSE/spacewalk/issues/13559
> Move push_package feature from core to secondary

- spacewalk/setup/salt/susemanager.conf
- spacewalk/setup/spacewalk-setup.changes
- susemanager-utils/susemanager-sls/salt/services/salt-minion.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR prevents useless package list refresh actions to be triggered by Uyuni when scheduling a package installation from the UI, or even when applying states that are calling the "zypperpkg" Salt module.
The `SALT_RUNNING` environment variable is expected to be injected by "zypperpkg" module when calling Zypper, but this is not happening after some refactor on the "zypperpkg" module.
This PR makes use of the new env variable mechanism via Salt minion configuration, so the `SALT_RUNNING` variable is injected when calling Zypper.
No difference.
- 
Fixes # …
> Prevent useless package list refresh actions on zypper minions (bsc#1183661)

- java/code/src/com/redhat/rhn/domain/kickstart/KickstartData.hbm.xml
- java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartTroubleshootingEditAction.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/webapp/WEB-INF/pages/common/fragments/kickstart/advanced/details.jspf
- java/code/webapp/WEB-INF/pages/kickstart/kickstartdetails.jsp
- java/code/webapp/WEB-INF/pages/kickstart/tree-form.jspf
- java/code/webapp/WEB-INF/pages/kickstart/troubleshooting.jsp
- java/spacewalk-java.changes
- schema/spacewalk/common/tables/rhnActionVirtCreate.sql
- schema/spacewalk/common/tables/rhnKSData.sql
- schema/spacewalk/common/tables/rhnKickstartableTree.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.2-to-susemanager-schema-4.2.3/001-add_rhnVirtCreateAction_cobblerid.sql
- schema/spacewalk/upgrade/susemanager-schema-4.2.9-to-susemanager-schema-4.2.10/100-increase-kernel-options-length.sql
Port of https://github.com/SUSE/spacewalk/pull/14183
No difference.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1182916
> Raise length limit for kernel options

- testsuite/features/step_definitions/command_steps.rb
This PR makes sure to do a `zypper ref` before installing (or removing) a pattern.
Technical notes:
* we need to call `run()` twice because of different handling of error codes
* we don't need to test for existence of `/usr/bin/zypper` as `zypper` will fail if it's not available
Ports:
* 4.0: SUSE/spacewalk#14350
* 4.1: SUSE/spacewalk#14349
> Do a zypper ref before installing a pattern

- testsuite/features/step_definitions/navigation_steps.rb
This PR adapts testsuite to select as a react component. There are currently two features with failures caused by react component replacing select:
1) Maintenance Windows
2) Content lifecycle
This PR works correctly with `Maintenance Windows` feature and doesn't break `Build OS images` (also using this select).
~~This change **must be tested with full testsuite run** before merging.~~ DONE
https://github.com/SUSE/spacewalk/issues/14194
> Testsuite - adapt testsuite to select by react component

- backend/rhn-conf/rhn_server_satellite.conf
- backend/satellite_tools/download.py
- backend/satellite_tools/repo_plugins/deb_src.py
- backend/satellite_tools/repo_plugins/yum_src.py
- backend/satellite_tools/test/unit/test_download.py
- backend/satellite_tools/test/unit/test_yum_src.py
- backend/spacewalk-backend.changes
Add a configuration value for setting the minimal transfer rate and a timeout period. If the transfer speed falls under the minimal transfer rate for the timeout duration, the download is aborted. 
I've reused the variable names (`minrate`, `timeout`) from [ulrgrabber](http://urlgrabber.baseurl.org/). They are passed through to PyCurl, therefore it is also an option to use libCurl's names (`LOW_SPEED_TIME`, `LOW_SPEED_LIMIT`). I find the urlgrabber ones a little bit nicer, but I don't mind either way.
No difference.
- Documentation issue was created: 
- PR: https://github.com/uyuni-project/uyuni-docs/pull/816
- No tests: Don't know how this can be tested in a meaningful way. Ideas welcome.
Fixes https://github.com/SUSE/spacewalk/issues/12635 …
> Reposync add timeout config

- testsuite/features/step_definitions/common_steps.rb
* make CentOS mounts survive reboots
* make that step idempotent
Ports:
* 4.0:
* 4.1: SUSE/spacewalk#14354
> Write ISO mounts to /etc/fstab

- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/spacewalk-java.changes
When SUSE Manager issues a container image inspection, `images.profileupdate` is executed.
The corresponding SLS file issue the login on every container registry
found from the docker-registries pillar.
This PR makes sure that docker-registries pillar is populated also for
inspection actions.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/12896
> Fix: Populate docker-registries on inspection (bsc#1178179)

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
- UEK 5 and 6 for Oracle Linux 7
- Multiverse and Restricted repos for Ubuntu 20.04
No difference.
- No documentation needed: not in the docs and to unimportant to add it
Fixes https://github.com/SUSE/spacewalk/issues/14191 https://github.com/SUSE/spacewalk/issues/14138
> Sw common channels update

- java/code/src/com/redhat/rhn/domain/state/StateFactory.java
- java/code/src/com/redhat/rhn/domain/state/StateRevision.hbm.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/configchannel/ConfigChannelHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/configchannel/test/ConfigChannelHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/FormulaSerializer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/ServerGroupHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/systemgroup/ServerGroupHandler.java
- java/spacewalk-java.changes
- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/configchannel.py
- spacecmd/src/spacecmd/group.py
Add missing API functions for handling Config Channels @ System Groups
No difference.
- API doc added
Fixes https://github.com/SUSE/spacewalk/issues/13710
> enhance server group API with config channel and formula access methods

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
Enable Ubuntu 20.04 syncing in testsuite now that we can
No difference.
Fixes #13372
Tracks 
4.1: https://github.com/SUSE/spacewalk/pull/14335
4.0: https://github.com/SUSE/spacewalk/pull/14336
> Enable Ubuntu 20.04 syncing in testsuite

- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/secondary/allcli_action_chain.feature
- testsuite/features/secondary/srv_distro_cobbler.feature
- testsuite/features/support/commonlib.rb
- testsuite/features/support/env.rb
Get rid of the service_pack_migration tag in our test framework and run it always.
It's causing troubles and a logic hard to maintain, we are making the wrong assumption that this tag is enabled in some other features like allcli_software_channels_dependencies.feature and srv_distro_cobbler.feature
It doesn't depend on the Jenkins pipeline change, in order to remove the variable passed by the environment, but we will merge both together. (https://github.com/SUSE/susemanager-ci/pull/207)
Some extra changes:
- I removed from our CI test suite the unnecessary sync of "12 SP5", having sync 15 SP1 and SP2 is enough for CI.
- I removed the unnecessary login via web browser in one scenario that runs fully using remote commands, so no need UI.
No difference.
- Cucumber …
> [Port] QA: Get rif of service_pack_migration tag, run it always

- testsuite/features/support/client_stack.rb
GPG key for SLE12 doesn't contain string with information about service pack version.
This change prevents failure of bootstrap in case of SLE12SP4 systems in QAM testsuite.
Same problem was already resolved by https://github.com/uyuni-project/uyuni/pull/3400 for SLE11 systems
https://github.com/SUSE/spacewalk/issues/14194
> Testsuite - change of name for SLE12 key

- backend/server/action/errata.py
used null instead of None in errata.py
No difference.
Before:
After:
Fixes #
If you …
> Fixed wrong type in python

- testsuite/features/step_definitions/command_steps.rb
Again a missing zypper ref.
Ports:
* 4.0;
* 4.1: SUSE/spacewalk#14366
> Fix workaround to set proper product

- testsuite/features/reposync/srv_enable_sync_products.feature
- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/step_definitions/common_steps.rb
Get rid of sles12 sp5 from CI tests
Ports:
- Manager-4.0
- Manager-4.1
> QA: Get rid of sles12 sp5 from CI tests

- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerProfileSyncCommand.java
- java/code/src/com/redhat/rhn/taskomatic/task/CobblerSyncTask.java
- java/spacewalk-java.changes
The `CobblerSyncTask` calls `CobblerProfileSyncCommand`, which in turn modifies the kickstart path attribute in the cobbler profile.
This results in a full sync, which might be slow on bigger setups.
Fixed by updating the attribute only if necessary (cobbler value differs from the one in Uyuni database).
No difference.
- No tests: no tests in this area
Tracks https://github.com/SUSE/spacewalk/issues/12174
> Only update the kickstart path in cobbler if necessary (bsc#1175216)

- spacewalk/setup/salt/susemanager.conf
- spacewalk/setup/spacewalk-setup.changes
- susemanager-utils/susemanager-sls/salt/bootstrap/susemanager.conf
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR moves the Salt "pkg" environment settings to the minion config file instead. This settings were wrongly pushed to the master configuration file by https://github.com/uyuni-project/uyuni/pull/3431 
No difference.
> Move Salt pkg environ settings to minion config file

- utils/spacewalk-common-channels.ini
We can't trust the default label created by `spacewalk-common-channels` for the GA repo, and we can't also use `base_parent` for the updates repo. All of this happens because the URLs for aarch64 do not follow the same standard as for `x86_64`
No difference.
- No documentation needed: Not documented yet.
- No tests: No automated tests (but @Bischoff is testing it, kudos for that!)
None.
> Solve spacewalk-common-channel problems for Leap 15.2 aarch64

- susemanager/bin/mgr-setup
Use value of parameter `product_name` from `/usr/share/rhn/config-defaults/rhn.conf` instead hardcoded string `SUSE Manager` for visible output.
No difference.
- No documentation needed: Cosmetic branding related Change
- No tests: There doesn't seem to exist a test for mgr-setup
Fixes #1354
> Debrand mgr-setup file

- client/rhel/rhnlib/rhnlib.changes
- client/rhel/rhnlib/rhnlib.spec
On SLE 11 we need to require python-backports.ssl_match_hostname to make the new stack work.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/14392
> Require backports ssl

- testsuite/Rakefile
- testsuite/documentation/guidelines.md
Add support to run multiple cucumber profiles
No difference.
- No tests
Fixes #
> QA: Support multiple Cucumber profiles

- susemanager-utils/testing/automation/obs-project.py
- susemanager-utils/testing/automation/wait-for-builds.sh
Adds obs-proejct for creating buildservice projects for pull requests
No difference.
Before:
After:
Fixes # …
> Add obs-project for creating build service projects for pull requests

- susemanager-utils/testing/automation/wait-for-builds.sh
This way, we can prevent the package from being rebuild
No difference.
Before:
After:
Fixes #
If you don't …
> Add lock option in wait for build script

- susemanager-utils/testing/automation/obs-project.py
Building for all repos takes longer in OBS. Given this is in the Pull
Request, building for openSUSE should be sufficient now.
No difference.
- No tests
> Build only for openSUSE in the Pull Request testing

- susemanager-utils/testing/automation/obs-project.py
Building for all repos takes longer in OBS. Given this is in the Pull
Request, building for openSUSE or SLE should be sufficient now.
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>
No difference.
No tests
Fixes #
> Build only for SUSE distributions in the Pull Request testing

- susemanager-utils/testing/automation/wait-for-builds.sh
Waiting for individual packages is not working for some reason, but
waiting for the whole project does, so let's wait for the project.
No difference.
- No tests
Fixes #
> Fix wait for build script: wait for project, not for individual packages

- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/secondary/allcli_action_chain.feature
- testsuite/features/secondary/trad_sp_migration.feature
- testsuite/features/support/commonlib.rb
- testsuite/features/support/env.rb
Get rid of the service_pack_migration tag in our test framework and run it always.
It's causing troubles and a logic hard to maintain, we are making the wrong assumption that this tag is enabled in some other features like allcli_software_channels_dependencies.feature and srv_distro_cobbler.feature
Note: It doesn't depend on the Jenkins pipeline change, in order to remove the variable passed by the environment, but we will merge both together. (https://github.com/SUSE/susemanager-ci/pull/207 was reverted and we need to apply again)
No difference.
Ports:
- Manager-4.0
- Manager-4.1 …
> QA: Get rif of service_pack_migration tag, run it always

- testsuite/features/secondary/srv_distro_cobbler.feature
- testsuite/features/step_definitions/common_steps.rb
Cosmetical fix on Cobbler so we always use the same product version
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Cosmetical fix on Cobbler so we always use the same product version

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/group.py
Fix a display correct help text and add two new calls.
- group_addconfigchannel()
- group_removeconfigchannel()
No difference.
- No documentation needed: **no docs for spacecmd**
Enhances https://github.com/uyuni-project/uyuni/pull/3402
> Configchannel at group enhancements

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
- suseRegisterInfo/suseRegister/info.py
- suseRegisterInfo/suseRegisterInfo.changes
- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/salt/certs/Amazon2.sls
- susemanager-utils/susemanager-sls/salt/packages/redhatproductinfo.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Support for Amazon Linux 2, which is the recommended OS for AWS.
To use:
```
```
Onboard normally.
For now `amazonlinux2-uyuni-client` uses the centos7 client tools, but we should add Amazon Linux 2 to OBS before shipping this. Reason is simple: without it we can't support Amazon Linux 2 aaarch64 which is cheaper and it's being used more and more each day.
**WARNING:** This PR also requires a SR for `uyuni-build-keys` at https://build.opensuse.org/project/show/home:juliogonzalezgil:branches:systemsmanagement:Uyuni:Master (will require a SR to `systemsmanagement:Uyuni:Master`, and a port of the same change to `susemanager-build-keys` at Head!
- All Amazon Linux instances I created have the same `/etc/machine-id`: `ec214dee1f497e5a0c3f972da49e4684`. That's a problem because we us it to …
> Support for Amazon Linux 2

- java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
- java/code/src/com/redhat/rhn/frontend/action/systems/sdc/UpdateCustomDataAction.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/test/BaseHandlerTestCase.java
- java/code/src/com/redhat/rhn/manager/system/ServerGroupManager.java
- java/code/src/com/redhat/rhn/manager/system/entitling/SystemEntitler.java
- java/code/src/com/redhat/rhn/manager/system/entitling/SystemUnentitler.java
- java/code/src/com/redhat/rhn/testing/BaseTestCaseWithUser.java
- java/code/src/com/redhat/rhn/testing/JMockBaseTestCaseWithUser.java
- java/code/src/com/redhat/rhn/testing/RhnMockStrutsTestCase.java
- java/code/src/com/suse/manager/webui/services/pillar/MinionCustomInfoPillarGenerator.java
- java/code/src/com/suse/manager/webui/services/pillar/MinionGeneralPillarGenerator.java
- java/code/src/com/suse/manager/webui/services/pillar/MinionPillarManager.java
- java/code/src/com/suse/manager/webui/services/pillar/test/MinionGroupMembershipPillarGeneratorTest.java
- java/code/src/com/suse/manager/webui/services/pillar/test/MinionPillarManagerTest.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/modules/pillar/suma_minion.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Provide Custom Info as Pillar data
No difference.
- TBD
Fixes https://github.com/SUSE/spacewalk/issues/12016
> Provide Custom Info as Pillar data

- testsuite/features/step_definitions/common_steps.rb
Add missing regex anchors in some step definitions.
Wrap the step in ^...$
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/14432
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/14433
> Testsuite: Add regex anchors in step definitions

- testsuite/features/build_validation/init_clients/proxy.feature
- testsuite/features/core/proxy_register_as_minion_with_gui.feature
- testsuite/features/core/proxy_register_as_minion_with_script.feature
- testsuite/features/core/proxy_register_as_trad_with_script.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
In build validation test suite, there was a conflict between sumaform, and the salt cleanup, that removes `/etc/salt/broker`.
Cleanest solution is to install the pattern ourselves **after** the cleanup (in all test suites).
We take the occasion to also clean up `/var/tmp/.rootXXX` directory used by sumaform to do some salt-ssh.
Plus some other code simplification.
Fixes SUSE/spacewalk#14421
Sumaform part uyuni-project/sumaform#870
susemanager-ci part SUSE/susemanager-ci#219
Ports:
* 4.0: SUSE/spacewalk#14431
* 4.1: SUSE/spacewalk#14429
> Fix salt cleanup for proxy

- testsuite/features/secondary/srv_distro_cobbler.feature
- testsuite/features/step_definitions/navigation_steps.rb
It fixes an issue in our test suite when expecting to find a button, but the browser window has not the button element visible, as we increased the entries per page to 100. As the best way to find an entry is not about expecting it on the next page, but filtering it, this is what this proposal does.
No difference.
Ports:
- Manager-4.1
- Manager-4.0
> QA: Fix selection of a snippet

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/salt/certs/AlmaLinux8.sls
- susemanager-utils/susemanager-sls/salt/packages/redhatproductinfo.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
AlmaLinux8 as a supported client
`uyuni-build-keys` at https://build.opensuse.org/project/show/home:juliogonzalezgil:branches:systemsmanagement:Uyuni:Master:Alma (will require a SR to `systemsmanagement:Uyuni:Master`
- Reposync (using the mirrorlist: https://github.com/SUSE/spacewalk/issues/14388)
- salt ssh minions do NOT trust the AlmaLinux automatically (as regular salt minions do, probably by accident). Seems the java code needs to be changed, and maybe the database, but it's unclear for me how to do it. Will talk to @mcalmer about it.
- After onboarding salt ssh minions if AlmaLinux GPG key is not accepted already, package installation/update will fail. This happens with CentOS8 as well.
- Reposync (using the mirrorlist: https://github.com/SUSE/spacewalk/issues/14388)
- Bootstrap …
> AlmaLinux8 as a supported client

- testsuite/features/core/first_settings.feature
- testsuite/features/step_definitions/command_steps.rb
Reverts uyuni-project/uyuni#3484
We will do it differently, using sumaform.
As we will safe an extra restart of tomcat service.
> Revert "Set up Java logging with level TRACE in testsuite"

- .github/workflows/labeler.yml
Make labeler only run once
No difference.
Fixes #
> Make labeler only run once

- java/code/webapp/WEB-INF/pages/multiorg/configuration.jsp
- java/spacewalk-java.changes
Fix broken docs link in `My Organization` -> `Configuraration`
No difference.
- No documentation needed: **Fix**
- No tests: **Fix**
Fixes https://github.com/SUSE/spacewalk/issues/14466
> Fix docs link in my organization configuration (bsc#1184286)

- susemanager/bin/mgr-setup
- susemanager/susemanager.changes
There are a list of messages:
```
/usr/lib/susemanager/bin/mgr-setup: line 10: [: ==: unary operator expected
/usr/lib/susemanager/bin/mgr-setup: line 10: [: ==: unary operator expected
...
```
During Uyuni setup in YaST
No difference.
- Fix condition in mgr-setup to prevent noise messages during setup
> Fix condition in mgr-setup to prevent noise messages during setup

- testsuite/features/build_validation/add_custom_repositories/add_ceos6_repositories.feature
- testsuite/features/build_validation/add_custom_repositories/add_ceos7_repositories.feature
- testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature
Change steps with new mirror hostname for mounting the centos DVDs
No difference.
Fixes: No issue created for this, direct fix for testsuite failure
Tracks:
4.1: https://github.com/SUSE/spacewalk/pull/14480
4.0: https://github.com/SUSE/spacewalk/pull/14481
> Change steps with new mirror hostname

- java/code/src/com/suse/manager/reactor/utils/RhelUtils.java
- java/spacewalk-java.changes
In case a system is detected to be a res system we currently only lookup res products as our base product which only works for versions < 8 where 8 is now a extension with rhel-base being the base product. The code change does a fallback search für rhel-base in case res returns an extension product.
No difference.
- No tests
Fixes #https://github.com/SUSE/spacewalk/issues/14416
> assign right res base product for version >=8 (bsc#1184005)

- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Keep salt-minion when it is installed to prevent update problems with dependend packages not available in the bootstrap repo.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/14426
> Keep salt minion when installed

- testsuite/features/secondary/buildhost_osimage_build_image.feature
Add a retail tag as the feature `proxy_retail_pxeboot_and_mass_import` is a dependency for `buildhost_osimage_build_image`
No difference.
Ports:
- Manager-4.1
- Manager-4.0
> Add a retail tag, the feature is a dependency for buildhost_osimage_build_image.feature

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Add aarch64 for CentOS7/8, Oracle7/8, Amazon Linux2 and Alibaba Linux 2
It will NOT be "supported" for Uyuni 2021.04. Requires testing first.
No difference.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/14440
- No tests: https://github.com/SUSE/spacewalk/issues/14398
Tracks: https://github.com/SUSE/spacewalk/issues/14398
> Add aarch64 for CentOS7/8, Oracle7/8, Amazon Linux2 and Alibaba Linux 2

- testsuite/run_sets/build_validation_init_clients.yml
Disable centos 8 from run_sets not only from renaming the files in the features folder.
No difference.
Fixes: No issue created, direct fix from BV testsuite review
Tracks 
4.1: https://github.com/SUSE/spacewalk/pull/14493
4.0: https://github.com/SUSE/spacewalk/pull/14494
> Disable centos 8 from run_sets

- susemanager-utils/susemanager-sls/salt/services/kiwi-image-server.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Upcoming Kiwi update introduces new kiwi requirements. Without these requirements, building new image fails on missing `qemu-img` binary.
No difference.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1184271
> Require new kiwi system dependencies

- testsuite/features/step_definitions/navigation_steps.rb
Still, a case that my test did not catch before. Here we fix the case to check if an option is selected on a React Select component.
No difference.
> QA: Fix "has react select" field and value

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minxen_guests.feature
KVM/XEN tests authorize always as admin, in order to avoid unexpected scenarios, let's use always the same user.
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: KVM/XEN tests authorize always as admin

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/support/env.rb
Skip Install patch scenario for 15sp3 because it is not released yet and has no patches.
No difference.
Fixes No issue created, directly from BV testsuite review
Tracks 
4.1: https://github.com/SUSE/spacewalk/pull/14505
4.0: https://github.com/SUSE/spacewalk/pull/14508
> Skip Install patch for 15sp3

- susemanager-utils/susemanager-sls/modules/engines/mgr_events.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes an issue with our custom `mgr_events` Salt engine at the time of dealing with the Tornado IOLoop.
Before this PR, the `mgr_events` engine is not properly instantiating the IOLoop to be used by this process, so it clashes when there is an already running tornado IOLoop, for example, when SaltStack Enterprise is running:
```console
Jan 16 15:01:59 suma-hostname salt-master[16536]: [CRITICAL] Engine 'mgr_events' could not be started!
Jan 16 15:01:59 suma-hostname salt-master[16536]: Traceback (most recent call last):
Jan 16 15:01:59 suma-hostname salt-master[16536]: File "/usr/lib/python3.6/site-packages/salt/engines/__init__.py", line 132, in run
Jan 16 15:01:59 suma-hostname salt-master[16536]: self.engine[self.fun](**kwargs)
Jan 16 15:01:59 suma-hostname salt-master[16536]: …
```
> Avoid conflicts with running ioloop on mgr_events engine (bsc#1172711)

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- utils/spacewalk-common-channels
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
bootstrap data and common-channels for leap 15.3
a fix for being able to adding 2 channels, at the same time, with same repo url 
No difference.
https://github.com/SUSE/spacewalk/issues/14440
* add leap 15.3 for x86 and aarch64 with `spacewalk-common-channels` (both archs at the same time)
* trigger sincronization with `spacewalk-repo-sync -p <parent> via CLI)`
* check that we can generate bootstrap repos with `mgr-create-bootstrap-repo`
Fixes https://github.com/SUSE/spacewalk/issues/14339
> Add openSUSE Leap 15.3

- utils/spacewalk-common-channels.ini
leap 15.3 is not yet ready ;) .
We will enable them later.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/14528
> Disable server and proxy stable channels for leap 15.3

- testsuite/features/secondary/srv_push_package.feature
- testsuite/features/step_definitions/common_steps.rb
https://github.com/SUSE/spacewalk/issues/14358
After investigation, the certificate doesn't seem needed anymore. I could run `rhnpush` command to push the package on the server side without any certificate issue.
Test suite have been run without the ssl downloaded without new error.
The SSL download should not be a test by itself because it's not part of SUMA project.
Discution : https://github.com/uyuni-project/uyuni/pull/3318#issuecomment-800077153
> Remove SSL download from push package

- testsuite/features/secondary/srv_mainpage.feature
- testsuite/features/secondary/srv_security.feature
- testsuite/features/step_definitions/navigation_steps.rb
This PR enforces the correct behavior of two features, which requires that we don't have old cookies stored in the browser.
These cookies, in case of no using a new web session, will cause a failed test, as they will keep the previous logged used authenticated.
Dependency of #3533 
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Assure that we don't have cookies in some scenarios

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Add multiverse, restricted and backports to Ubuntu 16.04 and 18.04
For both SUSE Manager and Uyuni
No difference.
- No documentation needed: We don't have such channels as part of the doc
- I checked manually that the URLs exist.
None
> Add multiverse, restricted and backports to Ubuntu 16.04 and 18.04

- java/code/src/com/redhat/rhn/taskomatic/task/ModularDataCleanup.java
- java/spacewalk-java.changes
Previously, the code for modular data cleanup (`modules.yaml` files) didn't check if the directory exists.
This adds a simple check with a descriptive log message in case the directory is missing (can happen, if the user never synced modular channels).
No difference.
bugfix
- No tests: no tests in this area
Tracks https://github.com/SUSE/spacewalk/issues/14463
> Bugfix: Check if the directory exists prior to modular data cleanup

- testsuite/run_sets/secondary_parallelizable.yml
Add missing test to the execution configuration
No difference.
Before:
After:
Fixes #
Tracks # …
> add missing test execution min_config_state_channel_xmlrpc.feature

- susemanager-utils/susemanager-sls/salt/virt/create-vm.sls
- susemanager-utils/susemanager-sls/salt/virt/statechange.sls
- susemanager-utils/susemanager-sls/src/states/virt_utils.py
- susemanager-utils/susemanager-sls/src/tests/test_state_virt_utils.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- susemanager-utils/susemanager-sls/susemanager-sls.spec
Creating or starting a VM using a storage pool or network that is stopped will cause a failure. This change automatically starts those and ensures the storage pools are refreshed.
Getting pools refreshed may be useful after restarting the virtual host since the mount could happen after the `libvirtd` start and thus no volume would be listed in the started pool.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/9340 …
> Automatically start networks and pools when starting / creating a VM

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minxen_guests.feature
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/support/env.rb
This code changes the actual behavior of our test suite, currently, we open a new web session for each scenario, so we require a log-in for each scenario. This PR aims to keep open the browser for the whole feature, resetting the session only when a new Cucumber feature starts.
Some scenarios rely on the current behavior, so they expect that we have a reset page on every scenario, but if we change that by holding the session, we must assure that the scenarios don't rely anymore on this.
So, this PR also includes a change in the KVM/XEN tests where we open a new tab, and we expect to have it closed when a new scenario starts. What we do in this case is to assure that we close the tab and we move to the first tab.
**Note:** 
This PR will speed up the test suite "per se", but holding the …
> QA: Capybara hold the web browser session

- backend/satellite_tools/spacewalk-debug
It seems it haven't worked for some time (I was missing files for inventory, for instance). This should make it work again.
In the end this rather obscure approach with grep was used.
Alternative (cleaner) approach with sourcing the os-release file was not
used as there is a danger of shadowing other env variables.
- No documentation needed: internal stuff
- No tests: no tests here
> Supportconfig: Fix the IS_SUSE variable reading

- susemanager-utils/susemanager-sls/src/states/virt_utils.py
Fix `susemanager-sls` build failure by removing the libvirt import.
No difference.
- No documentation needed: package build fix
- No tests: package build fix
Fixes #
> virt_utils state: remove libvirt import

- testsuite/documentation/cucumber-steps.md
- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/step_definitions/common_steps.rb
Change the default timeout of 250 seconds, to a bigger value of 600 seconds in some steps where most of the job executions these scenarios failed due to the timeout.
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Prevent a flaky tests on KVM/XEN scenarios

- java/code/src/com/suse/manager/webui/services/pillar/MinionGeneralPillarGenerator.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/src/beacons/pkgset.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
DO NOT MERGE UNTIL openSUSE/salt#347 IS MERGED
This PR addapts Uyuni to support the aptnotify introduced on https://github.com/openSUSE/salt/pull/347
this 
And updated version of: https://github.com/uyuni-project/uyuni/pull/3442
No difference.
- No tests: …
> Notify beacon for Debian/Ubuntu systems

- testsuite/config/cucumber.yml
- testsuite/features/secondary/min_retracted_patches.feature
- testsuite/features/secondary/srv_retracted_patches.feature
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/run_sets/secondary.yml
Do not merge before https://github.com/uyuni-project/uyuni/pull/3110!
The PR adds various scenarios related to the Retracted Patches feature.
It also adds/extends existing step definitions according to its needs.
To me it looks cleaner to keep the feature in a separate feature file, but I'd happy to hear other suggestions from the reviewers.
- No documentation needed: testsuite
Tracks https://github.com/SUSE/spacewalk/issues/13252
> Testsuite: Test the Retracted Patches feature

- utils/spacewalk-common-channels.ini
Fix the label and description for the almalinux8-ha channel (they mentioned extra, probably because I did a copypaste and didn't adjust that)
Thanks @vzhestkov for spotting it.
No difference.
- No tests: AlmaLinux 8 not covered by the testsuite
None
> Fix the label and description for the almalinux8-ha channel

- java/code/src/com/suse/manager/webui/services/test/StateSourceServiceTest.java
- testsuite/features/secondary/min_salt_software_states.feature
- testsuite/features/secondary/min_salt_user_states.feature
With the new Highstate summary page, the full highstate output is now hidden behind a "Show full highstate output" button. This PR reflects this change in cucumber.
> Adapt tests for new Highstate page

- java/code/src/com/suse/manager/webui/services/impl/test/monitoring/disable.json
- java/code/src/com/suse/manager/webui/services/impl/test/monitoring/enable.json
- susemanager-utils/susemanager-sls/salt/srvmonitoring/disable.sls
- susemanager-utils/susemanager-sls/salt/srvmonitoring/enable.sls
- susemanager-utils/susemanager-sls/salt/srvmonitoring/removejmxprops.sls
- susemanager-utils/susemanager-sls/salt/srvmonitoring/status.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- susemanager-utils/susemanager-sls/susemanager-sls.spec
The change restricts access to Java Remote Method Invocation to
`localhost` to prevent unauthorized remote code execution.
No change.
- No tests: Tests updated
Fixes # https://bugzilla.suse.com/show_bug.cgi?id=1184617
> Fix insecure JXM configuration

- testsuite/features/secondary/min_retracted_patches.feature
Previously, we were relying on the 'I wait until refresh package list on
"sle_minion" is finished' step, which didn't work very well in case
there was a lot of subsequent package installations/removals.
> Testsuite: Make sure package is installed on/removed from client in retracted patches tests

- testsuite/features/core/proxy_branch_network.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/upload_files/massive-import-terminals.yml
PR deletes (1) empty profiles and (2) dhcp test of regular systems in private network to prevent conflict with regular clients testing.
> Testsuite - delete empty bootstrap profiles

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
- java/spacewalk-java.changes
The check for mirrolists like used for CentOS failed as we added the repomd.xml file path at the end.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/14586
> Uyuni fix mirrorlist url handling

- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/manager/webui/services/test/SaltServerActionServiceTest.java
- java/spacewalk-java.changes
Previously, the list of filtered minions was computed incorrectly: the filtering condition was reversed, so instead of including minions with no retracted packages, the filter included only minions _with_ retracted packages.
Review commit-by-commit please.
No diff.
https://github.com/SUSE/spacewalk/issues/14605
> Retracted patches filtered minions fix

- spacewalk/admin/spacewalk-admin.changes
- spacewalk/admin/spacewalk-startup-helper
The DB schema version check was done against all entries in rhnVersionInfo table.
But we only need to check against the "current" schema as the older ones will just fail.
This caused the startup of the server to fail when multiple schema migrations were done in the past.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/14624
> Fix db schema version check

- susemanager-utils/susemanager-sls/salt/ansible/runplaybook.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR simply introduces a new SLS file that triggers the execution of an Ansible playbook in a minion. This `ansible.runplaybook` state needs some pillar data to render properly:
- `playbook_path`: path to the playbook in the minion
- `rundir`: directory `ansible-playbook` is executed
- (optional) `inventory`: define an alternative inventory file (default `/etc/ansible/hosts`) 
An example running this playbook: https://github.com/ansible/ansible-examples/tree/master/lamp_simple
```console
local:
----------
ID: run_ansible_playbook
Function: ansible.playbooks
Name: /root/playbooks/lamp_simple/site.yml
Result: True
Comment: Changes were made by playbook /root/playbooks/lamp_simple/site.yml
Started: 12:11:00.192506
Duration: 16707.01 ms
Changes:   
----------
apply common configuration to …
```
> [Ansible] Add new SLS file to trigger Ansible playbook execution

- susemanager-utils/susemanager-sls/src/tests/test_mgr_master_tops.py
This PR fixes test failure introduced in `ansible-integration` branch that is preventing the `susemanager-sls` package to build.
> [Ansible] Fix test due a change on master top definitions

- java/code/src/com/redhat/rhn/domain/server/Server_legacyUser.hbm.xml
- java/code/src/com/redhat/rhn/domain/server/test/ServerFactoryTest.java
- java/spacewalk-java.changes
POrt of: https://github.com/SUSE/spacewalk/pull/14635
relates to: https://github.com/SUSE/spacewalk/issues/14614
No difference.
Before:
After:
- Unit …
> Lower case fqdn comparation when calculating minion connection path

- rel-eng/push-packages-to-obs.sh
- susemanager-utils/testing/automation/push-to-obs.sh
- susemanager-utils/testing/docker/scripts/push-to-obs.sh
With this option, we can push new packages to a separate project instead
of updating the current one.
This is useful for pushing new packages into obs project for testing
pull requests, so that we only build new packages, instead of building
all the packages.
The current behavious is that packages will be updated in the specified projects, by using the -d option.
For example, we have systemsmanagement:Uyuni:Master, where we have ALL the packages. Note I am highlighting ALL.
Then, we take the sources from github/uyuni-project/uyuni/ , and build the SRPMs locally.
Once you have the SRPMs, we checkout systemsmanagement:Uyuni:Master and compare each package with the SRPMs.
Then, for each package that there are differences, we are updating the package and pushing it to …
> Add option to push to an obs test project

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
Correct expected text for product sync, adding the text that appears in the UI. This should only be for 4.2 for master.
No difference.
Fixes No issue, directly from BV testsuite review
> Correct expected text for product sync

- susemanager-utils/testing/automation/push-to-obs.sh
In previous commit I had missed to add the n option
> Fix push-to-obs syntax

- susemanager-utils/testing/docker/scripts/push-to-obs.sh
fix syntax to push-to-obs script
> fix syntax to push-to-obs script

- testsuite/features/step_definitions/command_steps.rb
The zypper.log rotates at 00:00 if its size is >= 10 Mb.
At the time when we inspect this log, its size is >~ 10 Mb, thus
there are some chances that the log is rotated before we search for
the pattern inside it.
- testsuite/features/step_definitions/command_steps.rb:
Inspect both, zypper.log and the rotated one zypper.log-%Y%m%d.xz.
Fixes https://github.com/uyuni-project/uyuni/pull/3285
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/14642
> Testsuite: inspect the zypper rotated log as well

- testsuite/Rakefile
Add support to include the union of tags through an environment variable `TAGS`
This will allow selecting multiple functional areas from the Jenkins pipeline, as we can't do the union of Cucumber profiles as was expected the default behavior passing multiple profiles (it does the intersection).
**Dependency:** We need to change the pipelines code to use tags instead of profiles (https://github.com/SUSE/susemanager-ci/pull/248), but this PR can be merged safely without the change on the pipeline as it will not break the execution of tests.
Related to https://github.com/SUSE/spacewalk/issues/14618
No difference.
Ports:
- Manager-4.0
- Manager-4.1 …
> QA: Support Cucumber tags as environment variable

- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/secondary/min_salt_install_package.feature
- testsuite/features/secondary/trad_inst_package_and_patch.feature
- testsuite/features/step_definitions/command_steps.rb
Align step definition with our code base to produce minimum sorprise.
- testsuite/features/step_definitions/command_steps.rb:
Don't wrap the shy group inside quotes to align with other
step definitions in our code base.
- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/secondary/min_salt_install_package.feature
- testsuite/features/secondary/trad_inst_package_and_patch.feature:
All callers updated.
Continuation of: https://github.com/uyuni-project/uyuni/pull/3600
> Testsuite: Minor tweak in a step definition

- testsuite/Rakefile
This reverts commit 33a27ad2ee7b2a9ae9c5ef9ce918b5e8355c5b2d.
This commit is skipping all the secondary features in the CI.
https://github.com/uyuni-project/uyuni/pull/3597
> Revert "QA: Support Cucumber tags as environment variable (#3597)"

- testsuite/Rakefile
This PR re-add the changes on the PR reverted, as the issue was caused in the susemanager-ci repository and it's already fixed and not in these lines.
- Reverts uyuni-project/uyuni#3608
- Related to https://github.com/SUSE/spacewalk/issues/14618
- susemanager-ci fix: https://github.com/SUSE/susemanager-ci/commit/d7ee0adebec63cc1c986651fa502c1ec6e8bdc9e
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/14664
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/14663 …
> Revert "Revert "QA: Support Cucumber tags as environment variable (#3597)""

- backend/cdn_tools/cdn-sync
- backend/satellite_tools/mgr-update-pkg-extra-tags
- backend/satellite_tools/satellite-sync
- backend/satellite_tools/spacewalk-remove-channel
- backend/satellite_tools/spacewalk-repo-sync
- backend/satellite_tools/update-packages
- backend/spacewalk-backend.changes
- client/tools/mgr-osad/mgr-osad.changes
- client/tools/mgr-osad/osa-dispatcher-selinux/osa-dispatcher.fc
- client/tools/mgr-osad/osa-dispatcher.service
- client/tools/mgr-osad/osad.service
- java/code/src/com/redhat/rhn/frontend/action/channel/manage/SyncRepositoriesAction.java
- java/spacewalk-java.changes
- proxy/installer/jabberd/c2s.xml
- proxy/installer/jabberd/sm.xml
- proxy/installer/spacewalk-proxy-installer.changes
- spacewalk/admin/spacewalk-admin.changes
- spacewalk/admin/spacewalk-service.systemd
- spacewalk/admin/spacewalk-wait-for-tomcat.service
- spacewalk/admin/spacewalk-wait-for-tomcat.service.SUSE
- spacewalk/spacewalk-setup-postgresql/bin/spacewalk-setup-postgresql
- spacewalk/spacewalk-setup-postgresql/spacewalk-setup-postgresql.changes
- susemanager-utils/testing/docker/master/uyuni-master-cobbler/cobbler_web.conf
- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes
Path `/var/run` is deprecated and should be replaces with `/run/`
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/14660
> Fix deprecation in systemd files

- web/html/src/components/input/Select.tsx
- web/html/src/utils/test-utils/index.ts
- web/spacewalk-web.changes
Fixes the positioning of the react select choices menu in modal dialogs.
Before:
After:
- No documentation needed: only fixes rendering
- No tests: too hard to test
> Fix ReactSelect options placement in modal dialogs (bsc#1183997)

- testsuite/Rakefile
As @calancha pointed out here https://github.com/uyuni-project/uyuni/pull/3615 we are using a tags expression that only works on a Cucumber version higher than 2.0.0, and we still need to use the previous style in the command line.
The Rake task expects a list of tags, separated by a comma, including any prepend necessary for the behavior the user wants to have, for instance: `TAGS=@scope_salt,@scope_traditional_client` which will run all the tests having one of those tags at least, another example could be `TAGS=~@scope_traditional_client` which will run all the tests not having this tag.
No difference.
Ports:
- Manager-4.0
- Manager-4.1 …
> QA: Use the correct tags expressions for Cucumber 2.0.0

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Add openSUSE Tumbleweed/MicroOS
I didn't test openSUSE Tumbleweed, but should hopefully "just" work, even without client tools, as salt-minion is available.
What works:
- Onboarding from WebUI
- Listing packages
- Installing packages (requires rebooting)
- Removing packages (requires rebooting)
- Remote  commands (from the system details > Remote Command, but NOT from Salt > Remote Commands, where [stays in `Pending` forever and at the logs](https://github.com/SUSE/spacewalk/issues/14574) I can only see that the user admin sent the command)
- Rebooting
What does not work:
- [Applying highstates](https://github.com/SUSE/spacewalk/issues/14573). IT doesn't fail, but I see (I enabled a formula and changed the values for the time zone)
```
----------
ID: mgr_do_nothing
Function: test.nop …
```
> Add openSUSE Tumbleweed/MicroOS

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Add bootstrap repo data for OES 2018 SP3
No difference.
- No documentation needed: **On OES product to document this**
Tracks https://github.com/SUSE/spacewalk/pull/14673
> Oes2018 sp3 bootstrap data

- java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemOverviewAction.java
- java/code/webapp/WEB-INF/pages/systems/sdc/overview.jsp
- java/spacewalk-java.changes
Stop displaying the activation key on the system details page
Before:
After:
- No tests: Only visual change
Fixes https://github.com/SUSE/spacewalk/issues/14172
> Remove Activation key from system details page

- branding/css/susemanager-dark-variables.less
- branding/css/susemanager-light-variables.less
- branding/css/susemanager-theme.less
- branding/css/uyuni-theme.less
- branding/css/uyuni-variables.less
- branding/spacewalk-branding.changes
- testsuite/features/secondary/min_config_state_channel_subscriptions.feature
- web/html/src/components/config-channels.tsx
- web/html/src/components/messages.tsx
- web/html/src/components/ranking-table.tsx
- web/html/src/components/salt-state-popup.tsx
- web/spacewalk-web.changes
Follow up of https://github.com/uyuni-project/uyuni/pull/3482 from the original RFC https://github.com/uyuni-project/uyuni-rfc/blob/master/accepted/00076-state-channels-visibility.md
The following change is valid for:
- `Home > My Organization > Configuration Channels`
- `Systems > Details > States > Configuration Channels`
- `Systems > System Groups > Details > States > Configuration Channels`
- `Admin > Organizations > Details > States > Configuration Channels`
Before:
After:
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&l …
> Simplify config states channels selection workflow by dropping and squashing tabs into one

- testsuite/features/step_definitions/command_steps.rb
This test is failing because we are not installing the right OpenSCAP package.
Install the specific OpenSCAP package for Red Hat.
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/14684
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/14685
> Testsuite: Fix trad_centos_client.feature

- java/code/src/com/redhat/rhn/common/db/datasource/xml/config_queries.xml
- java/code/src/com/redhat/rhn/manager/configuration/test/ConfigurationManagerTest.java
- java/spacewalk-java.changes
We don't support local-managed or sandbox files on the minion https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/client-configuration/configuration-management.html.
But there was still the way that customers were able to assign locally-managed/sandbox file to the minion and later got stuck because there was a problem. This PR make sure that customers don't get into that situation, to begin with
No difference.
- No documentation needed: documentation is already there that it is not suppored
-Unit test : existing test updated
Fixes # …
> Exclude minions from the systems list for locally-managed/sandbox files during copy To operation.

- java/spacewalk-java.spec
In order to use `jboss-logging` from SLE, we need to prettify the symlink just like for RHEL / CentOS. Only on openSUSE we would still use our own `jboss-logging` package, until the rebase on Leap 15.3.
No difference.
- No tests needed.
Part of the (downstream) issue https://github.com/SUSE/spacewalk/issues/12357.
> Prettify the symlink for jboss-logging

- java/spacewalk-java.spec
This patch is fixing a macro in the spec file: `opensuse` -> `is_opensuse`.
No difference.
- No tests needed.
> Correct the macro to check for opensuse ("is_opensuse")

- susemanager-utils/testing/automation/update-obs-environment-cr-project.sh
There is TEST:CR projects for each environment that "links" to
systemsmanagement:Uyuni:Master.
The purpose of these projects is to be able to freeze them before
running the e2e tests in the PR, so there is no issues with having
wrong metadata that does not reflect the state of the repository, which
happens if packages are rebuild after having done a "zypper up" and
before a "zypper in".
When this happens, we have the rerun the pipeline which takes 2-3 hours,
which is a major pain.
This script, is expected to be called from a jenkins job that will
update the packages in the TEST:CR projects to make sure there are links
to all the packages.
No difference. This is CI.
- No tests
related to https://github.com/SUSE/spacewalk/issues/14654 …
> Add script to update TEST:CR obs projects

- testsuite/features/step_definitions/command_steps.rb
The fix is not working as we expected: it doesn't provide the necessary XML file.
This reverts commit 94a3603d2830afd8f34b9a6f99833236480c8885.
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/14693
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/14694
> Revert "Testsuite: Fix trad_centos_client.feature"

- testsuite/features/secondary/min_bootstrap_script.feature
We don't show the activation key anymore in the minion overview page.
- testsuite/features/secondary/min_bootstrap_script.feature:
Delete this scenario.
https://github.com/SUSE/spacewalk/issues/14172
https://github.com/uyuni-project/uyuni/pull/3588
None
> Testsuite: Follow a UI change

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/step_definitions/navigation_steps.rb
Fix the step selecting in a reac-select component
> Fix react-select selection due to commit 362b725b

- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Provide more data in case of bootstrap failure because of jinja failure
No difference.
Fixes #3565
If you …
> Handle exceptions when http status is missing

- testsuite/run_sets/finishing_pr.yml
This takes 9 minutes and this test is not required for Pull Requests.
fixes https://github.com/SUSE/spacewalk/issues/14707
No difference.
- No tests
Fixes #https://github.com/SUSE/spacewalk/issues/14707
> Remove the smdba tests from the finishing set for Pull Requests e2e

- spacewalk/admin/spacewalk-admin.changes
- spacewalk/admin/spacewalk-service.systemd
`spacewalk-service stop` does not stop jabberd when osa-dispatcher failed to start.
Fix this by checking for `is-enabled`.
Port of https://github.com/SUSE/spacewalk/pull/14702
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/14702
> Fix stopping jabberd

- proxy/installer/squid.conf
- proxy/proxy-docs/spacewalk-proxy-docs.changes
- proxy/proxy-docs/squid.conf.sample
- proxy/proxy/spacewalk-proxy.changes
In proxy 3.2, 127.0.0.1 was added as a builtin acl. Having it
explicitely in squid.conf, is a duplication and makes this warning
appear:
2020/08/17 16:47:14| WARNING: (B) '127.0.0.1' is a subnetwork of (A)
'127.0.0.1'
2020/08/17 16:47:14| WARNING: because of this '127.0.0.1' is ignored to
keep splay tree searching predictable
2020/08/17 16:47:14| WARNING: You should probably remove '127.0.0.1'
from the ACL named 'localhost'
Before:
If you run "systemctl status squid" you would see
```
Aug 17 16:46:48 sumaproxy squid[5606]: 2020/08/17 16:46:48| WARNING: (B) '127.0.0.1' is a subnetwork of (A) '127.0.0.1'
Aug 17 16:46:48 sumaproxy squid[5606]: 2020/08/17 16:46:48| WARNING: because of this '127.0.0.1' is ignored to keep splay tree searching predictable
Aug 17 16:46:48 sumaproxy squid[5606]: …
```
> Remove 127.0.0.1 from ACL name localhost

- rel-eng/push-packages-to-obs.sh
- susemanager-utils/testing/automation/push-to-obs.sh
- susemanager-utils/testing/docker/scripts/push-to-obs.sh
when comparing if packages need to be updated, by default we were not
expanding links, and as result, all packages were found to need updates.
Let's add an option so we can expand links and we only update packages
that need to. This is needed for testing Pull Requests because
systemsmanagement:Uyuni:Master:TEST:X:CR are links to
systemsmanagement:Uyuni:Master, and without this option, all packages
are found that need to be updated and so the task takes longer.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/14706 …
> CI: add option for not expanding links

- testsuite/features/secondary/min_centos_openscap_audit.feature
- testsuite/features/secondary/min_salt_openscap_audit.feature
- testsuite/features/secondary/min_ubuntu_openscap_audit.feature
- testsuite/features/secondary/trad_centos_client.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- We were not capturing the issues of not having available a package when trying to install it, therefore we were not using the right packages in some scenarios. This PR raises an exception based on the output message of the installation step.
- We were not including client tools before installing an OpenScap package which is included as part of the client tools. We are adding them to all our OpenScap features.
No difference.
Ports:
- Manager-4.0
- Manager-4.1 …
> QA: Fix OpenScap issue in CentOS minion

- web/html/src/components/table/SearchField.tsx
- web/html/src/components/table/SearchPanel.tsx
- web/html/src/manager/admin/setup/products/products.tsx
- web/html/src/manager/admin/task-engine-status/taskotop.tsx
- web/html/src/manager/audit/cveaudit/cveaudit.tsx
- web/html/src/manager/audit/subscription-matching/subscription-matching-subscriptions.tsx
- web/html/src/manager/audit/subscription-matching/subscription-matching-unmatched-products.tsx
- web/html/src/manager/images/image-profiles.tsx
- web/html/src/manager/images/image-stores.tsx
- web/html/src/manager/images/image-view-packages.tsx
- web/html/src/manager/images/image-view-patches.tsx
- web/html/src/manager/images/image-view.tsx
- web/html/src/manager/maintenance/details/schedule-details.tsx
- web/html/src/manager/notifications/notification-messages.tsx
- web/html/src/manager/salt/keys/key-management.tsx
- web/html/src/manager/virtualization/ListTab.js
- web/html/src/manager/virtualization/pools/list/pools-list.js
https://github.com/uyuni-project/uyuni/commit/af11d65a3377e2ce2ad7e8720285ca9694120d49#diff-8cc13d70de76cf2c345bea40bd41c6ec0b8a51040de802915b25967886025748R47 broke search field usage in cases where the type checking for children didn't match components correctly.
No difference.
Fixes #
> Resolve input control conflicts

- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes an issue at the time of assigning the bootstrap repo when bootstrapping new systems.
Before this PR there was the wrong assumption that  `/etc/system-release` file was only present in Amazon Linux, while this file is indeed also present in CentOS:
- Amazon Linux:
```console
bash-4.2# cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
bash-4.2# cat /etc/system-release
Amazon Linux release 2 (Karoo)
bash-4.2# cat /etc/centos-release
cat: /etc/centos-release: No such file or directory
```
- CentOS:
```console
[root@9f310b021905 /]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)" …
```
> Do not assume AmazonLinux bootstrap repo for CentOS (bsc#1185421)

- susemanager-utils/testing/automation/push-to-obs.sh
- susemanager-utils/testing/docker/scripts/push-to-obs.sh
fix syntax error in push-to-obs
No difference.
Before:
After:
- No tests
Fixes #
> fix syntax error in push-to-obs

- proxy/installer/spacewalk-proxy-installer.spec
- proxy/installer/squid.conf
- proxy/proxy/spacewalk-proxy.changes
These removes ignore-no-cache option from squid, which is obsolete, to remove the warning
UPGRADE: refresh_pattern option 'ignore-no-cache' is obsolete. Remove it.
and sets the max date to a year, to remove the warning
refresh_pattern maximum age too high. Cropped back to 1 year.
No difference.
Before: Running squid -k you should see the mentioned warnings
After: You should not see the mentioned warnings in the logs
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/14059
> Remove warnings in suma bsc 1175369

- testsuite/features/secondary/buildhost_docker_auth_registry.feature
- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/run_sets/secondary.yml
- testsuite/run_sets/secondary_parallelizable.yml
Moving build host Cucumber features to the parallel tests, removing the scenario that kills the salt events pending to don't cause any collision.
Related to https://github.com/SUSE/spacewalk/issues/13118
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Moving build host feature to secondary_parallelizable.yml

- testsuite/features/secondary/srv_distro_cobbler.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/upload_files/autoinstall/cobbler/fedora12/initrd.img
- testsuite/features/upload_files/autoinstall/cobbler/fedora12/vmlinuz
- testsuite/features/upload_files/autoinstall/cobbler/mock/empty.xml
- testsuite/features/upload_files/autoinstall/cobbler/sles15sp2/initrd
- testsuite/features/upload_files/autoinstall/cobbler/sles15sp2/linux
The PR remove the upload of install files needed for srv_distro_cobbler.feature from the sumaform deployment to the testsuite execution.
Dependency : https://github.com/uyuni-project/sumaform/pull/873
New version of : https://github.com/uyuni-project/uyuni/pull/3562
No difference.
Issue : 
https://github.com/SUSE/spacewalk/issues/13755
- Cucumber background test were added
> Move autoinstall files upload from sumaform to spacewalk project

- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/trad_migrate_to_minion.feature
- testsuite/features/secondary/trad_migrate_to_sshminion.feature
Do not search for the activation key on the client overview page: it's not shown anymore.
It completes: https://github.com/uyuni-project/uyuni/pull/3638
Continuation of https://github.com/uyuni-project/uyuni/pull/3638
None
> Testsuite: Overview page doesn't show the activation key

- client/rhel/dnf-plugin-spacewalk/actions/errata.py
- client/rhel/dnf-plugin-spacewalk/dnf-plugin-spacewalk.changes
- client/rhel/yum-rhn-plugin/actions/errata.py
- client/rhel/yum-rhn-plugin/yum-rhn-plugin.changes
Fix undefined paramater usage in yum-rhn-plugin errata action.
No difference.
> Fix yum rhn plugin param change

- testsuite/features/build_validation/init_clients/sle11sp4_minion.feature
- testsuite/features/build_validation/init_clients/sle11sp4_ssh_minion.feature
BV test suite: add pre-requisite package on normal Salt and Salt SSH minions on SLE 11 SP4
Reference: https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/client-configuration/registration-bootstrap.html
Ports:
* 4.0: SUSE/spacewalk#14733
* 4.1: SUSE/spacewalk#14734
> SLE11 SP4 can't bootstrap without python-xml

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/suse/manager/webui/controllers/AnsibleController.java
- java/code/src/com/suse/manager/webui/templates/minion/ansible-path-content.jade
- web/html/src/components/action-schedule.tsx
- web/html/src/components/messages.tsx
- web/html/src/manager/minion/ansible/accordion-path-content.tsx
- web/html/src/manager/minion/ansible/ansible-path-content.tsx
- web/html/src/manager/minion/ansible/schedule-playbook.tsx
Implement Ansible playbook details page to show a playbook's content and schedule execution.
- Unit tests will be added with a separate PR
> Ansible playbook details and schedule page

- testsuite/features/core/srv_channels_add.feature
- testsuite/features/core/srv_create_repository.feature
- testsuite/features/step_definitions/salt_steps.rb
Related to https://github.com/SUSE/spacewalk/issues/13525
Removing the workaround to don't check GPG keys in Ubuntu, as far I can see we have the GPG keys in our server, so I guess we are fine.
```uyuni-master-srv:/srv/www/htdocs/pub # ls
AnotherRepo                                   centos6-gpg-pubkey-c105b9de.key          oes-gpg-pubkey-044ADAEE04881839.key   rhn-org-trusted-ssl-cert-1.0-1.noarch.rpm
RHN-ORG-TRUSTED-SSL-CERT                      centos7-gpg-pubkey-f4a80eb5.key          oes-gpg-pubkey-57DA9A6804A29DB0.key   sle-container-gpg-pubkey-d4ade9c3.key
RHN-ORG-TRUSTED-SSL-CERT.sha512               centos8-gpg-pubkey-05B555B38483C65D.key  ol67-gpg-pubkey-72F97B74EC551F03.key  sle10-gpg-pubkey-9c800aca.key
TestRepoDebUpdates …
```
> QA: Remove workround on Ubuntu GPG Check

- testsuite/features/step_definitions/navigation_steps.rb
Reduce from 10 to 3 the seconds (enough to re-load the page) to wait for a text in a list that will not be updated unless we refresh the page
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Fix flaky tests waiting for a pick-up of an event of a page without ajax

- testsuite/features/build_validation/init_clients/ceos6_ssh_minion.feature
- testsuite/features/build_validation/init_clients/ceos7_ssh_minion.feature
- testsuite/features/build_validation/init_clients/debian10_ssh_minion.feature
- testsuite/features/build_validation/init_clients/debian9_ssh_minion.feature
- testsuite/features/build_validation/init_clients/disabled/ceos8_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle11sp4_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle12sp4_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp1_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp2_ssh_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp3_ssh_minion.feature
- testsuite/features/build_validation/init_clients/ubuntu1604_ssh_minion.feature
- testsuite/features/build_validation/init_clients/ubuntu1804_ssh_minion.feature
- testsuite/features/build_validation/init_clients/ubuntu2004_ssh_minion.feature
- testsuite/features/step_definitions/command_steps.rb
Removing the import of GPG key for each client in our BV test suite, before we bootstrap it.
Related to https://github.com/SUSE/spacewalk/issues/13525
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Remove workaround for bug bsc#1181847

- java/code/src/com/suse/manager/reactor/messaging/LibvirtEngineDomainLifecycleMessageAction.java
- java/code/src/com/suse/manager/webui/controllers/virtualization/AbstractVirtualizationController.java
- java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualGuestsController.java
- java/code/src/com/suse/manager/webui/templates/virtualization/guests/console.jade
- java/code/src/com/suse/manager/webui/utils/TokenBuilder.java
- java/code/src/com/suse/manager/webui/utils/test/TokenBuilderTest.java
- java/code/src/com/suse/manager/webui/websocket/VirtNotifications.java
- java/code/src/com/suse/manager/webui/websocket/json/VirtNotificationMessage.java
- java/code/webapp/WEB-INF/decorators.xml
- java/spacewalk-java.changes
- web/html/src/manager/virtualization/guests/console/MessagePopUp.tsx
- web/html/src/manager/virtualization/guests/console/guests-console-types.js
- web/html/src/manager/virtualization/guests/console/guests-console.css
- web/html/src/manager/virtualization/guests/console/guests-console.js
- web/html/src/manager/virtualization/guests/console/guests-console.renderer.js
- web/html/src/manager/virtualization/guests/console/spice-client.js
- web/html/src/manager/virtualization/guests/console/vnc-client.js
- web/html/src/manager/virtualization/guests/list/guests-list.js
- web/html/src/manager/virtualization/nets/list/nets-list.js
- web/html/src/manager/virtualization/useVirtNotification.js
- web/html/src/manager/virtualization/virtualization-list-refresh-api.js
- web/spacewalk-web.changes
This PR improves the way the virtual console works:
* The console can be opened even if the VM is stopped. In such a case the console will automatically connect once the VM starts.
* The console URL doesn't depend on the virtual host server ID. This means the URL can be used to show the console of the VM wherever it is located. This is useful when the VM is migrated to another host.
* The console doesn't show any error message when the VM is properly shut down
See above.
- No documentation needed: It just makes the console more convenient to use: no need to document it. …
> Virtual console improvements

- testsuite/features/core/srv_channels_add.feature
- testsuite/features/core/srv_create_repository.feature
Reverts uyuni-project/uyuni#3666
As @mcalmer explained, we can't remove this workaround:
This is a test repo signed by a GPG key created by OBS. This is a 3rd Party repo and we never have the GPG key trusted automatically.
Possible solutions: 
1. revert this
2. write a test to "trust" the GPG key. If you do that, you can also enable "metadataSigned" for the RPM test repos.
> Revert "QA: Remove workround on Ubuntu GPG Check"

- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
- java/code/src/com/suse/manager/reactor/test/RegisterMinionActionTest.java
- java/spacewalk-java.changes
Implement a different behavior when onboarding minions under certain conditions.
Introduced because of https://bugzilla.suse.com/1183437
Short: change the way we handle registration requests of minions when a similar system already exists in the DB.
Main changes: when a system with the minion_id already exists we aborted in the past. Now we try to cleanup the DB by deleting conflicting systems.
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/933
- Unit tests were added/updated
Fixes https://github.com/SUSE/spacewalk/issues/14261 …
> Easier recycling systems

- testsuite/features/step_definitions/command_steps.rb
We were relying on the scap-security-guide installed on the client, instead of using the package provided by our client tools.
This PR installs them from client tools, as we previously enabled the client tools repositories.
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/14754
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/14755
> QA: Installing the correct scap-security-guide package from client tools

- testsuite/features/secondary/min_ansible_control_node.feature
- testsuite/features/secondary/minssh_ansible_control_node.feature
- testsuite/features/step_definitions/navigation_steps.rb
This PR fixes the current failures in the Ansible cucumber scenarios after latest changes.
No difference.
- No documentation needed: **testsuite**
> Testsuite: Fix cucumber Ansible tests

- java/code/src/com/redhat/rhn/domain/action/ActionFactory.java
- java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/org/OrgHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/org/trusts/OrgTrustHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/org/trusts/test/OrgTrustHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/audit/CVEAuditManager.java
- java/code/src/com/redhat/rhn/manager/audit/test/CVEAuditManagerTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/DailySummary.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/webapp/WEB-INF/nav/system_detail.xml
- java/code/webapp/WEB-INF/pages/systems/spmigration/spmigration-target.jsp
- java/code/webapp/WEB-INF/struts-config.xml
- java/spacewalk-java.changes
- schema/spacewalk/common/data/rhnActionType.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.2.9-to-susemanager-schema-4.2.10/400-rename-service-pack-migration.sql
- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/org.py
- spacecmd/src/spacecmd/system.py
- spacecmd/tests/test_org.py
- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/secondary/trad_product_migration.feature
Rename `SP` Migration to `Product` Migration
Rename `Migrate` Systems to `Transfer` Systems
Add new methods for `Product Migration` to spacecmd and XMLRPC API
and deprecate `SP Migration` methods
**Product Migration:**
**Transfer Systems:**
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/14491
- No tests: Just a rename shouldn't break any existing tests
Tracks https://github.com/SUSE/spacewalk/issues/14491
> Sp to product migration

- susemanager-utils/susemanager-sls/src/tests/test_beacon_pkgset.py
Fix for test unit of `pkgset` beacon from PR https://github.com/uyuni-project/uyuni/pull/3645
No difference.
- Unit tests were fixed
Fix for test unit related to this PR https://github.com/uyuni-project/uyuni/pull/3645
> Fix for pkgset beacon test

- testsuite/features/secondary/min_config_state_channel.feature
> Fix testsuite Apply button rename

- java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
- java/spacewalk-java.changes
- utils/cloneByDate.py
- utils/spacewalk-utils.changes
Not aligning the modules.yaml in this situation is wrong, since the source modules.yaml of the source can get updated, whereas the modules.yaml of the target still stays the same and might get incorrect for the new state of the channel.
Aligning the modules.yaml (this PR) is also wrong: if the clone-by-date tool is executed with a date "far in the past", then the modules.yaml of the source might be incorrect for the new state of the clone, since it contains references to packages that were filtered out when cloning.
While both approaches are wrokng, I believe aligning the metadata is "less wrong".
In general, this problem might be insolvable, since we don't control the generating of the modules.yaml.
Maybe instead of this fix, we only need to update the documentation.
- No tests: **add …
> When using the clone-by-date tool, the modules.yaml of the target channel is not aligned to the source.

- testsuite/features/step_definitions/navigation_steps.rb
- web/html/src/components/combobox.tsx
- web/html/src/components/input/Select.tsx
- web/html/src/manager/content-management/shared/components/panels/sources/channels/channels-selection.js
Follow the idea from https://ryanbigg.com/2020/09/react-select-capybara-selenium to make the react-select xpath expression more robust in the cucumber steps. Also applies the portalling fix to other uses of react-select.
No difference.
> More robust react-select cucumber tests

- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java
- java/spacewalk-java.changes
Fix incorrect boot image url - without this url saltboot fails to set up local boot.
Change default protocol to ftp - the same is used for system images
No difference.
- covered by openQA tests
Fixes https://github.com/SUSE/spacewalk/issues/14747 
https://bugzilla.suse.com/show_bug.cgi?id=1185509
> Fix boot image url, change default to ftp (bsc#1185509)

- susemanager-utils/susemanager-sls/susemanager-sls.changes
- susemanager-utils/susemanager-sls/susemanager-sls.spec
Switching from GPLv2 to Apache 2.0. One file still remains LGPLv2.1 though.
No difference.
- No documentation needed: I don't think we have that in the documentation.
- No tests: Just a license change.
Fixes https://github.com/SUSE/spacewalk/issues/11589
> License change for susemanager-sls

- testsuite/features/secondary/min_ansible_control_node.feature
- testsuite/features/secondary/minssh_ansible_control_node.feature
This PR simply add a "login" scenario to the Ansible cucumber tests to keep consistency with other features.
This is not strictly needed when the testsuite is executed entirely but it's helpful when running features tests in an isolate way to avoid auth problems.
No difference.
> Testsuite: Add login scenario for Ansible cucumber tests

- testsuite/features/secondary/min_ansible_control_node.feature
- testsuite/features/secondary/minssh_ansible_control_node.feature
This PR disables the Ansible feature tests for Uyuni since they're going to fail until SUMA 4.1.8 is released.
No difference.
> Testsuite: only execute Ansible feature tests on SUSE Manager

- susemanager-utils/susemanager-sls/salt/services/salt-minion.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Ensure in highstate that `/etc/sysconfig/rhn/systemid` exists in order to indicate that salt client is managed by Uyuni/SUMA.
Proxies and traditional clients have this file present, only regular salt clients were missing it.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/14621
> Ensure systemid file exists to indicate minion is managed by Uyuni

- java/code/src/com/suse/scc/client/SCCFileClient.java
- java/spacewalk-java.changes
Fixes a problem where we try to read the product tree file from the root directory of a offline setup while RMT puts it in a suma subdirectory. We keep the old location as a fallback since customers with working setups might have moved the file manually.
No difference.
- No tests: 
Fixes https://github.com/SUSE/spacewalk/issues/14467
> read product tree also from suma/ subdirectory in offline setups (bsc#1184283)

- testsuite/features/step_definitions/command_steps.rb
When the user adds/removes a package on a client, Salt automatically triggers a package list refresh.
But in that case, the action is triggered by `(none)`. Our wait step was waiting for an action triggered by `admin`.
This PR makes the test not care about who triggered the action.
Ports:
* 4.0: SUSE/spacewalk#14770
* 4.1: SUSE/spacewalk#14771
> Accept package list refresh scheduled by (none)

- susemanager/bin/pg-migrate-10-to-12.sh
- susemanager/bin/pg-migrate-12-to-13.sh
- susemanager/susemanager.changes
removes useless message about backup displayed
No difference.
Before:
After:
fixes bsc#1183080 issue#14190 …
> remove useless message about backup displayed

- java/code/src/com/suse/manager/webui/controllers/AnsibleController.java
- java/spacewalk-java.changes
- web/html/src/manager/minion/ansible/accordion-path-content.tsx
- web/spacewalk-web.changes
Parse Inventory content to distinguish already registered and managed systems against Uyuni or unknown hostnames.
No difference.
Before:
After:
- No documentation needed: included in ansible documentations
Fixes # https://github.com/SUSE/spacewalk/issues/14753
> Master: ansible inventory parsing to show registered systems

- java/code/src/com/redhat/rhn/manager/contentmgmt/FilterTemplateManager.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/FilterApiController.java
Minor fix to prepend the specified prefix to the filter names.
> Fix filter template prefix generation

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minssh_salt_install_package.feature
- testsuite/features/secondary/srv_scc_user_credentials.feature
- Use a different step to click in a modal, when deleting a SSC User
- Missing navigation to the sshminion page, before install a package
- Missing navigation to the virtualization section, before deleting the VM
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Fix some navigation issues

- susemanager-utils/testing/automation/obs-project.py
- susemanager-utils/testing/automation/publish-rpms.sh
Adding the availability for the CI to publish the RPMS in the jenkins node where they run.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/14626
> CI: Publish rpms in jenkins node

- java/code/src/com/redhat/rhn/domain/channel/Channel.hbm.xml
- java/spacewalk-java.changes
Improve query to load dropdown in channel add package
No difference.
Before:
After:
- No tests: query improvement
Fixes https://github.com/SUSE/spacewalk/issues/13117
Tracks …
> improve channels dropdown in add packages page

- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/step_definitions/command_steps.rb
Follow-up of #3704 (thanks Tino for the analysis of the problem).
Wait for the package list refresh right after the SP migration.
The SP migration fully completes once a package list refresh finish; only
after that, the client overview page will show the migrated products.
Ports:
* 4.0:
* 4.1:
> Fix migration on SSH minion

- testsuite/features/step_definitions/command_steps.rb
Follow-up of #3673 Installing the correct scap-security-guide package from client tools.
We should not install two conflicting SSGs.
Ports:
* 4.0:
* 4.1:
> Don't install two SCAP Security guides on Ubuntu

- web/html/src/manager/content-management/list-filters/filter-form.tsx
- web/spacewalk-web.changes
Fix endless loop in filter-form hooks usage.
No difference.
- No tests: Get the fix merged, will add unit tests in a follow-up PR.
No ticket, came up in daily meeting.
> Resolve race condition issues

- susemanager-utils/testing/automation/publish-rpms.sh
- susemanager-utils/testing/automation/push-to-obs.sh
- web/.yarnrc
Build packages in parallel, going from 18-20 minutes to 5 minutes!
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/14762
> CI: Build each package in a docker container in parallel

- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/features/secondary/srv_docker_cve_audit.feature
- testsuite/run_sets/secondary.yml
- testsuite/run_sets/secondary_parallelizable.yml
Rolling back some features as we found a dependency with CVE Audit tests, therefore they can't go to the parallel tests.
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/14830
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/14829
> QA: Go back some features are they are dependency of others

- testsuite/features/support/env.rb
Due to the change of paradigm to follow (where we keep the browser session throughout the Cucumber feature), when a scenario fails we must try to recover the state we need in the next scenario.
This fix is ​​temporary, because actually, what I think we should do is skip the rest of the scenarios until we reach the cleanup scenarios (adding a new `@cleanup` tag to identify them).
At the moment we do this fix, we will discuss the correct solution when we have Head CI stable/greener.
No difference.
Ports:
- Manager-4.0
- Manager-4.1 …
> QA: Recovering from a failed scenario

- testsuite/features/step_definitions/navigation_steps.rb
Fix exporters checkbox selection, now the node exporter checkbox is by default enabled and with this fix it doesn't fail anymore the test.
No difference.
Fixes No issue, directly fixed by head review
Tracks
4.1: https://github.com/SUSE/spacewalk/pull/14834
4.0: https://github.com/SUSE/spacewalk/pull/14835
> Fix exporters checkbox selection

- java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
- java/spacewalk-java.changes
Add the missing elaborators to list the correct information on the proxy page. Currently, we are showing default values for some columns.
Before:
After:
- No documentation needed: Display the correct icons
Fixes # https://github.com/SUSE/spacewalk/issues/14774
> Add the missing elaborators to list the correct information on the proxy page

- testsuite/features/secondary/buildhost_osimage_build_image.feature
Fixing a navigation step to click on Clear SSM button.
On previous PRs we were starting the scenario from the homepage, that's not any more true, as now we keep the web browser session for the whole session, so we must assure to move to the proper page. In that case, we were finding an element with value "Clear" while we were in a page with a hyperlink that has a text "Clear" so... we had an ambiguity.
No difference.
Ports:
- Manager-4.0
- Manager-4.1 …
> QA: Fix navigation step to Clear SSM button

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/client_stack.rb
This PR aims to catch a flaky test related to OS Family by adding more logs into a method.
Also, it will raise an exception if the OS Family is not supported inside a step definition related to OpenScap packages
No difference.
- Cucumber tests were change
Ports:
- Manager-4.0
- Manager-4.1
> QA: Adding more log when extracting OS Family

- utils/spacewalk-hostname-rename
- utils/spacewalk-utils.changes
spacewalk-hostname-rename test for configured hostnames before it starts.
It check various files like /etc/hostname, /etc/HOSTNAME and /etc/sysconfig/network and expect the FQDN there.
But often they should contain the short hostname only according to man pages. But they can deal also with FQDNs.
So just allow both.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/12429
Tracks 
> Fix hostname rename check

- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes
reprepro is picky with packages having the same name, but different checksums.
To avoid aborting, we copy the old packages to debs, add or overwrite them
with new found packages and run reprepro again (bsc#1184330)
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/14499
Tracks https://github.com/SUSE/spacewalk/pull/14777
> Ubuntu bootstrap repo fixes

- web/html/src/utils/test-utils/forms.ts
- web/html/src/utils/test-utils/index.ts
- web/html/src/utils/test-utils/server.ts
Cleans up the test-utils directory to be a bit less everything-in-one-file.
No difference.
> Clean up JS test utils

- search-server/spacewalk-search/spacewalk-search.changes
- search-server/spacewalk-search/src/java/com/redhat/satellite/search/scheduler/tasks/GenericIndexTask.java
- search-server/spacewalk-search/src/java/com/redhat/satellite/search/scheduler/tasks/IndexErrataTask.java
- search-server/spacewalk-search/src/java/com/redhat/satellite/search/scheduler/tasks/IndexPackagesTask.java
The indexer job is executed every 5 Minutes. When a job takes longer, a second instance is started and try to get the Lock.
This fail and result in an error message in the journal.
This PR try to catch the exception and write a simple message into the log "Indexer already running. Skipping".
This should prevent missunderstanings as this is not an error.
No difference.
- No tests: **lost logging changes**
Fixes https://github.com/SUSE/spacewalk/issues/14781
Tracks https://github.com/SUSE/spacewalk/pull/14864 …
> Prevent exception when skipping indexer

- java/code/webapp/WEB-INF/nav/system_detail.xml
- java/spacewalk-java.changes
When clicking in the Systems Details page of a Minion on Provisioning Tab, 2 sub menus are visible:
Autoinstallation and Power Management .
When you now click on "Power Management" the Autoinstallation become invisible.
This PR fix this problem.
In the past "Autoinstallation" was not supported for Minions. This has changed a while ago, but this menu workaround was not removed.
After:
- No tests: **minimal change**
Fixes https://github.com/SUSE/spacewalk/issues/14623
Tracks https://github.com/SUSE/spacewalk/pull/14866 …
> Fix provisioning menu

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
- susemanager-utils/susemanager-sls/salt/channels/disablelocalrepos.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Implements the possiblity to set DISABLE_LOCAL_REPOS=0 in the bootstrap script to prevent disabling local repos on the salt minions like it works for the traditional clients.
Adds missing SALT_RUNNING environment variable to salt minion config to prevent duplicated package list refreshes.
No difference.
Fixes bsc#1185568
https://jira.suse.com/browse/PM-2615
- Add support of DISABLE_LOCAL_REPOS=0 for salt minions (bsc#1185568)
- Add missing environment variable SALT_RUNNING for pkg module
to the minion configuration
- Add support for 'disable_local_repos' salt minion config parameter
(bsc#1185568)
> Add support of DISABLE_LOCAL_REPOS=0 in the bootstrap script for salt minions (bsc#1185568)

- utils/spacewalk-hostname-rename
- utils/spacewalk-utils.changes
When renaming the Uyuni Server, replace the hostname also in /root/.mgr-sync config file.
Delete also old tokens to require a new authentication.
No difference.
- No tests: **not tested**
Fixes https://github.com/SUSE/spacewalk/issues/14414
Tracks https://github.com/SUSE/spacewalk/pull/14865
> Hostname rename for mgr sync

- java/code/src/com/redhat/rhn/common/util/FileUtils.java
- java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java
- java/code/src/com/suse/manager/webui/services/pillar/MinionPillarFileManager.java
- java/spacewalk-java.changes
- susemanager-utils/testing/docker/master/uyuni-master-pgsql/Dockerfile
This pr makes sure that all pillar data written to `/srv/susemanager/pillar_data/`  is set with the correct owner/group/permissions to that files remain readable independent of it they were written by tomcat or taskomatic. In addition this also restricts read access to owner/group only since pillar data might contain sensitive data.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/13456
> ensure file owner/group and permissions when writing pillars (bsc#1179954)

- testsuite/features/secondary/srv_menu.feature
- testsuite/run_sets/secondary.yml
- testsuite/run_sets/secondary_parallelizable.yml
The srv_menu Cucumber feature can't go to our parallel tests set, as the feature checks UI Menu and their content, expecting that everything is empty. If we run this in parallel, it will randomly fail.
We could improve this feature to only check static UI content, but for now, we will just move it to the sequential set of tests, as we might need a discussion for the other approach.
No difference.
- Cucumber tests were moved
Ports:
- Manager-4.0
- Manager-4.1
> QA: Moving srv_menu to sequential test set

- susemanager-utils/testing/automation/spacewalk-pylint.sh
Return the correct return code for spacewalk-pylint.sh. `|| :` caused that `0` was always returned.
Now tests will fail until https://github.com/uyuni-project/uyuni/pull/3449 is merged.
No difference.
- No documentation needed: Bugix for the tests
- Bugfix for the tests.
Related:  https://github.com/uyuni-project/uyuni/pull/3449
> Return the correct return code for spacewalk-pylint.sh

- java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemGroup_queries.xml
- java/spacewalk-java.changes
Add group by clause to reduce the number of rows for groupAdvisoryTypes CTE to improve the performance.
No difference.
- [x ] **DONE**
Fixes # https://github.com/SUSE/spacewalk/issues/14629
> Add group by clause to reduce the number of rows for groupAdvisoryTypes CTE to improve the performance

- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE-Bug.md
- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE-enhancement.md
- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE-question.md
Issue templates can assign lables. Use this to differentiate between Bugs, Feature Requests and Questions.
No difference.
- No tests: **templates**
> add issue templates with basic labels

- testsuite/.rubocop_todo.yml
- testsuite/features/support/client_stack.rb
Do not use variable before it is defined, fix error here https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/230/testReport/junit/(root)/Setup%20SUSE%20Manager%20for%20Retail%20branch%20network/Enable_repositories_for_installing_branch_services/
No difference.
Fixes no issue, fixes previous 
> Do not use variable before it is defined

- spacewalk/admin/spacewalk-admin.changes
- spacewalk/admin/spacewalk-admin.spec
We use pidof which is not anymore installed by default. So we need to explicit require it.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/14900
> Manager 4.2 rc1 require pidof

- testsuite/features/support/client_stack.rb
Fix get_os_version return nil instead of raise because when we call the method we expect nil, nil instead of a raise. Without this it doesn't work. Also the `false` is needed to use it as array instead of string
No difference.
Fixes #
> Fix get_os_version return nil instead of raise

- testsuite/features/secondary/min_centos_monitoring.feature
- testsuite/features/secondary/min_monitoring.feature
- testsuite/features/secondary/srv_monitoring.feature
- testsuite/run_sets/secondary.yml
- testsuite/run_sets/secondary_parallelizable.yml
This PR moves the "monitoring" feature to the sequential list of tests, as it performs a restart of spacewalk-services.
It also documents its dependencies and reorders some other tests in the sequential list.
Related to https://github.com/SUSE/spacewalk/issues/11967
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/14911
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/14912
> QA: Monitoring feature can't run in parallel (restart services)

- testsuite/features/secondary/buildhost_docker_auth_registry.feature
The build image for a Docker profile needs more time, so we increase the timeout from 500 seconds to 600.
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: The build image for a Docker profile needs more time

- testsuite/features/secondary/min_retracted_patches.feature
The new way is the one used in min_salt_install_package.feature.
No difference.
- fix
- Cucumber tests updated
> Replace the waiting for package installation in retracted patches

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/reposync/srv_sync_products.feature
We get sometimes failures, especially in the build validation test suite, when products page had not the time to finish loading.
This PR waits until the "Loading" text has gone. It also cleans up the `When`/`Then`/`And` sequence in the affected files.
Note: it might be we need to add `, refreshing the page` clause in a second PR. That was impossible for me to test.
Ports:
* 4.0: SUSE/spacewalk#14915
* 4.1: SUSE/spacewalk#14913
> Wait until products page is loaded

- java/code/src/com/redhat/rhn/common/util/DateFormatTransformer.java
- java/code/webapp/WEB-INF/pages/systems/details/audit/xccdfdetails.jsp
- java/spacewalk-java.changes
Fixes the report links in `System` -> `Audit` -> `List Scans`
As well as the start/end timestamps displayed in `xccdf scan` details
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/14895
Tracks https://github.com/SUSE/spacewalk/issues/14896
> Fix scap audit issues

- backend/common/repo.py
- backend/spacewalk-backend.changes
Fixes GPG checking on synchronizing mirrored dpkg repo.
The following traceback appears on synchronizing mirrored dpkg repo if GPG check is enabled:
```
2021/04/02 04:14:00 +02:00 Unhandled error occurred: [Errno 2] No such file or directory: '/mirror/repo/RPMMD/ubuntu-2004-amd64-universe/Packages.gz'
2021/04/02 04:14:00 +02:00 Unexpected error: <class 'FileNotFoundError'>
2021/04/02 04:14:00 +02:00 Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 572, in sync
client_key_file=client_key_file)
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line 277, in __init__
self.repo.verify()
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/deb_src.py", line …
```
> Fix for GPG checking on synchonizing mirrored dpkg repo (bsc#1184351)

- proxy/proxy/salt-broker/salt-broker
- proxy/proxy/spacewalk-proxy.changes
Prevents stopping publishing messages on XPUB socket in salt-broker XPUB<->XSUB proxy.
In some cases XPUB stops publishing messages after stopping one of the minions behind a proxy.
It could happen even if the minion is behind a chain of 2 (or probably more) proxies.
It also prevents messages in `journald` about deprecated way of calling `yaml.load`.
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```
No difference.
- No tests: it's not possible to reproduce the issue in test environment.
Fixes `bsc#1182954`
- prevent stopping publishing messages on XPUB socket of salt-broker
(bsc#1182954)
- using …
> Prevent stopping publishing messages on XPUB socket

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/utils.py
- spacecmd/tests/test_utils.py
https://github.com/uyuni-project/uyuni/issues/3525
Let `spacecmd` parse empty arguments when there is nothing between the _item list separator_ . 
No difference.
- No tests: adapted and added
Fixes # https://github.com/uyuni-project/uyuni/issues/3525
> Let spacecmd parse empty|null parameters

- backend/server/configFilesHandler.py
- backend/server/test/unit-test/test_ConfigFilesHandler.py
- backend/spacewalk-backend.changes
- backend/test/docker-backend-server-tests.sh
- susemanager-utils/testing/automation/backend-unittest-pgsql.sh
Don't decode binary blobs into str
No difference.
Before:
After:
Fixes #
> Fix format file results binary blobs

- web/html/src/components/panels/InnerPanel.tsx
- web/html/src/manager/maintenance/list/maintenance-windows-list.tsx
- web/html/src/manager/minion/ansible/schedule-playbook.tsx
- web/html/src/manager/state/recurring-states-list.tsx
Hide the `Spacewalk Section Toolbar` if it has no children to render
Before:
After:
- No tests: UI bugfix
Fixes # https://github.com/SUSE/spacewalk/issues/13756
> Do not render the section toolbar if nothing is expected

- backend/common/rhnLog.py
- backend/spacewalk-backend.changes
- backend/spacewalk-backend.spec
This is a port of https://github.com/SUSE/spacewalk/pull/14827
Changes the rhnLog to use just the www instead of root group to match the logrotate 
#14651 
https://bugzilla.suse.com/show_bug.cgi?id=1185097
Port of # **remove rest of file if this is a port**
No difference.
Before:
After: …
> bsc1185097 fix logrotate perms 

- testsuite/features/secondary/min_ansible_control_node.feature
- testsuite/features/secondary/min_salt_openscap_audit.feature
- testsuite/features/secondary/minssh_ansible_control_node.feature
- testsuite/features/secondary/trad_openscap_audit.feature
Add LTSS repo before trying to install openscap or ansible because for older than 15sp2 the scap-security-guide is only in LTSS and it will be the case for ansible as well when we release.
No difference.
Fixes No issue, directly from RRTG review
> Add LTSS repo before trying to install openscap or ansible

- web/html/src/manager/virtualization/guests/console/guests-console.js
- web/html/src/manager/virtualization/nets/network-properties.js
- web/html/src/manager/virtualization/nets/virtualization-network-devs-api.js
- web/spacewalk-web.changes
Update the JWT token before it expires in the virtual machine graphical console. This avoids authentication errors when refreshing it after it expired.
No difference.
Fixes #
> virtual console: update JWT token before it expires

- testsuite/features/secondary/min_ubuntu_openscap_audit.feature
- testsuite/features/step_definitions/command_steps.rb
This PR enables the Universe repository in the OpenScap test for Ubuntu.
As for Uyuni, the libopenscap8 is only available there.
In SUMA we have it available from the client tools, but in any case, we will not make a difference here and we will enable this repository for both cases.
No difference.
Ports:
- Manager-4.0
- Manager-4.1
> QA: Add Universe repository for Ubuntu in Openscap test
