uyuni-project/uyuni

testsuite/features/secondary/min_centos_openscap_audit.feature, testsuite/features/secondary/min_salt_openscap_audit.feature, testsuite/features/secondary/min_ubuntu_openscap_audit.feature, testsuite/features/secondary/trad_centos_client.feature, testsuite/features/secondary/trad_openscap_audit.feature, testsuite/features/step_definitions/navigation_steps.rb
It adds a step waiting for 30 seconds, refreshing the page, until the OpenSCAP feature is available.
No difference.
Ports:
- Manager-4.0
- Manager-4.1
=> QA: Enforce a check to have OpenSCAP available before start using it

java/code/src/com/redhat/rhn/domain/entitlement/VirtualizationEntitlement.java, java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java, java/spacewalk-java.changes
A Xen virtualization host has the `virtual` grain set to `xen` and an
additional `virtual_subtype` set to `Xen Dom0`. Handle this case when
checking if the virtualization host entitlement is allowed.
No difference.
- No tests: would be too heavy to add
Fixes https://github.com/SUSE/spacewalk/issues/14807
=> Allow Xen Dom0 to have virthost entitlement

susemanager-utils/susemanager-sls/salt/virt/network-statechange.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Don't fail when deleting a virtual network that is stopped.
No difference.
- No tests: would require more cucumber tests that almost duplicate existing ones.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1186281
=> Fix deleting stopped virtual network

java/code/src/com/suse/manager/maintenance/MaintenanceWindowData.java, web/html/src/manager/maintenance/details/schedule-details.tsx
Don't display the web calendar in schedule details if the schedule has no maintenance calendar selected.
Remove some unused code from `MaintenanceWindowData`
=> Web calendar fix

java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemHardwareAction.java, java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerCommand.java, java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerSystemCreateCommand.java, java/code/webapp/WEB-INF/pages/systems/sdc/hardware.jsp, java/spacewalk-java.changes
Empty profiles created by `system.createSystemProfile` API call does not have complete information about what the hardware of bootstrapped will be. This includes network information such as IP address.
However MAC address, necessary for PXE booting can be provided.
This PR enabled cobbler integration to pass system mac address so autoinstallation pxe configuration can be created for the empty system profile.
Together with above mentioned change this PR also adds network interfaces without assigned IPv4 and IPv6 addresses in Hardware tab.
Before:
After: …
=> Allow empty system profiles in cobbler

backend/spacewalk-backend.spec, client/rhel/dnf-plugin-spacewalk/dnf-plugin-spacewalk.spec, client/rhel/spacewalk-client-tools/spacewalk-client-tools.spec, java/spacewalk-java.spec, proxy/proxy/spacewalk-proxy.spec, schema/spacewalk/susemanager-schema.spec, search-server/spacewalk-search/spacewalk-search.spec, spacecmd/spacecmd.spec, spacewalk/certs-tools/spacewalk-certs-tools.spec, susemanager-utils/susemanager-sls/susemanager-sls.spec, susemanager/susemanager.spec, utils/spacewalk-utils.spec, web/spacewalk-web.spec
Pass the spec linter to some packages, as requested by autobuild.
We are only changing packages that are to be submitted for SUSE Manager 4.2 GMC. The rest will come later.
For the packages used by client tools, I am defining `%license` if it doesn't exist, as we need to stay compatible with old OS.
This is WIP and merge candidate because:
- Needs to be merged before we submit GMC
- But we shouldn't merge before we check what packages we'll be submitting for GMC.
No difference.
- No documentation needed: SPEC change
- No tests: The packages are able to build locally
Tracks: https://github.com/SUSE/spacewalk/issues/14840 and https://github.com/SUSE/spacewalk/issues/14841 …
=> Pass the spec linter to some packages

testsuite/features/step_definitions/navigation_steps.rb
Fix clicking in a button inside a modal. By finding without filtering by title parameter.
No difference.
Ports:
- Manager-4.0
- Manager-4.1
=> QA: Fix clicking in a button inside a modal

testsuite/features/support/commonlib.rb
This PR fixes the function that generates a unique repository name:
It transforms *all* `/` to `_`, not only the *first one* (`gsub!` instead of `sub!`).
=> Fix generation of unique repository name

testsuite/features/support/twopence_init.rb
Scenarios for debian 9 and 10 were not executed. This PR adds the missing initialization for the corresponding minions.
Ports:
* 4.0: SUSE/spacewalk#14999
* 4.1: SUSE/spacewalk#14998
=> Added debian 9 and debian 10 minions

testsuite/features/support/constants.rb
This PR fixes the base channel for Debian bootstrap repositories.
Ports:
* 4.0: SUSE/spacewalk#15018
* 4.1 SUSE/spacewalk#15017
=> Fix bootstrap repository for Debian

testsuite/features/build_validation/init_clients/proxy.feature, testsuite/features/core/proxy_register_as_minion_with_gui.feature, testsuite/features/core/proxy_register_as_minion_with_script.feature, testsuite/features/core/proxy_register_as_trad_with_script.feature, testsuite/features/step_definitions/salt_steps.rb
This PR:
* cleans up the package `spacewalk-proxy-salt` holding the salt broker when we do a full salt cleanup
* handles the debian case
* tests that the `salt-broker` service is properly started
Ports:
* 4.0: SUSE/spacewalk#15027
* 4.1: SUSE/spacewalk#15026
=> Fix salt proxy cleanup

testsuite/features/step_definitions/common_steps.rb
This PR adds a test for debian instead of only ubuntu.
It is likely we have other such problems.
Ports:
* 4.0: SUSE/spacewalk#15031
* 4.1: SUSE/spacewalk#15030
=> Missing Debian test

testsuite/features/build_validation/smoke_tests/smoke_tests.template, testsuite/features/support/env.rb
- Enabling installation of patches for SLES15 SP3
- Fixing a missing navigation step for salt minions
No difference.
Port:
- Manager-4.0
- Manager-4.1
=> BV: Enable patches for SLES15 SP3

testsuite/features/build_validation/smoke_tests/smoke_tests.template, testsuite/features/support/constants.rb, testsuite/features/support/env.rb
This PR fixes various problems:
* we can't test patching on Debian, the notion does not exist
* there is no "bison" nor "autoconf" package to test on Debian - use "joe" instead"
* there is no need to go to "Details" to choose "Configuration" on the top menu
Ports:
* 4.0:
* 4.1:
=> Various build validation fixes

testsuite/features/support/constants.rb
Partial revert of previous PR.
Sorry, I did not realize I already installed "bison" in a previous run.
Ports:
* 4.0: SUSE/spacewalk#15054
* 4.1: SUSE/spacewalk#15053
=> BV: Revert default package name to bison

java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml, java/code/src/com/redhat/rhn/common/finder/test/JarFinderTest.java, java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java, java/spacewalk-java.changes, java/spacewalk-java.spec
We are trying to use as many libraries as possible from Leap repositories, only where we actually need a newer version than the one available from Leap or if the package is not available at all we would take it from Uyuni repos. With Leap 15.3 some libraries have been updated and this patch should update them for development environments and CI.
No difference.
- No documentation needed, affects only development environments.
- No tests needed, only affects development environments.
Fixes downstream issue: https://github.com/SUSE/spacewalk/issues/12357 …
=> Update libraries and resolve from Leap 15.3

spacecmd/spacecmd.changes, spacecmd/src/spacecmd/distribution.py
The spacecmd help for distribution_create has only a very old and outdated list of installation types.
Drop old types and add new once for currently used distributions.
No difference.
- No documentation needed: just help update
- No tests: **just help update**
Fixes https://github.com/SUSE/spacewalk/issues/15034
Tracks 
=> Spacecmd fix dist help

java/code/src/com/redhat/rhn/frontend/action/help/DocSearchSetupAction.java, java/spacewalk-java.changes
When searching the docs as a logged-in user a Internal Server Error was the result.
The search works when searching without log-in.
The reason is, that the local is `null` when the user did not explicit select a language for the docs.
The code needs to fallback to the default locale.
No difference.
- No tests: minor
Tracks https://github.com/SUSE/spacewalk/pull/14979
=> Fix doc search

java/code/src/com/suse/manager/reactor/messaging/RefreshGeneratedSaltFilesEventMessageAction.java, java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java, java/spacewalk-java.changes
Explicitly sets user/group/permissions for files generated in  /srv/susemanager/salt/custom for the case its run as root from taskomatic.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/14956
=> set file user/group/permissions for /srv/susemanager/salt/custom (bsc#1186325)

susemanager-utils/susemanager-sls/salt/bootstrap/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes an issue on the "bootstrap" state when configuring the boostrap repository on the instances that are bootstrapped via webUI/API.
The previous code was wrongly assuming Amazon Linux bootstrap repository for RHEL and AlmaLinux instances.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/15072
=> Do not assume Amazon bootstrap repo on RHEL and AlmaLinux instances (bsc#1186703)

web/html/src/build/fill-spec-file.js, web/html/src/manager/images/image-build.tsx, web/html/src/manager/images/image-profiles.tsx, web/html/src/manager/images/image-view.tsx, web/spacewalk-web.changes
Adds optional chaining for image building UI, fixing https://bugzilla.suse.com/show_bug.cgi?id=1186728  
Also fixes an unrelated lifecycle bug I found on the way.
No difference, except now you actually see the UI.
Fixes https://github.com/SUSE/spacewalk/issues/15076 and https://bugzilla.suse.com/show_bug.cgi?id=1186728
=> Fix image building UI

testsuite/features/step_definitions/common_steps.rb
Enable LTSS repo before installing branch server
No difference.
Fixes failure of 4.0 CI, no issue, directly from review
Tracks 4.1: https://github.com/SUSE/spacewalk/pull/15108
4.0: https://github.com/SUSE/spacewalk/pull/15107
=> Enable LTSS repo before installing branch server

testsuite/features/profiles/Docker/add_packages.sh, testsuite/features/profiles/internal_nue/Docker/add_packages.sh, testsuite/features/profiles/internal_prv/Docker/add_packages.sh
After the fixes for (bsc#1167586) (bsc#1164192) in Salt [1], now the containers are not longer requiring Python 2 in order to inspect the image.
This PR fixes the testing containers to not install `python` and `python-xml` since these are not required anymore.
[1] https://github.com/openSUSE/salt/commit/271826b0baa6b2281bc2eac9118a0fcc4675f106
No difference.
- Documentation issue was created: https://github.com/uyuni-project/uyuni-docs/pull/970
Tracks https://github.com/SUSE/spacewalk/issues/11072 …
=> Testsuite: Do not install "python2" in testing containers (bsc#1167586) (bsc#1164192)

java/code/src/com/redhat/rhn/common/db/datasource/xml/Channel_queries.xml, java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java, java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java, java/spacewalk-java.changes
refactoring to run tables analyze in CLM
During build validation tests a CLM project was created to flat centos repository. The build action of that project cause Postgres to be using 100% CPU and got stuck in one specific query. Run that query outside CLM process was really fast and uses all expected indexes.
As a side-effect, Uyuni server got completely unusable, and UI unresponsible.
This PR aims to solve this performance problem by running a database table analyze in the more used CLM tables during build.
Fix For: https://bugzilla.suse.com/show_bug.cgi?id=1186704
No difference.
Before:
After:
- No documentation needed: only internal and user …
=> Force reanalysis of rhnChannelPackage earlier (bsc#1186704)

susemanager-utils/susemanager-sls/salt/channels/gpg-keys.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Make sure Amazon Linux 2 trusts cento7 GPG GPG when bootstraping. 
No difference.
Before:
After: …
=> Accept GPG key for res7tools channel (bsc#1187102)

testsuite/features/build_validation/smoke_tests/smoke_tests.template
`spacecmd` is an important utility that must be installable.
As `spacecmd` comes from the client tools, this PR also tests
the GPG key for the client tools at the same time.
Ports:
* 4.0:
* 4.1:
=> Try to install spacecmd

susemanager-utils/susemanager-sls/salt/packages/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Leap has SLES product packages in its repos which cannot be installed.
For now do not run the product install check on Leap 15.3. As this product is free, it is not important for subscription matching.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/15105
Tracks
=> Skip product install on leap

java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java, java/code/src/com/suse/manager/utils/SaltUtils.java, java/spacewalk-java.changes
Problems fixed:
- Pass 'allowVendorChange' correctly when the migration is scheduled from the completed event page of a dry-run
- ~~Revert client's assigned channels when migration is failed for some reason~~ (needs more consideration in the future)
- Cucumber tests needed
Fixes https://github.com/SUSE/spacewalk/issues/15131
=> Fix product migration when scheduled from the event page (bsc#1187066)

testsuite/features/build_validation/init_clients/sle12sp5_client.feature, testsuite/features/build_validation/init_clients/sle12sp5_minion.feature, testsuite/features/build_validation/init_clients/sle12sp5_ssh_minion.feature, testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/support/env.rb, testsuite/features/support/twopence_init.rb, testsuite/run_sets/build_validation_init_clients.yml
Add Cucumber features to support SLES12SP5 onboarding and test. This is a partial PR, the rest was made some time ago [here](https://github.com/uyuni-project/uyuni/pull/3338) 
**Depends on** : Support inside sumaform (https://github.com/uyuni-project/sumaform/pull/899)
No difference.
Ports:
- Manager-4.0
- Manager-4.1
=> BV: Add support for sle12sp5

spacewalk/certs-tools/spacewalk-certs-tools.changes, spacewalk/certs-tools/sslToolConfig.py
Without this patch, customers will just see a
stacktrace when answering the wrong option during
configure-proxy process.
Before:
```
ERROR: unhandled exception occurred:
File "/usr/bin/rhn-ssl-tool", line 52, in <module>
sys.exit(mod.main() or 0)
File "/usr/lib/python3.6/site-packages/certs/rhn_ssl_tool.py", line 1335, in main
ret = _main() or 0
File "/usr/lib/python3.6/site-packages/certs/rhn_ssl_tool.py", line 1300, in _main
genServerCert(getCAPassword(options, confirmYN=0), DEFS, options.verbose)
File "/usr/lib/python3.6/site-packages/certs/rhn_ssl_tool.py", line 557, in genServerCert
ser = figureSerial(ca_cert, serial, index_txt)
File "/usr/lib/python3.6/site-packages/certs/sslToolConfig.py", line 480, in figureSerial
assert not ret
AssertionError …
```
=> added an improved error message if exitcode isnt 0

testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature, testsuite/features/support/constants.rb
Detail fixes to:
* the feature to create CLM filters for RedHat appstream data
* the bootstrap repo constants for CentOS 8, Debian 9, and Debian 10
Ports:
* 4.0: SUSE/spacewalk#15163
* 4.1: SUSE/spacewalk#15162, SUSE/spacewalk#15167
=> BV test suite : detail fixes

susemanager/bin/pg-migrate-12-to-13.sh, susemanager/susemanager.changes
This fixes the db migration script from 12 to 13. There was a hardcoded 10 in the path which should have been OLDVERSION variables instead.
No difference.
- No tests
=> fix db migrations script from 12 to 13

susemanager/bin/pg-migrate-10-to-13.sh, susemanager/bin/pg-migrate-12-to-13.sh, susemanager/susemanager.changes
These reindexes the database when running the migration to prevent corruption.
- No tests
Related: https://github.com/SUSE/spacewalk/issues/15127
fixes bsc#1187217
=> Fix database corruption after migrating to PostgreSQL13

testsuite/features/secondary/srv_security.feature, testsuite/features/step_definitions/security_steps.rb
Remove obsolete scenario "Do not use jsession id".
The current login form works differently.
The current workflow is:
- We hit the Sign In button
- An ajax request hit the routing on the server side
- If we don't have the csrf token we deny the request
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/15188
=> QA: Remove obsolete scenario "Do not use jsession id"

testsuite/features/secondary/srv_scc_user_credentials.feature, testsuite/features/step_definitions/navigation_steps.rb
This scenario removing SCC credentials works locally but fails often in CI, so we will make it even more reliable by giving an extra timeout.
No difference.
Ports:
- Manager-4.1
=> QA: Wait until the SCC credentials is not shown

utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
Add SLE Updates and Backport Updates repositories for openSUSE Leap 15.3
No difference.
- Documentation PR was created:https://github.com/uyuni-project/uyuni-docs/pull/995
- No tests: spacewalk-common-channels not covered by tests
None
=> Add SLE Updates and Backport Updates repositories for openSUSE Leap 15.3

susemanager/bin/pg-migrate-10-to-13.sh, susemanager/bin/pg-migrate-12-to-13.sh, susemanager/susemanager.changes
The message was stating "Starting spacewalk services" when it was only
starting postgresql.
This was a confusing message, because spacewalk services were started
later, after reindexing the database
Before: When running the susemanager/bin/pg-migrate-10-to-13.sh or susemanager/bin/pg-migrate-12-to13.sh, you could see "Starting spacewalk services" before "Reindexing the database"
After: You see the message "Starting PostgreSQL services" before "Reindexing the database" and after reindexing the database you see "Starting spacewalk services" 
- No documentation needed. This is bug fix in a message, no need to document it.
- No tests. No need to add tests, this is just a fix in a message.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1187451 …
=> Fix message in postgresql migration

schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.2.14-to-susemanager-schema-4.2.15/000-almalinux-fix-uyuni-tools-repositories.sql, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
We were supposed to use the EL8 client tools, not CentOS8, but since EL8 arrrived later to OBS, we didn't remember to change it.
This PR takes care of this, for new installations, and for existing installations.
No difference.
- No tests: We tested AlmaLinux8, thing is that the CentOS8 client tools work as well, as they use the same sources.
None
=> Use the right repositories for the AlmaLinux 8 Uyuni client tools

testsuite/features/secondary/buildhost_docker_auth_registry.feature, testsuite/features/step_definitions/docker_steps.rb, testsuite/features/step_definitions/navigation_steps.rb
Add more logs to debug portus image building in case of failure
No difference.
Ports:
- Manager-4.1
=> QA: Add more logs to debug portus image building in case of failure

susemanager/bin/server-migrator.sh, susemanager/susemanager.changes
instead of showing the message to run the PostgreSQL migration
No difference.
Before: Shows message about running pg migration when zypper dup exits with an error
After: Shows message about zypper dup having an error and does not show the  pg migration message
- No tests
=> Show error message is server migration goes wrong

spacecmd/src/spacecmd/errata.py, spacecmd/src/spacecmd/misc.py, spacecmd/src/spacecmd/report.py, spacecmd/src/spacecmd/softwarechannel.py, spacecmd/tests/helpers.py, spacecmd/tests/test_activationkey.py, spacecmd/tests/test_argumentparser.py, spacecmd/tests/test_custominfo.py, spacecmd/tests/test_report.py, spacecmd/tests/test_shell.py, spacecmd/tests/test_softwarechannel.py, spacecmd/tests/test_utils.py
Adds unit tests, ongoing bug fixes and minor refactorings to `spacecmd.softwarechannel` module.
NOTE: Changelog entry will be added after the work-in-progress is over.
=> Add tests of spacecmd to softwarechannel module

testsuite/features/step_definitions/salt_steps.rb
This reverts commit 5f5c10e5f518bd8620e62335198b7fe05001e4bc, as agreed at https://github.com/SUSE/susemanager-ci/pull/297
No difference.
- No documentation needed: Testsuite
Related: https://github.com/SUSE/spacewalk/issues/14997
=> Revert "Use a different repository for Salt for Uyuni"

backend/satellite_tools/reposync.py, backend/spacewalk-backend.changes
This PR fixes a really anoying issue that might happen only in rare cases when there are issues with the checksum/metadata from a repository that is being synced with `spacewalk-repo-sync`.
The package import is done in parallel for different "batches" during a reposync execution. The code that handles the processing of each "batch" does some checking after processing each package to figure out if it's time to do the actual SQL import of the packages that have been already processed in this batch.
The problem this PR is fixing happens in cases when there are checksum/metadata issues on the repository that it's been synced:
```console
...
2021/03/23 11:11:17 +02:00     31/39 : msodbcsql17-17.7.1.1-1.x86_64.rpm
2021/03/23 11:11:18 +02:00     32/39 : mssql-tools-17.2.0.2-1.x86_64.rpm …
```
=> Fix rare issues with reposync when there are errors with package checksums (bsc#1183151)

susemanager/Makefile.defs, susemanager/src/Makefile, susemanager/susemanager.changes, susemanager/susemanager.spec
Fixes issue https://github.com/SUSE/spacewalk/issues/13305
No difference.
- No tests: build time changes
Fixes https://github.com/SUSE/spacewalk/issues/13305
- porting the package to python3 with proper placement
compiled python files
=> Porting susemanager package to python3

spacewalk/certs-tools/rhn_ssl_tool.py, spacewalk/certs-tools/spacewalk-certs-tools.changes, spacewalk/certs-tools/sslToolConfig.py
generate private keys FIPS conform using openssl genpkey command with  aes-256-cbc
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/14990
=> FIPS 140-2 changes

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/spacewalk-java.changes
Adds missing localization strings for recently added taskomatic tasks
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/15091
=> Add missing task status strings

web/html/src/jest.config.js, web/html/src/tsconfig.json, web/html/src/utils/test-utils/setup/index.ts, web/html/src/utils/test-utils/setup/t.test.ts, web/html/src/utils/test-utils/setup/t.ts
Previously our JS unit test setup only supported `t()` as a simple identity function, this PR adds support for tagged templates.
No difference.
=> Add tagged template support to test-util `t()`

java/buildconf/test/rhn.conf.postgresql-example, java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemDetailsEditAction.java, java/code/src/com/suse/manager/webui/controllers/utils/AbstractMinionBootstrapper.java, java/code/src/com/suse/manager/webui/controllers/utils/test/SSHMinionBootstrapperTest.java, java/code/src/com/suse/manager/webui/services/pillar/MinionGeneralPillarGenerator.java, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/salt/channels/gpg-keys.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
When bootstrapping with ssh-push with tunnel, we need to use the port number for fetching GPG keys from the server,
as the server is only reachable via this portnumner.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/15195
=> fix install gpg key on sshpush tunnel

testsuite/features/core/proxy_branch_network.feature
Workaround for Leap 15.3 JeOS OpenStack image, which contains dhcp + dhcp-client in version 4.3.6-P1 (differs from the version in repository causing highstate to fail).
=> Testsuite - workaround to assure no dhcp packages are installed on proxy

java/spacewalk-java.changes, java/spacewalk-java.spec
Use the correct product tag for non-beta
No difference.
- No documentation needed: For now, this is documented at the internal wiki
- No tests: We should consider them (https://github.com/SUSE/spacewalk/issues/15248)
None
=> Use the correct product tag for non-beta

backend/server/test/unit-test/Makefile
This PR is re-introducing the `Makefile` for `backend/server/tests/unit-tests/` (droped in https://github.com/uyuni-project/uyuni/pull/3830) in order to have those tests running and prevent the issue that we're currently facing when building "spacewalk-backend" package:
```console
[  291s] make -C server/test/unit-test PYTHON_BIN=python3
[  291s] make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/spacewalk-backend-git-83.877b53f/server/test/unit-test'
[  291s] make[1]: *** No targets specified and no makefile found.  Stop.
[  291s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/spacewalk-backend-git-83.877b53f/server/test/unit-test'
[  291s] make: *** [Makefile.backend:40: test] Error 2
[  291s] error: Bad exit status from /var/tmp/rpm-tmp.Hdt6kU (%check)
```
I've removed …
=> Reintroduce "Makefile" for backend server unit tests

client/tools/spacewalk-koan/Makefile.spacewalk-koan, client/tools/spacewalk-koan/spacewalk-koan.changes
Fix for spacewalk-koan tests
They were still using the old container.
No difference.
Before:
After:
- No documentation needed: fix for tests
- Fix for tests
Related https://github.com/SUSE/spacewalk/issues/15238
=> Fix for spacewalk-koan tests

testsuite/features/core/proxy_branch_network.feature
=> Testsuite - dhcp workaround fix

testsuite/features/core/proxy_branch_network.feature, testsuite/features/core/proxy_register_as_minion_with_gui.feature, testsuite/features/core/proxy_register_as_minion_with_script.feature, testsuite/features/core/proxy_register_as_trad_with_script.feature
Force zypper ref in the tests that install patterns, otherwise if metadata has changed in the repos, tests fail.
No difference.
- No tests
=> Tests: force zypper ref before installing patterns

testsuite/features/core/allcli_sanity.feature, testsuite/features/step_definitions/command_steps.rb
This PR adds a check for reverse resolution of names.
Technical details:
* I used `getent` because it had to work with both DNS and avahi
Fixes SUSE/spacewalk#15037
Ports:
* 4.0: SUSE/spacewalk#15134
* 4.1: SUSE/spacewalk#15133, SUSE/spacewalk#15167
=> Add reverse resolution sanity check

testsuite/features/build_validation/reposync/srv_wait_for_product_reposync.feature, testsuite/features/step_definitions/command_steps.rb
We are currently waiting that the reposyncs finish, but then we don't check they went well.
This PR checks for the absence of `ERROR:` in reposync logs.
For now, it's BV only. We don't use mirrors in NUE's CI, so it's very easy to get errors of package checksum that does not match the one in the metadata.
Ports:
* 4.0: SUSE/spacewalk#15161
* 4.1: SUSE/spacewalk#15160, SUSE/spacewalk#15167
=> Check the reposync went smoothly

testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature
Filter python 3.6 instead of python 3.8 on RH 8-compatible systems.
This is needed in order to be able to install `spacecmd`.
Ports:
* 4.0: not applicable
* 4.1: SUSE/spacewalk#15175
=> spacecmd needs python 3.6

testsuite/run_sets/build_validation_init_clients.yml
Add 12sp5 to init clients run list
Ports:
* 4.0: SUSE/spacewalk#15183
* 4.1: SUSE/spacewalk#15182
=> Add SLE12SP5 to init clients run list

testsuite/features/step_definitions/common_steps.rb, testsuite/features/step_definitions/salt_steps.rb, testsuite/features/support/lavanda.rb, testsuite/features/support/twopence_init.rb
We parse the output of `ip address show dev eth0`
assuming that the IP appears in the second line.
The following piece of output is from the server at the head branch in the CI:
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
link/ether aa:b2:93:01:00:b2 brd ff:ff:ff:ff:ff:ff
altname enp0s3
altname ens3
inet 10.162.210.178/24 brd 10.162.210.255 scope global eth0
```
The above lines with `altname` break our assumption: we'd extract `enp0s3` as the wrong IP.
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/support/lavanda.rb
- testsuite/features/support/twopence_init.rb:
Grep for 'inet ' to select the right line.
Store the public IP as a new attribute of …
=> Testsuite: More robust client IP extraction

testsuite/features/step_definitions/common_steps.rb
Speed up a slow step.
We often the step `I check for failed events on history event page`.
This step should be quite fast (< 30 s); instead, it's taking
about 2-3 minutes on average.
This is because the `has_css?` inside the loop uses the default timeout,
i.e. `Capybara.default_max_wait_time` (10 s).
Check if the elemnent is in the row with no waiting time.
Fixes https://github.com/SUSE/spacewalk/issues/15019
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/15020
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/15021
=> Testsuite: Speed up a slow step

java/conf/cobbler/snippets/redhat_register_using_salt, java/spacewalk-java.changes
On a RedHat like system we have yum or dnf, but no zypper. Use the manual way to disable the repos.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/3880
Tracks https://github.com/SUSE/spacewalk/pull/15252 https://github.com/SUSE/spacewalk/pull/15254
=> Fix snippet rhel disable repos

java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/code/src/com/suse/manager/webui/controllers/StatesAPI.java, java/code/src/com/suse/manager/webui/services/SaltConstants.java, java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java, java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java, java/spacewalk-java.changes
When a system change its machine id, we need to remove old SLS files and regenerate them as they have the machine id in their name.
No difference.
- No tests: **unable to test file changes as they are disabled in tests**
Fixes https://github.com/SUSE/spacewalk/issues/15231
Tracks https://github.com/SUSE/spacewalk/pull/15278
=> Regen sls files when chaning machine

testsuite/features/secondary/min_centos_openscap_audit.feature, testsuite/features/secondary/trad_centos_client.feature, testsuite/features/step_definitions/command_steps.rb
Change to CentOS OpenSCAP profile, as it's currently using RedHat profile plus a hack.
Related to  https://github.com/SUSE/spacewalk/issues/14758
No difference.
Ports:
- Manager-4.0  https://github.com/SUSE/spacewalk/pull/15115
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/15114
=> QA: Change CentOS OpenSCAP profile

testsuite/features/step_definitions/command_steps.rb, testsuite/features/support/env.rb
I am testing to reduce the timeouts for syncing SCC products so that the acceptance tests for PR do not take that long.
No difference.
Before:
After:
- Cucumber tests were …
=> Reduce the time to 

java/code/src/com/redhat/rhn/manager/action/ActionManager.java, java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java, java/spacewalk-java.changes
This PR adds a 30 seconds delay before triggering a "Package List Refresh" action after a SP migration action is performed on a minion.
The problem before this PR is that the "Package List Refresh" action is scheduled just after the Salt return event is received from the minion when the "distupgrade" state has been executed, and it's as this time when the "salt-minion" services is restarted after the Salt update done during the SP migration.
Therefore, there is a high probability that "Package List Refresh" action is triggered when the minion is not fully reloaded and then the action will be marked as "Failed" due minion is not reachable at the moment.
To workaround this situation, this PR simply schedule "Package Refresh List" action to be triggered 30 seconds in the future, so we give …
=> Add some delay after SP migration before scheduling package refresh action (bsc#1187963)

web/html/src/manager/salt/formula-catalog/org-formula-catalog.tsx, web/spacewalk-web.changes, web/spacewalk-web.spec
The formula catalog page had an outdated filter function that expected different inputs than what's provided. This broke the search on that page, this PR fixes the issue.
Before: Search throws an error.
After: Search no longer throws an error.
- No documentation needed: bugfix.
- No tests: bugfix.
Fixes https://github.com/SUSE/spacewalk/issues/14954
=> Bugged search in formula catalog

web/html/src/components/table/TableDataHandler.tsx, web/html/src/components/utils/StatePersistedContext.ts, web/html/src/manager/audit/subscription-matching/subscription-matching.tsx
The saved context helper doesn't handle multiple components binding to it at the same time. Sadly that's the exact case it the only view where it's currently used. Removing the persisting in this view doesn't have any adverse effects since the data is already available. This was the only view that used this code so I removed it after removing it from this view.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/14106 …
=> Deprecate `StatePersistedContext`

web/html/src/core/utils/objects.ts, web/html/src/manager/content-management/shared/business/states.enum.ts, web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-view.tsx, web/spacewalk-web.spec
[`objectDefaultValueHandler`](https://github.com/uyuni-project/uyuni/blob/master/web/html/src/core/utils/objects.ts) is currently imported in only two views and is practically not used in either of them. This is evidenced by the fact that the util is actually bugged but the branch is never hit because all the values are defined in all the inputs. This PR removes the bugged utilty, removing unnecessary complexity.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13648 …
=> Deprecate `objectDefaultValueHandler`

susemanager-frontend/yarn.lock, web/html/src/core/channels/api/mandatory-channels-api.ts, web/html/src/manager/state/recurring-states-list.tsx, web/html/src/manager/systems/delete-system.tsx, web/html/src/manager/systems/virtualhostmanager/virtualhostmanager-details.tsx, web/html/src/manager/systems/virtualhostmanager/virtualhostmanager-edit.tsx, web/html/src/manager/systems/virtualhostmanager/virtualhostmanager-list.tsx, web/html/src/manager/systems/virtualhostmanager/virtualhostmanager.tsx, web/html/src/utils/test-utils/mock.tsx, web/spacewalk-web.spec
Stumbled upon this while fixing another bug, cleaning up our lint output, removing a bunch of unused imports.
No difference.
Part of https://github.com/SUSE/spacewalk/issues/13762
=> Remove unused imports

branding/css/theme.less, branding/css/uyuni-theme.less
What the title says.
Previously, the css class was not updated in all css files.
Before:
After:
Docs not affected.
- No tests
=> Retracted patch icon should be red

web/html/src/manager/visualization/data-tree.ts
Roll back an incorrect fix I made in https://github.com/uyuni-project/uyuni/pull/3839
No difference.
=> Rollback incorrect data-tree fix

java/code/src/com/redhat/rhn/frontend/xmlrpc/ansible/test/AnsibleHandlerTest.java, java/code/src/com/redhat/rhn/manager/system/AnsibleManager.java, java/code/src/com/redhat/rhn/manager/system/test/AnsibleManagerTest.java
Using low-level `rawJsonCall` is discouraged, unless there is a good reason for using it. In `AnsibleManager` this wasn't the case.
Rewritten to use parsing into `Xor`structure (the salt calls in `AnsibleManager` always return different types in success/error scenarios, so that we can use `Xor` here).
No difference.
internal stuff
https://github.com/SUSE/spacewalk/issues/14920
=> Ansible replace raw json call

susemanager-utils/testing/automation/push-to-obs.sh
We used to change the ownership after building the packages. However, when introduced the parallel building, we forgot about this step and so we are seeing errors in the ci about not being able to remove some files that are owned by root.
No difference.
- No documentation needed: This is a fix for building the product, nothing customer will face
- No tests: this is a fix for being able to test, plus this is not facing the customer
no links. This was a quick fix.
=> Update push-to-obs: change ownership afterwards

testsuite/features/step_definitions/command_steps.rb, testsuite/features/support/env.rb
see https://github.com/uyuni-project/uyuni/pull/3931#issuecomment-874119905
No difference.
- No tests
no links
=> Revert acceptance tests pr optimization scc

susemanager-frontend/susemanager-nodejs-sdk-devel/package.json, susemanager-frontend/yarn.lock, web/html/src/.eslintrc.js, web/html/src/eslint-local-rules/README.md, web/html/src/eslint-local-rules/index.js, web/html/src/eslint-local-rules/no-raw-date.js
Part of [SUSE/spacewalk#15112](https://github.com/SUSE/spacewalk/issues/15112), adds support for disallowing using raw Date instances in the frontend code.  
Also lays the ground for other similar additions in the future.  
No difference.
Part of https://github.com/SUSE/spacewalk/issues/15112
=> Add linter rule for no raw Date usage

susemanager/src/mgr-create-bootstrap-repo, susemanager/susemanager.changes
Fix a typo so mgr-create-bootstrap-script can exit gracefully when interrupted!
No difference.
- No documentation needed: just a typo fix
- No tests: typo has been fixed
Fixes #
=> Fix a typo so mgr-create-bootstrap-script can exit gracefully when interrupted!

testsuite/features/reposync/srv_sync_products.feature
Remove beta tag from client tools reposync
No difference.
Fixes no issue, directly from CI review
Tracks 4.2: https://github.com/SUSE/spacewalk/pull/15330
4.1 is not needed apparently there is no BETA in there
=> Remove beta tag from client tools reposync

testsuite/features/finishing/allcli_debug.feature, testsuite/features/finishing/srv_debug.feature
Move client scenario to right feature, it should not run on server debug when it's for all client debug.
No difference.
Fixes no issue, directly from BV review
=> Move client scenario to right feature

susemanager-utils/testing/automation/push-to-obs.sh
If the user aborts the job when building the packages, then files will be owned by
root. With this commit, we are catching the "exit signals" and calling
chown command, to enforce files be owned by Jenkins. Otherwise, the
workspace can't be cleaned up.
No difference.
- No tests:
quick fix
=> Clean up on jenkins abort when building packages

utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
The command spacewalk-common-channels fails on creating sdl8 channel, cause of a typo in the gpg key fingerprint. The PR fix the typo.
No difference.
Before:
After:
- Cucumber …
=> fix wrong gpgkey fingerprint for sdl8

java/code/src/com/redhat/rhn/domain/action/scap/ScapAction.java, java/code/src/com/redhat/rhn/domain/action/scap/ScapActionDetails.hbm.xml, java/code/src/com/redhat/rhn/domain/action/scap/ScapActionDetails.java, java/code/src/com/redhat/rhn/frontend/action/audit/ssm/BaseSsmScheduleXccdfAction.java, java/code/src/com/redhat/rhn/frontend/action/audit/ssm/SsmScheduleXccdfConfirmAction.java, java/code/src/com/redhat/rhn/frontend/action/audit/ssm/validation/scheduleXccdfForm.xsd, java/code/src/com/redhat/rhn/frontend/action/systems/audit/ScheduleXccdfAction.java, java/code/src/com/redhat/rhn/frontend/action/systems/audit/validation/scheduleXccdfForm.xsd, java/code/src/com/redhat/rhn/frontend/dto/XccdfTestResultDto.java, java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/XccdfTestResultDtoSerializer.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/XccdfTestResultSerializer.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/scap/SystemScapHandler.java, java/code/src/com/redhat/rhn/manager/action/ActionManager.java, java/code/src/com/redhat/rhn/manager/audit/ScapManager.java, java/code/src/com/redhat/rhn/manager/audit/scap/TestResultDiffer.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/webapp/WEB-INF/pages/common/fragments/audit/schedule-xccdf.jspf, java/code/webapp/WEB-INF/pages/systems/details/audit/xccdfdetails.jsp, java/code/webapp/WEB-INF/struts-config.xml, java/spacewalk-java.changes, schema/spacewalk/common/tables/rhnActionScap.sql, schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/0001-rhnActionScap-add-ovalfiles-attribute.sql, schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/0001-rhnScapAction-add-ovalfiles-attribute.sql, susemanager-utils/susemanager-sls/salt/scap/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes the Salt "scap" state that is used by Uyuni to schedule XCCDF scans on minions to use the new introduced `xccdf_eval` function.
This function allows to pass more attributes to the final `oscap` execution, like: `--fetch-remote-resources`, `--rule`, `--remediate`, `--tailoring-file`, `--tailoring-id`, etc.
**IMPORTANT:** This PR depends on the following changes for Salt: https://github.com/openSUSE/salt/pull/386
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/3222 …
=> openscap: allow passing extra parameters to XCCDF scans on minions

java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java, java/code/src/com/redhat/rhn/domain/server/ServerFactory.java, java/code/src/com/redhat/rhn/domain/server/test/ServerFactoryTest.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/LivePatchingApiController.java, java/spacewalk-java.changes, web/html/src/components/input/Select.tsx, web/html/src/manager/content-management/list-filters/templates/index.tsx, web/html/src/manager/content-management/list-filters/templates/live-patching.tsx, web/spacewalk-web.changes
New filter template: "Live patching based on a system" in CLM
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/15205
Fixes https://github.com/SUSE/spacewalk/issues/14098
=> Filter template: Live patching based on a system

java/code/src/com/redhat/rhn/domain/image/KiwiProfile.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/image/profile/ImageProfileHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/image/profile/test/ImageProfileHandlerTest.java, java/code/src/com/suse/manager/webui/controllers/ImageProfileController.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/utils/gson/ImageProfileCreateRequest.java, java/code/src/com/suse/manager/webui/utils/gson/ImageProfileJson.java, java/spacewalk-java.changes, schema/spacewalk/common/tables/suseKiwiProfile.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/004-suseKiwiProfile.sql, susemanager-utils/susemanager-sls/salt/images/kiwi-image-build.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes, web/html/src/manager/images/image-profile-edit.tsx, web/spacewalk-web.changes
This PR adds support for Kiwi options, including --profile. This is necessary for building unmodified image sources from Build Service.
--profile option can be specified multiple times, there is also --type option with similar use, so this PR stores the unmodified Kiwi command line in DB, to allow more flexibility.
Additional validation can be implemented later in front end.
Before:
After:
- Kiwi options field has been added to kiwi profile page
WIP
- Added to unit tests
This is minimal implementation of https://github.com/SUSE/spacewalk/issues/9264
Part of https://github.com/SUSE/spacewalk/issues/14570
If you need to …
=> Add support for Kiwi options

java/code/src/com/redhat/rhn/domain/action/salt/PlaybookActionDetails.hbm.xml, java/code/src/com/redhat/rhn/domain/action/salt/PlaybookActionDetails.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/ansible/AnsibleHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/ansible/test/AnsibleHandlerTest.java, java/code/src/com/redhat/rhn/manager/action/ActionChainManager.java, java/code/src/com/redhat/rhn/manager/action/test/ActionChainManagerTest.java, java/code/src/com/redhat/rhn/manager/system/AnsibleManager.java, java/code/src/com/redhat/rhn/manager/system/test/AnsibleManagerTest.java, java/code/src/com/suse/manager/webui/controllers/AnsibleController.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/utils/gson/AnsiblePlaybookExecutionJson.java, java/spacewalk-java.changes, schema/spacewalk/common/tables/rhnActionPlaybook.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/100-playbook-action-testmode.sql, susemanager-utils/susemanager-sls/salt/ansible/runplaybook.sls, web/html/src/manager/minion/ansible/schedule-playbook.tsx, web/spacewalk-web.changes
- No documentation needed: minor enhancement
Fixes https://github.com/SUSE/spacewalk/issues/14964
=> Add 'test mode' option to Ansible playbook execution

utils/cloneByDate.py, utils/spacewalk-utils.changes
Updated formatting to cloneByDate.py allow pylint pass.
No difference.
=> Updated formatting to cloneByDate.py allow pylint pass.

spacewalk/certs-tools/spacewalk-certs-tools.changes, spacewalk/certs-tools/spacewalk-certs-tools.spec
Removed Python 2 build/Only build for Python 3. Otherwise build fails due to Python3 only code.
**NOTE/IMPORTANT**: Alternative to #3939 . Reject #3939 if this one is accepted.
No difference.
- No documentation needed: No functional changes
Tested build successfully on COPR for
epel-8-x86_64
fedora-33-x86_64
opensuse-leap-15.3-x86_64
=> Removed Python 2 builds

spacewalk/admin/spacewalk-admin.changes, spacewalk/admin/spacewalk-admin.spec
Use package procps-ng for RHEL. sysvinit-tools is not available.
No difference.
Build tested successfully on
epel-7-x86_64 
epel-8-x86_64
opensuse-leap-15.3-x86_64
Fixes #
bsc#1186129
=> Added pidof requirement for RHEL (bsc#1186129)

susemanager-utils/susemanager-sls/salt/images/kiwi-image-build.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
rhn-org-trusted-ssl-cert-osimage requires findutils for correct function of post-install script.
This pull request adds the package explicitly, in case it is missing from bootstrap section of Kiwi config.xml.
Adding it to sls file allows straightforward update, without need to regenerate any package.
No difference.
- No documentation needed: no user visible change, it just makes the image building more robust
- No tests: already covered by cucumber tests
Part of implementation of https://github.com/SUSE/spacewalk/issues/14570 …
=> Add findutils to Kiwi bootstrap packages

web/html/src/build.js, web/spacewalk-web.spec
Currently, the frontend build validation [depends on the cwd](https://github.com/SUSE/spacewalk/issues/13915) and can pass while it shouldn't when executed in a subdirectory. This PR fixes the issue.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13915
=> Fix unstable frontend build validation

testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature
Add both centos 8 ISOs for syncing, appstream and baseos. Both are needed according to the documentation and the old url was failing to sync.
No difference.
Fixes no issue, directly from BV review.
Tracks 4.2:  https://github.com/SUSE/spacewalk/pull/15365
4.1: https://github.com/SUSE/spacewalk/pull/15364
=> Add both centos 8 ISOs for syncing

schema/spacewalk/upgrade/susemanager-schema-4.2.10-to-susemanager-schema-4.2.11/200-rename-service-pack-migration.sql
If the script updates the row with the same value, postgresql will move
it to the end of the dump. This then breaks the idempotency tests.
No difference.
Fixes #
=> Make 200-rename-service-pack-migration.sql truely idempotent

java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java, java/code/src/com/redhat/rhn/domain/server/MinionServer.java, java/code/src/com/redhat/rhn/domain/server/ServerConstants.java, java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/code/src/com/suse/manager/reactor/messaging/RegistrationUtils.java, java/code/src/com/suse/manager/reactor/test/RegisterMinionActionTest.java, java/code/src/com/suse/manager/reactor/utils/RhelUtils.java, java/code/src/com/suse/manager/reactor/utils/test/RhelUtilsTest.java, java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_alibaba.json, java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_almalinux.json, java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_centos.json, java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_centos2.json, java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_oracle.json, java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_res.json, java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_rhel.json, java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_rockylinux.json, java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/services/iface/RedhatProductInfo.java, java/code/src/com/suse/manager/webui/services/impl/SaltService.java, java/code/src/com/suse/manager/webui/utils/salt/custom/PkgProfileUpdateSlsResult.java, java/spacewalk-java.changes, schema/spacewalk/common/data/rhnPackageKey.sql, schema/spacewalk/common/data/rhnPackageProvider.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/100-rocky.sql
Java enablement for Rocky Linux 8.
- package provider detection:
- product detection:
**NOTE:** This will only work when we enable Rocky Linux as a SUSE Product it seems. Honestly I think this should work even for things that are not defined as SUSE Products (but that's not to be fixed at this PR)
No difference.
- Issue: https://github.com/SUSE/spacewalk/issues/15322
Related:
- https://github.com/uyuni-project/uyuni/pull/3681
- https://github.com/uyuni-project/uyuni/pull/3959
=> Rocky Linux 8 Java enablement

uyuni/common-libs/common/rhn_rpm.py
Fixes improper syntax for Python 2 pushed with https://github.com/uyuni-project/uyuni/pull/3920
```
[  101s] Bytecompiling .py files below /home/abuild/rpmbuild/BUILDROOT/uyuni-common-libs-4.3.0-3.1.uyuni.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
[  101s] Compiling /home/abuild/rpmbuild/BUILDROOT/uyuni-common-libs-4.3.0-3.1.uyuni.x86_64/usr/lib/python2.7/site-packages/uyuni/common/rhn_rpm.py ...
[  101s]   File "/usr/lib/python2.7/site-packages/uyuni/common/rhn_rpm.py", line 264
[  101s]     raise InvalidPackageError from None
[  101s]                                  ^
[  101s] SyntaxError: invalid syntax
```
No difference.
=> Remove `from None` from exception raising

spacewalk/certs-tools/spacewalk-certs-tools.spec
Fix a leftover from https://github.com/uyuni-project/uyuni/pull/3940 .
Use python3_version macro directly as suffix
No difference.
=> use python3_version macro directly as suffix

spacewalk/package/spacewalk.changes, spacewalk/package/spacewalk.spec
Update to postgresql13 for non-SUSE environments (allow EL8 to use PostgreSQL 13)
No difference.
=> Update to postgresql13 for non-SUSE environments

susemanager-utils/susemanager-sls/salt/ansible/runplaybook.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Removes nonexistent `test` parameter from `runplaybook` state.
https://bugzilla.suse.com/1188395
Port of: https://github.com/SUSE/spacewalk/pull/15420
No difference.
=> Remove 'test' pillar parameter from 'runplaybook' state (bsc#1188395)

java/code/src/com/redhat/rhn/frontend/strings/database/StringResource_en_US.xml, java/code/src/com/redhat/rhn/manager/user/test/UserManagerTest.java, java/spacewalk-java.changes, schema/spacewalk/common/data/rhnTimezone.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/002-new-timezones.sql
Add Beijing timezone to selectable timezones (bsc#1188193)
No difference.
N/A
- No tests: code with no test
https://github.com/SUSE/spacewalk/issues/15395
bsc#1188193
=> Add Beijing timezone to selectable timezones (bsc#1188193)

susemanager/bin/pg-migrate-x-to-y.sh, susemanager/susemanager.changes
- Abort if the directories for migration or failed migrations exist.
- Abort if any spacewalk service or the PostgreSQL service did not stop correctly.
Extra: Instead of calling `date` a thousand times, we now use a function, to increase readability.
It tested the changes by migrating Uyuni 2021.05 to Uyuni 2021.06 and this worked fine.
Besides the code changes, the important thing about this PR are the error messages. Can we improve them somehow or are my proposals good enough?
No difference.
- No documentation needed: The script itself suggest the user what to do.
- No tests: Script not part of the automated tests.
https://github.com/SUSE/spacewalk/issues/15397 …
=> Improve the error management for the PostgreSQL migration script (bsc#1188297)

java/code/src/com/redhat/rhn/domain/action/ActionFactory.java, java/spacewalk-java.changes
Port of: https://github.com/SUSE/spacewalk/pull/15423  
Already approved by @lucidd  
Fix NPE error when scheduling ErrataAction from relevant errata page 
https://github.com/SUSE/spacewalk/issues/15396
https://bugzilla.suse.com/show_bug.cgi?id=1188289
No difference.
Before:
After:
- No tests: 
Fixes #
=> NPE when scheduling patches from relevant patches page

java/code/src/com/redhat/rhn/manager/system/SystemManager.java, java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/code/src/com/suse/manager/webui/controllers/StatesAPI.java, java/code/src/com/suse/manager/webui/services/SaltActionChainGeneratorService.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java, java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java, java/code/src/com/suse/manager/webui/services/pillar/MinionPillarManager.java, java/code/src/com/suse/manager/webui/services/test/SaltActionChainGeneratorServiceTest.java
Previously, the salt-related cleanups in SaltStateGeneratorService.INSTANCE.removeServer called hibernate proxy methods on the server entity, which lead to hibernate 'no session' error since the server entity was evicted in the SystemManager.delete method.
Solved by introducing a DTO that carries the data needed for post-evict cleanup.
No difference.
- No tests: there are no tests here
=> Bugfix: Prevent "no session" hibernate error on deleting server

java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java, java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java, java/spacewalk-java.changes
Readable error when "mgr-sync add channel" is called with a no-existing label
N/A
N/A
N/A
Fixes #
bsc#1173143
=> Readable error when "mgr-sync add channel" is called with a no-existing label (bsc#1173143)

testsuite/features/step_definitions/command_steps.rb
Raise an error as soon as we find a problem with this step.
This step fails silently at head.  Instead, we want to report this failure as soon as it happens.
https://github.com/SUSE/spacewalk/issues/5838
- Manager-4.1:
- 
=> Testsuite: Catch cobbler test failures earlier

java/code/src/com/redhat/rhn/domain/product/SUSEProductUpgrade.java, java/code/src/com/redhat/rhn/manager/action/ActionManager.java, java/spacewalk-java.changes, spacecmd/spacecmd.changes, spacecmd/src/spacecmd/schedule.py, spacecmd/tests/test_schedule.py
This PR introduces a new command, `schedule_deletearchived` for `spacecmd`, to allow the user to bulk remove archived actions. Also fixes some related issues we figured out while testing this:
As you can see in the implementation, the new `schedule_deletearchived` command is making use of the already existing `schedule.deleteActions` endpoint from the XMLRPC api.
While making use of `schedule.deleteActions` endpoint we've realized of some problems regarding to removing actions:
1) Hibernate exception about missing default constructor:
```
ERROR: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: org.hibernate.InstantiationException: No default constructor for entity:  : com.redhat.rhn.domain.product.SUSEProductUpgrade
```
2) Removing certain actions using `ActionFactory.remove` …
=> spacecmd: add 'schedule_deletearchived' to bulk delete archived actions (bsc#1181223)

java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java, java/spacewalk-java.changes
The primary net interface of a system is specified in `is_primary ('Y'/null)` column in the `rhnServerNetInterface` table and it has a unique constraint, so there can only be one primary interface (marked `'Y'`) for a system. When the primary interface is changed on the client-side and is retrieved via a hardware refresh, the code tries to mark the new one with `Y` without clearing the old one, which leads to a SQL constraint violation.
This PR makes sure there's only one primary interface marked during the update via hardware refresh.
https://bugzilla.suse.com/1188400
Port of: https://github.com/SUSE/spacewalk/pull/15443 …
=> Fix updating primary net interface on hardware refresh (bsc#1188400)

java/code/src/com/redhat/rhn/manager/satellite/UpgradeCommand.java, java/code/src/com/suse/manager/webui/services/impl/SaltService.java, java/spacewalk-java.changes, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/100-enable-virthost-pillar-refresh.sql
Refresh the virtualization host pillars after a migration from a server where `virtpoller` beacon was available.
Removes warning lines like the following from the salt minion logs of the virtual hosts:
```
"2021-07-13 23:13:37,359 [salt.beacons     :140 ][WARNING ][9588] Unable to process beacon virtpoller"
```
No difference.
- No tests: migration only, too much of a corner case
Fixes https://github.com/SUSE/spacewalk/issues/15428
=> Refresh virtualization host pillar due to virtpoller removal

web/html/src/manager/images/image-profile-edit.tsx
Let react be happy with unique children keys: address react warnings
No difference.
- No tests: 
Fixes #
=> Let react be happy with unique children keys

web/html/src/manager/virtualization/guests/list/guests-list.renderer.tsx, web/html/src/manager/virtualization/guests/list/guests-list.tsx, web/spacewalk-web.changes
If the hypervisor can't be detected by Salt and no CRM cluster is setup on the virtual host minion we get a `null` `HostInfo` in the VMs page. Handle this gracefully.
No difference.
- No tests: corner case
=> Handle possibly null HostInfo in virtual guests page

susemanager-utils/susemanager-sls/salt/certs/SLES12.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
In SLES15SP3, the directory `/etc/pki/trust/anchors` is watched via the `ca-certificates.path` systemd unit, and as soon as its contents changed, the system-wide certificates are updated automatically. In `certs` state, we run `update-ca-certificates` right after deploying certs. These two processes create a race condition that in rare cases leads to an error.
See https://bugzilla.suse.com/1188500
This PR updates the `certs` state to run `update-ca-certificates` only if this systemd unit does not exist or is not running.
Corresponding sumaform fix for the testsuite: https://github.com/uyuni-project/sumaform/pull/926
**`ca-certificates.path` running (the state is skipped):**
```
----------
ID: update-ca-certificates
Function: cmd.run
Name: /usr/sbin/update-ca-certificates
Result: True …
```
=> Skip 'update-ca-certificates' run if the certs are updated automatically

testsuite/features/step_definitions/command_steps.rb
Fix typo using `vcenter` instead of `vCenter`
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Fix typo in a step definition

java/code/src/com/redhat/rhn/manager/org/MigrationManager.java, java/code/src/com/redhat/rhn/manager/org/test/MigrationManagerTest.java, java/spacewalk-java.changes
Fixes entitlements not being updated when transferring systems between organizations
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/15304
=> Fix entitlement update during system transfer

susemanager-utils/susemanager-sls/salt/certs/SLES12.sls
Follow-up to: https://github.com/uyuni-project/uyuni/pull/4019
Salt 3000 has a [bug](https://bugzilla.suse.com/1188641) with `unless` requisite together with execution modules. This PR is a workaround to this case.
See: https://bugzilla.suse.com/1188641
=> Check certs auto-update for Salt >= 3002 only

java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java, java/spacewalk-java.changes
Fix this `NullPointerException`:
```
2021-07-23 14:18:14,338 [salt-event-thread-7] ERROR com.suse.manager.reactor.PGEventListener - Unexpected exception while executing a MessageAction
java.lang.NullPointerException
at com.suse.manager.reactor.hardware.HardwareMapper.getUpdatedGuestMemory(HardwareMapper.java:562)
at com.suse.manager.reactor.hardware.HardwareMapper.updateVirtualInstance(HardwareMapper.java:698)
at com.suse.manager.reactor.hardware.HardwareMapper.lambda$mapVirtualizationInfo$5(HardwareMapper.java:683)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.suse.manager.reactor.hardware.HardwareMapper.mapVirtualizationInfo(HardwareMapper.java:682)
at com.suse.manager.utils.SaltUtils.handleHardwareProfileUpdate(SaltUtils.java:1724)
at …
```
=> Fix NPE in HardwareMapper

java/code/src/com/redhat/rhn/frontend/dto/ErrataOverview.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ErrataOverviewSerializer.java, java/spacewalk-java.changes
We got a report of a traceback when calling `softwarechannel_errata_merge` command of "spacecmd":
```
ERROR: time data '1/24/19' does not match format '%Y-%m-%d'
```
The logic on "spacecmd" is expecting the "issue_date" for the erratas listed using the XMLRPC are returned in ISO format, but this is not the currently the case. At the moment the "issue_date" format is different depending on the locale configuration of the Uyuni web UI.
This is not what we should expect from the XMLRPC where we probably want a fixed format for the dates.
So, this PR fixes the `ErrataOverviewSerializer` to ensure the "Date" attributes are returned in ISO format and not as the format defined by the locale configuration on the Uyuni server. This way, `spacecmd softwarechannel_errata_merge` is able to run …
=> Ensure XMLRPC returns "issue_date" in ISO format when listing erratas (bsc#1188260)

susemanager-utils/susemanager-sls/salt/cleanup_minion/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Remove `systemid` file on salt client cleanup when salt client is removed from Uyuni
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/14621
=> Remove systemid file on salt client cleanup

testsuite/features/secondary/srv_distro_cobbler.feature
Sometimes the cobbler feature fails testing the presence of `/srv/tftpboot/pxelinux.cfg/default`.
Our hypothesis is that we simply don't wait long enough. This PR addresses this problem.
The feature `srv_distro_cobbler.feature` will soon be replaced with a better one, but we would like to make sure this is not a product issue before we remove it.
Ports:
* 4.1: SUSE/spacewalk#15525
* 4.2: SUSE/spacewalk#15524
=> Wait until file is created by cobbler

susemanager/bin/pg-migrate-10-to-12.sh, susemanager/bin/pg-migrate-12-to-13.sh
Check whether the data-pg10 directory exists when executing the script, otherwiese it will just move data into that directory in line 83
No difference.
- No documentation needed: doesnt require docs imho, just to catch an error
- No tests
Make the database migration script check for existance of the migration directory to avoid re-run after something went wrong with a migration.
=> check for directory existance

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
removed double spaces in string
**remove double spaces in EN string**
just removed two double spaces
- No documentation needed: **Fixed string**
- No tests: **Fixed string**
Fixes #
=> typos: double spaces in string

.github/reviewers.yml, testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature
Fix for removing Appstream modules.
Piggyback: remove @lkotek from reviewers.
Ports:
* 4.1: SUSE/spacewalk#15544
* 4.2: SUSE/spacewalk#15543
=> Number of sources reduced in CLM for centos8

spacecmd/spacecmd.changes, spacecmd/src/spacecmd/misc.py, spacecmd/tests/test_misc.py
The "Satellite" XMLRPC handler was removed, but spacecmd was still using it. The correct endpoint is "proxy.listProxies".
No difference.
- No documentation needed: user invisible change
There is an existing [unit test](https://github.com/uyuni-project/uyuni/blob/master/spacecmd/tests/test_misc.py#L46-L57) for this function, but I think it is rather pointless. I would prefer to remove it, but first I want to hear your opinion.
Related to https://github.com/SUSE/spacewalk/issues/15313
Fixes bsc#1188042
=> Use correct API endpoint in spacecmd list_proxies

proxy/proxy/rhnProxyAuth.py, proxy/proxy/spacewalk-proxy.changes
Fixes sslerror handling
No difference.
Fixes bsc#1187673
- Fix traceback on handling sslerror (bsc#1187673)
=> Fix traceback on handling sslerror (bsc#1187673)

java/code/src/com/suse/manager/virtualization/VirtManagerSalt.java, java/code/src/com/suse/manager/virtualization/VirtualizationActionHelper.java, java/code/src/com/suse/manager/virtualization/test/TestVirtManager.java, java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualGuestsController.java, java/code/src/com/suse/manager/webui/controllers/virtualization/gson/VirtualGuestsUpdateActionJson.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/services/iface/VirtManager.java, java/code/src/com/suse/manager/webui/templates/virtualization/guests/create.jade, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/salt/virt/create-vm.sls, susemanager-utils/susemanager-sls/src/modules/virt_utils.py, susemanager-utils/susemanager-sls/src/tests/test_module_virt_utils.py, susemanager-utils/susemanager-sls/susemanager-sls.changes, web/html/src/manager/virtualization/guests/GuestProperties.tsx, web/html/src/manager/virtualization/guests/create/guests-create.tsx, web/html/src/manager/virtualization/guests/edit/guests-edit.tsx, web/html/src/manager/virtualization/guests/properties/templates.ts, web/spacewalk-web.changes
Allow selecting a template from the ones supported by the [`virt-tuner`](https://github.com/cbosdo/virt-tuner) tool.
Before:
After:
Fixes # …
=> Use virt-tuner when creating VMs

testsuite/features/secondary/min_salt_minions_page.feature
We had a step trying to click an element (Delete profile button) which is inside a modal dialog.
Let's be more concise and specify that this button is inside a modal dialog.
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Click on delete profile in a modal dialog

java/code/src/com/suse/manager/virtualization/GuestOsDef.java, java/code/src/com/suse/manager/virtualization/VirtualizationActionHelper.java, java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualGuestsController.java, java/code/src/com/suse/manager/webui/controllers/virtualization/gson/VirtualGuestsUpdateActionJson.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/templates/virtualization/guests/create.jade, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/salt/virt/create-vm.sls, susemanager-utils/susemanager-sls/src/grains/virt.py, susemanager-utils/susemanager-sls/src/tests/test_grains_virt.py, susemanager-utils/susemanager-sls/susemanager-sls.changes, testsuite/features/secondary/minkvm_guests.feature, testsuite/features/step_definitions/command_steps.rb, web/html/src/manager/virtualization/guests/GuestProperties.tsx, web/html/src/manager/virtualization/guests/edit/guests-edit.tsx, web/spacewalk-web.changes
Allow users to create UEFI virtual machines from the web interface and edit them.
Before:
After:
Fixes https://github.com/uyuni-project/uyuni/issues/3965
=> Add UEFI support for VM creation UI

proxy/installer/spacewalk-proxy-installer.changes, proxy/installer/squid.conf
This is required to not fetch out of data repodata. Change was suggested by @jmozd.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/14875
=> Proxy: Add second refresh pattern for repodata

testsuite/features/secondary/min_retracted_patches.feature
This PR removes test suite failures due to the fact that the system concerned by the package might take time to appear.
Ports:
* 4.1: SUSE/spacewalk#15559
* 4.2: SUSE/spacewalk#15558
=> Refresh the package page until hostname appears

susemanager-utils/susemanager-sls/src/tests/test_grains_virt.py
Fix virt grains unit tests
No difference.
Fixes #
=> Fix virt grains unit tests

java/code/src/com/redhat/rhn/taskomatic/task/ForwardRegistrationTask.java, java/code/src/com/suse/scc/SCCSystemRegistrationManager.java, java/code/src/com/suse/scc/model/SCCMinProductJson.java, java/spacewalk-java.changes
The SCC Team has reported load spikes after this feature got enabled. According to my investigation:
- an unexpected `Exception`s during the transmission of system data could result in the `ROLLBACK` of the transaction, thereby requiring a full re-sync of all systems at the next round
- one such `Exception` (an NPE) was actually visible in the logs of our internal server `manager.mgr.suse.de`
- randomization of wait time to 7 minutes might not be sufficient to spread the load well (mean is 3.5 minutes)
- the delayed retry mechanism (waiting for one week) was not really working for systems to delete
This PR addresses the concerns above in separate patches.
No difference.
- No tests: **SCC performance is not really tested, patches were tested manually …
=> Fix SCC system forwarding (bsc#1188900)

rel-eng/push-packages-to-obs.sh
When building packages for Pull Requests, we did not take into account
that tarball file names could change, like foo-git123-456789.cpio to
foo-git234-567890.cpio.
This commit removes all previous files and add the new ones.
No difference.
- No tests
N/A
=> CI: remove all tarballs and add new ones

testsuite/features/profiles/Kiwi/POS_Image-JeOS7_40/config.xml, testsuite/features/profiles/Kiwi/POS_Image-JeOS7_41/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_40/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_41/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_40/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_41/config.xml
SLE15-SUSE-Manager-Tools are published in 4.2 branch now. This PR fixes the URLs in the Kiwi profiles accordingly.
Ports:
* 4.1:
* 4.2: SUSE/spacewalk#15570
=> Kiwi profiles: Use 4.2 tools on 4.0 and 4.1

selinux/spacewalk-selinux/spacewalk-selinux-enable, selinux/spacewalk-selinux/spacewalk-selinux.changes
Fixes an error message during install on Enterprise Linux 8
No difference.
Tested during build.
Successfully built on
epel-7-x86_64
epel-8-x86_64
=> spacewalk-selinux: Detect Apache document root folder

spacewalk/spacewalk-setup-jabberd/spacewalk-setup-jabberd.changes, spacewalk/spacewalk-setup-jabberd/spacewalk-setup-jabberd.spec
`manage_database` will send irrelevant error messages during post installation, should Uyuni not be installed already. Let's not show the messages as they are expected. It seems currently only stdout messages are hidden.
No difference.
Build tested successfully on
epel-8-x86_64 
fedora-33-x86_64 
fedora-rawhide-x86_64
opensuse-leap-15.3-x86_64 
=> spacewalk-setup-jabber: Ignore post installation error messages

spacewalk/pylint/spacewalk-pylint, spacewalk/pylint/spacewalk-pylint.changes, spacewalk/spacewalk-python2-pylint/spacewalk-python2-pylint, spacewalk/spacewalk-python2-pylint/spacewalk-python2-pylint.changes, spacewalk/spacewalk-python3-pylint/spacewalk-python3-pylint, spacewalk/spacewalk-python3-pylint/spacewalk-python3-pylint.changes
Currently, pylint is not detected if it does not exist with only the python major version in the executable filename.
Example:
- pylint-2: Detected
- pylint-3: Detected
- pylint-36: Not detected
This change also picks up minor versions or other variations after the major version.
Background: spacewalk-python3-pylint does not run on SUSE Leap.
No difference.
- No tests: Manually tested. Low risk, minor change, easily revertible.
Packages spacewalk-pylint, spacewalk-python2-pylint and spacewalk-python3-pylint build tested successfully on:
epel-7-x86_64 
epel-8-x86_64 
fedora-33-x86_64 
fedora-rawhide-x86_64 
opensuse-leap-15.3-x86_64  …
=> spacewalk-X-pylint: Detect pylint executable with minor python version in name

testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature
Fix backport: use same scenario names between master, Manager-4.2, and Manager-4.1 branches.
No ports, uyuni only.
=> Align scenario names between branches

testsuite/features/support/env.rb
Instead of parametrizing the timeouts through code, depending of the kind of tests.
We moved this responsibility outside the test framework, having as default values those used on CI.
So, after this PR, we might provide a mechanism on the Jenkins Pipelines to set the desired new default timeout.
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Parametrize timeouts from env. variables

spacewalk/setup/salt/susemanager.conf, spacewalk/setup/spacewalk-setup.changes
This PR increases the maximum size allowed for files that are uploaded to the Salt master by Salt minion to avoid having issues with uploading the Scap results from running "Scap Audit" action using the profiles included in the `scap-security-guide` package of SLE15SP3, where report size is higher than default 100MB):
Results from Scap action:
```
Error processing SCAP results file /var/spacewalk/systems/1/1000010000/actions/299/results.xml: /var/spacewalk/systems/1/1000010000/actions/299/results.xml (No such file or directory)
```
While in salt minion logs:
```
2021-07-29 16:59:41,361 [salt.loaded.int.module.cp:856 ][ERROR   ][1514] cp.push Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the …
```
=> Scap: Increase max size for uploaded files to Salt master

testsuite/features/build_validation/create_bootstrap_repositories/srv_create_bootstrap_repositories.feature
This PR creates the bootstrap repos for SLE 12 SP5 in build validation testsuite.
It also documents why we need to create bootstrap repos when this is already done automatically by reposync.
Ports:
* 4.1:
* 4.2: https://github.com/SUSE/spacewalk/pull/15579
=> Create sle 12 sp5 bootstrap repos

susemanager-utils/susemanager-sls/src/modules/virt_utils.py, susemanager-utils/susemanager-sls/src/tests/test_module_virt_utils.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
The OCFS2 primitive may be nested at various levels with a group or not.
Look for children of the <resources> element to get the proper name for
the constraint configuration in VM config.
No difference.
=> Handle more OCFS2 config in virt_utils

java/code/src/com/redhat/rhn/domain/server/MinionServer.java, java/code/src/com/redhat/rhn/domain/server/ServerConstants.java, java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemOverviewAction.java, java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/spacewalk-java.changes
Add a a warning in the overview page if the system is a SLE Micro.
Before:
After:
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/15576
- No tests: code with no test
https://github.com/SUSE/spacewalk/issues/15508
[bsc#1188551
](https://bugzilla.suse.com/show_bug.cgi?id=1188551)
=> warn inside overview page in SLE Micro (bsc#1188551)

proxy/installer/fetch-certificate.py, proxy/installer/rhn-proxy-activate.py, proxy/installer/spacewalk-proxy-installer.changes, proxy/installer/spacewalk-proxy-installer.spec, proxy/proxy/apacheHandler.py, proxy/proxy/apacheServer.py, proxy/proxy/broker/rhnBroker.py, proxy/proxy/broker/rhnRepository.py, proxy/proxy/pm/rhn_package_manager.py, proxy/proxy/redirect/rhnRedirect.py, proxy/proxy/rhnAuthCacheClient.py, proxy/proxy/rhnAuthProtocol.py, proxy/proxy/rhnProxyAuth.py, proxy/proxy/rhnShared.py, proxy/proxy/spacewalk-proxy.changes, proxy/proxy/spacewalk-proxy.spec
Multiple changes to spacewalk-proxy and spacewalk-proxy-installer packages to build on Enterprise Linux 8.
- Python modifications to pass pylint.
- Spec file adaptions and improvements.
No difference.
Part of build process. Pylint tests on RHEL based systems.
spacewalk-proxy build tested ok on
opensuse-leap-15.3-x86_64 
spacewalk-proxy-installer build tested ok  with PR #4039 (running pylint) for
epel-8-x86_64 
opensuse-leap-15.3-x86_64  …
=> spacewalk-proxy: Enterprise Linux modifications

susemanager/bin/mgr-setup, susemanager/bin/pg-migrate-x-to-y.sh, susemanager/susemanager.changes, susemanager/susemanager.spec
**Moved postgresql config from spec to mgr-setup**:
The involved variable POSTGRES_LANG is only used during database initalisation. So the changes in %posttrans would only be relevant for new databases/upgrades. The Uyuni setup now checks for the right locale.
**Improved non-SUSE postgresql config handling**:
1. Set the environment locale for the postgres user during Uyuni setup.
2. Explicitly initialise the database with the required locale.
3. Load and double check the locale during a postgres upgrade.
No difference.
Build tested successfully on
epel-8-x86_64
opensuse-leap-15.3-x86_64
Manually tested upgrade from Leap 15.2 to 15.3 and Postgresql 13 using the scripts.
Manually tested …
=> susemanager: Modified postgresql configuration handling

web/html/src/manager/maintenance/calendar/web-calendar.test.tsx
Fix web-calendar unit tests
No difference.
- No documentation needed: **Fixing tests**
=> Fix web-calendar js unit tests

proxy/proxy/spacewalk-proxy.changes, proxy/proxy/spacewalk-proxy.spec
Adapted log folder ownership to avoid conflicts on Enterprise Linux during installation.
Modified post/pre installation sections for RHEL based systems.
No difference.
Tested during build and installation process.
Build successfully on OBS (manual copy/paste of spec file content)
Installed successfully on AlmaLinux 8
=> spacewalk-proxy: Adapted SPEC file to install on Enterprise Linux

java/code/src/com/suse/manager/webui/controllers/SystemsController.java, java/spacewalk-java.changes, web/html/src/manager/systems/delete-system.tsx, web/spacewalk-web.changes
When trying to delete a minion that is not reachable the user gets proposed to delete without cleanup. However the cleanup was being executed regardless due to a parameter from the frontend not being retrievable.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/15593
=> Fix cleanup always being executed on delete system (bsc#1189011)

proxy/proxy/apacheHandler.py, proxy/proxy/apacheServer.py, proxy/proxy/rhnAuthCacheClient.py
Fixes regression caused by https://github.com/uyuni-project/uyuni/pull/4029
CFG is used there and it's too sensitive to the order of importing
Superseeds https://github.com/uyuni-project/uyuni/pull/4092
No difference.
=> Revert imports order breaking proxy by PR#4029

spacewalk/setup/salt/salt-ssh-logging.conf, spacewalk/setup/spacewalk-setup.changes, spacewalk/setup/spacewalk-setup.spec, susemanager-utils/susemanager-sls/salt/cleanup_ssh_minion/init.sls, susemanager-utils/susemanager-sls/salt/ssh_bootstrap/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Logging for salt SSH (+ log rotation)
In all cases:
- `/var/log/salt-ssh.log` is created when the bootstrap happens and shows some non fatal errors and warnings depending on the system (@meaksh for awareness, but I think ion squad already knows)
- `/etc/logrotate.d/salt-ssh` is installed, and since `logrotate` is installed in all cases, it should rotate the file when the time comes.
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
-rw-r--r--. 1 root …
```
=> Logging for salt SSH

susemanager-utils/susemanager-sls/salt/services/salt-minion.sls, susemanager-utils/susemanager-sls/salt/ssh_bootstrap/init.sls
https://github.com/uyuni-project/uyuni/pull/4080 only added the logrotate configuration for new ssh minions.
This fix will add it in all cases.
I removed `/etc/logrotate.d/salt-ssh` from a CentOS7 existing salt-ssh minion, ran the highstate and:
```
[root@sshminion-centos7 logrotate.d]# cat salt-ssh 
/var/log/salt-ssh.log {
su root root
weekly
missingok
rotate 7
compress
notifempty
}
```
Since the config is part of `services/salt-minion.sls`, the configuration will also be added by the bootstrap, as the state file is used for ssh and non-ssh minions.
TBH: We should refactor this and avoid calling it `services/salt-minion.sls` and rather something like `common/salt.sls`. But then again, we should consider a refactor of many other states such as the bootstrap states :-)
No difference.
- No …
=> Apply the logrotate configuration for ssh for existing minions as well

schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/300-fix-entitlements.sql
Add a migration script to fix wrongly assigned entitlements due to past system transfer between organizations
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/15304
=> Add migration to fix wrongly assigned entitlements

java/code/src/com/redhat/rhn/taskomatic/task/SSHMinionActionExecutor.java, java/spacewalk-java.changes
Prior to this change, SSH minion actions stayed as "Queued" until they finish. This PR sets the actions as "Picked up" as soon as the execution starts.
See: https://bugzilla.suse.com/1188505
https://github.com/SUSE/spacewalk/issues/15496
=> Mark SSH minion actions when they're picked up (bsc#1188505)

testsuite/features/step_definitions/command_steps.rb, tftpsync/susemanager-tftpsync-recv/configure-tftpsync.sh, tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes, tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.spec
Solution for: https://github.com/SUSE/spacewalk/issues/15639
When a server has IPv4 and IPv6 configured installation script only allows IPv4. With this change, if no IP is passed, the default value will contain all the visible IPs (returned by host command) and will add them to apache configuration.
No difference.
Before:
After:
- …
=> Uyuni tftp script multiple ip on server

testsuite/features/secondary/srv_handle_channels_with_ISS_v2.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/features/support/twopence_init.rb, testsuite/run_sets/secondary.yml
Add integration tests for the new ISS v2 tool.
The steps of this test are:
- install inter-server-sync package on server
- Clone an existing channel with packages and patches
- Export it with ISS v2
- Remove the cloned channel
- Import with ISS v2
- Check if the imported channel has the data
No difference.
It's a command-line tool for now. …
=> add tests for the iss v2 tool

testsuite/features/secondary/buildhost_docker_auth_registry.feature
No difference.
Before:
After:
Fixes # …
=> increase timeout for build image with authenticated registry

testsuite/features/step_definitions/salt_steps.rb
This PR adds `--assume-yes` to two calls to `apt-get` to avoid being stuck by questions like:
```
Do you want to continue? [Y/n] 
```
Ports:
* 4.1: SUSE/spacewalk#15655
* 4.2: SUSE/spacewalk#15656
=> Avoid being stuck by confirmation question

java/code/src/com/redhat/rhn/domain/dto/EndpointInfo.java, java/code/src/com/redhat/rhn/domain/formula/ExporterConfig.java, java/code/src/com/redhat/rhn/domain/formula/FormulaFactory.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/HandlerFactory.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/EndpointInfoSerializer.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/monitoring/SystemMonitoringHandler.java, java/code/src/com/redhat/rhn/manager/formula/FormulaManager.java, java/code/src/com/redhat/rhn/manager/formula/test/FormulaManagerTest.java, java/code/src/com/redhat/rhn/manager/formula/test/prometheus-exporters-formula-data.json, java/spacewalk-java.changes
Add API method
`listEndpoints(User, List<Long>)`
to list all available application and Prometheus exporters endpoints for the systems whose IDs
match with the passed systems IDs.
Requires SUSE/salt-formulas#102
No difference.
- No documentation needed: change only to XMLRPC API with automatically generated reference documentation.
Fixes #
Tracks https://github.com/SUSE/spacewalk/issues/12777
=> Add API call to get all formula data

spacecmd/spacecmd.changes, spacecmd/src/spacecmd/shell.py, spacecmd/tests/test_misc.py, spacecmd/tests/test_shell.py
Excludes the `spacecmd whoami` command from the list of commands which doesn't require a login.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/15585
=> Spacewalk CMD: Remove whoami from the exclude login regex (bsc#1188977)

java/manager-build.xml
`deploy.port` option is ignored on the `rsync` step of Ant deployment. This PR updates `manager-build.xml` to use this option with `rsync`.
- No documentation needed: internal fix
- No tests: affects dev infrastructure
=> Use 'deploy.port' option on rsync step in Ant targets

java/code/src/com/redhat/rhn/frontend/xmlrpc/schedule/ScheduleHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/schedule/test/ScheduleHandlerTest.java, java/code/src/com/redhat/rhn/manager/action/ActionManager.java, java/spacewalk-java.changes, spacecmd/spacecmd.changes, spacecmd/src/spacecmd/schedule.py, spacecmd/tests/test_schedule.py
This PR enhance the current `schedule_deletearchived` function to allow passing a date limit for the archived actions to remove.
Besides of the changes on `spacecmd`, a new XMLRPC endpoint has been created to allow listing all archived actions via API without the limitting the results to 10K (due the display limit configuration)
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/14196
=> Allow passing a date limit for "schedule_deletearchived" on spacecmd (bsc#1181223)

susemanager-frontend/susemanager-nodejs-sdk-devel/package.json, susemanager-frontend/yarn.lock, web/html/src/package.json
Whenever backporting changes, since we don't have GH actions on those branches, I constantly end up popping open a bunch of terminals for all the scripts I need to run for sanity checks.  
This PR adds the script `$ yarn all` which runs _all_ necessary frontend sanity checks you need to run before merging a backport (or something else).
No difference.
=> Add `yarn all`

testsuite/features/step_definitions/command_steps.rb
Make the node IP visible in sanity check
No difference.
Fixes No issue, created directly from testsuite review
Tracks 4.2: https://github.com/SUSE/spacewalk/pull/15704
4.1: https://github.com/SUSE/spacewalk/pull/15705
=> Make the node IP visible in sanity check

testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature
This PR waits until title "Create a new filter" appears before filling in the fields of the CLM filter dialog box.
Ports:
* 4.1: SUSE/spacewalk#15707
* 4.2: SUSE/spacewalk#15706
=> Wait until dialog box to create new CLM filter is fully loaded

java/code/src/com/redhat/rhn/frontend/xmlrpc/system/monitoring/SystemMonitoringHandler.java
Fix API documentation strings for the call `system.monitoring.listEndpoints`.
No difference.
- No documentation needed: No new functionality.
- No tests: Just syntax fix.
=> Fix API doc for system.monitoring.listEndpoints

susemanager-utils/testing/automation/push-to-obs.sh
When building packages with yarn inside a container, the ownership of some files get
changed to root. Without this commit, the ownership is fixed **only**
for new files, not for old ones.
This commit fixes the ownership of **all** files.
Otherwise, next run in jenkins will fail because it can't clean up the
environment.
No difference.
- No tests
=> CI: Fix ownership on package building

susemanager-utils/testing/automation/push-to-obs.sh
fix file ownership
No difference.
- No tests
- [X ] No changelog needed
=> fix file ownership

testsuite/features/build_validation/smoke_tests/smoke_tests.template
A command like `cucumber -r features -n "Deploy the file to all subscribed systems"` would run the scenario on all minions.
This PR makes it possible to run `cucumber -r features -n "Deploy the configuration file to sle15sp3_minion"` for example.
Ports:
* 4.1: SUSE/spacewalk#15715
* 4.2: SUSE/spacewalk#15714
=> Fix non-unique scenario name

java/code/src/com/redhat/rhn/frontend/xmlrpc/BaseHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/LoggingInvocationProcessor.java, java/spacewalk-java.changes
`FaultException`s are expected outcomes and shouldn't be treated as errors in the logs. This PR reduces their log level to `DEBUG` and suppresses their stack traces in `rhn_web_ui.log`. The full exception will be still in the client response.
Also, in `rhn_web_api.log` even with **any kind of** exception, all the calls will be logged as `INFO`, without stack traces.
When any unexpected exception occurs, the stack traces will be still logged in `rhn_web_ui.log` anyway.
See: https://bugzilla.suse.com/1188853
Port of: https://github.com/SUSE/spacewalk/pull/15703 …
=> Do not log XMLRPC FaultExceptions as errors (bsc#1188853)

java/code/src/com/redhat/rhn/domain/image/OSImageStoreUtils.java, java/code/src/com/suse/manager/webui/controllers/ImageBuildController.java, java/code/src/com/suse/manager/webui/templates/content_management/view.jade, java/spacewalk-java.changes, web/html/src/manager/images/image-view.tsx, web/spacewalk-web.changes
Add a link to OS image store directory listing in image list page.
The link only displays if the directory exists for an org. The directory should not exist until at least one OS image is built.
- No documentation needed: minor addition
- Cucumber tests will be adapted
Fixes https://github.com/SUSE/spacewalk/issues/15256
Fixes https://github.com/SUSE/spacewalk/issues/12766
=> Add a link to OS image store dir in image list page

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml, java/code/src/com/redhat/rhn/manager/contentmgmt/FilterTemplateManager.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/FilterApiController.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/request/FilterRequest.java, java/spacewalk-java.changes, web/html/src/manager/content-management/list-filters/filter.utils.ts, web/html/src/manager/content-management/list-filters/templates/app-streams.tsx, web/html/src/manager/content-management/list-filters/templates/index.tsx, web/html/src/manager/content-management/list-filters/templates/live-patching.tsx, web/html/src/manager/content-management/shared/api/use-lifecycle-actions-api.ts, web/html/src/manager/content-management/shared/type/filter.type.ts, web/html/src/utils/hooks.test.tsx, web/html/src/utils/hooks.ts, web/html/src/utils/network.ts, web/spacewalk-web.changes
Frontend part for the appstreams filter template along with some network updates. I also cherry-picked the backend branch onto this for easier testing. I couldn't figure out how to correctly configure modular channels to get them to show up though (slight facepalm).
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/15727
Fixes https://github.com/SUSE/spacewalk/issues/14100
=> Appstreams filter template

testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/common_steps.rb, testsuite/features/support/lavanda.rb
Use a bigger buffer size when calling mgr-sync with twopence 
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Use a bigger buffer size when calling mgr-sync with twopence

web/html/src/utils/functions.test.ts, web/html/src/utils/functions.ts, web/spacewalk-web.changes
Tweak the JS capitalize() function to not capitalize strings only
composed of capital letters and dashes / underscores since those are
probably acronyms. An example would be SR-IOV: we don't want such a
formula name to be capitalized.
Before:
After:
- No tests: Harmless UI label change
=> Don't capitalize acronym strings

java/code/src/com/suse/manager/webui/controllers/virtualization/gson/VirtualNetworkInfoJson.java, java/code/src/com/suse/manager/webui/controllers/virtualization/test/VirtualNetsControllerTest.java, java/code/src/com/suse/manager/webui/controllers/virtualization/test/virt.net.info.json, java/spacewalk-java.changes
The JSon None value is not mapped to `null`, but to `JSonNull`. Fix the
comparison hen parsing virtual networks that have no bridge.
No difference.
=> Fix JSon null comparison when parsing virtual network infos

susemanager/bin/mgr-setup, susemanager/susemanager.changes, susemanager/susemanager.spec
Package `snapper` is required during setup for creating btrfs volumes using `mksubvolume`.
This change makes the `snapper` package optional.
Should the package be required and not installed at setup time, it will automatically be installed.
A friendly message is displayed should the automatic installation fail.
Background: Snapper and btrfs-progs are not available on Enterprise Linux 8. Making the packages optional allows system admins decide whether they would like to install 3rd party packages, create their own package or not use btrfs.
No difference.
- No tests: Manually tested.
Code works on Leap and AlmaLinux. Installation tested manually with and without package on AlmaLinux installation.
Build has been tested …
=> susemanager: Package 'snapper' is now optional

testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/common_steps.rb, testsuite/features/step_definitions/lock_packages_on_client.rb, testsuite/features/step_definitions/salt_steps.rb, testsuite/features/step_definitions/smdba_steps.rb, testsuite/features/support/client_stack.rb, testsuite/features/support/cobbler_test.rb, testsuite/features/support/commonlib.rb, testsuite/features/support/lavanda.rb, testsuite/features/upload_files/Redfish-Mockup-Server/rfSsdpServer.py
Refactor run command to use keyword parameters
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Refactor run command to use keyword parameters

testsuite/features/step_definitions/command_steps.rb
Missing change in run parameters
No difference.
Needs ports
=> QA: Missing change in run parameters

java/code/src/com/redhat/rhn/common/security/acl/Access.java, java/code/src/com/redhat/rhn/common/security/acl/test/AccessTest.java, java/code/webapp/WEB-INF/nav/channel_detail.xml, java/spacewalk-java.changes
Show AppStream tab just for modular channel
N/A
N/A
Fixes #
Tracks # https://github.com/SUSE/spacewalk/issues/10098
=> Show AppStream just for modular channel

susemanager-utils/testing/automation/push-to-obs.sh
CI: Fail on error when building the packages
If push-to-obs was giving an error, the process was not capturing this
correctly in the case of running it on parallel.
No difference.
tested using jenkins jobs
- [X ] **DONE**
- [X ] No changelog needed
=> CI: Catch errors when building packages

susemanager-utils/susemanager-sls/src/grains/cpuinfo.py
deprecation warning appears on log.warn()
log.warn is deprecated so use log.warning
No difference.
tested at my infrastructure
=> fix deprecation warning in cpuinfo.py

susemanager/bin/pg-migrate-x-to-y.sh, susemanager/susemanager.changes
The migration script assumes data_directory is not set. Otherwise, it
would give an error.
This commit prevents the error by checking and aborting it.
Before: If data_directory had a value in /var/lib/pgsql/data/postgresql.conf, you would see an error when trying to start the database after migration.
After: You will see an error before attempting the migration
- No tests
https://github.com/SUSE/spacewalk/issues/15556
=> Abort db migration if data_directory is set in postgresql configuration

java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml, java/code/src/com/redhat/rhn/domain/action/rhnpackage/PackageAction.java, java/code/src/com/redhat/rhn/frontend/action/rhnpackage/LockPackageAction.java, java/code/src/com/redhat/rhn/manager/rhnpackage/PackageManager.java, java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/webapp/WEB-INF/nav/system_detail.xml, java/spacewalk-java.changes, schema/spacewalk/common/data/rhnFeature.sql, schema/spacewalk/common/data/rhnServerGroupTypeFeature.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.1-to-susemanager-schema-4.3.2/001-package-lock-feature.sql, susemanager-utils/susemanager-sls/salt/packages/pkglock.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes, susemanager-utils/testing/automation/chown-objects.sh, testsuite/features/secondary/min_salt_lock_packages.feature, testsuite/features/secondary/trad_lock_packages.feature, testsuite/features/step_definitions/common_steps.rb, testsuite/features/step_definitions/lock_packages_on_client.rb, testsuite/run_sets/secondary.yml
Package Locks are currently only available for traditionally managed systems.
This PR should bring this feature also for salt minions.
It requires some implementation in salt to support locking with zypp, yum, dnf and apt.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/15572
- Change Package Locking 
- Change Feature checklist
- Change UI description
Fixes https://github.com/SUSE/spacewalk/issues/15305
Tracks https://github.com/SUSE/spacewalk/pull/15654 …
=> Package locks for salt clients

susemanager-utils/susemanager-sls/src/grains/virt.py, susemanager-utils/susemanager-sls/src/tests/test_grains_virt.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
When refreshing the virt grains libvirtd may not be up and running. For
this reason we need to avoid using the libvirt API to get the libvirt
version.
No difference.
=> Don't use libvirt API in virt grains

web/html/src/manager/systems/activation-key/activation-key-channels.tsx, web/spacewalk-web.changes
Change the explanation and warning about the default base channel in the activation key dialog.
Before:
After:
- No documentation needed: enhanced UI message
- No tests: only messages rewording
Fixes https://github.com/SUSE/spacewalk/issues/11457
=> Enhance base channel help message

schema/spacewalk/common/data/rhnServerServerGroupArchCompat.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.1-to-susemanager-schema-4.3.2/002-ansible-entitlement-for-all-archs.sql
We ship the ansible package for all architectures in our SUSE Manager Tools Channel, but allow to set the entitlement only for x86_64 and amd64.
A customer want to use it on POWER (ppc64le) and run into errors.
As we ship the packages for this arch we should also allow to use it.
Port of https://github.com/SUSE/spacewalk/pull/15793
No difference.
- No documentation needed: **such a militation was never documented**
=> Ansible ent for all archs

testsuite/features/secondary/proxy_cobbler_pxeboot.feature, testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
A minor refactor in a couple of tests:
split a long scenario in two and rewrite some scenario titles.
- proxy_retail_pxeboot_and_mass_import.feature
Split a long scenario in two.
- proxy_cobbler_pxeboot.feature: Rewrite two scenario titles.
https://github.com/SUSE/spacewalk/issues/15337
- Manager-4.2: https://github.com/SUSE/spacewalk/pull/15794
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/15795
=> Testsuite: Split a long scenario

testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature, testsuite/features/step_definitions/navigation_steps.rb
Adjust CLM filter that became a modal
No difference.
Fixes no issue, directly from BV review
Tracks 4.2: https://github.com/SUSE/spacewalk/pull/15821
4.1: Not needed because it didn't change in that version
=> Adjust CLM filter that became a modal

java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java, java/code/src/com/suse/manager/reactor/messaging/test/pkg_install.duplicates.json, java/code/src/com/suse/manager/utils/SaltUtils.java, java/spacewalk-java.changes
Sometimes Salt lists the same NEVRA twice in a `pkg.installed` result, only with different install timestamps. Use a merge function is to ignore these duplicate entries.
https://bugzilla.suse.com/1187572
Port of: https://github.com/SUSE/spacewalk/pull/15818
=> Ignore duplicates in 'pkg.installed' result when applying patches (bsc#1187572)

susemanager-utils/testing/automation/push-to-obs.sh
Only show logs when there has been an error and show which package
failed to build, not only the pid of the process that failed.
This should make it easier to find errors.
Before: A lot of output for packages that were successfully built, so finding the one that failed was like finding a needle in a haystack
After: Only the log of the failed package is shown, with a message stating which package is it.
- No tests
https://github.com/SUSE/spacewalk/issues/15560
=> CI: improve error reporting when building packages

testsuite/features/secondary/minkvm_guests.feature, testsuite/features/secondary/proxy_cobbler_pxeboot.feature
Split a scenario in two
- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature:
One scenario creates the profile, the other configures it.
https://github.com/SUSE/spacewalk/issues/15336
- Manager-4.2: https://github.com/SUSE/spacewalk/pull/15833
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/15834
=> Testsuite: Split a scenario in two

java/code/src/com/redhat/rhn/domain/errata/AdvisoryStatus.java, java/spacewalk-java.changes, schema/spacewalk/common/tables/rhnErrata.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.1-to-susemanager-schema-4.3.2/310-add-pending-advisory-status.sql
$subj
No difference.
- No documentation needed: bug
- No tests
https://github.com/uyuni-project/uyuni/issues/4011
=> Support syncing patches with advisory status 'pending'

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/spacewalk-java.changes
This PR simply adds a missing string definition shown in the XCCDF scan results page.
Now the missing string is visible
- 
- No tests: **cosmetic change**
Tracks https://github.com/SUSE/spacewalk/issues/15824
=> Add missing string on XCCDF scan results (bsc#1190164)

java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java, java/code/src/com/redhat/rhn/manager/system/SystemManager.java, java/spacewalk-java.changes, utils/spacewalk-hostname-rename, utils/spacewalk-utils.changes
Fix the `spacewalk-hostname-rename` script to:
* Avoid generating a new SSL CA if not needed
* Allow using third-party SSL certificate
* Refresh the minion pillar data since they also contain the server hostname in the repositories URLs
No difference.
- PR submitted: https://github.com/uyuni-project/uyuni-docs/pull/1158
Fixes https://github.com/SUSE/spacewalk/issues/15801
=> Make hostname renaming a smoother experience

testsuite/features/step_definitions/datepicker_steps.rb, web/html/src/components/datetime/DateTimePicker.tsx
[`testsuite/features/step_definitions/datepicker_steps.rb`](https://github.com/uyuni-project/uyuni/blob/master/testsuite/features/step_definitions/datepicker_steps.rb#L27) relies on the `data-provide` field used by the old datetime pickers. This PR adds those fields back so Cucumber is happy.
No difference.
=> Fix Cucumber selectors for datetime pickers

web/html/src/components/datetime/DateTimePicker.tsx, web/html/src/components/panels/InnerPanel.tsx, web/html/src/components/picker/recurring-event-picker.tsx, web/html/src/components/table/Table.tsx, web/html/src/manager/maintenance/list/schedule-list.tsx, web/html/src/manager/state/highstate-summary.tsx, web/html/src/manager/state/recurring-states-edit.tsx, web/html/src/manager/state/recurring-states-list.tsx, web/html/src/manager/state/recurring-states.tsx
Fixes time zone offset problems in recurring events views.  
Also fixes a number of missing key bugs and related issues I found when debugging the recurring events view.
Minor cosmetic difference, nothing to document.
- No documentation needed: only very minor user invisible changes.
- No tests: already covered by Cucumber which uncovered this problem.
Fixes https://github.com/SUSE/spacewalk/issues/15841
Part of https://github.com/SUSE/spacewalk/issues/9049
=> Fix time zone mismatch in recurring events

susemanager-frontend/susemanager-nodejs-sdk-devel/package.json, susemanager-frontend/yarn.lock, web/html/src/vendors/npm.licenses.structured.js, web/html/src/vendors/npm.licenses.txt, web/spacewalk-web.changes
Bumps immer to 9.0.6 to fix CVE-2021-23436.
No difference.
=> Bump immer to 9.0.6

susemanager-frontend/susemanager-nodejs-sdk-devel/susemanager-nodejs-sdk-devel.changes, web/spacewalk-web.changes
In https://github.com/uyuni-project/uyuni/pull/4207 I used the wrong changes file, this PR fixes the mistake.
No difference.
Follow-up to https://github.com/uyuni-project/uyuni/pull/4207
=> Fix incorrect changes location

susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes, susemanager-utils/supportutils-plugin-susemanager/susemanager
Broken symlinks in tomcat, taskomatic or search daemon do not prevent them from starting but result in any kind of funny errors which are hard to detect. So actively search for them and report them.
No difference.
- No tests: **support tool changes**
Tracks https://github.com/SUSE/spacewalk/pull/15861 https://github.com/SUSE/spacewalk/pull/15862
=> Supportconfig broken symlink check

java/code/src/com/redhat/rhn/frontend/xmlrpc/schedule/ScheduleHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/schedule/test/ScheduleHandlerTest.java, java/code/src/com/redhat/rhn/manager/action/ActionManager.java, java/spacewalk-java.changes, spacecmd/spacecmd.changes, spacecmd/src/spacecmd/schedule.py
This is a follows-up PR from https://github.com/uyuni-project/uyuni/pull/4007
This new PR introduces some more enhacements to "spacecmd" in order to do operate massively with actions:
- Add new `schedule_archivecompleted` fuction to massively archive completed actions older than a given date.
- Allow "non-interactive" usage of `schedule_deletearchived` and `schedule_archivecompleted` by allowing `-y|--yes` argument.
No difference.
- No documentation needed: **no documentation for spacecmd**
Tracks https://github.com/SUSE/spacewalk/issues/14196 …
=> spacecmd: enhacements for mass delete/archive actions (bsc#181223)

web/html/src/jest.config.js, web/html/src/manager/virtualization/nets/network-properties.test.tsx
I couldn't identify the problem nor a fix for https://github.com/SUSE/spacewalk/issues/15387 so I raised Jest's timeouts so we don't get false positives in our internal test runs a-la https://ci.suse.de/view/Manager/view/Manager-4.2/job/manager-4.2-dev-javascript-lint/259/console.
No difference.
A workaround for https://github.com/uyuni-project/uyuni/pull/4218
=> Increase Jest timeouts

.github/PULL_REQUEST_TEMPLATE.md
Add a link to the changelog policies for the PR template.
Links:
https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs
https://github.com/uyuni-project/uyuni/wiki/Contributing#changelog-rules-for-packages-at-git
Feel free to improve the wiki.
NOTE: If approved, this will require a backport to the private repo.
No difference.
- Irrelevant.
- Irrelevant
- None
=> Add links to the changelog policies for the PR template

web/html/src/manager/virtualization/guests/create/guests-create.tsx, web/html/src/manager/virtualization/guests/edit/guests-edit.tsx, web/html/src/utils/functions.ts, web/spacewalk-web.changes
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/15895
=> virt guests: formatting the earliest field breaks now

testsuite/features/support/client_stack.rb, testsuite/features/support/common_lib.rb, testsuite/features/support/env.rb, testsuite/features/support/lavanda.rb, testsuite/features/support/timeout_lib.rb
Fix a library dependency issue with repeat_until_timeout
No difference.
Ports:
- Manager-4.2
=> Fix a library dependency issue with repeat_until_timeout

susemanager-utils/susemanager-sls/src/states/mgrcompat.py, susemanager-utils/susemanager-sls/src/tests/test_state_mgrcompat.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes custom `mgrcompat` state module to work properly on Salt 3003 version and future Silicon release (3004).
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/15371
=> Fix custom "mgrcompat" state module to work with Salt 3003 and 3004

java/code/src/com/redhat/rhn/frontend/xmlrpc/saltkey/SaltKeyHandler.java, java/code/src/com/suse/manager/utils/SaltKeyUtils.java, java/spacewalk-java.changes
Added some endpoint for salt key API:
- `accept` : API endpoint to accept minion keys
-  `reject` : API endpoint to reject minion keys
- `pendingList` :  API endpoint to list pending salt keys
- `acceptedList` : API endpoint to list accepted salt keys
- `rejectedList` : API endpoint to list rejected salt keys
Resolve minor issue in `delete` API
No difference.
- API documentation generated correctly
- No tests: Not Appilicable
https://github.com/SUSE/spacewalk/issues/14189
=> API call to accept Salt keys 

spacewalk/admin/spacewalk-admin.changes, spacewalk/admin/spacewalk-admin.spec, spacewalk/admin/spacewalk-startup-helper
This PR removes the usage of pid and replace it with pgrep. It also removes the dependency on the `sysvinit-tools` on SUSE requiring the standard `procps`.
No difference.
Fixes #
SUSE/spacewalk/issues/14901 …
=> Used pgrep in place of pidof

java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java, java/spacewalk-java.changes, schema/spacewalk/common/tables/rhnActionPackageDetails.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.2-to-susemanager-schema-4.3.3/400-rhnactionpackagedetails-idx.sql
When scheduling a patch installation in SSM for multiple systems via Action Chain, the Package Details entry will be created 2 times and cause a ISE when selecting the chain.
This PR avoid to create multiple entries and set a unique index in DB to prevent storing wrong data in future.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/15881
=> Fix ise package action details

susemanager-utils/susemanager-sls/salt/bootstrap/init.sls, susemanager-utils/susemanager-sls/salt/channels/disablelocalbrokenrepos.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Some OS images include enabled repositories which are accessible only in special environments (e.g. inside of a specific cloud)
These images cannot be bootstrapped as they produce errors on refreshing the repositories.
This PR add a state which test the accessability of the local enabled repos and disable all, which cannot be used.
We keep the accessible once enabled until the bootstrapping is finished before we also disable them.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/15196
Fixes https://github.com/uyuni-project/uyuni/issues/3755
Tracks https://github.com/SUSE/spacewalk/pull/15938 …
=> Disable broken local repos before bootstrap

java/spacewalk-java.changes, susemanager-sync-data/additional_products.json
add centos7/8, oraclelinux 7/8, rockylinux 8, almalinux 8 and amazoninux 2 aarch64
No difference.
- No tests
Tracks # https://github.com/SUSE/spacewalk/issues/15411
=> adding aarch64 products

java/code/src/com/redhat/rhn/common/db/datasource/xml/Task_queries.xml, java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemDetailsEditAction.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/code/src/com/redhat/rhn/taskomatic/task/AutoErrataTask.java, java/code/src/com/redhat/rhn/taskomatic/task/TaskConstants.java, java/code/src/com/suse/manager/maintenance/MaintenanceManager.java, java/spacewalk-java.changes
Make the auto errata update respect maintenance windows
Fix a bug related to auto errata update when a CLM build of affected channel is in progress.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/15720
=> Fix autoupdate with maintenance windows

proxy/proxy/spacewalk-proxy.spec
With PR #4095 , the proxy does not build anymore on Enterprise Linux due to pylint failures. This change still runs pylint for Enterprise Linux, outputs issues during build but always passes.
No difference.
NOTE: Build not tested
=> spacewalk-proxy: Always pass pylint checks

susemanager-utils/susemanager-sls/salt/channels/disablelocalbrokenrepos.sls, susemanager-utils/susemanager-sls/salt/channels/disablelocalrepos.sls
yum style repos return for "enabled" a string which is "1" or "0". Test for this instead of a boolean test which always result in true.
Additionally replace `$basearch` variable in baseurl with the "osarch" grain and `$releasever` with "osmajorrelease" value to get a valid URL.
No difference.
Additional fix for https://github.com/uyuni-project/uyuni/pull/4227
Tracks https://github.com/SUSE/spacewalk/pull/15946 …
=> fix test for enabled repos and replace basearch var in URL

java/spacewalk-java.changes, susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
Add aarch64 bootstrap repositories for CentOS 7/8, Oracle Linux 7/8, Rocky Linux8, AlmaLinux8, Amazon Linux 2 and openSUSE Leap 15.3
Fix the changelog for `spacewalk-java`
No difference.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/14440
- Cucumber being added by QA, for the build validation
Tracks: https://github.com/SUSE/spacewalk/issues/15413 …
=> Add aarch64 bootstrap repos for CentOS clones and openSUSE Leap 15.3 for SUSE Manager

java/code/src/com/redhat/rhn/common/util/http/HttpClientAdapter.java, java/spacewalk-java.changes, proxy/installer/configure-proxy.sh, proxy/installer/spacewalk-proxy-installer.changes, proxy/installer/spacewalk-proxy-installer.spec, proxy/proxy/httpd-conf/spacewalk-proxy.conf, proxy/proxy/spacewalk-proxy.changes
configure-proxy.sh was configuring SSLProtocol with some outdated values.
The apache default is a better use for now. 
No difference.
- No documentation needed: **the current docs say already to adapt the config**
Fixes https://github.com/uyuni-project/uyuni/issues/4105
Tracks https://github.com/SUSE/spacewalk/pull/15940 https://github.com/SUSE/spacewalk/pull/15941
If you …
=> Align tls protocols for proxy

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
Remove two translation keys that are no longer in use
No difference.
Fixes SUSE/spacewalk/issues/14378
=> Removed unused translation keys

backend/satellite_tools/reposync.py, backend/spacewalk-backend.changes
This PR fixes an issue in `spacewalk-repo-sync` when trying to sync a repository which is using custom SSL client certificates, added via webUI, that contains whitespaces or weird characters as part of the "Description" attribute when creating it.
When "description" contains whitespaces, the cached files generated by SUMA to be consumed by reposync are stored like:
```console
adb700c5.0 -> Example SSL.pem
Example SSL.pem
Example SSL key.pem
```
And this makes reposync to fail as it is not properly handling the whitespaces:
```
2021/09/24 17:38:03 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'testchannel', '--type', 'yum', '--non-interactive']
2021/09/24 17:38:03 +02:00 Sync of channel started.
Preparing custom SSL CAPATH at /var/cache/rhn/reposync/.ssl-certs/1
2021/09/24 …
```
=> Sanitize cached filename for custom SSL certs used by reposync (bsc#1190751)

susemanager-utils/susemanager-sls/src/grains/virt.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
r-strings are not supported in python2.
No difference.
- No tests: python2-related change
Fixes #
=> Fix python2 compatibility of virt grain

java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java, java/code/src/com/suse/manager/reactor/messaging/test/minion.startup.applied.state.response.json, java/code/src/com/suse/manager/reactor/messaging/test/packages.profileupdate.livepatching.json, java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/utils/salt/custom/SystemInfo.java, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/salt/util/systeminfo.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
When the running kernel is changed on a system after a reboot, the corresponding live patch version also changes. At minion startup, we always check and update the running kernel but not the live patch info, so system details show outdated information for the live patch.
This PR adds a `sumautil.get_kernel_live_version` call to `util.systeminfo` state which is run in response to a minion startup, ensuring we update the live patch version properly.
See: https://bugzilla.suse.com/show_bug.cgi?id=1190276
Port of: https://github.com/SUSE/spacewalk/pull/15916
If you don't …
=> Update kernel live patch version on minion startup (bsc#1190276)

web/html/src/manager/content-management/shared/components/panels/sources/sources.tsx, web/spacewalk-web.changes
Since the "Type" select input has only a single hardcoded option, it bypasses the form context model implementation, so the value cannot be changed at all. This PR fixes the input value so the single option is selected by default.
If we add more values in the future, we'll need to implement the form model properly, but it's not required for now.
https://bugzilla.suse.com/show_bug.cgi?id=1190820
Port of: https://github.com/SUSE/spacewalk/pull/15937 …
=> Fix 'Type' input in CLM source edit form (bsc#1190820)

java/code/src/com/redhat/rhn/domain/action/salt/PlaybookActionDetails.hbm.xml, java/code/src/com/redhat/rhn/domain/action/salt/PlaybookActionDetails.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/ansible/AnsibleHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/ansible/test/AnsibleHandlerTest.java, java/code/src/com/redhat/rhn/manager/action/ActionChainManager.java, java/code/src/com/redhat/rhn/manager/action/test/ActionChainManagerTest.java, java/code/src/com/redhat/rhn/manager/system/AnsibleManager.java, java/code/src/com/redhat/rhn/manager/system/test/AnsibleManagerTest.java, java/code/src/com/suse/manager/webui/controllers/AnsibleController.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/utils/gson/AnsiblePlaybookExecutionJson.java, java/spacewalk-java.changes, schema/spacewalk/common/tables/rhnActionPlaybook.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.2-to-susemanager-schema-4.3.3/100-playbook-action-flushcache-flag.sql, susemanager-utils/susemanager-sls/salt/ansible/runplaybook.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes, web/html/src/manager/minion/ansible/schedule-playbook.tsx, web/spacewalk-web.changes
In some cases, Ansible users need to use `--flush-cache` flag when executing playbooks. This PR adds the flag as a checkbox on the schedule playbook page and passes it to Salt during action execution.
See: https://bugzilla.suse.com/show_bug.cgi?id=1190405
Port of: https://github.com/SUSE/spacewalk/pull/15933 …
=> Ansible 'flush_cache' flag for Playbook execution (bsc#1190405)

susemanager-utils/susemanager-sls/salt/channels/disablelocalbrokenrepos.sls, susemanager-utils/susemanager-sls/salt/channels/disablelocalrepos.sls
On SUSE `pkg.list_repos()` return objects with enabled = boolean, while on RedHat enabled return a string which is "1" or "0".
In our states we need to handle both.
We cannot check:
```
data.get('enabled', True) in [True, '1']
```
as when "enabled" return the string '0', it would match the boolean True.
So we better do the negative test
```
data.get('enabled', True) not in [False, '0']
```
No difference.
Additional fix for https://github.com/uyuni-project/uyuni/pull/4247
Tracks https://github.com/SUSE/spacewalk/pull/15962 …
=> return value for enabled can be boolean or string depening on the OS

java/code/src/com/redhat/rhn/domain/product/SUSEProductSet.java, java/spacewalk-java.changes
Prevent ISE if there is no base product when trying to schedule a product migration
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/15799
=> Fix ISE in product migration if base product is missing

web/html/src/.eslintrc.js, web/html/src/components/datetime/DateTimePicker.stories.js, web/html/src/components/datetime/DateTimePicker.tsx, web/html/src/eslint-local-rules/no-raw-date.js, web/html/src/manager/maintenance/calendar/web-calendar.test.tsx, web/html/src/manager/maintenance/calendar/web-calendar.tsx, web/html/src/utils/datetime/README.md, web/html/src/utils/datetime/localizedMoment.ts
Adds missing documentation, improves linter rule.
No difference.
Internal documentation was added.
- Unit tests were improved
Documentation for https://github.com/SUSE/spacewalk/issues/9049
=> Update documentation and linting for datetimes usage

susemanager-branding-oss/susemanager-branding-oss.changes, susemanager-branding-oss/susemanager-branding-oss.spec
Build susemanager-branding-oss only for SLE
Tested at:
https://build.opensuse.org/package/show/home:juliogonzalezgil:branches:systemsmanagement:Uyuni:Master/susemanager-branding-oss
https://build.suse.de/package/show/home:juliogonzalezgil:branches:Devel:Galaxy:Manager:Head/susemanager-branding-oss
No difference.
- No documentation needed: This package is not mentioned anywhere at the doc
- No tests: Covered by cucumber
None …
=> Build susemanager-branding-oss only for SLE

java/code/src/com/redhat/rhn/taskomatic/task/RhnQueueJob.java, java/code/src/com/redhat/rhn/taskomatic/task/repomd/RepomdIndexWriter.java, java/code/src/com/redhat/rhn/taskomatic/task/repomd/RpmRepositoryWriter.java, java/code/src/com/redhat/rhn/taskomatic/task/repomd/test/RpmRepositoryWriterTest.java, java/spacewalk-java.changes
Adds checksums in front of the filenames of repository metadata files, helping clients cache the metadata properly.
Tested on CentOS 8 and SLES15SP2 clients.
See: https://bugzilla.suse.com/1188315
Port of: https://github.com/SUSE/spacewalk/pull/15664
=> Add checksums to repository metadata filenames (bsc#1188315)

backend/server/rhnRepository.py, backend/spacewalk-backend.changes
Follow up on https://github.com/uyuni-project/uyuni/pull/4263
This PR adapt the download code for the traditional stack when downloading metadata files.
No difference.
Tracks
=> download metadata files with checksums for the traditional stack

backend/satellite_tools/spacewalk-diskcheck, backend/spacewalk-backend.changes, java/code/src/com/suse/manager/utils/DiskCheckHelper.java, java/code/src/com/suse/manager/utils/DiskCheckSeverity.java, java/code/src/com/suse/manager/utils/test/DiskCheckHelperTest.java, java/code/src/com/suse/manager/webui/controllers/login/LoginController.java, java/code/src/com/suse/manager/webui/controllers/login/templates/login.jade, java/code/src/com/suse/manager/webui/utils/LoginHelper.java, java/spacewalk-java.changes, web/html/src/manager/login/login.renderer.tsx, web/html/src/manager/login/login.tsx, web/spacewalk-web.changes
When the space is running low on the server a warning banner is displayed at the top of the login page. If the space level is critical and the server has not been shut down the banner is displayed as an error. The diskcheck script was changed to allow executing the check without sending a mail notification.
After:
A banner is shown when the server is running out of space in the directories monitored by the diskcheck script
- [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pull/1189)
Fixes SUSE/spacewalk/issues/14259
If you don't …
=> Introduce a banner in the login page when the available disk space reported by diskcheck is low

java/code/src/com/redhat/rhn/domain/contentmgmt/modulemd/ConflictingStreamsException.java, java/code/src/com/redhat/rhn/domain/contentmgmt/modulemd/ModuleDependencyException.java, java/code/src/com/redhat/rhn/domain/contentmgmt/modulemd/ModulemdApi.java, java/code/src/com/redhat/rhn/domain/contentmgmt/modulemd/ModulemdApiException.java, java/code/src/com/redhat/rhn/frontend/action/channel/AppStreamsAction.java, java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml, java/code/src/com/redhat/rhn/manager/contentmgmt/DependencyResolver.java, java/code/src/com/redhat/rhn/manager/contentmgmt/FilterTemplateManager.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/AppStreamsApiController.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/FilterApiController.java, java/spacewalk-java.changes
Improve exception handling and logging by adding checks to `getAllPackages` and `getAllModulesInChannel` API calls as well.
No difference.
=> Improve exception handling and logging for ModulemdApi

susemanager-utils/susemanager-sls/salt/channels/disablelocalbrokenrepos.sls
New disable broken repos state can result in conflicting IDs. This PR make them unique.
No difference.
Additional fix for #4247 
Tracks https://github.com/SUSE/spacewalk/pull/16000
=> prevent conflicting IDs when disabling repos

java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ContentProjectSerializer.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappersTest.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/ProjectPropertiesResponse.java, java/code/src/com/suse/manager/webui/utils/ViewHelper.java, java/spacewalk-java.changes, web/html/src/manager/content-management/list-projects/list-projects.tsx, web/html/src/utils/functions.ts, web/spacewalk-web.changes
Add a "Last build date" column to the CLM project list page
- No documentation needed: minor UI enhancement
Fixes https://github.com/SUSE/spacewalk/issues/15632
=> Last build date column in CLM project list

web/html/src/manager/content-management/list-filters/filter-edit.tsx, web/spacewalk-web.changes
Fix a regression that causes the CLM filter edit modal to open when navigating to the list view.  
https://bugzilla.suse.com/show_bug.cgi?id=1190867
No difference.
- No documentation needed: Bug fix.
- No tests: Nothing to test.
Fixes https://github.com/SUSE/spacewalk/issues/15951
=> Fix unwanted CLM filter edit modal opening (bsc#1190867)

susemanager-utils/susemanager-sls/src/beacons/pkgset.py, susemanager-utils/susemanager-sls/src/tests/test_beacon_pkgset.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
Fixes the traceback on salt-minion 2016.11.10.
```
2021-08-10 09:06:20,578 [salt.minion][CRITICAL][11722] The beacon errored: 
File "/usr/lib64/python2.6/site-packages/salt/minion.py", line 2250, in handle_beacons
beacons = self.process_beacons(self.functions)
File "/usr/lib64/python2.6/site-packages/salt/minion.py", line 421, in process_beacons
return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member
File "/usr/lib64/python2.6/site-packages/salt/beacons/__init__.py", line 96, in process
raw = self.beacons[fun_str](b_config[mod])
File "/var/cache/salt/minion/extmods/beacons/pkgset.py", line 67, in beacon
if os.path.exists(COOKIE_PATH):
File "/usr/lib64/python2.6/genericpath.py", line 18, in exists
st = os.stat(path) …
```
=> Fix pkgset beacon to work with salt-minion 2016.11.10 (bsc#1189260)

java/code/src/com/suse/manager/webui/controllers/DownloadController.java, java/code/src/com/suse/manager/webui/controllers/test/DownloadControllerTest.java, java/spacewalk-java.changes, java/spacewalk-java.spec
* fix logging of spark framework
* map requests to media.1/ directory in the DownloadController and provide the "products" file when its available.
Port of https://github.com/SUSE/spacewalk/pull/15869
No difference. …
=> Fix slf4j log4j provider

spacewalk/certs-tools/spacewalk-certs-tools.changes, spacewalk/certs-tools/spacewalk-ssh-push-init
Follow up PR after solving the issue: https://bugzilla.suse.com/show_bug.cgi?id=1189643
key is generated using open ssh format, but library JSCH only supports PEM format. This PR set the flag to generate key on PEM format when no key is found.
This change was tested at the reference server.
No difference. …
=> Set key format to PEM for traditional clients push ssh

susemanager-utils/testing/automation/publish-rpms.sh
We are using this script in the CI for downloading packages from obs, instead of from openSUSE mirrors.
However, the script was only working for yum/zypper repos.
This commit adds the ubuntu repos.
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/15846 …
=> Add ubuntu repos to publish script

susemanager-utils/testing/automation/publish-rpms.sh
The release packages are not being published. The reason is that these
packages are "sub-packages" and `osc getbinaries` is not downloading them.
However, we can specify the subpackage when calling `osc getbinaries`.
Thus, let's add an extra parameter so we can specify the subpackage
names.
No difference.
- No tests
related to https://github.com/SUSE/spacewalk/issues/15846 …
=> Add extra parameter for publishing packages

susemanager-utils/susemanager-sls/salt/channels/disablelocalbrokenrepos.sls
Use a different counter name to not interfer with the normal `repos_disabled` from the standard disable state.
No difference.
=> use a different counter name

susemanager-utils/susemanager-sls/src/grains/cpuinfo.py, susemanager-utils/susemanager-sls/src/states/virt_utils.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
Fix python2.6 compatibility for cpuinfo grain and virt_utils state.
No difference.
- No tests: python 2.6 only
Fixes https://github.com/SUSE/spacewalk/issues/15982 and https://bugzilla.suse.com/show_bug.cgi?id=1191123 …
=> More python2 compatibility fixed in grains and states

susemanager-utils/susemanager-sls/salt/channels/disablelocalbrokenrepos.sls
Define used variable
Additional fix for https://github.com/uyuni-project/uyuni/pull/4284
No difference.
=> define variable

web/html/src/components/table/Table.tsx, web/html/src/manager/state/highstate-summary.tsx
In highstate overview in creating a recurring state we currently try to key table items by a field which doesn't exist. This seems like a reasonable alternative, please feel free to propose a better field if `id` isn't sufficiently unique.
No difference.
- No tests: bugfix.
Fixes https://github.com/SUSE/spacewalk/issues/15856
If you …
=> Fix incorrect identifier in recurring states

java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemOverviewAction.java, java/code/webapp/WEB-INF/pages/systems/sdc/overview.jsp, java/spacewalk-java.changes
It doesn't make any sense to display a link to CLM live patching filter templates for systems that are of a product that doesn't have live patching. This PR hides the link for those systems.
Port of: https://github.com/SUSE/spacewalk/pull/16015
=> Hide link to live patching filter template for unsupporeted systems in system details (bsc#1190866)

testsuite/features/step_definitions/common_steps.rb
PR https://github.com/uyuni-project/uyuni/pull/4263 add checksums in front of the metadata files.
This PR adapt the tests to file the new filenames.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/16027 https://github.com/SUSE/spacewalk/pull/16028 …
=> check for metadata files with checksums as well

java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java, java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
`mgr-sync refresh` goes in error because of an exception in  `updateChannel` . The exception happens just when a channel is removed from SCC Repositories. Changed the exception in a more clear log error.
https://github.com/SUSE/spacewalk/issues/16016
https://bugzilla.suse.com/show_bug.cgi?id=1191222
=> fix mgr-sync refresh (bsc#1191222)

testsuite/features/secondary/srv_datepicker.feature
Test fix to the new format
No difference.
The following image shows the captured real UI during the test:
- No documentation needed: test fix
- No tests: test fix
Fixes [internal/private link](https://ci.suse.de/view/Manager/view/Manager-4.2/job/manager-4.2-dev-acceptance-tests-PRV/546/testReport/junit/(root)/Pick%20dates/Picking_a_time_should_set_the_hidden_fields/) …
=> Align the test to the datetime picker format

java/code/src/com/redhat/rhn/common/hibernate/HibernateFactory.java, java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
NPE is:
```
java.lang.NullPointerException
at com.suse.manager.utils.SaltUtils.handleImageBuildData(SaltUtils.java:1149)
at com.suse.manager.utils.SaltUtils.updateServerAction(SaltUtils.java:622)
at com.suse.manager.webui.services.SaltServerActionService.lambda$handleAction$159(SaltServerActionService.java:2722)
```
Since the NPE happens also when everything is working fine, let' s put the root cause NPE variable as optional (but let's create a  warning if it's null).
Moreover, unproxy function is removed as suggested in the comment:
```
Impelmentation is copied from Hibernate 5.2.10 and this method should be removed after that release.
```
No difference.
https://bugzilla.suse.com/show_bug.cgi?id=1185951
https://github.com/SUSE/spacewalk/issues/14927
Make sure …
=> NPE fix: action can be null in handleImageBuildData bsc#1185951

java/code/src/com/redhat/rhn/domain/server/MinionServer.java, java/code/src/com/redhat/rhn/domain/server/ServerFactory.java, java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/utils/salt/custom/SystemInfo.java, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/salt/util/systeminfo.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
This updates proxy path each time when the minion connects.
If the proxy is changed, it regenerates pillars and channels to point to the new proxy.
This is a part of implementation of https://github.com/SUSE/spacewalk/issues/15630
Open questions:
- it probably needs refactoring
- ssh minions might need special handling
No difference.
WIP
Partially fixes https://github.com/SUSE/spacewalk/issues/15630 …
=> Update proxy path on minion connection

backend/rhn-conf/rhn_server.conf, backend/rhn-conf/rhn_server_satellite.conf, backend/satellite_tools/satsync.py, backend/satellite_tools/xmlWireSource.py, client/rhel/spacewalk-client-tools/data/Makefile, client/rhel/spacewalk-client-tools/spacewalk-client-tools.spec, client/rhel/spacewalk-client-tools/src/bin/rhn_check.py, client/rhel/spacewalk-client-tools/src/up2date_client/rpcServer.py, client/tools/mgr-cfg/config_client/rhncfg-client.conf, client/tools/mgr-cfg/config_client/rhncfgcli.conf, client/tools/mgr-cfg/config_common/repository.py, client/tools/mgr-cfg/config_management/rhncfg-manager.conf, client/tools/mgr-cfg/config_management/rhncfg.conf, client/tools/mgr-custom-info/rhn-custom-info.py, client/tools/mgr-osad/rhn-conf/rhn_osa-dispatcher.conf, proxy/installer/configure-proxy.sh, proxy/installer/rhn.conf, proxy/proxy/pm/rhn-conf/rhn_proxy_package_manager.conf, proxy/proxy/rhn-conf/rhn_proxy.conf, spacewalk/admin/Makefile.admin, spacewalk/admin/spacewalk-admin.spec, spacewalk/config/usr/share/man/man5/rhn.conf.5, spacewalk/config/var/lib/rhn/rhn-satellite-prep/etc/rhn/rhn.conf, spacewalk/setup/bin/spacewalk-setup, spacewalk/setup/lib/Spacewalk/Setup.pm, spacewalk/setup/spacewalk-setup.spec, web/conf/rhn_web.conf
- remove mirror credential settings from rhn.conf - moved to DB since a long time
- remove `satellite.rhn.redhat.com` as default for rhn_parent. We do not set a default anymore
- remove iss_ca_chain. We use now just ca_cert as fallback
- set ca_chain to empty value or to /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT on managed clients
- remove expired RHNS-CA-CERT certificate
- do not install RedHat's gpg key
No difference. …
=> cleanup code from legacy things

susemanager-utils/testing/docker/scripts/schema_migration_test_pgsql.sh
--skip-gpg-key-import was dropped from spacewalk-setup scripts. Do not use it anymore when calling it to setup a test environment.
Follow up on https://github.com/uyuni-project/uyuni/pull/4301
No difference. …
=> remove dropped option from test script

testsuite/features/secondary/min_ansible_control_node.feature, testsuite/features/secondary/min_salt_openscap_audit.feature, testsuite/features/secondary/minssh_ansible_control_node.feature, testsuite/features/secondary/trad_openscap_audit.feature
Remove os_ltss_repo from CI minions to match the current status. We removed them from sumaform in the current 15sp2 and 15sp3 minions and this current PR is making the testsuite match. Supersedes https://github.com/uyuni-project/sumaform/pull/985
No difference.
Fixes #
Tracks 4.2: https://github.com/SUSE/spacewalk/pull/16307
4.1: I think it's not needed on 4.1, because it's using 15sp1 minion and it's LTSS already …
=> Remove os_ltss_repo from CI minions

java/buildconf/test/rhn.conf.postgresql-example, java/code/src/com/suse/scc/client/SCCRequestFactory.java, java/code/src/com/suse/scc/client/SCCWebClient.java, java/code/src/com/suse/scc/client/test/SCCRequestFactoryTest.java, java/spacewalk-java.changes
When connecting to SCC, set the product name and version as User-Agent header for better bug tracking
in case of invalid requests.
No difference.
- manual test show for Uyuni:
```
2021-10-28 08:30:01,602 [DefaultQuartzScheduler_Worker-8] DEBUG org.apache.http.headers - http-outgoing-0 >> POST /connect/organizations/systems HTTP/1.1
2021-10-28 08:30:01,602 [DefaultQuartzScheduler_Worker-8] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept: application/vnd.scc.suse.com.v4+json
2021-10-28 08:30:01,602 [DefaultQuartzScheduler_Worker-8] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip, deflate
2021-10-28 08:30:01,602 [DefaultQuartzScheduler_Worker-8] DEBUG …
```
=> Send suma id in http requests

scripts/translation/update-all-translation-strings.sh
spacewalk-abrt was removed from client tools[0]. We need to remove the
reference in the translation update script.
[0] https://github.com/uyuni-project/uyuni/commit/f7f21baddf87b3c84bbbb32f0a4ecc5d84f50d8e
No difference.
- No tests
No issue. I found this while doing another thing. …
=> Remove spacewalk-abrt

spacewalk/setup/spacewalk-setup.changes
Adds missing changelog entry
No difference.
Fixes #
=> Add missing changelog entry to spacewalk-setup

java/buildconf/ivy/ivy-suse.xml
This patch is updating the `snakeyaml` dependency to version 1.28 as they apparently updated it in openSUSE Leap 15.3.
No difference.
- No documentation needed: only internal and user invisible changes (dependencies)
There is currently no issue for this.
=> Update snakeyaml from version 1.25 -> 1.28

java/spacewalk-java.changes
add missing changelog in spacewalk-java
=> Add missing changelog

java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java, java/code/src/com/suse/manager/reactor/messaging/test/image.inspect.kiwi_compressed.json, java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java, java/code/src/com/suse/manager/webui/utils/salt/custom/OSImageInspectSlsResult.java, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/src/modules/kiwi_info.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
Compressed OS images pillars are missing compressions flag in pillars. This causes saltboot to deploy compressed image directly to the disk instead of decompressing it beforehand.
No difference.
Fixes #https://github.com/SUSE/spacewalk/issues/16148
Tracks #https://github.com/SUSE/spacewalk/pull/16172
If you …
=> Fix compressed image pillars for saltboot

testsuite/features/support/xmlrpc_system.rb
Take care that we call the correct API function by forcing proxyid to be an int.
Port of https://github.com/SUSE/spacewalk/pull/16373
No difference.
=> Force proxyid int

java/code/src/com/redhat/rhn/domain/credentials/Credentials.hbm.xml, java/code/src/com/redhat/rhn/domain/credentials/CredentialsFactory.java, java/code/src/com/redhat/rhn/domain/product/test/SUSEProductTestUtils.java, java/code/src/com/redhat/rhn/domain/scc/SCCRepository.java, java/code/src/com/redhat/rhn/domain/scc/SCCRepositoryAuth.java, java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java, java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java, java/code/src/com/redhat/rhn/manager/content/test/data1/productsUnscoped.json, java/code/src/com/redhat/rhn/manager/content/test/data1/repositories.json, java/code/src/com/redhat/rhn/manager/content/test/smallBase/productsUnscoped.json, java/spacewalk-java.changes
If 2 credentials provide access to the same repositories, we choose the "best" following some criterias.
When a repo is already setup and the auth item from a different credential become "the best", we have to switch
the assignment of the content source (repo) which did not happen.
In the old code just assigned the content source also to the new best auth, but leave the old assigned as well.
This had the consequence that in the re-link function, we switch the URL back and forth and under bad conditions
the `isRefreshNeeded()` function tell us, we use the wrong one and need to refresh which does not help.
Port of https://github.com/SUSE/spacewalk/pull/16123
No difference. …
=> Fix ContentSource links when auth items switch

java/buildconf/ivy/ivy-suse.xml, java/code/src/com/redhat/rhn/taskomatic/task/sshpush/SSHPushWorkerSalt.java, java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/code/src/com/suse/manager/webui/controllers/StatesAPI.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/services/iface/SaltApi.java, java/code/src/com/suse/manager/webui/services/impl/SaltService.java, java/code/src/com/suse/manager/webui/services/test/SaltServerActionServiceTest.java, java/code/src/com/suse/manager/webui/services/test/TestSaltApi.java, java/spacewalk-java.changes, java/spacewalk-java.spec, java/tito.props
This PR adjusts the code for the salt-netapi library PR https://github.com/SUSE/salt-netapi-client/pull/292. It introduces handling of ssh errors which previously caused `JsonParseError` and better error propagation in general to write more useful error messages in failed actions.
Before:
After:
- No tests
Fixes #https://github.com/SUSE/spacewalk/issues/12955
=> handle and propagate salt ssh errors

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/code/src/com/suse/manager/webui/controllers/utils/AbstractMinionBootstrapper.java, java/code/src/com/suse/manager/webui/controllers/utils/test/AbstractMinionBootstrapperTestBase.java, java/code/src/com/suse/manager/webui/controllers/utils/test/RegularMinionBootstrapperTest.java, java/code/src/com/suse/manager/webui/controllers/utils/test/SSHMinionBootstrapperTest.java, java/code/src/com/suse/manager/webui/utils/gson/BootstrapHostsJson.java, java/code/src/com/suse/manager/webui/utils/gson/BootstrapParameters.java, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/salt/bootstrap/susemanager.conf, susemanager-utils/susemanager-sls/susemanager-sls.changes, testsuite/features/secondary/min_bootstrap_reactivation.feature, testsuite/features/secondary/trad_check_registration.feature, testsuite/features/step_definitions/common_steps.rb, testsuite/features/support/xmlrpc_system.rb, testsuite/run_sets/secondary_parallelizable.yml, web/html/src/manager/systems/bootstrap/bootstrap-minions.tsx, web/spacewalk-web.changes
Enance the Bootstrap UI and API to allow reactivations using a reactivation key.
No difference.
After:
- Documentation PR was created: https://github.com/uyuni-project/uyuni-docs/pull/1232
Fixes https://github.com/SUSE/spacewalk/issues/14703
Tracks https://github.com/SUSE/spacewalk/pull/16260 …
=> Bootstrap UI for reactivation

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
Add missing repositories for aarch64 for AlmaLinux 8. We did it for SUSE Manager, but not for Uyuni.
No difference.
- No documentation needed: Was added already.
- No tests: Not covered by the testsuite as of today
Detected while doing https://github.com/uyuni-project/uyuni/pull/4471 for https://github.com/SUSE/spacewalk/issues/14445 …
=> Add missing repositories for aarch64 for AlmaLinux 8

java/code/src/com/redhat/rhn/domain/errata/Errata.hbm.xml, java/code/src/com/redhat/rhn/domain/errata/ErrataFactory.java, java/code/src/com/redhat/rhn/domain/errata/test/ErrataFactoryTest.java, java/code/src/com/redhat/rhn/testing/ErrataTestUtils.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/spacewalk-java.changes
Fix a potential problem when updating packages if subscribed channels are shared to other organizations
**Note**: Still need to check if this also affects the traditional stack
**Update:** The tradiational stack is not affected by this issue
No difference.
- Unit tests added
Tracks https://github.com/SUSE/spacewalk/issues/16049 …
=> Fix package update action with shared channels

java/code/src/com/redhat/rhn/frontend/xmlrpc/BaseHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/spacewalk-java.changes
For the XMLRPC function `bootstrap(...)` we used as last parameter the primitive type `boolean`.
This caused problems when detecting the right function. To find the function, the code look for the name and the same number of parameters like in the function call. In our case we fin 2:
```
int bootstrap(User, String, Integer, String, String, String, Integer, boolean)
int bootstrap(User, String, Integer, String, String, String, String, boolean)
```
The method `findPerfectMethod` compare now the XML converted type with the type in the signature.
As the XMLRPC library convert all types to Objects, we compare `boolean` with `Boolean`
which does not match.
In this case the first found method is used and a type convert is tried. But the first method is randomly changing and we could get sometimes …
=> Detect correct xmlrpc function

backend/spacewalk-backend.changes, backend/spacewalk-backend.spec
We still have a python2 dependency in a package which is already ported to python3.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/16395 https://github.com/SUSE/spacewalk/pull/16396 …
=> exchange zypp-plugin dependency to use the python3 version

testsuite/features/secondary/min_bootstrap_reactivation.feature, testsuite/features/secondary/minssh_bootstrap_xmlrpc.feature, testsuite/features/secondary/srv_datepicker.feature, testsuite/features/step_definitions/datepicker_steps.rb, testsuite/features/support/xmlrpc_system.rb
Many small or cosmetical changes, including:
* better error reporting for date picker tests
* remove unneeded `to_i` for XML-RPC tests
Ports:
* 4.1: SUSE/spacewalk#16398
* 4.2: SUSE/spacewalk#16397
=> Small or cosmetical changes for test suite

java/code/src/com/redhat/rhn/frontend/taglibs/DateTimePickerTag.java, web/html/src/manager/legacy/DateTimePicker.tsx, web/spacewalk-web.changes
Fix cases where the legacy `DateTimePicker` would pass the wrong time to the backend if selected date is in summer time or if server and user timezone differ.
As well as an issue where times between 12:00 and 12:59 would be parsed as 00:XX
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/16384 
Tracks https://github.com/SUSE/spacewalk/issues/16406 …
=> Fix legacy timepicker passing wrong time to the backend

testsuite/features/secondary/min_salt_software_states.feature, testsuite/features/secondary/minkvm_guests.feature, testsuite/features/secondary/trad_migrate_to_minion.feature, testsuite/features/step_definitions/salt_steps.rb
Since we are introducing the Salt Bundle for the registered clients, this PR adjusts some scenarios and steps definition in order to deal with the case where `venv-salt-minion` and not `salt-minion` is installed in the instances where the testsuite is running.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/14325 …
=> Testsuite: Adjust some scenarios and steps definition to work with "venv-salt-minion"

testsuite/features/secondary/min_salt_mgrcompat_state.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/salt_steps.rb
This PR fixes the manual execution of `salt-call` done by the testsuite to use `venv-salt-call` instead when running for Uyuni, as we are pushing the Salt bundle and this would be right way on the clients.
No difference.
https://github.com/SUSE/spacewalk/issues/14325 …
=> Testsuite: Adapt execution of "salt-call" to use "venv-salt-call" in Uyuni

susemanager-utils/susemanager-sls/salt/bootstrap/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR makes bootstrap state to react to `mgr_force_venv_salt_minion` pillar when performing the boostrap.
In the same way that `mgr_avoid_venv_salt_minion` pillar is disabling the usage of the Salt Bundle, this other one forces its usage, even if the bootstrap repositories do not have the `venv-salt-minion` package available, i.a. when `venv-salt-minion` is already installed in the system.
No difference.
If you don't …
=> Allow "mgr_force_venv_salt_minion" as pillar to force Salt Bundle during bootstrapping

schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.3-to-susemanager-schema-4.3.4/001-centos8-eol.sql, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
Use EL8 client tools for all EL8 clones (instead of the CentOS8 client tools, that will be EoL by the end of the year)
NOTE: We  still need to ensure that the EL8 client tools have packages that are newer or same version as CentOS8. See the [comment below](https://github.com/uyuni-project/uyuni/pull/4471#issuecomment-969036503).
No difference.
- No documentation needed: Transparent for the user
- No tests: We still don't cover CentOS8 or clones with the testsuite
Tracks: https://github.com/SUSE/spacewalk/issues/14445 …
=> Use EL8 client tools for all EL8 clones

.github/scripts/changelog.rb, .github/workflows/changelog_checker.yml
Use get-changed-files action, it also works on merged pull requests. Before, $files_modified was empty on merged pull requests and the workflow failed. Also simplified the ruby script while I was at it.
No diff.
- No documentation needed: github actions only
- No tests: github actions only
GitHub is a bit slow for me today, I want to do another manual test in my fork before ticking "done".
Couldn't find any issue.
=> Fix changelog checker

testsuite/features/step_definitions/command_steps.rb
fix query latest salt changes when the bundle is used
No difference.
=> fix query latest salt changes when the bundle is used

spacewalk/certs-tools/rhn_bootstrap.py, spacewalk/certs-tools/rhn_bootstrap_strings.py, spacewalk/certs-tools/spacewalk-certs-tools.changes, testsuite/features/core/proxy_register_as_minion_with_script.feature, testsuite/features/secondary/min_salt_mgrcompat_state.feature, testsuite/features/secondary/min_salt_software_states.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/common_steps.rb, testsuite/features/step_definitions/salt_steps.rb
This PR fixes some more issues detected in Uyuni Master acceptance tests after pushing the Salt bundle:
- Add `--force-bundle` to bootstrap script generator to force Salt bundle installation
- Fix typo in bash comparison during bootstrap
- Implement new steps to operate minion config and cache files and encapsulate logic for bundle
- Do not call `venv-salt-call` in server
- Set right process name in order to pkill targets venv-salt-minion
-  Pass `--force-bundle` when generating bootstrap scripts for minions in Uyuni
No difference. …
=> Testsuite: Add extra fixes to the testsuite after pushing Salt bundle

proxy/installer/configure-proxy.sh, proxy/installer/spacewalk-proxy-installer.changes
configure-proxy.sh check for salt-minion to fetch a real systemid file from the server which is required for a successful activation. 
This PR enhance the check for venv-salt-minion to do the same.
No difference. …
=> Fix proxy detect venv salt minion

proxy/installer/configure-proxy.sh, proxy/installer/fetch-certificate.py, proxy/installer/spacewalk-proxy-installer.spec
Fix a typo and make fetch-certificate use venv-salt-minion when it is installed.
No difference.
=> Fix typo configure proxy

susemanager-utils/susemanager-sls/salt/virt/engine-events.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
When using `venv-salt-minion` package, the minion configuration file should be placed at `/etc/venv-salt-minion/minion.d/`
No difference. …
=> Fix libvirt engine config destinion for Salt Bundle

testsuite/features/secondary/minkvm_guests.feature, testsuite/features/secondary/minxen_guests.feature
During the previous test steps, the testsuite is enabling the "Virtualization Host" system type, and this triggers a Salt call to apply a state to add the configuration file that enables the `libvirt_events` engine for the minion.
After this, the `salt-minion` (or bundle) is restarted in order to start the engine according to the new configuration.
The problem here is that the restart is done before the `libvirtd` daemon is actually up and running, so the `libvirt_events` engine is failing to start:
```
2021-11-30 10:20:24,047 [salt.loaded.int.engines.libvirt_events:762 ][ERROR   ][25231] Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': No such file or directory
File "/usr/lib/venv-salt-minion/lib/python3.9/site-packages/salt/engines/libvir …
```
=> Testsuite: Restart minion after libvirtd daemon is up and running

testsuite/features/build_validation/add_custom_repositories/add_ceos7_repositories.feature, testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature, testsuite/features/build_validation/add_custom_repositories/add_maintenance_update_repository.template, testsuite/features/step_definitions/common_steps.rb, testsuite/features/step_definitions/datepicker_steps.rb, testsuite/features/step_definitions/navigation_steps.rb
Various test suite fixes:
* 90 seconds max to pick an event ; apparently, our BV hypervisors are slower than test suite ones
* wrong error message "Couldn't find text" when the problem is that the text was found
and cosmetical changes:
* quotes in many other error messages, for readability
* feature titles
* new syntax for `raise` to make rubocop happy
Ports:
* 4.1: SUSE/spacewalk#16451
* 4.2: SUSE/spacewalk#16450
=> Various fixes

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
Adds Salt Bundle (`venv-salt-minion`) to all relevant system types
No difference.
https://github.com/uyuni-project/uyuni-docs/pull/1309
- Cucumber tests were added before
- Add Salt Bundle (venv-salt-minion) to bootstrap repositories
definitions for all relevant system types
=> Add Salt Bundle to bootstrap repos definitions

susemanager-utils/susemanager-sls/salt/services/docker.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR makes Docker states to use `venv-salt-minion` instead of `salt` in Docker state.
This fixes ramdom issues in the testsuite, as the salt-minion package is being installed and makes the following zypper commands to fail because zypper is already running:
```
FAIL: zypper mr --disable os_pool_repo os_update_repo returned 7. output : System management is locked by the application with pid 7442 (/usr/bin/zypper).
Close this application before trying again.
(RuntimeError)
./features/support/lavanda.rb:57:in `run'
./features/step_definitions/common_steps.rb:789:in `/^I disable repositories after installing Docker$/'
features/init_clients/buildhost_bootstrap.feature:75:in `And I disable repositories after installing Docker'
``` 
No difference.
- No documentation needed: only internal and …
=> Use "venv-salt-minion" instead of Salt for docker states

java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/salt/distupgrade/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes a problem which causes a failures in the Uyuni acceptance tests:
```
Install a patch on the client via Salt through the UI.Install a patch on the minion
```
The `allow_vendor_change` flag was passed as `allowVendorChange` for `patchinstall` state, while this state expects `allow_vendor_change`:
https://github.com/uyuni-project/uyuni/blob/f2da01e22c748024811d5f11844112764636baf1/susemanager-utils/susemanager-sls/salt/packages/patchinstall.sls#L24
This PR also aligns the rest of SLS files so all use `allow_vendor_change` as the pillar data that needs to be consumed by the SLS files.
No difference.
Make sure the changelogs entries …
=> Fix problem with "allow_vendor_change" flags to SLS

susemanager-utils/testing/automation/publish-rpms.sh
CI fix
gzip does not create the Packages.gz because it already
exists.
No difference.
- No tests
- X] **DONE**
=> CI: remove previous Packages.gz

java/code/src/com/redhat/rhn/manager/audit/scap/xml/Profile.java, java/code/src/com/redhat/rhn/manager/audit/test/ScapManagerTest.java, java/code/src/com/redhat/rhn/manager/audit/test/openscap/suma-ref42-min-sles15/xccdf-resume.xslt.in, java/code/src/com/redhat/rhn/testing/JMockBaseTestCaseWithUser.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/salt/scap/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
When parsing tailoring-file from the parameters we need to allow `/` for the file component.
In addition we need to check for the taloring options in the state to set the correct parameters for the call
No difference.
- Unit tests added
Tracks https://github.com/SUSE/spacewalk/pull/16358 and https://github.com/SUSE/spacewalk/pull/16467 …
=> Fix scap tailoring option

testsuite/features/step_definitions/common_steps.rb
This PR fixes a problem caused by one of testsuite fixes introduced in https://github.com/uyuni-project/uyuni/pull/4500.
Particularly for this scenario, we don't want to generate a bootstrap script that enabled the Salt bundle. The reasoning here is that, currently, based on the autoyast profile we're using, the "pxeboot" minion is autoinstalled using the "SLE basesystem" channels, and we don't have any `venv-salt-minion` package there. 
So, since autoinstallation happens without `venv-salt-minion`, we cannot generate a bootstrap script that enables the bundle.
**NOTES:**
- This step I'm fixing is currently only used by this single PXE boot for retail scenario.
- In case we want to really use the bundle on this context, we would need to adapt the autoyast profile, and provide a client …
=> Testuite: Do not enable Salt bundle for PXE minion bootstrap script

tftpsync/susemanager-tftpsync-recv/add.wsgi, tftpsync/susemanager-tftpsync-recv/delete.wsgi
Print stacktrace on error and increase the number of backup files to have the full history when running the testsuite.
No difference.
=> Improve logging in tftpsync receiver

java/code/src/com/suse/manager/webui/utils/LoginHelper.java, java/spacewalk-java.changes, schema/spacewalk/spacewalk-schema-upgrade, schema/spacewalk/susemanager-schema.changes, spacewalk/admin/spacewalk-admin.changes, spacewalk/admin/spacewalk-startup-helper, spacewalk/package/spacewalk.changes, spacewalk/package/spacewalk.spec, spacewalk/spacewalk-setup-postgresql/spacewalk-setup-postgresql.changes, spacewalk/spacewalk-setup-postgresql/spacewalk-setup-postgresql.spec
Change the database dependencies and checks to require on SUSE 15.4 a postgresql 14 DB
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/1317
Partly fix https://github.com/SUSE/spacewalk/issues/16348
=> Support Postgresql14

client/rhel/rhnlib/rhnlib.changes, client/rhel/rhnlib/rhnlib.spec, client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes, client/rhel/spacewalk-client-tools/spacewalk-client-tools.spec, client/tools/mgr-cfg/mgr-cfg.changes, client/tools/mgr-cfg/mgr-cfg.spec, client/tools/mgr-osad/mgr-osad.changes, client/tools/mgr-osad/mgr-osad.spec, client/tools/mgr-push/mgr-push.changes, client/tools/mgr-push/mgr-push.spec, client/tools/mgr-virtualization/mgr-virtualization.changes, client/tools/mgr-virtualization/mgr-virtualization.spec, client/tools/spacewalk-koan/spacewalk-koan.changes, client/tools/spacewalk-koan/spacewalk-koan.spec, client/tools/spacewalk-oscap/spacewalk-oscap.changes, client/tools/spacewalk-oscap/spacewalk-oscap.spec, suseRegisterInfo/suseRegisterInfo.changes, suseRegisterInfo/suseRegisterInfo.spec
python 2 got dropped from SLE15 and we never shipped python 2 versions of these packages.
Stop try to build them
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/15418
=> do not build python 2 package for SLE15

testsuite/features/init_clients/sle_minion.feature
Wait after a Product Migration for the Products to be displayed correctly. There are background jobs running between the Package List Refresh is finished and the Product is showed correctly.
No difference.
Partial port of https://github.com/SUSE/spacewalk/pull/16285 …
=> Wait product migration

testsuite/features/secondary/minkvm_guests.feature
=> Wait for page to be loaded in KVM tests

java/buildconf/build-props.xml, java/spacewalk-java.spec
On SUMA Head we get exceptions about 
`java.lang.NoClassDefFoundError: com/ongres/scram/common/stringprep/StringPreparation`
Provide the class in tomcat and taskomatic environment.
No difference. …
=> postgresql-jdbc needs ongres-scram dependencies

java/code/src/com/redhat/rhn/domain/action/salt/ApplyStatesActionDetails.hbm.xml, java/code/src/com/redhat/rhn/domain/action/salt/ApplyStatesActionDetails.java, java/code/src/com/redhat/rhn/domain/server/MinionServer.java, java/code/src/com/redhat/rhn/domain/server/ServerFactory.java, java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java, java/code/src/com/redhat/rhn/manager/action/ActionManager.java, java/code/src/com/suse/manager/reactor/messaging/ApplyStatesEventMessage.java, java/code/src/com/suse/manager/webui/controllers/MinionController.java, java/code/src/com/suse/manager/webui/controllers/MinionsAPI.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/templates/minion/proxy.jade, java/code/src/com/suse/manager/webui/templates/ssm/proxy.jade, java/code/src/com/suse/manager/webui/utils/gson/ServerSetProxyJson.java, java/code/webapp/WEB-INF/nav/ssm.xml, java/code/webapp/WEB-INF/pages/ssm/ssmindex.jsp, java/code/webapp/WEB-INF/pages/systems/sdc/connection.jsp, java/spacewalk-java.changes, schema/spacewalk/common/tables/rhnActionApplyStates.sql, schema/spacewalk/common/tables/rhnServerPath.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.4-to-susemanager-schema-4.3.5/010-apply-states.sql, schema/spacewalk/upgrade/susemanager-schema-4.3.4-to-susemanager-schema-4.3.5/020-server-path-idx.sql, susemanager-utils/susemanager-sls/salt/bootstrap/set_proxy.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes, web/html/src/manager/systems/index.ts, web/html/src/manager/systems/proxy.renderer.tsx, web/html/src/manager/systems/proxy.tsx, web/spacewalk-web.changes
This PR adds an API call for changing proxy.
It also extends ApplyStatesAction to handle local pillars in similar way as salt commandline.
There is an new React page `Change Proxy` reachable from minion Connection or via SSM.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/16513
Together with https://github.com/uyuni-project/uyuni/pull/4191
fixes https://github.com/SUSE/spacewalk/issues/15630 …
=> UI and API call for changing proxy

testsuite/features/build_validation/init_clients/proxy.feature, testsuite/features/core/proxy_branch_network.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/navigation_steps.rb, testsuite/features/step_definitions/salt_steps.rb, testsuite/features/support/constants.rb
Related card: https://github.com/SUSE/spacewalk/issues/16486
We want to make the systems in the private network to not have access to any external server outside the private network. This way catch this kind of issues earlier.
For now, this PR prevents this communication if the systems are configured with IPv4.
No difference.
Ports:
- Manager-4.2
- Manager-4.1 …
=> QA: Disable IPv4 forwarding on branch formula

branding/css/susemanager-theme.less, branding/css/uyuni-theme.less, branding/spacewalk-branding.changes
There was an explicit left-padding missing for a 4th-level navigation element. That's why the deepest path of the Audit section wasn't indented correctly.
Before:
After:
- No tests: Not applicable?
Not applicable. There seemed to be no issues raised with the problem solved here. …
=> Indentation for 4th level navigation element

backend/server/handlers/xmlrpc/up2date.py, backend/spacewalk-backend.changes, proxy/proxy/broker/rhnBroker.py, proxy/proxy/spacewalk-proxy.changes
When running a `zypper ref` on a client behind a proxy, the channel authentication is made against the proxy cached token... which is never updated when changing the channels.
This PR adds the `X-RHN-Auth-Channels` token to the `listChannels` response and modifies to proxy to use them to update the cached token. This way `zypper` triggers the auth token update on the proxy before trying to get data from them!
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/16488
See https://bugzilla.suse.com/show_bug.cgi?id=1193585 …
=> Proxy: update the cached channels when handling listChannels

java/code/src/com/redhat/rhn/domain/server/MinionServer.java, java/code/src/com/redhat/rhn/domain/server/ServerPath.java, java/code/src/com/redhat/rhn/domain/server/Server_legacyUser.hbm.xml, java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/code/src/com/suse/manager/reactor/test/RegisterMinionActionTest.java, java/code/src/com/suse/manager/webui/controllers/MinionsAPI.java, java/code/src/com/suse/manager/webui/controllers/utils/RegularMinionBootstrapper.java, java/code/src/com/suse/manager/webui/controllers/utils/SSHMinionBootstrapper.java, java/code/src/com/suse/manager/webui/controllers/utils/test/SSHMinionBootstrapperTest.java, java/code/src/com/suse/manager/webui/services/impl/MinionPendingRegistrationService.java, java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java, java/code/src/com/suse/manager/webui/services/impl/test/SaltSSHServiceTest.java, java/code/src/com/suse/manager/webui/services/impl/test/SaltServiceTest.java, java/code/src/com/suse/utils/Opt.java, java/code/src/com/suse/utils/test/OptTest.java, java/spacewalk-java.changes, schema/spacewalk/common/tables/suseMinionInfo.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.4-to-susemanager-schema-4.3.5/001-add-ssh-port-minion.sql, web/html/src/manager/systems/bootstrap/bootstrap-minions.tsx, web/spacewalk-web.changes
This PR adds the option to use a custom SSH port to manage a SSH-only minion. The port is configured through the UI and it's stored in the database
The port field is no longer disabled when choosing "Manage system completely via SSH (will not install an agent)":
After:
- No documentation change needed: The documentation does not reference any limitation in the choice of the SSH port.
- Cucumber tests WIP
Fixes SUSE/spacewalk/issues/12283 …
=> Allow configuring SSH port when bootstrapping SSH-only minions 

java/code/src/com/redhat/rhn/domain/contentmgmt/FilterCriteria.java, java/code/src/com/redhat/rhn/domain/contentmgmt/PackageFilter.java, java/code/src/com/redhat/rhn/domain/contentmgmt/test/ContentFilterTest.java, java/spacewalk-java.changes, web/html/src/manager/content-management/shared/business/filters.enum.test.ts, web/html/src/manager/content-management/shared/business/filters.enum.ts
Add additional matchers (lower, lowereq, greater, greatereq) to CLM package (NEVRA) filter
No difference.
- No documentation needed: **TODO: Check docs if there are mentions about the package (NEVRA) matchers**
Tracks https://github.com/SUSE/spacewalk/issues/13617
Tracks https://github.com/uyuni-project/uyuni/issues/3406 …
=> Add additional matchers to package (nevra) filter

java/code/src/com/redhat/rhn/domain/action/ActionFactory.java, java/code/src/com/redhat/rhn/domain/action/Action_legacyUser.hbm.xml, java/code/src/com/redhat/rhn/domain/action/test/ActionFactoryTest.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/spacewalk-java.changes
BugFix: backport of https://github.com/SUSE/spacewalk/pull/16254
=> BugFix: make sure pickup_time is not null when setting the status to picked up

java/code/src/com/redhat/rhn/domain/action/ActionChain.java, java/spacewalk-java.changes
Before this patch empty action chains were considered done which lead to them being deleted every time a reboot event hit the server. This could lead to new action chains being deleted in between creating them and filling them with actions leading to an error. The patch now takes empty action chains into account so that they are not considered done. 
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/16086 …
=> don't consider empty action chains done (bsc#1191377)

web/html/src/components/datetime/DateTimePicker.tsx, web/html/src/components/input/DateTime.stories.tsx, web/html/src/core/spa/spa-engine.tsx, web/html/src/manager/audit/cveaudit/cveaudit.tsx, web/html/src/manager/virtualization/guests/console/guests-console.tsx, web/html/src/manager/visualization/ui/components.ts, web/html/src/utils/functions.ts, web/html/src/utils/test-utils/timer.ts
We currently have lint warnings on old code which we don't plan to touch unless otherwise necessary. This PR adds commentary and ignores those raw date constructor uses so the lint output isn't littered.
No difference. …
=> Grandfather old date constructor uses

proxy/installer/configure-proxy.sh
No longer valid code-logic since commit 49d04c45a9b5c34569af6b0e9140a5fcca3d8ffa
No difference.
- No documentation needed: see PR's description
- No tests: see PR's description
Fixes #
=> Drop old and stale logic

reporting/reports/data/system-history, reporting/spacewalk-reports.changes
Fixes the traceback and error `more than one row returned by a subquery used as an expression` on calling `spacewalk-report system-history`
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/16060
Tracks https://github.com/SUSE/spacewalk/pull/16452
- Fixes query for system-history report to prevent more than one
row returned by a subquery with rhnxccdftestresult.identifier
(bsc#1191192)
=> Fix of system-history report query

testsuite/config/cucumber.yml, testsuite/features/secondary/srv_user_configuration_salt_states.feature
Get rid of Caasp/cluster tests, due to https://github.com/SUSE/spacewalk/issues/16456
Same for 4.1 and 4.2 due to https://github.com/SUSE/spacewalk/issues/16456
No difference.
- Cucumber tests were deleted
Ports:
- Manager-4.1
- Manager-4.2
=> Get rid of cluster tests

java/code/src/com/redhat/rhn/frontend/action/errata/ErrataDetailsSetupAction.java, java/code/src/com/redhat/rhn/frontend/action/errata/test/ErrataDetailsSetupActionTest.java, java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/code/src/com/suse/manager/errata/AbstractSimpleErrataParser.java, java/code/src/com/suse/manager/errata/AlibabaErrataParser.java, java/code/src/com/suse/manager/errata/AlmaLinuxErrataParser.java, java/code/src/com/suse/manager/errata/AmazonErrataParser.java, java/code/src/com/suse/manager/errata/ErrataParserFactory.java, java/code/src/com/suse/manager/errata/ErrataParsingException.java, java/code/src/com/suse/manager/errata/OracleErrataParser.java, java/code/src/com/suse/manager/errata/RedhatErrataParser.java, java/code/src/com/suse/manager/errata/RockyLinuxErrataParser.java, java/code/src/com/suse/manager/errata/SUSEErrataParser.java, java/code/src/com/suse/manager/errata/SUSERESErrataParser.java, java/code/src/com/suse/manager/errata/VendorSpecificErrataParser.java, java/code/src/com/suse/manager/errata/test/AlibabaErrataParserTest.java, java/code/src/com/suse/manager/errata/test/AlmaLinuxErrataParserTest.java, java/code/src/com/suse/manager/errata/test/AmazonErrataParserTest.java, java/code/src/com/suse/manager/errata/test/BaseErrataTestCase.java, java/code/src/com/suse/manager/errata/test/OracleErrataParserTest.java, java/code/src/com/suse/manager/errata/test/RedhatErrataParserTest.java, java/code/src/com/suse/manager/errata/test/RockyLinuxErrataParserTest.java, java/code/src/com/suse/manager/errata/test/SUSEErrataParserTest.java, java/code/src/com/suse/manager/errata/test/SUSERESErrataParserTest.java, java/code/webapp/WEB-INF/pages/errata/details.jsp, java/spacewalk-java.changes
This PR adds a link in the patch details page to the original vendor advisory. At the moment only SUSE is supported. More vendor will be added.
After: 
* A new section in the patch details page that show the vendor advisory link
- [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pull/1251)
Fixes SUSE/spacewalk/issues/14409
If you need …
=> Include link to vendor security advisory

susemanager-utils/susemanager-sls/src/modules/mgractionchains.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes an issue in transactional systems (SLE Micro / MicroOS) when using action chains to install/remove packages using action chains.
Before this PR, the actions are failing with the error like the following:
After this PR, the actions are successfully executed.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/14572 …
=> Fix problem installing/removing packages using action chains in transactional systems

spacewalk/setup/salt/susemanager.conf, spacewalk/setup/spacewalk-setup.changes
This PR increased the `max_event_size` value (x4) in the Salt master in order to allow events that are bigger than the default value.
There are cases, usually in cloud instances, where certain actions, particularly the HW refresh action, produces a Salt return event which is higher than the default value for the Salt master. This caused an error and therefore Java not properly parsing the HW data.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/16056
If you don't …
=> Increase "max_event_size" value for the Salt master (bsc#1191340)

backend/spacewalk-backend.changes, backend/spacewalk-backend.spec, client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes, client/rhel/spacewalk-client-tools/spacewalk-client-tools.spec, client/tools/mgr-custom-info/mgr-custom-info.changes, client/tools/mgr-custom-info/mgr-custom-info.spec, client/tools/mgr-osad/mgr-osad.changes, client/tools/mgr-osad/mgr-osad.spec, client/tools/mgr-virtualization/mgr-virtualization.changes, client/tools/mgr-virtualization/mgr-virtualization.spec, client/tools/spacewalk-client-cert/spacewalk-client-cert.changes, client/tools/spacewalk-client-cert/spacewalk-client-cert.spec, client/tools/spacewalk-oscap/spacewalk-oscap.changes, client/tools/spacewalk-oscap/spacewalk-oscap.spec, client/tools/spacewalk-remote-utils/spacewalk-remote-utils.changes, client/tools/spacewalk-remote-utils/spacewalk-remote-utils.spec, spacecmd/spacecmd.changes, spacecmd/spacecmd.spec, suseRegisterInfo/suseRegisterInfo.changes, suseRegisterInfo/suseRegisterInfo.spec, susemanager-utils/mgr-libmod/mgr-libmod.changes, susemanager-utils/mgr-libmod/mgr-libmod.spec, utils/spacewalk-utils.changes, utils/spacewalk-utils.spec, uyuni/common-libs/uyuni-common-libs.changes, uyuni/common-libs/uyuni-common-libs.spec
We get build errors because python rpm macros are not installed by default in the build system
https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/977/
=> require python macros for building

susemanager/src/mgr-create-bootstrap-repo, susemanager/susemanager.changes
Appends sha256 hash to `venv-enabled-ARCH.txt` files generated with `mgr-create-bootstrap-repo`.
The file is used to detect if the bootstrap repo contains Salt Bundle.
The hash is required for checking if we need to update Salt Bundle on salt-ssh managed systems.
No difference.
- Add sha256 hash to venv-enabled-ARCH.txt file generated with mgr-create-bootstrap-repo
=> Add hash to venv enabled txt

java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java, java/spacewalk-java.changes
This pr changes the cleanup of reboot actionchains so that it only considers actionchains that are scheduled on the minion whos event is currently processed. This fixes/reduces the likelihood of error due to concurrent deletions of actionchains.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/16275 …
=> only consider actionchains from same minion as event for deletion (bsc#1189561)

proxy/proxy/spacewalk-proxy.changes, proxy/proxy/spacewalk-proxy.spec
Removes unnecessary dependencies between packages, this is useful for the ongoing containerization effort.
No difference.
=> spacewalk-proxy: remove unnecessary dependencies to Squid

testsuite/features/support/env.rb, testsuite/features/support/twopence_init.rb
This PR makes the test suite expect MAC addresses instead of host names for Retail terminals.
It also fixes a small problem for Debian 11.
Sumaform PR: uyuni-project/sumaform#1021
Ports:
* 4.1: SUSE/spacewalk#16551
* 4.2: SUSE/spacewalk#16548
=> BV terminals have no reason to be reachable by network

testsuite/features/build_validation/init_clients/proxy.feature, testsuite/features/step_definitions/command_steps.rb
Allow all SSL Protocols in Proxy's Apache.
Explanation:
This one is very concrete for BV, as for CI we don't have a SLE11 and we don't plan to have it.
In BV, due to another issue during the cleaning process of salt packages, we handle ourselves the installation of suma_proxy pattern, so, it's not installed during salt states made by sumaform. That implies that we will not have apache installed at the moment we run salt states in sumaform. Therefore, we need to also handle ourselves from the test suite the change of config in Proxy's Apache.
No difference.
Ports:
- Manager-4.1
- Manager-4.2 …
=> BV: Allow all SSL Protocols in Proxy's Apache

testsuite/features/build_validation/core/allcli_sanity.feature, testsuite/features/core/allcli_sanity.feature
We are wrongly using eth0 in some steps
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: We are wronly using eth0 in some steps

java/code/src/com/suse/manager/webui/websocket/Notification.java, testsuite/features/secondary/srv_menu.feature
Fixes the SSM websocket errors and the virtual list menu link check in the testsuite.
No difference.
=> Virt list fix

testsuite/features/step_definitions/navigation_steps.rb, tftpsync/susemanager-tftpsync-recv/add.wsgi, tftpsync/susemanager-tftpsync-recv/configure-tftpsync.sh, tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes
- fix detection of base channel selection box in SSM channel management
- fix IPv4/IPv6 address handling when replacing PXE files from the Server (bsc#1189401)
No difference.
Tracks 
=> Improve ssm channel change and fix tftpsync IP replacement

proxy/installer/spacewalk-proxy-installer.spec
Fix `spacewalk-proxy-installer` package build
No difference.
=> Check if squid.conf is available in proxy installer post

java/buildconf/checkstyle-suppressions.xml, java/code/src/com/suse/manager/webui/controllers/MinionController.java, java/code/src/com/suse/manager/webui/controllers/MinionsAPI.java, java/code/src/com/suse/manager/webui/services/impl/SaltService.java, java/code/src/com/suse/manager/xmlrpc/dto/SystemEventDetailsDto.java
This PR fixes the `checkstyle-suppression.xml` file which contained wrong entries and fixes the javadoc of a class that was missing the documentation due to the suppressed warning.
No difference.
- No tests: just a configuration fix
n/a …
=> Removed wrong checkstyle suppressions and updated missing javadoc

.github/CODEOWNERS
While this file ends with ".py", it's not a Python code file. It "only" contains Python lists and dicts with data needed for bootstrapping.
Is there anyone who'd like to own `mgr_bootstrap_data.py`?
=> Remove mgr_bootstrap_data's code owner

spacewalk/setup/doc/conf.py
Correct the copyright incorrectly introduced in #4030
No difference.
- No tests: Docs only PR
Fixes #
These are just small changes to the manpage.
=> Change copyright according to offical docs

java/code/src/com/redhat/rhn/taskomatic/task/repomd/RpmRepositoryWriter.java, java/spacewalk-java.spec
Added libsolv-tools dependency.
Call repo2solv instead of repo2solv.sh.
No difference.
Not tested.
=> Generalised repo2solv usage

web/html/src/manager/systems/activation-key/activation-key-channels.tsx
- No documentation needed: cosmetic issue
- No tests: cosmetic issue
https://github.com/SUSE/spacewalk/issues/16415
=> Activation Keys: Only show the warning for SUMA Default, when the default channel is selected

uyuni/common-libs/uyuni-common-libs.spec
=> Old CentOSes don't support Recommends tag

backend/satellite_tools/download.py, backend/satellite_tools/repo_plugins/deb_src.py, backend/satellite_tools/repo_plugins/yum_dnf_src.py, backend/satellite_tools/repo_plugins/yum_src.py, backend/satellite_tools/reposync.py, backend/satellite_tools/test/unit/test_download.py, backend/satellite_tools/test/unit/test_reposync.py, backend/satellite_tools/test/unit/test_yum_src.py, uyuni/common-libs/common/Makefile, uyuni/common-libs/common/context_managers.py
There is a common pattern when using rhnConfig that, when forgetting a step, can cause issues in unrelated parts later on. This pattern is
1) save current component
2) switch to another component
3) read config from this component
4) switch back to the old component
There can be unforeseen bugs when the last step is forgotten.
Luckily, we now have a one-line solution that makes it impossible to forget a step -- there is only one:
with cfg_component("my_component") as CFG:
print(CFG.my_value)
No difference.
- No documentation needed: only changes implementation
I think it's a better idea to test this in uyuni before we think about backporting.
No user impacting change -> no …
=> Add context manager for rhnConfig

client/tools/mgr-cfg/mgr-cfg.changes, client/tools/mgr-cfg/mgr-cfg.spec
This PR fixes a problem with `mgr-cfg` package that is shipped in the client tools channels.
For instance in SLE15SP4, we do not build python2 subpackage but there is a hardcoded `Requires: python-selinux` that is going to make the build to fail as this package is not longer existing.
This PR fixes this "Require" to resolve properly depending on the build target.
No difference.
- No tests: **not needed**
Tracks https://github.com/SUSE/spacewalk/issues/16508 …
=> mgr-cfg: fix python selinux package name depending on build target (bsc#1193600)

spacewalk/setup/share/server_update.xml.xsl, spacewalk/setup/spacewalk-setup.changes, spacewalk/setup/spacewalk-setup.spec
update tomcat connection timeouts only if it has the previous (and now obsolete) default values.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/15719
=> Update tomcat connector timeouts to new default value

schema/spacewalk/common/views/rhnChannelNewestPackageView.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.4-to-susemanager-schema-4.3.5/030-rhnChannelNewestPackageView-fix-duplicates.sql
This PR fixes a nasty corner case that is caused when a repository provides two packages with the same nvra, where one of them has `epoch = 0` and the other one has no `epoch` defined.
The `epoch` is an optional attribute for a RPM package [1]. When this attribute is missing, it epoch is considered as "0".
For example, this repo: https://rpm.releases.hashicorp.com/RHEL/8/x86_64/stable/ provides twice the package `consul-1.10.4-1.x86_64` as we described.
The problem for Uyuni appears in `spacewalk-repo-sync` in case we are syncing a repository that provides these "conflictive" packages, but only when those packages are the latest versions for this particular package name inside the channel where we are syncing those packages. When this situation happens, it makes `spacewalk-repo-sync` to …
=> Report the latest built package on "rhnChannelNewestPackageView" when duplicates (bsc#1193612)

java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml, java/code/src/com/redhat/rhn/frontend/dto/SystemEventDto.java, java/code/src/com/redhat/rhn/frontend/dto/SystemPendingEventDto.java, java/code/src/com/suse/manager/xmlrpc/serializer/test/SystemEventDetailsDtoSerializerTest.java, java/code/src/com/suse/manager/xmlrpc/serializer/test/SystemEventDtoSerializerTest.java, java/code/webapp/WEB-INF/pages/systems/sdc/history.jsp, java/code/webapp/WEB-INF/pages/systems/sdc/pending_events.jsp, web/html/src/components/datetime/DateTimePicker.tsx
Fix an issue where the timepicker would not react to manually typed input (not using the dropdown)
This is a followup fix for https://github.com/uyuni-project/uyuni/pull/4483 and thus requires no additional changelog
Also fix issues where the wrong time would be displayed in system pending actions and action history if server timezone and user preferred timezone are differnt
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/16384 …
=> Fix timepicker not reacting to to typing input

susemanager-utils/susemanager-sls/src/grains/virt.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
In case of using Salt Bundle, `libvirt` python module is present in the salt bundle virtual environment, but `libvirt` could be not installed on the system. In this case any call for `grains` leads to writing the following message to the log or console:
```
[salt.loaded.ext.grains.virt:47  ][ERROR   ][2215] libvirtd is not installed or is not in the PATH
```
No difference.
- Add checking for libvirtd binary to grains.virt module
If you …
=> Add checking for libvirtd binary to grains.virt

susemanager-utils/susemanager-sls/src/tests/test_module_sumautil.py
Just a fix for a test.
No difference.
- Unit tests were fixed
=> Fix test_module_sumautil

java/conf/cobbler/snippets/minion_script, java/conf/cobbler/snippets/sles_register_script, java/conf/cobbler/snippets/wait_for_networkmanager_script, java/spacewalk-java.changes
In autoyast snipptes better use official XML comments and not `#` sign.
This produce XML parsing errors in yast.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/16590
=> Fix cobbler snippets xml

backend/satellite_tools/reposync.py, backend/server/importlib/backendOracle.py, backend/spacewalk-backend.changes, java/code/src/com/redhat/rhn/common/db/datasource/xml/Errata_queries.xml, java/code/src/com/redhat/rhn/domain/errata/Errata.hbm.xml, java/code/src/com/redhat/rhn/domain/errata/Errata.java, java/code/src/com/redhat/rhn/domain/errata/test/ErrataFactoryTest.java, java/code/src/com/redhat/rhn/domain/notification/test/NotificationFactoryTest.java, java/code/src/com/redhat/rhn/frontend/dto/ErrataOverview.java, java/code/src/com/redhat/rhn/taskomatic/task/repomd/UpdateInfoWriter.java, java/code/src/com/redhat/rhn/taskomatic/task/repomd/test/UpdateInfoWriterTest.java, java/spacewalk-java.changes, schema/spacewalk/common/tables/rhnErrata.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.4-to-susemanager-schema-4.3.5/030-add-rights-to-errata.sql
This PR retrieves and store the copyright information from the remote repository in order to add it to the updateinfo.xml of the generated repository. 
No difference.
Fixes SUSE/spacewalk/issues/12198 …
=> Add rights field to generated updateinfo.xml

java/code/src/com/redhat/rhn/manager/channel/CloneChannelCommand.java, java/code/src/com/redhat/rhn/manager/channel/test/CloneChannelCommandTest.java, java/spacewalk-java.changes
When cloning a channel via CLM, a DB trigger copies comps entries on insert. This PR removes the `modules.yaml` entry correctly when it should be removed.
https://bugzilla.suse.com/show_bug.cgi?id=1193008
Port of https://github.com/SUSE/spacewalk/pull/16447
=> Fix stripping module metadata when cloning channels in CLM (bsc#1193008)

web/html/src/.eslintrc.production.js, web/html/src/build/fill-spec-file.js, web/html/src/manager/systems/proxy.tsx
Currently, production lint allows unused variables which means cleaning them up later if someone forgets something. This PR disallows them.
No difference.
- No tests: Internal changes only.
=> Disallow unused variables in production

java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml, java/code/src/com/redhat/rhn/domain/rhnpackage/PackageFactory.java, java/code/src/com/redhat/rhn/domain/rhnpackage/Package_satellite.hbm.xml, java/code/src/com/redhat/rhn/frontend/action/rhnpackage/LockPackageAction.java, java/code/src/com/redhat/rhn/frontend/dto/PackageListItem.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/code/src/com/redhat/rhn/manager/action/ActionManager.java, java/code/src/com/redhat/rhn/manager/rhnpackage/PackageManager.java, java/code/src/com/redhat/rhn/manager/user/UserManager.java, java/spacewalk-java.changes
Add new endpoints to packages API: schedulePackageLockChange, listLocks
Minor changes:
- allow `ActionManager.schedulePackageLock` to take as argument a list of server
- fix format mismatch between PackageListItem class and Package class NEVRA
- add package_id `system.listInstalledPackages`
- system.listInstalledPackages object in a more readable order 
No difference.
API Documentation 
- N/A
Fixes https://github.com/SUSE/spacewalk/issues/15573 …
=> package locking XMLRPC API

testsuite/features/build_validation/smoke_tests/smoke_tests.template, testsuite/features/secondary/allcli_overview_systems_details.feature, testsuite/features/step_definitions/common_steps.rb
This will add more tests for the system details overview page, e.g. uptime, IP addresses, SUSE Manager system ID, etc.
No difference.
Before:
After:
Ports:
Manager-4.1
Manager-4.2 …
=> QA: Add tests for details overview page

testsuite/features/core/proxy_branch_network.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/common_steps.rb, testsuite/features/step_definitions/salt_steps.rb, testsuite/features/support/constants.rb, testsuite/features/support/lavanda.rb
Fix ADDRESSES hash keys, as in some places we use a text for a host, and in other places, we use another text for the same host. So we can't use the key in different hash tables.
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Fix ADDRESSES hash keys

susemanager-utils/testing/automation/run-command-in-server.py
This is an utility for the Continuous Integration system.
This utility uses paramiko to run a command via ssh.
We can use this for testing and debugging.
For example, for setting a custom header.
No difference.
- No tests
https://github.com/SUSE/susemanager-ci/pull/419 …
=> [CI] Add run-command-in-server.py utility

web/html/src/components/table/TableDataHandler.tsx, web/html/src/core/user-preferences/index.ts, web/html/src/manager/admin/setup/products/products.tsx, web/html/src/manager/admin/task-engine-status/taskotop.tsx, web/html/src/manager/audit/cveaudit/cveaudit.tsx, web/html/src/manager/audit/subscription-matching/subscription-matching-messages.tsx, web/html/src/manager/audit/subscription-matching/subscription-matching-pins.tsx, web/html/src/manager/audit/subscription-matching/subscription-matching-subscriptions.tsx, web/html/src/manager/audit/subscription-matching/subscription-matching-unmatched-products.tsx, web/html/src/manager/content-management/list-filters/list-filters.tsx, web/html/src/manager/content-management/list-projects/list-projects.tsx, web/html/src/manager/images/image-profiles.tsx, web/html/src/manager/images/image-stores.tsx, web/html/src/manager/images/image-view-packages.tsx, web/html/src/manager/images/image-view-patches.tsx, web/html/src/manager/images/image-view.tsx, web/html/src/manager/maintenance/list/calendar-list.tsx, web/html/src/manager/maintenance/list/schedule-list.tsx, web/html/src/manager/notifications/notification-messages.tsx, web/html/src/manager/salt/formula-catalog/org-formula-catalog.tsx, web/html/src/manager/salt/keys/key-management.tsx, web/html/src/manager/state/recurring-states-list.tsx, web/html/src/manager/systems/ssm/ssm-subscribe-channels.tsx, web/html/src/manager/systems/virtual-list.tsx, web/html/src/manager/systems/virtualhostmanager/virtualhostmanager-details.tsx, web/html/src/manager/systems/virtualhostmanager/virtualhostmanager-list.tsx
Move page size into a shared module for user prefs and remove unnecessary page size configs on tables. `Table` simply passes the `initialItemsPerPage` prop through to `TableDataHandler` which already internally uses the user's pref by default so all of those are unnecesary.
No difference.
If you need to …
=> Make page size usage more consistent

web/html/src/components/buttons.tsx, web/html/src/components/config-channels.tsx, web/html/src/components/datetime/DateTimePicker.tsx, web/html/src/components/fields.tsx, web/html/src/components/formula-selection.tsx, web/html/src/components/formulas/EditGroup.tsx, web/html/src/components/formulas/PasswordInput.tsx, web/html/src/manager/audit/cveaudit/cveaudit.tsx, web/html/src/manager/images/image-build.tsx, web/html/src/manager/images/image-import.tsx, web/html/src/manager/images/image-profile-edit.tsx, web/html/src/manager/images/image-profiles.tsx, web/html/src/manager/images/image-store-edit.tsx, web/html/src/manager/images/image-stores.tsx, web/html/src/manager/images/image-view-patches.tsx, web/html/src/manager/images/image-view.tsx, web/html/src/manager/salt/cmd/remote-commands.tsx, web/html/src/manager/salt/keys/key-management.tsx, web/html/src/manager/state/recurring-states.tsx, web/html/src/manager/systems/bootstrap/bootstrap-minions.tsx, web/html/src/manager/systems/virtualhostmanager/virtualhostmanager-details.tsx, web/html/src/manager/systems/virtualhostmanager/virtualhostmanager-edit.tsx, web/html/src/manager/systems/virtualhostmanager/virtualhostmanager.tsx
A common anti-pattern that we have is a string-based method binding loop in constructors. This is unnecessary and only makes the constructor very verbose. Most of these methods don't actually even need to be bound, but currently I went for the functionally equivalent option so I don't have to manually test every method that's affected.
No difference. …
=> Remove constructor context binding

web/html/javascript/spacewalk-essentials.js, web/html/javascript/spacewalk-login.js
As far as I could see, `spacewalk-login.js` is not actually used anywhere anymore given the login page is now in React. This also means the `formFocus` function is not used anywhere.  
Tagging Michael for a review just in case there's some arcane knowledge background that I'm missing here.
No difference.
- No tests: Unused code.
If …
=> Drop `spacewalk-login.js`

.github/CODEOWNERS, .yarnrc
Disable running package post-install scripts etc by default. This reduces our surface to misc attack vectors from packages.
No difference.
- No tests: Dependency management.
=> Don't run package scripts by default

testsuite/features/secondary/srv_restart.feature, testsuite/features/step_definitions/common_steps.rb, testsuite/features/step_definitions/navigation_steps.rb, testsuite/run_sets/secondary.yml
Add a feature to the testsuite that check if the server can be restarted through the WebUI 
Admin > Manager Configuration > Restart  options. In case of timeout, we refresh manually and navigate again to the same page to see that indeed the server was restarted.
Issue: https://github.com/SUSE/spacewalk/issues/9619
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/9619 …
=> Add restart_feature to testsuite

java/code/src/com/redhat/rhn/GlobalInstanceHolder.java, java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemDeleteConfirmAction.java, java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemMigrateAction.java
JSP actions constructors are expected to have no parameter. Use the
global instance holder to retrieve service managers in them.
This fixes a lot of the ISE in the cucumber runs after the merge of https://github.com/uyuni-project/uyuni/pull/4616
No difference.
Fixes # …
=> Use global instance holder from JSP actions

testsuite/features/step_definitions/common_steps.rb
This is a fixup PR for #4582. The uptime is displayed much more granular so the tests have to be, too.
No difference.
Before:
After:
Ports:
Manager-4.1
Manager-4.2 …
=> fix: Uptime in details overview page

proxy/proxy/rhnAuthCacheClient.py, proxy/proxy/spacewalk-proxy.changes
Gets rid of `new` Python 2 module used by `rhnAuthCacheClient.py` for `new.instance` call for exception handling.
This call is not really required there as it was used to handle very specific cases which shouldn't really happen and it's safe to handle the exception without it.
No difference.
- No tests: no any unit tests for this part
Fixes https://github.com/uyuni-project/uyuni/issues/4126
Tracks https://github.com/SUSE/spacewalk/issues/16248
- Remove old Python 2 dependency on module new from rhnAuthCacheClient
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyun …
=> Get rid of new.instance from rhnAuthCacheClient

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
Take the bootstrap repo location from the default spacewalk config file. This allows the correct destination folder on SUSE or EL.
No difference.
- No tests: 
File manually tested on AlmaLinux 8
=> Take bootstrap destination folder from config file

testsuite/features/support/twopence_init.rb
If the testsuite setup does include an additional network, the sanity check will fail with a ruby error.
This checks if private network variable is set before using it and assign the network prefix variable.
No difference.
Before:
After: …
=> Correct sanity check on cucumber tests without secondary network

java/code/src/com/redhat/rhn/domain/contentmgmt/FilterCriteria.java, java/code/src/com/redhat/rhn/domain/contentmgmt/PackageFilter.java, java/code/src/com/redhat/rhn/manager/contentmgmt/DependencyResolver.java, java/code/src/com/redhat/rhn/manager/contentmgmt/test/DependencyResolverTest.java, java/code/src/com/redhat/rhn/manager/contentmgmt/test/MockModulemdApi.java, java/spacewalk-java.changes, uyuni/common-libs/common/rhn_rpm.py, uyuni/common-libs/uyuni-common-libs.changes
During reposync, we look for a special RPM header tag called MODULARITYLABEL to find out if a package is modular and do the filtering for AppStream modules accordingly.
However, I've been checking out the actual metadata from various distributions (centos8, oraclelinux, almalinux, etc.) and found out that some maintainers use a different approach to label modular metadata in packages.
Some distributions use different tags, and some don't specify any tag at all. To make sure CLM works with all variants, we need to revert to filtering all the modular packages regardless of their tags, while still writing modularity tags into the DB for future use and debugging.
https://bugzilla.suse.com/show_bug.cgi?id=1192487
Port of https://github.com/SUSE/spacewalk/pull/16409 …
=> Avoid using RPM tags when filtering modular packages in CLM (bsc#1192487)

web/html/src/utils/network.ts, web/spacewalk-web.changes
Michael found a bug where GET requests are sending an unnecessary empty object as their data. This PR fixes the issue, but needs a testsuite run first.
No difference.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1194397 …
=> Don't send empty objects with GET requests

susemanager-branding-oss/susemanager-branding-oss.spec
Dynamic html docroot location for SUSE and non-suse systems
No difference.
not specifically tested
=> susemanager-branding-oss: Dynamic html docroot

backend/satellite_tools/mgr-sign-metadata-ctl, backend/satellite_tools/spacewalk-debug, backend/spacewalk-backend.spec
Replaced static html document root links with `spacewalk-cfg-get`
No difference.
No testing
=> spacewalk-backend: Removed static links

susemanager/susemanager.spec
Replaced static tftpboot folder creation during package installation.
No difference.
Not tested
=> Replaced static tftpboot folder creation

java/spacewalk-java.spec
- Fixed susemanager location for EL8.
- Reduced used variables to reduce complexity.
No difference.
Build and install tested successfully locally on Alma
=> spacewalk-java: Dynamic /srv folder

susemanager-utils/susemanager-sls/salt/channels/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Fixes dnf plugin path calculation in `channels` state while using Salt Bundle. As Salt Bundle is running with python version other than used for dnf plugins.
No difference.
Fixes https://github.com/uyuni-project/uyuni/pull/4626
- Fix dnf plugin path calculation when using Salt Bundle …
=> Fix channels state path calculation for dnf plugin with bundle

backend/satellite_tools/repo_plugins/yum_dnf_src.py
Fix using `CFG` with `cfg_component` context manager.
`CFG` was not defined in `setup_repo` of `yum_dnf_src` plugin.
No difference.
Tracks https://github.com/uyuni-project/uyuni/pull/4264/files …
=> Fix cfg_component in setup_repo of yum_dnf_src

susemanager/susemanager.spec
Reverts uyuni-project/uyuni#4641
See https://build.opensuse.org/package/live_build_log/systemsmanagement:Uyuni:Master/susemanager/openSUSE_Leap_15.3/x86_64
=> Revert "Cleanup of motd msg after uninstall"

testsuite/features/step_definitions/common_steps.rb
This is a fixup PR for #4582. The uptime is now rounded upfront.
No difference.
Before:
After:
Ports:
Manager-4.1
Manager-4.2 …
=> fix: Uptime in details overview page II

branding/css/buttons.less, web/html/src/manager/header/search/search.tsx
I introduced a small padding difference with the latest header update, this fixes the bug.
Few pixels of padding.
- No tests: Visual change only.
Followup to https://github.com/uyuni-project/uyuni/pull/4612
=> Fix header padding bug

backend/satellite_tools/download.py, backend/spacewalk-backend.changes, backend/spacewalk-backend.spec
This PR fixes a small issue that prevents "spacewalk-repo-sync" to properly work with latest `urlgrabber` version 4.1.0.
This PR requires:
- https://build.opensuse.org/request/show/942105 (Uyuni)
- https://build.suse.de/request/show/261056 (SUMA Head)
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/10749 …
=> Fix issues to work with latest "urlgrabber" version 4.1.0

.github/workflows/update_translations.yml
run the update translation script on weblate branch when weblate is pushing
No difference.
Before:
After:
Fixes #
Tracks # **add downstream PR, if …
=> run on master-weblate only when weblate pushes

spacewalk/package/spacewalk.spec, susemanager/bin/server-migrator.sh, susemanager/susemanager.changes
Upgrade server migrator to upgrade to 15.4.
No difference.
- Documentation required, issue will be created
- No tests
Partial fix https://github.com/SUSE/spacewalk/issues/16348
=> server migrator to 15.4

backend/satellite_tools/contentRemove.py, backend/spacewalk-backend.changes
Print more clear errors on calling `spacewalk-remove-channel` if `shutil.rmtree` raises an exception.
Before the change we can get the following output:
```
ERROR: unhandled exception occurred: ([Errno 30] Read-only file system: 'ARCHIVES.gz').
File "/usr/bin/spacewalk-remove-channel", line 220, in <module>
sys.exit(main() or 0)
File "/usr/bin/spacewalk-remove-channel", line 194, in main
just_kickstart_trees=options.just_kickstart_trees)
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/contentRemove.py", line 273, in delete_channels
_delete_ks_files(channelLabels)
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/contentRemove.py", line 606, in _delete_ks_files
shutil.rmtree(path, onerror=rm_error)
File …
```
=> Print more clear errors for spacewalk-remove-channel (bsc#1190564)

testsuite/features/step_definitions/common_steps.rb
Currently the following cucumber secondary tests are failing in Uyuni (not in Manager-4.2) 
- Lock packages on SLES salt minion.Attempt to install a locked package on the client
- Lock packages on traditional client.Attempt to install a locked package on the client
The issue is caused by a new HTML time format in UI: 
4.2: `<td>2022-01-03 15:09:02 CET </td>`
Uyuni: `<time data-reference-date="2022-01-03T15:59:46.765+01:00" datetime="2022-01-03T15:57:30.115+01:00">2022-01-03 15:57:30 CET  </time>`
The PR adapts the cucumber function in order to parse correctly the new format.
No difference. …
=> Fix lock secondary test

search-server/spacewalk-search/spacewalk-search.spec
This PR changes the spec file for seach package to not refer jakarta packages anymore.
I use the or option to keep compatibility with centos release like it was made in [1]
I think spacewalk java is already compatible with the package renaming.
There are only a couple of places I'm not completely sure [2] [3] [4].
I think I will need some guidance on how I can test these changes. I search the build server and the available packages on opensuse leap product. 
[1] https://github.com/uyuni-project/uyuni/pull/2953/files#diff-2de3ee26fbb18696208de9203d6937cc7551c86324f208e4dee716f4d43cf874R47-R52
[2] https://github.com/uyuni-project/uyuni/blob/master/java/spacewalk-java.spec#L645
[3] https://github.com/uyuni-project/uyuni/blob/master/java/spacewalk-java.spec#L649
[4] …
=> Uyuni 10544 jakart packages

client/tools/mgr-cfg/mgr-cfg.changes, client/tools/mgr-cfg/mgr-cfg.spec, client/tools/mgr-osad/mgr-osad.changes, client/tools/mgr-osad/mgr-osad.spec, client/tools/mgr-virtualization/mgr-virtualization.changes, client/tools/mgr-virtualization/mgr-virtualization.spec, client/tools/spacewalk-koan/spacewalk-koan.changes, client/tools/spacewalk-koan/spacewalk-koan.spec, client/tools/spacewalk-oscap/spacewalk-oscap.changes, client/tools/spacewalk-oscap/spacewalk-oscap.spec
This PR fixes some of the changes introduced in https://github.com/uyuni-project/uyuni/pull/4537/ in order to disable the python2 builds only for SLE15SP4 and higher, to avoid problems with latest released python2 subpackages.
No difference.
- Tracks: https://github.com/SUSE/spacewalk/issues/16508
- 
If …
=> Do not build python2 subpackages for SLE15SP4 and higher

.github/reviewers.yml, testsuite/features/core/proxy_branch_network.feature, testsuite/features/step_definitions/command_steps.rb
Various BV fixes:
* `ip -4` is not supported on older systems like SLE 11 and SLE 12
force using IPv4 for ping tests by not using the FQDN
* remove useless lines in `proxy_branch_network.feature`
* add Vanda to the reviewers
Ports:
* 4.1: SUSE/spacewalk#16663
* 4.2: SUSE/spacewalk#16661
=> BV various fixes

testsuite/features/secondary/srv_restart.feature
Changes the text we check in this feature so that it works with uyuni also.
No difference.
Fixes I didn't create an issue this is directly from testsuite review. …
=> Fix restart text

schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/702-debvercmp.sql
Continue with index migration when the expected indexes do not exist.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/16423
=> continue migration when indexes do not exist

java/spacewalk-java.spec, search-server/spacewalk-search/spacewalk-search.spec
This patch is changing our spec files to just make it more obvious that we are using log4j12 vs. log4j 2.x. It was already the case before, but previously the log4j12 package was named just log4j (in centos?), therefore this patch is just cleaning up leftovers.
No difference.
- No documentation needed: no visible or behavioral changes.
- No tests needed: no visible or behavioral changes.
Fixes # …
=> Make it more obvious that we are using log4j12

testsuite/features/core/proxy_register_as_minion_with_script.feature, testsuite/features/step_definitions/command_steps.rb
workaround for groff-full install bug.
Remove as soon as the bug is fixed in SP4 Beta
No difference.
https://bugzilla.suse.com/show_bug.cgi?id=1192195
=> workaround for bug 1192195 - change zypp conf to install docs

web/html/javascript/channel_tree.js, web/html/javascript/tree.js
Stumbled upon these while working on https://github.com/uyuni-project/uyuni/pull/4676. This PR removes IE detection hacks since they're picked up as license comments by the license extractor.  
No difference. …
=> Drop IE detection hacks

testsuite/features/build_validation/add_custom_repositories/srv_common_channels.feature, testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/step_definitions/navigation_steps.rb, testsuite/features/step_definitions/retail_steps.rb
This PR is specific to build validation.
It is possible that some VMs like Debian 11 or openSUSE 15.3 are not supported in some branches.
Furthermore, it might be we don't want to test with all supported clients.
This PR adds cucumber tags for declaring channels and synchronizing them, according to which clients we have.
Caveat: `@debian9_minion or @debian9_ssh_minion` does not work. Therefore we are examining the minion only, assuming we will never have the ssh minion without the base minion.
Alternative: SUSE/spacewalk#16697
** Also piggybacking a fix to Retail preparation PR. **
Ports:
* 4.1: SUSE/spacewalk#16712
* 4.2: SUSE/spacewalk#16711
=> Add cucumber tags for build validation clients

susemanager-utils/testing/automation/obs-project.py
CI: to avoid getting "noisy" emails to other users from obs
No difference.
- No tests
N/A
=> CI: set only one maintainer for obs proxy

testsuite/features/step_definitions/command_steps.rb, testsuite/features/upload_files/sle-15-sp2-autoyast.xml
Force tftp to use proxy instead of server
No difference.
Fixes no issue, was created directly from testsuite review
=> Force tftp to use proxy instead of server

susemanager/bin/server-migrator.sh, susemanager/susemanager.changes
We should have not merged this yet because of 2 reasons:
1- we do not support 15.4 yet
2- users can't migrate to 15.3 if we do not revert
No difference.
- No tests
N/A
=> Revert server migrator to 15.4

testsuite/features/secondary/proxy_cobbler_pxeboot.feature
passes the variable for redhat_management_server=proxy.example.org via UI instead of xml directly. We don't interfere with virtualisation tests. Goes together with https://github.com/uyuni-project/uyuni/pull/4705
No difference.
Fixes no issue, directly from testsuite review
Tracks 4.2: https://github.com/SUSE/spacewalk/pull/16731
4.1: https://github.com/SUSE/spacewalk/pull/16732 …
=> Pass variable via UI

testsuite/features/support/commonlib.rb
```
https://download.suse.de/ibs/SUSE:/Maintenance:/22379/
https://download.suse.de/download/ibs/SUSE:/Maintenance:/22379/ 
```
are both valid. Let's remove both prefixes, so we can use both forms on the `.json` file.
Ports:
* 4.1:
* 4.2: SUSE/spacewalk#16750
=> Some MUs have a different URL prefix

testsuite/features/build_validation/init_clients/proxy.feature
We can't reload apache if it's not running yet.
In any case, it's safer to modify its configuration only after SUSE Manager's configuration script has run.
Ports:
* 4.1: SUSE/spacewalk#16752
* 4.2: SUSE/spacewalk#16753
=> Don't tune SSL before the proxy is configured

testsuite/features/build_validation/smoke_tests/smoke_tests.template, testsuite/features/step_definitions/common_steps.rb
- Adds a specific message for special cases (1 day uptime shows "a day ago", 1 minute is "a minute ago" and so on)
- Fixes the uptime rules, according to the moment.js library: 
- <1min is "a few seconds ago"
- \>=45min is "an hour ago"
- \>=22 hours is "a day ago"
- \>=25 days is "a month ago"
- Run the uptime command only once, for getting the different uptime time units
No difference.
- [4.1](https://github.com/SUSE/spacewalk/pull/16710)
- [4.2](https://github.com/SUSE/spacewalk/pull/16755)
=> Fix uptime display tests to follow moment.js library rules

testsuite/features/step_definitions/common_steps.rb
Allow `fe80:` addresses when there are no `2620:` addresses.
This assumes SUSE Manager always displays the last IPv6 address, but according to my tests it is true.
Ports:
* 4.1: SUSE/spacewalk#16775
* 4.2: SUSE/spacewalk#16774
=> Allow link-local fe80: ipv6 addresses

client/tools/mgr-cfg/mgr-cfg.changes, client/tools/mgr-cfg/mgr-cfg.spec
This PR fixes a situation when installation `mgr-cfg` from the SLE15 clients tools. The packages on this channels are built based on SLE15SP0 and this means the logic we have in the spec file for the require of `python-selinux` is not working as expected for SLE15SP4.
Since we do not ship any `python2-mgr-cfg` as part of the SLE15 client tools, it is safe to fix the spec logic to simply do not require `python-selinux` for any SLE15 SP.
No difference. …
=> Fix "mgr-cfg" installation problem on SLE15SP4

testsuite/features/step_definitions/common_steps.rb
In the details page, test in order of priority:
- first the global IPv6 address with privacy extensions,
- then the global IPv6 address derived from MAC
- then the link-local IPv6 address.
Ports:
* 4.1: SUSE/spacewalk#16816
* 4.2: SUSE/spacewalk#16815
=> Test IPv6 address based on importance

testsuite/features/build_validation/smoke_tests/smoke_tests.template, testsuite/features/step_definitions/common_steps.rb
Fixes Ruby casting error on line 85 of common steps and uncomments no longer needed workaround for IPV6 on clients
No difference.
- Fixes [#16720](https://github.com/SUSE/spacewalk/issues/16720)
- [4.1](https://github.com/SUSE/spacewalk/pull/16817)
- [4.2](https://github.com/SUSE/spacewalk/pull/16818)
=> Fix uptime failing tests and re-enable IPV6 tests for clients

susemanager-utils/susemanager-sls/modules/engines/mgr_events.py
Depending on the Salt version, event.unpack has a different API.
Once we only use Salt 3004, we can fully switch to the new syntax.
No difference.
Before:
After:
Fixes # …
=> Call event.unpack correctly

susemanager-utils/susemanager-sls/modules/engines/mgr_events.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes a problem when getting the major Salt version on 3004:
```
2022-02-01 09:35:05,202 [tornado.application:640 ][ERROR   ][29129] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f028f5496a8>, <salt.ext.tornado.concurrent.Future object at 0x7f02833ac550>)
File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
ret = callback()
File "/usr/lib/python3.6/site-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
return fn(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 628, in _discard_future_result
future.result()
File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result …
```
=> Fix unpack issue getting Salt major version from "mgr_events"

testsuite/features/secondary/min_salt_install_package.feature
Related PR https://github.com/SUSE/spacewalk/issues/14248
No difference.
Ports:
- [Manager-4.1](https://github.com/SUSE/spacewalk/pull/16833)
- [Manager-4.2](https://github.com/SUSE/spacewalk/pull/16834) 
=> QA: Reinforce the cleanup of min_salt_install_package.feature

testsuite/features/secondary/min_ssh_tunnel.feature
Related Card: https://github.com/SUSE/spacewalk/issues/14247
Enforce the clean-up on min_ssh_tunnel.feature
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/16835
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/16836 …
=> QA: Wait for minion registration in the cleanup of min_ssh_tunnel

testsuite/features/secondary/buildhost_osimage_build_image.feature, testsuite/features/secondary/minkvm_guests.feature, testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature, testsuite/features/support/commonlib.rb, testsuite/features/support/env.rb
Related card: https://github.com/SUSE/spacewalk/issues/13530
Get rid of long_tests tag.
In addition, we want to also remove this parameter from our pipeline https://github.com/SUSE/susemanager-ci/pull/449
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/16837
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/16838 …
=> QA: Get rid of long_tests tag

java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml
ongres-scram is required to authenticate against a postgres DB which is configured scram-sha256 auth method.
Since Pg14 this is the default.
No difference.
- No tests: **development tools only**
=> add ongres-scram to ivy dependencies

java/code/src/com/redhat/rhn/manager/action/ActionManager.java, java/code/src/com/redhat/rhn/manager/action/test/ActionManagerTest.java, java/spacewalk-java.changes
When multi server action is canceled for just one of the servers we cannot unschedule the action on taskomatic side, only remove it from server actions. This filtering was missing when constructing options for taskomatic call and this PR adds it.
Port of https://github.com/SUSE/spacewalk/pull/16693
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/16608
Tracks https://github.com/SUSE/spacewalk/pull/16693 …
=> Filter actions to cancel by selected servers

.github/reviewers.yml, testsuite/features/step_definitions/command_steps.rb
This PR provides a CNAME for `proxy.example.org` on the branch network, so we don't get a `503` when PXE booting from cobbler or Retail.
(also adding back Dominik to the reviewers).
Ports:
* 4.1:
* 4.2:
=> Finish separation of private network

testsuite/features/support/commonlib.rb
This small change fix this issue:
```
Unable to find xpath "//i[contains(@class, 'fa-bell')]/following-sibling::*[text()='30  ']" (Capybara::ElementNotFound)
./features/step_definitions/common_steps.rb:1088:in `/^the notification badge and the table should count the same amount of messages$/'
features/secondary/srv_notifications.feature:14:in `the notification badge and the table should count the same amount of messages'
```
Note the '30  ' text.
No difference.
Ports:
- Manager-4.1
- Manager-4.2
If you don't …
=> QA: Strip a text containing the amount of items

testsuite/features/secondary/proxy_cobbler_pxeboot.feature, testsuite/features/step_definitions/command_steps.rb
Cobbler tests: squid needs being restarted so that the CNAME in the SSL certificate for proxy.example.org is recognized.
=> Restart squid so proxy.example.org is recognized

java/buildconf/ivy/ivy-suse.xml
Hibernate package was updated. Align ivy repo to new version to fix the test runs.
No difference.
=> hibernate was updated to 5.3.25

testsuite/features/support/env.rb
By design https://github.com/cucumber/cucumber-ruby/issues/1101 if we raise an error inside the AfterStep hook, it will not really show as failed in the scenario. This PR tries to solve that issue and at same time increase the timeout from the default (10) to 15 seconds.
No difference.
Ports:
- Manager-4.1
- Manager-4.2 …
=> QA: Fail the scenario if the Ajax Timeout raises

testsuite/features/secondary/proxy_cobbler_pxeboot.feature, testsuite/features/step_definitions/common_steps.rb
Do not do /etc/hosts hacks, especially when they can break other things
Ports:
* 4.1: SUSE/spacewalk#16882
* 4.2: SUSE/spacewalk#16883
=> cobbler should work without such horrible hacks

testsuite/features/step_definitions/retail_steps.rb
Fix typo checking for existence of an image
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Fix typo checking for existence of an image

spacecmd/spacecmd.changes, spacecmd/src/spacecmd/errata.py, spacecmd/src/spacecmd/system.py, spacecmd/tests/test_errata.py
This PR fixes an issue in `spacecmd`, which is not properly detecting interactive/non-interactive mode when running `system_applyerrata` and `errata_apply` commands:
```console
suma-42-srv.tf.local:~ # spacecmd 
Welcome to spacecmd, a command-line interface to Spacewalk.
Type: 'help' for a list of commands
'help <cmd>' for command-specific help
'quit' to quit
INFO: Connected to https://suma-42-srv.tf.local/rpc/api as admin
spacecmd {SSM:0}> system_applyerrata suma-42-min-sles15sp3.tf.local SUSE-15-SP3-2021-2858
Errata             Systems
--------------     -------
SUSE-15-SP3-2021-2858          1
Start Time: 20220120T17:46:52
spacecmd {SSM:0}> 
```
As you see, the command exited, didn't ask for user confirmation and directly existed without scheduling any action as it was expected.
With …
=> spacecmd: fix interactive mode for "system_applyerrata" and "errata_apply" commands (bsc#1194363)

testsuite/features/secondary/min_bootstrap_reactivation.feature
After the re-activation we need to wait for the bootstrapping really finished before we start to cleanup the system again.
It happened that we removed the system before the state apply finished. This cause state files requested which were already removed and in the database the system not yet fully exist while we already try to remove it again.
No difference. …
=> wait for onboarding completed before cleaning up again

testsuite/features/step_definitions/common_steps.rb
Fixing this case:
Where the type returned in the output is not an Array but a String, as there is only one line in the log.
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Fix the case of having a one line in the salt event logs

web/html/src/jest.config.js, web/html/src/package.json
Limit the amount of CPU threads and memory available to Jest to see if that's the source of CI issues as seen [here](https://ci.suse.de/view/Manager/view/Manager-Head/job/manager-Head-dev-javascript-lint/4970/console).
No difference. …
=> Test Jest performance throttling

susemanager/susemanager.spec
This change removes the message `You can access <PRODUCTNAME> via https://<HOSTNAME>` on login when the susemanager package has been removed.
No difference.
- No tests: none done. Low impact.
=> Cleanup of motd msg after uninstall

uyuni/base/uyuni-base.spec
- Changed Apache user for Enterprise Linux systems. User Apache does exist but is not really used. Root is used instead.
- Removed RHEL6 logic to remove complexity in SPEC files.
No difference.
Build retested manually via `rpmbuild -ba` …
=> uyuni-base: minor improvements

susemanager-utils/susemanager-sls/salt/services/salt-minion.sls, susemanager-utils/susemanager-sls/salt/util/mgr_disable_fqdns_grain.sls, susemanager-utils/susemanager-sls/salt/util/mgr_mine_config_clean_up.sls, susemanager-utils/susemanager-sls/salt/util/mgr_start_event_grains.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Having problems with minions configured wrong where changes we did in the past were not applied.
We better use the template during highstate for minions `susemanager.conf` we also use during bootstrapping time.
We do **not** watch the config file changes to prevent restarting the minion during bootstrapping.
This could result into lost actions like the package or hardware refresh when the minion gets restarted when these actions are currently waiting in the queue.
Port of https://github.com/SUSE/spacewalk/pull/16620
Adapted for venv usage
No difference. …
=> Configure minion correct

java/code/src/com/redhat/rhn/taskomatic/task/RebootActionCleanup.java, java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/spacewalk-java.changes
A race condition seems to happen again.
Change the code to switch an action to state "Picked Up" only when the current state is "Queued"
and add debug looging for cleanup action.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/16408 …
=> Fix salt job race

testsuite/features/step_definitions/command_steps.rb
When a product is selected, more time is needed than before to see the first reposync start.
This PR increases the inactivity timeout when we wait for all non-killed reposyncs to finish.
(seen only on `filemon` private test server, probably because it's slower)
Ports:
* 4.1: SUSE/spacewalk#16908
* 4.2: SUSE/spacewalk#16909
=> Longer reposync inactivity delay

spacecmd/spacecmd.changes, spacecmd/src/spacecmd/group.py, spacecmd/tests/test_group.py
`spacecmd group_backup` command backups system groups. This backup backups only name and description.  However since some time we allow formulas to be configured for groups as well. This PR enhanced backup (and restore via `spacecmd group_restore`) to include formulas configuration in the group backup.
Previously group backups were simple text files containing description string of the group. For formulas I changed that format to be in a JSON format having special field for description and formula configuration.
Restore procedure now tries to decode JSON to dics and if that fails it assumes that backup is in old format and loads it as a plain file.
No difference.
- No documentation needed: only …
=> Add support for formulas configuration in spacecmd group backup

java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java, java/spacewalk-java.changes
The existing code chains CLM filters in a recursive way and this causes stack overflows when the stack limit is exceeded. This PR reimplements the logic in an iterative way to prevent such issues.
Port of: https://github.com/SUSE/spacewalk/pull/16786
=> Fix stack overflow when building a CLM project from modular sources (bsc#1194990)

java/code/src/com/redhat/rhn/domain/action/Action_legacyUser.hbm.xml, java/code/src/com/redhat/rhn/domain/errata/CveFactory.java, java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java, java/code/src/com/redhat/rhn/domain/server/MinionSummary.java, java/code/src/com/redhat/rhn/domain/server/ServerFactory.java, java/code/src/com/redhat/rhn/domain/server/Server_legacyUser.hbm.xml, java/code/src/com/redhat/rhn/domain/server/test/ServerFactoryTest.java, java/code/src/com/redhat/rhn/manager/content/ubuntu/Binary.java, java/code/src/com/redhat/rhn/manager/content/ubuntu/Entry.java, java/code/src/com/redhat/rhn/manager/content/ubuntu/PackageInfo.java, java/code/src/com/redhat/rhn/manager/content/ubuntu/Release.java, java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataInfo.java, java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java, java/code/src/com/redhat/rhn/manager/content/ubuntu/UrlData.java, java/code/src/com/redhat/rhn/manager/content/ubuntu/Urls.java, java/code/src/com/redhat/rhn/taskomatic/task/RepoSyncTask.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/spacewalk-java.changes, schema/spacewalk/common/data/rhnPackageArch.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.6-to-susemanager-schema-4.3.7/050-add-additional-packagearchs.sql
This adds basic ubuntu errata support by downloading errata information from https://usn.ubuntu.com/usn-db/database.json and matching it after the syncing of Ubuntu channels. It also adds support for installing errata on ubuntu systems by mapping them to package installs.
No difference.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/16807
Fixes https://github.com/SUSE/spacewalk/issues/11634 …
=> add ubuntu errata data and install handling

web/spacewalk-web.spec
Fix [licenses missing from the bundle](https://build.opensuse.org/package/live_build_log/systemsmanagement:Uyuni:Master/spacewalk-web/openSUSE_Leap_15.3/x86_64) after https://github.com/uyuni-project/uyuni/pull/4676.
No difference.
Followup to https://github.com/uyuni-project/uyuni/pull/4676
If you need to …
=> Add javascript licenses back into the bundle

susemanager-utils/testing/automation/push-to-obs.sh
Otherwise we can't pass multiple package like "a,b,c", as it used to be
possible.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/16913
=> Fix packages list parameter in push-to-obs

testsuite/features/step_definitions/navigation_steps.rb
This will prevent this issue, where our next step tries to look for a text but it has on top a modal dialog that took a bit more time than expected to be closed.
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Wait until the SCC delete user modal dialog is not shown

web/html/src/build/fill-spec-file.js, web/spacewalk-web.changes, web/spacewalk-web.spec
Followup to https://github.com/uyuni-project/uyuni/pull/4676, cleans up dangling references to `susemanager-web-libs`.
No difference.
Followup to https://github.com/uyuni-project/uyuni/pull/4676 …
=> Fix `susemanager-web-libs` references

java/code/src/com/redhat/rhn/frontend/strings/database/StringResource_en_US.xml, java/code/src/com/redhat/rhn/manager/user/test/UserManagerTest.java, schema/spacewalk/common/data/rhnTimezone.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/002-new-timezones.sql, schema/spacewalk/upgrade/susemanager-schema-4.3.7-to-susemanager-schema-4.3.8/002-fix-china-timezone.sql
Replace the not existing `Asia/Beijing` timezone with `Asia/Shanghai`
No difference.
- No tests: 
Tracks https://github.com/SUSE/spacewalk/issues/16743
=> Fix Chinese timezone display

java/spacewalk-java.changes
DownloadController log: add bugnumber to changelog
Fixes https://github.com/SUSE/spacewalk/issues/16906
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1195666
=> DownloadController log: add bugnumber  (bsc#1195666)

web/spacewalk-web.spec
Properly deprecates `susemanager-web-libs` in the specfile.
No difference.
Followup for https://github.com/uyuni-project/uyuni/pull/4807
=> Add provides and obsoletes for `susemanager-web-libs`

java/code/src/com/suse/manager/virtualization/HostInfo.java, java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualGuestsController.java, java/code/src/com/suse/manager/webui/controllers/virtualization/test/VirtualGuestsControllerTest.java, java/spacewalk-java.changes
VHM report no hostInfo, leading to the following error:
SyntaxError: Unexpected token ','
Now return to an empty dictionary when hostInfo is not available.
No difference.
- Issue: https://github.com/SUSE/spacewalk/issues/16929
- 4.2: https://github.com/SUSE/spacewalk/pull/16932 …
=> Fix the virtualization list for foreign systems

testsuite/features/core/srv_create_repository.feature
We are started to have this issue, not directly finding a package we are looking for.
It seems now we will need to wait a bit.
Warning: This issue shows a possible problem of degradation of our system, as before, this wait was not required.
No difference.
Ports:
- Manager-4.1
- Manager-4.2 …
=> QA: Wait until I see wrong encoded packages in the list

java/code/src/com/redhat/rhn/frontend/xmlrpc/configchannel/ConfigChannelHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/configchannel/test/ConfigChannelHandlerTest.java, java/code/src/com/redhat/rhn/testing/ConfigTestUtils.java, java/spacewalk-java.changes
In the ISS v2, after we synchronize the state of the database, we need to be able to recreate certain salt files on the disk under the `/srv/susemanager/salt` folder, so that they can be later deployed to target systems. For this reason, we create a new XML-RPC endpoint on the uyuni side, so that the ISS agent can call it and trigger the generation of the salt files upon import operation.
**How to test manually**
1. Create a normal config channel.
2. Create a new file in the channel.
3. Export config channels and re-import on your target system.
4. On the target system, call `spacecmd`, then in the prompt call `api configchannel.syncSaltFilesOnDisk -A '[["<you_chanel_label>"]]'`. Be careful with parents as well as the quotes, since we want to pass a list of arguments, where the first …
=> HUB-ISS: XML-RPC endpoint to restore config channel files on disk

spacewalk/certs-tools/mgr_ssl_cert_setup.py
Jabberd uses the user "jabber". Change the owner of the certificate file to jabber.
No difference.
=> change owner of jabberd certificate file

testsuite/features/step_definitions/retail_steps.rb, testsuite/features/support/twopence_init.rb
This is an alternative PR for https://github.com/uyuni-project/uyuni/pull/4835
In this PR we define a default value for PXEBOOT_IMAGE if it's not defined in the controller.
This variable is only defined in the controller if during the sumaform deployment we included a pxeboot_minion.
With that PR we allow to validate building image procedure, without the requirement of having a pxeboot_minion deployed.
No difference.
Ports:
- Manager-4.1
- Manager-4.2 …
=> QA: Refactor to don't require pxeboot_minion deployed to have a pxeboot_image defined

testsuite/features/secondary/proxy_cobbler_pxeboot.feature, testsuite/features/upload_files/example.ks
Various cobbler fixes:
* change the default values for kernel parameters when PXE booting a minion via cobbler. It's a work around for https://bugzilla.suse.com/show_bug.cgi?id=1195842 .
* avoid an error message about the encryption of root password when rendering the example cobbler profile
(this error message was never detected by test suite, btw)
Ports:
* 4.1: SUSE/spacewalk#16970 SUSE/spacewalk#16973
* 4.2: SUSE/spacewalk#16969
=> Cobbler fixes

testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
This PR restores a line that was removed by accident during a refactoring.
The "salt" CNAME alias for the proxy was missing.
Ports:
* 4.1: SUSE/spacewalk#16992
* 4.2: SUSE/spacewalk#16993
=> Restore salt CNAME alias

testsuite/features/step_definitions/common_steps.rb
Add logging to uptime test case for debugging edge case failure
No difference.
- [4.1](https://github.com/SUSE/spacewalk/pull/16998)
- [4.2](https://github.com/SUSE/spacewalk/pull/16999)
=> Add logging to uptime to debug edge case

testsuite/features/core/proxy_branch_network.feature, testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature, testsuite/features/step_definitions/retail_steps.rb
This PR:
* works around a problem with initial events on the branch server that has always been swept under the rug (and that would need real Salt debugging someday)
* does a "Hardware Refresh" on the proxy, so `proxy.example.org` is in SUSE Manager's database, and the pxeboot minion is seen behind the proxy
* avoids using a FQDN for the proxy (see technical details below)
* adds the proxy to the SERVERS group, so command-line tools like `retail_yaml` work
In Retail, don't do
```
salt         CNAME   <fqdn of proxy>
```
as this will be replaced by
```
salt         CNAME    my-proxy.tf.local
```
if you use avahi, and we removed avahi support.
Instead, just use:
```
salt         CNAME    proxy
```
Using the FQDN was needed because it's the one that was in the SSL certificate. But now we …
=> Various Retail fixes

testsuite/features/step_definitions/navigation_steps.rb, testsuite/features/step_definitions/retail_steps.rb, testsuite/features/step_definitions/salt_steps.rb
Clear a field before fill in with text.
Capybara `fill_in` method has a default behaviour which triggers native.clear, but for some UI frameworks this will not be enough. Adding the optional parameter `clear: :backspace` it will send backspaces to the field to clean it.
No difference.
Ports:
- Manager-4.1
- Manager-4.2 …
=> QA: Clear a field before fill in with text

java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml, java/code/src/com/redhat/rhn/manager/rhnpackage/test/PackageManagerRetractedTest.java, java/spacewalk-java.changes
This reverts commit 89daf8a80be7eccc6c7992cb2537d70609da5401.
Reverts commit: https://github.com/uyuni-project/uyuni/pull/4804
It causes problems in search feature for install package
No difference.
Before:
After:
- No tests: …
=> Revert "query elaborator when listing packages to install"

testsuite/features/secondary/proxy_cobbler_pxeboot.feature, testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature, testsuite/features/step_definitions/navigation_steps.rb, testsuite/features/step_definitions/salt_steps.rb
In order to fix these two features in Uyuni CI:
- Feature:PXE boot a terminal with Cobbler
- Feature:PXE boot a Retail terminal
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Wait until the proxy it's shown in the page

testsuite/features/secondary/min_migrate_to_trad.feature, testsuite/features/secondary/trad_deleted_migrate_to_minion.feature, testsuite/features/step_definitions/common_steps.rb, testsuite/run_sets/secondary.yml
This PR adds a new migration test. It migrates a beforehand deleted traditional client into a Salt minion. The exact steps are
- register trad. client as Minion
- unregister Minion
- register as trad. client again
- unregister trad. client
- register trad. client as Minion again
This test case does not test a valid scenario. In SUMA you normally do not delete a traditional client and then register it again as Salt minion. You would always just bootstrap the traditional client as a Salt minion again and Salt would recognize that it is a traditional client and will take the the necessary steps to migrate it.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/6781
[Manager …
=> QA: Add test for migrating a deleted client into a Salt minion

testsuite/features/secondary/trad_centos_migrate_to_min.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/run_sets/secondary.yml
This will add a test for migrating a CentOS 7 traditional client to a Salt minion.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/6782
[Manager 4.2](https://github.com/SUSE/spacewalk/pull/17031)
[Manager 4.1](https://github.com/SUSE/spacewalk/pull/17032) …
=> QA: Add CentOS 7 migration test

testsuite/features/reposync/srv_sync_products.feature, testsuite/features/step_definitions/common_steps.rb
Client Tools in the Product Wizard does not exist in Uyuni.
We need to ignore this similar to the deselect call.
No difference.
Tracks
=> Client Tools in the Product Wizard exists not on Uyuni

testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/support/constants.rb
Head will contain for now BV 4.3 tests, until we have Manager-4.3 branch in Spacewalk
No difference.
**DON'T PORT IT.**
https://github.com/SUSE/spacewalk/issues/16526
=> QA: Head will contain for now BV 4.3 tests, until we have Manager-4.3 branch in Spacewalk

testsuite/features/build_validation/add_custom_repositories/srv_common_channels.feature, testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/support/constants.rb
Use the channel for openSUSE available at SCC instead of using `spacewalk-common-channel` like for Debian and old Ubuntus.
According to the doc https://documentation.suse.com/suma/4.2/en/suse-manager/client-configuration/clients-opensuseleap.html it's the correct way to proceed.
Ports:
* 4.1: SUSE/spacewalk#17070
* 4.2: SUSE/spacewalk#17071
=> Use SCC for openSUSE instead of common channels

testsuite/features/secondary/trad_centos_client.feature, testsuite/features/secondary/trad_centos_migrate_to_min.feature
Fixup of https://github.com/uyuni-project/uyuni/pull/4833
According to the failing [Uyuni tests](https://ci.suse.de/job/uyuni-master-dev-acceptance-tests-NUE/2704/testReport/(root)/Migrate%20a%20CentOS%207%20traditional%20client%20into%20a%20Salt%20minion/Prepare_the_CentOS_7_traditional_client_in_the_migration_context/), we have to delete the minion first to be able to register it as trad. client.
Furthermore I added the repository refresh to our CentOS 7 traditional client test to prevent it failing like it did with the migration tests of CentOS 7 in the past.
No difference.
- Documentation issue was created: [Link for SUSE Manager …
=> QA: fixups for CentOS 7 tests

testsuite/features/secondary/trad_deleted_migrate_to_minion.feature
Fixup of https://github.com/uyuni-project/uyuni/pull/4815
At the beginning of the test the Salt minion will get registered. At the end the minion will get deleted again. Hopefully this make the test idempotent again.
No difference.
- Cucumber tests were …
=> QA: fixup migration from trad client to minion

testsuite/features/secondary/min_centos_monitoring.feature, testsuite/features/secondary/min_monitoring.feature
Wait until Prometheus services are active, as currently it seems we need a bit more time until it's fully usable, once the apply states event has finished.
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/17101
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/17102 …
=> QA: Wait until Prometheus services are active

testsuite/features/support/env.rb
Raise exception again in AfterStep, instead of failing the scenario
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Raise exception again in AfterStep, instead of failing the scenario

testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature
When having extra Beta channels, the number of channels to build is different, so the text in the button is.
Let's make this more generic, just looking for the text "Build" in a button.
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/17118
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/17119 …
=> QA: BV click on Build button on CLM without check number of channels

spacewalk/certs-tools/mgr_ssl_cert_setup.py, spacewalk/certs-tools/spacewalk-certs-tools.changes
Convert the `mgr-ssl-cert-setup` tool to not store temporary files. Also add a function to be called by the salt runner to check SSL certificates for the proxy containers case.
No difference.
- No tests: Requires the python refactoring PR to be merged first
Fixes # …
=> SSL check refactoring

susemanager-utils/susemanager-sls/src/grains/cpuinfo.py, susemanager-utils/susemanager-sls/src/tests/data/lscpu-json.aarch64.sample, susemanager-utils/susemanager-sls/src/tests/data/lscpu-json.ppc64.out, susemanager-utils/susemanager-sls/src/tests/data/lscpu-json.ppc64.sample, susemanager-utils/susemanager-sls/src/tests/data/lscpu-json.s390.sample, susemanager-utils/susemanager-sls/src/tests/data/lscpu-json.x86_64.sample, susemanager-utils/susemanager-sls/susemanager-sls.changes
Some systems are old enough to not have the -J lscpu parameter. Instead
parse the regular output with C locale.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17035
4.2: https://github.com/SUSE/spacewalk/pull/17043 …
=> Don't use lscpu -J in grains

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml, java/code/src/com/redhat/rhn/frontend/taglibs/IconTag.java, java/code/src/com/suse/manager/webui/controllers/CVEAuditController.java, java/spacewalk-java.changes, web/html/src/components/icontag.tsx, web/html/src/manager/audit/cveaudit/cveaudit.tsx, web/spacewalk-web.changes
Provide link for CVEs 
Before:
After:
The links are shown only after a research
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/16651
=> Provide link for CVEs

spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb-user, spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes
- do not allow to change SUMA DB admin user
- do not allow to change ReportDB DB admin user
- remind that postgres in case-insensitive
No difference.
N/A
N/A
Fixes https://github.com/SUSE/spacewalk/issues/16989
=> ReportDB User: prevent to modify the main users

java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java, java/spacewalk-java.changes
fixes a npe when packages are null and prevents ubuntu erratas from being written to the database.
No difference.
- No tests
=> handle npe when packages are null

testsuite/features/step_definitions/command_steps.rb
@bischoff, @srbarrios and I discussed that this makes no sense at the moment since we found a machine in our network with the same IP address that will couse one of our core tests to fail. So the step is commented out for now.
No difference.
Manager 4.2 https://github.com/SUSE/spacewalk/pull/17126
Manager 4.1 https://github.com/SUSE/spacewalk/pull/17127 …
=> QA: Comment out ping command in core stage

backend/satellite_tools/spacewalk-debug, backend/spacewalk-backend.changes
Additional information reported by the `spacewalk-debug` plugin: task schedules `defaults` and `modified`.
No difference.
- No documentation needed: it's about supportconfig grasping values
- No tests: it's about supportconfig
Inspired by bsc#1187789
Fixes # …
=> Supportconfig spacewalk-debug: report task schedule values

java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java, susemanager-utils/testing/docker/scripts/init-pgsql-db4eclipse.sh
Eclipse needs this syntax to compile the code.
No difference.
=> Fix syntax for eclipse compiler

java/code/src/com/redhat/rhn/taskomatic/task/repomd/DebRepositoryWriter.java, java/code/src/com/redhat/rhn/taskomatic/task/repomd/RepositoryWriter.java, java/code/src/com/redhat/rhn/taskomatic/task/repomd/RpmRepositoryWriter.java, java/code/src/com/redhat/rhn/taskomatic/task/repomd/test/RpmRepositoryWriterTest.java, java/spacewalk-java.changes
This is the fix for a regression introduced with https://github.com/SUSE/spacewalk/pull/15664.
For channels with signed metadata, the fix adds the `repomd.xml.asc` and `repomd.xml.key` files to the list of created files so they won't be removed during metadata generation cleanup.
https://bugzilla.suse.com/show_bug.cgi?id=1192822
Port of: https://github.com/SUSE/spacewalk/pull/16439
If you need to …
=> Fix disappearing metadata key files after channel change (bsc#1192822)

web/html/src/utils/data-providers/paged-data-endpoint.test.ts, web/html/src/utils/functions.test.ts
A couple of async JS tests fail on some node versions. This PR disables those tests until we have a fix for them.
See: https://github.com/SUSE/spacewalk/issues/16912
=> Comment out faulty JS tests until fixed

testsuite/features/build_validation/init_clients/proxy.feature, testsuite/features/core/proxy_branch_network.feature, testsuite/features/secondary/min_centos_monitoring.feature, testsuite/features/secondary/min_monitoring.feature, testsuite/features/secondary/min_salt_formulas.feature, testsuite/features/secondary/min_salt_formulas_advanced.feature, testsuite/features/secondary/minkvm_guests.feature, testsuite/features/secondary/minxen_guests.feature, testsuite/features/secondary/proxy_cobbler_pxeboot.feature, testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature, web/html/src/components/FormulaForm.tsx, web/html/src/components/formulas/EditGroup.tsx, web/html/src/components/formulas/FormulaComponentGenerator.tsx, web/html/src/components/formulas/Group.tsx, web/html/src/components/formulas/SectionToggle.tsx, web/spacewalk-web.changes
This is a reopen of https://github.com/uyuni-project/uyuni/pull/4278 which has accidentally been merged and needed to be reverted due to breaking the testsuite
Add buttons to expand/collapse all formula sections.
And provide a search box in the Formulas context. **Note:** the search box is capable to filter in/out by the section name whether the section is a `group` or an `edit group` type **only**.
**Previous PR has already been reviewed**
See: https://github.com/parlt91/uyuni/pull/2
Tracks https://github.com/SUSE/spacewalk/issues/13404 …
=> Formulas show hide all sections and searchbox

.github/CODEOWNERS
Specify the `@uyuni-project/release-engineering` group correctly.
No difference.
- No documentation needed: only addresses the Git repository
- No tests: No code change
=> CODEOWNERS: Fix release-engineering syntax

proxy/installer/spacewalk-proxy-installer.changes, proxy/installer/spacewalk-proxy-installer.spec, proxy/proxy/spacewalk-proxy.changes, proxy/proxy/spacewalk-proxy.spec, spacewalk/setup/spacewalk-setup.changes, spacewalk/setup/spacewalk-setup.spec, utils/spacewalk-utils.changes, utils/spacewalk-utils.spec
remove pylint checks.
Fedora Packaging Guidelines advice against using pylint as it is opinion based (https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_running_tests)
Tests should be run within CI.
No difference. …
=> Remove pylint checks

susemanager-utils/susemanager-sls/src/tests/mockery.py, susemanager-utils/susemanager-sls/src/tests/test_beacon_pkgset.py, susemanager-utils/susemanager-sls/src/tests/test_grains_cpuinfo.py, susemanager-utils/susemanager-sls/src/tests/test_grains_virt.py, susemanager-utils/susemanager-sls/src/tests/test_mgr_master_tops.py, susemanager-utils/susemanager-sls/src/tests/test_module_mainframesysinfo.py, susemanager-utils/susemanager-sls/src/tests/test_module_sumautil.py, susemanager-utils/susemanager-sls/src/tests/test_module_udevdb.py, susemanager-utils/susemanager-sls/src/tests/test_module_uyuni_config.py, susemanager-utils/susemanager-sls/src/tests/test_module_virt_utils.py, susemanager-utils/susemanager-sls/src/tests/test_state_mgrcompat.py, susemanager-utils/susemanager-sls/src/tests/test_state_mgrutils.py, susemanager-utils/susemanager-sls/src/tests/test_state_product.py, susemanager-utils/susemanager-sls/src/tests/test_state_uyuni_config.py, susemanager-utils/susemanager-sls/src/tests/test_state_virt_utils.py, susemanager-utils/susemanager-sls/susemanager-sls.spec, susemanager-utils/susemanager-sls/test/test_engine.py, susemanager-utils/susemanager-sls/test/test_pillar_suma_minion.py
Replace python-mock with built-in unittest.mock
No difference.
=> Replace mock

spacewalk/certs-tools/rhn_bootstrap_strings.py, spacewalk/certs-tools/spacewalk-certs-tools.changes
Do not generate Salt Bundle sections to the bootstrap script for traditional clients
No difference.
- Do not generate Salt Bundle sections in bootstrap for traditional
=> Do not generate Salt Bundle sections to traditional bootstrap script

testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
This will increase our timeout for applying the saltboot sync for the PXE boot minion. Hopefully this will fix some of our timeout issues.
No difference.
Issue https://github.com/SUSE/spacewalk/issues/17009
[Manager 4.2](https://github.com/SUSE/spacewalk/pull/17164)
[Manager 4.1](https://github.com/SUSE/spacewalk/pull/17165) …
=> QA: Increase timeout for PXE boot minion

java/code/src/com/redhat/rhn/common/hibernate/AbstractConnectionManager.java, java/code/src/com/redhat/rhn/common/hibernate/HibernateFactory.java, java/code/src/com/redhat/rhn/common/hibernate/ReportDbHibernateFactory.java
This PR removes the throws that are done within a `finally` block.
No difference.
=> Avoid throwing exceptions within a finally block

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
add SLES15SP4 and SUMA Proxy 4.3 to  bootstrap repo definitions
Fixes: https://github.com/SUSE/spacewalk/issues/17173
- [] No changelog needed
=> Add SLES15SP4 and SUMA Proxy 4.3 to bootstrap repo definitions

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
This reverts commit d920c15743bd64af631d1d3ad76288f017ae63f6.
Wrong branch
=> Revert "Add SLES15SP4 and SUMA Proxy 4.3 to bootstrap repo definitions (#4939)

susemanager-sync-data/additional_products.json, susemanager-sync-data/channel_families.json, susemanager-sync-data/susemanager-sync-data.changes
Changes centos 8 eol urls to vault which still work.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/16869
=> change centos 8 urls to vault

testsuite/features/secondary/min_salt_install_with_staging.feature, testsuite/features/secondary/min_ubuntu_salt_install_with_staging.feature
The `Install package in the future and check for staging` scenario is failing. 
According to the comments of the colleagues: 
> The package is not anymore cached. It's happening in all our latest testsuite runs on Uyuni/Head CI.
After further investigations:
> It seems our parameters are set up a bit in a way that makes this test bit flaky. 
>
> java.salt_content_staging_window = 0.033 (~1.98 minutes)
> java.salt_content_staging_advance = 0.05 (3 minutes)
> 
> Now in our test, we schedule it 2 minutes in the future https://github.com/SUSE/spacewalk/blob/f1ba1f514b700c74a5cd34524d1615ab84b8bd9e/testsuite/features/secondary/min_salt_install_with_staging.feature#L53
> 
> So IIUC,  I see that the staging window started even before the current time, I didn't look into the code thoroughly but …
=> TESTSUITE Failing Scenario: Install package in the future and check for staging

java/code/src/com/suse/manager/webui/controllers/utils/SSHMinionBootstrapper.java, java/code/src/com/suse/manager/webui/controllers/utils/test/AbstractMinionBootstrapperTestBase.java, java/spacewalk-java.changes, spacecmd/spacecmd.changes, spacecmd/src/spacecmd/api.py, spacecmd/src/spacecmd/system.py, spacecmd/tests/test_system.py, susemanager-utils/susemanager-sls/modules/runners/mgrutil.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
Implement `system_bootstrap` in spacecmd
Port of https://github.com/SUSE/spacewalk/pull/16800
No difference.
- modules/reference/pages/spacecmd/system.adoc needs refreshing
https://github.com/SUSE/spacewalk/issues/16801
Fixes https://github.com/uyuni-project/uyuni/issues/4737 …
=> Spacecmd bootstrap

schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.2.9-to-susemanager-schema-4.2.10/010-errata-status.sql
Latest 4.1 schema already support "pending".
When a patch with status pending is synced and a migration from 4.1 to 4.2 happens, a check constraint violation happens.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/16943 …
=> fix advisory status migration

java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
Check if the server architecture could be found.
Throw an exception and log an error if it could not be found.
Cleanup the code and remove duplicate setting of the architecture
No difference. …
=> cleanup server architecture detection and improve error handling

java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java, java/code/src/com/redhat/rhn/domain/scc/SCCCachingFactory.java, java/code/src/com/redhat/rhn/taskomatic/task/ForwardRegistrationTask.java, java/code/src/com/suse/scc/SCCSystemRegistrationManager.java, java/code/src/com/suse/scc/client/SCCClient.java, java/code/src/com/suse/scc/client/SCCFileClient.java, java/code/src/com/suse/scc/client/SCCWebClient.java, java/code/src/com/suse/scc/model/SCCRegisterSystemJson.java, java/code/src/com/suse/scc/model/SCCUpdateSystemJson.java, java/code/src/com/suse/scc/test/SCCSystemRegistrationManagerTest.java, java/spacewalk-java.changes, susemanager/rhn-conf/rhn_server_susemanager.conf, susemanager/susemanager.changes
Send checkin time as "last_seen_at" to SCC.
Update all systems in SCC with this value in the first run after midnight.
No difference.
See https://github.com/SUSE/spacewalk/issues/16312
Tracks
=> Scc forward last seen

backend/tito.props, java/conf/rhn_java.conf, java/tito.props
- change java api version to 26
- adapt required SQL schema versions
No difference.
- No tests: **internals**
=> Adapt required versions

susemanager-utils/susemanager-sls/salt/channels/init.sls
Fix state dependency for product installed.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/17186
=> fix require indenting for product installed state

susemanager/bin/mgr-setup, susemanager/susemanager.changes
Adapt report-db-ca-cert to contain Enterprise Linux folder if the SUSE folder does not exist.
No difference.
manually tested positive path on Alma OK
=> Set RHEL cert folder for reportdb if default folder does not exist

spacewalk/admin/spacewalk-startup-helper, spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb-user, spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes
While parsing rhn.conf, all whitespaces in values got stripped.
This PR strip only leading and trailing whitespaces and keep spaces inside of the value.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/4925 …
=> Fix bash config parser

susemanager-utils/susemanager-sls/salt/channels/init.sls
After fixing require syncstates, the state itself is missing. We need to include the state file as well.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/17189
=> include util.syncstates

java/buildconf/build-props.xml, java/spacewalk-java.changes, java/spacewalk-java.spec
Build with new postgresql-jdbc driver depending on the availability of ongres-stringprep .
This should work with the old and the new driver.
No difference. …
=> New postgres jdbc driver

java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java, java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/spacewalk-java.changes
When matching MAC addresses during empty profiles lookup we should ignore MAC address case.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17130
Tracks https://github.com/SUSE/spacewalk/pull/17177 …
=> Finding empty profiles by mac address must be case insentitive

backend/satellite_tools/reposync.py, backend/spacewalk-backend.changes
Checking Client Certificates in reposync exist, but was disabled when using spacewalk-repo-sync.
This change enable the check by default and improved it by checking all certificates configured.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/11861
Tracks https://github.com/SUSE/spacewalk/pull/17112 …
=> Reposync client cert check

backend/satellite_tools/download.py, backend/satellite_tools/test/unit/test_download.py, backend/spacewalk-backend.changes
After upgrade of urlgrabber to >= 4, proxy variable wasn't set correctly due to missing type conversion.
Conversion from `byte` to `string` as well as unittest added. For further details, see related issue.
No difference.
Fixes #4932 …
=> Reposync: fix to ensure configured http proxy is used

java/code/src/com/suse/manager/utils/SaltUtils.java, java/spacewalk-java.changes
fixes class cast exception when hibernate object is proxy.
No difference.
- No tests
=> unproxy action before casting (bsc#1195772)

testsuite/features/step_definitions/command_steps.rb
Adds a new validation to the sanity check stage of the CI to ensure the hostname and reverse name resolution don't take more than 2 seconds - else, fails the stage as there's something wrong with the network that will fail other important features.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17203
- [4.1](https://github.com/SUSE/spacewalk/pull/17220)
- [4.2](https://github.com/SUSE/spacewalk/pull/17221)
=> QA: Add hostname and reverse lookup time sanity check

java/spacewalk-java.spec
Enterprise Linux stops building when the postgres file list is empty. This change guarantees that it always contains files.
No difference.
=> spacewalk-java: Avoid empty file list

spacewalk/setup/lib/Spacewalk/Setup.pm, spacewalk/setup/spacewalk-setup.changes
When spacewalk-setup is called with --clear-db, we should drop also the reporting database to not prevent a re-installation.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/4867
Fixes https://github.com/SUSE/spacewalk/issues/17182 …
=> Hub reporting fix reinstall

susemanager-utils/susemanager-sls/modules/roster/uyuni.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
Fixes the possible traceback:
```
...
File "/usr/share/susemanager/modules/roster/uyuni.py", line 302, in targets
ssh_push_port=int(prow.ssh_push_port),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
No difference.
- No tests: No unit tests for the module yet (TBD)
Fixes https://github.com/uyuni-project/uyuni/issues/4927
- Fix possible traceback in uyuni roster if no ssh port in the DB
If …
=> Fix possible traceback in uyuni if no ssh push port in the DB

java/build.xml, java/manager-build.xml
Remove useless ugly logging errors when building apidocs
No difference.
- No tests: tooling
Fixes #
=> Don't use log4j.properties in apidocs generation

spacewalk/setup/lib/Spacewalk/Setup.pm, susemanager/bin/mgr-setup
Fix dropping the reporting DB on resetup
=> fixup! drop the reporting DB when clear-db option is set

client/rhel/mgr-daemon/mgr-daemon.spec
Macro package not available on RHEL 7.
=> systemd-rpm-macros only available of rhel8 or later

susemanager-utils/testing/docker/scripts/push-to-obs.sh
Modify push-to-obs.sh to push containers
No difference.
- No documentation needed: Modify push-to-obs.sh to push containers
- No tests: This is required for tests
Nothing
=> Modify push-to-obs.sh to push containers

rel-eng/build-containers-for-obs.sh, susemanager-utils/testing/automation/push-to-obs.sh, susemanager-utils/testing/docker/scripts/push-to-obs.sh
The docker-based automation script loops over all packages in rel-eng.
In order to push container images it needs to loops on them as well.
No difference.
- No tests: automation tools fix
Fixes # …
=> Fix push-to-obs to push container images

spacewalk/certs-tools/mgr_ssl_cert_setup.py, spacewalk/certs-tools/spacewalk-certs-tools.changes
The timestamp in the certificates are UTC. Compare them with UTC time and not localtime.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/4990
=> Fix certificate date check

testsuite/features/support/env.rb
Fixes AfterStep when a scenario fails to not raise the exception but only print in stdout. That should clear some red tests. Before when a test failed the AfterStep hook also failed making all the scenarios in the feature red. Now we will be able to see exactly the real failing scenarios.
No difference.
Fixes no issue, directly from testsuite review.
Tracks:
4.2: https://github.com/SUSE/spacewalk/pull/17279
4.1: https://github.com/SUSE/spacewalk/pull/17280
If you don't …
=> Remove exception and leave stdout only

testsuite/features/step_definitions/navigation_steps.rb
Try/Catch page.reset when browser has not opened windows
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Try/Catch page.reset when browser has not opened windows

java/code/src/com/redhat/rhn/domain/image/ImageInfoFactory.java, java/spacewalk-java.changes
This fixes a null pointer exception when a store is deleted before image.
The problem appears in cucumber test "Build image with authenticated registry. Cleanup: delete registry image."
An alternative fix would be to disallow images without store, but that would require deleting of such images on migration. So this fix is less intrusive.
No difference.
- covered by cucumber tests
Fixes https://github.com/SUSE/spacewalk/issues/17288 …
=> Fix exception when image store is deleted before image

containers/proxy-ssh-image/Dockerfile, containers/proxy-ssh-image/proxy-ssh-image.changes, containers/proxy-systemd-services/uyuni-proxy-pod.service, containers/proxy-systemd-services/uyuni-proxy-systemd-services.spec, java/code/src/com/redhat/rhn/domain/server/ProxyInfo.hbm.xml, java/code/src/com/redhat/rhn/domain/server/ProxyInfo.java, java/code/src/com/redhat/rhn/domain/server/ServerFactory.java, java/code/src/com/redhat/rhn/domain/server/ServerPath.java, java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/code/src/com/redhat/rhn/frontend/xmlrpc/proxy/ProxyHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/proxy/test/ProxyHandlerTest.java, java/code/src/com/redhat/rhn/manager/system/SystemManager.java, java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java, java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java, java/code/src/com/suse/manager/webui/services/impl/test/SaltSSHServiceTest.java, java/code/webapp/WEB-INF/pages/systems/sdc/overview.jsp, java/spacewalk-java.changes, schema/spacewalk/common/tables/rhnProxyInfo.sql, schema/spacewalk/postgres/triggers/rhnProxyInfo.sql, schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.3.9-to-susemanager-schema-4.3.10/001-rhnProxyInfo-port.sql, spacecmd/spacecmd.changes, spacecmd/src/spacecmd/proxy.py, spacewalk/certs-tools/spacewalk-certs-tools.changes, spacewalk/certs-tools/sslToolConfig.py, susemanager-utils/susemanager-sls/modules/roster/uyuni.py, susemanager-utils/susemanager-sls/modules/runners/mgrutil.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
Allow setting the SSH port of the containerized proxies when creating the configuration for it. This will help making the systemd installation simpler since the host sshd port won't have to be changed. 
Add SSH Port field in proxy system details
After:
- Documentation for the whole feature will be needed later on, skipped for now
Fixes  https://github.com/SUSE/spacewalk/issues/17303 …
=> Configurable SSH port for containerized proxies

testsuite/features/secondary/min_timezone.feature, testsuite/features/secondary/srv_timezone.feature, testsuite/run_sets/secondary.yml
This PR adds a feature that tests different timezone functions. Here is the related ticket https://github.com/SUSE/spacewalk/issues/15864 with a lot of information on the bugs found during manual testing before writing the automation for this test.
No difference.
Fixes #
Fixes https://github.com/SUSE/spacewalk/issues/15864  …
=> Add new feature testing the timezone

susemanager-utils/testing/docker/scripts/Makefile
Let the user specify the head container via a environment variable
No difference.
- No tests
Fixes #
=> Use head container for cobbler testing

web/html/src/components/panels/InnerPanel.tsx, web/html/src/manager/maintenance/list/maintenance-windows-list.tsx, web/html/src/manager/state/recurring-states-list.tsx
Add help icon and info text to recurring action and maintenance window pages
No difference.
Before:
After:
Tracks https://github.com/SUSE/spacewalk/issues/17151
=> Improve schedule info

java/code/src/com/redhat/rhn/frontend/xmlrpc/proxy/test/ProxyHandlerTest.java
The used assert function is treated in eclipse as "not public" and produce compile errors.
Use a public API method
No difference.
=> use public API

sonar-project.properties
Fixes the following scanner error:
```
ERROR: Error during SonarScanner execution
ERROR: File python/rhn/rhnLockfile.py can't be indexed twice. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files
```
No difference.
Fixes #
If …
=> Fix sonarqube double indexing of python files

java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemHistoryEventAction.java, java/spacewalk-java.changes
Fix a NPE that occurs when navigating to the details of an action that is no longer present in the system history (e.g. because it got cancelled).
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/16959
=> Fix NPE when accessing cancelled action via system history

testsuite/Gemfile
Lock Capybara and Cucumber gem version, to prevent this issue:
No difference.
- No tests
Ports:
- Manager-4.1
- Manager-4.2
=> QA: Lock Capybara and Cucumber gem version

java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java, java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java, java/spacewalk-java.changes
Add new and changed ubuntu errata to the notification queue to send email when new errata arrive.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/17316
=> Send ubuntu errata notifications

schema/spacewalk/susemanager-schema.changes, schema/spacewalk/upgrade/susemanager-schema-4.2.2-to-susemanager-schema-4.2.3/001-rhnActionDup-add-alllow-vendor-change.sql, schema/spacewalk/upgrade/susemanager-schema-4.3.9-to-susemanager-schema-4.3.10/010-alllow-vendor-change-constrains.sql
fix check on allowVendorChange after schema update was called multiple times.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/17347
=> Fix schema idempotent issue

testsuite/features/secondary/srv_handle_config_channels_with_ISS_v2.feature, testsuite/features/secondary/srv_handle_software_channels_with_ISS_v2.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/run_sets/secondary.yml
Refactored PR of: https://github.com/uyuni-project/uyuni/pull/4716
implementation of: https://github.com/SUSE/spacewalk/issues/16757
No difference.
Before:
After:
- Cucumber …
=> uyuni iss test export config

java/code/src/com/redhat/rhn/manager/system/SystemManager.java, java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
The TFTP container will require the `proxy_fqdn` in the configuration file. Since we already ask it to the user, write it down as well.
No difference.
Fixes # …
=> Add proxy_fqdn to proxy config for TFTP container

testsuite/features/step_definitions/retail_steps.rb
OS Image name is now taken from Kiwi sources.
=> Testsuite: Fix os image name

java/code/src/com/redhat/rhn/frontend/xmlrpc/BaseHandler.java, java/spacewalk-java.changes
Prevent inherited and private methods in handlers to be exposed with the XMLRPC API.
=> Hide private methods in XMLRPC handlers

testsuite/features/step_definitions/command_steps.rb
In the Build Validation test suite, the controller is in the USA and the ARM minion is in Orthos network in Nuremberg. They are connected through a tunnel.
This adds a significant time to the reverse DNS resolution test, which should not be taken into account in the sanity checks.
=> When measuring time taken, do not count ssh

testsuite/.rubocop.yml
This disables the Metrics/ClassLength cop in RuboCop.
No difference.
- No tests: 
Manager 4.2: https://github.com/SUSE/spacewalk/pull/17377
Manager 4.1: https://github.com/SUSE/spacewalk/pull/17376
=> QE: RuboCop: Disable Metrics/ClassLength

susemanager-utils/susemanager-sls/salt/bootstrap/set_proxy.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
This fixes set_proxy.sls to use correct config file and service name on minions with salt bundle.
No difference.
TBD
Fixes #
=> Handle salt bundle in set_proxy.sls

susemanager/bin/pg-migrate-13-to-14.sh, susemanager/susemanager.changes
Add pg  migration script from version 13 to 14.
This script is a wrapper to pg-migrate-x-to-y.sh but it is convenient.
No difference.
- No tests
Partial fix for https://github.com/SUSE/spacewalk/issues/16348
=> Add pg migration script from version 13 to 14

java/code/src/com/suse/manager/webui/services/impl/SaltService.java, java/code/src/com/suse/manager/webui/utils/salt/custom/HwProfileUpdateSlsResult.java, java/spacewalk-java.changes
- Due to some issue on salt-api, the result of the action `hardware refresh` is not a serializable by `HwProfileUpdateSlsResult`: in this case the action remain stuck. Although the issue is in salt-api, we should log a warning to show when this raise condition happens. 
- Not sure if it's related to the HW refresh issue, but we noticed that the bootstrapping of a salt-ssh minion generates some async calls ( `addEntitlementToServer -> updatePillarAfterGroupUpdateForServers -> refreshPillar` ). Change the call made by refreshPillar sync
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17290 …
=> HW refresh stuck

containers/proxy-httpd-image/Dockerfile, containers/proxy-httpd-image/proxy-httpd-image.changes, containers/proxy-httpd-image/uyuni-configure.py, containers/proxy-systemd-services/uyuni-container-proxy-tftpd.service, containers/proxy-systemd-services/uyuni-proxy-pod.service, containers/proxy-tftpd-image/Dockerfile, containers/proxy-tftpd-image/proxy-tftpd-image.changes, containers/proxy-tftpd-image/uyuni-configure.py, containers/run-proxy.sh
This configures http and tftp container to be usable with cobber sync and then PXE autoinstallaion
No difference.
Fixes …
=> Configure tftp container

testsuite/features/support/constants.rb
Build Validation: fix adding of custom repositories for openSUSE 15.3 aarch64.
Ports:
* 4.1: SUSE/spacewalk#17387
* 4.2: SUSE/spacewalk#17386
=> Correct base channel for openSUSE 15.3 ARM

testsuite/Gemfile, testsuite/config/cucumber.yml, testsuite/features/secondary/srv_reportdb.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/common_steps.rb, testsuite/features/step_definitions/navigation_steps.rb, testsuite/features/support/commonlib.rb, testsuite/features/upload_files/create_user_reportdb.exp, testsuite/features/upload_files/delete_user_reportdb.exp, testsuite/run_sets/secondary_parallelizable.yml
Adds tests for ReportDB Feature.
Tests:
- Taskomatic job populating ReportDB
- Being able to connect to ReportDB from the server
- Being able to create (and delete) a read-only user for ReportDB
- Being able to connect to ReportDB with read-only user from external machine (controller)
- Ensuring read-only user can't add, modify or delete table from ReportDB
- Validating systems table lists the same systems as the UI Systems Overview
- Ensuring admin user can't connect to product database from external machine (controller)
- Making sure a system's property is changed in the ReportDB when changed in the UI and the `synced_date` is updated after the Taskomatic job
No difference.
Fixes …
=> QE: Add tests for ReportDB

testsuite/features/build_validation/smoke_tests/smoke_tests.template
Fix popup message on deploy conf files for BV 4.3
No difference.
Fixes no issue, directly from BV review
Tracks This is for master only, not for 4.2 because in 4.2 we still have the same old message. …
=> Fix popup message on deploy conf files for BV 4.3

java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/ContentManagementViewsController.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ControllerApiUtils.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java, java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/ProjectSoftwareSourceResponse.java, java/spacewalk-java.changes, web/html/src/manager/content-management/shared/components/panels/sources/sources.tsx, web/html/src/manager/content-management/shared/type/project.type.ts, web/spacewalk-web.changes
The message "unsynced patches" raise questions. Make it a link to a page which has details on what has changed.
No difference.
Before:
After:
- 
Port of https://github.com/SUSE/spacewalk/pull/17217
=> Improve clm info message

java/code/src/com/suse/manager/webui/services/impl/SaltService.java, java/spacewalk-java.changes
Check the owner and permssions before we try to change it.
If we have already correct settings, we can skip it and prevent warnings if we do not have the permissions to change it as we run as user tomcat.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/17305 https://github.com/SUSE/spacewalk/pull/17306 …
=> Change permissions only when needed

rel-eng/push-packages-to-obs.sh
Handling these values with OBS BuildFlag: dockerarg leads to issues due
to the whitespaces, doing the sed work at push time on the Dockerfile
rather than on ther _services is easier.
=> Modify the Dockerfile to set SUSE Manager label variables

java/buildconf/test/rhn.conf.postgresql-example, java/conf/default/rhn_hibernate.conf, java/conf/default/rhn_reporting_hibernate.conf, java/spacewalk-java.changes
ssh push action remain stuck and this error appears in `rhn_taskomatic_daemon.log`
```
022-03-29 14:12:23,291 [DefaultQuartzScheduler_Worker-18] ERROR com.redhat.rhn.taskomatic.task.SSHMinionActionExecutor  - Executing a task threw an exception: java.lang.IllegalStateException
2022-03-29 14:12:23,291 [DefaultQuartzScheduler_Worker-18] ERROR com.redhat.rhn.taskomatic.task.SSHMinionActionExecutor  - Message: The default-query-results-region Cache is not alive (STATUS_SHUTDOWN)
2022-03-29 14:12:23,291 [DefaultQuartzScheduler_Worker-18] ERROR com.redhat.rhn.taskomatic.task.SSHMinionActionExecutor  - Cause: null
2022-03-29 14:12:23,292 [DefaultQuartzScheduler_Worker-18] ERROR com.redhat.rhn.taskomatic.task.SSHMinionActionExecutor  - Stack trace:java.lang.IllegalStateException: The …
```
=> hibernate: set a non-singleton ehcache

client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes, client/rhel/spacewalk-client-tools/spacewalk-client-tools.spec, client/tools/mgr-cfg/mgr-cfg.changes, client/tools/mgr-cfg/mgr-cfg.spec, client/tools/mgr-osad/mgr-osad.changes, client/tools/mgr-osad/mgr-osad.spec, client/tools/mgr-push/mgr-push.changes, client/tools/mgr-push/mgr-push.spec, client/tools/mgr-virtualization/mgr-virtualization.changes, client/tools/mgr-virtualization/mgr-virtualization.spec, client/tools/spacewalk-koan/spacewalk-koan.changes, client/tools/spacewalk-koan/spacewalk-koan.spec, client/tools/spacewalk-oscap/spacewalk-oscap.changes, client/tools/spacewalk-oscap/spacewalk-oscap.spec, python/rhn/rhnlib.changes, python/rhn/rhnlib.spec, suseRegisterInfo/suseRegisterInfo.changes, suseRegisterInfo/suseRegisterInfo.spec
Prevent building python2 subpackages for SLE15
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17379
=> Prevent building python2 subpackages for SLE15

containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes, containers/proxy-systemd-services/uyuni-proxy-systemd-services.spec
Adapted to build on Enterprise Linux
No difference.
=> proxy-systemd-services: Adapted to build on Enterprise Linux

susemanager-utils/susemanager-sls/salt-ssh/preflight.sh, susemanager-utils/susemanager-sls/susemanager-sls.changes
Some of Debian based distros has no `ar` from `binutils` installed by-default.
This change is modifies the pre flight script to extract `deb` packages with `dpkg-deb -x ...` instead of using `ar`
No difference.
- No tests: Testing with bootstrap repo creation (used to get the package from) is not implemented in any test system
If you …
=> Use dpkg-deb to extract deb files instead of ar

spacewalk/certs-tools/rhn_bootstrap_strings.py, spacewalk/certs-tools/spacewalk-certs-tools.changes, susemanager-utils/susemanager-sls/salt-ssh/preflight.sh, susemanager-utils/susemanager-sls/susemanager-sls.changes
Use `%{_arch}` instead of `%{_host_cpu}` to detect package architecure for the Salt Bundle to be deployed.
No difference.
- No tests: alternative architecutres are not covered with the tests
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1197759 …
=> Fix architecture detection for the Salt Bundle

java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java, java/code/src/com/redhat/rhn/common/db/datasource/GeneratedSelectMode.java, java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateDriver.java, java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateTask.java, java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateWorker.java, java/code/src/com/redhat/rhn/taskomatic/task/ReportDBHelper.java, java/code/src/com/redhat/rhn/taskomatic/task/ReportDbUpdateTask.java, java/code/src/com/redhat/rhn/taskomatic/task/threaded/QueueDriver.java, schema/spacewalk/common/data/rhnTaskoBunch.sql, schema/spacewalk/common/data/rhnTaskoSchedule.sql, schema/spacewalk/common/data/rhnTaskoTask.sql, schema/spacewalk/common/data/rhnTaskoTemplate.sql, schema/spacewalk/upgrade/susemanager-schema-4.3.9-to-susemanager-schema-4.3.10/006-hub-reporting-task.sql
Adding a taskomatic job for aggregating reporting data from different susemanager servers
No difference.
- No tests
Fixes #
=> Hub reporting beta2 taskomatic

testsuite/ext-tools/maintenance_crawler.rb
Script to find repository URLs from a MI number
Related to : https://github.com/SUSE/spacewalk/issues/12728
Jenkins Job: https://ci.suse.de/view/Manager/view/Manager-qa/job/uyuni-master-qa-mu-repositories-crawler/
No difference.
- No tests
Ports:
- Manager-4.1
- Manager-4.2 …
=> Script to find repository URLs from a MI number

containers/proxy-httpd-image/Dockerfile, containers/proxy-httpd-image/proxy-httpd-image.changes, containers/proxy-ssh-image/proxy-ssh-image.changes, containers/proxy-ssh-image/uyuni-configure.py
Cleanup of uselss code/comments https://github.com/SUSE/spacewalk/issues/17396
No difference.
- No documentation needed: drop comments
- No tests: drop comments
Fixes # https://github.com/SUSE/spacewalk/issues/17396
=> Drop stale TODOs

java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java, java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java, java/spacewalk-java.changes
Set default image download protocol to `http`.
This will allow dropping ftp service on branch server in the future. `http` access to
the images is default part of proxy apache configuration.
The hostname `ftp` stays unchanged for now - it appears in documentation and in testsuite.
No difference.
- WIP
- covered by cucumber and unit tests
Fixes #
If you need to …
=> Set default image download protocol to http

susemanager-utils/testing/docker/scripts/clear-db-answers-pgsql.txt, susemanager-utils/testing/docker/scripts/schema_migration_reportdb_test_pgsql.sh
Containers might have a reportdb already. Drop it before re-creating it.
No difference.
=> drop and re-create the reportdb in the test correctly

testsuite/features/secondary/min_move_from_and_to_proxy.feature, testsuite/features/secondary/minssh_move_from_and_to_proxy.feature, testsuite/run_sets/secondary.yml
This is a test for moving minion and ssh minion between direct connection and a proxy.
No difference.
- No documentation needed: only testsuite
Test for https://github.com/uyuni-project/uyuni/pull/4313
=> Testsuite: Test for changing proxy

spacewalk/certs-tools/mgr_ssl_cert_setup.py, spacewalk/certs-tools/spacewalk-certs-tools.changes
Adapted openssl call in mgr_ssl_cert_setup.py to work on Python 3.9
No difference.
Fixes #
=> spacewalk-certs-tools: Adapt mgr_ssl_cert_setup.py to work on Python 3.9

susemanager-utils/susemanager-sls/salt/bootstrap/init.sls, susemanager-utils/susemanager-sls/salt/certs/debian.sls, susemanager-utils/susemanager-sls/salt/certs/init.sls, susemanager-utils/susemanager-sls/salt/certs/redhat.sls, susemanager-utils/susemanager-sls/salt/certs/suse.sls, susemanager-utils/susemanager-sls/salt/channels/gpg-keys.sls, susemanager-utils/susemanager-sls/salt/channels/init.sls, susemanager-utils/susemanager-sls/salt/ssh_bootstrap/init.sls
There is no dependency on the CA certificate deployment at the channel states.
This can cause the problem, that a package installation/update is triggered, but the required CA certificate is deployed later.
This result in SSL errors on the client.
No difference.
Fixes 
Contains also a fix for https://github.com/uyuni-project/uyuni/issues/4962
Tracks  …
=> depend channel state on deployment of the mgr ca cert

tftpsync/susemanager-tftpsync-recv/configure-tftpsync.sh, tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes
IPv6 transition IP addresses are invalid in the apache configuration.
Do not configure IPv6 addresses which start with '::' 
And allow configurations without IPv6 addresses specified
No difference. …
=> Fix tftpsync ipv6 config

susemanager-utils/susemanager-sls/salt-ssh/preflight.sh, susemanager-utils/susemanager-sls/susemanager-sls.changes
Fixes improper error handling on checking if the package was extracted.
No difference.
=> Fix improper error handling on extracting package by preflight script

spacecmd/spacecmd.changes, spacecmd/src/spacecmd/api.py, spacecmd/src/spacecmd/utils.py, spacecmd/tests/test_utils.py
Using "spacecmd api" with boolean paramaters fail as they are not parsed correctly and converted to strings.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/17415
=> Spacecmd api boolean param

java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java, java/spacewalk-java.changes, web/conf/rhn_web.conf, web/spacewalk-web.changes
As `salt` with the required feature was not published yet, we have to disable using the Salt Bundle with Salt SSH
No difference.
Tracks https://github.com/uyuni-project/uyuni/issues/5136
=> Temporary disable the Salt Bundle with Salt-SSH

web/conf/rhn_web.conf
Rolls back pre flight script disabling from https://github.com/uyuni-project/uyuni/pull/5140
No difference.
Tracks https://github.com/uyuni-project/uyuni/issues/5136
=> Rollback disabling salt ssh preflight script

python/spacewalk/server/importlib/debPackage.py, python/spacewalk/spacewalk-backend.changes
This PR is regarding #4481 
Before this PR, package-lists in the repository of debian packages are expected to be separated by comma-space (`', '`)
With this change, the package list is splitted by the comma only, and any leading and trailing whitespaces are striped from the elements of the package list.
The debian src-control spec does not explicitly state that package-lists have to be comma-space-separated.
It only is states (quoting the [manual](https://www.man7.org/linux/man-pages/man5/deb-control.5.html))
>       The syntax of Depends, Pre-Depends, Recommends and Suggests
>        fields is a list of groups of alternative packages. Each group is
>        a list of packages separated by vertical bar (or “pipe”) symbols,
>        ‘|’.  The groups are separated by commas.  Commas are to …
=> Backend deb importlib - less strict packages-list parsing 

java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateDriver.java
fixes criteria query exception
No difference.
Before:
After:
Fixes #
Make sure the changelogs entries you …
=> fix criteria query

java/buildconf/build-props.xml, java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml, java/spacewalk-java.changes, java/spacewalk-java.spec, search-server/spacewalk-search/buildconf/build-props.xml, search-server/spacewalk-search/buildconf/obs-maven-config.yaml, search-server/spacewalk-search/ivy.xml, search-server/spacewalk-search/spacewalk-search.changes, search-server/spacewalk-search/spacewalk-search.spec
Use new c3p0 package from Factory. The difference is, that mchange-commons is not included, but a separate package which requires a new symlink in the jar directory for tomcat, taskomatic and search server.
This PR also cleaned up some old ant checks for outdated hibernate versions which would not work anymore.
It also simplify the filelist of spacewalk-java to include all jars which are available in the directory. Same happens already for taskomatic and search server.
Ivy repos were also adapted to work with the new package.
No difference.
Partly fix https://github.com/SUSE/spacewalk/issues/17321 …
=> New c3p0 dependencies

spacewalk/setup/bin/spacewalk-setup, susemanager/bin/mgr-setup
Re-use existing CA cert and key if it was made available from the hub server.
No difference.
Fixes #
=> try to re-use CA cert and key if they are available locally

testsuite/features/step_definitions/command_steps.rb
No difference.
Before:
After:
Fixes # …
=> Remove the sleep to catch the cached package

java/code/src/com/suse/manager/webui/controllers/maintenance/MaintenanceController.java
Address a NPE when there is no user timezone configured in the db. In this case we will fallback to the server timezone.
No difference.
Before:
After:
- No tests: 
Tracks https://github.com/SUSE/spacewalk/issues/17146
=> Fix NPE in maintenance calendar display

java/code/src/com/redhat/rhn/domain/image/ImageInfoFactory.java, java/code/src/com/redhat/rhn/frontend/security/PxtAuthenticationService.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/HandlerFactory.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/image/DeltaImageInfoHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/image/ImageInfoHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/image/test/ImageInfoHandlerTest.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ImageFileSerializer.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ImageInfoSerializer.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ImageOverviewSerializer.java, java/code/src/com/suse/manager/webui/Router.java, java/code/src/com/suse/manager/webui/controllers/ImageUploadController.java, java/code/src/com/suse/manager/webui/services/iface/SaltApi.java, java/code/src/com/suse/manager/webui/services/impl/SaltService.java, java/code/src/com/suse/manager/webui/services/impl/runner/MgrRunner.java, java/code/src/com/suse/manager/webui/services/test/TestSaltApi.java, java/spacewalk-java.changes
Add new API calls and new fields in image lists.
Add image upload controller.
Image upload is compatible with the future HTTP API:
```
curl -H "Content-Type: application/json" -c cookies   -d "{'login':'admin','password':'admin'}" https://srv.tf.local/rhn/manager/api/login
curl -H "Content-Type: multipart/form-data" -F "data=@POS_Image_JeOS7_uyuni.x86_64-7.0.0-build87.tar.xz" -c cookies -b cookies https://srv.tf.local/rhn/manager/upload/image
```
No difference.
- TBD
Fixes https://github.com/SUSE/spacewalk/issues/16645
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyu …
=> API for image management

java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateWorker.java
To write last_sync, we need to lookup the server object in the worker thread.
Commit directly to really write it to the DB.
No difference.
=> fix writing last_synced

testsuite/.rubocop_todo.yml, testsuite/features/step_definitions/command_steps.rb, testsuite/features/support/lavanda.rb
This PR provides a new option in our Lavanda Objects, so we can run a remote command to a node and always log the output.
I did it to log the results of a suspicious script that fails when registering as SSH push via tunnel 
No difference.
- Manager-4.1
- Manager-4.2 …
=> QE: Added a verbose parameter in run method, so we always print the output of a command.

testsuite/documentation/cucumber-steps.md
Add TIP for Timeout Session Lifetime
No difference.
- Documentation needed: We added a tip about web session timeout
- No tests
Ports:
- Manager-4.1
- Manager-4.2
=> Add TIP for Timeout Session Lifetime

testsuite/features/support/env.rb
Few time ago we lost in a refactor the timestamps about when a scenario starts and ends.
This PR will get them back.
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QE: Cucumber methods should use log method instead of puts

java/manager-build.xml
Update coverage test target to Junit5
No difference.
Fixes #
=> Fix java unit tests coverage ant target

java/code/src/com/redhat/rhn/common/db/datasource/GeneratedSelectMode.java, java/code/src/com/redhat/rhn/taskomatic/task/ReportDBHelper.java
adding pagination to generated queries
No difference.
Before:
After:
Fixes # …
=> Hub reporting pagination for generated queries

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateWorker.java, java/code/src/com/redhat/rhn/taskomatic/task/ReportDbUpdateTask.java
The new hub reporting taskomatic job needs some translation strings
No difference.
=> add translation string for new Hub Reporting tasks

containers/proxy-tftpd-image/Dockerfile
Remove forgotten testing repo
No difference.
Fixes #
=> Remove unnecessary testing repo from tftp docker

java/code/src/com/redhat/rhn/domain/image/ImageInfo.java, java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java, java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/controllers/ImageBuildController.java, java/code/src/com/suse/manager/webui/services/SaltConstants.java, java/spacewalk-java.changes, java/spacewalk-java.spec, web/html/src/manager/images/image-view-buildlog.tsx, web/html/src/manager/images/image-view.tsx, web/spacewalk-web.changes
Store image build log in DB and show it in UI.
Before:
After:
New tab "Build Log" in Image details.
TBD
- Cucumber tests: TBD
Fixes #
=> Show image build log in UI

schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.1-to-uyuni-reportdb-schema-4.3.2/001-change-event-data-type.sql, schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.1-to-uyuni-reportdb-schema-4.3.2/003-fix-inventoryreport-duplication.sql
This PR fixes the scripts to updated the report db, to make them fully idempotent
No difference.
Fixes #
Tracks https://github.com/SUSE/spacewalk/issues/16564
=> Fix scripts idempotency

java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java, java/spacewalk-java.changes
We skip checks on URLs for free products. Currently we skipped the test only when the product class of that product was
"SLE-M-T" which failed when these products were still in Alpha or Beta stage and the product class was "SLE-M-T-ALPHA" or "SLE-M-T-BETA".
We also performed a check on openSUSE product URLs as the product class is "OPENSUSE".
No difference.
Port of https://github.com/SUSE/spacewalk/pull/17427
If …
=> Better free product check

java/code/src/com/redhat/rhn/testing/ImageTestUtils.java, java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java, java/code/src/com/suse/manager/reactor/messaging/test/image.inspect.kiwi.json, java/code/src/com/suse/manager/reactor/messaging/test/image.inspect.kiwi_compressed.json, java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java
Unit tests weren't properly updated and actual reason was carefully hidden behind some nonsense database insert problem. Only when commenting out transaction rollback (thanks @nadvornik for finding it) actual errors were presented.
This PR correctly adapts unit tests after PR https://github.com/uyuni-project/uyuni/pull/5109
No difference.
Fixes # …
=> Fix failing image building and inspection unit tests

schema/reportdb/common/views/ActionsReport.sql, schema/reportdb/common/views/ChannelsReport.sql, schema/reportdb/common/views/CustomChannelsReport.sql, schema/reportdb/common/views/ErrataChannelsReport.sql, schema/reportdb/common/views/ErrataListReport.sql, schema/reportdb/common/views/ErrataSystemsReport.sql, schema/reportdb/common/views/PackagesUpdatesNewestReport.sql, schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.2-to-uyuni-reportdb-schema-4.3.3/003-additional-tables.sql, schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.2-to-uyuni-reportdb-schema-4.3.3/004-additional-views.sql
This PR fixes the errors in the SQL script to create the reporting database
No difference.
- No tests:  no code changes
=> Fix wrong sql scripts for reportdb creation

java/code/internal/src/com/redhat/rhn/internal/doclet/ApiDoclet.java
Enables doc generation for `ApiResponseSerializer` base class.
=> HTTP API APIDOC fix

java/buildconf/build-props.xml, java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml, java/code/src/com/redhat/rhn/frontend/action/channel/manage/SyncErrataPackagesAction.java, java/spacewalk-java.spec
Fixed log4j migration issue
No difference.
Before:
After:
Fixes #
Make sure the changelogs entries you are …
=> removed log4j-over-slf4j

java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/MgrSyncChannelDtoSerializer.java
During the migration of the Serializers a small bug was introduced.
We store in the database a "mandatory" flag, but we provide in the API the opposite (optional).
This cause the testsuite to fail when it look for a channel of an extension product.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17482 …
=> fix channels optional flag

containers/proxy-httpd-image/Dockerfile, containers/proxy-httpd-image/proxy-httpd-image.changes
HTST support added dependency on headers module but this was not reflected in http container. This PR adds them.
No difference.
Fixes # …
=> Add headers and http_proxy modules to be in sync with regular proxy

testsuite/features/step_definitions/navigation_steps.rb
Increase advanced search test timeout from 5 to 10 seconds to give the search index enough time to update before performing a search and considering it a fail.
No difference.
- 4.1 https://github.com/SUSE/spacewalk/pull/17499
- 4.2 https://github.com/SUSE/spacewalk/pull/17498
=> QE: Increase timeout for advanced search tests

testsuite/features/secondary/allcli_overview_systems_details.feature
This adds a hardware refresh before testing the systems overview page for each client. This will hopefully prevent the IPv6 issues we saw in our testsuite. So even if the IP addresses change we still have the correct ones because of the hardware refresh shortly before testing it.
Furthermore I added the right tags for the Salt minion and the trad. client.
No difference.
- Fixes https://github.com/SUSE/spacewalk/issues/16626
- Manager 4.2
- Manager 4.1
- https://bugzilla.suse.com/show_bug.cgi?id=1193858
- https://bugzilla.suse.com/show_bug.cgi?id=1196469 …
=> QE: Add hardware refresh before overview tests

java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/spacewalk-java.changes, testsuite/features/secondary/min_ssh_tunnel.feature
ssh push reboot action has a valid response which contains the `shutdown` command, but the action needs to remain pending in order to execute `mgractionchains.resume` correctly. The problem does not happen with salt minion because the job `mgractionchains.resume` is executing after startup.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17388 …
=> Fix reboot time on salt-ssh client (bsc#1197591)

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
This PR adds missing dependencies required for Salt 3004 into the bootstrap repository definition for SLE15 family. New dependencies `python3-contextvars` and `python3-immutables`.
Currently, in case of using the BETA client tools, where Salt 3004 is already shipped, if these dependencies are not part of bootstrap repository and we try to bootstrap a minion without using Salt Bundle, then we face the following error due missing depedencies:
```console
CHECKING THE REGISTRATION STACK
-------------------------------------------------
* check for necessary packages being installed...
* client codebase is sle-15-sp3
package salt is not installed
package salt-minion is not installed
* going to install missing packages...
adding client software repository at …
```
=> Add missing dependencies for Salt 3004 into bootstrap repository for SLE15 family (bsc#1198221)

java/build.xml, java/buildconf/build-props.xml, java/code/src/log4j2.xml, java/manager-build.xml, java/spacewalk-java.spec
Remove the handling of custom log4j configuration in `build.xml` since that is never used.
No difference.
=> Simplify log4j handling in build.xml

testsuite/features/secondary/allcli_overview_systems_details.feature
There is another step necessary when doing a hardware refresh on a traditional client.
No difference.
Manager 4.2
Manager 4.1
=> fix: Hardware refresh on traditional client

susemanager-utils/susemanager-sls/src/modules/kiwi_info.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
Remove kiwi_info annotations, salt doesn't suppor them
No difference.
Fixes #
=> Remove kiwi_info annotations, salt doesn't suppor them

java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java, java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java, java/spacewalk-java.changes
Restore previously removed kernel and initrd url by mistake. And switch to use https by default.
No difference.
Fixes #
=> Add URL pillar entries to saltboot boot images

java/code/src/com/redhat/rhn/domain/image/ImageInfoFactory.java, java/code/src/com/redhat/rhn/manager/action/ActionChainManager.java, java/spacewalk-java.changes
This makes sure that image build action uses correct version string from ImageInfo.
createImageInfo() may change the value from empty string to "latest".
This should fix the failures in the testsuite where docker build is scheduled via XML RPC API
with empty version string.
No difference.
- covered by Cucumber tests
Fixes #
If …
=> Use correct image version from ImageInfo

susemanager-utils/susemanager-sls/modules/roster/uyuni.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
Improves the config management for `uyuni` roster module for salt with updating the cached data on changing the config for uyuni roster module.
In some cases if the pre flight script was disabled and then enabled back the cached roster data will not use the pre flight script.
The opposite situation is also possible.
No difference.
If …
=> Flush uyuni roster cache if the config has changed

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
Enable bootstrapping for Debian11 for SUSE Manager
No difference.
- No documentation needed: According to @jcayouette Debian11 was enabled for the doc for SUSE Manager 4.3 already
- No tests: Debian11 is not part of acceptance. But QE will need to do changes for BV (https://github.com/SUSE/spacewalk/issues/17549)
- 
Reference: https://github.com/SUSE/spacewalk/issues/15683 …
=> Enable bootstrapping for Debian11 for SUSE Manager

utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
Use the official URL for Debian11 security updates
No difference.
- No documentation needed: Transparent for the user
- No tests: Tool not covered by the tests
Related: https://github.com/SUSE/spacewalk/pull/17548
=> Use the official URL for Debian11 security updates

testsuite/features/secondary/srv_advanced_search.feature, testsuite/features/secondary/srv_reportdb.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/navigation_steps.rb, testsuite/features/support/xmlrpc_system.rb
By using a XMLRPC call (https://suma-head-srv.mgr.suse.de/rhn/apidoc/handlers/SystemSearchHandler.jsp#hostname), this PR tries to check first if the rhn-search service is responding correctly, before try the same feature using WebUI.
I would like feedback about where we should add this step, for now is embedded inside the step to clean the index of rhn-search service, but we could think of having it separately. **This is just a helper to assure the service is ready, the test will be the steps made on the WebUI.**
No difference.
Ports:
- Manager-4.1
- Manager-4.2 …
=> QE: Fix flackiness of a test case

testsuite/features/secondary/min_ansible_control_node.feature, testsuite/features/secondary/minssh_ansible_control_node.feature
On Ansible tests, when looking at inventories, we need to wait a bit until the page is loaded.
We can do it waiting until the page is loaded or just using a "wait until I see" of the text we are expecting, both of them could be valid approaches. I took the change that not includes a additional step.
No difference.
Ports:
- Manager-4.1
- Manager-4.2 …
=> QE: Fix flacky test on Ansible inventories

testsuite/features/step_definitions/retail_steps.rb
We need more logs when running bootstrap-pxeboot.exp to catch a test issue
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QE: We need more logs when running bootstrap-pxeboot.exp to catch a test issue

testsuite/features/secondary/min_salt_formulas.feature
Increase timeout to apply highstate after parametrize a formula.
it actually only happen in Head CI, in Uyuni CI we are good, it could be the hardware below it.
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QE: Increase timeout to apply highstate after parametrize a formula

testsuite/features/support/env.rb
This will log the output of `/var/log/cobbler/cobbler.log` in the output
when Cobbler fails.
No difference.
Manager 4.2
Manager 4.1
=> QE: Log Cobbler output when scenario fails

java/code/src/com/redhat/rhn/common/db/datasource/GeneratedSelectMode.java, java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateWorker.java, java/code/src/com/redhat/rhn/taskomatic/task/ReportDBHelper.java, java/spacewalk-java.changes
Currently synchronisation mechanism beetween hub and peripheral server assume that the db are exactly the same: this scenario is not always verified (e.g. during an upgrade, when the systems have different packages version).
The changes would like to enforce this functionalities, handling the case when a table in the hub does not exist in a peripheral server.
After:
Fixes https://github.com/SUSE/spacewalk/issues/17428 …
=> Handle missing tables gracefully during hub synchronisation

testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature, testsuite/features/step_definitions/retail_steps.rb
Retail scenario uses isolated network, so instead of connecting to public proxy FQDN, connect to internal FQDN.
No difference.
Fixes #
=> [Testsuite] Specify hostname to use in bootstrap script on proxy

testsuite/features/secondary/buildhost_docker_auth_registry.feature, testsuite/features/secondary/buildhost_docker_build_image.feature, testsuite/features/step_definitions/docker_steps.rb
The test "wait until all 5 container images are built" does not work correctly. It can be confused by failures in previous
scenarios. So if the first scenario failed, it made all the subsequent tests fail too.
Additionally, the failed tests did not wait until the scheduled build actions were finished, so they got queued on the
build host. This caused timeouts in subsequent scenarios.
The first commit changes the tests to wait for particular image name-version.
The "wait until all 3 container images are built" is still used once, because this is the only test which tests UI.
The second commit tests the number of image packages. It is not enough to rely on the result of inspect action:
https://github.com/uyuni-project/uyuni/blob/Manager-4.3-Beta2/java/code/src/com/suse/manager/utils/SaltUtil …
=> Testsuite: improve test of docker image build

testsuite/features/step_definitions/navigation_steps.rb, web/html/src/components/combobox.tsx, web/html/src/components/input/Select.tsx, web/html/src/components/input/select-test-attributes.tsx, web/html/src/manager/content-management/shared/components/panels/sources/channels/channels-selection.tsx, web/spacewalk-web.changes
Add `data-testid` support to the shared Select component. This will allow us to easily fetch and set the value in Cucumber tests.  
I haven't updated any of the related test code since I'm not sure which parts need to be addressed, hence the WIP in the title. Perhaps @srbarrios or @ktsamis can give me a hand with this?  
Other than that, feel free to review.  
In general, does this approach work for you?
No difference. …
=> Add `data-testid` support to the Select component

.github/workflows/rubocop.yml
According to https://github.com/actions/setup-ruby we should update our GitHub action for Ruby and RuboCop:
> Please note: This action is deprecated and should no longer be used. The team at GitHub has ceased making and accepting code contributions or maintaining issues tracker. Please, migrate your workflows to the [ruby/setup-ruby](https://github.com/ruby/setup-ruby), which is being actively maintained by the official Ruby organization.
This PR changes the GitHub action to the actively maintained one. 
No difference.
- No tests: Only changes to the CI
Manager 4.2
Manager 4.1 …
=> QE: Update Ruby CI

java/code/src/com/redhat/rhn/frontend/xmlrpc/XmlRpcServlet.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/test/XmlRpcServletTest.java, java/code/src/com/suse/manager/api/ListDeserializer.java, java/code/src/com/suse/manager/api/MapDeserializer.java, java/code/src/com/suse/manager/api/test/RouteFactoryTest.java, java/code/src/com/suse/manager/api/test/TestHandler.java, java/spacewalk-java.changes
This PR fixes various bugs in HTTP API
- `Long` to `Int` conversion in XMLRPC compatible handler methods
- Sonarqube errors
=> HTTP API fixes

testsuite/features/step_definitions/docker_steps.rb
Proper fix for a problem that appeared during a rebase conflict for #5175.
No ports, Uyuni only
=> API: fix rebase conflict properly

testsuite/features/core/proxy_branch_network.feature
Remove old workaround for bsc#1196050 - Hardware list refresh was not sufficient to detect a change in interface's IP address. Now the product problem is fixed, and we don't need to restart salt-minion on the proxy anymore.
Ports:
* 4.1: SUSE/spacewalk#17596
* 4.2: SUSE/spacewalk#17595
=> Remove old workaround

testsuite/features/support/namespaces/system.rb
Fix wrong API parameter
Ports:
* 4.1: SUSE/spacewalk#17601
* 4.2: SUSE/spacewalk#17599
=> Fix wrong parameter

testsuite/features/support/namespaces/system.rb
Fix wrong HTTP API method name.
Ports:
* 4.1: SUSE/spacewalk#17602
* 4.2: SUSE/spacewalk#17599
=> Fix method name

susemanager-utils/susemanager-sls/salt/bootstrap/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Replaces https://github.com/uyuni-project/uyuni/pull/5252 to be included in Uyuni-2022.04
Fix Error 'no match for argument: salt-minion' when bootstrapping Oracle Linux Clients due to missing oracle entry in 'RedHat OS Family'.
No difference.
Before:
After:
- No documentation needed: Only Bugfix
- No tests: Nothing changed on existing tests / no new tests added.
Fixes: https://github.com/uyuni-project/uyuni/issues/5061
Issue introduced in PR: https://github.com/uyuni-project/uyuni/pull/4249
If you …
=> fix(susemanager-sls): Oracle Linux Bootstrap Issue - Uyuni-2022.04

utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
Fix the channel name for the Debian 11 client tools. It mentioned "Debian10'", which is wrong and caused conflicts, as reported at https://github.com/uyuni-project/uyuni/issues/5069
No difference.
- No tests: But again, we should consider build validation to catch such issues :-)
Fixes  https://github.com/uyuni-project/uyuni/issues/5069 …
=> Fix the channel name for the Debian 11 client tools

testsuite/features/step_definitions/api_common.rb
Fix API test name in XML-RPC case
No ports, head only.
=> Fix API test name

containers/proxy-tftpd-image/proxy-tftpd-image.changes, containers/proxy-tftpd-image/tftp_wrapper.py
- Add HTTPS validation using provided CA cert
- Fix HSTS enablement issues
- Remove some experimental code
- make default logging level debug (can be removed prior GA, but is useful for validation)
No difference.
Fixes # …
=> Add HTTPS validation using provided CA cert

testsuite/features/step_definitions/docker_steps.rb
Make sure that the test for built container images does not match OS Images built by previous test.
Fixes the "And I wait at most 60 seconds until all "3" container images are built correctly in the GUI" failure.
=> Testsuite: Do not match OS Images in container test

testsuite/features/support/http_client.rb
Print the returned error message if HTTP API status code is not 200.
None, Head only
=> Print error message if HTTP status not 200

susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.changes, susemanager-utils/supportutils-plugin-susemanager-client/susemanagerclient
Dump config and logs of proxy containers in client supportconfig.
The rationale behind adding it in this plugin is that the host will need to be registered to install the `uyuni-proxy-systemd-services` package. However this may be reverted in a mid term to handle more OSes and potentially kubernetes deployments.
No difference. 
- No tests: supportconfig change
Fixes https://github.com/SUSE/spacewalk/issues/17520 …
=> Add supportconfig data from proxy containers

web/html/src/build/webpack.config.js, web/html/src/package.json, web/html/src/yarn.lock
Downgrade `CopyWebpackPlugin` to 5.1.2, this fixes out-of-memory issues in local OBS builds. If you ask me why, I don't know. If you ask me how I found out, the answer is with a lot of pain and suffering.
No difference.
- No tests: build tooling
Related: https://github.com/webpack-contrib/copy-webpack-plugin/issues/685
If you need to …
=> Downgrade `CopyWebpackPlugin`

testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
This will fix a wrong name when checking of the proxy of a bootstrapped
terminal exists. The issue was found in our Uyuni CI.
See https://github.com/SUSE/spacewalk/pull/17080 for an older PR that
did the fix in another place.
The PR is already building in [Jenkins](https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/1296/).
No difference.
https://github.com/SUSE/spacewalk/pull/17611
https://github.com/SUSE/spacewalk/pull/17612 …
=> QE: Fix wrong proxy name in terminal test

testsuite/documentation/api.md
Document how to easily debug the API from ruby.
Ports:
* 4.1: SUSE/spacewalk#17623
* 4.2: SUSE/spacewalk#17622
=> Document API standalone scripts

testsuite/features/build_validation/smoke_tests/smoke_tests.template
Card: https://github.com/SUSE/spacewalk/issues/17626
Include Prometheus and Prometheus exporter in our BV test suite
No difference.
Ports:
- Manager-4.1
- Manager-4.2
=> QE: Include Prometheus and Prometheus exporter in our BV test suite

proxy/installer/configure-proxy.sh, proxy/installer/spacewalk-proxy-installer.changes
When proxy is running salt bundle defaults were wrongly detected. This PR fixes loading correct configuration file
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17474
=> Prefer salt-bundle minion config if available

java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/code/src/com/suse/manager/reactor/test/RegisterMinionActionTest.java, java/spacewalk-java.changes
Saltbooted (Retail) terminals were made to always be part of TERMINALS group, but this was just to better organize them and was not really based on any business decision and turned out to be a nuisance.
This PR makes TERMINALS group optional. If exists, terminals will become a member on registration. Otherwise just continue onboarding.
This does not impact branch group which is still mandatory.
No difference.
- No …
=> Make group TERMINALS optional for saltbooted machines

rel-eng/push-packages-to-obs.sh
$subject
No difference.
- No documentation needed: rel-eng stuff
- No tests: rel-eng stuff
Fixes # https://github.com/SUSE/spacewalk/issues/17481
=> Add a changelog entry if container images version needs to be bumped

java/code/src/com/redhat/rhn/frontend/action/systems/SystemSearchHelper.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/search/SystemSearchHandler.java, java/code/src/com/suse/manager/api/RouteFactory.java, java/code/src/com/suse/manager/api/test/RouteFactoryTest.java
Serializers that serialize classes in the same class hierarchy override each other in the order they are added. To ensure that subclass serializers take precedence, they must be added later than serializers of their parent classes.
This PR reorders serializers according to the hierarchy relationship between their supported classes to obey the mentioned rule.
If you need to …
=> Ensure correct order of precedence with GSON serializers

java/spacewalk-java.changes, java/spacewalk-java.spec
Fix broken symlinks in webapp because of new netty version having the jar files at a different place.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/5278
=> require netty build for uyuni to fix failing tomcat start

java/buildconf/build-props.xml, java/spacewalk-java.changes
Allow byte-buddy.jar and byte-buddy/byte-buddy.jar as a location.
No difference.
=> Allow alternative location for byte-buddy

proxy/proxy/httpd-conf/spacewalk-proxy.conf, proxy/proxy/spacewalk-proxy.changes, spacewalk/config/etc/httpd/conf.d/zz-spacewalk-www.conf, spacewalk/config/spacewalk-config.changes
This patch is disabling HSTS headers by default, but leaving the configuration for relatively easy enablement. This way we can gather some experience first and then consider enabling it by default in a future release.
No difference.
- Documentation will be needed, I will create a PR with a paragraph on how to enable it and warn about required browser configuration (importing certificates)
- Testing might be considered in this issue: https://github.com/SUSE/spacewalk/issues/17576
Follow-up to #4981 
If …
=> Disable HSTS headers by default (Uyuni-2022.04)

web/html/src/manager/proxy/container-config.tsx, web/spacewalk-web.changes
Simple string change to be consistent with the SSL terminology
Before:
After:
- No tests: 
Fixes #
=> Use proper SSL terminology visible to the user

java/code/src/com/redhat/rhn/domain/errata/ErrataFactory.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java, java/code/src/com/suse/manager/webui/services/test/SaltServerActionServiceTest.java, java/spacewalk-java.changes, spacecmd/spacecmd.changes, spacecmd/src/spacecmd/system.py, susemanager-utils/susemanager-sls/salt/packages/pkgupdate.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
When doing a full system update it is better to call with salt `pkg.upgrade` and not `pkg.install` with defined version numbers.
This require a new API call and a new salt state.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/17587 …
=> Add real pkg update

schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.2-to-uyuni-reportdb-schema-4.3.3/002-fix-system-group.sql, schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.2-to-uyuni-reportdb-schema-4.3.3/003-additional-tables.sql, schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.2-to-uyuni-reportdb-schema-4.3.3/004-additional-views.sql, schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.3-to-uyuni-reportdb-schema-4.3.4/003-fixes-for-spacewalk-report-compatibility.sql, schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.3-to-uyuni-reportdb-schema-4.3.4/004-fix-missing-views.sql
This PR adds additional update scripts for the reporting database. In fact, a previous update file was missing a view (`ChannelsReport`) and created a view with a wrong name (`SystemHistoryKickstartReport` instead of `SystemHistoryAutoinstallationReport`). This PR addresses that by taking into account the wrong name in the update and by adding the possibly missing view.
No difference. …
=> Added some views that were missing in the previous update scripts

testsuite/features/step_definitions/navigation_steps.rb
Fix failing react-select XPath selector as followup to https://github.com/uyuni-project/uyuni/pull/5078
=> Fix react-select XPath selector

java/build.xml, java/code/internal/src/com/redhat/rhn/internal/doclet/VelocityHelper.java
Fix compile internal
No difference.
=> Fix compile internal

java/code/src/com/redhat/rhn/manager/system/SystemManager.java
Store credentials correctly by calling store function.
No difference.
=> store credentials when generating a new password

testsuite/features/step_definitions/navigation_steps.rb
Backport #5325 from 2022.04, with the same git commit hash
=> Backport #5325 from 2022.04, with the same git commit hash

susemanager-utils/testing/docker/scripts/generate-reportdb-docs.sh
This PR fixes an issue that prevents the documentation tool to run correctly with the latest version of the jdbc postgresql driver. This version needs an additional classpath entry for ongres. The first commit sets the classpath dynamically based on the version of the postgresql-jdbc driver package installed inside the docker container. The seconds adds some minor code cleanup based on the suggestion of shellcheck.
No difference.
- No tests: no code change …
=> Set the classpath for running SchemaSpy depending on the Posgresql jdb driver version
