susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
Port of https://github.com/uyuni-project/uyuni/pull/4939
=> Add SLES15SP4 and SUMA Proxy 4.3 to bootstrap repo definitions (#4939)

rel-eng/packages/susemanager, susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes, susemanager/susemanager.spec
Backport https://github.com/uyuni-project/uyuni/pull/4945 and tagging to master
=> Backport #4945 and tagging to master

.github/reviewers.yml
- Add Erwan to the QE list
- Rename qa to qe
No difference.
- No tests: 
https://github.com/SUSE/spacewalk/issues/17145
=> QA: Add Erwan

susemanager/bin/mgr-setup
Fixes https://github.com/uyuni-project/uyuni/pull/4955
=> fix setup certificate path in setup

susemanager-utils/susemanager-sls/salt/virt/create-vm.sls, susemanager-utils/susemanager-sls/src/modules/virt_utils.py, susemanager-utils/susemanager-sls/src/tests/test_module_virt_utils.py, susemanager-utils/susemanager-sls/susemanager-sls.changes
Fixes a few python3-isms occurring on python 2 virtual host minion.
No difference.
- No tests: only on py2 systems
=> Python2 salt virtualization fixes

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_de.xml
Mini translation update
No difference.
- No tests: **translation**
=> Translated using Weblate (German)

java/code/src/com/redhat/rhn/frontend/xmlrpc/image/DeltaImageInfoHandler.java
This fixes xmlrpc doc tags.
Fixes a problem created in #4466
=> Fix typo in xmlrpc doc

client/rhel/mgr-daemon/mgr-daemon.spec, client/tools/spacewalk-koan/spacewalk-koan.spec
Fixing some build issues. (detected by failed copr builds)
No difference.
Fixes #
=> Fix build issues

containers/proxy-httpd-image/Dockerfile, containers/proxy-salt-broker-image/Dockerfile, containers/proxy-squid-image/Dockerfile, containers/proxy-ssh-image/Dockerfile, containers/proxy-tftpd-image/Dockerfile
The base value is `$BASE` not `$ARG` !
No difference.
Fixes #
=> Base images fix

containers/proxy-httpd-image/Dockerfile, containers/proxy-salt-broker-image/Dockerfile, containers/proxy-squid-image/Dockerfile, containers/proxy-ssh-image/Dockerfile, containers/proxy-tftpd-image/Dockerfile
Uyuni container images base is SUSE BCI 15SP3
No difference.
Fixes #
=> Containers default base fix

containers/proxy-httpd-image/Dockerfile, containers/proxy-httpd-image/proxy-httpd-image.changes, containers/proxy-httpd-image/uyuni-configure.py, java/code/src/com/redhat/rhn/common/security/acl/Access.java, java/code/src/com/redhat/rhn/frontend/action/systems/sdc/ProxyClientsAction.java, java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml, java/code/src/com/redhat/rhn/manager/system/SystemManager.java, java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java, java/code/src/com/suse/manager/webui/controllers/utils/AbstractMinionBootstrapper.java, java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java, java/code/webapp/WEB-INF/nav/system_detail.xml, java/code/webapp/WEB-INF/pages/systems/sdc/overview.jsp, java/code/webapp/WEB-INF/pages/systems/sdc/proxyclients.jsp, java/spacewalk-java.changes
Title says it all
UI after the change:
Fixes https://github.com/SUSE/spacewalk/issues/17254
=> Use foreign entitlement for containerized proxies

client/tools/spacewalk-oscap/spacewalk-oscap.changes, client/tools/spacewalk-oscap/spacewalk-oscap.spec, rel-eng/packages/spacewalk-oscap
Backport changes for Manager-4.3-Beta2 and tagging
=> Backport changes for Manager-4.3-Beta2 and tagging

susemanager-utils/testing/automation/javascript-lint.sh
fix javascript lint test
No difference.
- No tests
Fixes #
=> fix javascript-lint test

sonar-project.properties
Fix sonarqube failure due to python refactoring
No difference.
Fixes #
=> Fix SonarQube config after the python refactoring

spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb, spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes
Autogenerate a better password. Use 25 characters and inlclude numbers as well.
Do not read endless from urandom and close the read after a limited number of lines.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/5009 …
=> auto generate better password

rel-eng/packages/uyuni-setup-reportdb, spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb, spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes, spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.spec
=> Backport #5036 and tagging

python/spacewalk/satellite_tools/repo_plugins/yum_src.py, python/spacewalk/spacewalk-backend.changes, python/test/unit/spacewalk/satellite_tools/test_yum_src.py, python/uyuni/common/fileutils.py, python/uyuni/uyuni-common-libs.changes, python/uyuni/uyuni-common-libs.spec
Adaption/Port of https://github.com/SUSE/spacewalk/pull/17218
No difference.
=> More decompression reposync

spacewalk/admin/spacewalk-admin.changes, spacewalk/admin/spacewalk-service.systemd
Hide grep result from terminal message.
No difference.
- No tests: **minor**
=> Hide message on restart

susemanager-utils/testing/automation/VERSION.SUSE-Manager, susemanager-utils/testing/automation/VERSION.Uyuni, susemanager-utils/testing/automation/schema-migration-reportdb-test-pgsql.sh, susemanager-utils/testing/automation/schema-migration-test-pgsql.sh, susemanager-utils/testing/docker/scripts/schema_migration_reportdb_test_pgsql.sh, susemanager-utils/testing/docker/scripts/schema_migration_test_pgsql.sh
Otherwise, this test fails for susemanager head RPMs, plus it needs to
be updated everytime.
The container should not contain any other RPMs, so it should be safe.
No difference.
- No tests
Related to https://github.com/SUSE/spacewalk/issues/14922
=> Do not look for specific version files when testing schema

susemanager-utils/testing/docker/scripts/schema_migration_reportdb_test_pgsql.sh, susemanager-utils/testing/docker/scripts/schema_migration_test_pgsql.sh
Installing multiple packages in separate commands lead to dependency errors.
No difference.
=> install packages together in one command solve internal dependencies

sonar-project.properties
Finally fix the duplicated index issue
=> Fix SonarQube test folders definitions

susemanager-utils/testing/docker/scripts/schema_migration_reportdb_test_pgsql.sh, susemanager-utils/testing/docker/scripts/schema_migration_test_pgsql.sh
Review the usage of ${} and the usage message
No difference.
- No tests
Fixes #
=> Refactor schema migration scripts

java/code/src/com/suse/manager/webui/templates/system-common.jade, java/spacewalk-java.changes
Fixes help link on system overview
#4665 
No difference.
- No tests: 
Fixes #
=> Fixes help link on system overview

testsuite/features/support/constants.rb
=> Use new base channel as key

testsuite/features/step_definitions/command_steps.rb
Follow-up of #5086. I did not realize this issue affected two cucumber steps, and fixed it for only one of them.
Ports:
* 4.1: SUSE/spacewalk#17394
* 4.2: SUSE/spacewalk#17393
=> Do not count time for SSH

testsuite/features/step_definitions/common_steps.rb
Fixes an issue in the testsuite for the uptime tests
No difference.
- [4.1](https://github.com/SUSE/spacewalk/pull/17402)
- [4.2](https://github.com/SUSE/spacewalk/pull/17400)
=> QE: Fix uptime tests

containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes
=> Add changelog for proxy-systemd-services ECO

rel-eng/push-packages-to-obs.sh
See title
No difference.
- No tests: tooling
=> Replace all uyuni instances of BuildTag line of SLE containers

susemanager-utils/mgr-libmod/mgr-libmod.changes, susemanager-utils/mgr-libmod/mgr-libmod.spec
python3-mock is not used so removing it from build requirements.
No difference.
=> mgr-libmod: Requirement adjustments

rel-eng/packages/susemanager-sls, susemanager-utils/susemanager-sls/salt-ssh/preflight.sh, susemanager-utils/susemanager-sls/susemanager-sls.changes, susemanager-utils/susemanager-sls/susemanager-sls.spec
Backport #5097 and tagging to 4.3-Beta2
=> Backport #5097 and tagging to 4.3-Beta2

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
Fix package names for SLE15 bootstrap repo packages
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17343
Tracks
=> Manager 4.3 beta2 bootstrap repo

spacewalk/certs-tools/rhn_bootstrap_strings.py, spacewalk/certs-tools/spacewalk-certs-tools.changes, susemanager-utils/susemanager-sls/salt-ssh/preflight.sh, susemanager-utils/susemanager-sls/susemanager-sls.changes
Reverts uyuni-project/uyuni#5120
=> Revert "Fix architecture detection for the Salt Bundle"

rel-eng/packages/spacewalk-certs-tools, rel-eng/packages/susemanager-sls, spacewalk/certs-tools/rhn_bootstrap_strings.py, spacewalk/certs-tools/spacewalk-certs-tools.changes, spacewalk/certs-tools/spacewalk-certs-tools.spec, susemanager-utils/susemanager-sls/salt-ssh/preflight.sh, susemanager-utils/susemanager-sls/susemanager-sls.changes, susemanager-utils/susemanager-sls/susemanager-sls.spec
Backport #5125 and tagging to master
=> Backport #5125 and tagging to master

susemanager/bin/pg-migrate-12-to-14.sh, susemanager/susemanager.changes
adding migration script for pg12 to pg14.
Tested for a migration from 4.1 to 4.3
No difference.
Fixes …
=> adding migration script for pg12 to pg14

schema/reportdb/common/tables/System.sql
=> fix a typo in the reportdb schema

susemanager-utils/testing/automation/wait-for-builds.sh
Sometimes, the wait for build command gets stucked. This seems to be an
issue with calling "osc project". It happens seldomly, but when it
happens, it never ends. The solution is to either run a rebuild or
cancel the command and call it again.
Thus, let's add a timeout to this command. If it gets stucked, let's run
it again. If after 2 retries this does not get fixed, meaning it is
again stucked, let's exit with an error.
No difference.
- No tests
N/A …
=> CI: add a timeout to "osc project" command

branding/spacewalk-branding.changes, client/rhel/yum-rhn-plugin/yum-rhn-plugin.changes
Missing changelogs for 2022.04/4.3 Beta3
=> Missing changelogs for 2022.04/4.3 Beta3

susemanager/susemanager.changes
=> fix changelog

java/build.xml, java/manager-build.xml
See title
No difference.
Fixes #
=> Fix ant build files log4j config files

web/html/src/manager/proxy/container-config.tsx, web/spacewalk-web.changes
$subject
Before:
After:
- No documentation needed: feature not yet documented
- No tests: feature not yet tested
Fixes # https://github.com/SUSE/spacewalk/issues/17509
=> All form fields with a hint message, rewording some

rel-eng/push-packages-to-obs.sh
$subject
No difference.
- No documentation needed: rel-eng stuff
- No tests: rel-eng stuff
Fixes #
=> Bugfix: comparison operator

java/code/src/com/redhat/rhn/common/db/NamedPreparedStatement.java, java/code/src/com/redhat/rhn/common/db/datasource/CachedStatement.java, java/code/src/com/redhat/rhn/common/db/datasource/WriteMode.java, java/code/src/com/redhat/rhn/common/db/datasource/xml/GeneralReport_queries.xml, java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateWorker.java, java/code/src/com/redhat/rhn/taskomatic/task/ReportDBHelper.java, java/code/src/com/redhat/rhn/taskomatic/task/ReportDbUpdateTask.java, java/manager-build.xml, java/spacewalk-java.changes, schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.3-to-uyuni-reportdb-schema-4.3.4/001-order-index-SystemPackageInstalled.sql, schema/reportdb/uyuni-reportdb-schema.changes
Using "ctid" does not use an index. Query the primary key and use the columns for order by clause.
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/1530
- 
Fixes: https://github.com/SUSE/spacewalk/issues/17483
=> Hub reporting performance improvment

testsuite/features/reposync/srv_sync_products.feature, testsuite/features/support/constants.rb
Sync beta client tools, so we sync salt-bundle packages too, and we fix the failure generating bootstrap repositories.
No difference.
No ports. Only for Master.
=> QE: Sync beta client tools

java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateDriver.java, java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateTask.java, java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateWorker.java, java/code/src/com/redhat/rhn/taskomatic/task/errata/ErrataCacheDriver.java, java/code/src/com/redhat/rhn/taskomatic/task/errata/ErrataQueueDriver.java, java/code/src/com/redhat/rhn/taskomatic/task/repomd/ChannelRepodataDriver.java, java/code/src/com/redhat/rhn/taskomatic/task/sshpush/SSHPushDriver.java, java/code/src/com/redhat/rhn/taskomatic/task/threaded/QueueDriver.java, java/code/src/com/redhat/rhn/taskomatic/task/threaded/TaskQueue.java, java/spacewalk-java.changes
Currently the taskomatic job `mgr-update-reporting-hub`:
- cannot be schedule more than once every 24h. Also trying to use `Single Run Schedule` from UI, does not work if last run was scheduled earlier than 24 hours ago
- Finished status was not checked properly: sometimes status remains as pending or running also if the job was successfully completed.
This PR: 
- remove the hardcoded check for the 24h 
- create a new setting for the thead driver, to specify if the task should be blocking 
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUME …
=> Improve TaskQueue for mgr-update-reporting-hub task

testsuite/features/secondary/buildhost_docker_auth_registry.feature, testsuite/features/support/namespaces/channel.rb
* Solve authentication problem when building docker images by moving all authentication at feature level.
* Fix wrong parameter name
Ports:
* 4.1: SUSE/spacewalk#17600
* 4.2: SUSE/spacewalk#17599
=> Various API problems

testsuite/features/secondary/min_salt_openscap_audit.feature
Add API authentication to scap feature.
Ports:
* 4.1: SUSE/spacewalk#17603
* 4.2: SUSE/spacewalk#17599
=> Add API authentication

rel-eng/packages/susemanager-sls, susemanager-utils/susemanager-sls/salt/bootstrap/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes, susemanager-utils/susemanager-sls/susemanager-sls.spec
Backport #5260 and tagging to master
Thanks to @wombelix for the fix.
=> Backport #5260 and tagging to master

schema/spacewalk/susemanager-schema.changes, schema/spacewalk/susemanager-schema.spec
Added build requirements to spec file.
No difference.
Build tested successfully on COPR:
epel-8-x86_64
epel-9-x86_64
opensuse-leap-15.3-x86_64
=> Update build requirements for susemanager-schema

java/code/src/com/redhat/rhn/frontend/xmlrpc/XmlRpcServlet.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/test/XmlRpcServletTest.java, java/code/src/com/suse/manager/api/ListDeserializer.java, java/code/src/com/suse/manager/api/MapDeserializer.java, java/code/src/com/suse/manager/api/test/RouteFactoryTest.java, java/code/src/com/suse/manager/api/test/TestHandler.java, java/spacewalk-java.changes
Reverts uyuni-project/uyuni#5183 to merge it to `2022.04` instead.
=> Revert "HTTP API fixes"

java/code/src/com/suse/manager/webui/menu/MenuTree.java, java/spacewalk-java.changes, web/html/src/components/utils/HelpLink.tsx, web/html/src/core/user-preferences/index.ts, web/html/src/manager/admin/config/monitoring-admin.tsx, web/html/src/manager/login/login-footer.tsx, web/html/src/manager/shared/menu/menu.tsx, web/html/src/utils/index.ts, web/html/src/utils/jsx.test.ts, web/html/src/utils/jsx.ts, web/spacewalk-web.changes
Also fixes some minor bugs in the menu I stumbled on.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17231
=> Fix broken documentation and release notes links

susemanager-utils/testing/docker/scripts/init-pgsql-db4eclipse.sh
Setup reportdb schema together with normal DB schema in unit test container
No difference.
=> setup reportdb schema together with main db schema for unit tests

java/buildconf/ivy/ivy-suse.xml, java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java, java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java, java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/services/test/SaltServerActionServiceTest.java, java/spacewalk-java.changes, java/tito.props
adjusts uyuni for changes in https://github.com/SUSE/salt-netapi-client/pull/300
No difference.
Fixes #16354
=> handle function name array results

testsuite/features/secondary/minkvm_guests.feature, testsuite/features/secondary/srv_power_management.feature, testsuite/features/secondary/srv_power_management_redfish.feature
This adds missing Cobbler scopes to some of our features. CC @SchoolGuy 
No difference.
Manager 4.2
Manager 4.1
=> QE: Add missing Cobbler scopes

proxy/proxy/httpd-conf/spacewalk-proxy.conf, proxy/proxy/spacewalk-proxy.changes, proxy/proxy/spacewalk-proxy.spec, rel-eng/packages/spacewalk-config, rel-eng/packages/spacewalk-proxy, spacewalk/config/etc/httpd/conf.d/zz-spacewalk-www.conf, spacewalk/config/spacewalk-config.changes, spacewalk/config/spacewalk-config.spec
=> Backport #5302 and tagging

utils/spacewalk-hostname-rename, utils/spacewalk-utils.changes
Fix spacewalk-hostname-rename
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17535
Fixes https://github.com/SUSE/spacewalk/issues/17647
=> Fix hostname rename

testsuite/features/step_definitions/api_common.rb, testsuite/features/support/namespaces/actionchain.rb, testsuite/features/support/namespaces/configchannel.rb, testsuite/features/support/namespaces/image.rb, testsuite/features/support/namespaces/schedule.rb, testsuite/features/support/namespaces/system.rb, testsuite/features/support/namespaces/user.rb
Catch up with new HTTP API parameter names.
Ports:
* 4.1: SUSE/spacewalk#17685
* 4.2: SUSE/spacewalk#17686
=> Use new parameter names

java/spacewalk-java.changes, java/spacewalk-java.spec, web/spacewalk-web.changes, web/spacewalk-web.spec
Minor changes and cleanup to spec files to fix dependencies or simplify the file.
No difference.
=> Minor Spec updates

java/buildconf/ivy/ivy-suse.xml
Match the velocity-engine version of the OBS repo
No difference.
Fixes #
=> Update velocity-engine to 2.3

rel-eng/packages/susemanager-sls, susemanager-utils/susemanager-sls/salt-ssh/preflight.sh, susemanager-utils/susemanager-sls/susemanager-sls.changes, susemanager-utils/susemanager-sls/susemanager-sls.spec
Backport #5380 and tagging to master
=> Backport #5380 and tagging to master

containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes, containers/proxy-systemd-services/uyuni-proxy-systemd-services.spec
See title
No difference.
- No tests: specfile change
Fixes #
=> Rename container_images_path spec file macro

containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes, containers/proxy-systemd-services/uyuni-proxy-systemd-services.spec, rel-eng/packages/uyuni-proxy-systemd-services
=> Backport #5396 and tagging

rel-eng/push-packages-to-obs.sh
$subject
No difference.
- No documentation needed: rel-eng stuff
- No tests: rel-eng stuff
Fixes #
=> Tilde to split image version from additional info

containers/proxy-httpd-image/proxy-httpd-image.changes, containers/proxy-salt-broker-image/proxy-salt-broker-image.changes, containers/proxy-squid-image/proxy-squid-image.changes, containers/proxy-ssh-image/proxy-ssh-image.changes, containers/proxy-tftpd-image/proxy-tftpd-image.changes
Sync changelog entries from IBS
=> Sync changelog entries from IBS

containers/proxy-httpd-image/proxy-httpd-image.changes, containers/proxy-salt-broker-image/proxy-salt-broker-image.changes, containers/proxy-squid-image/proxy-squid-image.changes, containers/proxy-ssh-image/proxy-ssh-image.changes, containers/proxy-tftpd-image/proxy-tftpd-image.changes, rel-eng/push-packages-to-obs.sh
Backport container fun from 4.3-RC1
=> Backport container fun from 4.3-RC1

containers/proxy-httpd-image/Dockerfile, containers/proxy-httpd-image/proxy-httpd-image.changes, containers/proxy-salt-broker-image/Dockerfile, containers/proxy-salt-broker-image/proxy-salt-broker-image.changes, containers/proxy-squid-image/Dockerfile, containers/proxy-squid-image/proxy-squid-image.changes, containers/proxy-ssh-image/Dockerfile, containers/proxy-ssh-image/proxy-ssh-image.changes, containers/proxy-tftpd-image/Dockerfile, containers/proxy-tftpd-image/proxy-tftpd-image.changes, rel-eng/push-packages-to-obs.sh
$subject
No difference.
- No tests: 
Fixes #
=> Container images tag and version fixes for RC1

containers/proxy-httpd-image/Dockerfile, containers/proxy-httpd-image/proxy-httpd-image.changes, containers/proxy-salt-broker-image/Dockerfile, containers/proxy-salt-broker-image/proxy-salt-broker-image.changes, containers/proxy-squid-image/Dockerfile, containers/proxy-squid-image/proxy-squid-image.changes, containers/proxy-ssh-image/Dockerfile, containers/proxy-ssh-image/proxy-ssh-image.changes, containers/proxy-tftpd-image/Dockerfile, containers/proxy-tftpd-image/proxy-tftpd-image.changes, rel-eng/push-packages-to-obs.sh
=> Backport #5407 to Master

spacewalk/admin/spacewalk-admin.changes, spacewalk/admin/spacewalk-service.systemd
Minor text change
No difference.
- No tests: **minor**
Tracks https://github.com/SUSE/spacewalk/pull/17765
=> clarify schema upgrade check message

java/code/src/com/redhat/rhn/frontend/action/errata/ErrataConfirmAction.java, java/code/src/com/redhat/rhn/frontend/action/systems/ErrataConfirmSetupAction.java, java/spacewalk-java.changes
was "...?aid=123,456" but should be "...?aid=123456"
No difference.
- No tests: **minor**
Fixes https://github.com/uyuni-project/uyuni/issues/4047
Tracks https://github.com/SUSE/spacewalk/pull/17763 https://github.com/SUSE/spacewalk/pull/17764 …
=> fix link to schedule page

.github/PULL_REQUEST_TEMPLATE.md
Add a reminder to the PR template to review the related Wiki page when updating API documentation.
=> PR template: Add checklist item for "API documentation"

search-server/spacewalk-search/buildconf/build-props.xml, search-server/spacewalk-search/rhn_search_daemon_dev.conf, search-server/spacewalk-search/scripts/build.properties, search-server/spacewalk-search/scripts/ivy.xml, search-server/spacewalk-search/spacewalk-search.changes, search-server/spacewalk-search/spacewalk-search.spec
Apache-commons-httpclient is not being used in the code (at least I couldn't find it). In addition, the referenced version is outdated and no longer maintained.
This PR removes apache-commons-httpclient.
No difference.
Fixes #5239  …
=> Apache commons httpclient

web/html/src/build/audit.js
I botched the merger of https://github.com/uyuni-project/uyuni/pull/5307, this fixes the issue.
No difference.
=> Improved error messages for audit ignore

testsuite/features/support/http_client.rb
Test suite: better error management for HTTP API.
No ports, Uyuni only.
=> HTTP API: Handle cases where there is an error code, but no error message

containers/proxy-httpd-image/proxy-httpd-image.changes, containers/proxy-salt-broker-image/proxy-salt-broker-image.changes, containers/proxy-squid-image/proxy-squid-image.changes, containers/proxy-ssh-image/proxy-ssh-image.changes, containers/proxy-tftpd-image/proxy-tftpd-image.changes, web/conf/rhn_web.conf
Bump SUSE Manager and Uyuni versions
For WebUI and containers (only changelog, the submission job will handle the Dockerfile)
No difference.
- No tests: visual inspection later
https://github.com/SUSE/spacewalk/issues/17553
https://github.com/SUSE/spacewalk/issues/17539 …
=> Bump SUSE Manager and Uyuni versions

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
Update the Copyright Year on the Notice Page
Fixes https://github.com/SUSE/spacewalk/issues/17843
=> Update copyright year

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
Port of https://github.com/SUSE/spacewalk/pull/17846
=> add SLED 12 SP3 bootstrap repo definition

java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerSystemCreateCommand.java, java/spacewalk-java.changes
The salt state in `autoinstall.sls` creates  `/etc/grub.d/42_uyuni_reinstall` file during autoinstallation inizialization. We need to add the information related to `self_update` if the system is connected to a proxy, retrieving the by the kickstarter profile and tree.
No difference.
- API documentation added: please review the Wiki page …
=> provisioning thought proxy should use proxy for self_update (bsc#1199036)

java/code/src/com/redhat/rhn/manager/audit/scap/xml/BenchmarkResume.java, java/spacewalk-java.changes
During scap evaluation result, mark the "profile" tag as no-required.
No difference. …
=> Set profile tag has no-mandatory in XCCDF result (bsc#1194262)

java/buildconf/apidoc/asciidoc/scripts.txt, java/buildconf/apidoc/docbook/scripts.txt, java/buildconf/apidoc/html/scripts.txt, java/buildconf/apidoc/jsp/scripts.txt, java/buildconf/apidoc/singlepage/scripts.txt, java/spacewalk-java.changes
=> add examples for HTTP over JSON API

spacewalk/package/spacewalk.spec, susemanager/bin/server-migrator.sh, susemanager/susemanager.changes
=> Server migrator 15 4

spacewalk/package/spacewalk.changes
add missing changelog entry on spacewalk.
No difference. …
=> add changelog entry for server migrator

java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java, java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java, java/spacewalk-java.changes
No difference.
- No tests: **TODO**
Tracks https://github.com/SUSE/spacewalk/issues/17858
=> Improve CLM channel cloning performance (bsc#1199523)

testsuite/features/step_definitions/retail_steps.rb
Retail testing: fix previous PR
=> Fix dynamic step syntax

containers/proxy-systemd-services/uyuni-proxy-pod.service, containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes
https://github.com/SUSE/spacewalk/issues/18267
No difference.
- No tests: 
Fixes https://github.com/SUSE/spacewalk/issues/18267
=> Bugfix: tftpd listen on udp (bsc#1200968)

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
Salt bundle did not work out of the box and some adjustments were needed. @vzhestkov took care of that, so please check with him and **do not merge** until his changes are ready for the bundle.
The following repository was used from Victor's PoC. Changes there should be hopefully soon get merged at `products`:
https://download.opensuse.org/repositories/home:/vzhestkov:/saltstack:/bundle:/next/AlmaLinux_9/
Add AlmaLinux 9, Oracle Linux 9, Red Hat Enterprise Linux 9
- Java changes
- PostgreSQL changes
For reference: Alma Linux worked fine, as it seems it trusts it's GPG key. For Oracle Linux, if the instance was installed from scratch, and you never updated, you need to trust it before onboarding salt-ssh minions by installing a package, or calling `rpm --import`, or trust it after the …
=> AlmaLinux 9, Oracle Linux 9, Red Hat Enterprise Linux 9

susemanager-utils/testing/automation/push-to-obs.sh
#5622 added the optional `-s` parameter, but then the SSH key was always passed to the other SSH script and was actually mounted for the container.
Now both things are only happeking if `-s` is present and `SSHKEY` is defined and exists.
No difference.
- No documentation needed: Internal script
- No tests: Nothing
Related: https://github.com/uyuni-project/uyuni/pull/5622 …
=> Make the SSH key really optional for push-to-obs.sh

java/spacewalk-java.changes, schema/spacewalk/susemanager-schema.changes, susemanager-utils/susemanager-sls/susemanager-sls.changes
Bugnumbers were missing in the changelogs
=> add bugnumbers to changelogs

containers/proxy-httpd-image/proxy-httpd-image.changes, containers/proxy-httpd-image/uyuni-configure.py, containers/proxy-ssh-image/proxy-ssh-image.changes, containers/proxy-ssh-image/uyuni-configure.py, containers/proxy-tftpd-image/proxy-tftpd-image.changes, containers/proxy-tftpd-image/uyuni-configure.py
https://github.com/SUSE/spacewalk/issues/17378
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/17378
=> Containers configuration scripts: python logging and configure log level

testsuite/run_sets/build_validation_retail_sle15.yml
Fix missing dash in run_sets YAML file. Thank you @vandabarata!
No difference.
=> Fix: Wrong file name in run_sets .yaml file

testsuite/features/secondary/min_timezone.feature
Change time format 
No difference.
Fixes # No issue
Tracks # https://github.com/SUSE/spacewalk/pull/18456
=> Change time format

proxy/installer/configure-proxy.sh, proxy/installer/fetch-certificate.py, proxy/installer/spacewalk-proxy-installer.changes, proxy/installer/spacewalk-proxy-installer.spec
When salt bundle is used, we need to use `/usr/lib/venv-salt-minion/bin/python` python version.
No difference.
- (OPTIONAL) …
=> Fix proxy minion -  Uyuni 5573

testsuite/features/step_definitions/command_steps.rb
Raise an exception when the wait for reposync processes timed out.
No difference.
Ports:
- Manager-4.2
=> QE: Raise an exception when the wait for reposync processes timed out

rel-eng/push-packages-to-obs.sh
fix push-packages-to-obs for the proxy-helm case.
=> CI: fix push-packages-to-obs for the proxy-helm case

testsuite/features/secondary/buildhost_docker_build_image.feature, testsuite/features/secondary/min_salt_openscap_audit.feature, testsuite/features/secondary/min_salt_user_states.feature, testsuite/features/secondary/srv_power_management_api.feature, testsuite/features/secondary/trad_cve_audit.feature, testsuite/features/step_definitions/navigation_steps.rb, testsuite/features/step_definitions/salt_steps.rb, testsuite/features/support/env.rb
Reverts uyuni-project/uyuni#1660
=> Revert "Using a new user per feature (Mandatory for parallel tests)"

containers/proxy-helm/Chart.yaml, containers/proxy-httpd-image/Dockerfile, containers/proxy-httpd-image/proxy-httpd-image.changes, containers/proxy-salt-broker-image/Dockerfile, containers/proxy-salt-broker-image/proxy-salt-broker-image.changes, containers/proxy-squid-image/Dockerfile, containers/proxy-squid-image/proxy-squid-image.changes, containers/proxy-ssh-image/Dockerfile, containers/proxy-ssh-image/proxy-ssh-image.changes, containers/proxy-tftpd-image/Dockerfile, containers/proxy-tftpd-image/proxy-tftpd-image.changes
Set MIT license for all Dockerfiles and helm chart
No difference.
- No tests: License update
Fixes #
=> Set license header

spacewalk/setup/lib/Spacewalk/Setup.pm
Fix prototype missmatch in setup
No difference.
=> Fix setup idn to ascii impl

web/README, web/README.md
Delete the old outdated readme, add a new one.
No difference.
- No documentation needed: This PR adds documentation.  
- No tests: Documentation.
Part of https://github.com/SUSE/spacewalk/issues/18162
=> Update `web` readme

testsuite/run_sets/build_validation_add_common_channels.yml, testsuite/run_sets/build_validation_init_clients.yml
Fixup for https://github.com/uyuni-project/uyuni/pull/5763
No difference.
- Manager 4.3
- Manager 4.2
=> QE: Fixup for replacing CentOS8 with Rocky8 in BV

testsuite/features/build_validation/add_custom_repositories/add_rocky8_repositories.feature
Fixes the URL of mounting the Rocky 8 image in BV.
No difference.
Before:
After: …
=> QE: BV: Fix mounting URL for Rocky 8

spacewalk/admin/mgr-monitoring-ctl, spacewalk/admin/spacewalk-admin.changes
```
$ bash ./mgr-monitoring-ctl --help
./mgr-monitoring-ctl {enable|status|disable} [pillar_data]
```
Port of https://github.com/SUSE/spacewalk/pull/18519
Adds --help
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if …
=> Add --help option to mgr-monitoring-ctl

.github/CODEOWNERS
=> Update CODEOWNERS for frontend actions

.github/CODEOWNERS
This will add missing files from QE to the CODEOWNERS file.
No difference.
Manager 4.3
Manager 4.2
=> QE: Add missing files to CODEOWNERS

.github/workflows/java-checkstyle.yml, java/buildconf/build-props.xml, java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml, java/spacewalk-java.changes, java/spacewalk-java.spec, search-server/spacewalk-search/buildconf/build-props.xml, search-server/spacewalk-search/buildconf/obs-maven-config.yaml, search-server/spacewalk-search/ivy.xml, search-server/spacewalk-search/spacewalk-search.changes, search-server/spacewalk-search/spacewalk-search.spec
Work on update java package dependencies.
- netty
- gson
- hibernate
- hibernate-types
- byte-buddy
- concurrentlinkedhashmap-lru
- spark-core
- spark-template-jade
No difference.
Fixes # …
=> Update package dependencies

spacecmd/spacecmd.changes, spacecmd/src/spacecmd/proxy.py, web/html/src/manager/proxy/container-config.tsx
$subject
No difference.
- No tests: 
Fixes #
=> Improve Proxy FQDN hint message

java/buildconf/build-props.xml, java/spacewalk-java.spec
fixed some dependencies which does not make sense and simplify the spec file
No difference.
=> prefer glassfish-activation-api and simplify specfile

susemanager-utils/testing/automation/push-to-obs.sh
We should provide a cookie_jar file which is re-used for 1 submission round to speedup the login
to OSC
No difference.
Fixes #
=> provide a re-usable cookie file

web/html/src/components/toastr/toastr.tsx
Stumbled on this while working on other things.
No difference.
=> Clean up unused test code

testsuite/documentation/optional.md
Synchronization between branches: documentation
Sibling PRs:
* 4.2: https://github.com/SUSE/spacewalk/pull/18791
* 4.3: https://github.com/SUSE/spacewalk/pull/18790
=> Synchronize code between branches (2)

testsuite/features/core/srv_create_repository.feature, testsuite/features/core/srv_disable_local_repos_off.feature
Synchronize code: remainders in core stage.
Sibling PRs:
* 4.2: https://github.com/SUSE/spacewalk/pull/18793
* 4.3: https://github.com/SUSE/spacewalk/pull/18792
=> Synchronize code between branches (3)

testsuite/features/secondary/min_ansible_control_node.feature, testsuite/features/secondary/min_custom_pkg_download_endpoint.feature, testsuite/features/secondary/min_salt_formulas.feature, testsuite/features/secondary/min_salt_install_package.feature, testsuite/features/secondary/min_salt_install_with_staging.feature, testsuite/features/secondary/min_salt_lock_packages.feature, testsuite/features/secondary/min_salt_openscap_audit.feature
Synchronize code between branches: minions.
Interesting part is on 4.2 branch.
Sibling PRs:
* 4.2:
* 4.3:
=> Synchronize code between branches (5)

testsuite/features/reposync/srv_sync_products.feature, testsuite/features/secondary/minssh_ansible_control_node.feature, testsuite/features/secondary/srv_cobbler_buildiso.feature, testsuite/features/secondary/srv_content_lifecycle.feature, testsuite/features/secondary/srv_distro_cobbler.feature, testsuite/features/secondary/srv_mainpage.feature, testsuite/features/secondary/srv_menu_filter.feature, testsuite/features/secondary/srv_payg_ssh_connection.feature, testsuite/features/secondary/srv_reportdb.feature, testsuite/features/secondary/srv_security.feature, testsuite/features/secondary/srv_users.feature, testsuite/features/step_definitions/common_steps.rb
Synchronize code between branches: server
Bug caught: in `srv_sync_products.feature`, the lines for the beta tools were not properly commented/uncommented.
Sibling PRs:
* 4.2: https://github.com/SUSE/spacewalk/pull/18833
* 4.3: https://github.com/SUSE/spacewalk/pull/18832
=> Synchronize code between branches (6)

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes
Porting of SUSE/spacewalk#18747
No difference.
Before:
After: …
=> Add python3-apipkg & python3-iniconfig to mgr_bootstrap_data.py

testsuite/README.md, testsuite/documentation/api.md, testsuite/documentation/code-coverage.md, testsuite/documentation/container-build-image.md, testsuite/documentation/cucumber-steps.md, testsuite/documentation/guidelines.md, testsuite/documentation/idempotency.md, testsuite/documentation/optional.md, testsuite/documentation/pitfalls.md, testsuite/documentation/software-components.md, testsuite/documentation/static-run.md
This will update our test suite documentation with regards to
- typos, Grammar
- fixing Markdown issues
- removing old information
- removing duplicate information
- adding new information e.g. from Confluence/spacewalk wiki that can be publicly available
Regarding the [software components](https://github.com/uyuni-project/uyuni/blob/master/testsuite/documentation/software-components.md), I was not able to find all of the gems in our test suite. For example `yaml` is only used in an outdated/deprecated file inside https://github.com/uyuni-project/uyuni/blob/master/testsuite/unit-tests/feature_names.rb so I removed it from our docs.
Another candidate is `rack` (it seems this is a runtime dependency of Capybara)
and `mime-types` where I am unsure if those gems are used at all.
Maybe someone …
=> QE: Update test suite documentation

java/code/src/com/redhat/rhn/taskomatic/task/payg/script/payg_extract_repo_data.py, java/spacewalk-java.changes
port of: https://github.com/SUSE/spacewalk/pull/18836
Fixes: https://github.com/SUSE/spacewalk/issues/18760
No difference.
Before:
After:
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation …
=> Support Pay-as-you-go new CA location for SLES15SP4 and higher

java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/utils/salt/custom/HwProfileUpdateSlsResult.java, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/salt/hardware/profileupdate.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Use mgrnet.dns_fqdns module.
This depends on https://github.com/uyuni-project/uyuni/pull/5733
No difference.
Depends on https://github.com/uyuni-project/uyuni/pull/5733
Fixes https://github.com/SUSE/spacewalk/issues/17929 …
=> Use mgrnet.dns_fqdns module

containers/proxy-helm/templates/config.yaml, containers/proxy-helm/templates/deployment.yaml, containers/proxy-helm/templates/service.yaml, containers/proxy-helm/templates/volumes.yaml
=> Fix .Release.Namespace case

containers/proxy-systemd-services/uyuni-proxy-httpd.service, containers/proxy-systemd-services/uyuni-proxy-pod.service, containers/proxy-systemd-services/uyuni-proxy-salt-broker.service, containers/proxy-systemd-services/uyuni-proxy-squid.service, containers/proxy-systemd-services/uyuni-proxy-ssh.service, containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes, containers/proxy-systemd-services/uyuni-proxy-tftpd.service
Read `/etc/sysconfig/proxy` in proxy systemd container sercices.
No difference.
- No tests: No automated test
Fixes https://github.com/SUSE/spacewalk/issues/18828
=> Use system HTTP proxy settings for containers

java/code/src/com/redhat/rhn/common/db/datasource/BaseMode.java, java/code/src/com/redhat/rhn/common/db/datasource/CachedStatement.java, java/code/src/com/redhat/rhn/common/db/datasource/Elaborator.java, java/code/src/com/redhat/rhn/common/db/datasource/ModeElaborator.java, java/code/src/com/redhat/rhn/common/db/datasource/ModeFactory.java, java/code/src/com/redhat/rhn/common/db/datasource/SelectMode.java, java/code/src/com/redhat/rhn/common/hibernate/AbstractConnectionManager.java, java/code/src/com/redhat/rhn/frontend/action/CSVDownloadAction.java, java/code/src/com/suse/manager/webui/websocket/Notification.java, java/spacewalk-java.changes
Fixes crash when filtering in systems lists with multiple users connected.
No difference.
- No tests: requires multiple users and some patience to reproduce
Fixes https://github.com/SUSE/spacewalk/issues/18898, https://github.com/SUSE/spacewalk/issues/18891 and https://github.com/uyuni-project/uyuni/issues/5890 …
=> Systems list crash

spacewalk/certs-tools/spacewalk-certs-tools.changes
We got an L3 for an already fixes issue without bug. So adding the bugnumber to the changelog
Port of https://github.com/SUSE/spacewalk/pull/19069
=> add new bugnumber for fixed issue

python/spacewalk/rhn-conf/rhn_server_satellite.conf, python/spacewalk/satellite_tools/download.py, python/spacewalk/satellite_tools/repo_plugins/yum_src.py, python/spacewalk/spacewalk-backend.changes
Reverts uyuni-project/uyuni#5911
=> Revert "add logspec param to urlgrabber"

susemanager-sync-data/additional_products.json
adding additional OES2023-SLE-Module-Legacy15 channels
No difference.
- No tests
=> add OES2023-SLE-Module-Legacy15 channels

.github/workflows/check_translations.yml
This adds back the need translation check but instead of failing it adds the "needs_translation" label.
No difference.
- 
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/18640
=> Add check translations

testsuite/features/secondary/minkvm_guests.feature
This PR fixes a test in KVM virtualization feature.
Ports:
* 4.2: SUSE/spacewalk#19088
* 4.3: SUSE/spacewalk#19087
=> Use correct event label

testsuite/features/step_definitions/command_steps.rb
Fixing a mistake in OOM detection
Tracks # 
4.2
4.3
=> Fixing OOM detection

testsuite/documentation/container-build-image.md, testsuite/documentation/cucumber-steps.md, testsuite/documentation/guidelines.md, testsuite/documentation/idempotency.md, testsuite/documentation/optional.md, testsuite/documentation/pitfalls.md, testsuite/documentation/software-components.md, testsuite/documentation/static-run.md
Synchronize code between branches: test suite documentation.
This PR also does the following changes:
* do not advertise minitest assertions anymore
* shorten or remove old rantings about bad code
Sibling PRs:
* 4.2: SUSE/spacewalk#19149
* 4.3: SUSE/spacewalk#19150
=> Synchronize code between branches (7)

testsuite/features/step_definitions/command_steps.rb
Removes the flakiness of having to check for --allow-vendor-change in the zypper logs
https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1726/
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18733
4.2 https://github.com/SUSE/spacewalk/pull/19206
4.3 https://github.com/SUSE/spacewalk/pull/19207 …
=> QE: Add validation for rotate log file name

testsuite/features/reposync/srv_add_rocky8_repositories.feature, testsuite/features/reposync/srv_sync_channels.feature
Fixup of https://github.com/uyuni-project/uyuni/pull/5831
- Fixes https://github.com/SUSE/spacewalk/issues/19271
=> QE: Fixups for Rocky 8

spacecmd/po/de.po, spacecmd/po/es.po, spacecmd/po/it.po, spacecmd/po/ja.po, spacecmd/po/ko.po, spacecmd/po/pt.po, spacecmd/po/pt_BR.po, spacecmd/po/ru.po, spacecmd/po/si.po, spacecmd/po/sk.po, spacecmd/po/spacecmd.pot, spacecmd/po/zh_CN.po, spacecmd/po/zh_HK.po, spacecmd/po/zh_TW.po
=> update strings for translations in spacecmd

testsuite/features/core/allcli_sanity.feature, testsuite/features/core/proxy_register_as_minion_with_script.feature, testsuite/features/reposync/srv_enable_sync_products.feature, testsuite/features/secondary/buildhost_osimage_build_image.feature, testsuite/features/secondary/min_docker_api.feature, testsuite/features/secondary/srv_virtual_host_manager.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/common_steps.rb, testsuite/features/support/constants.rb, testsuite/features/support/env.rb
This PR add changes to run the testsuite on AWS with a classic SUMA deployment ( using sles as server and proxy ) : 
- create a tag pair : `skip_if_cloud` and `cloud` to skip specifics scenario ( some docker scenarios, virtual host scenario, ...)
- change the way to select target when running remote commands
- add constants to manage repository names when added using SCC activation
- add cloud repositories synchronization to migrate sles minion and client
No difference.
- Add compatibility with AWS provider
https://github.com/uyuni-project/sumaform/pull/1126
https://github.com/SUSE/susemanager-ci/pull/612
https://github.com/SUSE/spacewalk/issues/17243
=> Aws cutomization rebase

susemanager/src/mgr_bootstrap_data.py
By accident a line in the bootstrap data file was replaces with invalid data
No difference.
Follow up on https://github.com/uyuni-project/uyuni/pull/6064
=> fix bootstrap data typo

testsuite/features/profiles/Makefile, testsuite/features/profiles/cloud_aws/Docker/Dockerfile, testsuite/features/profiles/cloud_aws/Docker/authprofile/Dockerfile, testsuite/features/profiles/cloud_aws/Docker/authprofile/sles15sp4.repo, testsuite/features/profiles/cloud_aws/Docker/serverhost/Dockerfile, testsuite/features/profiles/cloud_aws/Docker/serverhost/sles15sp4.repo, testsuite/features/profiles/cloud_aws/Docker/sles15sp4.repo, testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS6_42/config.xml, testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS6_head/config.xml, testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_41/config.xml, testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_42/config.xml, testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_head/config.xml, testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_uyuni/config.xml
The SUMA Team need to change the cloud environment. With this the mirror name changed.
Use the new mirror name from now on
No difference.
=> New aws env

spacewalk/admin/spacewalk-admin.changes, spacewalk/admin/uyuni-check-database.service
Add changelog to https://github.com/uyuni-project/uyuni/pull/6057
=> Added network-online target to After

web/html/javascript/login.js, web/html/src/core/debug/index.ts
Fix minor issues in development debugging utilities.
No difference.
=> Fix debugging utilities

java/code/src/com/redhat/rhn/common/conf/Config.java, java/code/src/com/redhat/rhn/common/localization/LocalizationService.java, java/code/src/com/redhat/rhn/common/util/FileUtils.java, java/code/src/com/redhat/rhn/domain/server/virtualhostmanager/VirtualHostManagerFactory.java, java/code/src/com/redhat/rhn/frontend/action/audit/AuditMachineAction.java, java/code/src/com/redhat/rhn/frontend/action/channel/ssm/BaseSubscribeAction.java, java/code/src/com/redhat/rhn/frontend/action/common/TinyUrlAction.java, java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartHelper.java, java/code/src/com/redhat/rhn/frontend/action/kickstart/RenderKickstartFileAction.java, java/code/src/com/redhat/rhn/frontend/action/systems/audit/ScapDownloadAction.java, java/code/src/com/redhat/rhn/frontend/action/user/AdminUserEditAction.java, java/code/src/com/redhat/rhn/frontend/servlets/DumpFilter.java, java/code/src/com/redhat/rhn/manager/audit/scap/file/ScapResultFile.java, java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/code/src/com/suse/manager/utils/SaltKeyUtils.java, java/code/src/com/suse/manager/webui/controllers/DownloadController.java, java/code/src/com/suse/manager/webui/controllers/FrontendLogController.java, java/code/src/com/suse/manager/webui/controllers/SystemsController.java, java/code/src/com/suse/manager/webui/controllers/virtualization/VirtualGuestsController.java, java/code/src/com/suse/manager/webui/utils/LoginHelper.java
Sanitize all user input passed to logs to avoid vulnerabilities.
No difference.
- No tests: Logging changes
Fixes #
=> Fix log vulnerabilities reported by sonarcloud

susemanager-sync-data/channel_families.json, susemanager-sync-data/susemanager-sync-data.changes
SLES15 SP3 get LTSS beginning of next year. Declare the channel families for it.
Port of https://github.com/SUSE/spacewalk/pull/19482
=> add SLES15 SP3 LTSS

rel-eng/packages/spacewalk-setup, spacewalk/setup/spacewalk-setup.changes, spacewalk/setup/spacewalk-setup.spec
=> Backport of #6133 and tagging

java/code/src/com/redhat/rhn/domain/action/ActionFormatter.java, java/code/src/com/redhat/rhn/domain/action/salt/ApplyStatesAction.java, java/spacewalk-java.changes
We have a special formatter for "State Apply" Actions. The result of Package and Errata actions are similar, but no formatter is applied.
This PR uses the same formatter for all state apply results.
No difference.
Before:
After:
- No tests: **UI only**
Fixes https://github.com/SUSE/spacewalk/issues/19089
Tracks https://github.com/SUSE/spacewalk/pull/19523 https://github.com/SUSE/spacewalk/pull/19524 …
=> Format results for package and errata actions similar to state apply actions

search-server/spacewalk-search/spacewalk-search.changes
Add changelog for search server since there is no other change than java `toString()` cleanup
No difference.
- No tests: changelog
Fixes #
=> Add search changelog

python/spacewalk/server/taskomatic.py, python/spacewalk/spacewalk-backend.changes
fixes https://github.com/uyuni-project/uyuni/issues/6193
No difference.
Before:
After:
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API …
=> Correct insert statement to reprocess system overview list

python/spacewalk/server/taskomatic.py, python/spacewalk/spacewalk-backend.changes, python/spacewalk/spacewalk-backend.spec, rel-eng/packages/spacewalk-backend
Backport #6199 and tagging to master
=> Backport #6199 and tagging to master

testsuite/features/build_validation/core/allcli_sanity.feature
ceos7 -> centos7
Ports:
* 4.3:
* 4.2:
=> Fixed minor leftover

susemanager-sync-data/additional_products.json, susemanager-sync-data/susemanager-sync-data.changes
remove version from product names as they are held separate
No difference.
Fixes #
=> remove version from product name

java/code/src/com/redhat/rhn/domain/action/ActionFactory.java, java/code/src/com/redhat/rhn/domain/kickstart/KickstartCommandName.java, java/code/src/com/redhat/rhn/domain/kickstart/KickstartData.java, java/code/src/com/redhat/rhn/domain/kickstart/KickstartDefaults.java, java/code/src/com/redhat/rhn/domain/kickstart/KickstartFactory.java, java/code/src/com/redhat/rhn/domain/kickstart/KickstartRawData.java, java/code/src/com/redhat/rhn/domain/kickstart/KickstartScript.java, java/code/src/com/redhat/rhn/domain/kickstart/builder/KickstartBuilder.java, java/code/src/com/redhat/rhn/domain/kickstart/builder/test/KickstartBuilderTest.java, java/code/src/com/redhat/rhn/domain/kickstart/test/KickstartCommandNameTest.java, java/code/src/com/redhat/rhn/domain/kickstart/test/KickstartDataTest.java, java/code/src/com/redhat/rhn/domain/kickstart/test/KickstartableTreeTest.java, java/code/src/com/redhat/rhn/frontend/action/kickstart/BaseKickstartEditAction.java, java/code/src/com/redhat/rhn/frontend/action/kickstart/CreateProfileWizardAction.java, java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartHelper.java, java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartSoftwareEditAction.java, java/code/src/com/redhat/rhn/frontend/action/kickstart/SystemDetailsEditAction.java, java/code/src/com/redhat/rhn/frontend/action/kickstart/test/CreateProfileWizardTest.java, java/code/src/com/redhat/rhn/frontend/struts/wizard/RhnWizardAction.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/profile/ProfileHandler.java, java/code/src/com/redhat/rhn/manager/kickstart/BaseKickstartCommand.java, java/code/src/com/redhat/rhn/manager/kickstart/KickstartFormatter.java, java/code/src/com/redhat/rhn/manager/kickstart/KickstartWizardHelper.java, java/code/src/com/redhat/rhn/manager/kickstart/test/KickstartScheduleCommandTest.java, java/code/src/com/redhat/rhn/manager/kickstart/test/KickstartSessionCommandCreateTest.java, java/code/src/com/redhat/rhn/manager/kickstart/tree/TreeCreateOperation.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
Fixes sonarcloud warning in files touched by PR #6186 . Created a separate PR since the fixes are quite big and would probably need more review.
No difference.
Fixes # …
=> Sonar fixes

python/spacewalk/satellite_tools/repo_plugins/yum_src.py, python/spacewalk/spacewalk-backend.changes
Reverts uyuni-project/uyuni#6246
=> Revert "Add 'octet-stream' to accepted mirrorlist content-types"

python/spacewalk/satellite_tools/repo_plugins/yum_src.py, python/spacewalk/spacewalk-backend.changes, python/spacewalk/spacewalk-backend.spec, rel-eng/packages/spacewalk-backend
=> Backport of #6254 and tagging

testsuite/features/build_validation/smoke_tests/smoke_tests.template, testsuite/features/secondary/allcli_config_channel.feature, testsuite/features/secondary/allcli_overview_systems_details.feature, testsuite/features/secondary/min_action_chain.feature, testsuite/features/secondary/min_bootstrap_api.feature, testsuite/features/secondary/min_cve_audit.feature, testsuite/features/secondary/min_empty_system_profiles.feature, testsuite/features/secondary/minssh_action_chain.feature, testsuite/features/secondary/minssh_bootstrap_api.feature
Fix mistakes login/logout from API Handler
No difference.
Ports:
- Manager-4.3
=> QE: Fix mistakes login/logout from API Handler

java/code/src/com/redhat/rhn/domain/errata/ErrataFactory.java, java/code/src/com/redhat/rhn/frontend/security/RedirectServlet.java, java/code/src/com/redhat/rhn/frontend/servlets/OvalServlet.java, java/code/src/com/redhat/rhn/frontend/servlets/ResourceReloadServlet.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/XmlRpcServlet.java, java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java
Addresses SonarCloud issues for servlets
No difference.
Fixes #
=> Fix sonarcloud issues in servlets

spacecmd/spacecmd.changes
=> correct changelog entry for default port

spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb, spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes
* Fixes password generation on non-UTF-8 locales.
* Uses an approach less wasteful of random data.
No difference.
- No tests: trivial?
Fixes #6247
=> Fix password generation in uyuni-setup-reportdb

.github/workflows/build_containers.yml
=> TEST more containers

.github/workflows/build_containers.yml
=> TEST continers again.sorry

.github/workflows/build_containers.yml
This was a test PR for testing github actions. Tests have been finished and I am removing the code.
Sorry for the noise.
=> Revert "TEST continers again.sorry"

.github/workflows/build_containers.yml
Reverts uyuni-project/uyuni#6338
This was a test PR for testing github actions. Tests have been finished and I am removing the code.
Sorry for the noise.
=> Revert "TEST more containers"

.github/workflows/build_containers.yml, .github/workflows/test_actions_docker.yml
Reverts uyuni-project/uyuni#6337
This was a test PR for testing github actions. Tests have been finished and I am removing the code.
Sorry for the noise.
=> Revert "TEST"

.github/workflows/test_actions_docker.yml
=> TEST pull docker container from github action

.github/workflows/test_actions_docker.yml
=> TEST . ignore

.github/workflows/test_actions_docker.yml
Reverts uyuni-project/uyuni#6360
=> Revert "TEST . ignore"

testsuite/features/step_definitions/common_steps.rb
Another channel name change
No difference.
Additional fix for https://github.com/uyuni-project/uyuni/pull/6380
=> fix check of channel label

java/code/src/com/suse/manager/webui/controllers/SystemsController.java, java/spacewalk-java.changes
Fixes the data in physical systems list page.
No difference.
- No tests: would require cucumber tests
Fixes https://github.com/uyuni-project/uyuni/issues/6269
=> Properly filter for physical systems

susemanager/src/mgr-create-bootstrap-repo, susemanager/susemanager.changes, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
Add client tools repo definition for Uyuni Client Tools to spacewalk-common-channels.
Bootstrap repo definitions are not needed but a fix for mgr-create-bootstrap-repo to handle Uyuni-Client-Tools with SUSE products which require a subscription.
No difference.
- Part of big SLE-Micro doc update
Requires https://github.com/uyuni-project/uyuni/pull/6121
Fixes https://github.com/SUSE/spacewalk/issues/19389
Tracks https://github.com/SUSE/spacewalk/pull/19527 …
=> Uyuni sle micro client tools

susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
`transactional-update.conf` file was unconditionally provisioned even for non-transactional systems. Move it under transactional jinja block.
No difference.
Fixes #
If you need to …
=> Move transactional-update conf file under transactional check

susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes, susemanager-utils/supportutils-plugin-susemanager/susemanager
Update suse manager support config plugin to also extract the number of salt events to be procesed.
No difference.
Before:
After:
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the …
=> update susemanager plugin to export the number of pending salt events

containers/proxy-helm/proxy-helm.changes, containers/proxy-helm/templates/_helpers.tpl, containers/proxy-helm/templates/deployment.yaml, containers/proxy-helm/values.yaml, containers/proxy-systemd-services/proxy.sh, containers/proxy-systemd-services/uyuni-proxy-httpd.service, containers/proxy-systemd-services/uyuni-proxy-salt-broker.service, containers/proxy-systemd-services/uyuni-proxy-services.config, containers/proxy-systemd-services/uyuni-proxy-squid.service, containers/proxy-systemd-services/uyuni-proxy-ssh.service, containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes, containers/proxy-systemd-services/uyuni-proxy-tftpd.service
Allow using a container image from a different registry path for 
* Helm charts
* systemd services
No difference.
- (OPTIONAL) …
=> Allow using a container image from a different registry path

testsuite/run_sets/build_validation_init_clients.yml
Follow-up of  #6395
Ports:
* 4.2: https://github.com/SUSE/spacewalk/pull/20115
* 4.3: https://github.com/SUSE/spacewalk/pull/20116
=> Finish removing sle15sp0

java/buildconf/ivy/ivy-suse.xml
See title
No difference.
Fixes #
=> Bump salt-net-api ivy dependency to 0.21.0 to match repos

java/code/src/com/redhat/rhn/GlobalInstanceHolder.java, java/code/src/com/redhat/rhn/common/db/ResetPasswordFactory.java, java/code/src/com/redhat/rhn/common/messaging/MessageQueue.java, java/code/src/com/redhat/rhn/common/util/RecurringEventPicker.java, java/code/src/com/redhat/rhn/domain/action/salt/build/ImageBuildActionFormatter.java, java/code/src/com/redhat/rhn/domain/action/salt/inspect/ImageInspectActionFormatter.java, java/code/src/com/redhat/rhn/domain/common/ManagerInfoFactory.java, java/code/src/com/redhat/rhn/domain/common/SatConfigFactory.java, java/code/src/com/redhat/rhn/domain/product/SUSEProductSet.java, java/code/src/com/redhat/rhn/frontend/action/channel/manage/AddRedHatErrataAction.java, java/code/src/com/redhat/rhn/frontend/taglibs/FormatDateTag.java, java/code/src/com/redhat/rhn/frontend/taglibs/list/DataSetManipulator.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/HandlerFactory.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/test/ChannelSoftwareHandlerTest.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/org/OrgHandler.java, java/code/src/com/redhat/rhn/manager/audit/CVEAuditManager.java, java/code/src/com/redhat/rhn/manager/errata/cache/ErrataCacheManager.java, java/code/src/com/redhat/rhn/taskomatic/core/SchedulerKernel.java, java/code/src/com/redhat/rhn/taskomatic/task/MinionActionChainCleanup.java, java/code/src/com/redhat/rhn/taskomatic/task/errata/ErrataQueueWorker.java, java/code/src/com/redhat/rhn/testing/RhnBaseTestCase.java, java/code/src/com/redhat/rhn/webapp/RhnServletListener.java, java/code/src/com/suse/manager/reactor/messaging/ChannelsChangedEventMessageAction.java, java/code/src/com/suse/manager/reactor/messaging/SystemIdGenerateEventMessageAction.java, java/code/src/com/suse/manager/reactor/messaging/test/MinionActionCleanupTest.java, java/code/src/com/suse/manager/webui/controllers/maintenance/MaintenanceScheduleController.java, java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java, java/code/src/com/suse/manager/webui/utils/MinionActionUtils.java, java/code/src/com/suse/manager/webui/utils/test/MinionActionUtilsTest.java
See title
No difference.
Fixes #
=> Remove unused private fields

README.md
Link to the Development Guides at the README
No difference.
- No tests: Text
None
=> Link to the Development Guides at the README

testsuite/features/secondary/min_cve_audit.feature
This will add a small check if the required patch is found in the step where the patch should be applied before selecting it.
No difference.                           
- fixes https://github.com/SUSE/spacewalk/issues/20190
- Manager 4.3: https://github.com/SUSE/spacewalk/pull/20196
- Manager 4.2: https://github.com/SUSE/spacewalk/pull/20197
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uy
uni/wiki/Contributing#uyuni-projectuyuni-repository …
=> QE: Add small checker to CVE audit scenario

susemanager-utils/susemanager-sls/salt/bootstrap/transactional_update.conf, susemanager-utils/susemanager-sls/susemanager-sls.changes
Add missing transactional_update.conf
No difference.
Fixes #
=> Add missing transactional_update.conf

susemanager-utils/susemanager-sls/salt/distupgrade/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes
Support SLE Micro migration
No difference. …
=> Support SLE Micro migration (bsc#1205011)

client/rhel/spacewalk-client-tools/spacewalk-client-tools.spec, proxy/proxy/spacewalk-proxy.spec, python/spacewalk/spacewalk-backend.spec, schema/spacewalk/susemanager-schema.spec, spacecmd/spacecmd.spec, spacewalk/certs-tools/spacewalk-certs-tools.spec, susemanager/susemanager.spec, utils/spacewalk-utils.spec
Added "make" as build requirement for some packages.
No difference.
=> Clarified build requirements

java/code/src/com/redhat/rhn/domain/server/MinionServer.java, java/code/src/com/redhat/rhn/domain/server/Server.java, java/code/src/com/redhat/rhn/domain/server/ServerConstants.java, java/spacewalk-java.changes, susemanager-utils/susemanager-sls/salt-ssh/preflight.sh, susemanager-utils/susemanager-sls/salt/bootstrap/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes, susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
openSUSE Leap Micro 5.3 and openSUE MicroOS as clients
Binaries for testing at https://build.opensuse.org/project/show/home:juliogonzalezgil:branches:systemsmanagement:Uyuni:Master
**openSUSE Leap Micro 5.3**
- https://github.com/SUSE/spacewalk/issues/20349: openSUSE Leap Micro, does not bootstrap without adding on top of `/usr/share/susemanager/salt/bootstrap/init.sls` the following
```
include:
- util.syncstates
```
- https://github.com/SUSE/spacewalk/issues/20278: Thew new minion needs an extra reboot for the beacon for reboots to work normally
- https://github.com/SUSE/spacewalk/issues/20306#issuecomment-1411971113: the formula to configure locale is broken (and not sure about others)
- https://github.com/uyuni-project/uyuni/issues/6560 Seems `pkg.*` on salt does not work over …
=> openSUSE Leap Micro 5.3 and openSUSE MicroOS as clients

java/code/src/com/redhat/rhn/frontend/dto/kickstart/KickstartableTreeDetail.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/tree/KickstartTreeHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/tree/test/KickstartTreeHandlerTest.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/KickstartTreeDetailSerializer.java, java/spacewalk-java.changes
Port of https://github.com/SUSE/spacewalk/pull/20472/
=> Adds API methods(create/update) which accepts kernel and post kernel options for kickstart distributions

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes
Add SLE 15 SP5 (with its different flavors, SAP and others) as a supported client to Uyuni.
No difference.
- Documentation issue was created: https://github.com/uyuni-project/uyuni-docs/pull/2031
No links
=> Add SLE 15 SP5 as a supported client to Uyuni

spacewalk/admin/spacewalk-admin.changes, spacewalk/admin/spacewalk-admin.spec
- Replaced apache2.service with httpd.service for RHEL systems.
- Minor spec file changes.
No difference.
=> Readded httpd variant for Enterprise Linux.

web/html/src/manager/proxy/container-config.tsx
Fix the doc link for proxy config.
No difference.
- No tests: **nothing to test**
Fixes # https://github.com/SUSE/spacewalk/issues/19534 …
=> Fix the doc link for proxy config

java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java
More logging useful when something goes wrong
No difference.
- No tests: **only logging**
=> add more debug logging for UbuntuErrataManager

.github/scripts/test_covering_pr.js, .github/workflows/test-covering-pr.yml
Summarizing the list of suggested tests using details html tag.
Thank you very much @Etheryte for that suggestion!
**Example about how it works:**
<details><summary>Suggested tests to cover this Pull Request</summary><ul><li>test 1<li>test 2<li>test 3<li>test 4<li>test 5</ul></details><suggested_tests>
No difference.
- No tests
No Ports …
=> Summarizing the list of suggested tests using details html tag.

testsuite/features/build_validation/reposync/srv_sync_all_products.feature
Small fixup for the BV SLE Micro tests
No difference.
- Manager 4.3: https://github.com/SUSE/spacewalk/pull/20648
=> QE: fix BV SLE Micro product sync

java/code/src/com/redhat/rhn/taskomatic/task/SystemProfileRefreshTask.java
Fix casing issue found by sonarcloud
No difference.
Port of https://github.com/SUSE/spacewalk/pull/20597
=> do sleep calculation as long

susemanager/bin/mgr-setup, susemanager/susemanager.changes
Replace apache group to root for Enterprise Linux
No difference.
Fixes #
=> Replace apache group to root for Enterprise Linux

schema/reportdb/uyuni-reportdb-schema.changes, schema/reportdb/uyuni-reportdb-schema.spec
Require perl-File-Find for Enterprise Linux
No difference.
Build tested on copr for el9 and Leap 15.4
=> Require perl-File-Find for Enterprise Linux

testsuite/run_sets/build_validation_init_clients.yml
Port of https://github.com/SUSE/spacewalk/pull/20703
=> Bootstrap SLE micro clients

containers/server-systemd-services/uyuni-server.service
=> fix style and timeout

testsuite/features/support/commonlib.rb, testsuite/features/support/constants.rb
Complete list of channels to sync by OS and remove required channel for migration
No difference.
Fixes #
Tracks #
4.2 https://github.com/SUSE/spacewalk/pull/20706
4.3 https://github.com/SUSE/spacewalk/pull/20705 …
=> CI: Correct the channels to sync

SECURITY.md
This patch is adding `SECURITY.md` as a security policy for the repository. Please let me know if you think any additional information should be added.
No difference.
- No tests.
No links.
=> Create a security policy (SECURITY.md)

.github/workflows/build_containers.yml
fix container build
No difference.
- No tests
=> CI: Acceptance tests at PR v2: fix container context

testsuite/Rakefile, testsuite/run_sets/build_validation_add_non_MU_channels.yml, testsuite/run_sets/build_validation_add_non_MU_repositories/build_validation_alma9_minion_build_clm.yml, testsuite/run_sets/build_validation_add_non_MU_repositories/build_validation_centos7_minion_add_iso.yml, testsuite/run_sets/build_validation_add_non_MU_repositories/build_validation_liberty9_minion_build_clm.yml, testsuite/run_sets/build_validation_add_non_MU_repositories/build_validation_oracle9_minion_build_clm.yml, testsuite/run_sets/build_validation_add_non_MU_repositories/build_validation_rocky8_minion_add_iso_and_build_clm.yml, testsuite/run_sets/build_validation_add_non_MU_repositories/build_validation_rocky9_minion_build_clm.yml, testsuite/run_sets/build_validation_add_non_MU_repositories/build_validation_ubuntu1804_minion_add_common_repositories.yml
Create independent run set for each non MU minion. This run-set will then be call by BV parallel pipeline.
Backport : https://github.com/SUSE/spacewalk/pull/20862
No difference.
Before:
After:
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documen …
=> Add support to BV parallel non MU specific run set

.github/workflows/test_all_in_one.yml
Adds new user `elariekerboull` to the list of beta users for acceptance tests on PR following instructions from https://github.com/uyuni-project/uyuni/wiki/Running-Acceptance-Tests-at-PR#enabling-it
No difference. …
=> Add new user to test_all_in_one.yml

python/uyuni/uyuni-common-libs.changes, python/uyuni/uyuni-common-libs.spec
Use versioned Python during packaging or rpm creation might fail with strict options.
No difference.
Fixes #
=> Uyuni common libs

testsuite/features/secondary/minkvm_guests.feature, testsuite/features/secondary/proxy_cobbler_pxeboot.feature, testsuite/features/secondary/srv_cobbler_buildiso.feature, testsuite/features/secondary/srv_cobbler_distro.feature, testsuite/features/secondary/srv_cobbler_profile.feature, testsuite/features/secondary/srv_cobbler_sync.feature, testsuite/features/secondary/srv_power_management.feature, testsuite/features/secondary/srv_power_management_redfish.feature, testsuite/features/step_definitions/cobbler_steps.rb, testsuite/features/step_definitions/command_steps.rb, testsuite/features/support/cobbler_test.rb
Refactor Cobbler tests
The main scope of this PR is to closely monitor Cobbler logs in features involving it in order to detect error messages and bugs that could happen but are not presently detected by the testsuite.
`/etc/cobbler/logging_config.conf` is edited to include a new parallel log file including debug level logs.
During each related feature, ~~the cobbler log is tailed to a different file which is then grepped for errors and removed.~~ the debug log is removed, cobblerd restarted then the log checked at the ed of the feature.
If errors are detected, a copy of the current debug log is kept with a timestamp to help for debugging purposes.
This PR also brings some changes towards ruby code related to cobbler to resolve some Rubocops warnings mostly regarding to formatting. 
No …
=> QE: Cobbler log parsing improvement

.github/workflows/test_all_in_one.yml
Add myself to the beta users of the new PR test @jordimassaguerpla implemented.
No difference.
Before:
After:
- (OPTIONAL) …
=> CI: Add dgedon to beta users

.github/workflows/test_all_in_one_common.yml
See title
No difference.
- No tests: not applicable
=> Add all-in-one Cucumber workflow user

testsuite/features/reposync/srv_sync_channels.feature, testsuite/features/reposync/srv_sync_products.feature
We caught the issue regarding the autoselection of the Server Applications Module.
The root cause was in the previous feature, where we are synchronizing via mgr-sync command the channel of the SUMA client tools. That action, automatically synchronize not only the client tools but all the inverted tree of dependencies for that channel, synchronizing its parents. So, when we tried to select the product in the next feature, in fact the selection was disabled, and so it prevented the automatically selection of the unrelated sub-product of SLES15 SP4 on regard of SUMA client tools, but at same time, it was one of the recommended products and so the scenario failed.
To fix it, we removed the scenario synchronizing the client tools in the previous feature, and rely only in the synchronization …
=> QE: Diverge product sync for SLES15 SP4

.github/workflows/test_all_in_one_p1.yml, .github/workflows/test_all_in_one_p2.yml, .github/workflows/test_all_in_one_p3.yml, .github/workflows/test_all_in_one_p4.yml, .github/workflows/test_all_in_one_p5.yml, .github/workflows/test_all_in_one_parallel_sets.yml
CI: extracts common code to a strategy matrix. 
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/21024
=> CI: Acceptance tests at PR v2: refactor tests

spacewalk/setup/lib/Spacewalk/Setup.pm, spacewalk/setup/spacewalk-setup.changes
read and persist report_db_sslrootcert value
No difference. …
=> read and persist report_db_sslrootcert value

client/tools/mgr-cfg/mgr-cfg.changes
**fix missing changelog entry**
No difference.
Before:
After:
- No documentation needed: **changelog fix only**
- No tests: **fix missing changelog entry**
Tracks https://github.com/SUSE/spacewalk/issues/20653
=> fix missing changelog entry

containers/proxy-tftpd-image/proxy-tftpd-image.changes, containers/proxy-tftpd-image/tftp_wrapper.py
This PR modifies fbtftp on containerized branch server to filter Cobbler menus on the fly and remove entries relevant to other branches.
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any …
=> Show only cobbler menu entries for given branch

susemanager/bin/mgr-setup, susemanager/susemanager.changes
See title
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/16847
=> Adjust product name in setup script output

java/code/src/com/redhat/rhn/manager/audit/ScapManager.java, java/spacewalk-java.changes
Attempt to fix https://sonarcloud.io/project/issues?resolved=false&types=VULNERABILITY&id=uyuni-project_uyuni&open=AYMYhZMr5TQr2KFg-0lU&tab=code
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/20639 …
=> Secure processing in ScapManager

spacewalk/setup/spacewalk-setup.spec
Fix build in IBS for SUSE distro
No difference.
=> add BuildRequires to tomcat to know about tomcat owned directories

susemanager-utils/susemanager-sls/salt/services/kiwi-image-server.sls, testsuite/features/step_definitions/retail_steps.rb
Repositories were renamed
No difference.
Before:
After: …
=> fix repo enablement

java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java, java/code/src/com/suse/manager/utils/SaltUtils.java, java/spacewalk-java.changes
Fix missing setting of the primary FQDN.
Additionally made some code cleanups
No difference.
Fix https://github.com/SUSE/spacewalk/issues/20981
Tracks https://github.com/SUSE/spacewalk/pull/21313 …
=> Fix hardware refresh issues

java/code/src/com/redhat/rhn/frontend/events/SsmPowerManagementAction.java, java/code/webapp/WEB-INF/struts-config.xml, java/spacewalk-java.changes, spacecmd/spacecmd.changes, spacecmd/src/spacecmd/misc.py
Fixes various minor bugs.
- Fixes https://github.com/SUSE/spacewalk/issues/21095
- Fixes https://github.com/SUSE/spacewalk/issues/20576
=> Minor Uyuni bugfixes

testsuite/features/reposync/srv_sync_products-reference.feature, testsuite/run_sets/reposync-reference.yml
add  special reposync task for reference server setup
No difference.
=> special reposync task for reference setups

java/code/src/com/redhat/rhn/common/util/CryptHelper.java, java/code/src/com/redhat/rhn/domain/token/ActivationKeyFactory.java, java/code/src/com/redhat/rhn/manager/action/MinionActionManager.java, java/code/src/com/redhat/rhn/manager/system/SystemManager.java, java/code/src/com/redhat/rhn/taskomatic/task/checkin/SystemCheckinUtils.java, java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java
Use secure random number generators in Java code.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/21411
=> Use secure randoms where needed

java/code/src/com/redhat/rhn/common/util/CryptHelper.java, java/code/src/com/redhat/rhn/domain/token/ActivationKeyFactory.java, java/code/src/com/redhat/rhn/manager/action/MinionActionManager.java, java/code/src/com/redhat/rhn/manager/system/SystemManager.java, java/code/src/com/redhat/rhn/taskomatic/task/checkin/SystemCheckinUtils.java, java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java
Follow up PR for https://github.com/uyuni-project/uyuni/pull/6999
No difference.
Fixes #
=> Fix for reportdb username generation

testsuite/features/secondary/min_salt_formulas.feature, testsuite/features/secondary/min_salt_formulas_advanced.feature, testsuite/podman_runner/12_run_salt_sle_minion.sh
CI: fix test formulas to increase test coverage of secondary features
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/20959
=> CI: Acceptance tests at PR v2: fix formulas

web/html/src/branding/css/base/theme.less, web/html/src/branding/css/uyuni/header.less
Followup to https://github.com/uyuni-project/uyuni/pull/6604, missed a small UI bug in the previous PR.
Bugfix.
- No tests: UI bugfix.
Followup to https://github.com/uyuni-project/uyuni/pull/6604
=> Fix SPA hooks header layout shift

java/code/src/com/redhat/rhn/frontend/action/common/DownloadFile.java
Remove a regex that was not really needed in `DownloadFile`. Also cleaned the easy sonarcloud issues in that class
No difference.
Fixes https://sonarcloud.io/project/issues?open=AYgGd19c95sNVT4b4G0t&id=uyuni-project_uyuni …
=> Don't use user input as a regular expression

testsuite/features/init_clients/container_sle_ssh_minion.feature, testsuite/features/secondary/allcli_action_chain.feature, testsuite/features/secondary/min_action_chain.feature, testsuite/features/secondary/minssh_action_chain.feature, testsuite/features/secondary/srv_restart.feature
Fix action chain secondary test feature for CI.
=> Fix action chain secondary feature

web/html/src/manager/login/uyuni/login.tsx
**This PR adds labels to the Login field of the sign in page. Previously, the sign in fields of Uyuni had only placeholder texts and no labels. This is an accessibility problem because the label tag is crucial, as it ensures that the form field is associated with its corresponding label, making it easier for assistive technologies and users with disabilities to understand the purpose of the input field. The placeholder texts should not be used in place of a proper label.**
Before:
After:
- No …
=> Add form labels to Login fields

testsuite/features/support/twopence_init.rb
Remove warning not applying to BV
=> Remove warning not applying to BV

testsuite/features/build_validation/core/allcli_sanity.feature, testsuite/features/build_validation/create_bootstrap_repositories/srv_create_bootstrap_repositories.feature, testsuite/features/build_validation/init_clients/opensuse155arm_minion.feature, testsuite/features/build_validation/init_clients/opensuse155arm_ssh_minion.feature, testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/support/constants.rb, testsuite/features/support/env.rb, testsuite/features/support/twopence_init.rb
This PR adds
* SLE 15 SP 5 (already partially done)
* openSUSE 15.5
to BV test suites.
Ports:
* 4.2: SUSE/spacewalk#21726
* 4.3: SUSE/spacewalk#21725
=> Add SLE 15 SP 5 and openSUSE 15.5

java/buildconf/ivy/ivy-suse.xml, java/spacewalk-java.changes
=> Adjust ivy configuration after tomcat update

testsuite/features/core/srv_channels_add.feature, testsuite/features/core/srv_create_activationkey.feature, testsuite/features/core/srv_create_repository.feature, testsuite/features/core/srv_docker.feature, testsuite/features/core/srv_first_settings.feature, testsuite/features/core/srv_organization_credentials.feature, testsuite/features/core/srv_osimage.feature, testsuite/run_sets/secondary_parallelizable.yml
This PR describes which `secondary` features are dependent on the features from the `core` stage.
Some dependencies might be missing and will be updated 
No difference.
Tracks #
4.2 https://github.com/SUSE/spacewalk/pull/21773
4.3 https://github.com/SUSE/spacewalk/pull/21774 …
=> Testsuite: Core feature dependency

web/html/src/manager/systems/virtualhostmanager/virtualhostmanager-details.tsx, web/html/src/manager/virtualization/guests/list/guests-list.tsx, web/spacewalk-web.changes
Port of https://github.com/SUSE/spacewalk/pull/21693
Check https://github.com/SUSE/spacewalk/pull/21693
Check https://github.com/SUSE/spacewalk/pull/21693
Fixes #
https://github.com/SUSE/spacewalk/issues/12273
=> Fix CPU and RAM details on vhm page

java/code/webapp/WEB-INF/nav/ssm.xml, java/spacewalk-java.changes
Port of https://github.com/SUSE/spacewalk/pull/21203
Check https://github.com/SUSE/spacewalk/pull/21203
Check https://github.com/SUSE/spacewalk/pull/21203
https://github.com/SUSE/spacewalk/pull/21203
=> Uyuni bug ssm provisioning

java/spacewalk-java.changes
Adding the bugnumber to the changelog
Port of https://github.com/SUSE/spacewalk/pull/21830
=> add bug number to changelog

java/code/src/com/redhat/rhn/common/util/FileUtils.java, java/code/src/com/suse/manager/ssl/SSLCertManager.java, java/spacewalk-java.changes
=> Don't log generated SSL certificate and key.

java/code/src/com/redhat/rhn/common/security/SessionSwap.java, java/spacewalk-java.changes
=> Remove SessionSwap secret logging

java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartHelper.java, java/code/src/org/cobbler/CobblerConnection.java, java/spacewalk-java.changes
**Port of commits mentioned in https://github.com/SUSE/spacewalk/issues/20419#issuecomment-1598857943**
Related https://github.com/SUSE/spacewalk/issues/21856
=> fix session information leak

.github/workflows/acceptance_tests_common.yml
workaround for https://github.com/actions/runner-images/issues/7753 https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394
No difference.
- No tests
https://github.com/actions/runner-images/issues/7753 https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394 …
=> fix podman

.github/CODEOWNERS
Update CODEOWNERS:
- Cobbler snippets would be reviewed by the python team rather than just a single person
- Adding a generic fallback to assign the java team as reviewers when there is no more specific assignment
=> Update CODEOWNERS: cobbler snippets

java/code/src/com/redhat/rhn/frontend/action/CSVDownloadAction.java, java/code/src/com/redhat/rhn/frontend/taglibs/list/CSVTag.java, java/spacewalk-java.changes, java/spacewalk-java.changes.houssemnasri.csv-export-bug
The CSV download would throw an exception when attempting to download patches, packages or system groups as CSV.
The bug can be explained in two parts. First, pageData was expected to be of type `List<SystemSearchResult>` however, this was never the case since the type of pageData is dependent on the type of data to be downloaded. If, for example, packages are being downloaded, then the type will be `List<PackageOverview`. Hence why I changed it to `List<BaseDto>` to be able to assign to it list of patches or system groups too. 
The second part concerns the use of `SystemSearchResult` in `CSVTag`, which remains unclear. Nevertheless, through an analysis of the program flow, it appeared that `makePartialResult()` would never be invoked and as such, it was removed. For the same reason, …
=> Fix CSV download exception

python/spacewalk/spacewalk-backend.changes.cbosdo.product_name
=> Add missing bsc to spacewalk-backend changelog

java/code/src/com/redhat/rhn/common/db/datasource/Elaborator.java, java/code/src/com/redhat/rhn/common/db/datasource/ModeElaborator.java, java/code/src/com/redhat/rhn/frontend/action/channel/ssm/BaseSubscribeAction.java
Fix 3 sonarcloud issues in new code
No difference.
Fixes #
=> Fix sonarcloud reported bugs in new code

susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.changes.mc.Manager-4.3-crypto-policy-in-supportconfig, susemanager-utils/supportutils-plugin-susemanager-client/susemanagerclient, susemanager-utils/supportutils-plugin-susemanager-proxy/supportutils-plugin-susemanager-proxy.changes.mc.Manager-4.3-crypto-policy-in-supportconfig, susemanager-utils/supportutils-plugin-susemanager-proxy/susemanagerproxy, susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes.mc.Manager-4.3-crypto-policy-in-supportconfig, susemanager-utils/supportutils-plugin-susemanager/susemanager
Port of https://github.com/SUSE/spacewalk/pull/22015
=> write configured crypto-policy in supportconfig

testsuite/features/init_clients/proxy_register_as_minion_with_script.feature
Fixup for https://github.com/uyuni-project/uyuni/pull/7287
No difference.
Already done.
=> QE: fix bootstrap script for using the Salt bundle

testsuite/features/build_validation/reposync/srv_sync_all_products.feature
=> Add ltss to sles15sp2 for BV

testsuite/features/build_validation/reposync/srv_sync_all_products.feature
=> remove useless space ltss

testsuite/features/step_definitions/navigation_steps.rb
=> Double timeout during logging

testsuite/features/build_validation/add_MU_repositories/monitoring_server_add_maintenance_update_repositories.feature
Create monitoring custom channel
Issue : https://github.com/SUSE/spacewalk/issues/22158
Depends on : https://github.com/SUSE/susemanager-ci/pull/915
=> Create monitoring custom channel

rel-eng/packages/uyuni-server-systemd-services
=> Forgot to remove releng definition for systemd package

susemanager/susemanager.spec
move /srv/www/htdoc/pub/repositories to /usr/share/susemanager/gpg/repositories
No difference.
Before:
After:
- (OPTIONAL) …
=> move /srv/www/htdoc/pub/repositories to /usr/share/susemanager/gpg/repositories

testsuite/features/step_definitions/retail_steps.rb
Typo fix in retail_step.rb
No difference.
Fixes #
Tracks # None
=> Typo fix in retail_steps.rb

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes.mackdk.fix-bootstrap-repo-data-ltss
Port of https://github.com/SUSE/spacewalk/pull/22293 without the data for SLE, since it has been already added by https://github.com/uyuni-project/uyuni/pull/7285
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/22287 …
=> Require LTSS channel for Proxy 4.2

testsuite/features/profiles/Makefile, testsuite/features/profiles/internal_nue/Docker/authprofile/sles15sp4.repo, testsuite/features/profiles/internal_nue/Docker/serverhost/sles15sp4.repo, testsuite/features/profiles/internal_nue/Docker/sles15sp4.repo, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_42/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_head/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_41/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_42/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_head/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_uyuni/config.xml, testsuite/features/profiles/internal_prv/Docker/authprofile/add_packages.sh, testsuite/features/profiles/internal_prv/Docker/authprofile/sles15sp4.repo, testsuite/features/profiles/internal_prv/Docker/serverhost/sles15sp4.repo, testsuite/features/profiles/internal_prv/Docker/sles15sp4.repo, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_42/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_head/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_41/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_42/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_head/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_uyuni/config.xml
CI minima mirrors and BV minima mirrors merged. Use the new merged mirror for all Docker and Kiwi profiles.
No ports
=> Use common mirrors for CI and BV both in NUE and PRV

testsuite/features/profiles/Makefile, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_42/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_head/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_41/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_42/config.xml, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_head/config.xml
Fix to previous PR (Kiwi profiles)
No ports.
=> Correct path is with ibs/Devel:

testsuite/features/profiles/Makefile, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_42/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_head/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_41/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_42/config.xml, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_head/config.xml
Final fix of previous PR
No ports
=> Correct path is ibs/Devel: (fixed)

testsuite/features/build_validation/containerization/proxy_as_pod_basic_tests.feature, testsuite/features/build_validation/smoke_tests/smoke_tests.template, testsuite/features/secondary/allcli_overview_systems_details.feature, testsuite/features/secondary/proxy_as_pod_basic_tests.feature, testsuite/features/step_definitions/api_common.rb, testsuite/features/step_definitions/cobbler_steps.rb, testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/common_steps.rb, testsuite/features/step_definitions/content_lifecycle_steps.rb, testsuite/features/step_definitions/datepicker_steps.rb, testsuite/features/step_definitions/docker_steps.rb, testsuite/features/step_definitions/file_management_steps.rb, testsuite/features/step_definitions/lock_packages_on_client.rb, testsuite/features/step_definitions/navigation_steps.rb, testsuite/features/step_definitions/retail_steps.rb, testsuite/features/step_definitions/salt_steps.rb, testsuite/features/step_definitions/setup_steps.rb, testsuite/features/step_definitions/smdba_steps.rb, testsuite/features/step_definitions/vm_steps.rb, testsuite/features/support/code_coverage.rb, testsuite/features/support/commonlib.rb, testsuite/features/support/env.rb
Part of https://github.com/SUSE/spacewalk/issues/14192
Improve our Ruby test framework by using correctly single and double quotes
No difference.
Ports:
- Manager-4.3
=> QE: Fix Ruby stile

testsuite/features/support/constants.rb
Fixup for a duplicate `elsif`
No difference.
- No ports needed, this affects only Uyuni.
=> QE: Fix duplicate elsif

spacewalk/setup/lib/Spacewalk/Setup.pm, spacewalk/setup/spacewalk-setup.changes.mbussolotto.improve_debug_setup
Print the command that is running in Setup.pm to ease debugging
No difference. …
=> Print the command that is running in Setup.pm to ease debugging

testsuite/features/init_clients/allcli_update_activationkeys.feature, testsuite/features/step_definitions/navigation_steps.rb
This PR fixes failures that might be due to changes in "Loading..." messages from developers (?).
Thanks @maximenoel8 for the precious help.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22453
=> Fix activation keys update

containers/hub-xmlrpc-api-image/Dockerfile, containers/proxy-helm/Chart.yaml, containers/proxy-httpd-image/Dockerfile, containers/proxy-salt-broker-image/Dockerfile, containers/proxy-squid-image/Dockerfile, containers/proxy-ssh-image/Dockerfile, containers/proxy-tftpd-image/Dockerfile, containers/server-helm/Chart.yaml, containers/server-image/Dockerfile
push-packages-to-obs.sh has a mechanism to set BuildTag using the product version
- for Dockerfile: https://github.com/uyuni-project/uyuni/blob/5cd461e3f5d0305398d8440b2e7d011034f2d7d7/rel-eng/push-packages-to-obs.sh#L281
- for Charts: https://github.com/uyuni-project/uyuni/blob/5cd461e3f5d0305398d8440b2e7d011034f2d7d7/rel-eng/push-packages-to-obs.sh#L302
So we can keep just `latest` as build tag, then push-packages-to-obs.sh would add the correct ones.
No difference.
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=docu …
=> set BuildTag using push-packages-to-obs.sh

containers/proxy-helm/Chart.yaml, rel-eng/push-packages-to-obs.sh
=> Remove the -helm part in chart build tags

containers/server-helm/templates/deployment.yaml, containers/server-helm/templates/ingress.yaml, containers/server-helm/values.yaml
Add migration flags to server helm chart
No difference.
Before:
After: …
=> Add migration flags to server helm chart

spacewalk/certs-tools/rhn_bootstrap.py, spacewalk/certs-tools/spacewalk-certs-tools.changes.mbussolotto.read_hostname_from_conf, spacewalk/setup/bin/spacewalk-setup, spacewalk/setup/bin/spacewalk-setup-cobbler, spacewalk/setup/spacewalk-setup.changes.mbussolotto.cobbler_fqdn, spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb, spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes.mbussolotto.setup_host, susemanager/bin/mgr-setup, susemanager/susemanager.changes.mbussolotto.read_hostname
The PR contains changes to enforce the setup procedure, in particular changes related to improve how hostname and FQDN are handled.
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes …
=> Enforce Setup: improve host and FQDN handling 

java/code/webapp/WEB-INF/includes/header.jsp, web/html/src/manager/notifications/notifications.tsx, web/html/src/manager/shared/menu/menu.tsx
**This PR fixes the label and display text errors in Uyuni home page**
No difference.
Fixes #7103 
=> Fix label and display error in home page

python/billingdataservice/billing-data-service.spec
See subject
No difference.
- No tests: Just a bump in the release number
=> Change release in spec files for billing-data-service in Uyuni

java/code/src/com/suse/manager/webui/templates/systems/all-list.jade, java/code/src/com/suse/manager/webui/templates/systems/virtual-list.jade, java/spacewalk-java.changes.cbosdo.page-size, web/html/src/manager/systems/all-list.renderer.tsx, web/html/src/manager/systems/all-list.tsx, web/html/src/manager/systems/virtual-list.renderer.tsx, web/html/src/manager/systems/virtual-list.tsx, web/spacewalk-web.changes.cbosdo.page-size
See title
No difference.
- No documentation needed: bug fix in UI
- No tests: user prefered size is not tested
Fixes https://github.com/uyuni-project/uyuni/issues/7633
=> Take user prefered list size into account in systems lists pages

java/code/src/com/redhat/rhn/common/util/FileUtils.java, java/code/src/com/redhat/rhn/domain/credentials/Credentials.java, java/code/src/com/redhat/rhn/domain/scc/SCCRepository.java, java/code/src/com/redhat/rhn/domain/scc/SCCRepositoryCloudRmtAuth.java, java/code/src/com/redhat/rhn/domain/scc/test/SCCRepositoryCloudRmtAuthTest.java, java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java, java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerPaygTest.java, java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java, java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataProcessor.java, java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygUpdateAuthTask.java, java/code/src/com/redhat/rhn/taskomatic/task/payg/test/PaygUpdateAuthTaskTest.java, java/code/src/com/redhat/rhn/testing/MockFileLocks.java, java/spacewalk-java.changes.mackdk.Manager-4.3-fix-exploding-repo-refresh, java/spacewalk-java.changes.mackdk.payg-combine-clashing-path, java/spacewalk-java.changes.mackdk.payg-credential-invalidation
This PR backports the following changes made for PAYG:
- https://github.com/SUSE/spacewalk/pull/22560 fixes multiple issues related to how the best authorization for accessing a repository is chosen when dealing with multiple PAYG credentials, and how those authorizations are updated when a credential is added/removed/invalidated.
- https://github.com/SUSE/spacewalk/pull/22578 changes how the paths from the credentials and from the repository are combined. When the path collides in fact now we are generated the wrong path. This change ensure we do not duplicate the overlapping folders in the final url.
- https://github.com/SUSE/spacewalk/pull/22631 avoids the call to the SCC /connect/organizations/repositories currently performed every 10 minutes during the PAYG credential refresh job …
=> Backports of latest changes for PAYG

web/html/src/utils/functions.ts, web/spacewalk-web.changes.eth.update-generator
Drops legacy fallbacks for password generation and simplifies the code we use.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/21410
=> Simplify and modernize password generation logic

testsuite/features/secondary/srv_rename_hostname.feature, testsuite/features/step_definitions/api_common.rb, testsuite/features/step_definitions/command_steps.rb, testsuite/features/support/commonlib.rb
See title
No difference.
Fixes #
=> Fix the hostname-rename test

testsuite/features/build_validation/reposync/srv_sync_all_products.feature
=> backport sync public cloud module

java/code/src/com/redhat/rhn/domain/channel/Channel.hbm.xml, java/spacewalk-java.changes.parlt.Manager-4.3-fix-child-channel-sharing
Port of: https://github.com/SUSE/spacewalk/pull/22798
=> Fix token validation for shared (public) child channels

.github/workflows/acceptance_tests_secondary.yml
Adds a new comment when running gh action.
No difference.
- No tests
=> CI: add comment in PR

.github/workflows/acceptance_tests_secondary.yml
TEST.
No difference.
Before:
After:
- No …
=> TEST message

.github/workflows/acceptance_tests_feedback.yml
=> fix gh action for adding a comment

containers/doc/server-kubernetes/README.md, containers/server-helm/templates/deployment.yaml
See title
No difference.
- No documentation needed: pre-doc notes fixes
- No tests: doc
Fixes #
=> Fix the offline installation instructions for podman and k3s

.github/workflows/acceptance_tests_feedback.yml
CI: Review message text.
No difference.
- No tests
N/A
=> CI: review message from acceptance tests

testsuite/features/build_validation/init_clients/debian12_minion.feature, testsuite/features/build_validation/init_clients/debian12_ssh_minion.feature
Replace outdated code with current version.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22835
=> Fix Debian 12 bootstrap test

rel-eng/push-packages-to-obs.sh
escape / in push-packages-to-obs.sh image
No difference.
- No tests
=> escape / in push-packages-to-obs.sh image

java/code/src/com/suse/manager/webui/controllers/DownloadController.java, susemanager-utils/susemanager-sls/salt/channels/dnf-susemanager-plugin/susemanagerplugin.py, susemanager-utils/susemanager-sls/susemanager-sls.changes.mc.Manager-4.3-token-debug-logging
When debugging tokens, print out all required data
No difference.
- No tests: **only debug**
=> add token debug logging

java/spacewalk-java.changes.meaksh.Manager-4.3-fix-xmlrpc-provision-server-endpoint
This PR simply fixes a changelog message
=> Fix changelog message and remove wrong file

schema/spacewalk/susemanager-schema.changes.witek.add_unique_index
Add changelog entry for susemanager-schema package
=> Add changelog entry for susemanager-schema package

testsuite/dockerfiles/server-all-in-one-dev/minima.yaml
=> CI: Fix minima configuration in server dev docker file

containers/init-image/Dockerfile
Fix of https://github.com/uyuni-project/uyuni/pull/7797/commits/e8d13eee08b6bb9086f827404c2507a1e8a458ca
No difference.
- No tests
=> fix param info in init imag

testsuite/dockerfiles/server-all-in-one-dev/Dockerfile, testsuite/dockerfiles/server-all-in-one-dev/minima.yaml
=> Fix docker files

containers/init-image/Dockerfile, containers/server-image/Dockerfile
=> Add name label to init-image and server-image containers

containers/init-image/Dockerfile, containers/server-image/Dockerfile
=> Remove double quotes in containers name labels as it messes up with tito

testsuite/dockerfiles/opensuse-minion/Dockerfile, testsuite/dockerfiles/rocky-minion/Dockerfile, testsuite/dockerfiles/ubuntu-minion/Dockerfile, testsuite/features/support/commonlib.rb
Install tar package in GH containers so we can collect logs later
No difference.
- No tests
No ports
=> Install tar package in GH containers so we can collect logs later

testsuite/features/secondary/min_cve_audit.feature
This will fix:
No difference.
Ports:
- Manager-4.3
=> QE: CVE Audit SLE Minion test, use the right test channel

java/code/src/com/redhat/rhn/manager/audit/AuditManager.java, java/code/src/com/suse/manager/webui/controllers/DownloadController.java, java/code/src/com/suse/manager/webui/services/impl/SaltService.java, java/code/src/com/suse/manager/webui/utils/gson/ProxyContainerConfigJson.java, java/spacewalk-java.changes.rjpmestre.address-high-rating-sonar-bugs_and_vunerabilities
Addressing high rated sonar detected issues. Mostly are false positives but still popping up in sonar report.
No difference.
Fixes #
=> Address high rating sonar bugs and vunerabilities

testsuite/features/step_definitions/command_steps.rb, testsuite/features/support/commonlib.rb
Reverts uyuni-project/uyuni#7866
=> Revert #7866 to fix commit message.

java/code/src/com/redhat/rhn/domain/action/ActionFactory.java, java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java, java/code/src/com/redhat/rhn/frontend/action/GenericIndexAction.java, java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemOverviewAction.java, java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml, java/code/src/com/redhat/rhn/taskomatic/task/MinionActionChainExecutor.java, java/code/src/com/redhat/rhn/taskomatic/task/MinionActionExecutor.java, java/code/src/com/redhat/rhn/taskomatic/task/SSHMinionActionExecutor.java, java/code/src/com/suse/manager/webui/Router.java, java/code/src/com/suse/manager/webui/controllers/DownloadController.java, java/code/src/com/suse/manager/webui/controllers/test/DownloadControllerTest.java, java/spacewalk-java.changes.mcalmer.Manager-4.3-prevent-download-payg-not-compliant, java/spacewalk-java.changes.mikeletux.22380-payg-restrict-byos-without-scc
This PR aims to put in place some restrictions for SUMA PAYG when dealing with BYOS instances and not SCC credentials are in place. The current restrictions are:
- You won't be able to schedule any action on regular BYOS Minions
- You won't be able to schedule any action on SSH BYOS Minions
- You won't be able to schedule any action-chain on BYOS Minions
- If you SSH to BYOS minions, these won't be able to access any respository hosted in SUMA.
Additionally to these restrictions, if using SSM to schedule any action, the whole action will fail as long as there's one BYOS Minion among the instances to manage. 
Also, when dealing with action-chains as long as action includes one BYOS instance, the whole action-chain will be cancelled. In all error messages it will display the instances that …
=> Payg restrictions port

java/code/src/com/suse/manager/webui/controllers/DownloadController.java, java/code/src/com/suse/manager/webui/utils/gson/ProxyContainerConfigJson.java, java/spacewalk-java.changes.rjpmestre.address-high-rating-sonar-bugs-and-vunerabilities-2
After addressing relevant issues from sonar ( https://github.com/uyuni-project/uyuni/pull/7794 ). A couple of them seem to have persisted (even after local analyzing with sonarlint and on sonar cloud branch analysis)
No difference.
Fixes # …
=> addressing high rating sonar issues

java/code/src/com/suse/manager/reactor/utils/ValueMap.java, java/code/src/com/suse/manager/webui/utils/salt/custom/SystemInfo.java, java/spacewalk-java.changes.parlt.fix-npe-test-mode
Port of https://github.com/SUSE/spacewalk/pull/23042
=> Prevent NPE when applying states in test mode

testsuite/features/support/constants.rb, testsuite/features/support/tags
Remove fake channel configuration by server name
No difference.
=> Remove fake channel configuration by server name

java/code/src/com/suse/manager/webui/controllers/DownloadController.java, java/code/src/com/suse/manager/webui/websocket/RemoteMinionCommands.java, java/code/src/log4j2.xml, java/conf/log4j2.xml.taskomatic, java/spacewalk-java.changes.mc.Manager-4.3-improve-logging-and-permissions
Port of https://github.com/SUSE/spacewalk/pull/23046
=> Improve logging and permissions

java/code/src/com/redhat/rhn/domain/server/MinionServer.java, java/code/src/com/redhat/rhn/domain/server/Server.java, java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/spacewalk-java.changes.juliogonzalez.amazonlinux2023, schema/spacewalk/common/data/rhnPackageKey.sql, schema/spacewalk/susemanager-schema.changes.juliogonzalez.amazonlinux2023, schema/spacewalk/upgrade/susemanager-schema-4.4.8-to-susemanager-schema-4.4.9/100-gpg-amazonlinux2023.sql, susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes.juliogonzalez.amazonlinux2023, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes.juliogonzalez.amazonlinux2023
Support for Amazon Linux 2023
Packages for testing are build built at https://build.opensuse.org/project/show/home:juliogonzalezgil:branches:systemsmanagement:Uyuni:Master
**NOTE:** Patching and patch detection could not be tested, as so far no patches  for any installed packages got released during the hack week, and Amazon does not allow deploying EC2 from old images.
**NOTE:** This PR also needs https://build.opensuse.org/request/show/1125090 and https://build.suse.de/request/show/313173 being accepted.
No difference.
- Documentation PR: https://github.com/uyuni-project/uyuni-docs/pull/2590
- No tests: As far a I can tell, we are not testing Amazon Linux 2, even if [it's available on premises](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html), but …
=> Support for Amazon Linux 2023

containers/doc/README.md
=> Fix --image-pullPolicy typo in server container doc

.github/PULL_REQUEST_TEMPLATE.md
Adapt PR template so we don't close issues automatically
No difference.
- No documentation needed: PR template
- No tests:  PR template
Tracks: https://github.com/SUSE/spacewalk/pull/23085
=> Adapt PR template so we don't close issues automatically

.github/workflows/java-checkstyle.yml, .github/workflows/sonarcloud.yml
Fix the PR values passed as parameters to sonar-scanner
=> workflows: use artifact to transmit PR data to sonarcloud workflow

testsuite/features/build_validation/core/allcli_sanity.feature, testsuite/features/build_validation/create_bootstrap_repositories/srv_create_bootstrap_repositories.feature, testsuite/features/build_validation/init_clients/sle15sp3s390_minion.feature, testsuite/features/build_validation/init_clients/sle15sp3s390_ssh_minion.feature, testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/support/constants.rb, testsuite/features/support/env.rb, testsuite/run_sets/build_validation/build_validation_init_clients.yml
This PR adds 2 new minions to BV test suite.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/23131
=> Add support for z/VM guests

.github/PULL_REQUEST_TEMPLATE.md
How to merge properly and small simplifications
No difference.
- No documentation needed: This is documentation, in a way
- No tests: Documentation
Issue(s): None
Ports(s): https://github.com/SUSE/spacewalk/pull/23148
=> How to merge properly and small simplifications

containers/doc/README.md, java/manager-build.xml, testsuite/features/support/lavanda.rb, testsuite/features/support/twopence_init.rb
Reflect the changes from https://github.com/uyuni-project/uyuni-tools/pull/115 in the doc and testsuite.
=> uyunictl has been renamed into mgrctl

java/code/src/com/suse/scc/registration/SCCSystemRegistrationSystemDataAcquisitor.java, java/spacewalk-java.changes.rjpmestre.address-sonar-reliability-bug-scc-system-registration-system-data-acquisitor
Fixes a sonar reliability bug detected at scc system registration system data acquisitor after refactoring
No difference.
=> Address sonar reliability bug

java/code/src/com/redhat/rhn/manager/action/ActionManager.java, java/spacewalk-java.changes.mbussolotto.dup
Follow up of https://github.com/uyuni-project/uyuni/pull/7987
Fix unit test - remove duplicate package just during installation. 
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to …
=> Fix unit test - remove duplicate packages just during installation

java/code/src/com/redhat/rhn/domain/action/server/ServerAction.java, java/code/src/com/redhat/rhn/domain/channel/ContentSource.java, java/code/src/com/redhat/rhn/domain/cloudpayg/PaygSshData.java, java/code/src/com/redhat/rhn/domain/iss/IssMaster.java, java/code/src/com/redhat/rhn/domain/kickstart/KickstartScript.java, java/code/src/com/redhat/rhn/domain/server/CPU.java, java/code/src/com/redhat/rhn/domain/server/Device.java, java/code/src/com/redhat/rhn/domain/server/Dmi.java, java/code/src/com/redhat/rhn/domain/server/MinionSummary.java, java/code/src/com/redhat/rhn/frontend/action/iss/EditMasterAction.java, java/code/src/com/redhat/rhn/frontend/action/iss/EditMasterSetupAction.java
Make debugging easier when we have toString methods for some bigger objects
No difference.
Ports(s): https://github.com/SUSE/spacewalk/pull/22804 …
=> Debug ubuntu errata call

spacewalk/config/etc/httpd/conf.d/z-public.conf
Follow symlinks in the `/pub` folder to expose the Root CA cert in the kubernetes case.
- No tests: already covered by the kubernetes CI that fails
=> Follow symlinks in pub

projects/ssl-cert-check/spacewalk-ssl-cert-check.changes.cbosdonnat.cleanup, proxy/installer/spacewalk-proxy-installer.changes.cbosdonnat.cleanup, proxy/proxy-docs/spacewalk-proxy-docs.changes.cbosdonnat.cleanup, proxy/proxy-html/spacewalk-proxy-html.changes.cbosdonnat.cleanup, proxy/proxy/spacewalk-proxy.changes.cbosdonnat.cleanup, schema/reportdb/uyuni-reportdb-schema.changes.cbosdonnat.cleanup
Since there was no other change in those packages since the last release we need a changelog entry.
=> Add changelogs after makefiles cleanup

python/spacewalk/spacewalk-backend.changes.mczernek.7594-fix
Fixing changelog so that tito can build the package
=> fix: Add bsc to changelog

testsuite/ext-tools/collect_and_tag_flaky_tests.rb
This PR add tags for all the columns from https://github.com/orgs/SUSE/projects/23/views/3 that we work on during the RRTG.
No difference.
- No tests
Ports:
- Manager-4.3 …
=> QE: Improve collect and tag

java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcInvoker.java, java/spacewalk-java.changes.mc.Manager-4.3-fix-taskomatic-api-XSS
Fix XSS in taskomatic XML RPC Handler.
No difference.
Ports(s): https://github.com/SUSE/spacewalk/pull/23278 …
=> Fix taskomatic api xss

testsuite/features/step_definitions/command_steps.rb
Fixing https://github.com/SUSE/spacewalk/issues/23277
No difference.
Ports(s):
- Manager-4.3
=> QE: Try a more fine grain search when looking for a system

containers/server-migration-14-16-image/Dockerfile, containers/server-migration-14-16-image/_service, containers/server-migration-14-16-image/server-migration-14-16-image.changes.nadvornik.migration_container, containers/server-migration-14-16-image/tito.props, rel-eng/packages/server-migration-14-16-image
Container for postgres migration
https://github.com/SUSE/spacewalk/issues/22587
No difference.
Before:
After:
- (OPTIONAL) …
=> Add server-migration-image

containers/BUILDING.md, containers/README.md, containers/doc/README.md
This will fix
- code block syntax
- unnecessary empty lines
- typos
No difference.
Issue(s): # …
=> docs: Fix layout of container Markdown files

java/code/src/com/redhat/rhn/manager/org/MigrationManager.java, java/code/src/com/redhat/rhn/manager/org/test/MigrationManagerTest.java, java/spacewalk-java.changes.mikeletux.bsc1216753
Port of https://github.com/SUSE/spacewalk/pull/22991
Check https://github.com/SUSE/spacewalk/pull/22991
- No documentation needed: this is just some little change requested by a customer
- No tests: This is just a little string change
Issue(s): https://github.com/SUSE/spacewalk/issues/22941
Ports(s): https://github.com/SUSE/spacewalk/pull/22991 …
=> Master bug 1216753 transfer system to another org

spacewalk/package/spacewalk.changes.juliogonzalez.fix-release-file, spacewalk/package/spacewalk.spec, web/spacewalk-web.changes.juliogonzalez.fix-release-file, web/spacewalk-web.spec
Reimplementatition of https://github.com/uyuni-project/uyuni/pull/7036, addresses @mcalmer's [comment](https://github.com/uyuni-project/uyuni/pull/7036#pullrequestreview-1433812875) 
Eventually the file should maybe be moved into a separate package, that can then be included in all the containers.
At SUSE Manager:
```
suma-refhead-srv:~ # cat /etc/uyuni-release 
Uyuni release 2023.09
suma-refhead-srv:~ # cat /etc/susemanager-release 
SUSE Manager release 4.4 (2023.09)
```
At Uyuni:
```
uyuni-refmaster-srv:~ # cat /etc/uyuni-release
Uyuni release 2023.09
uyuni-refmaster-srv:~ # cat /etc/susemanager-release
cat: /etc/susemanager-release: No such file or directory
```
At SUSE Manager:
```
suma-refhead-srv:~ # cat /etc/uyuni-release 
cat: /etc/uyuni-release: No such file or directory …
```
=> Add MU/Milestone information to /etc/susemanager-release

java/code/src/com/redhat/rhn/domain/product/SUSEProductSet.java, java/code/src/com/redhat/rhn/manager/distupgrade/DistUpgradeManager.java, java/spacewalk-java.changes.mc.Manager-4.3-improve-SPMigration-logging
Change some logging messages from debug to warn as they are very useful for finding real problems in SP Migrations.
No difference.
- No tests: **only changed logging**
Ports(s): https://github.com/SUSE/spacewalk/pull/23349 …
=> Improve sp migration logging

testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/support/constants.rb
Adjust channel waits according to latest timeouts
Ports:
* 4.3: SUSE/spacewalk#23381
=> Some more adjustments to channel waits

testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/reposync/srv_sync_products.feature, testsuite/features/step_definitions/navigation_steps.rb
Update new rhel8 base product name
No difference.
Ports(s): # https://github.com/SUSE/spacewalk/pull/23376 …
=> Update new rhel8 base product name

web/conf/rhn_web.conf, web/spacewalk-web.changes.deneb-alpha.rhn_web_to50
**Bump the WebUI version to 5.0.0 Alpha 1**
Before: `4.4.0 Alpha1`
After: `5.0.0 Alpha 1`
- No documentation needed: **bump of the version visible from the webui**
Issue(s): # https://github.com/SUSE/spacewalk/issues/22011 …
=> Bump the WebUI version to 5.0.0 Alpha 1

testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/reposync/srv_sync_products.feature
Addition to https://github.com/uyuni-project/uyuni/pull/8135
Ports(s): https://github.com/SUSE/spacewalk/pull/23385
=> finish rename of SLES ES to Liberty Linux

schema/reportdb/uyuni-reportdb-schema.changes.deneb-alpha.schema_bump50, schema/reportdb/uyuni-reportdb-schema.spec, schema/spacewalk/susemanager-schema.changes.deneb-alpha.schema_bump50, schema/spacewalk/susemanager-schema.spec
**Bump the version and add the schema migration to 5.0.0**
No difference. …
=> Bump the version and add the schema migration to 5.0.0

java/code/src/com/redhat/rhn/domain/server/Server_legacyUser.hbm.xml
This PR adds a missing backport from SUSE Manager 4.3 https://github.com/SUSE/spacewalk/pull/22899
The changelog is not present since it has already been by commit https://github.com/uyuni-project/uyuni/commit/a1b926f488c370130fe8abe58c9bc3fa2ea43e00 as `Fix issue of non-installed package listed as errata package update candidates (bsc#1212904)`.
No difference.
Ports(s): https://github.com/SUSE/spacewalk/pull/22899 …
=> Fix query to extract only packages relevant for the server

containers/server-migration-14-16-image/Dockerfile, containers/server-migration-14-16-image/server-migration-14-16-image.changes.cbosdonnat.image-fix
=> Adjust the server-migration image reference label

schema/reportdb/uyuni-reportdb-schema.changes.raul.schema_reportdb_migration_paths_5.0, schema/spacewalk/susemanager-schema.changes.raul.schema_reportdb_migration_paths_5.0
Add schema and reportdb migration paths for 5.0
No difference.
Before:
After: …
=> Add schema and reportdb migration paths for 5.0

testsuite/podman_runner/run
Some scripts were missing in the run script, so running the tests locally was not producing the same results as running them in github actions.
No difference.
- No tests
fixes https://github.com/SUSE/spacewalk/issues/23398 …
=> CI: fix run script

java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml
Change ivy config
Ports(s): https://github.com/SUSE/spacewalk/pull/23244
=> Jackson update

java/buildconf/checkstyle.xml, java/buildconf/ivy/ivy-suse.xml, java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java, java/manager-build.xml, java/spacewalk-java.changes.mc.checkstyle-update-10_12_7
Update Checkstyle to latest version
No difference.
Ports(s): 
=> Checkstyle update 10 12 7

containers/server-helm/server-helm.changes.nadvornik.liveness, containers/server-helm/templates/deployment.yaml, containers/server-image/Dockerfile, containers/server-image/healthcheck.sh, containers/server-image/server-image.changes.nadvornik.liveness
This PR adds  livenessProbe and readinessProbe to helm chart.
The livenessProbe is implemented via script, that tests all services - salt, apache, tomcat.
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if …
=> Add livenessProbe and readinessProbe to helm chart.

containers/server-helm/server-helm.changes.cbosdonnat.volumes-cleanup, containers/server-helm/templates/deployment.yaml, containers/server-helm/templates/volumes.yaml
Merge the `/srv/www` volumes into a single one and add one for `/var/lib/salt`.
=> Volumes cleanup

rel-eng/container_push.sh
Having to propagate these values in OBS configuration of multiple project will be painful and error prone: better store it in git.
=> Move the container eula and release_stage values to git

testsuite/features/step_definitions/cobbler_steps.rb
There is no continue button after the last action.
See https://github.com/SUSE/spacewalk/issues/19184
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/19184 …
=> QE: Fix Cobbler distro test

testsuite/features/reposync/allcli_update_activationkeys.feature
This tests, needs the proxy.
No difference.
- No tests
Issue(s): #https://github.com/SUSE/spacewalk/issues/23094
=> Testsuite: fix proxy key update test

java/code/src/com/suse/manager/webui/controllers/DownloadController.java, java/code/src/com/suse/manager/webui/controllers/test/DownloadControllerTest.java, java/spacewalk-java.changes.lucidd.4.3-1218669
this fixes an issue with missing tokens still causing issues when token checks are disabled.
No difference.
- No tests:
Issue(s): #https://github.com/SUSE/spacewalk/issues/23377
Ports(s): #https://github.com/SUSE/spacewalk/pull/23392 …
=> fix issue with disabling token check not working (bsc#1218669)

containers/hub-xmlrpc-api-image/hub-xmlrpc-api-image.changes.cbosdonnat.tito-builder
=> Add changelog for tito builder change

susemanager-utils/mgr-libmod/mgr-libmod.changes.mczernek.add-changelog
Add a missing changelog for the `mgr-libmod` pkg
=> Fix: Add changelog for libmod package

.github/workflows/acceptance_tests_common.yml, .github/workflows/acceptance_tests_secondary.yml, testsuite/Rakefile, testsuite/podman_runner/19_run_secondary_tests_subset.sh, testsuite/podman_runner/19_split_secondary_tests.sh, testsuite/podman_runner/run
split secondary tests to gain some speed.
No difference.
- No tests
Issue(s): #
=> split secondary tests

containers/server-helm/server-helm.changes.mbussolotto.gracefully_k3s, containers/server-helm/templates/deployment.yaml
Stop services and database in kubernetes gracefully
No difference. …
=> Stop services and database in kubernetes gracefully

.github/workflows/acceptance_tests_common.yml
Updates the license regex to allow the year 2024
No difference.
=> Update license 

.github/workflows/acceptance_tests_common.yml
This reverts commit 4a0645e80f3fb513e4411bdb8010489db6e23212.
unwanted commit 
No difference.
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-bra …
=> Revert "adjust acceptance tests project details"

java/spacewalk-java.changes.mc.adapt-required-versions-50-1, java/tito.props, python/spacewalk/spacewalk-backend.changes.mc.adapt-required-versions-50-1, python/spacewalk/tito.props
After the switch to 5.0, we should require the latest schema versions
No difference.
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-m …
=> require latest schema versions

web/conf/rhn_web.conf, web/spacewalk-web.changes.raul.uyuni_webversion_bump_2024.02
Bump web.version.uyuni to 2024.02 in web/conf/rhn_web.conf
Before: Showing 2024.01 in the webui
After: Showing 2024.02 in the webui
Issue(s): https://github.com/SUSE/spacewalk/issues/23410 …
=> Bump web.version.uyuni to 2024.02 in web/conf/rhn_web.conf

testsuite/features/build_validation/retail/sle12sp5_buildhost_build_kiwi_image.feature, testsuite/features/build_validation/retail/sle12sp5_terminal_deploy.feature, testsuite/features/build_validation/retail/sle12sp5_terminal_prepare.feature, testsuite/features/build_validation/retail/sle15sp4_buildhost_build_kiwi_image.feature, testsuite/features/build_validation/retail/sle15sp4_terminal_deploy.feature, testsuite/features/build_validation/retail/sle15sp4_terminal_prepare.feature
ATM the retail tests in our BV rely on a proxy that is set up as a branch server. 
These require a proxy
```yaml
features/build_validation/retail/proxy_branch_network.feature
features/build_validation/retail/sleXXspX_terminal_deploy.feature
```
These do not require a proxy
```yaml
features/build_validation/retail/sleXXspX_terminal_prepare.feature
features/build_validation/retail/sleXXspX_buildhost_build_kiwi_image.feature
```
So technically we can run 2 of the retail features without a proxy, however I do not know how useful this is. We could also add a `@proxy` tag on top of all of those retail features, instead of what I did in this PR. Let me know what you think, then I can adjust the PR.
No difference.
- Cucumber …
=> QE: Fix proxy tag in BV retail tests

testsuite/features/build_validation/add_non_MU_repositories/centos7_minion_add_iso.feature, testsuite/features/build_validation/add_non_MU_repositories/rocky8_minion_add_iso_and_build_clm.feature, testsuite/features/build_validation/init_clients/ubuntu2204_minion.feature, testsuite/features/build_validation/init_clients/ubuntu2204_ssh_minion.feature, testsuite/features/step_definitions/common_steps.rb, testsuite/features/step_definitions/navigation_steps.rb, testsuite/features/support/file_management.rb
Port of https://github.com/uyuni-project/uyuni/pull/8283
No difference.
Issue(s): # …
=> QE: Adapt BV test suite for 5.0

testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/reposync/srv_sync_products.feature, testsuite/features/support/constants.rb
Use LTSS channel for 15 SP4. The other SPs were already added by Maxime in July. I'm not 100% sure these files are the only ones I need to touch, I need to test this. 
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23322
Port(s): 4.3: https://github.com/SUSE/spacewalk/pull/23699
If you …
=> Use LTSS channel for 15 SP4

.github/workflows/build_containers.yml
=> CI: update to 2024.02 image

susemanager-utils/susemanager-sls/salt/uptodate.sls
For SUSE call zypper patch to update the updatestack.
No difference.
additional fix for https://github.com/uyuni-project/uyuni/pull/8264
Port(s): https://github.com/SUSE/spacewalk/pull/23724 …
=> further improve uptodate state

testsuite/features/support/constants.rb
Experimental data from 4.3 and head
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/23779
=> Fix lists of channels to sync - CI

java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java, java/code/src/com/redhat/rhn/common/messaging/SmtpMail.java, java/spacewalk-java.changes.rmateus.Manager-4.3-MU-4.3.10
Port from: https://github.com/SUSE/spacewalk/pull/23761
No difference.
Before:
After: …
=> Add timeout for smtp server connection(bsc#1218931)

susemanager-utils/susemanager-sls/src/modules/reboot_info.py, susemanager-utils/susemanager-sls/susemanager-sls.changes.agraul.silence-reboot-required
Don't log dnf needs-restarting output
`cmd.run_all` logs stdout and stderr of the command it ran with the
specified `output_loglevel` (defaults to DEBUG) with one exception:
when the command fails (retcode is non-zero and not in
`success_retcodes`), salt sets the loglevel to ERROR. This pollutes users
logs with messages like
```
[ERROR   ][1413] stdout: Core libraries or services have been updated since boot-up:
* kernel
* linux-firmware
```
No difference.
- No tests: open for discussion if we want to cover this (cucumber)
We could add a test that checks if any of these log messages appear in the minion log after we update specific packages. That would need to take place in the test suite. Do we want to have such a test? …
=> Don't log dnf needs-restarting output

uyuni/base/uyuni-base.changes.cbosdonnat.distributions-folder, uyuni/base/uyuni-base.spec
See title
Issue(s): https://github.com/uyuni-project/uyuni-tools/issues/155
=> Add /srv/www/distributions folder

testsuite/features/step_definitions/common_steps.rb, testsuite/features/support/commonlib.rb, testsuite/features/support/file_management.rb
wget is not in leap micro or sle micro
=> Testsuite: replace wget by curl

java/buildconf/ivy/ivy-suse.xml
Update ivy as two packages saw an update in OBS.
=> update jetty-util and jose4j in ivy

testsuite/Rakefile, testsuite/features/build_validation/init_clients/salt_migration_minion.feature, testsuite/features/build_validation/migration/salt_migration_minion_migration.feature, testsuite/features/build_validation/migration/sle15sp3_minion_migration.feature, testsuite/features/build_validation/migration/sle15sp3_ssh_minion_migration.feature, testsuite/features/build_validation/migration/slemicro54_minion_migration.feature, testsuite/features/build_validation/migration/slemicro54_ssh_minion_migration.feature, testsuite/features/support/constants.rb, testsuite/run_sets/build_validation/build_validation_init_clients.yml, testsuite/run_sets/build_validation/build_validation_migration.yml
Related to https://github.com/SUSE/spacewalk/issues/23586
None
- Cucumber features were added and edited
Issue(s): https://github.com/SUSE/spacewalk/issues/23586
Manager 4.3: https://github.com/SUSE/spacewalk/pull/23886
=> QE: BV - Add Salt migration tests

java/code/src/com/redhat/rhn/domain/kickstart/KickstartableTree.java, java/spacewalk-java.changes.kwalter.bsc1220221
No difference.
- No tests:
Issue(s): #
=> copy files since salt cant access symlinks (bsc#1220221)

spacewalk/config/spacewalk-config.changes.mbussolotto.cobbler_localhost, spacewalk/setup/spacewalk-setup.changes.mbussolotto.cobbler_localhost, utils/spacewalk-utils.changes.mbussolotto.cobbler_localhost
missing bsc reference for https://github.com/uyuni-project/uyuni/pull/8343
No difference.
- No tests
=> missing bsc reference 

susemanager-utils/susemanager-sls/modules/roster/uyuni.py, susemanager-utils/susemanager-sls/susemanager-sls.changes.mbussolotto.python_cobbler_host
follow up of https://github.com/uyuni-project/uyuni/pull/8444
use java.hostname conf instead of cobbler.host in susemanager-utils
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to …
=> use java.hostname conf instead of cobbler.host in susemanager-utils

proxy/proxy/apacheHandler.py, proxy/proxy/apacheServer.py
This reverts commit ab788d241566cc03ebf9228ab5ac0a94c24160b5.
Unfortunately we need to keep relying on presence of headers to correctly determine if we are rhnBroker or rhnRedirect otherwise we ends in a loop.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23964
If …
=> Revert "Simplify getting component type in proxy wsgi wrapper"

java/code/src/com/suse/manager/reactor/messaging/BatchStartedEventMessageAction.java
Improve the debug logging for a BatchStartEvent
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/23955 …
=> better debug logging for BatchStartEvent

testsuite/features/support/constants.rb
Added sle-manager-tools15-beta-pool-x86_64-sp4 as empty channel.
To fix this error:
```
uyuni-server:/var/cache/rhn/repodata # find . -type f -name "solv" -print0 | xargs -0 -n1 sh -c 'echo "File: $0"; dumpsolv "$0"' | grep -n -B 2 "repo size: 0 solvables"
1848088-File: ./sle-manager-tools15-beta-pool-x86_64-sp4/solv
1848089-repo_add_solv took 0 ms
1848090:repo size: 0 solvables
--
6788729-File: ./sle-module-suse-manager-retail-branch-server-4.3-updates-x86_64/solv
6788730-repo_add_solv took 0 ms
6788731:repo size: 0 solvables
--
6809181-File: ./fake-base-channel-suse-like/solv
6809182-repo_add_solv took 0 ms
6809183:repo size: 0 solvables
--
6810410-File: ./fake-base-channel-i586/solv
6810411-repo_add_solv took 0 ms
6810412:repo size: 0 solvables
--
6811293-File: …
```
=> QE: Added sle-manager-tools15-beta-pool-x86_64-sp4 as empty channel

java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/code/src/com/suse/manager/reactor/messaging/RegistrationUtils.java, java/code/src/com/suse/manager/reactor/test/RegisterMinionActionTest.java, java/code/src/com/suse/manager/reactor/test/dummy_systeminfo_byos.json, java/code/src/com/suse/manager/reactor/test/dummy_systeminfo_slespayg.json, java/code/src/com/suse/manager/webui/services/iface/SaltApi.java, java/code/src/com/suse/manager/webui/services/impl/SaltService.java, java/code/src/com/suse/manager/webui/services/test/TestSaltApi.java, java/code/src/com/suse/manager/webui/utils/salt/custom/SumaUtil.java, java/spacewalk-java.changes.agraul.payg-detection-exec-module, susemanager-utils/susemanager-sls/src/grains/public_cloud.py, susemanager-utils/susemanager-sls/src/modules/sumautil.py, susemanager-utils/susemanager-sls/susemanager-sls.changes.agraul.payg-detection-exec-module
Change from `is_payg_instance` grain to `sumautil.instance_flavor` execution function for detecting PAYG client. This change is required because the `instance-flavor-check` program can take minutes and grains need to be computed quickly. Adding a timeout to our grain function can result in false negatives, i.e. we think a system is BYOS when it really is PAYG. In this scenario, a client system would be denied during bootstrapping when the server itself is PAYG. The only way around that is to wait for the return of `instance-flavor-check` via an execution module call.
No difference.
- No tests: This is best tested with Java unit tests or with cucumber in AWS.
Issue(s): https://github.com/SUSE/spacewalk/issues/23443 …
=> Don't use a grain for PAYG client detection

testsuite/features/reposync/allcli_update_activationkeys.feature, testsuite/features/reposync/srv_sync_products.feature
For SUMA + Proxy 5.0, mirror SLE-Micro and the extensions
Also change the activation key product selection 
No difference.
Issue(s): #
Check …
=> Add SUMA 5.0 Extensions and fix the activation keys

web/html/src/branding/css/base/checkbox.scss, web/html/src/branding/css/base/fixes.scss, web/html/src/branding/css/base/inputs.scss, web/html/src/branding/css/base/network.scss, web/html/src/branding/css/base/setup-wizard.scss, web/html/src/branding/css/base/theme.less, web/html/src/branding/css/base/theme.scss, web/html/src/branding/css/base/visualization.scss, web/html/src/branding/css/susemanager/index.scss
This is the last part of the Less to Sass migration. Right now the only page these styles are visible on is the landing page and that page is visually unchanged. Any bugs in this pull request will only be visible and can be fixed once we actually start migrating other pages one by one.
Right now, these files are one-to-one with what we had in the old theme, so there isn't really anything to review.
This also fixes the sidebar issue which I hotfixed in a previous PR.
No difference.
Part of https://github.com/SUSE/spacewalk/issues/23935 …
=> Migrate remaining Less files to Sass

.github/CODEOWNERS
Fixes https://github.com/SUSE/spacewalk/issues/24022
=> Split 'frontend' and 'Naica' groups in CODEOWNERS

java/spacewalk-java.changes.parlt.remove-package-sync-not-available-msg, spacecmd/spacecmd.changes.deneb-alpha.fix_beta2_uyuni202403_changelogs, spacewalk/config/spacewalk-config.changes.lucidd.bsc1219061, susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.changes.deneb-alpha.fix_beta2_uyuni202403_changelogs
Fix missing changelogs or typos needed for tagging
No difference.
- No tests: changelog fixes only
Related: 
Issue(s): https://github.com/SUSE/spacewalk/issues/24034 https://github.com/SUSE/spacewalk/issues/23611 …
=> Fix missing changelogs or typos needed for tagging

web/conf/rhn_web.conf
- Bump Uyuni WebUI to 2024.03
- Bump SUSE Manager WebUI to 5.0.0 Beta2
Uyuni Before: 2023.02
SUSE Manager Before: 5.0.0 Beta1
Uyuni After: 2023.03
SUSE Manager After: 5.0.0 Beta2
- No documentation needed: **this is just  a WebUI string bump**
- No tests: **no additional tests needed**
Relate:
* https://github.com/SUSE/spacewalk/issues/23611
* https://github.com/SUSE/spacewalk/issues/24034
If you …
=> Bump WebUI to Beta2 and to Uyuni 2024.03

testsuite/features/build_validation/init_clients/proxy_container.feature, testsuite/features/build_validation/init_clients/slemicro51_minion.feature, testsuite/features/build_validation/init_clients/slemicro51_ssh_minion.feature, testsuite/features/build_validation/init_clients/slemicro52_minion.feature, testsuite/features/build_validation/init_clients/slemicro52_ssh_minion.feature, testsuite/features/build_validation/init_clients/slemicro53_minion.feature, testsuite/features/build_validation/init_clients/slemicro53_ssh_minion.feature, testsuite/features/build_validation/init_clients/slemicro54_minion.feature, testsuite/features/build_validation/init_clients/slemicro54_ssh_minion.feature, testsuite/features/build_validation/init_clients/slemicro55_minion.feature, testsuite/features/build_validation/init_clients/slemicro55_ssh_minion.feature
This PR changes only the BV code and
- onboards the containerized proxy as normal minion again
- add a reboot step after the Salt cleanup to all SLE Micro Minions
CI results with the new code:
No difference.
Issue(s): # …
=> QE: BV fixes for SLE Micro and containerized proxy

java/Makefile.docker, java/code/src/com/redhat/rhn/GlobalInstanceHolder.java, java/code/src/com/redhat/rhn/domain/action/Action.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/HandlerFactory.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/admin/configuration/test/AdminConfigurationHandlerTest.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/test/ChannelSoftwareHandlerTest.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerPtfTest.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java, java/code/src/com/redhat/rhn/manager/action/test/MinionActionManagerTest.java, java/code/src/com/suse/manager/attestation/AttestationManager.java, java/code/src/com/suse/manager/attestation/test/AttestationManagerTest.java, java/code/src/com/suse/manager/model/attestation/AttestationFactory.java, java/code/src/com/suse/manager/model/attestation/CoCoAttestationResult.java, java/code/src/com/suse/manager/xmlrpc/serializer/CoCoAttestationResultSerializer.java, java/code/src/com/suse/manager/xmlrpc/serializer/ServerCoCoAttestationReportSerializer.java, java/spacewalk-java.changes.mc.coco-attestation-api-2
Continue to implement APIs for CoCoAttestation
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23564 …
=> Coco attestation api 2

testsuite/features/build_validation/init_clients/proxy_container.feature, testsuite/features/init_clients/proxy_container.feature, testsuite/features/reposync/allcli_update_activationkeys.feature, testsuite/features/reposync/srv_sync_products.feature, testsuite/features/support/constants.rb
This is necessary for bootstrapping the proxy that we switched to openSUSE Leap Micro 5.5 in the CI this week.
The PR (CI only)
- Updates the proxy activation key
- Adds Leap Micro 5.5 to our constants for Uyuni - separated the base product and the client tools
- Triggers a reposync for Leap Micro 5.5 (We will try to synchronize the full product for now, and we can consider later if we can synchronize only client-tools later)
- Removes the SUMA tag for restarting the proxy, since we use Leap Micro for the cont. proxy in Uyuni Podman as well now
- Adds the same comments to the cont. proxy feature as in the BV file
No difference.
Issue(s): #
Make sure …
=> QE: Add Leap Micro 5.5 reposync definitions to the CI

python/spacewalk/server/importlib/backend.py, python/spacewalk/server/rhnServer/server_packages.py, python/spacewalk/spacewalk-backend.changes.mc.Manager-4.3-add-pkg-sig_type, python/uyuni/common/rhn_rpm.py, python/uyuni/uyuni-common-libs.changes.mc.Manager-4.3-add-pkg-sig_type
Handle packages during import correctly when they are signed with RSA/SHA512 signature type
Also support  RSA/SHA384 correct
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/23997 …
=> add package signature types

containers/server-helm/server-helm.changes.mbussolotto.pam, containers/server-helm/templates/deployment.yaml, containers/server-helm/templates/volumes.yaml, containers/server-image/Dockerfile, containers/server-image/pam_susemanager, containers/server-image/server-image.changes.mbussolotto.pam, spacewalk/config/var/lib/rhn/rhn-satellite-prep/etc/rhn/rhn.conf
- Enable SSSD, PAM and LDAP authentication by default
- Persists /etc/sssd folder: all authentication mechanism should be configured using sssd
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have …
=> Enable SSSD authentication by default in containers: uyuni changes

.github/workflows/build_containers.yml
CI: update base image to the latest released one.
No difference.
- No tests
=> Ci update base image to 2024 3

client/tools/mgr-push/mgr-push.changes
See title
Issue(s): https://github.com/SUSE/spacewalk/issues/24117
Port(s): https://github.com/SUSE/spacewalk/pull/24115
=> Add bsc number to old rhnpush CA changelog

schema/spacewalk/common/data/rhnPackageKey.sql, schema/spacewalk/susemanager-schema.changes.mc.update-provider, schema/spacewalk/upgrade/susemanager-schema-5.0.6-to-susemanager-schema-5.0.7/001-add-package-keys.sql
Update the GPG key ids of common package provider in the database
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24109 …
=> update list of package gpg keys in the database

containers/proxy-tftpd-image/proxy-tftpd-image.changes.oholecek.cobbler_translations, containers/proxy-tftpd-image/tftp_wrapper.py
To avoid clients behind proxy connecting directly to the server, we need to translate server fqdn to the proxy one. This PR adds this translation.
Also fixes preselection of correct entry for saltboot branch.
This PR does 2 translations/lookout simultaneously. It, as before looks for saltboot entries and filtering out the rest. Parallel to it it translate server fqdn to proxy fqdn for other entries.
At the end depending if saltboot entry was matched or not it presents either saltboot profile or translated cobbler profiles.
Tested this on grub 30k profiles and there is no noticeable delay. tftp request for filtered saltboot output was in approximately 0.3s.
No difference.
- No tests: **add …
=> Translate server fqdn to proxy fqdn for pxe boot menus

web/conf/rhn_web.conf, web/spacewalk-web.changes.mbussolotto.pam_default
Enable PAM Authentication by default
No difference.
Issue(s): # …
=> Enable PAM Authentication by default

java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ErrataOverviewSerializer.java, java/manager-build.xml, java/spacewalk-java.changes.quinilo.master
**Added booleans and serializer for reboot_suggested and restart_suggested**
No difference.
Api documentation added
Issue(s): https://github.com/uyuni-project/uyuni/issues/7811 …
=> Added serializer for rebootSuggested and restartSuggested

java/code/src/com/suse/manager/reactor/SaltReactor.java, java/spacewalk-java.changes.rmateus.m43_null_pointer_reboot_info
port of: https://github.com/SUSE/spacewalk/pull/24119
No difference.
Before:
After: …
=> Prevent NPE when processing reboot needed beacon event

.github/workflows/yard-doc-test-framework.yml, testsuite/.rubocop.yml, testsuite/features/step_definitions/api_common.rb, testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/content_lifecycle_steps.rb, testsuite/features/step_definitions/navigation_steps.rb, testsuite/features/support/api_test.rb, testsuite/features/support/cobbler_test.rb, testsuite/features/support/code_coverage.rb, testsuite/features/support/commonlib.rb, testsuite/features/support/custom_formatter.rb, testsuite/features/support/env.rb, testsuite/features/support/file_management.rb, testsuite/features/support/http_client.rb, testsuite/features/support/kubernetes.rb, testsuite/features/support/lavanda.rb, testsuite/features/support/namespaces/actionchain.rb, testsuite/features/support/namespaces/activationkey.rb, testsuite/features/support/namespaces/api.rb, testsuite/features/support/namespaces/audit.rb, testsuite/features/support/namespaces/channel.rb, testsuite/features/support/namespaces/configchannel.rb, testsuite/features/support/namespaces/image.rb, testsuite/features/support/namespaces/kickstart.rb, testsuite/features/support/namespaces/schedule.rb, testsuite/features/support/namespaces/system.rb, testsuite/features/support/namespaces/user.rb, testsuite/features/support/xmlrpc_client.rb
- Some headers to document some functions, using YARD doc style, to facilitate generating test framework documentation.
- Adapt some Ruby docstrings using a different doc style.
Note:
To generate the YARD doc use:
```
gem install yard
cd testsuite
yard doc --protected --private features/step_definitions/*.rb features/support/*.rb features/support/**/*.rb features/**/*.feature features/**/**/*.feature 
```
And add this into your home:
```
~  cat .yard/config 
--- !ruby/hash-with-ivars:SymbolHash
elements:
:load_plugins: true
:ignored_plugins: []
:autoload_plugins: []
:safe_mode: false
:"yard-cucumber":
language:
step_definitions: [ 'Given', 'When', 'Then', 'And', 'But']
menus: [ 'features', 'directories', 'tags', 'steps', 'step definitions' ]
ivars:
:@symbolize_value: false% …
```
=> QE: Additional docstrings into test framework code

.github/workflows/yard-doc-test-framework.yml
Fix in yard-doc-test-framework.yml, missing folder
No difference.
- No tests
No ports
=> Fix in yard-doc-test-framework.yml, missing folder

spacewalk/admin/import-suma-build-keys, spacewalk/admin/spacewalk-admin.changes.mbussolotto.master
use uyuni-build-keys.gpg is suma-build-keys.gpg is missing
No difference. …
=> use uyuni-build-keys.gpg is suma-build-keys.gpg is missing

testsuite/features/secondary/proxy_container_cobbler_pxeboot.feature
Fix typo
No difference.
No ports.
=> QE: Fix typo in Create auto installation profile

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml, java/code/src/com/suse/manager/model/attestation/CoCoEnvironmentType.java, java/code/src/com/suse/manager/model/attestation/CoCoResultType.java, java/code/src/com/suse/manager/model/attestation/test/AttestationFactoryTest.java
Remove the Azure environment type and the attached result types for Azure.
We do not support them yet. They may be added later, but for now we comment them out.
No difference.
Check [How …
=> remove Azure environment and result type as we do not support it yet

web/html/src/branding/css/susemanager/components/alerts.less, web/html/src/branding/css/susemanager/components/alerts.scss, web/spacewalk-web.changes.bisht-richa.fix-alignment-issue-credentials-modal
-  Fixed alert Alignment issue credentials modal.
- Added bottom space between alert and input box
No difference.
Before:
After:
- No documentation needed: No documentation needed
Issue(s): #[8209](https://github.com/uyuni-project/uyuni/issues/8209) …
=> Fixed Alignment issue in credentials modal

python/spacewalk/satellite_tools/Makefile
=> Add appstreams.py to spacewalk-backend built files

web/html/javascript/spacewalk-essentials.js, web/html/src/branding/css/base/setup-wizard.less, web/html/src/branding/css/base/setup-wizard.scss, web/html/src/manager/admin/setup/products/products.tsx, web/spacewalk-web.changes.bisht-richa.fixed-alignment-issue-product-table
- Fixed alignment issue in the Product table
- Added header text to the Recommended column 
No difference.
Before:
After:
- No documentation needed: No documentation needed
Issue(s): #[23103](https://github.com/SUSE/spacewalk/issues/23103) …
=> Fixed alignment issue in Product table

testsuite/run_sets/reference_reposync.yml
move special reposync for reference server at the end of the step
and do not check for sync finished for now
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24190
Port(s): https://github.com/SUSE/spacewalk/pull/24203 …
=> fix reference server setup

client/tools/mgr-push/mgr-push.changes.juliogonzalez.missing-clogs, python/spacewalk/spacewalk-backend.changes.cbosdo.Manager-4.3, spacecmd/spacecmd.changes.juliogonzalez.missing-clogs, spacewalk/config/spacewalk-config.changes.juliogonzalez.missing-clogs
Fix several issues that prevented tagging:
- Wrong bsc reference for spacewalk-backend: @cbosdo 
- No changes for spacecmd because we only have translations: @uyuni-project/release-engineering 
- missing entry for spacewalk-config: @cbosdo and @mbussolotto 
No difference.
- No documentation needed: Changelog fix
- No tests: Changelog fix
None. …
=> Fix issues with changelogs

testsuite/features/build_validation/smoke_tests/smoke_tests.template, testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/salt_steps.rb, testsuite/features/support/commonlib.rb
Fixes
- https://github.com/SUSE/spacewalk/issues/24256
- https://github.com/SUSE/spacewalk/issues/22421
and renames our SLE Micro only methods, steps to a more general `transactional systems` one, since we are also using Leap Micro. 
No difference.
Issue(s): # …
=> QE: Fix Leap Micro/transactional system test suite issues

java/code/src/com/redhat/rhn/frontend/dto/SystemOverview.java, java/spacewalk-java.changes.mc.Manager-4.3-MU-4.3.12-fix-systemlist
**DO NOT MERGE YET, A DISCUSSION IS HAPPENING AT https://suse.slack.com/archives/C02D78LLS04/p1715081655777619 TO SEE IF THIS PR IS ENOUGH, OR MORE FIXES ARE NEEDED, OR IF A ROLLBACK OF https://github.com/SUSE/spacewalk/pull/23730 NEEDS TO HAPPEN!!!!!!!!**
**CLARIFY THAT DISCUSSION BEFORE YOU MERGE THIS!!!!**
fix status icon of the systems overview list (bsc#1224012)
Port(s): https://github.com/SUSE/spacewalk/pull/24267 …
=> Fix system overview list

web/html/src/branding/css/susemanager/components/buttons.less, web/html/src/branding/css/susemanager/components/buttons.scss, web/spacewalk-web.changes.eth.btn-link
This PR fixes a regression caused by the Bootstrap upgrade. In short, some of our link buttons currently use just "btn-link", whereas others use "btn btn-link", and this discrepancy was not accounted for.
Before:
After:
- No tests: Styles only. …
=> Fix link button look and alignment

rel-eng/packages/uyuni-payg-timer, uyuni/uyuni-payg-timer/LICENSE, uyuni/uyuni-payg-timer/uyuni-payg-extract-data.py, uyuni/uyuni-payg-timer/uyuni-payg-timer-rpmlintrc, uyuni/uyuni-payg-timer/uyuni-payg-timer.changes, uyuni/uyuni-payg-timer/uyuni-payg-timer.service, uyuni/uyuni-payg-timer/uyuni-payg-timer.spec, uyuni/uyuni-payg-timer/uyuni-payg-timer.timer
For PAYG we need some data from the host available in the container.
This is a timer service which collect the data and write it into a volume which is used by the container
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24209 …
=> Payg timer

java/manager-build.xml, web/html/src/scripts/docker-javascript-lint.sh
See https://suse.slack.com/archives/C02D130RBA6/p1715784109707889
No difference.
- No tests: build scripts
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-p …
=> Disable frontend license validation step until a proper fix is implemented

containers/proxy-tftpd-image/tftp_wrapper.py
Fix syntax error introduced by PR #8694.
No difference.
- No tests: Fixes a CI break
Issue(s): # …
=> Fix missing parenthese in tftp_wrapper.py

python/spacewalk/satellite_tools/appstreams.py, python/spacewalk/satellite_tools/reposync.py, python/spacewalk/spacewalk-backend.changes.cbbayburt.appstreams-reposync-yaml-errors
Print details for YAML subdocument parsing errors when indexing module metadata in reposync.
Before:
```
15:44:37   Importing modules file 02eb300a009b1643f1af4593c678867bbaf60a570fbd792774323803c82c658a-modules.yaml.gz.
15:44:37 *** NOTE: Importing modules file for the channel 'testchannel'. Previous modules will be discarded.
15:44:37 An error occurred while reading module metadata: No module data exists in the metadata file.
15:44:37 Total time: 0:00:02
```
After:
```
15:45:21   Importing modules file 02eb300a009b1643f1af4593c678867bbaf60a570fbd792774323803c82c658a-modules.yaml.gz.
15:45:21 *** NOTE: Importing modules file for the channel 'testchannel'. Previous modules will be discarded.
15:45:21 An error occurred while reading module metadata: An error occurred while indexing a …
```
=> Print detailed parsing errors when indexing module metadata

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/code/src/com/suse/manager/webui/templates/org/custom.jade, java/code/src/com/suse/manager/webui/templates/org/recurring-actions.jade, java/spacewalk-java.changes.bisht-richa.fix-incorrect-capitalization
Fix incorrect capitalization Organization => recurring-actions tab
No difference.
Before:
After:
Issue(s): #8765 …
=> Fix incorrect capitalization

java/code/src/com/suse/manager/utils/SaltUtils.java, java/spacewalk-java.changes.cbbayburt.appstreams-error-results
Parse the failed `state.apply` result and print its comment in the failed action details.
Before:
After:
- No tests: Salt inputs not tested
Fixes https://github.com/SUSE/spacewalk/issues/24197 …
=> Print detailed error messages on AppStreams action failure

testsuite/features/build_validation/add_MU_repositories/add_maintenance_update_repositories.template, testsuite/features/build_validation/add_MU_repositories/monitoring_server_add_maintenance_update_repositories.feature, testsuite/features/build_validation/add_non_MU_repositories/centos7_minion_add_iso.feature, testsuite/features/build_validation/add_non_MU_repositories/rocky8_minion_add_iso_and_build_clm.feature
Try to be more reliable until this issue:
No difference.
Ports:
- Manager-4.3
=> QE: If the repository is sync., wait until click Sync Now

testsuite/features/step_definitions/common_steps.rb, testsuite/features/support/file_management.rb
Correct `I mount as "([^"]+)" the ISO from "([^"]+)" in the server, validating its checksum` step.
If I correctly understood the expected behavior, we want to copy the image on the server host and do the checksum on server host and then copy the distro using `mgradm distro copy`.
The current behavior was a mix of downloading the image and checksum in the container and doing the checksum on the host. I fix this behavior to have everything done on the server host and then push the image using mgradm command.
I also simplify some of the steps where we wanted to always run the command on local host but use different method depending on the server configuration. In conclusion I simplified the steps with `$is_container_provider`.
I also removed the direct calls of `run_local` and use `run` with …
=> run all command locally and use mgradm to mount the image

java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml
jackson and hamcrest was updated and we need to change the IVY config to get the latest packages
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24381 …
=> Uyuni ivy update jackson

java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/appstreams/ChannelAppStreamHandler.java, java/spacewalk-java.changes.cbbayburt.appstreams-apidoc-fix
=> Fix API doc for 'channel.appstreams.listModuleStreams'

.github/workflows/python-checkstyle.yml, containers/proxy-httpd-image/uyuni-configure.py, containers/proxy-salt-broker-image/uyuni-configure.py, containers/proxy-squid-image/uyuni-configure.py, containers/proxy-ssh-image/uyuni-configure.py, containers/proxy-tftpd-image/tftp_wrapper.py, containers/proxy-tftpd-image/uyuni-configure.py
In this PR, I am including Alex's formatting commit from https://github.com/agraul/uyuni/commit/1c2a1ab4fdefbc9cfc04c0411d3f7e7861e30c52 and adding additional changes, mostly to `tftp_wrapper.py`.
In this PR, we are enabling linting enforcement check on the `containers` directory. 
Please add the missing docstrings in your classes. Notably, the `tftp_wrapper.py` file is missing docstrings. There are `TODO` comments instead.
Pay attention to CLI arguments for `tftp_wrapper`, notably: `--httpHost`, `--serverFqdn`, and `--proxyFqdn`. 
The arguments stayed the same, however, they are now stored in variables that conform to Python naming.
In addition to the internal changes, please consider changing the arguments to use the `--http-host`, `--server-fqdn`, and `--proxy-fqdn` naming, which is I …
=> Enable linting in the containers directory

testsuite/features/init_clients/proxy_container_branch_network.feature
Fix previous PR, which was tested on BV, but fails on CI :sob: .
None, 5.0 only.
=> Properly open proxy's system page

testsuite/features/secondary/srv_cobbler_distro.feature, testsuite/features/secondary/srv_cobbler_profile.feature, testsuite/features/step_definitions/cobbler_steps.rb
- Do not hide error in `^I trigger cobbler system record on the "([^"]*)"$/` anymore.
- Merge scenarios that are logically linked together
No difference.
Issue(s): #
Ports(s): # Manager 4.3: …
=> QE: Refactor Cobbler distro and profile scenarios

java/spacewalk-java.changes.mc.align-version-deps-for-gmc, java/spacewalk-java.spec, java/tito.props, python/spacewalk/spacewalk-backend.changes.mc.align-version-deps-for-gmc, python/spacewalk/tito.props
- adjust minimal DB schame version requirements
- set product tree tag from Beta to SUMA5.0
No difference.
Issue(s):  …
=> Align version deps for gmc

testsuite/features/reposync/reference_srv_check_reposync.feature, testsuite/features/step_definitions/command_steps.rb, testsuite/features/support/commonlib.rb, testsuite/features/support/env.rb
As we don't have anymore beta channels, we need to skip them from our scenarios and list of channels.
Let's do it programmatically, instead of removing code lines.
No difference.
Ports:
- Manager-4.3 …
=> Don't take into account beta channels when we have beta disabled

susemanager-utils/susemanager-sls/salt/services/salt-minion.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes.mczernek.remove-old-venv-env
Backport of https://github.com/uyuni-project/uyuni/pull/8826
No difference.
Before:
After: …
=> Add a sls step to remove old venv env if present

spacewalk/certs-tools/rhn_bootstrap_strings.py, spacewalk/certs-tools/spacewalk-certs-tools.changes.mc.enable-sl-micro-60, susemanager-utils/susemanager-sls/salt-ssh/preflight.sh, susemanager-utils/susemanager-sls/salt/bootstrap/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes.mc.enable-sl-micro-60, susemanager/src/mgr_bootstrap_data.py, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes.mc.enable-sl-micro-60
Prepare bootstrap repo and bootstrapping code for SL-Micro 6.0
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23758
Port(s): #  …
=> Enable sl micro 60

testsuite/Gemfile
Try to specify a working version of ffi
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24448 …
=> use for testsuite gems ffi only in version 1.16.X

susemanager/susemanager.changes.mc.Manager-4.3-suma-missing-changelog
Add missing changelog 
For https://github.com/uyuni-project/uyuni/pull/8830
Port(s): https://github.com/SUSE/spacewalk/pull/24453
=> add changelog for susemanager

java/code/src/com/redhat/rhn/manager/system/SystemManager.java, java/spacewalk-java.changes.rmateus.uyuni_refresh_system_list_proxy
When we generate configuration info for a proxy on an existing system we should run the system list update process to present the system as a proxy.
No difference.
Before:
After:
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the …
=> Refresh systems list when create proxy configuration

testsuite/features/build_validation/add_non_MU_repositories/alma8_minion_build_clm.feature, testsuite/features/build_validation/add_non_MU_repositories/alma9_minion_build_clm.feature, testsuite/features/build_validation/add_non_MU_repositories/liberty9_minion_build_clm.feature, testsuite/features/build_validation/add_non_MU_repositories/oracle9_minion_build_clm.feature, testsuite/features/build_validation/add_non_MU_repositories/rocky9_minion_build_clm.feature, testsuite/features/build_validation/core/srv_prepare_rh_like_clm_filters.feature
Upstream port of https://github.com/SUSE/spacewalk/pull/24594.
No difference.
Issue(s): #
Ports(s): https://github.com/SUSE/spacewalk/pull/24594 …
=> QE: Fix AlmaLinux 8 CLM tests

testsuite/features/build_validation/retail/proxy_container_branch_network.feature
Fix of commit 609d972af6a1cf3a2c40ab583d1af21f6075d88a.
Move to proxy page before looking at its details.
None, 5.0 BV only.
=> Move to proxy page before looking at its details

testsuite/features/profiles/Kiwi/POS_Image-JeOS6_head/sysconfig/bootloader, testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS6_head/sysconfig/bootloader, testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_head/sysconfig/bootloader, testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_head/sysconfig/bootloader
See https://bugzilla.suse.com/show_bug.cgi?id=1227504.
No ports, profiles are shared between all branches.
=> Add file now needed to reboot SLES 12 terminals

.github/PULL_REQUEST_TEMPLATE.md
Following proposed best practices guide, this PR encourage developers to cover new functionalities with e2e tests.
https://www.bestpractices.dev/en/projects/6593?criteria_level=1#quality
No difference.
- No tests
Port(s): 
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/24591 …
=> Update PR template to encourage covering new functionalities with e2e tests

java/code/src/com/redhat/rhn/domain/notification/UserNotificationFactory.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/HandlerFactory.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/UserNotificationSerializer.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserNotificationsHandler.java, java/spacewalk-java.changes.quinilo.master
Added api calls getNotifications, makeNotificationRead, makeAllNotificationsRead, deleteNotification to UserNotificationHandler
Successor of https://github.com/uyuni-project/uyuni/pull/8668
No difference.
Issue(s): https://github.com/uyuni-project/uyuni/issues/5540
If …
=> Quinilo Notification API

java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java, java/code/src/com/redhat/rhn/domain/server/Server.java, java/code/src/com/redhat/rhn/frontend/action/GenericIndexAction.java, java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemOverviewAction.java, java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java, java/code/src/com/redhat/rhn/manager/content/test/smallBase/additional_products.json, java/code/src/com/redhat/rhn/taskomatic/task/MinionActionChainExecutor.java, java/code/src/com/suse/manager/webui/controllers/DownloadController.java, java/code/src/com/suse/manager/webui/controllers/test/DownloadControllerTest.java, java/spacewalk-java.changes.mc.Manager-4.3-fix-payg-client-detection-part2
Some not PAYG products can be managed also with SUMA PAYG. Fix the detection of:
- Free Products
- SUSE Manager Proxy BYOS
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24505 …
=> fix detection of not PAYG systems which are allowed to be managed by SUMA PAYG

java/code/src/com/redhat/rhn/domain/server/Server.java, java/code/src/com/redhat/rhn/domain/server/ServerConstants.java, java/spacewalk-java.changes.welder.bsc1227406
Includes `SL Micro` OS name as a possible value when checking if a given system is SL(E) Micro.
No difference.
Issue(s): bsc#1227406 …
=> Fix transactional update check for SL Micro

web/html/src/manager/systems/ssm/ssm-subscribe-channels.tsx, web/spacewalk-web.changes.parlt.fix-ssm-channel-change
Port of https://github.com/SUSE/spacewalk/pull/24746
=> Fix channel selection using SSM

java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserNotificationsHandler.java
Adds missing class-level API documentation for UserNotificationsHandler.
Follow-up to: https://github.com/uyuni-project/uyuni/pull/8860
=> Add API description for UserNotificationsHandler

java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserNotificationsHandler.java
=> Do not use Stream.toList() for Java 11

java/code/src/com/redhat/rhn/domain/action/server/ServerAction.java, java/code/src/com/redhat/rhn/domain/action/virtualization/VirtualizationCreateGuestAction.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/code/src/com/suse/manager/reactor/utils/LocalDateTimeISOAdapter.java, java/code/src/com/suse/manager/reactor/utils/OptionalTypeAdapterFactory.java, java/code/src/com/suse/manager/webui/controllers/AnsibleController.java, java/code/src/com/suse/manager/webui/controllers/StatesAPI.java, java/code/src/com/suse/manager/webui/controllers/appstreams/AppStreamsController.java, java/code/src/com/suse/manager/webui/utils/MinionActionUtils.java, java/spacewalk-java.changes.mc.fix-failing-server-action
In the past we did not use TypeAdapters for JSON parsing. That encoded optional values different than the new type adapter.
Reading the old values cause now Json Parsing Exceptions.
This PR fix parsing the legacy entries and also writing out the new entries.
Additionally the context return now sometimes no timezone which result in a NullPointerException.
No difference.
Issue(s): # …
=> Fix failing server action

susemanager-utils/susemanager-sls/modules/roster/uyuni.py, susemanager-utils/susemanager-sls/susemanager-sls.changes.rmateus.uyuni_add_ssh_port_tunnel_creating_tunnel
SSH roster through proxy looks should look first on the ssh port that is defined for the proxy, since it should containerized and can have a different value.
If it's not a proxy or is not defined it will fallback for the existing behavior. 
No difference.
Before:
After:
- API documentation added: please review the Wiki page [Writing …
=> Look for proxy ssh port before look for host ssh port

java/code/src/com/redhat/rhn/manager/satellite/UpgradeCommand.java, java/code/src/com/suse/manager/webui/services/iface/SaltApi.java, java/code/src/com/suse/manager/webui/services/impl/SaltService.java, java/code/src/com/suse/manager/webui/services/test/TestSaltApi.java, java/spacewalk-java.changes.rmateus.salt_sync_call_startup
packport of: https://github.com/SUSE/spacewalk/pull/24382
No difference.
Before:
After: …
=> Change syncAll call at start-up to be asynchronous (bsc#1224004)

testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/reposync/srv_sync_products.feature
Removes the BETA tag from the products, since they've been released
=> QE: Remove BETA from products after SUMA release

susemanager-utils/susemanager-sls/salt/channels/channels.repo, susemanager-utils/susemanager-sls/salt/channels/gpg-keys.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes.oholecek.translate_gpg_url_to_proxy
Forward port of https://github.com/SUSE/spacewalk/pull/24317
Translate gpg url if url has server name and client behind proxy
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API …
=> Translate gpg url if url has server name and client behind proxy 

web/html/src/branding/css/base/tables.less, web/html/src/branding/css/base/tables.scss
Revert changes for table > btn-group class
No difference.
Before:
After:
Issue(s): # …
=> Reverted back changes in table btn-group class

web/html/src/manager/admin/config/monitoring-admin.tsx, web/spacewalk-web.changes.bisht-richa.remove-bare-metal-systems-tab
Removed Bare-metal systems tab from the Manager Configuration section
No difference.
Before:
After:
Fixes: https://github.com/SUSE/spacewalk/issues/24519
Check [How …
=> Removed Bare-metal systems tab from Manager Configuration page

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, web/html/src/branding/css/susemanager/components/inputs.scss, web/html/src/branding/css/susemanager/components/text.scss, web/html/src/branding/css/susemanager/index.scss, web/html/src/components/coco-attestation/CoCoSettingsForm.tsx, web/html/src/core/spa/view-helper.ts, web/spacewalk-web.changes.bisht-richa.fix-SSM-subpages-layout
Fixed layout in ssm subpages
No difference.
Before:
After:
Issue(s): #https://github.com/uyuni-project/uyuni/issues/8726
Fixes: https://github.com/uyuni-project/uyuni/issues/8726 …
=> Review fix ssm subpages

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, web/html/src/branding/css/susemanager/components/panels.suma.scss, web/html/src/branding/css/susemanager/components/panels.uyuni.scss, web/html/src/core/spa/view-helper.ts, web/spacewalk-web.changes.bisht-richa.fixed-system-formulas-config-layout
Fixed broken layout of system formulas configuration page
No difference.
Before:
Hover state
After:
Hover state
Fixes: https://github.com/uyuni-project/uyuni/issues/8733 …
=> Fixed broken layout of system formulas configuration page

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, web/html/src/branding/css/susemanager/components/panels.scss, web/html/src/core/spa/view-helper.ts, web/spacewalk-web.changes.bisht-richa.fixed-missing-table-footer-border
Fixed table footer border 
No difference.
Before:
After:
- No tests
Fixes: https://github.com/uyuni-project/uyuni/issues/8737 …
=> Fixed table footer top border

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, web/html/src/branding/css/susemanager/components/buttons.scss, web/html/src/core/spa/view-helper.ts, web/html/src/manager/state/display-highstate.tsx, web/spacewalk-web.changes.bisht-richa.fixed-system-highstate-page-layout
Fix system highstate page layout
No difference.
Before:
After:
Fixes: https://github.com/uyuni-project/uyuni/issues/8731 …
=> Fixed broken layout of system highstate page

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, web/html/src/branding/css/susemanager/components/label.scss, web/html/src/branding/css/susemanager/index.scss, web/html/src/core/spa/view-helper.ts, web/spacewalk-web.changes.bisht-richa.fixed-badge-color-salt-key-page
Fix badge style in salt key table
No difference.
Before:
After:
Fixes: https://github.com/uyuni-project/uyuni/issues/8734 …
=> Added label css

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, web/html/src/branding/css/base/forms.scss, web/html/src/core/spa/view-helper.ts, web/spacewalk-web.changes.bisht-richa.fixed-missing-margin-cve-list
Fix missing margins in the CVE audit 
No difference.
Before:
After:
Fixes: https://github.com/uyuni-project/uyuni/issues/8758 …
=> Fixed missing margins in CVE audit

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, java/code/webapp/WEB-INF/pages/audit/scap/xccdfsearch.jsp, web/html/src/core/spa/view-helper.ts, web/spacewalk-web.changes.bisht-richa.fixed-open-scap-search-page-layout
Fixed OpenSCAP search page layout
No difference.
Before:
After:
Fixes: https://github.com/uyuni-project/uyuni/issues/8760 …
=> Fixed OpenSCAP search page layout

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, web/html/src/components/icontag.tsx, web/html/src/core/spa/view-helper.ts, web/html/src/manager/maintenance/details/schedule-details.tsx, web/html/src/manager/maintenance/list/maintenance-windows-list.tsx, web/html/src/manager/recurring/recurring-actions-list.tsx, web/spacewalk-web.changes.bisht-richa.fixed-double-padding-irecurring-actions
Fix double padding in the recurring actions table
No difference.
Before:
After:
Fixes: [#](https://github.com/uyuni-project/uyuni/issues/8761) …
=> Fixed double padding in recurring actions

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, web/html/src/core/spa/view-helper.ts, web/html/src/manager/admin/config/monitoring-admin.tsx, web/spacewalk-web.changes.bisht-richa.fixed-broken-layout-monitoring-page
Fixed broken layout in monitoring page
No difference.
Before:
After:
Fixes: https://github.com/uyuni-project/uyuni/issues/8768 …
=> Fixed broken layout in monitoring page

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, java/code/webapp/WEB-INF/pages/admin/scheduleDetail.jsp, java/spacewalk-java.changes.eth.inputs-and-friends, web/html/src/branding/css/susemanager/components/buttons.suma.scss, web/html/src/branding/css/susemanager/components/inputs.less, web/html/src/branding/css/susemanager/components/inputs.scss, web/html/src/branding/css/susemanager/components/legend.scss, web/html/src/branding/css/susemanager/components/modal.less, web/html/src/branding/css/susemanager/components/modal.scss, web/html/src/branding/css/susemanager/index.scss, web/html/src/components/datetime/DateTimePicker.tsx, web/html/src/core/spa/view-helper.ts, web/spacewalk-web.changes.eth.inputs-and-friends
This PR fixes a number of issues which were all visible on the schedule creation page: the page had alignment issues, disabled input styles were incorrect, input groups were not aligned properly, etc. In short, this fixes https://github.com/uyuni-project/uyuni/issues/8735, https://github.com/uyuni-project/uyuni/issues/8754 and https://github.com/uyuni-project/uyuni/issues/8822.
Before:
After:
- Docs issue already exists.
- No tests: UI bugfixes.
Fixes https://github.com/uyuni-project/uyuni/issues/8735
Fixes https://github.com/uyuni-project/uyuni/issues/8754
Fixes https://github.com/uyuni-project/uyuni/issues/8822 …
=> Fix schedule creation layouts, disabled input styles, input group alignment on the updated theme

java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml, java/spacewalk-java.changes.welder.fix-duplicate-packages-appstreams
Packages linked to app streams where appearing duplicate in the installable, removable and upgradable lists when the app stream is provided by multiple channels, even when these channels don't have any relationship with the system. This PR adapt the queries to fix this wrong behavior.
No difference.
Before:
After:
Issue(s): #
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelog …
=> Fix appstreams queries to avoid duplicate packages

java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/spacewalk-java.changes.cbosdo.ks-cancel
See title
No difference.
- No tests: 
Issue(s): https://github.com/SUSE/spacewalk/issues/23641
Port(s): https://github.com/SUSE/spacewalk/pull/24947 …
=> Add info URL to autoinstallation to cleanup the cobbler profile once done

java/code/src/com/suse/manager/webui/utils/ViewHelper.java, java/code/webapp/WEB-INF/pages/admin/setup/proxy-settings.jsp, web/html/src/branding/css/base/forms.scss, web/html/src/branding/css/base/setup-wizard.less, web/html/src/branding/css/base/setup-wizard.scss, web/html/src/branding/css/susemanager/components/buttons.less, web/html/src/branding/css/susemanager/components/buttons.scss, web/html/src/branding/css/susemanager/components/inputs.scss, web/html/src/branding/css/susemanager/components/modal.scss, web/html/src/branding/css/susemanager/components/text.scss, web/html/src/core/spa/view-helper.ts, web/html/src/manager/admin/setup/products/products-scc-dialog.tsx
Fixes numerous layout issues on the setup wizard page.
- No documentation needed: Docs issue already exists.
- No tests: UI work …
=> Migrate HTTP proxy, fix setup wizard layout issues

testsuite/features/support/env.rb
With this, we can open a browser on the controller by sshing to it with `ssh -X FQDN` and executing `chromium`. After that we can type the following into the search bar: `chrome://inspect` which will show the active remote targets. For this, we additionally need the `xauth` package on the controller. See the following sumaform PR.	
Related sumaform PR: https://github.com/uyuni-project/sumaform/pull/1654
Below you can see the current headless test suite and what it currently does by attaching to it via the debugging port.
No difference.
Issue(s): #
Ports(s): # Manager 4.3: …
=> QE: Add Chromedriver debugging port

testsuite/features/profiles/cloud_aws/Docker/Dockerfile, testsuite/features/profiles/internal_nue/Docker/Dockerfile, testsuite/features/profiles/internal_prv/Docker/Dockerfile
Missing call to "make" in the profiles.
No ports, Uyuni only.
=> Partial revert of f21851be1e50

testsuite/features/support/commonlib.rb, testsuite/features/support/env.rb, testsuite/features/support/network_utils.rb, testsuite/features/support/remote_node.rb
Handling a reboot of a remote node through net-ssh, plus fixing scp command
No difference.
No ports …
=> Handling a reboot of a remote node through net-ssh, plus fixing scp command

testsuite/features/secondary/srv_mainpage.feature
Fix user in srv_mainpage
No difference.
No ports …
=> Fix user in srv_mainpage

testsuite/features/step_definitions/content_lifecycle_steps.rb
Fix selection of channel in the sources of a CLM
No difference.
Ported together with qe-develop …
=> Fix selection of channel in the sources of a CLM

testsuite/features/support/file_management.rb
When we generate temporary files, the content injected was not flush.
So we were copying an empty file.
This was for instance causing an important issue in our test environment due to the fact that [local repositories were removed when we apply highstate.](https://documentation.suse.com/suma/5.0/en/suse-manager/client-configuration/repositories.html#_local_repository_locations)
No difference.
No ports, ported with qe-develop …
=> Flush generated temporary file

python/spacewalk/satellite_tools/spacewalk-data-fsck, python/spacewalk/spacewalk-backend.changes.mczernek.spacewalk-data-fsck-orphaned-pkgs
`spacewalk-data-fsck` can print a lot of `File path mismatch` messages for RPMs that are orphaned. Customers should be able to remove those RPMs, since orphaned RPMs are not served to clients.
Even if customers do not want to remove the orphaned RPMs, they should know why there's the `file path mismatch` error. 
Related to: https://bugzilla.suse.com/show_bug.cgi?id=1227882
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/25067
Issue(s): https://github.com/SUSE/spacewalk/issues/24852
Port(s): 
- 4.3: …
=> Make spacewalk-data-fsck aware of orphaned pkgs

spacewalk/setup/bin/spacewalk-setup, spacewalk/setup/spacewalk-setup.changes.mbussolotto.setup_cobbler
check return code of `spacewalk-setup-cobbler`
No difference. …
=> spacewalk-setup should stop if spacewalk-setup-cobbler fails (bsc#1226847)

testsuite/features/support/env.rb
We saw some issues with this in the 5.0.1 BV. I am not entirely sure, yet, if it was really due to that, but the error messages were indicating it.
```bash
disconnected: not connected to DevTools
(failed to check if window was closed: disconnected: not connected to DevTools)
(Session info: chrome-headless-shell=125.0.6422.141)
(Driver info: chromedriver=125.0.6422.141 (0000000000000000000000000000000000000000-0000000000000000000000000000000000000000),platform=Linux 5.14.21-150500.55.73-default x86_64) (Selenium::WebDriver::Error::WebDriverError)
./features/support/commonlib.rb:172:in `refresh_page'
(...)
```
Added with https://github.com/uyuni-project/uyuni/pull/9170.
No difference.
Issue(s): …
=> QE: Allow Chromium debugging port only in CI

java/code/src/com/redhat/rhn/frontend/action/systems/SystemSearchHelper.java, java/spacewalk-java.changes.welder.bsc1228412
This PR fixes the following error in system search: `java.lang.IllegalArgumentException: Comparison method violates its general contract!`
The previous approach used `Math.abs(score1 - score2) < .001` to account for slight differences, which could lead to inconsistent results in certain situations. For example, if score1 is slightly less than score2 but within the .001 threshold, the method would treat them as equal. However, if score2 is compared to another score, score3, that is just slightly more than .001 greater than score1, the transitive property required by the general contract of `compareTo` would be violated, leading to scenarios where A > B, B > C, and A < C, which is inconsistent.
No difference.
ℹ️ If a major new functionality is added, it …
=> Improve score comparison to avoid violating Comparator contract in System Search

testsuite/features/support/file_management.rb
The owner of top.sls was root, this was causing issues during the onboarding.
No difference.
Ported together with qe-develop …
=> Fix permissions on injected salt pillars

web/html/src/manager/audit/cveaudit/cveaudit.tsx
Fix an error that causes CVE Auditing of images to fail
Issue(s): #
Port(s): # 
=> Fix CVE Audit not working for images

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml, java/spacewalk-java.changes.mc.bsc-1225603
When clicking on the URL, nothing happens. It would be better anyway when this gets open into a new tab
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24495
Port(s): https://github.com/SUSE/spacewalk/pull/25092 https://github.com/SUSE/spacewalk/pull/25091 …
=> open bootstrap script directory URL in a new page

susemanager-sync-data/channel_families.json, susemanager-sync-data/susemanager-sync-data.changes.mc.Manager-4.3-add-channel_family-extsec
New Channel Family for SLES 12 SP5 LTSS Extended Security
Port(s): https://github.com/SUSE/spacewalk/pull/25036
=> add new channel family SLES-12-SP5-LTSS-Extended-Security-X86

spacewalk/certs-tools/mgr_ssl_cert_setup.py
Fix https://github.com/uyuni-project/uyuni/pull/9164
where these lines were removed by accident
=> readd parser lines which were removed by accident

testsuite/features/build_validation/migration/salt_migration_minion_migration.feature
Stop button is not visible with the new way of clicking on preview button.
Align this step scenario with similar scenario in our test.
No difference.
Port :
If …
=> Fix run command scenario for salt migration BV

testsuite/podman_runner/20_get_server_logs.sh
Fix upload artifacts step of the acceptance tests workflow.
No difference.
- No tests
Issue(s): fixes https://github.com/SUSE/spacewalk/issues/24909 …
=> Ci fix upload artifacts

.github/workflows/acceptance_tests_common.yml
Split filter into multiple filters, so that exclusion works.
Fixes https://github.com/SUSE/spacewalk/issues/24975
=> CI: fix filter files

testsuite/dockerfiles/buildhost/Dockerfile, testsuite/dockerfiles/buildhost/etc_pam.d_sshd, testsuite/dockerfiles/container-registry-auth/Dockerfile, testsuite/dockerfiles/container-registry/Dockerfile, testsuite/dockerfiles/rocky-minion/Dockerfile, testsuite/dockerfiles/server-all-in-one-dev/Dockerfile, testsuite/dockerfiles/ubuntu-minion/Dockerfile
Update dockerfiles prior to merge https://github.com/uyuni-project/uyuni/pull/9287
=> CI: Update dockerfiles prior to merge pull 9287

.github/workflows/build_containers.yml, testsuite/dockerfiles/controller-dev/Dockerfile
fix controller container
update workflow to build new containers: registries and buildhost
No difference.
- No tests
required by https://github.com/uyuni-project/uyuni/pull/9287 …
=> ci: update container build worklfow

containers/server-image/Dockerfile, containers/server-image/server-image.changes.mbussolotto.ha
add HANA and cluster formulas to server image
Testing it here : https://build.opensuse.org/package/show/home:mbussolotto:branches:systemsmanagement:Uyuni:Master/server-image
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentati …
=> add HANA and cluster formulas to server image

schema/spacewalk/susemanager-schema.changes.mbussolotto.ol9_schema_migration, schema/spacewalk/upgrade/susemanager-schema-4.4.3-to-susemanager-schema-4.4.4/000-uyuni-fix-ol9-repos.sql
see description 
No difference.
ℹ️ If a …
=> During schema upgrade, avoid insert problem when Extern - Oracle Linux 9 is not present (bsc#1230021)

java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml, java/code/src/com/redhat/rhn/common/finder/test/JarFinderTest.java
We will build our container soon with Leap 15.6. We should use the same jars available from there.
No difference.
- No tests: **for development** …
=> update IVY config to Leap 15.6

testsuite/features/secondary/min_retracted_patches.feature
this is failing in master. Let's skip it for now to give us time to debug.
No difference.:
- No tests
n/a
Check …
=> Skip failing test in master retracted patches

susemanager-sync-data/additional_products.json, susemanager-sync-data/additional_repositories.json, susemanager-sync-data/susemanager-sync-data.changes.lucidd.ubuntu-24.04
adds ubuntu 24.04 product data
No difference.
- No tests
Issue(s): https://github.com/SUSE/spacewalk/issues/23932
Port(s): https://github.com/SUSE/spacewalk/pull/25321 https://github.com/SUSE/spacewalk/pull/25334
If you need to …
=> add ubuntu 24.04

uyuni/uyuni-storage-setup/scripts/mgr-storage-proxy, uyuni/uyuni-storage-setup/scripts/mgr-storage-server, uyuni/uyuni-storage-setup/scripts/susemanager-storage-setup-functions.sh, uyuni/uyuni-storage-setup/uyuni-storage-setup.changes.oholecek.no-partition-for-storage
This comes from premium support suggestion.
Filesystem can be created directly on the block storage. Script is using whole disk anyway so partition adds needless complication when disk in virtual environment is expanded.
As a sideeffect this fixes using storage on LVM drive.
No difference.
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the …
=> Do not create partition on extra storage disk

java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataProcessor.java, java/spacewalk-java.changes.rmateus.5.0_change_heades_for_localhost_payg
Port of: https://github.com/SUSE/spacewalk/pull/25342/
No difference.
Issue(s): no issue
Port(s): https://github.com/SUSE/spacewalk/pull/25342/ …
=> change payg localhost product indentifier

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes.mcalmer.ubuntu2404-sumatoolbox-update
Add bootstrap repo definitions for SUSE Manager products. This is not needed for Uyuni, but for future branches for the SUSE Manager product.
Addition to: https://github.com/uyuni-project/uyuni/pull/8504 …
=> Ubuntu2404 sumatoolbox update

testsuite/features/secondary/min_salt_openscap_audit.feature
Fixes openSCAP path for the SLES minion as well
Port(s): # 
Followup of https://github.com/SUSE/spacewalk/pull/25411 for the original https://github.com/uyuni-project/uyuni/pull/9290
=> QE: Fix openscap path for SLES

testsuite/documentation/manual-cucumber.md
Move manual cucumber to Github instead of [Gitlab](https://gitlab.suse.de/galaxy/testplan/-/blob/master/manual-cucumber.md).
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/21855
Port(s): 
4.3 port: https://github.com/SUSE/spacewalk/pull/25407
5.0 port: https://github.com/SUSE/spacewalk/pull/25408
If you don't …
=> Move manual cucumber to GH

testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/step_definitions/navigation_steps.rb
In sle update pipeline, I can see the stage is green even if we have spinning sign: 
Check there are not spinning sign after the reposync stage.
Fix an issue where the check after the repository synchronization is always passing even if we have failing reposync.
The page is not loaded when we do the check.
Also add a verification that we have green stick. It will make sure we have at least one repository sync.
Also make the condition more straight forward ( unless + no_xpath => if + xpath )
No difference.
Issue: …
=> Make sure the product page is loaded

schema/reportdb/uyuni-reportdb-schema.changes.raul.fix_uyuni_reportdb_schema
Fix a missing reportdb migration that was breaking the schema, see: https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-master-dev-reportdb-schema-migration-test-pgsql/
After this PR is merged, I'll need to tag again.
No difference.
None …
=> Add a migration path for reportdb schema to 5.1.1 and 5.1.2

schema/spacewalk/common/tables/suseISSHub.sql, schema/spacewalk/common/tables/suseISSPeripheral.sql, schema/spacewalk/common/tables/suseISSPeripheralChannels.sql, schema/spacewalk/common/tables/tables.deps, schema/spacewalk/upgrade/susemanager-schema-5.1.1-to-susemanager-schema-5.1.2/001-issv3-add-tables.sql
Initial ISSv3 Database Schema
No difference.
- https://github.com/SUSE/spacewalk/issues/25359
Issue(s): https://github.com/SUSE/spacewalk/issues/25347
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-mer …
=> Issv3 db schema

java/code/src/com/redhat/rhn/domain/formula/FormulaFactory.java, java/spacewalk-java.changes.oholecek.add_mac_naming
Understand MAC terminal naming formula value and translate to correct kernel option. This is part is for containerized part.
Related PRs:
Non-containerized: https://github.com/SUSE/salt-formulas/pull/224
Initrd update: https://github.com/uyuni-project/retail/pull/170
No difference.
- API documentation added: please review the Wiki page …
=> Add new MAC based saltboot terminal naming

java/code/webapp/WEB-INF/includes/advertisements.jsp, java/conf/rhn_java.conf
See title
No difference.
- No tests: removal of unused code
Issue(s): #
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-an …
=> Remove the remaining unused dev chat JSP and config

.gitignore, .vscode/README.md, .vscode/launch.json.template, .vscode/settings.json, scripts/generate-vscode-workspace.sh
This is a demo of how to use VSCode workspace files so we can both have default configs and also the ability to change, override, etc.  
Please feel free to try it out and let me know if there's any use case this doesn't cover or anything that's missing. If we find that this doesn't work well or is too cumbersome, we can always try and find a different solution.  
Also, @Serp1co please review what you'd like to see in `settings.json` from the Java side, for now I just used what you pasted on Slack as testing values.
No difference.
Before:
After:
- Documentation issue was created: [Link for SUSE Manager …
=> VSCode workspace usage demo

microservices/coco-attestation/attestation-core/pom.xml, microservices/coco-attestation/attestation-core/src/test/java/com/suse/coco/attestation/AttestationQueueProcessorTest.java, microservices/coco-attestation/attestation-module-snpguest/src/main/java/com/suse/coco/module/snpguest/SNPGuestWorker.java, microservices/uyuni-java-common/pom.xml, microservices/uyuni-java-common/src/main/java/com/suse/common/concurrent/UnboundedGrowingThreadPoolExecutor.java, microservices/uyuni-java-common/src/main/java/com/suse/common/configuration/BaseConfigurationSource.java, microservices/uyuni-java-common/src/test/java/com/suse/common/concurrent/UnboundedGrowingThreadPoolExecutorTest.java, microservices/uyuni-java-parent/pom.xml
This PR introduces [Awaitility](http://www.awaitility.org), a new **test-only** dependency to handle and simplify async code in tests. This change is meant to ease async code testing and reduce flakyness.
No difference. …
=> Introduced Awaitility to handle async test code

testsuite/features/support/env.rb
For CI, we are now creating a user for each feature. We don't want this behavior for BV but we don't want to use admin either for smoke test.
This change will keep the current user and not overwrite it with admin.
By default, the current_user is going to be admin: 
https://github.com/uyuni-project/uyuni/blob/3eced2828ac9a2c743e3b55950721fe27a01c465/testsuite/features/support/env.rb#L51-L52
And this value will be set during this code if needed: https://github.com/uyuni-project/uyuni/blob/61c6cea2dda5955f9ba26d1135b456e69e27920b/testsuite/features/step_definitions/api_common.rb#L140-L153
For example for BV smoke test.
No difference.
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the …
=> QE: Create user only for certains feature, otherwise keep the same user

java/code/src/com/redhat/rhn/frontend/action/common/DownloadFile.java, java/spacewalk-java.changes.mbussolotto.npe_kickstart
Fix NPE if child channel has no parent (bsc#1231053)
No difference. …
=> Fix NPE if child channel has no parent (bsc#1231053)

java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml, java/spacewalk-java.changes.rmateus.Manager-4.3
port of: https://github.com/SUSE/spacewalk/pull/25490/commits
No difference.
Before:
After: …
=> Not present duplicated package on XML-RPC API endpoint(bsc#1231430

.devcontainer/test/Dockerfile, .devcontainer/test/bashrc, .devcontainer/test/devcontainer.json
Fix the devcontainer for testing
No difference.
- No tests
Ports:
- Manager-5.0 …
=> QE: Fix the devcontainer for testing

testsuite/features/step_definitions/command_steps.rb, testsuite/features/step_definitions/system_monitoring_steps.rb, testsuite/features/support/commonlib.rb, testsuite/features/support/constants.rb, testsuite/features/support/remote_node.rb, testsuite/features/support/system_monitoring.rb
Adding an extra check into the reposync.log file when we wait for a channel to be synchronized.
Additionally this PR adds a missing channel into sles15sp4 product on Uyuni product version.
And not relevant, but on the new debugging mode that allow us to select the API protocol, I disabled ssl verification, so we can debug it easly from our local machines.
No difference.
Ports:
- Manager-5.0
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni- …
=> Refactor wait reposync

java/code/src/com/redhat/rhn/common/util/http/HttpClientAdapter.java
fix "error: unmappable character"
=> fix syntax error

testsuite/features/reposync/srv_sync_channels.feature, testsuite/features/reposync/srv_sync_products.feature, testsuite/features/step_definitions/command_steps.rb
Refresh the product before starting the Feature: Synchronize products in the products page of the Setup Wizard.
If we don't refresh the product first, we see all the products available and this create testsuite issues.
See: https://github.com/SUSE/spacewalk/issues/25796
This change will also align with spacewalk project: https://github.com/SUSE/spacewalk/blob/5da8041fef4ff809d8091fe14700dc035eb5e641/testsuite/features/build_validation/reposync/srv_sync_all_products.feature#L6-L7
No difference.
Port: No ports needed, changes already on 4.3 and 5.0 …
=> Trigger a mgr-sync refresh at the beginning of reposync feature

web/html/javascript/spacewalk-essentials.js, web/html/javascript/susemanager-setup-wizard-proxy-settings.js, web/spacewalk-web.changes.welder.bsc1231852
Port of https://github.com/SUSE/spacewalk/pull/25624
No difference.
- No tests: legacy js code
Issue(s): https://github.com/SUSE/spacewalk/issues/25631
Port(s): https://github.com/SUSE/spacewalk/pull/25624 …
=> Validate proxy hostname format and escape proxy username to mitigate XSS vulnerabilities

java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml, search-server/spacewalk-search/buildconf/obs-maven-config.yaml, search-server/spacewalk-search/ivy.xml
httpclient and httpcore was updated
Also bcel, commons-lang3 and xalan-j2
Port(s): https://github.com/SUSE/spacewalk/pull/25821
=> update httpclient and other java libs

java/code/src/com/suse/manager/webui/controllers/PackageController.java, java/spacewalk-java.changes.cbosdo.all-software-fix
server_name is a copy-paste issue when copying the code from the systems page.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/25889 bsc#1233450
Port(s): https://github.com/SUSE/spacewalk/pull/25904 https://github.com/SUSE/spacewalk/pull/25905
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuy …
=> Fix wrong default sort column name in managed packages list

susemanager-sync-data/additional_products.json, susemanager-sync-data/susemanager-sync-data.changes.mcalmer.update-scc-sync-data
See title
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/25976 https://github.com/SUSE/spacewalk/pull/25977 …
=> Set Ubuntu 24.04 as released

containers/server-image/Dockerfile, containers/server-image/server-image.changes.vzhestkov.add-saline-formula-to-server-container
Add `saline-formula` package to the server container to make it possible to use with the web UI.
No difference.
Before:
After:
- No documentation needed: TBD
- No tests: just new formula to the server image, nothing to test here
Issue(s): # …
=> Add `saline-formula` to the server image

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes.mcalmer.micro61-for-uyuni, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes.mcalmer.micro61-for-uyuni
Add SL Micro 61 and openSUSE Leap Micro 6.1 repositories
No difference.
- Part of the EPIC
Issue(s): https://github.com/SUSE/spacewalk/issues/25802
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-prope …
=> Micro61 for uyuni

README.md
This is just an update for the README regarding the rename of the Uyuni downstream product (SUSE Manager -> SUSE Multi-Linux Manager).
No difference.
- No documentation needed: just a README update
- No tests: just a README update
=> Update README (Multi-Linux Manager)

proxy/proxy/salt-broker/salt-broker, proxy/proxy/spacewalk-proxy.changes.vzhestkov.salt-broker-opts-strict-and-verbose
There was a missing conditional part in the code which was causing issues on some of the deployments of the proxies because `XPUB_VERBOSE` and `XPUB_VERBOSER` opts were accidentally missing to be set on `XPUB` socket, what could cause connection loss to the minions behind the proxy in some unknown conditions.
Besides of the fix which prevents losing the opts on the socket, this PR implementing more verbose debug output to make it more noticible that the required opts are missing on the socket.
No difference.
- No tests: It's not possible to create proper test for it as the exact conditions of the issues are still unknown and it's not possible to reproduce them with the tests.
Tracks: …
=> Make socket opt setting more strict and verbose (bsc#1229286)

java/code/src/com/suse/manager/webui/services/pillar/MinionGeneralPillarGenerator.java, java/spacewalk-java.changes.mcalmer.fix-ubuntu-signed-by, susemanager-utils/susemanager-sls/salt/channels/channels.repo, susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.fix-ubuntu-signed-by
Fix regressions introduced by https://github.com/uyuni-project/uyuni/pull/9548
Belongs to: https://github.com/uyuni-project/uyuni/pull/9548
Port(s): 
=> Fix ubuntu signed by

java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml, java/manager-build.xml
Some java packages were updated and we need the new versions in IVY.
Port(s): https://github.com/SUSE/spacewalk/pull/26129
=> Update obs mvn dependencies

java/spacewalk-java.changes, java/spacewalk-java.changes.deneb-alpha.ivyChangelog, java/spacewalk-web.changes.bisht-richa.table-filters-description-fix
Add missing changelogs for #9593 and #8791.
**Please note, in #8791, the  partial  changelog file has  been created  with the wrong file name and tito didn't collect it correctly in `spacewalk-java.changes`, but the file has been left hanging around.  The code  changes have been already merged and delivered. This PR also changes directly the main `spacewalk-java.changes` for adding the missing entry.
A failure in the changelog tests is expected.**
No difference.
- No tests: just changelog fixes
Issue(s): https://github.com/SUSE/spacewalk/issues/25675
Related: #9593 and #8791 …
=> Add missing changelogs for #9593 and #8791

utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes.mcalmer.sle15-sp7-uyuni
Add Uyuni Client Tools for 2 upcoming products
- SL Micro 6.2
- SUSE Linux Enterprise 15 SP7 family
No difference.
- Part of the EPIC
Issue(s): https://github.com/SUSE/spacewalk/issues/26171
Port(s): not needed - uyuni only …
=> Add Uyuni Client Tools for SL Micro 6.2 and SLE 15 SP7 family

java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java, java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java, java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java, java/code/src/com/redhat/rhn/manager/distupgrade/DistUpgradeManager.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/webapp/WEB-INF/pages/systems/spmigration/spmigration-confirm.jsp, java/spacewalk-java.changes.mcalmer.product-migration-sles2sap, susemanager-utils/susemanager-sls/salt/channels/init.sls, susemanager-utils/susemanager-sls/salt/distupgrade/init.sls, susemanager-utils/susemanager-sls/salt/distupgrade/sap.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.product-migration-sles2sap
Implement SLES to SLES for SAP migration 
No difference.
- https://github.com/SUSE/spacewalk/issues/26049
Issue(s): https://github.com/SUSE/spacewalk/issues/26049
Port(s): No backports …
=> Product migration sles to sles for sap

testsuite/dockerfiles/opensuse-minion/Dockerfile
fix  testsuite/features/secondary/srv_push_package.feature
No difference.
Before:
After: …
=> CI: install mgr-push into opensuse minion

testsuite/features/step_definitions/command_steps.rb, testsuite/features/support/remote_node.rb
Revert https://github.com/uyuni-project/uyuni/pull/9637 and my follow-up https://github.com/uyuni-project/uyuni/pull/9640 .
PR 9637 breaks completely the test suites, due in particular to these upstream problems:
* https://github.com/moby/moby/issues/8513
* https://github.com/containers/podman/issues/9718
I tried to work around those problems, but it takes too much time and I am not even sure it can be acheived. I am reverting as we must move forward and have results.
Please re-merge  https://github.com/uyuni-project/uyuni/pull/9637 only once somùeone tested it does not break anymore the test suites.
Ports:
* 5.0: https://github.com/SUSE/spacewalk/pull/26248
* 4.3: https://github.com/SUSE/spacewalk/pull/26249
=> Revert fix mix output mgrctl

java/code/src/com/suse/manager/hub/SyncController.java, java/code/src/com/suse/manager/xmlrpc/iss/IssHandler.java
=> Issv3 fixes

testsuite/features/step_definitions/setup_steps.rb, testsuite/features/support/commonlib.rb, testsuite/features/support/file_management.rb
Improve how we obtain dev repositories, so it works under certain conditions, like repositories behind our minima mirror infrastructure.
No difference.
Ports:
- Manager-4.3
- Manager-5.0
If you need to …
=> QE: Improve how we obtain dev repositories

testsuite/run_sets/init_clients.yml
=> Remove the min_virthost feature from init_clients run set

python/rhn/rhnlib.changes.deneb-alpha.51alpha2_webui, spacewalk/config/spacewalk-config.changes.deneb-alpha.51alpha2_webui, web/conf/rhn_web.conf
- current version before tagging  of  `schema/spacewalk/susemanager-schema.spec`  is `5.1.2`
- there are changes to be tagged and there's  a path `schema/spacewalk/upgrade/susemanager-schema-5.1.2-to-susemanager-schema-5.1.3`. -> Nothing to be done
- also the migration from 5.0.X to 5.1.0 exists. -> Nothing to be done
please note:
~~~
Error: Changelog not added for package spacewalk-web
Error: Changelog added without changes for package rhnlib
Error: Changelog added without changes for package spacewalk-config
~~~
Are  expected.  
* The missing changelog on `spacewalk-web` for the version bump is not relevant for customers and there are other commits  to be tagged.  I skip it on purppose.
* The other two  changelogs  were missing nd reported  by  tito-wrapper.  So, also in this case, they …
=> Increase WebUI version and provide missing changelogs

java/code/src/com/suse/manager/webui/controllers/DownloadController.java
Sonarcloud suggested to sanitize the channel name
No difference.
=> sanitize the channel name

health-check/MANIFEST.in, health-check/pyproject.toml, health-check/src/uyuni_health_check/config.py, health-check/src/uyuni_health_check/config.toml, health-check/src/uyuni_health_check/config/grafana/alerts.yaml, health-check/src/uyuni_health_check/config/grafana/datasources.yaml, health-check/src/uyuni_health_check/config/prometheus/prometheus.yml, health-check/src/uyuni_health_check/config/templates/grafana_dashboard/supportconfig_with_logs.template.json, health-check/src/uyuni_health_check/config/templates/promtail/promtail.yaml.j2, health-check/src/uyuni_health_check/containers/manager.py, health-check/src/uyuni_health_check/containers/promtail/complete_checker.py, health-check/src/uyuni_health_check/exporters/exporter.py, health-check/src/uyuni_health_check/grafana/grafana_manager.py, health-check/src/uyuni_health_check/loki/loki_manager.py, health-check/src/uyuni_health_check/main.py, health-check/src/uyuni_health_check/utils.py
In this PR, I'm refactoring a number of things, notably I have:
- Added config.toml values and ensured that the values are used.
- This means also removing hardcoded image names, network name, etc.
- Unified verbose and quiet parameters, we now use only verbose.
- Added method typing.
- Fixed a few sonarcloud warnings.
- Remove "Uyuni" from container names. 
Note: This PR targets the `health-check-skeleton` branch, **not** `master`. …
=> [health-check] Code style and flow refactor

web/html/src/build/fill-spec-file.js, web/spacewalk-web.spec
See title, empty strings were not handled.
No difference.
- No tests: build tooling …
=> Fix license string merging

testsuite/features/init_clients/buildhost_bootstrap.feature
Undo temporary hack now Ondrej's code is merged
Port(s): none, head only
=> Re-enable build host events check

susemanager/bin/mgr-setup, susemanager/susemanager.changes.oholecek.prevent_selinux_by_writing_to_tmp
To prevent SELinux category problems when writing outside volumes
No difference.
- No tests: covered by sanity checks
Issue(s): #
If you need to …
=> Write new pg_hba.conf directly in correct dir

testsuite/features/step_definitions/setup_steps.rb
Adapt HTTP proxy test to UI change.
Port(s):
* 5.0: https://github.com/SUSE/spacewalk/pull/26333
=> Adapt HTTP proxy test to UI change

web/html/src/package.json, web/html/src/yarn.lock
Housekeeping for Dependabot, bump versions to the latest release.
No difference.
- No tests: build tooling
Fixes: https://github.com/uyuni-project/uyuni/security/dependabot/243
Fixes: https://github.com/uyuni-project/uyuni/security/dependabot/242 …
=> Update `webpack-cli` and `cross-spawn`

testsuite/features/reposync/srv_sync_products.feature
Remove duplicated scenarios
No difference.
- Cucumber tests were removed
Ports:
- Manager-4.3
- Manager-5.0 …
=> QE: Remove duplicated scenarios

.github/workflows/acceptance_tests_common.yml
Fix wrong path for recommended_tests.yml
No difference.
- No tests
No ports …
=> Fix wrong path for recommended_tests.yml

testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/reposync/srv_sync_products.feature
Follow-up of https://github.com/uyuni-project/uyuni/pull/9743
Port(s): none, HEAD only
=> More select or deselect of beta client tools

java/code/src/com/redhat/rhn/domain/credentials/SCCCredentials.java, java/code/src/com/redhat/rhn/frontend/action/satellite/SetupWizardAction.java, java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/NetworkDtoSerializer.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/sync/content/ContentSyncHandler.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/sync/content/test/ContentSyncHandlerTest.java, java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java, java/code/src/com/redhat/rhn/taskomatic/task/MgrSyncRefresh.java, java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygUpdateHostsTask.java, java/code/src/com/redhat/rhn/taskomatic/task/repomd/DebPackageWriter.java, java/code/src/com/suse/manager/api/test/TestHandler.java, java/code/src/com/suse/manager/hub/DefaultHubInternalClient.java, java/code/src/com/suse/manager/hub/test/HubManagerTest.java, java/code/src/com/suse/manager/matcher/MatcherRunner.java, java/code/src/com/suse/manager/webui/controllers/ProductsController.java, java/code/src/com/suse/manager/webui/controllers/admin/AdminViewsController.java, java/code/src/com/suse/manager/webui/controllers/admin/mappers/PaygResponseMappers.java, java/code/src/com/suse/manager/webui/controllers/admin/templates/payg_list.jade, java/conf/rhn_java.conf, java/spacewalk-java.changes.mcalmer.issv3-disable-pages, web/html/src/manager/admin/list-payg/list-payg.renderer.tsx, web/html/src/manager/admin/list-payg/list-payg.tsx, web/html/src/manager/admin/setup/products/products.tsx, web/spacewalk-web.changes.mcalmer.issv3-disable-pages
We need to disable some pages when we are a Peripheral server
- Admin => Setup Wizard => Organization Credentials
- Admin => Setup Wizard => Products
- Admin => Setup Wizard => Payg Connections
Before:
After:
- Part of the ISSv2 docs
Issue(s): https://github.com/SUSE/spacewalk/issues/25356 …
=> Issv3 disable pages

testsuite/features/reposync/allcli_update_activationkeys.feature
Adds Uyuni client tools on the Build Host AK
No difference.
Ports:
- Manager-4.3
- Manager-5.0 …
=> QE: Adds Uyuni client tools on the Build Host AK

java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/spacewalk-java.changes.rmateus.m50-1236011-fqdn-Proxy
Port of: https://github.com/SUSE/spacewalk/pull/26292
No difference.
Before:
After: …
=> Proxy server fqdn merge java filter (bsc#1236011)

java/code/src/com/suse/manager/xmlrpc/admin/AdminPaygHandler.java, java/spacewalk-java.changes.mcalmer.fix-api-namespace
The API namespace was wrong shown in the docs.
No difference.
- This change the docs
Port(s): https://github.com/SUSE/spacewalk/pull/26427 https://github.com/SUSE/spacewalk/pull/26428 …
=> Fix API namespace for AdminPaygHandler

susemanager-sync-data/additional_products.json, susemanager-sync-data/susemanager-sync-data.changes.mcalmer.amazon-linux-2023-bsrepo, susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes.mcalmer.amazon-linux-2023-bsrepo
Add bootstrap repository data for Amazon Linux 2023
No difference.
- Part of the Epic
Issue(s): https://github.com/SUSE/spacewalk/issues/26172
Ports: None (5.1 only) …
=> Add bootstrap repository data for Amazon Linux 2023

testsuite/features/reposync/srv_create_bootstrap_repositories.feature
Force creating bootstrap repositories
No difference.
Ports:
- Manager-4.3
- Manager-5.0 …
=> QE: Force creating bootstrap repositories

java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java, java/code/src/com/redhat/rhn/domain/channel/test/ChannelFactoryTest.java, java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java, java/code/src/com/redhat/rhn/manager/content/MgrSyncUtils.java, java/code/src/com/suse/manager/hub/HubController.java, java/code/src/com/suse/manager/hub/HubManager.java, java/code/src/com/suse/manager/hub/HubSparkHelper.java, java/code/src/com/suse/manager/hub/test/ControllerTestUtils.java, java/code/src/com/suse/manager/hub/test/HubControllerTest.java, java/code/src/com/suse/manager/model/hub/ChannelInfoJson.java, java/code/src/com/suse/manager/model/hub/CustomChannelInfoJson.java, java/code/src/com/suse/manager/model/hub/ModifyCustomChannelInfoJson.java
I added an API endpoint to modifycustom channels in the peripheral server.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/25353
Port(s): 
=> Issv3: new api to modify custom channels in the peripheral

java/code/src/com/suse/manager/hub/HubManager.java, web/html/src/components/hub/AddTokenButton.tsx, web/html/src/components/hub/index.tsx
Fix issues detected by sonarcloud
No difference.
Before:
After: …
=> Issv3 fix sonarcloud issues

testsuite/features/reposync/allcli_update_activationkeys.feature, testsuite/features/reposync/srv_create_dev_channels.feature, testsuite/features/reposync/srv_sync_dev_channels.feature, testsuite/features/secondary/allcli_action_chain.feature, testsuite/features/secondary/min_action_chain.feature, testsuite/features/secondary/min_check_patches_install.feature, testsuite/features/secondary/min_recurring_action.feature, testsuite/features/secondary/min_salt_install_package.feature, testsuite/features/secondary/min_salt_install_with_staging.feature, testsuite/features/secondary/min_salt_software_states.feature, testsuite/features/secondary/minssh_action_chain.feature, testsuite/podman_runner/03_run_controller_and_registry_and_buildhost.sh, testsuite/podman_runner/10_run_sshminion.sh, testsuite/podman_runner/12_run_salt_sle_minion.sh, testsuite/podman_runner/13_run_salt_rhlike_minion.sh, testsuite/podman_runner/14_run_salt_deblike_minion.sh
Fix flaky reposync by using mirrored repos. Otherwise, trying to pull from opensuse.org makes this unstable, because of the time needed to download too many packages, and the issue that metadata could be unsync with the content of the opensuse mirror.
No difference.
- No tests
Issue(s): #
If …
=> CI: fix flaky reposync by using mirrored repos

schema/spacewalk/susemanager-schema.changes.serpico.password-policy-hotfix, schema/spacewalk/upgrade/susemanager-schema-5.1.3-to-susemanager-schema-5.1.4/101-default-settings-updates.sql
Take excluded value instead of already stored one (update defaults with new pre-set to avoid possible null values) 
No difference.
Before:
After:
Issue(s): #
=> Password policy hotfix

web/html/src/components/hub/TokenTable.tsx
Sonarcloud fix
No difference.
Before:
After: …
=> Issv3 sonarcloud 2

java/buildconf/ivy/ivy-suse.xml, java/buildconf/ivy/obs-maven-config.yaml
Netty was updated in OBS and we need to adapt the version
No difference.
- No tests: **fixes tests**
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properl …
=> update ivy to new netty version

.github/workflows/git-checks.yml
Fixes the warnings we see with the `block-fixup` workflow.
See https://github.com/actions/checkout/releases
No difference.
- Cucumber tests were added/edited
Issue(s): #
Port(s): # none
If …
=> Update actions/checkout to recent version

web/conf/rhn_web.conf
Change WebUI versions for MLM to 5.1.0 Beta1 and 2025.03 for Uyuni.
Also checked the schema upgrade paths:
Before: 5.1.0 Alpha2 or Uyuni 2024.12
After: 5.1.0 Beta1 or Uyuni 2025.03
Issue(s): https://github.com/SUSE/spacewalk/issues/26544
https://github.com/SUSE/spacewalk/issues/26151 …
=> Bump WebUI versions for 5.1.0 Beta1 and Uyuni 2025.03

python/health-check/README.md, python/health-check/pyproject.toml
During renaming, I forgot to rename the scripts names as well.
=> [health-check] rename execution scripts

java/code/src/com/redhat/rhn/domain/channel/ChannelArch.java, java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java, java/code/src/com/redhat/rhn/manager/content/MgrSyncUtils.java, java/code/src/com/suse/manager/matcher/MatcherJsonIO.java, java/code/src/com/suse/scc/model/SCCProductJson.java, java/spacewalk-java.changes.mcalmer.introduce-arm64
Introduce new debian architecture `arm64`
No difference.
=> handle architecture arm64

.github/workflows/acceptance_tests_common.yml
This PR fixes issues with conditional checks using `env.skip` in the `acceptance-tests-common` workflow. Previously, `env.skip` was not properly evaluated in `if:` conditions, causing certain steps to execute even when they should have been skipped.
Steps should now correctly skip execution when `skip=true`.
No unintended execution of jobs when recommended tests exceed limits.
No difference.
- No tests
No ports
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyu …
=> Fix the skip of recommended tests

testsuite/dockerfiles/server-all-in-one-dev/Dockerfile
Add missing backslash on the Dockerfile
No difference.
- No tests
No ports …
=> Fix typo on server-all-in-one-dev dockerfile

java/code/src/com/redhat/rhn/common/db/datasource/ModeFactory.java
This PR addresses and resolves unchecked types warnings related to the use of PackageMetadata in the ModeFactory.java file.
No difference.
Before:
After:
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) …
=> Fix unchecked types warning around PackageMetadata(Update ModeFactory.java)

testsuite/dockerfiles/server-all-in-one-dev/Dockerfile
Change wget by curl on server-all-in-one-dev Dockerfile
No difference.
- No tests
No ports …
=> Change wget by curl on server-all-in-one-dev Dockerfile

testsuite/features/secondary/srv_reportdb.feature
This test is failing... we need to investigate, but meanwhile, let's skip it.
No difference.
- No tests
N/A …
=> CI: skip reportdb failing test

java/code/src/com/redhat/rhn/domain/action/ActionFactory.java, java/code/src/com/redhat/rhn/domain/action/Action_legacyUser.hbm.xml, java/code/src/com/redhat/rhn/domain/action/SupportDataAction.java, schema/spacewalk/common/data/rhnActionType.sql, schema/spacewalk/susemanager-schema.changes.mcalmer.supportdata-db, schema/spacewalk/upgrade/susemanager-schema-5.1.5-to-susemanager-schema-5.1.6/001-supportdata-action-type.sql
Implement DB and Hibernate changes for new supportdata feature
No difference.
- https://github.com/SUSE/spacewalk/issues/26620
- No tests: **just basic definitions - will be tested later with real code**
Issue(s): https://github.com/SUSE/spacewalk/issues/26615 …
=> Supportdata db

containers/proxy-salt-broker-image/prepare_target.sh, containers/proxy-salt-broker-image/proxy-salt-broker-image.changes.meaksh.master-use-salt-based-on-python311, containers/server-saline-image/Dockerfile, containers/server-saline-image/server-saline-image.changes.meaksh.master-use-salt-based-on-python311
This PR should fix the issues found building container after moving Salt to Python 3.11.
Since Salt is now only based on Python 3.11, we need to adjust the Dockerfile to target the right packages.
Since Salt is now based on Python 3.11, this makes the environment to contains both 3.6 and 3.11 python versions. This was messing the bash script that prepares the image. The mechanism is now enhanced.
No difference.
- No tests: **no actual codebase changes**
Issue(s): https://github.com/SUSE/spacewalk/issues/26544 …
=> Fix some issues after moving Salt to Python 3.11

testsuite/podman_runner/20_get_server_logs.sh
Fix rename supportconfig tarball
No difference.
- No tests
No ports …
=> Fix rename supportconfig tarball

testsuite/dockerfiles/ubuntu-minion/Dockerfile
packages is called xz-utils
No difference.
- No tests
N/A …
=> ci: fix ubuntu build

testsuite/features/support/env.rb
This PR is the aftermath of the support of SLE 15 SP7 on HEAD, one line was forgotten
None, head only.
=> Fix forward port to HEAD

testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/reposync/allcli_update_activationkeys.feature, testsuite/features/reposync/srv_sync_channels.feature, testsuite/features/reposync/srv_sync_products.feature, testsuite/features/support/constants.rb
Rename MLM tools in testsuite
No difference.
Issue(s): Fixes https://github.com/SUSE/spacewalk/issues/25943
Port(s): constants.rb needs porting to 5.0 and 4.3 to keep branches aligned …
=> Rename MLM tools in testsuite

.github/workflows/acceptance_tests_common.yml, .github/workflows/acceptance_tests_feedback.yml, .github/workflows/automatic-frontend-lint-fix-pr.yml, .github/workflows/build_containers.yml, .github/workflows/build_controller_test_container.yml, .github/workflows/changelogs.yml, .github/workflows/check_translations.yml, .github/workflows/external_pr_labeler.yml, .github/workflows/frontend-dependency-audit.yml, .github/workflows/frontend-lint.yml, .github/workflows/git-checks.yml, .github/workflows/java-checkstyle.yml, .github/workflows/java-microservices-mvn-build.yml, .github/workflows/javascript-build.yml, .github/workflows/javascript-unit-tests.yml, .github/workflows/labeler.yml, .github/workflows/python-checkstyle.yml, .github/workflows/recommended_tests.yml, .github/workflows/rubocop.yml, .github/workflows/salt-sls-files-checks.yml, .github/workflows/schema-migration-reportdb-test-pgsql.yml, .github/workflows/sonarcloud.yml, .github/workflows/stale.yml, .github/workflows/susemanager-sls-unit-tests.yml, .github/workflows/typescript-compilation.yml, .github/workflows/update_translations.yml, .github/workflows/yard-doc-test-framework.yml
One of the recommendations of the [Good security practices for using GitHub Actions features](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions?learn=getting_started).
For each action I went to the repository and used the last released version for the major version we were using, and specified the exact version with a comment.
If we were using master, I pinned to the latest commit.
I added some warnings about things to be reviewed later. The purpose of this PR is pinning to commits only.
No difference.
- No documentation needed: Adjustement on the GitHub actions.
- No tests: No …
=> Pin all GitHub actions to a commit

testsuite/features/reposync/srv_sync_products.feature, testsuite/features/support/constants.rb
Remove old client tools instead of appending, fix sp7 string to add `(BETA)`.
The design decision was to append the new client tools instead of replacing so we can keep constants.rb file aligned in all branches. But the problem is that we then have the old client tools empty in 5.1 and we need to add them to the list to be ignored. But that causes the constants file to be not aligned anyway so it doesn't make sense. So better to remove the old ones completely.
No difference.
Issue(s): no issue, directly from testsuite review
Port(s): no ports needed …
=> Remove old client tools instead of appending, fix sp7 string

.github/workflows/acceptance_tests_base.yml
Fix typo on tests base workflow
=> Fix typo on tests base workflow

susemanager/susemanager.changes.deneb-alpha.51_shebang_fix, susemanager/susemanager.spec
Follow-up from https://github.com/uyuni-project/uyuni/pull/10032 due to `server-image` failing to build with:
~~~
Problem: 1: nothing provides '/usr/bin/python311' needed by the to be installed susemanager-tools-5.1.6-150700.1.1.x86_64
~~~
Use the right Python3.11 shebang and the right python interpreter and, given that we are at this, adjust also the rebranding introducing the `produtprettyname` macro
No difference.
- Tests in:
- IBS: https://build.suse.de/project/show/home:deneb_alpha:branches:Devel:Galaxy:Manager:Head_vendor-salt-utils-versions-looseversion
- OBS: https://build.opensuse.org/project/show/home:deneb_alpha:branches:systemsmanagement:Uyuni:Master_vendor-salt-utils-versions-looseversion
Issue(s): …
=> Use correct Python version and related shebang (bsc#1239859)

.github/workflows/susemanager-sls-unit-tests.yml, susemanager-utils/susemanager-sls/src/tests/test_module_container_runtime.py
Use our Salt test container for Github Check
Our container contains the correct Python version and the test dependencies. We don't need to download them from PyPI during test execution and know that the right versions are used.
Need to check if the test pass in Github Actions (works locally)
Issue(s): # …
=> Use our Salt test container for Github Check

web/html/src/manager/login/login.tsx
Fixes SonarCloud issues with a potential security hotspot
No difference.
- No tests needed
Issue(s): https://github.com/uyuni-project/uyuni/issues/9878
=> SonarCloud security hotspot fix: using https instead of http

.github/workflows/acceptance_tests_base.yml
Follow RFC for hostnames and have a test domain. Otherwise, tests fail.
No difference.
- No tests
Needed for https://github.com/SUSE/spacewalk/issues/25948 …
=> CI: fix container registry names

java/code/src/com/redhat/rhn/manager/audit/CVEAuditManagerOVAL.java, java/code/src/com/suse/oval/OVALCleaner.java, java/code/src/com/suse/oval/OsFamily.java, java/code/src/com/suse/oval/vulnerablepkgextractor/UbuntuVulnerablePackageExtractor.java, java/code/src/com/suse/oval/vulnerablepkgextractor/VulnerablePackagesExtractors.java, java/spacewalk-java.changes.rmateus.m50-oval-ubuntu-support, susemanager-sync-data/oval.config.json, susemanager-sync-data/susemanager-sync-data.changes.rmateus.m50-oval-ubuntu-support
Enhance OVAL CVE analysis to also support Ubuntu OS.
No difference.
- Documentation: @admd will handle it, and PR for the overall OVAL support will be added in a future PR.
- API documentation: Not needed
- No tests: It's on tech preview only, and test will be added in the future. Until there, it was manually tested.
Issue(s): #
Port(s): https://github.com/SUSE/spacewalk/pull/26789 …
=> Uyuni oval ubuntu support

testsuite/features/build_validation/add_non_MU_repositories/rocky8_minion_add_iso.feature, testsuite/features/build_validation/init_clients/monitoring_server.feature, testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/reposync/srv_sync_channels.feature, testsuite/features/reposync/srv_sync_products.feature, testsuite/features/secondary/srv_cobbler_sync.feature, testsuite/features/secondary/srv_menu_filter.feature, testsuite/features/secondary/srv_restart.feature, testsuite/features/secondary/srv_task_status_engine.feature, testsuite/features/secondary/srv_users.feature
Only for 5.1 and leave texts from RPM packages as they do not change also the general product detection Uyuni vs. SUSE Manager was not changed
This change also the product extensions for 15 SP7 even if they not exist yet any may get an additional suffix.
No difference. …
=> change products and names to SUSE Multi-Linux Manager in the testsuite

proxy/proxy-html/spacewalk-proxy-html.changes.abid.fix-rebranding-issus, proxy/proxy-html/suse_proxy/index.html
Use the new name for  the proxy
No difference.
Before:
After:
Issue(s): # …
=> Rebrand the proxy name in index file

.github/dependabot.yml
Update only minor and major versions of github-actions.
Warning:
I was forced to do an additional change due to this error:
No ports
=> Update only minor and major versions of github-actions

utils/spacewalk-manage-channel-lifecycle, utils/spacewalk-utils.changes.mcalmer.Manager-5.0-fix-cert-error-running-in-container
spacewalk-manage-channel-lifecycle run inside of the container.
In this case it should connect to localhost and use plain HTTP to prevent SSL errors
Also basic linting was applied. Even if this tool is deprecated
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/26792 …
=> Fix cert error running in container (bsc#1240023)

.github/workflows/acceptance_tests_coordinator.yml, .github/workflows/acceptance_tests_parallel.yml, .github/workflows/acceptance_tests_recommended.yml, .github/workflows/acceptance_tests_sequential.yml
Reverts uyuni-project/uyuni#10033
```
Run peter-evans/repository-dispatch@v3
Error: Resource not accessible by integration
```
We can't use GITHUB_TOKEN from the base repo on the fork repo :S 
I'm gonna keep researching how to achieve it.
=> Revert "Refactor to run the GH validation on the fork's runner"

containers/proxy-httpd-image/Dockerfile
This is a follow-up of #10108.
Now we control the name of the release notes package for the proxy using the ARG PXYRELEASENOTESPKG. It's default is Uyuni and reads as release-notes-uyuni-proxy, but it's value can be adapted from the project config on the build service
After this PR, on the Prjconf of Multi-Linux Manager, we need to also specify the different value we want to pass.
`BuildFlags: dockerarg:PXYRELEASENOTESPKG=release-notes-multi-linux-manager-proxy`
With this PR, the default installed package is the Uyuni version, but on other products like Multi-Linux Manager we can have the branded version.
We already have the changelog entry from #10108 and in this case there's no need to additionally pollute the .changes
No difference.
- No documentation needed: only internal and user …
=> Pass the release notes package name as argument

.github/workflows/acceptance_tests_base.yml
Tests were triggered when any file was modified, because of
`!testsuite/features/buildvalidation`
This was matching for any file that was not inside this dir. For example, the issue template. This was very unconvenient and paintful to have to wait for the acceptance tests for any modification, plus the resources we were wasting.
We need to filters, one for a modification happening on any of the java or js files, one for modifications that were happening when the files were in testsuite but not in build_validation.
The first one, requires the default predicate `any`. The second one, the predicate `every`.
Then, you can combine the result of the 2 filters.
No difference.
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new …
=> CI: fix path filters

java/code/src/com/redhat/rhn/domain/audit/XccdfTestResult.java, java/spacewalk-java.changes.mbussolotto.XccdfTestResultEntity, testsuite/features/secondary/min_deblike_openscap_audit.feature, testsuite/features/secondary/min_rhlike_openscap_audit.feature
Fix OpenSCAP audit acceptance tests: comparableId field was missing in XccdfTestResult
No difference.
- Documentation issue was created: [Link for SUSE Multi-Linux Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- (OPTIONAL) …
=> Fix OpenSCAP audit acceptance tests: comparableId field was missing in XccdfTestResult

uyuni/base/uyuni-base.spec
When building as unpriviledged user creating directories with specific owner result in an operation not permitted error
```
[   50s] + install -d -m 0775 -o wwwrun -g www /home/abuild/rpmbuild/BUILDROOT/uyuni-base-5.1.1-150751.2.1.testorion.x86_64//var/spacewalk/systems
[   50s] install: cannot change owner and permissions of '/home/abuild/rpmbuild/BUILDROOT/uyuni-base-5.1.1-150751.2.1.testorion.x86_64//var/spacewalk/systems': Operation not permitted
```
No difference.
Port(s): 
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repos …
=> define directory owner via attributes

java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ChannelInfoJsonSerializer.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/OrgInfoJsonSerializer.java, java/code/src/com/suse/manager/xmlrpc/iss/HubHandler.java
Fix API doc generation
No difference.
=> Issv3 2 fix api doc

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml, java/code/src/com/suse/manager/hub/migration/IssMigrator.java, java/code/src/com/suse/manager/hub/migration/test/IssMigratorTest.java, java/code/src/com/suse/manager/webui/Router.java, java/code/src/com/suse/manager/webui/controllers/admin/AdminViewsController.java, java/code/src/com/suse/manager/webui/controllers/admin/beans/MigrationEntryDto.java, java/code/src/com/suse/manager/webui/controllers/admin/handlers/HubApiController.java, java/code/src/com/suse/manager/webui/controllers/admin/templates/hub_migrate_v1.jade, java/code/src/com/suse/manager/webui/controllers/admin/templates/hub_migrate_v2.jade, java/code/src/com/suse/manager/webui/controllers/admin/templates/list_peripherals.jade, java/code/src/com/suse/manager/webui/menu/MenuTree.java, java/spacewalk-java.changes.mackdk.issv3-migration-ui, web/html/src/components/hub/MigrateSlavesForm.tsx, web/html/src/components/hub/ModalEditButton.tsx, web/html/src/components/hub/index.tsx, web/html/src/components/hub/types.tsx, web/html/src/components/input/InputBase.tsx, web/html/src/components/large-text-attachment.tsx, web/html/src/manager/admin/hub/migrate-from-v1.renderer.tsx, web/html/src/manager/admin/hub/migrate-from-v2.renderer.tsx, web/html/src/manager/admin/hub/peripherals.renderer.tsx, web/html/src/manager/admin/hub/peripherals.tsx, web/html/src/manager/admin/index.ts, web/spacewalk-web.changes.mackdk.issv3-migration-ui
This PR adds a new button to migrate existing ISS v1 and v2 configurations to ISS V3. 
After:
- Documentation WIP
- No unit tests: already covered
Issue(s): https://github.com/SUSE/spacewalk/issues/25357 …
=> ISSv3 - UI for ISS Migration

containers/doc/README.md
No difference.
Before:
After:
- Documentation issue was created: [Link for SUSE Multi-Linux Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new). …
=> docs: fix typo

testsuite/features/support/env.rb
Reduce verbosity of Selenium logs on Debug Mode
No difference.
- No tests
Ports:
- Manager-4.3
- Manager-5.0 …
=> Reduce verbosity of Selenium logs on Debug Mode

susemanager-utils/susemanager-sls/src/modules/supportdata.py, susemanager-utils/susemanager-sls/src/tests/test_module_supportdata.py
When any kind of excpetion is thrown when doing cp.push, we just return the path to the master and let it download the files via scp.
Add also support for Debian (at least Ubuntu uses also sosreport)
No difference. …
=> Fix supportdata module

testsuite/features/build_validation/init_clients/alma8_ssh_minion.feature, testsuite/features/build_validation/init_clients/alma9_ssh_minion.feature, testsuite/features/build_validation/init_clients/centos7_ssh_minion.feature, testsuite/features/build_validation/init_clients/debian12_ssh_minion.feature, testsuite/features/build_validation/init_clients/liberty9_ssh_minion.feature, testsuite/features/build_validation/init_clients/opensuse156arm_ssh_minion.feature, testsuite/features/build_validation/init_clients/oracle9_ssh_minion.feature, testsuite/features/build_validation/init_clients/rhel9_ssh_minion.feature, testsuite/features/build_validation/init_clients/rocky8_ssh_minion.feature, testsuite/features/build_validation/init_clients/rocky9_ssh_minion.feature, testsuite/features/build_validation/init_clients/sle12sp5_ssh_minion.feature, testsuite/features/build_validation/init_clients/sle15sp2_ssh_minion.feature, testsuite/features/build_validation/init_clients/sle15sp3_ssh_minion.feature, testsuite/features/build_validation/init_clients/sle15sp4_ssh_minion.feature, testsuite/features/build_validation/init_clients/sle15sp5_ssh_minion.feature, testsuite/features/build_validation/init_clients/sle15sp5s390_ssh_minion.feature, testsuite/features/build_validation/init_clients/sle15sp6_ssh_minion.feature, testsuite/features/build_validation/init_clients/slemicro51_ssh_minion.feature, testsuite/features/build_validation/init_clients/slemicro52_ssh_minion.feature, testsuite/features/build_validation/init_clients/slemicro53_ssh_minion.feature, testsuite/features/build_validation/init_clients/slemicro54_ssh_minion.feature, testsuite/features/build_validation/init_clients/slemicro55_ssh_minion.feature, testsuite/features/build_validation/init_clients/ubuntu2004_ssh_minion.feature, testsuite/features/build_validation/init_clients/ubuntu2204_ssh_minion.feature, testsuite/features/init_clients/sle_ssh_minion.feature
Remove workaround for bsc#1222108.
This bug was closed as RESOLVED WORKSFORME, saying the issue was gone.
No difference.
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/26991
* 5.0: https://github.com/SUSE/spacewalk/pull/26990
=> Remove workaround for bsc#1222108

java/code/src/com/suse/manager/webui/controllers/SystemsController.java, java/code/src/com/suse/manager/webui/utils/PageControlHelper.java, java/code/src/com/suse/manager/webui/utils/test/PageControlHelperTest.java, java/spacewalk-java.changes.cbosdo.bsc1239826
Only keep the letters, digits hyphen and underscore in the user inputs to avoid Java script code execution.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26702 https://github.com/SUSE/spacewalk/issues/26887
Port(s): https://github.com/SUSE/spacewalk/pull/26751 https://github.com/SUSE/spacewalk/pull/26750 …
=> CVE-2025-23393, CVE-2025-23392: Filter user input in (virtual) systems lists pages (bsc#1239826), (bsc#1240386)

.github/workflows/acceptance_tests_scheduler.yml
We need to fix the scheduled jobs after this refactor
https://github.com/uyuni-project/uyuni/pull/10164
No difference.
- No tests
N/A …
=> CI: Fix scheduled jobs

testsuite/features/build_validation/reposync/srv_sync_all_products.feature
Fix product names for reposync.
No difference.
Cucumber tests were added
Port(s):
* 5.0: https://github.com/SUSE/spacewalk/pull/27027
* 4.3: https://github.com/SUSE/spacewalk/pull/27028
=> Fix product names

susemanager-branding-oss/susemanager-branding-oss.changes.deneb-alpha.MLM51-rebrand-skelcd, susemanager-branding-oss/susemanager-branding-oss.spec
The rebrand to Multi-Linux Manager requires also to adapt the EULA files we include in our containers.
Unfortunately, given that 15-SP7 will be soon GA, we can't postpone this change, but we need to implement it now.
Considering that the skelcd  is used in several other products, the  change on that  package will  be minimal,  and will only cover the bits  needed to rebrand Multi-Linux Manager 5.1,  without affecting  old SUSE Manager versions.
More  details are  also covered in https://github.com/SUSE/spacewalk/issues/26948
No difference.
- No documentation needed: no additional documentation needed.
- No tests: no tests to be added, but the …
=> Use rebranded skelcd-EULA-multi-linux-manager-server

java/code/src/com/redhat/rhn/domain/notification/types/ManagerVersion.java, java/code/src/com/redhat/rhn/domain/notification/types/UpdateAvailable.java, java/code/src/com/redhat/rhn/domain/notification/types/test/ManagerVersionTest.java, java/code/src/com/redhat/rhn/domain/notification/types/test/UpdateAvailableTest.java
Downstream PR had some comments that lead to: 
- renaming certain identifiers to use more  terminology better aligned with naming conventions;
- minor adjustments on version update code, introducing a "ManagerVersion" object to improve structure
No difference.
Port(s): # https://github.com/SUSE/spacewalk/pull/25383 …
=> Sync version update code

java/code/src/com/suse/manager/webui/controllers/login/templates/login.jade, java/code/webapp/WEB-INF/decorators/layout_error.jsp, java/code/webapp/WEB-INF/decorators/layout_head.jsp, java/spacewalk-java.changes.eth.bsc1240984, web/html/src/build/webpack.config.js, web/spacewalk-web.changes.eth.bsc1240984
Currently we correctly bust cache for the main entry points of scripts and assets:
https://github.com/uyuni-project/uyuni/blob/3d603f16df37b7f785369f4289e9daa912193b4e/java/code/webapp/WEB-INF/decorators/layout_head.jsp#L72
However, chunks created by Webpack, so submodules, updated branding assets that are imported further down the tree, etc, do not get busted. Since the ids are nondeterministic, we've previously missed the issue since it apparently just worked out in our favor.
This changeset adds hashes to chunk names for production builds to fix the issue.
No difference.
- No tests: should pass existing …
=> Ensure browser cache is busted when newer assets are available (bsc#1240984)

testsuite/features/step_definitions/docker_steps.rb
If the list of images is empty, try again instead of failing the test because it can take a few seconds to appear.
No difference.
- No tests …
=> Testsuite: fix docker build tests

proxy/proxy/httpd-conf/spacewalk-proxy.conf, proxy/proxy/spacewalk-proxy.changes.eth.bsc1241094, spacewalk/config/etc/httpd/conf.d/zz-spacewalk-www.conf, spacewalk/config/spacewalk-config.changes.eth.bsc1241094
Disable directory listing for everything besides /pub.
No difference.
- No documentation needed: config change
- No tests: should pass all existing tests
https://bugzilla.suse.com/show_bug.cgi?id=1241094 …
=> Disable directory listing (bsc#1241094)

containers/server-image/Dockerfile, containers/server-image/root/usr/lib/postfix/systemd/config_postfix, containers/server-image/server-image.changes.mbussolotto.postfix_persist
Persist postfix configuration flag also in /etc/postfix
No difference.
- Documentation issue was created: [Link for SUSE Multi-Linux Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new). …
=> Persist postfix configuration flag also in /etc/postfix (bsc#1239744)

testsuite/features/secondary/min_deblike_salt_install_package.feature, testsuite/features/secondary/min_deblike_salt_install_with_staging.feature, testsuite/features/secondary/min_retracted_patches.feature, testsuite/features/secondary/min_rhlike_salt_install_package_and_patch.feature, testsuite/features/secondary/min_salt_pkgset_beacon.feature
Fix some package related features that were failing before enabl
No difference.
- No tests
Issue(s): https://github.com/SUSE/spacewalk/issues/26921 …
=> CI: fix other package related features

java/code/src/com/redhat/rhn/domain/image/ImageInfoFactory.java, java/code/src/com/redhat/rhn/domain/notification/types/ManagerVersion.java, java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java, java/code/src/com/redhat/rhn/domain/server/ServerFactory.java, java/code/src/com/redhat/rhn/frontend/action/renderers/setupwizard/MirrorCredentialsRenderer.java, java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java, java/code/src/com/suse/manager/webui/controllers/StatesAPI.java, java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java, java/code/src/com/suse/manager/webui/websocket/Notification.java, java/code/src/com/suse/manager/webui/websocket/WebsocketSessionConfigurator.java, java/spacewalk-java.changes.mcalmer, testsuite/features/secondary/srv_maintenance_windows.feature, uyuni/base/uyuni-base.changes.mcalmer, uyuni/base/uyuni-base.spec
Fix 3 bugs found in the testsuite
- ~https://bugzilla.suse.com/show_bug.cgi?id=1241908~
- https://bugzilla.suse.com/show_bug.cgi?id=1241907
- https://bugzilla.suse.com/show_bug.cgi?id=1241906
No difference. …
=> Mc bugfixes

java/code/src/com/suse/manager/utils/PagedSqlQueryBuilder.java, java/code/src/com/suse/manager/utils/test/PagedSqlQueryBuilderTest.java, java/code/src/com/suse/manager/webui/controllers/SystemsController.java, java/code/src/com/suse/manager/webui/controllers/test/SystemsControllerTest.java, java/code/src/com/suse/manager/webui/templates/systems/all-list.jade, java/code/src/com/suse/manager/webui/templates/systems/virtual-list.jade, java/code/src/com/suse/manager/webui/utils/PageControlHelper.java, java/code/src/com/suse/manager/webui/utils/test/PageControlHelperTest.java, java/spacewalk-java.changes.cbosdo.systems-list-fix, web/html/src/manager/systems/all-list.renderer.tsx, web/html/src/manager/systems/virtual-list.renderer.tsx, web/spacewalk-web.changes.cbosdo.systems-list-fix
Silently removing all dangerous characters in the paging filter leads to impossible or invalid searches (bsc#1242004).
Instead of stripping down any character that is not a digit, letter, dash or underscore at the `PageControlHelper` level, divide the fix into two:
- Write the strings URL-encoded in the HTML page. Using `"#{query}"` in the jade template encodes the `"` and avoids string escape. To allow searches using `<` or `>` the string is then URL-decoded in the TS renderer.
- Strip any character that is not a letter, digit, dot, dash or underscore in sort and filter columns in the `PagedSqlQueryBuilder`.
This should be a reasonable assumption for an postgresql column identifier.
With those two fixes combined we have a proper fix for CVE-2025-23393 and CVE-2025-23392 as well as …
=> Better handling of systems lists filtering

testsuite/features/secondary/srv_virtual_host_manager.feature
Solves a test that is failing found during the rrtg tasks
No difference.
Issue(s): None
Port(s): 
- Manager 5.0
- Manager 4.3
- 
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-an …
=> QE: Solving Delete Virtual Host Manager test

testsuite/features/secondary/srv_maintenance_windows.feature
This PR solves a testsuite error found during the rrtgs tasks of a test that fails for testsuite fault.
No difference.
Issue(s): None
Port(s): None …
=> QE: Solving maintenance windows feature 

java/code/src/com/redhat/rhn/domain/common/RhnConfigurationFactory.java, java/code/src/com/suse/manager/webui/controllers/admin/handlers/PasswordPolicyController.java, java/code/src/com/suse/manager/webui/controllers/admin/service/PasswordPolicyService.java, java/spacewalk-java.changes.serpico.Manager-5.0-MU-5.0.4-password-policy-fix-2, web/html/src/manager/admin/password-policy/password-policy.tsx, web/spacewalk-web.changes.serpico.Manager-5.0-MU-5.0.4-password-policy-fix-2
backport of https://github.com/SUSE/spacewalk/pull/26962 and https://github.com/SUSE/spacewalk/pull/26949
No difference.
Issue(s): # https://github.com/SUSE/spacewalk/issues/26945
Port(s): # https://github.com/SUSE/spacewalk/pull/26962 and https://github.com/SUSE/spacewalk/pull/26949  …
=> Backport password policy bugfix bsc#1240960

java/tito.props, python/spacewalk/tito.props
Take care that a minimal schema version is available for java and backend
=> update the required DB schema versions for some packages

testsuite/features/secondary/srv_mainpage.feature
The EULA document has been moved from the frontage to the documentation.
No difference.
Issue(s): None
Port(s):It just applies to 5.1
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-bra …
=> QE: Adding an automated test that ensures that EULA is reachable by

java/code/src/com/suse/manager/utils/SaltUtils.java
Mainly use the proxies where the minion is connected through as jumhosts by compiling the `ProxyCommand` for the ssh options.
Special ssh tunnel options should not be needed as we do ssh commands and not use a different protocol.
No difference.
- No tests - hard to test without cucumber and a real upload. But this would pollute the upload server with useless data
Issue(s): https://github.com/SUSE/spacewalk/issues/26617 …
=> Supportdata ssh tunnel

rel-eng/chart_push.sh, rel-eng/container_push.sh, web/conf/rhn_web.conf
-  Bump the WebUI version to 5.1.0 RC and 2025.05 (https://github.com/SUSE/spacewalk/issues/27146)
- schema and reportdb migration paths are fine
-  Change the default registry namespace of Multi-Linux Manager 5.1 (https://github.com/SUSE/spacewalk/issues/27195)
Please note, this requires changes to uyuni-tools too (https://github.com/uyuni-project/uyuni-tools/pull/579).
Before: `5.1.0 Beta2` / `2024.04`
After: `5.1.0 RC` / `2024.05`
- Documentation issue was created - Epic GH issue will follow soon:
- **documentation needs review due to default namespace change**. 
- **documentation needs review due to RPM names of containers changed (air-gapped installations)**.
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the …
=> Change the default registry namespace of Multi-Linux Manager 5.1

client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes.deneb-alpha.51RC_fix_changes, spacecmd/spacecmd.changes.deneb-alpha.51RC_fix_changes, susemanager/susemanager.changes.deneb-alpha.51RC_fix_changes, susemanager/uyuni-setup-reportdb.changes.sbluhm.multiplepgsql
This PR adds missing changelogs and drops a leftover one from an old PR already merged.
- **dropped**: `susemanager/uyuni-setup-reportdb.changes.sbluhm.multiplepgsql` due to wrong file name. [Introduced in this commit](https://github.com/uyuni-project/uyuni/pull/8083/commits/86a2879eef0b4db0a885e53d17742af9f28d5d7f). Code changes have been already merged in https://github.com/uyuni-project/uyuni/pull/8083 and there's no point in adding that  info back in the old changelog.
- **added**:
- `client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes.deneb-alpha.51RC_fix_changes`
- `spacecmd/spacecmd.changes.deneb-alpha.51RC_fix_changes`
- `susemanager/susemanager.changes.deneb-alpha.51RC_fix_changes`
**Please, also  note that  the  failures on the changelog tests  are expected:**
~~~ …
=> Multi-Linux Manager 5.1 RC: add missing changelog entries and drop leftover one

java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java, java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java, java/code/src/com/suse/manager/hub/test/ControllerTestUtils.java, java/code/src/com/suse/manager/hub/test/HubControllerTest.java, java/code/src/com/suse/manager/model/hub/ChannelInfoDetailsJson.java, java/code/src/com/suse/manager/webui/controllers/DownloadController.java, java/code/src/com/suse/scc/SCCEndpoints.java, java/spacewalk-java.changes.mcalmer.issv3-fix-channel-sync
Channel syncronization from a hub server to a peripheral failed for custom channels.
The last component is not the SCCID, but the channel name.
Additionally the token for custom channels include the wrong Org and caused 
Forbidden: Token does not provide access to channel
errors
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27167 https://github.com/SUSE/spacewalk/issues/27181
If you uncheck …
=> Issv3 fix channel sync (bsc#1242889, bsc#1242324)

java/code/src/com/redhat/rhn/taskomatic/task/ForwardRegistrationTask.java, java/code/src/com/redhat/rhn/taskomatic/task/test/ForwardRegistrationTaskTest.java, java/code/src/com/suse/manager/webui/utils/SparkApplicationHelper.java, java/code/src/com/suse/manager/webui/utils/gson/ResultJson.java, java/code/src/com/suse/scc/SCCEndpoints.java, java/code/src/com/suse/scc/SCCSystemRegistrationManager.java, java/code/src/com/suse/scc/proxy/SCCProxyFactory.java, java/code/src/com/suse/scc/proxy/SCCProxyManager.java, java/code/src/com/suse/scc/proxy/SCCProxyRecord.java, java/code/src/com/suse/scc/proxy/SccProxyStatus.java, schema/spacewalk/postgres/class/scc_proxy_status_t.sql, schema/spacewalk/upgrade/susemanager-schema-5.1.6-to-susemanager-schema-5.1.7/600-create_suseSccProxy.sql
Implement the endpoint for accepting virtualization_host requests and forward them to SCC.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27056 …
=> receive and handle virtualization_host requests on a Hub

java/code/src/com/redhat/rhn/domain/action/supportdata/UploadGeoType.java, java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml, java/code/src/com/redhat/rhn/frontend/strings/nav/StringResource_en_US.xml, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java, java/code/src/com/suse/manager/webui/Router.java, java/code/src/com/suse/manager/webui/controllers/MinionController.java, java/code/src/com/suse/manager/webui/controllers/MinionsAPI.java, java/code/src/com/suse/manager/webui/templates/minion/support-data.jade, java/code/src/com/suse/manager/webui/utils/gson/SupportDataRequest.java, java/code/src/com/suse/manager/webui/utils/gson/UploadRegion.java, java/code/src/com/suse/utils/Json.java, java/code/src/com/suse/utils/gson/RecordTypeAdapterFactory.java, java/code/src/com/suse/utils/gson/test/RecordTypeAdapterFactoryTest.java, java/code/webapp/WEB-INF/nav/system_detail.xml, java/spacewalk-java.changes.mackdk.supportdata-ui, schema/spacewalk/common/data/endpoint.sql, schema/spacewalk/common/data/endpointNamespace.sql, schema/spacewalk/common/data/namespace.sql, schema/spacewalk/susemanager-schema.changes.mackdk.supportdata-ui, schema/spacewalk/upgrade/susemanager-schema-5.1.6-to-susemanager-schema-5.1.7/003-supportdata-rbac.sql, web/html/src/manager/minion/details/support-data.renderer.tsx, web/html/src/manager/minion/details/support-data.tsx, web/html/src/manager/minion/index.ts, web/spacewalk-web.changes.mackdk.supportdata-ui
This PR adds a tab in the system details page, to allow the user to generate and upload the support config data.
After:
- Documentation WIP
Issue(s): https://github.com/SUSE/spacewalk/issues/26619 …
=> Support Data UI

java/code/src/com/suse/manager/webui/templates/minion/support-data.jade
=> fixup! Add UI for uploading the support data of a system

testsuite/features/build_validation/reposync/srv_sync_all_products.feature, testsuite/features/support/commonlib.rb, testsuite/features/support/constants.rb, testsuite/features/support/env.rb
Support 5.1 proxy product. Create tag to manage slmicro61 and sle15sp7 synchronizing
We have an issue with synchronizing separately slmicro61 and proxy on top of slmicro61. If we have them both in a deployment, we will try to sync twice slmicro61 product. This will fail the reposync feature.
We have the same problematic with proxy on top of sle15sp7.
To manage this situation ( normal BV), and still be compatible with all the scenarios ( uyuni, proxy on top of sles15sp7 or slmicro61), I created a specific tag to sync slmicro51 and sle15sp7.
No difference.
- No tests: already …
=> Support 5.1 proxy product. Create tag to manage slmicro61 and sle15sp7 synchronizing

java/code/src/com/suse/manager/hub/HubController.java, java/code/src/com/suse/manager/hub/HubManager.java, java/code/src/com/suse/manager/model/hub/OrgInfoJson.java, java/code/src/com/suse/manager/webui/controllers/admin/beans/ChannelSyncDetail.java, java/spacewalk-java.changes.carlo.uyuni-get-peripheral-extended-org-info, java/spacewalk-java.changes.mcalmer.fix-peripheral-org-selection, web/html/src/branding/css/base/components/hierarchical-table.scss, web/html/src/branding/css/base/index.scss, web/html/src/components/hub/HierarchicalChannelsTable.tsx, web/html/src/components/hub/SyncOrgsToPeripheralChannels.tsx, web/html/src/components/hub/types.tsx, web/html/src/components/table/HierarchicalTable.tsx, web/spacewalk-web.changes.mcalmer.fix-peripheral-org-selection
Fix selection of peripheral organization.
- rename "SUSE" to "Vendor" 
- check for allowed orgs in the backend and show a fix string instead of a selection if there is no choice
- remove "Hub Org" as this is not helpful info and we need the space later
- show channel names instead of lable
- hide the organization selection if the row is not selected
- remove the ablity to clear the selected item in the organization selection
- fix the filtering by channel name and architecture
- Ensure the rows and the columns do not change size while editing the data
- already adapted
- already covered
Issue(s): https://github.com/SUSE/spacewalk/issues/27165 https://github.com/SUSE/spacewalk/issues/27187  …
=> Fix peripheral org selection (bsc#1242323)

web/html/src/branding/css/base/components/modal.scss, web/spacewalk-web.changes.bisht-richa.modal-height-fix
Fix modal height for small screens
After:
Fixes: https://github.com/SUSE/spacewalk/issues/27193 …
=> Fix: Adjust modal height for small screens

containers/proxy-httpd-image/proxy-httpd-image.changes.oholecek.redirect_api_proxy_server, containers/proxy-httpd-image/uyuni-configure.py
Add redirect of API calls from proxy to the server
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27113
Port(s): https://github.com/SUSE/spacewalk/pull/27228
If …
=> Add redirect of API calls from proxy to the server (bsc#1241880)

java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml, java/code/src/com/redhat/rhn/common/db/datasource/xml/Task_queries.xml, java/spacewalk-java.changes.kwalter.bsc1242010, reporting/reports/legacy/inactive-systems, reporting/reports/legacy/system-md5-certificates, reporting/spacewalk-reports.changes.kwalter.bsc1242010, schema/spacewalk/postgres/procs/update_system_overview.sql, schema/spacewalk/susemanager-schema.changes.kwalter.bsc1242010, schema/spacewalk/upgrade/susemanager-schema-5.1.7-to-susemanager-schema-5.1.8/001-update-system-overview.sql
port of https://github.com/SUSE/spacewalk/pull/27135
Issue: https://github.com/SUSE/spacewalk/issues/27116
=> Change the key to uppercase to match the criteria

.github/CODEOWNERS
Add code ownerships to CODEOWNERS file for RBAC.
=> Add RBAC code ownerships

susemanager-sync-data/channel_families.json, susemanager-sync-data/susemanager-sync-data.changes.mcalmer.Manager-4.3-lts
For SUMA 4.3 LTS we need new product classes defined.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/27393 …
=> Add SUSE Manager LTS Channel Families (jsc#MSC-956)

schema/spacewalk/common/data/endpoint.sql, schema/spacewalk/common/data/endpointNamespace.sql, schema/spacewalk/upgrade/susemanager-schema-5.1.7-to-susemanager-schema-5.1.8/100-rbac-missing-mappings.sql
Add missing RBAC endpoint as reported in: https://github.com/uyuni-project/uyuni/pull/10358#issuecomment-2943336315
=> Add RBAC mapping for 'cancel events' URL

susemanager-utils/susemanager-sls/salt/bootstrap/init.sls, susemanager-utils/susemanager-sls/susemanager-sls.changes.vzhestkov.adjust-openEuler-bootstrap
With the upcoming fix in `salt` (https://github.com/openSUSE/salt/pull/708) `openEuler` will start idenfying `os_family` as `RedHat` what's totally valid as it's a clone basically similar to `Alma` or `Rocky`, but before it was reporting `os_family` as `openEuler`, so this change is intended to fix the condition in the bootstrap state to make both options working.
Ther other conditional parts of the state already contains `or` for `RedHat`/`openEuler` so no need to adjust something else.
No difference.
- Unit tests …
=> Fix openEuler bootstrap to make it identified as RedHat family

java/code/src/com/suse/oval/vulnerablepkgextractor/UbuntuVulnerablePackageExtractor.java, java/spacewalk-java.changes.rmateus.m50_ubuntu_oval_parse_improvement
Improve oval data processing for Ubuntu.
No difference.
Before:
After:
- No documentation needed: Internl processing only.
Port(s): https://github.com/SUSE/spacewalk/pull/27133 …
=> Improve Ubuntu OVAL data parsing to detect more CVEs

java/spacewalk-java.spec, java/tito.props, python/spacewalk/tito.props, rel-eng/container_push.sh, spacecmd/spacecmd.changes.deneb-alpha.final-gmc-changes, susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.changes.deneb-alpha.final-gmc-changes, susemanager-utils/supportutils-plugin-susemanager-client/susemanagerclient, susemanager-utils/supportutils-plugin-susemanager-proxy/supportutils-plugin-susemanager-proxy.changes.deneb-alpha.final-gmc-changes, susemanager-utils/supportutils-plugin-susemanager-proxy/susemanagerproxy, susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes.deneb-alpha.final-gmc-changes, susemanager-utils/supportutils-plugin-susemanager/susemanager, web/conf/rhn_web.conf
- remove "Beta" from product_tree_tag
- adapt schema_version to latest schema
- set the containers as released
- bump WebUI to 5.1.0
- Update supportutils plugins to Multi-Linux Manager 5.1.0 and new branding
- Add missing changelog  entries:
- spacecmd: Update translation strings
- supportutils-plugin-susemanager-client: Replace removed check_service function (bsc#1216231)
Changelog failure expected for:
- `spacewalk-java` -> info not relevant to customers and we have other code to tag
- `spacewalk-web` -> info not relevant to customers and we have other code to tag
- `spacewalk-backend` -> info not relevant to customers and we have other code to tag
Before: 5.1.0 RC
After: 5.1.0
Issue(s): …
=> Final GMC changes

testsuite/dockerfiles/server-all-in-one-dev/Dockerfile
⚠️ Only merge this PR, once https://github.com/uyuni-project/uyuni/pull/10371 gets merged! ⚠️ 
Base repo has been removed in https://github.com/uyuni-project/uyuni/pull/10371
We need this repo in the test image to install packages that are needed for testing.
Just to make sure the right repos are configured, we start by deleting all repos and then adding the base one.
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/25878 …
=> CI: add base repo to build server test image

java/code/src/com/redhat/rhn/domain/state/StateRevision.java, java/code/src/com/redhat/rhn/domain/token/Token.java, java/spacewalk-java.changes.nadvornik.migrate_position, schema/spacewalk/susemanager-schema.changes.nadvornik.migrate_position, schema/spacewalk/upgrade/susemanager-schema-5.1.7-to-susemanager-schema-5.1.8/300-fix-config-channel-position.sql
~~JPA annotations do not support order starting with 1.
Migrate suseStateRevisionConfigChannel.position to start with 0
The same change is done to rhnServerConfigChannel to avoid problems when it is updated to JPA annotations in the future.~~
Update:
Starting from 0 in rhnServerConfigChannel caused unit test failures.
rhnRegTokenConfigChannels was also affected - migrated to JPA annotation without handling the starting value.
Current PR version starts with 1 everywhere - it is less intrusive change.
The migration sql fixes the ordering for all cases.
No difference.
Before:
After:
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to …
=> Fix order of config channels after migration (bsc#1244481)

spacecmd/spacecmd.changes.deneb-alpha.fix-changelog
Add missing changelog. follow-up of https://github.com/uyuni-project/uyuni/pull/10476
No difference.
- No documentation needed: changelog fix
- No tests: changelog change
Issue(s): https://github.com/SUSE/spacewalk/issues/27353 https://github.com/uyuni-project/uyuni/pull/10476
Port(s): none …
=> add missing changelog

java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java, java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java, java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java, java/code/src/com/suse/manager/webui/services/test/SaltServerActionServiceTest.java, java/spacewalk-java.changes.mcalmer.Manager-5.0-set-completion-time-for-actionchain-actions-correct, schema/spacewalk/susemanager-schema.changes.mcalmer.Manager-5.0-set-completion-time-for-actionchain-actions-correct, schema/spacewalk/upgrade/susemanager-schema-5.1.8-to-susemanager-schema-5.1.9/001-fix-rhnServerAction-trigger.sql
An Action Chain combine the states of multiple actions into 1 state.apply.
When that state.apply was finished we set all applied actions to the same completion time which create
confusions at the customer side when the execution order is different shown in event history. (No sorting for the same time)
This patch parse now the real completion time from the salt state and set it for the action.
We need to change the trigger as it overwrite the completion time and set all actions back to the same time.
No difference.
- …
=> Set completion time for actionchain actions correct (bsc#1243994)

testsuite/features/build_validation/init_clients/ubuntu2404_minion.feature, testsuite/features/build_validation/init_clients/ubuntu2404_ssh_minion.feature
Enable universe repository in Ubuntu 24.04 systems on BV, in order to be able to install spacecmd package, as it have a `python3-rpm` dependency package that it's only available if universe repository is enabled.
No difference.
Ports:
- https://github.com/SUSE/spacewalk/pull/27827
- https://github.com/SUSE/spacewalk/pull/27826 …
=> BV: Enable universe repository in Ubuntu 24.04

web/conf/rhn_web.conf, web/spacewalk-web.changes, web/spacewalk-web.changes.deneb-alpha.uyuni-202506
Bump WebUI to 2025.07 and fix malformed changes file ([#27701](https://github.com/SUSE/spacewalk/issues/27701))
NOTE1:Given that this change  will be resubmitted also to MLM 5.1 GMC, on the changelog entry this PR will mention
`Update translation strings` that have been provided via https://github.com/uyuni-project/uyuni/pull/10626 instead of mentioning a misleading WebUI version bump
NOTE2: for fixing https://github.com/SUSE/spacewalk/issues/27701 I'm directly changing the main .changes 
It's expected that the changelog test will fail.
Before: 2025.05
After: 2025.07
- No documentation needed: no additional documentation needed
- No tests: …
=> Bump WebUI to 2025.07 and fix malformed changes file

testsuite/features/support/constants.rb
Add missing system management channels for sles15sp6 and sles15sp7 product.
No difference.
Port(s): 5.0: https://github.com/SUSE/spacewalk/pull/27846
4.3: https://github.com/SUSE/spacewalk/pull/27847 …
=> Add system management channels

java/code/src/com/suse/manager/webui/controllers/admin/beans/PeripheralDetailsData.java, java/code/src/com/suse/manager/webui/controllers/admin/beans/PeripheralListData.java, java/spacewalk-java.changes.mackdk.issv3-fix-fqdn-label, web/html/src/components/dialog/DangerDialog.tsx, web/html/src/components/hub/ServerDetailsForm.tsx, web/html/src/components/hub/SyncOrgsToPeripheralChannels.tsx, web/html/src/components/large-text-attachment.tsx, web/html/src/manager/admin/hub/hub-details.tsx, web/html/src/manager/admin/hub/peripheral-details.tsx, web/html/src/manager/admin/hub/peripherals.tsx, web/spacewalk-web.changes.mackdk.issv3-fix-fqdn-label
This PR introduces the following changes in the UI:
- change the label used for the FQDN in the hub and peripheral details pages.
- Fix the count of the number of organizations synchronized, which now considers an organization the vendor `SUSE`
- Fix the urls pointing to the documentation
Before:
After:
Before:
After:
- [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pull/4067) …
=> ISSv3 - Minor UI improvements

susemanager/src/mgr_bootstrap_data.py, susemanager/susemanager.changes.mcalmer.leap-micro-62, utils/spacewalk-common-channels.ini, utils/spacewalk-utils.changes.mcalmer.leap-micro-62
Add repos to spacewalk-common-channels.ini and add bootstrap data 
No difference.
- General v16 docs
Issue(s): https://github.com/SUSE/spacewalk/issues/27619
Port(s): no ports …
=> Enable openSUSE Leap Micro 6.2

java/code/webapp/WEB-INF/nav/system_detail.xml, java/spacewalk-java.changes.mc.Manager-5.0-coco-attestation-salt-ssh
This was applied before, but reverted by a wrong resolved merge conflict.
Bring back the ACL change
No difference.
Port(s): 5.0 has it already  …
=> show Confidential Compute Attestation tab also for salt ssh managed clients

web/html/src/components/hub/TokenTable.tsx, web/spacewalk-web.changes.serpico.1244134-issv3-token-deletion-delete-loop-fix
fix for https://bugzilla.suse.com/show_bug.cgi?id=1244134
No difference.
Issue(s): # https://github.com/SUSE/spacewalk/issues/27432 https://bugzilla.suse.com/show_bug.cgi?id=1244134 …
=> 1244134 - ISSv3: Token deletion loop fix (bsc#1244134)

web/html/src/build/licenses/fs.js, web/html/src/build/licenses/index.js, web/html/src/core/intl/index.example.tsx, web/html/src/core/intl/inferValues.ts, web/html/src/manager/storybook/stories.generated.ts
Port of https://github.com/uyuni-project/uyuni/pull/10328
=> Add `react-intl` Storybook example

web/html/src/branding/css/base/components/help-block.scss, web/html/src/manager/content-management/list-filters/filter-edit.tsx, web/spacewalk-web.changes.bisht-richa.error-message-filter-modal
Update UI for error message when a CLM filter with a duplicate name is created
- [x **DONE**
Fixes: https://github.com/SUSE/spacewalk/issues/27624
Port(s): [5.0](https://github.com/SUSE/spacewalk/pull/27690) …
=> Fix error message for duplicate filter entries

web/html/src/manager/maintenance/list/maintenance-windows-list.tsx, web/spacewalk-web.changes.bisht-richa.fix-title-maintenance-create-button
Fix tooltip text calendars page
No difference.
Fixes: https://github.com/SUSE/spacewalk/issues/27158
Port(s): [5.0](https://github.com/SUSE/spacewalk/pull/27801)
If …
=> Fix tooltip text calendars page

susemanager-utils/susemanager-sls/modules/runners/mgrutil.py, susemanager-utils/susemanager-sls/susemanager-sls.changes.oholecek.fix_ica_ssls
Intermediate CAs are passed as a list which is not understood by
mgr-ssl-cert-setup. So expand it into multiple params instead.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27937
If …
=> Pass intermediate CAs as a sequence of arguments (bsc#1247083)

java/code/webapp/WEB-INF/pages/systems/spmigration/spmigration-setup.jsp, java/spacewalk-java.changes.bisht-richa.aligned-vendor-checkbox
Fixed Vendor Change checkbox alignment
Fixes: https://github.com/SUSE/spacewalk/issues/26970
Port(s):[ 5.0](https://github.com/SUSE/spacewalk/pull/27808) …
=> Fixed Vendor Change checkbox alignment (bsc#1241044)

reporting/reports/data/system-hardware, schema/reportdb/common/views/SystemHardwareReport.sql, schema/reportdb/postgres/docs/views/SystemHardwareReport.pre, schema/reportdb/upgrade/uyuni-reportdb-schema-5.1.4-to-uyuni-reportdb-schema-5.1.5/005-system-hardware-report.sql
Add IPv6 addresses to the Hardware Report
No difference.
Port(s): no ports
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-prope …
=> Hardware report add ipv6

java/code/src/com/redhat/rhn/manager/distupgrade/DistUpgradeManager.java, java/spacewalk-java.changes.parlt.fix-slmicro-product-migration
Port of: https://github.com/SUSE/spacewalk/pull/27974
=> Fix product migration for SL Micro not showing valid clones as target

java/code/src/com/redhat/rhn/domain/action/rhnpackage/PackageRefreshListAction.java, java/code/src/com/redhat/rhn/domain/action/salt/ApplyStatesAction.java, java/code/src/com/redhat/rhn/domain/action/salt/build/ImageBuildAction.java, java/code/src/com/redhat/rhn/domain/action/salt/inspect/ImageInspectAction.java, java/code/src/com/redhat/rhn/domain/server/test/ServerFactoryTest.java, java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java, java/code/src/com/suse/manager/utils/SaltUtils.java, java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
Fix some sonarcloud reports
No difference.
=> apply SonarCloud suggestions

susemanager-utils/susemanager-sls/src/modules/kiwi_info.py, susemanager-utils/susemanager-sls/susemanager-sls.changes.oholecek.add_new_kiwi_imagetypes
See $title
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27869 …
=> Add all result types kiwi knows so we can collect them (bsc#1246663)

testsuite/features/build_validation/migration/migration_sle15sp6_minion.feature, testsuite/features/build_validation/migration/migration_sle15sp6_ssh_minion.feature
Install latest zypper before migration test. Otherwise there is a warning:
Also install latest salt on the minion exactly like we do in ssh minion https://github.com/uyuni-project/uyuni/pull/10614/files#diff-08ba9e7f0046fc1e9f4acd9a54a4467cf9bb2048afe35dc4321e92b37872e36dR10 because we need to have the latest salt before migration
No difference.
Issue(s): no issue directly for testsuite review
Port(s): 
5.0: https://github.com/SUSE/spacewalk/pull/27913
4.3: https://github.com/SUSE/spacewalk/pull/27912 …
=> Install latest zypper before migration test and salt in minion before migration

testsuite/features/reposync/srv_sync_products.feature
Correct string for client tools name on released client tools. It's not wrong to use beta client tools but it's in a different part of the scenario already. 
No difference.
Issue(s): no issue directly from testsuite review
Port(s): no port needed, only on head, beta is not on others. …
=> Correct string for client tools name on released client tools

testsuite/ext-tools/collect_logs.py, testsuite/ext-tools/gather_timings.py, testsuite/ext-tools/hub-examples/auto-authentication.py, testsuite/ext-tools/hub-examples/install-pkg-all-systems.py, testsuite/ext-tools/hub-examples/manual-authentication.py, testsuite/ext-tools/hub-examples/relay-authentication.py
Script to collect logs from a list of fqdns
No difference.
- No tests
Ports:
- Manager-4.3
- Manager-5.0
Check …
=> Script to collect logs from a list of fqdns

reporting/reports/data/inventory, reporting/reports/data/system-hardware, reporting/spacewalk-reports.changes.mcalmer.adapt-report
- Add new system columns to the Inventory Report
- Fix a typo in the System Hardware Report
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/4293
- No tests
Port(s): https://github.com/SUSE/spacewalk/pull/28229 …
=> Adapt spacewalk-report

.github/workflows/sonarcloud.yml
Apply sonarcloud action update for a security fix.
No difference.
- No tests: sonarcloud action update
Issue(s): # …
=> Update sonarcloud github action

.github/workflows/sonarcloud.yml
I overlooked that the action name has changed a little since I introduced it.
No difference.
- No tests: github workflow change
Issue(s): #
If …
=> Fix sonarcloud action name

testsuite/features/core/srv_docker.feature, testsuite/features/secondary/allcli_software_channels.feature, testsuite/features/secondary/srv_maintenance_windows.feature, testsuite/features/secondary/srv_notifications.feature, testsuite/features/support/commonlib.rb, web/html/src/branding/css/base/components/buttons.suma.scss, web/html/src/components/pagination.tsx, web/html/src/manager/admin/setup/products/products.tsx, web/html/src/manager/notifications/notifications-list.tsx, web/html/src/manager/systems/virtual-list.tsx
- Revert a few changes in pagination control
- Updated button labels in the notification-messages page
- Some CSS style fixes
No difference.
Before:
After:
- Documentation issue was created: [Link for SUSE Multi-Linux Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if …
=> Revert pagination text, update buttons positions and style

java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
Apply some sonarcloud suggestions to ServerFactory class
No difference.
Port(s): 
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merg …
=> ServerFactory - sonarcloud suggestions

java/code/src/com/redhat/rhn/common/db/datasource/xml/Task_queries.xml, java/code/src/com/redhat/rhn/manager/rhnpackage/PackageManager.java, java/code/src/com/redhat/rhn/taskomatic/task/PackageCleanup.java, java/code/src/com/redhat/rhn/taskomatic/task/TaskConstants.java, java/code/src/log4j2.xml, python/spacewalk/satellite_tools/reposync.py
Better logging when removing packages
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/28147 …
=> Debug remove package

containers/server-attestation-image/Dockerfile, containers/server-attestation-image/server-attestation-image.changes.deneb-alpha.master-bsc1248252-ognl, microservices/coco-attestation/uyuni-coco-attestation.changes.deneb-alpha.master-bsc1248252-ognl, microservices/coco-attestation/uyuni-coco-attestation.spec, microservices/uyuni-java-parent/pom.xml, microservices/uyuni-java-parent/uyuni-java-parent.changes.deneb-alpha.master-bsc1248252-ognl, search-server/spacewalk-search/buildconf/build-props.xml, search-server/spacewalk-search/ivy.xml, search-server/spacewalk-search/spacewalk-search.changes.deneb-alpha.master-bsc1248252-ognl, search-server/spacewalk-search/spacewalk-search.spec
This is needed after the changes introduced by this maintenance request https://build.suse.de/request/show/389430
- CVE-2025-53192: Do not use apache-commons-ognl but its successor ognl (bsc#1248252)
- spacewalk-search: update mybatis version needed for building (`search-server/spacewalk-search/ivy.xml`)
No difference.
- tested here: 
- Uyuni: https://build.opensuse.org/project/show/home:deneb_alpha:branches:systemsmanagement:Uyuni:Master_ognl
- Head: https://build.suse.de/project/show/home:deneb_alpha:branches:Devel:Galaxy:Manager:Head-ognl
Issue(s): #
Port(s): 
- 5.0: …
=> CVE-2025-53192: Do not use apache-commons-ognl but its successor ognl (bsc#1248252)

python/spacewalk/satellite_tools/repo_plugins/deb_src.py, python/spacewalk/satellite_tools/repo_plugins/yum_src.py, python/spacewalk/spacewalk-backend.changes.vzhestkov.fix-reposync-latest-pkg, python/spacewalk/spacewalk-backend.spec, python/test/unit/spacewalk/satellite_tools/test_yum_src.py
Alternative for https://github.com/uyuni-project/uyuni/pull/10794
Use more reliable way of version comparison and getting rid of `looseversion` dependency.
No difference.
- Unit tests were added (NOT YET, TBD)
Issue(s): https://github.com/uyuni-project/uyuni/issues/10612
Tracks: https://github.com/SUSE/spacewalk/issues/28213 …
=> Use more reliable version comparison for reposync --latest (bsc#1248799)

python/uyuni-cobbler-helper/uyuni-cobbler-helper.spec, rel-eng/packages/uyuni-cobbler-helper
- Follow-up fix of #9652
- bump the new uyuni-cobbler-helper to 5.2 and adjust copyright line
- The package is new, no need to add a new changelog entry.
No difference.
Issue(s): follow-up of #9652
Port(s): NONE …
=> Bump the new uyuni-cobbler-helper to 5.2 and adjust copyright line
