- testsuite/features/support/commonlib.rb
- testsuite/features/support/http_client.rb
* Can fixed missing `auth` namespace, this PR removes the corresponding workarounds
* Can moved some more methods from POST to GET, this PR accomodates for it
* I forgot to use `channel.software` namespace in a call used for Build Validation, this PR fixes that
**TO BE MERGED ONLY ON 2022-04-30 AS CAN'S MODIFICATIONS ARE NOT YET ON REBUILT PACKAGES**
Ports:
* 4.1: SUSE/spacewalk#17676
* 4.2: SUSE/spacewalk#17678
> HTTP API polishing

- web/spacewalk-web.changes
Removed invalid '\r' character from Roboto*/Icon:
Illegal character (0xd) in filename: /var/www/html/fonts/Roboto/Icon
Illegal character (0xd) in filename: /var/www/html/fonts/RobotoCondensed/Icon
RPM build can fail.
No difference. …
> spacewalk-web: fixed invalid file name

- testsuite/features/build_validation/init_clients/proxy.feature
BV: the routing checbox cannot be accessed if the branch network formula is collapsed. Now it's the default due to SUSE/spacewalk#17148. This PR fixes that by expanding the formula.
Ports:
* 4.1: SUSE/spacewalk#17683
* 4.2: SUSE/spacewalk#17684
> Deploy the formula so all fields are shown

- reporting/reports/data/channel-packages
- reporting/reports/data/channels
- reporting/reports/data/custom-channels
- reporting/reports/data/custom-info
- reporting/reports/data/errata-channels
- reporting/reports/data/inventory
- reporting/reports/data/proxies-overview
- reporting/reports/data/scap-scan
- reporting/reports/data/scap-scan-results
- reporting/reports/data/system-extra-packages
- reporting/reports/data/system-history-configuration
- reporting/reports/data/system-history-errata
- reporting/reports/data/system-history-kickstart
- reporting/reports/data/system-history-packages
- reporting/reports/data/system-history-scap
- reporting/reports/data/users
- reporting/reports/data/users-md5
- reporting/reports/data/users-systems
This PR fixes some wrong column names that prevent the affected report from being generated. It also improves the backward compatibility by matching the sorting of the old report version, when possible
No difference. …
> Fixes for report files

- testsuite/features/support/namespaces/system.rb
This PR fixes a typo in previous PR #5334
Ports:
* 4.1: SUSE/spacewalk#17688
* 4.2: SUSE/spacewalk#17686
> Typo in parameter name

- java/code/src/com/suse/manager/webui/menu/MenuTree.java
Move reportdb schema docs into en sub directory to prevent it gets detected as language.
Additionally add that menu item also for not logged-in users under "About" item.
No difference.
> move reportdb schema docs in en subdirectory and add item at About as well

- java/code/src/com/redhat/rhn/taskomatic/task/threaded/TaskQueue.java
Get an NPE when a hub reporting task cannot reach the reportdb to sync. E.g. due to SSL certificate exception
No difference.
- No tests: **min**
> prevent NPE when queueRun is not set due to errors

- java/code/src/com/redhat/rhn/domain/server/Server_legacyUser.hbm.xml
- java/code/src/com/redhat/rhn/domain/server/test/ServerFactoryTest.java
- java/spacewalk-java.changes
Previously ubuntu errata installation would always try to install the latest package version even if that package is not available in the systems assigned channels. This fixes that by only considering packages from assigned channels.
No difference.
- No tests
Fixes https://github.com/uyuni-project/uyuni/issues/5023 …
> Fix ubuntu errata package version selection

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
Fix the smoke tests template at deploy configuration scenario
No difference.
Ports:
- Manager-4.1
- Manager-4.2
> QE: Fix the smoke tests template at deploy configuration scenario

- containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes
- containers/proxy-systemd-services/uyuni-proxy-systemd-services.spec
Choosing the proxy images to use depending on the system OS doesn'work
since those need to depend from the server that is used.
In order to fix this, allow setting the containers_image_path variable
in the project settings like so:
Macros:
%container_images_path registry.suse.com/suse/manager/4.3
:Macros
No difference.
- No tests: under construction
Fixes #5330  …
> Use container_images_path macro for proxy container images

- susemanager-utils/testing/docker/scripts/push-to-obs.sh
With new git 2.35.2 and higher permissions of the git repos are checked.
This is a problem when the git repo comes from a mounted directory in a docker container.
In this case we need to declare that directory as "save", otherwise git fail with:
```
fatal: unsafe repository ('/manager' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /manager
```
No difference.
Tracks  …
> declare /manager directory as save

- web/conf/rhn_web.conf
Cosmetic fix for the default email used at rhn_web.conf
No difference.
- No documentation needed: Cosmetic fix.
- No tests: I think this default value is not even used, as I think we instead always use the one from the YaST setup.
Nothing
> Cosmetic fix for the default email used at rhn_web.conf

- susemanager-utils/testing/docker/scripts/push-to-obs.sh
- web/html/src/scripts/docker-javascript-lint.sh
Replicate for https://github.com/uyuni-project/uyuni/pull/5348 for tne nodejs tests, as otherwise tests are failing with:
```
fatal: unsafe repository ('/manager' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /manager
error Command failed with exit code 128.
```
No difference.
- No documentation needed: Fix for tests
- No tests: Fix for tests
https://github.com/uyuni-project/uyuni/pull/5348 …
> Declare /manager directory as safe for nodejs tests

- susemanager-utils/susemanager-sls/salt/images/kiwi-image-build.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Legacy Kiwi used incorrect log file name, so cp.push failed.
This adds an option with the correct name.
No difference.
- covered by openqa tests (which are not yet fully configured for 4.3)
https://bugzilla.suse.com/show_bug.cgi?id=1199094
> Fix log file name for legacy Kiwi (bsc#1199094)

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml
- java/code/src/com/redhat/rhn/manager/rhnpackage/test/PackageManagerRetractedTest.java
- java/spacewalk-java.changes
- web/conf/rhn_web.conf
- web/spacewalk-web.changes
Tested on our manager with ubuntu channel. This should speedup the query by 50% .
But the returned number of packages is still high and maybe jsp has also a problem with this.
But we should give it a try
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/15201
Tracks  …
> speedup system_available_packages query

- java/code/src/com/suse/manager/utils/SaltUtils.java
fixes a case where the contains check was not adjusted to handle salts function name arrays.
No difference.
- No tests
Fixes #
> fix contains check for salt function name array

- python/spacewalk/common/repo.py
- python/spacewalk/spacewalk-backend.changes
This PR fixes a problem when running reposync to sync a local DEB repository using `file://` as part of the URL.
In some situations, when there is no `Release.gz` file, but some others like `Release.xz`, the current mechanism was not trying the different alternatives but simply raising an error if the first one if not found:
This situation produces problems for example when syncing Debian 11 repos from a local mirror.
```console
2022/04/28 16:33:12 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'debian-11-main-updates-amd64', '--type', 'deb', '--non-interactive']
2022/04/28 16:33:12 +02:00 Sync of channel started.
2022/04/28 16:33:12 +02:00 Unhandled error occurred: [Errno 2] No such file or directory: '/mirror/deb.debian.org/debian/dists/bullseye-updates/main/binary-amd64/P …
```
> Fix reposync issue with DEB repos when using a local mirror (bsc#1199142)

- testsuite/features/build_validation/core/allcli_sanity.feature
- testsuite/features/build_validation/create_bootstrap_repositories/srv_create_bootstrap_repositories.feature
- testsuite/features/build_validation/init_clients/sle15sp4_client.feature
- testsuite/features/build_validation/init_clients/sle15sp4_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp4_ssh_minion.feature
- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/constants.rb
- testsuite/features/support/env.rb
- testsuite/features/support/twopence_init.rb
- testsuite/run_sets/build_validation_init_clients.yml
Add support for SLE 15 SP4 to build validation.
I have run sanity checks with this PR to at least avoid obvious breakages.
Sibling PRs:
* Sumaform: uyuni-project/sumaform#1089
* Susemanager-ci: SUSE/susemanager-ci#537
* Infrastructure: https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/526
Ports:
* 4.1: SUSE/spacewalk#17751 (for code synchronization purposes only)
* 4.2: SUSE/spacewalk#17750
> Add SLE 15 SP4 to Build Validation

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/support/env.rb
Prometheus formula must be tested only in SUSE Systems
No difference.
Ports:
- Manager-4.1
- Manager-4.2
> QE: Prometheus formula must be tested only in SUSE Systems

- susemanager-utils/susemanager-sls/salt-ssh/preflight.sh
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Bootstrap repository URL on Yum based clients resolved wrong way. A part of the URL is doubled.
No difference.
- No tests: testsuite is not reaching this part of the script
Fixes https://github.com/uyuni-project/uyuni/issues/5372 …
> Fix bootstrap repository URL resolution for Yum based clients with preflight for Salt SSH

- containers/proxy-systemd-services/uyuni-proxy-services.config
- containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes
The longer
registry.opensuse.org/systemsmanagement/uyuni/stable/containers/uyuni
namspace is no longer provided.
No difference.
- No tests: not ready yet
Fixes #5387 
> Use registry.opensuse.org/uyuni namespace for proxy containers

- java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
- java/spacewalk-java.changes
The preflight script doesn't care about the SSH port, remove it from the
proxy path or we end up with URLs like https://server:8022:443/ with
both SSH and TLS ports.
Ensure we don't have the SSH proxy port in the pre flight script host parameter
No difference.
- No tests: testing the `SaltRoster` generation is not easy
Fixes #5389  …
> [4.3 RC1] Remove the port from the proxy path given to preflight script

- testsuite/features/profiles/Docker/Dockerfile
- testsuite/features/profiles/Docker/add_packages.sh
- testsuite/features/profiles/Docker/authprofile/Dockerfile
- testsuite/features/profiles/Docker/authprofile/add_packages.sh
- testsuite/features/profiles/Docker/authprofile/sles12sp4.repo
- testsuite/features/profiles/Docker/authprofile/sles15sp4.repo
- testsuite/features/profiles/Docker/serverhost/Dockerfile
- testsuite/features/profiles/Docker/serverhost/add_packages.sh
- testsuite/features/profiles/Docker/serverhost/sles12sp4.repo
- testsuite/features/profiles/Docker/serverhost/sles15sp4.repo
- testsuite/features/profiles/Docker/sles12sp4.repo
- testsuite/features/profiles/Docker/sles15sp2.repo
**Card**: https://github.com/SUSE/spacewalk/issues/17619
Update the docker profiles in CI to use SLES15 images, so we match Docker profiles with Build Host OS (SLES15SP4)
**Note:** For now we don't have an image for SLE15 available in the registry, I'm discussing it with @agraul , once we have one, we can merge this. We might for now use SLES15SP2 image and then I will make the changes in that PR to use it instead of SP4.
No difference.
- Docker profiles
No ports.
If you uncheck …
> QE: Update the Docker profiles in CI to use SLES15 images

- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/step_definitions/navigation_steps.rb
When we select a channel in the CLM "add sources" dialog box, a summary of the channel and its child channels appears, where the channel is selected via a checkbox.
If this summary has not the time to appear and we press the "Save" button too early, then the channel will not be selected in the sources.
This PR waits for the summary to appear, by waiting for the selected channel name to appear.
There are also cosmetical changes (in a separate commit).
Note: an unresolved problem in 4.2 is that the drop-down field is callled `undefined`. This should probably be fixed at product level.
Ports:
* 4.1: SUSE/spacewalk#17767
* 4.2: SUSE/spacewalk#17766
> Fix CLM sources modal

- rel-eng/push-packages-to-obs.sh
$subject
No difference.
- No documentation needed:  rel-eng stuff
- No tests: rel-eng stuff
Fixes #
> Drop handling container version in changelog

- java/code/webapp/WEB-INF/struts-config.xml
- java/spacewalk-java.changes
The config file diff output cannot be downloaded for SLS files because of a missing ACL rule. This PR adds the rule to ensure access.
https://bugzilla.suse.com/show_bug.cgi?id=1198914
Port of: https://github.com/SUSE/spacewalk/pull/17729
> Fix ACL rules for config diff download for SLS files (bsc#1198914)

- java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java
- java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java
- java/spacewalk-java.changes
Update the server needed cache after adding ubuntu errata. The errata mailer depends on correct data in the cache.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/17752
> update server needed cache after adding Ubuntu Errata

- java/code/src/com/suse/manager/webui/controllers/DownloadController.java
- java/code/src/com/suse/manager/webui/controllers/test/DownloadControllerTest.java
- java/spacewalk-java.changes
Apache module xsendfile cause hanging AJP connections when the file does not exist which should be send.
This PR test the existence of the file before returning to xsendfile and raise a "404 Not Found" when the file does not exist.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/17679
If you need …
> Check file exists

- java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
- java/spacewalk-java.changes
- testsuite/features/secondary/minssh_bootstrap_api.feature
- testsuite/features/step_definitions/command_steps.rb
When bootstrapping a ssh minion via a proxy and the server cannot reach the minion directly, we must use
the proxy as jump host also when getting the grains via salt-ssh after the first bootstrap call but before the client is
created in the database.
In this case we still must create a roster file as the autogenerated roster from DB will not yet find the minion.
No difference.
- Cucumber test added
Fixes https://github.com/uyuni-project/uyuni/issues/5370
Fixes https://github.com/SUSE/spacewalk/issues/17762
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repos …
> create a roster for pending minions not yet in DB

- java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/FilterResponse.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/ProjectFilterResponse.java
- java/spacewalk-java.changes
- web/html/src/components/datetime/DateTimePicker.tsx
Display usertime instead of server time for clm issue date filter
Remove toggle timezone between user and server time for the datetimepicker
Tracks https://github.com/SUSE/spacewalk/issues/17511
> Display usertime instead of server time for clm issue date filter

- testsuite/features/profiles/internal_nue/Docker/Dockerfile
- testsuite/features/profiles/internal_nue/Docker/add_packages.sh
- testsuite/features/profiles/internal_nue/Docker/authprofile/Dockerfile
- testsuite/features/profiles/internal_nue/Docker/authprofile/add_packages.sh
- testsuite/features/profiles/internal_nue/Docker/authprofile/sles12sp4.repo
- testsuite/features/profiles/internal_nue/Docker/authprofile/sles15sp4.repo
- testsuite/features/profiles/internal_nue/Docker/serverhost/Dockerfile
- testsuite/features/profiles/internal_nue/Docker/serverhost/add_packages.sh
- testsuite/features/profiles/internal_nue/Docker/serverhost/sles12sp4.repo
- testsuite/features/profiles/internal_nue/Docker/serverhost/sles15sp4.repo
- testsuite/features/profiles/internal_nue/Docker/sles12sp4.repo
- testsuite/features/profiles/internal_nue/Docker/sles15sp2.repo
- testsuite/features/profiles/internal_prv/Docker/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/add_packages.sh
- testsuite/features/profiles/internal_prv/Docker/authprofile/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/authprofile/add_packages.sh
- testsuite/features/profiles/internal_prv/Docker/authprofile/sles12sp4.repo
- testsuite/features/profiles/internal_prv/Docker/authprofile/sles15sp4.repo
- testsuite/features/profiles/internal_prv/Docker/serverhost/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/serverhost/add_packages.sh
- testsuite/features/profiles/internal_prv/Docker/serverhost/sles12sp4.repo
- testsuite/features/profiles/internal_prv/Docker/serverhost/sles15sp4.repo
- testsuite/features/profiles/internal_prv/Docker/sles12sp4.repo
- testsuite/features/profiles/internal_prv/Docker/sles15sp2.repo
Regenerated "internal_prv" and "internal_nue" with "make" command after switch from 12sp3 to 15sp2 for docker images.
None, no ports.
> Regenerated "internal_prv" and "internal_nue" with "make" command

- java/spacewalk-java.spec
Do not use beta for the product tag for SUSE Manager 4.3
No difference.
- No tests: Tested manually during BV
Related: https://github.com/SUSE/spacewalk/issues/17553
> Do not use beta for the product tag for SUSE Manager 4.3

- spacewalk/config/spacewalk-config.changes
- spacewalk/config/spacewalk-config.spec
`/usr/lib/susemanager/bin/pg-migrate-13-to-14.sh` fails with this error:
```
spacewalk-startup-helper[3420]: The SSL CA Certificate (/etc/pki/trust/anchors/LOCAL-RHN-ORG-TRUSTED-SSL-CERT) is required to setup the reporting database
spacewalk-startup-helper[3334]: Report Database creation has failed. Please check the logs.
```
on upgrade, create `LOCAL-RHN-ORG-TRUSTED-SSL-CERT`.
No difference. …
> On upgrade, create LOCAL-RHN-ORG-TRUSTED-SSL-CERT (bsc#1199376)

- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygUpdateHostsTask.java
- java/spacewalk-java.changes
Implementation of: https://github.com/SUSE/spacewalk/issues/17783
We now do a two-step process:
- check if `ca-certificates.path` service is running
- if not running call `/usr/sbin/update-ca-certificates`
Before this change the script `/usr/share/rhn/certs/update-ca-cert-trust.sh` was always called, and was causing some concurrency errors.
No difference.
Before:
After:
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for …
> payg taskomatic task for updating certificates (#17783)

- java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
- java/spacewalk-java.changes
Adds API Endpoint to create AppStreamFilters based on Template similar as the CLM Web UI functionality.
Re-use Classes and methods also used for the Web UI Implementation: https://github.com/uyuni-project/uyuni/pull/4147
No difference.
Before:
After:
- No documentation needed: API Documentation generated by javadoc
- No tests: already covered in `java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerTest.java`
none …
> XMLRPC API ContentManagement createAppStreamFilters

- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/spacewalk-java.changes
Fix exception when package install date is not reported.
```
2022-03-11 10:11:28,787 [salt-event-thread-2] ERROR com.suse.manager.webui.services.SaltServerActionService - Error processing Salt job return
java.util.NoSuchElementException: No value present
at java.base/java.util.Optional.get(Optional.java:148)
at com.suse.manager.utils.SaltUtils.createInstalledPackage(SaltUtils.java:1492)
at com.suse.manager.utils.SaltUtils.lambda$createPackagesFromSalt$96(SaltUtils.java:1472)
...
```
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/4996
Tracks https://github.com/SUSE/spacewalk/pull/17809 …
> fix NoSuchElementException when pkg install date is missing

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Add openSUSE Leap 15.4 repositories to spacewalk-common-channels
```
uyuni-refmaster-srv:~ # spacewalk-common-channels -a x86_64 opensuse_leap15_4*
SUSE Manager username: admin
SUSE Manager password: 
uyuni-refmaster-srv:~ # spacewalk-common-channels -a aarch64 opensuse_leap15_4*
SUSE Manager username: admin
SUSE Manager password:
uyuni-refmaster-srv:~ # spacewalk-repo-sync -l|grep leap
12:01:54 opensuse_leap15_4-aarch64-backports-updates | http://download.opensuse.org/update/leap/15.4/backports/
12:01:54 opensuse_leap15_4-x86_64-sle-updates | http://download.opensuse.org/update/leap/15.4/sle/
12:01:54 opensuse_leap15_4-x86_64-non-oss | http://download.opensuse.org/distribution/leap/15.4/repo/non-oss/
12:01:54 opensuse_leap15_4-x86_64-non-oss-updates | …
```
> Add openSUSE Leap 15.4 repositories to spacewalk-common-channels

- susemanager-utils/susemanager-sls/salt/bootstrap/bootstrap.repo
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Some repository flags are only known on SUSE systems. Do not set them when bootstrapping EL systems.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/4988
Tracks https://github.com/SUSE/spacewalk/pull/17825 …
> autorefresh and keeppackages flags only known on SUSE systems

- python/spacewalk/satellite_tools/spacewalk-debug
- python/spacewalk/spacewalk-backend.changes
The create-bootstrap logfiles are not part of spacewalk-debug collection.
As these are important logfiles, we better collect them.
No difference.
- No tests: **for debugging**
Tracks https://github.com/SUSE/spacewalk/pull/17830 …
> store create-bootstrap logs in spacewalk-debug

- testsuite/features/secondary/buildhost_docker_auth_registry.feature
- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/features/step_definitions/docker_steps.rb
The image packages list is valid after the successful end of inspect action.
The GUI test for finished build checked only build action. API test checks both build and inspect actions.
This PR makes sure that the API test is called before the test for image packages.
> Wait for inspect action before checking image packages

- web/html/src/.auditignore.js
- web/html/src/build/audit.js
- web/html/src/package.json
Since we moved branding dependencies into web, we now also get security advisories for them. Right now we don't have the bandwidth to upgrade Bootstrap so I've ignored it in the audit results.  
No difference.
- No tests: tooling …
> Add a way to ignore known issues in audits

- proxy/proxy/broker/rhnBroker.py
- proxy/proxy/spacewalk-proxy.changes
Debians "apt" does not work with token auth. As a workaround we configured basic auth and use the token as "login" (username). The password is empty.
But squid does not cache files recieved via an authenticated transaction which make the use of the proxy useless.
To solve this problem, this PR convert the basic auth into token auth. With token auth we have a solution to get
the files cached.
No difference.
- TBD
Fixes https://github.com/SUSE/spacewalk/issues/17776
Fixes https://github.com/uyuni-project/uyuni/issues/5241
Tracks https://github.com/SUSE/spacewalk/pull/17831 …
> convert Basic Auth into token auth to make caching possible

- testsuite/features/profiles/Docker/serverhost/Dockerfile
- testsuite/features/profiles/Docker/serverhost/sles15sp4-base.repo
- testsuite/features/profiles/internal_nue/Docker/serverhost/Dockerfile
- testsuite/features/profiles/internal_nue/Docker/serverhost/sles15sp4-base.repo
- testsuite/features/profiles/internal_prv/Docker/serverhost/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/serverhost/sles15sp4-base.repo
This PR adds the missing basesystem repo to the Docker profile now we switched Docker builds to sle 15 sp2.
PLEASE CHECK THE REPO URL. IT IS PROBABLY WRONG.
(and yeah, it's using sle 15 sp4 repos on sle 15 sp2 images... but do we really want to fix that?)
No ports.
> Add Basesystem repo

- susemanager-utils/susemanager-sls/salt/channels/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
When performing a distupgrade Dry Run, we should not install / update the products or gpg keys.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17828
Tracks https://github.com/SUSE/spacewalk/pull/17839 …
> do not install products and gpg keys in dryrun

- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
don't try to remove known_hosts entry if hostname is null
No difference.
- No tests
Fixes #
> don't try to remove known_hosts entry if hostname is null

- susemanager-sync-data/additional_products.json
- susemanager-sync-data/susemanager-sync-data.changes
Debian 11 should go to released now.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17806
Tracks https://github.com/SUSE/spacewalk/pull/17849
> change release status of Debian 11 to released

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Add RHEL 7 and 8 bootstrap repositories for Uyuni
My guess is that nobody noticed yet, because the bootstrap repository is common with centos/alma/rocky, so as long as the user has one of those other OS, bootstrapping RHEL would work.
This happens only happens for users that are only managing RHEL.
The fix on this PR was tested by @HerrmannMax (https://github.com/uyuni-project/uyuni/issues/5376#issuecomment-1127315017)
No difference.
- No documentation needed: This was supposed to work.
- No tests: At this point we can't automatically test RHEL
Fixes https://github.com/uyuni-project/uyuni/issues/5376 …
> Add RHEL 7 and 8 bootstrap repositories for Uyuni

- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/manager/webui/services/test/SaltServerActionServiceTest.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/salt/packages/pkgremove.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes and issue happening when scheduling a package remove action targeting multiple versions of the same package name. For example: `kernel-devel` or `kernel-source` packages, which we can have multiple versions installed at the same time on a system. 
The problem is that Salt is not able to process duplicates packages names as part of the same `pkg.removed` state execution. So, in case we are under this situation, and we schedule the removal of these packages from the Uyuni UI, the generated `packages.pkgremove` state would be something like:
```yaml
pkg_removed:
pkg.removed:
-   pkgs:
- kernel-source.noarch: 4.12.14-122.80.1
- kernel-source.noarch: 4.12.14-122.60.1
-   require:
- file: mgrchannels*
```
Notice the duplicated packages names as part of `pkgs`.
Now, when this state …
> Fix issue removing duplicated packages names in the same action (bsc#1198686)

- testsuite/features/support/constants.rb
This PR adds a missing constant that defines the channel of the bootstrap reposiory to create for SLE 15 SP4.
Ports:
* 4.1: SUSE/spacewalk#17861
* 4.2: SUSE/spacewalk#17860
> Add channel to sync for SLE 15 SP4

- web/spacewalk-web.changes
- web/spacewalk-web.spec
When installing SUSE Manager we should use a susemanager theme.
The uyuni theme stays for Uyuni installations on openSUSE
Fixes https://github.com/SUSE/spacewalk/issues/17867
Fixes https://github.com/SUSE/spacewalk/issues/17779 …
> change default theme to susemanager-light for SUSE Manager

- testsuite/features/secondary/srv_mainpage.feature
For SUMA 4.3 the copyright year has changed. Adapt the UI test to reflect this.
- Cucumber tests fixed
> the copyright year has changed in 4.3

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Add openSUSE Leap 15.4 bootstrap repositories
Tested:
No difference.
- PR: https://github.com/uyuni-project/uyuni-docs/pull/1560 (issue https://github.com/SUSE/spacewalk/issues/17541)
- No tests: Will be tested later, by sumaform and the testsuite
Fixes https://github.com/SUSE/spacewalk/issues/17542 …
> Add openSUSE Leap 15.4 bootstrap repositories

- client/tools/mgr-virtualization/mgr-virtualization.changes
- client/tools/mgr-virtualization/virtualization/poller.py
- python/spacewalk/server/rhnVirtualization.py
- python/spacewalk/spacewalk-backend.changes
The fix is composed of a client and server side fix. This requires
libvirt 0.9.13 or older, which should be fine on RHEL7 and SLE 12SP3+
clients.
No difference.
- No tests: traditional virtualization stack
Fixes https://github.com/SUSE/spacewalk/issues/17852 …
> Fix VM changes on traditional virtual hosts

- testsuite/features/profiles/Docker/authprofile/sles15sp2.repo
- testsuite/features/profiles/Docker/serverhost/sles15sp2.repo
- testsuite/features/profiles/Docker/sles15sp2.repo
- testsuite/features/profiles/internal_nue/Docker/authprofile/sles15sp2.repo
- testsuite/features/profiles/internal_nue/Docker/serverhost/sles15sp2.repo
- testsuite/features/profiles/internal_nue/Docker/sles15sp2.repo
- testsuite/features/profiles/internal_prv/Docker/authprofile/sles15sp2.repo
- testsuite/features/profiles/internal_prv/Docker/serverhost/sles15sp2.repo
- testsuite/features/profiles/internal_prv/Docker/sles15sp2.repo
Use the basesystem module for sle15sp2
Another PR to move back to SP4 will follow once we get the registry issue fixed
No ports, Uyuni only.
> Use basesystem repo

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/spacewalk-java.changes
- testsuite/features/secondary/min_salt_lock_packages.feature
- testsuite/features/secondary/trad_lock_packages.feature
Port of spacewalk PR : https://github.com/SUSE/spacewalk/pull/17868
Changes the Lock tab name to Lock / Unlock.
https://bugzilla.suse.com/show_bug.cgi?id=1193032
#17239 
Before:
After:
@jcayouette  Screen shots should be updated
Fixes # …
> Change Lock Menu Name

- susemanager/src/mgr-sync
- susemanager/src/mgr_sync/config.py
- susemanager/susemanager.changes
mgr-sync was exiting abruptly when a duplicated property existed in a configuration file. Now it shows an error message.
No difference.
- No documentation needed:  user invisible changes
Fixes #[1182742](https://bugzilla.suse.com/show_bug.cgi?id=1182742)
Tracks https://github.com/SUSE/spacewalk/issues/14113 …
> Exits mgr-sync if properties are duplicated in conf files (bsc#1182742)

- python/spacewalk/spacewalk-backend.changes
Fix the changelog entry with missing bsc#1199528 ref
> Fix the changelog entry with missing bsc#1199528 ref

- java/code/src/com/redhat/rhn/taskomatic/task/ForwardRegistrationTask.java
- java/code/src/com/suse/scc/SCCSystemRegistrationManager.java
- java/code/src/com/suse/scc/test/SCCSystemRegistrationManagerTest.java
- java/spacewalk-java.changes
Skip forwarding data to SCC when we do not have SCC credentials like in the Uyuni case
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17877
Fixes https://github.com/uyuni-project/uyuni/issues/5459
Tracks https://github.com/SUSE/spacewalk/pull/17906 …
> fix exception when trying to forward data to scc without credentials

- java/code/src/com/redhat/rhn/common/db/datasource/xml/ScapReport_queries.xml
- java/spacewalk-java.changes
- java/tito.props
- schema/reportdb/common/tables/XccdScanResult.sql
- schema/reportdb/postgres/docs/tables/XccdScanResult.pre
- schema/reportdb/upgrade/uyuni-reportdb-schema-4.3.4-to-uyuni-reportdb-schema-4.3.5/001-fix-scan-result-duplication.sql
- schema/reportdb/uyuni-reportdb-schema.changes
This PR addresses an issue in the primary key of  the table `XccdScanResult` that prevent to fill the table due to wrong data duplication.
No difference.
- Documentation for report db updated
Fixes https://github.com/SUSE/spacewalk/issues/17881 https://github.com/uyuni-project/uyuni/issues/5458 …
> Fixed duplication of XccdScanResult table by retrieving the ident_id

- utils/spacewalk-clone-by-date
- utils/spacewalk-clone-by-date.sgml
- utils/spacewalk-utils.changes
deprecation warning for spacewalk-clone-by-date 
No difference.
Before:
After: …
> deprecation warning for spacewalk-clone-by-date

- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
- java/code/src/com/redhat/rhn/common/finder/test/JarFinderTest.java
- java/code/src/com/redhat/rhn/testing/RhnMockHttpServletRequest.java
- java/code/src/com/suse/manager/saltboot/test/PXEEventTest.java
Uyuni builds on top of Leap 15.4 now, so we need to change buildfiles used for local compilation, but also CI, in order to resolve dependencies from the corresponding repositories. This patch also adds two new required dependencies needed from XXX:
* `ongres-stringprep`
* `ongres-stringprep-saslprep`
No difference.
- No tests: only dependency resolution is changed.
Fixes # …
> Update dependencies to be resolved from Leap 15.4

- testsuite/features/build_validation/init_clients/proxy.feature
- testsuite/features/build_validation/retail/proxy_branch_network.feature
- testsuite/run_sets/build_validation_retail_proxy.yml
This PR prepares the ground for uyuni-project/uyuni#4522
Reason is it's difficult to test the new PR if the branch server is still prepared from the old code.
(we still do BVs with the old code, excepted for Retail where we already use the new code).
Ports:
4.1: SUSE/spacewalk#18011
4.2: SUSE/spacewalk#18012
4.3: will be done by Julio
> Split the branch server preparation from proxy preparation

- java/spacewalk-java.changes
- java/spacewalk-java.spec
Fixes a bug for new installations of Uyuni where the version of Cobbler is taken from openSUSE Leap 15.4 and not `Uyuni:Master`.
No difference.
Fixes # …
> spacewalk-java: Set Cobbler 3.2.1 as exact requirement

- testsuite/features/support/env.rb
This will show more details in the saved screenshot if a scenario during bootstrapping failed and there is an option to show more details. This is due to adjustments of showing the errors made by https://github.com/uyuni-project/uyuni/pull/5395.
Only necessary for Uyuni/HEAD.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17948 …
> QE: Show details on errors in bootstrapping

- containers/proxy-httpd-image/Dockerfile
- containers/proxy-httpd-image/proxy-httpd-image.changes
- containers/proxy-salt-broker-image/Dockerfile
- containers/proxy-salt-broker-image/proxy-salt-broker-image.changes
- containers/proxy-squid-image/Dockerfile
- containers/proxy-squid-image/proxy-squid-image.changes
- containers/proxy-ssh-image/Dockerfile
- containers/proxy-ssh-image/proxy-ssh-image.changes
- containers/proxy-tftpd-image/Dockerfile
- containers/proxy-tftpd-image/proxy-tftpd-image.changes
Change the base image for all proxy containers to 15.4
So we can remove the `BuildFlags` from https://build.opensuse.org/projects/systemsmanagement:Uyuni:Master/prjconf
No difference.
- The change to Leap 15.4 as base OS (SLE15SP4 for the proxy images) is already part of  https://github.com/SUSE/spacewalk/issues/17541
- No tests: Managed by the acceptance testsuite
Tracks https://github.com/SUSE/spacewalk/issues/17491 …
> Change the base image for all proxy containers to 15.4

- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
- java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
This PR fixes the compilation errors generated when compiling with the Eclipse compiler ECJ.
No difference.
- No documentation needed: no functional changes
- No tests: no functional changes
> Fix eclipse compilation errors

- java/code/src/com/suse/manager/webui/controllers/DownloadController.java
- java/code/src/com/suse/manager/webui/controllers/test/DownloadControllerTest.java
Use the URI class for URL decoding as the URLdecoder mess around with the `+` sign.
No difference.
Fix problems with https://github.com/uyuni-project/uyuni/pull/5496
Tracks https://github.com/SUSE/spacewalk/pull/18082 …
> use URI class for URL decoding

- web/spacewalk-web.changes
- web/spacewalk-web.spec
This PR removes the build-time dependency on `nodejs-packaging`. The version we're using relies on Python 2 which is EOL.
If I understood correctly, this package was used to add provides etc information into packages in the past for security audits (perhaps @SchoolGuy can chime in with a more correct description), however it seems we currently don't use it as far as I could see and find when testing builds.  
The frontend build itself does not rely on this package, as we don't use `nodejs-less` etc anymore (Webpack handles those things instead now).
Using `rel-eng/build-packages-local-obs.sh`, `spacewalk-web` builds fine with `BuildRequires:  nodejs-packaging` removed.  
From the security side, frontend dependencies are covered by both Github's Dependabot, as well as a Github action …
> Remove `nodejs-packaging` as a build requirement

- testsuite/documentation/software-components.md
add backtic
No difference.
Before:
After:
- …
> Testsuite docs: fix language markup

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
This PR adds missing `python3-immutables` and `python3-contextvars` to bootstrap repository definition of RES8 and Ubuntu 18.04, as all those OSes will get Salt 3004 as new Salt version.
**NOTE: These two dependencies are not required for OS with Python version higher than 3.7, like Ubuntu 20.04 and Debian 10**
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/18152 …
> Add python3-contextvars and python3-immutables to missing bootstrap repos (bsc#1200606)

- testsuite/features/init_clients/sle_client.feature
- testsuite/features/init_clients/sle_minion.feature
Adding tags for system presence, so when we don't deploy a `sle_minion` or a `sle_client` VM, we don't try to init clients for them.
No difference.
Ports:
- Manager-4.1
- Manager-4.2
> QE: Add system presence tags for init client features

- testsuite/features/secondary/srv_monitoring.feature
- testsuite/features/step_definitions/common_steps.rb
This will add a step to be able to check if ports are open/closed.
Furthermore it will address one issue found in the testsuite regarding
checking the Taskomatic/Tomcat configuration file for a configuration
line for monitoring via JMX that is always present.
Now we only check if the desired ports for Taskomatic (3334) and Tomacat
(3333) are open or not instead of grepping for contents in their
configuration files.
@renner did the changes in sumaform already: https://github.com/uyuni-project/sumaform/pull/1109
No difference.
Manager 4.2
Manager 4.1
Sumaform changes: https://github.com/uyuni-project/sumaform/pull/1109
PR CI test: https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/ …
> QE: Add step to check for open/closed ports

- testsuite/features/step_definitions/common_steps.rb
With the `lsof` command we get a better result/detection of open/closed port compared to `ss` with our Ruby code.
This was a run on the Uyuni CI controller. 
```bash
Scenario: Check that monitoring is enabled                                                                                      # features/secondary/srv_monitoring.feature:
(...)
And file "/usr/lib/systemd/system/tomcat.service.d/jmx.conf" should contain "jmx_prometheus_javaagent.jar=5556" on server     # features/step_definitions/command_steps.rb:410
And file "/usr/lib/systemd/system/taskomatic.service.d/jmx.conf" should contain "jmx_prometheus_javaagent.jar=5557" on server # features/step_definitions/command_steps.rb:410
And port "3333" should be closed …
```
> QE: Fixup for #5566 for open/closed ports

- python/spacewalk/satellite_tools/download.py
- python/spacewalk/spacewalk-backend.changes
There was a problem with the logic for the `find_proxy` method from "urlgrabber" that is causing configured HTTP Proxy to not work properly for reposync in some cases, particularly when using mirrorlist in the repository to sync, like EL7.
The issue in "urlgrabber" is fixed by this PR: https://github.com/rpm-software-management/urlgrabber/pull/35 and we are including this fix also for our Leap 15.4 and SLE15SP4.
- Fixed "urlgrabber" package at: https://build.opensuse.org/package/show/devel:languages:python/python-urlgrabber 
- SR to Factory: https://build.opensuse.org/request/show/983211
**IMPORTANT NOTE: This PR needs to be released in coordination with the fix for "urlgrabber". @juliogonzalez is aware of this**
No difference.
- No documentation needed: only internal and user invisible …
> Fix issues with "http_proxy" not being used by reposync in some cases

- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes an issue on bootstrapping with classic Salt 3004 package for Ubuntu 18.04 caused by missing `python3-contextvars` and `python3-immutables`not being installed during bootstrapping.
These packages are set as "Recommends" in the Salt DEB package, because we have only a single DEB package we build for all OSes based distros. These two dependencies are supposed to get installed automatically during bootstrapping (as recommends are installed by default), but this is not happening because bootstrapping explicitely disabling adding recommended packages.
In the end, since we cannot add these two packages as hard dependencies for Salt in DEB based distros as those packages are not existing in, i.a., Ubuntu 20.04, what we are doing with this PR is to make boostrapping to also …
> Fix bootstrapping for Ubuntu 18.04 with classic Salt package (bsc#1200707)

- testsuite/features/support/http_client.rb
Actions like reboot can take a lot of time. See https://bugzilla.suse.com/show_bug.cgi?id=1200506 .
This PR aligns the timeout for the HTTP API with the one for XML-RPC.
No backports, head only.
Fixes: https://github.com/SUSE/spacewalk/issues/18133
> QE: Use the same timeout for XML-RPC and HTTP

- testsuite/features/support/constants.rb
Fix label of channel for openSUSE 15.3 ARM that is used for creating the corresponding activation key with the API.
Ports:
* 4.2: SUSE/spacewalk#18208
> Fix creation of activation key for openSUSE 15.3 ARM

- susemanager/bin/pg-migrate-x-to-y.sh
- susemanager/susemanager.changes
`pg-migrate-x-to-y.sh` suggests to use the `fast` mode if the disk does not have enough space to store the db backup.  The fast mode can be running `/usr/lib/susemanager/bin/pg-migrate-x-to-y.sh -f` instead of `/usr/lib/susemanager/bin/pg-migrate-x-to-y.sh fast` as suggested by the comment.
No difference.
- Doc PR: https://github.com/uyuni-project/uyuni-docs/pull/1621 …
> pg-migrate-x-to-y.sh migration without creating backup use -f option

- testsuite/features/reposync/srv_sync_channels.feature
Partial revert of previous PR.
We can't add SP5 twice - and we add it in later tests :disappointed: .
Ports:
* 4.2:
* 4.1:
> Back to 12 SP4 as SP5 conflicts with later tests

- testsuite/features/reposync/srv_sync_channels.feature
Previous PR worked fine, but assumed SLE 12 SP3 was mirrored.
This new version uses SLE 12 SP4 which we mirror anyway.
Ports:
* 4.2:
* 4.1: SUSE/spacewalk#18233
> We don't want to mirror SLE 12 SP3

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Fix the definitions for creating bootstrap repos for Debian 9 and Proxy 4.2 to make the bundle optional for these products.
No difference.
- No documentation needed: just prevent failings on creating bootstrap repos for Debian 9 and Proxy 4.2
- No tests for this part
> Fix bootstrap repo definitions to make the Bundle optional for Debian 9 and Proxy 4.2

- testsuite/features/secondary/srv_advanced_search.feature
- testsuite/features/step_definitions/navigation_steps.rb
This PR:
* removes search-specific code from the generic `I click on "..."` step
* makes use of `repeat_until_timeout` construct
Ports:
* 4.2: SUSE/spacewalk#18264
> Do not mingle with generic step

- java/buildconf/ivy/ivy-suse.xml
This is only a small patch to update the junit5 jars to their latest version. Also the [console launcher](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher) is added, that is required to run the unit tests from VS Code.
No difference.
- No documentation needed, only a minor update of test dependencies.
- No tests, this is an update to the unit test framework
No links. …
> Update junit5 jar files to their latest versions

- testsuite/features/build_validation/retail/sle12sp5_buildhost_build_kiwi_image.feature
- testsuite/features/build_validation/retail/sle15sp3_buildhost_build_kiwi_image.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/step_definitions/retail_steps.rb
This PR fixes #4522:
* the step `I reboot the PXE boot minion` now accepts an argument (the name of the terminal to reboot)
* on head, images get renamed once they are built
No ports, 4.2 fixes directly integrated into SUSE/spacewalk#18256
> Fixes for Retail in BV

- susemanager-utils/susemanager-sls/src/states/mgrcompat.py
- susemanager-utils/susemanager-sls/src/tests/test_state_mgrcompat.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Prevents traceback with undefined `__low__` as `mgrcompat` doesn't respect to LazyLoader and not passing `__low__` to `module.run`.
After discussion with @agraul the better solution was found.
Superseeds https://github.com/uyuni-project/uyuni/pull/5494
No difference.
Tracks # https://github.com/SUSE/spacewalk/issues/17838 …
> Let LazyLoader do its job in mgrcompat to prevent tracebacks

- proxy/proxy/spacewalk-proxy.changes
- proxy/proxy/spacewalk-proxy.spec
The proxy broker is not using any of the certs and cert-check tools and
these are pulling a lot of packages. In order to help slimming down
container images, move these requires to the proxy package so they are
still installed on regular proxies.
No difference. …
> Move cert deps from proxy-broker to proxy package

- containers/proxy-systemd-services/README.md
- containers/proxy-systemd-services/uyuni-proxy-httpd.service
- containers/proxy-systemd-services/uyuni-proxy-salt-broker.service
- containers/proxy-systemd-services/uyuni-proxy-services.config
- containers/proxy-systemd-services/uyuni-proxy-squid.service
- containers/proxy-systemd-services/uyuni-proxy-ssh.service
- containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes
- containers/proxy-systemd-services/uyuni-proxy-systemd-services.spec
- containers/proxy-systemd-services/uyuni-proxy-tftpd.service
* Proxy: add image tag configuration to systemd service
* Add comments to the config file and improve the README.md
* Remove `for` loops in `%service_{add|del}_{pre|post}` calls
No difference.
- No tests: work in progress
Fixes https://github.com/SUSE/spacewalk/issues/17788 …
> Container systemd fixes

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/spacewalk-java.changes
When activating Ansible Control Node add-on, its notification had a different style from others.
A line break and the "Note" word were added to make its style consistent.
No difference. Bug fix.
- No documentation needed: just a bug fix.
Fixes https://github.com/SUSE/spacewalk/issues/17242 …
> Fix notification message on system properties update to ensure style consistency

- java/code/src/com/redhat/rhn/common/security/acl/Access.java
- java/code/src/com/redhat/rhn/common/security/acl/test/AccessTest.java
- java/spacewalk-java.changes
When the URL is a valid path but contains an invalid sysid, the system was trying to lookup the server based on that wrong sysid
generating a LookupException.
The LookupException was captured and logged as a warning leading to a permission error to the user instead of an Internal Server Error.
No difference. Bug fix.
Fixes https://github.com/SUSE/spacewalk/issues/17216 …
> Fix Internal Server Error when URI contains invalid sysid

- java/code/src/com/redhat/rhn/frontend/action/systems/SSMUpdateHardwareProfileConfirm.java
- java/code/src/com/redhat/rhn/frontend/action/systems/SSMUpdateSoftwareProfileConfirm.java
- java/spacewalk-java.changes
Fix refresh action confirmation message when no system is selected showing 0 profiles are scheduled to be refreshed instead of 1 profile is scheduled.
No difference.
> Fix refresh action confirmation message when no system is selected

- java/code/src/com/redhat/rhn/manager/audit/CVEAuditManager.java
- java/code/src/com/redhat/rhn/manager/audit/test/CVEAuditManagerTest.java
- java/spacewalk-java.changes
Display patch as correctly installed in the currently installed product in CVE-Audit even though there might be a patch in a successor product that has updates for additional packages.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/17892 …
> CVE audit installed successor

- web/html/src/branding/css/susemanager/variables.less
- web/html/src/branding/css/uyuni/variables.less
It overrides the value of the variable `@bade-bg` from its default bootstrap value to `@gray-dark` to increase the contrast with the text and make it easier to read.
No difference.
- No documentation needed: just a small fix.
- No tests: CSS change.
Fixes https://github.com/SUSE/spacewalk/issues/12592 …
> Fixed badge color

- web/html/src/components/formulas/FormulaComponentGenerator.tsx
- web/spacewalk-web.changes
Add textarea to formulas.
- No documentation needed: **developer only**
> Textarea for formula

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
improve checking of the CA chain before deploying certificates on Server or Proxy
No difference.
> compare authorityKeyIdentifier with CAs subjectKeyIdentifier

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
mgr-ssl-cert-setup tool should show instructions what need to be restarted when the certificate change.
```
After changing the server certificate please execute:
$> spacewalk-service stop 
$> systemctl restart postgresql.service 
$> spacewalk-service start
As the CA certificate changed, please deploy the CA to all registered clients.
You can apply a highstate when the clients are salt managed.
```
- https://github.com/uyuni-project/uyuni-docs/pull/1638
Fixes https://github.com/SUSE/spacewalk/issues/18120 …
> display messages to restart services after certificate change

- java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemOverviewAction.java
- java/code/src/com/redhat/rhn/frontend/servlets/TransactionalUpdateRebootMessageFilter.java
- java/spacewalk-java.changes
Add WebFilter to show reboot alert message on all system detail pages for SLE Micro system. Without this filter the alert is only shown on the main system profile page, while the requirements are to shown it on all pages.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17954 …
> Show reboot alert message on all system detail pages (SLE Micro system)

- testsuite/run_sets/secondary.yml
We disabled 2 features in February since we had issues with those. We
have more time to look into those failures now.
No difference.
Manager 4.2
> QE: Enable temporarily disabled features again

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Seems we added everything except the client tools to spacewalk-common-channels.ini
No difference.
- No documentation needed: Already documented
- No tests: We need a BV for Uyuni, but that's still WIP :-)
Reported by @v0rtex9 at Gitter.
> Add missing SLES 15 SP4 client tools repositories to spacewalk-common-channels.ini

- testsuite/run_sets/secondary.yml
Reverts uyuni-project/uyuni#5625. This did cause too much trouble in the testsuite. We have to enable and investigate this later on.
> Revert "QE: Enable temporarily disabled features again"

- python/spacewalk/spacewalk-backend.changes
- python/uyuni/uyuni-common-libs.changes
This PR moves a changelog entry introduced by https://github.com/uyuni-project/uyuni/pull/5639 to the proper file.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/18317
> Uyuni-2022.06: Fix changelog entry

- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/PaygSshDataSerializer.java
- java/code/src/com/suse/manager/admin/PaygAdminManager.java
- java/code/src/com/suse/manager/webui/controllers/admin/beans/PaygProperties.java
- java/code/src/com/suse/manager/webui/controllers/admin/handlers/test/PaygApiControllerTest.java
- java/code/src/com/suse/manager/webui/controllers/admin/mappers/PaygResponseMappers.java
- java/code/src/com/suse/manager/xmlrpc/admin/test/AdminPaygHandlerTest.java
- java/spacewalk-java.changes
- testsuite/features/secondary/srv_payg_ssh_connection.feature
- web/html/src/manager/admin/create-payg/create-payg.tsx
- web/html/src/manager/admin/payg-shared/sshData/payg-ssh-data-edit.tsx
- web/html/src/manager/admin/payg-shared/sshData/payg-ssh-data-form.tsx
- web/html/src/manager/admin/payg-shared/sshData/payg-ssh-data-view.tsx
- web/html/src/manager/admin/payg/payg.tsx
- web/spacewalk-web.changes
For security reasons, we should hide the authentication data on the webUI. 
Also in the create form, password fields should be of type password.
When editing the ssh connection user should re-provide the authentication data, otherwise, the existing one will be removed.
Before:
After:
- No documentation needed: We are hiding data on the details page, and how to change data is not documented.
- tests already exists and were adapted to this change
Fixes https://github.com/SUSE/spacewalk/issues/17903
Tracks:
- needs 4.2 backport
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repos …
> Hide authentication data in PAYG UI (bsc#1199679)

- java/code/src/com/redhat/rhn/common/db/datasource/CachedStatement.java
- java/code/src/com/redhat/rhn/common/db/datasource/SelectMode.java
- java/spacewalk-java.changes
Since 2022.02, when CachedStatement started to store hibernate session,
all the pages using `rl:csv` custom JSP tag stopped working.
The reason is when CSVDownloadAction executes, the hibernate session linked
to the CachedStatements is closed.
To fix this, the method restoreSessionIfClosed was added and called in the
buggy points.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17725 …
> Fix download CSV links

- java/code/src/com/redhat/rhn/frontend/action/ssm/ProvisioningRemoteCommand.java
- java/code/src/com/redhat/rhn/frontend/action/systems/SystemRemoteCommandAction.java
- java/spacewalk-java.changes
It changes the format of the dates shown in alert messages to be consistent with the format filled in the scheduler component.
No difference.
- No documentation needed: small adjust on alert messages.
Fixes https://github.com/SUSE/spacewalk/issues/16860
> Fixed date format on scheduler related messages

- web/html/src/components/FormulaForm.tsx
It removes unsafe use of `t()` function in messages that could have elements on it.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/14111
> Fixed FormulaForm component

- java/code/src/com/redhat/rhn/domain/formula/FormulaFactory.java
- java/code/src/com/suse/manager/webui/controllers/FormulaController.java
- java/spacewalk-java.changes
When converting the formulas data from files to DB, don't cast to doubles, but int. This is a hacky workaround due to GSON parser being clueless about number types.
No difference.
- No tests: migration only
Fixes https://github.com/SUSE/spacewalk/issues/18102 …
> Import formula values as int rather than doubles when migrating

- susemanager-utils/testing/automation/push-to-obs.sh
- susemanager-utils/testing/docker/scripts/push-to-obs.sh
Prepare push-to-obs for MFA.
This will require:
- The MFA enabled for the user zypper-team
- `osc` updated to at least 0.178
- Backport to other branches
- Reconfiguration of the Jenkins jobs, so we provide the path to the key.
No difference.
- No documentation needed: CI stuff.
- No tests: CI stuff
Related: https://github.com/SUSE/spacewalk/issues/18180 …
> Prepare push-to-obs for MFA

- susemanager/src/mgr_bootstrap_data.py
Fix typo for the AlmaLinux9 x86_64 bootstrap repository
As reported by @santeri3700 at https://github.com/uyuni-project/uyuni/pull/5609#discussion_r918315851
No difference.
- No tests: RHEL9 and clones still not present at the testsuite
- https://github.com/uyuni-project/uyuni/pull/5609 …
> Fix typo for the AlmaLinux9 x86_64 bootstrap repository

- search-server/spacewalk-search/build.xml
- search-server/spacewalk-search/buildconf/build-props.xml
Fixes the class path for the log4j jar in the search-server package
No difference.
Fixes #
> log4j migration search server fix

- java/code/src/com/redhat/rhn/manager/session/SessionManager.java
It adds a `commitTransaction` call just after saving the WebSession during user authentication.
Without this, in some random situations, [this call](https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/redhat/rhn/domain/session/WebSessionFactory.java#L63) to get WebSession by its id returned null, even this WebSession being saved just some fractions of second before.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18176 …
> Fixed unexpected unauthorized when using HTTP API

- search-server/spacewalk-search/build.xml
Fixes `spacewalk-search` package build
No difference.
> search: set the JAVA_LIBDIR variable before imports use it

- java/code/src/com/suse/manager/webui/templates/content_management/build.jade
- java/spacewalk-java.changes
- web/html/src/manager/images/image-build.tsx
- web/html/src/manager/images/image-profile-edit.tsx
- web/spacewalk-web.changes
Profile ID and Host ID  were passed to javascript as strings in jade template, but the API returns numbers.
As a result, the comparison === in Select component did not match.
With this PR it uses numbers consistently.
No difference.
- No tests: 
Fixes https://github.com/SUSE/spacewalk/issues/17901 …
> Pass Profile and build host Id as a number (bsc#1199659)

- java/code/src/com/redhat/rhn/domain/image/ImageInfoFactory.java
- java/code/src/com/redhat/rhn/domain/server/Pillar.java
- java/code/src/com/suse/manager/reactor/messaging/test/ImageSyncedEventMessageActionTest.java
- java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java
- java/code/src/com/suse/manager/webui/services/test/SaltStateGeneratorServiceTest.java
- java/spacewalk-java.changes
- schema/spacewalk/postgres/triggers/suseImageInfo.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.3.12-to-susemanager-schema-4.3.13/110-suseImageInfo_del_pillar.sql
This PR moves image sync pillars to database. 
It creates/deletes the pillar for given group according to events sent by the branch server. Before, the pillars were created as files, now they are in DB.
For normal images it uses category `"SyncedImage" + ID`. The pillar is deleted with the image by a trigger.
There can be also legacy images which are not referenced in the database. For such images it uses category  `"LegacySyncedImage" - Name - Version`.
The second commit fixes the hashCode method of Pillar class.
When the hash was calculated from ID and pillar, it could change during object lifetime and patterns like this do not work:
```
branch.getPillarByCategory(category).orElseGet(() -> {
Pillar pillar = new Pillar(category, Collections.emptyMap(), branch); …
```
> Move ImageSync pillars to database

- testsuite/features/step_definitions/command_steps.rb
This PR detects error when editing `repo` files by replacing semicolons `; ` between sed commands with ` && `.
With a semicolon, only the last `sed` command could produce an error.
This PR also moves the invariants (the tests of `os_release`) outside of the loop.
https://en.wikipedia.org/wiki/Loop-invariant_code_motion
Finally, this PR removes one root cause for such errors: `os_pool_repo` and `os_update_repo` are not defined for CentOS.
Ports:
- 4.3: SUSE/spacewalk#18353
- 4.2: SUSE/spacewalk#18354
> Detect more sed errors when editing repositories

- spacewalk/setup/bin/spacewalk-setup-cobbler
- spacewalk/setup/spacewalk-setup.changes
- utils/spacewalk-hostname-rename
- utils/spacewalk-utils.changes
This PR corrects the behaviour of two things in `spacewalk-hostname-rename`:
1. Fix the default path handling for the Cobbler Apache directory.
2. Fix the `sed` expression which replaced data in `/root/.mgr-sync`
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17506
If you …
> Correct default path handling for Cobbler part of spacewalk-hostname-rename

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/kickstart.py
- spacecmd/tests/test_kickstart.py
There was a traceback on calling `spacecmd kickstart_export`:
```
File "/usr/bin/spacecmd", line 244, in <module>
shell.cmdloop()
File "/usr/lib64/python3.6/cmd.py", line 138, in cmdloop
stop = self.onecmd(line)
File "/usr/lib64/python3.6/cmd.py", line 217, in onecmd
return func(arg)
File "/usr/lib/python3.6/site-packages/spacecmd/kickstart.py", line 2302, in do_kickstart_export
ksdetails_list.append(self.export_kickstart_getdetails(p, kickstarts))
File "/usr/lib/python3.6/site-packages/spacecmd/kickstart.py", line 2251, in export_kickstart_getdetails
details[i].sort()
TypeError: '<' not supported between instances of 'dict' and 'dict'
```
No difference.
- Unit test was added
Tracks …
> Fix tracebacks on spacecmd kickstart_export (bsc#1200591)

- spacewalk/config/spacewalk-config.changes
- spacewalk/config/spacewalk-config.spec
While installing the pattern:
```
diff: /etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT: No such file or directory
diff: /srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT: No such file or directory
cp: cannot stat '/srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT': No such file or directory
warning: %posttrans(spacewalk-config-4.3.8-1.9.uyuni2.noarch.rpm) scriptlet failed, exit status 1
```
The error was caused by a typo in the `if` statement.
No difference.
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects= …
> fix posttrans error "RHN-ORG-TRUSTED-SSL-CERT" not found

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/kickstart.py
- spacecmd/tests/test_kickstart.py
`spacecmd` is showing help for `kickstart_import` instead of help for `kickstart_importjson` in case of calling `kickstart_importjson` with no arguments.
No difference.
- Unit test was added
Tracks https://github.com/SUSE/spacewalk/issues/18154 (not related to the issue directly, but was found during fixing the bug for this issue)
If …
> Show correct help for kickstart_importjson

- containers/proxy-httpd-image/proxy-httpd-image.changes
- containers/proxy-httpd-image/uyuni-configure.py
Since the user cannot call mgr-bootstrap on the containerized proxies,
mirror the complete /pub folder to get the server SSL cert and the
/pub/bootstrap folder content. (bsc#1199802)
No difference.
- No tests: proxy containers are not yet tested automatically
Fixes https://github.com/SUSE/spacewalk/issues/17942 …
> Mirror the complete pub folder in containerized proxy

- susemanager-utils/testing/automation/push-to-obs.sh
Other wise we get the following error at the 2obs jobs:
```
*************** PUSHING TO Devel:Galaxy:Manager:Head ***************
dnf-plugin-spacewalk
Going to update Devel:Galaxy:Manager:Head from SRPMS...
=== Processing package [dnf-plugin-spacewalk]
Try: 1
Try: 2
Try: 3
Couldn't load public key /root/.ssh/id_rsa: No such file or directory
ssh-keygen signature creation failed: 255
*** FAILED (checkout) [dnf-plugin-spacewalk]
```
As you an see, the error is wrong, as this gets fixed by having ` /root/.ssh/id_rsa.pub`.
Anyway, I tested this fix at Head, and now the script is able to submit,
No difference.
- No documentation needed: Submission jobs
- No tests: Tested by running it.
Related: https://github.com/SUSE/spacewalk/issues/18180 …
> The SSH public key is also required for OBS MFA

- susemanager-utils/testing/automation/push-to-obs.sh
- susemanager-utils/testing/docker/scripts/push-to-obs.sh
Basically check that the both files for private and public key exist both before we create the container, and *inside* the container.
It will help us if we ever remove any of the files, by mistake.
No difference.
- No documentation needed: Submission job
- No tests: Tested by running it.
Related: https://github.com/SUSE/spacewalk/issues/18180 …
> Some extra checks for MFA

- testsuite/features/support/commonlib.rb
- We need to consider more special cases like:
`http://download.suse.de/ibs/SUSE:/SLE-15-SP4:/Update:/Products:/Manager43/images/repo/SLE-Module-SUSE-Manager-Server-4.3-POOL-x86_64-Media1`
- We don't mirror anymore MIs repos.
No difference.
Ports:
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/18396 …
> QE: Fix the removed prefixes when we generate the custom repo names

- java/code/src/com/redhat/rhn/frontend/xmlrpc/XmlRpcLoggingInvocationProcessor.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/XmlRpcServlet.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/test/XmlRpcLoggingInvocationProcessorTest.java
- java/code/src/com/suse/manager/api/HttpApiLoggingInvocationProcessor.java
- java/code/src/com/suse/manager/api/HttpApiRegistry.java
- java/code/src/com/suse/manager/api/LoggingInvocationProcessor.java
- java/code/src/com/suse/manager/api/test/HttpApiLoggingInvocationProcessorTest.java
- java/code/src/log4j2.xml
- java/spacewalk-java.changes
It introduces a solution for logging HTTP API calls in a similar way to what is done on XML RPC.
The solution is based on Spark filters to capture which methods were called, which user called them and how long it took to process this request.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17890 …
> Introduced logging in the HTTP API

- java/buildconf/apidoc/asciidoc/scripts.txt
- java/buildconf/apidoc/docbook/scripts.txt
- java/buildconf/apidoc/html/scripts.txt
- java/buildconf/apidoc/jsp/scripts.txt
- java/buildconf/apidoc/singlepage/scripts.txt
- java/manager-build.xml
- java/spacewalk-java.changes
- Fixes the typo "HTTP over JSON" -> "JSON over HTTP"
- Puts the HTTP API examples on top of the page
- Adds an Ant target `apidoc-validate` to validate the API docs locally:
```bash
$ ant -f manager-build.xml apidoc-validate
```
Uyuni wiki has been updated with [instructions to use the new target](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API#validating-your-changes-locally).
Typo fixes
Fixes https://github.com/SUSE/spacewalk/issues/18237 …
> Fix typo and ordering of HTTP API example scripts

- containers/proxy-httpd-image/proxy-httpd-image.changes
- containers/proxy-httpd-image/uyuni-configure.py
- containers/proxy-systemd-services/uyuni-proxy-pod.service
- containers/proxy-systemd-services/uyuni-proxy-systemd-services.changes
Adds the cobbler proxy config to the httpd container and exposes the port 80 in the systemd services. No need to change the helm charts services since it's already there.
No difference.
- No tests: auto-installation is not automatically tested
Fixes https://github.com/SUSE/spacewalk/issues/18063 …
> Container proxy autoinstallation fixes

- java/code/src/com/suse/manager/api/HttpApiRegistry.java
- java/code/src/com/suse/manager/api/test/HttpApiRegistryTest.java
- java/spacewalk-java.changes
It changes the logout method from GET to POST on HTTP API.
No difference.
- No documentation needed: the change makes the code conform to the documentation.
Fixes https://github.com/SUSE/spacewalk/issues/17889
> Changed the logout method to POST on HTTP API

- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
- Add Leap/SLE repository to `obs-to-maven` config (requires `obs-to-maven-1.1.1`)
- Update gson from `2.8.5` to `2.8.9` in ivy config
- Explicitly specify JAR name which is different from the artifact name for `google-gson`.
> Update ivy config for google-gson-2.8.9

- java/code/src/com/redhat/rhn/domain/image/ImageInfo.java
- java/code/src/com/redhat/rhn/domain/image/ImageInfoFactory.java
- java/code/src/com/redhat/rhn/domain/image/test/ImageInfoFactoryTest.java
- java/spacewalk-java.changes
The first commit makes sure that the listDeltaImageInfos method returns only delta images from given org.
The second commit fixes a problem with deleting an image and related delta image in one transaction - it tried to set `target_image_id` to `null` and that failed on not null constraint. Using `updatable=false` prevents this behavior.
It also adjusts the unit test to catch this problem.
No difference.
Fixes # …
> Delta Image related fixes

- testsuite/features/secondary/srv_mainpage.feature
Adapt and remove cucumber tests related to the `About` link not present anymore on the main landing page (when signed out) since 4.3.
No difference.
- Cucumber tests were added : change `I see something` into `I see "Sign In"`and remove the section testing the `About` link for suse manager. 
Fixes: https://github.com/SUSE/spacewalk/issues/18323
No backport …
> Adapting cucumber tests relative to the About link in 4.3 mainpage

- testsuite/features/build_validation/add_custom_repositories/srv_wait_for_custom_reposync.feature
- testsuite/features/build_validation/reposync/srv_wait_for_product_reposync.feature
Adds a scenario to check reposync logs after repository syncing for custom channels is complete.
No difference.
- 4.2 backport : https://github.com/SUSE/spacewalk/pull/18322
> Check reposync logs after custom channels repo-sync

- susemanager-utils/susemanager-sls/salt/certs/suse.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Currently the deploy of SLE Micro CA Certificate is not working, because `update-ca-certificates` is never executed.
```
update-ca-certificates:
cmd.run:
- name: /usr/sbin/update-ca-certificates
- runas: root
- onchanges:
- file: mgr_ca_cert
{%- if grains['saltversioninfo'][0] >= 3002 %} # Workaround for bsc#1188641
- unless:
- fun: service.status
args:
- ca-certificates.path
{%- endif %}
```
This happens because SLE Micro has a false positive when checking `service.status` . To workaround the issue, we would check if an ca-certificates update is already running by checking `/var/lib/ca-certificates/ca-bundle.pem.tmp` file. 
No difference.
- No documentation needed: only internal and user invisible …
> Fix deploy of SLE Micro CA Certificate (bsc#1200276)

- containers/proxy-helm/Chart.yaml
- containers/proxy-helm/values.yaml
- rel-eng/push-packages-to-obs.sh
Adjust helm charts versions and default values depending whether we push to OBS or IBS
No difference.
- No tests: helm charts tooling
Fixes #
> Fix helm chart push to IBS and OBS

- testsuite/features/support/http_client.rb
Fixed the HTTP method to use POST instead of GET, according with the last change in the API.
No difference.
- No tests: fix on testsuit
> Changed logout method to use post

- testsuite/features/profiles/Docker/authprofile/Dockerfile
- testsuite/features/profiles/Docker/serverhost/Dockerfile
- testsuite/features/profiles/internal_nue/Docker/authprofile/Dockerfile
- testsuite/features/profiles/internal_nue/Docker/serverhost/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/authprofile/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/serverhost/Dockerfile
This PR tries to fix an issue in our CI caused by the upgrade of repositorie from SLES 15.2 to SLES 15.4 in our Docker Profiles.
We suspect that the base image  registry.mgr.suse.de/suma-head-testsuite must be upgraded to use 15.4. https://github.com/SUSE/spacewalk/issues/18450
But we will try to use the official image in this PR.
No difference.
No need ports, as we don't upgraded from 15.2 to 15.4 in Manager-4.2
@nodeg Please confirm :) ^^^ 
If you …
> QE: Using official 15.4 base images in our Docker Profiles

- testsuite/features/reposync/srv_wait_for_reposync.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/env.rb
Wait until all valid channels has been synced in CI.
For that purpose, we monitor the file `products.xml` until it exist in the channels folder (`/var/cache/rhn/repodata/#{channel}`).
CI run: https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/1447/console
No difference.
Ports:
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/18423 …
> QE: Wait until all valid channels has been synced in CI

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
This PR adds `python3-gnupg` to Debian 10 bootstrap repository as this is a dependency needed to install classic Salt 3004 minion package in Debian 10:
```
The following packages have unmet dependencies:
salt-common : Depends: python3-gnupg but it is not installable
Recommends: python3-contextvars but it is not installable
Recommends: python3-croniter but it is not going to be installed
```
No difference.
If …
> Add "python3-gnupg" to Debian10 bootstrap repo (bsc#1201842)

- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes an issue happening when bootstrapping a Debian 9 system using the "classic" Salt minion package:
```console
Apply States failed during bootstrap (retcode=2). Details:
pkg_|-salt-install-contextvars_|-python3-contextvars_|-installed: Problem encountered installing package(s). Additional info follows:
errors:
- Running scope as unit: run-rd65abbb383994fdb8d268b384a1ca046.scope
E: Unable to locate package python3-contextvars
```
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/18452 …
> Fix bootstrap issue in Debian 9 with classic minion because missing python3-contextvars (bsc#1201782)

- testsuite/features/step_definitions/common_steps.rb
`ss` gives the better output than `lsof`, especially when we have a small port number in a higher one:
```bash
head-srv:~ # lsof -i -P -n | grep 3333
postgres  13333   postgres   10u  IPv6 174132      0t0  UDP [::1]:50162->[::1]:50162 
postgres  13333   postgres   11u  IPv4 593821      0t0  TCP 127.0.0.1:5432->127.0.0.1:34556 (ESTABLISHED)
head-srv:~ # ss --listening --numeric | grep 3333
```
- CI PR run: https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-prs-ci-tests/1460/
- Issue: https://github.com/SUSE/spacewalk/issues/18314
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18314
Needs: https://github.com/SUSE/spacewalk/issues/18459
Manager 4.1
Manager 4.2
Make sure the …
> QE: Fixup for checking open/closed ports

- testsuite/features/step_definitions/command_steps.rb
Log when we wait to finish a sync. of a channel
No difference.
Ports:
- Manager-4.2
> QE: Log when we wait to finish a sync. of a channel

- testsuite/features/step_definitions/command_steps.rb
Use solv file to wait until a channel is sync.
As products.xml is an optional file.
```
// Optional files
if (updateinfoData != null) {
createdFiles.add(organizer.move(UPDATEINFO_FILE, "updateinfo.xml.gz", updateinfoData.getChecksum()));
}
if (productsData != null) {
createdFiles.add(organizer.move(PRODUCTS_FILE, "products.xml", productsData.getChecksum()));
}
``` 
No difference.
Ports:
- Manager-4.2 …
> QE: Use solv file to wait until a channel is sync

- testsuite/features/step_definitions/command_steps.rb
Fixes a ruby step in command_steps.rb in order to check for `sql_statements.sql.gz` instead of `sql_statements.sql`.
No difference.
Before:
After:
Fixes #
Tracks # 
> Fix for ISS v2 test issue

- containers/proxy-httpd-image/proxy-httpd-image.changes
- containers/proxy-salt-broker-image/proxy-salt-broker-image.changes
- containers/proxy-squid-image/proxy-squid-image.changes
- containers/proxy-ssh-image/proxy-ssh-image.changes
- containers/proxy-tftpd-image/proxy-tftpd-image.changes
"Tag" the docker images
We need this manually done until https://github.com/SUSE/spacewalk/issues/17786 is implemented (@cbosdo please schedule this task)
No difference.
- No documentation needed: Not needed. This is about the changelog
- No tests: Changelog changes
Related:
- https://github.com/SUSE/spacewalk/issues/17786
- https://github.com/SUSE/spacewalk/issues/18194 …
> "Tag" the docker images

- testsuite/features/step_definitions/command_steps.rb
Fix a step awaiting `products.xml` and wait for `solv` instead.
Add some logs in the channel-sync-waiting steps to keep some activity. 
No difference.
Fixes #
> Wait for solv instead of products.xml and add some logs to timeout loops

- .github/workflows/check_translations.yml
CI: add workflow to check if there are needed translations
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/15482
> CI: add workflow to check if there are needed translations

- testsuite/documentation/container-build-image.md
- testsuite/features/core/srv_channels_add.feature
- testsuite/features/core/srv_create_repository.feature
- testsuite/features/profiles/Docker/Dockerfile
- testsuite/features/profiles/Docker/add_packages.sh
- testsuite/features/profiles/Docker/authprofile/Dockerfile
- testsuite/features/profiles/Docker/authprofile/add_packages.sh
- testsuite/features/profiles/Docker/serverhost/Dockerfile
- testsuite/features/profiles/Docker/serverhost/add_packages.sh
- testsuite/features/profiles/internal_nue/Docker/Dockerfile
- testsuite/features/profiles/internal_nue/Docker/add_packages.sh
- testsuite/features/profiles/internal_nue/Docker/authprofile/Dockerfile
- testsuite/features/profiles/internal_nue/Docker/authprofile/add_packages.sh
- testsuite/features/profiles/internal_nue/Docker/serverhost/Dockerfile
- testsuite/features/profiles/internal_nue/Docker/serverhost/add_packages.sh
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_uyuni/config.xml
- testsuite/features/profiles/internal_prv/Docker/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/add_packages.sh
- testsuite/features/profiles/internal_prv/Docker/authprofile/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/authprofile/add_packages.sh
- testsuite/features/profiles/internal_prv/Docker/serverhost/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/serverhost/add_packages.sh
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_uyuni/config.xml
As suma-head-testsuite was build internally and manual, it was replaced with a uyuni based container build in OBS together with the other containers.
All teststuites should use the new uyuni-master-testsuite container. It is based on opensuse/leap:15.4 
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18450 …
> QE: use new testsuite container

- testsuite/features/profiles/Docker/authprofile/Dockerfile
- testsuite/features/profiles/internal_nue/Docker/authprofile/Dockerfile
- testsuite/features/profiles/internal_prv/Docker/authprofile/Dockerfile
The template for authenticated registry uses the wrong prefix.
When we copy the images, we store them below /cucutest
No difference.
> authenticated registry uses path prefix cucutest/

- testsuite/features/secondary/min_custom_pkg_download_endpoint.feature
- testsuite/features/upload_files/pkg_endpoint.sls
For the download endpoint test we need now a really existing server.
To fix the test a ftp server with a dummy repo was setup on the minima mirror.
Use that for the test.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18530 …
> use FTP server in minima-mirror for download endpoint test

- containers/proxy-httpd-image/remove_unused.sh
the httpd container failed to build at `remove_unused.sh` step. In a previous version we used to remove the `rpm-build` and its dependencies. Then we've decided to keep the `rpm-build` but the call to removing one of its dependencies stayed. I think we can safely remove it as well, since the zypper cache accounts for most of the used space in the image anyway. 
No difference.
- No tests needed
Fixes #
Tracks #  …
> Fix for httpd container failing to build

- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/step_definitions/command_steps.rb
This PR fixes the Cobbler tests. The PXE boot minion could not choose a SLE 15 SP2 entry in the boot menu that did not exist anymore.
It also removes quotes around something that is not a "string variable" but part of the step's name.
No ports, Uyuni and 4.3 only.
> The PXE boot minion is now SLE 15 SP4

- testsuite/features/upload_files/sle-15-sp4-autoyast.xml
This PR removes obsolete XML tags from SLE 15 SP4 cobbler profile.
See https://bugzilla.suse.com/show_bug.cgi?id=1201600.
No ports, Uyuni/4.3 only.
> Remove obsolete XML tags from cobbler profile

- spacewalk/admin/spacewalk-admin.changes
- spacewalk/admin/spacewalk-admin.spec
in `rhn.conf`, the default value for  `report_db_sslrootcert` is `/etc/pki/trust/anchors/LOCAL-RHN-ORG-TRUSTED-SSL-CERT` . This value is added in new reportdb installation, but it's not updated when an old reportdb version is already installed. This PR updates  `report_db_sslrootcert` to the new default value is the previous default value is set.
No difference. …
> force new report_db_sslrootcert if previous default is set

- java/code/src/com/redhat/rhn/taskomatic/task/threaded/TaskQueue.java
- java/spacewalk-java.changes
Taskomatic job `mgr-update-reporting-hub` won't finish. The issue seems to be caused on an error on checking when the task queue is empty.
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any …
> fix taskomatic task remain in progress

- java/code/src/com/redhat/rhn/frontend/xmlrpc/chain/ActionChainHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/action/ActionChainManager.java
- java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java
- java/spacewalk-java.changes
add onlyRelevant argument to addErrataUpdate API
No difference. …
> add onlyRelevant argument to addErrataUpdate API

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes
- python/test/unit/spacewalk/satellite_tools/test_yum_src.py
Fixes tracebacks on calling `spacewalk-repo-sync` on the repos with the update notice in the repos with missing `version`.
It sets the version to `"0"` to prevent DB schema issues.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/5617 …
> Fix reposync on loading update notice with no version

- java/code/src/com/redhat/rhn/common/conf/Config.java
- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/redhat/rhn/common/util/RecurringEventPicker.java
- java/code/src/com/redhat/rhn/domain/channel/Channel.hbm.xml
- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/redhat/rhn/frontend/action/channel/manage/RepositoriesAction.java
- java/code/src/com/redhat/rhn/frontend/action/channel/manage/SyncRepositoriesAction.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/taskomatic/task/MgrSyncRefresh.java
- java/code/webapp/WEB-INF/pages/channel/manage/syncrepos.jsp
- java/conf/rhn_java.conf
- java/spacewalk-java.changes
- utils/spacewalk-common-channels
- utils/spacewalk-utils.changes
This PR add a new configuration property to unify the management of custom and vendor channels. In particular when the property is set to true:
1) custom channel are synced together with vendor channels
2) when a custom channel is added using `spacewalk-common-channels` it is automatically synced
3) the UI to set up scheduled syncronization is disabled
After - Only when the configuration parameter is set to true:
- Documentation PR WIP
Fixes https://github.com/SUSE/spacewalk/issues/18138 …
> Automatic sync of custom channels

- testsuite/features/secondary/srv_monitoring.feature
After disabling monitoring Tomcat and Taskomatic services have to be
restarted. Accordingly the warning is displayed which should be checked
as the expected state.
No difference.
- No documentation needed: changed test scenario only.
Depends-On: uyuni-project/sumaform#1133
> Update expected state after disabling monitoring

- schema/reportdb/postgres/end.sql
- schema/reportdb/uyuni-reportdb-schema.changes
- schema/spacewalk/postgres/end.sql
- schema/spacewalk/susemanager-schema.changes
This PR switches two sql queries to use the pg_roles table instead of pg_authid.   When using a Cloud Based "RDS"  such as AWS, access to the pg_authid user is restricted as the cloud provider does not expose this. 
No difference.
[AWS limits access to pg_authid ](https://stackoverflow.com/questions/55143544/aws-rds-postgresql-access-to-pg-catalog-pg-authid-forbidden-in-all-contexts)
- [] No changelog needed …
> Switch to using pg_roles instead of pg_authid

- tftpsync/susemanager-tftpsync-recv/add.wsgi
- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes
Seems that it can happen that 2 "cobbler sync" run in parallel and the receiver on the proxy execute the same file in parallel.
This change is a step into better handling of this case.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/18618 https://github.com/SUSE/spacewalk/pull/18619
If you …
> fix problems with parallel running processes

- testsuite/features/core/srv_channels_add.feature
When we create a channel, a sync is triggered to create at least "empty" metadata.
In the testsuite we create and assign repositories shortly after it. When we now want to "sync" them
it could happen that the button is disabled as a sync is currently running.
Wait at the end of the channel_add test, for the metadata been generated.
This is also a test if that really happens.
After this we should not have problems to trigger another sync with the repo assigned and syncing the packges.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/18623 https://github.com/SUSE/spacewalk/pull/18624
Not ported to 4.1 …
> fix race condition when syncing channels

- testsuite/features/core/srv_create_repository.feature
Next try
No difference.
Addtitional on top of https://github.com/uyuni-project/uyuni/pull/5778
Tracks https://github.com/SUSE/spacewalk/pull/18632 https://github.com/SUSE/spacewalk/pull/18633 …
> wait for reposync been finished

- testsuite/ext-tools/maintenance_crawler.rb
This will fix the shebang of the maintenance crawler script and some
whitespace left inside.
Without the proper position of the shebang the script can only be
called with `ruby maintenance_crawler.rb` instead of just
`maintenance_crawler.rb`.
```bash
$ crawler.rb 25405                                                                                                                                                            
/home/dgedon/bin/crawler.rb: line 7: require: command not found                                                                                                               
/home/dgedon/bin/crawler.rb: line 8: require: command not found …
```
> QE: Fix maintenance crawler script header

- web/spacewalk-web.spec
Run production lint before building the package. We already have lint on Github actions, but we don't have actions running in the internal repos. This ensures we always keep things tidy.
No difference.
Fixes this old ticket: https://github.com/SUSE/spacewalk/issues/13149 …
> Lint before production build

- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes
When mgr-create-bootstrap-repo was called with -c <label> the option "--flush" had no effect.
This PR removed the old bootstrap repo also when the repo label is directly provided.
WARNING: bootsrap repos are multiarch. When flushing it for a specific label, all archs are removed, but only the specified is re-generated. The other archs should be generated as well **without using flush**
No difference.
- No documentation needed: already well explained
Fixes https://github.com/SUSE/spacewalk/issues/18174
Tracks  …
> flush directory also when called for a specific label (bsc#1200573)

- web/spacewalk-web.spec
Fix https://build.suse.de/package/live_build_log/Devel:Galaxy:Manager:4.2/spacewalk-web/SLE_15_SP3/aarch64
No difference.
> Roll back OBS lint

- java/code/src/com/redhat/rhn/domain/server/MinionServer.java
- java/spacewalk-java.changes
- schema/spacewalk/common/data/rhnPackageKey.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.0-to-susemanager-schema-4.4.1/100-rocky-epel.sql
- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
This PR should make Rocky Linux 9 work completely.
I hope I didn't miss something took me a while to get through all parts of the application.
The only thing I didn't add are the parts in the 2 `additional_products.json` files and the referencing repo templates in `mgr-bootstrap-data.py`, as I didn't know which IDs I would have had to set.
If you could tell me which I should set there I can of course also add this right away 🙂 
It also adds the EPEL 9 key to the schema as this hasn't been done up to now, as far as I can see.
No difference.
- Documentation issue was created: [uyuni-docs#1661](https://github.com/uyuni-project/uyuni-docs/issues/1661)
Make sure the changelogs entries …
> Add Rocky Linux 9 support

- .github/dependabot.yml
This will enable Dependabot updates for our used GitHub Actions.
See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
No difference. …
> Add Dependabot updates for GitHub Actions

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/step_definitions/command_steps.rb
This will fix an issue found during 4.3.1 BV regarding different service
names for SLE/Red Hat and Debian/Ubuntu. This will introduce a new step
to differentiate between them.
No difference.
Before:
After:
Manager 4.3
Manager 4.2 …
> QE: BV: Fix service name mismatch on Deblike

- testsuite/features/secondary/min_deblike_monitoring.feature
- testsuite/features/secondary/min_monitoring.feature
- testsuite/features/secondary/min_rhlike_monitoring.feature
- testsuite/run_sets/secondary_parallelizable.yml
This will add the same monitoring feature for the Debian-like minion like we already have for the SLE and the Red Hat-like minion.
Furthermore the old monitoring features now use the same logic as the new file introduced with https://github.com/uyuni-project/uyuni/pull/5819
No difference.
- Fixes https://github.com/SUSE/spacewalk/issues/18702
- https://github.com/uyuni-project/uyuni/pull/5819
- Manager 4.3
If …
> QE: add Debian-like monitoring feature

- .github/workflows/automatic-frontend-lint-fix-pr.yml
- .github/workflows/frontend-dependency-audit.yml
- .github/workflows/frontend-lint.yml
- .github/workflows/javascript-build.yml
- .github/workflows/javascript-unit-tests.yml
- .github/workflows/typescript-compilation.yml
In response to https://github.com/uyuni-project/uyuni/pull/5808, it would be very handy if the workflows reran themselves when there's a PR to change them so we can see if they're valid or not. I couldn't find a better way to try and implement this, perhaps @renner has any good ideas?
No difference.
If you …
> Rerun frontend workflows when workflow definitions change

- .github/workflows/labeler.yml
This will
- update the labeler GH action to the most recent version instead of the development version. Specifying a version number should also make Dependabot aware of updates for the labeler in the future.
- restricts the permissions. 
According to the official [labeler documentation](https://github.com/actions/labeler#inputs) only 2 are necessary:
`contents: read`
`pull-requests: write`
[Currently we use](https://github.com/uyuni-project/uyuni/runs/7915009892?check_suite_focus=true):
```bash
Actions: write
Checks: write
Contents: write
Deployments: write
Discussions: write
Issues: write
Metadata: read
Packages: write
Pages: write
PullRequests: write
RepositoryProjects: write
SecurityEvents: write
Statuses: write
```
See https://github.com/actions/labeler#create-workflow
No difference. …
> Update labeler GH action

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- susemanager/susemanager.spec
Add bootstrap repo data for Ubuntu 22.04 when synced with vendor channels.
No difference.
- https://github.com/SUSE/spacewalk/issues/18278
Port of https://github.com/SUSE/spacewalk/pull/18685
> create bootstrap repository data for Ubuntu 22.04 Vendor Channels

- .github/workflows/rubocop.yml
This will trigger the RuboCop workflow whenever the GH actions file
itself changes. Thanks @Etheryte for the suggestion!
@Etheryte PR: https://github.com/uyuni-project/uyuni/pull/5814
No difference. …
> QE: workflows when workflow definitions change

- python/uyuni/common/fileutils.py
- python/uyuni/uyuni-common-libs.changes
Fixes the function `makedirs` in `uyuni.common.fileutils` that was creating the required path even if the specified user/group did not exist, and then failing to chown. Now it does not create the path and raises an exception.
No difference.
- No documentation needed:  user invisible changes
- No tests:  bugfix
Fixes #5106 
Tracks https://github.com/SUSE/spacewalk/issues/17730 …
> Do not allow creating path if nonexistent user or group in fileutils

- testsuite/features/build_validation/retail/sle12sp5_terminal_deploy.feature
- testsuite/features/build_validation/retail/sle15sp4_terminal_deploy.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
- testsuite/features/step_definitions/retail_steps.rb
- testsuite/features/upload_files/reboot-pxeboot.exp
Like in Retail, we would like to know in test suite's Cobbler feature tests if reformatting really happened. For that we drop an `/intact` file in the PXE boot minion before trying to PXE boot it. After the PXE boot, the disk should have been reformatted and that file should be gone.
Also, when debugging a failed PXE boot, we would like to know which one of Cobbler or Retail was last to happen, by inspecting whether `/intact` contains `Cobbler` or `Retail`.
Ports:
* 4.2: SUSE/spacewalk#18713
* 4.3: SUSE/spacewalk#18712
> Check reformatting in Cobbler

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes
- python/test/unit/spacewalk/satellite_tools/test_yum_src.py
Adds the configured proxy to the url when using mirrorlist in reposync
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17493
Part of https://github.com/SUSE/spacewalk/issues/18523
> make zypper use proxy with mirrorlist

- .github/workflows/java-checkstyle.yml
Adding the workflow definition to `paths` in order to run the workflow when the definition itself changes. Inspired by @Etheryte's PR #5814.
No difference.
- No documentation needed, only CI changes.
- No tests, this is about GH actions.
Follow up to #5808, inspired by #5814.
> Update checkstyle workflow paths (to include itself)

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
Letsencrypt Root CA does not have an authorityKeyIdentifier set. This might be correct as it would point
anyway only to itself. But the script is using it to identify the self signed root ca.
This change detect "subject" == "issuer" and "isCA" and set the value for the internal evaluation.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/5830
Tracks https://github.com/SUSE/spacewalk/pull/18734 …
> fix root CAs which do not have authorityKeyIdentifier set to themself

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.0-to-susemanager-schema-4.4.1/200-fix-rhnActionImage-null.sql
The schema migration in https://github.com/uyuni-project/uyuni/pull/4404 is not correct, 
"NOT NULL" must be explicitly dropped.
No difference.
- No tests: schema migration tests do not catch this, not sure why.
Fixes https://github.com/SUSE/spacewalk/issues/18574
https://bugzilla.suse.com/show_bug.cgi?id=1202272 …
> Fix migration of image actions (bsc#1202272)

- testsuite/features/secondary/min_salt_formulas.feature
Enables and disables `os-update-repo` and `os-pool-repo` repositories before and after testing the locale formula as to include a missing package.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18537
4.2
4.3 …
> Enabling and disabling repositories before and after locale formula test

- testsuite/features/upload_files/sle-15-sp4-autoyast.xml
This PR fixes and issue happening on the testsuite around PXE booting, where we get errors like:
```
FAIL: expect -f /tmp/cleanup-pxeboot.exp 192.168.99.4 returned status code = 1.
Output:
spawn /usr/bin/ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 192.168.99.4
ssh: connect to host 192.168.99.4 port 22: Connection refused
send: spawn id exp3 not open
while executing
"send -- "linux\r""
(file "/tmp/cleanup-pxeboot.exp" line 6)
(RuntimeError)
./features/support/lavanda.rb:75:in `run'
./features/step_definitions/retail_steps.rb:284:in `/^I stop salt-minion on the PXE boot minion$/'
features/secondary/proxy_cobbler_pxeboot.feature:134:in `I stop salt-minion on the PXE boot minion'
```
The issue was caused because, the SLE15SP4 autoyast profile was **not** mentioning to …
> Include "openssh-server" to be installed by SLE15SP4 autoyast profile

- proxy/proxy/broker/rhnBroker.py
- proxy/proxy/spacewalk-proxy.changes
When changing the channels on the server side, the proxy token with a list of authenticated channels is still cached.
This prevent access to the new channels.
In case the requested channel is not in the channel list of the cached token, just try to renew it and check the channels
on the freshly updated token.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/18758 …
> renew the cached token when requested channel is not authorized

- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/spacewalk-java.changes
For image building, the download token contained list of all channels. The token was appended to each channel url.
In the end, the size of kiwi command line grew quadratically with the number of channels.
This commit generates new token for each channel.
No difference.
- No documentation needed: not an user visible change
- covered by Cucumber tests
Fixes https://github.com/SUSE/spacewalk/issues/18309
https://bugzilla.suse.com/show_bug.cgi?id=1201220
If you uncheck …
> Generate new token for each channel (bsc#1201220)

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/utils.py
- spacecmd/tests/test_api.py
Inside the `spacecmd` command-line interface the `api` function was showing an error when trying to pass dates with the `-A` argument. Now it parses the dates and calls the API endpoint with a suitable parameter type.
An example:
`api -A "sle-product-sles15-sp3-pool-x86_64,2022-05-20,2022-05-25" channel.software.listAllPackages`
No difference.
Fixes [#1198903](https://bugzilla.suse.com/show_bug.cgi?id=1198903)
Tracks  https://github.com/SUSE/spacewalk/issues/17671
If you don't need …
> Process date values in spacecmd api calls (bsc#1198903)

- testsuite/features/secondary/min_salt_formulas.feature
Adds the missing " for a test.
No difference.
[4.2](https://github.com/SUSE/spacewalk/pull/18773)
[4.3](https://github.com/SUSE/spacewalk/pull/18774)
> QE: Fix test typo

- testsuite/features/core/proxy_register_as_minion_with_gui.feature
- testsuite/features/core/proxy_register_as_minion_with_script.feature
- testsuite/features/core/proxy_register_as_trad_with_script.feature
- testsuite/features/step_definitions/command_steps.rb
Synchronize code between branches - bootstrapping proxies
In 4.3 and Uyuni, we don't need anymore the work around for bsc#1192195.
Sibling PRs:
* 4.2: https://github.com/SUSE/spacewalk/pull/18776
* 4.3: https://github.com/SUSE/spacewalk/pull/18775
> Synchronize code between branches

- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
In SUSE jakarta-activation does not provide what we need. We use glassfish-activation-api
No difference.
> jakarta-activation not required in SUSE

- java/code/src/com/redhat/rhn/domain/channel/Channel.java
- java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
- java/spacewalk-java.changes
Add support for calculating the dependencies of cloned vendor channels. By
- Get the original vendor channel and calculate dependencies for that
- Get all the clones of those dependencies
- Keep the clones that have the same base channel as the input channel we want the dependencies for.
No difference.
- No tests
Fixes #
Tracks https://github.com/SUSE/spacewalk/pull/18510
If …
> Calculate dependencies between cloned channels of vendor channels (bsc#1201626)

- java/spacewalk-java.changes
- java/spacewalk-java.spec
Public Cloud images are build only with "Required" packages. As `libtcnative-1-0` is only recommended, it is not available on Public Cloud images and produce a warning in tomcat about openssl cannot be loaded. As the native interface makes sense in our case anyway, we better require it in spacewalk-java
Additionally this PR reorder the dependencies to make them easier manageable.
It also drop some very old (spacewalk and satellite times) provides/obsoletes capabilites which we do not need anymore.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/18788
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs …
> Additional dependencies

- java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/reactor/messaging/test/state.apply.with.test.json
- java/spacewalk-java.changes
With salt 3004 the result of a "pkg.installed" with test=true has changed. 
In older versions and empty `changes: {}` was returned while with 3004 we have a structure similar to
an execution result
```
changes: {
'installed' : {
'adobe-sourcecodepro-fonts' : {
'new' : '2.030-1.30'
'old' : ''
}
}
}
```
Saltstack want to change this and return the same structure as when doing a real installation.
So we need to parse the function arguments and check for `test=True` and skip the evaluation of the result in the Java code.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/18547 …
> Fix state apply test mode result parsing

- testsuite/features/init_clients/sle_minion.feature
There's been an ongoing failing test across all branches, where we expected the `Test-Channel-x86_64` to be the Base Channel used for the SLE minion, but it's always the actual product channel being used as the Base Channel. After some investigation, it was found that, when removing the product migration from the normal CI testsuite, the part where we added the activation key was removed as well (https://github.com/uyuni-project/uyuni/commit/950514e00b43b2aff880303d5cd683ef4cc059d1#diff-81a40bfd7b5fe026484339618df80c8a557710f2bf8e4e80627c9c24345d17cbL78). So I added it to when we bootstrap the minion from the start.
Run [#1571](https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1571/)
No difference.
- …
> QE: Add activation key to sle_minion

- susemanager/susemanager.changes
- susemanager/susemanager.spec
server-migrator.sh is really only for Uyuni. Do not install it on SUSE Manager.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/18794 https://github.com/SUSE/spacewalk/pull/18795 …
> remove server-migrator.sh from SUSE Manager installations

- susemanager-utils/susemanager-sls/salt-ssh/preflight.sh
- susemanager-utils/susemanager-sls/susemanager-sls.changes
In case if there is no Salt Bundle for the debian based system preflight script could emit `rpm: command not found` error on the output, which makes no any sense in this case.
No difference.
- No tests: it's possible on unsupported debian based systems, which are out of scope of the testsuite …
> Fix preflight for salt ssh with no rpm message on debian systems

- containers/proxy-helm/proxy-helm.changes
- containers/proxy-helm/templates/config.yaml
- containers/proxy-httpd-image/Dockerfile
- containers/proxy-httpd-image/conf/mod_log_config.conf
- containers/proxy-httpd-image/proxy-httpd-image.changes
- containers/proxy-httpd-image/uyuni-configure.py
- containers/proxy-salt-broker-image/uyuni-configure.py
- proxy/proxy/apacheServer.py
- proxy/proxy/spacewalk-proxy.changes
- python/spacewalk/common/rhnLog.py
- python/spacewalk/spacewalk-backend.changes
This PR should make it easier to debug the containerized broker by redirecting logs into stdout/stderr inside a container.
Optionally we want also do discuss the possibility of implementing a more robust logs management solution for our container suite. 
No difference.
No tests: already covered
Fixes https://github.com/SUSE/spacewalk/issues/18428 …
> containerized broker logs

- testsuite/features/core/srv_create_repository.feature
Makes sure to check that the reposync has finished before disabling source package syncing. Outcome of discussion with @mcalmer on the root cause for the test failure on [this slack thread](https://suse.slack.com/archives/C02DDMY6R0R/p1661861712795339)
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18801
Will be ported only after running successfully in either Uyuni PR testsuite or Head and Master
- 4.2
- 4.3 …
> QE: Fix source package syncing

- java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java
- java/spacewalk-java.changes
- schema/spacewalk/common/data/rhnVirtualInstanceType.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.0-to-susemanager-schema-4.4.1/300-rhnVirtualInstanceType.sql
Show `Amazon EC2` in `Virtualization` field in the system profile for Amazon EC2 instances.
Requires https://github.com/openSUSE/salt/pull/555 to be present on the salt minion side.
Before:
Virtualization field in system profile was shown as `KVM/QEMU` or `Para-Virtualized` if running as `xen` instance.
After:
Virtualization field in system profile is labeled as `Amazon EC2`
- No tests: there is no tests for this part of functionality
Fixes https://github.com/SUSE/spacewalk/issues/16940
If you don't …
> Detect Amazon EC2 instances

- testsuite/features/core/srv_create_repository.feature
- testsuite/features/step_definitions/command_steps.rb
Waits for reposync to start instead of waiting for it to end to avoid losing session and taking too long.
Run [#1583](https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1583/)
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18801
Fixes #5869 
Ports
4.2
4.3
If you need to …
> QE: Fix reposync issue in core

- testsuite/features/support/http_client.rb
- testsuite/features/support/namespaces/activationkey.rb
- testsuite/features/support/namespaces/api.rb
- testsuite/features/support/xmlrpc_client.rb
Makes small adjustments to API calls while following the API doc.
- `activationkey.rb` correcting parameters values
- ~~`api.rb` adjusting `get_version` and `system_version` calls so they include a second parameter that is required (empty Hash)~~
- ~~`http_client.rb` to include `system_version` as a GET request and accept a default empty argument on api call~~
- ~~`xmlrpc_client.rb` to accept a default empty argument on api call~~
- Remove paraemeter-less api calls in `api.rb`
No difference.
Before:
After:
Ports :
4.2
4.3 …
> QE: Adjusting small API errors

- testsuite/features/core/srv_create_repository.feature
- testsuite/features/step_definitions/command_steps.rb
:weary: 
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18801
Fixes https://github.com/uyuni-project/uyuni/pull/5869
Fixes https://github.com/uyuni-project/uyuni/pull/5876
Ports
4.2
4.3 …
> QE: Fix core reposync with channel label

- susemanager-utils/susemanager-sls/src/modules/mgrnet.py
- susemanager-utils/susemanager-sls/src/tests/mockery.py
- susemanager-utils/susemanager-sls/src/tests/test_module_mgrnet.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Implements `mgrnet` salt module with the only function `mgrnet.dns_fqdns`.
`mgrnet.dns_fqdns` returns the list `dns_fqdns` with all found FQDNs with native DNS tools: `host` or `nslookup`.
If none of these tools available on the system, the function returns the list `fqdns` identical to the result of `network.fqdns` salt function.
No difference.
TBD
Tracks https://github.com/SUSE/spacewalk/issues/17929
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni …
> Add mgrnet salt module

- tftpsync/susemanager-tftpsync-recv/rhn_tftpsync.conf
- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes
Without these keys, existing proxies need to re-run the configuration script to add these keys to their config files. The config files are expected to exist, if they are missing, cobbler sync fails.
No difference.
- No tests: @uyuni-project/qe deems it too resource intensive to properly test proxy upgrades + cobbler.
Fixes # …
> Add missing IPv6 default configuration

- testsuite/features/step_definitions/command_steps.rb
:weary: :tired_face: 
https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1588/
https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1590/
https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1591/
https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1593/
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18801
Fixes https://github.com/uyuni-project/uyuni/pull/5869
Fixes https://github.com/uyuni-project/uyuni/pull/5876
Ports
4.2
4.3 …
> QE: Fix reposync fix

- python/spacewalk/satellite_tools/mgr-sign-metadata-ctl
- python/spacewalk/spacewalk-backend.changes
When signing metadata we deploy now also the armored key to the managed systems.
To do this, we need to make the key present in the salt filesystem.
This PR adapt `mgr-sign-metadata-ctl` command to permform the export
No difference.
* Release Notes (note added to https://github.com/SUSE/spacewalk/issues/18198)
* https://github.com/uyuni-project/uyuni-docs/pull/1744
Fixes https://github.com/uyuni-project/uyuni/issues/5805
Tracks https://github.com/SUSE/spacewalk/pull/18840
If you …
> export armored GPG key to salt filesystem

- susemanager-utils/susemanager-sls/salt/certs/suse.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Syntax error in state file
No difference.
- No tests: **unsupported os**
Tracks https://github.com/SUSE/spacewalk/pull/18865
> fix syntax error - remove trailing colon (bsc#1203049)

- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/step_definitions/common_steps.rb
This PR lets sumaform decide alone about the beta tools (we won't deselect them anymore from the test suite).
Sibling PRs:
* sumaform: uyuni-project/sumaform#1159
* 4.2: SUSE/spacewalk#18866
* 4.3: SUSE/spacewalk#18870
> Use sumaform as single source of truth for beta tools

- java/code/src/com/redhat/rhn/manager/content/MgrSyncUtils.java
- java/spacewalk-java.changes
port of https://github.com/SUSE/spacewalk/pull/18538
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18457
> Fix mirror accessible URL for NVIDIA and openSUSE channels (bsc#1201753)

- testsuite/features/reposync/srv_enable_sync_products.feature
When we test the product wizard, we enable SLED 15 SP4, while we intend to bootstrap SLES 15 SP4.
The problem is that both products share same packages. This creates a problem when we kill the reposyncs, the bootstrap repo for SLES 15 SP4 does not get created because SUSE Manager waits for the killed repos to be fully synced.
Strictly speaking, this is a product issue, but it needs a serious refactoring, for a use case that not many customers will meet. So let's work around it by reposyncing different SPs.
Ports:
* 4.2: https://github.com/SUSE/spacewalk/pull/18893
* 4.3: https://github.com/SUSE/spacewalk/pull/18892
Fixes #18707
> Do not use same SP for SLES and SLED

- java/code/src/com/redhat/rhn/frontend/action/schedule/CompletedSystemsAction.java
- java/code/src/com/redhat/rhn/frontend/action/schedule/FailedSystemsAction.java
- java/spacewalk-java.changes
This PR fixes an issue in the pagination of the completed and failed system of the event details page. Currently only the first 25 system are extracted from the database because the `PageControl` is recreated on each request. 
No difference.
- No documentation needed: bug fix on a documented functionality
Fixes https://github.com/SUSE/spacewalk/issues/18871
Tracks https://github.com/uyuni-project/uyuni/issues/5854 …
> Fixed pagination for completed/failed systems in action details

- testsuite/features/support/constants.rb
Tools for SLED are shared with SLES, we must not kill their reposync.
Note: version for 4.2 has a piggyback commit, meant to use sle 15 sp3 as the default for auto-installation, instead of sp2.
Ports:
* 4.2: https://github.com/SUSE/spacewalk/pull/18915
* 4.3: https://github.com/SUSE/spacewalk/pull/18914
> Tools for SLED are shared with SLES, we must not kill their reposync

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.0-tosusemanager-schema-4.4.1/001-remove-cluster_admin.sql
Remove the `cluster_admin` group from the database now that the cluster feature has been removed from the code base.
No difference.
- No tests: removed code is not tested 😉 
Fixes https://github.com/SUSE/spacewalk/issues/18617 …
> Remove legacy cluster_admin user group

- testsuite/features/upload_files/pkg_endpoint.sls
With the new firewalled network, it will get harder to use a test resource in PRV with test suites in NUE.
The best strategy is to duplicate every resource between NUE and PRV. It's also a good idea for resiliency / disaster recovery.
This PR uses the custom endpoint for FTP test in minima-mirror.mgr.suse.de in substitution for minima-mirror.mgr.prv.net in case of the HEAD and Uyuni test suites.
It will be followed by another PR that will add a sanity check to check the availability of the resource.
Fixes SUSE/spacewalk#18568
No ports, uyuni branch only
> For Head and Uyuni, use an endpoint in NUE

- testsuite/features/secondary/minkvm_guests.feature
Wait for "Hosted Virtual Systems" text in Create an auto installing KVM virtual machine scenario as the page is not ready when the step is run, causing it to fail.
Fixes #
Tracks # 
4.2
4.3 …
> QE: Wait for "Hosted Virtual Systems" text in KVM feature

- testsuite/features/step_definitions/navigation_steps.rb
Related to https://github.com/SUSE/spacewalk/issues/18486
Adding a rescue in a step that was looking for details of an already detached web element.
No difference.
Ports:
- Manager-4.2
- Manager-4.3
> QE: Rescue from detached element

- testsuite/features/step_definitions/common_steps.rb
Related to https://github.com/SUSE/spacewalk/issues/18947
This is just some additional log to understand what's the extra repository enabled in our minion at that point in the test suite.
No difference.
Ports:
- Manager-4.2
- Manager-4.3 …
> QE: Adding more log to be able to debug enabled channels

- java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
- java/spacewalk-java.changes
It fixes an out of memory error by changing the strategy to apply allow/deny filters. The problem currently happens when applying live patch template filters on the `SLES12-SP5-Updates for x86_64` channel which has a large number of errata to be filtered out. But, the root cause is related to a high number of `java.util.HashMap$Node` in the heap space, flooding it.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18630
If you …
> Fix out of memory error when building a CLM project

- java/code/src/com/redhat/rhn/domain/server/ServerGroup.hbm.xml
- java/spacewalk-java.changes
It fixes deleting a formula from a system group by adding orphan removal in the hibernate mapping.
No difference.
No documentation needed: bug fix.
Port of https://github.com/SUSE/spacewalk/pull/18711
> Added orphan removal to pillars mapping

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minxen_guests.feature
- testsuite/run_sets/secondary.yml
- testsuite/run_sets/secondary_parallelizable.yml
- Get rid of the clean-up scenarios that were unregistering KVM/XEN hosts. The reason behind it is that is worth to have History events available when the test-suite ends, than what we could gain with idempotency in these features.
- Make use of event status when we create heavy virtualized resources which takes time to be created. Before we were just waiting without much more details in the page were the resource should be shown, now if it fails we have a screenshot with the Event details.
No difference.
Ports:
- Manager-4.2
- Manager-4.3 …
> QE: Improving reliability of KVM/XEN tests

- susemanager-utils/susemanager-sls/salt/channels/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
When "mgr_disable_local_repos" is set to `False`, the bootstrap repository stays enabled as all local repos are disabled only before the bootstrapping.
In this case disable at least the bootstrap  repo.
Port of https://github.com/SUSE/spacewalk/pull/18973
No difference. …
> disable always the bootstrap repository

- containers/README.md
More k3s documentation fix
No difference.
- No documentation needed: It is a doc that is updated
- No tests: doc
Fixes #
> k3s doc fixes

- testsuite/features/secondary/min_custom_pkg_download_endpoint.feature
Follow-up of 5904
Use minima-mirror.mgr.suse.de when testing in NUE.
No ports, Uyuni branch only
> Use package download endpoint in NUE for HEAD and Uyuni

- testsuite/features/core/allcli_sanity.feature
When running the tests at PR, we are running this test in PRV while the download point is in NUE. This can't work because firewall rules prevent this connection.
This can be reverted once
https://github.com/SUSE/spacewalk/issues/18953 is fixed.
No difference.
- No documentation needed. This a change in the testsuite.
- This is a change in the testsuite.
Temporary fix until https://github.com/SUSE/spacewalk/issues/18953 is fixed. …
> Disable sanity check for ftp custom download point

- testsuite/features/support/twopence_init.rb
Prints the OS version of each node in the testsuite at runtime.
Fixes # https://github.com/SUSE/spacewalk/issues/18722
Tracks # 
4.2
4.3
> QE: Printing node OS in twopence_init.rb

- testsuite/features/secondary/min_salt_formulas.feature
- testsuite/features/step_definitions/salt_steps.rb
Part of https://github.com/SUSE/spacewalk/issues/18537
Fix for https://github.com/SUSE/salt-formulas/pull/179
No difference.
Ports:
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/19007
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/19008 …
> QE: Fix for https://github.com/SUSE/salt-formulas/pull/179

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
python3-py is required by salt.
This package was updated in SLE15 SP3/SP4 and with this update it got new dependencies to 'python3-apipkg' and 'python3-iniconfig'. But they do not exist in older SPs as the old version did not require them.
This PR mark these packages as optional.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/19002 …
> mark some bootstrap repo packages as optional

- susemanager-utils/susemanager-sls/salt/channels/init.sls
Multiple `{%-` cause removing multiple empty lines until 2 states appear in the same line which cause the json parse error.
Including disablelocalrepos.sls without removing the line.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/19012 …
> fix jinja newline removal causing state text joins

- susemanager-utils/susemanager-sls/salt/hardware/profileupdate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
The check `if 'mgrnet.dns_fqdns' in salt` does not work with ssh minion.
Checking the required tools is more reliable.
No difference.
- covered by Cucumber tests
Fixes 
> Fix mgrnet availability check

- containers/proxy-helm/proxy-helm.changes
- containers/proxy-helm/templates/config.yaml
- containers/proxy-helm/templates/deployment.yaml
- containers/proxy-helm/templates/service.yaml
- containers/proxy-helm/templates/volumes.yaml
- containers/proxy-helm/values.yaml
Setting the namespace as a value overrides the helm `-n myns` option. Removing those would just use the default option unless the user provides the `-n` parameter.
No difference.
- No documentation needed: would just work as expected by user
- No tests: helm chart is not tested
Fixes # …
> Helm chart: remove namespace value

- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
Fixes two more places that didn't properly handle the new salt function name format.
No difference.
- No tests
> properly handle salt function name array check

- python/spacewalk/satellite_tools/spacewalk-debug
- python/spacewalk/spacewalk-backend.changes
This PR enhance the cleanup of passwords done by `spacewalk-debug` when executed on the context of `supportconfig`.
There were some missing files that were not taken into account for the cleanup, like `rhn.conf.orig`, `uln.conf` and also cobbler settings.
This PR takes cares of including those missing files into the cleanup.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/18286
If you uncheck …
> spacewalk-debug: enhance passwords cleanup and include extra files (bsc#1201059)

- testsuite/features/finishing/srv_debug.feature
- testsuite/features/step_definitions/command_steps.rb
`grep` OOM error messages in `/var/log/messages` 
Fixes https://github.com/SUSE/spacewalk/issues/16986
Tracks # 
4.2
4.3
> Checking /var/log/messages for OOM errors

- testsuite/features/core/srv_create_repository.feature
- testsuite/features/step_definitions/command_steps.rb
Related issue https://github.com/SUSE/spacewalk/issues/18801
As we suspected from day one... it will be not enough only by waiting the channel start synchronizing, so this PR replaces the "wait for the channel to start sync" by "wait the channel has been fully sync"
No difference.
Ports:
- Manager-4.2
- Manager-4.3 …
> QE: Replace wait for the channel to start sync by wait the channel has been fully sync.

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minxen_guests.feature
- testsuite/features/step_definitions/common_steps.rb
In order to fix : https://github.com/SUSE/spacewalk/issues/18659
Customizing the time we wait until a event is picked up
No difference.
Ports:
- Manager-4.2
- Manager-4.3
> QE: Customizing the time we wait until a event is picked up

- susemanager-utils/susemanager-sls/modules/pillar/suma_minion.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- susemanager-utils/susemanager-sls/test/test_pillar_suma_minion.py
Read `postgres` options from `__master_opts__` if present to avoid possible tracebacks described in https://github.com/uyuni-project/uyuni/issues/5710
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/5710
Tracks https://github.com/SUSE/spacewalk/issues/18980 https://github.com/SUSE/spacewalk/issues/19030 …
> Fix reading postgres options with suma_minion ext pillar module

- utils/spacewalk-hostname-rename
- utils/spacewalk-utils.changes
Settings file for cobbler was moved from `/etc/cobbler/settings` to `/etc/cobbler/settings.yaml`, so the `spacewalk-hostname-rename` is failing if cobbler is migrated to `/etc/cobbler/settings.yaml` already.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19053 …
> Fix spacewalk-hostname-rename failing on reading /etc/cobbler/settings

- tftpsync/susemanager-tftpsync-recv/add.wsgi
- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes
There are some possible casses on getting the following tracebacks due to the race condition:
```
2021-12-05 18:36:02,531 - tftpsync_add - ERROR - Writing file failed: [Errno 2] No such file or directory: '/srv/tftpboot/grub/i386-pc/echo.mod.tmp' -> '/srv/tftpboot/grub/i386-pc/echo.mod'
File "/srv/www/tftpsync/add", line 105, in application
os.rename(tfname, rfname)
FileNotFoundError: [Errno 2] No such file or directory: '/srv/tftpboot/grub/i386-pc/echo.mod.tmp' -> '/srv/tftpboot/grub/i386-pc/echo.mod'
2021-12-05 18:36:02,568 - tftpsync_add - INFO - setting file '/srv/tftpboot/grub/i386-pc/blocklist.mod' (grub), status: 200 OK
2021-12-05 18:36:02,569 - tftpsync_add - ERROR - Writing file failed: [Errno 2] No such file or directory: …
```
> Prevent race conditions on cobbler sync

- testsuite/features/core/proxy_register_as_minion_with_gui.feature
- testsuite/features/core/proxy_register_as_minion_with_script.feature
- testsuite/features/core/proxy_register_as_trad_with_script.feature
Remove a check for Uyuni proxy product in our system details.
We will never use this commented step, as the system details in Uyuni will never show a product not available in SCC. And Uyuni Proxy is not in SCC.
No difference.
- Cucumber tests were removed
Ports (only for the sake of homogenized code):
- Manager-4.2
- Manager-4.3 …
> QE: Remove a check for Uyuni proxy product in our system details

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/retail_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/support/client_stack.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/lavanda.rb
- testsuite/features/support/twopence_init.rb
Implement OS attributes in `lavanda.rb` and using these attributes to replace calls to `get_os_version` and reduce the number of SSH calls.
Original comment: https://github.com/uyuni-project/uyuni/pull/5931#discussion_r971704252
Fixes # https://github.com/SUSE/spacewalk/issues/19000
Tracks # 
4.2
4.3
If …
> QE: Replacing get_os_version occurences

- java/code/src/com/suse/manager/webui/utils/salt/custom/HwProfileUpdateSlsResult.java
- java/code/src/com/suse/manager/webui/utils/salt/test/HwProfileUpdateSlsResultTest.java
- java/code/src/com/suse/manager/webui/utils/salt/test/hw_profile_update_res.json
- java/spacewalk-java.changes
Fix NPE in hardware refresh with a Salt-SSH Centos 7 minion without any activation key
No difference.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1203611
> Fix NPE in getDnsFqdns()

- tftpsync/susemanager-tftpsync-recv/add.wsgi
- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes
This reverts commit 32ce6d387998098f95ec3b56b7b86bec7bee95e6 (PR #5961) as we think the current fix is is not really avoiding the race condition to happen and it might hit performance.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/16495 …
> Revert "Prevent race conditions on cobbler sync (#5961)"

- testsuite/features/support/cobbler_test.rb
To avoid timeout errors during Cobbler buidliso tests, use the testsuite-wide `DEFAULT_TIMEOUT` (250 seconds) instead of the default for the XML-RPC library (30 seconds).
Fixes SUSE/spacewalk#18913
Ports:
* 4.2: https://github.com/SUSE/spacewalk/pull/19116
* 4.3: https://github.com/SUSE/spacewalk/pull/19115
> Use DEFAULT_TIMEOUT for Cobbler tests

- spacewalk/setup/bin/spacewalk-setup-cobbler
- spacewalk/setup/spacewalk-setup.changes
- spacewalk/setup/spacewalk-setup.spec
This PR makes `spacewalk-setup-cobbler` to trigger the migration of existing Cobbler settings and collections if necessary, particularly in the context of upgrading from previous Cobbler 3.1.2 version to latest 3.3.3.
Before this PR, after the upgrade to Cobbler 3.3.3, the "cobblerd" daemon was not able to start due deprecated values found on stored Cobbler collections, and also the current settings were not migrated to new `settings.yaml`.
This migration will now happen when `/etc/cobbler/settings` is detected, meaning we are coming from old Cobbler 3.1.2 and we need to migrate collections and settings to 3.3.3.
The steps are the following:
1. Make a backup of older `settings` file before executing migration.
2. Create a backup of stored cobbler collections before migration.
3. Execute …
> Migrate cobbler settings and collections to newer cobbler version (bsc#1203478)

- java/code/src/org/cobbler/CobblerObject.java
- java/spacewalk-java.changes
Fixes cobbler API use showing this exception:
```
redstone.xmlrpc.XmlRpcFault: <class 'TypeError'>:get_item_resolved_value() takes 3 positional arguments but 4 were given
at redstone.xmlrpc.XmlRpcClient.handleResponse(XmlRpcClient.java:444) ~[redstone-xmlrpc-client-1.1_20071120.jar:?]
at redstone.xmlrpc.XmlRpcClient.endCall(XmlRpcClient.java:376) ~[redstone-xmlrpc-client-1.1_20071120.jar:?]
at redstone.xmlrpc.XmlRpcClient.invoke(XmlRpcClient.java:165) ~[redstone-xmlrpc-client-1.1_20071120.jar:?]
at org.cobbler.CobblerConnection.invokeMethod(CobblerConnection.java:146) ~[rhn.jar:?]
at org.cobbler.CobblerConnection.invokeTokenMethod(CobblerConnection.java:179) ~[rhn.jar:?]
at org.cobbler.CobblerObject.getResolvedValue(CobblerObject.java:263) ~[rhn.jar:?]
at …
```
> Cobbler's get_item_resolved_value has not token

- testsuite/run_sets/secondary_parallelizable.yml
First PR for this card https://github.com/SUSE/spacewalk/issues/19103
No difference.
- Cucumber tests were disabled
Ports:
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/19121
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/19122
> QE: Disabling XEN test coverage, in preparation to completely remove them

- testsuite/features/secondary/min_timezone.feature
We see errors on this test, not finding "scheduled by MalaysianUser" but there are pending actions.
So wait until the action was at least picked up before checking for this text
Switched 2 tests to execute "run now" first as we need to wait until this action is completed.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/19126 https://github.com/SUSE/spacewalk/pull/19125 …
> wait until remote command was really executed

- testsuite/features/secondary/min_bootstrap_negative.feature
Refactor of negative tests to don't collide with other tests.
We now use localhost (controller host) to run the negative tests. 
No difference.
Ports:
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/19130
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/19129 …
> QE: Refactor of negative tests to don't collide with other tests

- testsuite/features/secondary/min_deblike_openscap_audit.feature
Switch to Ubuntu 22.04 only in 4.3/Head/Uyuni CT
Card: https://github.com/SUSE/spacewalk/issues/18857
Epic: https://github.com/SUSE/spacewalk/issues/17721
Dependency: https://github.com/SUSE/spacewalk/issues/18408
No difference.
- Cucumber tests were updated
Ports:
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/19132 …
> QE: Changing the only moving piece in our CT to update Ubuntu version

- .github/workflows/check_translations.yml
We need to compare if the PR needs more translations than the master branch. Without this fix, we were looking whether the master branch needed translations, because we use the event "pull_request_target", and with this event, the checkout is from the base branch (base branch=target branch), instead for the branch from the PR.
This is a fix for a github action (CI), not the product.
This is a fix for a github action (CI), not the product.
- No tests
This is a fix for a github action (CI), not the product.
Fixes https://github.com/SUSE/spacewalk/issues/19144
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectu …
> CI: fix needs translation

- testsuite/features/step_definitions/command_steps.rb
When we upgrade from Ubuntu20 to Ubuntu22, an issue enabling universe repo started, apparently we can't handle it as we were doing. We refactored. But now we have in our source code a URL from the origin server of Ubuntu repositories. That might need a next refactor.
For now that should unblock us.
No difference.
Ports:
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/19190 …
> QE: Refactor how we enable/disable Ubuntu universe repo

- testsuite/features/secondary/allcli_action_chain.feature
- testsuite/features/secondary/allcli_software_channels.feature
Fix another remaining issue from trad stack removal.
We need to have both sle and rh-like minion subscribed to the same channel in order to select a package to be installed. In this PR we fix this. Plus a scenario removed by mistake.
No difference.
NO PORTS …
> QE: Fix another remaining issue from trad stack removal

- susemanager-utils/testing/automation/wait-for-syncs.sh
This script is used in the CI to wait for package synchronization in the mirror.
No difference.
- No tests
Fixes # https://github.com/SUSE/spacewalk/issues/18522
> CI: add wait for sync tool

- java/buildconf/build-props.xml
- java/manager-build.xml
- sonar-project.properties
Remove the use of `<property environment="env"/>` in ant scripts since this may break if one environment variable has a value containing `${`... happens seldomly, but still...
Also add sonarcloud config to avoid counting the non-java files in the coverage checks
No difference.
- No tests: tooling
Fixes # …
> Don't read env from ant files

- testsuite/features/step_definitions/common_steps.rb
Fix the test suite for new network prefixes.
I did not change lines like:
```
testsuite/features/upload_files/virtualization/vCenter.json:        "10.162.186.111": {
```
as such addresses are fake anyway.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/19253
* 4.2: https://github.com/SUSE/spacewalk/pull/19254
> Use more vague IPv6 prefix

- spacecmd/spacecmd.changes
- spacecmd/src/bin/spacecmd
- spacecmd/src/spacecmd/activationkey.py
- spacecmd/src/spacecmd/configchannel.py
- spacecmd/src/spacecmd/kickstart.py
- spacecmd/src/spacecmd/proxy.py
- spacecmd/src/spacecmd/shell.py
- spacecmd/tests/test_activationkey.py
- spacecmd/tests/test_configchannel.py
- spacecmd/tests/test_shell.py
Previously there were two ways to print the "results" of commands: by leveraging a function called by postcmd or inside the command definitions. Most commands already printed "internally", but a few returned string or other sequences that were printed "externally".
For consistency, all output must be generated inside command definitions going forward. Existing code is adapted in this PR to meet that requirement.
Before:
On many commands, debug output contained the following:
```
DEBUG: system_list: 0
DEBUG: Undefined return code from "system_list"
```
After:
The only debug output is the following, independent of the type of the return value.
```
DEBUG: command=system_list, return_value=0
```
- No documentation needed: Only debug output changes.
Related issue …
> Refactor command result printing (bsc#1203283)

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
Remove test for uptime from BV, it mostly fails and doesn't add that much value to the BV I think, each client/minion has very different uptimes from CI and it will continue failing.
No difference.
Fixes no issue, directly from testsuite review
Tracks:
Manager-4.3: https://github.com/SUSE/spacewalk/pull/19256
Manager-4.2: https://github.com/SUSE/spacewalk/pull/19258 …
> Remove test for uptime from BV

- java/buildconf/manager-developer-build.properties.example
- java/manager-build.xml
This PR makes a small change in the ant `manager-build.xml` file. It allows to skip the `clean` step performed currently before each `compile`. In order to enable it, a new property `build.incremental.compile` needs to be defined inside the custom properties file `manager-developer-build.properties`. Without it, the build process maintains the old behaviour. 
When the property is enabled, the `clean` step will work as expected if invoked directly. So the old behaviour can still be obtained by chaining the tasks:
```
ant -f manager-build.xml clean webapp
```
This change is meant only as a developer convenience, to save time during build and deploy. 
No difference.
- No tests: change only affect the build process
Make sure …
> Added a property to avoid automatic cleaning before each ant compilation

- java/code/src/com/redhat/rhn/domain/channel/Channel.java
This deprecation generates sonarcloud errors and has no replacement solution. Just added a comment in the doc to not use it to count packages.
No difference.
- No tests: Annotation
Fixes # …
> Remove Channel.getPackage() deprecation

- susemanager-utils/susemanager-sls/salt/packages/pkgupdate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Add `refresh` to `packages.pkgupdate` the same way as set for `packages.pkginstall` as it could fail on updating the packages on the client if the repo was not refreshed before and has no this update in the cached repo metadata yet.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/19151 …
> Perform refresh with packages.pkgupdate state (bsc#1203884)

- java/code/src/com/redhat/rhn/frontend/xmlrpc/BaseHandler.java
- java/spacewalk-java.changes
Fixes an issue where only the first method is considered as fallback which leads to random jvm ordering of methods determining if call succeeds or fails.
No difference.
Before:
After:
- No tests
Fixes #https://github.com/SUSE/spacewalk/issues/19080
> consider all matched methods as fallback for xmlrpc (bsc#1203633)

- testsuite/features/step_definitions/retail_steps.rb
Use `NetworkManager` service instead of `network` for rh-like minion (Rocky 8)
Fixes # https://github.com/SUSE/spacewalk/issues/19268
> Using NetworkManager for Rocky 8 minion

- susemanager-utils/testing/automation/wait-for-builds.sh
Waiting on other archs and on images makes the thing suuuuper slow. Let's add the possibility to set repo and arch as optional args.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/18522
> CI: add repo and arch to wait-for-build script

- spacewalk/setup/lib/Spacewalk/Setup.pm
- spacewalk/setup/spacewalk-setup.changes
Removed `Net::LibIDN` from `Net::LibIDN::idn_to_ascii` in `spacewalk/setup/lib/Spacewalk/Setup.pm`.
Otherwise LibIDN2 cannot be used,
No difference.
> Re-added alternative usage of perl-Net-LibIDN2

- java/code/src/com/suse/manager/reactor/messaging/RegistrationUtils.java
- java/spacewalk-java.changes
backport of https://github.com/SUSE/spacewalk/pull/19241
> delay hardware refresh action to avoid missing channels (bsc#1204208)

- testsuite/features/reposync/srv_add_rocky8_repositories.feature
The sync will autmatically triggered when creating the custom channel or when adding repositories to a custom channel according to @mackdk , so this step can be skipped. Hopefully skipping this manual sync solves the not visible Sync Now button issue seen in the test suite.
No difference. …
> QE: Remove manual Rocky 8 custom channel sync

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/spacewalk-java.changes
backport of: https://github.com/SUSE/spacewalk/pull/18244
Fixes: https://github.com/SUSE/spacewalk/issues/18092
No difference.
Before:
After:
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documenta …
> Add channel availability check for product migration (bsc#1200296)

- testsuite/features/step_definitions/common_steps.rb
Using a step going to the client's profile instead of clicking on its link in a Cobbler feature.
Fixes # https://github.com/SUSE/spacewalk/issues/19184
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/19192
4.3 https://github.com/SUSE/spacewalk/pull/19193
> QE: Cobbler system record trigger step updating

- testsuite/features/secondary/buildhost_docker_auth_registry.feature
- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/features/step_definitions/docker_steps.rb
Separate the step waiting for an image to be successfully built and inspected in two different steps to reduce the number of failures and better identify the potential source of failure
Fixes #
> QE: Splitting image build check into two steps

- spacewalk/setup/bin/spacewalk-setup-cobbler
- spacewalk/setup/spacewalk-setup.changes
- spacewalk/setup/spacewalk-setup.spec
This PR fixes some issues detected in Uyuni 2022.10 around Cobbler, that makes Cobbler service to break causing different symthoms in the Uyuni server:
- https://github.com/uyuni-project/uyuni/issues/6037
- https://github.com/uyuni-project/uyuni/issues/6041
- https://github.com/uyuni-project/uyuni/issues/6045
These different issues were caused because the migrations of Cobbler settings and collections to newer Cobbler 3.3.3, triggered by `spacewalk-setup` package during the upgrade, didn't happen as it was expected. This makes the Cobbler service not able to start properly as it still has non-migrated settings and collections.
With the changes in this PR, the new update of `spacewalk-setup` will trigger the execution of the migration as expected, making the Cobbler service able to start …
> Uyuni 2022.10: Fix issues triggering Cobbler migrations

- python/spacewalk/satellite_tools/spacewalk-debug
- python/spacewalk/spacewalk-backend.changes
- susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes
- susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.spec
This PR adds a missing dependency to the Perl library XML Simple.
No difference.
- No tests: runtime environment issue, no code change
Fixes https://github.com/SUSE/spacewalk/issues/19178
> Added missing dependency for Perl XML Simple

- testsuite/run_sets/reposync.yml
Temporarily disable rocky8 reposync feature to observe other potential failures in further stages.
No difference.
- Cucumber tests were disabled
Tracks # No ports needed
> QE: Temporarily disabled srv_add_rocky8_repositories

- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
snakeyaml was updated to version 1.31. Use the new version in ivy as well.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/19119
> snakeyaml version update to 1.31

- susemanager-utils/susemanager-sls/salt/channels/channels.repo
- susemanager-utils/susemanager-sls/salt/channels/gpg-keys.sls
- susemanager-utils/susemanager-sls/salt/channels/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
When using `gpgkeys` parameter in the repository configuration, the installer import the key only when needed.
As the repositories are not signed, a refresh operation does not import the key. 
Only a package install/update operation would import this key, but we do not want to use "gpg-auto-import-gpg-keys" option in every state and teach also the users to set this option always.
So we better directly import the GPG keys which are set in **assigned** channels. 
As for yum/dnf you can configure "--assume-yes" to not say "yes" to key imports, it is better to directly import GPG keys also on Red Hat systems.
This makes the forced refresh operation in channels.sls obsolete.
Next issue found was, that `dnf` does not support multiline options. GPG keys must be comma or whitespace separated.
As …
> Change trust gpg keys

- java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java
- java/spacewalk-java.changes
- schema/spacewalk/common/data/rhnVirtualInstanceType.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.1-to-susemanager-schema-4.4.2/100-rhnVirtualInstanceType-Nitro.sql
Renames 'Amazon EC2/KVM' to 'Amazon EC2/Nitro' and improves the detection of this virtual instances with salt.
There are 2 PRs for salt required for it:
https://github.com/openSUSE/salt/pull/560
https://github.com/openSUSE/salt/pull/555
Upstream Salt have already merged these changes.
Just a name of the virtual instance type set for `Virtualization:` field.
Tracks https://github.com/SUSE/spacewalk/issues/19096 …
> Rename 'Amazon EC2/KVM' to 'Amazon EC2/Nitro' and improve the detection (bsc#1203685)

- web/html/src/components/datetime/DateTimePicker.stories.md
Minor internal debugging change for Storybook.
No difference.
> Add legacy datetime id to stories for testing

- java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
- java/spacewalk-java.changes
In some cases, channel-related pillar data changes depending on a CLM project's configuration. If the target channel is already assigned to some systems before the latest build, these changes never reflect to the actual pillar data unless channels are re-assigned manually.
This patch refreshes the pillar data for all the systems assigned to a CLM project's target channels whenever the project is rebuilt.
See: https://bugzilla.suse.com/show_bug.cgi?id=1200169
Case in hand: https://bugzilla.suse.com/show_bug.cgi?id=1200169#c17
Port of: https://github.com/SUSE/spacewalk/pull/19282
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni- …
> Refresh pillar data for the assigned systems when a CLM channel is built (bsc#1200169)

- java/code/src/com/redhat/rhn/common/security/acl/test/AccessTest.java
- java/code/src/com/redhat/rhn/domain/channel/Channel.hbm.xml
- java/code/src/com/redhat/rhn/domain/channel/Channel.java
- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/redhat/rhn/domain/channel/Modules.java
- java/code/src/com/redhat/rhn/domain/channel/RepoMetadata.hbm.xml
- java/code/src/com/redhat/rhn/domain/channel/RepoMetadata.java
- java/code/src/com/redhat/rhn/domain/channel/test/ChannelFactoryTest.java
- java/code/src/com/redhat/rhn/domain/channel/test/ChannelTest.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/modulemd/ModulemdApi.java
- java/code/src/com/redhat/rhn/frontend/action/common/DownloadFile.java
- java/code/src/com/redhat/rhn/manager/channel/CloneChannelCommand.java
- java/code/src/com/redhat/rhn/manager/channel/test/CloneChannelCommandTest.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/DependencyResolver.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerTest.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/DependencyResolverTest.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/MockModulemdApi.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/RpmRepositoryWriter.java
- java/code/src/com/suse/manager/webui/controllers/DownloadController.java
- java/code/src/com/suse/manager/webui/controllers/test/DownloadControllerTest.java
- java/spacewalk-java.changes
- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/spacewalk-backend.changes
- schema/spacewalk/common/tables/rhnChannelComps.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.1-to-susemanager-schema-4.4.2/200-rhnChannelComps-drop_unique_index.sql
- schema/spacewalk/upgrade/susemanager-schema-4.4.1-to-susemanager-schema-4.4.2/201-rhn_channel_cloned_comps_trig_fun.sql
Most CentOS flavors serve only the latest packages in their repositories. When a new release comes out, old packages are wiped out, new packages are served, and the modules.yaml file is replaced with a new one.
SUSE Manager on the other hand never removes synced packages. When a new release is synced, both the old and new packages are still available in channels. We read modules.yaml to look up the AppStream packages to filter out. Since the modules.yaml file is replaced with a new one and it does not contain any information about the older packages, those older packages leak into target repositories.
In SUSE Manager, we already keep the older modules.yaml files in the file system. This PR changes the behavior to also keep them in the database, and use them when retrieving the list of …
> Fix filtering of modular packages on CentOS flavors (bsc#1201893)

- java/manager-build.xml
The `test-pr` target is what makes the pipeline fail... make it depend on `test-coverage-report` and use it in the jenkins pipeline
No difference.
Fixes # …
> Call test-coverage-report in ant test-pr target

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.0-to-susemanager-schema-4.4.1/300-rhnVirtualInstanceType.sql
The previous schema upgrade introducing `aws_kvm` which was renamed to `aws_nitro` after is causing issues on schema upgrade. This PR is making condition for the previous schema upgrade script covering this case.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/19096 …
> Fix issues on upgrading Amazon EC2 related schema

- java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/salt/cleanup_ssh_minion/init.sls
- susemanager-utils/susemanager-sls/salt/ssh_bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
There is a wrong assumption used in the bootstrap and cleanup state for salt ssh client:
`/home/USERNAME/` home directory with `USERNAME` matching exact actual user name.
But this assumption is not true as the home directory could have any destination.
It has also additional check for cleanup for salt ssh client. In case of using sudo user it could lead to errors with no text in the web UI due to not passing `mgr_sudo_user` on calling `cleanup_ssh_minion` state apply. Works fine with `root` user only.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/18529 …
> Fix salt ssh wrong sudoer home directory on bootsrapping/cleanup

- testsuite/features/reposync/srv_add_rocky8_repositories.feature
- testsuite/features/reposync/srv_sync_channels.feature
- testsuite/features/secondary/min_rhlike_remote_command.feature
- testsuite/features/secondary/min_rhlike_ssh.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/constants.rb
- testsuite/run_sets/reposync.yml
- utils/spacewalk-common-channels.ini
This will add a sync of Rocky 8 via the command line and fixes some of the issues currently present in the CI.
PR test run: https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/1839
No difference.
fixes https://github.com/SUSE/spacewalk/issues/19322
no ports needed. …
> QE: Add sync of custom channels for Rocky 8

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/salt/channels/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Set GpgKeyUrl for PTF repositories to the locally installed PTF key.
Enforce suse-build-key package been installed which contains the PTF key.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18912 …
> Project Lotus: handle GPG keys for PTF repositories

- java/code/webapp/WEB-INF/pages/common/fragments/systems/system_listdisplay.jspf
- java/spacewalk-java.changes
In some system lists (e.g. system group page), the selected systems are not added to SSM, but rather a different action is executed. This PR removes the text "SSM" from the selection column to prevent confusion.
See: https://bugzilla.suse.com/show_bug.cgi?id=1203588
Before:
After:
- No tests: minor UI element
Fixes https://github.com/SUSE/spacewalk/issues/19081
If …
> Remove 'SSM' column text where not applicable (bsc#1203588)

- java/code/src/com/redhat/rhn/frontend/action/ssm/MigrateSystemsAction.java
- java/spacewalk-java.changes
Add a no-arg constructor to `MigrateSystemsAction` so that struts can instantiate it.
Port of: https://github.com/SUSE/spacewalk/pull/19382
> Add no-arg constructor to MigrateSystemsAction (bsc#1204651)

- java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
- java/code/src/com/redhat/rhn/frontend/servlets/SystemDetailsMessageFilter.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/spacewalk-java.changes
- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/misc.py
- spacecmd/tests/test_misc.py
It adds a warning message in UI for traditional stack deprecation. To do so, the webfilter previously used to show a reboot needed message was refactored to be a generic message filter for system details.
No difference.
- No documentation needed: just a warning message.
Port of https://github.com/SUSE/spacewalk/pull/18724 …
> Display a warning message in UI for traditional stack deprecation

- containers/proxy-httpd-image/proxy-httpd-image.changes
- containers/proxy-httpd-image/uyuni-configure.py
- containers/proxy-squid-image/Dockerfile
- containers/proxy-squid-image/proxy-squid-image.changes
- containers/proxy-squid-image/squid.conf
Fix the squid container to work with the latest squid update changing the path to the pid file.
Also fix the error changing permissions on `/srv/www/htdocs/pub` folder in `httpd` container since it doesn't exist there.
No difference.
- No tests: automation still to be worked on
Fixes https://github.com/SUSE/spacewalk/issues/19379
If …
> Squid pid fix

- java/code/src/com/redhat/rhn/domain/reactor/SaltEvent.hbm.xml
- java/code/src/com/suse/manager/reactor/PGEventStream.java
- java/spacewalk-java.changes
This PR fixes the following problems with salt event queue:
1. Event ordering 
Events were ordered by minion ID. As a result, certain minions had low prority and their events were processed with extreme delays on loaded server.
This behavior was introduced by commit 6c7981570024 but it is no longer needed because 63c9aff6a9ef implements better fix.
This PR reverts the behavior to standard FIFO.
2. Detecting stalled events in `startConnectionWatchdog`
The methods `executor.getTaskCount()` and `executor.getCompletedTaskCount()` are unreliable - according documentation they return "approximate total number of tasks".  Customer's log shows that this is a real problem, it contains messages mentioning negative number of events: `Found [0, 0, 0, 0, 2, 0, -1, 0, 0] events without a job. …
> Fix salt event queue (bsc#1203532)

- susemanager-utils/susemanager-sls/src/modules/kiwi_info.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Fix kiwi inspect regexp to allow image names with "-"
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19332 …
> Fix kiwi inspect regexp to allow image names with "-"

- java/code/src/com/redhat/rhn/manager/formula/test/FormulaManagerTest.java
- java/code/src/com/redhat/rhn/testing/ServerGroupTestUtils.java
- java/spacewalk-java.changes
Forward port of https://github.com/SUSE/spacewalk/pull/18448
Check if system has all formulas correctly assigned
When system has group formula assigned and user then edits this formula, we
need to assign edited formula as system formula as well for proper cleanup and
tracking.
Remove group formula assignments and data on group delete
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18421 and https://github.com/SUSE/spacewalk/issues/18422
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni …
> Form clear after delete

- java/code/src/log4j2.xml
- java/conf/log4j2.xml.taskomatic
Should fix #5883. Log4J2 should no more try to write the rotated logfile into CATALINA_HOME
No difference.
- No tests: no functional change
Fixes #5883
> Make RollingFile filePattern an absolute path

- testsuite/features/step_definitions/navigation_steps.rb
Temporarily disable checking on the welcome message to work around current failure in core: https://github.com/SUSE/spacewalk/issues/19369
No difference.
Fixes #
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/19428 …
> Temporarily disable checking on the welcome message

- testsuite/features/step_definitions/common_steps.rb
Use https instead of http when fetching a maintenance calendar via url
Related: https://github.com/SUSE/spacewalk/issues/19383
No difference.
- No documentation needed: **fix test**
Fix ci test
Fixes https://github.com/SUSE/spacewalk/issues/19429
> Fix maintenance calendar creation test via url

- spacewalk/setup/spacewalk-setup.changes
- spacewalk/setup/spacewalk-setup.spec
We have detected that in some cases, the Cobbler collections are containing old Cobbler 2 attributes, as it seems those collections from Cobbler 2 were never migrated to Cobbler 3.
This PR makes `spacewalk-setup` to trigger migration of Cobbler v2 collections to v3, as part of the Cobbler migration to 3.3.3.
Additionally, it makes also servers that were already migrated to 3.3.3 to trigger, at least once, the migration from of Cobbler collections from v2 to v3.
**NOTE: This PR requires changes on Cobbler package that is not yet pushed to Uyuni - still WIP at https://build.opensuse.org/package/show/home:PSuarezHernandez:branches:systemsmanagement:Uyuni:Master/cobbler**
No difference.
- No tests: **manually tested**
Tracks: …
> Uyuni-2022.10: Execute migration of Cobbler version 2 collections at least once (bsc#1203478)

- java/code/src/com/redhat/rhn/taskomatic/task/RhnJavaJob.java
- java/code/src/com/redhat/rhn/taskomatic/task/RhnQueueJob.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/RhnJavaJobTest.java
- java/spacewalk-java.changes
Fix number of file handles for deleted files is growing continuously in SUMA 4.3.1
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19196
> Fix number of file handles for deleted files is growing continuously in SUMA 4.3.1

- java/code/webapp/WEB-INF/pages/common/fragments/user/preferences.jspf
- web/html/src/branding/css/base/checkbox.less
- web/html/src/branding/css/susemanager/susemanager-theme.less
- web/html/src/branding/css/uyuni.less
- web/spacewalk-web.changes
My preferences page was missing a wrapper element on some settings.  
Before:
After:
- No documentation needed: UI bugfix.
- No tests: UI bugfix.
> Add missing label wrappers

- testsuite/features/support/env.rb
```
export PXEBOOT_IMAGE="sles15sp4o" 
export PROVIDER="libvirt"
export IS_USING_BUILD_IMAGE="False" 
export IS_USING_SCC_REPOSITORIES="False"
```
This is how bashrc looks like. We need to convert the "string" `False` into a boolean.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19436
If …
> bash variable is set to string "False" convert it to boolean

- java/code/src/com/redhat/rhn/domain/reactor/SaltEvent.hbm.xml
- java/code/src/com/redhat/rhn/domain/reactor/SaltEventFactory.java
- java/code/src/com/redhat/rhn/domain/reactor/test/SaltEventFactoryTest.java
- java/code/src/com/suse/manager/reactor/PGEventStream.java
- java/spacewalk-java.changes
After a change of java.salt_event_thread_pool_size, the queue number for pending events must be re-calculated.
Without this PR, changing of  java.salt_event_thread_pool_size with non-empty event queue can lead to events processed in incorrect order or stalled.
Typically, java.salt_event_thread_pool_size must be changed when there is some problem with processing of the events so the queue is not empty at this point.
No difference.
- Unit test added
Part of fix for https://github.com/SUSE/spacewalk/issues/19063
https://bugzilla.suse.com/show_bug.cgi?id=1203532 …
> Re-calculate salt event queue numbers on restart

- java/code/src/com/redhat/rhn/domain/action/ActionChain.hbm.xml
- java/code/src/com/redhat/rhn/domain/action/ActionChainFactory.java
- java/code/src/com/redhat/rhn/domain/action/test/ActionChainFactoryTest.java
- java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
- java/spacewalk-java.changes
This optimizes action chain processing on JobReturn event.
ActionChain::isDone is quite expensive. Before, it was called on all action chains.
(in the log from bsc#1203532 there is 4000 action chains and 26000 action chain entries)
This PR uses SQL query to find the related action chains for given minion.
No difference.
Partially fixes
https://github.com/SUSE/spacewalk/issues/19063
https://bugzilla.suse.com/show_bug.cgi?id=1203532
Related to https://github.com/uyuni-project/uyuni/pull/4539
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyun …
> Optimize action chain processing on job return event (bsc#1203532)

- java/code/src/com/redhat/rhn/taskomatic/core/TaskomaticDaemon.java
- java/spacewalk-java.changes
It improves taskomatic error logging by adding the stacktrace to the logs when taskomatic fails to start.
No difference.
> Add stack trace to the logs when taskomatic fails to start

- java/code/src/com/redhat/rhn/common/messaging/ActionExecutor.java
- java/code/src/com/redhat/rhn/common/messaging/SmtpMail.java
- java/code/src/com/redhat/rhn/common/util/MethodUtil.java
- java/code/src/com/redhat/rhn/domain/channel/AccessTokenFactory.java
- java/code/src/com/redhat/rhn/frontend/action/common/DownloadFile.java
- java/code/src/com/redhat/rhn/frontend/action/configuration/BaseAddFilesAction.java
- java/code/src/com/redhat/rhn/frontend/action/user/ResetPasswordSubmitAction.java
- java/code/src/com/redhat/rhn/frontend/dto/SystemSearchResult.java
- java/code/src/com/redhat/rhn/frontend/taglibs/ToolbarTag.java
- java/code/src/com/redhat/rhn/frontend/taglibs/helpers/ListViewHelper.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/XmlRpcServlet.java
- java/code/src/com/redhat/rhn/manager/audit/scap/file/ScapResultFile.java
- java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java
- java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcInvoker.java
- java/code/src/com/redhat/rhn/taskomatic/core/SchedulerKernel.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/ChannelRepodataWorker.java
Remove `printStackTrace()` calls in the `java` folder for non-tests. This never shows up and `Logger` should be used instead. This will also address some SonarCloud low security hotspots.
No difference.
- No tests: Logging
Fixes # …
> Don't call printStackTrace in production code, use logger instead

- testsuite/features/reposync/srv_add_rocky8_repositories.feature
- testsuite/features/secondary/srv_content_lifecycle.feature
The CLM tests expect that the project is empty. As the Rocky Linux tests added a first project now in "core", this is not true anymore.
This PR move the "empty project" test into the Rocky tests in core.
No difference. …
> move empty CLM Project test to first feature creating a project

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
- add bootstrap repo data for SUSE Liberty Linux 9
- add bootstrap repo data for Oracle, Alma and Rock Linux 9
- define Uyuni Client Tools Channel for RHEL9/SLL9 
No difference.
- No documentation needed here: **extra issue is open**
Fixes https://github.com/SUSE/spacewalk/issues/19157
Fixes https://github.com/SUSE/spacewalk/issues/18468
Tracks https://github.com/SUSE/spacewalk/pull/19408 …
> Enterprise Linux 9 enabelment

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
Ubuntu 18.04 needs python3-contextvars and python3-immutables because it runs Python3.6 and Salt 3004 requires these dependencies. We couldn't add them to the .deb as hard dependencies because we only maintain one build instruction for all .deb packages, no matter which OS the package is built for.
No difference.
- No tests: This only makes sense as end-to-end tests, out of scope for the bug fix PR.
Spacewalk Issue https://github.com/SUSE/spacewalk/issues/19301
Tracks #  …
> Install needed deps on Ubuntu 18.04 (bsc#1204517)

- susemanager-sync-data/additional_products.json
- susemanager-sync-data/susemanager-sync-data.changes
updates uyuni sync data with almalinux9, rockylinux9, oraclelinux9 and sll9. Also sets oes2023 products to released.
No difference.
- No tests
> update uyuni sync data

- susemanager/src/mgr_bootstrap_data.py
Fix a syntax error in the bootstrap data 
No difference.
Additional fix for https://github.com/uyuni-project/uyuni/pull/6092
Not needed for 4.3. This error does not exist there
> fix syntax in bootstrap repo data

- java/code/src/com/redhat/rhn/domain/config/ConfigChannel.java
- java/code/src/com/redhat/rhn/domain/config/ConfigChannelListProcessor.java
- java/code/src/com/redhat/rhn/domain/server/MinionServer.java
- java/code/src/com/redhat/rhn/domain/server/Server.java
- java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
- java/code/src/com/redhat/rhn/domain/server/test/ServerTest.java
- java/code/src/com/redhat/rhn/frontend/action/configuration/ssm/SubscribeConfirm.java
- java/code/src/com/redhat/rhn/frontend/action/configuration/ssm/UnsubscribeConfirmAction.java
- java/code/src/com/redhat/rhn/frontend/action/configuration/ssm/UnsubscribeConfirmSubmitAction.java
- java/code/src/com/redhat/rhn/frontend/action/configuration/ssm/test/SubscribeConfirmTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/XmlRpcSystemHelper.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/config/ServerConfigHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/config/test/ServerConfigHandlerTest.java
- java/spacewalk-java.changes
- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/system.py
When calling `spacecmd -d -- system_addconfigchannels` with a channel that is already present on a system we have a failure with this error in the log:
```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "suse_state_rev_id_cfgchn_id_uq"
Detail: Key (state_revision_id, config_channel_id)=(18, 1) already exists.
```
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19187 …
> ServerConfigHandler: don't add the same channel twice

- testsuite/features/reposync/srv_sync_channels.feature
`SUSE Manager Client Tools for RHEL and ES 7 x86_64` was renamed to
`SUSE Manager Client Tools for RHEL, Liberty and Clones 7 x86_64`
> fix client tools product name after rename

- java/code/src/com/redhat/rhn/domain/server/MinionServer.java
- java/code/src/com/redhat/rhn/domain/server/MinionSummary.java
- java/code/src/com/redhat/rhn/domain/server/Server.java
- java/code/src/com/suse/manager/webui/services/SaltActionChainGeneratorService.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/manager/webui/services/test/SaltActionChainGeneratorServiceTest.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/src/modules/mgractionchains.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- testsuite/features/reposync/srv_add_rocky8_repositories.feature
Currently the reboot of a transactional update minions does not work inside in a action chains. This is because all the actions are converted in a sls file, and this file is executed as a single transaction: since reboot is not allowed inside a transaction, the action chains stop to work.
In order to have the reboot action working:
-  more than one sls file are created, each one of them contains all the action until a reboot (if present in the action chain)
- the reboot action is not converted in an sls file, but it managed directly by `mgractionchains.py` (using the argument `activate_transaction=true`)
**KNOWN ISSUE:**
- If action does not generate any new snapshot, the reboot action would not work (since there's no reboot action but an `activate_transaction=true` ) . A possible …
> Action Chain: reboot on transactional update minions

- python/spacewalk/spacewalk-backend.changes
- python/spacewalk/spacewalk-backend.spec
Only new version of python3-debian support compression algorithms which are required by some Ubuntu 22.04 packages.
We released this already, but as optional update. This PR enforce installing the new version on Uyuni.
No difference.
- No tests: **only dependency change**
Port of https://github.com/SUSE/spacewalk/pull/19475
If you …
> require python3-debian which support compressions used by ubuntu 22.04

- testsuite/features/secondary/srv_dist_channel_mapping.feature
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/run_sets/secondary_parallelizable.yml
Add automated tests for the Distribution Channel Mapping page
No difference.
Partially Fixes https://github.com/SUSE/spacewalk/issues/10287
Manager-4.2
Manager-4.3
> QE: Add tests for distribution channel mapping

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/system.py
It changes `spacecmd` to use the correct API method when scheduling product migrations. Instead of using `scheduleProductMigration`, it was using `scheduleSPMigration` that is a deprecated method.
This PR also adds `--allow-vendor-change` and `--remove-products-without-successor` parameters to schedule product migration in `spacecmd`.
No difference.
- Documentation issue was created: [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/1859).
Fixes https://github.com/SUSE/spacewalk/issues/19208
If you don't …
> Improves schedule product migration in spacecmd

- java/code/src/com/redhat/rhn/domain/server/MinionServer.java
- java/code/src/com/redhat/rhn/domain/server/Server_legacyUser.hbm.xml
- java/code/src/com/redhat/rhn/frontend/servlets/SystemDetailsMessageFilter.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/suse/manager/reactor/SaltReactor.java
- java/code/src/com/suse/manager/reactor/test/RebootInfoBeaconTest.java
- java/code/src/com/suse/manager/webui/services/pillar/MinionGeneralPillarGenerator.java
- java/spacewalk-java.changes
- schema/spacewalk/common/tables/suseMinionInfo.sql
- schema/spacewalk/upgrade/susemanager-schema-4.4.1-to-susemanager-schema-4.4.2/300-add-reboot-need-column-to-suseMinionInfo.sql
- schema/spacewalk/upgrade/susemanager-schema-4.4.1-to-susemanager-schema-4.4.2/301-replace-update-system-overview.sql
- susemanager-utils/susemanager-sls/src/beacons/reboot_info.py
- susemanager-utils/susemanager-sls/src/tests/test_beacon_reboot_info.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
It adds a new execution module for SLE Micro systems which returns a boolean indicating if a reboot is needed, and uses the return of this module to show the warning message about necessary reboot only when it returns true.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/19036
If you need to …
> Improved reboot needed handling for SLE Micro

- susemanager-utils/testing/automation/wait-for-syncs.sh
Make the wait-for-sync script to return an exit code if the sync was not successful
No difference.
- No documentation needed: this is for the CI
- No tests: this is for the CI
Fixes https://github.com/SUSE/spacewalk/issues/19246
> CI: check if the sync was successful

- susemanager-utils/testing/automation/wait-for-builds.sh
fixes the wait-for-build script used in the CI
No difference.
- No tests
> CI: fix wait-for-build

- testsuite/features/step_definitions/navigation_steps.rb
Correct Rubocop warning coming from a temporary fix
No difference.
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/19480
> Correct RuboCop error from navigation steps

- testsuite/features/core/srv_create_repository.feature
prevent race conditions that other channels are still synced while we expect source packages been synced for Test-Channel-x86_64
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/19521 https://github.com/SUSE/spacewalk/pull/19522 …
> Enable source package syncing for the whole feature

- susemanager-utils/testing/automation/wait-for-syncs.sh
Wait for sync should wait for the last sync to finish and then trigger a new sync. Otherwise, the job could start in the middle of a previous sync and we would not know, making the packages not being updated.
No difference.
Before:
After:
- API documentation added: please review the Wiki page [Writing Documentation for the …
> CI: fix wait-for-sync

- java/code/src/com/redhat/rhn/domain/formula/FormulaFactory.java
- java/spacewalk-java.changes
Formulas selected on a server or group without having any configuration defined had no pillar data file on the file system on 4.2 and those were not converted into the DB pillars.
This PR now handles this case too.
No difference.
- No tests: Migration tests using files is painful to unit test
Fixes https://github.com/SUSE/spacewalk/issues/19374 …
> Pillar migration fix

- spacewalk/setup/spacewalk-setup.changes
- spacewalk/setup/spacewalk-setup.spec
This PR, together with [1], should make `spacewalk-setup` to fix the possible wrong `autoinstall` attribute from Cobbler collections caused by the failing v2-to-v3 collection migration that was executed.
In case `spacewalk-setup` notices the v2-to-v3 migration was executed, then it will trigger a new command to fix the possible inconsistencies for "autoinstall" in the stored collections:
```
```
This command will only take care of migrating and fixing the `autoinstall` attribute from the stored collections. In cases where automatic migration of "autoinstall" is not possible, the script will warn the user to manually fix it.user 
[1] https://build.opensuse.org/request/show/1035233
No difference.
- No tests: **tested …
> Uyuni-2022.10: Trigger fix of posible wrong "autoinstall" value from Cobbler collections (bsc#1203478)

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes
- python/test/unit/spacewalk/satellite_tools/test_yum_src.py
This commit fixes bsc#1203826. Previously, reposync would treat broken urls in the list of mirrors as valid, causing it to fail. The first commit checks whether urls contain any forbidden characters, and if they do, it discards them. The second commit checks that any page used as a candidate for a mirrorlist is a plaintext or xml page.
No difference.
Fixes #
> Exclude invalid mirror urls for reposync

- testsuite/features/support/constants.rb
This PR fixes the constants for openSUSE 15.4 minion
Ports:
* 4.2: SUSE/spacewalk#19547
* 4.3: SUSE/spacewalk#19546
> Bump openSUSE to 15.4

- java/code/src/com/redhat/rhn/domain/action/ActionFactory.java
- java/code/src/com/redhat/rhn/domain/action/Action_legacyUser.hbm.xml
- java/code/src/com/redhat/rhn/domain/action/test/ActionFactoryTest.java
- java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java
- java/code/src/com/redhat/rhn/domain/server/MinionSummary.java
- java/code/src/com/redhat/rhn/domain/server/test/MinionServerFactoryTest.java
- java/code/src/com/redhat/rhn/manager/action/MinionActionManager.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/manager/webui/services/test/SaltServerActionServiceTest.java
- java/spacewalk-java.changes
This PR make sure that an action is executed only on minions having a pending entry in the `ServerAction` table. Currently, if the user tries to reschedule the action on all the failed servers (through the web ui or the api), the taskomatic job actually executes the action on all of them. This is because the target minions were extracted without checking their action status.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19445
Tracks https://github.com/SUSE/spacewalk/pull/19529 https://github.com/SUSE/spacewalk/pull/19528 …
> Do not execute actions on minion that are not in pending status

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes
```
2022/11/15 06:58:02 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'test-channel-i586', '--type', 'yum', '--non-interactive']
2022/11/15 06:58:02 +02:00 Sync of channel started.
ERROR: Failed to reach repo url: file:///srv/www/htdocs/pub/TestRepoRpmUpdates/ - No connection adapters were found for 'file:///srv/www/htdocs/pub/TestRepoRpmUpdates/'
```
The reason for this error is the GET request for a mirror list:
```
> /usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py(536)_get_mirror_list()
-> webpage = requests.get(url, proxies=proxies, cert=cert, verify=verify)
(Pdb) url
'file:///srv/www/htdocs/pub/TestRepoRpmUpdates/'
(Pdb) proxies
{}
(Pdb) n
requests.exceptions.InvalidSchema: No connection adapters were found for …
```
> do not try to get a mirror list when file url is used

- susemanager-utils/susemanager-sls/src/states/product.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Add `--no-recommends` option when installing missing products via the `product` state.
See: https://bugzilla.suse.com/show_bug.cgi?id=1204330
Port of: https://github.com/SUSE/spacewalk/pull/19548
> Install new products with 'no-recommends' option (bsc#1204330)

- java/spacewalk-java.changes
- java/spacewalk-java.spec
/srv/susemanager/salt/salt_ssh/temp_bootstrap_keys directory can be 0700 instead of 0755. In this directory SUMA will store ssh private key files and it will create them with 0700 permission, so the directory itself can have the same.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/17695
Rebase of https://github.com/uyuni-project/uyuni/pull/4903
Tracks https://github.com/SUSE/spacewalk/pull/19556 https://github.com/SUSE/spacewalk/pull/19557
If you don't need …
> Hardening suggestion: permissions for

- java/code/src/com/redhat/rhn/manager/rhnpackage/PackageManager.java
If the path is null how could the file not be null given it's computed from the path?
> Remove useless code in PackageManager

- java/buildconf/ivy/ivy-suse.xml
- java/spacewalk-java.changes
Sync `jackson-databind` version in ivy config with the package version.
No difference.
Fixes #
> Fix jackson-databind version in ivy config

- python/rhn/SSL.py
- python/rhn/rhnlib.changes
Ensure that `readline()` stops when no data was received.
Apparently an SSL_ERROR_ZERO_RETURN is not always raised when there is no data. We saw this happening on a SLE12 SP5 client running Python 2.7.
Co-authored-by:  Victor Zhestkov <vzhestkov@gmail.com>
No difference.
- No tests: The behavior is hard to reproduce, we only saw it for a traditional SLE12 SP5 client. There are no existing tests that could extended without a lot of effort.
Internal tracker: https://github.com/SUSE/spacewalk/issues/19188 …
> Handle ZERO RETURN better in rhn/SSL (bsc#1204032)

- testsuite/features/step_definitions/common_steps.rb
A local mount conflicts with an nfs mount when the server is being rebooted and causes the server to fail to properly configure its network.
This PR applies the solution mentioned in https://www.suse.com/support/kb/doc/?id=000018796 to solve this issue.
No difference.
Tracks # No ports needed (only Uyuni) …
> Adding an option in /etc/fstab to resolve mounting conflicts

- java/code/src/com/redhat/rhn/frontend/servlets/SystemDetailsMessageFilter.java
- java/code/src/com/redhat/rhn/frontend/servlets/test/SystemDetailsMessageFilterTest.java
- java/spacewalk-java.changes
It fixes the traditional stack deprecation warning message to be shown considering the entitlements of the system. It was only checking if the system was a salt minion, but there are some systems that are neither salt minions nor traditional ones, like containerized proxies.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19551 …
> Fixed traditional stack warning message to be displayed only when the system has enterprise entitlement

- testsuite/features/secondary/srv_content_lifecycle.feature
Rocky 8 testing introduced a new CLM project for filter the appstream contents of the DVD. Since we cannot be 100% sure after which tested feature the filtered project can be deleted, this PR simply adjusts the general CLM test scenario.
No difference.
No ports needed, Rocky 8 testing ins only done in HEAD/Uyuni. …
> QE: Fix checking for empty CLM in CLM test

- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/spacewalk-backend.changes
When synchronizing a repository with the --sync-kickstart option on a RHEL8 or clone BaseOS channel the treeinfo file is just copied to the installation tree.
However the AppStream variant path is relative to this file and may not even exist if the user hasn't synchronized the AppStream repo.
To address this issuem it has been agreed with the reporter and user that AppStream variant should be removed from the generated treeinfo. To install AppStream packages in a kickstart the user then has to manually add the repo to the anaconda configuration file.
No difference.
- No tests: kickstart is not tested at all yet
Fixes https://github.com/uyuni-project/uyuni/issues/5677 …
> Remove AppStream variant from treeinfo files

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
- java/spacewalk-java.changes
Disables the automatic channel selection for cloned vendor channels by default for now until better default behavior has been implemented. The selection can be reenabled with a config setting.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/19248 …
> make automatic channel selection for cloned channels configurable

- schema/spacewalk/common/tables/suseRecurringAction.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.2-to-susemanager-schema-4.4.3/001-varchar-length-suseRecurringAction.sql
Increase `cron_expr` varchar length to 120 to match the length of `cron_expr` in rhnTaskoSchedule table.
No difference.
- No documentation needed: **Bug**
- No tests: **Bug**
Tracks https://github.com/SUSE/spacewalk/issues/19461
> Increase cron_expr varchar length in suseRecurringAction table

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
Change some instances where autoYaST was spelled incorectly
Autoyast -> AutoYaST
Just some spelling
- No documentation needed: **Typo fix**
- No tests: **Typo fix**
Tracks https://github.com/SUSE/spacewalk/issues/19585
> Fix AutoYaST spelling

- testsuite/features/secondary/srv_task_status_engine.feature
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/run_sets/secondary_parallelizable.yml
Add automated test for Task Engine Status Page
No difference.
Partially Fixes [#10287](https://github.com/SUSE/spacewalk/issues/10287)
Master 4.2 https://github.com/SUSE/spacewalk/pull/19630
Master 4.3 https://github.com/SUSE/spacewalk/pull/19628
> QE: Add automated test for Task Engine Status

- testsuite/features/build_validation/add_custom_repositories/add_rocky9_repositories.feature
- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/constants.rb
- testsuite/run_sets/build_validation_add_common_channels.yml
Temporary cleanup before we have usable SCC products for EL 9 tools / Rocky 9 / SUSE Liberty Linux 9 (even as beta) and know how to use them.
Note: on uyuni branch we might already have them, so I might come with a second PR on top of this one. But at least it will be on top of "clean" code.
* 4.2: no rocky 9 support
* 4.3: SUSE/spacewalk#19639
> Disable the EL 9 products for now

- testsuite/features/secondary/srv_cobbler_sync.feature
- testsuite/run_sets/secondary_parallelizable.yml
Add test to run cobbler sync via `Admin > Manager Configuration > Cobbler`.
No difference.
Fixes [#18806](https://github.com/SUSE/spacewalk/issues/18806)
Manager-4.3: https://github.com/SUSE/spacewalk/pull/19642
Manager-4.2: https://github.com/SUSE/spacewalk/pull/19643
> QE: Add test to run cobbler sync via WebUI

- testsuite/features/secondary/srv_task_status_engine.feature
The sanity checks in `srv_task_status_engine.feature` need to be split with tags to distinguish between suma and uyuni
No difference.
Fixes #https://github.com/SUSE/spacewalk/issues/10287
Manager-4.3: https://github.com/SUSE/spacewalk/pull/19649
Manager-4.2:
> QE: Split sanity checks to distinguish between products

- testsuite/features/step_definitions/command_steps.rb
Moves the waiting instruction for apt-get to finish after checking the package has been installed 
No difference.
Fixes #
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/19663
4.3 https://github.com/SUSE/spacewalk/pull/19662 …
> Waiting for apt-get to finish after checking install

- java/code/src/com/redhat/rhn/taskomatic/task/repomd/DebPackageWriter.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/test/DebPackageWriterTest.java
- java/spacewalk-java.changes
There are some invalid debian package descriptions out there. They do not provide correct metadata and this cause Uyuni to fail with a NPE.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19202
Fixes https://github.com/uyuni-project/uyuni/issues/6002
Tracks https://github.com/SUSE/spacewalk/pull/19657 https://github.com/SUSE/spacewalk/pull/19659 …
> check for null for install size

- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR adds a missing bsc to a changelog entry that was already included by https://github.com/uyuni-project/uyuni/pull/5949. 
This bsc reference was not added at the time the mentioned PR was created as it was not existing. We got an L3 and provided the PR as PTF while this was been released. That is why we are adjunsting this now for consistency and also in order to prevent issues with Maintenance.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/19496
If …
> Add missing bsc reference to "susemanager-sls" changelog

- java/code/src/com/redhat/rhn/domain/errata/test/ErrataFactoryTest.java
Fix `RendererHelperTest` Java unit test flakiness
No difference
Fixes #
> Don't use random strings in tests where we have unique constraints

- java/code/src/com/suse/manager/api/LoggingInvocationProcessor.java
- java/code/src/com/suse/manager/reactor/messaging/test/SaltTestUtils.java
- java/code/src/com/suse/manager/webui/services/impl/SaltService.java
- java/code/src/com/suse/manager/webui/services/impl/test/SaltServiceTest.java
- java/code/src/com/suse/manager/webui/services/impl/test/service/ssh_cert_check.json
- java/spacewalk-java.changes
Fix contents of certificates show up on `web_ui` logs
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19395
> Fix contents of certificates show up on web UI logs

- .github/workflows/susemanager-sls-unit-tests.yml
- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
- susemanager-utils/susemanager-sls/salt/channels/disablelocalrepos.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
We have currently 2 ways to change behavior of disabling local repositories.
This PR drop the old one using a grain. We now prefer to set the pillar data on the server.
The new behavior is documented, the old is not.
See also https://github.com/SUSE/spacewalk/issues/19293
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/1902 …
> drop legacy way to prevent disabling local repos

- reporting/spacewalk-report
- reporting/spacewalk-reports.changes
Fix missing param using spacewalk-report
No difference. …
> spacewalk-report: fix missing param

- java/code/src/com/suse/manager/webui/controllers/SystemsController.java
- java/code/src/com/suse/manager/webui/templates/systems/all-list.jade
- java/code/src/com/suse/manager/webui/templates/systems/virtual-list.jade
- java/spacewalk-java.changes
Take user preferences into account in page size of (virtual) systems lists.
No difference.
- No tests: Do we really want integration tests for such a tiny change?
Fixes https://github.com/uyuni-project/uyuni/issues/6188 …
> Honor user page size preference in new system list pages

- java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
- java/code/src/com/redhat/rhn/manager/channel/EusReleaseComparator.java
- java/code/src/com/redhat/rhn/manager/channel/test/ChannelManagerTest.java
Remove more old RHEL-related code
No difference.
Fixes #
> Remove RHEL < 6 code in ChannelManager

- utils/spacewalk-hostname-rename
- utils/spacewalk-utils.changes
`spacewalk-hostname-rename` should also changes `report_db_host`. Since the parameter can be changed by the user (default is uyuni server), spacewalk-hostname-rename can work interactively or using the parameter `--overwrite_report_db_host=[y/n]`
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18224 …
> spacewalk-hostname-rename changes report_db_host (bsc#1200801)

- java/buildconf/test/rhn.conf.postgresql-example
- java/code/src/com/redhat/rhn/taskomatic/task/ChannelRepodata.java
- java/code/src/com/redhat/rhn/taskomatic/task/ErrataCacheTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/ErrataQueue.java
- java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateWorker.java
- java/code/src/com/redhat/rhn/taskomatic/task/ReportDBHelper.java
- java/code/src/com/redhat/rhn/taskomatic/task/ReportDbUpdateTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/RhnQueueJob.java
- java/code/src/com/redhat/rhn/taskomatic/task/SSHPush.java
- java/code/src/com/redhat/rhn/taskomatic/task/errata/ErrataCacheDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/errata/ErrataQueueDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/ChannelRepodataDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/ChannelRepodataWorker.java
- java/code/src/com/redhat/rhn/taskomatic/task/sshpush/SSHPushDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/ReportDbUpdateTaskTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/threaded/TaskQueueFactory.java
- java/spacewalk-java.changes
- susemanager-utils/testing/docker/scripts/build-reportdb-schema.sh
- susemanager-utils/testing/docker/scripts/reset_pgsql_database.sh
This PR ignores conflicts that may happen during the insert of the data into the reporting database. These conflicts can only occur if the data from the source tables changes. This modification may change how the extracted data is sorted and paginated, and thus causing the same row to be inserted twice. By ignoring the insert conflict, we prevent an hard failure during the synchronization process, at the cost of losing the newest data, which will be picked up by the following run of the sync task.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/18552
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs …
> Avoid concurrency issues during reporting database synchronization

- testsuite/.rubocop_todo.yml
- testsuite/config/cucumber.yml
- testsuite/features/build_validation/containerization/proxy_as_pod_basic_tests.feature
- testsuite/features/core/proxy_register_as_pod.feature
- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
- testsuite/features/step_definitions/api_common.rb
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/twopence_init.rb
- testsuite/features/support/xmlrpc_client.rb
- testsuite/run_sets/build_validation_containerization.yml
- testsuite/run_sets/container_proxy.yml
- testsuite/run_sets/min_proxy.yml
- testsuite/run_sets/secondary.yml
**Card:** https://github.com/SUSE/spacewalk/issues/17133
Related PR: https://github.com/SUSE/susemanager-ci/pull/516
It's prepared to run as _first phase_ agreement **(running the containerized proxy test as a feature in the secondary stage)**, but the feature to use it as _second phase_ agreement is also implemented (replacing the traditional proxy by the pod proxy in the core stage). This means that we keep the feature `testsuite/features/core/proxy_register_as_pod.feature` unused and not added to any YAML file.
In addition:
- I refactored the init of the API Handler in order to always use HTTP when we are in debug mode (so in our IDEs to developer our tests) that way we will not need workarounds in our local environments.
- I also fixed spelling in the Gherkin keywords used in some …
> Containerized proxy tests

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/webapp/WEB-INF/pages/systems/details/packages/packagelist.jsp
- java/code/webapp/WEB-INF/pages/systems/details/packages/packagelist.jspf
- java/spacewalk-java.changes
This PR adds the summary column for the package list in the following pages:
- List / Remove
- Install
- Verify
After:
- No documentation needed: improvement on existing documented features
Fixes https://github.com/SUSE/spacewalk/issues/18968
> Display package summary

- testsuite/features/secondary/min_rhlike_salt_install_package_and_patch.feature
The RedHat-like minion does not need `Test-Channel-x86_64` anymore since it now has its dedicated test channel.
Miss from the base-poduct PR.
No difference.
Fixes #
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/19716 …
> Changing omitted test channel name for RH like client

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/scap.py
Fix ssm keyword parsing for scap scheduling in spacecmd
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/6225
> Fix ssm keyword parsing for scap scheduling in spacecmd

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes
This commit adds 'octet-stream' to the list of acceptable content-types for urls pointing to mirrorlists. This fixes:
https://github.com/uyuni-project/uyuni/issues/6244 and ensures that amazonlinux channels will continue to work.
No difference.
Fixes #
If you need to …
> Add 'octet-stream' to accepted mirrorlist content-types

- testsuite/features/build_validation/containerization/proxy_as_pod_basic_tests.feature
- testsuite/features/core/proxy_register_as_pod.feature
- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
Temporary stop/start tftp service until spacewalk-proxy handle it
Related bug: https://bugzilla.suse.com/show_bug.cgi?id=1205976
No difference.
Ports:
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/19740
> QE: Temporary stop/start tftp service until spacewalk-proxy handle it

- testsuite/features/secondary/srv_handle_config_channels_with_ISS_v2.feature
- testsuite/features/secondary/srv_handle_software_channels_with_ISS_v2.feature
- testsuite/features/step_definitions/command_steps.rb
On a previous PR I refactor a step to support passing a different host by parameter.
But I missed to refactor a scenario using the old step definition.
No difference.
Ports:
- Manager-4.3
> QE: Fix broken call to a step definition

- java/code/src/com/redhat/rhn/domain/notification/NotificationMessage.java
- java/code/src/com/redhat/rhn/domain/notification/types/NotificationType.java
- java/code/src/com/redhat/rhn/domain/notification/types/SubscriptionWarning.java
- java/code/src/com/redhat/rhn/domain/notification/types/test/SubscriptionWarningTest.java
- java/code/src/com/redhat/rhn/domain/user/Pane.java
- java/code/src/com/redhat/rhn/frontend/action/YourRhnAction.java
- java/code/src/com/redhat/rhn/frontend/action/renderers/SubscriptionWarningRenderer.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/taskomatic/task/DailySummary.java
- java/code/webapp/WEB-INF/dwr.xml
- java/code/webapp/WEB-INF/pages/common/fragments/yourrhn/subwarn.jsp
- java/code/webapp/WEB-INF/pages/yourrhn.jsp
- java/spacewalk-java.changes
- schema/spacewalk/common/data/rhnInfoPane.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.2-to-susemanager-schema-4.4.3/900-add-pane-subwarn-rhnInfoPane.sql
- web/html/src/manager/notifications/notification-messages.tsx
This is a port of https://github.com/SUSE/spacewalk/pull/19532
#11008 
This adds a new type of notification for subscriptions that are close to expiring or will expire. 
This warning will show on the overview page also with a link to the subscription matcher. 
The code is ready for review but I need to add unit tests.
Before:
After:
- API …
> Add a subscription warning to the overview page

- java/code/src/com/redhat/rhn/domain/notification/NotificationMessage.java
- java/code/src/com/redhat/rhn/domain/notification/UserNotificationFactory.java
- java/code/src/com/redhat/rhn/domain/notification/test/NotificationFactoryTest.java
- java/code/src/com/redhat/rhn/domain/user/test/UserFactoryTest.java
- java/code/src/com/redhat/rhn/frontend/events/test/NewUserEventTest.java
- java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcHandler.java
- java/code/src/com/redhat/rhn/testing/UserTestUtils.java
- java/spacewalk-java.changes
- python/uyuni/common/notificationUtils.py
- python/uyuni/uyuni-common-libs.changes
The notifications shown in the WebUI are not so usefull for people who not login very often.
Send them also as email if email notifications in the user preferences is enabled.
No difference.
- not needed
Tracks https://github.com/SUSE/spacewalk/pull/19751
> send notifications as email

- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_baremetal_discovery.feature
- testsuite/features/secondary/min_bootstrap_api.feature
- testsuite/features/secondary/min_bootstrap_reactivation.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/features/secondary/min_bootstrap_ssh_key.feature
- testsuite/features/secondary/min_deblike_ssh.feature
- testsuite/features/secondary/min_move_from_and_to_proxy.feature
- testsuite/features/secondary/min_rhlike_ssh.feature
- testsuite/features/secondary/min_salt_mgrcompat_state.feature
- testsuite/features/secondary/min_salt_minions_page.feature
- testsuite/features/secondary/min_ssh_tunnel.feature
- testsuite/features/secondary/minssh_bootstrap_api.feature
- testsuite/features/secondary/minssh_move_from_and_to_proxy.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
Fix this issue: https://github.com/SUSE/spacewalk/issues/19755
In a previous PR I decoupled the responsibility of login/logout from our API handler in a step that had these actions in an atomic way inside the step. I made that way, to be consistent to the way we were handling API calls in the rest of step definitions.
Applying this PR, will fix missing login/logout actions from outside the step, at the beginning and at the end of each feature using that step. 
No difference.
Ports:
- Manager-4.3 (It was only ported in 4.3)
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni- …
> QE: Login/Logout from API in order to enable the use of API calls during the steps

- java/code/src/com/suse/manager/reactor/utils/test/RhelUtilsTest.java
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_alibaba.json
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_almalinux.json
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_amazon.json
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_centos.json
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_centos_res.json
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_oracle.json
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_res.json
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_rhel.json
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_rockylinux.json
- java/code/src/com/suse/manager/reactor/utils/test/dummy_packages_redhatprodinfo_sll.json
- java/code/src/com/suse/manager/webui/utils/salt/custom/PkgProfileUpdateSlsResult.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/salt/packages/redhatproductinfo.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Fix "Feature:Bootstrap a SSH-managed Red Hat-like minion" fails with server error
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19713
> Fix "Feature:Bootstrap a SSH-managed Red Hat-like minion" fails with server error

- testsuite/features/init_clients/min_virthost.feature
- testsuite/features/secondary/minkvm_guests.feature
- testsuite/run_sets/init_clients.yml
The initialization of the virthosts is done in `minkvm_guest.features` which is executed during secondary_parallelizable. With the upcoming Salt bundle tests we need in already in secondary. The solution was to move the initialization into core and just leave the KVM tests in `minkvm_guest.feature` in secondary_parallelizable. This PR adds a new `min_virthost.feature` to init_clients in the core stage.
No difference.
Manager 4.3
Manager 4.2
If you …
> QE: Move virthost init from secondary to core

- susemanager-sync-data/additional_products.json
- susemanager-sync-data/susemanager-sync-data.changes
Tools Channels for OES 2023 need to be mandatory.
Additional fix for https://github.com/uyuni-project/uyuni/pull/6251
No difference.
> enable Tools Channels for OES 2023

- testsuite/features/support/twopence_init.rb
Fix typo in name of environment variable for openSUSE 15.4 SSH minion.
Ports:
* 4.2: SUSE/spacewalk#19771
* 4.3: SUSE/spacewalk#19770
> Fix environment variable name

- testsuite/features/build_validation/containerization/proxy_as_pod_basic_tests.feature
- testsuite/features/core/proxy_register_as_pod.feature
- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
Jabberd Service was removed in master.
Additional fix for https://github.com/uyuni-project/uyuni/pull/6216
No difference.
> jabberd service was removed

- java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
- Add a note in docs that expected date is ISO format.
- Return a proper exception in case filter already exist
Before this change error like below was thrown.
```
xmlrpc.client.Fault: <Fault -1: 'redstone.xmlrpc.XmlRpcFault: unhandled internal exception: com.redhat.rhn.domain.contentmgmt.ErrataFilter@4c017b33[pattern=<null>,criteria=com.redhat.rhn.domain.contentmgmt.FilterCriteria@27d71d3c[matcher=GREATEREQ,field=issue_date,value=2022-12-01T18:35:12Z],id=8,name=filter_name2,org=com.redhat.rhn.domain.org.Org@1d96f234[id=1,name=Suse],rule=DENY,created=2022-12-01 18:35:09.892,modified=2022-12-01 18:35:09.892]'>
```
No difference.
- No documentation needed: **API docs will get created automatically**
Fixes #
Make sure the …
> Update the API doc and check if filter already exists

- testsuite/features/build_validation/add_custom_repositories/add_rocky8_repositories.feature
- testsuite/features/build_validation/add_custom_repositories/add_rocky9_repositories.feature
avoid this:
Ports:
* 4.2: not appliable, we only have rocky 8
* 4.3: SUSE/spacewalk#19785
> Avoid conflict between CLM projects of same name

- testsuite/features/support/constants.rb
This PR fixes the channel name for mgr-create-bootstrap-repo in case of Rocky 9.
Ports:
* 4.2: N/A
* 4.3: SUSE/spacewalk#19793
> Fix Rocky 9 bootstrap repo

- testsuite/features/support/twopence_init.rb
This PR mitigates this pain:
```
Node: suma-bv-43-ctl, OS Version: 15.4, Family: opensuse-leap
'suma-bv-43-ctl' is running OS opensuse-leap 15.4
Node: suma-bv-43-srv, OS Version: 15-SP4, Family: sles
'suma-bv-43-srv.mgr.prv.suse.net' is running OS sles 15-SP4
Node: suma-bv-43-pxy, OS Version: 15-SP4, Family: sles
'suma-bv-43-pxy.mgr.prv.suse.net' is running OS sles 15-SP4
Node: suma-bv-43-cli-sles12sp4, OS Version: 12-SP4, Family: sles
'suma-bv-43-cli-sles12sp4.mgr.prv.suse.net' is running OS sles 12-SP4
Node: suma-bv-43-min-sles12sp4, OS Version: 12-SP4, Family: sles
'suma-bv-43-min-sles12sp4.mgr.prv.suse.net' is running OS sles 12-SP4
Node: suma-bv-43-minssh-sles12sp4, OS Version: 12-SP4, Family: sles
'suma-bv-43-minssh-sles12sp4.mgr.prv.suse.net' is running OS sles 12-SP4
Node: …
```
> Remove duplicate debug information

- java/code/src/com/redhat/rhn/domain/action/ActionFactory.java
- java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
- java/code/src/com/redhat/rhn/domain/server/Server_legacyUser.hbm.xml
- java/code/src/com/redhat/rhn/frontend/action/ssm/RebootSystemAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/SystemListHelper.java
- java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemOverviewAction.java
- java/code/src/com/redhat/rhn/frontend/dto/SystemOverview.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/webapp/WEB-INF/pages/systems/sdc/overview.jsp
- java/spacewalk-java.changes
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.2-to-susemanager-schema-4.4.3/002-systems-overview.sql
- web/html/src/components/systems.tsx
- web/spacewalk-web.changes
Add indications to the the system overview that a reboot is scheduled and to the system list that a reboot is needed
Before:
After:
- No tests: 
Tracks https://github.com/SUSE/spacewalk/issues/5309
> Add reboot needed/scheduled indications

- testsuite/features/support/constants.rb
Again a fix to Rocky 9 channels.
Why can't we use an unified naming scheme everywhere and that would be consistent between versions ???
Ports:
* 4.2: N/A
* 4.3: SUSE/spacewalk#19813
> Fix activation key for Rocky 9

- testsuite/features/secondary/min_ssh_tunnel.feature
Use `1-SUSE-SSH-KEY-x86_64` key in ssh tunnel feature in the cleanup stage to have ssh contact method as expected.
No difference.
Tracks #
4.2 https://github.com/SUSE/spacewalk/pull/19816
4.3 https://github.com/SUSE/spacewalk/pull/19817 …
> Use SSH key for SSH minion

- java/code/src/com/redhat/rhn/domain/product/SUSEProduct.java
- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
Fix crash when a product with a PTF repo had no repositories defined.
Happens as I used the product tag "Uyuni" while we had a PTF repo for SUSE Manager.
No difference.
> Project lotus fix crash

- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
Add the use of activation key for the bootstrap of sle minion in a cleanup scenario to have the same state as at the start.
Add a missing subscription to a channel to make a feature idempotent again.
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/19821
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/19823 (only on software channels feature)
4.3 https://github.com/SUSE/spacewalk/pull/19825 …
> Testsuite: Correct features to have them be idempotent

- testsuite/features/secondary/min_bootstrap_reactivation.feature
- testsuite/features/step_definitions/common_steps.rb
Removes api login and logout in `I enter the reactivation key of ` step to avoid conflict with a previous authentication.
Conflicts with https://github.com/uyuni-project/uyuni/blob/master/testsuite/features/secondary/min_bootstrap_reactivation.feature#L13
This affects only one scenario.
Fix case in related feature name as well.
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/19829
Tracks #
4.3 https://github.com/SUSE/spacewalk/pull/19832
Only case change for 4.2 https://github.com/SUSE/spacewalk/pull/19833 …
> Testsuite: Remove extra login

- susemanager-utils/testing/docker/scripts/schema_idempotency_test_pgsql.py
Port script to python 3
No difference.
> port schema_idempotency_test to python3

- testsuite/features/secondary/srv_advanced_search.feature
- testsuite/features/step_definitions/navigation_steps.rb
Related to https://github.com/SUSE/spacewalk/issues/19820
As you can see here, we are using the label, instead of the name, and the label is not unique, we have the same label text at three different web elements. That's causing our issue.
I will instead use the name.
No difference.
Ports:
- Manager-4.2
- Manager-4.3 …
> QE: Advanced search, using name instead of label to find checkboxes

- susemanager-utils/testing/docker/scripts/reportdb_schema_idempotency_test_pgsql.py
Fix also the repotdb script
Additional fix for https://github.com/uyuni-project/uyuni/pull/6305
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/19871
> port reportdb idempotency script to python3

- java/code/src/com/redhat/rhn/manager/setup/ProxySettingsManager.java
- java/code/src/com/redhat/rhn/manager/setup/test/ProxySettingsManagerTest.java
- java/spacewalk-java.changes
- web/html/javascript/susemanager-setup-wizard-proxy-settings.js
- web/spacewalk-web.changes
It removes console.log used to print the proxy data in browser logs in order to avoid expose sensitive data. It also changes proxy settings retrieval to not include password.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/19587 …
> Prevent proxy data from being logged

- schema/spacewalk/upgrade/susemanager-schema-4.3.9-to-susemanager-schema-4.3.10/006-update-rhnServerOverview.sql
- schema/spacewalk/upgrade/susemanager-schema-4.4.1-to-susemanager-schema-4.4.2/002-rhnServerOverview-bools.sql
This PR fixes the idempotency for a SQL script updating the table `rhnServerOverview` which was not working correctly when starting the migration from a version >= 4.3.0.
No difference.
- No tests: no code change
> Fix sql script idempotency for rhnServerOverview

- testsuite/features/support/twopence_init.rb
In a previous changes I refactored the method get_system_name so it raised and error if the node did not exist, I did it so we could catch easily some issues with not defined host.
But I missed a case where we are actually relying on not having it defined to return the text of the host parameter. I recovered this with some extra adjustments.
No difference.
Ports:
- Manager-4.3 …
> QE: Refactor get_system_name

- testsuite/features/secondary/min_config_state_channel_subscriptions.feature
Waiting for some web elements to be loaded, as we have several errors in `Feature:State Configuration channels`
https://github.com/SUSE/spacewalk/issues/19882
No difference.
Ports:
- Manager-4.3
- Manager-4.2 ?
> QE: Waiting for some web elements to be loaded

- testsuite/features/finishing/srv_smdba.feature
- testsuite/features/step_definitions/smdba_steps.rb
We have a running DB where we destroy its storage by removing files.
Then we call "restore" which takes some time. During this time it can happen that somebody ask the DB
and it coredump because of the broken data. This also prevent a successful restore.
Before destroying the storage, we better stop the DB
Port of https://github.com/SUSE/spacewalk/pull/19892
No difference. …
> Make dbtest more reliable

- testsuite/features/finishing/srv_debug.feature
- testsuite/features/finishing/srv_smdba.feature
- testsuite/features/step_definitions/smdba_steps.rb
Add a step checking the database status output to detect potential errors.
No difference.
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/19900
4.3 https://github.com/SUSE/spacewalk/pull/19901 …
> Testsuite: Enable error detection in SMDBA feature

- java/conf/rhn_java.conf
- java/spacewalk-java.changes
Limit the default changelog data in generated metadata. Instead of using unlimited(0) as default, use the same default as SUSE Linux Enterprise (20 entries).
No difference.
- [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pull/1945)
No tests: **no tests added**
Tracks SUSE/spacewalk#19711 …
> Limit changelog data in generated metadata to 20 entries. SUSE/spacewalk#19711

- testsuite/features/step_definitions/api_common.rb
Fix addition of custom channels to activation key
- for the filtered CLM result
- for the monitoring server
- for the build host and terminal
Tested on 4.3.3 BV deployment.
Ports:
* 4.2: SUSE/spacewalk#19914
* 4.3: SUSE/spacewalk#19913
> Fix addition of custom channels to activation key

- testsuite/features/step_definitions/common_steps.rb
Co-authored with @vandabarata .
The order of the events can be random.
That makes the timeout to pick them up too strict, especially for the slower SSH minions.
In this PR, we double that timeout to 3 minutes.
Ideally, we would have a global timeout for all of 3 bootstrap events. Something like:
```
And 500 seconds until the events "Apply states", "Hardware List Refresh", and "Package List Refresh" are completed
```
but that would be a much bigger fix.
Ports:
* 4.2:
* 4.3: https://github.com/SUSE/spacewalk/pull/19917
> The order of the bootstrap events can be random

- java/code/src/com/suse/manager/webui/templates/groups/custom.jade
- java/code/src/com/suse/manager/webui/templates/minion/custom.jade
- java/code/src/com/suse/manager/webui/templates/org/custom.jade
- java/code/src/com/suse/manager/webui/templates/yourorg/custom.jade
- java/code/webapp/WEB-INF/decorators/layout_error.jsp
- java/code/webapp/WEB-INF/decorators/layout_head.jsp
- java/code/webapp/WEB-INF/pages/schedule/actionchain.jsp
- java/spacewalk-java.changes
- web/html/src/styleguide/template.js
- web/spacewalk-web.changes
Revert the sources updated in https://github.com/uyuni-project/uyuni/pull/6012 until we figure out while the build is borked.
No difference.
https://github.com/SUSE/spacewalk/issues/19882
> Revert Select2 and jQuery UI to old sources

- web/html/src/core/log/index.ts
- web/spacewalk-web.changes
In JSP pages we inject CSRF Tokens as hidden fields into the page.
In REACT packages we often set a global variable.
Parse this variable if the token cannot be found in a hidden field.
No difference.
- No tests: **no idea how**
Tracks https://github.com/SUSE/spacewalk/pull/19925 https://github.com/SUSE/spacewalk/pull/19926
If you …
> extract the csrf token from the windows variable if not available as element

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.3-to-susemanager-schema-4.4.4/000-uyuni-fix-ol9-repos.sql
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
- repourl was wrongly pointing to a GPG key and the GPG key field was empty
- fixed also the distchannelmap setting
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/6266
Fixes https://github.com/SUSE/spacewalk/issues/19799 …
> fix oracle linux 9 repository definitions

- java/conf/logrotate/gatherer
- java/conf/logrotate/rhn_web_api
- java/spacewalk-java.changes
- proxy/proxy/logrotate/rhn-proxy-broker
- proxy/proxy/logrotate/rhn-proxy-redirect
- proxy/proxy/spacewalk-proxy.changes
- python/spacewalk/logrotate/spacewalk-backend-app
- python/spacewalk/logrotate/spacewalk-backend-applet
- python/spacewalk/logrotate/spacewalk-backend-cdn
- python/spacewalk/logrotate/spacewalk-backend-config-files
- python/spacewalk/logrotate/spacewalk-backend-config-files-tool
- python/spacewalk/logrotate/spacewalk-backend-iss
- python/spacewalk/logrotate/spacewalk-backend-iss-export
- python/spacewalk/logrotate/spacewalk-backend-package-push-server
- python/spacewalk/logrotate/spacewalk-backend-server
- python/spacewalk/logrotate/spacewalk-backend-tools
- python/spacewalk/logrotate/spacewalk-backend-xmlrpc
- python/spacewalk/spacewalk-backend.changes
- search-server/spacewalk-search/spacewalk-search.changes
- search-server/spacewalk-search/src/config/etc/logrotate.d/rhn-search
- susemanager-utils/susemanager-sls/salt/services/salt-minion.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR fixes the logrotate configuration files fixing the format of the `size` directive and removing the unneeded `weekly`.
No difference.
- No tests: no code change, only configuration files
Fixes https://github.com/SUSE/spacewalk/issues/19919
Tracks [Manager 4.3](https://github.com/SUSE/spacewalk/pull/19944) [Manager-4.2](https://github.com/SUSE/spacewalk/pull/19945) …
> Update logrotate configurations

- testsuite/features/secondary/srv_advanced_search.feature
Additional screenshot in Advanced Search tests to debug a flaky test
No difference.
No ports.
> QE: Additional screenshot in Advanced Search tests to debug a flaky test

- testsuite/features/secondary/min_deblike_openscap_audit.feature
Workaround for [1206586](https://bugzilla.suse.com/show_bug.cgi?id=1206586) (Ubuntu 22.04 OpenScap support)
Card in our board to revert the workaround when the issue is fixed  (Blocked as it's an issue external from SUMA team) https://github.com/SUSE/spacewalk/issues/19955
No difference.
- Cucumber tests were workarounded
Ports:
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/19956 …
> QE: Workaround for 1206586 (Ubuntu 22.04 OpenScap support)

- .github/workflows/rubocop.yml
This includes the 2 RuboCop configuration files that when changed should also trigger a RuboCop run in a pull request.
No difference.
- Manager 4.3
- Manager 4.2
> QE: Adjust RuboCop GitHub Actions workflow

- testsuite/features/reposync/srv_sync_channels.feature
We are checking that we have selected a channel `SLE-Module-Containers12-Pool for x86_64 Containers Module 12 x86_64 [sle-module-containers12-pool-x86_64-sp4]` but today it suddenly started to fail, and we noticed that the text has changed `SLE-Module-Containers12-Pool for x86_64 SP4 Containers Module 12 x86_64 [sle-module-containers12-pool-x86_64-sp4]`  notice the additional SP4 text appended.
This PR aims to adapt our tests with the changes in SCC.
No difference.
Ports:
- Manager-4.2
- Manager-4.3
If you don't …
> QE: Fix a rename of SCC channel for Containers sles12 sp4

- testsuite/features/support/commonlib.rb
- testsuite/features/support/constants.rb
Fixes RuboCop issues introduces with #6347
No difference.
- Manager: 4.3: https://github.com/SUSE/spacewalk/pull/19968
> Fix RuboCop issues introduces with #6347

- testsuite/features/reposync/srv_sync_channels.feature
Rename the channel SLE-Module-Containers12-Updates
No difference.
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/19970
> Rename the channel SLE-Module-Containers12-Updates

- testsuite/features/support/commonlib.rb
- testsuite/features/support/constants.rb
Considers only that Rocky is at version 8, without filtering by the subversion, making our code more resilient to minor version upgrades.
> QE: Ignore rocky subversion for reposync

- testsuite/features/step_definitions/command_steps.rb
https://github.com/uyuni-project/uyuni/blob/master/testsuite/features/step_definitions/command_steps.rb#L1484 converts OS versions such as `15-SP3` as `15.0` which results in the associated workaround to fail for 15SP3 minions.
This PR replaces `-SP` by `.` in the OS version beforehand so the line works properly.
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/18746
Tracks # 
4.3
4.2
If you …
> QE: Replace occurences of '-SP' in OS version before conversion to float

- testsuite/features/secondary/allcli_action_chain.feature
- testsuite/features/secondary/allcli_config_channel.feature
- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/allcli_software_channels_dependencies.feature
- testsuite/features/secondary/min_baremetal_discovery.feature
- testsuite/features/secondary/min_cve_audit.feature
- testsuite/features/secondary/min_salt_formulas.feature
- testsuite/features/secondary/srv_clone_channel_npn.feature
- testsuite/features/secondary/srv_group_union_intersection.feature
- testsuite/features/secondary/srv_power_management.feature
- testsuite/features/secondary/srv_power_management_redfish.feature
The step to click on "Clear" is failing sometimes, despite the button being there. Trying to follow the identifier to test if it passes this way.
Fixes https://github.com/SUSE/spacewalk/issues/19899
Ports:
- 4.3 https://github.com/SUSE/spacewalk/pull/20007
> QE: Fix clicking on clear step in testsuite

- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
With the new way of visiting a system's page directly, we use the `get_target` method, which doesn't include a case for the `pxeboot_minion`. For now, the fix has been to navigate to it using the step we used before.
- 4.3 https://github.com/SUSE/spacewalk/pull/20008
> QE: Fix navigation to pxeboot system's page

- testsuite/run_sets/reposync.yml
Temporarily disables Rocky 8 reposync until further debugging can happen on what the issue is, so we can have test results beyond Core.
> QE: Temporarily disable Rocky 8 reposync

- testsuite/features/secondary/allcli_action_chain.feature
- testsuite/features/secondary/allcli_config_channel.feature
- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/allcli_software_channels_dependencies.feature
- testsuite/features/secondary/min_cve_audit.feature
- testsuite/features/secondary/min_salt_formulas.feature
- testsuite/features/secondary/srv_clone_channel_npn.feature
- testsuite/features/secondary/srv_group_union_intersection.feature
- testsuite/features/secondary/srv_power_management.feature
- testsuite/features/secondary/srv_power_management_redfish.feature
Reverts the changes to clicking on Clear step, except the Cleanup for the Baremetal discovery feature, where it fixed the issue.
Fixes https://github.com/SUSE/spacewalk/issues/19899
Reverts most of #6400 
> QE: Revert changes to clicking on Clear step, except the fixed feature

- java/code/src/com/redhat/rhn/frontend/action/configuration/channel/ChannelDeployConfirmAction.java
Sonarcloud refactoring caused assigning the config file list to systems variable.
This cause property not found errors
No difference.
Only in master
> assign correct list to request

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
- susemanager-utils/susemanager-sls/salt-ssh/preflight.sh
- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Forward port of https://github.com/SUSE/spacewalk/pull/19370
Add ability to onboard SLE Micro servers using web ui and bootstrap script
No difference.
- No documentation needed: Already documented, this standardize onboarding to the same level as other systems
Fixes https://github.com/SUSE/spacewalk/issues/18505
Tracks https://github.com/SUSE/spacewalk/pull/19370 …
> SLE Micro web ui and bootstrap script onboarding

- testsuite/features/init_clients/srv_check_reposync.feature
Wait until the custom channel has been synchronized. As otherwise it fails sometimes when checking for solv file.
No difference.
Ports:
- Manager-4.3
- Manager-4.2?
> QE: Wait until the custom channel has been synchronized

- spacewalk/certs-tools/rhn_bootstrap_strings.py
Fix missing quotation marks in -n test
No difference.
Fixes #
> Fix missing quotation marks in -n test

- java/code/src/com/redhat/rhn/frontend/action/token/ActivationKeyDetailsAction.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/spacewalk-java.changes
- testsuite/features/core/srv_create_activationkey.feature
- testsuite/features/init_clients/allcli_update_activationkeys.feature
- testsuite/features/init_clients/min_virthost.feature
- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/srv_manage_activationkey.feature
- web/html/src/manager/content-management/shared/components/panels/sources/channels/channels-selection.tsx
- web/html/src/manager/minion/ansible/ansible-control-node.test.tsx
- web/html/src/manager/minion/ansible/ansible-control-node.tsx
- web/html/src/manager/minion/ansible/ansible-path-content.tsx
- web/html/src/manager/systems/activation-key/activation-key-channels.tsx
When creating an activation key it might happen that Loading the channels takes a while.
The testsuite does not always wait for the page being fully loaded.
This PR detect this case and throw a better message than an ISE and change the testsuite to wait for the 
"Loading..." text to disappear.
Additionally it align all occurrence of "Loading..." to use the same number of dots (3 dots)
No difference.
- Cucumber tests were adapted
Tracks https://github.com/SUSE/spacewalk/pull/20026 https://github.com/SUSE/spacewalk/pull/20027
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni- …
> Fix ise activation key create

- testsuite/features/step_definitions/navigation_steps.rb
Using the current code I end up always on the login page and the test fail:
When I use a relative URL, I stay logged-in and the test pass.
No difference.
> use visit with relative URL to stay logged-in

- testsuite/features/step_definitions/common_steps.rb
Adds logs to the SCC product listing command for easier debugging in case there are changes in product names.
- 4.2 https://github.com/SUSE/spacewalk/pull/20039
- 4.3 https://github.com/SUSE/spacewalk/pull/20038
> QE: Add logs to SCC product listing command

- testsuite/features/secondary/srv_advanced_search.feature
Adds a step to clean the search index before performing the first search.
Might fix https://github.com/SUSE/spacewalk/issues/19820
- 4.3 https://github.com/SUSE/spacewalk/pull/20049
- 4.2 https://github.com/SUSE/spacewalk/pull/20050
> QE: Add step to clean search index before doing first search

- java/code/src/com/redhat/rhn/manager/kickstart/KickstartFormatter.java
- java/spacewalk-java.changes
This PR fixes an issue with the snippets used by Uyuni when generating autoinstallation profiles.
After the upgrade to Cobbler 3.3.3, the `kickstart_*` snippets were renamed to `autoinstall_*`, so we need to adjust Java to use the proper ones to prevent errors when generating autoinstallation files:
```
...
...
...
```
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/19792 …
> Fix name for "autoinstall" snippets after Cobbler 3.3.3

- susemanager-utils/susemanager-sls/salt/channels/gpg-keys.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
SUSE Liberty Linux 9 comes with a new gpg key which needs to be installed.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/20048
> install SUSE Liberty v2 GPG key

- testsuite/features/step_definitions/command_steps.rb
IN AWS this check fail every second time. Try what happens if we re-try after 2 seconds.
No difference.
Before:
After:
- …
> re-try sanity check

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/spacewalk-java.changes
- schema/spacewalk/common/data/rhnServerGroupType.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.2-to-susemanager-schema-4.4.3/100-rename_monitoring_entitlement.sql
Rename the entitlement _Monitoring_ to _Monitored Host_.
Before: 
After:
- No documentation needed: Entitlement name is not mentioned in documentation.
- No tests: Minor change not covered by the tests.
Fixes SUSE/spacewalk#19615
> Rename monitoring enablement

- testsuite/run_sets/reposync.yml
Reverts uyuni-project/uyuni#6403 to be able to see why core fails when this is enabled.
> Revert "QE: Temporarily disable Rocky 8 reposync"

- testsuite/features/secondary/min_bootstrap_reactivation.feature
- testsuite/features/secondary/min_salt_mgrcompat_state.feature
- testsuite/features/secondary/min_salt_minions_page.feature
Add activation key bootstrap in features in order to get better idempotency.
Remove some cleanup scenarios that became unnecessary.
Includes port of https://github.com/SUSE/spacewalk/pull/20015
No difference.
Fixes #
Tracks # 
4.2
4.3 …
> Add activation key in feature

- java/code/src/com/redhat/rhn/manager/audit/CVEAuditManager.java
- java/code/src/com/redhat/rhn/manager/audit/test/CVEAuditManagerTest.java
- java/spacewalk-java.changes
Change behavior of CVE Audit to display patches from parent of cloned channel instead of from the successor product if it also has a patch for given CVE available.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/19846 …
> Fix CVE Audit ignoring errata in parent channels if patch in successor exists

- java/code/src/com/suse/manager/reactor/messaging/test/pkg_install.live_patch.json
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/utils/test/SaltUtilsTest.java
- java/spacewalk-java.changes
We don't run a full profile update after simple package install/upgrade operations because of performance reasons. However, the live patch data is only updated with a package profile update.
This patch will trigger a package profile update whenever a new live patch is installed, so the LP data shown on the system overview page will update automatically.
See: https://bugzilla.suse.com/show_bug.cgi?id=1206249
Port of: https://github.com/SUSE/spacewalk/pull/19980 …
> Trigger package refresh when a new live-patch is installed (bsc#1206249)

- testsuite/features/core/proxy_branch_network.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
This fixes the setup of retail environment.
Before, the image-sync was called before the retail groups were created. As a result, the bug https://bugzilla.suse.com/show_bug.cgi?id=1199157 was not detected. This PR moves  image-sync to the right place.
Also, it adds the required restart after installation of saltboot formula and assigns the branch server to branch group.
The second commit increases the timeout for saltboot state to 600s. It took 400s at 
https://ci.suse.de/view/Manager/view/Manager-Head/job/manager-Head-dev-acceptance-tests-NUE/3237/
No difference.
Before:
After:
- Documentation issue was created: [Link for SUSE …
> Testsuite: fixes for retail test

- tftpsync/susemanager-tftpsync/susemanager-tftpsync.changes
- tftpsync/susemanager-tftpsync/sync_post_tftpd_proxies.py
This PR introduces a threadpool to increase the performance of Cobbler sync while syncing files to proxies.
Before this PR, pushing individual files is done sequentially, which is a bottleneck in case of large deployments.
With this PR, files are pushed by a threadpool, increasing the performance of this operation.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/19577 …
> Introduce threadpool for tftpsync to increase performance while syncing files to proxies (bsc#1205489)

- spacecmd/spacecmd.changes
- spacecmd/spacecmd.spec
The spacecmd specfile lists python3-simplejson as a dependency, but this makes no sense, as simplejson is only used when python is < 2.6. The requirement is causing install errors. This patch removes the dependency. There should be no code that expects it.
No difference.
Fixes #
If you …
> Remove python3-simplejson dependency

- testsuite/features/init_clients/allcli_update_activationkeys.feature
Following https://suse.slack.com/archives/C02D12TNYLS/p1673352576688079 , adding a check to verify that all expected channels are enabled in the activation key update (including those automatically enabled).
`SLE-Product-SLES15-SP4-Updates for x86_64` is mandatory and - despite being included - is not considered as checked.
Two more channels are checked in 4.2 and 4.3: `SLE-Manager-Tools15-Updates for x86_64 SP4` and `SLE-Manager-Tools15-Pool for x86_64 SP4`
No difference.
Fixes #
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/20106
4.3 https://github.com/SUSE/spacewalk/pull/20105 …
> Testsuite: Add a check for enabled channels

- java/code/src/com/redhat/rhn/domain/channel/test/ChannelTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/spacewalk-java.changes
Check if a channel is modular using the proper `isModular()` method.
Port of: https://github.com/SUSE/spacewalk/pull/20041
> Fix modular channel check during system update via XMLRPC (bsc#1206613)

- testsuite/features/secondary/srv_content_lifecycle.feature
The content lifecycle feature was not completely idempotent as the channels created during that feature are not deleted and are never used either later on.
Channels are deleted in a certain order to avoid deletion conflicts between channel clones.
No difference.
Fixes #
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/20123
4.3 https://github.com/SUSE/spacewalk/pull/20122 …
> Testsuite: Cleanup content lifecycle feature to remove created channels

- testsuite/features/step_definitions/common_steps.rb
This will increase the timeout of downloading images in the test suite from 500s to 700s. This should fix the recently failing Rocky 8 reposync issues due to only partially downloading the ISO image.
No difference.
- Manager 4.3:
- Manager 4.2: …
> QE: Increase timeout for downloading ISOs

- susemanager-utils/testing/automation/java-checkstyle.sh
- susemanager-utils/testing/automation/java-unittests-pgsql.sh
Use a volume to cache the obs-to-maven data in CI.
No difference.
Fixes #
> Use a volume to cache obs-to-maven parsed primary.xml data

- testsuite/features/build_validation/core/allcli_sanity.feature
- testsuite/features/build_validation/create_bootstrap_repositories/srv_create_bootstrap_repositories.feature
- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/core/proxy_branch_network.feature
- testsuite/features/core/srv_create_activationkey.feature
- testsuite/features/init_clients/allcli_update_activationkeys.feature
- testsuite/features/init_clients/min_virthost.feature
- testsuite/features/init_clients/srv_check_reposync.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_bootstrap_reactivation.feature
- testsuite/features/secondary/min_salt_mgrcompat_state.feature
- testsuite/features/secondary/min_salt_minions_page.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
- testsuite/features/secondary/srv_advanced_search.feature
- testsuite/features/secondary/srv_manage_activationkey.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/step_definitions/security_steps.rb
- testsuite/features/support/constants.rb
- testsuite/features/support/env.rb
- testsuite/features/support/twopence_init.rb
Update the copyright headers of files we already edited this year.
Also, `security_steps.rb` was missing a copyright header. This adds it.
No difference.
- No tests: Only comments edited
Manager-4.3: https://github.com/SUSE/spacewalk/pull/20135
Manager-4.2: https://github.com/SUSE/spacewalk/pull/20136
> QE: Update copyright headers and add missing one

- spacecmd/spacecmd.changes
- spacecmd/spacecmd.spec
Add python-dateutil dependency for spacecmd.
No difference.
Fixes #6217
> Add python-dateutil dependency

- testsuite/features/secondary/min_ansible_control_node.feature
- testsuite/features/secondary/min_deblike_openscap_audit.feature
- testsuite/features/secondary/min_rhlike_openscap_audit.feature
- testsuite/features/secondary/minssh_ansible_control_node.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/support/commonlib.rb
Remove the use of injected repositories in the testsuite for SLES nodes
The use of some repositories remains:
`tools_update_repo`
`tools_pool_repo`
`tools_additional_repo`
`test_repo_rpm_pool ` 
These repositories do not have any equivalent in the base product channels even though they could be potentially integrated to a custom channel.
`os_pool_repo`
`os_update_repo`
These repositories are used to configure the proxy as a branch server. At that point, the channels have not be synced.
This could be solved by changing the order of features and/or with the future use of the proxy product. 
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/13869
Tracks # 
4.2 …
> Testsuite: Deprecate injected repos in features

- testsuite/features/secondary/min_deblike_openscap_audit.feature
- testsuite/features/secondary/min_rhlike_openscap_audit.feature
Due to updated openSCAP/scap-security-guide packages, the test suite has to be adapted, too.
Fixes https://github.com/SUSE/spacewalk/issues/20151
No difference.
- Manager 4.3:
- Manager 4.2: …
> QE: Rename openSCAP test results

- java/code/src/com/suse/manager/webui/services/SaltActionChainGeneratorService.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/src/modules/mgractionchains.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Currently some logs are misleading e.g. 
from `rhn_web_ui.log`:
```
2023-01-13 12:03:12,252 [salt-event-thread-3] ERROR com.suse.manager.webui.services.SaltActionChainGeneratorService - Could not collect salt:// references from file /srv/susemanager/salt/actionchains/actionchain_0_346f8bf963553ef574a0c65763c03803_1.sls
```
or in minion `/var/log/salt/minion`:
```
2023-01-13 12:03:09,010 [salt.loaded.ext.module.mgractionchains:85  ][ERROR   ][1080] File /etc/salt/minion.d/_mgractionchains.conf not found
```
Fix these messages.
No difference.
- Documentation issue was created: [Link for SUSE Manager …
> Improve logs when _mgractionchains.conf and *sls are missing

- testsuite/features/support/api_test.rb
- testsuite/features/support/cobbler_test.rb
- testsuite/features/support/custom_formatter.rb
- testsuite/features/support/http_client.rb
- testsuite/features/support/lavanda.rb
- testsuite/features/support/namespaces/actionchain.rb
- testsuite/features/support/namespaces/activationkey.rb
- testsuite/features/support/namespaces/api.rb
- testsuite/features/support/namespaces/audit.rb
- testsuite/features/support/namespaces/channel.rb
- testsuite/features/support/namespaces/configchannel.rb
- testsuite/features/support/namespaces/image.rb
- testsuite/features/support/namespaces/kickstart.rb
- testsuite/features/support/namespaces/schedule.rb
- testsuite/features/support/namespaces/system.rb
- testsuite/features/support/namespaces/user.rb
- testsuite/features/support/pretty_formatter.rb
- testsuite/features/support/xmlrpc_client.rb
This PR is part of this card https://github.com/SUSE/spacewalk/issues/14192
This PR only add documentation headers for each method, in order to get rid of Rubocop alarms that we are not ignoring.
**Note:
Be aware that all the documentation is auto-generate by the IDE, so feel free to contribute with suggestion comments and I will apply them directly.**
No difference.
- None
Ports:
- Manager-4.2
- Manager-4.3 …
> Add Doc headers in all the Class and Module methods

- testsuite/features/secondary/srv_content_lifecycle.feature
Include the removal of tools channels for susemanager in clp feature for susemanager
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/20175
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/20177
4.3 https://github.com/SUSE/spacewalk/pull/20176 …
> Testsuite: CLP cleanup fix

- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes
Show RHEL target for bootstrap repo creation only if it is really connected to the CDN.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/20156
> detect if RHEL target is really connected to the CDN (bsc#1206861)

- java/code/src/com/suse/manager/webui/services/pillar/MinionGeneralPillarGenerator.java
- java/code/src/com/suse/manager/webui/services/pillar/test/MinionPillarManagerTest.java
- java/spacewalk-java.changes
The new pillar item informs the minion if the server runs Uyuni or SUSE Manager.
No difference.
- Existing unit tests were extended
Required for SUSE/spacewalk#19584
> Add `mgr_server_is_uyuni` minion pillar item

- susemanager-utils/testing/automation/java-checkstyle.sh
- susemanager-utils/testing/automation/java-unittests-pgsql.sh
Cache the generated maven repository to only fetch the new packages
No difference.
Fixes #
> Cache obs-to-maven created repository

- testsuite/features/step_definitions/api_common.rb
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/datepicker_steps.rb
- testsuite/features/step_definitions/docker_steps.rb
- testsuite/features/step_definitions/lock_packages_on_client.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/step_definitions/retail_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/step_definitions/security_steps.rb
- testsuite/features/step_definitions/smdba_steps.rb
This PR adds headers to the beginning of each step-definition file to give a rough overview about the function of the steps found within.
This is to make finding the right steps easier, help newcomers find their way around faster, make finding already existing definitions easier and help identifying accidentally misplaced new step-definitions.
No difference.
- No tests: This only adds comments
Manager-4.3: https://github.com/SUSE/spacewalk/pull/20209
Manager-4.2: https://github.com/SUSE/spacewalk/pull/20210
Fixes: https://github.com/SUSE/spacewalk/issues/17294 …
> QE: Add summary headers to step definition files

- java/code/src/com/suse/manager/reactor/PGEventStream.java
- java/spacewalk-java.changes
After restart of postgres service, handling of salt events stops.
Debugging shows, that `salt-event-connection-watchdog` correctly detects that the connection was closed and calls
`SaltReactor::eventStreamClosed` -> `SaltReactor::connectToEventStream` -> `saltApi.getEventStream()` -> `new PGEventStream()`. All this is called with stale hibernate session, so the database access in `PGEventStream` constructor fails and the new connection is not created.
This PR makes sure that the stale session is not used.
No difference.
- No documentation needed: user invisible change
- Cucumber test: TBD
Fixes https://github.com/SUSE/spacewalk/issues/20143 …
> Fix reconnection of postgres event stream

- testsuite/features/reposync/srv_sync_channels.feature
- testsuite/features/support/constants.rb
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
spacewalk-commonn-channels for SUSE Liberty Linux
We had `el` channels added, but that was wrong, as the channel names must be specific for the OS (`spacewalk-common-channels` can't reuse channels, only repositories, as of today)
The base channel for the client tools for `el9` was incorrect.
And finally, the devel client tools were missing, as well as the entire SUSE Liberty Linux 7.
No difference.
- Documentation PR: https://github.com/uyuni-project/uyuni-docs/pull/2006
- No tests: 8 is already covered by the testsuite. I am testing 9 manually
Tracks https://github.com/SUSE/spacewalk/issues/20195 …
> spacewalk-commonn-channels for SUSE Liberty Linux

- java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
- java/spacewalk-java.changes
This PR fixes a problem with channels / packages related actions triggered via actions chains on SSH minions that we have seen happening in the HEAD acceptance tests. We need to explicitely add `gpg` as `ssh_extra_filerefs` on SSH executions made by Uyuni, in order to ensure those extra files are available on the context of SSH action chain execution.
As mentioned, this should fix some issues seen at Head acceptance tests:
```
----------
ID: mgr_deploy_tools_uyuni_key
Function: file.managed
Name: /etc/pki/rpm-gpg/uyuni-tools-gpg-pubkey-0d20833e.key
Result: false
Comment: Source file salt://gpg/uyuni-tools-gpg-pubkey-0d20833e.key not found in saltenv 'base'
Started: 13:57:27.009611
Duration: 2.696
SLS: channels.gpg-keys
Changed: {}
----------
```
No difference. …
> Include 'gpg' states and files as "ssh_extra_filerefs" to avoid issues on action chains for SSH minions

- susemanager-utils/susemanager-sls/src/states/mgrcompat.py
- susemanager-utils/susemanager-sls/src/tests/test_state_mgrcompat.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
On Salt 3005, the `module.run` state function was refactored and, it was finally decided upstream, that there is no deprecation of legacy syntax for `module.run` happening at all. Both syntax will be supported in future Salt versions.
(See NOTE at the beggining of https://docs.saltproject.io/en/latest/ref/states/all/salt.states.module.html)
In fact, after the refactor done by upstream on 3005 codebase for `module.run` (in order to support both syntaxes), if we tailor our parameters from the old syntax to the new syntax, this would cause issues in the execution of some functions.
Examples:
```
'docker.login' failed: login() got an unexpected keyword argument 'registries'
'cp.push' failed: push() got multiple values for argument 'path'
```
So, this PR simply fixes our custom …
> Fix custom "mgrcompat.module_run" state function to work with Salt 3005.1

- spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
- spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes
Test if postgres user exists can run command.
No difference. …
> uyuni-setup-reportdb: check postgres user (bsc#1205088)

- utils/spacewalk-common-channels.ini
Fix typo at SLL client tools devel channels, a `s` was missing, so the interpolation was failing.
No difference.
- No documentation needed: Internal code change
- No tests: already covered for 8 by the testsuite, for 9, manually.
Tracks https://github.com/SUSE/spacewalk/issues/20195
> Fix typo at SLL client tools devel channels

- susemanager-utils/susemanager-sls/salt/channels/gpg-keys.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This PR simply remove the usage of `unique` filter in our SLS files, as this is not compatible with old jinja2 versions we have in old Python 2.6 systems.
As we really want to prevent breaking compatibility here if possible, this PR simply refactors the template so the `unique` filter is not really needed.
No difference.
- No tests: **no checks for this atm**
Fixes # …
> Do not use non-compatible unique filter in old jinja2 (bsc#1206979) (bsc#1206981)

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/utils.py
The dateutil `parse` function parses as date/time stamps some strings that are not in ISO-8601 format which causes trouble in `api` calls in spacecmd when the user passes strings as parameters that are similar to dates (for example, to create a label).
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/19690 …
> Prevent api parameters parsing as dates if not in ISO-8601 (bsc#1205759)

- .github/workflows/susemanager-sls-compatible-python26-syntax.yml
This PR is introducing a new GitHub action to ensure we are not introducing new code which is not Python 2.6 compatible.
Even if Python 2.6 is EOL, we want to prevent breaking existing functionality for those old systems that might be running out there. This is why, we want to make the code for these custom Salt modules to be compatible with Python 2.6.
No difference.
- Added new tests via GitHub action.
Tracks  …
> Ensure custom Salt modules are still compatible with old Python 2.6

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
For now, SLL does not work with Uyuni, as it requires a SUSE Manager subscription, so we are removing the channels from spacewalk-common-channels.
SLL8 should be removed as well, but the testsuite is using it, so I will keep it for now.
No difference.
- PR TBD
- No tests: Removal
Tracks https://github.com/SUSE/spacewalk/issues/20195 …
> Remove SLL

- testsuite/features/build_validation/init_clients/monitoring_server.feature
- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/step_definitions/navigation_steps.rb
Adds another set of tests to validate Grafana working in the BV tests. 
Looks for each minion's section on the client dashboards and validates there's no graph without data.
Fixes https://github.com/SUSE/spacewalk/issues/19958
Ports:
- 4.2
- 4.3
> QE: Add further tests to grafana on BV

- testsuite/features/secondary/allcli_action_chain.feature
- testsuite/features/secondary/allcli_config_channel.feature
- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/allcli_software_channels_dependencies.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/secondary/min_baremetal_discovery.feature
- testsuite/features/secondary/min_cve_audit.feature
- testsuite/features/secondary/min_move_from_and_to_proxy.feature
- testsuite/features/secondary/min_retracted_patches.feature
- testsuite/features/secondary/min_salt_formulas.feature
- testsuite/features/secondary/srv_clone_channel_npn.feature
- testsuite/features/secondary/srv_group_union_intersection.feature
- testsuite/features/secondary/srv_maintenance_windows.feature
- testsuite/features/secondary/srv_power_management.feature
- testsuite/features/secondary/srv_power_management_redfish.feature
- testsuite/features/step_definitions/navigation_steps.rb
Fixes: https://github.com/SUSE/spacewalk/issues/20194
ATM this only occurs on 4.2 but we want to keep the test suite in sync. @srbarrios already confirmed that the logic behind the changed step works.
See Discussion in Slack: https://suse.slack.com/archives/C02D12TNYLS/p1674043102403269
No difference.
- Manager 4.3: 
- Manager 4.2:  …
> QE: Retracted patches: Remove Clear button click

- java/buildconf/LICENSE.txt
- java/code/src/com/redhat/rhn/domain/contentmgmt/FilterCriteria.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/modulemd/ModularityDisabledException.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/validation/ModularDependencyValidator.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/validation/test/ContentValidatorTestBase.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/validation/test/ModularDependencyValidatorTest.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/DependencyResolver.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/DependencyResolverTest.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/FilterApiController.java
- java/spacewalk-java.changes
- schema/spacewalk/common/tables/suseContentFilter.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.3-to-susemanager-schema-4.4.4/100-suseContentFilter-null-values.sql
- web/html/src/manager/content-management/list-filters/appstreams/appstreams.test.tsx
- web/html/src/manager/content-management/list-filters/appstreams/appstreams.tsx
- web/html/src/manager/content-management/list-filters/filter-form.tsx
- web/html/src/manager/content-management/shared/business/filters.enum.test.ts
- web/html/src/manager/content-management/shared/business/filters.enum.ts
- web/spacewalk-web.changes
In RHEL 9, the default streams of modules are now included as regular packages instead of modules. To allow users to set up CLM with all the default streams, we must allow creating of regular repositories without having to add any module filters.
This PR adds a new matcher type `none` to AppStream filters. When used, it strips the modular metadata from the channel without having to specify any modules.
See also: [Documentation PR (#2007)](https://github.com/uyuni-project/uyuni-docs/pull/2007)
Before:
After:
- [Documentation PR (#2007)](https://github.com/uyuni-project/uyuni-docs/pull/2007)
Fixes https://github.com/SUSE/spacewalk/issues/20032 …
> Add 'none' matcher for CLM module filters (bsc#1206817)

- susemanager-utils/susemanager-sls/modules/pillar/suma_minion.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- susemanager-utils/susemanager-sls/test/test_pillar_suma_minion.py
Prevents reopening DB connection on each pillar compile by storing DB connection in the `__context__`.
In large scale environments in case of massive oppertaions with the clients it could cause drop of the performance in case if it opens distinct connection to the DB for each request.
It requires passing `__context__` on the `salt` side, it will be implemented with distinct PR to `salt`.
Salt upstream PR required for this change to work as expected: https://github.com/saltstack/salt/pull/62898
Will backport it to `openSUSE/salt/release/3004` branch and put the link here also.
No difference.
Maybe just a note in the scaling section of the documentation as it requires extra distinct DB connection for each of salt-master workers.
Tracks …
> Optimize DB connections by using context for suma_minion pillar

- testsuite/run_sets/build_validation_add_common_channels.yml
CLM does not run for Alma and Oracle if they are not part of the run_set. This PR fixes that. 
No difference.
Fixes no issue, directly from testsuite review …
> Add Alma and Oracle CLM to run_set

- java/code/src/com/redhat/rhn/domain/channel/ReleaseChannelMap.java
- java/code/src/com/redhat/rhn/domain/org/usergroup/ExtGroup.java
Fixing package build
No difference.
Before:
After: …
> Remove @Nonnnull annotations as those don't build at packaging time

- susemanager-utils/susemanager-sls/src/grains/mgr_server.py
- susemanager-utils/susemanager-sls/src/tests/data/rhnconfdef.sample
- susemanager-utils/susemanager-sls/src/tests/test_grains_mgr_server.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Do not pass server related grains to minions.
The grains `is_uyuni` and `has_report_db` are evaluated by reading server configuration files entries. These configuration files are not available on common clients and the grains were always set to default values and of no use.
In case of missing server configuration files the grains `is_uyuni` and `has_report_db` are not being set now.
No difference.
- Existing tests updated
Fixes #SUSE/spacewalk#20145 …
> Do not pass server related grains to minions

- testsuite/features/secondary/min_salt_openscap_audit.feature
- testsuite/features/step_definitions/command_steps.rb
Use a profile coming from scap-security-guide package instead of a profile coming from openscap-content, so to follow our internal documentation https://documentation.suse.com/suma/4.3/en/pdf/suse_manager_administration_guide.pdf page 147
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/20139
Tracks #  …
> Use a profile coming from scap-security-guide

- testsuite/features/build_validation/add_custom_repositories/add_rocky8_repositories.feature
- testsuite/features/build_validation/add_custom_repositories/add_rocky9_repositories.feature
- testsuite/features/reposync/srv_add_rocky8_repositories.feature
With the changes from https://github.com/uyuni-project/uyuni/pull/6485, the "Matcher" field has multiple options to select from, therefore it's not preselected anymore. This PR selects the correct value as an extra step.
> Testsuite: Select 'matcher' value when adding AppStream filters in CLM

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes
Reposync fails for certain repos, because it tries to check the details of a content-type header that isn't present in those cases. This commit makes reposync treat urls with no content-type header as valid.
Fixes: https://github.com/uyuni-project/uyuni/issues/6298
No difference.
- No tests: I think the tests this really needs are integration tests, which are out of scope for now.
Fixes #6298 
If …
> Fix reposync content-type key bug

- testsuite/features/build_validation/init_clients/monitoring_server.feature
Adds validation of product name in Grafana's dashboard titles.
Fixes https://github.com/SUSE/spacewalk/issues/20142
- 4.2 https://github.com/SUSE/spacewalk/pull/20299
- 4.3 https://github.com/SUSE/spacewalk/pull/20298
> QE: Add right product name to Grafana dashboards

- testsuite/features/support/twopence_init.rb
This will now show the correct error if e.g. a wrong SSH key or no key at all is used. Before the wrong error `No hostname for ...` was shown which was not accurate and is misleading when debugging.
No difference.
- Manager 4.2: https://github.com/SUSE/spacewalk/pull/20310
- Manager 4.3: https://github.com/SUSE/spacewalk/pull/20309
- Fixes https://github.com/SUSE/spacewalk/issues/20296  …
> QE: Improve hostname/FQDN check in `twopence.rb`

- susemanager-utils/susemanager-sls/src/modules/mgractionchains.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Currently action chain check if there's chain to be restored, without prevent failure if recovery file does not exists. fix it.
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to …
> Prevent possible errors from "mgractionschains" module

- java/code/src/com/suse/manager/webui/services/SaltActionChainGeneratorService.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/spacewalk-java.changes
When an action chains is running, all the action are converted to a state file. In case of the transactional update system, the reboot action are removed and handle directly by the action chain logic. After this change https://github.com/uyuni-project/uyuni/commit/d658c32cd73c51df59e2d5f7da7fa78738268487 we need to identify the transactiona_update.reboot function as a reboot action.
No difference. …
> action chains: recognize transactional_update.reboot as a reboot action

- python/spacewalk/satellite_tools/download.py
Flaky download server produce `[Errno 14] curl#92 - "HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)"`. Give a second try using the same URL.
```
2023/01/21 16:14:39 +02:00 WARNING: Download failed: https://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Stable:/EL8-Uyuni-Client-Tools/EL_8/x86_64/libsodium-debugsource-1.0.18-2.34.uyuni.x86_6
4.rpm - [Errno 14] curl#92 - "HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)". Trying next mirror...
2023/01/21 16:14:39 +02:00     19/97 : libsodium-devel-1.0.18-2.34.uyuni.x86_64.rpm
2023/01/21 16:14:39 +02:00     20/97 : libsodium-debuginfo-1.0.18-2.34.uyuni.x86_64.rpm
2023/01/21 16:14:40 +02:00     21/97 : golang-github-wrouesnel-postgres_exporter-0.4.7-2.17.uyuni.x86_64.rpm
2023/01/21 16:14:40 +02:00 …
```
> on download errors try a 2nd time

- java/code/webapp/WEB-INF/pages/common/fragments/errata/relevant-errata-list.jspf
- java/spacewalk-java.changes
Makes the systems column on the relevant patch page sortable
This is a port of https://github.com/SUSE/spacewalk/pull/20289
After:
- No documentation needed:  the relevant patch docs do not mention anything about sortable columns
- No tests:  Just jsp changed, no unit tests and there are no cucumber tests testing sorting things. 
Fixes #13516
Needs to be ported to master …
> Makes the systems column on the relevant patch page sortable

- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
Some of our steps had too long timeouts without a good reason. Let's reduce them.
No difference.
Ports:
- Manager-4.2
- Manager-4.3
> QE: Reduced the timeout in some steps

- testsuite/Rakefile
If after 3min we still have some corrupted JSON report, we delete it and continue
Sorry to be a bit drastic here, but I prefer some report than nothing.
No difference.
- Cucumber tests were reffactored
Ports:
- Manager-4.2
- Manager-4.3
> If after 3min we still have some corrupted JSON report, we delete it and continue

- testsuite/features/core/srv_organization_credentials.feature
- testsuite/features/step_definitions/common_steps.rb
We had a wrong named step definition where we expected a value, using "it should", but in those cases we should not wait, as much as the time to load the DOM page.
It was the case of the SCC credentials validation. I refactored the step so now it's clear that we need to wait for the SCC credentials to be valid.
I set the timeout of 30 seconds.
No difference.
Ports:
- Manager-4.2
- Manager-4.3 …
> QE: Wait until the credentials are valid

- testsuite/Gemfile
Fix Rubocop 0.83.0 version in our Gemfile
No difference.
- No tests
Ports:
- Manager-4.2
- Manager-4.3
> Fix Rubocop 0.83.0 version in our Gemfile

- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes
Create repositories with SHA254 instead of SHA1. SHA1 is considered insecure. Enterprise Linux 9 also has it disabled.
Change credit to H. Hoffmann.
No difference.
> Create repos with SHA256 instead of SHA1

- containers/proxy-helm/proxy-helm.changes
- containers/proxy-helm/templates/config.yaml
- containers/proxy-httpd-image/proxy-httpd-image.changes
- containers/proxy-httpd-image/uyuni-configure.py
- containers/proxy-tftpd-image/proxy-tftpd-image.changes
- containers/proxy-tftpd-image/uyuni-configure.py
helm chart deployment fails when there is no `log_level` defined, which is the default with the generated tarball.
Set the default to `1` as in the `rhn.conf` defaults of the proxy WSGI scripts.
No difference.
- No tests: no automated tests for helm chart deployment.
Fixes #
If you need to …
> Default log_level value in proxy containers and helm chart to 1

- java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProjectFactory.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/test/ContentProjectFactoryTest.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/EnvironmentApiController.java
- java/spacewalk-java.changes
Display an error message when trying to delete a CLM environment if there are custom child channels not built through the environment.
No difference.
- No tests: existing tests adapted
Tracks https://github.com/SUSE/spacewalk/issues/20091
> Fix failing to delete CLM environment without error

- spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
- spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes
fix postgres user check
No difference.
- …
> fix postgres user check

- .gitignore
The cache directory for `obs-to-maven` (usually inside the `java` subfolder) should be ignored by git.
No difference.
- No tests needed.
No links.
> Ignore the .obs-to-maven-cache directory

- java/code/src/com/redhat/rhn/taskomatic/LogUtils.java
- java/code/src/com/redhat/rhn/taskomatic/task/ChannelRepodata.java
- java/code/src/com/redhat/rhn/taskomatic/task/ErrataCacheTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/ErrataQueue.java
- java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/RhnJavaJob.java
- java/code/src/com/redhat/rhn/taskomatic/task/RhnQueueJob.java
- java/code/src/com/redhat/rhn/taskomatic/task/SSHPush.java
- java/code/src/com/redhat/rhn/taskomatic/task/SystemOverviewUpdateQueue.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/RhnJavaJobTest.java
- java/spacewalk-java.changes
The current code was only configuring one appender, the log file never got anything and there where some race conditions with the files handling.
All the task configurations are applied on the main taskomatic log configuration, so we need to only touch what concerns the current task.
Creating a new logger out of the context with the changed configuration gets the data to the log files. And what's more: the log level can be changed in the /usr/share/rhn/classes/log4j2.xml file for the task, this will be taken into account at the next taskomatic start.
No difference.
- No tests: Log handling changes
Fixes https://github.com/SUSE/spacewalk/issues/20369 and https://github.com/SUSE/spacewalk/issues/20372
Tracks # **add …
> Fix the taskomatic log handling

- web/html/src/build/webpack.config.js
- web/html/src/package.json
- web/html/src/yarn.lock
Add a plugin to measure Webpack build times when needed.
No difference.
- No tests: Build tooling.
> Add speed measure plugin for Webpack

- java/code/src/com/redhat/rhn/common/security/acl/Access.java
- java/code/src/com/redhat/rhn/domain/server/Server.java
- java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
- java/code/src/com/redhat/rhn/domain/server/test/ServerFactoryTest.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- web/html/src/manager/content-management/shared/business/filters.enum.test.ts
- web/html/src/manager/content-management/shared/business/filters.enum.ts
- web/html/src/manager/minion/ptf/ptf-install.renderer.tsx
- web/html/src/manager/minion/ptf/ptf-list-remove.renderer.tsx
- web/html/src/manager/minion/ptf/ptf-overview.renderer.tsx
This PR fixes an issue where the wrong SLES version was used to check if the PTF uninstall feature was available. It also renames all the occurences of "Product Temporary Fixes" to the correct "Program Temporary Fixes (PTFs)" as used in the official documentation  (i.e. https://www.suse.com/support/kb/doc/?id=000018572)
No UI difference, just naming corrections
Project lotus documentation WIP …
> Additional PTFs fixes

- testsuite/features/step_definitions/common_steps.rb
This PR fixes a typo from https://github.com/uyuni-project/uyuni/pull/6533 that was rendering a step undefined.
No difference.
Fixes #
Tracks # No ports needed
> Testsuite: fix undefined workaround step

- testsuite/features/secondary/min_deblike_openscap_audit.feature
- testsuite/features/secondary/min_rhlike_openscap_audit.feature
- testsuite/features/secondary/min_salt_openscap_audit.feature
The link name for XCCDF results tends to change for some reason and needs to be adjusted in the testsuite - e.g. in https://github.com/SUSE/spacewalk/pull/20200 
To avoid adapting the testsuite every time, we can provide a partial name of the link to the testsuite that is common to the different possible names. 
Since only one result is available at a time, this PR won't create interference between Openscap features.
No difference.
Fixes #
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/20404
4.3 https://github.com/SUSE/spacewalk/pull/20405 …
> Testsuite: Shortening xccdf result link

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/redhat/rhn/domain/channel/test/ChannelFactoryTest.java
- java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
- java/spacewalk-java.changes
This PR implements an enhanced way of selecting recommended cloned vendor channels by taking into account common naming schemes. As long as every channel contains the original label plus some additional parts separated with - that are common across all related clones, they will be selected together.
There are a few improvements that can be made before merging this. I.e the initial selection of the base channel won't auto select any child channels since its shared and does not contain the common naming of every group of child channels it contains so its not possible to determine which group of child channels should be selected. However for the common base case where customers won't have multiple clones of the same child channel in one base channel it would be good if we detect that there …
> take common channel naming into account for auto selection

- web/html/src/components/ace-editor.tsx
Since Ace editor still relies on the global script being imported correctly, add a clearer error message to outline how to debug the issue.
No difference.
> Add clear error message for Ace editor

- web/html/src/manager/state/highstate.tsx
This PR remove wrong quoting added by mistake by commit https://github.com/uyuni-project/uyuni/commit/5349df95eaff8eda6fedd81ed973a86c72ace70f
Text message fixed
Before: `Applying the highstate has been 'scheduled'.`
After: `Applying the highstate has been scheduled.`
- No documentation needed: no functional changes. …
> Removed wrong quotes

- java/spacewalk-java.changes
- java/spacewalk-java.spec
- python/spacewalk/spacewalk-backend.changes
- python/spacewalk/spacewalk-backend.spec
- spacewalk/package/spacewalk.changes
- spacewalk/package/spacewalk.spec
- spacewalk/setup/spacewalk-setup.changes
- spacewalk/setup/spacewalk-setup.spec
Specify the required cobbler version at a single place: patterns, so we have a single place to change when we need a new cobbler version, and so we lower the risk of conflicts with PackageHub, as discussed at https://github.com/SUSE/spacewalk/issues/19497 with Marina, and at Slack with Pablo.
**WARNING: To be merged with the SR https://build.opensuse.org/request/show/1064014!**
No difference.
- No documentation needed: Internal change
- No tests: Installation and acceptance tests will test it.
Partial fix for https://github.com/SUSE/spacewalk/issues/19497 (will require backporting to SUSE Manager 4.3) …
> Specify the required cobbler version at a single place: patterns

- testsuite/features/step_definitions/setup_steps.rb
This PR restores a step whose definition was lost in another PR.
No difference.
Fixes #
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/20426
> Testsuite: Restore SCC credentials step

- java/code/src/com/redhat/rhn/common/hibernate/HibernateFactory.java
- java/code/src/com/redhat/rhn/domain/action/ActionFactory.java
- java/code/src/com/redhat/rhn/domain/action/Action_legacyUser.hbm.xml
- java/code/src/com/redhat/rhn/domain/action/server/test/ServerActionTest.java
- java/code/src/com/redhat/rhn/domain/action/test/ActionFactoryTest.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/taskomatic/task/MinionActionChainExecutor.java
- java/code/src/com/redhat/rhn/taskomatic/task/MinionActionExecutor.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/MinionActionChainExecutorTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/MinionActionExecutorTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/SubscribeChannelsActionTest.java
- java/code/src/com/redhat/rhn/testing/MockObjectTestCase.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/spacewalk-java.changes
- python/test/unit/spacewalk/satellite_tools/test_download.py
This PR changes the behaviour when dealing with actions that have an earliest execution date older than 24 hours:
- it makes possible to reschedule these old failed actions. The action earliest date is now updated on rescheduling and that will allow the job to always pick them up;
- when an action is too old to be executed, it is now set as failed with an explanatory error message.
No difference.
- No documentation needed: improvements on existing documented functionality.
Fixes https://github.com/SUSE/spacewalk/issues/19965
If you don't need …
> Reschedule old failed action

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/softwarechannel.py
- spacecmd/tests/test_softwarechannel.py
spacecmd commands `softwarechannel_diff` and `softwarechannel_errata_diff` were not showing any output. Now they print the result of the diff properly.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/20279 …
> Fix spacecmd output for softwarechannel diffs (bsc#1207352)

- testsuite/features/step_definitions/command_steps.rb
Maxime reported issues with this step and indeed using `check_errors = true` together with a `raise` in the next line that checks for the return code of the command above it, will not work. So I partially revert what I changed with https://github.com/uyuni-project/uyuni/pull/6448
No difference.
If you …
> QE: Revert reposync error checking to old behavior

- susemanager-utils/susemanager-sls/salt/channels/disablelocalrepos.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Reverts https://github.com/uyuni-project/uyuni/pull/6601 until we properly test it with multiple distros.
Related: https://github.com/SUSE/spacewalk/issues/20349
> Revert "Fix missing module when bootstraping transactional systems"

- susemanager-utils/susemanager-sls/src/modules/mgractionchains.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Now that reboot in SLE Micro works as expected, we can remove the `activate_transaction=true` workaround and run `transactional_update.reboot` outside the main transaction when the action chain contains a reboot command
LIMITATION:
`transactional_update.reboot` does not have the option `at_time` as `system.reboot`: this mean that the reboot is executed immediately, instead of after 3 minutes. This cause some issue on the visualization. Let's take an action chains with:
- package installation
- reboot
- package installation
- reboot
The action chain is executed correctly, but `System History` shows that these execution order (first action in the list is the first executed):
- package installation
- package installation
- reboot
- reboot
This happen because the time between the two reboot …
> Use transactional_update.reboot to reboot SLE Micro in an Action Chain

- java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/EnvironmentResponse.java
- java/spacewalk-java.changes
- web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-view.tsx
- web/html/src/manager/content-management/shared/components/panels/promote/promote.tsx
- web/html/src/manager/content-management/shared/type/project.type.ts
- web/spacewalk-web.changes
Dots in `id` attributes in DOM cause modal buttons to fail when targeting respective modals. A dot is a valid character in CLM project environment labels, so this PR avoids using environment labels in modal IDs and uses environment IDs instead.
See: https://bugzilla.suse.com/show_bug.cgi?id=1207838
Port of: https://github.com/SUSE/spacewalk/pull/20375 …
> Avoid using env labels containing dots in modal IDs in CLM (bsc#1207838)

- .github/workflows/susemanager-sls-compatible-python26-syntax.yml
- susemanager-utils/susemanager-sls/src/modules/mgrnet.py
- susemanager-utils/susemanager-sls/src/tests/test_module_mgrnet.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This is a spin-off PR from https://github.com/uyuni-project/uyuni/pull/6464 that fixes the issues raised by new introduced GH action to check we are not introducing non-compatible Python 2.6 code in our custom Salt modules provided by `susemanager-sls` package.
**UPDATE**: this PR additionally adapts `mgrnet` code to be compatible with old Salt 2016.11.10.
No difference.
Fixes #
Tracks https://github.com/SUSE/spacewalk/issues/20270 …
> Fix non-compatible Python 2.6 syntax in custom Salt modules (bsc#1206979) (bsc#1206981)

- proxy/proxy/apacheHandler.py
- proxy/proxy/apacheServer.py
- proxy/proxy/broker/rhnBroker.py
- proxy/proxy/rhnShared.py
- proxy/proxy/spacewalk-proxy.changes
This PR just increased the debug level for some messages that are causing lot of unnecessary noise in proxy backend logs files without bringing any valueable information at all. Keep in mind that default log level for rhn backend is `1`.
In some environments, this is causing the logs files to grow massively:
```
2022/12/21 00:24:45 +02:00 27790 XXXXXXXXXXX: broker/rhnBroker.handler
2022/12/21 00:24:45 +02:00 27790 XXXXXXXXXXX: proxy/rhnShared._serverCommo
2022/12/21 00:24:45 +02:00 27790 XXXXXXXXXXX: broker/rhnBroker.__handleAction
2022/12/21 00:24:45 +02:00 27790 XXXXXXXXXXX: proxy/rhnShared._clientCommo
2022/12/21 00:24:45 +02:00 27790 XXXXXXXXXXX: proxy/rhnShared._forwardServer2Client
2022/12/21 00:24:45 +02:00 27790 XXXXXXXXXXX: proxy/apacheHandler.handler('Leaving with status code …
```
> Avoid unnecessary debug messages from proxy backend (bsc#1207490)

- testsuite/features/step_definitions/api_common.rb
Fix name of Rocky 8 custom channel from CLM.
Ports:
* 4.2: https://github.com/SUSE/spacewalk/pull/20479
* 4.3: https://github.com/SUSE/spacewalk/pull/20480
> Correct name for Rocky 8 custom channel from CLM

- testsuite/features/step_definitions/api_common.rb
Revert in branches uyuni and 4.3 of previous PR.
Adjustment in branch 4.2.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/20481
* 4.2: https://github.com/SUSE/spacewalk/pull/20482
> Name of CLM results differs according to branch

- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/upload_files/salt_event_parser.py
The salt error detection was faulty, this PR aims to correct the detection script and exclude the detection of an expected error caused by `min_salt_lock_packages.feature`
We want to ignore the salt failure caused by `Feature: Lock packages on SLES salt minion`
Errors such as 
```
salt/auth       {
"_stamp": "2023-01-20T17:25:25.501308",
"id": "suma-pr4-min-sles15.mgr.prv.suse.net",
"pub": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwEB5emvXG+Db7IuywF0X\njla8N0SopuNZaxNelEpsPucGspjPtuwI0wX60pQunj8bTxeb6krWdUy0sJiOB0Ne\nCkoLRSejQ2y+RtrsVSRGyf34Y9UIR/N/xLSWBF6l1V7zhocbbwHpoCAWbw3A8C1v\neVABiXI5rrQCT11+QJJMsCiAuSiRSHWh8+rB3edl615LjH4VZqDao3I88dRN+vEv\n1Sr5SgJ0KPQAa+8YYFHt+PVSVgAKHbJnIn5kdX6M/Zzhhkt+VyeCLjgpdeDr88Fn\nW+TmfZtymrWofGfm0XhPyrJZtRQ+Ow8Zz09gRRMyvO2QkrKD …
```
> QE: Adjust server salt error detection

- java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java
- java/spacewalk-java.changes
This fixes a NumberFormatException when importing ubuntu errata with a different format.
No difference.
- No tests: manually verified
Fixes #https://github.com/SUSE/spacewalk/issues/20337
Fixes https://github.com/uyuni-project/uyuni/issues/6534
> handle ubuntu advisory ids with USN prefix (bsc#1207883)

- testsuite/features/secondary/min_deblike_openscap_audit.feature
Reverts uyuni-project/uyuni#6376
Workaround for [1206586](https://bugzilla.suse.com/show_bug.cgi?id=1206586) (Ubuntu 22.04 OpenScap support)
Card in our board to revert the workaround when the issue is fixed  (Blocked as it's an issue external from SUMA team) https://github.com/SUSE/spacewalk/issues/19955
No difference.
- Cucumber tests were workarounded
- Uyuni https://github.com/uyuni-project/uyuni/pull/6376 …
> Revert "QE: Workaround for 1206586 (Ubuntu 22.04 OpenScap support)"

- java/code/src/com/suse/manager/webui/controllers/ProductsController.java
- java/spacewalk-java.changes
- web/html/src/manager/admin/setup/products/products.tsx
- web/spacewalk-web.changes
Add the ability to add optional channels to sync through the webUI on installed products.
Before: 
After:
Issue: https://github.com/uyuni-project/uyuni-docs/pull/2066
- No tests: 
Tracks https://github.com/SUSE/spacewalk/issues/18966
> Add support to add optional channels in webUI

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Add openSUSE Leap 15.5 as a supported client to Uyuni
No difference.
- Documentation issue was created: https://github.com/uyuni-project/uyuni-docs/issues/2028
No links
> Add openSUSE Leap 15.5 support

- testsuite/features/step_definitions/common_steps.rb
The id of `Promote` buttons on the Conten Lifceycle Project page have been changed to use the environment ID instead of their labels. Since the ids are not necessarily pre-determined, we can search and click on the buttons in their order of appearance instead.
Needed after https://github.com/SUSE/spacewalk/pull/20376
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/20501
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/20505
4.3 https://github.com/SUSE/spacewalk/pull/20506 …
> Testsuite: Change the way buttons are found in content lifecycle feature

- java/code/src/com/redhat/rhn/taskomatic/domain/TaskoRun.hbm.xml
- schema/spacewalk/common/tables/rhnTaskoRun.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.4-to-susemanager-schema-4.4.5/020-taskorun-paths-removal.sql
Fix for https://github.com/uyuni-project/uyuni/pull/6611 missing hibernate mapping change.
No difference.
Fixes #
> Remove the /var/log/rhn/tasko/* files: DB changes

- java/code/src/com/redhat/rhn/domain/channel/Channel.hbm.xml
- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java
- java/spacewalk-java.changes
Refactor the `UbuntuErrataManager` to consume less memory.
No difference.
- No tests: Would require performance tests
Fixes https://github.com/SUSE/spacewalk/issues/19718
> Taskomatic memory improvements

- java/code/src/com/redhat/rhn/manager/action/ActionChainManager.java
- java/spacewalk-java.changes
This fixes handling of taskomatic failures.
`ActionChainManager::scheduleActions` creates an action, saves it to DB (in `ActionManager.createAction`) and calls takomatic API to schedule it.
The caller method (for example `ActionChainManager::scheduleApplyStates`) then adds `ActionDetails`.
If the taskomatic API fails with an exception, it leaves the action as is. It means that it is pending forever and clicking on details fails with NPE.
This PR makes sure that the action is fully created before calling taskomatic API and sets status to FAILED if there is taskomatic error. 
No difference.
- Cucumber tests: WIP
Part of fix for https://github.com/SUSE/spacewalk/issues/20143 …
> Handle taskomatic failures during action creation

- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/reactor/messaging/test/packages.profileupdate.livepatching.json
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/webui/utils/salt/custom/PkgProfileUpdateSlsResult.java
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/salt/packages/profileupdate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
A Package Profile Update should also report and handle the uptime of the system.
In case the salt start event gets lost, it is currently not possible to update this value with an action.
As the kernel live version and grains are also handled in pkgprofile update, it makes sense to send and update the uptime as well.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/20537 …
> get uptime with package profile update

- java/code/src/com/redhat/rhn/taskomatic/task/DailySummary.java
- java/spacewalk-java.changes
This might get send as email and could be very annoying as there is no chance to prevent it
Port of https://github.com/SUSE/spacewalk/pull/20538
> report subscription warnings via notification only on mondays

- testsuite/features/step_definitions/common_steps.rb
This will fix the reboot through webUI step in Ruby. Fixup of https://github.com/uyuni-project/uyuni/pull/5723
Tested on the 4.3 BV e.g. for Debian 11:
```bash
Scenario: Reboot the debian11_minion and wait until reboot is completed # features/build_validation/smoke_tests/debian11_minion_smoke_tests.feature:156
This scenario ran at: 2023-02-22 11:52:03 +0100
And I reboot the "debian11_minion" minion through the web UI          # features/step_definitions/common_steps.rb:549
2023-02-22 11:54:59 +0100 Still waiting for action to complete...        
This scenario took: 222 seconds 
2 scenarios (2 passed)
2 steps (2 passed)
3m46.725s
```
No difference.
- No documentation needed: only internal and user …
> QE: fix the reboot through webUI steps

- testsuite/features/init_clients/allcli_update_activationkeys.feature
- testsuite/features/step_definitions/setup_steps.rb
This fixs Uyuni CI flaky test, when we expect an auto-selection from SUSE Manager of some channels, but this is not immediate.
Wait 5 seconds when checking if a checkbox is marked
No difference.
Ports:
- Manager-4.2
- Manager-4.3 …
> QE: Wait 5 seconds when checking if a checkbox is marked

- .github/scripts/test_covering_pr.js
- .github/workflows/test-covering-pr.yml
- testsuite/Gemfile
- testsuite/features/support/code_coverage.rb
- testsuite/features/support/env.rb
- testsuite/features/support/twopence_init.rb
This PR add a new functionality to our test framework.
If a flag in the environment variable is enabled, it will produce code coverage in the Java server using Jacoco.
1. It will generate a report once each test feature finish, and flush the cove coverage triggered to have new metrics on next test feature.
2. Also, once a feature finish and we have the code coverage report, we parse the XML report using Nokogiri and we push the results to a Redis database instance that is configurable by environment variables in our controller.
1. Finally, this PR includes a new GitHub Action that will suggest as a comment in all new PRs opened, which are the Cucumber tests that will cover the product changes.
**Note**:
Before merging this PR, I will revert a commit including a change in …
> PoC: Push code coverage from each feature into a Redis DB

- README.md
This patch is simply adding the openssf badge to the project README file, referencing this page: https://bestpractices.coreinfrastructure.org/en/projects/6593.
No difference.
- No tests needed.
No links.
> Add openssf best practices badge to README

- .github/workflows/test-covering-pr.yml
Tweak the GitHub action test-covering-pr as apparently it only need one target, and must be the one that have access to write comments from a fork.
Note: That was already warned by @renner I could not see any issue when I was working in the PR, as I was not in a fork.
It seems `pull_request_target` will work for both scenarios.
No difference.
- No tests
No ports.
If you need …
> Tweak GitHub action for tests covering pr

- testsuite/features/build_validation/retail/sle12sp5_buildhost_build_kiwi_image.feature
- testsuite/features/build_validation/retail/sle15sp4_buildhost_build_kiwi_image.feature
- testsuite/features/init_clients/buildhost_bootstrap.feature
- testsuite/features/step_definitions/api_common.rb
- testsuite/features/support/namespaces/activationkey.rb
Instead of transforming a bootstrapped minion into a buildhost, we change the SLE activation key before bootstrapping to have the minion bootstrapped as a buildhost directly.
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/13736
Tracks #
4.2 https://github.com/SUSE/spacewalk/pull/20618
4.3 https://github.com/SUSE/spacewalk/pull/20619 …
> QE: Enable buildhost options in Activation Key for buildhost minion

- java/code/src/com/suse/manager/webui/utils/ViewHelper.java
- java/code/webapp/WEB-INF/decorators/layout_head.jsp
Adds base for selective stylesheet loading that enables us to upgrade Bootstrap page by page.
No difference.
- No tests: not a real feature
Fixes https://github.com/SUSE/spacewalk/issues/18942
> Enable selective loading of stylesheets for Bootstrap upgrade

- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/suse/manager/api/RouteFactory.java
- java/code/src/com/suse/manager/api/test/RouteFactoryTest.java
- java/spacewalk-java.changes
When the parameters are passed via the query string, a single value is always interpreted as a primitive, even if the method expects an array. This PR adds logic to wrap those single values in a List to satisfy the method signature.
See: https://bugzilla.suse.com/show_bug.cgi?id=1207297
The API method:
```
myMethod(User user, List<Integer> sids);
```
The calls:
```
$ curl $API/test/myMethod?sids=101&sids=102
{ "success": true }
$ curl $API/test/myMethod?sids=101
No method exists with the matching parameters
```
Fixes https://github.com/SUSE/spacewalk/issues/20245 …
> HTTP API: Allow single-value lists in query strings (bsc#1207297)

- java/code/src/com/redhat/rhn/frontend/xmlrpc/systemgroup/ServerGroupHandler.java
- java/spacewalk-java.changes
Fix API method 'systemgroup.listSystemsMinimal' to be read-only.
Port of: https://github.com/SUSE/spacewalk/pull/20567
> Make API method 'systemgroup.listSystemsMinimal' read-only (bsc#1208550)

- testsuite/features/init_clients/allcli_update_activationkeys.feature
When updating the activation key with child channels, wait for channels that should be automatically selected to appear as checked before checking other channels.
No difference.
Fixes #
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/20662
4.3 https://github.com/SUSE/spacewalk/pull/20661
If you need …
> Teststuite: Wait for expected channels to be checked before checking other channels

- java/buildconf/apidoc/asciidoc/scripts.txt
- java/buildconf/apidoc/docbook/scripts.txt
- java/buildconf/apidoc/html/scripts.txt
- java/buildconf/apidoc/jsp/scripts.txt
- java/buildconf/apidoc/singlepage/scripts.txt
Python2 XML-RPC API call example shows how to use datetime parameters.
This PR adds similar example to python3  section.
https://bugzilla.suse.com/show_bug.cgi?id=1205981 shows, that this example is needed.
https://github.com/SUSE/spacewalk/issues/19814
https://bugzilla.suse.com/show_bug.cgi?id=1205981 …
> Add python3 XML-RPC datetime example

- java/code/src/com/redhat/rhn/manager/kickstart/KickstartOptionsCommand.java
- java/spacewalk-java.changes
RHEL9 doesn't support the kickstart `install` option. Hide it from the details UI.
Option hidden.
- No documentation needed: Kickstarts are not documented
- No tests: Kickstarts are not auto tested
Fixes https://github.com/uyuni-project/uyuni/issues/5513
> Hide the install option for RHEL9 kickstart installs

- web/html/src/branding/css/base/theme.less
- web/html/src/branding/css/susemanager/components/tables.less
- web/html/src/components/table/SearchField.tsx
- web/html/src/components/table/SearchPanel.tsx
- web/spacewalk-web.changes
Fix header color bug, make search box layouts flow similar to Uyuni theme.
Before:
After:
- No documentation needed: Bugfixes, no feature changes.
Fixes https://github.com/SUSE/spacewalk/issues/19738
> Fix UI bugs in susemanager-light and susemanager-dark theme

- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/step_definitions/cobbler_steps.rb
- tftpsync/susemanager-tftpsync/configure-tftpsync.sh
- tftpsync/susemanager-tftpsync/susemanager-tftpsync.changes
This PR fixes a problem in the logic to remove the `proxies` section from Cobbler settings, at the time of running `configure-tftpsync.sh` script.
Before this PR, the logic to remove the `proxies` logic was buggy and it could go beyond expections, so ending up removing any other possible list item after the `proxies` section. In particular, we see this happening and removing items for `webdir_whitelist` and making Cobbler settings invalid.
This issue seems only visible in long running server, where Cobbler settings migration was executed at some point (making `proxies` section not being the latest one defined on the Cobbler settings file).
No difference.
Tracks …
> Fix "configure-tftpsync.sh" to not remove "webdir_whitelist" list values from Cobbler settings (bsc#1207063)

- python/uyuni/common/context_managers.py
- python/uyuni/uyuni-common-libs.changes
Allow default component for context manager in case no component is declared when using the context manager.
No difference.
> Allow default component for context manager

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/spacewalk-java.changes
Merged in manager Port of https://github.com/SUSE/spacewalk/pull/20660
#20126 
Adds some missing strings from the user preferences page
Before:
After:
- No tests: 
Fixes #
> Adds some missing strings from the user preferences page 

- containers/proxy-tftpd-image/proxy-tftpd-image.changes
- containers/proxy-tftpd-image/tftp_wrapper.py
TFTP server on containerized proxy did not differentiate between missing file and empty file.
Grub tries multiple menu files and uses the first existing. With this bug it ended up with empty menu. 
No difference.
- No tests
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1208624 …
> Fix handling of http 404 (bsc#1208624)

- java/code/src/com/suse/manager/saltboot/PXEEvent.java
- java/code/src/com/suse/manager/saltboot/SaltbootUtils.java
- java/code/src/com/suse/manager/saltboot/test/PXEEventTest.java
- java/spacewalk-java.changes
Pxe event parsing was broken.
This PR fixes it, updates unit tests and adds logging.
No difference.
- Unit tests fixed
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1208661
> Fix cobbler system entries for retail terminals - bsc#1208661

- testsuite/Rakefile
Create repository bootstrap during BV for monitoring server.
> Add server monitoring support

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Remove non-salt-bundle packages from repositories for SLE12, CentOS7 and clones
I ran some tests
No extra packages are needed:
```
[ec2-user@ip-172-31-44-109 ~]$ sudo su -
[root@myinstance ~]# rpm -i venv-salt-minion-3004-15.1.uyuni.x86_64.rpm 
warning: venv-salt-minion-3004-15.1.uyuni.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 0d20833e: NOKEY
```
No extra packages are needed:
```
[root@n223 ~]# rpm -i venv-salt-minion-3004-15.1.uyuni.x86_64.rpm 
advertencia:venv-salt-minion-3004-15.1.uyuni.x86_64.rpm: EncabezadoV3 RSA/SHA256 Signature, ID de clave 0d20833e: NOKEY
```
No difference.
- No documentation needed: Transparent for the user, as now they will be bootstrapping with the bundle
- No tests: Removing support
Fix for #6693 and https://github.com/SUSE/spacewalk/issues/20682 …
> Remove non-salt-bundle packages from repositories for SLE12, CentOS7 and clones

- susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes
- susemanager-utils/supportutils-plugin-susemanager/susemanager-connection-check.pl
Port of https://github.com/SUSE/spacewalk/pull/20690
Fix connection check tool as the calculation was not correct.
No difference.
Documentation PR was created: uyuni-project/uyuni-docs#2111
Tracks https://github.com/SUSE/spacewalk/pull/20691
> fix db connection check tool

- testsuite/features/build_validation/init_clients/slemicro52_minion.feature
- testsuite/features/build_validation/init_clients/slemicro53_minion.feature
The reboot of SLE Micro has to be the first thing after being onboarded, otherwise we cannot check events. The step
`I wait until onboarding is completed for ...` contains of several sub steps that can only be successful executed after SLE Micro gets rebooted.
The SSH minions behave differently and need no adaption.
No difference.
Manager 4.3:  …
> Fix SLE Micro init clients in BV

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/spacewalk-backend.changes
- python/test/unit/spacewalk/satellite_tools/test_reposync.py
- python/test/unit/spacewalk/satellite_tools/test_yum_src.py
This PR fixes some problems detected on "reposync" during kickstart files syncing:
- Fix issues with syncing from repository using mirrorlist
- Do not sync unnecessary and flaky files from "download.opensuse.org", i.a. Leap 15.4 repos, where it downloads tons of `.mirrorlist` and `#` files that are wrongly parsed from the HTML.
Before:
```console
...
08:46:04 
08:46:04   Importing kickstarts.
08:46:04 Trying treeinfo
08:46:04 Trying .treeinfo
08:46:04     Kickstartable tree not detected (no valid treeinfo file)
08:46:04 Sync completed.
08:46:04 Total time: 0:00:07
```
After:
```console
...
14:37:00 +02:00 
14:37:00 +02:00   Importing kickstarts.
14:37:00 +02:00     Added new kickstartable tree External_-_AlmaLinux_8_x86_64. Downloading content...
14:37:00 +02:00     Gathering all files in …
```
> Fix some problems with reposync kickstart files syncing

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/package.py
- spacecmd/tests/test_package.py
This PR fixes an issue in `spacecmd` that makes the targetted packages summary to be displayed in the console AFTER the user confirmation, instead of before to double check the action is going to perform what the user is expecting.
- Before this PR, the summary of packages is wrongly displayed AFTER the user confirmation:
```console
spacecmd {SSM:0}> package_remove zypper-log-*
Remove these packages [y/N]: n
Packages
--------
zypper-log-1.14.52-150400.1.9.noarch
zypper-log-1.14.53-150400.3.3.1.noarch
zypper-log-1.14.55-150400.3.6.1.noarch
zypper-log-1.14.57-150400.3.9.1.noarch
No packages has been removed
```
- After this PR, the summary is displayed BEFORE the user confirmation:
```console
spacecmd {SSM:0}> package_remove zypper-log-*
Packages
-------- …
```
> spacecmd: show packages before removing them (bsc#1207830)

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/step_definitions/command_steps.rb
This will refactor the necessary reboot steps for SLE Micro in our build validation smoke test template file. Thank you @Bischoff for doing this together with me.
No difference.
- Manager 4.3:  …
> QE: Refactor smoke test template for SLE Micro

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/step_definitions/command_steps.rb
Ignore errors when installing or removing tftpboot-installation on the server
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/19993
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/20730
4.3 https://github.com/SUSE/spacewalk/pull/20729 …
> Testsuite: tftpboot-installation cleanup

- testsuite/.rubocop_todo.yml
- testsuite/features/build_validation/init_clients/oracle9_minion.feature
- testsuite/features/build_validation/init_clients/oracle9_ssh_minion.feature
- testsuite/features/step_definitions/command_steps.rb
Adds the ports needed for monitoring to the Oracle minions' firewall permissions.
- 4.3 https://github.com/SUSE/spacewalk/pull/20731
> QE: Add monitoring ports to firewall for oracle minions

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes
Port of https://github.com/SUSE/spacewalk/pull/20721
The cloud infrastructure seems to forbid requests for a while when the authentication failed.
(maybe a DOS prevention?)
The wrong request to detect a mirror list caused failing download of metadata even with correct credentials.
This PR send now the required headers to authenticate successful against the cloud infrastructure.
No difference.
If you uncheck …
> send http headers with additional auth data on the mirrorlist request

- testsuite/features/step_definitions/api_common.rb
- testsuite/features/support/constants.rb
This PR fixes definitions for SLL 9: custom reporitory and base channel label.
Ports:
* 4.2: N/A
* 4.3: https://github.com/SUSE/spacewalk/pull/20746
> Fix testing of SLL 9

- testsuite/run_sets/secondary.yml
A spelling error causes the CI to skip the features in `secondary.yml` to be skipped.
This PR fixes it
Related to https://github.com/uyuni-project/uyuni/pull/6628
No difference.
Fixes #
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/20757 …
> Testsuite: Correct name of called feature

- .github/workflows/automatic-frontend-lint-fix-pr.yml
- .github/workflows/frontend-dependency-audit.yml
- .github/workflows/frontend-lint.yml
- .github/workflows/javascript-build.yml
- .github/workflows/javascript-unit-tests.yml
- .github/workflows/typescript-compilation.yml
Since Node 14 is [soon to be EOL](https://github.com/nodejs/release#release-schedule), bump Node to 16 for GH actions.
No difference.
- No tests: GH actions only
Fixes https://github.com/SUSE/spacewalk/issues/20578
> Bump Node version to 16 for GH actions

- testsuite/features/secondary/srv_content_lifecycle.feature
With the removal of the recommended child channels in the Content Lifecycle project feature (which did not have any impact on the feature) the code for Uyuni and SUMA are now identical.
This PR removes the present redundancy from this feature.
N.B. the differences between products on Uyuni branch are from an un-ported PR (https://github.com/SUSE/spacewalk/pull/20749)
No difference.
Fixes #
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/20762
4.3 https://github.com/SUSE/spacewalk/pull/20761
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-p …
> CLM feature: Remove separation between SUMA and Uyuni

- spacecmd/spacecmd.changes
- spacecmd/src/spacecmd/activationkey.py
- spacecmd/tests/test_activationkey.py
Fix the `spacecmd activationkey_details <key>` command showing the key details only in the debug mode with the `-d` flag set. 
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/20615 …
> fix not showing details

- testsuite/features/build_validation/init_clients/liberty9_minion.feature
- testsuite/features/build_validation/init_clients/liberty9_ssh_minion.feature
Adds the ports needed for monitoring to the Liberty Linux minions' firewall permissions.
- 4.3 https://github.com/SUSE/spacewalk/pull/20766
> QE: Add ports to firewall for monitoring on liberty linux

- java/code/src/com/redhat/rhn/common/security/acl/test/AccessTest.java
- java/code/src/com/redhat/rhn/domain/channel/Channel.hbm.xml
- java/code/src/com/redhat/rhn/domain/channel/Channel.java
- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/redhat/rhn/domain/channel/Modules.java
- java/code/src/com/redhat/rhn/domain/channel/RepoMetadata.hbm.xml
- java/code/src/com/redhat/rhn/domain/channel/RepoMetadata.java
- java/code/src/com/redhat/rhn/domain/channel/test/ChannelFactoryTest.java
- java/code/src/com/redhat/rhn/domain/channel/test/ChannelTest.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/ContentFilter.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/ModularPackageFilter.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/modulemd/ModulemdApi.java
- java/code/src/com/redhat/rhn/frontend/action/common/DownloadFile.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/channel/CloneChannelCommand.java
- java/code/src/com/redhat/rhn/manager/channel/test/CloneChannelCommandTest.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/DependencyResolver.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerTest.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/DependencyResolverTest.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/MockModulemdApi.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/RpmRepositoryWriter.java
- java/code/src/com/suse/manager/webui/controllers/DownloadController.java
- java/code/src/com/suse/manager/webui/controllers/test/DownloadControllerTest.java
- java/spacewalk-java.changes
- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/spacewalk-backend.changes
- schema/spacewalk/common/tables/rhnChannelComps.sql
- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.5-to-susemanager-schema-4.4.6/001-rhnChannelComps-revert_drop_uidx.sql
I recently discovered that a corrupt module metadata file was served by the vendor a few months ago. This file has been replaced the next day. But Uyuni keeps all mirrored metadata and calculates modular filtering using data from all of them. Because of this, CLM AppStream filtering has stopped working ever since for all instances that mirrored this invalid file. Simply discarding the corrupt file is not feasible either, because that means some packages that are unique in that file would leak into the target repositories.
This patch introduces a much simpler way of filtering out modular packages by relying on a keyword (`module`) in their release strings. With this improvement, archiving older metadata files is not necessary anymore.
``` …
```
> Filter modular packages using release strings (bsc#1207814)

- testsuite/features/support/env.rb
Update chrome driver option to download correctly in /tmp/download the files during the testsuite
Issue : https://github.com/SUSE/spacewalk/issues/20526
> Update download option from chrome to fix salt_action feature

- java/code/src/com/redhat/rhn/domain/notification/types/SubscriptionWarning.java
- java/code/src/com/redhat/rhn/domain/notification/types/test/SubscriptionWarningTest.java
- java/spacewalk-java.changes
Prevents null values in the `summary` and `details` fields of subscription warning notifications that cause the notifications page to crash.
Port of: https://github.com/SUSE/spacewalk/pull/20772
> Fix rendering of notifications page with subscription warnings (bsc#1209259)

- testsuite/features/support/twopence_init.rb
Removes a leftover regarding the traditional clients. We do not use them in Uyuni/HEAD anymore. I found it during a PR CI test:
```bash
16:00:27  Capybara APP Host: https://suma-pr8-srv.mgr.prv.suse.net:8888/
16:00:27  Client IP address or domain name variable empty
16:00:27  Host 'suma-pr8-ctl' is alive with determined hostname suma-pr8-ctl and FQDN suma-pr8-ctl.mgr.prv.suse.net
```
No difference.
No ports! …
> QE: Remove leftover traditional client code

- java/code/src/com/suse/manager/webui/websocket/Notification.java
- java/spacewalk-java.changes
Notification manager had several lock mechanisms to control concurrent access to websocket sessions.
They had a circular dependency between the Object lock and getting a database connection. This code change aims to remove this circular dependency and reduce the number of locks that can block execution.
No difference. Just internal processing only, related to thread management.
- No documentation needed: Just internal processing only, related to thread management.
- No tests: This problem emerged in the BV test environment. Developing tests for this case is impossible since it depends on thread execution order, which we cannot control.
Fixes https://github.com/SUSE/spacewalk/issues/20790
Tracks https://github.com/SUSE/spacewalk/pull/20800 …
> Refactor Java notification synchronize to avoid dead locks (bsc#1209369)

- search-server/spacewalk-search/spacewalk-search.changes
- search-server/spacewalk-search/src/config/com/redhat/satellite/search/db/config.xml
- search-server/spacewalk-search/src/config/search/rhn_search.conf
Port of https://github.com/SUSE/spacewalk/pull/20628
Adds a adjustable option for c3p0 pool size in search
#16057 
No difference.
- No documentation needed:  no docs for these
- No tests: 
Fixes #
> Adds a adjustable option for c3p0 maxPoolSize in search

- testsuite/features/support/commonlib.rb
4.2 now uses the salt-bundle in most of its operations. This causes issues on certain features that are salt dependent (e.g [bootstrapping with a script with or without salt-bundle](https://github.com/SUSE/spacewalk/blob/Manager-4.3/testsuite/features/step_definitions/file_management_steps.rb#L50))
This PR adds 4.2 to the list of products to enable salt-bundle use.
No difference.
Fixes #
Tracks # 
4.3
4.2
If …
> QE: Include 4.2 in the list of products that use salt-bundle

- susemanager-utils/susemanager-sls/modules/engines/mgr_events.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
After postgres error, the code never called commit or rollback, so all the following updates ended with postgres message 'current transaction is aborted, commands ignored until end of transaction block'
Details are here:
https://bugzilla.suse.com/show_bug.cgi?id=1208687#c17
No difference.
- No tests: we don't test all possible error conditions
Partial fix for https://bugzilla.suse.com/show_bug.cgi?id=1208687
https://github.com/SUSE/spacewalk/issues/20649
If you uncheck …
> Improve error handling in mgr_events.py (bsc#1208687)

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
- java/code/src/com/redhat/rhn/manager/content/test/data1/product_tree.json
- java/code/src/com/redhat/rhn/manager/content/test/smallBase/product_tree.json
- java/spacewalk-java.changes
- susemanager-utils/susemanager-sls/salt/channels/gpg-keys.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
There is a need to define multiple GPG key URLs for a channel.
With this PR it is possible to define a space separated list in the field and the backend takes all of them into account.
Additionally the suse addon gpg key is deployed on all system to be available if needed.
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/2120
Tracks https://github.com/SUSE/spacewalk/pull/20722 …
> support multiple gpgkey urls for a channel

- .github/workflows/build_containers.yml
Use names with "ci-test" prefix. Otherwise, users might think they are released packages.
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/20680
- [X ] No changelog needed
> CI: Acceptance Tests at PR v2: rename docker names

- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
- java/spacewalk-java.changes
ivy update - The big java update was now also released to Leap.
Some packages changed the repo, so we need to update obs-to-maven config as well.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/20806 …
> change jar versions in ivy configuration file

- spacewalk/setup/salt/susemanager.conf
- spacewalk/setup/spacewalk-setup.changes
In preparations for upcoming Salt 3006.0 release, this PR expliciately enables Salt "netapi" required clients, as starting with Salt 3006, all clients are disabled by default.
NOTE: These new settings should not interfere in case "salt-master" is not yet 3006 version.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/19924 …
> Enable "netapi" clients in Salt master configuration (required for Salt 3006)

- java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemReport_queries.xml
- java/spacewalk-java.changes
Report task that populates the table `SystemOutdated` was counting duplicated errata ID's. This lead to a number of outdated packages that were different from the one shown in the webUI.
No difference. This is a change in the values in the report database.
- No documentation needed: Internal change to the data saved in the database
Fixes #
If you uncheck …
> Update report outdated system query to de-duplicate errata id's

- spacewalk/admin/rhn-config-satellite.pl
- spacewalk/admin/spacewalk-admin.changes
- spacewalk/setup/bin/spacewalk-setup
- spacewalk/setup/lib/Spacewalk/Setup.pm
- spacewalk/setup/spacewalk-setup.changes
- fix `externaldb*` and `reportdb` param in `spacewalk-setup`: they didn't match with template in `spacewalk/config/var/lib/rhn/rhn-satellite-prep/etc/rhn/rhn.conf`
- `Setup.pm`: the DEBUG variable was also a dry-run mode, create a new variable to separate them
- `Setup.pm`: align `/etc/rhn/rhn.conf` with `/var/lib/rhn/rhn-satellite-prep/satellite-local-rules.conf`
- `rhn-config-satellite.pl` (called by `spacewalk-setup`) generates a backup file (with extensions `.orig`) everytime is called. Since it's called several time, the `.orig` file is pretty useless. I change it to save the backup file with `.CURRENT_TIME` extension
No difference.
- No documentation needed: only internal and user invisible …
> use template for reportdb configuration (bsc#1206783)

- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
- java/code/src/com/suse/manager/webui/services/pillar/MinionCustomInfoPillarGenerator.java
- java/code/src/com/suse/manager/webui/services/pillar/MinionPillarFileManager.java
- java/spacewalk-java.changes
After removing all custom info entries, the pillar was not removed from the database.
This PR fixes it and also fixes the unit test to detect such bugs next time.
No difference.
- Unit tests were fixed
Fixes https://github.com/SUSE/spacewalk/issues/20829
https://bugzilla.suse.com/show_bug.cgi?id=1209253 …
> Fix deleting custom info pillar (bsc#1209253)

- testsuite/features/step_definitions/api_common.rb
Changes used channel for the distro creation, as RHEL 8 is no longer synched by default.
4.3 https://github.com/SUSE/spacewalk/pull/20908
Fixes https://github.com/SUSE/spacewalk/issues/20899
> QE: Update used channel for distro creation through API

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.5-to-susemanager-schema-4.4.6/002-update-function-create_new_org.sql
SQL function create_new_org was updated but no update script was created. 
New installations would not have a problem but long-running servers are not able to create new organizations.
This PR adds the update script to change the create_new_org sql function.
No difference. Sql change only.
- No documentation needed: SQL change only
- No tests: sql change only
Fixes # https://github.com/uyuni-project/uyuni/issues/6770
Tracks:
- Manager 4.3: https://github.com/SUSE/spacewalk/pull/20896
- Manager 4.2:  https://github.com/SUSE/spacewalk/pull/20898 …
> Fix update of sql function create_new_org

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
python3-ordered-set is only required in SP4 and higher by python3-setuptools.
In SP3 and earlier, this dependency does not exists.
Mark this package as optional.
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/6663 …
> Make python3-ordered-set optional for the bootstrap repo

- .github/workflows/test_all_in_one.yml
Adds a welcome message when running the acceptance tests with a link to the wiki.
No difference.
- See https://github.com/uyuni-project/uyuni/wiki/Running-Acceptance-Tests-at-PR
- No tests
https://github.com/SUSE/spacewalk/issues/20680
> CI: Acceptance tests at PR: add welcome message

- testsuite/Rakefile
Add fail-fast option to cucumber to immediately fail core run set if any feature is failing.
Issue : https://github.com/SUSE/spacewalk/issues/20855
> Stop core run set if any feature fail

- testsuite/features/step_definitions/cobbler_steps.rb
Fix the step looking into cobbler log file by using the right variable name.
Fixes https://github.com/SUSE/spacewalk/issues/20940
- 4.3 https://github.com/SUSE/spacewalk/pull/20941
> QE: Fix cobbler log step not finding file

- testsuite/ext-tools/maintenance_json_generator.py
Add product in proxy repos for maintenance json script because we need it for new packages that maintenance is pushing for 4.2 which is in maintenance but is not LTSS
No difference.
Fixes no issue
Tracks no other PR is needed this script is only in uyuni master …
> Add product in proxy repos for maintenance json script

- testsuite/features/support/code_coverage.rb
Instead of loading all the Java classpath, we will only consider loading rhn.jar.
That's to avoid a recent issue with log4j that we want to get rid of asap.
```
12:41:16  FAIL: java -jar /tmp/jacococli.jar report /tmp/jacoco-allcli_sanity.exec  --xml /srv/www/htdocs/pub/jacoco-allcli_sanity.xml  --classfiles /srv/tomcat/webapps/rhn/WEB-INF/lib returned status code = 1.
12:41:16  Output:
12:41:16  [INFO] Loading execution data file /tmp/jacoco-allcli_sanity.exec.
12:41:16  Exception in thread "main" java.io.IOException: Error while analyzing /srv/tomcat/webapps/rhn/WEB-INF/lib/log4j_log4j-api.jar@org/apache/logging/log4j/util/Base64Util.class.
12:41:16  at org.jacoco.cli.internal.core.analysis.Analyzer.analyzerError(Analyzer.java:162)
12:41:16  at …
```
> Load only rhn.jar in Jacoco

- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/spacewalk-java.changes
When building Docker containers we would need to deploy the GPG signing keys into the container to be able to install packages. As this requires additional work for customers to prepare the Dockerfile correctly to use another buildarg we decided that it is better to disable the GPG ckeck on the repositories we use during the building of the image.
The repository is available only during the buildtime and provide trusted content. We use SSL to access the repository to secure the connection.
No difference.
- TBD
Fixes #
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-project …
> Disable gpgckeck for container build

- testsuite/Rakefile
output_****-build_validation_wait_for_custom_reposync.json are sometime malformated because two or more nodes will export there results in the same file. 
wait for custom reposync feature don't have a unique name and will be call each time we add non_mu or MU channels.
Because we are now running this steps in parallel, the timestamp can be the same.
To make this result file unique, I'm adding the node name. To do so, I need to export the node name on pipeline side and get this node name on testsuite side
CI : https://github.com/SUSE/susemanager-ci/pull/814
SM42 : https://github.com/SUSE/spacewalk/pull/20979
SM43 : https://github.com/SUSE/spacewalk/pull/20978 …
> Rename wait reposync result file with NODE name 

- java/code/src/com/redhat/rhn/common/security/acl/Access.java
- java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
- java/code/src/com/suse/manager/webui/controllers/MinionsAPI.java
- java/spacewalk-java.changes
This PR addresses the following issues related to project lotus:
- fixes the selection issue when clicking on the "select all" link in the ptf list pages.
- adds support for PTF removal on SLES 12 when the proper zypper version is installed
- fixes an issue with the check of PTF repositories on a system subscribed to cloned channels
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/20994
If you …
> Project lotus updates

- python/spacewalk/rhn-conf/rhn.conf
- python/spacewalk/spacewalk-backend.changes
- python/spacewalk/spacewalk-backend.spec
Add httpd user and group to rhn.conf
No difference.
> Add httpd user and group to rhn.conf

- spacecmd/src/spacecmd/utils.py
**The PR   modified the spacecmd/src/spacecmd/utils.py file to use docstring comments instead of source comments**
No difference.
Before:
After:
- No documentation needed: **This PR only works on the docstrings, no code was modified or added**
- No tests: **This PR only works on the docstrings, no code was modified or added**
Fixes #6006  …
> Use docstring instead  of source  comments

- testsuite/features/step_definitions/command_steps.rb
If the environment is slow, the solv file from the fake rpm package might not be ready on time and the package that is being grepped might not be present yet. This PR encapsulates the dumpsolv package grep in a `repeat_until_timeout` clause to wait for the reference to appear.
This PR aims to resolve the failure of `Reposync works as expected. Check reposync of custom channel` which can happen from time to time in Uyuni CI and is caused by the solv file not being ready in time.
No difference.
Fixes #
Tracks # 
4.2
4.3 …
> Testsuite: Wait for solv file to be filled

- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/step_definitions/setup_steps.rb
Validate that recommended products are selected if its parent is selected.
This PR wants to give us more information about an issue we are experiencing in our testsuite, where apparently one of our recommended products is not selected automatically.
No difference.
Ports:
- Manager-4.3 …
> QE: Validate that recommended products are selected if its parent is selected

- susemanager-utils/susemanager-sls/salt/packages/pkgupdate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Updating all packages fail on debian systems when kernel needs to be added or removed.
To do this, we need to call "dist-upgrade" according to https://itsfoss.com/apt-get-upgrade-vs-dist-upgrade/
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/6595
Tracks https://github.com/SUSE/spacewalk/pull/21062 https://github.com/SUSE/spacewalk/pull/21063 …
> use dist-upgrade for updating all packages on a debian system

- spacewalk/setup/spacewalk-setup.spec
Remove ownership of `/etc/tomcat` as it should be (and also is) owned by the tomcat package. Keeping this would result in installation conflicts.
No difference.
Fixes #
I don't think a changelog is required here as it fixes a previous PR without intermediate release. …
> spacewalk-setup: Remove ownership of /etc/tomcat

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
Avoid conflict names for openSUSE channels (I was aware that labels could conflict, but not names)
Problem reported at the mailing list: https://lists.opensuse.org/archives/list/users@lists.uyuni-project.org/thread/ALGZ7DZHN3E6ZGI2WDWCOCV35MQJ3OOP/
No difference.
- No documentation needed: The channel labels are used for spacewalk-common-channel, so this change is not relevant.
- No tests: We don't have tests for `spacewalk-common-channels` for now.
Fixes https://github.com/uyuni-project/uyuni/issues/6831 and fixes https://github.com/SUSE/spacewalk/issues/21043
If …
> Avoid conflict names for openSUSE channels

- web/html/src/components/datetime/DateTimePicker.tsx
- web/html/src/manager/legacy/DateTimePicker.tsx
- web/spacewalk-web.changes
Port of https://github.com/SUSE/spacewalk/pull/21027
> Fix datetimepicker time to match user configured timezone (bsc#1209231)

- testsuite/dockerfiles/opensuse-minion/Dockerfile
CI: install gzip so we have zgrep for running the tests.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/20953
> CI: Acceptance tests at PR add gzip

- web/html/src/components/datetime/DateTimePicker.tsx
Debugging utilities to easily untangle issues with DateTimePicker, cherry-picked from https://github.com/SUSE/spacewalk/pull/21064.
No difference.
> Add debugging UI for DateTimePicker

- spacewalk/setup/lib/Spacewalk/Setup.pm
- spacewalk/setup/spacewalk-setup.changes
fix migration test
No difference.
- No …
> fix migration test

- testsuite/features/secondary/minssh_bootstrap_api.feature
Forgotten change of name in this specific feature causing a failure on this step.
This channel name is now `Fake-RPM-SUSE-Channel` on Uyuni
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/20944
Tracks # No ports needed …
> Testsuite: Correct name of fake channel in feature

- testsuite/dockerfiles/opensuse-minion/Dockerfile
- testsuite/dockerfiles/rocky-minion/Dockerfile
- testsuite/dockerfiles/ubuntu-minion/Dockerfile
CI: install udev so the hardware refresh works
No difference.
- No tests
Fixes # https://github.com/SUSE/spacewalk/issues/20956
> CI: Acceptance tests at PR v2: install udev in minions

- tftpsync/susemanager-tftpsync/susemanager-tftpsync.changes
- tftpsync/susemanager-tftpsync/sync_post_tftpd_proxies.py
Fix a race condition where multiple threads were writing to the same file, overriding each others changes. This recording shows the problem without the fix
[![asciicast](https://asciinema.org/a/571221.svg?t=30&speed=1.5)](https://asciinema.org/a/571221?t=30&speed=1.5)
At the end, there are < 20 files referenced in `pxe_cache.json`. After the fix, the same file contains more than 200 entries, i.e. less files are pushed to proxies (fewer cache misses) and file deletions are propagated correctly.
No difference.
- No documentation needed: backend bugfix
- No tests: We'll add a cucumber test in a follow up PR
Bug tracker: https://github.com/SUSE/spacewalk/issues/20771
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#chan …
> Fix tftpsync `pxe_cache.json` race

- spacewalk/setup/bin/spacewalk-setup
- spacewalk/setup/lib/Spacewalk/Setup.pm
- susemanager-utils/testing/docker/scripts/schema_migration_reportdb_test_pgsql.sh
- susemanager-utils/testing/docker/scripts/schema_migration_test_pgsql.sh
After these changes https://github.com/uyuni-project/uyuni/commit/b91d21ebfbb5a01449e4eef06ab6765ccfe51551 we had problems with migration test, and these changes supposed to fix it https://github.com/uyuni-project/uyuni/commit/8684be36ecc53906c14753296fd400a92ea46554, but they break java test.
So I had a deeper analysis about why migration test succeed before  https://github.com/uyuni-project/uyuni/commit/b91d21ebfbb5a01449e4eef06ab6765ccfe51551  and, after enabling debug mode I found:
```
* Configuring tomcat.
Command: '/usr/bin/spacewalk-setup-tomcat '
open3: exec of /usr/bin/spacewalk-setup-tomcat  failed: No such file or directory at /manager/spacewalk/setup/lib/Spacewalk/Setup.pm line 307.
```
so most of the function in `spacewalk-setup` were not executing during migration test.
This …
> fix java test

- schema/spacewalk/susemanager-schema.changes
- schema/spacewalk/upgrade/susemanager-schema-4.4.5-to-susemanager-schema-4.4.6/100-rename_monitoring_entitlement.sql
The migration script for monitoring entitlement renaming had landed in the old directory and had no effect when upgrading from version 4.4.3 or newer.
This change copies the migration script to the next release directory. The rename will be effective in version 4.4.6.
Fixes migration script from #6321 …
> Copy monitoring entitlement schema migration script

- web/conf/rhn_web.conf
Prepare the migration for Uyuni 2024.04:
* Adjust the version number in web/conf/rhn_web.conf
* Add the migration schema from uyuni-reportdb-schema-4.4.2 to uyuni-reportdb-schema-4.4.3
No difference.
Before:
After:
- No documentation needed: **already covered**
Tracks SUSE/spacewalk#20653 …
> Prepare the migration for Uyuni 2024.04:

- testsuite/podman_runner/12_run_salt_sle_minion.sh
- testsuite/podman_runner/13_run_salt_rhlike_minion.sh
- testsuite/podman_runner/14_run_salt_deblike_minion.sh
add a unique product_uuid. Otherwise, they all have the product_uuid of the  host.
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/20956
> CI: Acceptance tests at PR v2: add unique product_uuid

- containers/proxy-tftpd-image/proxy-tftpd-image.changes
tagged proxy-tftpd-image for Uyuni 2023.04
No difference.
Before:
After:
- No documentation needed: **just tagging**
- No tests: **just tagging**
Tracks SUSE/spacewalk#20653
> tagged proxy-tftpd-image for Uyuni 2023.04

- java/code/src/com/redhat/rhn/frontend/action/kickstart/RenderKickstartFileAction.java
Fix https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&types=VULNERABILITY&id=uyuni-project_uyuni&open=AYcyhEfpc8r8RCRRorHO&tab=code
No difference.
- []x **DONE**
- No tests: log output change
Fixes # …
> Sanitize logged data in RenderKickstartFileAction

- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- susemanager-utils/susemanager-sls/salt/cleanup_minion/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- testsuite/features/secondary/min_salt_minions_page.feature
- testsuite/features/step_definitions/salt_steps.rb
On minion cleanup we do not disable the minion and do not remove the minion config file as this is not easy possible to disable the service which is executing the cleanup.
We found a solution to stop the minion independent of the service to achieve this.
Additionally this PR improve the logging on delete system, when the ssh key could not be removed from known_hosts file.
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/2194
Fix https://github.com/SUSE/spacewalk/issues/21187
Tracks  …
> Improve minion cleanup

- web/html/src/manager/login/susemanager/login.tsx
- web/html/src/manager/login/uyuni/login.tsx
- web/spacewalk-web.changes
Port of merged https://github.com/SUSE/spacewalk/pull/20866
#19753 
The sign in button is disabled with an empty password field 
After:
- No tests:
Fixes #
> Make password and user field required on login page

- web/html/src/branding/css/susemanager/components/date-time-picker.less
- web/html/src/components/datetime/DateTimePicker.tsx
- web/spacewalk-web.changes
Increase font sizes, fix small UI inconsistencies, add missing accessibility labels.
Before:
After:
- Documentation issue already exists for the theme update
Fixes https://github.com/SUSE/spacewalk/issues/21109
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1210437 …
> Increase DateTimePicker font sizes

- java/code/webapp/WEB-INF/pages/common/fragments/errata/relevant-errata-list.jspf
Try to fix
```
2023-04-18 05:39:29,032 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-9] WARN  com.redhat.rhn.frontend.taglibs.list.ColumnTag - Trying to set  column [systems] as the default sort.The default sort column has already been set for [advisoryName]. Can't reset it to [systems].
```
No difference.
Port of https://github.com/SUSE/spacewalk/pull/21158 …
> multiple defaultsort args cause warnings, remove duplicates

- java/code/src/com/redhat/rhn/manager/org/MigrationManager.java
- java/spacewalk-java.changes
Call channel changed event after migrating a system to a different organization. During this transfer
all channels are unsubscribed, but the repositories stayed on the target system.
Now an action is scheduled to apply the current state which is "no channels" and result in an empty repo file .
No difference.
Port of https://github.com/SUSE/spacewalk/pull/21096 …
> remove channels from client after transfer to a different organization

- java/code/src/com/redhat/rhn/frontend/action/kickstart/ScheduleKickstartWizardAction.java
- java/code/src/com/redhat/rhn/manager/action/ActionManager.java
- java/code/src/com/redhat/rhn/manager/kickstart/SSMCreateRecordCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerSystemCreateCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerVirtualSystemCommand.java
- java/spacewalk-java.changes
Fix NPE in create cobbler sytem entry when system has no creator set.
Partial port of https://github.com/SUSE/spacewalk/pull/21133
> fix NPE in cobbler system sync when server has no creator set

- java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
- java/spacewalk-java.changes
Method `listPossibleSuseBaseChannelsForServer()` uses the products to detect which base channels could be used.
On a new registered systems often the products are not yet installed but it could be, that the server has already a base channel assigned.
Return at least the assigned base channel as candidate if no products are installed.
This prevent that the assigned base channel is not visible in the list of base channels, but the child channels are visible.
No difference.
Before:
After:
Fixes https://github.com/SUSE/spacewalk/issues/19911
Tracks https://github.com/SUSE/spacewalk/pull/21142 https://github.com/SUSE/spacewalk/pull/21143
Make sure the changelogs entries you are adding are compliant …
> return at least the assigned base channel if no product is installed

- testsuite/features/step_definitions/cobbler_steps.rb
Unify Uyuni and SUMA products in Cobbler log monitoring step definition.
This will enable to sync the different branches on that topic.
No difference.
Fixes #
Tracks #
4.3 https://github.com/SUSE/spacewalk/pull/21154 …
> QE: Unify Uyuni and SUMA branches in Cobbler log monitoring

- susemanager-utils/susemanager-sls/salt/images/kiwi-image-build.sls
- susemanager-utils/susemanager-sls/salt/services/kiwi-image-server.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
forward port of https://github.com/SUSE/spacewalk/pull/21021
We still use kiwi-legacy to build SLE12 images. Because of old codebase, supportability is very limited and using new kiwi-ng is recommended even for SLE12 images. Since we do not support SLE11 anymore, this PR introduces optional kiwi-ng usage for SLE12 images on SLE12 buildhosts.
To enable kiwi-ng on SLE12 buildhosts either use `use_kiwi_ng: True` pillar, or create custom_info key for build host with `use_kiwi_ng` with `True` value.
No difference. …
> Enable KiwiNG to be used on SLE12 buildhosts

- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/test/CobblerCommandTest.java
- java/code/src/org/cobbler/CobblerObject.java
- java/spacewalk-java.changes
The kernel only requires double quotes if there is a space in the value. See https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html#the-kernel-s-command-line-parameters for reference.
Port of https://github.com/SUSE/spacewalk/pull/21242
No difference.
Fixes # …
> Add double quotes around kernel a option value if it contains a space

- testsuite/features/step_definitions/salt_steps.rb
It can happen that the pillar data is not empty yet despite the associated salt job being indicated as done.
This PR adds a `repeat` clause to wait a bit for the data to be emptied.
Additional information: https://github.com/SUSE/spacewalk/issues/18664#issuecomment-1514732996
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/18664
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/21219
4.3 https://github.com/SUSE/spacewalk/pull/21218 …
> Testsuite: Repeat several times the check for an empty pillar data

- java/code/src/com/redhat/rhn/frontend/xmlrpc/image/DeltaImageInfoHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/image/ImageInfoHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/image/test/ImageInfoHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/DeltaImageSerializer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/util/PillarUtils.java
- java/spacewalk-java.changes
xml-rpc does not support Long type. This PR converts the "size" entry in image pillars to string
before exporting via xml-rpc and back to Long after import.
No difference.
- API documentation added
Fixes https://github.com/SUSE/spacewalk/issues/19990
> Fix image size entries in xml-rpc

- susemanager-utils/susemanager-sls/modules/pillar/suma_minion.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Do not include pillar_only formulas in highstate
No difference.
Fixes # …
> Do not include pillar_only formulas in highstate

- containers/proxy-httpd-image/proxy-httpd-image.changes
- containers/proxy-httpd-image/uyuni-configure.py
- containers/proxy-squid-image/proxy-squid-image.changes
- containers/proxy-squid-image/squid.conf
- java/code/src/com/redhat/rhn/frontend/security/PxtAuthenticationService.java
- java/code/src/com/redhat/rhn/testing/RhnMockHttpServletResponse.java
- java/code/src/com/suse/manager/webui/Router.java
- java/code/src/com/suse/manager/webui/controllers/SaltbootController.java
- java/code/src/com/suse/manager/webui/controllers/test/SaltbootControllerTest.java
- java/code/src/com/suse/manager/webui/controllers/test/image_pillar.json
- java/code/webapp/WEB-INF/web.xml
- java/spacewalk-java.changes
- spacewalk/config/etc/httpd/conf.d/zz-spacewalk-www.conf
- spacewalk/config/spacewalk-config.changes
Containerized proxy does not have access to pillars. This provides the mapping from proxy-local image URLs to global ones via http redirects.
Also, it fixes cache setting for `/os-images` and `/tftp` dirs.
No difference.
- No documentation needed: expected behavior
Fixes https://github.com/SUSE/spacewalk/issues/18455 …
> Mapping of image URLs

- .github/workflows/test_all_in_one_common.yml
CI: Fix the Ubuntu version to have a stable CI. If we use "latest", the ubuntu host could be updated and so the podman version, which could break the CI. Given the ubuntu host is only used to run podman, let's keep this stable.
No difference.
- No tests
> Fix the ubuntu version. We do not want suprises

- testsuite/Rakefile
Small fix in Rakefile, when trying to run a task in parallel
No difference.
- No tests
Ports:
- Manager-4.2
- Manager-4.3
> Fix Rake reference to CustomFormatter

- .github/workflows/test_all_in_one_common.yml
- java/code/src/com/redhat/rhn/frontend/struts/BaseListAction.java
- java/code/src/com/redhat/rhn/frontend/struts/RequestContext.java
- java/code/src/com/redhat/rhn/frontend/struts/test/BaseSetListActionTest.java
- java/code/src/com/redhat/rhn/frontend/taglibs/ListDisplayTag.java
- java/code/src/com/redhat/rhn/frontend/taglibs/ListDisplayTagBase.java
- java/code/src/com/redhat/rhn/frontend/taglibs/UnpagedListDisplayTag.java
- java/code/src/com/redhat/rhn/frontend/taglibs/rhn-taglib.tld
- java/code/src/com/redhat/rhn/frontend/taglibs/test/ListDisplayTagTest.java
- java/code/src/com/redhat/rhn/frontend/taglibs/test/UnpagedListDisplayTagTest.java
- java/code/src/com/redhat/rhn/testing/ActionHelper.java
In addition to the CSV tag, ListDisplay tag also includes some logic for CSV export that is not used anywhere. This patch removes this bit from the codebase.
- No documentation needed: code maintenance
- No tests: only removal
Fixes https://github.com/SUSE/spacewalk/issues/20640
> Remove unused CSV export logic in JSP ListDisplay tag

- web/html/src/components/FormulaForm.tsx
- web/html/src/components/table/TableDataHandler.tsx
- web/html/src/components/utils/Loading.tsx
- web/spacewalk-web.changes
Adds a loading indicator to the formula details page to prevent showing an error during loading.
Fixes https://github.com/SUSE/spacewalk/issues/13387
> Add loading indicator to formula details page (bsc#1179747)

- spacewalk/admin/spacewalk-service
- spacewalk/admin/spacewalk-startup-helper
- spacewalk/package/spacewalk.changes
- spacewalk/package/spacewalk.spec
- spacewalk/setup/lib/Spacewalk/Setup.pm
- spacewalk/setup/spacewalk-setup.changes
- spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
- spacewalk/uyuni-setup-reportdb/bin/uyuni-sort-pg_hba
- spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes
- susemanager/bin/mgr-setup
- susemanager/susemanager.changes
The installation structure of PGSQL14 from the official PostgreSQL repository is different. This repository is being used for the Enterprise Linux implementation.
This change tries to detect the service and data folder names.
No difference.
Manually tested installation on Leap 15.4 …
> Allow for flexible Pgsql14 installation

- testsuite/dockerfiles/controller-dev/Dockerfile
- testsuite/dockerfiles/controller-dev/etc_pam.d_sshd
- testsuite/dockerfiles/opensuse-minion/Dockerfile
- testsuite/dockerfiles/opensuse-minion/etc_pam.d_sshd
- testsuite/dockerfiles/rocky-minion/Dockerfile
- testsuite/dockerfiles/rocky-minion/etc_pam.d_sshd
- testsuite/dockerfiles/server-all-in-one/Dockerfile
- testsuite/dockerfiles/server-all-in-one/etc_pam.d_sshd
- testsuite/dockerfiles/ubuntu-minion/Dockerfile
- testsuite/dockerfiles/ubuntu-minion/etc_pam.d_sshd
- testsuite/podman_runner/00_setup_env.sh
Fixes pam/sshd configuration so sshd works inside the containers with podman. This is a known bug. See: https://github.com/containers/podman/issues/3651
No difference.
- No tests
https://github.com/containers/podman/issues/3651
> Ci fix podman sshd pam
