testsuite/features/step_definitions/command_steps.rb

Port of https://github.com/SUSE/spacewalk/pull/5527

do not append the org id twice

---

testsuite/features/min_docker_build_image.feature
testsuite/features/min_docker_xmlrpc.feature
testsuite/features/min_osimage_build_image.feature
testsuite/features/step_definitions/docker_steps.rb
testsuite/run_sets/testsuite.yml

Testsuite: docker steps cleanup

---

.github/PULL_REQUEST_TEMPLATE.md

The PR template itself.
This is to have a template which makes sense at least for SUSE contributors.
Community-wise I think the content is still OK, but we might explain it better (maybe in a separate contribution guide file?)
No difference.
- No documentation needed: **this is documentation itself**
- No tests: **documentation**
No relevant links

PR template: Uyuni adaptations

---

java/spacewalk-java.changes

Add missing `spacewalk-java.changes` entry for bsc#1105574 
No difference.
- No tests needed

Add missing changelog entry for bsc#1105574

---

.gitignore

Add .gitignore specifics to IDEA
No difference.
- No documentation needed: gitignore, no customer facing
- No tests: no need to test
Tracks # TBD

Chore: update gitignore with IDEA-specific paths

---

java/code/src/com/redhat/rhn/domain/rhnpackage/test/PackageNameTest.java
java/code/src/com/redhat/rhn/manager/audit/CVEAuditManager.java
java/code/src/com/redhat/rhn/manager/audit/test/CVEAuditManagerTest.java
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/5549

Master cve deduplicated bsc1101033

---

java/Makefile.docker

Use new container for development

switch to 3.2 container as starting point

---

java/code/src/com/redhat/rhn/taskomatic/TaskomaticApi.java
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/4732.

TaskomaticApi: do not use removed API

---

web/html/src/manager/image-import.js

Fix & clarify the usage of images import
No difference.
- No documentation needed: already written in documentation: https://github.com/SUSE/doc-susemanager/blob/develop/adoc/advanced_topics_image_management.adoc#at.images.docker.importing
- No tests: no change to test
- Manager-3.2: https://github.com/SUSE/spacewalk/pull/5625

Fix: images import

---

java/code/src/com/redhat/rhn/domain/server/Server.java
java/code/src/com/redhat/rhn/frontend/action/channel/ssm/BaseSubscribeAction.java
java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
java/code/src/com/redhat/rhn/manager/distupgrade/DistUpgradeManager.java
java/code/src/com/redhat/rhn/manager/distupgrade/test/DistUpgradeManagerTest.java

Fixes tech debt referenced on https://github.com/SUSE/spacewalk/issues/1558
No difference.
- No documentation needed: Code refactoring
- No tests: Code refactoring, no functionality was changed.  Already covered by existing tests
Fixes https://github.com/SUSE/spacewalk/issues/1558

Change Server.getInstalledProductSet return to Optional

---

testsuite/features/core_srv_setup_wizard.feature
testsuite/features/support/setup_browser.rb

Testsuite: resurrect @notwithfromdir

---

testsuite/features/step_definitions/docker_steps.rb

It adds a test suite step "When I check the fist image"

Testsuite: forgotten a step when porting

---

susemanager-sync-data/channels.xml
susemanager-sync-data/susemanager-sync-data.changes

Add SLE12 SP4 family to supported products
Port of https://github.com/SUSE/spacewalk/pull/5718

Support sle12 sp4

---

testsuite/docs/cucumber-steps.md
testsuite/features/allcli_config_channel.feature
testsuite/features/allcli_overview_systems_details.feature
testsuite/features/allcli_reboot.feature
testsuite/features/allcli_software_channels.feature
testsuite/features/allcli_software_channels_dependencies.feature
testsuite/features/core_centos_salt.feature
testsuite/features/core_centos_salt_ssh.feature
testsuite/features/core_centos_tradclient.feature
testsuite/features/core_min_salt_ssh.feature
testsuite/features/core_srv_setup_wizard.feature
testsuite/features/min_centos_salt_install_package_and_patch.feature
testsuite/features/min_salt_formulas.feature
testsuite/features/minssh_action_chain.feature
testsuite/features/minssh_bootstrap_xmlrpc.feature
testsuite/features/srv_group_union_intersection.feature
testsuite/features/step_definitions/salt_steps.rb
testsuite/features/support/setup_browser.rb

This PR does changes for consistency with Retail:
* documentation for steps dealing with services
* more readable tags
* use `--force` when installing formulas
* use hash in formulas steps

Testsuite: various preparations for retail

---

java/code/src/com/suse/manager/webui/controllers/ProductsController.java
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/5721

Exclude product channels without a channel from channel UI (bsc#1105886)

---

java/spacewalk-java.changes

(cherry picked from commit 9362d1e)
Fix changelog entry for bsc#1105062

fix changelog entry for bsc#1105062

---

backend/satellite_tools/contentRemove.py
backend/satellite_tools/spacewalk-remove-channel
backend/spacewalk-backend.changes
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/test/ChannelSoftwareHandlerTest.java
java/spacewalk-java.changes

port of https://github.com/SUSE/spacewalk/pull/5716

Remove channel from Minion when channel itselsf is removed from Manager(bsc#1104120)

---

susemanager-utils/testing/automation/susemanager-unittest.sh
susemanager/Makefile.susemanager
susemanager/src/authenticator.py
susemanager/src/errata_helper.py
susemanager/src/helpers.py
susemanager/src/mgr_bootstrap_data.py
susemanager/src/mgr_clean_old_patchnames.py
susemanager/src/mgr_delete_patch.py
susemanager/src/mgr_sync/channel.py
susemanager/src/mgr_sync/cli.py
susemanager/src/mgr_sync/config.py
susemanager/src/mgr_sync/logger.py
susemanager/src/mgr_sync/mgr_sync.py
susemanager/src/mgr_sync/product.py
susemanager/src/package_helper.py

This PR enables the pylint checks for `susemanager-unittest` and fixes all the issues found.

Enable pylint checks on "susemanager" and fix all issues

---

testsuite/docs/Guidelines.md
testsuite/features/profiles/Docker/Dockerfile
testsuite/features/profiles/Docker/authprofile/Dockerfile
testsuite/features/profiles/Docker/authprofile/add_packages.sh
testsuite/features/profiles/Docker/serverhost/Dockerfile
testsuite/features/profiles/Docker/serverhost/add_packages.sh
testsuite/features/profiles/Kiwi/POS_Image-JeOS6/config.sh
testsuite/features/profiles/Kiwi/POS_Image-JeOS6/config.xml

Testsuite: move Kiwi and Docker profiles to testsuite itself

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/configchannel/ConfigChannelHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ConfigRevisionSerializer.java
spacecmd/spacecmd.changes
spacecmd/src/lib/configchannel.py
spacecmd/src/lib/system.py

Cherry-picked from https://github.com/SUSE/spacewalk/pull/5711

spacecmd updated for state channels

---

susemanager-sync-data/channel_families.xml
susemanager-sync-data/channels.xml
susemanager-sync-data/susemanager-sync-data.changes

Add SUSE Manager Retail Branch Server product to SUSE Manager.
In addition fix some channels for SLE12 SP4
- part of Retail docs
- manual
Tracks # https://github.com/SUSE/spacewalk/pull/5772

Retail branch server

---

susemanager-utils/testing/docker/scripts/init-ora-db4eclipse.sh
susemanager-utils/testing/docker/scripts/init-pgsql-db4eclipse.sh

DB init scripts for test containers
- No tests: **used for test**
Tracks # https://github.com/SUSE/spacewalk/pull/5791

add DB init scripts for eclipse test container

---

testsuite/docs/optional.md
testsuite/features/core_srv_docker_profiles.feature
testsuite/features/core_srv_osimage_profiles.feature
testsuite/features/min_docker_auth_registry.feature
testsuite/features/srv_docker_advanced_content_management.feature
testsuite/features/step_definitions/navigation_steps.rb
testsuite/features/support/twopence_init.rb

Testsuite: move profiles to testsuite itself

---

java/code/src/com/redhat/rhn/manager/configuration/ConfigurationManager.java
java/code/src/com/suse/manager/webui/services/test/ConfigChannelSaltManagerLifecycleTest.java
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/5763

Manager: Fix problem with deleting the assigned channels(bsc#1107850)

---

testsuite/features/min_salt_install_package.feature

Testsuite: fix standard step

---

web/html/src/components/FormulaForm.js
web/html/src/components/formulas/EditGroup.js
web/spacewalk-web.changes

Fixes multiple issues related to handling of forms in javascript
No difference.
- No documentation needed: expected behavior
covered by Cucumber min_salt_formulas_advanced.feature test
and by Retail OpenQA tests
Tracks https://github.com/SUSE/spacewalk/pull/5776

fixed javascript handling of formulas

---

testsuite/features/core_centos_tradclient.feature

Testsuite: fixed new package names

---

java/code/src/com/suse/manager/webui/websocket/Notification.java
java/spacewalk-java.changes

Websocket endpoint error java.io.IOException (bsc#1080474)

---

testsuite/features/core_centos_salt.feature
testsuite/features/core_centos_tradclient.feature

Work around problem on CentOS 7 with 2 network interfaces

---

search-server/spacewalk-search/rhn_search_daemon_dev.conf
search-server/spacewalk-search/spacewalk-search.changes
search-server/spacewalk-search/src/config/search/rhn_search_daemon.conf

limit number of old java logfiles (bsc#1107869)

Manager log4j maxfiles

---

testsuite/features/core_centos_salt.feature
testsuite/features/step_definitions/common_steps.rb
testsuite/features/support/setup_browser.rb
testsuite/features/support/twopence_init.rb

Testsuite: various preparations for Retail 

---

susemanager-branding-oss/license.txt
susemanager-branding-oss/susemanager-branding-oss.changes

Use ASCII quotation marks. Otherwise in text mode those characters cannot be rendered on some hardware resulting in ugly characters being displayed.

Manager bsc1098970

---

web/html/src/components/formulas/EditGroup.js

Add id to generic button in order to have ids looking like the complete path of the dynamic form.

Add id to formula button

---

testsuite/features/core_srv_setup_wizard.feature

[WIP] Testsuite: we were running mgr-sync-refresh twice in parallel

---

testsuite/features/step_definitions/salt_steps.rb

Testsuite: fix variable name for checkbox state

---

rel-eng/build-packages-local-obs.sh
susemanager-frontend/susemanager-nodejs-sdk-devel/package.json
susemanager-frontend/susemanager-nodejs-sdk-devel/setup.sh
susemanager-frontend/susemanager-nodejs-sdk-devel/susemanager-nodejs-sdk-devel.spec
susemanager-frontend/yarn.lock
web/html/src/manager/index.js
web/html/src/package.json
web/html/src/vendors/npm.licenses.structured.js
web/html/src/vendors/npm.licenses.txt
web/setup.sh
web/spacewalk-web.spec

- Fixes spacewalk-web build. It seems flow-bin ships with a binary that conflics with obs, demanding some gclib packages that  some architectures can't provide.
- Fixes some wrong webpack configuration wrong paths
No difference.
Before:
After:
- No tests
Fixes #

Fixijng spacewalk-web build on obs

---

susemanager/src/mgr_bootstrap_data.py
susemanager/susemanager.changes

Add bootstrap repo for SLE12 SP4 (port of https://github.com/SUSE/spacewalk/pull/5752)

Sle12 sp4 bootstrap repo

---

java/conf/rhn_java.conf
java/spacewalk-java.changes

Increase Java API version, since Uyuni is already 4.0
No difference.
- No documentation needed: Confirmed with doc team. We don't have references to this.
- No tests: This is not really a code change, it should be covered already.

Increase Java API version

---

testsuite/features/srv_smdba.feature

do not test for internal stuff of postgresql

do not test for internal stuff of postgresql

---

testsuite/features/srv_smdba.feature

It fixes a typo in smdba feature tests.

Testsuite: fix typo in smdba

---

susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes
susemanager-utils/supportutils-plugin-susemanager/susemanager

- Make it easier to identify actually running postgresql version.
- Add information about actual version of database.

Manager supportconfig pg version

---

java/code/src/com/redhat/rhn/frontend/events/TransactionHelper.java

Improves the `TransactionHelper` by catching more failure cases and logging them better.
No difference.
- No tests: **component already covered**
Tracks https://github.com/SUSE/spacewalk/pull/5944

TransactonHelper: reliability improvements

---

rel-eng/build-packages-local-obs.sh
susemanager-frontend/susemanager-nodejs-sdk-devel/package.json
susemanager-frontend/yarn.lock
web/html/src/.babelrc
web/html/src/build/webpack.config.js
web/html/src/manager/notification-messages.js

This PR disable the regeneration of javascript licenses on watch mode and add a new webpack alias, so we can easily import the shared react components inside the folder "src/components".
No difference.
- No tests

Webpack improvements 

---

testsuite/features/profiles/Kiwi/POS_Image-JeOS6/config.xml

Kiwi image root password in clear text.

Testsuite: password in clear text

---

testsuite/features/profiles/Kiwi/POS_Image-JeOS6/image.sh

It runs post-installation steps.
uyuni only.

Testsuite: post-installation steps

---

testsuite/features/profiles/Kiwi/POS_Image-JeOS6/root/etc/systemd/system/image-deployed.service

This PR adds missing bit to kiwi profile so the PXE minion does its initial registration.

Testsuite: pxe minion registration

---

backend/cdn_tools/cdnsync.py
backend/cdn_tools/repository.py
schema/spacewalk/common/data/rhnKSInstallType.sql
schema/spacewalk/common/data/rhnKickstartTimezone.sql
schema/spacewalk/susemanager-schema.changes
schema/spacewalk/upgrade/spacewalk-schema-2.8-to-spacewalk-schema-2.9/003-rhnKSInstallType.sql
schema/spacewalk/upgrade/spacewalk-schema-2.8-to-spacewalk-schema-2.9/004-rhnKickstartTimezome.sql
schema/spacewalk/upgrade/susemanager-schema-4.0.1-to-susemanager-schema-4.0.2/003-rhnKSInstallType.sql
schema/spacewalk/upgrade/susemanager-schema-4.0.1-to-susemanager-schema-4.0.2/004-rhnKickstartTimezome.sql

Get important changes from spacewalk to uyuni

Spacewalk cherry pick 20180929

---

java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
java/code/src/com/suse/manager/utils/SaltUtils.java

Ports of https://github.com/SUSE/spacewalk/pull/5834

Blank new line at the end of the salt stdout

---

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
java/code/webapp/WEB-INF/pages/channel/all.jsp
java/code/webapp/WEB-INF/pages/channel/custom.jsp
java/code/webapp/WEB-INF/pages/channel/popular.jsp
java/code/webapp/WEB-INF/pages/channel/retired.jsp
java/code/webapp/WEB-INF/pages/channel/shared.jsp
java/code/webapp/WEB-INF/pages/channel/vendor.jsp
java/code/webapp/WEB-INF/pages/common/fragments/channel/channel_header.jspf
java/spacewalk-java.changes

Added UI shortcuts on the top right in
the Software Channels submenu so that
the User has an easier time navigating
the webpage.
cherrypick from: https://github.com/SUSE/spacewalk/pull/5988

Added shortcuts for Software Channels

---

susemanager-frontend/susemanager-nodejs-sdk-devel/package.json
susemanager-frontend/yarn.lock
web/html/src/build/webpack.config.js

Add copy-webpack-plugin to sync the folder with old javascript files to the folder dist
No difference.
- No tests

Add copy-webpack-plugin to sync the folder with old javascript files to the folder dist

---

testsuite/features/min_salt_minions_page.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/step_definitions/salt_steps.rb
testsuite/features/support/setup_browser.rb
testsuite/features/support/twopence_init.rb

Various style fixes in preparation for Retail.

Testsuite: various fixes

---

testsuite/features/min_action_chain.feature
testsuite/features/minssh_action_chain.feature
testsuite/features/step_definitions/xmlrpc_common.rb
testsuite/features/trad_action_chain.feature

Port of https://github.com/SUSE/spacewalk/pull/5747, https://github.com/SUSE/spacewalk/pull/5865, https://github.com/SUSE/spacewalk/pull/5866

Testsuite: wait until there are no more action chains present

---

susemanager-utils/testing/automation/VERSION

Fixes unit tests
- No tests: **fixes tests**

fix name of ora container when uyuni is used

---

schema/spacewalk/upgrade/susemanager-schema-4.0.1-to-susemanager-schema-4.0.2/100-rhn_avdl_mod_trig.sql.postgresql

indepodent fix for trigger creation
- No tests: **fixes a test**

drop the trigger if it exists

---

testsuite/features/core_srv_setup_wizard.feature

Increases timeout for a testsuite scenario step to prevent failure when overloaded environments.

Increase timeout to wait on overloaded scenarios

---

java/code/src/com/suse/manager/webui/templates/virtualization/guests/show.jade
web/html/src/manager/virtualization/guests/edit/guests-edit.js
web/html/src/manager/virtualization/guests/edit/guests-edit.renderer.js
web/html/src/manager/virtualization/guests/guest-properties.js
web/html/src/manager/virtualization/guests/list/guests-list.js
web/html/src/manager/virtualization/guests/list/guests-list.renderer.js
web/html/src/manager/virtualization/guests/list/guests-list.utils.js
web/html/src/manager/virtualization/guests/virtualization-guest-action-api.js
web/html/src/manager/virtualization/guests/virtualization-guests-list-refresh-api.js

This is just code cleanup in the end.
No difference.
- No documentation needed: code cleanup needs no doc
- No tests: code cleanup, just need existing tests to pass again

ESlint fixes and flowification of virtualization JS files

---

web/html/src/manager/virtualization/guests/list/guests-list.utils.js

Trivial JS require fix.
No difference.
- No documentation needed: trivial internal fix
- No tests: virt testsuite covers the fix

Fix Guest list utils requires.

---

branding/spacewalk-branding.changes

Port of https://github.com/SUSE/spacewalk/pull/6219**

Add missing change log entry

---

utils/spacewalk-utils.changes

Add missing changelog entry for the single-touched package

Add changelog entry

---

spacecmd/spacecmd.changes

Port of https://github.com/SUSE/spacewalk/pull/6218

change log entry has been updated

---

backend/satellite_tools/repo_plugins/yum_src.py
backend/spacewalk-backend.changes

Re-targeted to Uyuni https://github.com/SUSE/spacewalk/pull/6140

BSC#1110427

---

testsuite/features/support/lavanda.rb
testsuite/features/support/twopence_init.rb

Just better testsuite debugging, and correct English

Better DNS debugging

---

java/scripts/taskomatic.service
java/spacewalk-java.changes
spacewalk/setup/share/server.xml.xsl

Increase maximum number of open files and threads for taskomatic. Needed for large installations. Using the values that have been reported to work for affected customer.

Manager bsc1111966

---

web/html/src/manager/image-profile-edit.js

Fix a duplicate var name err when building JS.
No difference.
- No tests: build err, not needed.

Fix duplicate var name in image-profile-edit.js

---

testsuite/features/step_definitions/common_steps.rb
testsuite/features/step_definitions/navigation_steps.rb

Fixes errs in the test suite.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/6267

TESTSUITE: Cucumber fixes

---

backend/satellite_tools/repo_plugins/deb_src.py
java/code/src/com/redhat/rhn/common/db/datasource/xml/config_queries.xml
java/code/src/com/redhat/rhn/domain/kickstart/RepoInfo.java
java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartHelper.java
java/code/src/com/redhat/rhn/frontend/dto/ConfigSystemDto.java
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
java/code/src/com/redhat/rhn/manager/configuration/ConfigurationManager.java
java/code/src/com/redhat/rhn/manager/configuration/EnableConfigHelper.java
java/code/src/com/redhat/rhn/manager/kickstart/KickstartWizardHelper.java

Cherry pick spacewalk commits which seems to be usefull for uyuni as well.
- No documentation needed: **internals**
- No tests: **from spacewalk**

Spacewalk cherry pick 20181103

---

java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java

Before the code moved only one formula, others were deleted too early.
With this fix it works as expected.
- No tests:
Tracks # https://github.com/SUSE/spacewalk/pull/6319

Fix deletion of old formula data

---

java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
java/spacewalk-java.changes

Port downstream: https://github.com/SUSE/spacewalk/pull/6288

bsc#1114362 - SUMA Web UI System Currency reports incorrectly if system joins a group 

---

java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemGroup_queries.xml
java/code/src/com/redhat/rhn/manager/system/ServerGroupManager.java
java/code/src/com/redhat/rhn/manager/system/SystemManager.java
java/spacewalk-java.changes

Performance improvements for group listings and detail page
No difference.
- No documentation needed: bug fixing
- No tests: performance-only, correctness already covered
Fixes # https://bugzilla.suse.com/show_bug.cgi?id=1111810
Tracks # https://github.com/SUSE/spacewalk/pull/6284

Performance improvements for system group listings and detail page (bsc#1111810)

---

web/html/src/build/webpack.config.js

Add copywebpack css only for development

Add copywebpack css only for development

---

spacecmd/spacecmd.changes
spacecmd/src/lib/softwarechannel.py

Adds the ability to merge errata/packages of
software channels via spacecmd. This functionality
is already available via the API.
Port from https://github.com/SUSE/spacewalk/pull/6023

Add errata/packages-merge to spacecmd (bsc#987798)

---

testsuite/features/step_definitions/salt_steps.rb

Testsuite: give enough time for the filtered list to appear

---

testsuite/features/step_definitions/salt_steps.rb

Leave 3 seconds for filtered package list to appear

---

rel-eng/_service
rel-eng/build-packages-for-obs.sh
rel-eng/push-packages-to-obs.sh

Reverts uyuni-project/uyuni#325

Revert "Use obscpio instead of tarballs for OBS submissions"

---

web/html/src/components/input/Form.js
web/html/src/components/input/InputBase.js
web/html/src/components/panels/Panel.js

* Allow setting a default value on Form fields (will be used in PR #181)
* Fix validation in Form component
* Allow adding buttons on the top right corner of Panel components (not used yet, but will come with PR #181 )
No difference.
- No documentation needed: internal changes
- No tests: tiny changes in component: tests will need to cover the use of these features once they are actually used.

Form fixes and Panel buttons

---

susemanager-utils/susemanager-sls/susemanager-sls.spec

Add the missing lines in the spec file for the new salt-engine, that we missed in PR https://github.com/uyuni-project/uyuni/pull/310/
No difference.
- No tests: bug fix
Tracks https://github.com/SUSE/spacewalk/pull/6429

Adapt spec file for the new salt-engine

---

client/rhel/mgr-daemon/rhnsd.timer

Last PR miss the timer file for mgr-daemon
No difference.
- No documentation needed: **quick fix**
- No tests: **quick fix for build**

add missing timer file

---

client/rhel/mgr-daemon/mgr-daemon.spec

Fix building.
No difference.
- No tests: **fix**

fix building of mgr-daemon

---

susemanager-frontend/susemanager-nodejs-sdk-devel/package.json
susemanager-frontend/yarn.lock

Cleanup unused susemanager-nodejs-sdk-devel dependencies
Fixes #342

Cleanup unused susemanager-nodejs-sdk-devel dependencies

---

utils/spacewalk-common-channels
utils/spacewalk-common-channels.ini
utils/spacewalk-utils.changes

Add Uyuni channels: Server, proxy and client tools so they can be used with spacewalk-common-channels tool.
No difference.
- No documentation needed: Not documented
- No tests: Should be already tested.
Fixes #
Tracks https://github.com/SUSE/spacewalk/issues/6177

WIP: Add Uyuni channels: Server, proxy and client tools

---

client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes
client/rhel/spacewalk-client-tools/src/bin/spacewalk-update-status.py

Bugfix for https://bugzilla.suse.com/show_bug.cgi?id=1116610

Convert generators to iterables

---

susemanager/src/mgr-create-bootstrap-repo
susemanager/src/mgr_bootstrap_data.py
susemanager/susemanager.changes

adapt mgr-create-bootstrap-repo for Uyuni and let it create bootstrap repos for openSUSE and CentOS
No difference.
- No documentation needed: **works like before - just new options available**
- No tests: **hard to test without real syncing**
Fixes partly https://github.com/SUSE/spacewalk/issues/6177

Create bootstrap repo for uyuni

---

README.md

Add a link to the bug report tool at README.md
Before:
After:
- No documentation needed: README.md change.
- No tests: README.md change.
- None

Add a link to the bug report tool at README.md

---

README.md

Update links to IRC and Mailing lists.
Before:
After:
- No documentation needed: README.md change.
- No tests: README.md change.
- None

Update links to IRC and Mailing lists

---

susemanager-utils/testing/docker/scripts/push-to-obs.sh

fix cleanup paths
No difference.

use correct paths

---

.github/PULL_REQUEST_TEMPLATE.md

Fix typo at PR template
No difference.
- No documentation needed: Doc Typo fixed.
- No tests: Doc typo fixed
None

Fix typo at PR template

---

java/build.xml
java/buildconf/build-props-tomcat8.xml
java/buildconf/build-props-tomcat9.xml
java/spacewalk-java.changes
java/spacewalk-java.spec

Port of https://github.com/SUSE/spacewalk/pull/6141

Allow installing on both Tomcat 8 and 9

---

client/rhel/dnf-plugin-spacewalk/dnf-plugin-spacewalk.changes
client/rhel/mgr-daemon/mgr-daemon.changes
client/rhel/yum-rhn-plugin/yum-rhn-plugin.changes
client/tools/mgr-cfg/mgr-cfg.changes
client/tools/spacewalk-abrt/spacewalk-abrt.changes
client/tools/spacewalk-oscap/spacewalk-oscap.changes
client/tools/spacewalk-remote-utils/spacewalk-remote-utils.changes
java/spacewalk-java.changes

Basically some entries from last sync from Spacewalk, plus entries for empty changelogs.
No difference.
- No documentation needed: Changelog fixes.
- No tests: Changelog fixes.
Tracks https://github.com/SUSE/spacewalk/issues/6374
If the test `changelog_test`already ran, then add another new comment with the following text:

Fix changelogs for Uyuni 4.0.1 release

---

utils/spacewalk-common-channels.ini

Fix URLs for Stable Server and Proxy, and adjust variables for GPG stuff
No difference.
Tracks # https://github.com/SUSE/spacewalk/issues/6374
If the test `changelog_test`already ran, then add another new comment with the following text:

Fix URLs for Stable Server and Proxy, and adjust variables for GPG stuff

---

schema/spacewalk/common/data/rhnPackageKey.sql
schema/spacewalk/common/data/rhnPackageProvider.sql
schema/spacewalk/susemanager-schema.changes
schema/spacewalk/upgrade/susemanager-schema-4.0.2-to-susemanager-schema-4.0.3/300-add-uyuni-keys.sql

Add Uyuni GPG to the database
No difference.
Tracks # https://github.com/SUSE/spacewalk/issues/6374
If the test `changelog_test`already ran, then add another new comment with the following text:

Add Uyuni GPG to the database

---

java/code/src/com/suse/manager/webui/controllers/FrontendLogController.java

Do not log `username` as a sensitive data, log the `userid` instead.
No difference.
- No documentation needed: nothing to document
- No tests: nothing to test
Fixes #
Tracks # https://github.com/SUSE/spacewalk/pull/6656

Prevent logging sensitive data

---

java/spacewalk-java.spec

Fix building of spacewalk-java due to updated packages.
No difference.
- No tests: **fix building**

fix filelist - adapt jar files to new packages

---

java/code/src/com/suse/manager/reactor/messaging/test/LibvirtEngineDomainLifecycleMessageActionTest.java
java/code/src/com/suse/manager/reactor/messaging/test/SaltTestUtils.java
java/code/src/com/suse/manager/webui/controllers/ImageBuildController.java
java/code/src/com/suse/manager/webui/controllers/test/BaseControllerTestCase.java
java/code/src/com/suse/manager/webui/controllers/test/VirtualGuestsControllerTest.java
java/code/src/com/suse/manager/webui/utils/MinionActionUtils.java
java/code/webapp/WEB-INF/nav/system_detail.xml
testsuite/features/step_definitions/command_steps.rb
web/html/src/manager/virtualization/guests/list/guests-list.js

Add a few test utility functions and extract some code for reuse. This PR is a  split of the huge PR #181  for virtual machines creation UI.
Before:
Domain-0 guest mistakenly shows actions
After:
Domain-0 is shown but with no possible actions to avoid user's confusion.
- No documentation needed: such a tiny diff (and a bug fix), that it's not worth mentioning.
- No tests: only code reorganization
required for PR#181

Virt small refactoring

---

java/code/src/com/suse/manager/reactor/messaging/test/LibvirtEngineDomainLifecycleMessageActionTest.java
java/code/src/com/suse/manager/reactor/messaging/test/SaltTestUtils.java
java/code/src/com/suse/manager/virtualization/GuestDefinition.java
java/code/src/com/suse/manager/virtualization/GuestDiskDef.java
java/code/src/com/suse/manager/virtualization/GuestGraphicsDef.java
java/code/src/com/suse/manager/virtualization/GuestInterfaceDef.java
java/code/src/com/suse/manager/webui/controllers/ImageBuildController.java
java/code/src/com/suse/manager/webui/controllers/test/BaseControllerTestCase.java
java/code/src/com/suse/manager/webui/controllers/test/VirtualGuestsControllerTest.java
java/code/src/com/suse/manager/webui/utils/MinionActionUtils.java
java/code/webapp/WEB-INF/nav/system_detail.xml
testsuite/features/step_definitions/command_steps.rb
web/html/src/manager/virtualization/guests/list/guests-list.js

Parse more from the libvirt XML definitions.
No difference.
- No documentation needed: internals only 
Needed for PR #181 as it's a split part of it.

Virt domain def parse

---

java/code/src/com/suse/manager/reactor/messaging/test/LibvirtEngineDomainLifecycleMessageActionTest.java
java/code/src/com/suse/manager/reactor/messaging/test/SaltTestUtils.java
java/code/src/com/suse/manager/virtualization/DomainCapabilitiesJson.java
java/code/src/com/suse/manager/virtualization/GuestDefinition.java
java/code/src/com/suse/manager/virtualization/GuestDiskDef.java
java/code/src/com/suse/manager/virtualization/GuestGraphicsDef.java
java/code/src/com/suse/manager/virtualization/GuestInterfaceDef.java
java/code/src/com/suse/manager/virtualization/HostCapabilitiesJson.java
java/code/src/com/suse/manager/virtualization/VirtManager.java
java/code/src/com/suse/manager/webui/Router.java
java/code/src/com/suse/manager/webui/controllers/ImageBuildController.java
java/code/src/com/suse/manager/webui/controllers/VirtualGuestsController.java
java/code/src/com/suse/manager/webui/controllers/VirtualNetsController.java
java/code/src/com/suse/manager/webui/controllers/VirtualPoolsController.java
java/code/src/com/suse/manager/webui/controllers/test/BaseControllerTestCase.java
java/code/src/com/suse/manager/webui/controllers/test/VirtualGuestsControllerTest.java
java/code/src/com/suse/manager/webui/controllers/test/VirtualNetsControllerTest.java
java/code/src/com/suse/manager/webui/controllers/test/VirtualPoolsControllerTest.java
java/code/src/com/suse/manager/webui/controllers/test/virt.guest.allcaps.json
java/code/src/com/suse/manager/webui/controllers/test/virt.net.info.json
java/code/src/com/suse/manager/webui/controllers/test/virt.pool.info.json
java/code/src/com/suse/manager/webui/utils/MinionActionUtils.java
java/code/src/com/suse/manager/webui/utils/gson/VirtualNetworkInfoJson.java
java/code/src/com/suse/manager/webui/utils/gson/VirtualStoragePoolInfoJson.java
java/code/webapp/WEB-INF/nav/system_detail.xml
testsuite/features/step_definitions/command_steps.rb
web/html/src/manager/virtualization/guests/list/guests-list.js

Provide REST APIs to expose virtual networks, disks and host capabilities.
No difference.
- No documentation needed: no GUI diff
Needed for PR #181 as it's a split part of it

Virt manager api

---

backend/spacewalk-backend.spec

Two more python dependency problems
No difference.
- No tests: **just deps**

use python version prefix for requests and m2crypto

---

testsuite/features/step_definitions/command_steps.rb

Test reverse name resolution in Retail network

---

testsuite/features/core_proxy_branch_network.feature
testsuite/features/step_definitions/salt_steps.rb

Network address is variable now

---

backend/spacewalk-backend.spec

fix prefix of debian package
No difference.
- No tests: **just dependency fixes**

prefix debian python package correct for SUSE

---

tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.spec

Use python3 version of mod_wsgi
No difference.
- No documentation needed: **just dependencies**
- No tests: **just dependencies**

fix dependencies for python 3

---

testsuite/features/srv_change_task_schedule.feature
testsuite/run_sets/testsuite.yml

Add cucumber test for updating Schedule of Tasks (bsc#1099287)

 Add cucumber test for updating Schedule of Tasks (bsc#1099287)

---

proxy/installer/spacewalk-proxy-installer.spec

Fix a typo and get the correct the path.
No difference.
- No tests: **fix build error**

fix copy and paste error and get the correct file

---

spacecmd/spacecmd.changes

rephrased changelog entry to fit the 3.2 one

Rephrased changelog entry (bsc#987798)

---

susemanager/susemanager.changes

fix changelog entry for bsc#1099311

fix changelog entry for bsc#1099311)

---

java/spacewalk-java.changes

^^^
The code is in uyuni [already](https://github.com/uyuni-project/uyuni/pull/290), it was just the changelog patch, which I forgot to port.

Update changelog for system.createEmptyProfile XMLRPC endpoint patch

---

backend/satellite_tools/spacewalk-debug
backend/spacewalk-backend.changes
java/code/src/com/redhat/rhn/common/db/datasource/xml/Task_queries.xml
java/code/src/com/redhat/rhn/domain/kickstart/KickstartCommand.java
java/code/src/com/redhat/rhn/taskomatic/task/DailySummary.java
java/code/src/com/suse/manager/webui/Router.java
java/spacewalk-java.changes
web/html/src/components/datetimepicker.js
web/spacewalk-web.changes

Backport of missing patches from downstream                                                                                                                                                                                              
^^^
Tracks:
- https://github.com/SUSE/spacewalk/issues/5339
- https://github.com/SUSE/spacewalk/issues/6126
- https://github.com/SUSE/spacewalk/issues/5725
- https://github.com/SUSE/spacewalk/issues/3633
- https://github.com/SUSE/spacewalk/issues/2069

Backport bugfixes

---

java/spacewalk-java.changes

Add missing parenthesis to spacewalk-java.changes entry
No difference.

Add missing parenthesis to spacewalk-java.changes entry

---

java/spacewalk-java.changes

Adds a missing changelog line.
No difference.
- No documentation needed: **changelog only**
- No tests: **no code change**

Added changelog line deleted by mistake

---

susemanager-utils/susemanager-sls/susemanager-sls.changes
susemanager/susemanager.changes

DO NOT MERGE until I confirm with the developers why the entries are missing.
Add missing changelog entries from Manager-3.2
No difference.
- No documentation needed: Only missing changelog entries.
- No tests: Only missing changelog entries.
- https://github.com/SUSE/spacewalk/issues/6742

WIP: Add missing changelog entries from Manager-3.2

---

web/spacewalk-web.changes

Port of https://github.com/SUSE/spacewalk/pull/6772#discussion_r247850890

Reword changelog entry for notifications messages feedback fix

---

java/code/src/com/redhat/rhn/common/db/datasource/xml/User_queries.xml
java/code/src/com/redhat/rhn/frontend/action/user/AssignedGroupsSetupAction.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
java/code/src/com/redhat/rhn/manager/user/UserManager.java
java/code/src/com/redhat/rhn/manager/user/test/UserManagerTest.java
java/spacewalk-java.changes
schema/spacewalk/oracle/packages/rhn_user.pkb
schema/spacewalk/oracle/packages/rhn_user.pks
schema/spacewalk/postgres/packages/rhn_user.pkb
schema/spacewalk/postgres/packages/rhn_user.pks
schema/spacewalk/upgrade/susemanager-schema-4.0.3-to-susemanager-schema-4.0.4/203-rhn_user.pkb.sql.oracle
schema/spacewalk/upgrade/susemanager-schema-4.0.3-to-susemanager-schema-4.0.4/203-rhn_user.pkb.sql.postgresql
schema/spacewalk/upgrade/susemanager-schema-4.0.3-to-susemanager-schema-4.0.4/203-rhn_user.pks.sql.oracle
schema/spacewalk/upgrade/susemanager-schema-4.0.3-to-susemanager-schema-4.0.4/203-rhn_user.pks.sql.postgresql

Improve performance for granting and revoking permissions to user for groups
No difference.
- No documentation needed: bug fixing
Fixes partially https://github.com/SUSE/spacewalk/issues/6104
Tracks https://github.com/SUSE/spacewalk/pull/6700

Manager grant permissions to user for groups

---

schema/spacewalk/susemanager-schema.changes

Add entry in schema changes file, missing in PR https://github.com/uyuni-project/uyuni/pull/503
No difference.
- No documentation needed: only small change in schema change log file
- No tests: only small change in schema change log file 

Add new entry log for bsc-1111810

---

backend/server/handlers/xmlrpc/registration.py
client/rhel/dnf-plugin-spacewalk/dnf-plugin-spacewalk.spec
client/rhel/dnf-plugin-spacewalk/spacewalk.py
client/rhel/rhnlib/rhn/connections.py
documentation/Makefile
documentation/how-to-generate-documentation.txt
java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
java/code/src/com/redhat/rhn/manager/system/SystemManager.java
schema/spacewalk/common/data/rhnPackageKey.sql
schema/spacewalk/upgrade/spacewalk-schema-2.8-to-spacewalk-schema-2.9/005-fedora-keys.sql
schema/spacewalk/upgrade/susemanager-schema-4.0.4-to-susemanager-schema-4.0.5/005-fedora-keys.sql
selinux/spacewalk-selinux/spacewalk-selinux-enable
selinux/spacewalk-selinux/spacewalk.te
spacewalk/admin/rhn-deploy-ca-cert.pl

Cherry pick some commits from spacewalk which could be useful for Uyuni as well.
No difference.
- No tests: **cherry-pick**

Spacewalk cherry pick 20190112

---

testsuite/features/core_srv_channels_add.feature
testsuite/features/core_srv_create_activationkey.feature
testsuite/features/core_srv_create_repository.feature
testsuite/features/min_ubuntu_salt_install_package_and_patch.feature
testsuite/features/step_definitions/command_steps.rb

Adds initial test cases for package operations on Ubuntu.
No difference.
https://github.com/SUSE/spacewalk/issues/6490

Ubuntu pkg operations test cases

---

testsuite/features/allcli_software_channels.feature

Add Software Channels tests for Ubuntu minions.
No difference.
- No documentation needed:  Just Cucumber tests
- No tests: Added Cucumber tests

Add Software Channels tests for Ubuntu minion

---

testsuite/features/allcli_reboot.feature

Add reboot tests for Ubuntu minions.
No difference.
- No documentation needed: Just tests
- Cucumber Tests were added

Add Ubuntu reboot tests

---

testsuite/features/srv_group_union_intersection.feature

Add group intersect/union tests for Ubuntu minions.
No difference.
- No documentation needed: Just Cucumber tests
- No tests: Added Cucumber tests

Add group union/intersect tests for ubuntu minion

---

spacecmd/spacecmd.changes
spacecmd/src/lib/api.py
spacecmd/src/lib/softwarechannel.py

Fix spacecmd py3 issues.
No difference.
- No documentation needed: just py3 fixes
- No tests: covered by sumaform

spacecmd python3 fix

---

testsuite/features/allcli_system_group.feature

It fixes a test suite failure created by a forward port.
Relevant branches:
- Manager-3.1 SUSE/spacewalk#6998 
- Manager-3.2 SUSE/spacewalk#6999

Fix undefined step problem

---

testsuite/features/min_custom_pkg_download_endpoint.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/step_definitions/salt_steps.rb
testsuite/features/support/commonlib.rb
testsuite/features/upload_files/pkg_endpoint.sls
testsuite/run_sets/testsuite.yml

Cucumber tests for https://github.com/uyuni-project/uyuni/pull/565
Tracks # https://github.com/SUSE/spacewalk/pull/6952

cucumber tests for a custom pkg download points

---

web/html/src/manager/virtualization/guests/virtualization-domains-caps-api.js
web/html/src/manager/virtualization/nets/virtualization-nets-list-refresh-api.js
web/html/src/manager/virtualization/pools/virtualization-pools-list-refresh-api.js

Add API react components providing data like virtual storage pool infos, network infos and host capabilities. Will be needed in PR #181
No difference.
- No documentation needed: no UI diff
- No tests: React components only. Will indirectly be tested by cucumber tests added in PR #181
Needed for PR #181 since it's a split part of it

Virt react api components

---

java/build.xml

Fix spacewalk-java package build on HEAD.
No difference.
- No documentation needed: build fix
- No tests: build fix

spacewalk-java: fix apidoc jasper2 build

---

client/tools/spacewalk-koan/Makefile.spacewalk-koan
client/tools/spacewalk-koan/spacewalk-koan.changes
client/tools/spacewalk-koan/test/test_merge_rd.py

Take care to use up-to-date container and fix a py3 local import issue
No difference.
- fixed test

Use up to date container and port py3

---

branding/spacewalk-branding.changes

This PR fixes the latest changelog entry added by https://github.com/uyuni-project/uyuni/pull/609
No difference.
- No documentation needed: **not needed**
- No tests: **not needed**

Update changelog for "spacewalk-branding"

---

susemanager-utils/susemanager-sls/susemanager-sls.changes

Add bsc#1126280 to susemanager-sls changelog
No difference.
- No documentation needed: Changelog update
- No tests: Changelog update

Add bsc#1126280 to susemanager-sls changelog

---

backend/satellite_tools/spacewalk-debug
backend/server/action_extra_data/scap.py
backend/server/handlers/xmlrpc/registration.py
client/rhel/rhnlib/rhn/connections.py
client/rhel/spacewalk-client-tools/src/up2date_client/config.py
client/rhel/spacewalk-client-tools/test/testSSLSocketTimeout.py
client/tools/mgr-cfg/config_common/file_utils.py
schema/spacewalk/common/tables/rhnXccdfIdent.sql
schema/spacewalk/upgrade/spacewalk-schema-2.9-to-spacewalk-schema-2.10/001-rhnXccdfIdent-ident.sql.oracle
schema/spacewalk/upgrade/spacewalk-schema-2.9-to-spacewalk-schema-2.10/001-rhnXccdfIdent-ident.sql.postgresql
schema/spacewalk/upgrade/susemanager-schema-4.0.6-to-susemanager-schema-4.0.7/001-rhnXccdfIdent-ident.sql.oracle
schema/spacewalk/upgrade/susemanager-schema-4.0.6-to-susemanager-schema-4.0.7/001-rhnXccdfIdent-ident.sql.postgresql
utils/spacewalk-manage-channel-lifecycle

Copy some changes from spacewalk project to uyuni.
No difference.
- some tests changed

Spacewalk cherry pick 20190217

---

spacewalk/certs-tools/rhn_bootstrap_strings.py
spacewalk/certs-tools/spacewalk-certs-tools.changes

clean up downloaded gpg keys after bootstrap (bsc#1126075)

Manager bsc1126075

---

web/html/src/manager/image-profile-edit.js
web/html/src/manager/products.js
web/spacewalk-web.changes

per pr: https://github.com/SUSE/spacewalk/pull/6935

Sort activation key lists on bootstrap page and create image profile pages

---

java/code/src/com/redhat/rhn/frontend/action/channel/manage/CloneChannelAction.java
java/code/webapp/WEB-INF/pages/common/fragments/channel/channel_tree_erratas.jspf
java/code/webapp/WEB-INF/pages/common/fragments/channel/channel_tree_packages.jspf
java/code/webapp/WEB-INF/pages/common/fragments/channel/channel_tree_provider.jspf
java/code/webapp/WEB-INF/pages/common/fragments/channel/channel_tree_systems.jspf
java/spacewalk-java.changes

Backport of https://github.com/SUSE/spacewalk/pull/7045

bsc#1124639 - Fix a problem when cloning public child channels with a private base channel from another organization 

---

testsuite/run_sets/testsuite.yml

Disable 'Build OS images' tests

Disable 'Build OS images' tests

---

java/code/src/com/redhat/rhn/taskomatic/task/CobblerSyncTask.java

Fixes some `ClassCastExceptions` caused by changes in the Cobbler XML-RPC return types.
No difference.
- No tests: already covered by cucumber tests
Fixes https://github.com/SUSE/spacewalk/issues/7149

Cobbler 3.0 fixes

---

testsuite/features/min_custom_pkg_download_endpoint.feature
testsuite/features/step_definitions/command_steps.rb

Chang the target from server to the proxy.
Tracks # https://github.com/SUSE/spacewalk/pull/7044*

Change target from server to proxy in cucumber tests

---

java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
schema/spacewalk/susemanager-schema.changes
schema/spacewalk/upgrade/susemanager-schema-3.2.16-to-susemanager-schema-3.2.17/001-suseproductsccrepo-delete-invalid-entries.sql

Follow up for https://github.com/uyuni-project/uyuni/pull/590 to handle missing channels in more places.

handle missing repo for channel

---

testsuite/features/core_centos_salt_ssh.feature
testsuite/features/trad_centos_client.feature

Yum is not so good in dependency resolution. So we need to install the real package name.
No difference.
- fixes test

use real name instead of alias for package installation

---

java/spacewalk-java.changes
java/spacewalk-java.spec

No difference.
Before:
After:
Fixes #

Remove obsolete /rhn/help directory from spacewalk-java

---

java/code/src/com/redhat/rhn/common/hibernate/AnnotationRegistry.java
java/code/src/com/redhat/rhn/domain/channel/Channel.hbm.xml
java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
java/code/src/com/redhat/rhn/domain/channel/test/ChannelFactoryTest.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ContentManager.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProject.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProjectFactory.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProjectFilter.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ProjectSource.java
java/code/src/com/redhat/rhn/domain/contentmgmt/SoftwareProjectSource.java
java/code/src/com/redhat/rhn/domain/contentmgmt/test/ContentManagerTest.java
java/code/src/com/redhat/rhn/domain/contentmgmt/test/ContentProjectFactoryTest.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/EntityExistsFaultException.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/EntityNotExistsFaultException.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ContentProjectSourceSerializer.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java
java/code/src/com/redhat/rhn/manager/EntityExistsException.java
java/code/src/com/redhat/rhn/manager/EntityNotExistsException.java
java/code/src/com/redhat/rhn/manager/configuration/test/ConfigurationManagerTest.java
java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerTest.java
java/spacewalk-java.changes
schema/spacewalk/common/tables/suseContentFilterProject.sql
schema/spacewalk/common/tables/suseContentProjectSource.sql
schema/spacewalk/upgrade/susemanager-schema-4.0.6-to-susemanager-schema-4.0.7/051-susecontentprojectsource.sql.oracle
schema/spacewalk/upgrade/susemanager-schema-4.0.6-to-susemanager-schema-4.0.7/051-susecontentprojectsource.sql.postgresql
schema/spacewalk/upgrade/susemanager-schema-4.0.6-to-susemanager-schema-4.0.7/054-susecontentfilterproject.sql.oracle
schema/spacewalk/upgrade/susemanager-schema-4.0.6-to-susemanager-schema-4.0.7/054-susecontentfilterproject.sql.postgresql

^^^
Commit-by-commit.
No difference.
- XMLRPC api doc added
Fixes https://github.com/SUSE/spacewalk/issues/6538 and https://github.com/SUSE/spacewalk/issues/6513

Allow managing Project Sources on Content Projects

---

backend/server/rhnServer/server_hardware.py
backend/spacewalk-backend.changes
client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes
client/rhel/spacewalk-client-tools/src/up2date_client/hardware.py
client/rhel/spacewalk-client-tools/src/up2date_client/rpmUtils.py

Co-authored-by: Jochen Breuer <jbreuer@suse.de>
Fixes bootstrapping SLE15 https://bugzilla.suse.com/show_bug.cgi?id=1128564
No difference.
Before:
After:
Fixes #

Fix bootstrapping SLE15 client (bsc#1128541)

---

testsuite/features/min_salt_install_with_staging.feature
testsuite/features/step_definitions/command_steps.rb

Port https://github.com/SUSE/spacewalk/pull/6829

Port Fix issue in test suite in content staging feature

---

java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerTest.java

The fix should ensure the following behavior:
Attach:
- attaching a new project source -> attached state
- attaching already BUILT source -> built state
- attaching detached source -> built state
Detach:
- detaching built source -> detached state
- detaching attached (not built) source -> delete source
No difference.
No links

Fix the soft delete for content sources, add tests

---

java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
java/code/src/com/suse/manager/reactor/messaging/test/action.chain.refresh.needed.json
java/code/src/com/suse/manager/reactor/messaging/test/action.chain.refresh.not.needed.json
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/7097
Fixes # https://github.com/SUSE/spacewalk/issues/7078 & https://github.com/SUSE/spacewalk/issues/7104
Tracks # **https://github.com/SUSE/spacewalk/pull/7097**

If needed, execute at most  one full package refresh per action chain-bsc1126099

---

java/code/src/com/redhat/rhn/taskomatic/task/sshpush/SSHPushWorkerSalt.java
java/code/src/com/redhat/rhn/taskomatic/task/sshpush/test/SSHPushWorkerSaltTest.java
java/code/src/com/redhat/rhn/taskomatic/task/sshpush/test/minion.startup.applied.state.response.json
java/code/src/com/suse/manager/reactor/messaging/ApplyStatesEventMessage.java
java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
java/code/src/com/suse/manager/reactor/messaging/MinionStartEventMessageAction.java
java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
java/code/src/com/suse/manager/reactor/messaging/test/action.chain.refresh.needed.json
java/code/src/com/suse/manager/reactor/messaging/test/action.chain.refresh.not.needed.json
java/code/src/com/suse/manager/reactor/messaging/test/minion.startup.applied.state.response.json
java/code/src/com/suse/manager/reactor/test/MinionStartupActionTest.java
java/code/src/com/suse/manager/utils/SaltUtils.java
java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
java/code/src/com/suse/manager/webui/services/impl/SaltService.java
java/code/src/com/suse/manager/webui/utils/salt/State.java
java/code/src/com/suse/manager/webui/utils/salt/custom/ScheduleMetadata.java
java/code/src/com/suse/manager/webui/utils/salt/custom/SystemInfo.java
java/spacewalk-java.changes
susemanager-utils/susemanager-sls/salt/util/systeminfo.sls
susemanager-utils/susemanager-sls/susemanager-sls.changes

Port of https://github.com/SUSE/spacewalk/pull/7038
Fixes # https://github.com/SUSE/spacewalk/issues/6832
Tracks # **https://github.com/SUSE/spacewalk/pull/7038**

On minion startup get latest system info bsc1122381

---

java/buildconf/apidoc/docbook/handler.txt
java/buildconf/apidoc/html/handler.txt
java/buildconf/apidoc/jsp/handler.txt
java/buildconf/apidoc/singlepage/handler.txt
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/schedule/ScheduleHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/spacewalk-java.changes

Fixes apidoc issues...
already merged into 3.2 per: https://github.com/SUSE/spacewalk/pull/7096

Fix apidoc issues

---

susemanager-utils/susemanager-sls/salt/channels/disablelocalrepos.sls
susemanager-utils/susemanager-sls/susemanager-sls.changes

Port of https://github.com/SUSE/spacewalk/pull/7217

Adapt disablelocalrepos syntax for Salt 2016.10 (rhel6, sle11)

---

backend/satellite_tools/repo_plugins/deb_src.py
backend/spacewalk-backend.changes

Make reposync use and append token correctly to the URL
No difference.
- No documentation needed: internal mechanism to fetch URL, no doc needed
- No tests: there were None about Debian/Ubuntu
Tracks https://github.com/SUSE/spacewalk/pull/7000

Fix: Debian reposync

---

java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
java/code/src/com/redhat/rhn/manager/content/MgrSyncUtils.java
java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
java/code/src/com/suse/scc/model/SCCProductJson.java
java/spacewalk-java.changes
susemanager-sync-data/additional_products.json
susemanager-sync-data/product_tree.json
susemanager-sync-data/susemanager-sync-data.changes

Collection of the following PRs:
- https://github.com/uyuni-project/uyuni/pull/685
- https://github.com/uyuni-project/uyuni/pull/696
- https://github.com/uyuni-project/uyuni/pull/697
- https://github.com/uyuni-project/uyuni/pull/567
- https://github.com/uyuni-project/uyuni/pull/699

Ubuntu pr collection

---

testsuite/features/step_definitions/xmlrpc_common.rb

fix typo
No difference.
- fixes a test

assign return value to result variable

---

testsuite/features/support/setup_browser.rb

This PR undoes the attempt to fix the selenim crashes in #707.

Undo attempt to fix selenium crash

---

java/code/src/com/redhat/rhn/common/db/datasource/xml/User_queries.xml

Fixes an Oracle JUnit test.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/7018

User_queries: remove spurious semicolon

---

testsuite/features/min_bootstrap_script.feature
testsuite/features/step_definitions/common_steps.rb
testsuite/run_sets/testsuite.yml

Adds Cucumber feature file to bootstrap a minion using the bootstrap script
cherry-pick from https://github.com/SUSE/spacewalk/pull/6906

Add Cucumber minion bootstrap test via script-6746

---

testsuite/features/min_activationkey.feature
testsuite/features/min_bootstrap_script.feature
testsuite/features/min_bootstrap_xmlrpc.feature
testsuite/features/min_centos_salt.feature
testsuite/features/min_empty_system_profiles.feature
testsuite/features/min_salt_minions_page.feature
testsuite/features/min_ubuntu_salt.feature
testsuite/features/minssh_bootstrap_xmlrpc.feature
testsuite/features/proxy_retail_pxeboot.feature
testsuite/features/srv_virtual_host_manager.feature
testsuite/features/trad_baremetal_discovery.feature
testsuite/features/trad_centos_client.feature
testsuite/features/trad_migrate_to_minion.feature
testsuite/features/trad_migrate_to_sshminion.feature
testsuite/features/trad_ssh_push.feature

Always wait and check result when we delete clients

---

testsuite/features/srv_virtual_host_manager.feature

Fix does not apply to IP addresses

---

testsuite/features/support/setup_browser.rb

Doubling once again memory (see #728)
- [x ] No changelog needed

Doubling memory again

---

search-server/spacewalk-search/spacewalk-search.changes
search-server/spacewalk-search/spacewalk-search.spec

No difference.
Before:
After:
Fixes #

Fix spec file for rhn-search 

---

branding/spacewalk-branding.changes
susemanager-frontend/susemanager-nodejs-sdk-devel/susemanager-nodejs-sdk-devel.changes

Add missing changelogs for spacewalk-branding and susemanager-nodejs-sdk-devel from https://github.com/uyuni-project/uyuni/pull/417
No difference. Adding missing changelog entries only.
- No documentation needed: Adding missing changelog entries only.
- No tests: Adding missing changelog entries only.
https://github.com/uyuni-project/uyuni/pull/417

Add missing changelogs

---

.github/PULL_REQUEST_TEMPLATE.md
susemanager-frontend/susemanager-nodejs-sdk-devel/package.json
susemanager-frontend/yarn.lock
web/html/src/vendors/npm.licenses.structured.js
web/html/src/vendors/npm.licenses.txt

Fix javascript linting - update dependencies to fix vulnerability
https://github.com/davidtheclark/cosmiconfig/issues/180
No difference.
- No tests

Fix javascript linting - update dependencies to fix JS vulnerability (js-yaml)

---

client/rhel/yum-rhn-plugin/rhnplugin.py
client/rhel/yum-rhn-plugin/yum-rhn-plugin.changes
java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartHelper.java
java/spacewalk-java.changes
schema/spacewalk/susemanager-schema.changes
schema/spacewalk/upgrade/spacewalk-schema-2.9-to-spacewalk-schema-2.10/002-rhnXccdfIdent-ident-upgrade.sql
schema/spacewalk/upgrade/susemanager-schema-4.0.8-to-susemanager-schema-4.0.9/002-rhnXccdfIdent-ident-upgrade.sql
utils/spacewalk-utils.changes
utils/spacewalk-utils.spec

Get usefull commits from spacewalk
No difference.
- No tests: **no tests in spacewalk**

Spacewalk cherry pick 20190321

---

usix/Makefile.usix
usix/common/__init__.py
usix/common/usix.py
usix/spacewalk-usix.changes
usix/usix-pylintrc

Fixes the only pylint issue found in `usix` package.

Lintfix for usix

---

testsuite/features/step_definitions/navigation_steps.rb

Log out already logged-in user under different name

---

java/code/src/com/redhat/rhn/common/messaging/MessageQueue.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ContentEnvironment.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProject.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProjectFactory.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProjectHistoryEntry.java
java/code/src/com/redhat/rhn/domain/contentmgmt/EnvironmentTarget.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ProjectSource.java
java/code/src/com/redhat/rhn/domain/contentmgmt/SoftwareEnvironmentTarget.java
java/code/src/com/redhat/rhn/domain/contentmgmt/test/ContentProjectFactoryTest.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/EditChannelAction.java
java/code/src/com/redhat/rhn/frontend/events/AlignSoftwareTargetAction.java
java/code/src/com/redhat/rhn/frontend/events/AlignSoftwareTargetMsg.java
java/code/src/com/redhat/rhn/frontend/events/CloneErrataAction.java
java/code/src/com/redhat/rhn/frontend/events/CloneErrataEvent.java
java/code/src/com/redhat/rhn/frontend/events/test/CloneErrataActionTest.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
java/code/src/com/redhat/rhn/manager/channel/CloneChannelCommand.java
java/code/src/com/redhat/rhn/manager/channel/test/ChannelManagerContentAlignmentTest.java
java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerTest.java
java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java
java/code/src/com/redhat/rhn/manager/errata/cache/ErrataCacheManager.java
java/spacewalk-java.changes

Allow building content project.
- commit-by-commit - all the messages are self-explanatory
No difference.
Tracks  https://github.com/SUSE/spacewalk/issues/6517

Content management: Build functionality

---

susemanager-utils/susemanager-sls/susemanager-sls.changes

Add missing changelog for susemanager-sls (#703)
Missing changelog.
- No documentation needed:Missing changelog.
- No tests: Missing changelog.
#703

Add missing changelog for susemanager-sls

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
java/spacewalk-java.changes

Fix API doc generation
No difference.
- No documentation needed: **fixes docs**
- fix build

Fix api doc contentmgmt

---

testsuite/features/step_definitions/navigation_steps.rb

Port of https://github.com/SUSE/spacewalk/pull/7457

Fix authorization step

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ContentProjectSourceSerializer.java

Fixes a couple of errors about XMLRPC doc generating.
No difference.
- No tests

Fix XMLRPC doc generating

---

testsuite/features/min_bootstrap_script.feature

Fix cucumber test in uyuni where the product name is part of the title.
No difference.
Fixes #

fix product name matching

---

proxy/installer/spacewalk-proxy-installer.changes
susemanager/susemanager.changes

add bugzilla number bsc#1131231 to changelog

add bugzilla number bsc#1131231 to changelog

---

spacecmd/spacecmd.changes
spacecmd/src/lib/system.py

Backport of https://github.com/SUSE/spacewalk/pull/7101

backport of fixes for bsc#1130077 and bsc#1125744

---

rel-eng/build-packages-local-obs.sh

Adds a hint how to install Tito.

Add a hint how to install tito

---

proxy/proxy/spacewalk-proxy.changes
proxy/proxy/spacewalk-proxy.spec
rel-eng/packages/spacewalk-config
rel-eng/packages/spacewalk-proxy
rel-eng/packages/susemanager-sls
spacewalk/config/spacewalk-config.changes
spacewalk/config/spacewalk-config.spec
susemanager-utils/susemanager-sls/src/modules/sumautil.py
susemanager-utils/susemanager-sls/susemanager-sls.changes
susemanager-utils/susemanager-sls/susemanager-sls.spec

Port of #787 to master. To be merged after autobuild approves the SRs, and to be merged with a MERGE COMMIT to keep github hashes and tag references.

Port of #787 and #806 to master

---

testsuite/README.md

It document Ubuntu repositories for test suite
Tracks: none, uyuni only

Documenting Ubuntu repositories

---

testsuite/features/allcli_system_group.feature
testsuite/features/core_proxy_branch_network.feature
testsuite/features/min_osimage_build_image.feature
testsuite/features/min_salt_formulas.feature
testsuite/features/proxy_retail_pxeboot.feature
testsuite/features/step_definitions/salt_steps.rb

Synchronize all Salt modules when installing formulas

---

java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
java/code/src/com/redhat/rhn/common/hibernate/HibernateFactory.java
java/code/src/com/redhat/rhn/domain/action/server/ServerAction.java
java/code/src/com/redhat/rhn/domain/reactor/SaltEvent.hbm.xml
java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
java/code/src/com/redhat/rhn/domain/server/Server_legacyUser.hbm.xml
java/code/src/com/suse/manager/reactor/SaltReactor.java
java/code/src/com/suse/manager/reactor/messaging/BatchStartedEventMessage.java
java/code/src/com/suse/manager/reactor/messaging/BatchStartedEventMessageAction.java
java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
java/code/src/com/suse/manager/reactor/messaging/test/BatchStartedEventMessageActionTest.java
java/code/src/com/suse/manager/reactor/messaging/test/batch.start.json
java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
java/code/src/com/suse/manager/webui/services/impl/SaltService.java
java/code/src/com/suse/manager/webui/utils/salt/custom/ScheduleMetadata.java
java/conf/rhn_java.conf
java/spacewalk-java.changes
schema/spacewalk/postgres/tables/suseSaltEvent.sql
schema/spacewalk/susemanager-schema.changes
schema/spacewalk/upgrade/susemanager-schema-4.0.10-to-susemanager-schema-4.0.11/002-alter-susesaltevent.sql.oracle
schema/spacewalk/upgrade/susemanager-schema-4.0.10-to-susemanager-schema-4.0.11/002-alter-susesaltevent.sql.postgresql
susemanager-utils/susemanager-sls/modules/engines/mgr_events.py
susemanager-utils/susemanager-sls/susemanager-sls.changes
susemanager-utils/susemanager-sls/test/test_engine.py

Integrate the new 'rate-limiting' (AKA 'batch-mode') feature of Salt.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/6948

Manager  - Add support for command batching

---

testsuite/features/allcli_system_group.feature

This PR fixes a test suite bug.
Fixes #7573.

Testsuite: Not on the right page at the right time

---

spacecmd/Makefile.python
spacecmd/spacecmd.changes
spacecmd/src/spacecmd/activationkey.py
spacecmd/src/spacecmd/filepreservation.py
spacecmd/tests/helpers.py
spacecmd/tests/test_activationkey.py
spacecmd/tests/test_filepreservation.py

Continue adding unit tests for Spacecmd:

Spacecmd unit tests: api and activation key

---

testsuite/features/core_srv_sync_channels.feature

This PR fixes a test suite typo introduced in #377 .
uyuni only.

Fixed error in channel name

---

java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectActionsApiController.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/EnvironmentResponse.java
susemanager-frontend/yarn.lock
web/html/src/core/auth/use-roles.js
web/html/src/core/hooks/use-interval.js
web/html/src/core/utils/objects.js
web/html/src/manager/content-management/project/project.js
web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-form.js
web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-view.js
web/html/src/manager/content-management/shared/type/project.type.js
web/html/src/vendors/npm.licenses.structured.js
web/html/src/vendors/npm.licenses.txt

Track environment build status update - frontend
In each environment the following info will be shown:
Status:  "Cloning channels" | "Generating repositories data" | "Built" | "Failed"
- No tests.
Fixes # https://github.com/SUSE/spacewalk/issues/7428

Content Lifecycle - track build status update - frontend

---

web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-lifecycle.js
web/html/src/manager/content-management/shared/components/panels/filters/filters.js
web/html/src/manager/content-management/shared/components/panels/properties/properties-edit.js
web/html/src/manager/content-management/shared/components/panels/sources/sources.js
web/spacewalk-web.changes

Fix text issues on content management page
No difference.
Before:
After:

Fix text issues on content management page

---

testsuite/features/core_proxy_branch_network.feature

This PR changes the order of firewalling actions in the test suite.

Open avahi port before we change the firewall

---

testsuite/features/core_proxy_branch_network.feature

Not sure how to make this work. Reverting last change in the meantime.

Revert avahi port opened before highstate

---

testsuite/features/allcli_config_channel.feature
testsuite/features/core_srv_create_repository.feature
testsuite/features/min_action_chain.feature
testsuite/features/min_activationkey.feature
testsuite/features/min_config_state_channel.feature
testsuite/features/min_state_config_channel.feature
testsuite/features/minssh_action_chain.feature
testsuite/features/trad_action_chain.feature
testsuite/features/trad_config_channel.feature
testsuite/features/trad_need_reboot.feature

This PR revert part of commit 2e109c2ae0f35d1156a122988dab56e80d6c0102 "Add missing backward and forward ports"

Revert abusive accelerations

---

java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
java/code/src/com/suse/scc/client/SCCFileClient.java
java/spacewalk-java.changes

 Fix leftovers from #863 

---

spacewalk/config/spacewalk-config.changes

Add mising bsc bsc#1132197
No difference.
- No documentation needed: Changelog fix
- No tests: Changelog fix

Add missing bsc#1132197

---

backend/spacewalk-backend.changes

Add missing changelog for #786.
No difference.
- No tests
Fixes #

Changelog update for mgr-sign-metadata-ctl 

---

susemanager-sync-data/product_tree.json
susemanager-sync-data/susemanager-sync-data.changes

- Add SLES11 SP4 LTSS to SLES for SAP product
- Add Beta Tools Channel
- Add more tags
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/7700

Update sync data

---

java/code/src/com/suse/manager/virtualization/VirtManager.java
testsuite/features/minkvm_guests.feature
testsuite/features/minxen_guests.feature

A few easy fixes for the virtualization features
No difference.
- No documentation needed: just minor implementation fixes
- No tests: fixes existing tests

Virt fixes

---

client/rhel/mgr-daemon/mgr-daemon.changes
client/tools/mgr-cfg/mgr-cfg.changes
client/tools/mgr-custom-info/mgr-custom-info.changes
client/tools/mgr-osad/mgr-osad.changes
client/tools/mgr-push/mgr-push.changes
client/tools/mgr-virtualization/mgr-virtualization.changes

As notified by Bernhard M. Wiedemann
No difference.
- No documentation needed: Fixed a changelog entry.
- No tests: Fixed a changelog entry.
Not needed.

Fix wrong bugzilla issue 11040346 to correct one 1104034

---

java/spacewalk-java.changes
schema/spacewalk/susemanager-schema.changes
susemanager-utils/susemanager-sls/susemanager-sls.changes

Add missing changelog entries from:
- @moio: https://github.com/uyuni-project/uyuni/pull/572 ([bsc#1125097](https://bugzilla.suse.com/show_bug.cgi?id=1125097), https://github.com/SUSE/spacewalk/pull/7004)
- @mcalmer: https://github.com/uyuni-project/uyuni/pull/596 ([bsc#1125492](https://bugzilla.suse.com/show_bug.cgi?id=1125492) https://github.com/SUSE/spacewalk/pull/7086)
No difference.
- No documentation needed: Changelog entries
- No tests: Changelog entries
None

Missing changelog

---

susemanager-utils/susemanager-sls/susemanager-sls.changes

Adds missing changelog to: https://github.com/uyuni-project/uyuni/pull/640

Add missing changelog entry for commit 2372eb1

---

testsuite/features/profiles/Docker/Dockerfile

This PR fixes a typo in previous PR.

Fixed path to avahi conf files

---

testsuite/features/profiles/Docker/add_packages.sh
testsuite/features/profiles/Docker/authprofile/add_packages.sh
testsuite/features/profiles/Docker/serverhost/add_packages.sh

With "simple" key, there is not test channel. Don't fail if it is absent.

The test channel might be absent

---

testsuite/features/profiles/Docker/authprofile/sles12sp4.repo
testsuite/features/profiles/Docker/serverhost/sles12sp4.repo
testsuite/features/profiles/Docker/sles12sp4.repo

This PR enables the repository from which avahi packages are downloaded.

Enabled the helper repository

---

testsuite/documentation/optional.md
testsuite/features/step_definitions/command_steps.rb
testsuite/features/step_definitions/navigation_steps.rb

Virtualization test suite enhancements
No difference.
- No documentation needed: testsuite fixes
- No tests: Fixing the tests

Testsuite fixes

---

testsuite/features/step_definitions/navigation_steps.rb
testsuite/features/support/setup_browser.rb

Port https://github.com/SUSE/spacewalk/pull/7399

Port 7399: Some small improvements regarding clicks on the UI

---

java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProjectFactory.java
java/code/src/com/redhat/rhn/domain/contentmgmt/test/ContentFilterTest.java
java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/ContentManagementViewsController.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/FilterApiController.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectApiController.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectHandler.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/request/FilterRequest.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/FilterResponse.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/ProjectFilterResponse.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/templates/list-filters.jade
web/html/src/manager/content-management/list-filters/filter-edit.js
web/html/src/manager/content-management/list-filters/filter-form.js
web/html/src/manager/content-management/list-filters/filter.utils.js
web/html/src/manager/content-management/list-filters/list-filters.js
web/html/src/manager/content-management/list-filters/list-filters.renderer.js
web/html/src/manager/content-management/project/project.js
web/html/src/manager/content-management/shared/business/filters.enum.js
web/html/src/manager/content-management/shared/components/panels/filters-project/filters-project-selection.js
web/html/src/manager/content-management/shared/components/panels/filters-project/filters-project.js
web/html/src/manager/content-management/shared/type/filter.type.js
web/html/src/manager/content-management/shared/type/project.type.js
web/spacewalk-web.changes

Nevra + Patch name filter - first implementation of UI
- No tests.

Nevra + Patch advisory name filter - first implementation of UI

---

java/code/src/com/suse/manager/webui/websocket/RemoteMinionCommands.java

Follow up of #690
- Add user in event summary
- Truncate output larger than 4000 chars to fit in the db
- Escape command output to avoid cross site scripting
No difference.
Before:
After:
- No documentation needed: small enhancements
- No tests: small enhancements

Salt remote commands: truncate long output and escape html to guard agains XSS

---

java/buildconf/build-props.xml
java/spacewalk-java.changes
java/spacewalk-java.spec

Fix: add new JARs into specfile
Fix: add stax2-api and stax-api to ant

Fix specfile and ant JARs

---

client/rhel/mgr-daemon/mgr-daemon.changes
client/rhel/mgr-daemon/mgr-daemon.spec
client/tools/mgr-cfg/mgr-cfg.changes
client/tools/mgr-cfg/mgr-cfg.spec
client/tools/mgr-custom-info/mgr-custom-info.changes
client/tools/mgr-custom-info/mgr-custom-info.spec
client/tools/mgr-osad/mgr-osad.changes
client/tools/mgr-osad/mgr-osad.spec
client/tools/mgr-push/mgr-push.changes
client/tools/mgr-push/mgr-push.spec
client/tools/mgr-virtualization/mgr-virtualization.changes
client/tools/mgr-virtualization/mgr-virtualization.spec

Obsolete new versions of client tools packages
No difference.
- No documentation needed: SPEC fix
- No tests: SPEC fix
Replaces: https://github.com/uyuni-project/uyuni/pull/981

Obsolete new versions of client tools packages

---

client/rhel/mgr-daemon/mgr-daemon.spec
client/tools/mgr-cfg/mgr-cfg.spec
client/tools/mgr-custom-info/mgr-custom-info.spec
client/tools/mgr-osad/mgr-osad.spec
client/tools/mgr-push/mgr-push.spec
client/tools/mgr-virtualization/mgr-virtualization.spec

Increase the last part of the version for renamed client tool packages (fix #982)
No difference.
- No documentation needed: SPEC fix
- No tests: SPEC fix
Replaces: https://github.com/uyuni-project/uyuni/pull/981

Increase the last part of the version for renamed client tool packages

---

testsuite/documentation/optional.md
testsuite/features/core_first_settings.feature
testsuite/features/min_docker_build_image.feature
testsuite/features/step_definitions/common_steps.rb
testsuite/features/step_definitions/navigation_steps.rb
testsuite/features/support/setup_browser.rb
testsuite/features/support/twopence_init.rb

Port changes from 4.0 rc1

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/PackageSerializer.java
java/spacewalk-java.changes
testsuite/features/allcli_system_group.feature
testsuite/features/step_definitions/command_steps.rb

these are already merged or approved(3.2 blocked now)... 
No difference.
Before:
After:
Fixes #

Missing commits

---

spacecmd/spacecmd.changes
spacecmd/src/spacecmd/cryptokey.py
spacecmd/src/spacecmd/distribution.py
spacecmd/tests/test_activationkey.py
spacecmd/tests/test_cryptokey.py
spacecmd/tests/test_custominfo.py
spacecmd/tests/test_distribution.py
spacecmd/tests/test_filepreservation.py
spacecmd/tests/test_shell.py
spacecmd/tests/test_ssm.py

Add unit tests for the following modules:
Note: changelog notification commit check supposed to fail every update and will be added only at the end of this PR progress.
This PR has been extended to more modules due to `master` branch lock-out.

Add unit tests for spacecmd

---

spacewalk/certs-tools/rhn_bootstrap_strings.py
spacewalk/certs-tools/spacewalk-certs-tools.changes

An echo command in the bootstrap script is missing the closing quotation mark which breaks the complete script. This PR fixes it.

4.0 rc1 bsc1135659

---

testsuite/features/step_definitions/command_steps.rb

When waiting for the VM to be up the test step was trying to SSH on the
virtual machine using the domain name. However that doesn't work in
non-avahi world and for some reason some VMs had their eth0 renamed to
eth1 after the start, leading to the VM being unreachable.
To ensure the VM is booted, we now add a log to the VM serial console
and wait for the 'login:' string to appear in it.
No difference.
- No documentation needed: testsuite implementation change
- No tests: test suite implementation change

More reliable KVM tests

---

testsuite/Gemfile

Now we have Ruby 2.5, upgrade Gemfile accordingly

---

schema/spacewalk/susemanager-schema.changes
schema/spacewalk/upgrade/susemanager-schema-4.0.3-to-susemanager-schema-4.0.4/001-suseSCCRepository.sql.postgresql

fix schema migration for suseSCCRepositoryAuth (bsc#1136558)

Manager bsc1136558

---

spacecmd/spacecmd.changes
spacecmd/src/spacecmd/softwarechannel.py

Supersedes https://github.com/uyuni-project/uyuni/pull/1033

Bugfix: referenced variable before assignment

---

spacecmd/spacecmd.changes
spacecmd/src/spacecmd/group.py
spacecmd/tests/helpers.py
spacecmd/tests/test_group.py
spacecmd/tests/test_repo.py

Note: changelog is updated at the end of the PR cycle.

Bugfixes and unit tests on spacecmd

---

web/html/src/manager/admin/config/monitoring-admin.js
web/html/src/manager/admin/setup/products/products.js
web/html/src/manager/admin/task-engine-status/taskotop.js
web/html/src/manager/audit/cveaudit/cveaudit.js
web/html/src/manager/audit/subscription-matching/subscription-matching.js
web/html/src/manager/images/image-build.js
web/html/src/manager/images/image-profiles.js
web/html/src/manager/images/image-stores.js
web/html/src/manager/images/image-view.js
web/html/src/manager/salt/cmd/remote-commands.js
web/html/src/manager/salt/formula-catalog/org-formula-catalog.js
web/html/src/manager/salt/keys/key-management.js
web/html/src/manager/systems/bootstrap/bootstrap-minions.js
web/html/src/manager/systems/virtualhostmanager/virtualhostmanager.js
web/html/src/manager/visualization/hierarchy.js
web/spacewalk-web.changes

Update the remaining help bubble URLs in spacewalk-web.
Port of https://github.com/SUSE/spacewalk/pull/7993

Update help URLs in spacewalk-web

---

susemanager-utils/testing/docker/scripts/test_cobbler.sh

Fixes broken cobbler testsuite.
No difference.
- No documentation needed: Just a fix.
- No tests: Fixes the cobbler test execution inside CI
Fixes #

Adjust test execution command.

---

susemanager-utils/susemanager-sls/modules/pillar/suma_minion.py
susemanager-utils/susemanager-sls/susemanager-sls.changes

Port of https://github.com/SUSE/spacewalk/pull/8061

Fix formula name encoding on Python 3 (bsc#1137533) 

---

testsuite/run_sets/uyuni.yml

Disable features/core_proxy_branch_network.feature for Uyuni (until formulas are fixed for Leap 15.1)
No difference.
- No documentation needed: Testsuite change.
- No tests:  Testsuite change.
None

Disable features/core_proxy_branch_network.feature for Uyuni

---

testsuite/documentation/cucumber-steps.md

PR documents possibility to use cookies to store login information instead of logging again using login form. It doesn't modify any functionality of testsuite. 
Purpose of PR is to save this solution for possible future use.
https://github.com/SUSE/spacewalk/issues/7655

Testsuite - store login information via cookies

---

susemanager-utils/susemanager-sls/modules/pillar/suma_minion.py
susemanager-utils/susemanager-sls/susemanager-sls.changes

A regression was introduced after this PR https://github.com/uyuni-project/uyuni/pull/948. This PR fixes that.
No difference.
Before:
After:
- No documentation needed: **Bug fix**
- No tests: **Indentation fixed**
Fixes # https://github.com/SUSE/spacewalk/issues/7975
Tracks # https://github.com/SUSE/spacewalk/pull/7980

Fix the indentation so custom formulas can be read correctly

---

web/html/javascript/susemanager-setup-wizard-mirror-credentials.js

$subj
After:
- No tests: no tests in the old JS area
Tracks https://github.com/SUSE/spacewalk/issues/7896

Disable credentials delete button when credentials are being verified

---

testsuite/run_sets/testsuite.yml

This PR fixes a small error introduced when porting "reposync rationalization" changes to uyuni.

Leftover from cherrypicking

---

java/code/src/com/redhat/rhn/frontend/action/channel/ChannelErrataAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/ChannelPackagesAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/ChannelSubscribedAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/TargetSystemsConfirmAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/AddCustomErrataAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/AddRedHatErrataAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/ChannelPackagesAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/ChannelPackagesAddAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/ChannelPackagesCompareAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/ChannelPackagesCompareMergeAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/ChannelPackagesCompareMergeConfirmAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/ChannelPackagesRemoveAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/ConfirmErrataAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/ErrataCloneAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/ErrataRemoveAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/ListErrataAction.java
java/code/src/com/redhat/rhn/frontend/action/channel/manage/PublishErrataAction.java
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/7891

bsc#1134677 - Keep querystring on ListTag parent_url for actions that have the cid param

---

java/code/src/com/redhat/rhn/manager/action/ActionManager.java
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/8158

bsc#1137144 - Fix profiles package scheduling when epoch is null

---

testsuite/features/step_definitions/command_steps.rb
testsuite/features/step_definitions/common_steps.rb

This PR adapts the test suite to SLE 15 clients for the steps ` I enable repositories before installing Docker' and `I disable repositories after installing Docker.
- Manager 3.2: SUSE/spacewalk#8170
- Manager 4.0: SUSE/spacewalk#8171

Adapt Docker and OS image idempotency steps to SLE 15

---

testsuite/features/step_definitions/common_steps.rb

Fix error in idempotency steps

---

susemanager-sync-data/channel_families.json
susemanager-sync-data/susemanager-sync-data.changes

New Product Classes / Channel Families added for SLES12 SP3 LTSS
Tracks https://github.com/SUSE/spacewalk/pull/8197

sles12 sp3 ltss product classes

---

testsuite/features/step_definitions/common_steps.rb
testsuite/features/step_definitions/docker_steps.rb
testsuite/features/step_definitions/navigation_steps.rb

Port from  https://github.com/SUSE/spacewalk/pull/7462
Copy of https://github.com/uyuni-project/uyuni/pull/942

Speedup xpath port

---

web/html/src/components/formula-selection.js
web/html/src/components/formulas/EditGroup.js
web/html/src/components/formulas/FormulaComponentGenerator.js
web/html/src/components/formulas/PasswordInput.js
web/html/src/manager/admin/config/monitoring-admin.js
web/html/src/manager/admin/setup/products/products.js
web/html/src/manager/audit/cveaudit/cveaudit.js
web/html/src/manager/content-management/shared/components/panels/build/build.js
web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-lifecycle.js
web/html/src/manager/content-management/shared/components/panels/sources/sources.js
web/html/src/manager/groups/formula/group-formula-selection.js
web/html/src/manager/groups/formula/group-formula.js
web/html/src/manager/images/image-import.js
web/html/src/manager/images/image-profile-edit.js
web/html/src/manager/images/image-profiles.js
web/html/src/manager/images/image-stores.js
web/html/src/manager/images/image-view-overview.js
web/html/src/manager/images/image-view-runtime.js
web/html/src/manager/images/image-view.js
web/html/src/manager/minion/formula/minion-formula-selection.js
web/html/src/manager/minion/formula/minion-formula.js
web/html/src/manager/salt/formula-catalog/org-formula-catalog.js
web/html/src/manager/shared/menu/menu.js
web/html/src/manager/systems/bootstrap/bootstrap-minions.js
web/html/src/manager/virtualization/guests/console/guests-console.js
web/html/src/manager/visualization/data-tree.js
web/html/src/manager/visualization/hierarchy.js
web/html/src/manager/visualization/ui/components.js

Various overseen Strings which can be translated added.
No difference.
- No documentation needed: Just enablement of translation.
- No tests: None existent.
Fixes #
Tracks https://github.com/SUSE/spacewalk/issues/1570

Add translation functions where applicable.

---

testsuite/features/step_definitions/common_steps.rb

2nd part of https://github.com/uyuni-project/uyuni/pull/1138
No difference.
Before:
After:
Fixes #

Remove the tool channels reference from the checklist as not supported in uyuni

---

testsuite/features/min_action_chain.feature
testsuite/features/min_activationkey.feature
testsuite/features/min_docker_auth_registry.feature
testsuite/features/min_osimage_build_image.feature
testsuite/features/min_ubuntu_salt.feature

Port of https://github.com/SUSE/spacewalk/pull/8230

Port of Merge some scenarios getting rid of expected timeouts #8230

---

web/html/src/manager/systems/subscribe-channels/subscribe-channels.js
web/spacewalk-web.changes

Change content on client side instead of reloading the page to a specific URL.
No difference.
- No tests: this PR actually fixes some test
Fixes #

Master - fix redirect software assignment

---

web/html/src/components/toastr/toastr.css
web/html/src/components/toastr/toastr.js
web/html/src/manager/content-management/create-project/create-project.js
web/html/src/manager/content-management/list-filters/filter-edit.js
web/html/src/manager/content-management/project/project.js
web/html/src/manager/content-management/shared/components/panels/build/build.js
web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-lifecycle.js
web/html/src/manager/content-management/shared/components/panels/filters-project/filters-project.js
web/html/src/manager/content-management/shared/components/panels/promote/promote.js
web/html/src/manager/content-management/shared/components/panels/properties/properties-edit.js
web/html/src/manager/content-management/shared/components/panels/sources/sources.js

Port of https://github.com/SUSE/spacewalk/pull/8117

Master toastr fixes

---

.github/PULL_REQUEST_TEMPLATE.md
susemanager-utils/testing/automation/spacecmd-unittest.sh

Add CI jobs to run spacecmd unit tests

spacecmd unittest automation runner

---

testsuite/features/step_definitions/common_steps.rb

Fix proxy repos in test suite

---

susemanager/bin/server-migrator.sh

Close unclosed echo at server-migrator.sh
No difference.
None

Close unclosed echo at server-migrator.sh

---

branding/java/code/src/com/redhat/rhn/branding/strings/StringResource_en_US.xml
branding/spacewalk-branding.changes
testsuite/features/srv_mainpage.feature

Set Copyright year to 2019 as requested
Minimal difference.
- No documentation needed: **to minor to document**
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1141598
Tracks https://github.com/SUSE/spacewalk/pull/8407

Copyright date

---

testsuite/features/step_definitions/common_steps.rb

Port of https://github.com/SUSE/spacewalk/pull/8347

Catch an exception inside a repeat_until_timeout

---

testsuite/features/step_definitions/navigation_steps.rb

Port of https://github.com/SUSE/spacewalk/pull/8881

Click button speed up

---

testsuite/features/core_first_settings.feature

Port spacewalk/8965

---

susemanager-utils/testing/docker/scripts/schema_idempotency_test_pgsql.py

Current way to order the migrations is not sufficient. We add just the target version in front of the files which result in the following execution order:
- 4.0.10-...
- 4.0.11-...
- 4.0.1-....
- 4.0.2-....
The result can be failed indempotent test.
This PR bring the files in the correct order and number them with a simple integer
- 0000-...
- 0001-...
- 0002-..
No difference.
- fix unit tests
Tracks

walk the path and order migration files by re-numbering

---

testsuite/features/core_trad_register_client.feature

Port of SUSE/spacewalk/pull/8963
SUSE/spacewalk/issues/6715

Testsuite - Reducing core feature for traditional client

---

backend/satellite_tools/reposync.py

Follow-up of https://github.com/uyuni-project/uyuni/pull/632

Fix: add log when discarding previous comps files

---

java/code/src/com/redhat/rhn/frontend/action/LoginAction.java
java/code/src/com/redhat/rhn/frontend/security/PxtAuthenticationService.java
java/code/src/com/suse/manager/webui/controllers/FrontendLogController.java
web/html/javascript/loggerhead.js
web/html/javascript/spacewalk-essentials.js
web/spacewalk-web.changes

Since I was touching this area I fixed some more problems here:
- IE warning message of an unsupported browser. The prop document.documentMode is only used by IE browsers
- Fix rhn_web_frontend logs for IE.
- Fix rhn_web_frontend logs for Login Page (Added url to UNPROTECTED_URIS)
- Started logging the user-agent string after login 
Each topic corresponds to one commit
@Loquacity I added you just to review the message shown to the user:
"The browser Internet Explorer is not supported. Consider using one of the following browsers: Firefox, Chrome, Edge or Safari"
- No tests.
Fixes  https://github.com/SUSE/spacewalk/issues/7908 https://github.com/SUSE/spacewalk/issues/8302 https://github.com/SUSE/spacewalk/issues/8301 https://github.com/SUSE/spacewalk/issues/8344 …

Add IE unsupported browser warning and loggerhead improvements

---

testsuite/documentation/optional.md
testsuite/features/srv_content_lifecycle.feature
testsuite/features/srv_mainpage.feature

Cosmetical nitpicks:
* added missing test suite documentation
* correct product name capitalizing
* normalized starting column for cucumber @tags
See also SUSE/spacewalk#8972
uyuni only.

Cosmetical: missing documentation, etc.

---

spacewalk/package/spacewalk.changes
spacewalk/package/spacewalk.spec

This is ugly:
zypper se spacewalk-common:
i | spacewalk-common | Spacewalk Systems Management Application with Oracle database backend | Paket
Also do no longer build unneeded/untested package.

Manager no oracle

---

uyuni/base/uyuni-base.changes
uyuni/base/uyuni-base.spec

add /usr/share/rhn to uyuni-base-common

Manager aaa base

---

testsuite/features/srv_content_lifecycle.feature
testsuite/features/step_definitions/common_steps.rb
testsuite/features/step_definitions/navigation_steps.rb
testsuite/features/step_definitions/salt_steps.rb
testsuite/features/support/commonlib.rb

It reverts the deletion of some sleeps reverted on #1001, fixing some mistake with them too.

Fixing small navigation issues, after SPA merged

---

java/code/src/com/redhat/rhn/domain/contentmgmt/ContentFilter.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProjectFactory.java
java/code/src/com/redhat/rhn/domain/contentmgmt/ErrataFilter.java
java/code/src/com/redhat/rhn/domain/contentmgmt/PackageFilter.java
java/code/src/com/redhat/rhn/domain/contentmgmt/test/ContentFilterTest.java
java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerChannelAlignmentTest.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/FilterApiController.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/request/FilterRequest.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/FilterResponse.java
java/spacewalk-java.changes
web/html/src/components/input/Form.js
web/html/src/components/input/Radio.js
web/html/src/manager/content-management/list-filters/filter-form.js
web/html/src/manager/content-management/list-filters/filter.utils.js
web/html/src/manager/content-management/shared/type/filter.type.js
web/spacewalk-web.changes

$subj
The PR contains some refactoring and generalizing code. The refactoring is done on commit-by-commit basis. If you want to follow the refactoring flow, I suggest reviewing commit-by-commit, otherwise feel free just to look at the "after"-state.
After:
https://github.com/SUSE/doc-susemanager/issues/621
Tracks https://github.com/SUSE/spacewalk/issues/8526

CLM: Implement ALLOW filters

---

web/html/src/components/input/Radio.js
web/html/src/manager/content-management/list-filters/filter-form.js

Fix Radio.js html bootstrap structure and alignment
- No tests

Fix Radio.js html bootstrap structure and alignment

---

java/code/src/com/redhat/rhn/frontend/dto/ScheduledAction.java
java/code/src/com/suse/manager/webui/controllers/NotificationMessageController.java
java/code/src/com/suse/manager/webui/controllers/UserLocalizationDateAdapter.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ControllerApiUtils.java
java/spacewalk-java.changes
web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-view.js
web/html/src/manager/notifications/notification-messages.js
web/spacewalk-web.changes

Normalize date formats for actions, notifications and clm.
For the future there are 3 pain points we have to fix transversally on the product:
- Normalize all date formats to use the User Preferences timezone (just like this)
- Refactor the way we handle timezones on the Client (Timepicker of ActionScheduler)
- Give more awareness to the user about timezones. For instance, showing more hints like: this action will be schedule within 2 hours and as @paususe suggested showing a big clock on the header (I like that idea)
- …

bsc#1142774 - Normalize date formats for actions, notifications and clm

---

java/code/src/com/redhat/rhn/domain/contentmgmt/ErrataFilter.java
java/code/src/com/redhat/rhn/domain/contentmgmt/FilterCriteria.java
java/code/src/com/redhat/rhn/domain/contentmgmt/test/ContentFilterTest.java
java/spacewalk-java.changes
web/html/src/manager/content-management/list-filters/filter-form.js
web/html/src/manager/content-management/list-filters/filter.utils.js
web/html/src/manager/content-management/shared/business/filters.enum.js
web/html/src/manager/content-management/shared/type/filter.type.js
web/spacewalk-web.changes

Filter patches by type:
- Product Enhancement Advisory
- Security Advisory
- Bug Fix Advisory
- General doc update for CLM with new Filters needed. See other PRs.
Fixes https://github.com/SUSE/spacewalk/issues/8984
Tracks 

CML: Filter Patches by type

---

java/buildconf/apidoc/docbook/macros.txt
java/buildconf/apidoc/jsp/macros.txt
java/code/src/com/redhat/rhn/domain/contentmgmt/FilterCriteria.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/handler-manifest.xml
java/spacewalk-java.changes

- Add new API endpoint to list available Filter Criteria
- improve API documentation of Filter Criteria
- Fix registration of contentmgmt handler (bsc#1145753)
No difference.
- https://github.com/SUSE/spacewalk/issues/9028
- No tests: **mostly docs**
Fixes https://github.com/SUSE/spacewalk/issues/9083
Tracks https://github.com/SUSE/spacewalk/pull/9085

Improve filter criteria docs

---

testsuite/run_sets/refhost.yml
testsuite/run_sets/virtualization.yml

This PR fixes a few test suite feature paths.
- Manager-3.2  Not appliable
- Manager-4.0 SUSE/spacewalk#9160

Fixed a few feature paths

---

java/spacewalk-java.changes
web/html/src/components/FormulaForm.js
web/html/src/components/formula-selection.js
web/html/src/components/panels/InnerPanel.js
web/html/src/components/section-toolbar/section-toolbar.js
web/html/src/core/spa/spa-renderer.js
web/html/src/manager/admin/setup/products/products.js
web/html/src/manager/notifications/notification-messages.js
web/html/src/manager/shared/spa/spa-engine.js
web/spacewalk-web.changes

No difference.
Before:
After:
Fixes #

SPA - improvements + fixes 

---

client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes
client/rhel/spacewalk-client-tools/src/up2date_client/up2dateAuth.py

Port of # **https://github.com/SUSE/spacewalk/pull/9155**

Refresh cache 5 minutes before actual expiration((bsc#1143562) 

---

testsuite/features/support/custom_formatter.rb

Adapt custom formatter to new gemfile

---

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
java/code/src/com/suse/manager/webui/controllers/VirtualPoolsController.java
web/html/src/components/tree/tree.js
web/html/src/manager/virtualization/guests/create/guests-create.js
web/html/src/manager/virtualization/guests/edit/guests-edit.js

Various fixes related to virtualization.
No difference.
- No documentation needed: only internal bits
- No tests: tiny bits, also fixing flow errors.

Misc fixes

---

susemanager-frontend/susemanager-nodejs-sdk-devel/package.json
susemanager-frontend/susemanager-nodejs-sdk-devel/setup.sh
susemanager-frontend/yarn.lock
web/html/src/package.json
web/html/src/scripts/docker-javascript-lint.sh

@cbosdo feel free to merge this :)
Having the storybook in the package susemanager-nodejs-sdk-devel structured is crashing OBS, because they are too big. Since we don't need them for the OBS build, one solution could be to add them to the package spacewalk-web, but due to the way we import our main dependencies from nodejs-sdk-devel it's not so simple. As far I understood it will be a big mess between the transitive dependencies from nodejs-sdk-devel and storybooks. Ideally, spacewalk-web would include directly the main dependencies it needs, but that would kill our obs build process structure...
The best solution here is to create a new storybook yarn workspace package, that will have the spacewalk-web has a dependency. I am currently working on that, but it will take a bit more time to …

Move all dependencies to nodejs-sdk-devel module and remove the ones we don't need before uploading to OBS

---

backend/satellite_tools/reposync.py
backend/spacewalk-backend.changes

Manager bsc1149633

---

testsuite/run_sets/refhost.yml
testsuite/run_sets/testsuite.yml
testsuite/run_sets/uyuni.yml
testsuite/run_sets/virtualization.yml

Port of https://github.com/SUSE/spacewalk/pull/9401

Testsuite - reference to feature fix

---

client/tools/mgr-cfg/actions/configfiles.py
client/tools/mgr-cfg/mgr-cfg.changes

Port of https://github.com/SUSE/spacewalk/pull/9409

Fix data type issue to correctly decode if needed(bsc#1150320)

---

backend/spacewalk-backend.changes
backend/spacewalk-backend.spec

BuildRequires:  systemd for spacewalk-diskcheck

Manager diskcheck

---

testsuite/features/step_definitions/common_steps.rb

Remove deprecated nagios steps

---

java/scripts/taskomatic
java/spacewalk-java.changes

use default in case taskomatic.java.maxmemory is unset

Manager taskomatic

---

uyuni/base/uyuni-base.spec

Do not build the server package on old distributions.
No difference.
- No tests: **fixes build**

Do not build server package for older distributions

---

backend/spacewalk-backend.spec
java/code/src/com/suse/manager/utils/SaltUtils.java

Small improvements
No difference.
Before:
After:
Fixes #

small improvements

---

java/build.xml
java/buildconf/ivy/ivy-suse.xml
java/conf/eclipse/.settings/org.eclipse.jdt.core.prefs
susemanager-utils/susemanager-sls/src/tests/mockery.py

Few build and test fixes.
No difference.
- No documentation needed: only build and test fixes
- No tests: only build and test fixes
Fixes #

Build fixes

---

java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java

port of https://github.com/SUSE/spacewalk/pull/9570

Log  json if function is null

---

susemanager-utils/susemanager-sls/salt/bootstrap/remove_traditional_stack.sls

Only 1 unless statement is allowed. We need to combine the statements to make it work.
No difference.
- fixes tests
- exists only in master

combine unless staments as only 1 is allowed

---

testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/support/env.rb
testsuite/run_sets/testsuite.yml
testsuite/run_sets/uyuni.yml

Port of https://github.com/SUSE/spacewalk/pull/9683
(Correction of retail feature name is included.)

Testuite - minor fixes for retail features

---

java/code/src/com/redhat/rhn/manager/system/SystemManager.java
java/spacewalk-java.changes

port of https://github.com/SUSE/spacewalk/pull/9706

Match return type with the actual type defined in procedure

---

testsuite/Rakefile

It fixes a missing newline in the testsuite Rakefile.

Missing newline

---

testsuite/documentation/idempotency.md
testsuite/features/secondary/allcli_config_channel.feature
testsuite/features/secondary/allcli_software_channels.feature
testsuite/features/secondary/allcli_software_channels_dependencies.feature
testsuite/features/secondary/min_action_chain.feature
testsuite/features/secondary/min_osimage_build_image.feature
testsuite/features/secondary/min_salt_formulas.feature
testsuite/features/secondary/minssh_action_chain.feature
testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
testsuite/features/secondary/srv_clone_channel_npn.feature
testsuite/features/secondary/srv_cve_audit.feature
testsuite/features/secondary/srv_group_union_intersection.feature
testsuite/features/secondary/srv_power_management.feature
testsuite/features/secondary/trad_action_chain.feature
testsuite/features/secondary/trad_baremetal_discovery.feature
testsuite/features/secondary/trad_config_channel.feature
testsuite/features/secondary/trad_lock_packages.feature
testsuite/features/step_definitions/lock_packages_on_client.rb
testsuite/features/step_definitions/navigation_steps.rb

Port of https://github.com/SUSE/spacewalk/pull/9739
No difference.
Before:
After:
Fixes #

Port - Clean Up scenario to remove systems selected at the end of features affected

---

testsuite/features/step_definitions/navigation_steps.rb

We just look for the text, either as link or plain text.
No difference.
- fixes tests
Tracks https://github.com/SUSE/spacewalk/pull/9788

Fix checkbox checking in lists

---

testsuite/features/secondary/min_action_chain.feature
testsuite/features/secondary/min_salt_install_package.feature
testsuite/features/secondary/min_salt_install_with_staging.feature
testsuite/features/secondary/min_salt_pkgset_beacon.feature
testsuite/features/secondary/min_salt_software_states.feature
testsuite/features/secondary/min_ubuntu_salt_install_package.feature
testsuite/features/secondary/minssh_action_chain.feature
testsuite/features/secondary/minssh_centos_salt_install_package_and_patch.feature
testsuite/features/secondary/srv_cve_audit.feature
testsuite/features/secondary/trad_action_chain.feature
testsuite/features/secondary/trad_check_patches_install.feature
testsuite/features/secondary/trad_inst_package_and_patch.feature
testsuite/features/secondary/trad_need_reboot.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/step_definitions/common_steps.rb

This PR adapts the test suite to new repository names after sumaform refactoring.
Fixes: #9770
4.0: SUSE/spacewalk#9799
3.2: SUSE/spacewalk#9800 

Use new repository names

---

web/html/src/manager/content-management/list-filters/filter-edit.js
web/spacewalk-web.changes

merged in 9173 already. port from 4.0

clp filter edit ui fix

---

java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/response/FilterResponse.java
java/spacewalk-java.changes
web/html/src/manager/content-management/list-filters/list-filters.js
web/spacewalk-web.changes

port of 9608
No difference.
Before:
After:
Fixes #

Fix sorting on content filter list page 

---

java/code/src/com/suse/manager/webui/controllers/contentmanagement/ContentManagementViewsController.java
java/spacewalk-java.changes
web/html/src/manager/content-management/project/project.js
web/spacewalk-web.changes

Check for invalid project name and show better message 

---

testsuite/features/secondary/srv_check_channels_page.feature

Add lost commit again
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/9663

openSUSE Build Service name corrected

---

search-server/spacewalk-search/spacewalk-search.changes
search-server/spacewalk-search/src/config/rhn-search

make rhn-search read rhn.conf for memory 

---

java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
java/code/webapp/WEB-INF/pages/systems/system-remote-command.jsp
java/spacewalk-java.changes
susemanager-utils/susemanager-sls/salt/remotecommands/init.sls
susemanager-utils/susemanager-sls/susemanager-sls.changes

Port of https://github.com/SUSE/spacewalk/pull/9915

Salt remote script timeout bsc1153181

---

web/html/src/manager/groups/formula/group-formula.renderer.js

Fix formula rendering in the system group UI.
No difference.
- No tests: simple fix
Fixes #

Fix formula rendering in system group UI

---

java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java

Enhance debug logging for channels and products
No difference.
- No tests: **just debug logging added**
Tracks https://github.com/SUSE/spacewalk/pull/9551

Enhance channel logging

---

testsuite/documentation/cucumber-steps.md

This PR documents new step `I run .... with logging` in list of useful steps.
Ports
* 4.0 : SUSE/spacewalk#9978
* 3.2 : SUSE/spacewalk#9979

Document new step "I run with logging"

---

backend/spacewalk-backend.changes
backend/spacewalk-backend.spec

add systemd service macros required by buildservice.

Manager diskcheck systemd

---

susemanager-sync-data/additional_products.json
susemanager-sync-data/additional_repositories.json
susemanager-sync-data/susemanager-sync-data.changes
susemanager-utils/susemanager-sls/pillar_data/gpgkeys.yml
susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
susemanager-utils/susemanager-sls/salt/certs/CentOS8.sls
susemanager-utils/susemanager-sls/salt/certs/RES8.sls
susemanager-utils/susemanager-sls/salt/certs/RedHat8.sls
susemanager-utils/susemanager-sls/susemanager-sls.changes
susemanager/src/mgr_bootstrap_data.py
susemanager/susemanager.changes

- add RHEL 8 Base product
- changed RHEL 5, 6 and 7 products to released
- sort products and repositories to have in future smaller diffs
No difference.
- No documentation needed: **already in progress**
- No tests: **metadata change**

Rhel es 8 preparation

---

search-server/spacewalk-search/spacewalk-search.changes

Add a bugnumber to changelog
Tracks https://github.com/SUSE/spacewalk/pull/10051

add bugnumber to changelog

---

java/code/src/com/redhat/rhn/manager/system/VirtualizationActionCommand.java
java/code/src/com/suse/manager/webui/websocket/VirtNotifications.java
web/html/javascript/susemanager-translate.js
web/html/src/.storybook/preview-head.html
web/html/src/components/dialog/ActionConfirm.js
web/html/src/components/dialog/dialog.stories.js
web/html/src/components/input/Radio.js
web/html/src/manager/content-management/shared/components/panels/properties/properties-view.js
web/html/src/manager/virtualization/guests/list/guests-list.js
web/html/src/manager/virtualization/pools/list/pools-list.js

Add various refactoring in the virtualization JS and Java code to prepare for the virtualization pool actions PR (#1166).
Also fixes storybook.
No difference.
- No documentation needed: refactoring only
- No tests: refactoring only

Virt misc refactoring

---

testsuite/features/step_definitions/command_steps.rb
testsuite/features/upload_files/ubuntu-set-netplan.sh

Make sure Ubuntu minion does not get everything twice via DHCP

---

testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature

Check that we are on right formulas page

---

spacewalk/config/etc/httpd/conf.d/zz-spacewalk-www.conf
spacewalk/config/spacewalk-config.changes
spacewalk/config/spacewalk-config.spec

Enable Apache compression for static files.
The pictures below (before/after) reports an example for just one file, but it is valid for all files with the following types:
- text/html
- text/plain
- text/xml
- text/css
- text/javascript
- application/javascript
Highlight on the `Transferred` value: the diff between the `size` value and the `transferred` one means how much network bandwidth we save downloading static files when they are compressed:
- `vendors.bundle.js` before: size = 834.43 KB , **transferred 835 KB**
- `vendors.bundle.js` after: size = 834.43 KB, **transferred 244.17 KB**
Before:
After:
- No documentation needed: hidden technical detail
- No tests: nothing to test
Fixes https://github.com/SUSE/spacewalk/issues/7887
Tracks # TODO …

Enable apache compression for static files

---

testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
testsuite/features/step_definitions/navigation_steps.rb

Port of https://github.com/SUSE/spacewalk/pull/10135

Testsuite - save of bind formula check

---

testsuite/features/secondary/min_salt_install_with_staging.feature

Reorder the cleanup of "install with staging" tests

---

java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectApiController.java
java/spacewalk-java.changes
web/html/src/manager/content-management/shared/components/panels/properties/properties-form.js
web/html/src/manager/content-management/shared/components/panels/properties/properties-view.js
web/spacewalk-web.changes

Change form order on clp page

---

web/html/src/manager/content-management/shared/components/panels/environment-lifecycle/environment-lifecycle.js
web/spacewalk-web.changes

Add environment label when deleting environment

---

utils/spacewalk-manage-channel-lifecycle
utils/spacewalk-utils.changes

Backport of https://github.com/SUSE/spacewalk/commit/3177a038c9116cfc114ab970111f7ba906008e7f

Isbm lifecycle management fqdn bsc 1153578

---

branding/java/code/src/com/redhat/rhn/branding/strings/StringResource_en_US.xml
branding/spacewalk-branding.changes
java/code/src/com/redhat/rhn/frontend/action/channel/manage/DeleteChannelAction.java
java/code/src/com/redhat/rhn/frontend/struts/RhnAction.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/test/ChannelSoftwareHandlerTest.java
java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/10192

Master - ISE deleting clm channels

---

backend/common/rhnConfig.py
backend/spacewalk-backend.changes

fix for https://bugzilla.suse.com/show_bug.cgi?id=1158283
No difference.
- No documentation needed: Issue only results in a warning in the logfiles
- No tests: 
Fixes #10216

Manager bsc1158283

---

testsuite/features/reposync/srv_sync_channels.feature

This PR fixes previous PRs by choosing a test package that lives on the very minimalistic mirror we have.
Ports:
* 3.2: SUSE/spacewalk#10263
* 4.0: SUSE/spacewalk#10262

More things that are not available on minima mirror

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/auth/AuthHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/auth/test/AuthHandlerTest.java
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/10226

Add a method in api to check if the provided session is a valid one

---

testsuite/features/reposync/srv_enable_sync_products.feature
testsuite/features/reposync/srv_sync_products.feature

Make sync work with products we have on the mirror
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/10269

use products available on the mirror

---

java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java

Port of https://github.com/SUSE/spacewalk/pull/9599

change log message from error to debug

---

.github/labeler.yml

Playing with labeler in order to generate the labels as they should. Test on my fork, it seems to work now.
No difference.
- No documentation needed:  CI Change
- No tests: Tested on my fork
None

Add recursivity to the labeler

---

java/code/webapp/WEB-INF/pages/rhnpackage/packagedetail.jsp

By accident changed the wrong key

changed the wrong key

---

susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.changes
susemanager-utils/supportutils-plugin-susemanager-client/susemanagerclient
susemanager-utils/supportutils-plugin-susemanager-proxy/supportutils-plugin-susemanager-proxy.changes
susemanager-utils/supportutils-plugin-susemanager-proxy/susemanagerproxy

rhncfg-actions has been renamed to mgr-cfg-actions
No difference.
- No documentation needed: Internal only
- No tests: Just supportconfig data

Manager cfg actions

---

testsuite/features/init_clients/sle_minion.feature

Small fix in step name.
Ports
3.2
4.0

Fix step name

---

testsuite/documentation/cucumber-steps.md

This PR
* fixes a ruby error in doc
* removes a dead link
Ports:
* 3.2:
* 4.0:

Minor test suite doc fixes

---

java/conf/rhn_java.conf
java/spacewalk-java.changes
java/spacewalk-java.spec

Introduce new product_tree tags
- SUMA4.1
- Beta
No difference.
- No tests: **needed for beta testing**
Fixes partly https://github.com/SUSE/spacewalk/issues/10058

Prepare beta 41

---

testsuite/Gemfile

https://github.com/uyuni-project/uyuni/network/alert/testsuite/Gemfile/rack/open

Upgrade rack - CVE-2019-16782

---

susemanager-frontend/susemanager-nodejs-sdk-devel/package.json

Fixing package building with the new storybook dependencies.
No difference.
- No documentation needed: internal
- No tests: Fixing test failure
Fixes #

Fix yarn packages to remove

---

testsuite/features/secondary/srv_content_lifecycle.feature
testsuite/features/step_definitions/common_steps.rb

This PR does various test suite fixes:
* update content lifecycle test to SLE 12 SP5
* fix wrong variable name in credentials test
Ports:
* 4.0: SUSE/spacewalk#10520
No 3.2

Content lifecycle

---

testsuite/run_sets/secondary.yml
testsuite/run_sets/secondary_parallelizable.yml
testsuite/run_sets/testsuite.yml
testsuite/run_sets/uyuni.yml

This PR:
* re-adds features that we lost while splitting `testsuite.yml` into several files;
* adds new features that people forgot to put in all yaml files.
Fixes: SUSE/spacewalk#10512
Ports:
* 3.2: SUSE/spacewalk#10510
* 4.0: SUSE/spacewalk#10509

Some feature tests were somehow lost

---

testsuite/features/secondary/minkvm_guests.feature
testsuite/features/secondary/minxen_guests.feature
testsuite/features/secondary/srv_content_lifecycle.feature
testsuite/features/step_definitions/content_lifecycle_steps.rb
testsuite/features/step_definitions/datepicker_steps.rb
testsuite/features/support/lavanda.rb
testsuite/features/support/ssh.rb
testsuite/features/support/xmlrpc_actionchain.rb
testsuite/features/support/xmlrpc_activationkey.rb
testsuite/features/support/xmlrpc_api.rb
testsuite/features/support/xmlrpc_channel.rb
testsuite/features/support/xmlrpc_cve_search.rb
testsuite/features/support/xmlrpc_image.rb
testsuite/features/support/xmlrpc_schedule.rb
testsuite/features/support/xmlrpc_system.rb
testsuite/features/support/xmlrpc_user.rb
testsuite/features/support/xmlrpc_vhm.rb
testsuite/features/support/xmlrpctest.rb

Cleanup:
* remove more unused files
* fix copyright mentions
Ports:
* 3.2: SUSE/spacewalk#10540
* 4.0: SUSE/spacewalk#10539

Some more cleanup

---

java/buildconf/build-props.xml
java/spacewalk-java.spec

A lot of java libs have changed in SLES 15 SP2.
Try to keep things building.
No difference.
- No tests: **fix building**

Java dependencies for sp2

---

testsuite/features/secondary/srv_organization_credentials.feature

This PR waits until the dialog box has at least displayed the expected text.
Ports:
* 3.2: SUSE/spacewalk#10554
* 4.0: SUSE/spacewalk#10553

Give the dialog box time to display

---

testsuite/features/init_clients/sle_minion.feature
testsuite/features/secondary/min_bootstrap_negative.feature
testsuite/features/secondary/min_bootstrap_script.feature
testsuite/run_sets/secondary_parallelizable.yml
testsuite/run_sets/testsuite.yml
testsuite/run_sets/uyuni.yml

Port of https://github.com/SUSE/spacewalk/pull/10528

Testsuite: Make core features lighter

---

testsuite/documentation/code-coverage.md
testsuite/documentation/cucumber-steps.md
testsuite/features/secondary/srv_users.feature
testsuite/features/step_definitions/navigation_steps.rb
testsuite/features/step_definitions/salt_steps.rb
testsuite/features/step_definitions/security_steps.rb

This PR removes some dead code (not all, there's probably more).
Ports:
* 3.2: SUSE/spacewalk
* 4.0: SUSE/spacewalk

Remove dead code

---

testsuite/features/secondary/srv_content_lifecycle.feature

In content lifecycle management, the output after build has changed. This PR adapts the test suite.

Use '>' as separator instead of '-'

---

testsuite/features/step_definitions/salt_steps.rb

- Add support for ubuntu in one step
This is a port of https://github.com/SUSE/spacewalk/pull/10618

Testuite: Port of SUSE/spacewalk#10618

---

susemanager-utils/dracut-mgrbootstrap/dracut-mgrbootstrap.changes
susemanager-utils/dracut-mgrbootstrap/dracut-mgrbootstrap.spec
susemanager-utils/dracut-mgrbootstrap/mgrbootstrap/module-setup.sh

Detect which release package is available to identify the distribution.
No difference.
- No tests: **either it build or not**

support SLES as well as openSUSE distros

---

testsuite/features/secondary/srv_content_lifecycle.feature

This PR accomodates for different channel lists with Uyuni.
Uyuni only, no ports.

Different button on Uyuni

---

utils/spacewalk-common-channels.ini
utils/spacewalk-utils.changes

Add OEL 8 repositories
No difference.
Before:
After:
Fixes #

Add Oracle Enterprise Linux 8 repositories to spacewalk-common-channels

---

testsuite/features/step_definitions/common_steps.rb

This PR removes experimental code.
uyuni only.

Revert experimental display

---

java/buildconf/LICENSE.txt

Update Java license text template for 2020
- Checkstyle test

Update Java license text template for 2020

---

spacewalk/certs-tools/rhn-ssl-tool.sgml
spacewalk/certs-tools/spacewalk-certs-tools.changes

Manager bsc1010746

---

testsuite/features/init_clients/sle_ssh_minion.feature
testsuite/features/qam/init_clients/sle11sp4_ssh_minion.feature
testsuite/features/qam/init_clients/sle12sp4_ssh_minion.feature
testsuite/features/qam/init_clients/sle15_ssh_minion.feature
testsuite/features/qam/init_clients/sle15sp1_ssh_minion.feature
testsuite/features/secondary/minssh_bootstrap_xmlrpc.feature

Port of https://github.com/SUSE/spacewalk/pull/10690

Testsuite - workaround decription for bsc#1124634

---

java/code/src/com/suse/manager/reactor/PGEventStream.java

It is expected to fix the compilation problem seen in:
https://build.opensuse.org/package/show/systemsmanagement:Uyuni:Master/spacewalk-java
No difference.
- No documentation needed: **internal fix**
- No tests: **covered**

pgjdbc-ng 0.8.3 compatibility fix

---

client/rhel/dnf-plugin-spacewalk/actions/packages.py
client/rhel/dnf-plugin-spacewalk/dnf-plugin-spacewalk.changes
client/rhel/rhnlib/rhnlib.spec
java/code/src/com/redhat/rhn/manager/kickstart/KickstartFormatter.java
java/spacewalk-java.changes

Cherry pick changes from spacewalk which may be usefull for uyuni as well.
No difference.
- No tests: **sw had no tests**

Spacewalk cherry pick 20200209

---

susemanager/src/mgr_bootstrap_data.py
susemanager/susemanager.changes

Data to generate bootstrap repos for SLE15 SP2 family
No difference.
Tracks:
- https://github.com/SUSE/spacewalk/pull/10706
- https://github.com/SUSE/spacewalk/pull/10707

Bootstrap data sle15 sp2

---

branding/spacewalk-branding.changes

Changelog for https://github.com/uyuni-project/uyuni/commit/d5e4d20680252551ef69c102524dfce5121d0d0e

Changelog for patch colors icon

---

rel-eng/packages/susemanager
susemanager/src/mgr_bootstrap_data.py
susemanager/susemanager.changes
susemanager/susemanager.spec

Merge fix for bsc#1164563 from Manager-4.1-beta1

Merge fix for bsc#1164563 from Manager-4.1-beta1

---

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_bn_IN.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ca.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_de.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_es.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_fr.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_gu.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_hi.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_it.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ja.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ko.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_pa.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_pt_BR.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ru.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ta.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_uk.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_zh_CN.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_zh_TW.xml
java/spacewalk-java.changes

use term 'patch' instead of 'errata' (bsc#1164649)
Before: "Enable Errata E-mail Notifications (for users belonging to this organization)"
After: "Enable Patch E-mail Notifications (for users belonging to this organization)"
- No documentation needed: Branding issue
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1164649

Manager bsc1164649

---

susemanager-sync-data/additional_products.json

Fix typos.
No difference.
- No documentation needed: **follow up of another PR**
- No tests: **follow up of another PR**
Tracks https://github.com/SUSE/spacewalk/pull/10802 https://github.com/SUSE/spacewalk/pull/10801

fix typos in OES 2018 SP2 product repositories

---

java/code/src/com/suse/manager/reactor/utils/OptionalTypeAdapterFactory.java
java/spacewalk-java.changes

port of https://github.com/SUSE/spacewalk/pull/10834

Change empty strings to optional.empty

---

java/code/src/com/suse/manager/reactor/utils/OptionalTypeAdapterFactory.java

Use more specific exception so we don't catch everything. 
No difference.
- No documentation needed: **nothing to document**
- No tests: **just manual tested it**
Fixes #

Use more specific exception so we don't catch everything

---

java/buildconf/ivy/ivy-suse.xml

Port of https://github.com/SUSE/spacewalk/pull/10854

Update salt-netapi-client jar version

---

utils/spacewalk-utils.changes

Port of https://github.com/SUSE/spacewalk/pull/10872

Add the bug entry for bsc1151583

---

java/code/src/com/redhat/rhn/domain/action/ActionFactory.java
java/code/src/com/redhat/rhn/domain/action/Action_legacyUser.hbm.xml
java/code/src/com/redhat/rhn/domain/action/virtualization/VirtualizationCreateAction.java
java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/code/src/com/redhat/rhn/manager/system/VirtualizationActionCommand.java
java/code/src/com/redhat/rhn/manager/system/test/VirtualizationActionCommandTest.java
java/code/src/com/suse/manager/webui/controllers/VirtualGuestsController.java
java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
java/code/src/com/suse/manager/webui/websocket/VirtNotifications.java
java/spacewalk-java.changes
web/html/src/components/action/ActionStatus.js
web/html/src/components/action/ActionStatus.stories.js
web/html/src/manager/virtualization/guests/list/guests-list.js
web/html/src/manager/virtualization/useVirtNotification.js
web/spacewalk-web.changes

Add a message in the ''Virtualization > Guests'' tab if a VM creation action is not complete.
Simply a new information message
- No documentation needed:  Just a new information message
- No tests: impossible to add a reliable test since the notification disappears when the guest is created. The test suite may not be fast enough to catch it
Fixes SUSE/spacewalk#9585

Virt guest create notif

---

java/code/src/com/suse/manager/virtualization/VirtManager.java
java/code/src/com/suse/manager/webui/controllers/VirtualNetsController.java
java/code/src/com/suse/manager/webui/controllers/VirtualPoolsController.java

Small Virtualization Java code refactoring needed for the pool actions PR.
No difference.
- No documentation needed: No UI change
- No tests: covered by existing tests
Fixes #

Virt java refactoring

---

web/html/src/manager/virtualization/ActionApi.js
web/html/src/manager/virtualization/guests/properties/guest-properties-form.js
web/html/src/manager/virtualization/guests/virtualization-guest-action-api.js
web/html/src/manager/virtualization/pools/virtualization-pools-list-refresh-api.js

Small refactoring in the virtualization JS code needed for the virtualization pool actions PR
No difference.
- No documentation needed: no UI change
- No tests: covered by existing tests
Fixes #

Virt js refactoring

---

spacewalk/package/spacewalk.changes
spacewalk/setup/spacewalk-setup.changes

Created bugreports and added the numbers to the changelogs

Fix missing bugnumbers

---

java/buildconf/checkstyle.xml
java/buildconf/ivy/ivy-suse.xml
java/buildconf/ivy/ivyconf.xml
java/code/src/com/redhat/rhn/common/hibernate/HibernateFactory.java
java/code/src/com/redhat/rhn/domain/server/PinnedSubscriptionFactory.java
java/code/src/com/redhat/rhn/frontend/action/configuration/ssm/UnsubscribeConfirmSubmitAction.java
java/code/src/com/redhat/rhn/frontend/dto/BootstrapSystemOverview.java
java/code/src/com/redhat/rhn/frontend/dto/SetupWizardProductDto.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/util/SerializerHelper.java
java/code/src/com/redhat/rhn/manager/configuration/ConfigurationManager.java
java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
java/code/src/com/redhat/rhn/manager/system/VirtualInstanceManager.java
java/code/src/com/redhat/rhn/taskomatic/task/repomd/RepomdIndexWriter.java
java/code/src/com/suse/manager/reactor/utils/ZonedDateTimeISOAdapter.java
java/code/src/com/suse/manager/webui/controllers/NotificationMessageController.java
java/code/src/com/suse/manager/webui/controllers/StatesAPI.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java
java/code/src/com/suse/manager/webui/services/SaltActionChainGeneratorService.java
java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
java/code/src/com/suse/manager/webui/services/impl/MonitoringService.java
java/code/src/com/suse/manager/webui/utils/gson/BootstrapHostsJson.java
java/code/src/com/suse/manager/webui/utils/salt/State.java
susemanager-utils/testing/docker/master/uyuni-master-base/add_packages.sh

Update checkstyle to 8.30 (latest version)
No difference.
- No documentation needed: tooling update
- No tests: tooling update
Fixes #

Checkstyle update

---

backend/common/Makefile

Fixes broken build.
No difference.
Before:
After:
Fixes #

Add missing file for common lib

---

client/tools/mgr-cfg/mgr-cfg.changes

Add missing changelog entry
No difference.
- No documentation needed: changelog IS documentation
- No tests: changelog change
Fixes #

Add mgr-cfg changelog

---

spacewalk/setup/spacewalk-setup.changes

Add missing bug number to `spacewalk-setup.changes`
No difference.
- No documentation needed: internal change
Tracks https://github.com/SUSE/spacewalk/pull/10969

Update spacewalk-setup.changelog to add bsc#1166388

---

java/code/src/com/suse/manager/webui/templates/minion/minion-header.jade
java/code/webapp/WEB-INF/pages/common/fragments/systems/system-header.jspf

Fix a typo in a label
Change of the label value
- No documentation needed: already in
- No tests: typo fix
Already fixed in Manager-4.0

Fix: typo in system locked

---

java/code/src/com/redhat/rhn/frontend/struts/BaseSetHelper.java
java/spacewalk-java.changes

port of https://github.com/SUSE/spacewalk/pull/10628
*

fix ise when clicking on ss

---

README.md

Fix links for IRC and mailing lists
No difference.
- No documentation needed: This is just an update for the main README.
- No tests: This is just an update for the main README.
Fixes #2031 

Fix links for IRC and mailing lists

---

spacewalk/package/spacewalk.spec

Fix version check in specfile to get correct dependencies.
No difference.
- Fixes https://github.com/SUSE/spacewalk/issues/10921

fix version check in spec

---

java/spacewalk-java.changes

Add missing changelog entry
No difference.
- No documentation needed: changelog change
- No tests: changelog change
Fixes #

Add changelog

---

testsuite/features/secondary/min_recurring_action.feature
testsuite/features/step_definitions/common_steps.rb
testsuite/features/step_definitions/datepicker_steps.rb
testsuite/run_sets/secondary.yml
web/html/src/components/picker/recurring-event-picker.js

Cucumber tests for the recurring actions feature
No difference.
- No documentation needed: This is just tests
Tracks # https://github.com/SUSE/spacewalk/issues/10940

Recurring Actions Cucumber tests

---

testsuite/features/upload_files/massive-import-terminals.yml

Forgotten second commit of #2051.

Add bind option "empty-zones-enable no"

---

susemanager-utils/susemanager-sls/salt/services/kiwi-image-server.sls
susemanager-utils/susemanager-sls/salt/util/syncmodules.sls

Fix for indentation in sls files.
No difference.
- No documentation needed: This is just a non-visible fix.
- No tests: Already covered

Fix for indentation in sls files

---

java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java

To prevent potential NPEs.
No difference.
- Additional commit to #1995 

filter products without channel family in hasToolsChannelSubscription

---

spacewalk/admin/uyuni-check-database.service

Take care that the database is started before we check it.
No difference.

run uyuni-check-database after postgresql is started

---

java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
java/code/src/com/redhat/rhn/frontend/dto/ShortSystemInfo.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ShortSystemInfoSerializer.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
java/code/src/com/redhat/rhn/manager/system/SystemManager.java
java/spacewalk-java.changes

Introduce a new serializer with a subset of field from the SystemOverviewSerializer.
No difference.
- No tests

use appropriate serializer with correct documentation (bsc#1168083)

---

java/code/src/com/redhat/rhn/frontend/action/schedule/PendingActionsSetupAction.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/schedule/ScheduleHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/schedule/test/ScheduleHandlerTest.java
java/code/src/com/redhat/rhn/manager/action/ActionManager.java
java/code/src/com/redhat/rhn/manager/action/test/ActionManagerTest.java
java/code/src/com/suse/manager/webui/controllers/ImageBuildController.java
java/code/src/com/suse/manager/webui/controllers/VirtualPoolsController.java
java/code/src/com/suse/manager/webui/controllers/test/VirtualPoolsControllerTest.java
java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
java/code/src/com/suse/manager/webui/utils/MinionActionUtils.java
java/code/src/com/suse/manager/webui/utils/gson/ScheduledRequestJson.java
java/code/src/com/suse/manager/webui/utils/gson/SsmScheduleChannelChangesJson.java
java/code/src/com/suse/manager/webui/utils/gson/SubscribeChannelsJson.java
java/code/src/com/suse/manager/webui/utils/gson/VirtualGuestsBaseActionJson.java
java/code/src/com/suse/manager/webui/utils/gson/VirtualGuestsUpdateActionJson.java
java/code/src/com/suse/manager/webui/utils/gson/VirtualPoolBaseActionJson.java

Tiny refactoring split from for PR #2006
No difference.
- No documentation needed: only java code refactoring
- No tests: should be covered already
Fixes #

Tiny refactorings

---

testsuite/features/secondary/min_centos_monitoring.feature
testsuite/features/secondary/min_monitoring.feature
testsuite/features/step_definitions/navigation_steps.rb
testsuite/run_sets/secondary_parallelizable.yml

- Add a test for the monitoring feature.
(https://github.com/SUSE/spacewalk/issues/10991)
Manager-4.0: https://github.com/SUSE/spacewalk/pull/11184

Testsuite: Add test for monitoring feature

---

testsuite/features/secondary/min_monitoring.feature

Fix monitoring test:  enable the right repository for the feature.

Testsuite: Use the right repository

---

java/buildconf/apidoc/asciidoc/apiindex.txt
java/buildconf/apidoc/asciidoc/handler.txt
java/buildconf/apidoc/asciidoc/macros.txt
java/code/internal/src/com/redhat/rhn/internal/doclet/ApiCall.java
java/code/internal/src/com/redhat/rhn/internal/doclet/AsciidocWriter.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/activationkey/ActivationKeyHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/api/ApiHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/chain/ActionChainHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/access/ChannelAccessHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/configchannel/ConfigChannelHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/errata/ErrataHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/image/ImageInfoHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/KickstartHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/profile/ProfileHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/profile/software/SoftwareHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/profile/system/SystemDetailsHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/org/OrgHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/packages/PackagesHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/proxy/ProxyHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/recurringaction/RecurringActionHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/sync/master/MasterHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/config/ServerConfigHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/crash/CrashHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/scap/SystemScapHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/user/external/UserExternalHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/virtualhostmanager/VirtualHostManagerHandler.java
java/manager-build.xml

Fixes for the apidoc bugs mentioned in the review meeting
No difference.
- No documentation needed: this IS doc
- No tests: doc
Fixes #

Apidoc fixes

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/XmlRpcSystemHelper.java
java/code/src/com/suse/manager/webui/controllers/MinionsAPI.java
java/code/src/com/suse/manager/webui/controllers/utils/AbstractMinionBootstrapper.java
java/code/src/com/suse/manager/webui/controllers/utils/RegularMinionBootstrapper.java
java/code/src/com/suse/manager/webui/controllers/utils/SSHMinionBootstrapper.java
java/code/src/com/suse/manager/webui/controllers/utils/test/AbstractMinionBootstrapperTestBase.java
java/code/src/com/suse/manager/webui/controllers/utils/test/RegularMinionBootstrapperTest.java
java/code/src/com/suse/manager/webui/services/iface/SystemQuery.java
java/code/src/com/suse/manager/webui/utils/InputValidator.java
java/code/src/com/suse/manager/webui/utils/gson/BootstrapHostsJson.java
java/code/src/com/suse/manager/webui/utils/gson/BootstrapParameters.java
java/code/src/com/suse/manager/webui/utils/test/InputValidatorTest.java
java/spacewalk-java.changes
web/html/src/manager/systems/bootstrap/bootstrap-minions.js
web/spacewalk-web.changes

Commit-by-commit. Read the commit messages as well please.
The contents can be divided into 2 parts:
Previously `BootstrapHostsJson` was used in both Web UI and XMLRPC. This class
was originally intended to be used in the Web UI only, to back the data passed
from the frontend client.
In this PR this is changed and the `BootstrapParameters` class is used for the
bootstrap parameters passing (from UI/XMLRPC to the backend).
aka the main point of this PR. This part consists of:
* change the `BootstrapHostsJson` to accept the auth method parameter and ssh
key/passphrase
* implement the new UI for passing the ssh key/passphrase to the backend
Before:
(different style because a screenshot from SUSE Manager 3.2 was used)
After:
- https://github.com/uyuni-project/uyuni-docs/pull/211
- Cucumber …

Bootstrap minions using an SSH private key via Web UI

---

java/code/src/com/redhat/rhn/common/messaging/MessageQueue.java
java/code/src/com/redhat/rhn/frontend/action/errata/test/ChannelActionTest.java
java/code/src/com/redhat/rhn/taskomatic/core/SchedulerKernel.java
java/code/src/com/redhat/rhn/taskomatic/task/MinionActionChainExecutor.java
java/code/src/com/redhat/rhn/taskomatic/task/MinionActionExecutor.java
java/code/src/com/redhat/rhn/testing/RhnBaseTestCase.java
java/code/src/com/redhat/rhn/webapp/RhnServletListener.java
java/code/src/com/suse/manager/reactor/SaltReactor.java

Fix channel change issues with salt-ssh clients probably caused by https://github.com/SUSE/spacewalk/pull/11234 and https://github.com/uyuni-project/uyuni/pull/2116
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/11278

Uyuni channel changed event

---

testsuite/features/support/env.rb

Continuation of preceding simplecov PR.
Backports:
* 4.0: SUSE/spacewalk#11319
* 3.2: SUSE/spacewalk#11318

Commenting out simplecov

---

susemanager-utils/testing/docker/master/Makefile

rebuild containers

---

java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
java/code/src/com/redhat/rhn/domain/rhnpackage/PackageFactory.java
java/code/src/com/redhat/rhn/domain/state/StateFactory.java
java/code/src/com/redhat/rhn/domain/state/test/StateFactoryTest.java
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/PackageStateSerializer.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
java/code/src/com/redhat/rhn/manager/rhnpackage/PackageManager.java
java/code/src/com/redhat/rhn/manager/rhnpackage/test/PackageManagerTest.java
java/code/src/com/redhat/rhn/manager/system/SystemManager.java
java/code/src/com/suse/manager/reactor/messaging/ChannelsChangedEventMessageAction.java
java/code/src/com/suse/manager/reactor/messaging/RegistrationUtils.java
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/11222

Add new Api endpoints for package state

---

java/spacewalk-java.changes

Fix spacewalk-java changes file from an incomplete previous merge.
No difference.
- No documentation needed: internal changes
- No tests neeeded
Fixes #

Fix spacewalk-java changes files from imcomplete previous merge

---

java/code/src/com/suse/manager/reactor/messaging/RegistrationUtils.java

Port of https://github.com/SUSE/spacewalk/pull/11345

generate package state always

---

java/code/src/com/redhat/rhn/domain/formula/FormulaFactory.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/formula/FormulaHandler.java
java/code/src/com/redhat/rhn/manager/formula/test/FormulaManagerTest.java
java/code/src/com/redhat/rhn/manager/system/SystemManager.java
java/code/src/com/redhat/rhn/manager/system/entitling/SystemEntitler.java
java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
java/code/src/com/suse/manager/reactor/test/RegisterMinionActionTest.java
java/code/src/com/suse/manager/utils/SaltUtils.java
java/code/src/com/suse/manager/webui/controllers/FormulaController.java
java/spacewalk-java.changes

port of spacewalk 10196
Fixes #

Check for formula when adding to system/group 

---

java/code/src/com/redhat/rhn/domain/action/salt/build/ImageBuildAction.java
java/code/src/com/redhat/rhn/domain/image/ImageProfile.java
java/code/src/com/suse/manager/webui/controllers/ImageProfileController.java
java/spacewalk-java.changes
web/html/src/manager/images/image-build.js
web/html/src/manager/images/image-profile-edit.js
web/spacewalk-web.changes

This PR addresses some regressions on image management UI
Fixes https://github.com/SUSE/spacewalk/issues/10538
https://bugzilla.suse.com/1170046
https://bugzilla.suse.com/1169773

Image management forms fixes

---

web/spacewalk-web.changes

Update changelog file for https://github.com/uyuni-project/uyuni/commit/40fc100f05a5afc2b29bc87fcbd078598f3afa04.
No difference.
- No tests:

Update spacewalk-web.changes file

---

susemanager-utils/susemanager-sls/salt/bootstrap/remove_traditional_stack.sls

Port the commit d21bb651e12e8333926b5ba5ab166512df8a22ae

Keep suseRegisterInfo on proxies

---

susemanager-utils/susemanager-sls/susemanager-sls.changes

Add missing changelog entry for https://github.com/uyuni-project/uyuni/pull/2191
No difference.
- No tests: Only change log
Fixes # SUSE/spacewalk#11424

add missing changelog entry

---

java/code/src/com/redhat/rhn/domain/server/MinionIds.java
java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java
java/code/src/com/redhat/rhn/domain/server/ServerGroup.hbm.xml
java/code/src/com/redhat/rhn/domain/server/ServerGroupFactory.java
java/code/src/com/redhat/rhn/domain/server/Server_legacyUser.hbm.xml
java/code/src/com/suse/manager/webui/controllers/MinionController.java
java/spacewalk-java.changes

Improve performance for SystemGroupDetail>States view.
No difference.
- Unit tests exist already
Fixes #
Tracks https://github.com/SUSE/spacewalk/pull/10412

Improve performance for 'States' view in SystemGroups detail view

---

susemanager-sync-data/additional_products.json
susemanager-sync-data/channel_families.json
susemanager-sync-data/susemanager-sync-data.changes

update sync-data with centos and oracle products.
No difference.
- No tests

Sync data centos oracle

---

java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemGroup_queries.xml
java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
java/code/src/com/redhat/rhn/domain/dto/FormulaData.java
java/code/src/com/redhat/rhn/domain/dto/SystemGroupID.java
java/code/src/com/redhat/rhn/domain/dto/SystemGroupsDTO.java
java/code/src/com/redhat/rhn/domain/dto/SystemIDInfo.java
java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
java/code/src/com/redhat/rhn/domain/server/ServerGroupFactory.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/HandlerFactory.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/test/ChannelSoftwareHandlerTest.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/formula/FormulaHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/FormulaDataSerializer.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SystemGroupsDTOSerializer.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
java/code/src/com/redhat/rhn/manager/action/test/MinionActionManagerTest.java
java/code/src/com/redhat/rhn/manager/formula/FormulaManager.java
java/code/src/com/redhat/rhn/manager/formula/test/FormulaManagerTest.java
java/code/src/com/redhat/rhn/manager/system/SystemManager.java
java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
java/spacewalk-java.changes

Adds 3 new endpoints in the API to be used by the prometheus service discovery. These are:
endpoint 1 - retrieving system group info for systems with a given entitlement
endpoint 2 - retrieving combined formula data for a list of systems and a given formula name
endpoint 3 - retrieving network information for a list of systems
This was tested in a dump of 30k systems, and for retrieving the required information for a set of 1k systems, it takes:
endpoint 1: ~2 seconds
endpoint 2: ~2 seconds
endpoint 3: ~2 minutes 40 seconds
The implementation for the "endpoint 3" to retrieve network information is a naive implementation at the moment, and it needs to be refactored for achieving a better performance. This refactor is not trivial, and it will probably involved several changes in the …

API endpoints for the prometheus service discovery

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SystemGroupsDTOSerializer.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java

Fix the xmlrpc api doc in system handler
No difference.
- No tests needed for it

Fix xmlrpc api doc in system handler

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/formula/FormulaHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/FormulaDataSerializer.java

Fix the API docs for formula handler
No difference.
- No tests needed
Fixes #

Fix api docs for formula handler

---

java/code/src/com/redhat/rhn/common/db/datasource/CachedStatement.java
java/code/src/com/redhat/rhn/common/db/datasource/xml/Channel_queries.xml
java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
java/code/src/com/redhat/rhn/domain/errata/AbstractErrata.java
java/code/src/com/redhat/rhn/domain/errata/Errata.java
java/code/src/com/redhat/rhn/domain/errata/ErrataFactory.java
java/code/src/com/redhat/rhn/domain/errata/impl/UnpublishedErrata.java
java/code/src/com/redhat/rhn/frontend/events/test/CloneErrataActionTest.java
java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java
java/code/src/com/redhat/rhn/manager/errata/cache/ErrataCacheManager.java
java/spacewalk-java.changes

Revert "Merge pull request #2201 from uyuni-project/faster-clm"

---

utils/spacewalk-common-channels.ini
utils/spacewalk-utils.changes

Use HTTPS for Oracle repositories
No difference.
- No documentation needed: A mention on the release notes will be needed.
- No tests: Tool not covered by testing right now.
None

Use HTTPS for Oracle repositories

---

java/code/src/com/redhat/rhn/domain/contentmgmt/test/ContentFilterTest.java
java/code/src/com/redhat/rhn/domain/contentmgmt/test/ModuleFilterTest.java
java/code/src/com/redhat/rhn/domain/contentmgmt/validation/ContentProjectValidator.java
java/code/src/com/redhat/rhn/domain/contentmgmt/validation/test/ContentValidatorTestBase.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/ContentValidationFaultException.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/test/ContentManagementHandlerTest.java
java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
java/code/src/com/redhat/rhn/manager/contentmgmt/test/ContentManagerTest.java
java/code/src/com/redhat/rhn/manager/contentmgmt/test/DependencyResolverTest.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/ResponseMappers.java
java/spacewalk-java.changes
web/html/src/manager/content-management/list-filters/filter-form.js

Validate CLM projects on build/promote with XMLRPC
- Documented in API docs
Fixes https://github.com/SUSE/spacewalk/issues/11422

Validate CLM projects on build/promote with XMLRPC

---

web/html/src/manager/systems/bootstrap/bootstrap-minions.js
web/spacewalk-web.changes

https://github.com/uyuni-project/uyuni/pull/2205
redo of this... code already approved. but for some reason in a, maybe in a bad rebase the commits disappeared...  
No difference.
Before:
After:
Fixes #
Tracks # **add …

Sort act keys bspage

---

README.md

Update the main `README.md` to remove IRC and add Gitter, as we are moving there.
No difference.
- No documentation needed: Not part of the doc.
- No tests: README update.
Tracks https://lists.opensuse.org/uyuni-announce/2020-06/

Move to Gitter

---

java/code/src/com/suse/manager/webui/controllers/ProductsController.java
java/code/src/com/suse/manager/webui/controllers/channels/ChannelsApiController.java
java/spacewalk-java.changes

port of sw#2255
No difference.
Before:
After:
Fixes # …

Clm speedup

---

schema/spacewalk/common/data/rhnPackageKey.sql
schema/spacewalk/common/data/rhnPackageProvider.sql
schema/spacewalk/susemanager-schema.changes
schema/spacewalk/upgrade/susemanager-schema-4.1.7-to-susemanager-schema-4.1.8/001-package-provider-changes.sql

Update Package Provider name and add some gpg keys now used to sign packages.
No difference.

update provider name and add missing keyids

---

branding/css/uyuni/uyuni-theme.less

Fixing `branding` package build
No difference.
Before:
After:
Fixes # …

Fix class name

---

testsuite/features/secondary/trad_cve_id_new_syntax.feature

When mirroring is too fast, we have a lot of available patches. The pagination hide the patch we look for.
Search for the patch before selecting it.
No difference.
Tracks #

reduce the listed patches to our dummy patches

---

susemanager-sync-data/channel_families.json
susemanager-sync-data/susemanager-sync-data.changes

SLE 12 SP4 get LTSS with new product classes.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/11817

New product classes

---

.github/ISSUE_TEMPLATE.md

Add a template for the issues.
No difference.
- No documentation needed: No, this is for the GitHub repository.
- No tests: No, this is for the GitHub repository.
None

Add a template for the issues

---

susemanager/src/mgr-create-bootstrap-repo
susemanager/susemanager.changes

Do not more a not existing directory.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/11823

Fix missing destdir

---

java/code/src/com/redhat/rhn/domain/recurringactions/RecurringActionFactory.java
java/code/src/com/suse/manager/model/maintenance/CalendarFactory.java
java/code/src/com/suse/manager/model/maintenance/ScheduleFactory.java

$subj
No difference.
- No documentation needed: internal stuff
- No tests: not testable change

Specify the result type of the JPQL queries to get rid of warnings

---

web/html/src/manager/admin/setup/products/products.js
web/spacewalk-web.changes

2 fixes and 1 improvement. See the commit messages for further info (they are
pretty detailed).
I suggest reviewing "commit-by-commit".
No difference.
- No documentation needed: bugfixes + minor changes
- No tests: ui code
Tracks https://github.com/SUSE/spacewalk/issues/11837

Products page improvement

---

java/buildconf/build-props-susemanager.xml
java/spacewalk-java.changes
java/spacewalk-java.spec

Fix some broken jar symlinks.
https://bugzilla.suse.com/show_bug.cgi?id=1174229
No difference.
- No documentation needed: **build bugfix**
- No tests: **will be tested by the Cucumbe test suite when installing**
Fixes #

Fix broken jar symlinks (bsc#1174229)

---

java/code/src/com/suse/manager/maintenance/IcalUtils.java
java/code/src/com/suse/manager/maintenance/test/IcalUtilsTest.java

Previously, the equals was called on the SUMMARY object, not on its value.
No difference.

Fix the event filtering in MULTI Schedules

---

java/conf/rhn_java.conf
java/spacewalk-java.changes
java/spacewalk-java.spec

After SUSE Manager 4.1 is released we need to prepare master branch for next version.
No difference.
- No tests: **not needed**

Enable beta tag

---

schema/spacewalk/common/data/rhnActionType.sql
web/html/src/manager/virtualization/guests/GuestProperties.js
web/html/src/manager/virtualization/pools/list/pools-list.js

Fixes tiny but test-breaking rebase errors from the virtual network PR.
No difference.
- No documentation needed: no UI change
- No tests: fixing actually broken tests.

Virt rebase fixes

---

susemanager-utils/testing/docker/master/uyuni-master-spacewalkkoan/add_packages.sh

Fix containers used for testing

add gzip to container

---

java/code/src/com/redhat/rhn/common/db/datasource/xml/test_queries.xml
java/code/src/com/redhat/rhn/domain/common/ManagerInfoFactory.java
java/code/src/com/redhat/rhn/domain/scc/SCCCachingFactory.java
java/code/src/com/redhat/rhn/domain/scc/test/SCCCachingFactoryTest.java
java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
java/spacewalk-java.changes

Backport of https://github.com/SUSE/spacewalk/pull/11999

Data null means sync never ran yet (bsc#1174357)

---

testsuite/features/qam/reposync/srv_sync_qam_products.feature

PR adds products needed for retail features (for supported terminal versions and build hosts).
https://github.com/SUSE/spacewalk/issues/11333

QAM testsuite - synchronize products needed for retail

---

java/code/src/com/redhat/rhn/domain/kickstart/KickstartData.java
java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartHelper.java
java/code/src/com/redhat/rhn/manager/kickstart/KickstartFormatter.java

Port of https://github.com/SUSE/spacewalk/pull/12226

Fix checking packages for autoinstallation in case of salt

---

backend/po/cs.po

Translated using Weblate (Czech)

---

testsuite/features/reposync/srv_check_installer_updates.feature
testsuite/features/secondary/srv_distro_cobbler.feature
testsuite/features/step_definitions/common_steps.rb

Update for https://github.com/uyuni-project/uyuni/pull/2512 - some commits got lost

Cucumber tests installer updates

---

java/code/src/com/redhat/rhn/domain/server/test/ServerTest.java

Update ServerTest.java, Fix Issue #2542

---

java/spacewalk-java.changes

Fix changelog for bsc#1175556
No difference.
- No documentation needed: not needed

Fix changelog for bsc#1175556

---

scripts/translation/trans-units-extractor.py
scripts/translation/xliffmerger.py

A simple tool to manage xliff files
No difference.
Before:
After:
Fixes # …

Xliff merge tool

---

testsuite/features/step_definitions/command_steps.rb

During a testsuite review, we found an issue with an expression in this method, and we fixed by reverting the changes, creating again two methods instead of merging them in one. In my opinion, having two methods with the same behavior and purpose make it easier to by mistake not maintain both methods, and being unsynced.
This PR joins them in one step definition again but making it more readable, so without injecting variables in the regular expressions.
No difference.
- No tests
Will need ports …

QA: Refactoring repo handling step definition

---

LICENSE.change

As requested by @brejoc , "agreement" from my side to change
from GPLv2 to the Apache 2.0 license.

rpasche license change

---

susemanager-utils/susemanager-sls/src/examples/uyuni_config_hardcode.sls

Update salt config modules example for static data.
Port to manager 4.1
- No documentation needed: example update

correct salt config module hardcode example

---

java/code/src/com/redhat/rhn/frontend/taglibs/list/CSVTag.java
web/html/src/core/spa/spa-engine.js

Port of https://github.com/SUSE/spacewalk/pull/12547

Disable spa for non-redirect links

---

backend/satellite_tools/satsync.py
backend/server/handlers/applet/applet.py
backend/server/handlers/xmlrpc/registration.py
client/rhel/spacewalk-client-tools/src/bin/rhn_check.py
client/rhel/spacewalk-client-tools/src/firstboot-legacy-rhel5/rhn_choose_server_gui.py
client/rhel/spacewalk-client-tools/src/firstboot-legacy-rhel5/rhn_create_profile_gui.py
client/rhel/spacewalk-client-tools/src/firstboot-legacy-rhel5/rhn_finish_gui.py
client/rhel/spacewalk-client-tools/src/firstboot-legacy-rhel5/rhn_login_gui.py
client/rhel/spacewalk-client-tools/src/firstboot-legacy-rhel5/rhn_provide_certificate_gui.py
client/rhel/spacewalk-client-tools/src/firstboot-legacy-rhel5/rhn_review_gui.py
client/rhel/spacewalk-client-tools/src/firstboot-legacy-rhel5/rhn_start_gui.py
client/rhel/spacewalk-client-tools/src/firstboot-legacy-rhel6/rhn_login_gui.py
client/rhel/spacewalk-client-tools/src/up2date_client/config.py
client/rhel/spacewalk-client-tools/src/up2date_client/rhnreg_constants.py
client/rhel/spacewalk-client-tools/src/up2date_client/rpcServer.py
client/rhel/spacewalk-client-tools/src/up2date_client/tui.py
client/rhel/spacewalk-client-tools/src/up2date_client/up2dateErrors.py
client/rhel/yum-rhn-plugin/rhnplugin.py
java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml

No difference.
- No tests:  nothing to test here
https://github.com/SUSE/spacewalk/issues/12289

Revisit the RH strings occurences

---

susemanager/etc/logrotate.d/susemanager-tools
susemanager/susemanager.changes

logroate seems not to work for some config files. Try to fix the configs.
No difference.
- No documentation needed: **as documented**
Tracks 

Fix logrotate config

---

testsuite/features/qam/smoke_tests/smoke_tests.template

Port of https://github.com/SUSE/spacewalk/pull/12601

QAM Remote command: Specify target hostname

---

client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes
client/rhel/yum-rhn-plugin/yum-rhn-plugin.changes

Add missing changelog for PR 2637 (RH strings)

---

testsuite/features/qam/add_custom_repositories/add_ceos8_repositories.feature

Adapt testsuite code to new network.
Ports:
* 4.1: SUSE/spacewalk#12846
* 4.0: SUSE/spacewalk#12847

URL of minima mirror for QAM changed

---

java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java
java/code/src/com/redhat/rhn/manager/distupgrade/DistUpgradeManager.java

Improve debug logging and change indentations and line breaks for better code readability.
No difference.
- No tests: **only debugging code**
Tracks https://github.com/SUSE/spacewalk/pull/12830

Improve debug logging sp migration

---

testsuite/features/step_definitions/salt_steps.rb

https://github.com/SUSE/spacewalk/issues/11427
(It fixes https://github.com/uyuni-project/uyuni/pull/2744)
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/12883
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/12884

Testsuite: Clean up sle_ssh_tunnel_minion as well

---

README.md

Add a link to the wiki about how to contribute
No difference.
- This PR itself is changing doc.
- No tests: Just a markdown file
Tracks https://github.com/SUSE/spacewalk/issues/12663

Add a link to the wiki about how to contribute

---

susemanager-utils/susemanager-sls/salt/bootloader/autoinstall.sls
susemanager-utils/susemanager-sls/susemanager-sls.changes

Reboot also when no changes in grub conf where required.
No difference.
- No documentation needed: **internal detail**
- No tests: **not tested**
Fixes https://github.com/SUSE/spacewalk/issues/12802
Tracks https://github.com/SUSE/spacewalk/pull/12932

Reboot use require

---

testsuite/features/qam/init_clients/ceos6_client.feature
testsuite/features/qam/init_clients/ceos7_client.feature
testsuite/features/secondary/min_centos_openscap_audit.feature
testsuite/features/secondary/trad_centos_client.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/support/constants.rb

Port of https://github.com/SUSE/spacewalk/pull/12870

Testsuite: Fix openscap dependencies for sle trad client

---

java/code/src/com/redhat/rhn/domain/contentmgmt/validation/ContentPropertiesValidator.java
java/code/src/com/redhat/rhn/domain/contentmgmt/validation/strict/ContentStrictValidator.java
java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
java/code/src/com/redhat/rhn/frontend/xmlrpc/ValidationException.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/EnvironmentApiController.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/EnvironmentHandler.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/FilterApiController.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/FilterHandler.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectActionsApiController.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectActionsHandler.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectApiController.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectHandler.java
java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ValidationUtils.java
java/code/src/com/suse/manager/webui/utils/gson/ResultJson.java
java/spacewalk-java.changes
web/html/src/manager/content-management/shared/api/use-lifecycle-actions-api.js

The goal of this PR is to:
- fix the order of args in the doc of the XMLRPC API method `buildProject`
- extract the properties validation from frontend to backend (new class `ContentPropertiesValidator`), so that XMLRPC benefits from it too
- internationalize the CLM strings
- fix a couple of bugs found on the way:
- couple of validations were missing
- the error string in the ui was joined with `<br />`, which didn't work. fixed by reporting each error separately (see the screenshot below)
I think review commit-by-commit should be the best thing (There is only one twist in the "Refactor: Move the helper method to appropriate place" commit (the validator class had a dumb name originally)). Commit msgs sometimes contain useful information.
before:
after: …

CLM: fix XMLRPC docs and XMLRPC validation

---

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_zh_CN.xml
java/code/src/com/redhat/rhn/frontend/strings/template/StringResource_pt_BR.xml

Fix build of `spacewalk-java` failing due to wrong @@\<keyword\>@@ syntax

Fix typos in @@<keyword>@@ macros

---

java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
java/spacewalk-java.changes

Reverts uyuni-project/uyuni#2806 - we need to push this to the right MU branch

Revert "Use correct eauth module and credentials for Salt SSH calls (bsc#1178319)"

---

testsuite/features/step_definitions/salt_steps.rb

Port of https://github.com/SUSE/spacewalk/pull/13070

Testsuite: Use rcsalt-minion stop on suse minions

---

backend/satellite_tools/rhn-schema-stats
backend/satellite_tools/spacewalk-debug
backend/spacewalk-backend.changes
susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.changes
susemanager-utils/supportutils-plugin-susemanager-client/susemanagerclient
susemanager-utils/supportutils-plugin-susemanager-proxy/supportutils-plugin-susemanager-proxy.changes
susemanager-utils/supportutils-plugin-susemanager-proxy/susemanagerproxy
susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes
susemanager-utils/supportutils-plugin-susemanager/susemanager
susemanager-utils/supportutils-plugin-susemanager/susemanager-connection-check.pl

Cleanup checks and add missing and useful things
No difference.
- No tests: **for debugging only**
Fixes https://github.com/SUSE/spacewalk/issues/10144
Tracks https://github.com/SUSE/spacewalk/pull/13079 https://github.com/SUSE/spacewalk/pull/13081

Improve supportutils plugins

---

susemanager-sync-data/additional_products.json
susemanager-sync-data/channel_families.json
susemanager-sync-data/susemanager-sync-data.changes

fix a problem with a duplicate repo definition and add some new channels families created in SCC
No difference.
- No tests: **scc data update**
Tracks https://github.com/SUSE/spacewalk/pull/13055 https://github.com/SUSE/spacewalk/pull/13056

Update susemanager sync data

---

schema/spacewalk/susemanager-schema.changes

from commit 20450742ee17a4e82198f7320741bda83f7cd173

Port of changelog bsc entry (bsc#1178204)

---

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_bn_IN.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ca.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_cs.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_de.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_es.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_fr.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_gu.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_hi.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_it.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ja.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ko.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_pa.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_pt_BR.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ru.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_sk.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ta.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_uk.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_zh_CN.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_zh_TW.xml
testsuite/features/secondary/srv_mainpage.feature

Update copyright 
No difference.

Update copyright to 2020

---

testsuite/features/secondary/minkvm_guests.feature
testsuite/features/secondary/minxen_guests.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/support/commonlib.rb
testsuite/features/upload_files/sle-15-sp2-autoyast.xml

Fixes the testsuite to also run on uyuni.
No difference.
- No documentation needed: test fixes

Tftpboot test fix

---

testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature

Scroll up to let the chromedrive find a button.
Continuation of https://github.com/uyuni-project/uyuni/pull/2879
https://github.com/uyuni-project/uyuni/pull/2879
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13192
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13193

Testsuite: Another scroll up to help Selenimum driver

---

testsuite/features/secondary/min_centos_openscap_audit.feature

OpenSCAP packages are installed on CentOS too

---

testsuite/features/secondary/srv_content_lifecycle.feature

This button might need a few seconds to show up; give enough time to it to appear.
Fixes #
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13237
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13236

Testsuite: Give enough time to the button to appear

---

uyuni/base/LICENSE
uyuni/base/uyuni-base.changes
uyuni/base/uyuni-base.spec

- Added compatibility for RHEL8.
- Removed RHEL6 logic.
No difference.
- No documentation needed: *No functional change.
- No tests: Will be tested by auto-build.
Fixes #

Added RHEL8 compatibility

---

java/code/src/com/redhat/rhn/frontend/taglibs/helpers/RenderUtils.java

Help debugging a NPE in RenderUtils
No difference.
- No documentation needed: minor code refactoring
- No tests: trivial code refactoring
Fixes #

RenderUtils: split line where an NPE rarely happens to help debugging

---

uyuni/base/uyuni-base.spec

Forgot to call setup to get the License file
No difference.
- No tests: **fix build**

fix package build

---

client/rhel/spacewalk-client-tools/spacewalk-client-tools.spec

Fix a small problem with an `%if` macro
No difference.
- No tests: **fix package build**

Spacewalk client tools fix macro

---

testsuite/features/qam/init_clients/ceos6_client.feature
testsuite/features/qam/init_clients/ceos7_client.feature

Port of https://github.com/SUSE/spacewalk/pull/13206

qam: Enable SUMA tools repos before bootstrap centos clients

---

client/tools/mgr-osad/mgr-osad.spec

Fixed mistyped sed statement
No difference.
- No documentation needed: no functional change
- No tests: done by build process
Fixes #

mgr-osad: Fixed mistyped sed statement

---

client/tools/mgr-push/mgr-push.changes
client/tools/mgr-push/mgr-push.spec

- defined __python for python2.
- Excluded RHEL8 for Python 2 build.
No difference.
- No documentation needed: No functional change
- No tests: Tested by auto-build.
Fixes #

mgr-push: RHEL Python changes

---

branding/spacewalk-branding.changes
branding/spacewalk-branding.spec

- Simplified spec file..
- Parameterised /srv location.
No difference.
- No tests: Automatically tested during build.
Verified build on CentOS 8 and LEAP 15.2.
Fixes #

spacewalk-branding: Restructured SPEC file.

---

testsuite/features/step_definitions/salt_steps.rb

One of our PRs has been partially undoing another one.
Ports:
* 4.0: SUSE/spacewalk#13299
No 4.1.

Remove code duplicated by accident

---

spacewalk/config/spacewalk-config.changes
spacewalk/config/spacewalk-config.spec

Updated SPEC file to build on RHEL related systems.
No difference.
- No tests: Automated test during build process.
Tested build successfully on CentOS8, LEAP 15.2
Fixes #

spacewalk-config: Updated to build on RHEL

---

susemanager/susemanager.spec

Changing PreReq to Requires(pre) make the named packages disapear from the build environement.
Need now an explicit BuildRequires
No difference.
- No tests: **fixes building**

need to require some tools during buildtime

---

testsuite/features/qam/reposync/srv_sync_qam_products.feature

Adding LTSS Updates for SLES11SP3, SLES11SP4, SLES12SP4
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/13307

QAM: Adding LTSS Updates for SLES11SP3, SLES11SP4, SLES12SP4

---

backend/server/handlers/xmlrpc/registration.py
backend/server/rhnVirtualization.py
backend/spacewalk-backend.changes
java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java
java/spacewalk-java.changes
schema/spacewalk/common/data/rhnVirtualInstanceType.sql
schema/spacewalk/susemanager-schema.changes
schema/spacewalk/upgrade/susemanager-schema-4.2.3-to-susemanager-schema-4.2.4/003-add-virtual-instance-type.sql

Port of https://github.com/SUSE/spacewalk/pull/13244

Add VirtualPC virtualization type

---

testsuite/features/support/commonlib.rb

Rewrite a list of constant strings as suggested by Rubocop
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/13400
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/13401

Testsuite: Pacify Rubocop

---

testsuite/features/qam/add_custom_repositories/add_ceos8_repositories.feature

This PR fixes a copy&paste mistake in QAM.
Ports:
* 4.0: SUSE/spacewalk#13434
* 4.1: SUSE/spacewalk#13433

Fixed CentOS 8 parent

---

web/html/src/manager/admin/config/monitoring-admin.js
web/html/src/manager/login/login.js

Fixes lint issues unrelated to the the Flow problem.
No difference.
- No documentation needed: No gui diff.
- No tests: Only linting fixes.

Fix Javascript lint issues

---

testsuite/Rakefile

Fix Rakefile typo passing profile
No difference.

QA: Fix Rakefile typo passing profile

---

testsuite/features/step_definitions/common_steps.rb

Ports:
* 4.0: SUSE/spacewalk#13528
* 4.1: SUSE/spacewalk#13529

Fix race condition

---

testsuite/README.md

Change SUSE Manager by Uyuni in the testsuite Readme
No difference.
- No tests
Fixes #

Update test suite README.md

---

backend/server/importlib/backend.py

Fix for https://github.com/uyuni-project/uyuni/pull/3047 
No difference.
Tracks 

fix extra tags import

---

testsuite/features/step_definitions/common_steps.rb

This PR removes left over code that I forgot during latest changes.
Ports:
* 4.0:
* 4.1: SUSE/spacewalk#13592

Remove leftovers

---

web/html/src/build/migrate-ts/index.js

Found an edge case where macOS was not happy with an empty sed, this seems to resolve the issue.
No difference.
- No tests: Needs to pass all existing tests.
Related: https://github.com/SUSE/spacewalk/issues/13208

Fix macOS sed issue in TS migration script

---

susemanager-frontend/susemanager-nodejs-sdk-devel/susemanager-nodejs-sdk-devel.changes

Add missing changelog entry for HMR update
No difference.
Related: https://github.com/SUSE/spacewalk/commit/5142329e571e8cd9a26883693dacc12ec2af4a16

Add missing changes entry for HMR upgrade

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/systemgroup/ServerGroupHandler.java
java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java
java/spacewalk-java.changes

Port of https://github.com/SUSE/spacewalk/pull/13664

Add an API end point which accept 'onlyRelevant' parameter when applying errata

---

client/rhel/dnf-plugin-spacewalk/dnf-plugin-spacewalk.changes

Add changelog for created Korean po translation file

---

branding/spacewalk-branding.changes

add missing branding changelog entry
No difference.
- No documentation needed:  changelog entry
- No tests: changelog entry
Fixes #

Add missing branding changelog

---

branding/css/theme.less
susemanager-frontend/susemanager-nodejs-sdk-devel/package.json
susemanager-frontend/yarn.lock
web/html/src/components/datetimepicker.js
web/html/src/components/input/Form.js
web/html/src/components/input/FormMultiInput.js
web/html/src/components/input/FormMultiInput.stories.js
web/html/src/components/input/InputBase.js
web/html/src/components/input/InputBase.test.js
web/html/src/components/input/Range.js
web/html/src/components/input/Range.stories.js
web/html/src/components/input/Range.test.js
web/html/src/components/input/Select.js
web/html/src/components/input/Select.stories.js
web/html/src/components/input/Text.js
web/html/src/components/input/Text.stories.js
web/html/src/components/panels/PanelRow.js
web/html/src/utils/test-utils/index.js

Adds a few enchancements to the Form React components like:
* Support for multiple properties on `InputBase`
* Add a `Range` component
* Add keys to `DateTimePicker` children to avoid flooding the browser console
* Handle multiple selected items on `Select` components
No difference: these changes will be used in future PRs
- No documentation needed: no visible change yet
- No tests: no visible change yet, React Stories added
Fixes #

React components improvements

---

testsuite/run_sets/build_validation_add_custom_repositories.yml
testsuite/run_sets/build_validation_reposync.yml

Fix a small typo after renaming a feature file.
No difference.
Ports:
- Manager-4.0: 
- Manager-4.1: 

QAM: Fix srv_sync_all_products call in yaml

---

testsuite/features/build_validation/init_clients/sle15sp3_client.feature
testsuite/features/build_validation/init_clients/sle15sp3_minion.feature
testsuite/features/build_validation/init_clients/sle15sp3_ssh_minion.feature
testsuite/features/build_validation/reposync/srv_sync_all_products.feature
testsuite/run_sets/build_validation_init_clients.yml

This PR adds support for SLES 15 SP3 (BETA) to QAM test suite.
Solves issue SUSE/spacewalk#13796
Ports:
* 4.0: SUSE/spacewalk#13814
* 4.1: SUSE/spacewalk#13813
CI part: SUSE/susemanager-ci#182

Add SLE 15 SP3

---

java/code/src/com/suse/manager/webui/controllers/utils/AbstractMinionBootstrapper.java

Add debuglogging for DB test
No difference.
- No tests: **debugging**
Tracks https://github.com/SUSE/spacewalk/pull/13831 https://github.com/SUSE/spacewalk/pull/13832

add debug logging for DB test

---

rel-eng/packages/susemanager-tftpsync-recv
tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes
tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.spec

Port of #/3198 to master

---

testsuite/features/step_definitions/common_steps.rb

This PR fixes a step that was not working.
Ports:
* 4.0: SUSE/spacewalk#13892
* 4.1: SUSE/spacewalk#13891

Wait for Search button, not for placeholder text

---

schema/spacewalk/upgrade/susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/702-debvercmp.sql

Since PR https://github.com/uyuni-project/uyuni/pull/3122, the CI [1] is failing while running `susemanager-schema-4.2.4-to-susemanager-schema-4.2.5/702-debvercmp.sql` on a database that was already migrated to `4.27` (because the `rhnservercrash` was already dropped on `susemanager-schema-4.2.6-to-susemanager-schema-4.2.7/801-drop-servercrash.sql`).
From Jenkins logs:
```
susemanager-schema-4.2.7-to-susemanager-schema-4.2.8/0033-702-debvercmp.sql.postgresql
...
psql:<stdin>:363: ERROR:  relation "rhnservercrash" does not exist
LINE 3:          from rhnservercrash p
^
ERROR: Upgrade failed! Most probably the new SQL scripts are not idempotent!
```
Use a pl/pgsql block to check if `rhnservercrash` exists before updating it.
[1] https://ci.suse.de/blue/organizations/jenkins/manager-Head-sche …

Fix schema migration when 'rhnservercrash' was already dropped

---

.github/workflows/changelog_checker.yml
.github/workflows/update_translations.yml
scripts/translation/update-all-translation-strings.sh

Will merge after the holidays.
(review commit-by-commit)
Adding a workflow that is triggered as a github action after push to `master` branch.
The result can be seen here: https://github.com/hustodemon/uyuni (the action added new commits on top of master).
Questions:
No difference.
- No documentation needed: automation
- No tests:  automation

Update translations workflow

---

.github/workflows/update_translations.yml

github workflow
- No tests in this area

Run the translation update automation only on the Uyuni repository (not in forks)

---

testsuite/features/step_definitions/xmlrpc_common.rb

Follow-up of #3251
Ports:
* 4.0:
* 4.1:

More debugging information

---

java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
java/spacewalk-java.changes

No difference.
Before:
After:
- No tests
Fixes # https://github.com/SUSE/spacewalk/issues/13991

fix action chains for saltssh minions

---

testsuite/features/build_validation/init_clients/proxy.feature
testsuite/features/build_validation/retail/build_sle11sp3_kiwi_image.feature
testsuite/features/build_validation/retail/build_sle12sp4_kiwi_image.feature
testsuite/features/build_validation/retail/build_sle15sp2_kiwi_image.feature
testsuite/features/build_validation/retail/configure_saltboot_formula.feature
testsuite/features/build_validation/retail/deploy_sle11sp3_terminal.feature
testsuite/features/build_validation/retail/deploy_sle12sp4_terminal.feature
testsuite/features/build_validation/retail/deploy_sle15sp2_terminal.feature
testsuite/features/build_validation/retail/sle11sp4_kiwi_image_buildhost.feature
testsuite/features/build_validation/retail/sle12sp4_kiwi_image_buildhost.feature
testsuite/features/build_validation/retail/sle15sp2_kiwi_image_buildhost.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/step_definitions/common_steps.rb
testsuite/features/support/twopence_init.rb

Port of https://github.com/SUSE/spacewalk/pull/13645 and https://github.com/SUSE/spacewalk/pull/13281

QAM - initial retail features support

---

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
java/code/webapp/WEB-INF/decorators.xml
java/code/webapp/WEB-INF/decorators/layout_error.jsp
java/code/webapp/errors/404.jsp
java/code/webapp/errors/500.jsp
java/spacewalk-java.changes

Port of: https://github.com/SUSE/spacewalk/pull/13829
No difference.
Before:
After:
Fixes https://github.com/SUSE/spacewalk/issues/13720
relates …

Uyuni  404 500 pages optimization

---

web/html/src/.eslintrc.js
web/html/src/components/action-schedule.tsx
web/html/src/components/formulas/FormulaComponentGenerator.tsx

Enforce the ESLint triple-equals rule, fix up old occurrences of `==`.
No difference.

Enforce ESLint `eqeqeq`

---

web/html/src/components/FormulaForm.tsx
web/html/src/components/config-channels.tsx
web/html/src/components/formula-selection.tsx
web/html/src/components/pagination.tsx
web/html/src/components/systems.tsx
web/html/src/utils/legacy.ts

Fix lint issues from merged branches. It seems some of the merged branches conflicted with each other but didn't validate.
No difference.
Related to https://github.com/SUSE/spacewalk/issues/14074

Resolve lint issues on master

---

testsuite/features/secondary/srv_scc_user_credentials.feature

Cosmetical - use standard feature description syntax.
No ports, please directly fix this in your PRs @atighineanu .

Changed feature description

---

.github/workflows/add_pr_reviewer.yml

Added atighineanu to the yaml
Added mnoel9 to the yaml

added myself (atighineanu) to the reviewer list

---

java/buildconf/apidoc/html/scripts.txt

Fix a small typo in a comment.
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/14207
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/14208

Fix small typo in comment

---

testsuite/features/build_validation/init_clients/sle11sp4_ssh_minion.feature
testsuite/features/build_validation/init_clients/sle12sp4_ssh_minion.feature
testsuite/features/build_validation/init_clients/sle15_ssh_minion.feature
testsuite/features/build_validation/init_clients/sle15sp1_ssh_minion.feature
testsuite/features/build_validation/init_clients/sle15sp2_ssh_minion.feature
testsuite/features/build_validation/init_clients/sle15sp3_ssh_minion.feature
testsuite/features/secondary/minssh_bootstrap_xmlrpc.feature

Follow up of https://github.com/uyuni-project/uyuni/pull/3413
Tracks https://github.com/SUSE/spacewalk/pull/14290 https://github.com/SUSE/spacewalk/pull/14291

delete scenario which delete product package from package state from other places

---

testsuite/run_sets/build_validation_create_bootstrap_repositories.yml

This PR fixes a wrong feature name in an yaml file

BV: fix feature name

---

susemanager-sync-data/additional_products.json

add additional ubuntu and oraclelinux repositories
No difference.
- No tests: 
Fixes https://github.com/SUSE/spacewalk/issues/14191 https://github.com/SUSE/spacewalk/issues/14138

add additional ubuntu and oraclelinux repositories

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/systemgroup/ServerGroupHandler.java

fix typo in serializer name

---

backend/satellite_tools/repo_plugins/deb_src.py
backend/satellite_tools/repo_plugins/yum_dnf_src.py
backend/satellite_tools/repo_plugins/yum_src.py
backend/spacewalk-backend.changes

Improves switching config component on exception handling for reposync plugins
No difference.
Improves https://github.com/uyuni-project/uyuni/pull/3334

Improve switching config component on exception handling

---

testsuite/features/init_clients/sle_minion.feature
testsuite/features/init_clients/sle_ssh_minion.feature
testsuite/features/reposync/srv_enable_sync_products.feature
testsuite/features/reposync/srv_sync_products.feature
testsuite/features/secondary/allcli_action_chain.feature
testsuite/features/secondary/srv_content_lifecycle.feature
testsuite/features/secondary/srv_distro_cobbler.feature
testsuite/features/step_definitions/common_steps.rb
testsuite/features/support/commonlib.rb
testsuite/features/support/env.rb

This PR reverts 548c9564bbc36a070841042c286d7114b110f748 and 3e9c8e893284183d499b788a36f0dc14f49d57f7.
Removing the `@service_pack_migration` tag might still be a good idea, I had not the time to separate damaging part from good part, sorry.
Ports:
* 4.0
* 4.1

Emergency revert of breaking PR and subsequent fix

---

susemanager-utils/testing/automation/obs-project.py

No difference.
Before:
After:
Fixes # …

Test obs project

---

susemanager-sync-data/additional_products.json
susemanager-sync-data/susemanager-sync-data.changes

add oes2018 sp3 product
No difference.
- No tests
Fixes #https://github.com/SUSE/spacewalk/issues/14372

add OES2018-SP3 (bsc#1183845)

---

.github/workflows/auto-author-assign.yml

Add toshimaru/auto-author-assign GH action
https://github.com/toshimaru/auto-author-assign
No difference.
Fixes #

Add toshimaru/auto-author-assign GH action

---

testsuite/features/step_definitions/common_steps.rb

Ensure the cleanup scenario removes all created distros.
Delete the distributions created from the web UI as well.
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/14476
- Manager-4.0: https://github.com/SUSE/spacewalk/pull/14475

Testsuite: Fix idempotency in the cobbler test

---

.github/workflows/auto_request_review.yml

Do not rerequest approvals for edits
No difference.
Fixes #

Do not rerequest approvals for edits

---

susemanager-utils/susemanager-sls/susemanager-sls.spec

Package all python grains files
No difference.
- No documentation needed: internal change
Fixes https://github.com/SUSE/spacewalk/issues/14447

Package all python grains

---

client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes

Title says it all :-)
No difference.
- No documentation needed: Changelog fix
- No tests:  Changelog fix
None.

Add missing changelog entry for spacewalk-client-tools about the translations

---

client/rhel/mgr-daemon/mgr-daemon.changes

Title says it all :-)
No difference.
- No documentation needed: Changelog fix
- No tests:  Changelog fix
None.

Add missing changelog entry for mgr-daemon about the translations

---

backend/rhn-conf/rhn_server_xmlrpc.conf
backend/spacewalk-backend.changes
backend/tito.props
java/conf/rhn_java.conf
java/spacewalk-java.changes
java/spacewalk-java.spec
java/tito.props
schema/spacewalk/spacewalk-schema-upgrade
spacewalk/admin/spacewalk-admin.changes
spacewalk/admin/spacewalk-startup-helper

Define versioned dependencies between packages and services.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13399

add dependencies with versions for packages

---

spacewalk/certs-tools/rhn_bootstrap_strings.py

Fix a typo: activaion -> activation
https://github.com/uyuni-project/uyuni/pull/3314
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/14561

Fix typo: activaion -> activation

---

.github/reviewers.yml

Exclude features from qa automatic reviews
No difference.
Fixes #

Exclude features from qa automatic reviews

---

.github/reviewers.yml

Update reviewers action
No difference.
Fixes #

Update reviewers action

---

susemanager-sync-data/channel_families.json
susemanager-sync-data/susemanager-sync-data.changes

Add MicroOS to supported products
No difference.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/14550
Fixes https://github.com/SUSE/spacewalk/issues/14549

Microos channel family

---

java/code/src/com/redhat/rhn/domain/kickstart/KickstartableTree.java
java/code/src/com/redhat/rhn/frontend/action/common/DownloadFile.java
java/code/src/com/redhat/rhn/manager/kickstart/cobbler/test/CobblerCommandTest.java
java/code/src/com/redhat/rhn/manager/kickstart/tree/TreeCreateOperation.java
java/code/src/com/redhat/rhn/manager/kickstart/tree/test/TreeCreateOperationTest.java
java/spacewalk-java.changes

Get metadata and packages from the same source: either the media or the synced channels.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/14540

Checksum problem with autoinstall

---

testsuite/features/core/proxy_branch_network.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/upload_files/massive-import-terminals.yml

Reverts uyuni-project/uyuni#3573

Revert "Testsuite - delete empty bootstrap profiles"

---

testsuite/features/secondary/min_retracted_patches.feature

Fix the test for retracted patches.
- testsuite/features/secondary/min_retracted_patches.feature:
Ensure we install/remove the packages.
Fixes https://github.com/uyuni-project/uyuni/pull/3395

Testsuite: Fix test for retracted patches

---

susemanager-utils/testing/automation/push-to-obs.sh

fix a typo

---

susemanager-frontend/susemanager-nodejs-sdk-devel/susemanager-nodejs-sdk-devel.changes
susemanager-frontend/susemanager-nodejs-sdk-devel/susemanager-nodejs-sdk-devel.spec

Add MPL-2.0 to susemanager-nodejs-sdk-devel.spec

---

web/spacewalk-web.changes

Update changelog with retracted patches changes

---

spacewalk/certs-tools/spacewalk-certs-tools.changes

Add changelog entry for https://github.com/uyuni-project/uyuni/pull/3543
- Manager-4.1: https://github.com/SUSE/spacewalk/pull/14668

Update changelog for spacewalk-certs-tools

---

utils/spacewalk-common-channels.ini
utils/spacewalk-utils.changes

Fix the URLs for SLE15 stable client tools
No difference.
- No tests: Not covered by cucumber.
https://github.com/uyuni-project/uyuni/pull/3632/files

Fix the URLs for SLE15 stable client tools

---

web/html/src/components/table/SearchField.test.tsx
web/html/src/components/table/SearchField.tsx
web/html/src/components/table/SearchPanel.tsx
web/html/src/components/table/Table.tsx
web/html/src/components/table/TableDataHandler.tsx
web/html/src/manager/content-management/list-filters/list-filters.tsx
web/html/src/manager/content-management/shared/components/panels/filters-project/filters-project.js
web/html/src/manager/content-management/shared/type/filter.type.ts
web/html/src/utils/data.test.js
web/html/src/utils/data.ts
web/spacewalk-web.changes

Add selection, project sorting, deleting etc to the CLM filter list.
Before:
After:
- No documentation needed: documentation will be added once the filter wizard is ready.
Fixes https://github.com/SUSE/spacewalk/issues/14099

Update CLM filter list

---

web/html/src/components/table/SearchField.test.tsx
web/html/src/components/table/Table.test.js
web/html/src/utils/test-utils/index.ts

Followup to https://github.com/uyuni-project/uyuni/pull/3649 to add test coverage
No difference.
Related to https://github.com/uyuni-project/uyuni/pull/3649

Add test coverage for control conflict changes

---

java/code/src/com/redhat/rhn/domain/server/VirtualInstance.java
java/code/src/com/redhat/rhn/manager/system/VirtualInstanceManager.java
java/code/src/com/redhat/rhn/taskomatic/task/gatherer/VirtualHostManagerProcessor.java
java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java
java/spacewalk-java.changes

Cherry-pick of https://github.com/SUSE/spacewalk/pull/14711

Remove the unneeded check that was stopping updating a virtual instance type

---

branding/css/susemanager-theme.less
branding/css/uyuni-theme.less
java/code/src/com/redhat/rhn/frontend/strings/nav/StringResource_en_US.xml
java/code/src/com/suse/manager/webui/controllers/AnsibleController.java
java/code/src/com/suse/manager/webui/templates/minion/ansible-control-node.jade
java/code/src/com/suse/manager/webui/templates/minion/ansible-path-content.jade
java/code/webapp/WEB-INF/nav/system_detail.xml
web/html/src/manager/minion/ansible/accordion-path-content.tsx
web/html/src/manager/minion/ansible/ansible-control-node.tsx
web/html/src/manager/minion/ansible/ansible-path-content.tsx
web/html/src/manager/minion/ansible/ansible-path-type.tsx
web/html/src/manager/minion/ansible/edit-ansible-path.tsx
web/html/src/manager/minion/ansible/new-ansible-path.tsx
web/html/src/manager/minion/index.js

Add Playbooks and Inventories subtabs for Ansible to list all playbooks in paths and content of inventory files.
After:
Fixes …

Ansible path content for Playbooks and Inventories

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/ansible/AnsibleHandler.java

Fix xmlrpc doc build.
No difference.
fix

Fix xmlrpc doc

---

testsuite/run_sets/secondary_parallelizable.yml

As we renamed the Cucumber feature file, we also need to rename it inside the YAML file.
No difference.
The rename from SP Migration to Product Migration is not ported, so we don't need ports here either.

QA: Rename the trad_sp_migration.feature in yml

---

client/rhel/dnf-plugin-spacewalk/dnf-plugin-spacewalk.changes
client/rhel/mgr-daemon/mgr-daemon.changes
client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes
client/rhel/yum-rhn-plugin/yum-rhn-plugin.changes

Add missing changelog entries for packages that translations
No difference.
- No documentation needed: Changelogs
- No tests:  Changelogs
None

Add missing changelog entries for packages that translations

---

java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
java/code/src/com/redhat/rhn/frontend/xmlrpc/ansible/AnsibleHandler.java
java/code/src/com/suse/manager/webui/templates/minion/ansible-path-content.jade
web/html/src/manager/minion/ansible/schedule-playbook.tsx

Ansible fixes

---

testsuite/features/secondary/trad_baremetal_discovery.feature
testsuite/features/secondary/trad_check_registration.feature

Fix cucumber tests related to system transfer
No difference.
- No documentation needed: Fix tests
- 
- No tests: Fix tests

Fix testsuite tests related to system transfer

---

java/code/src/com/suse/manager/webui/controllers/DownloadController.java

Log an additional variable to help figure out the possible problems. 
No difference.
Fixes #

Add additional log to help figure out a problem

---

susemanager-utils/testing/automation/publish-rpms.sh
susemanager-utils/testing/automation/push-to-obs.sh
web/.yarnrc

Reverts uyuni-project/uyuni#3670
We are having trouble building the yarn packages.

Revert "CI: Build each package in a docker container in parallel"

---

client/tools/mgr-osad/mgr-osad.changes
client/tools/mgr-osad/mgr-osad.spec

Port of https://github.com/SUSE/spacewalk/pull/13331

change the permission so logrotate works

---

testsuite/features/init_clients/sle_minion.feature
testsuite/features/init_clients/sle_ssh_minion.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/step_definitions/navigation_steps.rb

This PR:
* SP migrates repositories inherited from sumaform
* does cosmetic changes, removes dead code, and synchronizes branches
Port of SUSE/spacewalk#14813, SUSE/spacewalk#14820, and SUSE/spacewalk#14836
Ports:
* 4.0: none
* 4.1: SUSE/spacewalk#14836

Fix SP migration

---

web/html/src/components/action-schedule.tsx
web/spacewalk-web.changes

See: https://bugzilla.suse.com/1185968
- No tests: Feature not covered
Fixes [bsc#1185968](https://bugzilla.suse.com/1185968)

Fix date-time picker radio controls (bsc#1185968)

---

java/code/src/com/redhat/rhn/frontend/action/channel/manage/repo/RepoDetailsAction.java
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
java/spacewalk-java.changes

Entering random repo ids in the URL cause NPEs and result into Internal Server Errror pages.
This change catch it and produce a Not Found page.
Port of https://github.com/SUSE/spacewalk/pull/14788

Ise to normal error

---

susemanager/src/mgr_sync/product.py
susemanager/src/test/test_mgr_sync/test_product_operations.py
susemanager/susemanager.changes

Sort the product list in mgr-sync output
No difference.

Sort mgr sync products

---

web/html/src/manager/minion/ansible/accordion-path-content.test.tsx
web/html/src/manager/minion/ansible/accordion-path-content.tsx
web/html/src/manager/minion/ansible/ansible-control-node.test.tsx
web/html/src/manager/minion/ansible/ansible-control-node.tsx
web/html/src/manager/state/highstate-summary.test.tsx
web/html/src/utils/test-utils/mock.tsx

Add frontend tests for the new Ansible Integration code
No difference.
Fixes #

Master - ansible frontend tests

---

testsuite/features/secondary/min_ansible_control_node.feature
testsuite/features/secondary/min_centos_openscap_audit.feature
testsuite/features/secondary/min_salt_openscap_audit.feature
testsuite/features/secondary/min_ubuntu_openscap_audit.feature
testsuite/features/secondary/minssh_ansible_control_node.feature
testsuite/features/secondary/trad_centos_client.feature
testsuite/features/secondary/trad_migrate_to_minion.feature
testsuite/features/secondary/trad_migrate_to_sshminion.feature
testsuite/features/secondary/trad_openscap_audit.feature
testsuite/features/step_definitions/common_steps.rb

Change the repo to use in Ubuntu client tools, related with the change of repository name here: https://github.com/uyuni-project/sumaform/pull/885
No difference.
Ports:
- Manager-4.0 https://github.com/SUSE/spacewalk/pull/14883
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/14884

QA: Change the repo to use in Ubuntu client tools

---

testsuite/features/secondary/minkvm_guests.feature
testsuite/features/step_definitions/command_steps.rb

Add two fixes for the cucumber virtualization features.
No difference.
Fixes #

Test virt fixes

---

testsuite/features/secondary/min_ansible_control_node.feature
testsuite/features/secondary/minssh_ansible_control_node.feature

Reverts uyuni-project/uyuni#3692

Revert "Testsuite: only execute Ansible feature tests on SUSE Manager"

---

testsuite/features/build_validation/reposync/srv_sync_all_products.feature

This PR adds reposync for Debian 9 and 10.
It also reorders and makes the feature pretty.
Ports:
* 4.0:
* 4.1: SUSE/spacewalk#15001

Reposync Debian 9 and 10

---

testsuite/features/step_definitions/command_steps.rb

Yet another missing Debian test.
There will probably be more.
Ports:
* 4.0: SUSE/spacewalk#15040
* 4.1: SUSE/spacewalk#15039

Missing Debian test

---

utils/spacewalk-common-channels.ini
utils/spacewalk-utils.changes

update proxy to 15.3 in common channels
No difference.
- No tests
no links

update proxy to 15.3 in common channels

---

testsuite/features/step_definitions/common_steps.rb

Reverts uyuni-project/uyuni#3850

Revert "Enable LTSS repo before installing branch server"

---

susemanager/bin/server-migrator.sh
susemanager/susemanager.changes

update migration script to 15.3
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/15036

update migration script to 15.3

---

testsuite/features/build_validation/reposync/srv_sync_all_products.feature
testsuite/features/reposync/srv_sync_products.feature

Remove BETA tags from reposync to find the right elements in the page.
No difference.
Fixes no issue, directly from BV testsuite review
Tracks 4.1: https://github.com/SUSE/spacewalk/pull/15234
deliberately not adding 4.0 it's EOL

Remove BETA tags from reposync

---

web/html/src/.eslintrc.js
web/html/src/components/input/FormMultiInput.tsx
web/html/src/components/input/Range.stories.js
web/html/src/components/input/Range.test.tsx
web/html/src/components/links.tsx
web/html/src/components/pagination.tsx
web/html/src/core/channels/utils/channels-dependencies.utils.ts
web/html/src/manager/audit/cveaudit/cveaudit.tsx
web/html/src/manager/groups/formula/group-formula-selection.renderer.tsx
web/html/src/manager/maintenance/ssm/schedule-picker.tsx
web/html/src/manager/minion/formula/minion-formula-selection.renderer.tsx
web/html/src/manager/minion/packages/package-states.tsx
web/html/src/manager/salt/cmd/remote-commands.tsx
web/html/src/manager/salt/formula-catalog/org-formula-catalog.tsx
web/html/src/manager/virtualization/nets/properties/fields-data.ts
web/html/src/manager/visualization/data-tree.ts
web/spacewalk-web.spec

Followup to [#3838](https://github.com/uyuni-project/uyuni/pull/3838), fixes a number of small lint issues that clog the output.
No difference.

Fix misc lint warnings

---

susemanager-utils/susemanager-sls/src/tests/test_module_virt_utils.py

Mock libvirt in `test_module_virt_utils.py` to get the tests pass when building the `susemanager-sls` package with no installed libvirt python binding package.
No difference.
Fixes #

Mock libvirt in test_module_virt_utils.py

---

backend/satellite_tools/repo_plugins/yum_dnf_src.py
backend/spacewalk-backend.changes

Fixed minrate/timeout configuration for dnf plugin.
(Caused an exception on EL8)
No difference.
- No tests: Test cases will have to be written for the whole EL8 implementation. On TODO once stable again.

Fixed minrate/timeout configuration for dnf plugin.

---

utils/spacewalk-common-channels.ini
utils/spacewalk-utils.changes

Fix typo for the almalinux8 devel client tools
No difference.
- No documentation needed: Fix typo
- No tests: Not covered
https://github.com/uyuni-project/uyuni/commit/1af7337c61a3f25420f7a106859fa16b953f7408#r53297081

Fix typo for the almalinux8 devel client tools

---

testsuite/documentation/cucumber-steps.md
testsuite/features/reposync/srv_sync_products.feature
testsuite/features/secondary/allcli_action_chain.feature
testsuite/features/secondary/allcli_config_channel.feature
testsuite/features/secondary/allcli_software_channels.feature
testsuite/features/secondary/allcli_software_channels_dependencies.feature
testsuite/features/secondary/min_retracted_patches.feature
testsuite/features/secondary/srv_menu.feature
testsuite/features/secondary/srv_power_management.feature
testsuite/features/secondary/srv_power_management_redfish.feature
testsuite/features/secondary/srv_test_maintenance_windows.feature
testsuite/features/secondary/trad_baremetal_discovery.feature

This is a port of https://github.com/SUSE/spacewalk/pull/15358
Port of: https://github.com/SUSE/spacewalk/pull/15358
https://github.com/uyuni-project/uyuni/pull/3922
https://github.com/uyuni-project/uyuni/pull/3872

Reenable client tools for sles15sp3 head

---

spacewalk/certs-tools/rhn_bootstrap_strings.py

Fixes regression on calling `mgr-bootstrap --traditional` brought in with https://github.com/uyuni-project/uyuni/pull/3895
No difference.
Not needed

Fix regression on mgr-bootsrap for traditional

---

testsuite/features/build_validation/retail/deploy_sle11sp3_terminal.feature
testsuite/features/build_validation/retail/deploy_sle12sp4_terminal.feature
testsuite/features/build_validation/retail/deploy_sle15sp2_terminal.feature
testsuite/features/build_validation/retail/sle11sp4_kiwi_image_buildhost.feature
testsuite/features/build_validation/retail/sle12sp4_kiwi_image_buildhost.feature
testsuite/features/build_validation/retail/sle15sp2_kiwi_image_buildhost.feature
testsuite/features/init_clients/buildhost_bootstrap.feature
testsuite/features/init_clients/min_centos_salt.feature
testsuite/features/init_clients/min_ubuntu_salt.feature
testsuite/features/init_clients/sle_minion.feature
testsuite/features/init_clients/sle_ssh_minion.feature
testsuite/features/secondary/allcli_action_chain.feature
testsuite/features/secondary/allcli_config_channel.feature
testsuite/features/secondary/allcli_software_channels.feature
testsuite/features/secondary/allcli_software_channels_dependencies.feature
testsuite/features/secondary/min_activationkey.feature
testsuite/features/secondary/min_bootstrap_negative.feature
testsuite/features/secondary/min_bootstrap_script.feature
testsuite/features/secondary/min_bootstrap_xmlrpc.feature
testsuite/features/secondary/min_centos_ssh.feature
testsuite/features/secondary/min_retracted_patches.feature
testsuite/features/secondary/min_salt_mgrcompat_state.feature
testsuite/features/secondary/min_ubuntu_ssh.feature
testsuite/features/secondary/minssh_bootstrap_xmlrpc.feature
testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
testsuite/features/secondary/srv_custom_system_info.feature
testsuite/features/secondary/srv_power_management.feature
testsuite/features/secondary/srv_power_management_redfish.feature
testsuite/features/secondary/srv_test_maintenance_windows.feature
testsuite/features/secondary/trad_centos_client.feature

Completes a previous port missing a commit.
Instead of:
I follow the left menu "Home > Overview"
We must use:
I follow the left menu "Systems > Overview"
Completes: https://github.com/uyuni-project/uyuni/pull/3984
https://github.com/SUSE/spacewalk/pull/15358

Testsuite: Complete a port

---

web/html/src/components/links.tsx

Fixes some small lint issues I picked up between other things.
No difference.

Add missing link props

---

testsuite/features/secondary/srv_virtual_host_manager.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/upload_files/virtualization/vCenter.json

Move vscenter.json file upload from sumaform to testsuite
No difference.
Ports:
- SUMA 4.0
- SUMA 4.1
- SUMA 4.2

Upload vCenter.json file from testsuite to server

---

testsuite/features/secondary/srv_content_lifecycle.feature

We are not using BETA channels anymore.
This reverts commit 3dadb6ee85a65d3061afa31f270bfe9ad456731a
https://github.com/uyuni-project/uyuni/pull/3262
- Manager-4.2:
schema_migration_test_oracle"

Revert 'We have 2 BETA channels in HEAD'

---

schema/spacewalk/susemanager-schema.changes
schema/spacewalk/upgrade/susemanager-schema-4.1.8-to-susemanager-schema-4.1.9/001-rhnActionVirtCreateDiskDetails-remove-type.sql
schema/spacewalk/upgrade/susemanager-schema-4.1.8-to-susemanager-schema-4.1.9/002-rhnActionVirtCreateDiskDetails-add-fields.sql
schema/spacewalk/upgrade/susemanager-schema-4.2.2-to-susemanager-schema-4.2.3/001-add_rhnVirtCreateAction_cobblerid.sql
schema/spacewalk/upgrade/susemanager-schema-4.2.9-to-susemanager-schema-4.2.10/100-increase-kernel-options-length.sql
schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/001-virt-create-cluster.sql

Fix older schema upgrade scripts idempotency failures due to https://github.com/uyuni-project/uyuni/pull/3986.
No difference.

Schema upgrade idempotency fixes

---

java/code/src/com/redhat/rhn/domain/action/Action_legacyUser.hbm.xml
java/code/src/com/suse/manager/webui/controllers/virtualization/gson/VirtualGuestsUpdateActionJson.java
schema/spacewalk/common/tables/rhnActionVirtCreate.sql
schema/spacewalk/upgrade/susemanager-schema-4.3.0-to-susemanager-schema-4.3.1/200-rhnactionvirtcreate-refactoring.sql
testsuite/features/secondary/minkvm_guests.feature
testsuite/features/secondary/minxen_guests.feature

Fix test breaks introduced by https://github.com/uyuni-project/uyuni/pull/3986
No difference.

KVM / Xen test fixes

---

susemanager/bin/pg-migrate-10-to-12.sh
susemanager/bin/pg-migrate-12-to-13.sh

Reverts uyuni-project/uyuni#3443
see https://github.com/uyuni-project/uyuni/pull/3443#issuecomment-887379972

Revert "check for directory existance"

---

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml

Clean-up extra spaces in string
**Remove duplicated spaces in string**
Remove duplicated spaces in string
- No documentation needed: **Remove duplicated spaces in string**
Fixes #

Remove duplicated spaces in string

---

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml

removed  double space in string
**removed double space in string**
No difference.
- No documentation needed: **removed double space in string**
- No tests: **removed double space in string**
Fixes #

removed double space in string

---

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml

Remove double space in strings
**Remove double space in strings**
No difference.
- No documentation needed: **Remove double space in strings**
- No tests: **Remove double space in strings**
Fixes #

Remove double space in strings

---

web/html/src/manager/audit/cveaudit/cveaudit.tsx
web/html/src/manager/content-management/shared/components/panels/sources/channels/child-channels.tsx
web/html/src/manager/maintenance/maintenance-windows.tsx
web/html/src/manager/state/recurring-states.tsx
web/html/src/manager/systems/virtualhostmanager/virtualhostmanager.tsx

Fixes unnecessary escapes plus updates commentary to fix some last lint issues.
No difference.

Fix regex linter issues

---

java/code/src/com/suse/manager/webui/templates/virtualization/guests/create.jade

Add missing comma breaking the VM creation page after a bad merge.
No difference.

VM creation dialog: fix rebase error

---

java/code/src/com/suse/manager/virtualization/GuestOsDef.java
susemanager-utils/susemanager-sls/salt/virt/update-vm.sls

cucumber tests KVM and Xen fixes

---

java/code/src/com/suse/manager/webui/controllers/virtualization/gson/VirtualNetworkInfoJson.java
java/spacewalk-java.changes

In some virtual network types like sriov-pool there may be no defined
bridge.
No difference.
- No tests: SR-IOV requires specific hardware
Fixes bsc#1189167

Properly handle virtual networks without bridge

---

susemanager/bin/server-migrator.sh
susemanager/susemanager.changes

Tell the user to use the new PG migration script
No difference.
- No documentation needed: This was already documented
- No tests: Not part of the tests
None

Tell the user to use the new PG migration script

---

web/html/src/components/buttons.tsx
web/html/src/components/dialog/LegacyDialog.tsx
web/html/src/components/dialog/ModalButton.tsx
web/html/src/components/input/DateTime.stories.tsx
web/html/src/components/input/Form.tsx
web/html/src/components/input/FormMultiInput.stories.tsx
web/html/src/components/input/Password.stories.tsx
web/html/src/components/input/Radio.stories.tsx
web/html/src/components/input/Select.stories.tsx
web/html/src/components/input/Text.stories.tsx
web/html/src/components/input/form.stories.tsx
web/html/src/manager/state/recurring-states-details.tsx
web/html/src/manager/state/recurring-states-list.tsx
web/html/src/manager/state/recurring-states-utils.tsx

Fixes misc small TODOs that were left from the migration https://github.com/SUSE/spacewalk/issues/13952.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/13952

Clean up followup TODOs

---

java/code/src/com/redhat/rhn/domain/action/ActionChain.hbm.xml
java/code/src/com/redhat/rhn/domain/action/ActionChain.java
java/code/src/com/redhat/rhn/domain/action/ActionChainFactory.java
java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
java/spacewalk-java.changes

https://github.com/SUSE/spacewalk/pull/15625

Delete ActionChains when the last action is a Reboot and it completes (bsc#1188163)

---

backend/common/repo.py
backend/spacewalk-backend.changes
testsuite/features/step_definitions/command_steps.rb

This PR:
* fixes a typo in an error message ("verfication" instead of "verification")
* lets us detect more errors during reposync
See https://bugzilla.suse.com/show_bug.cgi?id=1189558 for the motivation.
Ports:
* 4.1: SUSE/spacewalk#15713
* 4.2: SUSE/spacewalk#15712

Detect bsc 1189558

---

testsuite/features/reposync/srv_sync_products.feature

Remove client tools BETA channels from reposync, the deselect lines have to be commented out at ALPHA again. 
No difference.
Fixes No issue, directly from testsuite review
Tracks:
-  4.2: https://github.com/SUSE/spacewalk/pull/15796
- 4.2:  https://github.com/SUSE/spacewalk/pull/15797

Remove client tools BETA channels from reposync

---

.github/reviewers.yml

Add Dominik as QA reviewer
- Manager-4.2: https://github.com/SUSE/spacewalk/pull/15803

Testsuite: Add Dominik as QA reviewer

---

susemanager-utils/testing/automation/push-to-obs.sh

CI: Exit on error when package build fails
We were not exiting with an error when a package build was failing, we
were missing an exit command ;)
Then, the trap command was a mess, it was not properly espaced with
backslashes and was adding more complexity than anything else. I just
realized, that if we have this:
bash -c "trap cleanup EXIT;CMD1;CMD2;cleanup"
If CMD* are bash scripts, the trap call should not be needed, because the last
cleanup should always be executed, no matter how CMD2 exits.
Then, using a pipe was messing up the return code (exit code) of the
background jobs, plus the output was confusing. Meaning, we better
change this
docker run ..... | tee output.log &
by
docker run ..... > pid.log
wait pid
cat pid.log
Finally, to make sure we are not hidding an error when not …

Test errors on yarn build 2

---

web/html/src/manager/systems/ssm/ssm-subscribe-channels.tsx

Remove unused variable, cleaning up lint.
No difference.

Clean up lint

---

backend/rhn-conf/rhn.conf
backend/spacewalk-backend.changes
backend/spacewalk-backend.spec
spacewalk/setup/bin/spacewalk-setup
spacewalk/setup/bin/spacewalk-setup-cobbler
spacewalk/setup/spacewalk-setup.changes

- Added Apache config folder to default rhn.conf.
- Removed hard coding of Apache config folder during setup.
- Fixed cobbler.conf truncation during setup.
No difference.
Fixes #4165 , #4163 

Cobbler setup fix

---

java/spacewalk-java.changes
schema/spacewalk/susemanager-schema.changes

Add the missing bug ID to changelogs for bsc#1190455
Follow up to: https://github.com/uyuni-project/uyuni/pull/4134

Add bug ID to changelogs for bsc#1190455

---

spacewalk/certs-tools/rhn_bootstrap_strings.py
spacewalk/certs-tools/spacewalk-certs-tools.changes
susemanager/src/mgr_bootstrap_data.py
susemanager/susemanager.changes

Port of https://github.com/SUSE/spacewalk/pull/15484

Use the apt-key in case of debian based machines to add the gpg keys

---

proxy/installer/spacewalk-proxy-installer.spec

Fix syntax error in spec file
No difference.

fix duplicate post section is spec

---

susemanager-sync-data/susemanager-sync-data.changes

No difference.
Before:
After:
Fixes # …

add susemanager-sync-data changelog entries

---

java/spacewalk-java.changes

changelog - fix mgr-sync refresh (bsc#1191222)

---

.github/reviewers.yml
testsuite/features/step_definitions/command_steps.rb

Minor test suite fixes:
* better error message for openscap packages
* update reviewers list
* better error message for cobbler sync
Ports:
* 4.1:
* 4.2:

Minor changes

---

spacewalk/admin/spacewalk-admin.spec

Follow up on https://github.com/uyuni-project/uyuni/pull/4301

remove empty dir from specfile

---

web/po/sk.po

update translations
No difference.
- No tests: translation

translation update

---

client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes
client/tools/mgr-cfg/mgr-cfg.changes
client/tools/mgr-custom-info/mgr-custom-info.changes
spacewalk/config/spacewalk-config.changes
susemanager-frontend/susemanager-nodejs-sdk-devel/susemanager-nodejs-sdk-devel.changes

Add missing changelog entries for https://github.com/uyuni-project/uyuni/pull/3824 and https://github.com/uyuni-project/uyuni/pull/4295, so I can tag the changes.
No difference.
- No documentation needed: Missing changelogs
- No tests: Missing changelogs
None

Add missing changelog entries

---

testsuite/run_sets/build_validation_sanity_check.yml

Adds a new build validation sanity check yml file for this [PR 
](https://github.com/SUSE/susemanager-ci/pull/366) 
No difference.
Before:
After: …

Add new build validation sanity check yml file

---

testsuite/features/step_definitions/command_steps.rb

The LTSS repo exists only for products which are end of there general lifetime. sumaform sometimes have it and sometimes not.
To prevent that this makes the testsuite fail all the time, make it optional and do not check for error if enabling failed.
No difference.
- Cucumber tests changed
Tracks https://github.com/SUSE/spacewalk/pull/16345 https://github.com/SUSE/spacewalk/pull/16346 …

in testsuite make ltss repo optional

---

testsuite/features/step_definitions/common_steps.rb

Refine the removal of workaround for bsc #1191444

---

testsuite/features/secondary/allcli_software_channels.feature

Wait for the deferred action to be picked up

---

backend/satellite_tools/repo_plugins/deb_src.py

Add missing import of rhnSQL required for https://github.com/uyuni-project/uyuni/pull/3921
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/3559#issuecomment-961909014
Not required as the change was not released yet

Add missing import to deb_src.py

---

testsuite/features/support/xmlrpc_system.rb

Make sure the proxy id is an integer

---

testsuite/features/step_definitions/salt_steps.rb

Testsuite: Fix typo when on step redirection

---

testsuite/features/build_validation/add_custom_repositories/add_ceos8_repositories.feature

Press "Create Filter" button

---

java/spacewalk-java.changes

Add changelog for PR#4483

---

testsuite/features/build_validation/smoke_tests/smoke_tests.template
testsuite/features/secondary/srv_handle_channels_with_ISS_v2.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/step_definitions/docker_steps.rb
testsuite/features/support/client_stack.rb

* regenerate kernel on SLE 11 SP4
* style and English fixes
See also uyuni-project/sumaform#1018
Ports:
* 4.1: SUSE/spacewalk#16458
* 4.2: SUSE/spacewalk#16457

Fix reboot problem

---

schema/spacewalk/susemanager-schema.changes
schema/spacewalk/upgrade/susemanager-schema-4.3.3-to-susemanager-schema-4.3.4/002-use_almalinux_mirror.sql
utils/spacewalk-common-channels.ini
utils/spacewalk-utils.changes

Partial fix for https://github.com/SUSE/spacewalk/issues/14388
No difference.
- No tests
Partial fix for https://github.com/SUSE/spacewalk/issues/14388

Update common channels to almalinux mirror list

---

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE-Bug.md

Grammar and typos
Fix typos in bug template
No difference.
Fixes #

Fix typos in bug template

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/activationkey/ActivationKeyHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/profile/ProfileHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/profile/system/SystemDetailsHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/code/src/com/redhat/rhn/frontend/xmlrpc/system/config/ServerConfigHandler.java
java/spacewalk-java.spec

Do not use primitive types as function parameters for XMLRPC.
No difference.
https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/961/

change boolean into Boolean

---

testsuite/features/build_validation/init_clients/proxy.feature
testsuite/features/core/proxy_branch_network.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/step_definitions/navigation_steps.rb
testsuite/features/step_definitions/salt_steps.rb
testsuite/features/support/constants.rb

Reverts uyuni-project/uyuni#4556

Revert "QA: Disable IPv4 forwarding on branch formula"

---

java/manager-build.xml

Add a new ant task named "test-report" which allows us to run the tests and create a report. it can be useful when running locally to find tests with errors.
Will be produced an XML report and an HTML report.
The html report will be located at `java/test-results/html`.
This can be served as web page by running the following command inside the html foulder: `python3 -m http.server 8000`
No difference.
Before:
After:
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documenta …

add task to create test report for unit tests

---

testsuite/features/build_validation/core/allcli_sanity.feature
testsuite/features/build_validation/init_clients/proxy.feature
testsuite/features/core/allcli_sanity.feature
testsuite/features/core/proxy_branch_network.feature
testsuite/features/step_definitions/command_steps.rb
testsuite/features/step_definitions/common_steps.rb
testsuite/features/step_definitions/salt_steps.rb
testsuite/features/step_definitions/xmlrpc_common.rb
testsuite/features/support/commonlib.rb
testsuite/features/support/constants.rb
testsuite/features/support/lavanda.rb
testsuite/features/support/twopence_init.rb
testsuite/features/support/xmlrpc_system.rb

Refactor how we handle interfaces in Lavanda nodes.
Note: It also includes missing code from a reverted/re-added related PR 
No difference.
Ports:
- Manager-4.1
- Manager-4.2

QA: Refactor how we handle interfaces in Lavanda nodes

---

susemanager/bin/mgr-setup
susemanager/susemanager.changes

Installation on Rocky Linux 8 now works.
No difference.
Not tested. Low impact change.

Added installation on Rocky Linux 8

---

web/html/src/components/FormulaForm.tsx
web/html/src/components/formulas/EditGroup.tsx
web/html/src/components/formulas/FormulaComponentGenerator.tsx
web/html/src/components/formulas/Group.tsx
web/html/src/components/formulas/SectionToggle.tsx
web/spacewalk-web.changes

Revert https://github.com/uyuni-project/uyuni/pull/4278 since it was merged accidentally and causes the testsuite to break

Revert "Merge pull request #4278"

---

web/html/src/manager/systems/proxy.tsx

Fix unused variables in https://github.com/uyuni-project/uyuni/pull/4313
No difference.
- No tests.
Related to https://github.com/uyuni-project/uyuni/pull/4313

Fixes for Changing proxy PR

---

spacewalk/setup/spacewalk-setup.spec

Fixes the build on Enterprise Linux
No difference.
- No tests: copy/pasted from existing code
Fixes #4600 

Added RHEL package for PR4600

---

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml

Provide string for "ovalfiles" which produce errors in the logs
No difference.

add string ovalfiles

---

web/html/src/.eslintrc.js
web/html/src/.eslintrc.production.js
web/html/src/build/.eslintrc.js
web/html/src/components/action-schedule.tsx
web/html/src/components/formulas/FormulaComponentGenerator.tsx
web/html/src/components/utils/HashRouter.tsx
web/html/src/manager/admin/config/monitoring-admin.tsx
web/html/src/manager/clusters/add-cluster/add-cluster.renderer.tsx
web/html/src/manager/clusters/add-cluster/finish-add.tsx
web/html/src/manager/clusters/cluster/cluster.renderer.tsx
web/html/src/manager/clusters/join-cluster/join-cluster.renderer.tsx
web/html/src/manager/clusters/list-clusters/list-clusters.renderer.tsx
web/html/src/manager/clusters/remove-node/remove-node.renderer.tsx
web/html/src/manager/clusters/upgrade-cluster/upgrade-cluster.renderer.tsx
web/html/src/manager/content-management/list-filters/list-filters.renderer.tsx
web/html/src/manager/content-management/list-projects/list-projects.renderer.tsx
web/html/src/manager/content-management/project/project.renderer.tsx
web/html/src/manager/images/image-import.tsx
web/html/src/manager/minion/packages/package-states.tsx
web/html/src/manager/minion/packages/use-package-states.api.tsx
web/html/src/manager/notifications/notifications.tsx
web/html/src/manager/organizations/config-channels/org-config-channels.tsx
web/html/src/manager/salt/cmd/remote-commands.tsx
web/html/src/manager/systems/ssm/ssm-subscribe-channels.tsx
web/html/src/manager/visualization/ui/components.ts
web/html/src/package.json
web/html/src/utils/network.ts
web/html/src/utils/test-utils/.eslintrc.js

Clean up console logs which are leftover debugging information, require no log in production (error etc is fine), clean up a small Flow-specific check.
No difference.

No console log in production

---

testsuite/features/build_validation/init_clients/proxy.feature
testsuite/features/core/proxy_branch_network.feature
testsuite/features/step_definitions/salt_steps.rb
testsuite/features/support/constants.rb
testsuite/features/upload_files/01-netcfg.yaml

Do not route anymore on the proxy to the private network.
Fixes SUSE/spacewalk#16486
Requires SUSE/salt-formulas#160
Followup of #4566
Replacement of #4590
Ports:
* 4.1: TBD
* 4.2: TBD

Do not route anymore for private network

---

java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_sk.xml
java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_uk.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_uk.xml
java/code/src/com/redhat/rhn/frontend/strings/nav/StringResource_uk.xml
web/po/sk.po

Master weblate translation update

---

client/tools/mgr-push/mgr-push.changes
client/tools/mgr-push/mgr-push.spec
suseRegisterInfo/suseRegisterInfo.changes
suseRegisterInfo/suseRegisterInfo.spec

Adding missing fixes from https://github.com/uyuni-project/uyuni/pull/4662
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/16508

Add missing "sle_version" conditionals in #4662

---

testsuite/features/step_definitions/common_steps.rb

Trying to make my huge retail PR portable from branch to branch...
In this PR it's about aligning code for a workaround that has not been removed back to the original.

Realign with the other branches

---

testsuite/features/support/env.rb

Add missing cucumber tags.
Ports:
* 4.1: SUSE/spacewalk#16694
* 4.2: SUSE/spacewalk#16695

Add definition for Debian 11 minion tags

---

susemanager-utils/testing/automation/obs-project.py

Fix typo in ci

---

testsuite/features/upload_files/sle-15-sp2-autoyast.xml

Reverts uyuni-project/uyuni#4691
this will be fixed another way that doesn't interfere with the virtualisation test

Revert "Force tftp to use proxy instead of server"

---

backend/rhn-conf/rhn.conf
rel-eng/packages/uyuni-setup-reportdb
spacewalk/spacewalk-setup-postgresql/bin/spacewalk-setup-postgresql
spacewalk/uyuni-setup-reportdb/LICENSE
spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes
spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.spec
susemanager/bin/mgr-setup

Setup tool for configuring the reporting DB
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/16560

implement setup script for reporting database

---

testsuite/features/step_definitions/common_steps.rb

It seems SUSE manager takes like public IPv6 to display it in the details page.
This PR does the same.
Also it fixes the style:
* no need to look on `/etc/release` to determine the OS type and family, we now have `public_interface` variable on nodes
* let's raise an exception if the command could not be run
* no need to do complicated bash pipes, ruby has all the necessary ammunition to do text processing :smile_cat: .
Ports:
* 4.1: SUSE/spacewalk#16759
* 4.2: SUSE/spacewalk#16760

Fix IPv6 in details page

---

testsuite/features/step_definitions/common_steps.rb

Adds 11 hours to every 24h increment to consider the next day, due to moment.js library's rules
No difference.
- [Issue Card](https://github.com/SUSE/spacewalk/issues/16720)
- 4.1
- 4.2

Add 11 hours to rounded days

---

testsuite/features/core/proxy_register_as_minion_with_gui.feature
testsuite/features/core/proxy_register_as_minion_with_script.feature
testsuite/features/core/proxy_register_as_trad_with_script.feature
testsuite/features/secondary/srv_mainpage.feature
testsuite/features/secondary/srv_users.feature
testsuite/features/secondary/trad_baremetal_discovery.feature
testsuite/features/step_definitions/navigation_steps.rb

Removed the $PRODUCT references in the Cucumber tests, both in the Gherkin steps and the steps themselves.
No difference.
Fixes [#5885](https://github.com/SUSE/spacewalk/issues/5885)

Refactor product cucumber names

---

backend/tito.props
java/conf/rhn_java.conf
java/tito.props
spacewalk/admin/spacewalk-startup-helper
spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.spec

- Integrate report db checks into the bootprocess
- inititalize the schema when setting up the DB
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/16561

Hub reporting report integration

---

sonar-project.properties

See title
No difference.
- No tests: Tooling config

Add sonarqube scanner configuration

---

sonar-project.properties

Fine tune the sonarqube configuration
No difference.
- No tests: tool config
Fixes #

Sonarqube config tweaks

---

proxy/installer/configure-proxy.sh
proxy/installer/spacewalk-proxy-installer.changes
proxy/installer/spacewalk-proxy-installer.spec
proxy/installer/spacewalk-setup-httpd
proxy/proxy/spacewalk-proxy.changes
proxy/proxy/spacewalk-proxy.spec
spacewalk/certs-tools/Makefile.certs
spacewalk/certs-tools/gen-test-cert-chain.sh
spacewalk/certs-tools/mgr-ssl-cert-setup
spacewalk/certs-tools/mgr_ssl_cert_setup.py
spacewalk/certs-tools/spacewalk-certs-tools.changes
spacewalk/certs-tools/spacewalk-certs-tools.spec
spacewalk/config/spacewalk-config.changes
spacewalk/config/spacewalk-config.spec
spacewalk/setup/bin/spacewalk-setup
spacewalk/setup/lib/Spacewalk/Setup.pm
spacewalk/setup/share/ssl.conf.7
spacewalk/setup/share/ssl.conf.8
spacewalk/setup/spacewalk-setup.changes

No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/1345
Fixes #
https://ci.nue.suse.com/view/Manager/view/Uyuni-PRs/job/uyuni-prs-ci-tests/955/

Change certificate setup

---

testsuite/features/step_definitions/command_steps.rb

Followup of previous PR. Do it the same way as in 4.1 and 4.2.
No ports.

Realign with other branches

---

web/html/src/jest.config.js
web/html/src/package.json

Reverts uyuni-project/uyuni#4789 as it didn't fix the issue in CI.

Revert "Test Jest performance throttling"

---

java/code/src/com/redhat/rhn/domain/scc/SCCRepository.java
java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataExtractor.java

Correct some sonar error on PAYG code
No difference.
Before:
After:
Fixes #
Tracks # **add …

correct sonar errors

---

spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb

Fix setup of the reporting database
No difference.

Hub reporting fix setup

---

java/code/src/com/redhat/rhn/common/db/datasource/xml/ChannelReport_queries.xml
java/code/src/com/redhat/rhn/common/db/datasource/xml/ReportDb_queries.xml
java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemReport_queries.xml
schema/reportdb/common/tables/Channel.sql
schema/reportdb/common/tables/Errata.sql
schema/reportdb/common/tables/Package.sql
schema/reportdb/common/tables/System.sql
schema/reportdb/common/tables/SystemAction.sql
schema/reportdb/common/tables/SystemChannel.sql
schema/reportdb/common/tables/SystemConfigChannel.sql
schema/reportdb/common/tables/SystemEntitlement.sql
schema/reportdb/common/tables/SystemErrata.sql
schema/reportdb/common/tables/SystemGroup.sql
schema/reportdb/common/tables/SystemHistory.sql
schema/reportdb/common/tables/SystemOutdated.sql
schema/reportdb/common/tables/SystemPrimaryAddress.sql
schema/reportdb/common/tables/SystemVirtualData.sql
schema/reportdb/common/tables/dual.sql
schema/reportdb/common/views/ErrataListReport.sql
schema/reportdb/common/views/HistoryReport.sql
schema/reportdb/common/views/InactiveSystemsReport.sql
schema/reportdb/common/views/InventoryReport.sql
schema/reportdb/common/views/views.deps

Add the table and view definition for the reporting database
No difference.
- No tests: no code change
Fixes https://github.com/SUSE/spacewalk/issues/16564

Reporting database schema

---

java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
java/code/src/com/redhat/rhn/common/db/datasource/WriteMode.java
java/code/src/com/redhat/rhn/common/db/datasource/xml/ChannelReport_queries.xml
java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemReport_queries.xml
java/code/src/com/redhat/rhn/common/hibernate/ReportDbConnectionManager.java
java/code/src/com/redhat/rhn/taskomatic/task/ReportDbUpdateTask.java
java/conf/default/rhn_reporting_hibernate.conf
java/spacewalk-java.spec

This fixes a few things so that the taskomatic job can properly connect to the reporting db. It also adds batching to the first reporting database query.
No difference.
- No tests
Fixes #

Reporting DB Taskomatic job

---

java/code/src/com/redhat/rhn/common/db/datasource/xml/ChannelReport_queries.xml
java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemReport_queries.xml
java/code/src/com/redhat/rhn/common/db/datasource/xml/file-list.xml
java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
java/code/src/com/redhat/rhn/taskomatic/task/ReportDbUpdateTask.java
schema/reportdb/common/tables/Errata.sql
schema/reportdb/common/tables/SystemVirtualData.sql
schema/reportdb/common/views/ErrataListReport.sql
schema/reportdb/common/views/HistoryReport.sql
schema/reportdb/common/views/InventoryReport.sql
schema/reportdb/common/views/SystemInactivityReport.sql
schema/reportdb/common/views/views.deps

Hub reporting fill reportdb tables

---

testsuite/features/reposync/srv_sync_products.feature

Beta Client Tools Products are now extensions of the normal Client Tools Products.
(exception: SLE12 - with SLE12 we included the client tools channels into the SLE main product)
No difference. …

Beta Client Tools are now extension of client tools

---

testsuite/features/step_definitions/common_steps.rb

Account for non deterministic IPv6 address being shown
No difference.
- [4.1](https://github.com/SUSE/spacewalk/pull/17056)
- [4.2](https://github.com/SUSE/spacewalk/pull/17055)

Account for non deterministic ipv6 address

---

spacewalk/admin/spacewalk-admin.changes
spacewalk/admin/spacewalk-service.systemd
spacewalk/admin/spacewalk-startup-helper
spacewalk/admin/uyuni-check-database.service
spacewalk/config/spacewalk-config.changes
spacewalk/config/spacewalk-config.spec

fix some errors during migration
No difference.

Fix db migration

---

testsuite/run_sets/secondary.yml

Fixup of https://github.com/uyuni-project/uyuni/pull/4833
No difference.
[Manager 4.2](https://github.com/SUSE/spacewalk/pull/17073)
[Manager 4.1](https://github.com/SUSE/spacewalk/pull/17072)
Make sure the changelogs entries you …

QA: fixup for CentOS 7 migration test

---

testsuite/run_sets/secondary.yml

This will temporarily disabled the newly introduced migrations since we have a lot of issues in the CI that worked before. See the links section below for more information.
No difference.
- Cucumber tests were commented out
At the moment we test this only in …

QA: Temporarily disable new migrations

---

java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java

Rebase the changes from Cedric from IntellJ autofixes**
No difference.
- No documentation needed: Rebase
- No tests: Rebase
None

Rebase the changes from Cedric from IntellJ autofixes

---

java/spacewalk-java.changes
java/spacewalk-java.spec

rebase of https://github.com/uyuni-project/uyuni/pull/4893

Sbluhm startup issues

---

spacewalk/certs-tools/mgr_ssl_cert_setup.py

Fixes certificate folder for Enterprise Linux
No difference.
Fixes #

Updated path for RHEL

---

spacewalk/certs-tools/update-ca-cert-trust.sh

`update-ca-cert-trust.sh` must now handle also the HTTP dir. Also the case that the client is registered and has an own different ca.
No difference.

handle HTTP trust dir as well

---

java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
java/code/src/com/redhat/rhn/manager/kickstart/FilePreservationListsCommand.java
java/code/src/com/redhat/rhn/taskomatic/task/repomd/RpmRepositoryWriter.java
java/code/src/com/suse/manager/gatherer/GathererRunner.java
java/code/src/com/suse/pam/Pam.java

Fixes SonarQube warnings introduced by the big Java cleanup PR
No difference.
Fixes #

Fix newly uncovered SonarQube errors

---

testsuite/LICENSE

Update year in our MIT-LICENSE, and rename it.
No difference.
Ports:
- Manager-4.1 https://github.com/SUSE/spacewalk/pull/17018
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/17019

QA: Update year in our MIT-LICENSE

---

java/spacewalk-java.changes

adds a bugzilla reference to the changelog
No difference.
- No tests
Fixes #

add bsc to changelog entry

---

java/buildconf/ivy/ivy-suse.xml

update ivy config as c3p0 was updated to 0.9.5.5

update ivy config as c3p0 was updated
