- testsuite/features/step_definitions/common_steps.rb
With the previous code, if time was greater than half an hour but less than an hour, it was calculating 0 days.
Fixes uptime test
No difference.
- No tests
N/A
> fix uptime test

- .github/workflows/test_all_in_one_common.yml
- testsuite/Gemfile
- testsuite/features/secondary/allcli_overview_systems_details.feature
- testsuite/podman_runner/02_setup_network.sh
- testsuite/podman_runner/03_run_controller.sh
- testsuite/podman_runner/04_setup_ssh_controller.sh
- testsuite/podman_runner/05_install_gems_in_controller.sh
- testsuite/podman_runner/06_start_server.sh
- testsuite/podman_runner/07_manager_setup.sh
- testsuite/podman_runner/08_build_server_code.sh
- testsuite/podman_runner/09_run_sshminion.sh
- testsuite/podman_runner/10_setup_sshd.sh
- testsuite/podman_runner/11_run_core_tests.sh
- testsuite/podman_runner/12_run_salt_sle_minion.sh
- testsuite/podman_runner/13_run_salt_rhlike_minion.sh
- testsuite/podman_runner/14_run_salt_deblike_minion.sh
- testsuite/podman_runner/15_accept_all_keys.sh
- testsuite/podman_runner/16_run_init_clients_tests.sh
- testsuite/podman_runner/17_run_secondary_tests.sh
- testsuite/podman_runner/18_run_secondary_parallelizable_tests.sh
- testsuite/podman_runner/18_run_secondary_parallelizable_tests_subset.sh
- testsuite/podman_runner/18_split_secondary_p_tests.sh
CI: Enable hardware refresh tests
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/20956
> CI: Acceptance tests at PR v2: enable hw refresh

- java/spacewalk-java.changes
- java/spacewalk-java.spec
- spacewalk/setup/spacewalk-setup.changes
- spacewalk/setup/spacewalk-setup.spec
- susemanager/susemanager.changes
- susemanager/susemanager.spec
spacewalk-java:
- Cleanup of spacewalk-java file to reduce complexity.
- Remove glassfish-jaxb-core requirement for Enterprise Linux.
- Update package requirement libtcnative-1-0 to tomcat-native to have common name between EL and SUSE.
spacewalk-setup:
- Corrected tomcat installation requirement.
susemanager.spec
- Ensure installation of make for building. Build might fail (does fail on copr) otherwise.
No difference.
Fixes #
If you …
> Cleaning of spacewalk-java.spec/susemanager.spec/spacewalk-setup.spec

- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/features/secondary/min_bootstrap_ssh_key.feature
Part of https://github.com/SUSE/spacewalk/issues/14021
Describing feature dependencies for SLE Minion bootstrap
No difference.
- Cucumber tests were described
Ports:
- Manger-4.3
- Manager-4.2
> QE: Describing feature dependencies for SLE Minion bootstrap

- java/code/src/com/suse/manager/reactor/messaging/RegistrationUtils.java
- java/spacewalk-java.changes
When executing a full highstate at registration time, it was not executed with a user object.
This lead to invisible result details in the system history as the org does not match.
No difference.
- No tests: **detail**
Port of https://github.com/SUSE/spacewalk/pull/21265 …
> execute highstate on registration with a user if available

- susemanager-utils/susemanager-sls/salt/images/kiwi-image-inspect.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes
Bundle image build can be enabled via custom info. It was however enabled only in build phase, not in inspect phase.
This caused further problems with registering images to cobbler.
This PR fixes it.
No difference.
- covered by openqa tests
> Fix enabling bundle build via custom info

- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerSystemCreateCommand.java
- java/spacewalk-java.changes
When `self_update=0` is set in distro, we should not add the URL to the installer update repo.
Only when no "self_update" option exists, or if it is a URL, it should be written and point to the install server which can be a proxy.
Additionally this fix an index out of bound exception when a network interface without IP addresses is part of the server object.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/21284 …
> Fix reinstall kernel opts

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/content/MgrSyncUtils.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
- java/spacewalk-java.changes
When neither SCC credentials nor a local mirror is configured happens,
the isRefreshNeeded() method result in an NPE and we have only a Internal Server Error.
But in such a case a refresh is not needed, so we now return just false.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/21287
If you need …
> Fix ise no scc creds nor fromdir

- java/code/src/com/suse/manager/saltboot/SaltbootUtils.java
- java/spacewalk-java.changes
Registering OS images in Cobbler is optional and must be configured first.
This PR replaces exception with log.warn on systems where it is not configured.
No difference.
> Do not throw on missing saltboot group

- testsuite/dockerfiles/rocky-minion/etc_pam.d_sshd
CI: fix rhlike minion
No difference.
- No tests
N/A
> CI: Acceptance tests at PR v2: fix rhlike

- testsuite/features/secondary/srv_cobbler_profile.feature
This PR fixes several points that diverge from our conventions.
In particular "feature" is a feature of the product. It is not a feature of SUSE Manager to crash with ISEs. It is a feature to be able to edit Cobbler profiles.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/21321
* 4.2: N/A
> A "feature" is a feature of the product

- java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
- web/html/src/manager/content-management/shared/components/panels/sources/channels/channels-api-transforms.ts
- web/spacewalk-web.changes
When clicking  on a CLM projects `Attach/Detach Sources` prevent the popup from loading forever by ignoring mandatory channel results that don't match the list of channels.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/19250 …
> Ignore mandatory channels results that don't match list of channels

- testsuite/features/step_definitions/common_steps.rb
Follow-up of #6974
Measured 777 seconds to transfer Rocky 8, the timeout was at 700 seconds -> the ISO image was truncated
Ports together with ports of #6974
> Increased timeout for the Rocky 8 case

- testsuite/features/build_validation/retail/proxy_branch_network.feature
- testsuite/features/core/proxy_register_as_minion_with_gui.feature
- testsuite/features/core/proxy_register_as_minion_with_script.feature
Remove expect package installation for Proxy from testsuite and move it to sumaform
Issue : https://github.com/SUSE/spacewalk/issues/21328
Sumaform : https://github.com/uyuni-project/sumaform/pull/1295
> Move expect package installation to sumaform

- java/code/src/com/redhat/rhn/domain/action/salt/ApplyStatesActionResult.java
- java/code/src/com/suse/manager/webui/utils/YamlHelper.java
- java/code/src/com/suse/manager/webui/utils/test/YamlHelperTest.java
- java/spacewalk-java.changes
In some big setups, the state result file can be huge and Snakeyaml now has a document limit. Set this limit to the maximum value.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/21333 …
> Increase the maximum size of YAML state result to parse

- testsuite/features/step_definitions/vm_steps.rb
Until now the MAC address found in the environment variable
`MAC_MIN_NESTED` in the `.bashrc` of the controller will be always used
when we have a nested VM. In our case it should only be used for the
SLES minion where we test the Salt migration and where we have dedicated MAC- and IP addresses.
No difference.
Manager 4.3:  …
> QE: Fix MAC address for nested VMs

- testsuite/features/secondary/min_salt_migration.feature
This will refactor the checks after migrating the minion to the Salt bundle in order to have clearer results what fails and to not skip a lot of steps if for example the first step in a scenario fails.
No difference.
- no ports! …
> QE: Refactor Salt bundle migration tests

- java/code/src/com/redhat/rhn/frontend/action/ssm/CustomValueSetAction.java
- java/spacewalk-java.changes
Pillars must be refreshed after setting custom info values.
- No tests: JSP stack
Fixes https://github.com/SUSE/spacewalk/issues/21236
> Refresh pillars after setting custom values via SSM (bsc#1210659)

- spacewalk/certs-tools/mgr-package-rpm-certificate-osimage
- spacewalk/certs-tools/spacewalk-certs-tools.changes
Port of https://github.com/SUSE/spacewalk/pull/21319
Sometimes the order if installing bootstrap packages in kiwi build installs ca-certificate and our package with suma certificate before installing shadow package. When this happens, ca-certificate post install script fails on missing home directory for root user and does not update trust anchors. This then results on zypper  failure to download packages during image build.
This PR adds explicit dependency of our osimage certificate package on shadow package.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/21291
Tracks …
> Add shadow as dependency for osimage certificate package

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/webapp/WEB-INF/pages/systems/sdc/overview.jsp
- java/spacewalk-java.changes
When a system is a virtual guest and we have the information about the host, show it in the Systems Overview page
No difference.
After:
Tracks https://github.com/SUSE/spacewalk/pull/21379
> show virtualization host info in systems overview page

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes
Port of https://github.com/SUSE/spacewalk/pull/21108
This PR adds the bootstrap definitions for SLE-Micro 5.4 and for openSUSE Leap Micro 5.4
Fixes https://github.com/SUSE/spacewalk/issues/20739
> Add bootstrap repository definitions for SLE-Micro 5.4 and openSUSE Leap Micro 5.4

- web/html/src/manager/systems/subscribe-channels/subscribe-channels.tsx
- web/spacewalk-web.changes
When a product has only mandatory channels synced the selection page of software channel change
show the checkbox checked. But when clicking on confirm, the confirm page show the channels "unchecked" and
only the base channel is subscribed.
The selection page test selected channels and mandatory channels separate, but the confirm page only rely on the selected channels list. This means we need to take care that the mandatory channels are added to the selected channels list.
Port of https://github.com/SUSE/spacewalk/pull/21373 …
> force all mandatory channels being selected in software channel change page

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/spacewalk-java.changes
When adding Microfocus NCC Credentials to mirror OES products, the mgr-sync refresh exit with SCCClientException as these credentials do not provide the expected SCC endpoints.
We need to ignore this, if the credentials provide access to OES repositories.
Port of https://github.com/SUSE/spacewalk/pull/21369 …
> on sccclientexception test for OES credentials and move forward

- spacewalk/admin/spacewalk-admin.changes
- spacewalk/admin/spacewalk-admin.spec
1. Added missing python3-websockify requirement for mgr-websockify.service.
2. Removed unnecessary SUSE `BuildRequires`limitation.
No difference.
Fixes # …
> spacewalk-admin: Minor improvements

- testsuite/config/cucumber.yml
- testsuite/features/secondary/min_project_lotus.feature
- testsuite/run_sets/secondary_parallelizable.yml
Pre-requisites for the feature: custom repo for PTFs.
Tests: installation and removal of PTFs through **PTFs** tab in *Software*, as well as through the **Packages** tab.
Fixes https://github.com/SUSE/spacewalk/issues/20887
- 4.3 https://github.com/SUSE/spacewalk/pull/21377
> QE: Add tests for Project Lotus

- python/rhn/SSL.py
- python/rhn/rhnlib.changes
See title. This should address the sonarcloud issues.
No difference.
- No tests: old TLS versions disabled
Fixes https://github.com/SUSE/spacewalk/issues/20641
> Only use TLSv1+ for SSL connections

- testsuite/features/secondary/min_salt_software_states.feature
- testsuite/features/secondary/min_salt_user_states.feature
fix salt states tests
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/20957
> CI:Acceptance tests at PR v2: fix salt state tests

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
This PR specifies x86_64 for Rocky 9 and Oracle 9
It also aligns the way we specify architectures along the various scenarios.
Ports:
* 4.2: https://github.com/SUSE/spacewalk/pull/21434
* 4.3: https://github.com/SUSE/spacewalk/pull/21433
> Properly select architectures in setup wizard

- susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes
- susemanager-utils/supportutils-plugin-susemanager/susemanager
This PR fixes the name of the property to tune to improve the performances of the salt events queue processing. Currently in fact the supportconfig plugin output is referring to the wrong property. 
No difference.
- No documentation needed: the property is already correctly documented
- No tests: fix in the message the supportconfig plugin prints out. …
> Fixed property to tune for salt events queue processing

- susemanager/bin/mgr-setup
Added one more location for detecting the postgresql service name.
Changelog is covered by already existing entry. `- Automatically detect PostgreSQL service and data folder name.`.
I will add a new entry in case a new version has been tagged.
No difference.
Fixes # …
> mgr-setup: Additional postgresql service detection

- java/code/src/com/suse/manager/webui/controllers/login/templates/login.jade
- java/code/webapp/WEB-INF/decorators/layout_error.jsp
- web/html/javascript/spacewalk-essentials.js
- web/html/src/branding/css/base/theme.less
- web/html/src/branding/css/susemanager/components/header.less
- web/html/src/branding/css/susemanager/susemanager-theme.less
- web/html/src/branding/css/updated/layout.scss
- web/html/src/branding/css/uyuni.less
- web/html/src/branding/css/uyuni/header.less
- web/html/src/branding/css/uyuni/legacy-theme.less
- web/html/src/branding/css/uyuni/theme.less
- web/html/src/core/spa/spa-engine.tsx
- web/html/src/core/spa/theme-loader.ts
Add SPA navigation hooks to toggle between the current and updated theme. Deprecate numerous jQuery layout handlers that were causing problems when switching between themes.
Only minor visual alignment changes: the scrollbar wrapper has changed on the main area, the header icons are now more consistently aligned, the header is more uniform between the two themes.
- Documentation issue already exists for the theme update.
Fixes https://github.com/SUSE/spacewalk/issues/18943
Fixes https://github.com/SUSE/spacewalk/issues/18944
If you don't …
> Add theme hooks to SPA navigation

- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
- java/code/src/com/suse/manager/metrics/SystemsCollector.java
- java/spacewalk-java.changes
Use native queries for collecting systems metrics to achieve better performance.
This is a backport of modified implementation in SUSE Manager.
No difference.
- No documentation needed: Only performance improvement.
Backports SUSE/spacewalk#21419
> Use native queries for collecting systems metrics

- testsuite/features/step_definitions/salt_steps.rb
When installing `uyuni-config-formula` on server, it automatically drags  `uyuni-config-modules` package.
During the cleanup, when  `uyuni-config-formula` is removed, `uyuni-config-modules` is left behind.
This in turn creates a problem when starting `salt-minion` on a CentOS 7 minion in 4.2 context:
```
mai 16 12:04:43 suma-42-min-centos7 salt-minion[1890]: [ERROR   ] Failed to import module uyuni_config, this is due most likely to a syntax error:
mai 16 12:04:43 suma-42-min-centos7 salt-minion[1890]: Traceback (most recent call last):
mai 16 12:04:43 suma-42-min-centos7 salt-minion[1890]: File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1658, in _load_module
mai 16 12:04:43 suma-42-min-centos7 salt-minion[1890]: mod = imp.load_module(mod_namespace, fn_, fpath, desc)
mai 16 …
```
> Remove automatically installed dependency if needed

- java/code/src/com/redhat/rhn/frontend/xmlrpc/BaseHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/XmlRpcLoggingInvocationProcessor.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/test/XmlRpcLoggingInvocationProcessorTest.java
- java/code/src/com/suse/manager/api/HttpApiLoggingInvocationProcessor.java
- java/code/src/com/suse/manager/api/LoggingInvocationProcessor.java
- java/code/src/com/suse/manager/api/test/HttpApiLoggingInvocationProcessorTest.java
- java/code/src/com/suse/manager/api/test/LoggingInvocationProcessorTest.java
port of https://github.com/SUSE/spacewalk/pull/21376
> make redacting sensitive values from api logs more robust

- java/code/src/com/suse/scc/SCCSystemRegistrationManager.java
- java/spacewalk-java.changes
This PR changes the error written in logs that happens when deregistering a system that is locally but not in SCC. Now if that scenario takes place, it just prints an info message instead of the error one with the full stacktrace.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/20446
If you …
> Amend misleading error message when deregistering system that is not in SCC

- testsuite/features/secondary/min_deblike_salt_install_package.feature
The `virgo-dummy` package is occasionally not present yet in the upgrade list of the debian minion.
This PR adds a step to wait for the package name to appear before attempting to check it.
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/18971
Tracks # 
4.2
4.3 …
> Testsuite: Wait for package to appear before checking it in the list

- testsuite/Rakefile
- testsuite/index.js
When we rerun test on existing platform, the former results are mixing with the new results creating messy result html summary.
This PR is design for Jenkins run. It will take the build number to create a unique folder where only the test results run during this build will be store.
The html result will only have the last run results.
The former html result will still be available in the former build result directory.
This change will not affect local run.
CI PR : https://github.com/SUSE/susemanager-ci/pull/866
> Create unique result folder

- testsuite/features/secondary/min_project_lotus.feature
Uyuni/ Head (and SUSE Manager 5.0) are expected to sync custom repos automatically by default, so test steps have been adapted to account for that.
Fixes https://github.com/SUSE/spacewalk/issues/21426 and https://github.com/SUSE/spacewalk/issues/21518
> QE: Adapt custom reposync to expected default behavour on uyuni

- testsuite/features/step_definitions/command_steps.rb
- utils/spacewalk-hostname-rename
- utils/spacewalk-utils.changes
* test suite fix: `spacewalk-hostname-rename` does not have `-u` and `-p` parameters
* product fix: wrong name for loop variable in function `refresh_pillar()` of script `spacewalk-hostname-rename`
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/21531
* 4.2: https://github.com/SUSE/spacewalk/pull/21534
> Fixes for bsc#1207550

- java/code/src/com/redhat/rhn/domain/contentmgmt/PackageFilter.java
- java/spacewalk-java.changes
This PR fixes some of the problematic regular expressions reported by SonnarCloud.
It reduces complexity and makes sure that the regex does not match against substring.
No difference.
Partially fixes https://github.com/SUSE/spacewalk/issues/21403 …
> Fix regular expressions in PackageFilter

- testsuite/features/step_definitions/command_steps.rb
This PR works around this bug https://bugzilla.redhat.com/show_bug.cgi?id=1073481
```
[root@suma-42-min-centos7 ~]# systemctl show venv-salt-minion.service -p ActiveState
ActiveState=inactive
[root@suma-42-min-centos7 ~]# systemctl is-active venv-salt-minion 
unknown
```
--> we can't test for `systemctl is-active` to return `inactive` when the service is inactive.
Ports:
* 4.2: https://github.com/SUSE/spacewalk/pull/21554
* 4.3: https://github.com/SUSE/spacewalk/pull/21553
> systemctl is-active does not always return "inactive" if inactive

- testsuite/features/secondary/allcli_software_channels_dependencies.feature
- testsuite/run_sets/secondary_parallelizable.yml
This feature was disabled  since the associated repositories were not necessarily synced (https://github.com/uyuni-project/uyuni/pull/1767).
Now that they are systematically synced, this feature can be re-enabled after being adapted with the right channels.
No difference.
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/21556
4.3 https://github.com/SUSE/spacewalk/pull/21555 …
> Testsuite: Re-enable and adapt allcli_software_channels_dependencies feature

- testsuite/features/step_definitions/command_steps.rb
This PR provides the username and the password that are needed now that `spacewalk-hostname-rename` calls `spacecmd` to refresh the pillars.
Ports:
* 4.2: SUSE/spacewalk#21582
* 4.3: SUSE/spacewalk#21581
> Pass password to spacewalk-hostname-rename command

- testsuite/features/build_validation/add_non_MU_repositories/alma9_minion_build_clm.feature
- testsuite/features/build_validation/add_non_MU_repositories/liberty9_minion_build_clm.feature
- testsuite/features/build_validation/add_non_MU_repositories/oracle9_minion_build_clm.feature
- testsuite/features/build_validation/add_non_MU_repositories/rocky8_minion_add_iso_and_build_clm.feature
- testsuite/features/build_validation/add_non_MU_repositories/rocky9_minion_build_clm.feature
This adds a small step to check if the text `Loading...` is not present. Otherwise we run into the following issues because the loading screen is still there.
No difference.
Before:
After:
- Manager 4.3: https://github.com/SUSE/spacewalk/pull/21583
- Manager 4.2: https://github.com/SUSE/spacewalk/pull/21584 …
> QE: BV Add checker for loading text

- testsuite/features/secondary/allcli_software_channels_dependencies.feature
SCC is needed and without this tag, this tests fails on Pull Request testing where SCC is not configured.
No difference.
- No tests
N/A
> add scc_credentials tag to allcli_software_channels_dependencies.feature

- testsuite/features/secondary/allcli_reboot.feature
- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/secondary/min_action_chain.feature
- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/features/secondary/min_bootstrap_ssh_key.feature
- testsuite/features/secondary/min_change_software_channel.feature
- testsuite/features/secondary/min_deblike_ssh.feature
- testsuite/features/secondary/min_move_from_and_to_proxy.feature
- testsuite/features/secondary/min_rhlike_ssh.feature
- testsuite/features/secondary/min_salt_lock_packages.feature
- testsuite/features/secondary/min_salt_mgrcompat_state.feature
- testsuite/features/secondary/min_salt_minions_page.feature
- testsuite/features/secondary/min_ssh_tunnel.feature
- testsuite/features/secondary/minssh_action_chain.feature
- testsuite/features/secondary/minssh_bootstrap_api.feature
- testsuite/features/secondary/minssh_move_from_and_to_proxy.feature
- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
- testsuite/features/secondary/srv_delete_channel_from_ui.feature
- testsuite/features/secondary/srv_delete_channel_with_tool.feature
- testsuite/features/secondary/srv_monitoring.feature
- testsuite/features/secondary/srv_power_management_api.feature
- testsuite/features/secondary/srv_restart.feature
- testsuite/features/secondary/srv_users.feature
This PR adds comments to describe which features in the testsuite can fail when the current feature fails.
This PR only includes this in features part of the `secondary` stage. The `secondary_parrallelizable` features will be included into another PR.
Some differences will appear in 4.2 and 4.3 branches to account for traditional clients.
No difference.
Fixes #
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/21479
4.3 https://github.com/SUSE/spacewalk/pull/21480
If …
> QE: Documenting which features will fail if a given feature fails

- susemanager-utils/susemanager-sls/modules/tops/mgr_master_tops.py
- susemanager-utils/susemanager-sls/salt/switch_to_bundle/mgr_switch_to_venv_minion.sls
- susemanager-utils/susemanager-sls/salt/util/mgr_switch_to_venv_minion.sls
- susemanager-utils/susemanager-sls/src/tests/test_mgr_master_tops.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes
This is the implementation corresponding to the Uyuni RFC [#00096 ](https://github.com/uyuni-project/uyuni-rfc/blob/master/accepted/00096-automatic-migration-salt-bundle.md)
The intention of this PR is to automatically perform the migration for Salt 3000 clients to Salt Bundle, as Salt 3000 is EOL. This process should be transparent to the user.
The implementation adds a migration state to the highstate that checks the conditions to performe the migration are satisfied.
NOTE: This has been manually tested with an SLE 12 SP5 and a CentOS 7 client in the development environment.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/21145 …
> Force migration from Salt 3000 clients to Salt Bundle

- web/html/src/branding/css/base/theme.less
- web/spacewalk-web.changes
Fix page layout blowing out of proportion on pages with logs that have long unwrappable lines.
Bugfix.
Before:
After:
- No tests: Bugfix.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1211713
> Fix layout alignment on pages showing failed states logs (bsc#1211713)

- testsuite/features/step_definitions/command_steps.rb
We need to call `spacecmd` a first time to pass the API credentials before we call `spacewalk-hostname-rename`. But at this point the new SSL certificate is not created yet, so we need option `--nossl`.
Ports:
* 4.2: https://github.com/SUSE/spacewalk/pull/21599
* 4.3: https://github.com/SUSE/spacewalk/pull/21598
> Can't use SSL before the new certificate is created

- schema/reportdb/common/views/SystemInactivityReport.sql
- schema/reportdb/upgrade/uyuni-reportdb-schema-4.4.3-to-uyuni-reportdb-schema-4.4.4/01-fix-system-inactivity-report.sql
- schema/reportdb/uyuni-reportdb-schema.changes
This PR changes the view `SystemInactivityReport` of the reporting database to use the `synced_date` column instead of the `current_timestamp` to compute the inactivity. This change is required to make sure the inactive period of a system is correctly calculated at the time of the reporting database synchronization and never changes when extracting the report at different times.
No difference.
- No documentation needed: bugfix of an existing document feature
- No tests: non breaking change in the SQL view definition
Fixes https://github.com/SUSE/spacewalk/issues/21558 …
> Used synced_date instead of current_timestamp in the SystemInactivityReport

- java/spacewalk-java.spec
Remove some of the renamings of Enterprise Linux symlinks to avoid issues on alternative packages/package updates.
This adds some more flexibility to the package structures that can be used.
Changelog can be covered under: "Simplify Java package dependencies"
I will add a new entry in case a merge happens after a new release.
No difference. …
> spacewalk-java/EL: remove symlink renaming

- testsuite/features/secondary/min_salt_formulas.feature
- testsuite/features/secondary/min_salt_user_states.feature
These tests fail because timectl returns an error:
timedatectl failed: System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Let's skip them.
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/20959 …
> CI: Acceptance tests at PR v2: skip apply highstate tests

- containers/server-systemd-services/uyuni-server-services.config
- containers/server-systemd-services/uyuni-server-systemd-services.changes
- containers/server-systemd-services/uyuni-server.service
Migrate a uyuni server to container. 
`uyuni-server-systemd-service` RPM already provide the script `uyuni-server.sh`. There's a new option called `migrate` to migrate a local uyuni server instance to container.
Issue: https://github.com/SUSE/spacewalk/issues/20055
No difference.
- Documentation created https://github.com/uyuni-project/uyuni-docs/pull/2190
- No tests …
> Migrate uyuni server to container

- web/html/src/branding/css/uyuni/legacy-variables.less
- web/html/src/branding/css/uyuni/login.less
**This PR fixes an accessibility issue on the login page. Previously, some texts on the page had very low contrast making them hard to read. This PR lands a fix for those texts**
No difference.
Before:
After:
- No documentation needed: **This is a change in the shade of the color of some tets and so does not require documentation**
Fixes #6776  …
> Fix low contrast texts in Login page

- testsuite/features/secondary/buildhost_docker_build_image.feature
The image deletion cleanup wasn't deleting all the images - made sure all the versions were contemplated in the deletion step.
- 4.2 https://github.com/SUSE/spacewalk/pull/21651
- 4.3 https://github.com/SUSE/spacewalk/pull/21650
- Part of https://github.com/SUSE/spacewalk/issues/21381 …
> QE: Fix deletion of images

- testsuite/features/step_definitions/salt_steps.rb
Refactoring the step to cleanup salt minion left-overs.
- I removed spacewalk-proxy-salt from the packages to remove, until we have a good reason to remove it. I don't find the reason we were doing it in all the minions.
- I fixed the packages we were cleaning in the case of Debian-Like minion in Uyuni
- I re-organized if-statements with the aim to make it easier to read and follow
No difference.
Ports:
- Manager-4.2
- Manager-4.3
If you uncheck …
> Refactoring the step to cleanup salt minion left-overs

- testsuite/ext-tools/maintenance_json_generator.py
Fix missing client tools in Leap json script, we were missing one of the possible client tools suffixes that caused a repo to not be included.
No difference.
Fixes [#21652](https://github.com/SUSE/spacewalk/issues/21652)
Tracks no other PR needed, only uyuni has this script …
> Fix missing client tools in Leap json script

- testsuite/Rakefile
Fix issue when calling index.js to generate cucumber report. The result_folder variable was not correctly recognize.
> Correctly handle result_folder variable when calling index.js

- testsuite/features/secondary/buildhost_docker_auth_registry.feature
- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
One of the likely reasons for issues on the flaky tests on the buildhost, is that we're trying to do a build action while an image profile is still being deleted, as evidenced by the presence of this in the `rhn_web_ui` logs of the server
```yaml
[salt-event-thread-6] WARN  com.suse.manager.utils.SaltUtils - Image Profile ID not found while performing: Image Build suse_real_key in handleImageBuildData
[salt-event-thread-6] WARN  com.suse.manager.utils.SaltUtils - Image Profile ID not found while performing: Image Build suse_real_key in handleImageBuildData
```
These happened after the supposed cleanup and image deletion was done, and we were already trying to build the `auth_registry_profile` image, in the feature that ran after this.
Looking at the code, it gives us a hint of what is …
> QE: Add step to wait for salt jobs to finish on buildhost as part of cleanup

- .github/workflows/acceptance_tests_secondary.yml
- .github/workflows/acceptance_tests_secondary_parallel.yml
CI: Run acceptance tests only when java, js or tests have been modified. Othewise, makes no sense.
No difference.
- No tests
Fixes  https://github.com/SUSE/spacewalk/issues/21454
> CI: Acceptance tests at PR v2: filter paths

- proxy/installer/spacewalk-proxy-installer.changes
- proxy/installer/spacewalk-proxy-installer.spec
- proxy/installer/squid.conf
This PR modifies Squid configuration, by adding custom "refresh_pattern" for `venv-enabled-*.txt` files that are part of bootstrap repositories. This way we ensure to provide fresh version of this files when modified on the Uyuni/SUSE Manager server. 
This fix prevents problems for SSH minions behind proxies, which might still keep using an older Salt Bundle version because this PROXY is still serving an outdated `venv-enabled-*.txt` file pointing to an older Salt Bundle version.
No difference.
- No tests: **covered by BV**
Tracks https://github.com/SUSE/spacewalk/issues/21663 …
> Fix Squid "refresh_pattern" for "venv-enabled-*.txt" files (bsc#1211956)

- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes
This PR fixes a problem on `mgr-create-bootstrap-repo` when generating the `venv-enabled-*.txt` file in cases where there are multiple versions of `venv-salt-minion` package available in the same bootstrap repository.
As there was not explicit sorting of available packages, we could end up with an older `venv-salt-minion` version as the one finally written at generated `venv-enabled-*.txt` file for this bootstrap repo.
No difference.
- No tests: **covered in BV**
Tracks https://github.com/SUSE/spacewalk/issues/21662
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectu …
> Use newest "venv-salt-minion" version available to generate the "venv-enabled-*.txt" files (bsc#1211958)

- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/min_change_software_channel.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/secondary/srv_cobbler_buildiso.feature
- testsuite/features/secondary/srv_cobbler_distro.feature
- testsuite/features/secondary/srv_cobbler_profile.feature
When counting assigned channels on a system we need to take differences between SUMA and Uyuni into account.
In this case with or without Client Tools Channels.
Also marking cobbler log parsing as flaky.
- Cucumber tests changed
4.3 or 4.2 not affected
> Fix counting channels

- testsuite/features/step_definitions/cobbler_steps.rb
After restarting cobblerd we directly test access which fail often just because cobblerd seems not be totally up yet.
Give it a second to start.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/21685
Does not exist in 4.2 …
> give cobbler a second to come up

- containers/proxy-squid-image/proxy-squid-image.changes
- containers/proxy-squid-image/squid.conf
This is a continuation of https://github.com/uyuni-project/uyuni/pull/7089 where we missed to include the new "refresh_pattern" into the `squid.conf` file we use for "proxy-squid-container".
No difference.
- No tests: **covered by BV**
Tracks https://github.com/SUSE/spacewalk/issues/21663 …
> Fix Squid "refresh_pattern" for "venv-enabled-*.txt" files in proxy-squid-container (bsc#1211956)

- testsuite/features/build_validation/retail/sle12sp5_terminal_deploy.feature
- testsuite/features/build_validation/retail/sle15sp4_terminal_deploy.feature
In our retail tests we cannot access the retail terminal via the API because we do not have a twopence target for them available. In the past we simply used the webUI for navigation which is slower compared to the API. In this case we have to rely on the slower webUI steps for retail terminals.
No difference.
- Manager 4.3:
- Manager 4.2: …
> QE: Use webUI steps for accessing system in retail

- java/code/webapp/WEB-INF/pages/common/fragments/audit/scap-list-columns.jspf
- java/spacewalk-java.changes
Port of https://github.com/SUSE/spacewalk/pull/20557
Before:
After: …
> Remove the diff column from the scap results page

- testsuite/features/secondary/srv_mainpage.feature
The copyright year on the Copyright Notice has been updated to 2023, this PR adapts the associated scenario accordingly.
No difference.
Fixes #
Tracks #
4.3
4.2 seemingly not needed
> Testsuite: Update expected copyright date from 2022 to 2023

- testsuite/features/support/env.rb
Change the way the `@skip_if_container` test flag is computed to use a new variable set by sumaform.
No difference.
Fixes #
> Use the CONTAINER_RUNTIME value for @skip_if_container check

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/redhat/rhn/frontend/servlets/EnvironmentFilter.java
- java/code/src/com/redhat/rhn/frontend/servlets/RhnHttpServletResponse.java
- java/spacewalk-java.changes
- spacewalk/setup/bin/spacewalk-setup
- spacewalk/setup/bin/spacewalk-setup-httpd
- spacewalk/setup/share/vhost-nossl.conf
- spacewalk/setup/spacewalk-setup.changes
- spacewalk/setup/spacewalk-setup.spec
- susemanager/bin/mgr-setup
- susemanager/susemanager.changes
Running the server container in kubernetes will require SSL termination at ingress level and certificates generated outside of the cluster. This change allows disabling those.
No difference.
- No tests: setup scripts
Fixes # …
> Add options to disable ssl in setup

- spacewalk/certs-tools/mgr-package-rpm-certificate-osimage
- spacewalk/certs-tools/spacewalk-certs-tools.changes
- spacewalk/certs-tools/spacewalk-certs-tools.spec
- susemanager/bin/mgr-setup
In the kubernetes case there is no ssl-build folder and the CA certificate is simply mounted in /etc/pki/trust/anchors. Use this file as default in the mgr-package-rpm-certificate-osimage tool.
No difference.
Fixes # …
> Use the CA certificate in the /etc/pki to generate buildhost RPM

- java/code/src/com/redhat/rhn/frontend/taglibs/FormatDateTag.java
- java/code/src/com/suse/manager/webui/utils/UserPreferenceUtils.java
- web/html/javascript/spacewalk-essentials.js
- web/html/src/components/datetime/DateTime.tsx
- web/html/src/components/datetime/DateTimePicker.tsx
- web/html/src/components/datetime/FromNow.stories.md
- web/html/src/components/datetime/FromNow.test.tsx
- web/html/src/components/datetime/FromNow.tsx
- web/html/src/components/datetime/timeProps.test.ts
- web/html/src/components/datetime/timeProps.ts
- web/html/src/core/log/loggerhead.ts
- web/html/src/global.d.ts
- web/html/src/jest.config.js
- web/html/src/manager/legacy/FormatDateTag.tsx
- web/html/src/manager/legacy/index.ts
- web/html/src/styleguide/setup.js
- web/html/src/utils/datetime/localizedMoment.test.ts
- web/html/src/utils/datetime/localizedMoment.ts
- web/html/src/utils/test-utils/setup/index.ts
Make datetime value fields use machine-readable values and correctly use user configuration in titles. Also remove unused code and migrate related code out of the old `spacewalk-essentials.js`.  
Example output:  
```html
<time title="2023-04-25 09:18 PDT" datetime="2023-04-25T09:18:28.475-07:00">a few seconds ago</time>
```
**TODO:** Check if this also fixes bsc#1195190
No difference.
Unit tests were added
Fixes https://github.com/SUSE/spacewalk/issues/18451 …
> Datetime tooltips do not show timestamps

- testsuite/features/secondary/srv_rename_hostname.feature
- testsuite/features/step_definitions/command_steps.rb
Remove timeout on command and add spacewalk service restart in cleanup
No difference.
Fixes #
Tracks #
4.2 https://github.com/SUSE/spacewalk/pull/21719 & https://github.com/SUSE/spacewalk/pull/21631
4.3 https://github.com/SUSE/spacewalk/pull/21731 …
> Testsuite: Enhance hostname rename test feature

- testsuite/run_sets/build_validation/build_validation_core.yml
We are running sanity checks twice and chained. Let's remove the feature from the core stage.
No difference.
- Cucumber tests were removed from the YAML
Ports:
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/21732
- Manager-4.2 https://github.com/SUSE/spacewalk/pull/21733 …
> QE: Remove sanity checks from Core stage, as we have a dedicate stage for them

- testsuite/features/step_definitions/cobbler_steps.rb
In order to be sure that `cobblerd` is ready in the next feature, add a sub-step waiting for `cobblerd` at the end of the cobbler cleanup steps.
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/21736
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/21737 …
> Testsuite: Wait for cobblerd to have restarted at the end of cleanup step

- java/code/src/com/suse/manager/webui/utils/SaltRoster.java
- java/spacewalk-java.changes
This PR escapes the roster with the tags  `{% raw %}` and `{% endraw %}` to [disable jinja processing](https://jinja.palletsprojects.com/en/3.1.x/templates/#escaping). This escaping is needed to prevent the processing of special character sequences like `{{` that might be contained in the password. This also forbids the user to inject a template from the UI fields.
No difference.
- Unit tests: code is not easily testable, work in progress.
Fixes https://github.com/SUSE/spacewalk/issues/21585
If you …
> Disable jinja processing for the roster file

- .github/workflows/acceptance_tests_secondary.yml
- .github/workflows/acceptance_tests_secondary_parallel.yml
CI: excludes running the acceptance tests if only the changelog has changed.
No difference.
- No tests
N/A
> CI: Acceptance tests at PRv2: do not run if we only change the changelog

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
This PR adds SLE-Micro 5.4 Uyuni client tools channels to spacewalk-common-channels
- No tests: change in configuration file
Fixes https://github.com/SUSE/spacewalk/issues/20737
> Added SLE-Micro 5.4 and openSUSE Leap Micro 5.4 to spacewalk-common-channels

- spacewalk/setup/spacewalk-setup.changes
- spacewalk/setup/spacewalk-setup.spec
- uyuni/base/uyuni-base.changes
- uyuni/base/uyuni-base.spec
Updating Enterprise Linux Apache user/group from root:root to apache:apache.
Purpose: Enhance security, simplify recently changed code (keep it simple)
No difference.
> Update Enterprise Linux Apache user/group

- .github/workflows/acceptance_tests_common.yml
CI: Enable running acceptance tests for all users
No difference.
- No tests
Fixes # https://github.com/SUSE/spacewalk/issues/21697
> CI: Acceptance tests at PRv2: enable all users

- testsuite/run_sets/build_validation/build_validation_init_clients.yml
This PR adds SLES and openSUSE 15.5 to our run_sets.
@maximenoel8 are these files still needed with the new pipelines? If not, maybe just remove them to reduce the maintenance load and make things simpler.
Note: the 4.2 port also adds 2 missing files.
Ports:
* 4.2: https://github.com/SUSE/spacewalk/pull/21749
* 4.3: https://github.com/SUSE/spacewalk/pull/21750
> More complete run_set

- spacewalk/setup/bin/spacewalk-setup
Better handle when `no-ssl` is not defined at setup time.
- No tests: setup message
Fixes https://github.com/uyuni-project/uyuni/issues/7129
> Fix no-ssl handling in setup script

- python/spacewalk/satellite_tools/spacewalk-data-fsck
- python/spacewalk/spacewalk-backend.changes
Make spacewalk-data-fsck compatible to Enterprise Linux rpm version.
SUSE version of `rpm.TransactionSet().dbMatch` returns `bytes` whereas the RHEL version returns `string` despite being the same rpm version.
This change checks on the returned value and only converts them to string if they are not.
No difference.
Fixes # …
> Make spacewalk-data-fsck compatible to Enterprise Linux rpm version

- testsuite/features/support/constants.rb
More channels were missing for the addition of all the 15.5 minions and clients.
- 4.2 https://github.com/SUSE/spacewalk/pull/21761
- 4.3 https://github.com/SUSE/spacewalk/pull/21760
> QE: Add missing channels for 15.5 minions

- testsuite/features/build_validation/init_clients/monitoring_server.feature
- testsuite/features/build_validation/smoke_tests/smoke_tests.template
The button to view the dashboards as a list is actually a radio button - have adapted the grafana tests for that fact.
- 4.2 https://github.com/SUSE/spacewalk/pull/21767
- 4.3 https://github.com/SUSE/spacewalk/pull/21768
> QE: Adapt grafana tests to the new grafana version

- java/code/src/com/redhat/rhn/common/messaging/MessageDispatcher.java
- java/spacewalk-java.changes
Port of https://github.com/SUSE/spacewalk/pull/21744
> Release DB connection in RHN Message Dispatcher thread

- spacewalk/certs-tools/rhn_ssl_tool.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
- spacewalk/certs-tools/sslToolCli.py
In order to avoid the password to stay in shell history, allow users to pass a --password-file /path/to/file to get rhn-ssl-tool read the password from the file.
No difference.
- No tests: will be covered when testing container server
Fixes # …
> cert-tools: allow reading the CA password from a files

- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_bootstrap_reactivation.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/run_sets/secondary.yml
- testsuite/run_sets/secondary_parallelizable.yml
Bootstrapping features in secondary parallel stage might cause conflicts with other features when the features will be run in parallel. Moving them to the regular sequential secondary stage seems like the safest choice.
No difference.
Tracks # 
4.2
4.3 …
> Testsuite: Move bootstrap features in regular secondary stage

- java/code/src/com/suse/manager/webui/websocket/Notification.java
- java/spacewalk-java.changes
Port of https://github.com/SUSE/spacewalk/pull/21766
> Improve handling of websocket exceptions

- spacewalk/certs-tools/mgr-package-rpm-certificate-osimage
Fix the name of the CA file after https://github.com/uyuni-project/uyuni/pull/7111
Fixes #
> Fix the name of the cert file in osimage package

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes
This PR adds the RHEL 7, 8 and 9 pool and tools channels to the spacewalk-common-channels.
We talked on Matrix/Gitter 2 months ago about that.
And this is the part which has to be changed for the application itself, the rest of changes will happen in the documentation.
- ~~No documentation needed: **add explanation. This can't be used if there is a GUI diff**~~
- ~~No documentation needed: only internal and user invisible changes~~
- ~~Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for ~~community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).~~
- ~~API documentation added: please review the Wiki page …
> Add RHEL channels to spacewalk-common-channels

- testsuite/features/secondary/allcli_action_chain.feature
The `Action chains on several systems at once` feature was not fully updated when replacing the RedHat-like minion by the SSH minion.
No difference.
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/21777
4.3 https://github.com/SUSE/spacewalk/pull/21776 …
> Testsuite: Replace deprecated references to rhlike minion in feature

- testsuite/features/step_definitions/cobbler_steps.rb
Increase timeout after restart of service slightly
No difference.
Fixes no issue, directly from testsuite review
Tracks # **add downstream PR, if any** needs ports
> Increase timeout after restart of service

- java/code/src/com/redhat/rhn/domain/formula/FormulaFactory.java
- java/spacewalk-java.changes
The monitoring endpoint parse formula metadata files. If they contain yaml errors, they are not properly
catched. Also the information which file is broken is missing in the logs.
Just catch YAML Errors and log the name of the file. Then return an empty collection.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/20699 …
> catch yaml exceptions and report which metadata file is wrong

- projects/perl-Satcon/bin/satcon-deploy-tree.pl
- projects/perl-Satcon/perl-Satcon.changes
- spacewalk/admin/rhn-config-satellite.pl
- spacewalk/admin/spacewalk-admin.changes
- spacewalk/setup/bin/spacewalk-setup
- spacewalk/setup/spacewalk-setup.changes
When running mgr-setup (or mgr-setup -s) and groups www and apache already exist at the same time on the system, permissions are set wrong. Especially /etc/rhn/rhn.conf.
This change reads the used Apache group from the apache config files.
No difference.
Manually tested to install on Leap 15.4 and EL9.
Fixes #7092  …
> Fix to detect correct Apache group instead of assuming it

- .github/workflows/acceptance_tests_common.yml
- .github/workflows/acceptance_tests_secondary.yml
- .github/workflows/acceptance_tests_secondary_parallel.yml
Maintenance mode because of https://github.com/uyuni-project/uyuni/discussions/7164
> CI: disable acceptance tests for maintenance

- testsuite/features/secondary/min_bootstrap_reactivation.feature
- testsuite/features/secondary/min_salt_minions_page.feature
Adding steps to wait for the onboarding process to be completed each time in `Bootstrapping with reactivation key`, since not waiting for these processes to complete leads to leftover tasks in taskomatic.
Also adding a missing `@sle_minion` tag in `Management of minion keys` feature.
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/21814
Tracks # 
4.2
4.3 …
> Testsuite: Wait for end of full onboarding process

- .github/workflows/acceptance_tests_common.yml
- java/buildconf/ivy/ivy-suse.xml
If we install podman, we will actually update it to the latest version, given podman is already installed in the base image.
If we install the latest version, we will have this issue https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394 https://github.com/actions/runner-images/issues/7753
Until this is fixed upstream, we need to not update podman.
No difference.
- No tests
Fixes  https://github.com/uyuni-project/uyuni/discussions/7164 …
> CI: do not update podman

- java/code/src/com/redhat/rhn/frontend/action/common/TinyUrlAction.java
- java/spacewalk-java.changes
> Remove logging tiny url parameters

- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerDistroCreateCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerLoginCommand.java
- java/spacewalk-java.changes
> Do not output XMLRPC token in debug logs

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
Allow usage of openssl3 when replacing certificates with mgr_ssl_cert_setup. Currently Leap 15.5 is using openssl 1. Openssl 3 is outputting the text slightly different. This PR allows handling of the openssl input for v1 and v3.
No difference.
Fixes #
If you need to …
> Add openssl3 compatibility to mgr_ssl_cert_setup

- java/code/src/com/redhat/rhn/common/security/SessionSwap.java
- java/code/src/com/redhat/rhn/common/util/FileUtils.java
- java/code/src/com/redhat/rhn/frontend/action/common/TinyUrlAction.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerDistroCreateCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerLoginCommand.java
- java/code/src/com/suse/manager/ssl/SSLCertManager.java
- java/spacewalk-java.changes
Revert CVE-2023-22644 fixes committed in master in favor of https://github.com/uyuni-project/uyuni/pull/7180
> CVE-2023-22644 revert

- reporting/reports.py
- reporting/spacewalk-report
- reporting/spacewalk-reports.changes
- reporting/spacewalk-reports.spec
- spacewalk/setup/share/embedded_diskspace_check.py
- utils/spacewalk-sync-setup
- utils/spacewalk-utils.changes
- utils/spacewalk-utils.spec
spacewalk-report is a server-side tool, i.e. it does not be Python2-compatible. Six is therefore superfluous.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/21851
Tracks https://github.com/SUSE/spacewalk/pull/21852 …
> Drop salt.ext.six usage

- java/buildconf/ivy/ivy-suse.xml
- java/spacewalk-java.changes
This patch updates the jetty-util (to version 9.4.51) for development and testing purposes. Changelog entry should not be relevant for users, I would suggest we remove it before compiling the final changelog.
Tracks https://github.com/SUSE/spacewalk/pull/21809.
> Uyuni-2023.04: Update jetty-util to version 9.4.51

- java/code/src/com/redhat/rhn/common/security/SessionSwap.java
- java/code/src/com/redhat/rhn/common/util/FileUtils.java
- java/code/src/com/redhat/rhn/frontend/action/common/TinyUrlAction.java
- java/code/src/com/redhat/rhn/frontend/action/renderers/setupwizard/MirrorCredentialsRenderer.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerDistroCreateCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerLoginCommand.java
- java/code/src/com/redhat/rhn/manager/session/SessionManager.java
- java/code/src/com/suse/manager/ssl/SSLCertManager.java
- java/spacewalk-java.changes
Port of commits mentioned in https://github.com/SUSE/spacewalk/issues/20419#issuecomment-1598857943
Related https://github.com/SUSE/spacewalk/issues/21856
> [2023.04] CVE 2023 22644

- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_bootstrap_reactivation.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/run_sets/secondary.yml
- testsuite/run_sets/secondary_parallelizable.yml
Reverts uyuni-project/uyuni#7145
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/21863
> Revert "Testsuite: Move bootstrap features in regular secondary stage"

- testsuite/features/step_definitions/retail_steps.rb
Do not make assumptions about which RH-like minion we use on each branch.
Rocky 8 uses `NetworkManager` service, CentOS uses `network` service.
Alma and others are missing but can be added easily.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/21865
* 4.2: https://github.com/SUSE/spacewalk/pull/21867
Fixes #21779
> Allow both CentOS and Rocky on all branches

- java/code/src/com/redhat/rhn/domain/action/salt/ApplyStatesAction.java
- java/spacewalk-java.changes.mcalmer.Manager-4.3-show-parse-error-reason
The reason why a state apply failed is stored in DB, but not shown in the UI.
This PR change this and print out also the result output which can contain very useful information
Before:
After:
Port of https://github.com/SUSE/spacewalk/pull/21859 …
> show reasons for state apply errors in UI

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.agraul.fix-salt-3006-bootstrap-deps
Add missing Salt 3006.0 deps to bootstrap repos
These are new dependencies that are required for Salt 3006.0
- No tests: Bootstrap repos are created in the cucumber test suite.
Fixes bsc#1212700
Tracks https://github.com/SUSE/spacewalk/pull/21886
Tracks https://github.com/SUSE/spacewalk/pull/21887 …
> Add missing Salt 3006.0 deps to bootstrap repos

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes
- spacewalk/certs-tools/spacewalk-certs-tools.changes.ktsamis.openssl
Reverts c37882bc435bea1c147ca416e609398290c69748 because it broke uyuni and head testsuites. 
Before (with printing the keyId and issuerKeyId and subject for debugging):
```
uyuni-master-srv:~ # /usr/bin/rhn-ssl-tool --gen-server --no-rpm --cert-expiration=3650 --set-org=SUSE --set-org-unit=SUSE --password=spacewalk --set-city=Nuernberg --set-email=uyuni@mgr.suse.de --dir=/root/ssl-
build-fubar --set-state=Bayern --set-hostname=uyuni-master-srv.mgr.suse.de --set-country=DE                                                                                                                        
Generating the web server's SSL private key: /root/ssl-build-fubar/uyuni-master-srv.mgr/server.key …
```
> Revert c37882bc435bea1c147ca416e609398290c69748

- spacewalk/setup/spacewalk-setup.changes.agraul.drop-salt-ext-six-embedded-diskspace-check
Add changelog entry to be aligned with SUMA 4.2 / 4.3. Those version need the changelog since the embedded_diskspace_check change is the only change for spacewalk-setup in the next submission.
Tracks https://github.com/SUSE/spacewalk/pull/21900
Tracks https://github.com/SUSE/spacewalk/pull/21899 …
> Add changelog for embedded_diskspace_check change

- java/code/src/com/redhat/rhn/manager/contentmgmt/DependencyResolver.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/test/DependencyResolverTest.java
- java/spacewalk-java.changes.cbbayburt.disable-modularity
After adding 'None (disable modularity)' filter, modules are still available in the target repository. This patch fixes this behavior.
- Unit tests added
Fixes https://github.com/uyuni-project/uyuni/issues/7133
> Filter out modules properly with 'none' matcher (bsc#1212770)

- testsuite/features/secondary/min_salt_software_states.feature
When running `Salt package states` feature, the initial package state is not always known, which can cause failures in the feature, especially if it already has been run once.
This PR adds a pre-requisite scenario to set those stages as `unmanaged` before running the tests, thus improving the idempotency of the feature.
Example of initial state causing failures after a first run of the feature:
No difference.
Fixes #
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/21938
4.2 https://github.com/SUSE/spacewalk/pull/21939 …
> Testsuite: Set the package states as unmanaged for better idempotency

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/redhat/rhn/common/db/datasource/SelectMode.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/webapp/WEB-INF/pages/common/fragments/systems/group_listdisplay.jspf
- java/conf/rhn_java.conf
- java/spacewalk-java.changes.mbussolotto.update_status
create flag to disable update status (bsc#1212730)
TODO
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/21891
> Create flag to disable update status

- java/code/src/com/suse/manager/gatherer/GathererJsonIO.java
- java/spacewalk-java.changes.cbosdo.vhm-null
This is to avoid errors like the following if the libvirt virtual host gatherer module is installed:
```
Caused by: java.lang.IllegalStateException: Expected a string but was NULL at line 36 column 30 path $..sasl_username
```
No difference.
- No tests: covered in the containerized server tests
Fixes # …
> VHG: read null values

- python/spacewalk/common/rhnConfig.py
- python/spacewalk/spacewalk-backend.changes.cbosdo.product_name
- python/spacewalk/spacewalk-backend.spec
rhnConfig parses the rhn.conf file at import time to set the PRODUCT_NAME constant. This causes issues if the code is not running with sufficient permissions.
Instead, define the PRODUCT_NAME to "Uyuni" in the code and change it to "SUSE Manager" in the spec file when needed.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/21905 and https://github.com/SUSE/spacewalk/issues/21934
If you uncheck …
> Hard code product name in rhnConfig

- testsuite/features/step_definitions/datepicker_steps.rb
The script used to set the timepicker value does not seem to work anymore as the event in `Install a package on the SLES minion with staging enabled` feature is picked immediately instead of 3 minutes later.
This PR replaces this script by an already existing step.
In order to use this existing step, the time formatting when calculating the time ahead has been adapated to be in a 24 hour format and uses the `%k` format argument as indicated by [strftime documentation](https://apidock.com/ruby/DateTime/strftime).
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/20942
https://github.com/SUSE/spacewalk/issues/20943
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/21949
4.3 …
> Testsuite: Change staging time input

- web/html/javascript/susemanager-setup-wizard-mirror-credentials.js
- web/spacewalk-web.changes.mackdk.fix-credential-deletion
This PR restore the ability to delete an SCC credential. In fact, in the credentials page there still was an usage of the function `columnHeight()`, which has been removed by commit [`39e960a`](https://github.com/uyuni-project/uyuni/commit/39e960a811153d01659e0d90b5bf2f6452f648aa#diff-a0325cedf530f28bb95f4dd94807045c3129cef550b580bf3ca8617ed93e74a7). The error prevented the delete button to be activated, thus making the delete functionality inaccessible.
The delete button works again.
- No documentation needed: fix of an existing documented functionality
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuy …
> Remove usage of deleted function columnHeight()

- java/code/src/com/redhat/rhn/frontend/servlets/test/SystemDetailsMessageFilterTest.java
- java/code/src/com/redhat/rhn/manager/audit/ScapManager.java
- java/code/src/com/redhat/rhn/testing/SparkTestUtils.java
- java/code/src/com/suse/manager/api/test/RouteFactoryTest.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/mappers/test/ResponseMappersTest.java
- java/code/src/com/suse/manager/webui/controllers/test/BaseControllerTestCase.java
- java/code/src/com/suse/manager/webui/controllers/test/DownloadControllerTest.java
- java/code/src/com/suse/manager/webui/controllers/test/LoginControllerTest.java
- java/code/src/com/suse/manager/webui/controllers/test/ProxyControllerTest.java
- java/code/src/com/suse/manager/webui/controllers/test/SaltbootControllerTest.java
- java/code/src/com/suse/manager/webui/controllers/test/SetControllerTest.java
- java/code/src/com/suse/manager/webui/controllers/test/VirtualHostManagerControllerTest.java
- java/code/src/com/suse/manager/webui/utils/salt/test/HwProfileUpdateSlsResultTest.java
- java/code/src/com/suse/manager/webui/utils/test/PageControlHelperTest.java
- java/code/src/com/suse/manager/webui/utils/test/SparkTestUtilsTest.java
- java/manager-build.xml
- java/spacewalk-java.changes.mackdk.remove-wrong-dependencies-from-classpath
This PR removes CheckStyle and JaCoCo from compilation and runtime classpath. This two jars contains bundled all their dependencies which can be used by mistake while coding. For example, Guava was used in unit test even though it should not be a dependency of Uyuni (which is addressed in this PR as well). Moreover, the presence of Saxon in the CheckStyle jar meant that, during the execution of unit tests, it was used in place of Xalan. 
Finally, this PR also contains a small refactoring, moving class `SparkTestUtils` to `com.redhat.rhn.testing` (the package currently used for test utility classes) and moving `ResponseMappersTest` to `test`.
No difference.
- No tests: only build related refactorings
Make sure the …
> Remove wrong dependencies from classpath

- spacewalk/admin/salt-secrets-config.py
- spacewalk/admin/spacewalk-admin.changes.mcalmer.spacewalk-admin-cleanup
- spacewalk/admin/spacewalk-admin.spec
Cleanup of some python2 leftovers
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/12358
> remove python2 leftovers

- .github/CODEOWNERS
The generic fallback for Java should not be triggered when there is only a change to a changelog file. This patch adds a pattern to let them be ignored.
> CODEOWNERS: ignore changelogs in the java directory

- containers/server-helm/templates/config.yaml
- containers/server-image/uyuni-setup.service
- containers/server-systemd-services/setup_podman_timezone.sh
- containers/server-systemd-services/uyuni-server-services.config
- containers/server-systemd-services/uyuni-server-systemd-services.spec
- containers/server-systemd-services/uyuni-server.service
set timezone in container
- add TZ to `systemd` configuration. The value in the config file is set to the default one, but it should make more clear to the user that is possible to setup.
- TZ is automatically set if the container is started by systemd ( `timedatectl` is provided by systemd rpm, so it's always present )
To enforce the TZ settings, sumaform enforce the TZ settings using salt grain  https://github.com/uyuni-project/sumaform/pull/1347
No difference.
- Documentation issue was created: [Link for SUSE Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documenta …
> set timezone in the container

- python/spacewalk/common/rhnConfig.py
- python/spacewalk/common/rhnLog.py
- python/spacewalk/spacewalk-backend.changes.cbosdo.rhnconfig-nofile
- python/uyuni/common/fileutils.py
- python/uyuni/uyuni-common-libs.changes.cbosdo.rhnconfig-nofile
Now that rhnLog looks for the apache user and group in rhn.conf unit tests are failing if the file is not present. Use openSUSE values as default if rhn.conf is not available.
Note that this should never happen on a running server instance!
No difference.
Fixes #
If …
> Allow missing rhn.conf file

- susemanager-utils/susemanager-sls/salt/cleanup_minion/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.fix-cleanup-minion-saltssh
When deleting a salt-ssh managed system, the cleanup state try do disable and stop salt-minion process.
This can result in a state.apply error which require a force delete when neither salt-minion nor venv-salt-minion is installed.
In case where a customer use salt-minion against an own salt-master, this would disable and remove a working minion.
This resulted also in testsuite errors.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/21968 https://github.com/SUSE/spacewalk/pull/21969
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-p …
> do not disable salt-minion on salt-ssh managed clients

- testsuite/features/init_clients/buildhost_bootstrap.feature
It is possible that we try to check a checkbox that hasn't loaded yet - this PR adds a waiting step to see the associated text beforehand to try and solve this issue.
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/21372
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/21973
4.3 https://github.com/SUSE/spacewalk/pull/21974 …
> Testsuite: Wait for checkbox text to appear before trying to check

- testsuite/features/secondary/min_ssh_tunnel.feature
Specifies the architecture to select when installing `milkyway-dummy` in order to avoid having the wrong installed version.
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/21121
Tracks #
4.2 https://github.com/SUSE/spacewalk/pull/21976
4.3 https://github.com/SUSE/spacewalk/pull/21975
If you …
> Testsuite: Check package with correct architecture

- testsuite/features/step_definitions/command_steps.rb
Related to https://github.com/SUSE/spacewalk/issues/21992
Fixes a loop that does not time out by itself, causing a testsuite timeout.
No difference.
Related to # https://github.com/SUSE/spacewalk/issues/21992
Tracks # None - only Uyuni (feature is not present as of now on SUSE Manager branches)
If you need …
> Testsuite: Refactor step so loop can time out

- testsuite/features/step_definitions/command_steps.rb
The current timeout setup is never reached as expected resulting in the testsuite waiting indefinitely for the reposync to be completed even when it is stuck.
With this fix, the timeout should be about 2 hours instead of 12.
No difference.
Fixes #
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/21983
4.3 https://github.com/SUSE/spacewalk/pull/21982 …
> Testsuite: Move the 2 hour timeout for reposync to a more appropriate place

- python/uyuni/common/rhn_deb.py
- python/uyuni/uyuni-common-libs.changes.mbussolotto.fix_deb
Python-debian has changed the way it looks up the file names from the tar headers. Somehow they enforce the dot-slash (./) in the file name starting from the version 0.1.44, while it's totally possible to have a tar with file names as simple relative paths like control, not ./control. Since we cannot downgrade the version (introduced to fix https://github.com/SUSE/spacewalk/issues/17726 ) I just introduced a new method to do the same steps performed in version < 0.1.44  (as described here https://github.com/SUSE/spacewalk/issues/21530#issuecomment-1576992005 )
There's already a bug opened to fix issue in `python-debian` library https://www.mail-archive.com/pkg-python-debian-maint@alioth-lists.debian.net/msg00598.html
No difference.
- …
> Workaround for python3-debian bug about collecting control file

- susemanager-utils/susemanager-sls/salt/channels/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.agraul.no-products-for-opensuse
openSUSE repos often contain multiple "product packages", that conflict. The idea is that installer installs the correct product once and that's it. In Uyuni, we currently install all products we can find. That does not work because of the conflict.
No difference.
- No tests: this came up when using openSUSE MicroOS. Until we test with client OSes where this happens (like MicroOS or Tumbleweed), we can't test this properly
Fixes https://github.com/uyuni-project/uyuni/issues/7068 …
> Don't install products on openSUSE client OSes

- java/code/src/com/redhat/rhn/common/security/SessionSwap.java
**Remove conflicting line for making it possible to have a clean backport of security fixes in #7189.
This change will be reverted after  the  backport**
No difference.
- No documentation needed: **this is a temp change for allowing the backport of #7189**
(https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- No tests: **this is a temp change for allowing the backport of #7189**
Relates: #7189
Relates: …
> Remove conflicting line for making it possible to have a clean backport of security fixes in 7189

- java/code/src/com/redhat/rhn/common/security/SessionSwap.java
**Remove conflicting lines for making it possible to have a clean backport of security fixes in https://github.com/uyuni-project/uyuni/pull/7189.
This change will be reverted after the backport together with https://github.com/uyuni-project/uyuni/pull/7275**
No difference.
Before:
After:
- No documentation needed: **this is a temp change for allowing the backport of #7189**
- No tests: **this is a temp change for allowing the backport of #7189**
Relates: https://github.com/uyuni-project/uyuni/pull/7189
Relates: https://github.com/SUSE/spacewalk/issues/21856 …
> Remove conflicting lines for making it possible to have a clean backport of security fixes in 7189

- spacewalk/certs-tools/gen-test-cert-chain.sh
- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.mcalmer.support-ec-crypto-keys-in-certs
SSL Certificates using EC crypographic keys are now supported to get deployed with mgr-ssl-cert-setup tool
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/2360
See also https://github.com/uyuni-project/uyuni/discussions/7236
Tracks https://github.com/uyuni-project/uyuni/pull/7266 …
> Support ec crypto keys in certs

- spacecmd/spacecmd.changes.blu-base.cryptokey_update
- spacecmd/src/spacecmd/cryptokey.py
- spacecmd/tests/test_cryptokey.py
`spacecmd` has function for most API calls for managing SSL/GPG keys, such as creating and deleting. There also is an API call [to update](https://www.uyuni-project.org/uyuni-docs-api/uyuni/api/kickstart.keys.html#apidoc-kickstart_keys-update-loggedInUser-description-type-content) keys. However, the function to update a key is missing in `spacecmd`.
This PR adds the function `cryptokey_update` to update SSL/GPG keys in the same way as creating them via `spacecmd`.
Discussion point:  
This mostly duplicates code present in the `cryptokey_create` function, respectively the method `do_cryptokey_create` in `/spacecmd/src/spacecmd/cryptokey.py` and its test. It might be advantageous to extract the common logic between the create, and update function. Would you suggest further such work?
No …
> Add spacecmd function: cryptokey_update

- testsuite/features/step_definitions/command_steps.rb
During parallel BV pipeline, `mgr-create-bootstrap-repo` is not correctly release after create_bootstrap_repository feature finishes. Add a step to wait until `mgr-create-bootstrap-repo` process is finished.
Related to : https://github.com/SUSE/spacewalk/issues/21827
> Check mgr-create-bootstrap-repo process not running before forcing this command

- java/code/src/com/redhat/rhn/manager/rhnpackage/PackageManager.java
- java/spacewalk-java.changes.mc.Manager-4.3-fix-source-rpm-sql-query
Got syntax error when looking for Source Package to Manage
```
ERROR: argument of JOIN/ON must be type boolean, not type numeric
```
Port of https://github.com/SUSE/spacewalk/pull/21990
> fix sql join syntax for source package search

- python/spacewalk/satellite_tools/rhn_ssl_dbstore.py
- python/spacewalk/satellite_tools/satCerts.py
- python/spacewalk/spacewalk-backend.changes.mcalmer.store-ca-in-db
- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.mcalmer.store-ca-in-db
- spacewalk/setup/bin/spacewalk-setup
- spacewalk/setup/spacewalk-setup.changes.mcalmer.store-ca-in-db
Use mgr-ssl-cert-setup to store a new CA certificate in the database.
Drop this single task from spacewalk-setup.
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/2359
Fixes https://github.com/SUSE/spacewalk/issues/21991
Tracks https://github.com/SUSE/spacewalk/pull/22020 …
> mgr-ssl-cert-setup: Store ca in db

- java/code/src/com/redhat/rhn/common/security/SessionSwap.java
**Revert #7275 and #7277 after the merge of the backport from #7189**
For having a clean backport of #7189 I had to manually rollback some changes on master. 
* #7275
* #7276
* #7275
This PR should revert the changes that are not needed anymore on master because in the meantime uyuni-2023.04 and  master diverged. A revert of #7276 doesn't look needed anymore
No difference.
- No documentation needed: **Revert #7275 and #7277 after the merge of the backport from #7189**
- No tests: **Revert #7275 and #7277 after the merge of the backport from #7189**
Related https://github.com/SUSE/spacewalk/issues/20419
Related https://github.com/SUSE/spacewalk/issues/21856
This is a revert of  a  temp fix. no changelog needed.  …
> Revert 7275 and 7277 after the merge of the backport from 7189

- .github/workflows/acceptance_tests_secondary.yml
- .github/workflows/acceptance_tests_secondary_parallel.yml
Run the acceptance tests on master once a day, so we have a reference to compare to when tests fail on the PR. Also, checking the reference jobs will give us a heads up if something is broken. This would have been really helpful when podman had been updated with a broken version.
No difference.
- No tests
[Fixes](https://github.com/SUSE/spacewalk/issues/21993)
If you need to …
> ci: schedule a reference job once a day

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
The encoding was wrong when providing the CA to the DB tool. Fix that
No difference.
Additional to https://github.com/uyuni-project/uyuni/pull/7267
Tracks 
> fix CA encoding before storing it into DB

- java/code/src/com/suse/manager/gatherer/GathererJsonIO.java
- java/code/src/com/suse/manager/gatherer/test/GathererJsonIOTest.java
- java/code/src/com/suse/manager/gatherer/test/modulelist.json
- java/spacewalk-java.changes.mbussolotto.parse_null
parse virtual-host-gatherer null value. 
Fix for `Virtual host manager web UI` cucumber tests
Before:
> parse virtual-host-gatherer null value

- python/spacewalk/satellite_tools/spacewalk-data-fsck
- python/spacewalk/spacewalk-backend.changes.apatard.spacewalk-data-fsck-srpm
The function is_orphaned_srpm() is used to check if a src.rpm has a corresponding binary package in the database. It is looking for a binary package having the same name as the src.rpm. For instance a package foo*.src.rpm should produce something like foo*.noarch.rpm. Unfortunately, it's a false idea. For instance, python packages are coming from python-foo*.src.rpm and the resulting package is python3-foo*.noarch.rpm.
To solve the issue:
1 - Try to find the src.rpm in rhnPackageSource table. If not found, the
file can be deleted
2 - If found, look for packages having the source_rpm_id matching the
source package.
> python/spacewalk/satellite_tools/spacewalk-data-fsck: Fix srpm check

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.mc.fix-bootstrap-data
Fix bootstrap data and require LTSS channels for SLE15 SP1 up to SP3 to get the new dependency package.
Port of https://github.com/SUSE/spacewalk/pull/22031
> require LTSS channels for SLE 15 SP1, SLE 15 SP2 and SLE 15 SP3

- java/code/src/com/suse/manager/webui/menu/MenuTree.java
- java/spacewalk-java.changes.cbosdo.inactive-systems-fix
Filter inactive systems on `status_type` rather than `system_type`.
No difference.
- No tests: legacy link bound to be dropped sooner or later
Fixes #7067
> Fix the URL showing the inactive systems list (gh#7067)

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
Do not try to deploy the proxy CA for containerized proxy into DB.
This code is executed on the Server and not on the proxy.
No difference.
See https://github.com/SUSE/spacewalk/issues/22046
Additional fix for https://github.com/uyuni-project/uyuni/pull/7267
Tracks https://github.com/SUSE/spacewalk/pull/22048 …
> proxy container config is created on server where CA should not be added to DB

- java/code/src/com/redhat/rhn/frontend/dto/AuditDto.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/packages/PackagesHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/audit/AuditManager.java
- java/code/src/com/redhat/rhn/manager/satellite/UpgradeCommand.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/RpmRepositoryWriter.java
- java/code/src/com/suse/manager/reactor/PGEventStream.java
- java/code/src/com/suse/manager/webui/utils/MinionActionUtils.java
This PR fixes some sonarcloud bugs by using try-with-resources to address simple cases of streams not properly closed.
No difference.
> Use try-with-resources to properly close streams

- testsuite/features/secondary/min_ssh_tunnel.feature
The `milkyway-dummy` package is already installed in the SSH minion at that point in the testsuite, probably due to a missing uninstall in the deploy stage.
Since the package is already installed, this feature cannot find the right package architecture to install and fails.
This PR fixes this failure while the root cause is being looked into.
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/18885
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/22056
4.3 https://github.com/SUSE/spacewalk/pull/22055 …
> Testsuite: SSH tunnel package removal

- susemanager-utils/susemanager-sls/modules/roster/uyuni.py
Fixing single (to double) quotes on log. 
(should have be included in https://github.com/SUSE/spacewalk/pull/22016)
Creating Uyuni connection instances ends up logging db connection password. 
This PR masks it.
No difference.
- No tests: Cosmetic change on logs
Fixes #19859 …
> Mask uyuni roster module password on logs

- java/buildconf/build-props.xml
- java/spacewalk-java.changes.mc.fix-lib-logging
- java/spacewalk-java.spec
Some libs we use, use apache-commons-logging and we want to print such messages also in our logs.
Example:  `org.apache.http` 
No difference.
- No tests: **just additional logging**
Tracks https://github.com/SUSE/spacewalk/pull/22059 …
> fix logging of libraries using apache-commons-logging

- testsuite/features/secondary/srv_cobbler_buildiso.feature
- testsuite/features/secondary/srv_cobbler_distro.feature
- testsuite/features/secondary/srv_cobbler_profile.feature
- testsuite/features/secondary/srv_cobbler_sync.feature
- testsuite/features/step_definitions/cobbler_steps.rb
We restore cobbler settings.yaml from a backup which might be outdated when other tests were skipped before.
So create explicit a backup of this file before we start the test which at the end restore it.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/22067 …
> backup current cobbler settings.yaml before we restore it

- testsuite/features/reposync/srv_sync_products.feature
Fixes 
by splitting up the 2 product selections.
Tests on the 4.3. CI in NUE were successful:
```bash
suma-43-ctl:~/spacewalk/testsuite # cucumber features/reposync/dom.feature
Capybara APP Host: https://suma-43-srv.mgr.suse.de:8888
Host 'suma-43-ctl' is alive with determined hostname suma-43-ctl and FQDN suma-43-ctl.mgr.suse.de
Node: suma-43-ctl, OS Version: 15.4, Family: opensuse-leap
Host 'suma-43-srv.mgr.suse.de' is alive with determined hostname suma-43-srv and FQDN suma-43-srv.mgr.suse.de
Node: suma-43-srv, OS Version: 15-SP4, Family: sles
Host 'suma-43-pxy.mgr.suse.de' is alive with determined hostname suma-43-pxy and FQDN suma-43-pxy.mgr.suse.de
Node: suma-43-pxy, OS Version: 15-SP4, Family: sles
Host 'suma-43-min-kvm.mgr.suse.de' is alive with determined hostname suma-43-min-kvm …
```
> QE: Fix reposync proxy/Retail branch server

- java/code/src/com/redhat/rhn/common/finder/CompositeFinder.java
- java/code/src/com/redhat/rhn/common/finder/FileFinder.java
- java/code/src/com/redhat/rhn/common/finder/Finder.java
- java/code/src/com/redhat/rhn/common/finder/FinderFactory.java
- java/code/src/com/redhat/rhn/common/finder/JarFinder.java
- java/code/src/com/redhat/rhn/common/finder/test/FileFinderTest.java
This PR fixes how `FinderFactory` associates the packages to their physical locations. In fact, the class is currently based on the wrong assumption that a package maps to only one physical location. In reality, a package can be available on the classpath from multiple directories/jars. 
This is currently not an issue as the test and production code is compiled and bundled together by the ant build file, but it will be if we want to properly separate them, split the production code into separate modules and/or we move to any other build tool that separates the main and test context (like Maven/Gradle). In this cases the `Finder`, as it is currently implemented, won't be able to resolve the resources (for example, the hibernate mappings) that are in different jar/context but shares the …
> Added multiple URLs support in FinderFactory

- java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java
- java/spacewalk-java.changes.nadvornik.ubuntu_errata_opt
This PR optimizes memory usage in UbuntuErrataManager. 
Without this change, calling UbuntuErrataManager increased the memory used by freshly started taskomatic process
from 0.5GB to 2.5GB. With this PR it is 0.5GB to 1.5GB
Most of the memory was consumed by the `cveByName` lookup table, which contained hibernate objects for all CVEs mentioned in errata file.
With this PR, the CVEs are created only when they are referenced from `Errata` entry and only if they do not exist yet.
Additional memory is saved by removing unnecessary conversion from stream to list and back.
The speed is about the same as before.
There is a change in the behavior regarding CVE entries, that are not referenced by any package from synced channels.
Before, such entries were written to the DB, now they are skipped. I …
> Optimize memory usage in UbuntuErrataManager

- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataProcessor.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygUpdateAuthTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/test/PaygUpdateAuthTaskTest.java
- java/spacewalk-java.changes.mcalmer.invalidate-payg-credentials-after-instance-is-unavailable
- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/spacewalk-backend.changes.mcalmer.invalidate-payg-credentials-after-instance-is-unavailable
When a connected PAYG client instance is turned off, we should invalidate the credentials to prevent reposync.
Add a hint to reposync so users can fix the issue by turning on the instance again.
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/2378
Fix https://github.com/SUSE/spacewalk/issues/22072
Tracks https://github.com/SUSE/spacewalk/pull/22074
If you …
> invalidate PAYG client credentials after repeated connection failure

- java/code/src/com/redhat/rhn/domain/contentmgmt/modulemd/ModulemdApi.java
- java/spacewalk-java.changes.cbbayburt.mgr-libmod-path
Call mgr-libmod using its absolute path to prevent $PATH hijacking.
Reported as a security hotstpot by SonarCloud:
https://sonarcloud.io/project/security_hotspots?id=uyuni-project_uyuni&hotspots=AYMYhYqW5TQr2KFg-0P4
Fixes https://github.com/SUSE/spacewalk/issues/21416 …
> Call mgr-libmod with its absolute path

- susemanager/src/mgr-salt-ssh
- susemanager/susemanager.changes.meaksh.fix-home-env-in-mgr-salt-ssh-to-avoid-gitfs-issues
This PR fixes `mgr-salt-ssh` script to properly set the `HOME` environment when switching to `salt` user before performing the Salt SSH executions.
Without this change, when having `gitfs` remotes configured in your Salt Master, and after recent changes on the "pygit2" backend, the `mgr-salt-ssh` tool is crashing:
```console
[CRITICAL] Exception caught while initializing gitfs remote 'xxxx@xxxxxxxx': /var/cache/salt/master/gitfs/b74b8bafb5711478f2833218caa61957fd1b21720da203e692de00d955059627: failed to stat '/root/.gitconfig'
File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 466, in __init__
self.new = self.init_remote()
File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1776, in init_remote
self.repo = …
```
> Fix "HOME" environment for "mgr-salt-ssh" to avoid issues with gitfs (bsc#1210994)

- rel-eng/bin/mkchlog
This PR makes `mkchlog` wrap the message at 67 characters like specified [in the wiki](https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs). This works only for the text specified on the command line. When editing the file with the editor, no changes are made to the user input.
An additional option `-n, --no-wrap` is added to allow avoiding the automatic text wrapping if needed.
For example:
```
mkchlog "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultricies ac metus a varius. Phasellus quis nisi ac libero maximus lobortis accumsan."
```
Will produce the following changelog:
```
- Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus 
ultricies ac metus a varius. Phasellus quis nisi ac libero 
maximus lobortis accumsan.
```
while:
```
mkchlog …
```
> Wrap message at 67 characters with mkchlog

- java/code/src/com/redhat/rhn/domain/notification/UserNotificationFactory.java
- java/code/src/com/redhat/rhn/frontend/events/BaseMailAction.java
- java/code/src/com/redhat/rhn/frontend/events/NewUserAction.java
- java/code/src/com/redhat/rhn/frontend/events/TraceBackAction.java
- java/spacewalk-java.changes.mc.Manager-4.3-improve-mailer-init
When mailer setup result in an exception, it may not become very visible in the logs and produce
funny unrelated log messages.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22125 …
> Improve mailer init

- rel-eng/bin/mkchlog
- Use 'getopt' for better arg support
- Add checks to see if run inside Uyuni working dir
- Getting the username and feature name from git is not mandatory and will be ignored if fails
- Exit early if an unexpected error occurs
- No documentation needed: already covered
- No tests: tool not tested …
> Improvements on mkchlog

- testsuite/features/reposync/srv_sync_products.feature
Filter for just "RHEL" produce too many results and the product we look for is not on the first page.
Be more specific to get the expected result on the first page.
No difference.
No need to backport to 4.3 as we look for a different product …
> be more specific in the filter to get less results

- susemanager/bin/mgr-setup
- susemanager/susemanager.changes.mbussolotto.ignore_overlay
Skip swap creation and BTRFS checks when we have overlayfs. Required for setup containers.
No difference.
- (OPTIONAL) …
> Skip swap creation and BTRFS checks when we have overlayfs

- testsuite/features/secondary/allcli_overview_systems_details.feature
Follow up of https://github.com/uyuni-project/uyuni/pull/7339
In order to test the Systems filter in the testsuite, change one step in a feature to use a step that goes through this filter.
No difference.
Fixes #
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/22185 …
> Testsuite: Use the systems filter to find the minion

- testsuite/features/init_clients/allcli_update_activationkeys.feature
- testsuite/features/init_clients/buildhost_bootstrap.feature
- testsuite/features/init_clients/proxy_register_as_minion_with_gui.feature
- testsuite/features/init_clients/proxy_register_as_minion_with_script.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/reposync/srv_enable_sync_products.feature
- testsuite/features/reposync/srv_sync_channels.feature
- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/reposync/srv_wait_for_reposync.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/constants.rb
This will move Uyuni completely to using openSUSE Leap instead of SLES.
- use Leap for the `suse-minion`
- sync Leap 15.4 instead of SLES 15 SP4
```bash
uyuni-srv:/var/log/rhn/reposync # ls -lh
total 7.9M
-rw-rw---- 1 wwwrun www 1.7K Aug  2 11:06 fake_base_channel.log
-rw-rw---- 1 wwwrun www 6.5K Aug  2 08:55 fake-i586-channel.log
-rw-rw---- 1 wwwrun www 3.1K Aug  2 13:21 fake-rpm-suse-channel.log
-rw-rw---- 1 wwwrun www  16K Aug  2 11:32 opensuse_leap15_4-uyuni-client-x86_64.log
-rw-rw---- 1 wwwrun www 121K Aug  2 11:32 opensuse_leap15_4-x86_64-backports-updates.log
-rw-rw---- 1 wwwrun www 4.5M Aug  2 11:32 opensuse_leap15_4-x86_64.log
-rw-rw---- 1 wwwrun www 6.2K Aug  2 11:32 opensuse_leap15_4-x86_64-non-oss.log
-rw-rw---- 1 wwwrun www 6.4K Aug  2 11:32 …
```
> QE: Use Leap instead of SLES in the Uyuni CI

- testsuite/features/secondary/min_salt_formulas_advanced.feature
- testsuite/features/step_definitions/navigation_steps.rb
Adds a step to filter formulas so formulas not on the first page of results are shown.
Filter placeholder:
No difference.
Fixes # https://github.com/SUSE/spacewalk/issues/22180
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/22189 …
> Testsuite: Add step to filter formulas

- web/html/src/components/FormulaForm.tsx
- web/html/src/components/messages.tsx
- web/html/src/core/channels/api/use-mandatory-channels-api.ts
- web/html/src/manager/admin/config/monitoring-admin.tsx
- web/html/src/manager/admin/setup/products/products-scc-dialog.tsx
- web/html/src/manager/admin/setup/products/products.tsx
- web/html/src/manager/groups/formula/group-formula-selection.renderer.tsx
- web/html/src/manager/groups/formula/group-formula.renderer.tsx
- web/html/src/manager/images/image-build.tsx
- web/html/src/manager/images/image-import.tsx
- web/html/src/manager/images/image-profile-edit.tsx
- web/html/src/manager/images/image-profiles.tsx
- web/html/src/manager/images/image-store-edit.tsx
- web/html/src/manager/images/image-stores.tsx
- web/html/src/manager/images/image-view.tsx
- web/html/src/manager/minion/formula/minion-formula-selection.renderer.tsx
- web/html/src/manager/minion/formula/minion-formula.renderer.tsx
- web/html/src/manager/systems/activation-key/activation-key-channels-api.tsx
- web/html/src/manager/systems/delete-system.tsx
- web/html/src/manager/systems/details/mgr-server-info.tsx
- web/html/src/manager/systems/ssm/ssm-subscribe-channels.tsx
- web/html/src/manager/systems/subscribe-channels/subscribe-channels.tsx
- web/spacewalk-web.changes.eth.msgmap
Fix link interpolation in message maps, also rename `msgMap` → `messageMap`.
Bugfix, the following messages are now correctly displayed:
> Fix message map translations

- spacewalk/uyuni-setup-reportdb/bin/uyuni-setup-reportdb
- spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes.mbussolotto.pg_wait
reportdb setup: use pg_isactive to wait for postgres
Checking the socket doesnt work in the container world, using the tool coming with postgres is much cleaner and works in both cases.
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the …
> reportdb setup: use pg_isactive to wait for postgres

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.mbussolotto.reregistering
Remove server keys to allow reregistering to different master
No difference.
- No tests
> Remove server keys to allow reregistering to different master

- java/code/src/com/suse/manager/gatherer/GathererJsonIO.java
- java/code/src/com/suse/manager/gatherer/test/GathererJsonIOTest.java
- java/code/src/com/suse/manager/gatherer/test/modulelist.json
- java/spacewalk-java.changes.mbussolotto.parse_null
parse virtual-host-gatherer null value 
No difference. …
> parse virtual-host-gatherer null value (#7282)

- testsuite/features/build_validation/retail/sle12sp5_buildhost_build_kiwi_image.feature
- testsuite/features/secondary/buildhost_docker_auth_registry.feature
- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/step_definitions/salt_steps.rb
Related card: https://github.com/SUSE/spacewalk/issues/22078
Improve how we handle the validation of each image building, including additional checks to don't perform another image building unless there are no pending Salt jobs in the build host.
I also increase the timeout for Salt jobs related to building images to 6 minutes and make the check verbose so we know what was running if the timeout raise.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22094 …
> QE: Wait for pending Salt Jobs after building an image before moving to next build action

- testsuite/features/support/env.rb
Add a timestamp in the HTML report when a scenario fails
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22193
> QE: Add a timestamp in the HTML report when a scenario fails

- testsuite/features/step_definitions/common_steps.rb
Add more log to debug IPv6 flaky test
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22188
> QE: Add more log to debug IPv6 flaky test

- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
PXEBoot: If we raise a previous timeout, we are able to recover and continue with next scenario
(In the second screenshot we fail because we did not wait for the onboarding)
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22181 …
> PXEBoot: If we raise a previous timeout, we are able to recover and continue with next scenario

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/support/lavanda.rb
- Increase some timeouts related to Salt Jobs
- Refresh page while waiting for KVM pages to finish loading spinning
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22138
> QE: Increase some timeouts related to Salt Jobs and refresh page for KVM loading page

- testsuite/features/build_validation/retail/proxy_branch_network.feature
- testsuite/features/init_clients/proxy_branch_network.feature
- testsuite/features/secondary/allcli_overview_systems_details.feature
- testsuite/features/secondary/min_salt_mgrcompat_state.feature
- testsuite/features/secondary/min_salt_minion_details.feature
Refactor how we wait for Hardware refresh action by specifying the salt job to wait.
This new step definition can start to be used for other actions where we want to specifically wait for a concrete Salt Job. 
Like building images, where we should wait for mods:
```
- images.profileupdate
- images.docker
```
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22095 …
> QE: Refactor how we wait for Hardware refresh action by specifying the salt job to wait

- testsuite/features/support/commonlib.rb
- testsuite/features/support/constants.rb
Do not kill the reposync of openSUSE Leap 15.4 for Uyuni. We recently switched the Uyuni CI from SLES to openSUSE Leap, so we should not kill the reposync of it.
No difference.
> QE: Fix Uyuni reposync for openSUSE Leap 15.4

- testsuite/features/step_definitions/api_common.rb
- testsuite/features/step_definitions/file_management_steps.rb
Because we are now creating a specific channel for monitoring, remove changing monitoring_server for sle15sp4_minion so the API call when creating the activation key will correctly look for monitoring custom channel
> Differency monitoring from sleminion

- testsuite/features/step_definitions/navigation_steps.rb
Wait until the System Overview page is loaded before trying to look for the system.
During BV we had situations where we are refreshing the page before Overview System page was loading. This wrong refresh was keeping us on the page where we were clicking on the left menu ( Bootstrap page or Main Overview)
Related to this issues : 
- https://github.com/SUSE/spacewalk/issues/22174
- https://github.com/SUSE/spacewalk/issues/22164 / Issue 2
> Check Overview Page is correctly loaded before looking for system

- testsuite/features/step_definitions/navigation_steps.rb
During the BV testing, on some tests, the fields in the login page are empty but the testsuite is expecting to be log in. 
After investigation, it seems we fill the field too early. With this new step, we make sure the username is correctly loaded.
Related to : https://github.com/SUSE/spacewalk/issues/22176
> Check login page is correctly loaded

- testsuite/features/step_definitions/common_steps.rb
Add waiting steps between click during the onboarding waiting around event tab.
During the BV, some of the refresh methods were starting before the page loaded ( same than https://github.com/uyuni-project/uyuni/pull/7371 )
Related to : https://github.com/SUSE/spacewalk/issues/22175
> Add waiting text checks between event click link

- testsuite/features/build_validation/retail/sle12sp5_terminal_deploy.feature
- testsuite/features/build_validation/retail/sle15sp4_terminal_deploy.feature
- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
Reverts uyuni-project/uyuni#7339
The `I navigate to` step is necessary for pxe boot and terminals as they cannot be accessed by using the `I am on` step.
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/22237
> Revert "Testsuite: Replace steps that use systems filter to navigate to minions"

- python/spacewalk/satellite_tools/spacewalk-debug
- python/spacewalk/spacewalk-backend.changes.agraul.supportutils-add-cobbler-collections
Add cobbler collections to supportconfig.
We have been requesting the contents of /var/lib/cobbler/collections in many of the cobbler bugs in the last year. That's one round-trip we can save by collecting these JSON files upfront with the supportconfig plugin.
No difference.
No tests: Testing all the contents of the supportconfig is a lot of work for little gain. …
> Add cobbler collections to supportconfig

- java/code/src/com/redhat/rhn/domain/server/Server_legacyUser.hbm.xml
- java/spacewalk-java.changes.vzhestkov.extend-listErrataNamesForServers-for-salt-bundle
Extends `listErrataNamesForServers` to consider `venv-salt-minion` as a salt upgrade on the client to prevent tracebacks on upgrading the list of packages if the salt bundle is included in the list.
No difference.
- No tests: Not sure if the test for it is really possible.
Fixes https://github.com/SUSE/spacewalk/issues/22017
If you …
> Extend list errata names for servers for salt bundle

- testsuite/features/step_definitions/navigation_steps.rb
The text on the System Overview page changes after 4.3 and is consequently different on Uyuni and Head
`raise 'Overview System page didn\'t load' unless has_content?('System Overview')` consequently fails on those branches
This PR adapts the System Overview test so it also takes into account this change
No difference.
Fixes #
Tracks # 
4.2 https://github.com/SUSE/spacewalk/pull/22244
4.3 https://github.com/SUSE/spacewalk/pull/22244 …
> Testsuite: Add System Overview possibility for Uyuni/Head

- testsuite/Gemfile
mini_mime > 1.1.2, requires ruby >= 2.6, but we have an older version of ruby.
No difference.
- No tests
- 
N/A
> CI: set mini_mime gem to specific version

- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/reposync/srv_wait_for_reposync.feature
- testsuite/features/step_definitions/command_steps.rb
Missed replacement of `server.run` and typo correction.
No difference.
Fixes #
Tracks # None - only Uyuni
> Testsuite: Correct omitted run method

- testsuite/features/secondary/minkvm_guests.feature
This PR removes a test that was not really justified.
We never selected "test-net0" after creating the VM, there's no reason it appears as selected.
Fixes SUSE/spacewalk#22211
Ports:
* 4.2: SUSE/spacewalk#22253
* 4.3: SUSE/spacewalk#22252
> We never selected test-net0, there's no reason it appears selected

- testsuite/features/secondary/buildhost_docker_build_image.feature
Restore word that was unintentionally deleted in https://github.com/uyuni-project/uyuni/pull/7375
No difference.
Fixes #
Tracks # 
4.3 https://github.com/SUSE/spacewalk/pull/22267
> Testsuite: Add missing 'empty'

- spacewalk/setup/spacewalk-setup.changes.oholecek.tomcat-install-check
- spacewalk/setup/spacewalk-setup.spec
Port of https://github.com/SUSE/spacewalk/pull/22229
Under some circumstances like updating older unconfigured SUMA system, tomcat.xml was not configured properly as source tomcat.xml was not configured. Instead of relying if we are doing rpm update or new install, check status or rhn.conf file.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/21323
Tracks https://github.com/SUSE/spacewalk/pull/22229
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-p …
> Check for configured rhn.conf instead of rpm run status

- testsuite/features/finishing/srv_smdba.feature
- testsuite/features/step_definitions/smdba_steps.rb
Since the switch from SLES to openSUSE Leap 15.4, we sync much more packages, which results in a bigger database. Moving from the default timeout of 250 s to 600 s could help solve failing in the finishing stage of our test suite. Furthermore we enable error checking to fail earlier.
See https://github.com/SUSE/spacewalk/issues/22277
No difference. …
> QE: Create step for database backup

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
Fix use_salt_bundle variable doesnt exist anymore
No difference.
Ports:
- Manager-4.3
- Manager-4.2
> QE: Fix use_salt_bundle variable doesnt exist anymore

- testsuite/features/support/constants.rb
CI: Fix fake base channel. When running inside github actions with podman, we are not syncing any product, to avoid external dependencies. Thus, the base channel for the fake channel, can't be Leap or SLE, but "Fake base channel".
No difference.
- No tests
N/A …
> CI: Fix Fake base channel

- java/code/src/com/redhat/rhn/taskomatic/task/gatherer/VirtualHostManagerProcessor.java
- java/code/src/com/suse/manager/gatherer/HostJson.java
When data from virtual host gatherer have an old format, maybe not all fields could be parsed and stay empty/NULL.
This can cause NPE when working with the data.
Provide default values in case we do not have the data
No difference.
Tracks  …
> prevent NPE when cpu values could not fetched or parsed correctly

- testsuite/features/build_validation/add_activation_keys/add_activation_key.template
- testsuite/features/build_validation/create_bootstrap_repositories/create_bootstrap_repository.template
Currently all feature titles for creating the bootstrap repository are identical, making the test suite report hard to read and making it impossible to run them manually. This PR adds the minion name to the feature title.
Ports:
* 4.3: SUSE/spacewalk#22304
* 4.2: SUSE/spacewalk#22305
> Better feature and scenario titles for BV

- .github/workflows/external_pr_labeler.yml
Adds a GH Action named "External PR labeler" that adds `external-contrib` label to any newly opened PR by a user who is not a member of the uyuni-project org.
This action uses a personal access token with `org:read` permission. The token must be stored as a repository secret with the name `READ_ORG_TOKEN`. …
> Add external PR labeler action

- testsuite/features/secondary/allcli_overview_systems_details.feature
https://github.com/uyuni-project/uyuni/pull/7380 with commit c618cec137831c719a07620c4938611f38922a8d introduced the "Wait until there is no Salt job calling the module hardware.properties on ssh_minion" . But this is failing for ssh_minion. Reverting this test.
No difference.
- No tests
N/A …
> QE: Partial revert of how we wait for hw refresh

- testsuite/documentation/cucumber-steps.md
- testsuite/documentation/pitfalls.md
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/constants.rb
This fixes some of the 4.3 CI issues found by @mcalmer which are leftovers from the Twopence lazy init backport. See https://github.com/SUSE/spacewalk/pull/22269
Twopence uses the following init, so the hostname rename and SSH reboot tests could be a bit simplified because we know what the server target is already and do not have to use its IP address:
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22313 …
> QE: Fix server restart via SSH

- java/code/src/com/redhat/rhn/domain/channel/Channel.hbm.xml
- java/code/src/com/redhat/rhn/domain/channel/test/ChannelFactoryTest.java
- java/spacewalk-java.changes.nadvornik.channel_access
This should improve the slow query on channel accessibility by org.
Main changes:
- COUNT replaced with EXISTS
- do not use views
- rhnOrgChannelTreeView uses union of separate SELECTs for parent and child channels. In this case, single SELECT is ok.
- handling of public channel family in rhnOrgChannelFamilyPermissions might be inefficient, not sure
Added unit test to make sure the query behaves the same as before.
No difference.
Might fix https://bugzilla.suse.com/show_bug.cgi?id=1211874
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni …
> Optimize org channel accessibility query (bsc#1211874)

- testsuite/run_sets/secondary.yml
Disables the rename server hostname feature until a proper fix can be found for the recent twopence refactor
- 4.3 https://github.com/SUSE/spacewalk/pull/22322
> QE: Disable rename server feature as a temp fix for twopence refactor

- .github/workflows/external_pr_labeler.yml
Label community PRs as 'community' instead of 'external-contrib' with "External PR labeler" GH action.
> Label community PRs as 'community' instead of 'external-contrib'

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
Adds an extra wait to account for the time between the Loading text disappearing and the options for dashboards to appear. "General" is a section that always appears when loading is done.
- 4.2 https://github.com/SUSE/spacewalk/pull/22329
- 4.3 https://github.com/SUSE/spacewalk/pull/22328 …
> QE: Add extra wait for Grafana to load in BV

- testsuite/features/step_definitions/navigation_steps.rb
Systems is always visible. Looking for Systems text and System overview will not wait correctly for the System Overview page to be loaded.
@elariekerboull , I would like to remove the Systems text check. For me this text is always visible on the Left Menu.
> Remove has_content? Systems when looking for new system

- java/code/src/com/redhat/rhn/domain/org/test/CustomDataKeyTest.java
- java/code/src/com/redhat/rhn/domain/server/MinionServer.java
- java/code/src/com/redhat/rhn/domain/server/test/CustomDataValueTest.java
- java/code/src/com/redhat/rhn/domain/server/test/MinionServerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
- java/code/src/com/suse/manager/saltboot/PXEEventMessageAction.java
- java/code/src/com/suse/manager/saltboot/SaltbootUtils.java
- java/code/src/com/suse/manager/saltboot/test/PXEEventTest.java
- java/spacewalk-java.changes.oholecek.saltboot_pillars
- susemanager-utils/susemanager-sls/modules/pillar/suma_minion.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.oholecek.recurse_formula_pillar
This PR add java side handling of saltboot pillars and custom info to be able to force disk repartitioning and/or image redeployment.
No difference.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pull/2375)
Fixes https://github.com/SUSE/spacewalk/issues/21884
Tracks https://github.com/SUSE/spacewalk/pull/22057 …
> Add support for saltboot pillar force_redeploy and force_repartition

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Action_queries.xml
- java/code/src/com/redhat/rhn/common/db/datasource/xml/System_queries.xml
- java/code/src/com/redhat/rhn/manager/action/ActionManager.java
- java/code/src/com/suse/manager/reactor/SaltReactor.java
- java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/manager/xmlrpc/serializer/test/SystemEventDetailsDtoSerializerTest.java
- java/code/src/com/suse/manager/xmlrpc/serializer/test/SystemEventDtoSerializerTest.java
- java/spacewalk-java.changes.parlt.set-package-refresh-scheduler
- spacecmd/tests/test_system.py
- testsuite/features/init_clients/proxy_branch_network.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
This PR was originally part of an L3 but it got closed due to noresponse. In the end I forgot to merge it. I think this change is a valuable addition though, so I think we should still merge it.
Change default/fallback scheduler from `(none)` to `(system)`
Set the scheduler on `package list refresh` action if possible
No difference.
- No tests: already covered (existing tests adapted)
Tracks https://github.com/SUSE/spacewalk/issues/21290 …
> Set package refresh scheduler if possible

- testsuite/features/secondary/min_project_lotus.feature
We changed the step to follow links, so I'm updating the cleanup test for the custom repos used on Project Lotus tests
Already present on 4.3
> QE: Fix Repo cleanup for Proejct Lotus tests

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/redhat/rhn/domain/channel/ContentSource.hbm.xml
- java/code/src/com/redhat/rhn/domain/cloudpayg/PaygSshDataFactory.java
- java/code/src/com/redhat/rhn/domain/credentials/Credentials.java
- java/code/src/com/redhat/rhn/domain/credentials/CredentialsFactory.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerPaygTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataExtractor.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataProcessor.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/beans/PaygInstanceInfo.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/detect_os.sh
- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/payg_extract_repo_data.py
- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/rhui7_extract_repo_data.py
- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/rhui_extract_repo_data.py
- java/code/src/com/redhat/rhn/taskomatic/task/payg/test/PaygAuthDataProcessorTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/test/PaygUpdateAuthTaskTest.java
- java/code/src/com/suse/manager/admin/PaygAdminManager.java
- java/spacewalk-java.changes.mcalmer.rhui-via-payg
- java/tito.props
- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/satellite_tools/satCerts.py
- python/spacewalk/spacewalk-backend.changes.mcalmer.rhui-via-payg
- schema/spacewalk/common/data/suseCredentialsType.sql
- schema/spacewalk/susemanager-schema.changes.mcalmer.rhui-via-payg
- schema/spacewalk/upgrade/susemanager-schema-4.4.6-to-susemanager-schema-4.4.7/001-add-rhui-credential-type.sql
- susemanager-utils/susemanager-sls/salt/bootstrap/remove_traditional_stack.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.rhui-via-payg
Support RHUI configuration via Pay-as-you-Go client connection in the cloud
Replace https://github.com/uyuni-project/uyuni/pull/7050
Port of https://github.com/SUSE/spacewalk/pull/21590
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/2274
> Suma payg rhui via payg client connection

- python/test/unit/spacewalk/satellite_tools/test_reposync.py
PAYG or RHUI code introduced regressions in reposync unit tests
No difference.
Port https://github.com/SUSE/spacewalk/pull/22353
> fix python reposync unit tests

- rel-eng/bin/mkchlog
Out of the box macOS ships with BSD getopt which doesn't support long args. If we detect that's the case, warn the user and exit early.
No difference.
- No tests: rel-eng tooling
> Add BSD getopt error for macOS

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/redhat/rhn/frontend/action/configuration/files/FileDetailsAction.java
- java/code/src/com/redhat/rhn/frontend/action/configuration/files/FileDownloadAction.java
- java/code/src/com/redhat/rhn/frontend/action/renderers/TasksRenderer.java
- java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemDetailsEditAction.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
The property `ConfigDefaults.isDocAvaialable()` in fact was checking if the installation was SUSE Manager or Uyuni.
As we provide documentation in both we can safely get rid of this check and remove all `*.nodoc` string resources.
Kudos for @parlt91 for the hint.
Follow up of #7348
Before:
After:
- No documentation needed: provides helpful information in the UI.
- No tests: minor change
Fixes #7348 …
> Remove ConfigDefaults.isDocAvailable

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/twopence_env.rb
- testsuite/features/support/twopence_init.rb
- testsuite/run_sets/secondary.yml
Add a refresh option to invalidate cache in Twopence/Lavanda instances
No difference.
Ports:
- Manager-4.3
> QE: Add a refresh option to invalidate cache in Twopence/Lavanda instances

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
Product Refresh is not working as we check for localhost connection in the wrong table
Port of https://github.com/SUSE/spacewalk/pull/22365
> check for localhost in correct table

- java/code/src/com/redhat/rhn/domain/channel/ChannelFamily.java
- java/code/src/com/redhat/rhn/frontend/action/tasko/SatSchedulesAction.java
- java/code/src/com/redhat/rhn/frontend/action/tasko/ScheduleDetailAction.java
- java/code/src/com/redhat/rhn/taskomatic/TaskoFactory.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygComputeDimensionsTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/payg_extract_repo_data.py
- java/code/src/com/suse/cloud/CloudPaygManager.java
- java/code/src/com/suse/cloud/test/CloudPaygManagerTest.java
- java/spacewalk-java.changes.mc.Manager-4.3-suma-payg-billing-adapter-checks
- python/billingdataservice/billing-data-service.changes.mc.Manager-4.3-billing-adapter-checks-2
- python/billingdataservice/billing-data-service.spec
- python/billingdataservice/payg-service-override.conf
- spacewalk/admin/spacewalk-startup-helper
- susemanager-utils/supportutils-plugin-susemanager/susemanager
Require csp-billing-adapter-service package and enhance the systemd overwrite files to require
also csp-billing-adapater.service running. Same as for the billing-data-service
Also add some bugfixes
Port of https://github.com/SUSE/spacewalk/pull/22358
> Billing adapter checks 2

- java/code/src/com/redhat/rhn/taskomatic/TaskoFactory.java
- java/code/src/com/redhat/rhn/taskomatic/TaskoJob.java
- java/code/src/com/redhat/rhn/taskomatic/TaskoQuartzHelper.java
- java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcHandler.java
- java/code/src/com/redhat/rhn/taskomatic/task/TaskHelper.java
- java/spacewalk-java.changes.mackdk.taskomatic-do-not-hide-scheduling-errors
In taskomatic we hide and ignore very often SchedulerExceptions. This lead into problems as some jobs might not be executed. Additionally `null` is returned in XMLRPC functions which is forbidden and cause exceptions.
This PR try to avoid returning `null` and throw SchedulerExceptions instead. It also improve logging of errors.
No difference.
Fixes # …
> throw and log SchedulerExceptions in taskomatic

- testsuite/.rubocop_todo.yml
- testsuite/features/step_definitions/cobbler_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/twopence_init.rb
We had some corner case after the refactor of the twopence node init that are addressed in this PR.
No difference.
Adapted port of https://github.com/SUSE/spacewalk/pull/22384 and https://github.com/SUSE/spacewalk/pull/22385
> Improve the Twopence lazy initzialition refactor

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/spacewalk-java.changes.cbosdo.local-reportdb
- spacewalk/setup/lib/Spacewalk/Setup.pm
- spacewalk/setup/spacewalk-setup.changes.cbosdo.local-reportdb
When the report database is installed on the server we don't need and can't use SSL to connect to it using localhost hostname. This comes in handy to avoid hairpin requests in the container setup.
No difference.
- No tests: container CI will soon use it …
> Don't force SSL verify-full mode for localhost report DB

- java/code/src/com/suse/cloud/CloudPaygManager.java
- java/code/src/com/suse/cloud/CspBillingAdapterStatus.java
- java/code/src/com/suse/cloud/test/CloudPaygManagerTest.java
- java/code/src/com/suse/cloud/test/data/csp-config.nocreds.json
- java/code/src/com/suse/cloud/test/data/csp-config.nonet.json
- java/code/src/com/suse/cloud/test/data/csp-config.ok.json
- java/spacewalk-java.changes.mc.Manager-4.3-check-csp-adapter-operating-state
Check status of the billing adapter for the compliance check
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22389
> Check csp adapter operating state

- testsuite/features/secondary/srv_rename_hostname.feature
- testsuite/features/step_definitions/command_steps.rb
This PR fixes the test of hostname rename feature, where the cleanup was not working, and was making all subsequent feature tests fail.
It also adds idempotency, and a smoke test on the renamed server.
Fixes: https://github.com/SUSE/spacewalk/issues/22323
Ports:
* 4.3: cannot port as the "refresh" parameter of get_target is not implemented yet:
```
def get_target(host)
node = $node_by_host[host]
node = twopence_init(host) if node.nil?
node
end
```
To be clarified with Oscar.
> Fix hostname rename feature

- testsuite/features/support/constants.rb
SUSE Liberty Linux does not work/is not supported on Uyuni as of now.
No difference.
Before:
After:
No ports. This affects only Uyuni!
- Fixes https://github.com/SUSE/spacewalk/issues/20248 …
> QE: Remove SLL8 from Uyuni

- testsuite/features/reposync/srv_wait_for_reposync.feature
- testsuite/features/support/commonlib.rb
Kills the openSUSE Leap 15.4 reposyncing to see if we are able to bootstrap the openSUSE minion in the Uyuni CI.
See https://github.com/SUSE/spacewalk/issues/22336
No difference.
Before:
After: …
> QE: Kill the openSUSE Leap repo sync

- testsuite/features/support/pretty_formatter.rb
- testsuite/features/support/twopence_env.rb
- testsuite/features/support/twopence_init.rb
While debugging some stuff, I noticed that we were not handling some imported dependencies correctly.
In this PR I changed it to be more precise when requiring them.
No difference.
Ports:
> QE: Improving how we handle Ruby dependencies

- susemanager-utils/testing/automation/VERSION.SUSE-Manager
- susemanager-utils/testing/automation/schema-migration-test-pgsql.sh
- susemanager-utils/testing/docker/scripts/schema_migration_test_pgsql.sh
Additional changes for https://github.com/uyuni-project/uyuni/pull/7473
No difference.
> fix schema migration test

- testsuite/features/reposync/reference_srv_check_reposync.feature
- testsuite/features/reposync/reference_srv_sync_products_extra.feature
See https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-master-infra-reference-NUE/754
There is no channel named `sle-product-sles15-sp4-pool-x86_64` available via `spacewalk-common-channels`. Furthermore, we do not sync SLES in Uyuni anymore.
```bash
uyuni-refmaster-srv:~ # spacewalk-common-channels -l | grep sles15
sles15-sap-sp2-devel-uyuni-client: x86_64, s390x, aarch64, ppc64le
sles15-sap-sp2-uyuni-client: x86_64, s390x, aarch64, ppc64le
sles15-sap-sp3-devel-uyuni-client: x86_64, s390x, aarch64, ppc64le
sles15-sap-sp3-uyuni-client: x86_64, s390x, aarch64, ppc64le
sles15-sap-sp4-devel-uyuni-client: x86_64, s390x, aarch64, ppc64le
sles15-sap-sp4-uyuni-client: x86_64, s390x, aarch64, ppc64le
sles15-sap-sp5-devel-uyuni-client: x86_64, s390x, aarch64, ppc64le
sles15-sap-sp5-uyuni-client: …
```
> QE: Fix wrong repo in reference products sync

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/lavanda.rb
- testsuite/features/support/twopence_init.rb
More fixes in twopence_init after the rebase on master.
No difference.
Before:
After: …
> Fix twopence_init after rebase

- susemanager/bin/mgr-setup
- susemanager/susemanager.changes.mbussolotto.timezone
`TZ` (if set) is used as timezone by the system, but not everywhere (e.g. UI uses ` /etc/localtime`a and completely ignore `TZ`). With this PR  we ensure during setup that the two values represent the same timezone.
No difference.
- API documentation added: please review the Wiki page [Writing Documentation for the …
> keep aligned TZ and /etc/localtime

- testsuite/features/init_clients/proxy_branch_network.feature
- testsuite/features/secondary/allcli_system_group.feature
- testsuite/features/secondary/min_salt_formulas.feature
- testsuite/features/secondary/srv_user_configuration_salt_states.feature
- testsuite/features/step_definitions/salt_steps.rb
testsuite: do not install or remove formula if in container
No difference. …
> testsuite: do not install or remove formula if in container

- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/payg_extract_repo_data.py
- java/spacewalk-java.changes.mc.Manager-4.3-fix-instance-identifier-header-payg
Doing product refresh against RMT Cloud infrastructure for PAYG images fail as we send the wrong
Header data.
We need to send the data from the base product and not the data from /etc/os-release
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22441 …
> fix X-Instance-Identifier header send when doing a product refresh at Cloud RMT Server

- testsuite/documentation/cucumber-steps.md
- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/min_change_software_channel.feature
- testsuite/features/secondary/min_project_lotus.feature
- testsuite/features/secondary/srv_change_task_schedule.feature
- testsuite/features/secondary/srv_maintenance_windows.feature
- testsuite/features/secondary/srv_users.feature
- testsuite/features/step_definitions/navigation_steps.rb
```
Then radio button "foobar" is checked
```
->
```
Then radio button "foobar" should be checked
```
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22456
> Follow our conventions for step names

- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_change_software_channel.feature
- testsuite/features/secondary/minssh_bootstrap_api.feature
This PR is a follow-up of #7495
I did NOT change the waits for "Loading..." in the software channels page, as it might work differently from the activation keys page.
Piggyback: fix some copyright dates in those software channel features.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22455
> Fix activation keys 2

- web/html/src/manager/salt/formula-catalog/org-formula-catalog.tsx
- web/spacewalk-web.changes.eth.translate-salt
Currently the Salt formula catalog alert is not translatable, this PR fixes this issue.
No difference.
- No tests: nothing to test
Fixes https://github.com/uyuni-project/uyuni/issues/3383
> Add missing translation wrappers for Salt formula catalog

- proxy/installer/configure-proxy.sh
- proxy/installer/configure-proxy.sh.sgml
- proxy/installer/spacewalk-proxy-installer.changes.mc.drop-mgr_cfg-from-proxy
- proxy/installer/spacewalk-proxy-installer.spec
- proxy/proxy/spacewalk-proxy.changes.mc.drop-mgr_cfg-from-proxy
- proxy/proxy/spacewalk-proxy.spec
Drop mgr-cfg dependency
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/2427
Fixes https://github.com/SUSE/spacewalk/issues/18882
> remove dependency to mgr-cfg and drop other deps

- java/code/src/com/redhat/rhn/manager/content/MgrSyncUtils.java
- java/code/src/log4j2.xml
We have the option to use a mirror and mount repositories local to Uyuni Server.
But it is not easy to find out where Uyuni search for a repository on which local path.
This PR add now log messages (info level) which print the possible paths to the logs when this class
is turned into logging also info messages. 
They also show alternative paths which are possible for some repositories.
No difference.
Log Example:
```
2023-09-04 17:11:26,156 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-8] INFO  com.redhat.rhn.manager.content.MgrSyncUtils - SCC mirrorpath: /mirror/SUSE/Products/SLE-Module-Server-Applications/15-SP4/x86_64/product
2023-09-04 17:11:26,160 [ajp-nio-0:0:0:0:0:0:0:1-8009-exec-8] INFO  com.redhat.rhn.manager.content.MgrSyncUtils - SMT mirrorpath for 'ubuntu-2204-amd64-main': …
```
> Log mirror path

- testsuite/features/core/srv_create_activationkey.feature
- testsuite/features/init_clients/allcli_update_activationkeys.feature
- testsuite/features/init_clients/buildhost_bootstrap.feature
This will use a dedicated activation key for the build host.
No difference.
- Manager 4.3: 
> QE: Create buildhost activation key

- java/code/src/com/redhat/rhn/taskomatic/task/RecurringActionJob.java
- java/spacewalk-java.changes.parlt.fix-recurring-state-ordering
Using a Set instead of a list caused the order of the states to be incorrect.
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/22465
> Fix recurring state execution not using correct order

- .github/workflows/stale.yml
Add "Stale PRs" GH action to label and close inactive community PRs.
The action runs daily at 01:00 UTC to label any PR that is inactive for 60 days with `Stale` label.
After further 10 days, the action closes the PR and deletes its branch. The author has the chance to update the PR or simply remove the `Stale` label to unmark the PR for closing.
If needed, we can extend the action to issues as well.
Check out https://github.com/actions/stale for the full range of options this action supports.
If you …
> Add 'Stale PRs' GH action to label and close inactive community PRs

- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_ansible_control_node.feature
- testsuite/features/secondary/min_bootstrap_api.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/features/secondary/min_change_software_channel.feature
- testsuite/features/secondary/min_custom_pkg_download_endpoint.feature
- testsuite/features/secondary/min_salt_openscap_audit.feature
- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/minssh_ansible_control_node.feature
- testsuite/features/secondary/minssh_bootstrap_api.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/secondary/srv_dist_channel_mapping.feature
- testsuite/features/secondary/srv_maintenance_windows.feature
- testsuite/features/secondary/srv_manage_activationkey.feature
- testsuite/features/secondary/srv_task_status_engine.feature
- testsuite/features/step_definitions/command_steps.rb
This includes some more adjustments for using openSUSE Leap 15.4 in our Uyuni CI. KVM + Cobbler tests will still fail because of the missing TFTP package I was not able to find (see e.g. https://suse.slack.com/archives/C02CKHR76Q2/p1694189245268889).
I ran all tests manually on the Uyuni CI controller. Some of the tests look a little bit different in Uyuni than in SUMA because of e.g. no child channels were selected by default due to the missing reposync.
Furthermore, I also fixed an issue in the finishing stage where we could not extract the log files due to taking special care of the nested VM. This works now again:
```bash
uyuni-master-ctl:~/spacewalk/testsuite # cucumber features/dom.feature
Capybara APP Host: https://uyuni-master-srv.mgr.suse.de:8888
Initializing a twopence node for …
```
> QE: Update test suite for using Leap 15.4

- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/allcli_software_channels_dependencies.feature
- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_salt_openscap_audit.feature
This PR adjusts more things in the test suite code for using Leap 15.4. in Uyuni.
No difference.
- Manager 4.3:
> QE: more test suite adjustment for Leap 15.4

- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
This is a patch for the `obs-to-maven` and `ivy` configurations in order to resolve libraries from Leap 15.5 repositories, for building Uyuni locally or for running tests in CI.
Downstream issue: https://github.com/SUSE/spacewalk/issues/21561
> Update dependencies for Leap 15.5

- testsuite/features/support/constants.rb
Fix parent channel for hexagon pipeline.
No difference. …
> Fix update activation key

- testsuite/features/support/twopence_init.rb
> fixup! Adjust testsuite for containerized server

- testsuite/features/reposync/srv_sync_products.feature
I did the mistake of using opensuse_15.5 instead of opensuse_15_5 ( . instead of _ ).
This PR fixes it.
No difference.
- No tests
> Fix leap_15_5 common_channel in testsuite

- utils/spacewalk-common-channels.ini
Fix common stable and devel channels for proxy and server testing, in the context of leap 15.5 migration.
No difference.
- No tests
related to epic https://github.com/SUSE/spacewalk/issues/21515
> Fix common stable and devel channels for proxy and server testing

- containers/proxy-httpd-image/Dockerfile
- containers/proxy-httpd-image/proxy-httpd-image.changes.raul.change-leap-version-in-containers
- containers/proxy-salt-broker-image/Dockerfile
- containers/proxy-salt-broker-image/proxy-salt-broker-image.changes.raul.change-leap-version-in-containers
- containers/proxy-squid-image/Dockerfile
- containers/proxy-squid-image/proxy-squid-image.changes.raul.change-leap-version-in-containers
- containers/proxy-ssh-image/Dockerfile
- containers/proxy-ssh-image/proxy-ssh-image.changes.raul.change-leap-version-in-containers
- containers/proxy-tftpd-image/Dockerfile
- containers/proxy-tftpd-image/proxy-tftpd-image.changes.raul.change-leap-version-in-containers
**Adapt containers to openSUSE Leap 15.5**
No difference.
- No documentation needed: **To be mentioned in the release notes**
Tracks https://github.com/SUSE/spacewalk/issues/22510
> Adapt containers to openSUSE Leap 15.5

- utils/spacewalk-utils.changes.jmassaguerpla@suse.com.fix_common_stable_and_devel_channels
Update spacewake-utils.changes with changes from https://github.com/uyuni-project/uyuni/pull/7540
No difference.
- No tests
related to https://github.com/SUSE/spacewalk/issues/21515
> Update spacewalk-utils.changes with leap 15.5

- java/spacewalk-java.changes.parlt.ignore-mandatory-channel-results
Add missing changelog entry for bsc#1204270
No difference.
- No tests: 
Fixes #
Tracks  #
> Add missing changelog for bsc#1204270

- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/allcli_software_channels_dependencies.feature
- testsuite/features/secondary/min_activationkey.feature
- testsuite/features/secondary/min_bootstrap_api.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/features/secondary/min_change_software_channel.feature
- testsuite/features/secondary/min_custom_pkg_download_endpoint.feature
- testsuite/features/secondary/minssh_bootstrap_api.feature
- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/secondary/srv_dist_channel_mapping.feature
- testsuite/features/secondary/srv_manage_activationkey.feature
Adapt secondary tests to 15.5
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/21562
> Migrate testsuite to 15.5

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/secondary/srv_dist_channel_mapping.feature
Fix some tests that I forgot in a previous PR.
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/21562
> Fix tests to check for 15.5 and not 15.4

- java/code/src/com/redhat/rhn/domain/task/TaskFactory.java
- java/code/src/com/redhat/rhn/taskomatic/task/systems/SystemsOverviewUpdateWorker.java
- java/spacewalk-java.changes.cbosdo.system-update-fix
Fix for https://github.com/uyuni-project/uyuni/issues/7313 where only the system update tasks for systems of organization 1 where cleaned up.
No difference.
- No tests: requires multiple orgs
Fixes https://github.com/uyuni-project/uyuni/issues/7313 …
> Remove all tasks for the processed system in the system update

- java/code/src/com/redhat/rhn/domain/notification/NotificationMessage.java
- java/code/src/com/redhat/rhn/domain/notification/types/NotificationType.java
- java/code/src/com/redhat/rhn/domain/notification/types/UpdateAvailable.java
- java/code/src/com/redhat/rhn/domain/notification/types/UpdateAvailableNotification.java
- java/code/src/com/redhat/rhn/domain/notification/types/test/UpdateAvailableTest.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/taskomatic/task/DailySummary.java
- java/conf/rhn_java.conf
- java/spacewalk-java.changes.mseidl.update-notification
- web/html/src/manager/notifications/notification-messages.tsx
- web/spacewalk-web.changes.mseidl.update-notification
This patch contains code to check in the background for updates or critical security patches available from the official Uyuni channels on a daily basis (via the `daily summary` taskomatic job). Users are then notified in the UI with a reference to the latest release notes accordingly. The notification shown is currently rather generic and the patch relies on the repo names in order to work (), so this could be further improved in a number of ways. For example we could:
- Identify official channels via the URL instead of the repo name (to make it work even if an admin renamed the channels)
- Send email notifications or show a more prominent popup right after login
- Make the notification message more specific and show more details, for example distinguishing between security patch and new …
> Notify users when updates are available to the Uyuni server

- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/payg_extract_repo_data.py
- java/spacewalk-java.changes.mackdk.4.3-fix-credential-extraction-sles-12
This PR fixes an issue with extracting PAYG credentials from a SLES 12 client. In this os the default python 3 version is 3.4 and currently the script is using the subprocess.run() to run instance-flavor-check, which is not available for that version. This PR changes the script to use subprocess.call() instead. With this change, the way the PAYG instance is identified is also changed. Before we were relying on the text "PAYG" on the standard output, now we check the return code of the command.
Port of https://github.com/SUSE/spacewalk/pull/22523
**Wait for the 4.3 PR to be reviewed to merge this**
Fixes https://github.com/SUSE/spacewalk/issues/22522
Tracks https://github.com/SUSE/spacewalk/pull/22523 …
> Use call() instead of run() to maintain Python 3.4 compatibility

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/step_definitions/vm_steps.rb
The VM is far enough in the start process to get a shutdown event, so we also wait for this as the Leap 15.5 images are running the firstboot wizard.
No difference.
Fixes # …
> Also wait for JeOS firstboot dialog to stop VM

- susemanager/bin/server-migrator.sh
- susemanager/susemanager.changes.mbussolotto.server-migrator
Migrate from Leap 15.4 to 15.5
No difference.
- TODO
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/22507
> Migrate from Leap 15.4 to 15.5

- containers/init-image/Dockerfile
- containers/init-image/init-image.changes.oholecek.static_users
For various maintenance tasks and migrations, it is beneficial to have a stable and well known user and group ids for data in the container. This PR creates needed users and groups before anything is installed. Packages themselves during installation check for user/group existence and at most assign supplemental groups if needed.
UIDs and GIDs are starting at 10550 to limit potential conflict with host system and also avoid conflict with host's system users and groups.
DB's postgres user has to have login shell because we list it's envs during configuration which does not work with nologin.
No difference.
- Documentation issue was …
> Precreate system users to always have well known UID and GID

- testsuite/features/init_clients/proxy_branch_network.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
The name of the event in the event history and event summary doesn't exactly match, as the event summary doesn't have "scheduled by (system)". As such, we removed that part of the event check.
Fixes https://github.com/SUSE/spacewalk/issues/22555
- 4.3 https://github.com/SUSE/spacewalk/pull/22556 …
> QE: Fix event history check by shortening event name

- testsuite/podman_runner/07_manager_setup.sh
- testsuite/podman_runner/run_db_migrations.sh
Currently in the acceptance test we upgrade the database based on the version of the spec files. This breaks the tests when we create the new tag but the packages are not yet released and the podman container still has the old version installed. 
This PR changes this behaviour and uses the version of the schema package installed on the podman container to detect which scripts to run
No difference.
- No tests: change in the test scripts …
> Run the updates based on the installed version

- testsuite/features/init_clients/proxy_branch_network.feature
- testsuite/features/step_definitions/salt_steps.rb
This PR removes a fixed wait of 700 seconds.
2nd attempt - this time it has been tested properly, e.g. redeploying from scratch at each test.
We win between 6 to 8 minutes per test suite run in NUE and PRV.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22568
> No fixed delay until proxy gets responsive again

- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/rhui7_extract_repo_data.py
- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/rhui_extract_repo_data.py
- java/spacewalk-java.changes.mc.Manager-4.3-fix-RHUI7
Fix RHUI support for RHEL 7 client. As 8 and 9 may see the same in future, applied the same change also to the other script.
RedHat changed the hostnames of the RHUI repository server to include numbers in the name.
rhui.x.y.z => rhui3.x.y.z
Port of https://github.com/SUSE/spacewalk/pull/22598 …
> fix RHUI support for RHEL 7 clients

- .github/workflows/acceptance_tests_common.yml
- .github/workflows/acceptance_tests_secondary.yml
- .github/workflows/acceptance_tests_secondary_parallel.yml
- testsuite/podman_runner/19_get_server_logs.sh
CI: upload server logs as artifacts in github actions, so we can debug better. We need this for issues that are hard to reproduce, like when they only happen sometimes (flaky tests).
No difference.
- No tests
N/A
> upload artifacts in github actions for debugging

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.cbosdo.pkcs8-key
Newer versions of openssl generate the keys in PKCS8 format with the `BEGIN PRIVATE KEY` instead of `BEGIN (RSA|EC) PRIVATE KEY`.
The mgr-ssl-cert-setup tool now fails only if it cannot read the key or if the key is encrypted.
No difference.
- No tests: manual tests
Fixes # …
> Handle PKCS8 format for server keys in setup script

- search-server/spacewalk-search/spacewalk-search.changes.cbosdo.search_javaopts
- search-server/spacewalk-search/src/config/rhn-search
- search-server/spacewalk-search/src/config/search/rhn_search_daemon.conf
Since the tanuki wrapper removal we cannot enable Java remote debugging on the search server. A JAVA_OPTS option will now help this.
No difference.
- No tests: empty option
Fixes # …
> Add JAVA_OPTS option for rhn-search

- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
The config file to clean is no longer a `zip`, but a `tar.gz`. The missing file test fails in container server CI, but is ignored in master:
No difference.
Fixes # …
> testsuite: fix container proxy test cleanup

- CONTRIBUTING.md
This PR adds some notes and best practices about "Pull Requests"  to the `CONTRIBUTING.md` file. These notes were collected and agreed internally in our development squad.
We think it could be useful as general contributing notes on "Pull Requests" workflow and expectations.
NOTE: If you think these changes fit better directly in the "Contributing" page of the wiki, then we can agree here on the content and then incorporate it to the wiki. If so, please make your comment when making your review. TIA!
No difference.
- No tests: **no tests needed**
Tracks https://github.com/SUSE/spacewalk/issues/19311 …
> Enhance "CONTRIBUTING.md" with notes about Pull Requests

- testsuite/run_sets/secondary_parallelizable.yml
As mentioned in https://github.com/SUSE/spacewalk/issues/22594, the advanced search tests will be disabled in Uyuni until the search server can be reworked.
Fixes https://github.com/SUSE/spacewalk/issues/22594
No ports necessary
> QE: Disable Advanced Search tests for Uyuni

- web/html/src/branding/css/susemanager/components/buttons.less
- web/html/src/branding/css/uyuni/buttons.less
- web/html/src/components/datetime/DateTimePicker.test.tsx
- web/html/src/components/datetime/DateTimePicker.tsx
- web/html/src/utils/test-utils/mock.tsx
- web/html/src/utils/test-utils/screen.ts
- web/spacewalk-web.changes.eth.Manager-4.3-MU-4.3.8-bsc-1215820
Port of https://github.com/SUSE/spacewalk/pull/22630
> Fix datetimepicker erroneously updating the date field (bsc#1210253, bsc#1215820)

- susemanager-utils/susemanager-sls/salt/packages/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.fix-uyuni-in-cloud
Fix uyuni testsuite in cloud
- do not require instance-flavor-check tool on opensuse
No difference.
Fixes #
Tracks https://github.com/SUSE/spacewalk/pull/22536
> do not install instance-flavor-check on opensuse

- java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemReport_queries.xml
- java/code/src/com/redhat/rhn/taskomatic/task/ReportDbUpdateTask.java
- java/spacewalk-java.changes.mc.Manager-4.3-alt-reportdb-copy-sys_pkg_updates
Copying available package updates for systems into report db may take for some customers with extreme amount of data "endless" (multiple days).
This is an alternative approach to copy the data system by system.
Interestingly this is also faster when normal amount of data
```
``` 
The query explain in our case went down as well (factor 10)
Execution Time: 314.961 ms (OLD)
to
Execution Time: 29.757 ms (NEW)
Port of https://github.com/SUSE/spacewalk/pull/22611 …
> alternative to copy system package updates to reportdb

- java/code/src/com/redhat/rhn/domain/notification/UserNotificationFactory.java
- java/code/src/com/redhat/rhn/frontend/events/BaseMailAction.java
- java/spacewalk-java.changes.houssemnasri.fix-notification-error
The problem is that `Class#forName` can throw a `LinkageError` or `ExceptionInInitializerError` which wouldn't be caught by the current catch statement. Eventually, since `configureMailer()` is called during class initialization, the exception will be caught by the classloader and translated into `NoClassDefFoundError`. However, I still don't know why exactly an Error was thrown in the first place nor I can reproduce the other behaviors reported like the WebUI not responding. 
To reproduce, replace the content of `configureMailer()` with `throw new LinkageError();`, and then try to visit the notifications page. In the logs, you'll get a similar exception to what was reported in the linked issue. One difference is that the exception starts from `prepareUserNotifications` not `dataUnread`. …
> Fix NoClassDefFoundError when opening notifications

- java/code/src/com/redhat/rhn/frontend/action/renderers/setupwizard/MirrorCredentialsRenderer.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/webapp/WEB-INF/pages/admin/setup/mirror-credentials-verify.jsp
- java/spacewalk-java.changes.1211270.mikeletux
Port of https://github.com/SUSE/spacewalk/pull/22540
No difference.
PR in docs repo -> https://github.com/uyuni-project/uyuni-docs/pull/2469
Require testsuite change https://github.com/uyuni-project/uyuni/pull/7593
Fixes https://github.com/SUSE/spacewalk/issues/21688 …
> Wrong SCC credentials not marked as invalid

- java/buildconf/LICENSE.txt
- java/code/src/com/suse/manager/webui/controllers/AnsibleController.java
- java/code/src/com/suse/manager/webui/controllers/test/AnsibleControllerTest.java
- java/spacewalk-java.changes.mikeletux.bsc1213132
Port of https://github.com/SUSE/spacewalk/pull/22566
No difference.
- No documentation needed: it is a bugfix for something it should've worked earlier.
- Unit tests were added: `AnsibleControllerTest.testParseInventoryAndGetHostnames`
Fixes https://github.com/SUSE/spacewalk/issues/22065 …
> Master bug 1213132 ansible inventory

- susemanager/bin/pg-migrate-x-to-y.sh
- susemanager/susemanager.changes.vzhestkov.fix-owner-after-smdba
Running `smdba system-check autotuning` can produce the files in `/var/lib/pgsql/data/` with `root` user permission what can cause issues on running Postgres afterwards.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/22437 …
> Fix owner after smdba execution in the DB migration script (bsc#1214746)

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/spacewalk-java.changes.mackdk.remove-warning-in-payg-scenario
This PR removes a warning in the logs about missing Tools Channels subscription when the the tools channels are synced with PAYG credentials, as reported in https://github.com/SUSE/spacewalk/issues/22500#issuecomment-1720329031
No difference.
- No tests: only change in logging …
> Do not warn about missing Client Tools Channel subscription

- python/spacewalk/common/rhnConfig.py
- python/spacewalk/spacewalk-backend.changes.tanganellilore.fix_clear_cache_config
In `mgr-inter-sync` if we use `--iss-parent` or if we missing to add `iss_parent` on `rhn.conf`, configuration passed or retrived from DB will be used only for some functions, not for whole run of the script.
A issue that highlight this is this one:
https://github.com/uyuni-project/uyuni/issues/7565
This PR will fix this behavior, that is generated by calculation of initialized component and `timeDiff `in same line.
Actually, `self.__config` will be cleared everytime `self.__component` is `None` and `timeDiff` is not `0`, so everytime we have new component, we simply delete all config already loaded.
This probably was introduced with the new method `with cfg_component(component=None)` that for example is used internally. Calling this we simply define new component=None and `parse` …
> mgr-inter-sync command fix config clear cache

- testsuite/features/step_definitions/navigation_steps.rb
Currently the Cucumber step for selecting times uses 12-hour time which can lead to odd issues. Since our picker expects 24-hour time anyway, use that format instead.
```perl
use POSIX qw(strftime);
print strftime("%l:%M %P\n", localtime(5143213912312740)); # 9:59 pm
print strftime("%H:%M\n", localtime(5143213912312740)); # 21:59
```
No difference. …
> Make navigation steps use 24-hour time, not 12-hour time

- testsuite/podman_runner/run_db_migrations.sh
This PR changes the logic of how the sql scripts are applied in the podman testsuite runner. Instead of listing just listing the directories with a `find` and relying on the list to be correctly sorted (which was not the case and cause the linked issue), it now starts from the directory `<schema name>-<current version>-to-*` and moves to the next one specified after the `-to-` part, looping until there are no further directories to pick up.
This should ensure the correct application of all the required sql scripts starting from the current schema version installed inside the podman container.
No difference.
- No tests: only changes to the test infrastracture
Fixes https://github.com/SUSE/spacewalk/issues/22617
Make sure …
> Fix podman sql scripts selection

- web/html/src/components/datetime/DateTimePicker.test.tsx
- web/html/src/components/datetime/DateTimePicker.tsx
- web/html/src/utils/datetime/localizedMoment.test.ts
- web/html/src/utils/datetime/localizedMoment.ts
- web/spacewalk-web.changes.eth.date-improve
Currently, the picker works somewhat counterintuitively when you omit a ":" or leave off a trailing number, sometimes producing odd values which are not instantly clear why they happened. This PR moves the time parsing over to moment, adds test coverage, and other small improvements.
No difference.
If you need …
> Improve datetimepicker time input

- java/code/src/com/suse/manager/webui/controllers/login/templates/login.jade
- java/spacewalk-java.changes.eth.network-debug
- web/html/src/build/webpack.config.js
- web/html/src/core/log/loggerhead.ts
- web/html/src/utils/network.ts
- web/spacewalk-web.changes.eth.network-debug
Currently our global logger only logs errors and warns from our own code which means we crucially miss errors thrown from React etc. This PR binds our logger to the global console so we should see more information from debug logs.  
Additionally I've added [performance marks](https://developer.mozilla.org/en-US/docs/Web/API/Performance/mark) so it's easier to line up events if the client makes a performance recording for us. Otherwise you need to jump between our own logs and the recording to get the full picture.  
(As a side effect, thanks to these changes I found a small bug in our login page where the locale was set too late so it was undefined for some scripts.)
No difference.
Fixes …
> Make `Loggerhead` log include error logs from third-party code

- java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
- java/spacewalk-java.changes.cbbayburt.bsc1213689
Sync GPG fields on target repositories on build/promote in case the values have changed in the source after the last build.
Port of: https://github.com/SUSE/spacewalk/pull/22537
> Sync GPG properties on each build in CLM (bsc#1213689)

- testsuite/documentation/cucumber-steps.md
- testsuite/features/build_validation/add_non_MU_repositories/oracle9_minion_build_clm.feature
- testsuite/features/build_validation/containerization/proxy_as_pod_basic_tests.feature
- testsuite/features/build_validation/init_clients/proxy.feature
- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/init_clients/proxy_register_as_pod.feature
- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/retail_steps.rb
- testsuite/features/support/env.rb
This will fix test suite issues I found during the 4.3.8 BV
```salt
----------
ID: node_exporter
Function: pkg.installed
Name: golang-github-prometheus-node_exporter
Result: true
Comment: 1 targeted package was installed/updated.
Started: 03:21:31.704386
Duration: 4529.007
SLS: prometheus-exporters
Changed: golang-github-prometheus-node_exporter:
old: ''
new: 1.5.0-150100.3.26.1
----------
ID: node_exporter
Function: file.managed
Name: /etc/sysconfig/prometheus-node_exporter
Result: true
Comment: File /etc/sysconfig/prometheus-node_exporter updated
Started: 03:21:36.236282
Duration: 76.993
SLS: prometheus-exporters
Changed: diff: "--- 
+++ 
@@ -1,11 +1,9 @@
-## Path:        Network/Monitors/Prometheus/node_exporter
-## Description: Prometheus node exporter startup parameters
\
-## Type: …
```
> QE: Fix test suite issues for build validation

- testsuite/features/secondary/min_recurring_action.feature
- testsuite/features/step_definitions/datepicker_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
This will
- restore idempotency regarding SUSE minion child channels
- fix the issue with the event not showing up
The screenshot below shows e.g. the output of
```cucumber
And I check radio button "schedule-daily"
And I enter 2 minutes from now as "time-daily_time"
```
scheduled at around 11:21 am, but this is definitely not nearly around Europe/Berlin.
I adjusted the `get_future_time()` method according to the following:
https://ruby-doc.org/stdlib-2.5.8/libdoc/date/rdoc/DateTime.html#method-i-strftime
>Time (Hour, Minute, Second, Subsecond):
%H - Hour of the day, 24-hour clock, zero-padded (00..23)
%k - Hour of the day, 24-hour clock, blank-padded ( 0..23)
This method was only used in package installation tests, which I tested with my new changes. I also make use of this method in one …
> QE: Fix Recurring Actions test

- java/code/src/com/redhat/rhn/frontend/xmlrpc/saltkey/SaltKeyHandler.java
- java/spacewalk-java.changes.cbbayburt.bsc1214463
Updates the following endpoints in the 'saltkey' namespace to accept GET requests instead of POST:
- acceptedList
- pendingList
- rejectedList
- deniedList
Port of: https://github.com/SUSE/spacewalk/pull/22493
> Change list endpoints in saltkey namespace to accept GET requests instead of POST (bsc#1214463)

- java/code/src/com/redhat/rhn/frontend/events/NewUserAction.java
- java/code/src/com/redhat/rhn/frontend/events/NewUserEvent.java
- java/code/src/com/redhat/rhn/manager/user/CreateUserCommand.java
- java/spacewalk-java.changes.cbbayburt.bsc1214553
"Create user" action uses a different, older logic than all the other events to send emails and it doesn't respect users' email preferences. This patch removes users that have email notifications off from the recipient list when sending "user creation" emails.
Port of: https://github.com/SUSE/spacewalk/pull/22550 …
> Respect user email preferences when sending 'user creation' emails (bsc#1214553)

- testsuite/ext-tools/maintenance_json_generator.py
We were missing LTSS for 4.2 proxy and server and web scripting for 4.3. Web scripting is used for tomcat for example.
No difference.
Fixes no issue
Tracks no PR
> Update json script with missing products

- testsuite/features/core/srv_create_activationkey.feature
- testsuite/features/init_clients/allcli_update_activationkeys.feature
- testsuite/features/reposync/srv_create_repository.feature
- testsuite/features/reposync/srv_sync_fake_channels.feature
- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
- testsuite/run_sets/github_validation/github_validation_core.yml
- testsuite/run_sets/reposync.yml
First commit is about cleanup and nitpicks:
* remove a few duplicated test lines removed
* When/And
* unique scenario names
* homogeneous filtering of packages
Second commit is a refactor done independantly by Oscar and me:
* isolate the reposync of fake channels
Third commit does the real stuff:
* synchronize SLES 15 SP 4 on Uyuni (it will go to build host and PXE booted hosts)
* add a base channel to build host activation key
* create new channel and activation key for terminal, with SLES 15 SP4 as base channel
* make sure the PXE-bootstrapped hosts (both Cobbler and Retail) use the build host activation key
**It should be followed by a new PR that kills SLES 15 SP4 reposync right after beginning and tests Cobbler on Leap.**
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22720
> Sync sles too on uyuni 2

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Task_queries.xml
- java/code/src/com/redhat/rhn/domain/channel/AccessToken.java
- java/code/src/com/redhat/rhn/domain/channel/AccessTokenChangeException.java
- java/code/src/com/redhat/rhn/domain/channel/AccessTokenFactory.java
- java/code/src/com/redhat/rhn/domain/channel/test/AccessTokenFactoryTest.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/redhat/rhn/taskomatic/task/TaskConstants.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/webui/controllers/DownloadController.java
- java/code/src/com/suse/manager/webui/controllers/test/DownloadControllerTest.java
- java/code/src/com/suse/manager/webui/services/impl/SaltService.java
- java/spacewalk-java.changes.rmateus.m43_token_clean_up
backport of:
- https://github.com/SUSE/spacewalk/pull/21874
Delete invalid tokens in token cleanup process (bsc#1211874)
Customers with a high number of session tokens which is taking a long time to be able to process the channel authentication.
These PR sets add more data clean-up when to de-associate the token from the minion.
If the token is expired or if the token is invalid and not associated with any minion we can delete it.
Besides that, I move the delete part from java processing to one single SQL statement. This makes the process cleaner and much faster.
It also improves the mechanism of propagates the new token generation by making a salt async call instead of schinchronized.
Also add a validation that the token needs to exist in the database, otherwise is considered invalid.
No …
> Token cleanup process improvements (bsc#1213376)

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.rjpmestre.bsc1215120
adds the bootstrap data so SLES 15 for SAP SP1/2/3 entries are listed in mgr-create-bootstrap-repo (bsc#1215120)
No difference.
- No tests
https://github.com/SUSE/spacewalk/pull/22604
> Fix SLES 15 for SAP entries in mgr-create-bootstrap-repo (bsc#1215120)

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes.mackdk.Manager-4.3-reposync-key-import-debug
Port of https://github.com/SUSE/spacewalk/pull/22162
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/22119
> Added key import debug logging to reposync

- java/code/src/com/suse/manager/webui/controllers/DownloadController.java
Download Tokens of image build repositories are not stored in DB.
The valid check needs to pass if they are not found.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22727 …
> fix token check of image build repositories

- java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java
- java/code/src/com/redhat/rhn/taskomatic/TaskoJob.java
- java/code/src/com/redhat/rhn/taskomatic/TaskoQuartzHelper.java
- java/code/src/com/redhat/rhn/taskomatic/core/RhnJobFactory.java
- java/code/src/com/redhat/rhn/taskomatic/task/RepoSyncTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/UbuntuErrataTask.java
- java/spacewalk-java.changes.mackdk.improve-ubuntu-errata-processing
- schema/spacewalk/common/data/rhnTaskoTask.sql
- schema/spacewalk/common/data/rhnTaskoTemplate.sql
- schema/spacewalk/susemanager-schema.changes.mackdk.improve-ubuntu-errata-processing
- schema/spacewalk/upgrade/susemanager-schema-4.4.6-to-susemanager-schema-4.4.7/001-improve-ubuntu-errata-processing.sql
This PR aims to avoid repo-sync task starvation by separating the ubuntu errata syncing process. In this way, other reposync process can start without waiting for the download and the processing of the ubuntu errata database (which might take a long time when syncing ubuntu and debian channels).
To support this some improvement were made in the way taskomatic handles the execution of the tasks in the same bunch. In particular:
- If a task execution attempt results in a `null` value (meaning that the task is either already running or no more thread are available to process it) the bunch processing will be stopped and rescheduled if needed.
- When rescheduling the bunch, the new job will start from the index of the task that could not be executed and not from the beginning
No difference.
- …
> Improve ubuntu errata processing

- java/code/src/com/redhat/rhn/domain/notification/UserNotificationFactory.java
- java/code/src/com/redhat/rhn/domain/notification/test/NotificationFactoryTest.java
- java/spacewalk-java.changes.mc.Manager-4.3-fix-notification-email-content
Fix regexp which strip out too many characters
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22729
> fix notification messages email content

- testsuite/features/core/srv_create_activationkey.feature
- testsuite/features/init_clients/allcli_update_activationkeys.feature
- testsuite/features/reposync/srv_sync_fake_channels.feature
Test suite change:
We do not have SCC credentials to sync SLE channels. In any case, this was needed for the build host, for the retail use case, which is not tested in gh actions anyway.
No difference.
- No tests
N/A
> Skip sync SLE channels in github actions

- java/code/src/com/redhat/rhn/common/security/acl/Acl.java
- java/code/src/com/redhat/rhn/domain/kickstart/KickstartData.java
- java/code/src/com/redhat/rhn/frontend/action/CSVDownloadAction.java
- java/code/src/com/redhat/rhn/frontend/action/kickstart/PowerManagementAction.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/provisioning/powermanagement/PowerManagementHandler.java
- java/code/src/com/redhat/rhn/manager/configuration/ConfigurationValidation.java
- java/code/src/com/suse/manager/reactor/utils/RhelUtils.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
This PR fixes some of the problematic regular expressions by using `String contains()`  method or by using possessive quantifiers.
No difference.
- Covred by unit tests
Partially fixes https://github.com/SUSE/spacewalk/issues/21403
> Fix problematic regular expressions reported by SonarCloud

- testsuite/features/reposync/reference_srv_check_reposync.feature
- testsuite/features/reposync/reference_srv_sync_products_extra.feature
This updates the reposync tests to leap 15.5
No difference.
- This is a test
Fixes https://github.com/SUSE/spacewalk/issues/22688
> testsuite: update reposync to leap 15.5

- .github/workflows/susemanager-sls-compatible-python26-syntax.yml
Checkout@v1 is the only version compatible with python 2.6. Using a higher version leads to workflows failing when checking out the repo, see https://github.com/uyuni-project/uyuni/actions/runs/6427883155/job/17454183064?pr=7466
Refs https://github.com/uyuni-project/uyuni/pull/7498
No difference. …
> Use checkout@v1 in susemanager-sls-compatible-python26-syntax workflow

- .github/workflows/sonarcloud.yml
- java/code/src/com/redhat/rhn/common/security/acl/Acl.java
- java/code/src/com/redhat/rhn/frontend/action/CSVDownloadAction.java
- java/code/src/com/redhat/rhn/frontend/action/channel/manage/SyncRepositoriesAction.java
- java/code/src/com/redhat/rhn/frontend/action/kickstart/PowerManagementAction.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/PrimaryXmlWriter.java
- java/code/src/com/suse/manager/reactor/utils/RhelUtils.java
- java/code/src/com/suse/manager/reactor/utils/test/RhelUtilsTest.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/scc/client/SCCClientUtils.java
Add a workflow to run sonarcloud on each PR. Also fix regular expression issues pointed out by sonarcloud.
No difference.
Fixes #
> Sonarcloud action

- .github/workflows/susemanager-sls-compatible-python26-syntax.yml
This GH action is intended to run on python2, which is only supported by v1 of the checkout action.
Related failures after version bump: https://github.com/uyuni-project/uyuni/actions/workflows/susemanager-sls-compatible-python26-syntax.yml
> Revert actions-checkout dependency to v1 in python2 compatibility check

- java/code/src/com/redhat/rhn/frontend/action/common/DownloadFile.java
- java/spacewalk-java.changes.nadvornik.filespaces
- spacewalk/config/etc/httpd/conf.d/zz-spacewalk-www.conf
- spacewalk/config/spacewalk-config.changes.nadvornik.filespaces
backport of https://github.com/SUSE/spacewalk/pull/22606 and https://github.com/SUSE/spacewalk/pull/22670
> Handle spaces in /ks/dist/ file names bsc#1213680

- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataProcessor.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/payg_extract_repo_data.py
- java/spacewalk-java.changes.mc.Manager-4.3-fix-payg-cert-import
The payg import script look for the RMT CA certificate in the following order:
1. /usr/share/pki/trust/anchors/
2. /etc/pki/trust/anchors/
This order seems to be wrong as updates to certificates are applied to /etc/ only.
This cause old certificates are still available in /usr/... and gets imported (first match win)
while the new certificates in /etc/ are ignored.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22695 …
> Fix payg cert import

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/commonlib.rb
It seems we need to update and copy the CA certificate not only to the controller, but also to the proxy.
```bash
❯ rubocop _0.83.0_ features/support/commonlib.rb
Inspecting 1 file
.
1 file inspected, no offenses detected
```
```bash
suma-head-ctl:~/spacewalk/testsuite # cucumber features/secondary/srv_rename_hostname.feature 
Capybara APP Host: https://suma-head-srv.mgr.suse.de:8888
Initializing a twopence node for 'server'.
Host 'server' is alive with determined hostname suma-head-srv and FQDN suma-head-srv.mgr.suse.de
Node: suma-head-srv, OS Version: 15-SP4, Family: sles
Activating XML-RPC API
Using the default profile...
(...)
4 scenarios (4 passed)
15 steps (15 passed)
1m40.624s
```
No difference.
- Cucumber tests …
> QE: Fix `update_ca()` for hostname rename tests

- susemanager/susemanager.changes.mbussolotto.remove_uyuni-build-keys
- susemanager/susemanager.spec
ERROR:
```
=========== Test SUSE-Manager-Server x86_64 ===========
can't install patterns-suma_server-4.3-150550.10.1.develHead.x86_64:
package patterns-suma_server-4.3-150550.10.1.develHead.x86_64 requires susemanager-tools, but none of the providers can be installed
nothing provides uyuni-build-keys needed by susemanager-tools-4.4.8-150550.6.1.develHead.x86_64
```
Remove uyuni-build-keys dependency from susemanager rpm (susemanager-build-keys already priovides it)
No difference.
- 
- No tests …
> Remove uyuni-build-keys dependency from susemanager rpm

- python/spacewalk/satellite_tools/spacewalk-debug
- python/spacewalk/spacewalk-backend.changes.oholecek.support-config-db-stats
Port of https://github.com/SUSE/spacewalk/pull/22390
No difference.
- No documentation needed: As far as I know we don't have support config features documented
Tracks https://github.com/SUSE/spacewalk/pull/22390
> Add database table stats and configs to the support configs

- testsuite/features/reposync/reference_srv_check_reposync.feature
fix endless
` I am still waiting for 'opensuse_leap15_5' channel to be synchronized.`
No difference.
Before:
After:
- …
> fix opensuse channel names

- containers/doc/server-kubernetes/README.md
- containers/server-helm/templates/k3s-ingress-routes.yaml
Update the traefik routes forJDWP debug port changes for tomcat and search server
Also update the K3S documentation for offline installation after verification of the instructions.
No difference.
Fixes # …
> K3S debug ports and doc update

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
This PR fixes the most obvious issues in products page:
* align columns
* `@uyuyni` -> `@uyuni` for SLE micro 5.2
* re-enable disabled code for SLE micro 5.4
* (4.3 branch only) remove duplicated code for Debian 12
This PR does not fix:
* duplicate scenario names
* many `undefined method 'map' for true:TrueClass` errors at run time,
i.e. the web driver does not seem able to recover after an error
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22779
> Fix alignement, reenable disabled code

- testsuite/features/step_definitions/command_steps.rb
The full result is so big, that internal buffers seems to be filled and not the complete output is returned.
This cause no "SLES" keyword is included in the output and the test always hit the timeout.
This PR return only the important lines and make the test pass again.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/22784 …
> limit command output to important lines

- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/content_lifecycle_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/step_definitions/setup_steps.rb
- testsuite/features/support/commonlib.rb
> backport catch request_timeout

- java/code/src/com/redhat/rhn/common/security/acl/Access.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ServerSerializer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/webapp/WEB-INF/pages/systems/sdc/overview.jsp
- java/spacewalk-java.changes.mikeletux.22205
Port of https://github.com/SUSE/spacewalk/pull/22732
Port of https://github.com/SUSE/spacewalk/pull/22732
- Docs already in place in Javadoc
- No tests: just some changes in the UI
Port of https://github.com/SUSE/spacewalk/pull/22732
Tracks https://github.com/SUSE/spacewalk/issues/22205 …
> Master show client payg UI api

- java/code/webapp/WEB-INF/pages/kickstart/ssm/schedule.jsp
Don's video highlighted a UI bug, this button doesn't have the regular button classes.
Bugfix.
> Add missing button classes

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
We only need to add the client tools channel name when using `spacewalk-common-channels`. The base channel is not necessarily needed.
No difference.
- Manager-4.3: https://github.com/SUSE/spacewalk/pull/22802 …
> QE: fix SLE Micro client tools sync in Uyuni BV

- testsuite/features/support/constants.rb
Fix activation key tests.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22805
> Add missing constants for Debian 12

- testsuite/features/secondary/min_recurring_action.feature
The software update text is taking few seconds to show up. Because we are using should and not wait, we are expecting the text to be immediately visible. Change the should see to wait for text.
https://github.com/SUSE/spacewalk/issues/22735
> Fix recurring action test

- testsuite/features/reposync/reference_srv_sync_products_extra.feature
This was introduces by the switch from SLES to openSUSE in the Uyuni CI, but we do not need the sync of the Uyuni client tools in SUMA.
No difference.
- Manager 4.3: https://github.com/SUSE/spacewalk/pull/22816  …
> QE: Remove Uyuni client tools sync from reference reposync

- java/buildconf/ivy/ivy-suse.xml
- java/spacewalk-java.changes.mbussolotto.tomcat_rev
According to https://ant.apache.org/ivy/history/2.5.2/ivyfile/dependency.html update tomcat jars to version greater than 9.0.75 (but lower than 10.0.0).
No difference.
- No tests
> Update tomcat jars to version greater than 9.0.75

- susemanager-utils/susemanager-sls/salt/channels/dnf-susemanager-plugin/susemanagerplugin.py
- susemanager-utils/susemanager-sls/salt/channels/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mc.Manager-4.3-fix-azure-rhui-plugin-issues
- disable dnf_rhui_plugin as it break our susemanagerplugin. This plugin overwrite our X-Mgr-Auth header field
- fix susemanagerplugin to not overwrite header fields set by other plugins
No difference.
- No tests: **manual - happens only in Azure**
Port of https://github.com/SUSE/spacewalk/pull/22800 …
> disable dnf_rhui_plugin and fix header handling of susemanagerplugin

- .github/workflows/acceptance_tests_secondary.yml
fix permissions in github actions.
No difference.
- No tests
N/A
> Ci add feedback from gh actions acceptance tests fix

- .github/workflows/acceptance_tests_feedback.yml
- .github/workflows/acceptance_tests_secondary.yml
I am getting all the time permission problems if I try to add a comment from the same workflow we run the tests. Let's do it differently and add a comment from a separate workflow.
No difference.
- No tests
N/A
- [A] **DONE**
- [A] No changelog needed
> Ci add feedback as separate workflow

- containers/doc/server-kubernetes/README.md
Fix the tarball names in the podman offline container documentation.
No difference.
- No documentation needed: documentation notes change
- No tests: doc
Fixes #
> server container: fix the documentation for podman offline installation

- python/rhn/rhnlib.changes.mbussolotto.ca_rhnpush
add missing changelog
No difference.
- No …
> changelog - Use CA certificate from /etc/pki/trust/anchors in rhnpush 

- java/code/src/com/redhat/rhn/common/util/FileUtils.java
- java/code/src/com/suse/manager/ssl/SSLCertData.java
- java/code/src/com/suse/manager/ssl/test/SSLCertDataTest.java
- java/code/src/com/suse/manager/webui/controllers/ProxyController.java
- java/code/src/com/suse/manager/webui/utils/gson/ProxyContainerConfigJson.java
- java/spacewalk-java.changes.rjpmestre.fix_proxy_config_fqdn_mapping
- web/html/src/manager/proxy/container-config.tsx
- web/spacewalk-web.changes.rjpmestre.fix_proxy_config_fqdn_mapping
It was noticed that configuring a proxy sometimes would fail and just display a generic error. 
Analysis can be split in two: 
- what was causing the problem:
Files uploaded during configuration are stored and moved based on a 'machine name' mapping based on the provided 'Proxy FQDN'.
https://github.com/uyuni-project/uyuni/blob/32465f6efccd319926ae1897e14d9d20d4d89c39/spacewalk/certs-tools/sslToolLib.py#L73
Current solution based on a slightly more generic occurrence: 
https://github.com/uyuni-project/uyuni/blob/f1f62028c363f8ea95b0cc080b4fa9eddf9fbaa0/spacewalk/certs-tools/rhn_ssl_tool.py#L205
- why was just a generic error
This had to do with our (rhn) custom FileUtils throwing generic RTEs while RhnRuntimeException is expected …
> fix FQDN machine name mapping on proxy configuration

- client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes.raul.changelogs_spacewalk-client-tools_spacecmd
- spacecmd/spacecmd.changes.raul.changelogs_spacewalk-client-tools_spacecmd
Adds changelogs regarding the translations in the two mentioned packages, spacewalk-client-tools and spacecmd
No difference.
- No documentation needed: only changelogs additions
Related: https://github.com/SUSE/spacewalk/issues/22583
> Add changelogs for translations in spacewalk-client-tools and spacecmd

- .github/workflows/acceptance_tests_feedback.yml
rephrase message in gh actions
No difference.
- No tests
N/A
> rephrase message in gh actions

- testsuite/.rubocop_todo.yml
- testsuite/features/secondary/srv_rename_hostname.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/support/commonlib.rb
This 
- fixes the server hostname rename test
- added some basic hostname and certificate check after each rename
- moves the step `When(/^I apply highstate on "([^"]*)"$/) do |host|` to `salt_steps.rb` since it belongs there
- reverts the `update_ca` method to its original form because we only need it on the controller
```bash
dominik-ctl:~/spacewalk/testsuite # cucumber features/secondary/srv_rename_hostname.feature
(...)
22 scenarios (10 skipped, 12 passed)
45 steps (10 skipped, 35 passed)
5m39.206s
dominik-ctl:~/spacewalk/testsuite #
```
I implemented some basic certificate and hostname checks which did work:
```bash
(...)
Scenario: Check all new server certificates on the minions         # features/secondary/srv_rename_hostname.feature:131
This scenario ran at: 2023-10-19 14:42:12 …
```
> QE: Fix and improve the server hostname rename test

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/conf/rhn_java.conf
- java/spacewalk-java.changes.HoussemNasri.minutes-before-reboot
This PR adds a new config entry to `rhn.conf` named `java.reboot_delay` that is used to specify the number of minutes Uyuni has to wait before performing a system reboot.
No difference.
No documentation needed: **Description of the new config was added to `rhn_java.conf`. It should be enough as the default 3 minutes reboot delay was not mentioned in Uyuni docs nor in the XML-RPC API.**
No tests: already covered
Fixes https://github.com/uyuni-project/uyuni/issues/7707 …
> Enable setting system reboot delay via rhn.conf

- .github/workflows/acceptance_tests_feedback.yml
Only update comment in github, do not add a new one.
No difference.
- No tests
N/A
> CI: only update comment, or we create spam

- .github/workflows/acceptance_tests_feedback.yml
fixes the message from github actions acceptance tests at PR feedback.
No difference.
- No tests
N/A
> Fix feedback message for github

- .github/workflows/acceptance_tests_feedback.yml
fix the message from acceptance tests feedback
No difference.
- No tests
N/A
> Fix github message from acceptance tests

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/support/env.rb
This PR removes the `@skip_for_alma9`  and `@skip_for_rocky9` tags, now that Alma 9 and Rocky 9 have patches.
The implementation of these tags was wrong anyway.
Note: Alma 9 has no "Non-Critical" patches as of now. This should be fixed by 4.3.10. If it's not, we will work around it again, but this time with a working implementation.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22853
> Test patches on all clients excepted Debian

- testsuite/features/secondary/min_salt_formulas.feature
Enable sle_update_repo repository to have glibc-locale available needed for the parametrized formula
Fixes : https://github.com/SUSE/spacewalk/issues/22595
> Enable repository to have glibc-locale available

- susemanager-utils/testing/automation/obs-project.py
- susemanager-utils/testing/automation/publish-rpms.sh
This is a port of https://github.com/SUSE/spacewalk/pull/21921
In order to use the current user MFA setup, we better use "osc api" instead of trying to use urllib python library. Since a call to "osc" will already use the MFA that is setup for the current user. Otherwise, we would have to implement it with python urllib, which is, at least, challenging :)
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/21471 …
> CI: Use "osc api" so that it uses the Multi Factor Authentication

- schema/spacewalk/common/tables/rhnServerNeededCache.sql
- schema/spacewalk/susemanager-schema.changes.kwalter.serverneededcache-index
- schema/spacewalk/upgrade/susemanager-schema-4.4.6-to-susemanager-schema-4.4.7/002-add-serverneededcache-index.sql
adds an additional index to rhnserverneededcache to speed up certain types of queries.
No difference.
- No tests
Tracks https://github.com/SUSE/spacewalk/issues/21708
> add index on rhnserverneededcache server/errata id to speed up certain queries (bsc#1211912)

- testsuite/features/reposync/srv_create_fake_channels.feature
- testsuite/features/reposync/srv_create_fake_repositories.feature
- testsuite/features/reposync/srv_sync_fake_channels.feature
- testsuite/podman_runner/11_run_core_tests.sh
- testsuite/podman_runner/16_run_init_clients_tests.sh
- testsuite/podman_runner/17_run_secondary_tests.sh
- testsuite/podman_runner/18_run_secondary_parallelizable_tests.sh
- testsuite/podman_runner/18_run_secondary_parallelizable_tests_subset.sh
- testsuite/run_sets/github_validation/github_validation_core.yml
Having refactored in a previous PR how we handle synchronization of channels, we missed the fact that we don't need a different Cucumber feature on the GH Validation in order to create the fake repositories, therefore we can delete it and re-use the same Cucumber feature that we use in our CI test suite.
No difference.
- Cucumber tests were adapted
No Ports:
- Manager-4.3 (For now, we did not port GH Validations to Spacewalk) …
> QE: Fix GH validation core stage

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.mc.Manager-4.3-bsrepo-def-slemicro55
- susemanager/susemanager.changes.mc.bsrepo-def-slemicro55
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes.mc.bsrepo-def-slemicro55
- Add bootstrap repository data for SLE-Micro 5.5 and openSUSE Leap Micro 5.5
- add repository definitions for openSUSE Leap Micro 5.5 to spacewalk-common-channels
No difference.
A port of https://github.com/SUSE/spacewalk/pull/22860 + openSUSE Leap …
> add bootstrap repository data X micro 5.5

- testsuite/features/secondary/min_cve_audit.feature
- testsuite/features/step_definitions/api_common.rb
Fix the channel to check on the CVE Audit test
No difference.
Ports:
- Manager-4.3
> QE: Fix the channel to check on the CVE Audit test

- testsuite/features/step_definitions/command_steps.rb
This PR tries to call `check_restart` with the correct arguments.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22865
> We check the restart of the host, not of the SUMA server

- testsuite/features/secondary/srv_rename_hostname.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/support/commonlib.rb
- the proxy uses `venv-salt-minion` instead of `salt-minion`
- Red Hat-like minion has a different location for certificates: `/etc/pki/ca-trust/source/anchors/`
- Debian-like minion has a different location for certificates: `/usr/local/share/ca-certificates/susemanager/`
- no `pxeboot-minion` available at this point
- fix `certutil` issue in `update_controller_ca`
The test suite somehow can not apply high state on the KVM host via Salt. When running it manually, however, it works fine.
```bash
@virthost_kvm
Scenario: Apply high state on the virthost to populate new server CA # features/secondary/srv_rename_hostname.feature:120
This scenario ran at: 2023-10-24 09:21:24 +0200
Timeout after 250 seconds (Timeout.timeout), last result was: bash: dominik-min-kvm.mgr.suse.de: command not found …
```
> QE: Fixup for server hostname rename test

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/step_definitions/command_steps.rb
- The package `tftpboot-installation-openSUSE-Leap-15` is now available with the switch to openSUSE Leap 15.5
- the network interface `test-net0` was never stopped, which caused a failed highstate in the latter server hostname rename test
No difference. …
> QE: Improve KVM test

- testsuite/features/secondary/min_check_patches_install.feature
- testsuite/features/secondary/srv_check_channels_page.feature
We had some changes to the checksums recently and switched from SHA256 to SHA512.
Fixes https://github.com/SUSE/spacewalk/issues/22845
Tested on HEAD.
```bash
(...)
Scenario: Check packages of SLES release 6789 patches                                                                                                               # features/secondary/min_check_patches_install.feature:36
This scenario ran at: 2023-10-24 14:35:53 +0200
When I follow the left menu "Patches > Patch List > Relevant"                                                                                                     # features/step_definitions/navigation_steps.rb:364
And I follow "andromeda-dummy-6789" …
```
> QE: Fix switch from sha256 to sha512

- testsuite/features/build_validation/init_clients/monitoring_server.feature
- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/step_definitions/common_steps.rb
There were errors when, in Grafana, we were trying to check a radio button when it was already checked. This makes it so we don't double check the button, and the rest of the tests can continue as normal. Tested with @Bischoff on the 4.3.9 BV.
- 4.3 https://github.com/SUSE/spacewalk/pull/22857 …
> QE: Fix grafana radio button check

- python/billingdataservice/billing-data-service.changes.mc.Manager-4.3-relax-dependency
- python/billingdataservice/billing-data-service.spec
This makes the install check pass  when the public cloud module is not available.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/22854
> relax dependency to csp-billing-adapter-service

- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/server/importlib/backend.py
- python/spacewalk/server/importlib/packageImport.py
- python/spacewalk/spacewalk-backend.changes.witek.add-unique-index
- schema/spacewalk/common/tables/rhnPackageChangeLogData.sql
- schema/spacewalk/postgres/start.sql
- schema/spacewalk/upgrade/susemanager-schema-4.4.6-to-susemanager-schema-4.4.7/203-add-changelogdata-index.sql
In spite of client code trying to avoid duplicate records for changelog
data such records are observed in the database.
The change enforces unique combination of `name`, `time` and `text`
fields by updating the definition of the unique index on the database
level.
Additionally:
- Add logging package details during failed import.
- Clean up the logic for removing duplicate changelog entries.
Tracks suse/spacewalk#22470 …
> Extend unique index for rhnpackagechangelogdata table

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
According to my tests, the deployment of `/etc/s-mgr/config` works even if we don't reboot afterwards.
This PR does not make stability any better, it just helps speed.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22868
> A reboot is not needed to deploy a file in /etc on a SLE micro

- testsuite/features/build_validation/init_clients/slemicro51_minion.feature
- testsuite/features/build_validation/init_clients/slemicro52_minion.feature
- testsuite/features/build_validation/init_clients/slemicro53_minion.feature
- testsuite/features/build_validation/init_clients/slemicro54_minion.feature
- testsuite/features/step_definitions/command_steps.rb
It looks like SSH reboots on SLE micro minions provoke `Minion is down or could not be contacted` failures.
Switching back to plain old UI reboots.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/22873
> Reboot SLE micros through the web UI

- python/spacewalk/satellite_tools/spacewalk-debug
- python/spacewalk/spacewalk-backend.changes.slsnow.spacewalk-debug-clm
1. Query and store CLM project history for each project:
- For each project, the script retrieves the project's environments and their current corresponding version histories.
- More specifically, the project's environment history (message, version, and created date) is saved in a separate text file for each project under the "clm/projects" directory.
2. Save all CLM related DB tables to "clm/full_tables.txt":
- The script queries all the tables related to the Content Lifecycle Management (CLM) feature.
- The output is saved in a single file called "clm/full_tables.txt" in the output.
This should be helpful for users and support engineers, to avoid having to collect this data from the webUI manually. It may be helpful to add something similar to the API and spacecmd.
Fixes …
> Adding CLM collection to spacewalk-debug

- rel-eng/push-packages-to-obs.sh
IBS is failing building two images:
- `init-image` -> `unresolvable: nothing provides container:opensuse/leap:15.4`
- `server-image` -> `unresolvable: nothing provides container:uyuni/init:latest`
The issue can be fix in  `push-packages-to-obs.sh` (as explained here https://github.com/uyuni-project/uyuni/commit/ae1a97c2f530387e3dde697d3d142e6eb21eebed ) :
- `init-image` is not required in IBS, so it shouldn't be pushed
- `server-image`  should use `bci/bci-init:15.4` instead of `container:uyuni/init:latest`
No difference.
- No tests
If you …
> Use INIT_BASE bci for images push in ibs

- python/spacewalk/spacewalk-backend.changes.mc.more-strict-permissions
- python/spacewalk/spacewalk-backend.spec
Use better file permissions for a config file
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/22880
> set stricter file permissions for config file

- java/code/src/com/redhat/rhn/common/util/http/HttpClientAdapter.java
- java/code/src/com/suse/manager/webui/services/impl/SaltService.java
- java/conf/rhn_java.conf
- java/spacewalk-java.changes.mc.Manager-4.3-salt-api-connection
It seems that sometimes (with high load) HTTP connections from taskomatic to salt-api for salt-ssh calls gets stuck,
while the ssh connection from the server to the client does not exist (anymore?), the http connection is still up and waiting for a result. Such connections can stay open for days.
To prevent keeping these connections open forever, this PR introduce a socket timeout which will kill the connection after a time of inactivity.
This time is by default very long (12 hours) as during a salt-ssh connection a full state.apply needs to be finished before a result is send back. If this state.apply contain for example a distribution upgrade with thousand of packages, it could take hours to complete.
No difference.
- …
> specify http timeouts for salt-api connections

- java/code/src/com/redhat/rhn/frontend/xmlrpc/RhnXmlRpcServer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/XmlRpcServlet.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/spacewalk-java.changes.meaksh.Manager-4.3-fix-xmlrpc-provision-server-endpoint
This PR fixes an issue with `system.provisionSystem` endpoint, where the kickstart host that is used to generate tftpboot tree is calculated based on the hostname of the request, leading to wrongly assume `localhost` (and therefore generating wrong files) when connected to Uyuni XMLRPC API via `localhost`.
This PR makes this endpoint to use the same mechanism that the UI uses to calculate the kickstart host:
- If request is done via an Uyuni Proxy -> use the first proxy address in the chain of Uyuni proxies.
- Otherwise use default Cobbler host (Uyuni Server)
You can see the above mechanism implemented here: https://github.com/SUSE/spacewalk/blob/d4787b8757f0f5d2bbc56c5b325258349d56df09/java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartHelper.java#L258-L282
No difference.
- …
> Fix "system.provisionSystem" xmlrpc endpoint to calculate kickstart host properly (bsc#1215209)

- rel-eng/push-packages-to-obs.sh
use init-image based on bci-base 15.4 in IBS
No difference.
- No tests
> use init-image based on bci-base 15.4 in IBS

- schema/spacewalk/common/tables/rhnPackageChangeLogData.sql
- schema/spacewalk/upgrade/susemanager-schema-4.4.6-to-susemanager-schema-4.4.7/203-add-changelogdata-index.sql
Fix schema migration script for creating unique index.
> Fix creating unique index

- containers/init-image/Dockerfile
- containers/server-image/Dockerfile
- rel-eng/push-packages-to-obs.sh
Change base image format and PRODUCT_PATTERN_PREFIX, to match regex in push-to-obs
No difference.
- No tests
> Change base image format and PRODUCT_PATTERN_PREFIX, to match regex in push-to-obs

- java/code/src/com/redhat/rhn/common/util/http/HttpClientAdapter.java
We moved a function into an inner class.
But it was used in Test cases in a special way which require it to be external.
This PR reset everything back
No difference.
No backport to 4.3 required …
> Bing back dropped use for proxy method

- rel-eng/push-packages-to-obs.sh
server-image should use suse/manager/4.4/init:latest in IBS
No difference.
- No testsd
> server-image should use suse/manager/4.4/init:latest in IBS

- testsuite/features/secondary/min_change_software_channel.feature
Update enabled software channel. We need a description of the expected channels in the future.
No difference.
> Update enabled software channels number

- testsuite/features/secondary/srv_dist_channel_mapping.feature
Use full debian base channel name to avoid ambiguous map.
Indeed base channel is matching more than one element in the channel drop box.
We are lucky to have this issue only in this feature. Our fake base channel should never have only Fake-Base-Channel name because it is share by more than one channel. I think we should rename the fake base channel for suse as for rh and debian like channel ( Fake-Base-Channel-Suse-like )
No difference. …
> Use the full debian base channel name to avoid Ambiguous match

- spacewalk/setup/spacewalk-setup.changes.sbluhm.Replace_filesize
- spacewalk/setup/spacewalk-setup.spec
Replace "filesize" in spacewalk-setup post script with "stat" to allow running on Enterprise Linux.
No difference.
> Replace filesize with stat

- testsuite/features/reposync/allcli_update_activationkeys.feature
Fake-RPM-Terminal-Channel is only created when a pxeboot minion is part of the tests.
This is on the case in the cloud. Do not try to assign this channel to an activation key
No difference.
No port needed as this channel does not exist in 4.3 …
> do not assign Fake-RPM-Terminal-Channel to activation key when channel was not created

- client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes.stefan.titofix
- client/rhel/spacewalk-client-tools/spacewalk-client-tools.spec
- java/spacewalk-java.changes.stefan.titofix
- java/spacewalk-java.spec
- projects/ssl-cert-check/spacewalk-ssl-cert-check.changes.stefan.titofix
- projects/ssl-cert-check/spacewalk-ssl-cert-check.spec
- python/spacewalk/spacewalk-backend.changes.stefan.titofix
- python/spacewalk/spacewalk-backend.spec
- schema/reportdb/uyuni-reportdb-schema.changes.stefan.titofix
- schema/reportdb/uyuni-reportdb-schema.spec
- schema/spacewalk/susemanager-schema.changes.stefan.titofix
- schema/spacewalk/susemanager-schema.spec
Tito requires to list the package source as %{name}-%{version}.tar.gz
If an existing source is set, tito downloads the package instead of using the git structure. This stops the package from building on Fedora Copr (the download has a different folder structure).
(see Tito man page at https://github.com/rpm-software-management/tito/blob/9fd0c5a2c7c801f3186a0d7c836ed7278fdcff0c/tito.8.asciidoc?plain=1#L55)
No difference.
Build manually tested on copr  epel-9-x86_64.
Fixes # …
> Update package source to meet tito requirement

- testsuite/dockerfiles/controller-dev/Dockerfile
- testsuite/dockerfiles/opensuse-minion/Dockerfile
- testsuite/dockerfiles/server-all-in-one/Dockerfile
Testsuite: update test containers to leap 15.5
No difference.
- No tests
Fixes https://github.com/SUSE/spacewalk/issues/22694
> Testsuite: update test containers to leap 15.5

- java/spacewalk-java.changes.sbluhm.googlegson
- java/spacewalk-java.spec
1. Disallow Google GSON 2.10 or higher due to removed methods.
Salt communication fails otherwise with a class not found exception when accessing the Salt keys page.
(GSON 2.10 is available in the Enteprise Linux 9 repos)
2. Remove minimum GSON requirement. What would install a lower version?
No difference.
Package build tested on Copr for  epel-9-x86_64 
Fixes #
If you …
> Disallow Google GSON 2.10 or higher due to removed methods

- testsuite/dockerfiles/server-all-in-one-dev/Dockerfile
- testsuite/dockerfiles/server-all-in-one-dev/minima.yaml
This PR add the synchronization of Deb Test Packages repository, in order to be able to test Debian-like clients in the GitHub Validation
No difference.
- No tests
No ports.
> CI: also sync deb repos

- web/conf/rhn_web.conf
- web/spacewalk-web.changes.deneb-alpha.Bump_WebUI_Version
**Update the WebUI version to 2023.10**
Before: 2023.09
After: 2023.10
- No documentation needed: **this is only a bump of the WebUI version**
- No tests: **Update the WebUI version to 2023.10**
Relates https://github.com/SUSE/spacewalk/issues/22583
> Bump WebUI version

- containers/init-image/Dockerfile
Parametrize info in init image, in this way `push-packages-to-obs.sh` can set the correct values for IBS.
No difference.
- No tests
> Parametrize info in init image

- .github/workflows/acceptance_tests_common.yml
> CI: Enable workflow for acceptance tests

- testsuite/features/support/commonlib.rb
Add a new if statement to catch empty repositories while we are waiting for a channel to be synchronized.
No difference.
Ports:
- It will be included together with https://github.com/SUSE/spacewalk/pull/22934
> QE: Add a new if statement to catch empty repositories while we are waiting for a channel to be synchronized

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes.raul.fix_debian_12_uyuni_client_tools_stable
URL for Debian 12  repo  for Uyuni client tools (stable) was wrong, at some point of it, it contained a "11" instead of a "12".
Nothing to be seen in the GUI, maybe in the console when using spacewalk-common-channels, but no GUI.
Fixes #7830 …
> Fix Debian 12 wrong repo url for Uyuni client tools (stable)

- testsuite/features/step_definitions/command_steps.rb
Fix the step to extract log files from active nodes
No difference.
Ports:
- Manager-4.3
> QE: Fix the step to extract log files from active nodes

- .github/workflows/acceptance_tests_common.yml
- testsuite/podman_runner/19_get_server_logs.sh
- testsuite/podman_runner/20_get_client_logs.sh
Collect log files from clients, when the GH Validation fails
No difference.
- No tests
No ports
> GH validation client logs

- testsuite/features/support/commonlib.rb
Debug log for channel_is_synced method
No difference.
Ports:
- Manager-4.3
> QE: Debug log for channel_is_synced method

- testsuite/features/support/commonlib.rb
- testsuite/features/support/constants.rb
We expect some channels to be empty.
It's hard to programmatically know when a channel is empty or just still in progress.
So, for now, we will skip those channels that we expect empty through a new array.
No difference.
Ports:
- Manager-4.3 …
> QE: Skip the 'wait to be synched' of empty channels

- testsuite/features/support/commonlib.rb
Small refactor to obtain in the GH action output the grains values for each node.
No difference.
- No tests
Ports:
- Manager-4.3
> Refactor collecting salt grains output

- testsuite/features/secondary/min_cve_audit.feature
- testsuite/features/secondary/srv_activationkey_api.feature
- testsuite/features/step_definitions/api_common.rb
Fix the channel label to compare in CVE Audit test, and take advantage of that to improve some other steps to have a more concise input.
No difference.
Ports:
- Manager-4.3
> QE: Fix the channel label to compare in CVE Audit test

- testsuite/features/github_validation/init_clients/sle_minion.feature
- testsuite/features/github_validation/init_clients/sle_ssh_minion.feature
- testsuite/features/init_clients/min_rhlike_salt.feature
- testsuite/features/reposync/srv_create_fake_channels.feature
- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/min_recurring_action.feature
- testsuite/features/secondary/min_rhlike_openscap_audit.feature
- testsuite/features/secondary/min_rhlike_ssh.feature
- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/secondary/srv_delete_channel_from_ui.feature
- testsuite/features/secondary/srv_dist_channel_mapping.feature
- testsuite/features/secondary/srv_manage_channels_page.feature
- testsuite/features/secondary/srv_patches_page.feature
- testsuite/features/secondary/srv_push_package.feature
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/support/constants.rb
Rename Fake Base Channel and Fake Child Channel to fix ambiguity issues
No difference.
Ports:
- Manager-4.3
> QE: Rename Fake Base Channel and Fake Child Channel to fix ambiguity issues

- testsuite/features/upload_files/salt_event_parser.py
In the latest BV I had this failure:
```
15:04:10  Then the salt event log on server should contain no failures # features/step_definitions/salt_steps.rb:448
15:04:10        FAIL: python3 /tmp/salt_event_parser.py returned status code = 1.
15:04:10        Output:
15:04:10        Traceback (most recent call last):
15:04:10          File "/tmp/salt_event_parser.py", line 30, in <module>
15:04:10            if not j["return"][k]["result"]:
15:04:10        TypeError: string indices must be integers
15:04:10         (RuntimeError)
15:04:10        ./features/support/lavanda.rb:154:in `run'
15:04:10        ./features/step_definitions/salt_steps.rb:456:in `/^the salt event log on server should contain no failures$/'
15:04:10        features/build_validation/finishing/srv_debug.feature:13:in `the …
```
> Fix QE script to not throw traceback

- testsuite/.rubocop.yml
- testsuite/features/step_definitions/api_common.rb
- testsuite/features/step_definitions/cobbler_steps.rb
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/content_lifecycle_steps.rb
- testsuite/features/step_definitions/datepicker_steps.rb
- testsuite/features/step_definitions/docker_steps.rb
- testsuite/features/step_definitions/file_management_steps.rb
- testsuite/features/step_definitions/lock_packages_on_client.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/step_definitions/retail_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/step_definitions/setup_steps.rb
- testsuite/features/step_definitions/smdba_steps.rb
- testsuite/features/step_definitions/vm_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/http_client.rb
- testsuite/features/support/kubernetes.rb
- testsuite/features/support/lavanda.rb
- testsuite/features/support/namespaces/system.rb
- testsuite/features/support/twopence_env.rb
- testsuite/features/support/twopence_init.rb
Passing always a Exception class will prevent to warn this Cop https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/RaiseException
No difference.
Ports:
- Manager-4.3
> QE: Improve our raise exception avoiding a Rubocop warning

- susemanager-utils/susemanager-sls/salt/packages/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.obarrios.fix-mgr_install_flavor_check-salt-state-for-opensuse
The evaluation of the salt state mgr_install_flavor_check was incorrect in our GH acceptance tests, where we deploy in a container an openSUSE 15.5 Salt minion.
This PR aims to fix it by removing the change to lowercase, being more explicit in the evaluation.
No difference.
- No tests
Ports:
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/23007 …
> Fix the evaluation of mgr_install_flavor_check in openSUSE

- java/spacewalk-java.changes.sbluhm.apache-commons-io
- java/spacewalk-java.spec
Build of FileUtils fails with apache-commons-io bundles lower than 2.11.0. This change ensures the minimum version to build.
No difference.
Build tested on copr for
`epel-9-x86_64 `
` opensuse-leap-15.5-x86_64 ` …
> Enforce minimum build version for apache-commons-io

- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
- testsuite/features/step_definitions/navigation_steps.rb
Following the example of min_recurring_action, downgrade milkyway-dummy-1.0 on sle minion, switch to fake channel to have milkyway-dummy-2.0 available. Apply the upgrade and switch back the channel.
For the Remove package from Salt minion, the scenario was not removing a package but installing one. Change the scenario to remove a package.
No difference. …
> Have patch available for upgrade in a control scenario

- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
Revert change for the tftpd package for cobbler.
No difference.
Before:
After:
- 
> Revert cobbler changes

- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/spacewalk-java.changes.meaksh.master-fix-traceback-remote-commands
This PR makes that action result for a Remote Command action to be set even if there are unexpected issues parsing the expected JSON from the action execution.
For example, before this PR, in cases of broken SSH connection while running a Remote Command action, the action will appears as stuck forever, as the traceback produced at parsing JSON is preventing the action result to be set.
No difference.
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-r …
> Prevent losing Remote Command action result if returned JSON cannot be parsed

- java/code/src/com/suse/scc/SCCSystemRegistration.java
- java/spacewalk-java.changes.rjpmestre.enhance-hardware-data-sent-to-scc-by-memory
As SCC API can now collect systems memory (RAM).  
This enhances hardware data sent to SCC by adding total memory in MiB
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/22758
> Enhance hardware data sent to SCC by memory

- .gitignore
- python/spacewalk/satellite_tools/repo_plugins/__init__.py
- python/spacewalk/satellite_tools/repo_plugins/deb_src.py
- python/spacewalk/satellite_tools/repo_plugins/yum_dnf_src.py
- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes.mczernek.7594-fix
When an RPM package does not set required metadata headers, reposync throws errors for that repository.
In this change, we enforce that the metadata is set before the repository plugin includes the package in the `list_packages` function for further processing.
No difference.
- No tests: no tests seem necessary (though I can add one for each modified plugin repository if you think it necessary)
Closes https://github.com/SUSE/spacewalk/issues/22135 …
> fix(7594): Skip syncing packages with incorrect metadata (bsc#1213738)

- python/spacewalk/satellite_tools/download.py
- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/satellite_tools/spacewalk-repo-sync
- python/spacewalk/spacewalk-backend.changes.mczernek.4746
- python/test/unit/spacewalk/satellite_tools/test_download.py
- python/test/unit/spacewalk/satellite_tools/test_reposync.py
When a package fails to download, `reposync.py` still tries to process and link it internally. This PR fixes https://github.com/uyuni-project/uyuni/issues/4746
No difference.
Before:
After:
Fixes # …
> fix(4746): Do not link and sync pkgs that fail to download

- .github/workflows/acceptance_tests_feedback.yml
This way, users can compare their results with master.
> CI: Add links to secondary test results in master

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/commonlib.rb
This fixes our `Extract the logs from all our clients` scenario.
No difference.
- Manager 4.3: 
> QE: Fix log file extraction scenario

- spacewalk/spacewalk-setup-postgresql/setup/postgresql.conf
- spacewalk/spacewalk-setup-postgresql/spacewalk-setup-postgresql.changes.nadvornik.disable_jit
This PR disables JIT in new postgres configurations.
JIT can cause long delays (1-2s) at random queries. In Uyuni/SUMA it probably does not bring any benefits.
JIT is provided by postgresql-llvmjit package. The package is typically installed in Uyuni and not installed in SUMA.
Details in https://github.com/SUSE/spacewalk/issues/22363
- WIP
- No tests: our tests run without JIT
Fixes https://github.com/SUSE/spacewalk/issues/22363 …
> Disable postgres JIT

- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataExtractor.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/script/detect_os.sh
- java/spacewalk-java.changes.mc.Manager-4.3-sle-micro-payg-os-detection
PAYG Connection feature has a os detection to differentiate between SLES, RHEL 7, 8 and 9.
SLE-Micro does not match the SLES detection. This PR fix this and will perform the same detection as on SLES.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/23014 …
> fix SLE-Micro PAYG detection

- .vscode/settings.json
See title.
No difference.
- No documentation needed: devtools
- No tests: devtools
Fixes https://github.com/uyuni-project/uyuni/pull/7820#discussion_r1392350207
> Scope off VSCode editor settings, update outdated spec

- testsuite/features/support/commonlib.rb
QE: Add constants.rb and api_test.rb dependencies for commonlib
No difference.
Ports:
- Manager-4.3
> QE: Add constants.rb and api_test.rb dependencies for commonlib

- java/code/src/com/suse/scc/client/SCCWebClient.java
Improve logging for SCC Web Client. Log URLs in info level and more data in debug.
No difference.
Issue https://github.com/SUSE/spacewalk/issues/22943
> Improve web client logging

- java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java
- java/spacewalk-java.changes.mc.ubuntu-errata-compressed-db
Ubuntu provide the USN database also Bzip2 compressed.
Try to download the compressed first. In case this is not working fallback to raw json file.
In terms of time it does not give a big difference if the network bandwidth is high.
Maybe is makes a difference with less bandwitdth.
Download and decompress in case of bzip compressed file it takes ~ 15 seconds.
Same number when you download the uncompressed file.
The second commit skip all errata which does not have matching package names in the channel we look at.
This seems to bring down the time by 50% on the update channel i tested with.
No difference.
Two points of https://github.com/SUSE/spacewalk/issues/20604
Ports: …
> try to download compressed ubuntu usn database and skip errata without packages

- java/code/src/com/suse/manager/webui/controllers/DownloadController.java
My PR made the methods not static. A second PR rolled it back by accident and created this syntax error.
No difference.
Fix syntax error introduced by https://github.com/uyuni-project/uyuni/pull/7885 …
> remove static rolled back by a different PR

- testsuite/features/reposync/srv_create_fake_channels.feature
- testsuite/features/reposync/srv_create_fake_repositories.feature
- testsuite/features/reposync/srv_sync_fake_channels.feature
- testsuite/features/secondary/srv_channel_api.feature
This PR adds the fake repository to the child channels in case the fake distributions have both base and child channels.
After that, it forces the synchronization of the child channels in order to be populated with the content of the fake repositories.
Additionally, it removes a leftover `testsuite/features/core/srv_create_fake_repositories.feature`
This aims to solve an issue in several cases, where we were expecting to have certain packages, but the channels were empty and so the systems doesn't have updates available:
Feature:Recurring Actions
No difference.
Ports:
- Uyuni https://github.com/SUSE/spacewalk/pull/23039 …
> QE: Fix child channels synchronization

- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/support/commonlib.rb
Convert time to integer before using in commonlib. Enforce it so it's not a string. 
No difference.
Fixes no issue, directly from testsuite review.
Tracks no 4.3 needed, the method doesn't exist in 4.3 …
> Convert time to integer before using

- testsuite/features/reposync/srv_sync_fake_channels.feature
Don't sync the test-base-channel as it doesn't contain anymore a test repository, instead, we included it on its child channel.
If we do, Uyuni will show an error.
No difference.
- Cucumber tests were removed
- Manager-4.3 Already part of https://github.com/SUSE/spacewalk/pull/23039 …
> QE: Don't sync test-base-channel as it doesnt contains any repo

- testsuite/features/secondary/min_recurring_action.feature
A testrepo was added at recurring action test and not removed again.
This cause errors in later tests when counting the assigned repos
No difference.
Port of https://github.com/SUSE/spacewalk/pull/23055 …
> disable test repo after usage

- testsuite/run_sets/reference_reposync.yml
Fix reference setup and add steps which add and update activation keys.
No difference.
Ports https://github.com/SUSE/spacewalk/pull/23057
> add required steps about activation keys

- java/code/src/com/redhat/rhn/frontend/action/kickstart/ScheduleKickstartWizardAction.java
- java/spacewalk-java.changes.welder.bsc1217223
Clicking on `Create PXE installation configuration` after selecting a non SUSE Manager manager profile was causing a NPE when checking if the "disk warning" should be shown. This PR fixes the NPE.
No difference.
Port of https://github.com/SUSE/spacewalk/pull/23048 …
> Fix NPE when creating PXE config for an unmanaged profile

- java/code/src/com/redhat/rhn/frontend/action/BaseSearchAction.java
- search-server/spacewalk-search/src/java/com/redhat/satellite/search/index/IndexManager.java
- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
- testsuite/features/step_definitions/command_steps.rb
Fix more testsuite errors
No difference.
These tests or errors do not exist in 4.3
> More testsuite fixes

- testsuite/features/secondary/allcli_software_channels_dependencies.feature
Clear SSM as pre-requisite for channel subscription tests
This will assure that other previous features failing, not running the clean-up scenarios, will not cause this feature to fail due to previous selected systems.
Example:
No difference.
Ports:
- Manager-4.3 …
> QE: Clear SSM as pre-requisite for channel subscription tests

- java/buildconf/ivy/ivy-suse.xml
jetty-util was updated in OBS. Change our ivy file to use the new version.
Port of https://github.com/SUSE/spacewalk/pull/22901
> update ivy version of jetty-util

- testsuite/features/init_clients/min_rhlike_salt.feature
- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/min_rhlike_openscap_audit.feature
- testsuite/features/secondary/min_rhlike_ssh.feature
- testsuite/features/secondary/srv_maintenance_windows.feature
Assign correct channel to RH-like systems
No difference.
Ports:
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/23064
> QE: Assign correct channel to RH-like systems

- testsuite/features/secondary/min_change_software_channel.feature
Fix the number of enabled repositories expected in the feature "Assign child channel to a system".
It has been decreased by one because we [recently](https://github.com/uyuni-project/uyuni/pull/7906) fixed another collateral issue where we forgot to disable an injected test repository.
No difference.
It seems it doesn't need a port.
If you need to …
> QE: Fix the number of channels expected

- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
Fix a typo on the pod proxy test.
As `And I check the package for "..." in the list` as a step wrapping `And I check "..." in the list` for a particular host.
In our case after the refactor that has been made recently, we want to directly set a particular package.
No difference.
Ports:
- Manager-4.3 …
> QE: Fix a typo on the pod proxy test

- testsuite/features/step_definitions/api_common.rb
- testsuite/features/support/http_client.rb
Fixing this step, because we must specify the exception to catch:
No difference.
Ports:
- Manager-4.3
> QE: Fix the rescue of a wrong API call

- susemanager-branding-oss/susemanager-branding-oss.changes.mbussolotto.branding_oss_build_fix
- susemanager-branding-oss/susemanager-branding-oss.spec
- web/spacewalk-web.changes.mbussolotto.el9_package
- web/spacewalk-web.spec
Fix missing folders in susemanager-branding-oss spec file and spacewalk-web rpm
No difference.
- No tests
> Fix susemanager-branding-oss and spacewalk-web rpm

- testsuite/podman_runner/09_build_server_code.sh
Because of https://github.com/uyuni-project/uyuni/pull/7651, package files are moved from /srv. However, this change is done at the RPM spec file, meaning it won't be available in the gh actions until the new RPM packages for uyuni have been released and published.
Thus, meanwhile, we need to create those dirs by hand.
> gh actions: fix directories

- testsuite/dockerfiles/controller-dev/Dockerfile
To speed up our workflow, here we cache the Ruby gems for the controller at the building container image time.
So, once the workflow is running, most of the Ruby gems are already cached.
No difference.
- No tests
No ports
> GH Validation: Cache Ruby gems for the controller inside the container image

- java/spacewalk-java.changes.mackdk.enforce-snakeyaml-version
- java/spacewalk-java.spec
This PR enforces the version of snakeyaml in the spec file. We are requiring version 1.33 since commit https://github.com/uyuni-project/uyuni/commit/f9fef7149d92c13918a7acc82f046b80c6881d34 that introduced the usage of `LoadOptions.setCodePointLimit()`
No difference.
Tracks https://github.com/SUSE/spacewalk/issues/22504 …
> Ensure correct snakeyaml version is required

- java/code/src/com/suse/manager/saltboot/PXEEvent.java
- java/code/src/com/suse/manager/saltboot/test/PXEEventTest.java
- java/spacewalk-java.changes.oholecek.pxe_event_branchid_fix
Backport of https://github.com/SUSE/spacewalk/pull/22746
When retail branch id is numeric only, json data in salt event are serialized to the Double instead of String and we need explicit conversion. This PR adds it.
No difference.
Fixes #
Tracks https://github.com/SUSE/spacewalk/pull/22746
If you need to …
> Fix conversion to string if branchid is numeric in PXEEvent

- .github/workflows/java-checkstyle.yml
- .github/workflows/sonarcloud.yml
The Java-checkstyle workflow run as unprivileged on the PR branch and upload the build results as artifacts.
When it succeeds the sonarcloud scan workflow uses those artifacts and run the scan on the target branch to avoid security issues and access the token. Using `workflow_run` as a trigger is the trick but that means the checkstyle workflow has to run on all PRs changing code even if there is no Java change.
Fixes https://github.com/SUSE/spacewalk/issues/22986 …
> Run sonarcloud scan as workflow_run

- branding/spacewalk-branding.changes.sbluhm.refactoring_srv
- branding/spacewalk-branding.spec
- java/build.xml
- java/spacewalk-java.changes.sbluhm.refactoring_srv
- java/spacewalk-java.spec
- python/spacewalk/spacewalk-backend.changes.sbluhm.refactoring_srv
- python/spacewalk/spacewalk-backend.spec
- spacewalk/certs-tools/rhn_bootstrap.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.sbluhm.refactoring_srv
- spacewalk/config/spacewalk-config.changes.sbluhm.refactoring_srv
- spacewalk/config/spacewalk-config.spec
- susemanager-branding-oss/susemanager-branding-oss.changes.sbluhm.refactoring_srv
- susemanager-branding-oss/susemanager-branding-oss.spec
- susemanager-utils/susemanager-sls/susemanager-sls.changes.sbluhm.refactoring_srv
- susemanager-utils/susemanager-sls/susemanager-sls.spec
- susemanager/susemanager.changes.sbluhm.refactoring_srv
- susemanager/susemanager.spec
- web/spacewalk-web.changes.sbluhm.refactoring_srv
- web/spacewalk-web.spec
1. Continues the activities for https://github.com/uyuni-project/uyuni/pull/7651 to align Enterprise Linux installations to the same destination.
2. Reverted some changes.
3. Renamed two variables in code to clarify their usage.
4. Fixed a regression in spacewalk-branding (folder permissions in spec file were different to other packages)
No difference.
Manually tested an EL9 install and waited for UI to come up.
Fixes #
If you don't …
> Followup to move all package files from /srv for Enterprise Linux compatibililty

- .github/workflows/java-checkstyle.yml
- .github/workflows/sonarcloud.yml
Running ant on the PR code in the sonarcloud job is dangerous: getting the java dependencies out of the existing artifact will do the trick.
> sonarcloud: get the java dependencies from the artifact

- .github/workflows/java-checkstyle.yml
- .github/workflows/sonarcloud.yml
On a push sonarcloud scanner would need to be called differently and the results would have to be checked in sonarcloud. For those reason the sonarcloud workflow is now disabled on pushes.
On pushes, we then don't need to run the java-checkstyle workflow on non java file changes.
> Limit the checkstyle and sonarcloud workflow runs on pushes

- testsuite/features/support/commonlib.rb
When attempting to get the system name for the virtualized VM, this creates an issue as it isn't an initalized twopence node. Adding the VM to the special cases should fix that.
Issue(s): https://github.com/SUSE/spacewalk/issues/21347
Ports(s): 4.3 https://github.com/SUSE/spacewalk/pull/23099 …
> QE: Fix system name for virtualization tests, as VM is not twopence node

- web/html/src/manager/minion/ansible/schedule-playbook.tsx
- web/spacewalk-web.changes.mikeletux.22929
Port of https://github.com/SUSE/spacewalk/pull/23026
Port of https://github.com/SUSE/spacewalk/pull/23026
- No docs needed
Issue(s): https://github.com/SUSE/spacewalk/issues/22929
> Bug 1216657 - Playbook name shown as `{name}` instead of actual name

- branding/spacewalk-branding.changes.mbussolotto.fix_branding_rpm
- branding/spacewalk-branding.spec
Fix spacewalk-branding rpm
I tried these changes here https://build.opensuse.org/package/show/home:mbussolotto:branches:systemsmanagement:Uyuni:Master/spacewalk-branding
No difference.
- No tests
> Fix spacewalk-branding rpm

- testsuite/features/support/commonlib.rb
This PR reverts the old way to manage the get_system_name for unknown hosts.
We tried an improvement, but it seems to don't work, so for now we will handle it using a rescue.
We can think a better code once we have the tests stable.
No difference.
Ports:
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/23102/ …
> Fix get_system_name for unknown systems

- branding/spacewalk-branding.spec
Removes the `tomcat` ownership from folder /usr/share/susemanager/www/htdocs
No difference.
Manual install tested on epel9-x86_64
Skipping changelogs, if that is OK. I think we have enough on this topic. …
> Remove spacewalk-branding conflict to spacewalk-html

- testsuite/features/build_validation/add_non_MU_repositories/centos7_minion_add_iso.feature
- testsuite/features/build_validation/add_non_MU_repositories/rocky8_minion_add_iso_and_build_clm.feature
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/support/file_management.rb
[spacewalk #20573](https://github.com/SUSE/spacewalk/issues/20573) Add SHA256 checksum verification when mounting images
[spacewalk #20900](https://github.com/SUSE/spacewalk/issues/20900) Fix mounting ISO step when using a mirror
No difference.
- Cucumber tests were fixed and edited
Ports:
- Manager 4.3
> QE: Fix ISO mounting step and add SHA256 checksum verification 

- testsuite/features/support/commonlib.rb
- testsuite/features/support/file_management.rb
Gathering all the files and directories related functions in `file_management.rb` , in order to keep  `commonlib.rb` tidy.
Includes some minor refactors to comply with Rubocop's rules.
No difference.
- No features or step definitions have been modified
Ports(s):  Manager 4.3
> QE: Move files related functions to their own Ruby file

- java/code/src/com/redhat/rhn/manager/satellite/SystemCommandThreadedExecutor.java
- java/code/src/com/redhat/rhn/taskomatic/task/RepoSyncTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/RhnJavaJob.java
- java/spacewalk-java.changes.cbosdo.reposync-log
Taskomatic external command line executor stores all the stdout and stderr into a String. Stdout can grow really big for reposync and we already have it in the reposync logs. Disabling the reposync stdout copy to gain some memory.
No difference.
- No tests: memory usage reduction
Fixes #
If you …
> Reposync fixes

- java/code/src/com/redhat/rhn/common/util/FileUtils.java
- java/code/src/com/redhat/rhn/frontend/action/audit/AuditSearchAction.java
- java/code/src/com/redhat/rhn/frontend/dto/AuditDto.java
- java/code/src/com/redhat/rhn/manager/audit/AuditManager.java
Fix https://sonarcloud.io/project/issues?open=AYsd0cnIhCuKbzRvZ3mK&id=uyuni-project_uyuni  as well as a few other sonarcloud reported issues in `AuditManager`.
No difference.
Fixes # …
> Fix a few Sonarcloud issues in AuditManager

- testsuite/run_sets/build_validation/build_validation_reposync.yml
- testsuite/run_sets/build_validation/build_validation_wait_for_product_reposync.yml
Move inside the reposync stage the disable the scheduled task for reposync.
Note: This need to be merged together with a removal of the rake task call inside the Jenkins Pipeline.
https://github.com/SUSE/susemanager-ci/pull/1037
No difference.
Ports(s): https://github.com/SUSE/spacewalk/pull/23118 …
> QE: Move the disable of Scheduled reposync task

- java/code/src/com/redhat/rhn/manager/action/ActionManager.java
- java/spacewalk-java.changes.mbussolotto.name_id
It might happens that a package changes architecture (e.g. from `x86_64` and `noarch`). In that case an upgrade off all the packages would try to install both packages, but this scenario it's not supported by salt (it's not possible to `pkg.install` packages with the same name in a single state).
This changes prevents this failure excluding packages with duplicated name and logging a warning.
Example:
**Now**
```
----------
ID: pkg_installed
Function: pkg.installed
Name: pkg_installed
Result: false
Comment: An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/state.py", line 2402, in call
*cdata["args"], **cdata["kwargs"]
File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
return …
```
> Prevent installation of packages with same name in a single action

- susemanager/bin/server-migrator.sh
There is a typo in the repo name when [migrating to a new OS version](https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/db-migration-xy.html):
`Update repository wiht updates from SUSE Linux Enterprise`
This was annoying me a bit, so here is the fix for that!
No difference.
Before:
After:
- No documentation needed: this only changes the displayname of one of the OS repos after a major upgrade
- No tests: didn't see that checked in any of the tests
I don't think this is worth a changelog entry.
> Fix typo in repo name in server-migrator script

- .github/workflows/acceptance_tests_secondary.yml
- .github/workflows/acceptance_tests_secondary_parallel.yml
GH-actions: run secondary tests more often to detect flaky tests
> GH-actions: run secondary tests more often to detect flaky tests

- java/code/src/com/redhat/rhn/domain/notification/NotificationMessage.java
- java/code/src/com/redhat/rhn/domain/notification/PaygNotCompliantWarning.java
- java/code/src/com/redhat/rhn/domain/notification/types/NotificationType.java
- java/code/src/com/redhat/rhn/domain/notification/types/PaygNotCompliantWarning.java
- java/code/src/com/redhat/rhn/frontend/action/YourRhnAction.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/template/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/taskomatic/task/DailySummary.java
- java/spacewalk-java.changes.mikeletux.warning-message-payg-non-compliant
- web/html/src/manager/notifications/notification-messages.tsx
- web/spacewalk-web.changes.mikeletux.23079
Port of https://github.com/SUSE/spacewalk/pull/23079
Port of https://github.com/SUSE/spacewalk/pull/23079
I think this doesn't need documentation as it is just a warning that's given to the user if it is not payg compliant.
No tests added since it's just some warning messages.
Issue(s): https://github.com/SUSE/spacewalk/issues/22382
Ports(s): [# **add downstream PR(s), if any**](https://github.com/SUSE/spacewalk/pull/23079) …
> PAYG better visible feedback when the server is not compliant

- java/code/src/com/redhat/rhn/manager/formula/FormulaManager.java
- java/code/src/com/redhat/rhn/manager/formula/test/dhcpd-formula-data.json
- java/code/src/com/redhat/rhn/manager/formula/test/dhcpd-formula-form.json
- java/spacewalk-java.changes.cbbayburt.bsc1216555
Formula validation checks lists against the first element of the default values in the definition. When the default has no elements, it throws an OOB exception.
This patch disables the check when the default is an empty list.
Port of: https://github.com/SUSE/spacewalk/pull/22920
Fixes https://github.com/SUSE/spacewalk/issues/22903 …
> Fix validation of lists with empty defaults in formulas (bsc#1216555)

- schema/spacewalk/susemanager-schema.changes.cbosdonnat.43-upgrade-fix
- schema/spacewalk/upgrade/susemanager-schema-4.4.1-to-susemanager-schema-4.4.2/003-system_checkin_threshold.sql
See title
- No tests: manual 4.3 migration tests
> DB upgrade fix from 4.3: rhnTaskQueue now has an id

- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/FilterApiController.java
- java/spacewalk-java.changes.cbbayburt.bsc1215949
When attaching filters to a CLM project, the Java method wrongly compares a "project-filter ID" to a "filter ID", which prevents some filters from being properly attached. This patch fixes the code to compare two "filter IDs" correctly.
> Fix filter ID comparison when attaching filters to a CLM project (bsc#1215949)

- testsuite/podman_runner/09_build_server_code.sh
50% of the time, downloading new jars from the open build service is failing. If the "ivy build" fails, try again a couple of times.
> CI: retry ivy build if it fails

- testsuite/features/step_definitions/salt_steps.rb
Partial revert of 1491df55f68
Missing linefeeds prevented venv-salt-minion from starting
We can make rubocop happy another time.
Edit: rubocop does not even seem to bother....
Ports:
* 4.3: not applicable
> Partial revert of 1491df55f68c

- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
We do build tests on SLE 15 SP4, even on Uyuni branch.
This `@susemanager` tag was probably left by mistake in the revert a1124059a5602476aa8074fcd0d1fc0644229fa2.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/23159
> We do build tests on SLE 15 SP4 even on Uyuni branch

- spacewalk/package/spacewalk.changes.oholecek.prjconf_based_postgres
- spacewalk/package/spacewalk.spec
- spacewalk/spacewalk-setup-postgresql/spacewalk-setup-postgresql.changes.oholecek.prjconf_based_postgres
- spacewalk/spacewalk-setup-postgresql/spacewalk-setup-postgresql.spec
- spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes.oholecek.prjconf_based_postgres
- spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.spec
This PR changes dependency handling of postgresql requires to be set by OBS/IBS project config instead of hardcoded in the spec file.
Project config for the projects should be modified like following:
```
Macros:
%postgresql_version 15
:Macros
```
depending on what version we want for given project.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23091 …
> Rely on obs prjconf to set wanted postgresql version

- spacewalk/certs-tools/spacewalk-certs-tools.spec
Removed duplicate spacewalk-push-register and spacewalk-ssh-push-init files in from spec. Seems they were initially listed twice so the duplicate was missed.
No difference.
- No tests: already covered by spec build.
Issue(s): #
Use change log from earlier commit …
> Removed duplicate spacewalk-push-register and spacewalk-ssh-push-init

- .github/PULL_REQUEST_TEMPLATE.md
This partially reverts commit c89a16dca78a2abd095c9228425659558ab79c61, as discussed at the retrospective.
No difference.
- No documentation needed: This is doc, somehow
- No tests: Doc
Issue(s): None
Ports(s): https://github.com/SUSE/spacewalk/pull/23163 …
> Partially revert "How to merge properly and small simplifications (#8009)

- testsuite/features/secondary/minkvm_guests.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/step_definitions/command_steps.rb
* use tftpboot package for SLES 15 SP4 even on Uyuni
* makes identical title for 2 scenarios differ
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/23177
> Install tftpboot for SLES 15 SP4 on all products

- spacewalk/package/spacewalk.changes.oholecek.minmax-pgsql-macros
- spacewalk/package/spacewalk.spec
- spacewalk/spacewalk-setup-postgresql/spacewalk-setup-postgresql.changes.oholecek.minmax-pgsql-macros
- spacewalk/spacewalk-setup-postgresql/spacewalk-setup-postgresql.spec
- spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.changes.oholecek.minmax-pgsql-macros
- spacewalk/uyuni-setup-reportdb/uyuni-setup-reportdb.spec
postgresql_version_min set the minimal required version
postgresql_version_max set the maximum allowed version (excluding set version)
if postgresql_version_min is not set, 14 is used
if postgresql_version_max is not set, 15 is used
No difference.
Before:
After:
Issue(s): #
If you …
> Make postgres version requirements to be installable

- java/code/src/com/redhat/rhn/frontend/xmlrpc/schedule/ScheduleHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/schedule/test/ScheduleHandlerTest.java
- java/code/src/com/redhat/rhn/manager/action/ActionManager.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/spacewalk-java.changes.mc.Manager-4.3-cancle-action-api-more-info
When cancel an action with pre-requisite actions failed, show in the error message the first action which can be canceld.
No difference.
Ports(s): https://github.com/SUSE/spacewalk/pull/23174 …
> Cancel action api more info

- client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes.sbluhm.removedist
- client/rhel/spacewalk-client-tools/src/up2date_client/up2dateErrors.py
Removed unused and deprecated/removed platform.dist import
It is deprecated and not being used. So might as well remove it.
(It will cause issues in future Python versions)
No difference.
Issue(s): # …
> Removed unused and deprecated/removed platform.dist import

- java/code/src/com/redhat/rhn/common/db/datasource/xml/ChannelReport_queries.xml
- java/code/src/com/redhat/rhn/common/db/datasource/xml/GeneralReport_queries.xml
- java/code/src/com/redhat/rhn/common/db/datasource/xml/ScapReport_queries.xml
- java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemReport_queries.xml
- java/code/src/com/redhat/rhn/taskomatic/task/ReportDBHelper.java
- java/code/src/com/redhat/rhn/taskomatic/task/ReportDbUpdateTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/ReportDbUpdateTaskTest.java
- java/spacewalk-java.changes.mackdk.improve-pagination-reportdb
This PR changes the way we execute the queries, using the FETCH FIRST approach and specifying a filter in the WHERE clause. With this approach each subsequent batch iteration will extract fewer rows hence perform better.
No difference.
Tracks https://github.com/SUSE/spacewalk/pull/23054
If you need to …
> Improved the paginated queries for syncing the reporting database

- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygUpdateHostsTask.java
- java/spacewalk-java.changes.mc.Manager-4.3-payg-connection-improvments
set only 1 IP for cloud rmt servers in /etc/hosts
No difference.
Ports(s): https://github.com/SUSE/spacewalk/pull/23140 …
> improve PAYG connection setup

- testsuite/features/step_definitions/common_steps.rb
Fixes https://github.com/SUSE/spacewalk/issues/22311
We have a step trying to confront the uptime displayed in the web UI with the one obtained from the host's /proc/uptime.
Right now, It expects the exact same value to be displayed but roundings, delays and a JS library get in the way resulting in a very flaky test.
We can probably afford to have some room for +/- 1 variations between the 2 counters, in some cases.
No difference.
- No documentation needed: "only internal and user invisible changes"
- One step used in the tests has been fixed
Issue card: https://github.com/SUSE/spacewalk/issues/22311 …
> QE: fix uptime validation test

- susemanager/bash-completion/Makefile
- susemanager/bash-completion/README.md
- susemanager/bash-completion/completions/_common.bash
- susemanager/bash-completion/completions/mgr-create-bootstrap-repo.bash
- susemanager/bash-completion/completions/mgr-sync.bash
- susemanager/bash-completion/completions/spacewalk-common-channels.bash
- susemanager/bash-completion/completions/spacewalk-remove-channel.bash
- susemanager/bash-completion/completions/spacewalk-repo-sync.bash
- susemanager/susemanager.changes.cbbayburt.bash-completion
- susemanager/susemanager.spec
Provide bash completion scripts for the following CLI tools:
- spacewalk-remove-channel
- spacewalk-common-channels
- mgr-sync
- mgr-create-bootstrap-repo
- spacewalk-repo-sync
> Bash completion for spacewalk tools

- java/code/src/com/suse/manager/webui/Router.java
- java/spacewalk-java.changes.cbbayburt.bsc1216754
- web/html/src/manager/errors/not-found.tsx
- web/spacewalk-web.changes.cbbayburt.bsc1216754
The `404.jade` template passes the request URLs directly to JS, which allows arbitrary code injection via request URLs. This patch encodes the URLs to safeguard against injections.
Port of: https://github.com/SUSE/spacewalk/pull/23010 …
> Sanitize request URLs for the 404 template (bsc#1216754)

- web/html/src/.eslintrc.js
- web/html/src/components/package/PackageListActionScheduler.tsx
- web/html/src/eslint-local-rules/index.js
- web/html/src/eslint-local-rules/intl-apostrophe-curly.js
- web/html/src/manager/admin/setup/products/products.tsx
- web/html/src/manager/images/image-view-overview.tsx
- web/html/src/manager/images/image-view.tsx
- web/html/src/manager/maintenance/edit/calendar-edit.tsx
- web/html/src/manager/state/highstate.tsx
Fixes the issue outlined in https://github.com/SUSE/spacewalk/pull/23026 in other similar places, also adds linting to detect it elsewhere.
No difference.
> Fix single apostrophe curly interpolation bug, add linting rule to detect it

- web/html/src/manager/audit/subscription-matching/subscription-matching-messages.tsx
- web/spacewalk-web.changes.mackdk.add-new-subscription-matcher-message
This PR adds the handling of the new message introduced by https://github.com/uyuni-project/subscription-matcher/pull/48
No difference.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/22893
Tracks https://github.com/SUSE/spacewalk/issues/22862 …
> Added new subscription-matcher message

- testsuite/features/support/constants.rb
We have duplicate modules in some products, including the default. So I removed the duplicate.
The containers also depend on basesystem being there so it takes forever and silently fails in the end (nothing in the reposync logs) so the module fails to be there if it's in the wrong order. I moved it almost at the end to be sure the right order is used. 
No difference.
Issue(s): no issue directly from testsuite review
Ports(s): 4.3: https://github.com/SUSE/spacewalk/pull/23210
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repositor …
> Remove duplicates and reorder containers module

- web/conf/rhn_web.conf
- web/spacewalk-web.changes.raul.update_rhnwebversion_check_migrationpaths
Bump version in web/conf/rhn_web.conf and add missing migration paths from both previous Uyuni and SUSE Manager
Bump version in web/conf/rhn_web.conf and add missing migration paths from both previous Uyuni and SUSE Manager
In web-ui, before logging in:
Before: 2023.10
After: 2023.12
Related to [#22851](https://github.com/SUSE/spacewalk/issues/22851) …
> Bump version in web/conf/rhn_web.conf and add missing migration paths

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/reposync/allcli_update_activationkeys.feature
- testsuite/features/reposync/reference_srv_check_reposync.feature
- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/allcli_software_channels_dependencies.feature
- testsuite/features/secondary/min_recurring_action.feature
- testsuite/features/secondary/proxy_as_pod_basic_tests.feature
- testsuite/features/support/constants.rb
This PR reverts commit "BV: We only need containers module on the POD Proxy VM".
Containers are needed on build host to test Docker.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/23234
Note: in the 4.3 port, I have left alone the additions to `proxy_as_pod_basic_tests.feature`.
> Revert PR 8042

- susemanager-utils/susemanager-sls/salt/packages/init.sls
- susemanager-utils/susemanager-sls/src/grains/public_cloud.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mc.Manager-4.3-improve-payg-detection
when instance-flavor-check tool gets installed, the grain is not directly updated as it is kind of static data.
Calling `util.syncgrains` should update them for the next call.
Ports(s): https://github.com/SUSE/spacewalk/pull/23154 …
> Improve payg detection

- java/code/src/com/redhat/rhn/domain/product/test/SUSEProductTestUtils.java
- java/code/src/com/suse/manager/matcher/MatcherJsonIO.java
- java/code/src/com/suse/manager/matcher/test/MatcherJsonIOTest.java
- java/spacewalk-java.changes.mc.subscription-matching-vcores-for-slemicro
MicroOS is counted by number of vCores when it is not used as hypervisor.
Provide total number of CPUs to the subscription matcher input in this case.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23212
Ports(s): https://github.com/SUSE/spacewalk/pull/23273 …
> provide total number of CPUs for SLE Micro systems

- java/code/src/com/suse/manager/metrics/PrometheusExporter.java
- java/code/src/com/suse/manager/metrics/ThreadPoolListCollector.java
- java/code/src/com/suse/manager/reactor/PGEventStream.java
- java/spacewalk-java.changes.mc.monitor-salt_queue
expose the data for the salt queue handling the salt return events
No difference.
- https://github.com/uyuni-project/uyuni-docs/pull/2693
Ports(s): https://github.com/SUSE/spacewalk/pull/23225 …
> monitor the salt queue handling the results

- web/html/src/manager/schedule-options/action-chain-picker.tsx
- web/spacewalk-web.changes.eth.select-interop
A regression in https://github.com/uyuni-project/uyuni/pull/7701 caused the initial value of the schedule picker not being set without interacting with the picker. This PR is a quick fix for it while I look into the underlying cause.
No difference.
- No tests: fixes Cucumber test
https://suse.slack.com/archives/C02DDMY6R0R/p1703001720936379
https://github.com/SUSE/spacewalk/issues/23243 …
> Fix missing action chain schedule initial value

- java/buildconf/test/rhn.conf.postgresql-example
- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/suse/manager/webui/controllers/MinionController.java
- java/code/src/com/suse/manager/webui/menu/MenuTree.java
- java/code/webapp/WEB-INF/nav/ssm.xml
- java/code/webapp/WEB-INF/nav/system_detail.xml
- java/code/webapp/WEB-INF/struts-config.xml
- java/conf/rhn_java.conf
- java/spacewalk-java.changes.parlt.remote-command-restriction
Port of https://github.com/SUSE/spacewalk/pull/23176
> Add option to disable remote commands from web UI

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml
- java/code/src/com/redhat/rhn/domain/rhnpackage/PackageBreaks.java
- java/code/src/com/redhat/rhn/domain/rhnpackage/PackageSupplements.java
- java/code/src/com/redhat/rhn/manager/rhnpackage/PackageManager.java
- java/spacewalk-java.changes.mc.Manager-4.3-fix-removing-deb-packages
When removing a debian package via API, some dependencies are not cleaned up before removing the main package.
This can lead into ClassCast exceptions.
No difference.
Ports(s): https://github.com/SUSE/spacewalk/pull/23246 …
> fix exception when removing a debian package (bsc#1216781)

- python/spacewalk/spacewalk-backend.changes.mackdk.credentials-hierarchy
- schema/spacewalk/susemanager-schema.changes.mackdk.credentials-hierarchy
- schema/spacewalk/upgrade/susemanager-schema-4.3.19-to-susemanager-schema-4.3.20/001-add-rhui-credential-type.sql
- schema/spacewalk/upgrade/susemanager-schema-4.3.7-to-susemanager-schema-4.3.8/300-payg-database-changes.sql
- schema/spacewalk/upgrade/susemanager-schema-4.3.9-to-susemanager-schema-4.3.10/002-add-suseUyuniServerInfo.sql
- schema/spacewalk/upgrade/susemanager-schema-4.4.6-to-susemanager-schema-4.4.7/001-add-rhui-credential-type.sql
- spacewalk/setup/spacewalk-setup.changes.mackdk.credentials-hierarchy
- susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes.mackdk.credentials-hierarchy
This PR fixes the sql scripts idempotency and adds the missing changelogs. 
Please note that the  fix is up to the database schema 4.3.0, if the idempotency test is started from an earlier version, it might still fail. Currently, our tooling is using 4.3.8 as starting point.
No difference.
- No tests: No code change
If you need to …
> Credentials hierarchy - Additional fixes

- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes.majchroo.fix-conflicting-uyuni-tools
Change NAME of multiple SLES15 for SAP channels to include "SAP" at the end.
This PR resolves a conflict caused by duplicated names for SLES15 and SLES15 for SAP.
This logic was applied based on current SLES12 and SLES12 for SAP.
1) Activate uyuni-client tools for **SLES**
```
spacewalk-common-channels sles15-sp5-uyuni-client
```
2) Activate uyuni-client tools for **SLES4SAP**
```
spacewalk-common-channels sles15-sap-sp5-uyuni-client
```
Both channels are active.
Error activating "second" channel
```
localhost:~ # spacewalk-common-channels sles15-sap-sp5-uyuni-client
INFO: sle-product-sles_sap15-sp5-pool-x86_64 exists
WARNING: sles15-sap-sp5-uyuni-client-x86_64: redstone.xmlrpc.XmlRpcFault: The channel name 'Uyuni Client Tools for SLES15 SP5 x86_64' is already in use, please enter a …
```
> Fix conflicting "name" for SLES15 and SLES15 for SAP uyuni client tools spacewalk-common-channel.

- spacecmd/spacecmd.changes.cbosdonnat.localhost-nossl
- spacecmd/src/bin/spacecmd
Getting the FQDN will provide useless results when running in the server container. In order to avoid hairpins and SSL trouble, use http://localhost to connect to the API by default in this case.
Issue(s): # …
> spacecmd: use localhost without ssl when running on the server

- containers/proxy-helm/proxy-helm.changes.cbosdonnat.traefik
- containers/proxy-helm/templates/ingress.yaml
- containers/proxy-helm/templates/k3s-ingress-routes.yaml
- containers/proxy-helm/values.yaml
For now the proxy installation on kubernetes required disabling traefik and using metallb for the network part. This commit adds the IngressRouteTCP, IngressRouteUDP and Ingress resources to use with traefik.
No difference.
- [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pull/2685)
- No tests: proxy tests will have to be changed later with the all-containers approach
Needed for PR https://github.com/uyuni-project/uyuni-tools/pull/96 …
> Proxy: add ingress routes and rules for traefik

- spacewalk/setup/bin/spacewalk-setup
Remove the left-over parenthesis remained by mistake after the query update. This fixes the issue when setting up the database.
No difference.
- No tests: setup script …
> Remove wrong parenthesis

- testsuite/features/secondary/srv_rename_hostname.feature
This PR changes the way to navigate to the KVM Host overview page. Instead of relying on the URL generated after obtaining the ID of that system through an API Call, we will navigate through web elements, interacting with the web.
We see this issue:
```
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) (Faraday::SSLError)
/usr/lib64/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
/usr/lib64/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/lib64/ruby/2.5.0/net/http.rb:985:in `connect'
/usr/lib64/ruby/2.5.0/net/http.rb:920:in `do_start'
/usr/lib64/ruby/2.5.0/net/http.rb:909:in `start'
/usr/lib64/ruby/gems/2.5.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:146:in `request_via_request_method' …
```
> QE: Workaround to navigate to the KVM Host, as the API call fails due to SSL issues

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/step_definitions/setup_steps.rb
- testsuite/features/support/env.rb
Backport : 
- https://github.com/SUSE/spacewalk/pull/22351/files
- https://github.com/SUSE/spacewalk/pull/22352/files
No difference. …
> backport BV stability improvement

- testsuite/features/build_validation/migration/min_salt_migration.feature
- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/constants.rb
- testsuite/features/support/env.rb
- testsuite/run_sets/build_validation/build_validation_migration.yml
- testsuite/run_sets/secondary.yml
The feature was previously using a nested VM, resulting in flaky tests. Now it relies on a dedicated SLES 15 SP5 minion.
Related to https://github.com/SUSE/spacewalk/issues/22410  - testsuite changes
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/22410
Manager 4.3 backport: https://github.com/SUSE/spacewalk/pull/23320 …
> QE: refactor min_salt_migration.feature and move it to BV

- testsuite/features/support/commonlib.rb
After the backport from manager43 to uyuni oif the BV stabilities changes, one function is missing.
Add it to uyuni
No difference.
Before:
After:
Check [How …
> Fix backport client type

- susemanager-utils/susemanager-sls/salt/certs/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.vzhestkov.fix-certs-include
There is no need to define and use distinct macro for just a simple task to include SLS.
So removing it.
No difference.
- No tests: no proper tests for this part, highstate apply will fail for the client if the state is wrong …
> Remove includesls macro definition and usage as not relevant

- testsuite/features/support/commonlib.rb
- testsuite/features/support/env.rb
Backport catch_timeout_message option to uyuni
No difference.
Before:
After:
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-pro …
> Add option to catch timeout

- containers/init-image/Dockerfile
- containers/init-image/init-image.changes.oholecek.disable-removeipc
SLE adds a specific systemd branding which sets `RemoveIPC=no` for logind. We don't have this in the container and result is postgres unable to communicate with clients manifesting by error:
```
FATAL:  could not open shared memory segment "/PostgreSQL.241200488": No such file or directory
```
This PR adds directive `RemoveIPC=no` and fixes above mentioned issue.
No difference.
Issue(s): # …
> Set RemoveIPC=no for logind to stop removing IPC mechanisms by systemd

- testsuite/features/support/commonlib.rb
Refactor the check_text_and_catch_request_timeout_popup? function to comply with Rubocop
No difference.
- A function used by the Cucumber testsuite has been edited
Backport - Manager 4.3: https://github.com/SUSE/spacewalk/pull/23340
> QE: refactor check_text_and_catch_request_timeout_popup?

- java/code/src/com/redhat/rhn/domain/credentials/PasswordBasedCredentials.java
- java/code/src/com/redhat/rhn/domain/credentials/test/CredentialsTest.java
- spacewalk/setup/bin/spacewalk-setup
- spacewalk/setup/spacewalk-setup.changes.mcalmer.Manager-4.3-fix-setting-scc-passwd
Seems that encode_base64() append a final newline at the end of the output which break setting the scc password in DB during setup.
Additionally we store the encoded password in the password column. This mapping was missing after the refactoring of the credentials classes.
The old code stored the password not encoded and when loading an encoded password it encoded it again and authentication failed.
No difference.
- already covered
- added unit test
Ports(s): https://github.com/SUSE/spacewalk/pull/23342
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-reposito …
> fix setting scc password during setup

- susemanager-utils/susemanager-sls/salt-ssh/preflight.sh
- susemanager-utils/susemanager-sls/susemanager-sls.changes.agraul.ssh-tunnel-add-selinux-policy
SSH Push in the "tunnel" flavor can conflict with SELinux policies shipped by operating systems. The default policies are not aware of the additional port we need for the tunnel.
The preflight.sh script is executed at the beginning of bootstrapping to download the Salt Bundle and allow Salt code execution. To allow for this download, a custom policy is written when SELinux is enabled and the system is managed via a tunnel. The policy is only written and loaded once.
No difference.
Issue(s): # …
> preflight.sh: Write SELinux policy if needed

- containers/init-image/Dockerfile
- containers/init-image/init-image.changes.oholecek.upstream-pgsql-user
Inspecting postgresql upstream container image I noticed they too create hardcoded UID and GIDs for postgres user, however they chose to use 999 [0]. This PR sync our values to theirs.
0: https://github.com/docker-library/postgres/blob/master/16/bookworm/Dockerfile#L13
No difference.
Issue(s): # …
> Use the same UID and GID for postgres as upstream does

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/reposync/reference_srv_sync_products_extra.feature
- testsuite/features/reposync/srv_sync_products.feature
When you enter the Products page of the Setup Wizard, you can have this:
Wait for this text to disappear.
**Note: it's only one of the 7 current errors in 4.3 BV!** (happens at Debian 12)
Ports:
* 4.3: SUSE/spacewalk#23346
> Wait for "A refresh of the product data..." is gone

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
Apparently, we added the containers channels to the list of channels to wait for (in `support/constants.rb`), but in the case of BV forgot to trigger the corresponding synchronization.
This resulted in a wait until timeout for the containers module.
Ports:
* 4.3: SUSE/spacewalk#23351
> Containers module needed for SLE 15 SP4 build host

- java/code/src/com/redhat/rhn/taskomatic/task/repomd/test/DebReleaseWriterTest.java
Fix java 17 related unit tests failures
> Don't test compressed files checksums in debian files

- java/buildconf/apidoc/jsp/handler.txt
- java/spacewalk-java.changes.mseidl.apidoc-link-fix
Fixes apidoc link to point to self instead of top.
https://bugzilla.suse.com/show_bug.cgi?id=1213507
#22448 
merged in 4.3
No difference.
Before:
After:
- No tests:
Issue(s): #
Check [How to …
> Fix apidoc link

- python/spacewalk/spacewalk-backend.changes.deneb-alpha.fix-wsgi-requires
- python/spacewalk/spacewalk-backend.spec
- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.changes.deneb-alpha.fix-wsgi-requires_tftpsync-recv
- tftpsync/susemanager-tftpsync-recv/susemanager-tftpsync-recv.spec
**Use the new apache2-mod_wsgi package name**
No difference.
- No tests: **no test added but built locally on OBS**
Tracks https://github.com/SUSE/spacewalk/issues/22574
> Use the new apache2-mod_wsgi package name

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/constants.rb
Some steps to wait for reposync seem to be missing.
Piggyback: augment timeout from 2 hours to 2 hours and a half because of debian 11.
Ports:
* 4.3: SUSE/spacewalk#23364
> Add channels to wait for

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
Reposyncs can take a lot of time. That means that the UI can time out and the user is brought back to the login page.
In latest BV I have 4 failures in steps like
```
And I enter "xxx" as the filtered product description
```
with failure
```
Unable to find css "input[name='product-description-filter']" (Capybara::ElementNotFound)
```
and with such a screenshot
This PR addresses the issue by making sure we are logged in before each UI-oriented scenario.
Ports:
* 4.3: SUSE/spacewalk#23366
> Re-login if needed

- .github/workflows/acceptance_tests_common.yml
- .github/workflows/acceptance_tests_secondary.yml
- .github/workflows/acceptance_tests_secondary_parallel.yml
Run the workflow for all PRs, but only run the scripts depending changed files
No difference.
- No tests
No ports
> GH Validation: Run the workflow for all PRs, but only run the scripts depending changed files

- schema/spacewalk/susemanager-schema.changes.nadvornik.schema-upgrade
- schema/spacewalk/upgrade/susemanager-schema-4.4.1-to-susemanager-schema-4.4.2/003-system_checkin_threshold.sql
The schema upgrade from 4.3 fails on this, because information_schema.columns is case sensitive.
```
susemanager=# SELECT 1 FROM information_schema.columns WHERE table_name = 'rhnTaskQueue' AND column_name = 'id';
?column? 
----------
(0 rows)
susemanager=# SELECT 1 FROM information_schema.columns WHERE table_name = 'rhntaskqueue' AND column_name = 'id';
?column? 
----------
1
(1 row)
```
No difference. …
> Fix schema upgrade

- java/spacewalk-java.changes.juliogonzalez.4.3-sync
- schema/spacewalk/susemanager-schema.changes.juliogonzalez.4.3-sync
- search-server/spacewalk-search/spacewalk-search.changes.juliogonzalez.4.3-sync
- susemanager-utils/susemanager-sls/susemanager-sls.changes
- susemanager/susemanager.changes
- susemanager/susemanager.changes.juliogonzalez.4.3-sync
- web/spacewalk-web.changes
- web/spacewalk-web.changes.juliogonzalez.4.3-sync
Add missing changelogs entries and bugzilla references from SUSE Manager 4.3, in preparation for 5.0
NOTE: `Changelogs / Test changelog entries (pull_request_target) Failing after 12s ` need to be ignored, as I really need to directly change "master" files, to add missing bscs.
No difference.
- No documentation needed: Changelogs
- No tests: Changelogs
Issue(s): https://github.com/SUSE/spacewalk/issues/23387 …
> Add missing changelogs entries and bugzilla references from SUSE Manager 4.3

- spacewalk/package/spacewalk.changes.juliogonzalez.remove-pxe-image-requirement
- spacewalk/package/spacewalk.spec
Remove pxe-default-image requirement from spacewalk-common when building on SLE, as PXE images are not provided anymore for SUSE Manager 5.0
No difference.
- Card: A card should be already created by @admd for the doc team. …
> Remove pxe-default-image requirement from spacewalk-common when building the package on SLE

- containers/hub-xmlrpc-api-image/Dockerfile
- containers/hub-xmlrpc-api-image/hub-xmlrpc-api.changes.cbosdonnat.versions-fix
- containers/init-image/Dockerfile
- containers/init-image/init-image.changes.cbosdonnat.versions-fix
- containers/proxy-httpd-image/Dockerfile
- containers/proxy-httpd-image/proxy-httpd-image.changes.cbosdonnat.versions-fix
- containers/proxy-salt-broker-image/Dockerfile
- containers/proxy-salt-broker-image/proxy-salt-broker-image.changes.cbosdonnat.versions-fix
- containers/proxy-squid-image/Dockerfile
- containers/proxy-squid-image/proxy-squid-image.changes.cbosdonnat.versions-fix
- containers/proxy-ssh-image/Dockerfile
- containers/proxy-ssh-image/proxy-ssh-image.changes.cbosdonnat.versions-fix
- containers/proxy-tftpd-image/Dockerfile
- containers/proxy-tftpd-image/proxy-tftpd-image.changes.cbosdonnat.versions-fix
- containers/server-image/Dockerfile
- containers/server-image/server-image.changes.cbosdonnat.versions-fix
- containers/server-migration-14-16-image/Dockerfile
- containers/server-migration-14-16-image/server-migration-14-16-image.changes.cbosdonnat.versions-fix
The reference label value needs to match the build tag and then contain the product version.
The ARG PRODUCT_VERSION is appended when pushing the image to OBS. …
> Fix the reference label in container images

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/constants.rb
This PR addresses the reposync for Retail in the Uyuni case.
According to Ondrej, the existing Uyuni channels contain all the Retail packages, so this PRs just adds two comments stating there is nothing to do.
Ports:
* 4.3: SUSE/spacewalk#23404
> Mention the missing sync for Retail in Uyuni

- web/spacewalk-web.changes.deneb-alpha.fix_spacewalk-html_license
- web/spacewalk-web.spec
Revert reordering of license tags for `spacewalk-html`. 
This is a follow-up of https://github.com/uyuni-project/uyuni/pull/8120 needed because the reordering of the license tag done by spec-cleaner is breaking the  `manager-Head-dev-javascript-lint` on the CI with
~~~
$ yarn -s check-package && NODE_OPTIONS="--trace-warnings --trace-deprecation --unhandled-rejections=strict" node build
WARN: Currently installed ace-builds version 1.3.3 only matches expected version ajaxorg/ace-builds#v1.3.3 when coerced
clean-webpack-plugin: /manager/web/html/src/dist has been removed.
(node:200) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after …
> Revert reordering of license tags for spacewalk-html

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/constants.rb
* add missing scenario for rocky9 under uyuni
* make package lists in constants match with the ones in feature
* fix waiting for RES 8
Ports:
* 4.3: SUSE/spacewalk#23422
> Missing reposync for rocky 9 on uyuni

- susemanager-branding-oss/susemanager-branding-oss.changes.juliogonzalez.branding-oss-susemanager-5.0
- susemanager-branding-oss/susemanager-branding-oss.spec
This package is not needed for Uyuni, so we keep it disabled.
It requires @deneb-alpha to fix product definitions for the upper case, and so they generate 5.0 release packages.
No difference.
- No documentation needed: There should be another card to do the doc for other architectures.
- No tests: We build the package and have monitor jobs for this. …
> Enable aarch64 builds for susemanager-branding-oss for SUSE Manager

- susemanager-utils/susemanager-sls/salt-ssh/preflight.sh
In Bash, the string to the right of the =~ operator is interpreted as a POSIX extended regular expression. A quoted expression is matched literally, therefore we can't quote the string on the right side.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23369
Old PR causing the issues: https://github.com/uyuni-project/uyuni/pull/8034
If you uncheck …
> preflight.sh: Fix REPO_PORT condition syntax

- susemanager-branding-oss/susemanager-branding-oss.changes.juliogonzalez.branding-non-eula
- susemanager-branding-oss/susemanager-branding-oss.spec
Temporary use a dummy EULA for SUSE Manager. For SUSE Manager Alpha1 and Alpha2 until we figure out how to handle it.
No difference.
- No documentation needed: Temporary workaround
- No tests: AFAIK no test checks the licenses …
> Temporary use a dummy EULA for SUSE Manager

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
Again, renaming products.
Ports:
* 4.3: SUSE/spacewalk#23442
> SCC renamed SLES ES 7 to SUSE Liberty Linux 7

- susemanager-branding-oss/susemanager-branding-oss.changes.juliogonzalez.master
- susemanager-branding-oss/susemanager-branding-oss.spec
Do not require SUSE-Manager-Server-release for susemanager-branding-oss
We only required it because of the EULA, as that package has it, but unfortunately we won't be able to depend on it, as `SUSE-Manager-Server-release` is a package for the host, and not for the containers.
`SUSE-Manager-Server-release` is generated in the SLE15SP5 based codestream, while other packages including `susemanager-branding-oss` are based in the SLE15SP6 codestream, and doesn't have visibility of this
We'll need to find a way of getting the EULA. Could be buildrequiring a skelcd package that has it.
Does not build for Uyuni neither on top of openSUSE or on top of SLE: https://build.opensuse.org/package/show/home:juliogonzalez:branches:systemsmanagement:Uyuni:Master/susemanager-branding-oss
Builds on top of …
> Do not require SUSE-Manager-Server-release for susemanager-branding-oss

- testsuite/features/step_definitions/command_steps.rb
According to the manpage/help of OpenSSL, there are only parameters with one dash and not 2. I am not sure why it manually works with 2 dashes but in the test suite it fails.
No difference.
Issue(s): #
Ports(s): # https://github.com/SUSE/spacewalk/pull/23451 …
> QE: Fix openSSL parameters in hostname rename test

- susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes.agraul.db-connection-helper-add-python-connections
- susemanager-utils/supportutils-plugin-susemanager/susemanager-connection-check.pl
Salt now selects pillar data from the DB, which needs a varying amount of DB connections based on the number of worker threads.
Reposync chooses the number of subprocesses based on the amount of CPU cores, the same calculation is now included in the calculation of required DB connections.
No difference.
- No tests: we don't have tests for supportconfig tools
Fixes # …
> Add Python DB connections to helper script

- testsuite/features/step_definitions/datepicker_steps.rb
Closes https://github.com/SUSE/spacewalk/issues/14266
Replace the JS call to `setScheduleTime()` with actual UI interactions.
No difference
- A step used in a Cucumber test was edited
Issue(s): https://github.com/SUSE/spacewalk/issues/14266
Ports(s): Manager 4.3 https://github.com/SUSE/spacewalk/pull/23368
> QE: replace a JS call with UI interaction

- testsuite/features/build_validation/migration/slemicro54_minion.feature
- testsuite/features/build_validation/migration/slemicro54_ssh_minion.feature
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/run_sets/build_validation/build_validation_migration.yml
Closes https://github.com/SUSE/spacewalk/issues/21745
Add to BV Cucumber features testing the Product Migration  functionality for a SLE micro 5.4 minion to SLE Micro 5.5
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/21745
Ports:  Manager 4.3 https://github.com/SUSE/spacewalk/pull/23361
> QE: BV - Add  features for SLE Micro product migration

- schema/spacewalk/common/data/rhnTaskoSchedule.sql
- schema/spacewalk/susemanager-schema.changes.mc.Manager-4.3-change-hwrefresh-schedule
- schema/spacewalk/upgrade/susemanager-schema-5.0.3-to-susemanager-schema-5.0.4/200-change-sys-profile-refresh-schedule.sql
change schedule of system-profile-refresh to run on the 2nd saturday
of a month to not collide with normal working times
No difference.
- No change needed
Ports(s): https://github.com/SUSE/spacewalk/pull/23378 …
> change schedule of system-profile-refresh

- susemanager-sync-data/additional_products.json
- susemanager-sync-data/susemanager-sync-data.changes.mc.oes-and-res-changes
- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.mc.Manager-4.3-oes-and-res-changes
- rename OES 2023-SP4 into OES23.4 in bootstrap data and repository descriptions
Ports(s): https://github.com/SUSE/spacewalk/pull/23331
> Oes and res changes

- java/code/src/com/redhat/rhn/common/db/datasource/xml/SystemReport_queries.xml
- java/code/src/com/redhat/rhn/taskomatic/task/ReportDbUpdateTask.java
Another improvement on top of #23054 which use the ById variant also for SystemPackageInstalled table.
No difference.
Ports(s): https://github.com/SUSE/spacewalk/pull/23325
Check [How to …
> use ById mechanism for SystemPackageInstalled report db table

- java/code/src/com/suse/manager/webui/controllers/bootstrap/AbstractMinionBootstrapper.java
- java/spacewalk-java.changes.mc.Manager-4.3-fix-known_hosts-test
We might have now an existing /var/lib/salt/.ssh directory, but no `known_hosts` file in it.
We cannot directly check for file exists as we do not have permissions to read the directory.
We need to ignore this error so we check for the message
No difference.
Ports(s): https://github.com/SUSE/spacewalk/pull/23438 …
> handle not existing known_host file in permission check

- susemanager/src/mgr_sync/config.py
- susemanager/src/mgr_sync/mgr_sync.py
- susemanager/susemanager.changes.cbosdo.https-tools-fix
- utils/spacewalk-common-channels
- utils/spacewalk-utils.changes.cbosdo.https-tools-fix
In some cases the http port seems not available for the XML-RPC API. Use `http://localhost:80` by default for those tools and https when using the server's FQDN.
Using `localhost` helps reducing the possible hairpins when running in a container environment.
No difference.
- No tests: tools defaults, partly covered by e2e tests
Fixes https://github.com/uyuni-project/uyuni/issues/5565 …
> Use https to access the API in spacewalk-common-channels and mgr-sync

- java/code/src/com/redhat/rhn/domain/channel/test/ChannelFamilyTest.java
- java/code/src/com/redhat/rhn/manager/setup/MirrorCredentialsManager.java
- java/code/src/com/redhat/rhn/manager/setup/SubscriptionDto.java
- java/code/src/com/redhat/rhn/manager/setup/test/MirrorCredentialsManagerTest.java
- java/code/src/com/suse/scc/model/SCCSubscriptionJson.java
- java/spacewalk-java.changes.mackdk.fix-npe-store-credentials
- susemanager-utils/testing/docker/scripts/init-pgsql-db4eclipse.sh
- susemanager-utils/testing/docker/scripts/init-pgsql-reportdb4eclipse.sh
This PR fixes a `NullPointerException` that happens when the user tries to create a new mirror credential using a username already associated with an existing credentials. Currently the code throws exception preventing the user to be notified about the error.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23459
Port(s): https://github.com/SUSE/spacewalk/pull/23474 …
> Fix NullPointerException when checking for duplicate credentials

- testsuite/features/support/commonlib.rb
Adds 5.0 to the product version method of the testsuite.
No difference.
- No tests
Issue(s): https://github.com/SUSE/spacewalk/issues/23081 …
> Testsuite: add 5.0 version in the product_version method

- containers/server-image/Dockerfile
- containers/server-image/motd
- containers/server-image/server-image.changes.cbosdonnat.shell-warning
To be very clear that entering a shell in a container may be dangerous, add a warning about the risk for interactive shells.
For sh shells we'll add `ENV=/etc/sh.shrc.local` in uyuni-tools. See https://github.com/uyuni-project/uyuni-tools/pull/133
Issue(s): https://github.com/SUSE/spacewalk/issues/23455 …
> Add a warning message for interactive shells

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/webapp/WEB-INF/pages/channel/manage/repo/repodetails.jsp
- java/spacewalk-java.changes.cbbayburt.bsc1217874
The help text for the "Filters" field in the custom repo details form is not descriptive/correct. This PR adds a proper explanation and a correct example.
Before:
After:
- No tests: static UI
Issue(s): https://github.com/SUSE/spacewalk/issues/23169
Check …
> Update help text for the custom repo filter field (bsc#1217874)

- testsuite/features/support/xmlrpc_client.rb
Closes https://github.com/SUSE/spacewalk/issues/23499
Read the card for a more in depth analysis.
Our testsuite expects a SystemCallError to be raised when an API call fails. At the moment, only the HTTP client does so.
This PR adds the same behavior to the XMLRPC client we have in our testsuite.
No difference.
- Files related to the Cucumber testsuite were modified
Issue(s):  https://github.com/SUSE/spacewalk/issues/23499
Ports(s): Manager 4.3 https://github.com/SUSE/spacewalk/pull/23505
Check [How …
> QE: return a SystemCallError on failing XMLRPC calls

- testsuite/features/step_definitions/datepicker_steps.rb
Title
Related to https://github.com/SUSE/spacewalk/issues/23506
No difference.
- A step used in the Cucumber testsuite has been fixed
Issue(s): https://github.com/SUSE/spacewalk/issues/23506
Ports(s): Manager 4.3
> QE: fix date-picker CSS selector

- java/conf/rhn_java.conf
- java/spacewalk-java.changes.mc.product_tree-tag-50
- java/spacewalk-java.spec
Prepare for the next SUSE Manager major version, set product_tree tag to Beta and change the config value to SUMA5.0
No difference.
@uyuni-project/qe This change will make the "Beta Client Tools Channels" visible in the Product Page. This needs to be handled in the testsuite.  …
> set product_tree tag to Beta and change the config value to SUMA5.0

- containers/server-image/Dockerfile
- containers/server-image/server-image.changes.cbosdonnat.gitfs
Add pygit2 for gitfs in server container
Issue(s): https://github.com/SUSE/spacewalk/issues/23397
> server: add missing dependencies to use gitfs in container

- testsuite/features/secondary/srv_scc_user_credentials.feature
- testsuite/features/step_definitions/setup_steps.rb
Credential editing was not being tested by the testsuite until now.
This additional scenario and the new step definition it depends on allow for testing of the credential-editing functionality, including behavior when entering an already existing name.
No difference.
Issue(s):
Ports(s):
If you need to …
> QE: Add testing for credential editing

- testsuite/features/step_definitions/command_steps.rb
There are issues when using only rum() where the command could potentially be executed inside a container instead of the host. With this change, we force the execution on the host.
`hotname -f` on our 5.0 does not return anything useful according to Cedric.
No difference.
Issue(s): # …
> QE: Force FQDN check to run locally on the host

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Task_queries.xml
- java/code/src/com/redhat/rhn/taskomatic/task/PackageCleanup.java
- java/code/src/com/redhat/rhn/taskomatic/task/TaskConstants.java
- java/spacewalk-java.changes.mc.change-org-for-orphen-vendor-packages-via-taskomatic
- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/spacewalk-backend.changes.mc.change-org-for-orphen-vendor-packages-via-taskomatic
- python/test/unit/spacewalk/satellite_tools/test_reposync.py
When vendor packages were removed from a repo, they become orphan but cannot be removed by an admin as long as they are not belong to an organization.
To solve this, a org change statement was added to reposync.
This had some side effects when a package moved from one repo to another as it become first orphan, change the org and when it appears in the new repo it does not match the org and is downloaded and created again.
This PR move the functionality to taskomatic and it should be executed only once per day.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/22944 
Ports(s): https://github.com/SUSE/spacewalk/pull/23334 …
> Change org for orphan vendor packages via taskomatic

- java/code/src/com/redhat/rhn/domain/recurringactions/RecurringActionFactory.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/manager/recurringactions/RecurringActionManager.java
- java/code/src/com/suse/manager/webui/controllers/RecurringActionController.java
- java/code/src/com/suse/manager/webui/utils/gson/RecurringActionScheduleJson.java
- java/code/src/com/suse/manager/webui/utils/gson/SimpleMinionJson.java
- java/spacewalk-java.changes.parlt.one-shot-action-execution
- web/html/src/components/states-picker.tsx
- web/html/src/manager/recurring/recurring-actions-edit.tsx
- web/spacewalk-web.changes.parlt.one-shot-action-execution
Add support for one shot action execution during create/edit of a recurring custom state schedule. If multiple systems are part of the entity a list that allows for selection of individual systems will be displayed.
After:
- No documentation needed: Small QoL change. Does not affect the functionality of the feature
- No tests: **small visual change.**
Issue(s): https://github.com/SUSE/spacewalk/issues/22484 …
> One shot action execution

- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
- java/spacewalk-java.changes.dottorblaster.get-relevant-errata-multiple-sids
Solves (at least I hope so) #8183.
Adds a new endpoint to the API that lets `getRelevantErrata` have a list of `sid`s as a parameter. 
No difference.
Before:
After:
- I hope I got it right!
Issue(s): #8183 
I still need to write an entry.
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-bran …
> Add getRelevantErrata endpoint that takes a list of sids

- testsuite/features/secondary/srv_cobbler_profile.feature
- testsuite/features/step_definitions/api_common.rb
- testsuite/features/support/namespaces/system.rb
Related to https://github.com/SUSE/spacewalk/issues/22651 - detailed info in the comments
Implement and add an API call to system.createSystemRecord using the SID and kickstart label
No difference.
- One Cucumber testsuite scenario and its step definition have been modified.
Issue(s): https://github.com/SUSE/spacewalk/issues/22651
Ports(s): Manager 4.3 https://github.com/SUSE/spacewalk/pull/23535
> QE: refactor and fix "Create and modify a System profile using the XML-RPC API" scenario

- .github/workflows/acceptance_tests_secondary.yml
- .github/workflows/acceptance_tests_secondary_parallel.yml
We need to differentiate secondary and secondary parallel to be able to set them as required.
Let's choose "acceptance tests" like name, that is more descriptive than just test-uyuni
> CI: fix test names

- testsuite/.rubocop_todo.yml
Do not choke on
```
features/support/constants.rb:670:18: C: Style/InlineComment: Avoid trailing inline comments.
'default' => # CHECKED
^^^^^^^^^
```
Port(s):
* 4.3:
> Allow comments on same line as code in constants.rb

- testsuite/features/step_definitions/api_common.rb
Pass the correct value  to a function executing an API call.
No difference.
- A Cucumber step definition was edited
Port(s):  Manager 4.3 https://github.com/SUSE/spacewalk/pull/23576
> QE: fix system.setVariables API call

- testsuite/features/support/constants.rb
Liberty 7 product has base channel name "RHEL x86_64 Server 7"
Piggyback: indentation a bit calmer...
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/23597
> Liberty 7 product has base channel name "RHEL x86_64 Server 7"

- spacewalk/admin/Makefile.admin
- spacewalk/admin/import-suma-build-keys
- spacewalk/admin/spacewalk-admin.changes.mc.import-suma-build-keys
- spacewalk/admin/spacewalk-admin.spec
- spacewalk/admin/uyuni-update-config
When running Uyuni in container the SUSE Manager Build Keys will not get imported into the RPM DB as the `%post` script of the RPM package will not get executed.
This PR add this task to the startup of the container which give us the possibility to have a clean keyring available in the containers.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23524 …
> import SUSE Manager Build Keys into the rpm keyring

- testsuite/features/step_definitions/command_steps.rb
In the containerized server, the permissions for the admin user of ReportDB are presented a bit differently, so I've fixed the regex to match that as well.
Fixes https://github.com/SUSE/spacewalk/issues/23507
Ports - 4.3 https://github.com/SUSE/spacewalk/pull/23604
Check [How to …
> QE: Change regex to extract permissions for ReportDB user

- .github/workflows/build_containers.yml
CI: update server container to latest release (2024.01)
No difference.
- No tests
https://github.com/SUSE/spacewalk/issues/23607
> CI: update server container to latest release (2024.01)

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- schema/spacewalk/common/data/suseInternalState.sql
- schema/spacewalk/susemanager-schema.changes.mcalmer.improve-uptodate
- schema/spacewalk/upgrade/susemanager-schema-5.0.4-to-susemanager-schema-5.0.5/100-add-internal-state-update-salt.sql
- susemanager-utils/susemanager-sls/salt/update-salt.sls
- susemanager-utils/susemanager-sls/salt/uptodate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.improve-uptodate
Implement some improvements to update systems via recurring states.
- provide a standalone salt update state
- improve update stack update state
- check pillar to skip reboot_if_needed if not wanted
No difference.
- Not needed, but added https://github.com/SUSE/spacewalk/issues/23573
Issue(s): https://github.com/SUSE/spacewalk/issues/22483
Ports(s): https://github.com/SUSE/spacewalk/pull/23577 …
> improve update systems via recurring states

- python/spacewalk/server/importlib/headerSource.py
- python/spacewalk/spacewalk-backend.changes.meaksh.Manager-4.3-bsc1219151
This PR fixes an issue that happens in "spacewalk-repo-sync" when trying to synchronize an RPM package that contains files with sizes higher than 4GB:
```console
2024/01/31 14:41:35 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '-c', 'res-as-8-debug-updates-x86_64', '--include', 'firefox-debuginfo']
2024/01/31 14:41:35 +02:00 Sync of channel started.
2024/01/31 14:41:41 +02:00 Repo URL: https://updates.suse.com/SUSE/Updates/RES-AS/8/debug/update/?<token>
2024/01/31 14:41:41 +02:00     Packages in repo:             23167
2024/01/31 14:41:41 +02:00     Packages passed filter rules:     1
2024/01/31 14:41:41 +02:00     Packages already synced:          0
2024/01/31 14:41:41 +02:00     Packages to sync:                 1
2024/01/31 14:41:41 +02:00     New packages to download:         1 …
```
> Fix issue in "spacewalk-repo-sync" when RPM packages contains files with size greater than 4GB (bsc#1219151)

- susemanager/bin/mgr-setup
- susemanager/susemanager.changes.cbosdonnat.no-motd
In a container the /etc/motd file is not persisted and defined in the container image, avoid writing this file in the setup.
> Don't change the /etc/motd at the end of the setup

- testsuite/features/support/twopence_init.rb
Otherwise, twopence gets the output of /etc/motd on every node.run
No difference.
- No tests
N/A
> Testsuite: remove /etc/motd contents from the server

- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/min_change_software_channel.feature
- testsuite/features/step_definitions/api_common.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/support/namespaces/channel.rb
Closes https://github.com/SUSE/spacewalk/issues/22908
Do not evaluate the number of enabled repositories and instead use an API call to retrieve the number of subscribed channels.
No difference.
- Step definitions used by some Cucumber tests were edited
Issue(s):  https://github.com/SUSE/spacewalk/issues/22908
Ports(s): Manager 4.3 https://github.com/SUSE/spacewalk/pull/23619
> QE: refactor verification of a system's subscribed channels

- java/code/src/com/suse/manager/api/HttpApiRegistry.java
- java/spacewalk-java.changes.cbosdonnat.api-auth-fix
Since there is no user, this API method has to be unauthenticated or it can't be called.
> Add org/createFirst to unauthenticated HTTP API paths

- susemanager-utils/susemanager-sls/salt/uptodate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mc.Manager-4.3-fix-reboot-detection
pkg.update calls `zypper update` which only look at package data and ignore flags set for the patch.
As we want to perform a full update, we can simply check if any patch require a reboot and use this as second opinion.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/23630
If you need to …
> Fix reboot needed detection

- susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.changes.mcalmer.update-supportplugin-functions
- susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.spec
- susemanager-utils/supportutils-plugin-susemanager-client/susemanagerclient
- susemanager-utils/supportutils-plugin-susemanager-client/susemanagerclient-scplugin
- susemanager-utils/supportutils-plugin-susemanager-proxy/supportutils-plugin-susemanager-proxy.changes.mcalmer.update-supportplugin-functions
- susemanager-utils/supportutils-plugin-susemanager-proxy/susemanagerproxy
- susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes.mcalmer.update-supportplugin-functions
- susemanager-utils/supportutils-plugin-susemanager/susemanager
With ALP only the new style supportconfig plugin resource file will be supported.
Time to migrate it.
It is available since SLE15 GA.
We can already use it when running Server and Proxy on SLE15.
Just for clients we need both versions as SLE12 and older support only the old style format
No difference.
Port(s): Not (yet) ported. Not need as 4.3 server and proxy will stay on SLE15 and client will switch to this version as soon as 5.0 gets released. Depends on when we want to start supporting SLE-Micro 6.0 …
> port to new supportconfig plugin resource file

- python/linting/lint.sh
- spacewalk/admin/spacewalk-admin.changes.mc.no-symlinks-in-saltfs
- spacewalk/admin/uyuni-update-config
- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.mc.Manager-4.3.11-no-symlinks-in-saltfs
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mc.Manager-4.3.11-no-symlinks-in-saltfs
- susemanager-utils/susemanager-sls/susemanager-sls.spec
Salt does not allow symlinks in the salt filesystem which point to the outside.
This means we need to change how we provide the CA certificate.
In the past we had a symlink. Now we need to put a copy to it.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/23633 …
> No symlinks in saltfs

- java/buildconf/LICENSE.txt
- java/spacewalk-java.changes.rjpmestre.license-copyright-year-update
This PR updates the regex license so it allows to use year 2024.
No difference.
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge- …
> Update license 2024 regex

- testsuite/features/build_validation/init_clients/monitoring_server.feature
This fixes the Grafana dashboard tests in our BV. Since we have a 5.0 BV now, we this product differentiation.
```bash
(...)
Scenario: Test Grafana dashboards of monitoring server            # features/build_validation/init_clients/monitoring_server.feature:88
This scenario ran at: 2024-02-08 10:52:07 +0100
When I visit the grafana dashboards of this "monitoring_server" # features/step_definitions/navigation_steps.rb:1191
And I wait until I do not see "Loading Grafana" text            # features/step_definitions/navigation_steps.rb:43
And I check radio button "View as list", if not checked         # features/step_definitions/common_steps.rb:215
Then I should see a "Apache2" text                              # features/step_definitions/navigation_steps.rb:589
And I should see a "PostgreSQL …
```
> QE: Fix Grafana dashboard scenario in BV tests

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
It looks like "No data" appears shortly and is then replaced by minion's data on the Grafana page.
This PR adds a wait for this to happen.
Port(s):
* 4.3:
> Wait until "No data" appears on Grafana page

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
Configuration files: give the confirmation page time to appear
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/23659
> Configuration files: give the confirmation page time to appear

- testsuite/features/step_definitions/command_steps.rb
Remove some step definitions which are no longer used in any of the feature files.
No difference.
- Cucumber step definitions were deleted
Port(s): # Manager 4.3 https://github.com/SUSE/spacewalk/pull/23661
> QE: remove unused step definitions

- testsuite/features/step_definitions/command_steps.rb
testsuite: fix configure tftpsync.sh path.
Issue(s): https://github.com/SUSE/spacewalk/issues/22625
> testsuite: fix configure-tftpsync.sh path

- web/conf/rhn_web.conf
- web/spacewalk-web.changes.deneb-alpha.webversion_bump
* **Bump the WebUI version to 5.0.0 Beta1**
* schema  and reportdb  migration paths are  ok. no need  to  create  the empty migration  paths
Before: 5.0.0 Alpha1
After: 5.0.0 Beta1
- No documentation needed: **Bump the WebUI version to 5.0.0 Beta1**
Issue(s): https://github.com/SUSE/spacewalk/issues/23495 …
> Bump the WebUI version to 5.0.0 Beta1

- testsuite/features/build_validation/retail/proxy_branch_network.feature
- testsuite/features/build_validation/retail/sle12sp5_buildhost_build_kiwi_image.feature
- testsuite/features/build_validation/retail/sle15sp4_buildhost_build_kiwi_image.feature
* wait for the retail network to stabilize after network formula
* wait for the OS build host entitlement to appear
For the first one we found no other solution than a fixed wait :disappointed: .
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/23668
> Wait for retail network and for build host entitlement

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.mc.add-debian12-bootstrap-data
Add missing Debian 12 bootstrap data for SUSE Manager
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/22665 (partial forward port) …
> add debian 12 bootstrap data

- containers/init-image/init-image.changes.cbosdonnat.image-arch
- rel-eng/container_push.sh
Since OBS doesn't interpret the placeholder in the FROM image, nor the %_arch variable from the spec file, we only use the architecture in the path of the images to release.
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-pr …
> Don't add architecture in the path for the init image on IBS

- testsuite/features/build_validation/retail/sle12sp5_terminal_deploy.feature
- testsuite/features/build_validation/retail/sle15sp4_terminal_deploy.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
Wait for the first event on Retail terminal. This because there is one more full minute needed after it to reformat the terminal, apply and verify the image, and we don't want it to eat the timeout.
Port(s):
* 4.3:
* https://github.com/SUSE/spacewalk/pull/23670
* https://github.com/SUSE/spacewalk/pull/23674
* https://github.com/SUSE/spacewalk/pull/23675
* https://github.com/SUSE/spacewalk/pull/23676
> Wait for first event on Retail terminal

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.mcalmer.Manager-4.3-MU-4.3.11-fix-ca-deploy-on-proxy
Fix regression introduced with the last bugfix (https://github.com/uyuni-project/uyuni/pull/8268).
On a proxy, the salt filesystem directory does not exists. No need to copy the CA to that place.
This prevent a "No such file or directory" error
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/23684 …
> skip deploying the CA into the salt dir on proxies

- testsuite/features/init_clients/proxy_register_as_minion_with_gui.feature
- testsuite/features/init_clients/proxy_register_as_minion_with_script.feature
- testsuite/features/reposync/allcli_update_activationkeys.feature
The name changed:
Uyuni/Uyuni Podman server CI:
We have more similar occurrences for this in `secondary`, but I would wait until they really show up as failure:
```cucumber
@uyuni
Scenario: Play with recommended and required child channels selection for a single system
Given I am on the Systems overview page of this "sle_minion"
When I follow "Software" in the content area
And I follow "Software Channels" in the content area
And I wait for child channels to appear
And I check radio button "(none, disable service)"
And I wait for child channels to appear
And I check radio button "openSUSE Leap 15.5 (x86_64)"
Then I should see the child channel "Uyuni Proxy Devel for openSUSE Leap 15.5 (x86_64) (Development)" "unselected" and "disabled"
Then I should see the child channel "openSUSE 15.5 non …
```
> QE: Fix proxy Uyuni client tools

- schema/reportdb/uyuni-reportdb-schema.changes.deneb-alpha.fix_reportdb_min_version
Add the missing migration path to 5.0.4 for the reportdb schema
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23495 …
> Add the missing migration path to 5.0.4 for the reportdb schema

- testsuite/features/build_validation/init_clients/slemicro51_minion.feature
- testsuite/features/build_validation/init_clients/slemicro51_ssh_minion.feature
- testsuite/features/build_validation/init_clients/slemicro52_minion.feature
- testsuite/features/build_validation/init_clients/slemicro52_ssh_minion.feature
- testsuite/features/build_validation/init_clients/slemicro53_minion.feature
- testsuite/features/build_validation/init_clients/slemicro53_ssh_minion.feature
- testsuite/features/build_validation/init_clients/slemicro54_minion.feature
- testsuite/features/build_validation/init_clients/slemicro54_ssh_minion.feature
- testsuite/features/build_validation/init_clients/slemicro55_minion.feature
- testsuite/features/build_validation/init_clients/slemicro55_ssh_minion.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
To fix the issue described at [Salt execution error being displayed when trying to bootstrap an SLE Micro minion through the UI](https://bugzilla.suse.com/show_bug.cgi?id=121814), following the bootstrapping process, automatic booting is disabled.
This change was implemented due to intermittent automatic reboots, which could occur before Salt could relay the results of applying the bootstrap salt state.
We'll need to reboot the SLE Micro 5.X minions via SSH in order to complete the bootstrap procedure.
Includes also Sumaform cleanup and closes https://github.com/SUSE/spacewalk/issues/23224
No difference.
- Cucumber Scenarios using a new step definition were added to substitute previous scenarios.
Port(s): Manager 4.3 …
> QE: sumaform cleanup and reboot  after bootstrap for SLE Micro 5.X minions

- .github/CODEOWNERS
- .github/workflows/acceptance_tests_common.yml
- .github/workflows/acceptance_tests_feedback.yml
- Exclude BV folder from GitHub PR test suite tests. Since we do not test any BV tests with the GitHub Actions PR tests, it makes no sense to wait for the regular test suite code to be tested when BV only code is modified.
- Add missing QE owned files to CODEOWNERS 
No difference.
- No tests are needed, only configuration is added.
Issue(s): # …
> QE: Remove Build Validation folder from PR tests

- testsuite/features/init_clients/proxy_register_as_minion_with_gui.feature
- testsuite/features/init_clients/proxy_register_as_minion_with_script.feature
- testsuite/features/reposync/allcli_update_activationkeys.feature
- testsuite/features/support/constants.rb
We want to test the devel packages in our CI, not the released stable ones.
Reverts https://github.com/uyuni-project/uyuni/pull/8304 Regression initially introduced with https://github.com/uyuni-project/uyuni/pull/8281.
The changes from https://github.com/uyuni-project/uyuni/pull/8326 are not needed anymore.
No difference.
Issue(s): # …
> QE: Fix Uyuni Proxy channel selection

- testsuite/features/build_validation/add_non_MU_repositories/centos7_minion_add_iso.feature
- testsuite/features/build_validation/add_non_MU_repositories/rocky8_minion_add_iso_and_build_clm.feature
- testsuite/features/build_validation/init_clients/ubuntu2204_minion.feature
- testsuite/features/build_validation/init_clients/ubuntu2204_ssh_minion.feature
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/support/file_management.rb
This fixes some of the current issues found in the 5.0 BV, like
- Add MU repos: wrong parent channel selection
- Add non MU repos: adapt our image mounting steps for the container, e.g. use `mgradm distro copy`, because we cannot mount anything inside the server container
- fix the proxy selection step for Ubuntu 22.04
No difference.
Issue(s): #
Ports(s): # https://github.com/SUSE/spacewalk/pull/23719
If you …
> QE: Adapt BV test suite for 5.0

- java/code/src/com/redhat/rhn/common/ExceptionMessage.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/suse/manager/webui/controllers/SystemsController.java
- java/code/src/com/suse/manager/webui/controllers/test/SystemsControllerTest.java
- java/code/src/com/suse/manager/webui/templates/systems/virtual-list.jade
- java/code/src/com/suse/utils/Predicates.java
- java/code/src/com/suse/utils/test/PredicatesTest.java
- java/spacewalk-java.changes.rjpmestre.fix-virtual-systems-filters
- web/html/src/manager/systems/list-filter.tsx
- web/html/src/manager/systems/virtual-list.renderer.tsx
- web/html/src/manager/systems/virtual-list.tsx
- web/spacewalk-web.changes.rjpmestre.fix-virtual-systems-filters
This PR fixes virtual system listing and enhances its filtering system. It adds a new dropdown input field. This will allow users to select either "Virtual Host" or "Virtual System" as the target for their query.
Before:
After:
- No documentation needed: There is a GUI difference but the granularity its not high enough to cover these filters.
Issue(s): https://github.com/SUSE/spacewalk/issues/21192 …
> fix virtual systems listing filters

- susemanager-sync-data/additional_products.json
- susemanager-sync-data/channel_families.json
- susemanager-sync-data/susemanager-sync-data.changes.mackdk.fix-oes-internal-name
This PR fixes the identifier for OES 23.4 due to the change of internal name from Open_Enterprise_Server to OES.
No difference.
- No tests: change in configuration files
Issue(s): https://github.com/SUSE/spacewalk/issues/23444
Port(s): https://github.com/SUSE/spacewalk/pull/23582 …
> Fix OES 23.4 internal name

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/manager/profile/ProfileManager.java
- java/scripts/spelling/ignored_en.txt
- java/spacewalk-java.changes.pinvernizzi.frontend-typo-fix
Fix a typo appearing in the "Deploy Files" page when trying to deploy configuration files.
Co**m**firm -> Confirm
After: Same with  "Confirm" in the displayed  text
- No tests: minor change in UI
Port(s):  Manager 4.3 https://github.com/SUSE/spacewalk/pull/23660
> Fix typo in 'Deploy Files' page

- testsuite/features/support/constants.rb
This PR fixes constants `CHANNEL_TO_SYNC_BY_OS_PRODUCT_VERSION` and `TIMEOUT_BY_CHANNEL_NAME` based on experimental data from a test suite run on the uyuni BV test suite.
Note: in `srv_sync_all-products` we must use these arrays in all cases, not only for SLES. @szachovy will take care of that, see SUSE/spacewalk#23395.
Issue(s): SUSE/spacewalk#23572
Port(s):
* 4.3: SUSE/spacewalk#23772
> Fix lists of channels to sync - Uyuni

- testsuite/features/secondary/srv_errata_api.feature
- testsuite/features/step_definitions/api_common.rb
- testsuite/features/support/http_client.rb
- testsuite/features/support/namespaces/system.rb
- testsuite/run_sets/secondary_parallelizable.yml
Closes https://github.com/SUSE/spacewalk/issues/23534
Adds namespaces and testsuite support for  the system.getRelevantErrata API calls/endpoints and features to test them.
No difference.
- Cucumber tests and files were added and edited
Issue(s): https://github.com/SUSE/spacewalk/issues/23534
Port(s): Manager 4.3 https://github.com/SUSE/spacewalk/pull/23773
> QE: add systems errata API testing feature

- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/support/constants.rb
Still more fixes after reposync refactoring in October:
* fix wrong channel name for client tools in Uyuni
* we don't reposync a "fake" product, only individual channels
* add 2 more missing timeouts
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/23780
> More reposync timeout fixes

- java/code/src/com/suse/manager/reactor/PGEventStream.java
- java/spacewalk-java.changes.rmateus.m43-pgeventlistener-error-handling
Port of: https://github.com/SUSE/spacewalk/pull/23645
When we are processing an event action, like RegisterMinionEventMessageAction, an exception can happen (minion not exist, for example). The action execution on the PGEventListener, when an exception happens, will look for an exception handler for this particular action. In the case of minion registration action, it has a custom exception handler, which sends some notifications.
The PGEventStream calls the process event and passes an exception handler, that deals with event removal from the database, and calls the custom exception handler for the error.
The problem happens when the custom exception handler also throws an exception, forcing the rollback of the event removal from database. This happened on the "TransactionHelper" -> …
> Commit salt event removal in case of process failure (bsc#1218931)

- testsuite/features/step_definitions/command_steps.rb
Test for an empty list of channels remaining to wait for _after_ we reduced their list
Also changed a bit the error messages.
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/23795
> Have one less iteration in waits

- susemanager-utils/susemanager-sls/salt/bootstrap/remove_traditional_stack.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.vanda.vb-rm-disabled-repos-from-trad-migration-sls
Removes the mention to `disabled repos` on the traditional client to salt migration
No difference.
- Documentation being taken care of on the context of https://github.com/SUSE/spacewalk/issues/22391
- Cucumber tests being added on the context of https://github.com/SUSE/spacewalk/issues/22391
Ports:
- 4.3 …
> Remove disabled repos from salt to avoid issues on traditional to salt migration

- java/code/src/com/suse/scc/registration/SCCSystemRegistrationSystemDataAcquisitor.java
- java/code/src/com/suse/scc/test/registration/SCCSystemRegistrationSystemDataAcquisitorTest.java
- java/spacewalk-java.changes.rjpmestre.fix-memory-size-extraction-virtual-instances
This PR fixes the memory size extraction in virtual instances (while registering in scc).
The problem was the initial assumption that this value would not be nullable.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23649 …
> fix memory size extraction in virtual instances

- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.welder.bsc1218146
Backport 23680 from Manager-4.3: Remove automatic reboot from transactional systems bootstrap
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23248 
Port(s): https://github.com/SUSE/spacewalk/pull/23680 …
> Backport 23680 from Manager-4.3: Remove automatic reboot from transactional systems bootstrap

- .github/workflows/python-checkstyle.yml
As per https://github.com/uyuni-project/uyuni/pull/8100, we linted files only in 4 directories: `python`, `spacewalk`, `susemanager` and `susemanager-utils`. This PR modifies the workflow such that it only runs checks on files in those directories. 
Tested before squashing commits into one.
No difference.
Issue(s): # …
> Feat: Provide Python path matching in GH flow 

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.mcalmer.bootstrap-repos-2024
- utils/spacewalk-common-channels.ini
- utils/spacewalk-utils.changes.mcalmer.bootstrap-repos-2024
- added SLE15 SP6  to bootstrap data
- added Uyuni Client Tools Channels to spacewalk-common-channels.ini
- add also openSUSE Leap 15.6 and its uyuni client tools
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23476
Port(s): https://github.com/SUSE/spacewalk/pull/23814
If you need to …
> add bootstrap repository definition for SLE15 SP6

- java/code/src/com/redhat/rhn/frontend/xmlrpc/HandlerFactory.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/admin/configuration/AdminConfigurationHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/admin/configuration/test/AdminConfigurationHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/admin/configuration/test/config1.yaml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/admin/configuration/test/minimal.yaml
- java/code/src/com/suse/manager/webui/services/iface/SaltApi.java
- java/code/src/com/suse/manager/webui/services/impl/SaltService.java
- java/code/src/com/suse/manager/webui/services/impl/runner/MgrUtilRunner.java
- java/code/src/com/suse/manager/webui/services/test/TestSaltApi.java
- java/spacewalk-java.changes.nadvornik.uyuni_config
- susemanager-utils/susemanager-sls/modules/runners/mgrutil.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.nadvornik.uyuni_config
This PR implements API call equivalent to Uyuni configuration formula.
All the logic is handled in java,  except for salt minion id matching, which is implemented
via salt runner call.
No difference.
- TBD
https://github.com/SUSE/spacewalk/issues/22499
Check …
> Replace Uyuni configuration formula with an API call

- web/html/src/package.json
- web/html/src/yarn.lock
- web/spacewalk-web.changes.eth.json5
json5 is not a dependency we use directly, but a lot of our build tooling relies on it. This PR pins it to a specific resolution to resolve a number of Dependabot issues.
No difference.
Part of https://github.com/SUSE/spacewalk/issues/22581 …
> Upgrade json5

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
This will remove the old cloud tests for SLES 15 SP2 and SP3 and align the code with what we already have in 4.3. See https://github.com/SUSE/spacewalk/pull/23592.
`contsants.rb` do not need to be adjusted, the entries are not present there.
No difference.
Issue(s): #
Ports(s): # not needed. The change is already present in 4.3 …
> QE: Remove old cloud tests in BV

- testsuite/features/secondary/srv_restart_postgres.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/run_sets/secondary.yml
This test restarts postgres service and verifies, that it is handled correctly in java and salt - applying highstate must work.
This should catch the bugs discussed in  https://github.com/SUSE/spacewalk/issues/20143
> Testsuite: test restart of postgres

- .github/workflows/python-checkstyle.yml
Previously, the Python workflow matched any paths that contained the strings `python`, `spacewalk`, or `susemanager`. The intention was to match only paths that begin with the string, which is now fixed in the regular expression.
No difference.
Before:
After:
- No documentation needed: **a workflow change**
- No tests: **a workflow change**
Issue(s): #
If …
> Match only beginning of path in Python workflow

- testsuite/features/core/srv_first_settings.feature
Since mgradm install now enforces the first user creation, this step needs to be skipped in the CI.
Related to https://github.com/uyuni-project/uyuni-tools/pull/192
Issue(s): https://github.com/SUSE/spacewalk/issues/23337 …
> CI: skip first user creation for container

- testsuite/features/build_validation/init_clients/proxy_container.feature
- testsuite/features/build_validation/init_clients/proxy_traditional.feature
- testsuite/features/build_validation/retail/sle12sp5_buildhost_build_kiwi_image.feature
- testsuite/features/build_validation/retail/sle15sp4_buildhost_build_kiwi_image.feature
- testsuite/features/core/srv_first_settings.feature
- testsuite/features/init_clients/proxy_branch_network.feature
- testsuite/features/init_clients/proxy_container.feature
- testsuite/features/init_clients/proxy_traditional.feature
- testsuite/features/secondary/allcli_system_group.feature
- testsuite/features/secondary/min_baremetal_discovery.feature
- testsuite/features/secondary/min_bootstrap_script.feature
- testsuite/features/secondary/min_salt_formulas.feature
- testsuite/features/secondary/min_ssh_tunnel.feature
- testsuite/features/secondary/proxy_cobbler_pxeboot.feature
- testsuite/features/secondary/proxy_retail_pxeboot_and_mass_import.feature
- testsuite/features/secondary/srv_monitoring.feature
- testsuite/features/secondary/srv_rename_hostname.feature
- testsuite/features/secondary/srv_restart.feature
- testsuite/features/secondary/srv_user_configuration_salt_states.feature
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/env.rb
- testsuite/features/support/file_management.rb
This PR
- renames the 2 variables used for the GitHub validation and the container runtime
- uses the correct one in the ISO mounting steps that failed in the 5.0 BV because of that before
See https://github.com/SUSE/spacewalk/issues/23705
No difference.
Issue(s): #
Ports(s): # No port needed 
If you need …
> QE: Fix variables for GitHub and container runtime

- testsuite/features/support/constants.rb
Apparently the labels for Rocky 9 and Ubuntu 22.04 and 20.04 have changed, according to https://github.com/SUSE/spacewalk/issues/23705#issuecomment-1981078586. This only touches the labels for SUMA, **not** Uyuni.
These regressions were introduced with
- https://github.com/uyuni-project/uyuni/pull/8367 
- https://github.com/SUSE/spacewalk/pull/23788
```bash
uyuni-server:/tmp # mgr-create-bootstrap-repo
1. RES7-x86_64
2. RHEL8-x86_64
3. SLE-12-SP5-x86_64
4. SLE-15-SP1-x86_64
5. SLE-15-SP2-x86_64
6. SLE-15-SP3-x86_64
7. SLE-15-SP4-x86_64
8. SLE-15-SP5-s390x
9. SLE-15-SP5-x86_64
10. SLE-ES8-x86_64
11. SLE-MICRO-5.1-x86_64
12. SLE-MICRO-5.2-x86_64
13. SLE-MICRO-5.3-x86_64
14. SLE-MICRO-5.4-x86_64
15. SLE-MICRO-5.5-x86_64
16. SUSE-LibertyLinux9-x86_64
17. almalinux-9-x86_64
18. debian11-amd64 …
```
> QE: Fix Rocky 9 and Ubuntu channel label for SUMA in the BV

- web/html/src/components/input/Radio.module.css
- web/html/src/components/picker/recurring-event-picker.module.css
- web/html/src/manager/admin/config/monitoring-admin.module.css
- web/html/src/manager/content-management/shared/components/panels/build/build-version.module.css
- web/html/src/manager/content-management/shared/components/panels/filters-project/filters-project.module.css
- web/html/src/manager/content-management/shared/components/panels/sources/channels/channels-selection.module.css
- web/html/src/manager/content-management/shared/components/panels/sources/sources.module.css
- web/html/src/manager/login/susemanager/login.module.less
- web/html/src/manager/virtualization/guests/console/guests-console.module.css
- web/spacewalk-web.changes.eth.comma-power
I fat fingered the last rebase in the style scoping PR, this PR makes the selectors for the old and new theme separate as they should be.  
Note to self, this issue might also be present in the stashed branch with the Sass update.
Fixes login page and other affected pages where styles are broken.
- No tests: CSS …
> Fix incorrectly scoped styles

- .github/labeler.yml
- .github/workflows/labeler.yml
This PR
-  bumps the version of our labeler GitHub action to v5 and adapts the `labeler.yml` file to the new configuration file structure. See 
- https://github.com/actions/labeler#breaking-changes-in-v5
- https://github.com/actions/labeler#basic-examples
- ~`pull_request_target` is temporarily change to `pull_request`, and will be reverted once all checks have passed. See https://github.com/actions/labeler#notes-regarding-pull_request_target-event~ commit deleted
-  ~tmp change in one of our Ruby files to check the labeler~ commit deleted
No difference.
Issue(s): #
Ports(s): # …
> Update GitHub labeler action from v4 to v5

- testsuite/features/build_validation/init_clients/proxy_container.feature
- testsuite/features/init_clients/proxy_container.feature
We included a reboot after bootstrapping the Proxy Host, as we considered we were operating under a transactional-server image (SLE or Leap Micro), but in fact, in our test environment we still deploying a SLES/Leap system. Therefore, we don't need to reboot just after the bootstrap.
Note: We will keep the scenario commented, as very soon, we will make a change in our infra and start using a SLE/Leap Micro image for the Proxy Host
No difference.
- Cucumber tests were disabled
No ports …
> QE: Don't reboot after bootstrapping the Proxy Host, as we don't use yet a transactional-server image

- testsuite/features/build_validation/init_clients/proxy_container.feature
- testsuite/features/init_clients/proxy_container.feature
- testsuite/features/step_definitions/command_steps.rb
This PR refactors the step definition to include the Avahi hosts into the Uyuni Podman args.
Before, it was made through the configuration of a systemd service, but that has been changed with the new Proxy version, now we pass it through an environment variable `UYUNI_PODMAN_ARGS`.
Although, we can also pass it through the configuration file like:
```
podman:
args:
- --add-host=...
- --add-host=...
```
And we also have the possibility to pass it using an argument, `mgrpxy install podman` has a `--podman-arg` argument.
If any, add Avahi hosts into the containerized proxy configuration
No difference.
Related to https://github.com/SUSE/spacewalk/issues/23517
No ports …
> QE: If any, add Avahi hosts into the containerized proxy configuration

- .github/workflows/python-checkstyle.yml
When a PR only modifies python files outside of the directories specified in the linting workflow, the Python linting check should pass, not fail.
> Fix: skip Python workflow check when no files matched

- testsuite/features/init_clients/proxy_branch_network.feature
Extend current workaround against `dhcp-server` package issues to `named` package
Also cleanup a few leftovers in tagging.
Port(s):
* 4.3: SUSE/spacewalk#23909
> Work around problem with bind package

- testsuite/features/build_validation/core/srv_first_settings.feature
- testsuite/features/core/srv_first_settings.feature
> Since mgradm install now enforces the first user creation, this step needs to be skipped in the CI.
Same as https://github.com/uyuni-project/uyuni/pull/8402 but for BV. 
No difference.
Issue(s): #
Ports(s): # not needed …
> QE: Skip first user creation in BV for container

- testsuite/features/step_definitions/command_steps.rb
On CI, if a channel is not synchronized in the expected time, raise an error, so we identify on time the root cause, instead of having it hidden and cascaded in other test cases.
But in BV, let's keep the behavior untouched and let's keep running the pipeline.
No difference.
Ports:
- Manager-4.3 …
> QE: On CI, if a channel is not synchronized in the expected time, raise an error

- python/spacewalk/server/importlib/suseProductsImport.py
- python/spacewalk/spacewalk-backend.changes.mc.Manager-4.3
While ISSv1, columns with NULL data are sometimes say "None" and that is inserted as string to the DB.
This convert 'None' to NULL during import.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/23942 …
> Fix issv1 scc data import

- web/html/src/branding/css/base/theme.less
- web/html/src/branding/css/base/theme.scss
- web/spacewalk-web.changes.eth.master
The latest round of UI updates broke pages that have very wide content such as logs. This fix addresses that immediate problem, we can simplify the core layout itself after we've finished the Bootstrap upgrade.
Before:
After:
- No tests: stylesheets
Issue(s): https://bugzilla.suse.com/show_bug.cgi?id=1220343 …
> Fix layout on wide content areas

- testsuite/features/secondary/srv_cobbler_distro.feature
- testsuite/features/step_definitions/cobbler_steps.rb
Attempt to fix https://github.com/SUSE/spacewalk/issues/19184
With this suggestion: https://github.com/SUSE/spacewalk/issues/19184#issuecomment-1920802458
No difference.
Ports:
- Manager-4.3 …
> QE: Fix the ks param used in Cobbler

- testsuite/features/support/constants.rb
It looks like an error of mine in commit 6b1dc87
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/23962
> Do not sync RBS for proxy product

- containers/server-image/Dockerfile
- containers/server-image/server-image.changes.mc.drop-vhm-kubernetes
SUMA should not connect to Kubernetes. Let's drop the Kubernetes module from the image.
No difference.
- https://github.com/SUSE/spacewalk/issues/23946
- No tests: **no tests for dropped features**
Issue(s): https://github.com/SUSE/spacewalk/issues/23907 …
> remove virtual-host-gatherer-Kubernetes module

- java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
- java/spacewalk-java.changes.cbosdonnat.proxy-register-fix
When first generating the container proxy configuration and then bootstrapping the host, two systems are showing up the list. This merges the two into a minion.
The downside is that the systemid file added to the configuration is no longer valid as is contains the OS and OS release which are set with the registration.
- No documentation needed: May be we need to document that the configuration needs to be generated again, unless we find a way to overcome this issue.
Issue(s): https://github.com/SUSE/spacewalk/issues/23800 …
> Merge minion with foreign proxy

- python/spacewalk/satellite_tools/repo_plugins/deb_src.py
- python/spacewalk/spacewalk-backend.changes.agraul.strip-whitespace-deb-pkg-metadata
Strip whitespace from debian package metadata
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/23981 …
> Strip whitespace from .deb package metadata (bsc#1214387)

- java/code/src/com/redhat/rhn/domain/scc/SCCCachingFactory.java
- java/code/src/com/redhat/rhn/domain/scc/test/SCCCachingFactoryTest.java
The `refreshNeeded()` test is a bit unstable. This try to make the test more stable
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/23973 …
> stabilize refresh test

- java/code/src/com/redhat/rhn/frontend/dto/PackageDto.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/PackageDtoSerializer.java
- java/code/src/com/redhat/rhn/manager/content/ubuntu/UbuntuErrataManager.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/PrimaryXmlWriter.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/RepomdWriter.java
- java/spacewalk-java.changes.mc.Manager-4.3-fix-ubuntu-errata-epoch-matching
Our package DTOs report NULL epoch as a single whitespace.
Additionally we need to check epoch anyway different as NULL == "" == 0.
This PR trim the whitespace from epoch and simplify other places dealing with it.
Additionally it introduce a special equal function for epoch values in UbuntuErrataManager.
No difference.
Issue(s): https://github.com/uyuni-project/uyuni/issues/8134
Port(s): https://github.com/SUSE/spacewalk/pull/23970 …
> fix matching epoch while creating ubuntu erratas

- containers/server-image/uyuni-configfiles-sync
This PR makes RPM scriptlets executed by `uyuni-configfiles-sync` to simulate a package upgrade to not trigger service restart in order to prevent getting stuck while trying to restart service during startup, even before the actual service should start.
On an stuck scenario, we see this, where apparently `/usr/bin/systemctl try-restart postfix.service` is stuck:
```
root      2707  0.0  0.3  26784 15332 ?        Ss   13:11   0:00 /usr/bin/python3 /usr/sbin/uyuni-update-config
root      2716  0.0  0.1   9708  4088 ?        S    13:11   0:00  \_ /bin/bash /usr/bin/uyuni-configfiles-sync sync
root      6974  0.0  0.0   9336  3472 ?        S    13:12   0:00      \_ sh -s -- 1
root      6997  0.0  0.0   9336  2008 ?        S    13:12   0:00          \_ sh -s -- 1
root      6998  0.0  0.1 …
```
> uyuni-configfiles-sync: prevent RPM scriptlets to restart services during startup

- susemanager-utils/susemanager-sls/src/modules/kiwi_info.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.oholecek.add_squash_fs
Our kiwi build inspection was missing squashfs output format. This PR adds recognition of it.
No difference.
- No tests: integration tests cover for regressions, no unit tests are present
Fixes https://github.com/SUSE/spacewalk/issues/22772
Tracks https://github.com/SUSE/spacewalk/pull/22743 …
> Recognize squashfs build results from kiwi

- susemanager-utils/susemanager-sls/src/modules/reboot_info.py
- susemanager-utils/susemanager-sls/src/tests/test_module_reboot_info.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mc.fix-reboot-required-detection
When detecting if a reboot is needed on a SUSE system, check only on SLES11 for the `do_purge_kernels` file.
Since SLES 12 we have `reboot-needed` and this should be used exclusivly.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23984
Port(s): https://github.com/SUSE/spacewalk/pull/23986 …
> distinguish between different SUSE versions when detecting if a reboot is needed

- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/spacewalk-java.changes.mc.Manager-4.3-reschedule-ssh-actions-after-reboot
When a state.apply contains a reboot and the minion is managed via salt-ssh using an unprivileged user, ssh return
` System is going down. Unprivileged users are not permitted to log in anymore. ...`
This cause a problem when a package list refresh should happen after a system update.
This PR detect this case and reschedule the action 3 Minutes later, by reducing the "remaining tries" counter.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/23980
If you don't …
> reschedule failed ssh actions caused by a connection error due to a scheduled reboot

- java/code/src/com/redhat/rhn/domain/product/SUSEProductSet.java
- java/code/src/com/suse/scc/client/SCCWebClient.java
- java/code/src/com/suse/scc/registration/SCCSystemRegistrationContext.java
- java/code/src/com/suse/scc/registration/SCCSystemRegistrationCreateUpdateSystems.java
- java/code/src/com/suse/scc/registration/SCCSystemRegistrationSystemDataAcquisitor.java
- java/code/src/com/suse/scc/registration/SCCSystemRegistrationUpdateCachedItems.java
- java/code/src/com/suse/scc/test/registration/AbstractSCCSystemRegistrationTest.java
- java/code/src/com/suse/scc/test/registration/SCCSystemRegistrationCreateUpdateSystemsTest.java
- java/code/src/com/suse/scc/test/registration/SCCSystemRegistrationSystemDataAcquisitorTest.java
- java/code/src/com/suse/scc/test/registration/SCCSystemRegistrationUpdateCachedItemsTest.java
- java/spacewalk-java.changes.rjpmestre.bsc1219634.bsc1221182
Both login and password are required by SCC for system registration. However, only the 'login' field is relevant for matching previously registered systems next to SCC. This commit removes the reliance on the 'password' field as an identifier for SCC register cached items.
No difference.
- No tests: already covered (updated)
Issue(s): https://github.com/SUSE/spacewalk/issues/23649 …
> drop system password as identifier on scc system registration

- testsuite/features/support/commonlib.rb
- testsuite/features/support/constants.rb
Fixing two possible issues which make uyuni reference server not setup correctly.
- We have empty Debian style channels. So the Packages file can be empty.
- We have an inconsistent naming in spacewalk-common-channels where we have no "dot" in the name, but when we create the channel in Uyuni, we have the "dot".
No difference.
- Cucumber tests adapted …
> Reference server mirror fix

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
We got errors about strings marked for translation, but they do not exist.
Port(s): https://github.com/SUSE/spacewalk/pull/24000
> add missing strings for translation

- containers/proxy-httpd-image/proxy-httpd-image.changes.oholecek.fix_logging_error
- containers/proxy-httpd-image/uyuni-configure.py
- containers/proxy-tftpd-image/proxy-tftpd-image.changes.oholecek.tftp_use_localhost_and_http
- containers/proxy-tftpd-image/tftp_wrapper.py
To prevent hairpin problems and also because we are by default running in pod with other containers, we want to connect to the localhost instead of FQDN.
With localhost we use http.
PR includes black linting of the file.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23966
If you need to …
> Tftp container: Use localhost and http by default

- testsuite/Rakefile
- testsuite/features/build_validation/init_clients/proxy_container.feature
- testsuite/features/build_validation/init_clients/proxy_traditional.feature
- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/constants.rb
- testsuite/run_sets/build_validation/build_validation_init_proxy.yml
This PR
1. a)  adapts the Rakefile for the two proxy variants (containerized, traditional) introduced with https://github.com/uyuni-project/uyuni/pull/8352.
```bash
[2024-03-12T13:35:18.790Z] + ./terracumber-cli --outputdir /home/jenkins/workspace/manager-5.0-qe-build-validation-NUE/results --tf susemanager-ci/terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf --gitfolder /home/jenkins/workspace/manager-5.0-qe-build-validation-NUE/results/sumaform --parallelism 60 --logfile /home/jenkins/workspace/manager-5.0-qe-build-validation-NUE/results/60/testsuite.log --runstep cucumber --cucumber-cmd 'export BUILD_NUMBER=60; export BUILD_VALIDATION=true; export CAPYBARA_TIMEOUT=60; export DEFAULT_TIMEOUT=500;  cd /root/spacewalk/testsuite; rake …
```
> QE: Adapt Uyuni/5.0 BV for the containerized proxy

- rel-eng/container_push.sh
The first tag is the only one that podman load will load for RPM contained images. In order to know which image is installed we need the one with the version first.
> Move latest as the latest buildtag in pushed containers

- spacewalk/admin/salt-secrets-config.py
- spacewalk/admin/spacewalk-admin.changes.agraul.use-java-hostname-uyuni-roster
- susemanager-utils/susemanager-sls/salt-ssh/preflight.sh
Follow up of https://github.com/uyuni-project/uyuni/pull/8462: also use `java.hostname` to generate `uyuni_roster_config` 
No difference.
This bug was discovered via https://ci.suse.de/view/Manager/view/Manager-Test/job/manager-TEST-Hexagon-acceptance-tests/1257/testReport/, ssh-push-tunnel failed because of the wrong hostname.
Issue(s): # …
> Update `uyuni_roster_config` generation (`cobbler.host` -> `java.hostname`)

- testsuite/Rakefile
Fixes a global variable in the Rakefile introduced in https://github.com/uyuni-project/uyuni/pull/8451
```bash
[2024-03-25T09:14:26.706Z] + ./terracumber-cli --outputdir /home/jenkins/workspace/manager-5.0-qe-build-validation-NUE/results --tf susemanager-ci/terracumber_config/tf_files/SUSEManager-5.0-build-validation-NUE.tf --gitfolder /home/jenkins/workspace/manager-5.0-qe-build-validation-NUE/results/sumaform --parallelism 30 --logfile /home/jenkins/workspace/manager-5.0-qe-build-validation-NUE/results/73/testsuite.log --runstep cucumber --cucumber-cmd 'export BUILD_NUMBER=73; export BUILD_VALIDATION=true; export CAPYBARA_TIMEOUT=60; export DEFAULT_TIMEOUT=500;  cd /root/spacewalk/testsuite; rake jenkins:generate_rake_files_build_validation'
[2024-03-25T09:14:27.267Z] Running command... …
```
> QE: Fix global variabel in Rakefile

- testsuite/Rakefile
Rake is not able to interact with our test framework, so we need to define the needed variable in the Rakefile itself.
No difference.
Issue(s): # …
> QE: Define var for container detection in Rakefile

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/constants.rb
This will adapt reposync in BV for SUMA to sync the correct channels for the containerized proxy (Proxy Extension 5.0 and RBS Extension 5.0). The old channels for 4.3 are deleted.
No difference.
Issue(s): # …
> QE: Add proxy and RBS extensions 5.0 to BV

- susemanager-utils/susemanager-sls/src/modules/kiwi_info.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.oholecek.add_squash_fs
Bundle builds create`.tar.xz` files as well for other file formats, so we need to come up with different matching method.
No difference.
- No documentation needed: revert
- No tests: revert, caught by integration tests
Issue(s): #
Check …
> Revert tbz images support because it clash with bundle builds.

- java/code/webapp/WEB-INF/pages/yourrhn.jsp
- java/spacewalk-java.changes.eth.subscription-warning
The diff view is not very good for this PR. In short, this PR simply moves the subscription warning element into a row of its own so if it isn't visible, it doesn't break the rest of the layout into a new line. Since it's full width anyway, it would need to have a row of its own in any case.
Before:
After:
- No documentation needed: I stepped on this as a part of the Bootstrap upgrade and there is already a docs ticket to upgrade screenshots for this. …
> Update landing page layouts
