uyuni-project/uyuni

- susemanager-utils/susemanager-sls/salt/switch_to_bundle/mgr_switch_to_venv_minion.sls
- susemanager-utils/susemanager-sls/salt/util/mgr_switch_to_venv_minion.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.agraul.bundle-migration-all
- testsuite/features/build_validation/migration/salt_migration_minion_migration.feature
Open the classic salt-minion.rpm -> Salt Bundle migration to all Salt versions (not just 3000).
No difference.
Need to check if we document which versions will get migrated. We need to document that all minions will get turned into venv-salt-minion automatically to prevent confusion.
- API documentation added: please review the Wiki page …
> Enable automatic bundle migration for all minions

- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataExtractor.java
increase payg response timeout to 20 seconds.
No difference.
- No tests
Issue(s): #https://github.com/SUSE/spacewalk/issues/23992
> increase payg response timeout to 20 seconds

- containers/proxy-helm/proxy-helm.changes.cbosdo.helm-label
- containers/proxy-helm/templates/deployment.yaml
- containers/server-helm/server-helm.changes.cbosdo.helm-label
- containers/server-helm/templates/deployment.yaml
Add the same app label on the deployment than on the pods. This will make it easier to search for the server and proxy deployments.
No difference.
- No documentation needed:  mostly used for internal purpose
- No tests: helm charts changes
Issue(s): # …
> Add app labels on the kubernetes deployments

- testsuite/features/step_definitions/navigation_steps.rb
I was too prompt in replacing those steps with `data-testid` ones. Adding them back.
Issue(s): #
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properl …
> Add again the steps checking textareas without data-testid

- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_uyuni/config.xml
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_uyuni/config.xml
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_uyuni/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_uyuni/config.xml
This PR adds "hostname" to the Kiwi OS image profile.
This utility is needed on the retail terminal for the bootstrap test after mass import.
No ports: profiles are shared between all branches.
> Make sure "hostname" package is available

- java/code/src/com/redhat/rhn/domain/action/ActionChainFactory.java
- java/code/src/com/redhat/rhn/domain/action/test/ActionChainFactoryTest.java
- java/code/src/com/redhat/rhn/frontend/action/schedule/InProgressSystemsAction.java
- java/code/src/com/redhat/rhn/taskomatic/TaskoFactory.java
- java/code/src/com/redhat/rhn/taskomatic/TaskoXmlRpcHandler.java
- java/code/src/com/redhat/rhn/taskomatic/TaskomaticApi.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/spacewalk-java.changes.mc.Manager-4.3-fix-unschedule-action-chains
When unscheduling an action which is part of an action chain, the action chain becomes visible again.
But when you try to schedule it again, it fails as the "action chain executor" job label was not removed.
When we schedule an action chain, we do not create "minion-action-executor-" tasko schedules like for single actions.
We create one "minion-action-chain-executor-" for the chain.
The actions are created, but not scheduled.
When unscheduling now the actions, we need to check if they belong to an action chain and unschedule the action chain when it is the last action which gets removed now.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24018
Make sure the changelogs entries you …
> Fix unschedule action chains

- java/code/src/com/redhat/rhn/frontend/xmlrpc/proxy/ProxyHandler.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
Collections.emptyList() is private and can no longer be accessed at runtime when serializing to Json. List.of() doesn't have this problem.
No difference.
- No tests: covered by cucumber tests
Issue(s): # …
> Fix Java 17 upgrade issue with container proxy configuration generation

- .github/CODEOWNERS
Move ownership of `web/conf/rhn_web.conf` to @uyuni-project/release-engineering as the config is edited more often by this group
No difference.
- No tests: this is just a GH config
Issue(s): # …
> Move ownership of web/conf/rhn_web.conf to release-engineering

- containers/server-attestation-image/Dockerfile
- containers/server-attestation-image/server-attestation-image.changes.mackdk.coco-fix-arch
- microservices/coco-attestation/uyuni-coco-attestation.spec
This PR ensures the package for the snpguest attestation module is not built if the architecture is not `x86_86`, since the tool `snpguest` would not be available. It also change the way the container is built: the architecture specific module is only added to the image if the container is of the correct architecture. This requires changing the Project Config in OBS by adding the following snippet:
```
%if "%_repository" == "containers"
%ifarch x86_64
BuildFlags: dockerarg:ARCH_SPECIFIC_MODULES=uyuni-coco-attestation-module-snpguest
%endif
%endif
```
No difference.
- No documentation needed: the change only affects packaging
- No tests: the change only affects packaging …
> Coco fix arch

- susemanager-utils/susemanager-sls/susemanager-sls.changes.deneb-alpha.fix_release_reference
- susemanager-utils/susemanager-sls/susemanager-sls.spec
Autobuild team asked to not force a `Release: 1` in the spec file but instead, they asked to keep `Release: 0` letting OBS to automatically handle the release change.
@sbluhm reported that this switch is unfortunately breaking the build of some sources where the hardcoded `Release: 1` value was used for downloading also additional sources like for example rpmlint filters. spec files we are doing from `Release: 1` to `Release: 0`.
~The PR switches the affected  URL to use the %{release} macro instead of hardcoding it's value.~
Using the %{release} macro doesn't work for building in Copr. The PR is switching the  URL from `1` to `0`
No difference.
- No tests: only internal spec file change
- NONE …
> Do not hardcode release version in the source URL

- testsuite/features/step_definitions/common_steps.rb
Don't use `--server` parameter of `rhnpush` as it triggers the hairpin problem.
Issue(s): https://github.com/SUSE/spacewalk/issues/21384
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/24064
Bug: https://bugzilla.suse.com/show_bug.cgi?id=1222325
> Avoid hairpin problem with rhnpush

- testsuite/features/build_validation/retail/sle12sp5_buildhost_build_kiwi_image.feature
- testsuite/features/build_validation/retail/sle15sp4_buildhost_build_kiwi_image.feature
- testsuite/features/init_clients/buildhost_bootstrap.feature
- testsuite/features/step_definitions/setup_steps.rb
Build Host entitlement adds some extra minutes to apply the salt high-state.
So we need to wait some more minutes until the onboarding is completed. 
No difference.
Ports:
- Manager-4.3 …
> QE: Build Host entitlement adds some extra minutes to apply the salt high-state

- testsuite/features/support/commonlib.rb
Wait 10s to obtain a result from the searchByName API method
No difference.
Ports:
- Manager-4.3
> Wait 10s to obtain a result from the searchByName API method

- testsuite/features/init_clients/proxy_container.feature
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/support/commonlib.rb
This PR 
- adds a Salt (`salt-minion`, `venv-salt-minion`) cleanup for the containerized proxy. Furthermore, in case of SLE Micro, `salt-minion` could be installed alongside `venv-salt-minion`, so we also remove it, if it is installed.
- onboards the containerized proxy as regular Minion again
- fixes the `slemicro_host` method, which did not work for e.g. a SLE Micro proxy because we only checked for the minion name
I ran the cleanup command manually on the proxy, and we need to reboot it after the cleanup.
```bash
dominik-ctl:~/spacewalk/testsuite # cucumber features/init_clients/proxy_container.feature
(...)
@containerized_server @scope_containerized_proxy @proxy
Feature: Setup containerized proxy
In order to use a containerized proxy with the server
As the system administrator
I want …
```
> QE: Add and improve cleanup for the containerized proxy

- testsuite/features/init_clients/proxy_container.feature
This PR skips again the scenarios to bootstrap and assure the onboarding of the Proxy Host.
For now, we have an issue after onboarding, as it takes too much time to retrieve the system from the system.searchByName API endpoint.
As consequence of this issue, the generated proxy configuration doesn't match with the Proxy Host systemId, and the proxy container fails authentication to the server.
**Bug**: https://bugzilla.suse.com/show_bug.cgi?id=1222628
**Slack thread**: https://suse.slack.com/archives/C02CLB6AGJ3/p1712742621440079
No difference.
- Cucumber tests were skipped
No ports. …
> QE: Skip proxy host onboarding

- testsuite/features/step_definitions/setup_steps.rb
Fix typo in step definition to check if we still onboarding
No difference.
Ports:
- Manager-4.3
> QE: Fix typo in step definition to check if onboarding

- containers/server-attestation-image/Dockerfile
- containers/server-attestation-image/server-attestation-image.changes.deneb-alpha.remove_not_needed_arg_server-attestation-image
Remove hardcoded ARG PRODUCT_VERSION and let the container push script control it.
Tested via:
* https://build.suse.de/projects/home:deneb_alpha:branches:Devel:Galaxy:Manager:Head_BETA2/packages/server-attestation-image/files/Dockerfile?expand=1
* https://build.opensuse.org/projects/home:deneb_alpha:branches:systemsmanagement:Uyuni:Master_2024_03/packages/server-attestation-image/files/Dockerfile?expand=1
No difference.
- No tests: **only Dockerfile argument change**
Related: https://github.com/SUSE/spacewalk/issues/23611 https://github.com/SUSE/spacewalk/issues/24034 …
> Remove hardcoded ARG PRODUCT_VERSION and let the container push script control it

- testsuite/features/reposync/srv_sync_products.feature
We need to specify the arch in the key for Leap. It diverge from the rest of key names, because we manage several architectures in the map.
In the future, we should align the naming of these keys, appending the arch to all of them.
Note: It only affects Uyuni, not SUMA.
No difference.
Ports:
- Mangaer-4.3 …
> Fix: Wrong key for a list of channels

- java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartHelper.java
- java/spacewalk-java.changes.cbosdo.migration_fix
`cobbler.host` is now set to `localhost` and should not be used to get the real server's FQDN.
No difference.
Issue(s): #
Check [How to …
> Use java.hostname to compute the FQDN for system provisioning

- java/code/src/com/redhat/rhn/frontend/action/common/DownloadFile.java
- java/spacewalk-java.changes.cbosdo.ks-fix
Getting the first item of an array without checking the array length in the first place is not a good idea. I wonder how that hasn't been an issue since 2009.
No difference.
- No tests: trivial
Issue(s): # …
> Fix OutOfBoundsException when downloading file from /ks/dist/

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.mc.fix-bootstrap-of-res-with-zypper-installed
- susemanager-utils/susemanager-sls/salt-ssh/preflight.sh
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mc.fix-bootstrap-of-res-with-zypper-installed
On a Liberty system it could happen that `zypper` is installed together with dnf or yum.
On Liberty 7 this cause problems as zypper is preferred over yum and with this the wrong bootstrap repo URL is generated.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24069 …
> Fix bootstrap of res with zypper installed

- susemanager/bin/mgr-setup
- susemanager/susemanager.changes.mc.container-open-db-for-internal-network
The main database should be accessible from the internal network when running in container.
This is needed when other containers connected to the same network need to work with the DB.
No difference.
Issue: https://github.com/SUSE/spacewalk/issues/23556 …
> in containers open the main database for the internal network

- testsuite/features/step_definitions/api_common.rb
This PR is a simplification.
We were making sure we did not add same custom channel twice, first for the traditional client, and then for the salt minion.
This is not needed anymore in head branch.
None, Uyuni only! We still need this code in 4.3.
> Remove leftover from traditional clients

- .github/workflows/python-checkstyle.yml
- python/README.md
- python/linting/lint.sh
In this PR, I:
- Migrate the container image from my fork to the `systemsmanagement` build
- Modify `lint.sh` so that the local container image is always up to date before execution
relates to fails in https://github.com/uyuni-project/uyuni/pull/8421
> Keep Python linting container up to date

- testsuite/features/reposync/allcli_update_activationkeys.feature
This fixes the activation key update of the proxy for Uyuni.
```bash
(...)
Feature: Update activation keys
In order to register systems to the spacewalk server
As admin
I want to update activation keys to use synchronized base products
Scenario: Log in as admin user                  # features/dom.feature:7
This scenario ran at: 2024-04-18 10:59:47 +0200
Given I am authorized for the "Admin" section # features/step_definitions/navigation_steps.rb:400
This scenario took: 13 seconds
Scenario: Update the openSUSE Leap Micro 5.5 Proxy Host key with synced base product   # features/dom.feature:10
This scenario ran at: 2024-04-18 11:00:00 +0200
When I follow the left menu "Systems > Activation Keys"                              # features/step_definitions/navigation_steps.rb:338
And I follow …
```
> QE: Fix proxy activation key

- web/spacewalk-web-rpmlintrc
- web/spacewalk-web.changes.raul.fix_lint_errors
- web/spacewalk-web.spec
Backports https://github.com/SUSE/spacewalk/pull/24083
No difference.
Issue(s): Partially fixes https://github.com/SUSE/spacewalk/issues/20836
Port(s): https://github.com/SUSE/spacewalk/pull/24083 …
> Backport: Add filters for rpmlint in package spacewalk-web (#24083)

- susemanager-utils/susemanager-sls/src/modules/kiwi_info.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.oholecek.add_squashfs
Kiwi creates .tar.xz for both PXE images and tbz images. However with PXE we are not interested in this result.
No difference.
- No tests: regressions covered by integration tests
Issue(s): https://github.com/SUSE/spacewalk/issues/24011 …
> Differentiate between PXE images and others like tbz

- java/buildconf/build-props.xml
- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
- java/code/src/com/redhat/rhn/common/util/FileUtils.java
- java/code/src/com/redhat/rhn/common/util/download/DownloadUtils.java
- java/code/src/com/redhat/rhn/common/util/test/FileUtilsTest.java
- java/code/src/com/redhat/rhn/domain/kickstart/KickstartFactory.java
- java/code/src/com/redhat/rhn/domain/kickstart/KickstartRawData.java
- java/code/src/com/redhat/rhn/domain/kickstart/cobbler/CobblerSnippet.java
- java/spacewalk-java.changes.mackdk.drop-jcommon
- java/spacewalk-java.spec
This PR drops the dependency on jcommon. It was only used to copy from a `Reader` to a `Writer`. This operation is part of the java  API since version 10.
No difference.
> Remove jcommon dependency in favor of modern java

- java/code/src/com/redhat/rhn/frontend/servlets/AuthFilter.java
- java/spacewalk-java.changes.rmateus.master
Follow-up on the pr: https://github.com/uyuni-project/uyuni/pull/8465
All API action that are read-only are being published as GET request. This PR enhances the validation to only allow calling GET methods.
With the current implementation, those read-only users can still call API methods that are for UI usage and can make post requests to those. this happens because the API on UI methods are also using the same prefix "/manager/api".
With this change, all HTTP methods different from GET will be blocked.
No difference.
Before:
After:
- Documentation issue was created: [Link for SUSE Manager …
> User with API ready only are only allowed to make GET requests

- testsuite/features/build_validation/add_non_MU_repositories/alma8_minion_build_clm.feature
- There is no PHP 8.1 available in AlmaLinux 8, so we need to use a different filter
- The child channel is also a different one (the same we already have for Rocky 8): `RES8-Manager-Tools-Pool for x86_64 Alma`
Probably copy-paste errors from the AlmaLinux 9 feature file.
No difference.
Issue(s): # …
> QE: 5.0 BV fixes

- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
Uyuni is still compiled with java 11. Stay compatible as long as we did not switch fully to java 17
No difference. …
> Build with java11

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/step_definitions/navigation_steps.rb
Sometimes we don't have any available non-critical patches.
Let's perform a different test strategy, let's don't filter by the kind of patch but let's assure the patch doesn't require a reboot, if so, we select the next patch.
Note: If we have two consecutive patches requiring reboot, bad luck 🤣
No difference.
Ports:
- Manager-4.3
If you need to …
> QE: Improve apply patch in BV

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/suse/manager/attestation/AttestationManager.java
- java/code/src/com/suse/manager/attestation/test/AttestationManagerTest.java
- java/code/src/com/suse/manager/model/attestation/AttestationFactory.java
- java/code/src/com/suse/manager/webui/Router.java
- java/code/src/com/suse/manager/webui/controllers/ConfidentialComputingController.java
- java/code/src/com/suse/manager/webui/controllers/MinionsAPI.java
- java/code/src/com/suse/manager/webui/menu/MenuTree.java
- java/code/src/com/suse/manager/webui/templates/audit/confidential-computing.jade
- java/spacewalk-java.changes.mackdk.coco-attestation-ui-audit
- web/html/src/components/CoCoScansList.tsx
- web/html/src/manager/audit/coco/coco-global-scans-list.renderer.tsx
- web/html/src/manager/audit/index.ts
- web/spacewalk-web.changes.mackdk.coco-attestation-ui-audit
This PR adds a UI page to display the attestation reports on all systems accessible by the user under Audt > Confidential Computing. This listing behaves the same as the the one from https://github.com/uyuni-project/uyuni/pull/8597, without the system filtering, and reuses the same components.
Note: this change is merging to branch `coco-attestation-part2`.
After:
- Documentation WIP https://github.com/SUSE/spacewalk/issues/23652
Issue(s): https://github.com/SUSE/spacewalk/issues/23563 …
> Coco attestation UI - Audit

- .gitignore
- java/code/src/com/redhat/rhn/common/db/datasource/xml/CoCoAttestationReport_queries.xml
- java/code/src/com/redhat/rhn/common/db/datasource/xml/file-list.xml
- java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateWorker.java
- java/code/src/com/redhat/rhn/taskomatic/task/ReportDbUpdateTask.java
- java/code/src/com/suse/manager/model/attestation/CoCoEnvironmentType.java
- java/code/src/com/suse/manager/model/attestation/CoCoResultType.java
- java/spacewalk-java.changes.mc.report-db-coco
- reporting/reports/data/coco-attestation
- reporting/reports/data/coco-attestation-results
- reporting/spacewalk-reports.changes.mc.report-db-coco
- schema/reportdb/check_reportdb_doc
- schema/reportdb/common/tables/CoCoAttestation.sql
- schema/reportdb/common/tables/CoCoAttestationResult.sql
- schema/reportdb/common/views/CoCoAttestationReport.sql
- schema/reportdb/common/views/CoCoAttestationResultReport.sql
- schema/reportdb/common/views/views.deps
- schema/reportdb/postgres/docs/tables/CoCoAttestation.pre
- schema/reportdb/postgres/docs/tables/CoCoAttestationResult.pre
- schema/reportdb/postgres/docs/views/CoCoAttestationReport.pre
- schema/reportdb/postgres/docs/views/CoCoAttestationResultReport.pre
- schema/reportdb/upgrade/uyuni-reportdb-schema-5.0.4-to-uyuni-reportdb-schema-5.0.5/001-add-CoCoAttestation.sql
- schema/reportdb/upgrade/uyuni-reportdb-schema-5.0.4-to-uyuni-reportdb-schema-5.0.5/002-add-CoCoAttestationResult.sql
- schema/reportdb/upgrade/uyuni-reportdb-schema-5.0.4-to-uyuni-reportdb-schema-5.0.5/003-add-view-CoCoAttestationReport.sql
- schema/reportdb/upgrade/uyuni-reportdb-schema-5.0.4-to-uyuni-reportdb-schema-5.0.5/004-add-view-CoCoAttestationResultReport.sql
- schema/reportdb/uyuni-reportdb-schema.changes.mc.coco-attestation-part2
Add Confidential Compute Attestation Reports also to the report database and create some default reports
No difference.
- Part of the bug CoCo docs
Issue(s): https://github.com/SUSE/spacewalk/issues/23565 …
> Report db for CoCo Attestation

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
In order to show the correct IPv6 entry, we need to first have finished at least once the HW refresh.
Therefore, we re-ordered scenarios to match what we do in CI tests.
Issue example:
No difference.
- Cucumber tests were re-orderer
Ports:
- https://github.com/SUSE/spacewalk/pull/24159 …
> QE: Re-order BV smoke tests in order to fix IPv6 issue

- java/code/src/com/redhat/rhn/frontend/xmlrpc/proxy/ProxyHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/proxy/test/ProxyHandlerTest.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
- java/code/src/com/suse/manager/ssl/SSLCertData.java
- java/code/src/com/suse/manager/ssl/SSLCertManager.java
- java/code/src/com/suse/manager/ssl/test/SSLCertManagerTest.java
- java/code/src/com/suse/manager/utils/ExecHelper.java
- java/code/src/com/suse/manager/webui/controllers/ProxyController.java
- java/code/src/com/suse/manager/webui/controllers/test/ProxyControllerTest.java
- java/spacewalk-java.changes.cbosdo.multi-fqdn
- java/spacewalk-java.spec
Since there is no hardware refresh to provide the list of all the FQDNs of the proxy we will use the SSL certificate subject CN and alternate names as FQDNs.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24066 …
> Container proxy: use SSL cert cnames as FQDNs

- java/code/src/com/redhat/rhn/common/db/datasource/xml/ErrataCache_queries.xml
- java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml
- java/spacewalk-java.changes.welder.appstreams-adapt-queries
- schema/spacewalk/common/tables/rhnChannelNewestPackage.sql
- schema/spacewalk/common/tables/tables.deps
- schema/spacewalk/common/views/rhnChannelNewestPackageView.sql
- schema/spacewalk/common/views/suseServerAppStreamHiddenPackagesView.sql
- schema/spacewalk/common/views/suseServerAppStreamPackageView.sql
- schema/spacewalk/common/views/views.deps
- schema/spacewalk/postgres/packages/packages.deps
- schema/spacewalk/upgrade/susemanager-schema-5.0.6-to-susemanager-schema-5.0.7/520-change-channel-newest-package-table-view.sql
- schema/spacewalk/upgrade/susemanager-schema-5.0.6-to-susemanager-schema-5.0.7/521-add-server-appstreams-views.sql
- schema/spacewalk/upgrade/susemanager-schema-5.0.6-to-susemanager-schema-5.0.7/522-rhn_channel.pkb.sql
- schema/spacewalk/upgrade/susemanager-schema-5.0.6-to-susemanager-schema-5.0.7/523-rhn_server.pkb.sql
- testsuite/podman_runner/run_db_migrations.sh
It adapts package queries to filter out modular packages that are part of disabled modules in the server.
No difference.
Fixes: https://github.com/SUSE/spacewalk/issues/23785
Check [How to …
> Adapt package queries for modular repositories

- python/spacewalk/satellite_tools/mgr-sign-metadata-ctl
- python/spacewalk/spacewalk-backend.changes.cbosdo.Manager-4.3
Some users may have a umask setting too strict permissions on the GPG key exported in /srv/susemanager/salt/gpg/. Enforcing the permissions to avoid issues when applying the salt state.
No difference.
- No tests: untested python script
Issue(s): https://github.com/SUSE/spacewalk/issues/24155
Port(s): https://github.com/SUSE/spacewalk/pull/24173 …
> Set the permissions on the exported GPG key in salt folder

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/suse/manager/attestation/AttestationManager.java
- java/code/src/com/suse/manager/webui/controllers/MinionController.java
- java/code/src/com/suse/manager/webui/controllers/MinionsAPI.java
- java/code/src/com/suse/manager/webui/templates/ssm/coco-ssm-schedule.jade
- java/code/src/com/suse/manager/webui/templates/ssm/coco-ssm-settings.jade
- java/code/src/com/suse/manager/webui/utils/gson/SystemScheduledRequestJson.java
- java/code/src/com/suse/manager/webui/utils/gson/SystemsCoCoSettingsJson.java
- java/code/webapp/WEB-INF/nav/ssm.xml
- java/code/webapp/WEB-INF/pages/ssm/ssmindex.jsp
- java/spacewalk-java.changes.mackdk.coco-attestation-ui-ssm-new
- web/html/src/components/CoCoScansList.tsx
- web/html/src/components/CoCoSettingsForm.tsx
- web/html/src/components/coco-attestation/CoCoSettingsForm.tsx
- web/html/src/components/coco-attestation/Utils.tsx
- web/html/src/components/target-systems.tsx
- web/html/src/manager/minion/coco/coco-settings.renderer.tsx
- web/html/src/manager/minion/coco/coco-settings.tsx
- web/html/src/manager/systems/coco/ssm-schedule.renderer.tsx
- web/html/src/manager/systems/coco/ssm-schedule.tsx
- web/html/src/manager/systems/coco/ssm-settings.renderer.tsx
- web/html/src/manager/systems/coco/ssm-settings.tsx
- web/html/src/manager/systems/index.ts
- web/spacewalk-web.changes.mackdk.coco-attestation-ui-ssm-new
This PR adds Confidential Computing support in the System Set Manager. In particular, two new pages are added to allow configuring and scheduling attestations on multiple systems.
After:
- Documentation work in progress
Issue(s): https://github.com/SUSE/spacewalk/issues/23562 …
> Coco attestation UI - System Set Manager

- java/buildconf/LICENSE.txt
- java/code/src/com/redhat/rhn/domain/server/ProxyInfo.hbm.xml
- java/code/src/com/redhat/rhn/domain/server/ProxyInfo.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
- java/spacewalk-java.changes.rjpmestre.fix_chained_container_proxies_configuration
- schema/spacewalk/common/tables/rhnProxyInfo.sql
- schema/spacewalk/susemanager-schema.changes.rjpmestre.fix_chained_container_proxies_configuration
- schema/spacewalk/upgrade/susemanager-schema-5.0.6-to-susemanager-schema-5.0.7/100-update-proxy-info.sql
Currently, when creating a proxy configuration either through the UI under `Systems/Proxy Configuration` or using `spacecmd proxy_container_config_generate_cert`, the generated ssh.yaml always references server_ssh_key_pub as the SSH key for the SUMA instance, regardless of the specified server/parent FQDN.
This PR addresses this issue by checking whether the server/parent FQDN refers to the actual SUMA instance itself or an already registered proxy. Then, ssh.yaml should reference either SUMA's (`/srv/susemanager/salt/salt_ssh/mgr_ssh_id.pub`) or the proxy SSH key (now stored in `rhnproxyinfo` table)
No difference.
Issue(s): https://github.com/uyuni-project/uyuni/issues/8157
Make sure the …
> fix chained container proxies configuration

- testsuite/features/step_definitions/command_steps.rb
This occurred for several Minions, therefore let's have more than 1 minute for that kind of channels:
```bash
[2024-04-19T07:47:03.931Z] Scenario: Wait for running reposyncs to finish after adding custom channel for alma9_minion # features/build_validation/add_MU_repositories/alma9_minion_add_maintenance_update_repositories.feature:44
[2024-04-19T07:47:03.931Z] This scenario ran at: 2024-04-19 09:43:46 +0200
[2024-04-19T07:47:03.931Z] Timeout after 60 seconds (Timeout.timeout): Channel not fully synced
[2024-04-19T07:47:03.931Z] When I wait until the channel "custom_channel_alma9_minion" has been synced               # features/step_definitions/command_steps.rb:388
[2024-04-19T07:47:03.931Z] Unknown timeout for channel custom_channel_alma9_minion, assuming one minute …
```
> QE: Wait 10 min to sync custom channels

- java/code/src/com/suse/manager/model/attestation/CoCoAttestationResult.java
- java/code/src/com/suse/manager/webui/utils/gson/CoCoAttestationResultJson.java
- java/spacewalk-java.changes.mackdk.coco-attestation-add-full-logs
- microservices/coco-attestation/attestation-core/src/main/resources/mappers/attestation-result.xml
- microservices/coco-attestation/attestation-module-snpguest/src/main/java/com/suse/coco/module/snpguest/SNPGuestWorker.java
- microservices/coco-attestation/attestation-module-snpguest/src/main/java/com/suse/coco/module/snpguest/execution/ProcessOutput.java
- microservices/coco-attestation/attestation-module-snpguest/src/test/java/com/suse/coco/module/snpguest/SNPGuestWorkerTest.java
- microservices/coco-attestation/attestation-module/src/main/java/com/suse/coco/model/AttestationResult.java
- schema/spacewalk/common/tables/suseCoCoAttestationResult.sql
- schema/spacewalk/susemanager-schema.changes.mackdk.coco-attestation-add-full-logs
- schema/spacewalk/upgrade/susemanager-schema-5.0.6-to-susemanager-schema-5.0.7/002-coco-add-process-output.sql
- web/html/src/components/coco-attestation/CoCoReport.tsx
- web/html/src/components/coco-attestation/CoCoResult.tsx
- web/html/src/components/coco-attestation/Utils.tsx
- web/spacewalk-web.changes.mackdk.coco-attestation-add-full-logs
This PR adds a new field in the attestation result to allow the attestation module to store the full processing output. This could help to diagnose any issue during the attestation and inspect the full execution.
After:
- In case of attestation failed:
- In case of attestation succeeded:
- When not used:
- Documentation WIP …
> Add detailed process output from the attestation module

- schema/spacewalk/upgrade/susemanager-schema-1.7.56.13-to-susemanager-schema-1.7.56.18/01_123-rhnChannelNewestPackageView.sql
- schema/spacewalk/upgrade/susemanager-schema-1.7.56.20-to-susemanager-schema-1.7.57/00_015-evr_t-max-replace.sql
- schema/spacewalk/upgrade/susemanager-schema-4.2.9-to-susemanager-schema-4.2.10/015-ignore-retracted-pkgs-in-newest-pkgs-view.sql
- schema/spacewalk/upgrade/susemanager-schema-4.3.17-to-susemanager-schema-4.3.18/000-ptf-package-visibility.sql
- schema/spacewalk/upgrade/susemanager-schema-4.3.4-to-susemanager-schema-4.3.5/030-rhnChannelNewestPackageView-fix-duplicates.sql
- schema/spacewalk/upgrade/susemanager-schema-4.4.3-to-susemanager-schema-4.4.4/400-ptf-package-visibility.sql
postgresql doesn't allow removing columns when replacing views. This PR modifies the older migration scripts for `rhnChannelNewestPackageView` to use `DROP/CREATE VIEW` statements instead of `REPLACE VIEW`.
No difference.
- No documentation needed: Schema bugfix …
> Fix schema migration for 'rhnChannelNewestPackageView'

- java/code/src/com/suse/manager/webui/utils/gson/SystemScheduledRequestJson.java
- java/code/src/com/suse/manager/webui/utils/gson/SystemsCoCoSettingsJson.java
Uyuni bare installation will still run a few month with java 11.
So we need to stay with that syntax for a short while.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24192 …
> change java 17 syntax back to java 11 for uyuni bare installation

- testsuite/features/step_definitions/api_common.rb
Fixes https://github.com/SUSE/spacewalk/issues/24183
In the 5.0 BV we have the proxy and RBS channels assigned to the regular SLEM 5.5 Minion AK.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24183 …
> QE: Fix SLEM 5.5 activation key creation in BV

- containers/server-image/Dockerfile
- containers/server-image/server-image.changes.cbosdo.master
It seems the PUT command in Dockerfile strips the file permissions, enforcing the execution flag using a RUN command to be on the safe side.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24188 …
> Add execution permissions on healthcheck.sh

- containers/server-attestation-image/Dockerfile
- containers/server-attestation-image/server-attestation-image.changes.mackdk.fix-attestation-image-healthcheck
This PR fixes the command used for the health check of  the attestation container to make sure the status is correctly reported as `healthy`.
No difference. …
> Fix attestation image HEALTHCHECK

- web/conf/rhn_web.conf
- Bump the WebUI to 5.0.0 RC for SUSE Manager and to Uyuni 2024.05 for Uyuni
- Please also note that the migrations schemas for the reportdb and susemanager-schema are available. no need of additional gitkeep
Before: `5.0.0 Beta 2` for SUSE Manager and `2024.03` for Uyuni
After: `5.0.0 RC` for SUSE Manager and `2024.05` for Uyuni
- No documentation needed: this is just the string on the WebUI
- No tests: no new tests needed
Relate(s): https://github.com/SUSE/spacewalk/issues/23744 and https://github.com/SUSE/spacewalk/issues/23742
We have already other changes for spacewalk-web. No need to confuse the users with a changelog that mentions both Uyuni 2024.05 and SUSE Manager 5.0 …
> Bump the WebUI to 5.0.0 RC for SUSE Manager and to Uyuni 2024.05 for Uyuni

- testsuite/features/build_validation/core/allcli_sanity.feature
- testsuite/features/build_validation/create_bootstrap_repositories/srv_create_bootstrap_repositories.feature
- testsuite/features/build_validation/init_clients/opensuse156arm_minion.feature
- testsuite/features/build_validation/init_clients/opensuse156arm_ssh_minion.feature
- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/constants.rb
- testsuite/features/support/env.rb
- testsuite/run_sets/build_validation/build_validation_init_clients.yml
Adds support for openSUSE Leap 15.6 aarch 64 on BV
Issue(s): https://github.com/SUSE/spacewalk/issues/23848
Port(s): 
- 4.3 https://github.com/SUSE/spacewalk/pull/24261
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properl …
> QE: Add opensuse 15.6 support only for aarch64 on BV

- testsuite/features/build_validation/migration/salt_migration_minion_migration.feature
- testsuite/features/build_validation/migration/sle15sp3_minion_migration.feature
- testsuite/features/build_validation/migration/sle15sp3_ssh_minion_migration.feature
- testsuite/features/build_validation/migration/slemicro54_minion_migration.feature
- testsuite/features/build_validation/migration/slemicro54_ssh_minion_migration.feature
- testsuite/features/step_definitions/command_steps.rb
Related to https://github.com/SUSE/spacewalk/issues/24233
Removes unused and not up to date OS salt packages from minions which are going to attempt a Product migration.
Not sure if this is a bug, but having those packages on the minion will otherwise stop product migrations as long as they are not updated to the last version (even if the system is using venv-salt or is managed via SSH).
I've also noticed a place in which we use **-n** with **transactional update** but I think we meant to use **-y** to skip the prompt for confirming packages installation.
No difference.
- Cucumber test features and step definitions were modified
Issue(s): https://github.com/SUSE/spacewalk/issues/24233
Port(s): SUMA 4.3 …
> QE: Review migration features

- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.vzhestkov.fix-bootstrap-for-t-u
Fix transactional systems bootstrapping with preinstalled salt minion packages
No difference.
- No tests: tests are already present in cucumber and failing for some cases
Tracks: https://github.com/SUSE/spacewalk/issues/23799 …
> Fix transactional systems bootstrapping with preinstalled salt minion packages

- susemanager-utils/susemanager-sls/src/beacons/reboot_info.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.vzhestkov.fix-reboot_info-beacon
Avoid sending empty events to the master in case if reboot_info salt module is not yet synchronized
No difference.
- No tests: too complex to test it properly
Tracks: https://github.com/SUSE/spacewalk/issues/23526 …
> Avoid sending empty events to the master with reboot_info beacon

- susemanager/bin/mgr-setup
- susemanager/susemanager.changes.mc.fix-default-db-connections
When we initially configure SUMA/Uyuni we want to setup with 400 DB connections.
In a container we might have a postgresql.conf with a different value which must be explicit overwritten.
No difference. …
> configure the database to provide enough connections for our default setup

- proxy/proxy/salt-broker/broker
- proxy/proxy/salt-broker/salt-broker
- proxy/proxy/spacewalk-proxy.changes.vzhestkov.make-salt-broker-smarter
In some cases if `salt-broker` is unable to communicate to `salt-master` it works as a dam collecting the salt events (mostly `salt/auth` as the minions can't proceed further). After reconnecting to the `master` all of the collected events will be pushed to the master and causing a flood of `salt/auth` events.
This PR is adding some ZeroMQ sockopts to the config to be set on `XSUB` and `DEALER` sockets to make them more reactive on disconnecting from the master. And implements `monitor` socket and method to react on disconnecting and connecting back to the master.
There are two important options here to change the behavior on disconnecting from the master:
- `drop_after_retries`: Default is `-1` means `do not drop on disconnecting`, `0` means drop on discronnect with no retries, or the …
> Make salt broker service more reactive on disconnects from the master

- containers/proxy-tftpd-image/proxy-tftpd-image.changes.oholecek.fix_ontimeout_cobbler
- containers/proxy-tftpd-image/tftp_wrapper.py
Recent addition of cobbler translations also made cobbler to ignore ONTIMEOUT syslinux entries, like saltboot does because it generates new one. This is not correct in cobbler scenario.
No difference.
- No tests: covered by integration/acceptance tests
Issue(s): # https://github.com/SUSE/spacewalk/issues/24249 …
> Do not ignore ONTIMEOUT pxe in cobbler case

- spacewalk/setup/bin/spacewalk-setup
- spacewalk/setup/spacewalk-setup.changes.cbosdo.setup-message
This is already done by mgradm in a more visible way.
No difference.
- No tests: setup message
Issue(s): https://github.com/uyuni-project/uyuni/issues/8671 …
> Remove the visit message at the end of the setup

- containers/server-image/Dockerfile
- containers/server-image/server-image.changes.cbosdo.apache-exporter
See title
No difference.
- No tests: package removed from image
Issue(s): https://github.com/SUSE/spacewalk/issues/24217
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-bran …
> Remove unused apache exporter from server image

- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/spacewalk-java.changes.cbosdo.multi-fqdn
A previous PR added the FQDNs from the proxy configuration to the new system created (foreign), but not to the existing one.
No difference.
- Cucumber tests were failing
Issue(s): https://github.com/SUSE/spacewalk/issues/24066 …
> Add FQDNs from the proxy configuration to existing system

- testsuite/features/build_validation/migration/sle15sp3_minion_migration.feature
- testsuite/features/build_validation/migration/sle15sp3_ssh_minion_migration.feature
- testsuite/features/build_validation/migration/slemicro54_minion_migration.feature
- testsuite/features/build_validation/migration/slemicro54_ssh_minion_migration.feature
After a product migration takes place in BV, we should use real channels from the new product version (and therefore new base channel) to test whether it is possible to successfully subscribe the minion to a new child channel.
No difference.
- Cucumber tests were  modified
Issue(s): https://github.com/SUSE/spacewalk/issues/24233
Port(s): Manager 4.3 https://github.com/SUSE/spacewalk/pull/24316
> QE: use real channels in product migration features

- .github/CODEOWNERS
See title, right now frontend is marked as owners for conf directories, po files, etc other things that are not directly under our umbrella.
No difference.
- No documentation needed: codeowners
- No tests: nothing to test …
> Make frontend code ownership more granular

- testsuite/features/build_validation/retail/proxy_container_branch_network.feature
- testsuite/features/init_clients/proxy_container_branch_network.feature
- testsuite/features/step_definitions/retail_steps.rb
This PR sets the name of the proxy to its name on the private network in prevision for pxeboot via Cobbler or Retail.
No ports.
> Retail - fix proxy name

- containers/proxy-tftpd-image/proxy-tftpd-image.changes.jmozd.fix_http_in_system_profiles
- containers/proxy-tftpd-image/tftp_wrapper.py
The tftp proxy pulls system profiles for PXE boot from the central Uyuni server, where Cobbler generates these pointing typically to the central server's host for http-fetching profiles and installable. When pointing the client to a proxy for installation, these requests should go to the proxy's host instead.
This change adds code in the containerized tftp gateway to replace the according host entries in URLs for grub (grub/system/\*) and pxelinux (pxelinux.cfg/01-\*) PXE profiles.
No difference.
- No tests: unsure if the test automatism does handle the test case
https://bugzilla.suse.com/show_bug.cgi?id=1223855 …
> replace server urls on tftp pull

- java/code/src/com/suse/cloud/PaygComplainceInfo.java
This PR restores compatibility with Java 11 by removing a pattern matching `instanceof` introduced in the `equals()` autogenerated by the IDE.
No difference. …
> Removed Java 17 only feature in autogenerated equals

- web/html/src/branding/css/base/theme.less
- web/html/src/branding/css/base/theme.scss
- web/html/src/branding/css/susemanager-dark-variables.less
- web/html/src/branding/css/susemanager-dark-variables.scss
- web/html/src/branding/css/susemanager-dark.less
- web/html/src/branding/css/susemanager-dark.scss
- web/html/src/branding/css/susemanager/variables.less
- web/html/src/branding/css/susemanager/variables.scss
- web/html/src/build/webpack.config.js
- web/spacewalk-web.changes.eth.dark-theme
We initially piped both the light and dark sidebar theme into one file to make the core theme migration easier, now both work and I've reintegrated it.
- Docs ticket already exists
- No tests: theme …
> Reenable the dark sidebar version

- containers/server-hub-xmlrpc-api-image/Dockerfile
- containers/server-hub-xmlrpc-api-image/server-hub-xmlrpc-api-image.changes.nadvornik.hub-update
Call update-ca-certificates on startup of hub xmlrpc container.
Without this change the service does not see the certificates mounted in  /etc/pki/trust/anchors volume.
No difference.
TBD
https://github.com/uyuni-project/uyuni-tools/issues/292
Check …
> Call update-ca-certificates on startup of hub xmlrpc container

- testsuite/features/step_definitions/command_steps.rb
In our current Build Validation pass, we suspected that this step might be failing silently.
So we want to improve the verbosity of it, without printing the whole output on every iteration, as this will overload our logs.
As we expect to have error code 0 o 1 from the grep command piped to spacecmd command, we decided to fail the step if the error code is different than these values.
No difference.
No ports. …
> QE: The step to run mgr-sync will now fail if the error code is different than expected values 0 or 1

- testsuite/features/support/lavanda.rb
Seems some tools still print color codes when called from the testsuite.
This let some XML parser fail and we do not get the testresults
No difference. …
> remove terminal escape sequences from output

- java/code/src/com/redhat/rhn/domain/server/Server.java
- java/code/src/com/suse/manager/webui/services/pillar/MinionGeneralPillarGenerator.java
- java/spacewalk-java.changes.welder.reboot-beacon-interval
- schema/spacewalk/upgrade/susemanager-schema-5.0.6-to-susemanager-schema-5.0.7/200-enable-pillar-refresh.sql
It modifies the reboot info beacon execution interval. It extends the interval from 10 seconds to 180 seconds for Red Hat-like systems and to 30 seconds for other systems.
The main reason for changing it is that the `dnf needs-restarting` command executed for RH-like might be too resource-intensive for the systems. Even for the other systems, checking every 10 seconds seems to be too often, so increasing to 30 seconds can be more suitable.
No difference.
Issue(s): https://github.com/uyuni-project/uyuni/issues/8457 …
> Increase reboot info beacon interval

- testsuite/features/init_clients/proxy_container.feature
According to @vzhestkov, this is a bad thing and we should not use it anymore. ~So I disabled the scenario temporarily~ So I removed this scenario after testing it on the HEAD CI, to see if that fixes https://github.com/SUSE/spacewalk/issues/24360
Slack thread: https://suse.slack.com/archives/C02D134507M/p1715932883653409
- tainted the proxy resources with terraform and let them be recreated
- remove the already present Salt key in `/var/lib/salt/.ssh/known_hosts` on the server container
- comment out the cleanup scenario
- rerun the feature:
```bash
suma-head-ctl:~/spacewalk/testsuite # cucumber features/init_clients/proxy_container.feature
Capybara APP Host: https://suma-head-srv.mgr.suse.de:8888
Initializing a twopence node for 'server'.
Host 'server' is alive with determined hostname …
```
> QE: Remove sumaform cleanup of the container proxy

- containers/server-image/Dockerfile
- containers/server-image/server-image.changes.mc.add-and-handle-billing-data-service
- python/billingdataservice/billing-data-service.changes.mc.add-and-handle-billing-data-service
- python/billingdataservice/billing-data-service.service
- python/billingdataservice/billing-data-service.spec
- python/billingdataservice/payg-service-override.conf
- spacewalk/admin/mgr-check-payg.service
- spacewalk/admin/spacewalk-admin.changes.mc.add-and-handle-billing-data-service
- spacewalk/admin/spacewalk-startup-helper
The billing-data-service is needed for SUMA PAYG Public Cloud image.
As we do not want a special container, we install it by default inside of the container and enable the service.
The service has a condition to only start when ISPAYG environment variable is set. This should be done by "mgradm install"
via the service file.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24287
If you uncheck …
> Add and handle billing data service

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml
- schema/spacewalk/common/tables/suseAppstream.sql
- schema/spacewalk/common/tables/suseAppstreamApi.sql
- schema/spacewalk/common/tables/suseServerAppstream.sql
- schema/spacewalk/susemanager-schema.changes.welder.optimize-appstream-queries
- schema/spacewalk/upgrade/susemanager-schema-5.0.7-to-susemanager-schema-5.0.8/001-optimize-appstreams-hidden-packages-views.sql
It fixes `suseServerAppStreamHiddenPackagesView` by considering the `stream` column when joining `suseAppstream` and `suseServerAppstream` tables and includes new indexes to optimize the queries on it.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24195 …
> Optimize AppStreams related queries

- web/html/src/branding/css/bootstrap5-scaffolding-variables.scss
- web/html/src/branding/css/susemanager/components/modal.less
- web/html/src/branding/css/susemanager/components/modal.scss
- web/html/src/branding/css/susemanager/components/pre.scss
- web/html/src/branding/css/susemanager/index.scss
- web/html/src/components/dialog/util.ts
- web/spacewalk-web.changes.eth.modal-diff
Bootstrap 3 and 5 handle modals slightly differently, so we need to use a placeholder layout in 5 until we wrap up the migration. The new styles are mostly just verbatim copies of what 3 uses for modals so the look and feel is the same.
Modals work again on the notification messages page.
- No documentation needed: bugfix.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1224401 …
> Emulate Bootstrap 3 modals in Bootstrap 5

- spacecmd/src/spacecmd/proxy.py
- web/html/src/manager/proxy/container-config.tsx
This requirement is not valid anymore for the proxy so removing it.
No difference.
Before:
After:
- No tests: Only a label change and that isn't covered by tests.
Issue(s): # …
> Update the message as this requirement is not valid anymore

- testsuite/features/step_definitions/navigation_steps.rb
Fix mark second check box/row in a list.
As it is now, it raise an ambiguous matching error.
No difference.
Ports:
- Manager-4.3
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-an …
> BV: Fix mark second check box/row in a list

- testsuite/features/support/file_management.rb
Command `curl --insecure http://mirror.chpc.utah.edu/pub/centos/7/isos/x86_64/sha256sum.txt-o sha256sum.txt` is currently failing because we are missing a space between the url and the -o option
No difference. …
> checksum url failing because option -o have no space

- testsuite/features/support/constants.rb
In CI, we still distinguish between Proxy Containerized and Classic Proxy.
In BV, for 5.0/Uyuni, we just have one kind of proxy (containerized).
So, we need to fix the constants adding a key for "proxy"
No difference.
No ports. …
> QE: Fix constants for proxy in 5.0 and Uyuni BV environments

- java/code/src/com/redhat/rhn/frontend/taglibs/list/ListTagUtil.java
- java/spacewalk-java.changes.bisht-richa.fix-missing-pagination-icon
Fixed missing icons in pagination buttons:
https://localhost:8080/rhn/admin/SatSchedules.do
https://localhost:8080/rhn/systems/details/packages/PackageList.do?sid=1000010006&
No difference.
Before:
After:
Issue(s): #8728 …
> Fixed missing pagination buttons icon

- web/html/src/branding/css/base/tables.less
- web/html/src/branding/css/base/tables.scss
- web/html/src/branding/css/susemanager/components/text.less
- web/html/src/branding/css/susemanager/components/text.scss
- web/html/src/branding/css/susemanager/index.less
- web/html/src/manager/admin/task-engine-status/taskotop.tsx
- web/html/src/manager/notifications/notification-messages.tsx
- web/spacewalk-web.changes.bisht-richa.fix-mute-text-color-contrast
- Fixed skipped tasks and read messages color contrast in table
No difference.
**Before:**
**After:**
Issue(s): #[#24136](https://github.com/SUSE/spacewalk/issues/24136) …
> Fix skipped status text color

- java/code/src/com/redhat/rhn/taskomatic/task/gatherer/VirtualHostManagerProcessor.java
- java/code/src/com/redhat/rhn/taskomatic/task/gatherer/test/VirtualHostManagerProcessorTest.java
- java/code/src/com/suse/manager/gatherer/GathererRunner.java
- java/code/src/com/suse/manager/gatherer/HostJson.java
- java/spacewalk-java.changes.mackdk.fix-host-identifier
This PR handles the change of host identifier in virtual-host-gatherer when dealing with VMWare hosts. This is needed because the current field is not reliable when dealing with an update of the VMWare OS.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23401
Port(s): https://github.com/SUSE/spacewalk/pull/24001
Related change: https://github.com/uyuni-project/virtual-host-gatherer/pull/37
If you …
> Fix host identifier

- testsuite/features/secondary/srv_cobbler_buildiso.feature
- testsuite/features/secondary/srv_cobbler_distro.feature
- testsuite/features/secondary/srv_cobbler_profile.feature
- testsuite/features/step_definitions/cobbler_steps.rb
- testsuite/features/support/cobbler_test.rb
This 
- will remove the very disruptive step `When(/^I remove kickstart profiles and distros$/)` since it is causing issues across all our CIs. With this step we basically remove every profile and distribution regardless if it was created in the current feature or not.
In Cobbler, we first need to delete a system to be then able to delete the profile that was assigned to this system. The same applies for a distribution. Before being able to delete a distribution, the associated profile needs to be deleted beforehand.
So instead of calling `I remove kickstart profiles and distros`, only the system, profile and distribution that was created in the currently executed feature will also get deleted at the end of this feature.
- fix some of the Cobbler spelling mistakes (`Cobbler` vs. …
> QE: Refactor how Cobbler items are deleted

- java/code/webapp/WEB-INF/pages/admin/setup/mirror-credentials.jsp
- java/code/webapp/WEB-INF/pages/schedule/actionchain.jsp
- java/code/webapp/WEB-INF/pages/ssm/systems/deleteconfirmdialog.jspf
- java/spacewalk-java.changes.eth.modal-event
- web/html/src/branding/css/bootstrap5-scaffolding-variables.scss
- web/html/src/branding/css/susemanager/components/modal.less
- web/html/src/branding/css/susemanager/components/modal.scss
- web/html/src/branding/css/susemanager/components/tables.less
- web/html/src/branding/css/susemanager/components/tables.scss
- web/html/src/components/dialog/Dialog.tsx
- web/html/src/components/dialog/util.ts
- web/html/src/components/popup.tsx
- web/spacewalk-web.changes.eth.modal-event
The backwards compatibility fix we have for Bootstrap 3 and 5 modals was incomplete and the overlay was not always hidden properly. This PR fixes the issue.
Also fix a number of small layout inconsistencies between different pages, fix the icon not being an actual icon like elsewhere, etc.
No difference.
- No documentation needed: bugfix.
https://suse.slack.com/archives/C02D130RBA6/p1716280210173269 …
> Fix modal backwards compatibility event handling, fix layout inconsistencies

- java/code/src/com/redhat/rhn/frontend/action/configuration/sdc/OverviewAction.java
- java/spacewalk-java.changes.mc.fix-npe-on-timestring
We saw NPE in `makeTimeMessage(OverviewAction.java:351)` when running the testsuite.
This PR fix the issue and some other things sonarcloud was suggesting
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24379 …
> Uyuni fix npe on timestring

- testsuite/run_sets/build_validation/build_validation_retail_proxy.yml
- testsuite/run_sets/build_validation/build_validation_retail_sle12.yml
- testsuite/run_sets/build_validation/build_validation_retail_sle15.yml
With containerized server and proxy, one cannot prepare that Saltboot group formula before he/she has built the images. It is not possible anymore to prepare the proxy, then build the images.
The reason why it worked in a non-containerized setup is that Retail used an image-sync state at the end.
No port, 5.0 only.
> Change order of Retail features

- java/code/src/com/redhat/rhn/frontend/action/common/DownloadFile.java
- java/code/src/com/redhat/rhn/manager/kickstart/KickstartManager.java
- java/code/src/com/redhat/rhn/manager/kickstart/KickstartUrlHelper.java
- java/code/src/com/redhat/rhn/manager/kickstart/SSMScheduleCommand.java
- java/spacewalk-java.changes.oholecek.replace_cobblerhost_by_javahost
Moving to the containerized server required cobbler host setting to be set to localhost. Because of this we cannot use getCobblerHost when constructing profile URLs or cobbler profiles. This PR changes some last occurrences or getCobblerHost usages. 
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24383 …
> Replace getCobblerHost by getJavaHostname

- web/html/src/branding/css/base/notifications.less
- web/html/src/branding/css/base/notifications.scss
- web/html/src/branding/css/base/theme.less
- web/html/src/branding/css/base/theme.scss
- web/html/src/branding/css/susemanager/components/header.less
- web/html/src/branding/css/susemanager/components/header.scss
- web/spacewalk-web.changes.eth.header-alignment
Fixes the search box and the bell alignment in the header. Fixing this issue by itself is easier than detangling the breaking change back out.
Before:
After:
- No documentation needed: bugfix.
- No tests: UI bugfix.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1225072
Check [How …
> Fix header layout alignment bugs (bsc#1225072)

- susemanager-utils/susemanager-sls/salt/packages/profileupdate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.cbbayburt.bsc1224476
Our `appstreams` module is not available for Centos 7 and older (no `dnf`). This PR excludes gathering module information from the package profile update for these distributions.
No difference.
Fixes https://github.com/SUSE/spacewalk/issues/24372 …
> Exclude AppStream information from package profile update for Centos 7 and older (bsc1224476)

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/webapp/WEB-INF/pages/systems/sdc/proxyclients.jsp
- java/spacewalk-java.changes.mbussolotto.proxy_message
Remove obsolete proxy installation messages (bsc#1224778)
No difference.
- No tests
Issue(s): https://github.com/SUSE/spacewalk/issues/24374
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly) …
> Remove obsolete proxy installation messages (bsc#1224778)

- java/code/src/com/suse/manager/webui/utils/ViewHelper.java
- web/html/src/branding/css/susemanager/components/buttons.suma.less
- web/html/src/branding/css/susemanager/components/buttons.suma.scss
- web/html/src/branding/css/susemanager/index.scss
- web/html/src/core/spa/view-helper.ts
- web/spacewalk-web.changes.bisht-richa.fix-search-icon-button-height
Fix the height of the search icon button
No difference.
Before:
After:
- No tests:
Issue(s): #8755
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-bran …
> Fix search icon button height

- testsuite/features/build_validation/retail/proxy_container_branch_network.feature
- testsuite/features/init_clients/proxy_container_branch_network.feature
I intentionaly did not copy this code from traditional proxy, because I was not sure it was still needed.
Now I am sure of that.
Affects both CI and BV.
No port, 5.0 only.
> Schedule a Hardware list refresh after changing the network

- containers/proxy-helm/proxy-helm.changes.mbussolotto.squid_conf
- containers/proxy-helm/templates/config.yaml
- containers/proxy-helm/templates/deployment.yaml
- containers/proxy-helm/values.yaml
- containers/proxy-squid-image/Dockerfile
- containers/proxy-squid-image/proxy-squid-image.changes.mbussolotto.squid_conf
- containers/proxy-squid-image/squid_example.conf
- containers/proxy-squid-image/uyuni-configure.py
include /etc/squid/conf.d/*.conf
No difference.
https://github.com/uyuni-project/uyuni-docs/pull/3011
- No tests
Issue(s): https://github.com/uyuni-project/uyuni-tools/issues/263
Depends on: https://github.com/uyuni-project/uyuni-tools/pull/320 …
> include /etc/squid/conf.d/*.conf

- .github/workflows/build_containers.yml
- testsuite/dockerfiles/controller-dev/Dockerfile
Ci update server container to 2024 05 and fix ssh 4
No difference.
- No tests
Issue(s): https://github.com/SUSE/spacewalk/issues/23742
> Ci update server container to 2024 05 and fix ssh 4

- testsuite/features/reposync/allcli_update_activationkeys.feature
This PR adds
- missing SLE15 SP4 LTSS child channel to the right activation keys
- missing checks for some of the child channels
No difference.
Issue(s): # …
> QE: Add SLE15SP4 LTSS to activation keys

- containers/proxy-tftpd-image/proxy-tftpd-image.changes.oholecek.fix_pxe_system_translations
- containers/proxy-tftpd-image/tftp_wrapper.py
In filters we rely on that there is some non label entry which does not begins with whitespace. However system entries generated by cobbler does not have it.
This commit adds an empty line after content so there is always one.
No difference.
Issue(s): # TBD …
> Fix PXE system filter to actually store results

- python/spacewalk/satellite_tools/reposync.py
- python/test/unit/spacewalk/satellite_tools/test_reposync.py
This was moved to spacewalk.common.fileutils. It's still available as createPath, but we can use the snake_case version as well.
No difference.
- No tests: already covered 
Issue(s): # …
> reposync: fix createPath after move

- testsuite/features/secondary/proxy_container_retail_mass_import.feature
- testsuite/features/secondary/proxy_traditional_retail_mass_import.feature
- testsuite/features/step_definitions/retail_steps.rb
Initial motivation was to remove the failure at the cleanup of mass imported minions and have one red less.
This PR re-enables mass import checks by working around bsc#1220864.
None, 5.0 only.
> Re-enable mass import checks

- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataExtractor.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/beans/PaygInstanceInfo.java
- java/code/src/com/suse/cloud/CloudPaygManager.java
- java/code/src/com/suse/cloud/PaygComplainceInfo.java
- java/code/src/com/suse/cloud/test/CloudPaygManagerTest.java
- java/code/src/com/suse/cloud/test/TestCloudPaygManagerBuilder.java
- java/spacewalk-java.changes.mc.fix-payg-findings
- python/billingdataservice/billing-data-service.changes.mc.fix-payg-findings
- python/billingdataservice/billing-data-service.service
- python/billingdataservice/billing-data-service.sysconfig
- uyuni/uyuni-payg-timer/uyuni-payg-extract-data.py
- uyuni/uyuni-payg-timer/uyuni-payg-timer.changes.mc.fix-payg-findings
billing-data-service is running inside of the container. No need to check for the package outside of the container
No difference. …
> do not check for billing-data-service as it run inside of the container

- testsuite/features/support/env.rb
Fix initialization of global var. beta_enabled
As it is now, it will set is a true, if the environment variable is defined, doesn't matter the value set on it.
No difference.
Ports:
- Manager-4.3 …
> QE: Fix initialization of global var. beta_enabled

- containers/proxy-httpd-image/proxy-httpd-image.changes.oholecek.cobbler_proxy_redirect
- containers/proxy-httpd-image/uyuni-configure.py
Proxying apache is trying to connect to itself using host IP address. This however fails because of hairpin problem. Using redirect moves this responsibility to the client, at the expense of revealing this rewritten URL and one more TCP roundtrip.
No difference.
- No tests: already covered by BV testsuite
Issue(s): # https://bugzilla.suse.com/show_bug.cgi?id=1225520 …
> Use redirect instead of proxypass for rewritten cobbler autoyast link

- testsuite/features/secondary/proxy_container_retail_mass_import.feature
- testsuite/features/step_definitions/retail_steps.rb
- testsuite/features/upload_files/bootstrap-pxeboot.exp
Follow-up of https://github.com/uyuni-project/uyuni/pull/8818:
* pass the activation key as a parameter when building the bootstrap script
* pick up bootstrap script directly from minion with curl instead of doing 2 scp copies
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/24420
> More elegant code suggested by Ondrej

- testsuite/features/secondary/min_check_patches_install.feature
Related to https://github.com/SUSE/spacewalk/issues/22610
Introduces some checks to verify both the patches for andromeda-dummy and virgo-dummy are present.
It should also take care of possible failures due to a patch not being displayed in the first page of results - the pages are limited to 100 results and virgo-dummy is usually at the end of a list of 120+ patches.
EDIT: verified on HEAD CI.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/22610
Port(s): (4.3) https://github.com/SUSE/spacewalk/pull/24436 …
> QE: fix scenario searching for existing patches

- testsuite/features/secondary/srv_cobbler_distro.feature
- testsuite/features/secondary/srv_cobbler_profile.feature
More Cobbler related changes.
- removes the Cobbler API login in the Cobbler profile feature since the Cobbler API is not used there
- adds TODOs for switching the Cobbler API to the SUMA API in the Cobbler distro feature
- adds more distro removals in the Cobbler distro feature. The creation of those profiles are hidden behind the following steps, so it was not obvious that their cleanup was missing
```ruby
When(/^I create a kickstart tree via the API$/) do
$api_test.kickstart.tree.create_distro('fedora_kickstart_distro_api', '/var/autoinstall/Fedora_12_i386/', 'fake-base-channel-rh-like', 'fedora18')
end
When(/^I create a kickstart tree with kernel options via the API$/) do
$api_test.kickstart.tree.create_distro_w_kernel_options('fedora_kickstart_distro_kernel_api', …
```
> QE: Add distro cleanups to Cobbler distro feature

- testsuite/features/reposync/srv_disable_scheduled_reposync.feature
* Disable Cobbler automatic sync so it does not interfer with Cobbler tests
Notes:
* the automated cobbler sync remains needed in 4.3
* it will get removed in 5.1
* Make existing scenario work despite existing bug
Port: (the workaround part only)
* 4.3: https://github.com/SUSE/spacewalk/pull/24440
> Disable Cobbler automatic sync + work around UI bug

- java/manager-build.xml
This PR adds on the classpath the new `open-test-reporting` dependency required by the latest junit5 package.
No difference.
- No tests: change affects only the testing phase
Port(s): https://github.com/SUSE/spacewalk/pull/24442 …
> Fix Junit 5 test execution

- testsuite/features/step_definitions/command_steps.rb
Sync time for PTF custom channel is close to the default maximum of 60 seconds and sometimes over it.
This PR takes the standard default for custom channels for PTF custom channels as well.
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/24444
- [x ] No changelog needed
> PTF channels are custom channels too

- testsuite/features/secondary/min_retracted_patches.feature
- testsuite/features/secondary/srv_clone_channel_npn.feature
In Uyuni we have the Leap Micro patches in the "All Patches" list. This result in multiple pages and we need to use the filter to see the expected results on the first page.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24447 …
> use filter when acting on Patch List > All

- java/code/src/com/redhat/rhn/domain/kickstart/KickstartFactory.java
- java/code/src/com/redhat/rhn/manager/system/CancelKickstartSessionOperation.java
- java/spacewalk-java.changes.cbosdo.ks-cancel
When cancelling an autoinstallation, the cobbler system profile needs to be removed and the initiate action has to be canceled.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23790 …
> Remove dangling bits in autoinstallation cancel

- testsuite/features/secondary/srv_cobbler_distro.feature
this default value made us use SLES kernel for a Fedora distro...
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/24454
> Do not take default value (SLES) for Fedora distro

- susemanager-sync-data/channel_families.json
- susemanager-sync-data/susemanager-sync-data.changes.mc.sle12sp5-ltss-channel_families
Add new SLES12 SP5 LTSS product classes.
Removed Liberty HA LTSS 7 product class
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24457 …
> add SLE 12 SP5 LTSS channel families and remove Liberty HA LTSS 7

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- testsuite/features/secondary/srv_mainpage.feature
- Update copyright year from 2023 to 2024
Before: `Copyright (c) 2011 - 2023 SUSE LLC.`
After: `Copyright (c) 2011 - 2024 SUSE LLC.`
Also the testsuite has been fixed
- No documentation needed: this doesn't require a documentation update
- Updated tests: already covered, just updated the existing test
Issue(s): #
Port(s): # **this needs to be ported to 4.3 too** …
> Update copyright year to 2024

- java/code/src/com/redhat/rhn/domain/kickstart/KickstartableTree.java
- java/spacewalk-java.changes.mc.Manager-4.3-force-overwrite-symlink
symlinks in the salt filesystem are not supported anymore.
This PR replace symlinks with regular files.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24465 …
> replace symlink to kernel and initrd in salt filesystem with regular files

- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/min_change_software_channel.feature
This PR aims to:
- make clear when API calls are used
- replace the naming SLES minion with openSUSE minion in some instances
- (the meaningful part) make these scenarios less flaky without adding complexity and/or maintenance overload
The scope of this feature should be to:
- verify the state of the channels before the action for changing channels is scheduled
- verify the state remains consistent after an action has been scheduled
- verify the state changes as expected once the action/event is complete
- verify both the UI and  API return the correct state of the channels for a given system before and after the action
To do so counting the initial number of enabled channels we would need one of:
1.  global variable
2.  hardcoded number which has been previously verified
3. some logic …
> QE: tidy some channels management scenarios

- testsuite/features/secondary/srv_cobbler_distro.feature
- testsuite/features/step_definitions/cobbler_steps.rb
This PR fixes the last failing Cobbler test.
The issue was that we were selecting by default the profile from Retail.
In addition to selecting the correct radio button, this code was rationalized.
There was also a bug in 4.3, "client" versus "sle_client".
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/24496
> Choose correct profile

- java/code/src/com/redhat/rhn/domain/action/ActionFactory.java
- java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java
- java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/reactor/messaging/test/hardware.profileupdate.public_cloud_payg.json
- java/code/src/com/suse/manager/reactor/messaging/test/hardware.profileupdate.x86.json
- java/code/src/com/suse/manager/reactor/test/RegisterMinionActionTest.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/webui/utils/salt/custom/HwProfileUpdateSlsResult.java
- java/spacewalk-java.changes.mc.Manager-4.3-fix-payg-client-detection
- susemanager-utils/susemanager-sls/salt/hardware/profileupdate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mc.Manager-4.3-fix-payg-client-detection
PR https://github.com/uyuni-project/uyuni/pull/8331 changed the instance flavor check and moved it from grains into an execution module.
But the hardware refresh was forgotten and still test for the grain. As this grain does not exist anymore, all systems are
set to BYOS.
This makes it impossible to run any action on these clients when we have a SUSE Manager Server PAYG.
Also when this is fixed, the re-detection is impossible as it require to execute an action on BYOS systems.
So this PR allow to run a Hardware refresh also on BYOS systems to be able to fix instance type.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24501 …
> Fix payg client detection

- web/conf/rhn_web.conf
**Bump WebUI to 5.0.0 for SUSE Manager and to Uyuni 2024.06 for Uyuni**
- Please also note that we don't need any additional `.gitkeep`:
- the migrations schemas for susemanager-schema are available
- the reportdb doesn't have new changes to be tagged
Before: `5.0.0 RC` for SUSE Manager and `2024.05` for Uyuni
After: `5.0.0` for SUSE Manager and `2024.06` for Uyuni
- No documentation needed: this is just the string on the WebUI
- No tests: no new tests needed
Relate(s): https://github.com/SUSE/spacewalk/issues/23747 and https://github.com/SUSE/spacewalk/issues/23749
We have already other changes for spacewalk-web. No need to confuse the users with a changelog that mentions both Uyuni 2024.06 and SUSE Manager 5.0
If you …
> Bump WebUI to 5.0.0 for SUSE Manager and to Uyuni 2024.06 for Uyuni

- java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
- java/spacewalk-java.changes.mcalmer.fix-sshpush-tunnel
- susemanager-utils/susemanager-sls/modules/roster/uyuni.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.fix-sshpush-tunnel
When configuring ssh cascade for ssh push with tunnel via proxies, the last proxy command has a reverse port forwarding rule using the hostname of the proxy. That hostname is the name of the "host", but we land inside of the container which has its own network. 
To reach the given hostname, a connection is made to the host which redirect again inside of the container.
Also in case if the RPM based installed proxy, localhost should work as we want to redirect the local port always.
This should handle also the case of containerized SUSE Manager Server 5.0 with a plain SUSE Manager 4.3 proxy.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24510 …
> fix hairping problem during ssh push with tunnel

- testsuite/features/secondary/min_salt_lock_packages.feature
Related to https://github.com/SUSE/spacewalk/issues/20168
One scenario of this feature can fail for the reason detailed in the issue's comments: at times, an event has not yet been completed when we check for the state that results from it.
These makes the test flaky despite everything else actually working fine and the feature working as intended.
Although the root cause of this behavior lies in the way we check for completed events, this PR introduces a few more checks to standardize the scenarios and - hopefully - make the whole thing more robust.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/20168
Port(s): 4.3 https://github.com/SUSE/spacewalk/pull/24506
If you don't …
> QE: additional checks in Salt packages lock scenarios

- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes.mbussolotto.notification
Runing `mgr-create-bootstrap-repo` I had this error:
```
File "/usr/sbin/mgr-create-bootstrap-repo", line 1082, in <module>
sys.exit(abs(main() or 0))
File "/usr/sbin/mgr-create-bootstrap-repo", line 1060, in main
r = create_repo(elabel, opts, mgr_bootstrap_data, additional=args)
File "/usr/sbin/mgr-create-bootstrap-repo", line 845, in create_repo
create_bootstrap_failure_notification(label, messages)
File "/usr/sbin/mgr-create-bootstrap-repo", line 262, in create_bootstrap_failure_notification
cfg.notification_type_disabled
File "/usr/lib/python3.6/site-packages/spacewalk/common/rhnConfig.py", line 254, in __getattr__
raise AttributeError(key)
AttributeError: notification_type_disabled
```
looks like it's a typo, the configuration in …
> fix typo on notification

- java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/KickstartHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/tree/KickstartTreeHandler.java
- java/spacewalk-java.changes.oholecek.fix_using_serverfqdn_for_distro_api
Autoinstallation distro API uses host used by client as a host to access the distro files. This was probably done because of proxies, but for proxy we have postprocessing translations in place, which assumes server fqdn used there. Also using client's host means using spacecmd on container would use 'localhost'.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24508 …
> Use javaHostName instead of passed server name

- rel-eng/container_push.sh
This is GMC and we can now start to push the containers as released and with the final `sle-eula` EULA.
- No tests: this is an internal script
Relate(s): https://github.com/SUSE/spacewalk/issues/23747 and https://github.com/SUSE/spacewalk/issues/23749 and https://github.com/uyuni-project/uyuni-tools/pull/353 …
> Switch RELEASE_STAGE to released and EULA to sle-eula

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
We've experienced numerous failures in our smoke tests which are related to UI elements not being found.
This issue probably stems from the way skipped and failed test interact which each other, causing the webdriver to be on a different URL/web-page than the one the scenario expects.
Introducing a step in a few scenarios forcing navigation to a client's detail page should hopefully make the tests more robust and independent from each other's results.
NOTE: the final feature files are generated from a template using Rake, so the changes are applied there.
- No diff
- Cucumber tests were modified (actually, the template to generate them)
Issue(s): https://github.com/SUSE/spacewalk/issues/24518
Port(s): 4.3 …
> QE: improve BV smoke tests template

- python/rhn/rhnlib.changes
- python/rhn/rhnlib.changes.deneb-alpha.add_missing_bsc1222731
Align changelogs between SUMA 4.3 and SUMA 5.0 and add missing bsc#1222731 reference 
https://github.com/SUSE/spacewalk/issues/24543
**Please note that I also edited the main .changes for adding the missing bsc reference. the changelog test is expected to fail**
No difference.
- No tests: just changelog fix
Issue(s): https://github.com/SUSE/spacewalk/issues/24543 …
> Align changelog entries and add missing bsc#1222731

- testsuite/features/secondary/min_retracted_patches.feature
Follow up on https://github.com/uyuni-project/uyuni/pull/8856
When using the "back" button in a test, we need to re-apply the filter.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24526 …
> re-apply the filter after using the back button

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/reposync/srv_sync_products.feature
Changes the endings of SUSE Manager Proxy Extension 5.0 in the testsuite scenarios. Tested on the 5.0 BV environment.
Ignoring GitHub actions errors for the reason of [5.0 BV GMC](https://github.com/SUSE/spacewalk/issues/23832)
No difference.
Before:
After:
Issue(s): https://github.com/SUSE/spacewalk/issues/24560 …
> BV 5.0 GMC - Channels missmatch in SUSE Manager Proxy Extension 5.0 testsuite scenarios

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml
- java/spacewalk-java.changes.mc.fix-upgradable-package-query
The Package Upgrade page list duplicate package names. When all packages are selected, salt return an error like
`You are passing a list of packages that contains duplicated packages names`.
Adapt the query to return only the latest version of a package.
No difference.
Before:
After:
Issue(s): https://github.com/SUSE/spacewalk/issues/24509 …
> fix system_upgradable_package_list query to not list duplicate names

- java/spacewalk-search.changes.rjpmestre.switch_used_java_to_java-17-openjdk
There was a changelog file that did not belong where it was. As we're tagging and resubmitting, we're taking the chance to remove it to avoid confusions.
I'm not adding a changelog for this, as this is actually about removing one (that never got into the tagging anyway because it was for the wrong package).
No difference.
Issue(s): # …
> Remove wrong changelog from spacewalk-search into spacewalk-java

- testsuite/features/secondary/srv_push_package.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
Card: https://github.com/SUSE/spacewalk/issues/24072
Now the official strategy when using rhnpush/mgrpush is to run it outside the server container.
No difference.
No ports …
> QE: Perform mgr-push through a minion instead of running it from the server

- susemanager-utils/susemanager-sls/src/grains/public_cloud.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.vzhestkov.implement-v2-for-aws-instance-detection
Implement `v2` with token to get AWS instance data according to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
No difference.
- No tests: No unit tests for this module
Issue(s): https://github.com/SUSE/spacewalk/issues/24504 …
> Implement v2 for AWS instance detection

- rel-eng/packages/uyuni-storage-setup
- uyuni/uyuni-storage-setup/LICENSE
- uyuni/uyuni-storage-setup/README.md
- uyuni/uyuni-storage-setup/scripts/mgr-storage-proxy
- uyuni/uyuni-storage-setup/scripts/mgr-storage-server
- uyuni/uyuni-storage-setup/scripts/susemanager-storage-setup-functions.sh
- uyuni/uyuni-storage-setup/uyuni-storage-setup.changes.mc.add-uyuni-storage-tool
- uyuni/uyuni-storage-setup/uyuni-storage-setup.spec
Uyuni storage tool is a port of https://github.com/SUSE-Enceladus/susemanager-cloud-setup
with adaptions for VM images and bare metal installations.
It can be used for adding extra storage after Uyuni / SUSE Manager is already setup.
No difference.
- https://github.com/SUSE/spacewalk/issues/24363
- manual
Issue(s): https://github.com/SUSE/spacewalk/issues/24358 …
> Add uyuni storage tool

- uyuni/uyuni-payg-timer/uyuni-payg-extract-data.py
- uyuni/uyuni-payg-timer/uyuni-payg-timer.changes.mc.fix-uninitialized-var-access
On BYOS systems the variable 'has_metering_access' is not initialized before it is accessed.
No difference.
Issue(s): https://bugzilla.suse.com/show_bug.cgi?id=1226483 …
> fix accessing 'has_metering_access' on BYOS systems

- testsuite/features/support/constants.rb
SLE 15 SP6 constants and timeouts with Leap 15.6
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24568
Port(s): https://github.com/SUSE/spacewalk/pull/24577
Check [How to …
> BV 5.0 GMC - Add SLE 15 SP6 to the resposync testsuite

- testsuite/features/build_validation/create_bootstrap_repositories/srv_create_bootstrap_repositories.feature
- testsuite/features/build_validation/init_clients/slmicro60_minion.feature
- testsuite/features/step_definitions/command_steps.rb
* Fixing a typo in `Scenario: Reboot the SL Micro 6.0 minion through SSH`
* Specify whether to `--flush` when creating bootstrap repositories
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24593
Port(s): <s>https://github.com/SUSE/spacewalk/pull/24602</s> does not apply to 4.3
If you …
> BV 5.0 GMC - Minions bootstrapping issues

- uyuni/uyuni-payg-timer/uyuni-payg-extract-data.py
- uyuni/uyuni-payg-timer/uyuni-payg-timer.changes.mc.fix-pkglist-uyuni-payg-timer
The list of packages to check for compliance was wrong.
- python311-azure-mgmt-billing was removed as it is not on the image anymore
- python-instance-billing-flavor-check was added as it tells us if we are PAYG or not
No difference.
Issue(s):  …
> adapt packages to check for modifications

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.vzhestkov.fix-pki-dir-deletion
In case of second run of bootstrap script when the minion is already tried to authenticate to the master it's possible that PKI directory will be removed and the minion key regenerated, so that the master will get two (or even more) keys with the same minion ID.
Additionally: set PKI config directory to be more precise to prevent possible deletion of master PKI directory in case if bootstrap script will try to bootstrap the salt master host with classic `salt-minion` package.
No difference.
- No tests: in some test it was already causing errors, so it seems that some of the tests are covering it already.
Issue(s): #
Make sure the changelogs entries you are adding are compliant …
> Fix salt minion PKI directory cleanup with bootstrap script

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.mc.sll-7-ltss-bootstrap-repo
Bootstrap repo data for Linerty Linux 7 LTSS is missing
No difference.
Issue(s): 
Port(s): https://github.com/SUSE/spacewalk/pull/24652 …
> add bootstrap repository data for Liberty Linux 7 LTSS

- testsuite/features/step_definitions/common_steps.rb
In order to avoid this error:
```
Scenario: Check the new channel is working
When I refresh the metadata for "slemicro54_minion"
The host slemicro54_minion has not yet a implementation for that step (ScriptError)
./features/step_definitions/common_steps.rb:305:in `/^I refresh the metadata for "([^"]*)"$/'
features/build_validation/migration/slemicro54_minion_migration.feature:78:in
`I refresh the metadata for "slemicro54_minion"'
```
add Micro OS, SLE Micro and Leap Micro to metadata refresh step.
Port(s):
* 4.3:  https://github.com/SUSE/spacewalk/pull/24662
> Add Micro OS, SLE Micro and Leap Micro to metadata refresh step

- testsuite/features/build_validation/migration/salt_migration_minion_migration.feature
* Fixes typos in salt migration minion regarding channels selection.
* Shortens remote command list to only one required result.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24659
Port(s): https://github.com/SUSE/spacewalk/pull/24663
> BV 5.0 GMC - salt migration minion testsuite errors

- testsuite/features/step_definitions/command_steps.rb
Fixes the Gherkin syntax.
>When steps are used to describe an event, or an action. This can be a person interacting with the system, or it can be an event triggered by another system.
Then steps are used to describe an expected outcome, or result.
https://cucumber.io/docs/gherkin/reference/#when
No difference.
Issue(s): #
Ports(s): # https://github.com/SUSE/spacewalk/pull/24665 …
> QE: Fix Gherkin syntax

- schema/reportdb/common/tables/Errata.sql
- schema/reportdb/upgrade/uyuni-reportdb-schema-5.0.5-to-uyuni-reportdb-schema-5.0.6/001-alter-errata-cve-column.sql
- schema/reportdb/uyuni-reportdb-schema.changes.mc.master
Errata table has a column defined as VARCHAR(4000) which is the maximum.
But new patches - especially kernel - have huge lists of CVE ids that we go over this maximum and updating the report DB
failed with:
```
ERROR: value too long for type character varying(4000)
```
This change the type to "TEXT" which should be able to take everything what is provided.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24607 …
> change Errata cve column to type text

- java/code/src/com/redhat/rhn/domain/formula/FormulaFactory.java
- java/code/src/com/redhat/rhn/manager/formula/FormulaManager.java
- java/code/src/com/suse/manager/webui/controllers/AnsibleController.java
- java/spacewalk-java.changes.mackdk.prepare-for-snakeyaml-upgrade
This PR remove usages of the deprecated constructor `SafeConstructor()`. This will allow smooth migration to version 2.2
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24693
Port(s): https://github.com/SUSE/spacewalk/pull/24696 …
> Removed usages of deprecated SnakeYAML `SafeConstructor()`

- testsuite/features/build_validation/migration/salt_migration_minion_migration.feature
Do not remove the Salt migration minion from SUMA server at the end of  feature.
It makes debugging harder and has no real advantage:
1) The VM still exists and uses resources
2) The minion has its packages upgraded and is no more in the starting state --> the feature is not idempotent
The only point would be to verify that the removal itself works, but that can eventually be done manually.
No difference.
- Cucumber tests were modified (removed scenario)
Issue(s): https://github.com/SUSE/spacewalk/issues/24233
Port(s): 4.3 https://github.com/SUSE/spacewalk/pull/24723 …
> QE: do not unregister the Salt migration minion

- testsuite/features/step_definitions/command_steps.rb
Related to https://github.com/SUSE/spacewalk/issues/23475
The return of this function call was never used, causing the API client to still be the previous one.
Yep, that's all.
No difference.
- A Cucumber step definition was modified
Issue(s): https://github.com/SUSE/spacewalk/issues/23475
Port(s): 4.3
> QE: correctly reset the API client

- schema/spacewalk/susemanager-schema.changes.parlt.fix-recurring-state-config-migration
- schema/spacewalk/upgrade/susemanager-schema-4.4.6-to-susemanager-schema-4.4.7/100-update-recurring-action.sql
Fix a problem where the migration would delete existing `suseRecurringStateConfig` entries during migration due to delete cascading.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24743
Check [How to …
> Fix recurring custom state configs being deleted during migration 

- testsuite/features/secondary/min_rhlike_openscap_audit.feature
Profile standard is not available anymore for `openscap ssg-centos8-xccdf.xml`.
Switch to ANSSI-BP-028 (intermediary) profile. For more info see : https://github.com/SUSE/spacewalk/issues/24629 
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24629 …
> Update profile name (standart not available anymore)

- testsuite/features/secondary/min_rhlike_openscap_audit.feature
A minor change,  the centos8 xml does work but I'd guess it is better to use a rhel-8 one with the change to Rocky 8 (?).
Available XML files:
```
[root@uyuni-master-podman-min-rocky8 content]# ls
ssg-centos7-ds-1.2.xml         ssg-fedora-ds.xml           ssg-ol8-cpe-oval.xml        ssg-ol9-xccdf.xml                     ssg-rhcos4-ocil.xml           ssg-rhel8-ds-1.2.xml          ssg-rhv4-cpe-dictionary.xml
ssg-centos7-ds.xml             ssg-fedora-ocil.xml         ssg-ol8-ds-1.2.xml          ssg-openeuler2203-cpe-dictionary.xml  ssg-rhcos4-oval.xml           ssg-rhel8-ds.xml              ssg-rhv4-cpe-oval.xml
ssg-centos7-xccdf.xml          ssg-fedora-oval.xml         ssg-ol8-ds.xml              ssg-openeuler2203-cpe-oval.xml        ssg-rhcos4-xccdf.xml          ssg-rhel8-ocil.xml …
```
> QE: use Rocky 8 specifig xml for OpenScap audit

- testsuite/features/support/namespaces/kickstart.rb
Uyuni testuite relies on an HTTP client sending/receiving JSON to test REST API endpoints.
The parameters' names we use in our testsuite wrapper for such API calls are turned into keys for the JSON sent in POST calls and must therefore perfectly match the endpoint's parameter names.
The XMLRPC API, tested with SUMA,  likely  relies on positional parameters instead.
No difference.
- Cucumber tests definitions were modified
Issue(s): https://github.com/SUSE/spacewalk/issues/24572 …
> QE: correct names for paramaters in kickstart API calls

- schema/spacewalk/susemanager-schema.changes.parlt.master
- schema/spacewalk/upgrade/susemanager-schema-4.4.6-to-susemanager-schema-4.4.7/100-update-recurring-action.sql
Fix a case where `custom state` type recurring actions would wrongly be inserted into `suseRecurringHighstate` if the table was empty during time of migration.
No difference.
Before:
After:
Issue(s): https://github.com/SUSE/spacewalk/issues/24794 …
> Fix custom state recurring actions being inserted into recurringHighstate table

- testsuite/features/secondary/srv_rename_hostname.feature
- testsuite/features/step_definitions/command_steps.rb
The Uyuni feature file is missing a reboot through SSH after the hostname changes.
Another thing worth noticing is that we're executing the following code to know whether the services are back up or not
```ruby
repeat_until_timeout(timeout: default_timeout, message: 'Spacewalk didn\'t come up') do
out, _code = temp_server.run('spacewalk-service status', check_errors: false, timeout: 10)
if !out.to_s.include?('dead') && out.to_s.include?('running')
log 'Server spacewalk service is up'
break
end
sleep 1
end
```
this works fine in 4.3, but not on Uyuni where the following service doesn't run
```
○ mgr-check-payg.service - Check and install PAYG billing service.
Loaded: loaded (/usr/lib/systemd/system/mgr-check-payg.service; static)
Active: inactive (dead)
Condition: start condition failed at …
```
> QE: reboot and check server health after hostname change

- web/conf/rhn_web.conf
- web/spacewalk-web.changes.raul.bump_uyuni_2024.07
Do **NOT** merge till after the release of SUSE Manager 5.0 GMC.
Merge this when it is time to release Uyuni 2024.07
Bump the WebUI version to 2024.07
Before:
WebUI Showing version 2024.06 (which was not released)
After:
WebUI Showing version 2024.07
Issue(s): https://github.com/SUSE/spacewalk/issues/23749 …
> Bump the WebUI version to 2024.07

- susemanager-utils/susemanager-sls/modules/runners/mgrutil.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.agraul.speedup-mgrutil-remove-known-host
`mgrutil.remove_ssh_known_host` uses Salt's `ssh.rm_known_host` function. `ssh.rm_known_host` computes the path to the `known_hosts` file if that is not passed. This computation can take a long time because it uses the generic `user.info` function, which can be slow when users configure e.g. winbindd to provide user/group information.
We now bypass this potentially expensive computation and try to find the config file ourselves.
No difference.
- No tests: we don't have environments where we can test the runtime performance of "slow" directory servers.
Issue(s): https://github.com/SUSE/spacewalk/issues/24171
Port(s): https://github.com/SUSE/spacewalk/pull/24315
Make sure the changelogs entries you are adding are compliant …
> Speed-up mgrutil.remove_ssh_known_host runner function

- java/code/src/com/redhat/rhn/frontend/dto/HistoryEvent.java
- java/spacewalk-java.changes.mcalmer.fix-NPE-in-event-history
A queued action has no completion time set.
When querying the history, a date string NULL is valid.
Just set completion time to null as well.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/9132
Port(s): https://github.com/SUSE/spacewalk/pull/24481 …
> prevent NPE when listing history events without completion time

- java/buildconf/build-props.xml
- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
- java/spacewalk-java.changes.mbussolotto.byte-buddyy
- java/spacewalk-java.spec
fix byte-buddy runtime dependency. Testing it here: https://build.opensuse.org/project/show/home:mbussolotto:branches:systemsmanagement:Uyuni:Master
No difference.
- No tests
Issue(s): https://github.com/uyuni-project/uyuni/issues/8859
> fix byte-buddy runtime dependency

- java/code/src/com/redhat/rhn/domain/common/ManagerInfoFactory.java
- java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
- java/code/src/com/redhat/rhn/domain/scc/test/SCCCachingFactoryTest.java
- java/spacewalk-java.changes.mc.fix-product-refresh-in-cloud
update last sync refresh timestamp only when at least one time products were synced before.
This happens when PAYG Update Task only refreshing repositories, but never products were synchronized
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/24717 …
> update last sync refresh timestamp only when products were synced

- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/spacewalk-java.changes.welder.fix-centos7-pkg-profile-update
- susemanager-utils/susemanager-sls/salt/packages/profileupdate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.welder.fix-centos7-pkg-profile-update
Bug fix, see title.
No difference.
Issue(s): #
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch …
> Fix package profile update on CentOS 7 when yum-utils is not installed

- java/code/src/com/suse/cloud/CloudPaygManager.java
- java/spacewalk-java.changes.mc.fix-payg-race-condition
During setup we first setup the container which start without the payg*.json files.
It will think it is a BYOS setup.
After the container is running, we call `uyuni-payg-extract-data` from mgradm to perform the detection and create the files.
But the container is running and the next detection will be done just 1 hour later.
This PR check if the complianceInfo report BYOS and no Cloud Provider, but the payg_compliance.json file exits and is readable.
In this case it force a re-detection.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24677 …
> Fix payg race condition

- microservices/coco-attestation/attestation-module-snpguest/src/main/java/com/suse/coco/module/snpguest/SNPGuestWorker.java
- microservices/coco-attestation/attestation-module-snpguest/src/test/java/com/suse/coco/module/snpguest/SNPGuestWorkerTest.java
- microservices/coco-attestation/uyuni-coco-attestation.changes.mackdk.attestation-fix-report-missing
This PR fixes an issue with the snpguest attestation module. Currently, when the report is not present (because the attestation action failed) a `NullPointerException` is thrown. This change handles this edge case and notifies of the problem in the log.
No difference. …
> Do not throw exception if the nonce/report are not available

- microservices/coco-attestation/attestation-module-secureboot/src/main/java/com/suse/coco/module/secureboot/SecureBootWorker.java
- microservices/coco-attestation/attestation-module-secureboot/src/test/java/com/suse/coco/module/secureboot/SecureBootWorkerTest.java
- microservices/coco-attestation/uyuni-coco-attestation.changes.mackdk.attestation-fix-secureboot
This PR changes the behaviour of the Secure Boot validation to ensure the text `SecureBoot enabled` is present in the output from mokutil in order to mark the result as `SUCCEEDED`. Currently if we get a different errors from the expected one, we could potentailly mark a failed test as correct.
No difference. …
> Mark Secure Boot as succeeded only if the correct message is present in the output

- java/code/src/com/redhat/rhn/domain/channel/ChannelFamilyFactory.java
- java/code/src/com/redhat/rhn/domain/cloudpayg/PaygProductFactory.java
- java/spacewalk-java.changes.mc.payg-proxy-product-for-aarch64
The Proxy product exist now also for aarch64. This got a different Channel Family.
To show this correctly, we need to check for "startwith()".
This will also allow to see "BETA" versions.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24672 …
> include proxy products for aarch64

- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/CoCoAttestationConfigSerializer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/suse/manager/model/attestation/AttestationFactory.java
- java/code/src/com/suse/manager/model/attestation/ServerCoCoAttestationConfig.java
- java/code/src/com/suse/manager/xmlrpc/serializer/ServerCoCoAttestationReportSerializer.java
- java/spacewalk-java.changes.mackdk.fix-coco-attestation-api
This PR fixes:
- The absence of the `attestOnBoot` field in the `getCoCoAttestationConfig` API
- The error that happens when serializing for the XMLRPC API a `ServerCoCoAttestationReport` when the `attested` date is `null`. This might happen when the report is still PENDING
- The field `attestOnBoot` is ignored by `setCoCoAttestationConfig`  API when no configuration exists
- The error that happens when `getCoCoAttestationConfig` is called and no configuration is present. Now if the system has coco support an empty configuration is returned.
- Prevent all the API to work with systems that do not have support for coco attestation. An `UnsupportedOperationException` is now returned by the API.
- Return an `EntityNotExistsFaultException` when the system specified in the call does not match …
> Fix CoCo Attestation API errors

- python/spacewalk/satellite_tools/appstreams.py
- python/spacewalk/spacewalk-backend.changes.cbbayburt.appstreams-reposync-8972
- python/test/unit/spacewalk/satellite_tools/test_appstreams.py
Some packages in REMI's 3rd party repositories include a '~' character as part of the version string. This patch fixes the module import during repo-sync to recognize this character.
Fixes https://github.com/uyuni-project/uyuni/issues/8972 …
> Fix importing module metadata from REMI's repositories

- susemanager-sync-data/additional_products.json
- susemanager-sync-data/susemanager-sync-data.changes.kwalter.centos7
the old centos 7 repo urls don't work anymore. this changes the urls to the currently working ones.
No difference.
- No tests
Issue(s): https://github.com/SUSE/spacewalk/issues/24768
Port(s): https://github.com/SUSE/spacewalk/pull/24783 …
> change to new and working repo urls

- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerSystemCreateCommand.java
- java/spacewalk-java.changes.mczernek.mczernek_1219450
- schema/spacewalk/common/data/rhnTaskoSchedule.sql
- schema/spacewalk/susemanager-schema.changes.mczernek.mczernek_1219450
When using the API to add a system, the API explicitly triggers a Cobbler synchronization. This should not be necessary because:
a) Cobbler shouldn't need a sync after adding a system
b) There is the `cobbler-sync-default` task in SUMA to schedule Cobbler sync periodically.
The default cadence of executing the `cobbler-sync-default` is every minute. This can be computationally expensive in large environments that add/remove a lot of systems in a short period of time, esp. because one `cobbler sync` can take longer than 5 minutes.
In this PR, I'm increasing the default schedule from 1 minute to every 5 minutes.
No difference.
Before:
After:
Issue(s): …
> Remove cobbler synchronization when adding system

- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mczernek.disable-slem-timer-on-bootstrap
When bootstrapping SLEM, disable the SLEM's reboot timer so that it does not interfere with SUMA's timed work, e.g. reposyncing or other scheduled work.
No difference.
Before:
After:
- Documentation PR: https://github.com/uyuni-project/uyuni/pull/8981
Issue(s): # https://github.com/SUSE/spacewalk/issues/24251 …
> Disable transactional-update.timer on SLEM at bootstrap

- susemanager-utils/testing/docker/scripts/Makefile
- susemanager-utils/testing/docker/scripts/test_cobbler.sh
This PR fixes the Cobbler Jenkins pipeline that is failing with the `127.0.0.1 != 192.168.1.1` errors.
NOTE: This PR depends on the container modifications in OBS and IBS changes.
**Cobbler**:
- https://github.com/openSUSE/cobbler/pull/94
- https://github.com/openSUSE/cobbler/pull/95
- https://github.com/openSUSE/cobbler/pull/96
- https://github.com/openSUSE/cobbler/pull/97
**OBS**:
- 1181964
**IBS**:
- 336382
- 336383
Issue(s): https://github.com/SUSE/spacewalk/issues/20850
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repositor …
> Fix the cobbler test pipeline scripts

- java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_bn_IN.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ca.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_cs.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_de.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_es.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_fr.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_gu.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_hi.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_it.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ja.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ko.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_pa.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_pt_BR.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ru.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_si.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_sk.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_ta.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_uk.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_zh-HK.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_zh_CN.xml
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_zh_TW.xml
- java/code/webapp/WEB-INF/pages/systems/spmigration/spmigration-target.jsp
- java/spacewalk-java.changes.nadvornik.salt_package
Salt package installed on a client is checked for updates before product migration.
The package name was hardcoded as `salt`.
With this PR it prefers `venv-salt-minion` if it is installed.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24350
https://bugzilla.suse.com/show_bug.cgi?id=1224209
Port(s): https://github.com/SUSE/spacewalk/pull/24839 …
> Check the correct salt package before product migration (bsc#1224209)

- testsuite/Rakefile
- testsuite/features/support/env.rb
During client bootstrap stage, when a client a failing to bootstrap, we are still trying to check if the client is correctly setup. This checks are adding 5-10 extra minutes to the test.
This PR will fail the client bootstrap feature if any scenario is failing. It will speed up the test when failing.
No difference. …
> BV: use option fail fast during clients bootstrap stage

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/step_definitions/api_common.rb
The scenario `Deploy the configuration file to <client>` cannot run in parallel if using the same user. `Configuration > Channels` share the same context.
To prevent this issue, create a unique user for each client and use it during the smoke test.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24605 …
> Create a user for each client in BV

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes.meaksh.master-fix-timeoutexpired
This PR simply fixes an small issue detected in a reference to `subprocess.TimeoutExpired`.
No difference.
- No tests: **no tests around this feature** …
> yum_src: use proper name variable name for "subprocess.TimeoutExpired"

- python/spacewalk/common/repo.py
- python/spacewalk/satellite_tools/repo_plugins/deb_src.py
- python/spacewalk/spacewalk-backend.changes.meaksh.master-introduce-timeout-for-deb-reposync
As mentioned in the title, this PR introduces a timeout when running "reposync" against DEB channels. This would prevent getting reposync stuck in case connections with the remote repositories gets stuck.
No difference.
- No tests: **no tests for this corner case**
Issue(s): https://github.com/SUSE/spacewalk/issues/24459
Port(s): https://github.com/SUSE/spacewalk/pull/24755 …
> deb_src: introduce timeout when syncing DEB channels (bsc#1225960)

- java/code/src/com/suse/manager/webui/utils/ViewHelper.java
- web/html/src/branding/css/susemanager/components/buttons.suma.scss
- web/html/src/branding/css/susemanager/components/buttons.uyuni.scss
- web/html/src/core/spa/view-helper.ts
- web/spacewalk-web.changes.bisht-richa.fixed-btn-info-style-new-theme
Fixed btn-info inconsistency in new and old theme
No difference.
Before:
After:
Issue(s): https://github.com/uyuni-project/uyuni/issues/8730
Fixes: https://github.com/uyuni-project/uyuni/issues/8730 …
> Btn info inconsistent

- java/code/src/com/suse/manager/webui/utils/ViewHelper.java
- java/code/webapp/WEB-INF/pages/errata/erratasearch.jsp
- java/spacewalk-java.changes.bisht-richa.fixed-advanced-package-search-layout
- web/html/src/branding/css/base/tables.scss
- web/html/src/core/spa/view-helper.ts
- web/spacewalk-web.changes.bisht-richa.fixed-advanced-package-search-layout
Fixed advanced package-search page layout
No difference.
Before:
After:
Fixes: https://github.com/uyuni-project/uyuni/issues/8739 …
> Fixed advanced package search page layout

- java/code/src/com/suse/manager/webui/utils/ViewHelper.java
- web/html/src/branding/css/base/forms.scss
- web/html/src/core/spa/view-helper.ts
- web/spacewalk-web.changes.bisht-richa.fixed-margin-maintenance-schedule-page
Fixed missing margin between inline radio buttons
No difference.
Before:
After:
Fixes: https://github.com/uyuni-project/uyuni/issues/8762 …
> Fixed missing margin between inline radio buttons

- java/code/src/com/suse/manager/webui/utils/ViewHelper.java
- web/html/src/core/spa/view-helper.ts
- web/html/src/manager/images/image-build.tsx
- web/spacewalk-web.changes.bisht-richa.fix-build-image-page-layout
Fixed build image page layout in the new theme
No difference.
Before:
After:
Fixes: https://github.com/uyuni-project/uyuni/issues/8993 …
> Fixed build image page layout in new theme

- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/spacewalk-java.changes.oholecek.fix_false_positive_ssh_gen_error
Fix false positive log of error. `orElseThrow` uses lambda, but logging was outside of it.
No difference.
- No tests: only logging detail
Issue(s): https://github.com/SUSE/spacewalk/issues/24645 …
> fix false positive ssh key generation error

- web/html/src/components/action-schedule.tsx
- web/spacewalk-web.changes.parlt.fix-MW-datetime-selection
Fix the datetime selection for the action scheduler component, when using maintenance windows.
No difference.
- No documentation needed: **BUGFIX**
- No tests: **BUGFIX**
Issue(s): https://github.com/SUSE/spacewalk/issues/24851 …
> Fix action scheduler datetime selection if using maintenance windows

- python/spacewalk/satellite_tools/appstreams.py
- python/spacewalk/spacewalk-backend.changes.welder.appstreams-refresh-newest-package
- schema/spacewalk/common/views/suseServerAppStreamHiddenPackagesView.sql
- schema/spacewalk/susemanager-schema.changes.welder.fix-appstreams-related-views
- schema/spacewalk/upgrade/susemanager-schema-5.0.10-to-susemanager-schema-5.0.11/200-fix-appstreams-related-views.sql
It adds a call to refresh newest package after import modules metadata for a channel and fix the views using appstreams data to calculate the newest package correctly.
No difference.
Issue(s): # …
> Fix appstreams newest package definitions

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml
- java/code/src/com/redhat/rhn/domain/rhnpackage/Package.java
- java/code/src/com/redhat/rhn/domain/rhnpackage/Package_satellite.hbm.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerPtfTest.java
- java/code/src/com/redhat/rhn/testing/PackageTestUtils.java
- java/spacewalk-java.changes.meaksh.master-improve-perforance-to-check-for-ptf-packages
- python/spacewalk/satellite_tools/xmlSource.py
- python/spacewalk/server/importlib/backendLib.py
- python/spacewalk/server/importlib/backendOracle.py
- python/spacewalk/server/importlib/packageImport.py
- python/spacewalk/spacewalk-backend.changes.meaksh.master-improve-perforance-to-check-for-ptf-packages
- schema/spacewalk/common/tables/rhnPackage.sql
- schema/spacewalk/common/views/susePackageExcludingPartOfPtf.sql
- schema/spacewalk/susemanager-schema.changes.meaksh.master-improve-perforance-to-check-for-ptf-packages
- schema/spacewalk/upgrade/susemanager-schema-5.0.8-to-susemanager-schema-5.0.9/300-replace-susePackageExcludingPartOfPtf-view.sql
This PR improves the performance to determine which packages are PTFs or part of a PTF, as in large environments with tons of packages, these SQL operations, and particularly the `susePackageExcludingPartOfPtf` SQL view can cause very huge delays in the context of Content Lifecycle Management (CLM) operations.
In order to achieve a better performance, this PR is doing the following changes:
- Add new columns `is_ptf` and `is_part_of_ptf` to `rhnPackage` table.
- These attributes are set once during package import, so no need to calculate them on each request.
- The `susePackageExcludingPartOfPtf` view and other SQL queries have been adapted to use the new attributes.
No difference.
Issue(s): …
> Improve SQL queries and performance to check for PTF packages (bsc#1225619)

- java/code/src/com/redhat/rhn/domain/server/NetworkInterface.java
- java/code/src/com/redhat/rhn/domain/server/test/NetworkInterfaceTest.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerSystemCreateCommand.java
- java/spacewalk-java.changes.meaksh.Manager-4.3-prevent-issues-on-duplicate-ips-bsc1226461
- susemanager-utils/susemanager-sls/src/modules/sumautil.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.meaksh.Manager-4.3-prevent-issues-on-duplicate-ips-bsc1226461
This PR fixes an issue seen when dealing with Autoinstallation and some of your systems contain `docker*`, `virbr*` or `cni-podman*` interfaces with the same IP address.
Then, when triggering autoinstallation for those systems, an ISE is raised (due duplicate IP address on Cobbler) and autoinstallation is not triggered properly:
```
...
Caused by: org.cobbler.XmlRpcException: XmlRpcException calling cobbler.
at org.cobbler.CobblerConnection.invokeMethod(CobblerConnection.java:160) ~[rhn.jar:?]
at org.cobbler.CobblerConnection.invokeTokenMethod(CobblerConnection.java:190) ~[rhn.jar:?]
at org.cobbler.SystemRecord.invokeModify(SystemRecord.java:310) ~[rhn.jar:?]
at org.cobbler.CobblerObject.modify(CobblerObject.java:339) ~[rhn.jar:?]
at …
```
> Autoinstallation: prevent issues with duplicate IP address due to some networks (bsc#1226461)

- susemanager-utils/susemanager-sls/salt/cleanup_minion/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.meaksh.master-bsc1228101
This PR fixes a typo on the paths to some minion files to cleanup when deleting a system in Uyuni. This was noticed as the `/etc/venv-salt-minion/pki/minion/minion_master.pub` and some other files were not cleaned up properly during system deletion as it was expected.
No difference.
- No tests: **no tests for this**
Issue(s): https://github.com/SUSE/spacewalk/issues/24906
Port(s): https://github.com/SUSE/spacewalk/pull/24907
If you …
> Fix typo on directories to cleanup when deleting a system (bsc#1228101)

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/constants.rb
This enables the sync of SUSE Liberty Linux 7 LTSS in our BV ~and switches the CentOS 7 Minion/SSH Minion to SLL 7 LTSS~. With https://github.com/SUSE/spacewalk/issues/24884 we will then migrate the CentOS 7 Minion to SLL 7 LTSS.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24438
Ports(s): Manager 4.3: …
> QE: Enable SLL 7 LTSS reposync in BV

- susemanager-utils/susemanager-sls/modules/roster/uyuni.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.rmateus.uyuni_add_ssh_port_tunnel_creating_tunnel
This reverts commit ef8b5d0052f42c4db8f61ddca22eeba06faa32e0.
from https://github.com/uyuni-project/uyuni/pull/8741
It connect to the client using the proxy port.
No difference.
Check [How …
> Revert "Look for proxy ssh port before look for host ssh port"

- testsuite/features/build_validation/migration/sle15sp3_minion_migration.feature
- testsuite/features/build_validation/migration/sle15sp3_ssh_minion_migration.feature
- testsuite/features/build_validation/migration/slemicro54_minion_migration.feature
- testsuite/features/build_validation/migration/slemicro54_ssh_minion_migration.feature
PRs to fix https://bugzilla.suse.com/show_bug.cgi?id=1224209 have been merged and we should no longer need to remove OS Salt during product migrations.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24233
Port(s): 4.3 https://github.com/SUSE/spacewalk/pull/24897
> QE: do not remove OS Salt during product migrations

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/env.rb
During the BV smoke test, we are using client user to execute the test.
If a scenario is failing, in `After do |scenario|`, the code block inside `if scenario.failed?` is going to be executed.
A step of this rescue scenario is to log back to susemanager with admin.
Unfortunately, this scenario switch back to admin user and doesn't use our client user.
During BV, we have a user for each smote tests scenario. Currently, `I reboot the "([^"]*)" minion through the web UI` is looking at reboot event triggered by admin ( only during bootstrap ) and not reboot event from the current user. Because the testsuite was not looking at the correct event, we were not waiting for the slemicro to correctly reboot and starting new test during the slemicro reboot.
This change will correctly log with the …
> QE : use current user instead of admin during after step authentification

- testsuite/features/secondary/srv_handle_config_channels_with_ISS_v2.feature
- testsuite/features/secondary/srv_handle_software_channels_with_ISS_v2.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/file_management.rb
Simplifies two folder removal operations into one.
Verification tests are passing:
```
uyuni-master-podman-ctl:~/uyuni/testsuite # cucumber features/secondary/srv_handle_config_channels_with_ISS_v2.feature
Capybara APP Host: https://uyuni-master-podman-srv.mgr.suse.de:8888
Initializing a twopence node for 'server'.
Host 'server' is alive with determined hostname uyuni-master-podman-srv and FQDN uyuni-master-podman-srv.mgr.suse.de
Node: uyuni-master-podman-srv, OS Version: 15.6, Family: opensuse-leap
Initializing a twopence node for 'server'.
Host 'server' is alive with determined hostname uyuni-master-podman-srv and FQDN uyuni-master-podman-srv.mgr.suse.de
Node: uyuni-master-podman-srv, OS Version: 15.6, Family: opensuse-leap
Activating HTTP API
Using the default profile... …
```
>  Merge two steps of folder's removal into one

- testsuite/features/build_validation/init_clients/sle15sp4_minion.feature
- testsuite/features/build_validation/init_clients/sle15sp4_ssh_minion.feature
- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
Forward port of https://github.com/SUSE/spacewalk/pull/24942. However, only HEAD is changed. Uyuni/Uyuni Podman is also affected, however, we do not fully sync openSUSE Leap 15.5 to be able to install the correct kernel.
See https://github.com/SUSE/spacewalk/issues/24903
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24903 …
> QE: Use correct kernel image for SLES 15 SP4

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
When synchronizing Liberty LTSS, we need to open the sub-list to check if the clients are correctly selected.
No difference. …
> QE: Liberty 7 LTSS : Open sub-list to verify client tools are selected

- web/conf/rhn_web.conf
- web/spacewalk-web.changes.deneb-alpha.webui501-202408
- Update the WebUI version fo r SUMA 5.0.1  and Uyuni 2024.08
- migration schema and reportdb are fine
Before: WebUI version  `5.0.0` and `2024.07`
After: WebUI version  `5.0.1` and `2024.08`
- No documentation needed: **No additional documentation needed**
- No tests: no  additional tests needed
related: https://github.com/SUSE/spacewalk/issues/24610 and https://github.com/SUSE/spacewalk/issues/23751
A changelog entry  is  needed for tagging the  change with tito. …
> Bump WebUI version for SUMA 5.0.1 and Uyuni 2024.08

- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/support/constants.rb
If we do not let the Uyuni client tools being fully synchronized, we will e.g. not have `mgr-push` available which we need for further tests.
This only affects the CI and also only openSUSE Leap 15.5 X86 which we use in the CI.
Fixes https://github.com/SUSE/spacewalk/issues/24979
Test in the Uyuni CI
```bash
uyuni-master-ctl:~/spacewalk/testsuite # cucumber features/reposync/srv_sync_products.feature
Capybara APP Host: https://uyuni-master-srv.mgr.suse.de:8888
Initializing a twopence node for 'server'.
Host 'server' is alive with determined hostname uyuni-master-srv and FQDN uyuni-master-srv.mgr.suse.de
Node: uyuni-master-srv, OS Version: 15.5, Family: opensuse-leap
Initializing a twopence node for 'server'.
Host 'server' is alive with determined hostname uyuni-master-srv and FQDN …
```
> QE: Do not kill Uyuni Client Tools sync

- testsuite/features/step_definitions/common_steps.rb
Changed "1 (minutes, hours, days) ago" to the proper grammatical equivalent expected in the valid uptime messages considered.
Port(s): # 4.3 https://github.com/SUSE/spacewalk/pull/25009
> QE: Add further validation for uptime flexibility

- testsuite/features/secondary/min_ssh_tunnel.feature
Before:
<details>
```
Scenario: Run a remote command on this SSH tunnel minion                              # features/secondary/min_ssh_tunnel.feature:73
This scenario ran at: 2024-08-07 13:17:36 +0200
When I follow the left menu "Salt > Remote Commands"                                # features/step_definitions/navigation_steps.rb:339
Then I should see a "Remote Commands" text in the content area                      # features/step_definitions/navigation_steps.rb:11
When I enter command "echo 'My remote command output'"                              # features/step_definitions/salt_steps.rb:210
And I enter the hostname of "ssh_minion" as "target"                                # features/step_definitions/navigation_steps.rb:437
The hostname of ssh_minion is …
```
> Conditional fixes on running remote command on SSH tunnel minion

- testsuite/features/step_definitions/common_steps.rb
Card https://github.com/SUSE/spacewalk/issues/25001
No difference.
- Unit tests were fixed
Ports:
- Manager-4.3 : I will not port this, as in 4.3 we test rhnpush and we didn't port some other changes. So I prefer to keep 4.3 untouch for the sake of stability. …
> Fix mgrpush assert in order to strip the path of the package parameter

- testsuite/ext-tools/hub-examples/README
- testsuite/ext-tools/hub-examples/auto-authentication.py
- testsuite/ext-tools/hub-examples/install-pkg-all-systems.py
- testsuite/ext-tools/hub-examples/manual-authentication.py
- testsuite/ext-tools/hub-examples/relay-authentication.py
I added some useful snippets to test a Hub environment.
Setting up a Hub environment it's quite resource and time consuming, so I don't consider to automate this for now. These scripts will help to run some basic tests in that kind of environment, if you prepare one manually.
Related to the testing card: https://github.com/SUSE/spacewalk/issues/24175
No difference.
- No tests
Ports:
- Manager-4.3 …
> Hub authentication examples

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/support/env.rb
This PR disables the test for spacecmd on SL Micro.
Ports:
* 4.3: https://github.com/SUSE/spacewalk/pull/25118
> spacecmd is not included on SL Micro

- uyuni/uyuni-storage-setup/uyuni-storage-setup.changes.mc.fix-debugpackage-build
- uyuni/uyuni-storage-setup/uyuni-storage-setup.spec
Disable building debuginfo packages as they will be empty anyway.
Important for other OSes which do not auto-detect this during building
> do not build debuginfo package

- testsuite/features/secondary/srv_content_lifecycle.feature
I assume the failing CLM test in Uyuni is caused by clicking too fast on the "Save" button before the calculation of mandatory child channels is finished.
This PR try to wait until the list is visible by checking for the "Update" channel text
No difference.
- Cucumber tests adapted
Port(s):  …
> try to wait until the list of child channels are visible before clicking on "Save"

- testsuite/features/support/network_utils.rb
- testsuite/features/support/remote_node.rb
Fixing remaining issue on the new Remote Node class
No difference.
No ports, for this particular PR, as all will go in a unique port from qe-develop. …
> QE: Fix wrong return value in scp method

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/file_management.rb
- testsuite/features/support/network_utils.rb
- testsuite/features/support/remote_node.rb
This refactor:
- simplifies the connection with remote nodes
- adds the possibility to run the testsuite from an IDE running in a MacOS
- fixes an issue with temporary files being copied to remote nodes
- Remove a duplicate initialization of the server node
No difference.
No ports, as this goes to qe-develop …
> Refactor Remote Node

- testsuite/features/step_definitions/api_common.rb
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/env.rb
- testsuite/features/support/network_utils.rb
- Add the possibility to force the API protocol that we want to use during a test execution
- Add an extra exception to handle unreachable hosts
- Fix an issue handle the exit code of a ssh call.
- Refactor some remaining calls to Twopence methods
- Remove a not-used step definition
No difference.
- No tests
No ports. It will be ported all together with qe-develop branch. …
> Fixes related to RemoteNode implementation

- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/step_definitions/navigation_steps.rb
Small improvement to fix this issue:
No difference.
Ports:
- Manager-4.3
Check [How …
> Filter by channel in CLM sources, before selecting it

- testsuite/features/build_validation/retail/sle12sp5_terminal_deploy.feature
- testsuite/features/build_validation/retail/sle15sp4_terminal_deploy.feature
- testsuite/features/secondary/proxy_container_retail_pxeboot.feature
- testsuite/features/secondary/proxy_traditional_retail_pxeboot.feature
This change aims to remove a flaky test:
No difference.
No ports, part of qe-develop …
> Find the text of the event, instead of an event completed during last minute

- java/code/src/com/suse/manager/api/DateSerializer.java
- java/code/src/com/suse/manager/api/RouteFactory.java
- java/code/src/com/suse/manager/api/test/RouteFactoryTest.java
- java/spacewalk-java.changes.parlt.fix-http-api-date-format
Change the ouput of `Date` object return values to be in iso8601 format.
There is an issue with the default gson `setDateFormat()` being locale specific, hence it's necessary to manually set the timezone to UTC in a custom serializer.
See here for more info: https://github.com/google/gson/issues/281
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24791
Fixes https://github.com/SUSE/spacewalk/issues/24093 …
> Fix date format when using the HTTP API to use iso8601 date

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes.meaksh.master-reposync-gpgkeys-refactor
This PR refactors the code around GPG keys importing from Spacewalk keyring to the RPM DB that is used by Zypper during `spacewalk-repo-sync` execution:
- GPG keys are processed individually, instead of all in the same file.
- Continue processing keys even if there are errors in some of them. 
- Enhance related import logging.
No difference.
- No tests: **already covered at accepteance tests. No unit tests for GPG keys import**
Issue(s):
- https://github.com/SUSE/spacewalk/issues/23150
- https://github.com/uyuni-project/uyuni/issues/8176 (?)
Ports(s): https://github.com/SUSE/spacewalk/pull/23629
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#chang …
> reposync: import GPG keys to RPM DB individually (bsc#1217003)

- containers/server-image/server-image.changes.rmateus.uyuni_1229923_syncfiles
- containers/server-image/uyuni-configfiles-sync
Fix the error when synchronizing configuration files on image start up. It tries to look for the packages with a find, and the file lists are too long.
No difference.
Before:
After:
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for- …
> Fix package name search when sync volumes data (bsc#1229923)

- testsuite/dockerfiles/server-all-in-one-dev/Dockerfile
- testsuite/dockerfiles/server-all-in-one-dev/minima.yaml
Adds a custom modular repository to the CI containerized server
No difference.
- No tests: only CI setup changes
Issue(s): https://github.com/SUSE/spacewalk/issues/23765
> Add dummy modular repo in the CI containerized server

- spacecmd/spacecmd.changes.agraul.speedup-softwarechannel_removepackages
- spacecmd/src/spacecmd/softwarechannel.py
- spacecmd/src/spacecmd/utils.py
- spacecmd/tests/test_softwarechannel.py
Speedup softwarechannel_removepackages
Instead of converting the list of dictionaries to strings and later find each package db id from the local cache (which needs to be built first), we can build ourselves a dictionary with the same package name string as the key and the id as the value. This approach bypasses building the cache. A request to list all packages for the requested channel takes place either way and did not use the cache.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24775
Port(s): https://github.com/SUSE/spacewalk/pull/24973, https://github.com/SUSE/spacewalk/pull/25203 …
> spacecmd: speedup softwarechannel_removepackages

- susemanager-sync-data/susemanager-sync-data.spec
susemanager-sync-data fails to build after the merge of https://github.com/uyuni-project/uyuni/pull/7509, due to a missing directory.
Add the missing directory to the spec file
No difference.
- No tests: 
Issue(s): #
Port(s): # …
> Fix susemanager-sync-data build

- .github/workflows/build_containers.yml
- testsuite/dockerfiles/server-all-in-one-dev/Dockerfile
Bump the version of the container image we use as base for the CI containerized server
No difference.
- No tests: Just GH CI changes
Issues: https://github.com/SUSE/spacewalk/issues/23765 …
> Update container image version of uyuni/server

- web/html/src/branding/css/base/theme.scss
- web/html/src/manager/salt/cmd/remote-commands.tsx
- web/spacewalk-web.changes.bisht-richa.fixed-find-targets-button-issue
- Fix the `Find target` button behavior for the feature salt > remote commands
- Fix the missing background color for the pending status badge and show/hide the response labels. 
No difference.
Before:
After:
Fixes: https://github.com/SUSE/spacewalk/issues/25108 …
> Fixed find target button bug

- spacecmd/spacecmd.changes.mczernek.spacecmd-bootstrap-fix
- spacecmd/src/spacecmd/system.py
When executing system bootstrap with specified port number, e.g. `system_bootstrap -H suma-new-minion -p 22 -u root -P linux -a 1-sles15-sp5-ssh`, the port number is a string. However, [SystemHandler](https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java#L8379) expects this to be an int.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/25093
Port(s): 
- https://github.com/SUSE/spacewalk/pull/25176
- https://github.com/SUSE/spacewalk/pull/25178 …
> Fix spacecmd type issue during bootstrap

- java/code/webapp/WEB-INF/web.xml
- java/spacewalk-java.changes.mbussolotto.remove_session_timeout
remove session timeout from webapp, in order to use the persisted one in `/etc/tomcat/web.xml`: this would allow to tune it as described https://www.uyuni-project.org/uyuni-docs/en/uyuni/administration/troubleshooting/tshoot-logintimeout.html
No difference.
- Doc needs to be changed from `/usr/share/susemanager/www/tomcat/webapps/rhn/WEB-INF/web.xml`  to `/etc/tomcat/web.xml`
- No tests
Issue(s): https://github.com/uyuni-project/uyuni/issues/8030
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni- …
> remove session timeout from webapp, in order to use the persisted one in /etc/tomcat/web.xml

- .github/workflows/schema-migration-reportdb-test-pgsql.yml
This updates the GitHub Action for checking out Ruby in the CI and fixes the following warning:
```bash
schema_migration_reportdb_test_pgsql
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-ruby@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
No difference.
Issue(s): #
If you don't …
> CI: Use correct GH Action in schema migration tests

- web/html/src/manager/systems/all-list.tsx
- web/spacewalk-web.changes.welder.fix-systems-list-extra-pkg
It was showing wrong value when extra packages count is zero.
No difference.
Issue(s): # …
> Fix Extra Packages column in systems list

- susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.changes.deneb-alpha.drop_proxy-systemd-services
- susemanager-utils/supportutils-plugin-susemanager-client/susemanagerclient
- susemanager-utils/supportutils-plugin-susemanager-client/susemanagerclient-scplugin
Revert supportutils-plugin-susemanager-client changes from uyuni-project/uyuni#9232 due to SUSE/spacewalk#25211
No difference.
- No tests: reverting a previously merged change
Issue(s): https://github.com/SUSE/spacewalk/issues/25211
Port(s): No backports needed. Only the drop of `uyuni-proxy-systemd-services` will have to be ported to `Manager-5.0`
No need to add an additional changelog entry for this. 
If you …
> Revert supportutils-plugin-susemanager-client changes from uyuni-project/uyuni#9232 due to SUSE/spacewalk#25211

- testsuite/features/reposync/srv_create_fake_channels.feature
- testsuite/features/reposync/srv_create_fake_repositories.feature
- testsuite/features/reposync/srv_sync_fake_channels.feature
- testsuite/features/support/constants.rb
Related to https://github.com/SUSE/spacewalk/issues/23765
Depends on:
Add a custom dummy modular repository and the corresponding base channel for it.
They'll later be used to test AppStream features.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23765
Port(s): SUMA 5.0 
If you need to …
> QE: Add dummy AppStream repository and channel

- java/code/src/com/redhat/rhn/common/db/datasource/xml/ErrataCache_queries.xml
- java/spacewalk-java.changes.oholecek.replace-errata-view-by-select
- schema/spacewalk/common/views/suseServerChannelsRetractedPackagesView.sql
- schema/spacewalk/susemanager-schema.changes.oholecek.errata-optimizations
- schema/spacewalk/upgrade/susemanager-schema-5.1.0-to-susemanager-schema-5.1.1/002-errata-view-optimization.sql
Optimize errata view computation by dropping superfluous table joins.
Remove errata usage view completely from computationally intensive errata server cache update.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24426
Port(s): https://github.com/SUSE/spacewalk/pull/25167 …
> Retracted errata query optimizations

- testsuite/features/secondary/minssh_tunnel.feature
This PR fixes a faulty upstream port
Port(s):
* no 4.3, menu entry is correct
* 5.0: change merged together with https://github.com/SUSE/spacewalk/pull/25150
> Menu entry on the left changed with 5.0

- testsuite/features/init_clients/proxy_container.feature
- testsuite/features/reposync/allcli_update_activationkeys.feature
There is no Leap Micro in the cloud. So we need to run with standard openSUSE Leap.
This might break not containerized proxy installation on Leap. 
No difference.
- Cucumber tests were adapted …
> in the cloud uyuni run on Leap while on normal installation with micro

- java/code/src/com/suse/manager/reactor/messaging/JobReturnEventMessageAction.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/spacewalk-java.changes.mc.delay-pkg-refresh-if-needed
Delay the package list refresh when salt was updated to give the daemon time to restart
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23193
Port(s): https://github.com/SUSE/spacewalk/pull/24955 https://github.com/SUSE/spacewalk/pull/25246 …
> Delay pkg refresh if needed

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.mc.Manager-4.3-adapt-bsrepo-15sp6
Package python3-ply seems to be missing in the bootstrap repo when the classic salt-minion package is installed.
No difference.
- No tests: corner case
Port(s): https://github.com/SUSE/spacewalk/pull/24931 https://github.com/SUSE/spacewalk/pull/25004 …
> add missing package python3-ply to bootstrap repo definition

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.dfaltum.master
Modifies the parsing of the authorityKeyIdentifier line according to this issue: https://github.com/uyuni-project/uyuni/issues/9163
Port: https://github.com/SUSE/spacewalk/pull/25028
> Parse openssl3 authorityKeyIdentifier output line differently

- python/uyuni/common/fileutils.py
- python/uyuni/uyuni-common-libs.changes.mc.Manager-4.3-reposync-mkdir-umask
When using umask 077, reposync create directories with 0700 permissions which prevent tomcat from reading these directories.
os.mkdir seems to apply the umask on the given mode. This require an extra os.chmod to enforce the permissions
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/25109 https://github.com/SUSE/spacewalk/pull/25110 …
> enforce directory permissions at repo-sync when creating directories

- java/code/src/com/suse/manager/matcher/MatcherJsonIO.java
- java/spacewalk-java.changes.mc.Manager-4.3-fix-npe-matcher-io
When a system has no base product a NPE can happen when generating the input for the subscription matcher.
Port(s): https://github.com/SUSE/spacewalk/pull/24980
> fix NullPointerException when generating subscription matcher input

- java/code/src/com/redhat/rhn/domain/server/MinionServer.java
- java/code/src/com/redhat/rhn/domain/server/Server.java
- java/code/src/com/suse/manager/webui/services/test/SaltActionChainGeneratorServiceTest.java
- java/spacewalk-java.changes.mc.fix-add-monitoring-ent-to-slemicro
- testsuite/features/init_clients/proxy_container.feature
The Monitoring System Type were not visible for SLE-Micro 5 systems incl. SUSE Manager Proxy 5 .
The same applied for support PTF repositories.
SL-Micro 6 still miss the node_exporter package and cannot be enabled yet.
Issue(s): https://github.com/SUSE/spacewalk/issues/24710
Port(s): https://github.com/SUSE/spacewalk/pull/25082 https://github.com/SUSE/spacewalk/pull/25083 …
> add SLE-Micro 5 to the list of systems which support monitoring

- java/code/src/com/redhat/rhn/frontend/dto/OwnedErrata.java
- java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java
- java/spacewalk-java.changes.serpico.7427-cleanup-truncata-errata
ErrataManager.truncateErrata now tries to clean orphan erratas at the end (erratas with no channel)
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/7427 …
> 7427 cleanup truncata errata

- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/suse/manager/webui/services/impl/SaltSSHService.java
- java/spacewalk-java.changes.mc.Manager-4.3-cleanup-proxy-known_hosts
- proxy/proxy/mgr-proxy-ssh-force-cmd
- proxy/proxy/spacewalk-proxy.changes.mc.Manager-4.3-cleanup-proxy-known_hosts
When a system gets deleted, take care that it is also removed from proxy known_hosts
Port(s): https://github.com/SUSE/spacewalk/pull/25043
> Cleanup proxy known hosts

- testsuite/features/secondary/min_rhlike_openscap_audit.feature
openSCAP tests are failing due to a filename change - this fixes that.
> QE: Fix path for openscap

- web/html/javascript/spacewalk-essentials.js
- web/spacewalk-web.changes.eth.multi-sst
The legacy script that handles sticky headers doesn't account for the fact that some pages may have multiple sections which are sticky header candidates. In the future we want to move this over to a purely CSS solution since [`position: sticky`](https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky) is now widely supported, for the time being this PR fixes the infinite layout expansion bug.
No more infinite scroll.
- No tests: UI bug
https://suse.slack.com/archives/C02D130RBA6/p1726915321046259 …
> Fix sticky header scroll bug

- java/code/src/com/redhat/rhn/frontend/xmlrpc/BaseHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/errata/ErrataHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/errata/test/ErrataHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/provisioning/snapshot/SnapshotHandler.java
- java/code/src/com/suse/manager/api/ApiRequestParser.java
- java/code/src/com/suse/manager/api/ListDeserializer.java
- java/code/src/com/suse/manager/api/MapDeserializer.java
- java/code/src/com/suse/manager/api/test/RouteFactoryTest.java
- java/spacewalk-java.changes.cbbayburt.api-datetime-input
Fix parsing of dates in HTTP API when the argument is a nested element in a struct.
Additionally, this PR refactors some deprecated bits around Gson.
Fixes https://github.com/uyuni-project/uyuni/issues/8269
Check [How to …
> Fix date input on HTTP API endpoints

- python/spacewalk/satellite_tools/appstreams.py
- python/spacewalk/spacewalk-backend.changes.cbbayburt.bsc1230274
Build systems of some RH-like distributions sometimes wrongly output `-1` as an unsigned integer for the `buildorder` property. This causes the upstream library `libmodulemd2-2.13.0` to fail to parse those values.
Since we don't use the `buildorder` property in Uyuni, we can safely ignore these failures. This PR introduces the change to ignore these parsing errors and continue operation without any real side-effect.
- No tests: Already covered
Fixes https://github.com/uyuni-project/uyuni/issues/9123
Fixes https://github.com/SUSE/spacewalk/issues/25209
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projec …
> Ignore 'buildorder' parsing errors when parsing module metadata entries (bsc#1230274)

- containers/proxy-httpd-image/proxy-httpd-image.changes.oholecek.store_proxy_fqdn
- containers/proxy-httpd-image/uyuni-configure.py
- proxy/proxy/broker/rhnBroker.py
- proxy/proxy/rhnShared.py
- proxy/proxy/spacewalk-proxy.changes.oholecek.fix_authtoken_hostname
AuthToken appended FQDN is used also for translating autoyast/ks server FQDN to proxy one. AuthToken thus has to use external FQDN and not internal pod hostname.
This commit introduce this change and also fix for hairpin problem as AuthToken hostname was used for internal connection, which must be localhost (or internal pod hosname) for container scenario.
No difference.
- Cucumber tests were added TBD
Issue(s): https://github.com/SUSE/spacewalk/issues/25231
Port(s): https://github.com/SUSE/spacewalk/pull/25236 …
> Use proxy FQDN from config file for auth token

- java/code/src/com/redhat/rhn/domain/cloudpayg/PaygProductFactory.java
- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerPaygTest.java
- java/spacewalk-java.changes.mc.Manager-4.3-enable-deb-for-payg
- python/spacewalk/satellite_tools/repo_plugins/deb_src.py
- python/spacewalk/spacewalk-backend.changes.mcalmer.enable-deb-for-payg
The RMT Server in the Public Clouds can now provide also Ubuntu and Debian Tools Channels.
With this we can remove the restrictions we had for using Debian like repositories for SUMA PAYG.
Port(s): https://github.com/SUSE/spacewalk/pull/25169 https://github.com/SUSE/spacewalk/pull/24006 …
> Enable deb for payg

- java/code/src/com/redhat/rhn/frontend/action/systems/audit/ScapSetupAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/audit/test/ScapSetupActionTest.java
- java/spacewalk-java.changes.mackdk.openscap-debian12
This PR fixes the package required to run OpenSCAP tests on a Debian 12  and Ubuntu 24.04 systems.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24821
Port(s): https://github.com/SUSE/spacewalk/pull/24996 https://github.com/SUSE/spacewalk/pull/25133 …
> Require correct scap packages for Ubuntu and Debian

- spacecmd/spacecmd.changes.cbbayburt.bsc1227578
- spacecmd/src/spacecmd/kickstart.py
- spacecmd/tests/test_kickstart.py
In `kickstart_delete`, the code first resolves wildcard arguments and returns matching labels. Then it tries to make sure if every arg actually matched a result. But since the original wildcard args don't literally match the resulting labels, the second check throws an error. This PR removes the second check (only exists in this method) to match the method with the rest of the system.
See bug: https://bugzilla.suse.com/show_bug.cgi?id=1227578
Fixes https://github.com/SUSE/spacewalk/issues/24761
If you don't …
> Fix error in 'kickstart_delete' when using wildcards (bsc#1227578)

- susemanager/bin/mgr-setup
- susemanager/susemanager.changes.oholecek.error_exit_update
This PR adds some well-known exit codes for mgrsetup script to be able to differentiate between failures.
No difference.
Issue(s): # …
> Differentiate between error results mgr-setup

- utils/spacewalk-utils.spec
It had an extra '.' in https://github.com/uyuni-project/uyuni/pull/9251/files
No difference.
- No tests
quick fix for https://github.com/uyuni-project/uyuni/pull/9251/files
This is a quick fix for https://github.com/uyuni-project/uyuni/pull/9251/files Changelog is in that PR …
> Fix spacewalk-utils package

- containers/server-image/Dockerfile
- containers/server-image/krb5-conf-setup.sh
- containers/server-image/krb5.conf
- containers/server-image/server-image.changes.oholecek.krb5-persistent-fix
See title.
No difference.
- Documentation issue was created: https://github.com/SUSE/spacewalk/issues/25033
- No tests: not testing kerberos integration
Issue(s): https://github.com/SUSE/spacewalk/issues/25033 …
> Add custom krb5.conf which moved keytab under krb5.conf.d

- java/buildconf/ivy/ivy-suse.xml
Update `hamcrest-library` ~and `hamcrest-core`~ to 3.0 due to `SUSE:Maintenance:35494:343927`
No difference.
- No tests: **for development** …
> Update hamcrest-library to 3.0 due to SUSE:Maintenance:35494:343927

- .devcontainer/test/Dockerfile
Using Ruby 3.3 in Test DevContainer
No difference.
- No tests
Ports:
- Manager-4.3 …
> Using Ruby 3.3 in Test DevContainer

- testsuite/features/support/code_coverage.rb
- testsuite/features/support/remote_node.rb
Change path to store the code coverage report, to be aligned with the pipeline code.
No difference.
- No tests
No ports …
> Change path to store the code coverage report

- .github/workflows/acceptance_tests_common.yml
While working on this other PR: https://github.com/uyuni-project/uyuni/pull/9313 I noticed the acceptance tests were skipped while they supposed to be running.
I noticed there was a problem on the acceptance tests workflow file that is preventing them to run.
After I pushed the changes in this PR to the other PR, then the acceptance tests started working again.
No difference.
- No tests: **this is not a code change** …
> [github] fix problem detecting when to run acceptance tests

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/commonlib.rb
- testsuite/features/support/constants.rb
Fix ubuntu synchronization issues during BV uyuni reposync stage.
```bash
uyuni-bv-master-server:~ # mgrctl exec -i 'spacewalk-common-channels -u admin -p admin --list' | grep ubuntu-2204-pool-amd64-uyuni
ubuntu-2204-pool-amd64-uyuni: amd64-deb
```
No difference.
Port : …
> Fix ubuntu 2004 reposync issue and 2204 reposync issue

- susemanager-sync-data/additional_products.json
- susemanager-sync-data/channel_families.json
- susemanager-sync-data/susemanager-sync-data.changes.mc.Manager-5.0-sles15-sp5-ltss
- add SLES15-SP5-LTSS channel families
- add MicroOS PPC channel family
- set Ubuntu 22.04 to released
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/25463
Check [How to …
> add SLES15-SP5-LTSS channel families

- web/conf/rhn_web.conf
Bump Web UI version to 2024.10 and schema db upgrades for spacewalk and reportdb
For the main schema: migrations are there and are correct
For reportdb: the package didn't change, it's not in tito-wrapper report:
```
raul@mordor:~/Documentos/gh-repos/git-repos-initial-clone/spacewalk_initial_clone/spacewalk (adjust-webui-version_check-migration-paths_2024.10 *$)$ grep ^Version schema/spacewalk/susemanager-schema.spec 
Version:        5.1.0
raul@mordor:~/Documentos/gh-repos/git-repos-initial-clone/spacewalk_initial_clone/spacewalk (adjust-webui-version_check-migration-paths_2024.10 *$)$ ls -la schema/spacewalk/upgrade/susemanager-schema-5.1.0-to-susemanager-schema-5.1.1/
total 8
drwxr-xr-x 1 raul raul   110 oct 10 15:14 .
drwxr-xr-x 1 raul raul 27078 oct 10 15:14 ..
-rw-r--r-- 1 raul raul …
```
> Bump Web UI version to 2024.10 and schema db upgrades for spacewalk and reportdb

- testsuite/Rakefile
fail-fast flag will fail the cucumber testsuite as soon as a step is failing and will not execute the next steps.
We currently use this method for core features and bv init clients. 
I would like to extend this fail fast to init proxy and init monitoring server in BV.
Currently, I have proxy boostrap failing in 5.0 BV and it takes 30 minutes to fail. With this change it takes only 10 minutes.
If a step in those two fails, it will likely get the proxy or monitoring server in a bad shape.
No difference.
Port :
Make sure the changelogs entries you are …
> Add init proxy and init monitoring server to the fail fast tag

- testsuite/features/reposync/srv_sync_products.feature
Fix an issue where 5.0 proxy and 5.0 proxy retail channels were not synchronized at the end of reposync stage in CI
Add wait reposync step to proxy and retail reposync feature.
No difference.
Port:
Issue:  …
> Add wait for reposync for 5.0 proxy and 5.0 proxy retail channels.

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/step_definitions/navigation_steps.rb
Rename step verifying UI after reposync to better reflect the tests.
No difference.
Port:
Issue:  …
> Rename step verifying UI after reposync to better reflect the tests.

- .github/workflows/schema-migration-reportdb-test-pgsql.yml
Adds the explicit Ruby version to the  `schema_migration_reportdb_test_pgsql` workflow to fix:
No difference.
Issue(s): # …
> CI: Fix `schema_migration_reportdb_test_pgsql` workflow

- .github/workflows/yard-doc-test-framework.yml
Using Ruby 3.3 in YARD doc generation
No difference.
- No tests
No ports. …
> Update yard-doc-test-framework.yml to use Ruby 3.3

- testsuite/features/secondary/min_rhlike_appstreams.feature
It includes new Cucumber test scenarios to cover the basic functionality of native appstreams support. 
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24199 …
> Add integration tests for native appstreams

- java/code/webapp/WEB-INF/nav/system_detail.xml
- java/spacewalk-java.changes.nadvornik.foreign_group
- schema/spacewalk/common/data/rhnServerGroupTypeFeature.sql
- schema/spacewalk/susemanager-schema.changes.nadvornik.foreign_group
- schema/spacewalk/upgrade/susemanager-schema-5.1.0-to-susemanager-schema-5.1.1/010-foreign-groups.sql
With this PR it is possible to assign foreign servers and proxies to system groups.
No difference.
- No documentation needed: expected behavior
Issue(s): https://github.com/SUSE/spacewalk/issues/24096
https://bugzilla.suse.com/show_bug.cgi?id=1222447
Check …
> Allow group assignment for foreign servers (bsc#1222447)

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Errata_queries.xml
- java/code/src/com/redhat/rhn/domain/channel/Channel.hbm.xml
- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/redhat/rhn/frontend/action/channel/manage/AddCustomErrataAction.java
- java/code/src/com/redhat/rhn/frontend/action/channel/manage/AddErrataToChannelAction.java
- java/code/src/com/redhat/rhn/frontend/action/channel/manage/AddRedHatErrataAction.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
- java/code/webapp/WEB-INF/pages/channel/manage/adderrataredhat.jsp
- java/spacewalk-java.changes.welder.bsc1228856
When a patch exists in multiple origin channels, SUMA currently doesn’t allow importing from more than one channel. This PR adds a checkbox that allows the user to list the already included patches so that it is possible to import the related packages in case the patch was originally imported from a different channel.
Issue(s): https://github.com/SUSE/spacewalk/issues/25002
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs …
> Allow the listing of already included patches when importing them into a custom channel

- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/spacewalk-backend.changes.welder.fix-reposync-package-errata-link
This PR updates the logic for determining whether an errata requires an update. It introduces a new check that compares the packages associated with the errata in the repository against those in the database. If any package is found in the repository but is not yet reflected in the database, the errata is flagged for an update.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24793 …
> Detect and update errata when not all repository packages are linked

- java/code/src/org/cobbler/Profile.java
- java/code/src/org/cobbler/test/ProfileTest.java
- java/spacewalk-java.changes.cbosdo.cobbler-cast-fix
Getting the list of cobbler profiles happens in two steps:
* calling cobbler's `get_profiles` API to list all the profiles
* calling cobbler's `get_profile` API to get more info on each profile
In between those two calls, some of the profiles could be gone due to concurrent deletion. In such a case `get_profile` will return `"~"` which means `null`.
Filter out the `"~"` returns to avoid the class cast exception and better reflect reality.
Issue(s): https://github.com/SUSE/spacewalk/issues/24846
Port(s): …
> Safer cobbler get_profile cast

- testsuite/features/support/env.rb
This Cucumber tag will fail a scenario including this tag.
That can be useful to skip some scenarios that we know that will fail, speeding up the test results.
No difference.
Ports:
- Manager-4.3
If you …
> New Cucumber tag to fail a scenario without running it, useful for some known issues

- java/code/webapp/WEB-INF/nav/system_detail.xml
- java/spacewalk-java.changes.mc.Manager-5.0-coco-attestation-salt-ssh
- testsuite/features/secondary/min_deblike_openscap_audit.feature
- testsuite/features/secondary/min_rhlike_openscap_audit.feature
- testsuite/features/secondary/min_salt_openscap_audit.feature
The Audit Tab with the Confidential Compute Attestation pages are only visible for salt managed clients with default contact method. This was done as OpenSCAP scans can only be done with a minion installed.
But CoCo attestation works also with salt-ssh managed systems. Show this also for these kind of clients.
Port(s): https://github.com/SUSE/spacewalk/pull/25389 …
> show Confidential Compute Attestation tab also for salt ssh managed clients

- python/spacewalk/satellite_tools/appstreams.py
- python/spacewalk/spacewalk-backend.changes.cbbayburt.appstream-ver-fix
- python/test/unit/spacewalk/satellite_tools/test_appstreams.py
Support '^' in RPM version string when importing appstreams during reposync.
Fixes https://github.com/uyuni-project/uyuni/issues/9211
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-b …
> Support '^' in RPM version string when importing appstreams

- java/code/src/com/redhat/rhn/domain/notification/NotificationMessage.java
- java/code/src/com/redhat/rhn/domain/notification/types/ChannelSyncFailed.java
- java/code/src/com/redhat/rhn/domain/notification/types/ChannelSyncFinished.java
- java/code/src/com/redhat/rhn/domain/notification/types/CreateBootstrapRepoFailed.java
- java/code/src/com/redhat/rhn/domain/notification/types/EndOfLifePeriod.java
- java/code/src/com/redhat/rhn/domain/notification/types/OnboardingFailed.java
- java/code/src/com/redhat/rhn/domain/notification/types/PaygAuthenticationUpdateFailed.java
- java/code/src/com/redhat/rhn/domain/notification/types/PaygNotCompliantWarning.java
- java/code/src/com/redhat/rhn/domain/notification/types/StateApplyFailed.java
- java/code/src/com/redhat/rhn/domain/notification/types/SubscriptionWarning.java
- java/code/src/com/redhat/rhn/domain/notification/types/UpdateAvailable.java
- java/code/src/com/redhat/rhn/domain/notification/types/test/UpdateAvailableTest.java
- java/spacewalk-java.changes.cbosdo.notification-fix
After the Java 17 update the Gson introspection raises an error when
parsing the runtime field. Since this field is only for testing, mark it
as transient to skip it during serialization and deserialization.
No difference.
- No tests: For some reason the unit test I could come up with didn't trigger the error, only a real environment did.
Issue(s): https://github.com/SUSE/spacewalk/issues/24905
Port(s): https://github.com/SUSE/spacewalk/pull/25471
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelog …
> UpdateAvailable notification parsing fix

- containers/server-image/Dockerfile
- containers/server-image/server-image.changes.oholecek.add_missing_grub_efis
Grub was missing loaders for other architectures then AMD64. This PR adds loaders for AArch64 and PPC64le.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/25562
Port(s): https://github.com/SUSE/spacewalk/pull/25561
If you don't …
> Add aarch64 and ppc64 grub loaders

- java/code/src/com/redhat/rhn/domain/action/ActionFactory.java
- java/code/src/com/redhat/rhn/domain/action/server/ServerAction.hbm.xml
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/spacewalk-java.changes.mc.improve-handling-of-job-returns
When we handle uptime values, we check for reboot actions which needs to be marked as COMPLETED.
We load all actions for the system and iterate over them to look for type REBOOT.
This is inefficient, a all actions needs to be rendered.
This PR query the DB only for a list of action types which should really be checked.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/25253
If …
> improve cleanup of reboot actions

- java/code/src/com/redhat/rhn/frontend/events/TraceBackAction.java
- java/code/src/com/redhat/rhn/taskomatic/task/TaskHelper.java
- java/spacewalk-java.changes.mcalmer.fix-hostname-in-mail-title
InetAddress.getLocalHost().getHostName() just get the internal container network FQDN name.
This is fix to `uyuni-server.mgr.internal ` and does not help to identify the origin of the error if you run multiple instances.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/25405
If you need to …
> use external hostname in email subject

- java/code/src/com/redhat/rhn/frontend/taglibs/list/ListTagUtil.java
- java/spacewalk-java.changes.eth.fa2
- web/html/src/branding/css/susemanager/components/icons.less
- web/html/src/branding/css/susemanager/components/icons.scss
- web/html/src/branding/css/susemanager/index.less
- web/html/src/branding/css/susemanager/index.scss
- web/spacewalk-web.changes.eth.fa2
The previous fix for missing pagination buttons in https://github.com/uyuni-project/uyuni/pull/8771 only fixes missing icons in views that use that specific Java class for rendering. This PR reverts that change and makes the global font icon styles overrule font styles we inherit from Bootstrap.
Before:
After:
- No tests: UI bugfix
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1231378
If …
> Fix font icon style assignment (bsc#1231378)

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/api/ApiHandler.java
- java/code/src/com/suse/manager/api/HttpApiRegistry.java
- java/code/src/com/suse/manager/webui/controllers/login/LoginController.java
- java/code/src/com/suse/scc/client/SCCRequestFactory.java
- java/code/src/com/suse/scc/client/SCCWebClient.java
- java/spacewalk-java.changes.mc.Manager-5.0-fix-reportdb-update-with-container
- schema/spacewalk/common/tables/rhnActionApplyStates.sql
- schema/spacewalk/susemanager-schema.changes.mc.Manager-5.0-fix-reportdb-update-with-container
- schema/spacewalk/upgrade/susemanager-schema-5.1.1-to-susemanager-schema-5.1.2/002-rhnActionApplyStates.sql
- susemanager-utils/susemanager-sls/Makefile.python
- susemanager-utils/testing/automation/susemanager-sls-tests.sh
Forward porting parts of https://github.com/SUSE/spacewalk/pull/25586 which should stay in master.
The reportdb handling will be handled in a different PR.
This introduce only the new API endpoint for the product name and the database column for direct call
as it is specified in 5.0
No difference.
Partial Port(s) of : https://github.com/SUSE/spacewalk/pull/25586 …
> Add productname api

- web/html/src/manager/systems/ssm/ssm-subscribe-channels.tsx
- web/html/src/manager/systems/subscribe-channels/subscribe-channels.tsx
Add a key property in multiple elements, this fixes #8729  
No difference.
Issue(s): #8729
> Add React keys in subscribe-channels (issue #8729)

- java/code/src/com/redhat/rhn/common/conf/Config.java
- java/spacewalk-java.changes.mackdk.avoid-config-exception
- microservices/uyuni-java-common/src/main/java/com/suse/common/configuration/FileConfigurationSource.java
- microservices/uyuni-java-common/uyuni-java-common.changes.mackdk.avoid-config-exception
This PR introduces the following changes:
- avoids an exception that might happen when trying to parse a missing or unreadable configuration file.
- improves the code for handling the configuration by using `Path` instead of `File`.
-  fixes a problem in the `uyuni-java-common` module, where the streams obtained through `Files.list()` were not correctly closed and might lead to a memory leak.
No difference.
If …
> Avoid configuration exception for missing or unreadable files

- testsuite/features/step_definitions/api_common.rb
Having a different e-mail for each of the generated users per feature is causing a "Too many recipients" issue.
Therefore, we will re-use the same e-mail.
No difference.
Ports:
- Manager-5.0 https://github.com/SUSE/spacewalk/pull/25579
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/25580
If you …
> QE: Use the same e-mail for all users created through the test framework

- microservices/coco-attestation/attestation-core/src/main/java/com/suse/coco/CoCoAttestation.java
- microservices/coco-attestation/attestation-core/src/main/java/com/suse/coco/attestation/AbstractProcessorThread.java
- microservices/coco-attestation/attestation-core/src/main/java/com/suse/coco/attestation/AttestationQueueProcessor.java
- microservices/coco-attestation/attestation-core/src/main/java/com/suse/coco/attestation/ListeningThread.java
- microservices/coco-attestation/attestation-core/src/main/java/com/suse/coco/attestation/ProcessingThread.java
- microservices/coco-attestation/attestation-core/src/package/coco-attestation.sh
- microservices/coco-attestation/attestation-core/src/package/log4j2.xml
- microservices/coco-attestation/attestation-core/src/test/java/com/suse/coco/attestation/AttestationQueueProcessorTest.java
- microservices/coco-attestation/uyuni-coco-attestation.changes.mackdk.shutdown-attestation-service-gracefully
This PR refactors the attestation queue processor to allow shutting it down after being started. It also handles the shutdown hook to properly close all connections and running threads when java receives a `SIGTERM` or `SIGINT` signal. It also disables the Log4j internal hook because it was interfering with the new one. The logging framework shutdown is called explicitly after the processing is terminated.
Note: this PR is currently built on top of https://github.com/uyuni-project/uyuni/pull/8678, which should be merged before this one. After that, this branch should be rebased.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24452 …
> Shutdown attestation service gracefully

- SECURITY.md
- testsuite/Rakefile
Solves the issue with the following result from rubocop running pipeline result:
```
+ export PRODUCT=SUSE-Manager
+ PRODUCT=SUSE-Manager
+ gitarro.ruby2.5 -r SUSE/spacewalk -c ruby_rubocop -d rubocop checkstyle -f testsuite/ -t /var/lib/jenkins/workspace/manager-prs-ruby_rubocop-pipeline/jenkins_pipelines/manager_prs/tests_files/rubocop.sh -g /var/lib/jenkins/workspace/manager-prs-ruby_rubocop-pipeline -u https://ci.suse.de/job/manager-prs-ruby_rubocop-pipeline/58493/ -P 25633
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
/usr/lib64/ruby/gems/2.5.0/gems/faraday-0.17.3/lib/faraday/upload_io.rb:65: warning: constant …
```
> Rubocop Rakefile fixes

- susemanager-utils/susemanager-sls/modules/pillar/suma_minion.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.meaksh.Manager-4.3-bsc1228232
- susemanager-utils/susemanager-sls/test/test_pillar_suma_minion.py
- testsuite/features/secondary/srv_salt_git_pillar.feature
- testsuite/features/step_definitions/salt_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/upload_files/salt_git_pillar_setup.sh
- testsuite/run_sets/secondary.yml
This PR fixes an issue with that can be seen in certain scenarios, where multiple `ext_pillar` modules are configured (particularly in combination with `git_pillar` module) and a pillar compilation is triggered via Salt Runner execution.
Under these circunstances, we see the following exception happening:
```
[ERROR   ] Exception caught loading ext_pillar 'git':
File "/usr/lib/python3.6/site-packages/salt/pillar/__init__.py", line 1200, in ext_pillar
ext = self._external_pillar_data(pillar, val, key)
File "/usr/lib/python3.6/site-packages/salt/pillar/__init__.py", line 1130, in _external_pillar_data
ext = self.ext_pillars[key](self.minion_id, pillar, *val)
File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
return self.loader.run(run_func, *args, **kwargs) …
```
> suma_minion: prevent issues when calling Salt runners (bsc#1228232)

- susemanager-utils/susemanager-sls/src/modules/reboot_info.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.meaksh.master-bsc1231404
This PR just prevent a crash when scheduling "Package List Refresh" action, as `reboot_info.reboot_required` function was raising an Exception:
```
Error running 'reboot_info.reboot_required': Unable to run command '['dnf', '-q', 'needs-restarting', '-r']' with the context '......', reason: command not found
```
The reason is that `osmajorrelease` grain in old Salt 2016.11.10 (used in this OS) is rendered as string instead of integer, making the current logic not to work.
No difference.
- No tests: **no active testing on rhel6 and clones**
Issue(s): https://github.com/SUSE/spacewalk/issues/25460
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#chang …
> Prevent a crash on Liberty 6 and RHEL 6 clones (bsc#1231404)

- utils/spacewalk-hostname-rename
- utils/spacewalk-utils.changes.meaksh.master-bsc1229848
This PR forces `spacewalk-hostname-rename` to perform an explicit login to `spacecmd` in order to have an active session when running the "refreshing pillar data for minions" stage of this script.
There is an issue currently at refreshing pillar data for minions stage, which may lead to having a stuck execution when the "spacecmd" session is expired, as the call to "spacecmd" hides the login prompt, making the user to feel that the script is stuck while it is waiting for reading input credentials from the user (but not visible).
This PR, just performs the login to "spacecmd" explicitely, before this stage, so we know the session is active and the login prompt is not hidden.
No difference.
- No tests: **user case not …
> Force the spacecmd login when running "spacewalk-hostname-rename" (bsc#1229848)

- java/code/src/com/redhat/rhn/common/ErrorReportingStrategies.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/proxy/ProxyHandler.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/redhat/rhn/manager/system/SystemManagerUtils.java
- java/code/src/com/redhat/rhn/manager/system/proxycontainerconfig/ProxyContainerConfigCreate.java
- java/code/src/com/redhat/rhn/manager/system/proxycontainerconfig/ProxyContainerConfigCreateAcquisitor.java
- java/code/src/com/redhat/rhn/manager/system/proxycontainerconfig/ProxyContainerConfigCreateContext.java
- java/code/src/com/redhat/rhn/manager/system/proxycontainerconfig/ProxyContainerConfigCreateContextHandler.java
- java/code/src/com/redhat/rhn/manager/system/proxycontainerconfig/ProxyContainerConfigCreateGenerateFileMaps.java
- java/code/src/com/redhat/rhn/manager/system/proxycontainerconfig/ProxyContainerConfigCreateTarCreate.java
- java/code/src/com/suse/manager/webui/controllers/ProxyController.java
- java/spacewalk-java.changes.rjpmestre.chained_container_proxies_configuration_refactor
Introduces the Chain of Responsibility pattern to streamline the creation of a proxy container configuration file. This  enhances code readability as we extracted a portion of code from the SystemManager class (which was dedicated to this flow) and relocated it into a dedicated structures with clear and defined steps. Additionally, it also improves testability as each step has a narrow scope.
No difference.
- No documentation needed: we commented each object/step with their purpose
Related:
- https://github.com/uyuni-project/uyuni/pull/8634
- https://github.com/uyuni-project/uyuni/issues/8157 …
> Chained container proxies configuration refactor

- java/buildconf/build-props.xml
- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
- java/code/src/com/redhat/rhn/common/util/StringUtil.java
- java/code/src/com/redhat/rhn/frontend/action/audit/AuditSearchAction.java
- java/code/src/com/redhat/rhn/frontend/action/channel/manage/EditChannelAction.java
- java/code/src/com/redhat/rhn/frontend/action/schedule/ActionChainSaveAction.java
- java/code/src/com/redhat/rhn/frontend/action/schedule/test/ActionChainSaveActionTest.java
- java/code/src/com/redhat/rhn/frontend/struts/ActionChainHelper.java
- java/code/src/com/redhat/rhn/frontend/struts/test/ActionChainHelperTest.java
- java/spacewalk-java.changes.mackdk.drop-stringtree
- java/spacewalk-java.spec
This PR replaces the usages of `stringtree-json` `JSONWriter` and `JSONReader` with calls to existing gson conversion methods.
No difference. …
> Remove stringtree-json dependency in favor of google gson

- testsuite/features/build_validation/migration/sle15sp3_minion_migration.feature
- testsuite/features/build_validation/migration/sle15sp3_ssh_minion_migration.feature
It takes care of installing the latest OS Salt on the SLE 15 SP3 SSH minion we use to test product migration.
This is needed because we use a pristine image with an old version of it and the Product Migration feature requires the latest to be installed.
It also removes scenarios relying on a Salt file that is not present on the SLES 15 SP3 minions.
`/root/salt` and the `repos` Salt states are only found on the server 
No difference.
Port(s): 
- 4.3: https://github.com/SUSE/spacewalk/pull/25655
- 5.0: https://github.com/SUSE/spacewalk/pull/25656 …
> QE: correctly upgrade Salt in product migrations

- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/spacewalk-java.changes.mackdk.reportdb-ensure-lowercase-username
- schema/spacewalk/susemanager-schema.changes.mackdk.reportdb-ensure-lowercase-username
- schema/spacewalk/upgrade/susemanager-schema-5.1.1-to-susemanager-schema-5.1.2/000-convert-reportdb-users-to-lowercase.sql
This PR make sure the username we generate for the reporting database is always lowercase. This prevents a mismatch between java, bash and salt.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/23817
Ports(s): https://github.com/SUSE/spacewalk/pull/25617 https://github.com/SUSE/spacewalk/pull/25449 …
> Ensure the reporting database username is lowercase

- java/buildconf/build-props.xml
- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
- java/code/src/com/redhat/rhn/common/messaging/MessageQueue.java
- java/code/src/com/redhat/rhn/taskomatic/task/HubReportDbUpdateDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/errata/ErrataCacheDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/errata/ErrataQueueDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/ChannelRepodataDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/ChannelRepodataWorker.java
- java/code/src/com/redhat/rhn/taskomatic/task/sshservice/SSHServiceDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/systems/SystemsOverviewUpdateDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/ChannelRepodataTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/threaded/AbstractQueueDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/threaded/QueueDriver.java
- java/code/src/com/redhat/rhn/taskomatic/task/threaded/TaskQueue.java
- java/code/src/com/redhat/rhn/taskomatic/task/threaded/TaskQueueFactory.java
- java/code/src/com/redhat/rhn/taskomatic/task/threaded/TaskThreadFactory.java
- java/licenses/concurrent.txt
- java/spacewalk-java.changes.mackdk.drop-concurrent
- java/spacewalk-java.spec
This PR removes the dependency on concurrent since those APIs have been part of standard java since version 1.5. This PR also improves the `QueueDriver` interface and decouple the handling logic so that `TaskQueue` no longer requires knowledge of the `QueueDriver` implementation details.
No difference.
If …
> Remove concurrent dependency in favor of java.util.concurrent

- containers/server-image/pam-susemanager-account
- containers/server-image/pam-susemanager-auth
- containers/server-image/pam-susemanager-password
- containers/server-image/pam-susemanager-session
- containers/server-image/server-image.changes.oholecek.remove_pam_ldap
- spacewalk/config/spacewalk-config.changes.oholecek.remove_pam_ldap
- spacewalk/config/usr/share/man/man5/rhn.conf.5
pam_ldap was deprecated in SLE15PS3 in favor of sssd, having it in our pam configuration cause login errors
No difference.
- No documentation needed: valid method already documented
Issue(s): https://github.com/SUSE/spacewalk/issues/25665
Port(s): https://github.com/SUSE/spacewalk/pull/25682 …
> Remove pam_ldap config as it is not longer shipped

- java/code/src/com/suse/manager/webui/utils/ViewHelper.java
- java/code/webapp/WEB-INF/pages/ssm/systems/misc/index.jsp
- java/spacewalk-java.changes.eth.all-view
- web/html/src/branding/css/base/theme.scss
- web/html/src/branding/css/susemanager/components/buttons.suma.scss
- web/html/src/branding/css/susemanager/components/lists.scss
- web/html/src/branding/css/susemanager/components/mark.scss
- web/html/src/branding/css/susemanager/components/tables.scss
- web/html/src/branding/css/susemanager/index.scss
- web/html/src/build/webpack.config.js
- web/html/src/components/virtual-list/VirtualList.module.less
- web/html/src/components/virtual-list/VirtualList.tsx
- web/html/src/core/spa/view-helper.ts
- web/html/src/manager/content-management/shared/components/panels/sources/channels/channels-selection.module.css
- web/html/src/manager/content-management/shared/components/panels/sources/channels/channels-selection.tsx
- web/spacewalk-web.changes.eth.all-view
Make Bootstrap 5 styles the default for remaining pages.  
Also, fixes some small issues I found in testing the last pages.  
This PR intentionally does not cut out the toggling logic we have, in case we need it before we wrap up the whole thing.
All pages not yet migrated are affected.
- No documentation needed: Docs issue already exists. …
> Make Bootstrap 5 styles the global default

- testsuite/features/build_validation/init_clients/slemicro51_minion.feature
- testsuite/features/build_validation/init_clients/slemicro52_minion.feature
- testsuite/features/build_validation/init_clients/slemicro53_minion.feature
- testsuite/features/build_validation/init_clients/slemicro54_minion.feature
- testsuite/features/build_validation/init_clients/slemicro55_minion.feature
- testsuite/features/build_validation/init_clients/slmicro60_minion.feature
- testsuite/features/step_definitions/command_steps.rb
During 5.0.2, I can see that sometime I still have the Pending for reboot message when looking at the screenshot.
In the code, we are rebooting the slemicro after each actions so I added a step to detect this message after reboot.
Those changes are mainly for improving our test coverage.
Add check after ssh reboot for venv-salt-minion service
Add check after reboot by web interface to see if pending message visible.
Port(s): 
- 5.0 : https://github.com/SUSE/spacewalk/pull/25687
- 4.3 : https://github.com/SUSE/spacewalk/pull/25688
Make sure the …
> Add check after ssh reboot for venv-salt-minion service

- testsuite/features/profiles/Kiwi/POS_Image-JeOS6_head/config.xml
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_uyuni/config.xml
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS6_head/config.xml
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_uyuni/config.xml
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_head/config.xml
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_uyuni/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_head/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_head/config.xml
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_uyuni/config.xml
Card: https://github.com/SUSE/spacewalk/issues/25658
In our new MUs 5.0.2 and 4.3.14 we announce that the POS images will be compressed.
That's done just by a change in the kiwi profiles, there is no product code changed.
But the customers are using a set of kiwi profiles different than those that we use in our test framework, therefore we need to adapt our kiwi profiles too.
No difference.
- No tests
No ports.
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyu …
> QE: Kiwi compressed images

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.mc.Manager-5.0-res7ltss-optional-dmidecode
Mark additional packages as optional.
Liberty 7 LTSS for OL do not have all the packages in the repo and generating the bootstrap repo fails for this.
With marking them optional they can be ignored without producing error messages.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/25485
If you …
> mark dmidecode and logrotate as optional for Liberty 7 LTSS

- java/code/src/com/redhat/rhn/domain/channel/AccessTokenFactory.java
- java/code/src/com/redhat/rhn/domain/kickstart/KickstartableTree.java
- java/code/src/com/redhat/rhn/domain/server/MinionServer.java
- java/code/src/com/redhat/rhn/domain/server/MinionServerFactory.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/test/ChannelSoftwareHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/MinionActionExecutor.java
- java/code/src/com/suse/manager/reactor/messaging/ChannelsChangedEventMessageAction.java
- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectSourcesApiController.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/manager/webui/services/test/SaltServerActionServiceTest.java
- java/spacewalk-java.changes.mc.adapt-channel-change
Currently we have 2 ways in the code how channels are changed.
1. One is changing the channels first in the Database and send it out to the client after it was changed.
2. The other way (new) we send the new channels out to the client first and only when the change was performed on the client successfully, we adapt the channels in the database.
The first (old) way has the benefit, that also offline clients change the channels and it can be changed on the client also later by just applying the channel state. 
The 2nd way is complicated as new access tokens needs to be generated, but the channel pillar data needs to be manually compiled and send via the state.apply instead of using the standard way by reading the database.
Offline minions will not change the channels at all which is a …
> Adapt channel change

- testsuite/features/support/env.rb
Card https://github.com/SUSE/spacewalk/issues/25606
No difference.
Ports:
- Manager-5.0 …
> Fix the format of the command in print_server_logs function

- containers/server-image/krb5.conf
- containers/server-image/server-image.changes.oholecek.fix-krb-ccache
Use FILE type which is ccache default anyway.
No difference.
Issue(s): # …
> KRB cannot use KEYRING ccache type in container

- .github/CODEOWNERS
Assign default reviewers for the workflows.
We should probably add more contributors. If you have ideas, please ping me and I will add them to https://github.com/orgs/uyuni-project/teams/workflows-reviewers/members
No difference.
- No documentation needed: `CODEOWNERS`changes
- No tests:  `CODEOWNERS`changes
As agreed at https://github.com/SUSE/spacewalk/issues/25344 …
> Assign default reviewers for the workflows

- java/code/src/com/redhat/rhn/frontend/taglibs/list/AlphaBarHelper.java
- java/code/webapp/WEB-INF/decorators/layout_head.jsp
- java/code/webapp/WEB-INF/includes/header.jsp
- java/code/webapp/WEB-INF/pages/admin/setup/mirror-credentials-list.jsp
- java/code/webapp/WEB-INF/pages/admin/setup/mirror-credentials.jsp
- java/code/webapp/WEB-INF/pages/common/fragments/kickstart/kickstart-rules.jspf
- java/code/webapp/WEB-INF/pages/schedule/actionchain.jsp
- java/code/webapp/WEB-INF/pages/ssm/systems/deleteconfirmdialog.jspf
- web/html/src/branding/css/base/setup-wizard.less
- web/html/src/branding/css/base/setup-wizard.scss
- web/html/src/branding/css/susemanager/components/buttons.suma.scss
- web/html/src/branding/css/susemanager/components/dropdown-menu.scss
- web/html/src/branding/css/susemanager/index.scss
- web/html/src/build/webpack.config.js
- web/html/src/components/buttons.tsx
- web/html/src/components/dialog/Dialog.tsx
- web/html/src/components/panels/Panel.tsx
- web/html/src/components/popup.tsx
- web/html/src/components/states-picker.tsx
- web/html/src/manager/content-management/shared/components/panels/build/build-version.tsx
- web/html/src/manager/systems/ssm/ssm-subscribe-channels.tsx
- web/html/src/styleguide/template.js
- web/spacewalk-web.changes.eth.global-scripts
Followup to https://github.com/uyuni-project/uyuni/pull/9417, this PR switches the global Bootstrap related scripts over from 3 to 5.
I'm still checking the remainder of places where we use data attributes, but the change will be the same everywhere it's affected.
No difference.
- No documentation needed: documentation issue already exists for the migration.
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-project …
> Make Bootstrap 5 scripts the global default

- java/conf/rhn_java.conf
- java/spacewalk-java.changes.mc.prepare51
- java/spacewalk-java.spec
- java/tito.props
- python/spacewalk/spacewalk-backend.changes.mc.prepare51
- python/spacewalk/tito.props
- enable beta client tools usage
- set product_tree_tag to SUMA5.1
- require 5.1 database schema versions
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/24491
Check [How …
> Prepare packages for SUSE Manager 5.1

- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/support/quality_intelligence.rb
- Moving of sync duration to the end of the feature
- Fix an issue with the parameter type into Prometheus client
No difference.
Ports:
- Manager-5.0 https://github.com/SUSE/spacewalk/pull/25757
If you …
> QI: Moving reporting of sync duration to the end of the feature and fixing a wrong type.

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/reposync/srv_sync_products.feature
Correctly wait for the Setup Wizard page to be loaded before starting checking for errors during reposync.
No difference.
Port(s):
- 4.3: https://github.com/SUSE/spacewalk/pull/25758
- 5.0: https://github.com/SUSE/spacewalk/pull/25759 …
> QE: wait for the Setup Wizard page to be ready

- spacewalk/setup/bin/spacewalk-setup
- spacewalk/setup/spacewalk-setup.changes.cbosdo.setup-cleanup
- susemanager/bin/mgr-setup
- susemanager/susemanager.changes.cbosdo.setup-cleanup
Since Uyuni and SUSE Manager are now only shipped in containers there is only one use case of mgr-setup called from mgradm: mgr-setup -s -n. All other flags can go away... even those flags can be removed once mgradm stops using them as they will be the only behavior.
- No tests: setup script is only covered with end-to-end tests
Issue(s): #
If you need to …
> Remove now unused code from mgr-setup

- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerProvisioningTest.java
- java/code/src/com/redhat/rhn/testing/RhnMockHttpServletRequest.java
- java/spacewalk-java.changes.oholecek.add_proxy_api_provisioning
Using web ui it is possible to schedule system provisioning through specific proxy. This is not possible using any API call. This commit adds this missing provisionSystem API call and related unit tests.
Automatic proxy detection based on request headers is preserved.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/25636 …
> Add provisionSystem API with proxy option

- testsuite/features/step_definitions/command_steps.rb
I have this issue:
```hcl
uyuni-ci-master-podman-server:~ # mgrctl exec -i 'pkill --full fake_ipmi_host.sh || :'
uyuni-ci-master-podman-server:~ # echo $?
143
```
So I ignore the errors for `get_target('server').run('pkill --full fake_ipmi_host.sh')`
If one of the IPMI Power management features is failing, it will keep `ipmi_sim` process running. The next feature will try to start again this `ipmi_sim` process. In this situation, the command `ipmi_sim -n < /dev/null > /dev/null &` will be executed and wait for the previous process to stop ( nothing will stop the process ). The command will not return any code and the ssh connection will die. This situation will not be detected by the ssh timeout and the testsuite will stay stuck forever at this stage.
Use nohup command to start the …
> Improve starting ipmi_sim program

- testsuite/features/support/system_monitoring.rb
Don't raise an error for now, if a reposync.log is not processed correctly.
Instead, add some more debugging logs.
No difference.
Ports:
- Manager-5.0 https://github.com/SUSE/spacewalk/pull/25773
If you …
> Don't raise an error for now, if a reposync.log is not processed correctly

- testsuite/features/support/system_monitoring.rb
Handle the different output depending the API protocol for event_details
No difference.
Ports:
- Manager-5.0 …
> Handle the different output depending the API protocol for event_details

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/commonlib.rb
- testsuite/features/support/metrics_collector_handler.rb
- testsuite/features/support/system_monitoring.rb
- Make a deep copy when we retrieve the value of a map
- Add more logs when processing and pushing metrics
No difference.
Ports:
- Manager-5.0 https://github.com/SUSE/spacewalk/pull/25785
If you need …
> Make a deep copy of a map value and add more logs when processing and pushing metrics

- susemanager-utils/susemanager-sls/salt/bootstrap/init.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.vzhestkov.fix-wrong-master-key-on-rebootstrap
In case if the minion was registered before for the other master on bootstrapping it will not be able to connect to the master due to key verification fail.
Bootstrapping with the script was already fixed with https://github.com/uyuni-project/uyuni/pull/8967
No difference.
If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the Cucumber test suite
Issue(s): # …
> Fix wrong master key on rebootstrap

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/reposync/srv_sync_products.feature
- testsuite/features/support/constants.rb
Uyuni product synchronized for proxy is not correct.
No difference.
Port:
Issue:  …
> Fix uyuni proxy sync

- java/code/src/com/suse/manager/webui/controllers/FrontendLogController.java
- java/spacewalk-java.changes.kwalter.bsc1231900
This limits the message size accepted by the frontend-log message endpoint.
- No tests:
Issue(s): #
Port(s):  https://github.com/SUSE/spacewalk/pull/25661 https://github.com/SUSE/spacewalk/pull/25660 …
> limit frontend-log message size (bsc#1231900)

- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/UserSerializer.java
- java/spacewalk-java.changes.renner.fix-users-enabled-flag
This should fix the `enabled` flag for users when listed via the API, using for example the `user.listUsers()` call. Enabled obviously means not disabled, which seemed to be a small issue in the `UserSerializer` class.
No difference.
- No documentation needed, this should work as expected now.
Issue(s): #
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1233431 …
> Fix the enabled flag for users listed via API (bsc#1233431)

- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/test/UserSerializerTest.java
After fixing a bug in there this week (see #9483), I'd like to add a small unit test to cover for the functionality in `UserSerializer`.
No difference.
- No documentation needed, just test code in this PR.
- This is adding a test for existing functionality.
Issue(s): This is an addon for https://github.com/uyuni-project/uyuni/pull/9483
Port(s):
- https://github.com/SUSE/spacewalk/pull/25822 (`Manager-5.0`)
- https://github.com/SUSE/spacewalk/pull/25824 (`Manager-4.3`) …
> Add a test for the UserSerializer class

- web/html/src/package.json
- web/html/src/yarn.lock
Following https://github.com/uyuni-project/uyuni/pull/9220 we don't actually rely on `react-styleguidist` as a dependency anywhere, this PR removes it from our package.
No difference.
- No documentation needed: remove unused code
- No tests: remove unused code
Followup to https://github.com/uyuni-project/uyuni/pull/9220 …
> Drop unused dependency `react-styleguidist`

- proxy/proxy/salt-broker/salt-broker
- proxy/proxy/spacewalk-proxy.changes.vzhestkov.salt-broker-no-strict-spacewalk-req
`salt-broker` is using `spacewalk` lib just to read 1 config parameter (`rhn_parent`) from `rhn.conf` which is filled with extra script in the containerised deployment. It would be way easier to put `master` config to the broker config instead and the container with the `salt-broker` could become bit lighter due to unneeded `spacewalk` libraries in it.
No difference.
Issue(s): # …
> Make salt-broker less dependant on spacewalk libs

- proxy/proxy/salt-broker/salt-broker
- proxy/proxy/spacewalk-proxy.changes.vzhestkov.implement-ipv6-for-salt-broker
`salt-broker` was unable to handle IPv6 connections from minions to the master.
This PR implements IPv6 support for `salt-broker`
No difference.
Tracks: https://github.com/SUSE/spacewalk/issues/24752
Issue(s): # …
> Add IPv6 support for salt-broker (bsc#1227827)

- .github/workflows/changelogs.yml
- .github/workflows/changelogs/README.md
- .github/workflows/changelogs/changelogs.py
- .github/workflows/changelogs/test_changelogs.py
- .github/workflows/changelogs/trackers.xml
A complete overhaul of the changelog validation workflow, introducing many enhancements over the existing GitHub action.
- Validation is done by a standalone script (`.github/workflows/changelogs/changelogs.py`)
- Checks if the changelog is added to the correct package
- Performs basic checks against typos, spacing, capitalization, whitespace, and line length issues
- Ensures correct spelling of tracker IDs (bsc#, jira-#, etc.) mentioned in the changelogs
- Matches mentioned tracker IDs against the PR title and commit messages
- Verifies that a bug exists and belongs to "SUSE Manager" in `bugzilla.suse.com`
- Pinpoints the exact location of an issue in a changelog file
- Recognizes every type of tracker as defined by OBS/IBS (see: `.github/workflows/changelogs/trackers.xml`)
- Inline …
> Enhanced changelog validation

- proxy/proxy/salt-broker/salt-broker
- proxy/proxy/spacewalk-proxy.changes.vzhestkov.make-salt-broker-master-ip-change
In some cases `salt-broker` could got stuck trying to connect to the `salt-master` with the old IP address of it, in case if IP address of the master has changed.
This fix is making `salt-broker` more agressive on re-resolving IP address.
No difference.
Tracks: https://github.com/SUSE/spacewalk/issues/24752, https://github.com/SUSE/spacewalk/issues/24871
Issue(s): #
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-proje …
> Make salt-broker reconnecting on master IP change

- java/buildconf/manager-developer-build.properties.example
- java/manager-build.xml
- testsuite/podman_runner/09_build_server_code.sh
This PR refactors the ant script for improving the deployment process. Instead of having separate multiple tasks for deploying inside or outside the container, this change introduces a new property `deploy.mode` which specify how the process is performed and can have the following values:
- `local`, the deployment is done by copying the files in the same machine where the repository lives
- `remote`, the deployment is done on the remote machine defined by `deploy.host`. The copying is done by opening an SSH tunnel to the machine and transferring the data
- `container`, the deployment is performed to a containerized server using `mgrctl`. The container can be locally installed or remote depending by the backend used by `mgrctl` which can be explicitly set by using the property …
> Refactor Ant deployment

- java/code/src/com/suse/manager/webui/controllers/login/templates/login.jade
- java/code/webapp/WEB-INF/decorators/layout_error.jsp
- java/code/webapp/WEB-INF/decorators/layout_head.jsp
- java/spacewalk-java.changes.eth.login
- web/spacewalk-web.changes.eth.login
See title, no pages should use the old theme anymore, but the login page was still looking for it.
Fixes login page.
- No tests: UI bugfix
Slack thread: https://suse.slack.com/archives/C02D134507M/p1732619812848779 …
> Fix dangling old theme reference

- java/spacewalk-java.changes.mackdk.remove-dwr-dependency
- java/spacewalk-java.spec
This PR removes the references to DWR from the `spacewalk-java` spec file. The library was in fact removed by https://github.com/uyuni-project/uyuni/pull/6134 and it's no longer used, but it was still installed and added to the classpath.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/5967 …
> Remove DWR dependency

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/spacewalk-java.changes.carlo.Manager-4.3-fix-kickstart-string
updated UI tip pointing to new kickstarts template directory.
moved /var/lib/rhn/kickstarts references in the UI string files to /var/lib/cobbler/templates/
No difference.
- [x ] **DONE**
- No tests: minimal text change
Port(s): https://github.com/SUSE/spacewalk/pull/25885  …
> updated UI tip pointing to new kickstarts template directory (bsc#1221219)

- testsuite/features/step_definitions/salt_steps.rb
We filter out the package lock failure from https://github.com/uyuni-project/uyuni/blob/master/testsuite/features/secondary/min_salt_lock_packages.feature. However, the error still appears alongside non-ignored errors if there is more than 1 error in the salt event log.
The goal of this PR is to filter the output so that intentionally triggered errors do not appear, avoiding confusion.
How it looks now:
```
Then the salt event log on server should contain no failures # features/step_definitions/salt_steps.rb:507
Found 3 failures in salt event log:
"__id__": "mgr_buildimage",
"__run_num__": 1,
"__sls__": "images.docker",
"changes": {},
"comment": "Module function docker.build threw an exception. Exception: invalid tag 'registry.mgr.suse.de:5000/cucutest/auth_registry_profile:latest': …
```
> Filter package lock failures from salt event parser

- susemanager-sync-data/additional_products.json
- susemanager-sync-data/susemanager-sync-data.changes.mcalmer.Manager-4.3-OES244-sync-data-update
Add support for OES 24.4
No difference.
- https://github.com/SUSE/spacewalk/issues/25899
- No tests: tested by requesting team
Port(s): https://github.com/SUSE/spacewalk/pull/25893
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-m …
> Add support for OES 24.4 (bsc#1230585)

- susemanager-utils/susemanager-sls/salt/rebootifneeded.sls
- susemanager-utils/susemanager-sls/salt/uptodate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.Manager-5.0-fix-undef-var-in-rebootifneeded
After splitting the "reboot if needed" part from the `uptodate` state, we got an undefined variable.
This PR add a trick to keep the functionality by touching /run/reboot-needed file when patches
request restart. This cause zypper ps report 102 exit code which is used in the new `rebootifneeded` state.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/25901 …
> Fix rebootifneeded state which miss definition of a variable (bsc#1233426)

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/spacewalk-java.changes.bisht-richa.search-placeholder-text
- testsuite/features/step_definitions/navigation_steps.rb
This PR fixes the bugzilla issue : https://bugzilla.suse.com/show_bug.cgi?id=1233082
Change search input placeholder text on the Upgrade package page
Before:
After:
Issues: https://github.com/SUSE/spacewalk/issues/25108 …
> Fixed place holder message text in Upgrade package page

- testsuite/features/support/constants.rb
Follow-up of #8932 which was for SUSE Manager.
Add SLE 15 SP6 to the resposync on Uyuni.
Issue(s): https://github.com/SUSE/spacewalk/issues/24573
Port(s):
* 5.0: https://github.com/SUSE/spacewalk/pull/25911
* 4.3: https://github.com/SUSE/spacewalk/pull/25910
> Add SLE 15 SP6 to the resposync on Uyuni

- .github/workflows/changelogs.yml
- .github/workflows/changelogs/changelogs.py
- .github/workflows/changelogs/test_changelogs.py
This PR adds some fixes to the changelogs action after the first test runs upstream:
- Add back the "checkbox" condition in Changelog tests action
- Run the workflow code from the `base` branch instead of PR `head`:
This makes it impossible to inject malicious code to the workflow code
- Fix the error when testing PRs with >300 files
- Propagate the GH action `debug` flag to print verbose messages on debug runs
- Fix indexing when one package name is a substring of another
- Ignore spacing issues in version strings
- Retrieve extended (untruncated) commit messages from GH API
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-re …
> Changelog action: Fixes after test runs

- testsuite/features/secondary/srv_salt_git_pillar.feature
With `And I wait until there is no pillar refresh salt job active` it takes a couple of minutes more, but hopefully may solve recurring:
```
Then the pillar data for "git_pillar_foobar" should be "12345" on "sle_minion"
Message:
Output value wasn't found: uyuni-ci-master-podman-suse-minion.mgr.suse.de:
(ScriptError)
./features/step_definitions/salt_steps.rb:378:in `/^the pillar data for "([^"]*)" should be "([^"]*)" on "([^"]*)"$/'
features/secondary/srv_salt_git_pillar.feature:18:in `the pillar data for "git_pillar_foobar" should be "12345" on "sle_minion"'
```
Full scenario run for conformity:
```
uyuni-ci-master-podman-controller:~/spacewalk/testsuite # cucumber features/secondary/srv_salt_git_pillar.feature
Using Ruby version: 3.3.6
QUALITY INTELLIGENCE MODE ENABLED.
Capybara APP …
```
> Check for the expected pillar data after enabling Git pillar stability

- testsuite/features/build_validation/init_clients/proxy.feature
- testsuite/features/step_definitions/salt_steps.rb
port of https://github.com/SUSE/spacewalk/pull/25556/ . See there for explanation.
Additional changes from the 5.0 port:
Remove only some files, not whole directories.
Use existing step for removing packages since we have it.
Change the order of file removal and package removal. That is the important part because it saves us from a reboot inbetween these actions. Now with this order the transaction should not be in an inconsistent state after only one reboot. Testing currently to make sure we don't break anything
No difference.
Issue(s): …
> Refactor salt cleanup step

- testsuite/features/init_clients/buildhost_bootstrap.feature
- testsuite/features/init_clients/min_deblike_salt.feature
- testsuite/features/init_clients/min_rhlike_salt.feature
- testsuite/features/init_clients/min_virthost.feature
- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
Reverts uyuni-project/uyuni#9530
Tt does not fly, as we actually don't have the repositories synchronized on CT, and therefore... we don't have the venv-enabled txt file, and so, we can't bootstrap the minions :disappointed:
It's a pity, I would like to at least think again about synchronizing Leap 15.5, to have a good comparison between onboardings on SUMA and Uyuni. But for now, reverting.
> Revert "Clean up deployment salt minion leftovers on CT"

- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerXMLRPCHelper.java
Cleanup sonarcloud issues in `CobblerXMLRPCHelper`.
No difference.
- No tests: minor cleanups
Issue(s): # …
> Cleanup in the CobblerXMLRPCHelper class

- java/code/src/com/redhat/rhn/manager/rhnpackage/PackageManager.java
- java/spacewalk-java.changes.cbosdo.packages-list
This fixes the following error message when filtering all managed packages (bsc#1233450):
ERROR: missing FROM-clause entry for table "pn"
No difference.
- No tests: hard to test
Issue(s): https://github.com/SUSE/spacewalk/issues/25889
If you uncheck …
> Add missing join in the count query for the packages list

- python/spacewalk/satellite_tools/mgr-sign-metadata-ctl
- python/spacewalk/spacewalk-backend.changes.mcalmer.fix-signed-check
The mgr-sign-metadata-ctl check-channels command is currently only checking for debian repos correctly.
No difference.
- No tests: cmd tool no tests
Port(s): TBD …
> Fix mgr-sign-metadata-ctl check-channels when checking for signatures in repomd metadata (bsc#1233884)

- containers/server-saline-image/Dockerfile
- containers/server-saline-image/_service
- containers/server-saline-image/cleanup.sh
- containers/server-saline-image/run_saline.sh
- containers/server-saline-image/server-saline-image.changes
- containers/server-saline-image/tito.props
- rel-eng/packages/server-saline-image
Adds server container with Saline inside.
No difference.
Before:
After: …
> Add saline server container

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.mcalmer.Manager-5.0-sl-micro61-bs-repo
Add bootstrap repository definition for SL Micro 6.1
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/25829 …
> add bootstrap repo definitions for SL Micro 6.1

- python/spacewalk/server/importlib/packageImport.py
- python/spacewalk/spacewalk-backend.changes.mczernek.rpmimport-fix
An RPM package may not set any summary in the RPM header. Technically, this is an invalid RPM package, but reposync can handle this case.
- No documentation needed: **Internal bugfix**
- No tests: **Internal bugfix**
Issue(s): https://github.com/SUSE/spacewalk/issues/25668
Port(s): 
- 4.3: https://github.com/SUSE/spacewalk/pull/25801
- 5.0: https://github.com/SUSE/spacewalk/pull/25995 …
> Set default rpm package summary value if it's missing

- java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
- java/spacewalk-java.changes.cbbayburt.bsc1233400
"Live patching for a product" filter in CLM shows versions of all the available kernels in a dropdown, including `kernel-default-base` and any other flavours. Since live patching is only available for `kernel-default`, this change excludes the versions from other kernel packages from the dropdown list.
Port of [#25987 (Manager-4.3)](https://github.com/SUSE/spacewalk/pull/25987)
Issue: https://github.com/SUSE/spacewalk/issues/25813 …
> Only show versions for 'kernel-default' in CLM Live Patching template (bsc#1233400)

- java/code/src/com/suse/manager/webui/services/pillar/MinionGeneralPillarGenerator.java
- java/spacewalk-java.changes.mcalmer.Manager-4.3-ubuntu2404-set-signedby
- susemanager-utils/susemanager-sls/salt/channels/channels.repo
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.ubuntu2404-set-signedby
Improve handling of Debian repository configuration.
- Set "Signed-by" also for unsigned repos to prevent warning messages
- Do not set "Trusted" when the repo should be signed
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/25979 …
> Ubuntu2404 set signedby

- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/redhat/rhn/manager/system/test/SystemManagerTest.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/spacewalk-java.changes.mcalmer.improve-channel-change
This PR handle 3 issues
- when child channels do not match the base channel, raise early an excpeption
- when an exception happens late, cancel the server action if it exists
- support 2 special cases which were possible with the deprecated setBaseChannel() call
- when baseChannelLabel and childLabels are both empty, unassign all channels from the system
- when only a new baseChannelLabel is provided, look for compatible child channels to the assigned once and add them
No difference.
Port(s): Added on top of https://github.com/SUSE/spacewalk/pull/25923 …
> Improve channel change

- microservices/uyuni-java-parent/uyuni-java-parent.changes.mackdk.add-missing-changelogs
- search-server/spacewalk-search/spacewalk-search.changes.mackdk.add-missing-changelogs
This PR adds missing changelog entries to `spacewalk-search` and `uyuni-java-parent`.
No difference.
- No documentation needed: no functional changes
- No tests: No code changes
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merg …
> Added missing changelogs

- java/buildconf/apidoc/asciidoc/apiindex.txt
- java/spacewalk-java.changes.cbosdo.apidoc
Since users need to use dots to separate the API modules those should be showing up in the help to avoid confusion (bsc#1233761).
No difference.
- API documentation changed: https://github.com/uyuni-project/uyuni-docs-api/pull/59
- No tests: doc tooling
Issue(s): https://github.com/SUSE/spacewalk/issues/25898 …
> Use dots instead of underscores in the left menu

- testsuite/features/build_validation/init_clients/proxy.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/commonlib.rb
@ releng, could you merge squash with Commit name: Upgrade mgrpxy tool before installing the containerized proxy
Thanks !
When installing the proxy container on proxy host, mgrpxy is not updated.
After bootstrapping the new proxy, update mgrpxy tool using spacewalk and reboot the proxy.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/25946
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyun …
> Upgrade mgrpxy tool before installing the containerized proxy.

- testsuite/features/init_clients/buildhost_bootstrap.feature
- testsuite/features/init_clients/min_virthost.feature
- testsuite/features/init_clients/sle_minion.feature
- testsuite/features/init_clients/sle_ssh_minion.feature
- testsuite/features/reposync/srv_create_bootstrap_repositories.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/run_sets/reference_reposync.yml
- testsuite/run_sets/reposync.yml
This PR aims to have back the proper onboarding of salt bundle on Continuous Testing for at least those minions that have a product synchronized, or at least the Client Tools.
For that, we are force to regenerate the bootstrap repository, so the venv-enabled-x86_64.txt is generated.
Until now, we live without it, because we were installing salt-bundle manually through sumaform, in particular we do it at cloud-init or combustion stage, we do like that so sumaform can run the salt states to configure all the system after the VM is deployed.
But what it happen now is that our server detects a salt-bundle package already installed and don't do a proper onboarding of the minion, installing the package on the custom client tools repo, instead it's using the one previously installed, that's why …
> Force the generation of bootstrap repositories in CT

- java/code/src/com/redhat/rhn/frontend/action/ssm/RebootSystemAction.java
- java/spacewalk-java.changes.carlo.Manager-4.3-fix-ssm-page-reboot
When accessing menu Systems > System Set Manager > Misc > Reboot with no system selected, an "Internal server error" page is shown. This is due to the fact that the query Server.findServersPendingRebootAction has a clause "IN (:systemIds)", hence an empty set of selected systems crashes the query.
No difference.
Issue(s): 
Port(s): https://github.com/SUSE/spacewalk/pull/26105
> fixes - ISE when removing systems from SSM (bsc#1222820)

- web/html/src/manager/admin/setup/products/products.tsx
- web/spacewalk-web.changes.carlo.Manager-5.0-scc-credentials-message
After adding SCC credentials, while SCC synchronisation is still ongoing, when you switch to the products tab, a misleading error appears: "No SUSE Manager Server Subscription available. Products requiring Client Tools Channel will not be shown.".
This error does not make sense since the synchronisation is still happening.
No difference.
- No tests: manual behaviour testing
Issue(s): 
Port(s): https://github.com/SUSE/spacewalk/pull/26134, https://github.com/SUSE/spacewalk/pull/26169
> Fixed misleading error while waiting for SCC credentials synchronisation (bsc#1227374)

- java/code/src/com/suse/manager/webui/controllers/DownloadController.java
- java/spacewalk-java.changes.carlo.Manager-4.3-fix-debian12-log
When synchronising Debian 12 product, a lot of log messages appear all the time in /var/log/rhn_web_ui.log on the server, like these:
INFO: ... - 404 - File not found: /var/cache/rhn/repodata/debian-12-suse-manager-tools-amd64/InRelease
INFO: ... - 404 - File not found: /var/cache/rhn/repodata/debian-12-pool-amd64/Release.gpg
Debian has alternative files as metadata "Release" vs "InRelease".
Seems that Debian12 is trying first the "InRelease" which we do not generate by default.
Hence the extra log messages are not needed and should be filtered out.
No difference.
Issue(s): 
Port(s): https://github.com/SUSE/spacewalk/pull/26177, https://github.com/SUSE/spacewalk/pull/26178
> Filter away Debian12 boostrap extra log messages (bsc#1216553)

- python/spacewalk/satellite_tools/exporter/exportLib.py
- python/spacewalk/server/importlib/backend.py
- python/spacewalk/spacewalk-backend.changes.mcalmer.Manager-4.3
- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes.mcalmer.Manager-4.3
We renamed the table suseProductSCCRepository into suseChannelTemplate.
Some queries still use the old table name.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/26127 …
> Fix missing table renames

- susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.changes.meaksh.fix-requires
- susemanager-utils/supportutils-plugin-susemanager-client/supportutils-plugin-susemanager-client.spec
- susemanager-utils/supportutils-plugin-susemanager-proxy/supportutils-plugin-susemanager-proxy.changes.meaksh.fix-requires
- susemanager-utils/supportutils-plugin-susemanager-proxy/supportutils-plugin-susemanager-proxy.spec
- susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.changes.meaksh.fix-requires
- susemanager-utils/supportutils-plugin-susemanager/supportutils-plugin-susemanager.spec
This PR adjust the requires of the following packages to allow compatibility with latest 3.2.9 version of `supportutils` (as the used "provides" has been dropped):
- `supportutils-plugin-susemanager`
- `supportutils-plugin-susemanager-client`
- `supportutils-plugin-susemanager-proxy`
Since these plugins are running also with older versions of `supportutils`, like in SLE12 (version 3.0.12), we are not requiring provides anymore but the main `supportutils` package.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26200 …
> Fix supportutils plugins to work with latest 3.2.9 version (bsc#1235145)

- java/code/src/com/redhat/rhn/domain/scc/SCCRepositoryCloudRmtAuth.java
- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/content/MgrSyncUtils.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerTest.java
- java/code/src/com/redhat/rhn/manager/content/test/MgrSyncUtilsTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataProcessor.java
- java/spacewalk-java.changes.mcalmer.cdn-change-project
- python/spacewalk/spacewalk-backend.changes.mcalmer.Manager-4.3-cdn-change-project
- python/spacewalk/spacewalk-backend.spec
We discuss to switch the CDN and this require a little code changes
No difference.
- https://github.com/SUSE/spacewalk/issues/25961
- manual
- unit tests added
Issue: https://github.com/SUSE/spacewalk/issues/25954
Port(s): https://github.com/SUSE/spacewalk/pull/26075 https://github.com/SUSE/spacewalk/pull/26087 …
> Handle upcoming new CDN

- java/code/src/com/redhat/rhn/manager/action/ActionManager.java
- java/spacewalk-java.changes.mcalmer.Manager-4.3-unique-pkglist-in-action
The package name+arch must be unique for salt pkg states.
Take care that this is correctly set in the Action Details
No difference.
Fixes https://github.com/uyuni-project/uyuni/issues/8121
Fixes https://github.com/uyuni-project/uyuni/issues/8998
Port(s): https://github.com/SUSE/spacewalk/pull/25985
If …
> Make the list for package actions unique so it can be passed to salt (bsc#1232042)

- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygAuthDataProcessor.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygUpdateAuthTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/test/PaygUpdateAuthTaskTest.java
- java/spacewalk-java.changes.mcalmer.Manager-4.3-lazy-error-report
For a PAYG Connection we check if the instance is PAYG. This test seems to be flaky and sometimes return BYOS.
We already invalidated the credentials only when the error happened the 2nd time in a row, but we showed the notification already on the first error.
This scares the user and produce questions especially as still everything works.
So with this PR we send the notification also on the second error when we also invalidate the credentials.
If the error happen only 1 time and is fixed with the next try, no visible error is reported.
No difference.
- Unit tests were adapted
Port(s): https://github.com/SUSE/spacewalk/pull/26033 …
> Lazy error report

- client/rhel/spacewalk-client-tools/po/Makefile
- client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes.mcalmer.show-source-string-change
- python/spacewalk/po/Makefile
- python/spacewalk/spacewalk-backend.changes.mcalmer.show-source-string-change
- spacecmd/po/Makefile
- spacecmd/spacecmd.changes.mcalmer.show-source-string-change
- susemanager/po/Makefile
- susemanager/susemanager.changes.mcalmer.show-source-string-change
- web/po/Makefile
- web/spacewalk-web.changes.mcalmer.show-source-string-change
Change translation scripts to include previous changes of the source string for translators
No difference.
- No tests: **translation tools**
Issue(s): None
Port(s): https://github.com/SUSE/spacewalk/pull/26201 https://github.com/SUSE/spacewalk/pull/26204 …
> Show Source String change for translations

- containers/proxy-squid-image/proxy-squid-image.changes.mcalmer.api-for-pillar-refresh-all-systems
- containers/proxy-squid-image/squid.conf
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/spacewalk-java.changes.mcalmer.api-for-pillar-refresh-all-systems
- python/spacewalk/satellite_tools/mgr-sign-metadata-ctl
- python/spacewalk/spacewalk-backend.changes.mcalmer.api-for-pillar-refresh-all-systems
- spacecmd/spacecmd.changes.mcalmer.api-for-pillar-refresh-all-systems
- spacecmd/src/spacecmd/system.py
Allow via API and spacecmd to refresh pillar data of all systems.
When refreshing the metadata via mgr-sign-metadata-ctl generate also the pillar data new.
Finally reduce the maximal caching time in the proxy for metadata.
No difference.
- not needed
Issue(s): https://github.com/uyuni-project/uyuni/issues/8563 https://github.com/uyuni-project/uyuni/issues/8189
Port(s): ? …
> Allow refresh of all system pillar data via API and spacecmd

- .github/workflows/changelogs/changelogs.py
- .github/workflows/changelogs/test_changelogs.py
Adds validation for duplicates in the new changelog entries in the same package.
> Changelog validation: test duplicate entries

- testsuite/features/secondary/srv_security.feature
- testsuite/features/step_definitions/security_steps.rb
* File `susemanager-light.css` does not exist anymore, replace it with `susemanager-sp-migration.css`.
* Do note use `sample`, or do not make tests random in any manner, we want predictable tests.
* Don't use `arg1` and `arg2`, prefer meaningful parameter names.
Port(s):
* 5.0: https://github.com/SUSE/spacewalk/pull/26217
* 4.3: https://github.com/SUSE/spacewalk/pull/26218
> susemanager-light.css does not exist anymore

- containers/server-image/server-image.changes.cbosdo.timezone-fix
- containers/server-image/timezone_alignment.service
By default systemd doesn't pass manager environment variables to the services process, they need to be explicitely added with PassEnvironment. (bsc#1235692)
No difference.
- No tests: systemd service change.
Issue(s): https://github.com/SUSE/spacewalk/issues/26188
Port(s): https://github.com/SUSE/spacewalk/pull/26189
If you need to …
> Pass the TZ variable to alignment service

- susemanager/src/mgr_bootstrap_data.py
- susemanager/susemanager.changes.carlo.uyuni-mlm-bootstrap-repo-sle15sp7
Creates SLE15SP7 bootstrap repo definitions for Multi-Linux Manager
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/26195, https://github.com/SUSE/spacewalk/pull/26196
> Create SLE15SP7 bootstrap repo definitions for SUSE Multi Linux Manager

- java/code/src/com/redhat/rhn/frontend/action/channel/ssm/BaseSubscribeAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemChannelsAction.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/audit/CVEAuditManager.java
- java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
- java/code/src/com/redhat/rhn/manager/channel/test/ChannelManagerTest.java
- java/code/src/com/redhat/rhn/manager/ssm/SsmManager.java
- java/code/src/com/suse/manager/webui/controllers/SsmController.java
- java/code/src/com/suse/manager/webui/controllers/SystemsController.java
- java/spacewalk-java.changes.cbbayburt.bsc1233724
- java/spacewalk-java.changes.cbbayburt.bsc1235908
The recent refactoring from `Stream.collect(Collectors.toList())` to `Stream.toList()` makes all the lists immutable. This causes an exception when the API handler method tries to sort the list down the line. This PR reverts the refactoring for this instance.
- No tests: handler not tested
Fixes https://github.com/SUSE/spacewalk/issues/26222 …
> Fix immutability issue in audit.listSystemsByPatchStatus (bsc#1235908)

- java/code/src/com/redhat/rhn/frontend/action/channel/ssm/BaseSubscribeAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemChannelsAction.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/contentmgmt/ContentManagementHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/audit/CVEAuditManager.java
- java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
- java/code/src/com/redhat/rhn/manager/channel/test/ChannelManagerTest.java
- java/code/src/com/redhat/rhn/manager/ssm/SsmManager.java
- java/code/src/com/suse/manager/webui/controllers/SsmController.java
- java/code/src/com/suse/manager/webui/controllers/SystemsController.java
- java/spacewalk-java.changes.cbbayburt.bsc1225287
- java/spacewalk-java.changes.cbbayburt.bsc1233724
- java/spacewalk-java.changes.cbbayburt.bsc1235908
Our apidoc generator doesn't support any style formatting (not even line breaks), so I had to remove all the extra information for this method. With the openAPI plans for the future, we shouldn't spend any more effort on this.
Fixes https://github.com/SUSE/spacewalk/issues/24492 …
> Fix formatting in 'contentmanagement' API docs (bsc#1225287)

- testsuite/features/support/remote_node.rb
Currently in our testsuite, the mgrctl command have unstable behavior related to https://github.com/SUSE/spacewalk/issues/25605
Without the option -t, the output come in disorder. See information in the bsc: https://bugzilla.suse.com/show_bug.cgi?id=1235603
It's a upstream issue and the bug is marked as RESOLVED WONTFIX. So we need to necessary changes on the testsuite side.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/25605
Port(s): https://github.com/SUSE/spacewalk/pull/26220 …
> Fix mix output for mgrctl by using option -t

- java/manager-build.xml
This PR enables the use of the SSH tunnel when selecting the `remote-container` deployment mode. This was previously not working because the flag `deploy.requires.ssh` was not set to `true` with `remote-container` mode.
This change also regroups the condition checks in order to improve readability. 
No difference.
- No documentation needed: no code changes
Port(s): https://github.com/SUSE/spacewalk/pull/26182 …
> Ensure the remote-container deploy mode uses an SSH tunnel

- testsuite/features/step_definitions/command_steps.rb
For some reason, `systemd is-enabled <service>` started addinga carriage return (`0x0d`) at the end of its output, thus breaking the sanity check.
This PR fixes that.
No ports, Head only (5.0 does not seem affected).
> Fix systemd services check

- testsuite/features/support/commonlib.rb
Add some family names to `suse_host?` function, in order to fix this issue in Uyuni tests:
No difference.
Ports:
- Manager-4.3
- Manager-5.0 …
> QE: Add some family names to suse_host? function

- testsuite/features/secondary/min_check_patches_install.feature
- testsuite/features/secondary/min_cve_audit.feature
- testsuite/features/secondary/min_salt_install_package.feature
- testsuite/features/secondary/min_salt_install_with_staging.feature
- testsuite/features/secondary/minssh_action_chain.feature
The number of patches has increased and now they are not in a single page anymore.
We must therefore apply some filtering so we can select the dummy patch we want to apply.
Port(s):
* https://github.com/SUSE/spacewalk/pull/26256
* https://github.com/SUSE/spacewalk/pull/26257
> Select right patch to add

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- testsuite/features/secondary/srv_mainpage.feature
- Update copyright year from 2024 to 2025
Before: `Copyright (c) 2011 - 2024 SUSE LLC.`
After: `Copyright (c) 2011 - 2025 SUSE LLC.`
Also the testsuite has been fixed
- No documentation needed: this doesn't require a documentation update
- Updated tests: already covered, just updated the existing test
Issue(s): #
Port(s): # https://github.com/SUSE/spacewalk/pull/26260 and https://github.com/SUSE/spacewalk/pull/26259 …
> Update copyright year to 2025

- java/code/src/com/redhat/rhn/domain/server/Server.java
- java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
- java/code/src/com/suse/manager/reactor/test/RegisterMinionActionTest.java
- java/code/src/com/suse/manager/reactor/test/dummy_systeminfo_rhel9.json
- java/code/src/com/suse/manager/reactor/test/rhel_minion_test_data.json
- java/spacewalk-java.changes.mcalmer.Manager-5.0-fix-monitoring-ent-detection
On Oracle Linux the OS Release is a 2 digit number. Our isRedHatX detection uses the family but expected only a single number.
Now we use a startsWith() to also detect sub releases.
This PR simplify also the OS release detection. We simply use what the grains will report to us instead of trying to stay compatible with the traditional stack.
No difference.
- Unit tests were adapted
Port(s): https://github.com/SUSE/spacewalk/pull/26108
If …
> Fix monitoring ent detection

- containers/proxy-squid-image/squid.conf
https://github.com/uyuni-project/uyuni/pull/9602 modified maximum squid cache time to proper 5 minutes, but did not modify tftp metadata timeout. This PR adjust that to 5 minutes as well.
I chose not to write new changelog entry as this can be covered by changelog provided by @mcalmer in mentioned PR.
No difference.
Issue(s): # …
> Adjust max squid cache time also for tftp metadata

- testsuite/features/secondary/min_deblike_openscap_audit.feature
- testsuite/features/secondary/min_rhlike_openscap_audit.feature
- testsuite/features/secondary/min_salt_lock_packages.feature
Since the last changes introduced in our GH validation setup, we are using now shared volumes that seems to have permission issues on the server.
This cause issues in some tests during the GH validation, and this prevents to merge unrelated PRs. For that reason, I would like to skip these issues until the issue with the volumes is fixed, unblocked the rest of PRs.
Issue:
No difference.
- Cucumber tests were skipped
No ports …
> QE: Disable some features until the volumes permission issue is fixed on GH validation

- java/code/src/com/redhat/rhn/taskomatic/TaskomaticApi.java
- java/code/src/com/redhat/rhn/taskomatic/task/RootCaCertUpdateTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/payg/PaygUpdateHostsTask.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/SyncController.java
- java/code/src/com/suse/manager/hub/test/HubManagerTest.java
- java/code/src/com/suse/manager/model/hub/IssRole.java
- java/code/src/com/suse/manager/xmlrpc/iss/IssHandler.java
- java/code/src/com/suse/utils/CertificateUtils.java
- java/code/src/com/suse/utils/test/CertificateUtilsTest.java
- java/spacewalk-java.changes.carlo.issv3-taskomatic-job
- schema/spacewalk/common/data/rhnTaskoBunch.sql
- schema/spacewalk/common/data/rhnTaskoTask.sql
- schema/spacewalk/common/data/rhnTaskoTemplate.sql
- schema/spacewalk/susemanager-schema.changes.carlo.issv3-taskomatic-job
- schema/spacewalk/upgrade/susemanager-schema-5.1.2-to-susemanager-schema-5.1.3/001-issv3-rootcacertificates-taskomatic.sql
When onboarding a peripheral or a hub, a root certificate might be needed if the two servers do not share a common one. The certificate is transferred during the registration process and stored in the database.
However, this does not alter the system trust configuration. This step cannot be implemented from the web UI/API backend, as Tomcat does not run with the required root privileges.
Therefore, we need to implement a Taskomatic job that checks if new certificates have been added or updated and stores them accordingly in the trusted certificate path
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26180 …
> Create a taskomatic job to refresh the trusted root CAs in ISSv3

- java/buildconf/LICENSE.txt
- java/code/src/com/redhat/rhn/domain/org/OrgFactory.java
- java/code/src/com/redhat/rhn/domain/server/MgrServerInfo.java
- java/code/src/com/redhat/rhn/domain/server/ServerFQDN.java
- java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/redhat/rhn/manager/system/proxycontainerconfig/ProxyContainerConfigCreateAcquisitor.java
- java/code/src/com/redhat/rhn/taskomatic/task/ReportDBHelper.java
- java/code/src/com/suse/manager/hub/DefaultIssInternalClient.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/IssInternalClient.java
- java/code/src/com/suse/manager/hub/IssSparkHelper.java
- java/code/src/com/suse/manager/hub/SyncController.java
- java/code/src/com/suse/manager/hub/test/HubManagerTest.java
- java/code/src/com/suse/manager/model/hub/ManagerInfoJson.java
- java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
- java/code/src/com/suse/manager/reactor/messaging/RegistrationUtils.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/webui/controllers/SystemsController.java
- java/spacewalk-java.changes.mcalmer.issv3-info-apis
- web/html/src/manager/systems/details/mgr-server-info.tsx
Add and use API functions to get information about the reportDB from a manager server and also create a user for the reportDB access.
This bring the Hub report DB feature back to master and is the successor for https://github.com/SUSE/spacewalk/pull/25586
No difference.
- Part of the ISSv3 docs
- Unit tests were adapted
Issue(s): https://github.com/SUSE/spacewalk/issues/25474 …
> Issv3 info apis

- testsuite/features/init_clients/buildhost_bootstrap.feature
Workaround to reach secondary in head.
Remove as soon as SELinux fix is merged: https://github.com/uyuni-project/uyuni/pull/9707
Port(s): none, head only.
> Temporary workaround: do not check events on build host

- java/code/src/com/redhat/rhn/common/messaging/SmtpMail.java
- java/spacewalk-java.changes.mcalmer.set-send-date-for-email
Set a send date when we prepare emails.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/26253 https://github.com/SUSE/spacewalk/pull/26254 …
> set a send date when preparing emails

- client/rhel/spacewalk-client-tools/po/Makefile
- client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes.mcalmer.remove-no-wrap-for-translations
- python/spacewalk/po/Makefile
- python/spacewalk/spacewalk-backend.changes.mcalmer.remove-no-wrap-for-translations
- spacecmd/po/Makefile
- spacecmd/spacecmd.changes.mcalmer.remove-no-wrap-for-translations
- susemanager/po/Makefile
- susemanager/susemanager.changes.mcalmer.remove-no-wrap-for-translations
- web/po/Makefile
- web/spacewalk-web.changes.mcalmer.remove-no-wrap-for-translations
Weblate force string wrapping.
Using --no-wrap does not make sense
> Allow translation to wrap strings as weblate force it

- spacewalk/certs-tools/gen-rpm.sh
- spacewalk/certs-tools/spacewalk-certs-tools.changes.oholecek.copy-generated-rpm
moving the file from container space to volume preserve SELinux context category (MCS) which them prevents access to them after container restart. Copying it stores the file with correct context.
No difference.
- No tests: already covered, problem found by testsuite
Issue(s): # …
> Copy generated CA rpms instead of moving them

- testsuite/features/build_validation/core/allcli_sanity.feature
- testsuite/features/core/allcli_sanity.feature
- testsuite/features/step_definitions/command_steps.rb
This PR officializes Vladimir's test for SELinux problems.
Feel free to object this PR. It adds 5 minutes to the sanity checks!
Another option could be to run it at the end of the testsuite, at same time we check the logs. The idea to do it at the beginning is that we can spare ourselves a run if SELinux is going to block us.
Port(s):
* 5.0:
> Check SELinux labels on container volumes

- testsuite/features/finishing/srv_smdba.feature
Avoid using `/smdba-backup-test` in the root filesystem, not in a container volume. SELinux does not like that.
Use instead `/var/spacewalk/db-backup`, like in our documentation.
Issue(s): https://bugzilla.suse.com/show_bug.cgi?id=1223142
Port(s):
* 5.0: https://github.com/SUSE/spacewalk/pull/26329
* 4.3: none, containerized server only
> Avoid SELinux + container volumes clashes

- testsuite/features/step_definitions/command_steps.rb
On my last PR, I pushed a duplicated step. Fixing it here.
No difference.
Ports:
- Manager-4.3
- Manager-5.0 …
> QE: Fix redundant step

- containers/server-image/Dockerfile
- rel-eng/custom/custom.py
This is done in two steps:
1. Unpack the tarball before installing the packages. This allows permissions defined the packages to take precedence.
2. Change the push code to set all root.tar.gz archive as owned by root user and group. If any change is needed it can be done in the Dockerfile.
set all files in container's root.tar.gz as root
No difference.
Issue(s): # …
> Fix permissions of files contained in root.tar.gz

- testsuite/features/init_clients/proxy_traditional.feature
- testsuite/features/secondary/allcli_software_channels.feature
- testsuite/features/secondary/allcli_software_channels_dependencies.feature
- testsuite/features/secondary/min_bootstrap_activation_key.feature
- testsuite/features/secondary/min_bootstrap_api.feature
- testsuite/features/secondary/min_change_software_channel.feature
- testsuite/features/secondary/min_custom_pkg_download_endpoint.feature
- testsuite/features/secondary/min_recurring_action.feature
Following the PR https://github.com/uyuni-project/uyuni/pull/9670
This PR remove some steps in some scenarios that were wrong, because the channels are not anymore available.
No difference.
- Cucumber tests were removed
Ports:
- Manager-4.3
- Manager-5.0 …
> QE: Remove steps of not anymore sync channels on CI

- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/suse/manager/hub/HubController.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/test/ControllerTestUtils.java
- java/code/src/com/suse/manager/hub/test/HubControllerTest.java
- java/code/src/com/suse/manager/model/hub/ChannelInfoJson.java
- java/code/src/com/suse/manager/model/hub/OrgInfoJson.java
The aim is to test a HubController API call without actually setting up a remote server and using tools like postman.
The idea is that unit tests can be done to test the behaviour and the returned values, while a single manual test can be done from the external (e.g. postman) to check that the API endpoint is really visible.
I tested all the old API endpoints with this testing method.
Also, I added two API endpoints to list all organizations and all the channels in the peripheral server.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/25353
Port(s): 
> HubController tests and new APIs to list organizations and channels on the peripheral server

- testsuite/features/build_validation/init_clients/monitoring_server.feature
- testsuite/features/build_validation/smoke_tests/smoke_tests.template
Smoke tests on the minion are now passing:
```
suma-bv-50-controller:~/spacewalk/testsuite # cucumber features/build_validation/smoke_tests/debian11_minion_smoke_tests.feature:236
Minion IP address or domain name variable empty
Buildhost IP address or domain name variable empty
Red Hat-like minion IP address or domain name variable empty
Debian-like minion IP address or domain name variable empty
SSH minion IP address or domain name variable empty
PXE boot MAC address variable empty
KVM server minion IP address or domain name variable empty
Using Ruby version: 3.3.7
Capybara APP Host: https://suma-bv-50-server.mgr.suse.de:8888
Initializing a remote node for 'server'.
Node: suma-bv-50-server, OS Version: 15-SP6, Family: sles
Activating XML-RPC API
Using the default profile... …
```
> Adjust grafana to 5.0.3 BV

- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/step_definitions/setup_steps.rb
Debug log when not successful product list
No difference.
- Cucumber tests were enhanced
Ports:
- Manager-4.3
- Manager-5.0 …
> Debug log when not successful product list

- susemanager-utils/susemanager-sls/salt/services/salt-minion.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mczernek.remove-unnecessary-state
This PR removes the call to `post_start_cleanup.sh` in highstate. We now have a systemd timer mechanism that calls the script, so we don't have to rely on the script being executed from highstate.
Port(s): TODO …
> Remove unnecessary salt upgrade cleanup from highstate

- testsuite/features/support/commonlib.rb
This PR reinforce how we check if a channel is fully synchronized.
In theory, if the reposync log file prints that a channel is synchronized and prints the total time, we can guess the channel is synchronized, but in practice that can be wrong.
With this reinforcement, we are not only checking the log file, but also assuring that the solv files are completed.
No difference.
Ports:
- Manager-4.3
- Manager-5.0 …
> QE: Reinforce and warn the check of a channel synchronization.

- java/code/src/com/redhat/rhn/domain/scc/SCCCachingFactory.java
fixes an issue with the wrong parameter type being used for the query parameter
No difference.
- No tests
Check …
> fix wrong type on list order query

- python/spacewalk/rhn-conf/rhn_server_satellite.conf
- python/spacewalk/satellite_tools/repo_plugins/deb_src.py
- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes.meaksh.master-extend-filters-on-reposync
- python/test/unit/spacewalk/satellite_tools/test_yum_src.py
- spacewalk/config/spacewalk-config.changes.meaksh.master-extend-filters-on-reposync
- spacewalk/config/var/lib/rhn/rhn-satellite-prep/etc/rhn/rhn.conf
This PR enables `spacewalk-repo-sync` to filter packages matching the entire "NEVRA" instead of the package name only.
This extended nevra filtering must be enabled in `rhn.conf` by setting:
```
server.satellite.reposync_nevra_filter = 1
```
This is particularly useful when dealing with big repositories, where package name filters are not enough and you want to use more fine-grained filters to synchronize only certain packages.
```console
[...]
14:36:57 Repo URL: https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu/dists/noble/main/binary-amd64/
14:36:57     Packages in repo:                45
14:36:57     Packages passed filter rules:     0
[...]
```
```console
[...]
14:38:07 Repo URL: https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu/dists/noble/main/binary-amd64/
14:38:07     Packages …
```
> Allow "reposync" to filter packages using the entire NEVRA (bsc#1234226)

- python/spacewalk/common/rhnConfig.py
- python/spacewalk/spacewalk-backend.changes.vzhestkov.fix-version-cfg-parse
`web.version.uyuni` config value is wrongly parsed as `float` and `2024.10` became `2024.1`.
`web.version` added as well even if it makes no much sense now, but anyway it should be always string as well.
No difference.
- No tests: there are no unit tests for this legacy part of the code
Issue(s): https://github.com/uyuni-project/uyuni/issues/9414
Port(s): Not needed as Uyuni is the only having such values wrongly parsed as floats
If you …
> Always parse versions from rhn config as strings

- python/spacewalk/satellite_tools/accounts/satpasswd
- python/spacewalk/server/Makefile
- python/spacewalk/server/db_config.py
- python/spacewalk/server/rhnUser.py
- python/spacewalk/spacewalk-backend.changes.mcalmer.fix-min_passwd_len-config
- python/spacewalk/spacewalk-backend.spec
We started to move configuration values from rhn.conf into the database rhnConfiguration table.
As we need now some of the moved values in python code, we need a function which get us these
from the DB.
No difference.
Addition to: https://github.com/uyuni-project/uyuni/pull/9423 …
> Implement module to get configuration values from the database

- testsuite/features/reposync/allcli_update_activationkeys.feature
- testsuite/features/reposync/srv_create_dev_channels.feature
Fix typo build_host
No difference.
Ports:
- Manager-4.3
- Manager-5.0
Check [How to …
> QE: Fix typo build_host

- spacewalk/admin/uyuni-update-config
Using the wrong namespace cause never finding the key when it already exists.
No difference.
Additional fix for https://github.com/uyuni-project/uyuni/pull/9423 …
> fix config namespace to prevent duplicate entries

- .github/workflows/git-checks.yml
Add action for blocking merging of fixup commits
No difference.
- No documentation needed: Not part of the product, just a GitHub action
- No tests: To some extent, this is a test :-)
Issue(s): https://github.com/SUSE/spacewalk/issues/24385#issuecomment-2624342334
Port(s): None …
> Add action for blocking merging of fixup commits

- testsuite/documentation/optional.md
- testsuite/features/core/allcli_sanity.feature
- testsuite/features/github_validation/init_clients/buildhost_bootstrap.feature
- testsuite/features/init_clients/buildhost_bootstrap.feature
- testsuite/features/reposync/srv_create_dev_channels.feature
- testsuite/features/reposync/srv_sync_dev_channels.feature
- testsuite/features/secondary/buildhost_docker_auth_registry.feature
- testsuite/features/secondary/buildhost_docker_build_image.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/secondary/proxy_container_cobbler_pxeboot.feature
- testsuite/features/secondary/proxy_container_retail_pxeboot.feature
- testsuite/features/secondary/proxy_traditional_retail_pxeboot.feature
- testsuite/features/secondary/srv_rename_hostname.feature
- testsuite/features/support/constants.rb
- testsuite/features/support/env.rb
Align `build_host` naming
No difference.
Ports:
- Manager-4.3
- Manager-5.0
Check …
> QE: Align `build_host` naming

- .github/ISSUE_TEMPLATE/bugreport.yaml
Since uyuni-tools is now used for deployment, updates, and part of the management, this PR is adding a field for it, for our GitHub issue template.
We are already noticed some bugs where the problem is that the user is using an old uyuni-tools version, and having this info would allow to provide better assistance.
It's not mandatory, as not all bugs require it. But I can change this is you think it will be useful to always have it.
No difference.
- No documentation needed: Issue template
- No tests: Issue template
None
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#chan …
> Field for uyuni-tools for GitHub issues

- testsuite/features/reposync/srv_create_bootstrap_repositories.feature
Manually generate the bootstrap repo for Uyuni Build Host, because it will NOT be triggered automatically using `mgr-create-bootstrap-repo --auto --force --with-custom-channels`
No difference.
Ports:
- Manager-4.3
- Manager-5.0 …
> QE: Manually generate the bootstrap repo for Uyuni Build Host

- testsuite/documentation/optional.md
- testsuite/documentation/static-run.md
- testsuite/features/reposync/reference_srv_check_reposync.feature
- testsuite/features/reposync/reference_srv_sync_products_extra.feature
- testsuite/features/secondary/allcli_system_group.feature
- testsuite/features/secondary/min_deblike_openscap_audit.feature
- testsuite/features/secondary/srv_dist_channel_mapping.feature
- testsuite/features/secondary/srv_mgr_sync_list_products.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/run_sets/github_validation/github_validation_core.yml
- testsuite/run_sets/reference_reposync.yml
- testsuite/run_sets/refhost.yml
- testsuite/run_sets/reposync.yml
- testsuite/run_sets/secondary.yml
This PR bumps to Ubuntu 24.04 in feature files.
Tested on 5.0 branch with:
* sanity checks
* core features
* reposync features
* proxy features
* init client features
* some secondary features:
- allcli_config_channel.feature
- allcli_overview_systems_details.feature
- allcli_reboot.feature
- allcli_software_channels.feature
- allcli_software_channels_dependencies.feature
- allcli_system_group.feature
- min_deblike_monitoring.feature
- min_deblike_openscap_audit.feature
- min_deblike_remote_command.feature
- min_deblike_salt_install_package.feature
- min_deblike_salt_install_with_staging.feature
- min_deblike_ssh.feature
Piggybacks:
* rename a file which purpose has changed over time
* remove a scenario that we explicitely say we don't do a few lines later
Port(s):
* 5.0: …
> Switch to Ubuntu 24.04 in CI/refenv 5.0/head/uyuni

- containers/server-saline-image/Dockerfile
- containers/server-saline-image/server-saline-image.changes.vzhestkov.saline-switch-to-tornado
Use `Tornado` instead of `CherryPy` in `Saline` as it works better and more native with async manner of `Salt`.
Requires SR: https://build.opensuse.org/request/show/1245988
No difference.
- No tests: there is no any tests yet. TBD in future
SR: https://build.opensuse.org/request/show/1245988 …
> Use Tornado instead of CherryPy in Saline

- java/code/src/com/suse/manager/hub/HubController.java
- java/code/src/com/suse/manager/hub/HubSparkHelper.java
- java/code/src/com/suse/manager/hub/test/HubControllerTest.java
On the APIs to synchronize on a peripheral server it has to be ensured that if anything goes wrong in the handling of the API endpoint request, for example an exception is thrown, a well-formed response is returned back anyway.
At the moment there are cases in which if a runtime exception happens in the code calling stack (routes referring to the HubController class), this exception is not caught, therefore letting the API server hang with no response.
These conditions should be tackled so that an "internal server error" with a meaningful error message could be issued instead.
Although these APIs are intended for inter server communication, this will eventually help with the debugging process.
No difference.
- Unit tests …
> Issv3: Ensure sync hub APIs are responding correctly if a runtime exception occurs

- testsuite/features/support/commonlib.rb
This PR includes 5.1 as a valid product version to be included in the group of versions using salt bundle, instead of classic salt. Also fix the match for Head versions, so when Head will become the next 5.2 version, we don't really need to include 5.2, until it's released ;)
I added a TODO, as we ideally should refactor this code to only use Salt Bundle for now on, as all our current supported versions are using Salt Bundle.
No difference.
Ports:
- Manager-4.3
- Manager-5.0 …
> QE: Handle 5.1 when resolving product_version

- testsuite/features/profiles/Kiwi/POS_Image-JeOS6_head/images.sh
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_head/images.sh
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_uyuni/images.sh
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS6_head/images.sh
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_head/images.sh
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_uyuni/images.sh
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_head/images.sh
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_head/images.sh
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_uyuni/images.sh
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_head/images.sh
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_head/images.sh
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_uyuni/images.sh
Aligns the setup scripts for the testing Kiwi POS images with the ones of the released build profiles at https://github.com/SUSE/manager-build-profiles/tree/master
No difference.
- Resources used by Cucumber tests were modified
Issue(s): https://github.com/SUSE/spacewalk/issues/26399
Port(s):  No
> Align test  POS images setup scripts with the released ones

- containers/server-postgresql-image/Dockerfile
- containers/server-postgresql-image/_service
- containers/server-postgresql-image/root/docker-entrypoint-initdb.d/create-db.sh
- containers/server-postgresql-image/root/docker-entrypoint-initdb.d/create-reportdb.sh
- containers/server-postgresql-image/root/docker-entrypoint-initdb.d/evr_t.sql
- containers/server-postgresql-image/root/docker-entrypoint-initdb.d/uyuni-postgres-config.sh
- containers/server-postgresql-image/root/usr/local/bin/uyuni-entrypoint.sh
- containers/server-postgresql-image/server-postgresql-image.changes
- containers/server-postgresql-image/tito.props
- rel-eng/packages/server-postgresql-image
This PR adds a dedicated postgres container.
The script `uyuni-postgres-config.sh` replaces `smdba system-check autotuning` functionality.
No difference.
TBD
Part of https://github.com/SUSE/spacewalk/issues/25363
If you need to …
> Dedicated container for database

- java/code/src/com/suse/manager/hub/HubController.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/test/HubControllerTest.java
- java/code/src/com/suse/manager/webui/controllers/ProductsController.java
After registration of a new peripheral, we need to sync the products from the Hub or we cannot add channels.
Currently this needs to be performed on the Peripheral using mgr-sync refresh.
This PR adds the APIs for it using with the new Token API and provide this feature from the Hub side similar to
the Refresh on the Product Page.
No difference.
- No tests: it has to be tested manually
Issue(s): https://github.com/SUSE/spacewalk/issues/26496
Port(s): 
> ISSv3: API to perform a product refresh on the peripheral from the hub

- java/code/src/com/redhat/rhn/domain/notification/types/UpdateAvailable.java
- java/code/src/com/redhat/rhn/domain/notification/types/test/UpdateAvailableTest.java
- java/spacewalk-java.changes.mcalmer.multi-linux-rebranding
Change the URL for the release notes as our product get renamed to "SUSE Multi-Linux Manager".
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26459
Port(s): no port - 5.1 + only …
> Change releasenotes URL for SUSE Multi-Linux Manager 5.1

- java/buildconf/ivy/ivy-suse.xml
- java/buildconf/ivy/obs-maven-config.yaml
- java/code/src/com/redhat/rhn/taskomatic/TaskomaticApi.java
- java/code/src/com/suse/manager/hub/DefaultHubInternalClient.java
- java/code/src/com/suse/manager/hub/HubController.java
- java/code/src/com/suse/manager/hub/HubInternalClient.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/test/HubControllerTest.java
- java/code/src/com/suse/manager/hub/test/HubManagerTest.java
- java/code/src/com/suse/manager/webui/Router.java
At the end of a registration, trigger a product refresh on the peripheral to have the product info from the Hub available.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/25354 …
> perform product refresh on peripheral after registration

- testsuite/features/build_validation/retail/sle12sp5_buildhost_build_kiwi_image.feature
- testsuite/features/build_validation/retail/sle15sp4_buildhost_build_kiwi_image.feature
- testsuite/features/secondary/buildhost_osimage_build_image.feature
- testsuite/features/step_definitions/command_steps.rb
Removes and old workaround we had in place for https://github.com/SUSE/spacewalk/issues/10360
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/10360
Port(s): 
- 4.3 https://github.com/SUSE/spacewalk/pull/26511
- 5.0 https://github.com/SUSE/spacewalk/pull/26501
> QE: remove workaround for building Kiwi images

- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/spacewalk-java.changes.kwalter.bsc1236268
This fixes an issue preventing OES from showing up in the products page. The problem was that the roundtrip from URI to Path and back removed the trailing / on the urls for OES which are required
No difference.
- No tests
Issue(s): https://github.com/SUSE/spacewalk/issues/26285
Port(s):  …
> fix accessibleUrl removing trailing / on urls (bsc#1236268)

- python/spacewalk/server/importlib/backend.py
- python/spacewalk/server/importlib/backendLib.py
- python/spacewalk/spacewalk-backend.changes.mczernek.round-int-values
When we process package metadata, packages can mistakenly have float where we expect integer, for example `Installed Size`, `Size`, etc.
Though this is technically an invalid package, Uyuni can round such values to integer instead of throwing an exception.
In this PR, if a package contains a float value in metadata where we expect integer, we first round the value to the nearest integer.
In case where such value is neither float nor int, I improve the error that is displayed to the user.
Issue(s): https://github.com/uyuni-project/uyuni/issues/9613
Port(s): TODO …
> Enable packages metadata to be float when int is expected (gh#uyuni-project/uyuni#9613)

- java/code/src/com/redhat/rhn/common/security/acl/Access.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/strings/nav/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/ServerInvocationException.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/test/HubManagerTest.java
- java/code/src/com/suse/manager/model/hub/HubFactory.java
- java/code/src/com/suse/manager/webui/controllers/admin/AdminViewsController.java
- java/code/src/com/suse/manager/webui/controllers/admin/beans/HubDetailsData.java
- java/code/src/com/suse/manager/webui/controllers/admin/beans/PeripheralResponse.java
- java/code/src/com/suse/manager/webui/controllers/admin/beans/UpdateRootCARequest.java
- java/code/src/com/suse/manager/webui/controllers/admin/handlers/HubApiController.java
- java/code/src/com/suse/manager/webui/controllers/admin/templates/hub_details.jade
- java/code/src/com/suse/manager/webui/controllers/admin/templates/list_peripherals.jade
- java/code/src/com/suse/manager/webui/menu/MenuTree.java
- java/code/src/com/suse/manager/xmlrpc/iss/HubHandler.java
- web/html/src/components/buttons.tsx
- web/html/src/components/hub/DeregisterServer.tsx
- web/html/src/components/hub/HubDetailsForm.tsx
- web/html/src/components/hub/PeripheralsList.tsx
- web/html/src/components/hub/RegisterPeripheralForm.tsx
- web/html/src/components/hub/index.tsx
- web/html/src/components/hub/types.tsx
- web/html/src/components/large-text-attachment.tsx
- web/html/src/manager/admin/hub/hub-details.renderer.tsx
- web/html/src/manager/admin/hub/hub-details.tsx
- web/html/src/manager/admin/hub/peripherals.renderer.tsx
- web/html/src/manager/admin/hub/peripherals.tsx
- web/html/src/manager/admin/index.ts
This PR adds the menu and  the navigation to make the [previously made pages](https://github.com/uyuni-project/uyuni/pull/9783) accessible and adds the hub details page
NOTE: all the pages and the features around peripherals are included only as mock, they will be part of an additional PR.
After:
- Documentation WIP
Issue(s): https://github.com/SUSE/spacewalk/issues/25355
If …
> ISSv3 - UI skeleton and Hub details page

- .gitignore
- java/code/src/com/redhat/rhn/common/hibernate/AnnotationRegistry.java
- java/code/src/com/redhat/rhn/domain/access/AccessGroup.java
- java/code/src/com/redhat/rhn/domain/access/Namespace.java
- java/code/src/com/redhat/rhn/domain/access/WebEndpoint.java
- java/code/src/com/redhat/rhn/domain/access/WebEndpointFactory.java
- java/code/src/com/redhat/rhn/domain/user/User.java
- java/code/src/com/redhat/rhn/domain/user/legacy/UserImpl.java
- schema/spacewalk/blend
- schema/spacewalk/common/schemas/access.sql
- schema/spacewalk/common/tables/accessGroup.sql
- schema/spacewalk/common/tables/accessGroupNamespace.sql
- schema/spacewalk/common/tables/endpoint.sql
- schema/spacewalk/common/tables/endpointNamespace.sql
- schema/spacewalk/common/tables/namespace.sql
- schema/spacewalk/common/tables/tables.deps
- schema/spacewalk/common/tables/userAccessGroup.sql
- schema/spacewalk/common/tables/userNamespace.sql
- schema/spacewalk/common/views/endpointCatalog.sql
- schema/spacewalk/common/views/userAccessTable.sql
- schema/spacewalk/common/views/views.deps
- schema/spacewalk/postgres/Makefile
- schema/spacewalk/postgres/schemas/Makefile
- schema/spacewalk/schema-source-sanity-check.pl
- schema/spacewalk/susemanager-schema.changes.cbbayburt.rbac-base-schema
- schema/spacewalk/upgrade/susemanager-schema-5.1.3-to-susemanager-schema-5.1.4/200-rbac.sql
It is a port of https://github.com/uyuni-project/uyuni/pull/9802 containing the schema migration and the ORM implementation.
No difference.
Issue(s):
Port(s):  …
> Add RBAC schema implementation

- testsuite/features/step_definitions/navigation_steps.rb
This PR manages the case where a page obtained from an automatic refresh collides with the system overview page.
See https://github.com/SUSE/spacewalk/issues/26525
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/26543
* 5.0: https://github.com/SUSE/spacewalk/pull/26542
> Fix racing condition

- .github/workflows/build_containers.yml
- testsuite/dockerfiles/opensuse/leap/15.4/Dockerfile
- testsuite/dockerfiles/opensuse/leap/15.5/Dockerfile
- testsuite/dockerfiles/uyuni-master-testsuite/Dockerfile
This is the first step to fix https://github.com/SUSE/spacewalk/issues/25948
We need the test images in ghcr.io so we can later pull them and push them to the authenticated and non-authenticated registries that we use when running tests that build container images based on the content of the registries.
No difference.
- No tests
Issue(s): # https://github.com/SUSE/spacewalk/issues/25948
If you …
> CI: add build test images to ghcr.io

- testsuite/podman_runner/03_run_controller_and_registry_and_buildhost.sh
This way, we can later use these images in the build container tests
** This goes after https://github.com/uyuni-project/uyuni/pull/9851 **
No difference.
- No tests
Issue(s): #https://github.com/SUSE/spacewalk/issues/25948
If you …
> CI: push build test images to the test container

- testsuite/run_sets/reference_reposync.yml
The devel channels were missing in the `run_sets` files for the reference environments. This is an issue for all our reference envs.
No difference.
- Cucumber tests were added/edited
Issue(s): # …
> QE: Fix reference reposync file

- java/code/src/com/suse/manager/xmlrpc/iss/RestHubExternalClient.java
- java/spacewalk-java.changes.mackdk.fix-registration
This PR fixes an issue with ISSv3 registration using username/password. Due to [commit b023419](https://github.com/uyuni-project/uyuni/commit/b023419ebd4039e67164668088b95441d8da9292#diff-44d2ad9eae6435e6b813986a2988089cb3598816e3759a2dbacff2b1a4b9d153R142), the logout API has been changed from `POST` to `GET`. This breaks the peripheral registration, as 404 is received when trying to logout the user used for generating the token.
No difference. …
> ISSv3 - Use GET instead of POST for the logout

- rel-eng/chart_push.sh
- rel-eng/container_push.sh
Rebrand the product to Multi-Linux Manager
No difference.
- No tests: internal script
- but tested on IBS  at  https://build.suse.de/project/show/home:deneb_alpha:branches:Devel:Galaxy:Manager:Head_rebrandTags
- see also registry namespaces in https://registry.suse.de/cgi-bin/cooverview?srch_term=project%3D%5Ehome%3Adeneb_alpha%3Abranches%3ADevel%3AGalaxy%3AManager%3AHead_rebrandTags*
Issue(s): https://github.com/SUSE/spacewalk/issues/26379 https://github.com/SUSE/spacewalk/issues/26544 …
> Rebrand the product to Multi-Linux Manager

- testsuite/ext-tools/collect_and_tag_flaky_tests.rb
Check variable if not nil for flaky tests tagging. Not yet tested
No difference.
Issue(s): Fixes: https://github.com/SUSE/spacewalk/issues/26477
Port(s): 
5.0: https://github.com/SUSE/spacewalk/pull/26592
4.3: https://github.com/SUSE/spacewalk/pull/26593
If you …
> Check variable if not nil for flaky tests tagging

- testsuite/features/build_validation/finishing/srv_selinux.feature
- testsuite/features/finishing/srv_selinux.feature
- testsuite/run_sets/build_validation/build_validation_finishing.yml
* fix copy and paste error which lead to wrong feature name
* remove SELinux test from BV
Port(s):
* 5.0: https://github.com/SUSE/spacewalk/pull/26589
* 4.3: non applicable
> Fix wrong feature name

- java/code/src/com/suse/manager/api/HttpApiRegistry.java
- java/code/src/com/suse/manager/api/test/HttpApiRegistryTest.java
- java/spacewalk-java.changes.cbbayburt.logout-api-get
- No documentation needed: Covered by API docs
- No tests: routing not tested
> Allow both GET and POST requests for /auth/logout API endpoint

- java/code/src/com/suse/manager/hub/HubController.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/test/HubManagerTest.java
- java/code/src/com/suse/manager/model/hub/HubFactory.java
- java/code/src/com/suse/manager/model/hub/UpdatableServerData.java
- java/code/src/com/suse/manager/webui/controllers/admin/handlers/HubApiController.java
- java/code/src/com/suse/manager/xmlrpc/iss/HubHandler.java
This PR ensure the root CA is refreshed by calling the Taskomatic job if the field is updated through the API or the UI. It also uses a POJO instead of map to improve type safety.
No difference.
-  Documentation WIP TBD …
> ISSv3 - schedule a root CA refresh after the field is updated

- testsuite/dockerfiles/controller-dev/Dockerfile
We want to have the latest gems, so we do not get the error that prometheus-client gem is not being installed, when running the tests.
To update the controller, we need to update it to 15.6, given RPMs for old 15.5 are not available.
We do not need to stick to 0.9.6 version for ssh, given the ssh in opensuse 15.6 already contains the fix.
From `rpm -q --changelog libssh`
* Thu Feb 29 2024 adam.majer@suse.de
- Fix regression parsing IPv6 addresses provided as hostname (bsc#1220385)
* Added libssh-fix-ipv6-hostname-regression.patch
No difference.
- No tests
Issue(s): https://github.com/SUSE/spacewalk/issues/26598
Make …
> CI: update controller to opensuse 15.6 and install latest gems

- testsuite/dockerfiles/ubuntu-minion/Dockerfile
Fix openscap library on ubuntu-minion dockerfile
No difference.
- No tests
No ports …
> Fix openscap library on ubuntu-minion dockerfile

- testsuite/features/support/commonlib.rb
- testsuite/features/support/remote_node.rb
This PR makes the difference between OS family and version of real host and container.
In the case of non-containerized systems, both fields will be identical.
Port(s):
* 5.0: https://github.com/SUSE/spacewalk/pull/26636
* 4.3: non applicable
> Distinguish between OS of real host and of container

- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ChannelInfoJsonSerializer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ManagerInfoJsonSerializer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/OrgInfoJsonSerializer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/OrgSerializer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java
- java/code/src/com/suse/manager/api/RouteFactory.java
- java/code/src/com/suse/manager/hub/DefaultHubInternalClient.java
- java/code/src/com/suse/manager/hub/HubController.java
- java/code/src/com/suse/manager/hub/HubInternalClient.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/test/ControllerTestUtils.java
- java/code/src/com/suse/manager/model/hub/HubFactory.java
- java/code/src/com/suse/manager/model/hub/UpdatableServerData.java
- java/code/src/com/suse/manager/webui/controllers/admin/beans/ChannelSyncModel.java
- java/code/src/com/suse/manager/webui/controllers/admin/beans/IssV3ChannelResponse.java
- java/code/src/com/suse/manager/webui/utils/SparkApplicationHelper.java
- java/code/src/com/suse/manager/xmlrpc/iss/HubHandler.java
- java/code/src/com/suse/manager/xmlrpc/iss/test/HubHandlerTest.java
Adding some missing XMLRPC entries for HubManager
No difference.
Issue(s): 
Port(s): 
> Issv3: add xmlrpc hub apis

- testsuite/features/secondary/srv_content_lifecycle.feature
- testsuite/features/step_definitions/content_lifecycle_steps.rb
This PR add testcases that test the content lifecycle filters.
Fixes: https://github.com/uyuni-project/uyuni/issues/7967
No difference.
Issue(s): https://github.com/uyuni-project/uyuni/issues/7967
Port(s): 
- Manager 5.0
> QE: Adding testcases that test the content lifecycle filters

- testsuite/documentation/cucumber-steps.md
- testsuite/features/step_definitions/common_steps.rb
Let's always check first if the button is present, for that, we will refactor the code and make use of another mechanism we had in a not used step definition, so aside of check if the button is present it also checks if the radio button is checked, in case it is, it will not try to check it again.
No difference.
Ports:
- Manager-4.3 https://github.com/SUSE/spacewalk/pull/26689
- Manager-5.0 https://github.com/SUSE/spacewalk/pull/26688 …
> QE: Refactor choose radio button

- testsuite/dockerfiles/ubuntu-minion/Dockerfile
The ubuntu minion needs xz to compress the log files. Otherwise, the task "Get client logs" fails.
No difference.
- No tests
Issue(s):N/A …
> CI: fix get logs client task

- susemanager-utils/susemanager-sls/susemanager-sls.changes.deneb-alpha.saltVersion51susemanager-sls
- susemanager-utils/susemanager-sls/susemanager-sls.spec
* Fix build unresolvable due to switch to `python311-salt` in SLE-15-SP7
* Add the missing URL tag in the specfile
* Make use of the `productprettyname` macro for not hardcoding  the product name
No difference.
- Build tested on:
- [IBS](https://build.suse.de/package/show/home:deneb_alpha:branches:SUSE:SLE-15-SP7:Update:Products:MultiLinuxManager51_fixpython/susemanager-sls)
- [OBS](https://build.opensuse.org/package/show/home:deneb_alpha:branches:systemsmanagement:Uyuni:Master_fixpython/susemanager-sls)
Issue(s): https://github.com/SUSE/spacewalk/issues/26544
Make sure the …
> Switch to Python 3.11 Salt from SLE 15-SP7

- testsuite/features/secondary/allcli_system_group.feature
Doing the rrtg tasks we found that some of the system group and SSM tests are flaky. In this PR the tescases are improved.
Details:
* the problem was that we were applying twice the same patch `virgo-dummy-3456`
* so now we apply first `virgo-dummy-3456`, then `andromeda-dummy-6789`
* but after that, `andromeda-dummy` is fully installed and patched to latest version, and installation fails
* so we first uninstall  `andromeda-dummy`, and only then install it.
No difference.
Port(s):
- Manager 5.0: https://github.com/SUSE/spacewalk/pull/26715 …
> QE: Improving systemgroups and ssm tests

- testsuite/features/support/commonlib.rb
Remove retry method to get the system id. This retry method seems to bring some instability.
No difference.
Port(s): 
- 5.0: https://github.com/SUSE/spacewalk/pull/26412
- 4.3: https://github.com/SUSE/spacewalk/pull/26411
- uyuni: https://github.com/uyuni-project/uyuni/pull/9757 …
> Remove repeat command when getting the system id

- .github/workflows/acceptance_tests_coordinator.yml
Fix test coordinator workflow to use `pull_request_target`
No difference.
- No tests
No ports
Check [How to …
> Fix test coordinator workflow

- .github/workflows/acceptance_tests_base.yml
- .github/workflows/acceptance_tests_coordinator.yml
Fix GH workflows filter paths.
We moved an `if`, so we run it at step level, instead of job level, in order to generate at least `Skipping tests` step, to allow having correct status checks.
No difference.
- No tests
No ports
If …
> Fix GH workflows filter paths

- .github/workflows/acceptance_tests_coordinator.yml
Change the concurrency group for the Tests Coordinator, so the name of the group includes the PR reference.
Otherwise as this workflow is now running on master, all the executions where queued due to the concurrency group.
No difference.
- No tests
No ports …
> Change the concurrency group for the Tests Coordinator

- .github/workflows/acceptance_tests_base.yml
As we changed the workflow calling that one, to use `pull_request_target` now that code in use by default when we checkout, is the code from the base branch. Instead, we need to checkout the code from the PR.
No ports
> Checkout the PR code on Tests Base workflow

- testsuite/features/support/env.rb
This PR manages the case where Capybara::Session is nil .
No difference.
Port(s):
* 5.0: https://github.com/SUSE/spacewalk/pull/26764
* 4.3: https://github.com/SUSE/spacewalk/pull/26765
> Catch when web session instance is nil

- testsuite/features/support/env.rb
Fix how to process code coverage per feature. We made a mistake and we were taking into account the first scenario of next feature, as it was before.
No difference.
Ports:
- Manager-4.3
- Manager-5.0
If …
> Fix how to process code coverage per feature

- python/spacewalk/satellite_tools/repo_plugins/deb_src.py
- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes.agraul.vendor-looseversion
- python/spacewalk/spacewalk-backend.spec
- susemanager/susemanager.changes.agraul.use-correct-shebang-in-mgr-salt-ssh
- susemanager/susemanager.spec
In preparation for running Salt Master with Python 3.11, we need to remove imports in the still Python 3.6 based spacewalk-backend as well as use the right shebang in `mgr-salt-ssh`.
No difference.
- No tests: already covered, raised by QE
Issue(s): https://github.com/SUSE/spacewalk/issues/26758 …
> Vendor salt.utils.versions.Looseversion

- java/code/src/com/redhat/rhn/frontend/action/configuration/sdc/FileListConfirmSubmitAction.java
- java/code/src/com/redhat/rhn/frontend/action/configuration/sdc/FileListSubmitAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
- java/code/src/com/redhat/rhn/manager/action/ActionManager.java
- java/code/src/com/redhat/rhn/manager/audit/CVEAuditManager.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/suse/manager/webui/controllers/SSOController.java
- java/code/src/com/suse/utils/Lists.java
Refactored Java code to comply with SonarCloud rule **S1155**:  
Replaced instances of `collection.size() < 1` with `collection.isEmpty()`, and `collection.size() >= 1` with `!collection.isEmpty()`.
No difference.
- No documentation needed: only internal and user-invisible changes
- No tests done: just fixing sonar cloud issues
Issue(s): #9947  
> Fix issue 9947, use isEmpty() for checking emptiness

- java/code/src/com/suse/manager/errata/SUSEErrataParser.java
- java/spacewalk-java.changes.mcalmer.Manager-5.0-no-advisory-link-for-slmirco
SUSE does not create Vendor Advisories for SL-Micro 6 products.
We should not generate the links in the patch UI which point only to not existing pages.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/26704 …
> do not show Vendor Advisory link for SL-Micro 6 products (bsc#1237770)

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml
- java/code/src/com/redhat/rhn/frontend/action/rhnpackage/LockPackageAction.java
- java/code/webapp/WEB-INF/pages/systems/details/packages/lockpkgs.jsp
- java/spacewalk-java.changes.mcalmer.Manager-5.0-fix-pkglock-ui
When a package installed on a system is not available anymore in the repository it could not be send for locking anymore.
This happens with 5.0 now more often with 3rd party OSes as we now remove packages from our repos when they are removed from the upstream repository.
Additionally these packages are not links anymore in the list as the link result anyway in a "not found" or "permission error"
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/26685
If you …
> Fix package locking for packages not available anymore (bsc#1236877)

- testsuite/features/secondary/allcli_action_chain.feature
- testsuite/features/secondary/min_action_chain.feature
- testsuite/features/secondary/min_timezone.feature
- testsuite/features/secondary/minssh_action_chain.feature
- testsuite/features/secondary/srv_maintenance_windows.feature
- testsuite/features/step_definitions/api_common.rb
Refactors the action chain related features in order to have each one of them use different names for different action chains.
Currently we reuse the same names over and over, both inside a single feature and between different features.
Switching to using different names allows to:
1) make the tests closer to what a customer will do
2) make debugging a little bit easier
3) possibly avoid testsuite failures due to sharing the same name for different chains - although that should be a non-issue, I have the impressions that if we schedule a bunch of commands, run and delete a chain, create another one with the same name, schedule more command (...) all in a short time span we might get into troubles as UI and internal serve state get out of sync.
Also, currently some failures leave behind a …
> QE: refactor and reword action chain features

- testsuite/features/secondary/min_change_software_channel.feature
Box checking and unchecking matching the `Uyuni Client Tools for openSUSE Leap 15.5 (x86_64)*` regex is problematic (as it was with *BETA). In this scenario we have both `Uyuni Client Tools for openSUSE Leap 15.5 (x86_64)` and `Uyuni Client Tools for openSUSE Leap 15.5 (x86_64) (Development)`.
Changing the sequence to `Uyuni Client Tools for openSUSE Leap 15.5 (x86_64)` be served first makes the scenario passing:
```
uyuni-ci-master-podman-controller:~/spacewalk/testsuite # cucumber features/secondary/min_change_software_channel.feature:140
Using Ruby version: 3.3.7
QUALITY INTELLIGENCE MODE ENABLED.
Capybara APP Host: https://uyuni-ci-master-podman-server.mgr.suse.de:8888
Initializing a remote node for 'server'.
Host 'server' is alive with determined hostname …
```
> Feature: Assign child channel to a system | Scenario: Cleanup: subscribe the system back to previous channels

- susemanager-utils/susemanager-sls/src/modules/supportdata.py
- susemanager-utils/susemanager-sls/src/tests/test_module_supportdata.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.supportdata-salt-module
Salt execution module to get support data
No difference.
- part of feature doc
Issue(s): https://github.com/SUSE/spacewalk/issues/26616
> Supportdata salt module

- java/code/src/com/suse/manager/webui/utils/SaltConfigChannelState.java
- java/spacewalk-java.changes.kwalter.bsc1237694
Writes out the config channel states in reverse priority order so that higher priority goes last and can override the effects of lower priority states.
No difference.
- No tests
Issue(s): https://github.com/SUSE/spacewalk/issues/26547 …
> fix config channels not following priority in highstate (bsc#1237694)

- spacewalk/admin/spacewalk-admin.changes.mcalmer.Manager-5.0-fix-bds-migration
- spacewalk/admin/uyuni-update-config
When migrating from 4.3 PAYG to 5.0 the config for billing-data-service is migrated.
But in 4.3 the listen address was 127.0.0.1 while in 5.0 running inside of the container it must be 0.0.0.0 to be accessible from the outside.
This PR check in uyuni-update-config if the listen address is 127.0.0.1 and change it to 0.0.0.0.
Anything other value found stay untouched to keep customer configuration changes.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/26708 …
> fix billing-data-service configuration after upgrade (bsc#1236118)

- testsuite/features/profiles/github_runner/Docker/Dockerfile
- testsuite/features/profiles/github_runner/Docker/add_packages.sh
- testsuite/features/profiles/github_runner/Docker/authprofile/add_packages.sh
- testsuite/features/profiles/github_runner/Docker/serverhost/add_packages.sh
CI: Update github actions docker build profile             
* Update to Leap 15.5
* Skip installing packages for github actions
Build is happening at the docker daemon, which is at the ubuntu host.
It can't access the server channels.
No difference.
- No tests
partial fix for https://github.com/SUSE/spacewalk/issues/25948
If you …
> Ci review docker build profile

- testsuite/features/secondary/srv_content_lifecycle.feature
CI: remove flaky tests in content lifecycle
No difference.
- No tests
N/A …
> CI: remove flaky tests in content lifecycle

- java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
- java/code/src/com/suse/manager/webui/services/impl/SaltService.java
- java/spacewalk-java.changes.carlo.uyuni-fix-user-pillar-errors
On a MLM server, let's assume a user creates an invalid top-level pillar file that for example references some non existing file 'bogus.sls':
e.g. uyuni-server:/ # cat /srv/pillar/top.sls 
base:
'*':
- 'bogus'
With this scenario, when onboarding a minion there are two problems:
1) the user gets an empty error message
2) the rhn_web_ui.log contains a backtrace
Both those two issues are undesirable. This PR fixes them both:
Here is the user error message:
and here is the rhn_web_ui.log
No difference.
Issue(s): 
Port(s): https://github.com/SUSE/spacewalk/pull/26692, https://github.com/SUSE/spacewalk/pull/26698 …
> Fix: manage errors in user-defined pillars (bsc#1230403)

- java/code/src/com/redhat/rhn/frontend/xmlrpc/chain/ActionChainHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/chain/test/ActionChainHandlerTest.java
- java/spacewalk-java.changes.carlo.uyuni-api-add-highstate
It seems that in the API for action chain the scheduling of the highstate is forgotten. 
This PR adds an API `addApplyHighstate` to add an highstate application at an action chain
No difference.
- API documentation added (apidoc)
Issue(s): https://github.com/SUSE/spacewalk/issues/26098
Port(s): https://github.com/SUSE/spacewalk/pull/26725, https://github.com/SUSE/spacewalk/pull/26729
> Adds calling a highstate in the API for actionchain (bsc#1157520)

- java/code/src/com/redhat/rhn/frontend/struts/StrutsDelegate.java
- java/spacewalk-java.changes.carlo.uyuni-fix-openscap-audit-date
The follwing bugged behaviour is fixed: when scheduling a new OpenScap XCCDF Scan, and the earliest date was set in the future, the scan use to start immediately.
No difference.
- No tests: manually tested (UI)
Issue(s): 
Port(s): https://github.com/SUSE/spacewalk/pull/26747, https://github.com/SUSE/spacewalk/pull/26748
> Fix: openscap audit is running immediately even when scheduled for next days (bsc#1239743)

- spacewalk/certs-tools/mgr_ssl_cert_setup.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.meaksh.Manager-5.1-Beta1-bsc1240041
- susemanager-utils/susemanager-sls/modules/runners/mgrutil.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.meaksh.Manager-5.1-Beta1-bsc1240041
This PR fixes an issue seen in 5.1 Beta1, as the `spacewalk-certs-tools` are not yet migrated to Python 3.11, therefore our mgrutil runner (running in 3.11) is not able to import some helper function.
The way this PR solves the issue is by calling the `mgr-ssl-cert-setup` CLI instead of importing and using the particular helper function.
No difference.
- No tests: **tested manually**
Issue(s): # …
> Manager-5.1-Beta1: Prevent errors when generating proxy configuration (bsc#1240041)

- java/code/src/com/redhat/rhn/domain/action/salt/inspect/ImageInspectActionResult.java
Fixes issue https://github.com/SUSE/spacewalk/issues/26741 (Applying the highstate to Salt SSH minions causes a warning HHH000038 at rhn_taskomatic_daemon.log)
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26741
Port(s): no backports
> Fix: avoids taskomatic log warning HHH000038: Composite-id class does not override equals/hashCode

- web/html/src/manager/content-management/shared/business/filters.enum.ts
- web/spacewalk-web.changes.carlo.uyuni-fix-filters
Fixes bug 1238922: Filters of type Product Temporary Fix (Fixes Package Name) can't be created 
No difference.
Issue(s): 
Port(s): https://github.com/SUSE/spacewalk/pull/26671, https://github.com/SUSE/spacewalk/pull/26677
> Fix: Filters of type Product Temporary Fix cannot be created (bsc#1238922)

- java/code/src/com/redhat/rhn/frontend/action/token/ActivationKeyDetailsAction.java
- java/code/src/com/redhat/rhn/frontend/struts/StrutsDelegate.java
- java/code/src/com/redhat/rhn/frontend/taglibs/list/DataSetManipulator.java
- java/spacewalk-java.changes.carlo.uyuni-fix-sort-immutable
Fixes bug 1237581 - L3: Internal server error when accessing groups in activation keys #26534 
Object `DataSetManipulator` gets and stores a `List dataset` member.
If this list is immutable, the instruction `dataset.sort()` throws an exception
No difference.
- No tests: tested manually
Issue(s): 
Port(s): https://github.com/SUSE/spacewalk/pull/26660, https://github.com/SUSE/spacewalk/pull/26679
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge- …
> Fix: Internal server error when accessing groups in activation keys (bsc#1237581) 

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Errata_queries.xml
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/spacewalk-java.changes.carlo.uyuni-errata-overview
Fixes bug bsc#1236910: Using "reboot_suggested" or "restart_suggested" by API always responds "False"
No difference.
- No tests: API tested manually
Issue(s): 
Port(s): https://github.com/SUSE/spacewalk/pull/26657, https://github.com/SUSE/spacewalk/pull/26676
> Fix: Using reboot_suggested or restart_suggested by API always responds false (bsc#1236910)

- java/code/src/com/redhat/rhn/frontend/struts/StrutsDelegate.java
Patch to a bug found after closing [https://github.com/uyuni-project/uyuni/pull/10015](url) 
The datePicker is chosen when:
the form does not specify a SCHEDULE_TYPE
or the SCHEDULE_TYPE key is null or empty
or the SCHEDULE_TYPE key is equal to the datetime schedule type
No difference.
- No tests: manual tests
Issue(s): https://github.com/SUSE/spacewalk/issues/26717
> Fix bug found after merging uyuni-fix-openscap-audit-date

- java/code/src/com/redhat/rhn/common/hibernate/AnnotationRegistry.java
- java/code/src/com/redhat/rhn/domain/action/ActionFactory.java
- java/code/src/com/redhat/rhn/domain/action/Action_legacyUser.hbm.xml
- java/code/src/com/redhat/rhn/domain/action/supportdata/SupportDataAction.java
- java/code/src/com/redhat/rhn/domain/action/supportdata/SupportDataActionDetails.java
- java/code/src/com/redhat/rhn/domain/action/supportdata/UploadGeoEnumType.java
- java/code/src/com/redhat/rhn/domain/action/supportdata/UploadGeoType.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
- java/code/src/com/redhat/rhn/manager/action/ActionManager.java
- java/spacewalk-java.changes.mcalmer.supportdata-db-2
- schema/spacewalk/common/tables/suseActionSupportDataDetails.sql
- schema/spacewalk/common/tables/tables.deps
- schema/spacewalk/postgres/class/upload_geo_t.sql
- schema/spacewalk/upgrade/susemanager-schema-5.1.5-to-susemanager-schema-5.1.6/002-supportdata-action-details.sql
We need additional parameter for the support data action. This PR add Action Details to store the case number and additional parameter which can be used at execution time.
No difference.
- Part of an extra issue
Issue(s): https://github.com/SUSE/spacewalk/issues/26621 …
> Supportdata add Action Details and API

- java/code/src/com/redhat/rhn/domain/kickstart/KickstartFactory.java
- java/code/src/com/redhat/rhn/domain/kickstart/KickstartSession.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/spacewalk-java.changes.nadvornik.overview_update
Forward port of https://github.com/SUSE/spacewalk/pull/26639
This PR fixes a race on updating the system overview table.
The use of TaskFactory.lookup is not reliable. It can return a task that is currently running in concurrent DB transaction and can't see the latest changes. As a result, the system overview is not fully updated.
UPDATE:
This change triggered test failure in ActionManager.cancelActions test. The reason was an unrelated bug
fixed in the second commit:
cancelActions removed serverAction from the DB twice, first
via KickstartFactory.failKickstartSessions -> KickstartSession.markFailed ->
ActionFactory.removeActionForSystem and then directly from cancelActions
failKickstartSessions is called only from cancelActions, so the commit
changes it to keep the serverAction.
No …
> Fix race at updating system overview table (bsc#1235853)

- susemanager/src/mgr-create-bootstrap-repo
- susemanager/susemanager.changes.mcalmer.fix-bs-repo-basechannel-only
Create a bootstrap repo with --usecustomchannels was not possible when the root product had only
a base channel and no child channels. A query just looked for child channels.
No difference.
- No tests: **exception case QE only**
Issue(s): https://bugzilla.suse.com/show_bug.cgi?id=1239747
Port(s): https://github.com/SUSE/spacewalk/pull/26719 …
> find base channels for products which do not have child channels (bsc#1239747)

- java/code/webapp/WEB-INF/pages/common/fragments/yourrhn/subwarn.jsp
- java/spacewalk-java.changes.eth.sub-not
See GUI diff.
Before:
After:
- No tests: layout update
Related discussion: https://suse.slack.com/archives/C02D78LLS04/p1728636748424919 …
> Update subscription matching warning layout

- web/html/src/manager/minion/ansible/ansible-control-node.tsx
- web/html/src/manager/minion/ansible/new-ansible-path.tsx
- web/spacewalk-web.changes.eth.ans
This is not the nicest fix, ideally we'd fix the global styles that affect this, but that would mean breaking many other things. For now, this fix applies only here and resolves the problem.
After:
- No documentation needed: layout bugfix
- No tests: layout bugfix
Fixes https://github.com/SUSE/spacewalk/issues/26555 …
> Fix Ansible add directory UI layout

- web/html/javascript/spacewalk-essentials.js
- web/html/src/branding/css/base/components/toolbar.scss
- web/html/src/branding/css/base/theme.scss
- web/html/src/branding/css/suse-light-variables.scss
- web/html/src/branding/css/uyuni-variables.scss
- web/spacewalk-web.changes.eth.bsc1239621
See https://bugzilla.suse.com/show_bug.cgi?id=1239621
Update the sticky toolbar used in Software → Packages → Lock/Unlock (and many other places) to use CSS sticky instead of Js sticky. We still use Js to apply styles after the fact, but this change ensures the bar always gets unstickied even when the layout shifts due to notifications or similar.
Gotta be honest, this is touching some very groovy old global scripts so I hope this didn't break some other magic behavior.
The sticky bar unstickies as it should.
- No tests: UI bug
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1239621 …
> Fix sticky toolbar hiding notification messages on packages page (bsc#1239621)

- web/html/src/manager/content-management/list-filters/filter-edit.tsx
- web/spacewalk-web.changes.bisht-richa.filter-modal-buttons-alignment
- Fix the delete button alignment in the Filter Details modal.
No difference.
Before:
After:
Issue(s): https://github.com/SUSE/spacewalk/issues/26817 …
> Fix delete button alignment in filter modal.

- susemanager-utils/susemanager-sls/salt/uptodate.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mczernek.mczernek_1237060
The `uptodate` sls state currently uses `pkg.uptodate`, which uses `dist_upgrade: False` by default. This means that users using the `uptodate` recurring state on Ubuntu/Debian systems experience not fully patched systems.
- Issue created at https://github.com/uyuni-project/uyuni-docs/issues/3773
Issue(s): https://github.com/SUSE/spacewalk/issues/24418
Port(s):
- 4.3: https://github.com/SUSE/spacewalk/pull/26649
- 5.0: https://github.com/SUSE/spacewalk/pull/26648
If you …
> Change uptodate recurring action to use apt-get dist-upgrade bsc#1237060

- java/code/webapp/WEB-INF/pages/systems/errata.jsp
- java/spacewalk-java.changes.bisht-richa.patch-icon-hover-text
Fix tooltip text for icons in the patches list
No difference.
Before:
After:
Fixes: [#26076](https://github.com/SUSE/spacewalk/issues/26076) …
> Fix tooltip text for icons in the patches list

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/utils/CertificateUtils.java
- java/spacewalk-java.changes.mackdk.issv3-hub-reporting-different-rootca
This PR changes how the root ca is retrieved when syncing the hub reporting database and connecting to the peripheral. Currently, the logic assumed the root ca was the same among the hub and its peripheral. With the changes implemented for ISSv3 the hub is able to connect peripherals that have a different root ca and the certificate is stored in `/etc/pki/trust/anchors`.
This change ensure the correct certificate is picked up if available and used to establish a secure connection to the remote PostgreSQL database. This will allow the hub reporting feature to work when the peripheral has different root ca, if those machine are registered using the ISSv3 feature.
No difference.
- Addeded note to the documentation ticket:  https://github.com/SUSE/spacewalk/issues/25359
- No tests: already …
> Use correct root ca when syncing a peripheral reporting database

- testsuite/features/reposync/srv_sync_products.feature
```shell
05:26:38  And I select "SUSE Linux Micro 6.1" as a product                         # features/step_definitions/setup_steps.rb:82
05:26:38        Ambiguous match, found 4 elements matching visible xpath "//span[contains(text(), 'SUSE Linux Micro 6.1')]/ancestor::div[contains(@class, 'product-details-wrapper')]/div/input[@type='checkbox']" (Capybara::Ambiguous)
05:26:38        ./features/step_definitions/setup_steps.rb:85:in `/^I (deselect|select) "([^"]*)" as a product$/'
05:26:38        features/reposync/srv_sync_products.feature:173:in `I select "SUSE Linux Micro 6.1" as a product'
```
Ports: not needed …
> fix "Ambiguous match" as 4 products are found

- java/code/src/com/redhat/rhn/domain/iss/IssSlave.java
- java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java
- java/code/src/com/suse/manager/hub/DefaultHubInternalClient.java
- java/code/src/com/suse/manager/hub/HubController.java
- java/code/src/com/suse/manager/hub/HubInternalClient.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/migration/IssMigrator.java
- java/code/src/com/suse/manager/hub/migration/IssMigratorFactory.java
- java/code/src/com/suse/manager/hub/migration/test/IssMigratorTest.java
- java/code/src/com/suse/manager/hub/test/ControllerTestUtils.java
- java/code/src/com/suse/manager/hub/test/HubControllerTest.java
- java/code/src/com/suse/manager/hub/test/HubManagerTest.java
- java/code/src/com/suse/manager/model/hub/migration/MigrationItem.java
- java/code/src/com/suse/manager/model/hub/migration/MigrationMessage.java
- java/code/src/com/suse/manager/model/hub/migration/MigrationMessageLevel.java
- java/code/src/com/suse/manager/model/hub/migration/MigrationResult.java
- java/code/src/com/suse/manager/model/hub/migration/MigrationResultCode.java
- java/code/src/com/suse/manager/model/hub/migration/SlaveMigrationData.java
- java/code/src/com/suse/manager/xmlrpc/iss/HubHandler.java
- java/code/src/com/suse/manager/xmlrpc/iss/test/HubHandlerTest.java
- java/code/src/com/suse/manager/xmlrpc/serializer/MigrationResultSerializer.java
- java/code/src/com/suse/utils/CustomCollectors.java
- java/code/src/com/suse/utils/Lists.java
- java/code/src/com/suse/utils/test/CustomCollectorsTest.java
- java/code/src/com/suse/utils/test/ListsTest.java
This PR introduces an API to migrate ISS v1 slaves, turning them into ISS v3 peripherals
UI work-in-progess
- API documentation added
Issue(s): https://github.com/SUSE/spacewalk/issues/25357 …
> ISSv3 - Migration from ISS v1

- testsuite/features/reposync/srv_sync_products.feature
- web/html/src/components/pagination.tsx
To select the page size from the testsuite we need a name for the combox.
- Cucumber tests were changes
> make page number and page size selectable from the testsuite

- testsuite/features/support/commonlib.rb
Double the timeout if we run code coverage tool
No difference.
- Cucumber tests were enhanced
Ports:
- Manager-4.3
- Manager-5.0 …
> Double the timeout if we run code coverage tool

- susemanager-utils/susemanager-sls/salt/services/docker.sls
- susemanager-utils/susemanager-sls/salt/update-salt.sls
- susemanager-utils/susemanager-sls/salt/util/mgr_switch_to_venv_minion.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.meaksh.master-add-python311-cases-to--susemanager-sls
In SLE15SP7 there is no more `python3-salt` package, in favor of new `python311-salt`.
This PR adjusts the internal Uyuni SLS files that are explicitely mentioning `python3-salt` package to cover this 15SP7 case.
NOTE: in `update-salt.sls` and `mgr_switch_to_venv_minion.sls` we cannot use the `pythonversion[1]` trick to calculate the target package name, as those SLS bits run also for the Salt Bundle, so the target package calculation can be wrong.  
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26711
Port(s):
https://github.com/SUSE/spacewalk/pull/26824
https://github.com/SUSE/spacewalk/pull/26825 …
> Adjust SLS files for 15SP7 and systems running higher Python version

- .github/workflows/acceptance_tests_coordinator.yml
- .github/workflows/acceptance_tests_parallel.yml
- .github/workflows/acceptance_tests_recommended.yml
- .github/workflows/acceptance_tests_sequential.yml
`acceptance_tests_coordinator.yml` still runs on `pull_request_target` (so it has access to secrets).
But instead of calling workflows directly via `workflow_call` (which would inherit pull_request_target), it triggers `repository_dispatch`.
`repository_dispatch` runs as an event on the forked repository (i.e., PR head branch), NOT the base repo.
Since the actual test workflows (`acceptance_tests_recommended.yml, acceptance_tests_sequential.yml, acceptance_tests_parallel.yml`) now run on `repository_dispatch`, the GitHub runner will execute on the fork, testing the PR code.
No ports
> Refactor to run the GH validation on the fork's runner

- testsuite/dockerfiles/postgresql/Dockerfile
Keep as much as possible similar to the original postgres image in the CI image
No difference.
Issue(s): # …
> Do not override entrypoint in the CI postgresql image

- testsuite/features/support/commonlib.rb
Issue found during 5.1 testing using uyuni: https://github.com/SUSE/spacewalk/issues/26062#issuecomment-2767679613
OS family for alma, oracle and liberty are not correctly detected preventing a correct cleanup for those minion during BV.
Correct family list:
- alma family: almalinux
-  oracle family: ol
-  liberty: rhel
No difference.
Issue(s): # …
> Fix rhlike detection

- java/code/src/com/redhat/rhn/common/conf/sso/SSOConfig.java
- java/code/src/com/redhat/rhn/domain/action/server/ServerAction.java
- java/code/src/com/redhat/rhn/domain/channel/test/ChannelFamilyFactoryTest.java
- java/code/src/com/redhat/rhn/domain/kickstart/KickstartScript.java
- java/code/src/com/redhat/rhn/domain/product/test/SUSEProductTestUtils.java
- java/code/src/com/redhat/rhn/domain/reactor/SaltEvent.java
- java/code/src/com/redhat/rhn/domain/server/ServerHistoryEvent.java
- java/code/src/com/redhat/rhn/domain/server/ServerSnapshot.java
- java/code/src/com/redhat/rhn/domain/server/ServerSnapshotTagLink.java
- java/code/src/com/redhat/rhn/domain/server/SnapshotTag.java
- java/code/src/com/redhat/rhn/domain/server/SnapshotTagName.java
- java/code/src/com/redhat/rhn/frontend/action/common/BaseSetOperateOnDiffAction.java
- java/code/src/com/redhat/rhn/frontend/action/configuration/ssm/SubscribeConfirm.java
- java/code/src/com/redhat/rhn/frontend/action/errata/ChannelAction.java
- java/code/src/com/redhat/rhn/frontend/action/errata/NotifySetupAction.java
- java/code/src/com/redhat/rhn/frontend/action/help/ForgotCredentialsAction.java
- java/code/src/com/redhat/rhn/frontend/dto/ErrataCacheDto.java
- java/code/src/com/redhat/rhn/frontend/listview/AlphaBar.java
- java/code/src/com/redhat/rhn/frontend/servlets/RhnHttpServletRequest.java
- java/code/src/com/redhat/rhn/frontend/taglibs/DateTimePickerTag.java
- java/code/src/com/redhat/rhn/manager/configuration/ConfigChannelCreationHelper.java
- java/code/src/com/redhat/rhn/manager/kickstart/KickstartUrlHelper.java
- java/code/src/com/redhat/rhn/manager/kickstart/cobbler/CobblerCommand.java
- java/code/src/com/redhat/rhn/manager/rhnpackage/test/PackageManagerTest.java
- java/code/src/com/redhat/rhn/testing/ErrataTestUtils.java
- java/code/src/com/suse/manager/webui/controllers/VirtualHostManagerController.java
- java/code/src/com/suse/manager/webui/services/test/SaltServerActionServiceTest.java
- java/code/src/com/suse/manager/webui/utils/LoginHelper.java
- java/code/src/com/suse/scc/model/SCCMinProductJson.java
Fixes the following SonarCloud issues, where the fixes are straightforward
After review and approval, they will be squashed into one commit only
SonarCloud fix: java:S1858 toString() should never be called on a String object
SonarCloud fix: java:S1158 Use static primitive wrapper class toString() method
SonarCloud fix: java:S1185 Overriding methods should do more than simply call the same method in the super class
SonarCloud fix: java:S1656 Remove or correct useless self-assignment
SonarCloud fix: java:S1157 Replace toUpperCase()/toLowerCase() and equals() calls with a single equalsIgnoreCase() call
SonarCloud fix: java:S1130 Remove the declaration of thrown exception as it cannot be thrown from method body
SonarCloud fix: java:S2209 Static members should be accessed statically
SonarCloud …
> Sonar Cloud miscellaneous fixes 2

- java/code/src/com/redhat/rhn/common/messaging/MessageDispatcher.java
- java/code/src/com/redhat/rhn/common/validator/ValidatorService.java
- java/code/src/com/redhat/rhn/domain/action/salt/StateResult.java
- java/code/src/com/redhat/rhn/domain/contentmgmt/ContentProjectFactory.java
- java/code/src/com/redhat/rhn/frontend/action/channel/ssm/BaseSubscribeAction.java
- java/code/src/com/redhat/rhn/frontend/action/multiorg/TrustAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/provisioning/kickstart/SessionStatusAction.java
- java/code/src/com/redhat/rhn/frontend/dto/BaseDto.java
- java/code/src/com/redhat/rhn/frontend/dto/ChannelOverview.java
- java/code/src/com/redhat/rhn/frontend/dto/ChannelTreeNode.java
- java/code/src/com/redhat/rhn/frontend/dto/UpgradablePackageListItem.java
- java/code/src/com/redhat/rhn/frontend/struts/SelectableAdapter.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/BaseHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/systemgroup/ServerGroupHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
- java/code/src/com/redhat/rhn/manager/action/ActionManager.java
- java/code/src/com/redhat/rhn/manager/kickstart/IpAddress.java
- java/code/src/com/redhat/rhn/taskomatic/task/DailySummary.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/RpmRepositoryWriter.java
- java/code/src/com/suse/manager/api/ApiResponseSerializer.java
- java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
- java/code/src/com/suse/manager/webui/controllers/VirtualHostManagerController.java
Fixes the following SonarCloud issues, where the fixes are straightforward
After review and approval, they will be squashed into one commit only
SonarCloud fix: java:S3457 Format strings should be used correctly
SonarCloud fix: java:S4201 Remove unnecessary null checks: instanceof returns false for nulls
SonarCloud fix: java:S2153 Remove the boxing to Long: the argument is already of the same type
SonarCloud fix: java:S3626 Jump statements should not be redundant
SonarCloud fix: java:S4838 An iteration on a Collection should be performed on the type handled by the Collection
SonarCloud fix: java:S3038 Abstract methods  with the same signature as a method in an interface should not be redundant
SonarCloud fix: java:S1161 @Override should be used on overriding and implementing methods …
> Sonar Cloud miscellaneous fixes

- java/code/src/com/redhat/rhn/common/hibernate/HibernateFactory.java
- java/code/src/com/redhat/rhn/common/hibernate/ReportDbHibernateFactory.java
- java/code/src/com/redhat/rhn/frontend/servlets/RhnHttpServletRequest.java
- java/code/src/com/redhat/rhn/frontend/servlets/RhnHttpServletResponse.java
- java/code/src/com/redhat/rhn/taskomatic/core/TaskomaticDaemon.java
- java/code/src/com/redhat/rhn/taskomatic/core/test/TestDaemon.java
- java/code/src/com/suse/manager/reactor/utils/ValueMap.java
- java/code/src/com/suse/manager/webui/controllers/MinionsAPI.java
- java/code/src/com/suse/manager/webui/controllers/PackageController.java
- java/code/src/com/suse/manager/webui/controllers/ProxyController.java
- java/code/src/com/suse/manager/webui/controllers/RecurringActionController.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectActionsApiController.java
- java/code/src/com/suse/manager/webui/controllers/contentmanagement/handlers/ProjectApiController.java
Fixes the following SonarCloud issues **java:S1874 Deprecated code should not be used**
After review and approval, they will be squashed into one commit only
**1) deprecated call to Hibernate LockMode.UPGRADE**
> Deprecated. Instead use PESSIMISTIC_WRITE
[from: https://docs.jboss.org/hibernate/orm/3.5/javadocs/org/hibernate/LockMode.html#UPGRADE](https://docs.jboss.org/hibernate/orm/3.5/javadocs/org/hibernate/LockMode.html#UPGRADE)
**2) deprecated call to HttpServletRequest.isRequestedSessionIdFromUrl**
> Deprecated. As of Version 2.1 of the Java Servlet API, use isRequestedSessionIdFromURL() instead.
[from: https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#isRequestedSessionIdFromUrl()](https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletReques …
> SonarCloud fix: java:S1874 Deprecated code should not be used (part 1)

- java/code/src/com/redhat/rhn/domain/org/OrgConfig.java
- java/code/src/com/redhat/rhn/frontend/action/multiorg/OrgConfigAction.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/org/OrgHandler.java
- java/code/src/com/suse/manager/webui/services/iface/SaltApi.java
- java/code/src/com/suse/manager/webui/services/impl/SaltService.java
- java/code/src/com/suse/manager/webui/services/test/TestSaltApi.java
- java/code/webapp/WEB-INF/pages/common/fragments/org-config.jspf
- java/spacewalk-java.changes.carlo.uyuni-scap-upload-size-limit
Removes all references in code and in UI about the org configuration parameter scap_file_sizelimit.
This setting is outdated and worked only when using the traditional stack which was removed in 5.0.
This parameter is now directly modified in salt master susemanager.conf file.
Before:
The part in red has been **removed**
After:
- Documentation issue was created: https://github.com/uyuni-project/uyuni-docs/issues/3845
- No tests: manual tests
Issue(s): https://github.com/SUSE/spacewalk/issues/26787
Port(s): **not backported to 4.3**   …
> Fix: remove SCAP file upload size limit setting (bsc#1240050)

- susemanager-utils/testing/automation/VERSION.Uyuni
I forgot to remove the temporary image used for the unit tests.
> Revert "Use temporary image for pgsql unit tests"

- .github/workflows/build_containers.yml
- testsuite/dockerfiles/buildhost/Dockerfile
- testsuite/dockerfiles/opensuse-minion/Dockerfile
- testsuite/dockerfiles/opensuse/leap/15.6/Dockerfile
update test containers to leap 15.6
No difference.
- No tests
Issue(s): partial fix for https://github.com/SUSE/spacewalk/issues/26493 …
> CI: update test containers to leap 15.6

- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes.mcalmer.fix-reposync-logging
Do not log messages meant for debugging with a tag named "ERROR".
This is missleading and may result in useless bug reports
Issue(s): https://bugzilla.suse.com/show_bug.cgi?id=1240124
Port(s): https://github.com/SUSE/spacewalk/pull/26810 …
> do not log debug messages as error (bsc#1240124)

- .github/workflows/acceptance_tests_coordinator.yml
Cancel in progress adapted for PRs on the Test Coordinator. Otherwise, when changing a PR, your old builds are not cancelled and so your new builds can't start immediately, but you have to wait, in the worst case, one hour for them to start.
No difference.
- No tests
N/A …
> Cancel in progress adapted for PRs on the Test Coordinator

- testsuite/features/profiles/github_runner/Docker/Dockerfile
this goes after https://github.com/uyuni-project/uyuni/pull/10114 and after having built the new containers.
No difference.
- No tests
Issue(s): patial fix for https://github.com/SUSE/spacewalk/issues/26493 …
> CI: update build profiles for gh validation to leap 15.6

- java/code/src/com/redhat/rhn/common/db/datasource/xml/Package_queries.xml
Fix
ERROR: more than one row returned by a subquery used as an expression
Port(s): https://github.com/SUSE/spacewalk/pull/26822
> fix subquery return more than one row error

- testsuite/features/profiles/Kiwi/POS_Image-JeOS6_head/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_head/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_head/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_uyuni/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS6_head/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS6_head/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_head/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_head/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_uyuni/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_uyuni/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_head/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS6_head/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_head/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_head/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_uyuni/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_uyuni/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_head/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS6_head/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_head/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_head/root/etc/systemd/system/image-deployed.service
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_uyuni/root/etc/systemd/system/image-deployed-bundle.service
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_uyuni/root/etc/systemd/system/image-deployed.service
Fixup of commit 2d046a11e1ee5ecd579ecf8d7318e0712ed3502c
* in `image-deployed-bundle.service` we use `venv-salt-bundle` package and `venv-salt-call` utility
* in `image-deployed.service` we use regular `salt` package and `salt-call` utility
No difference.
See https://github.com/SUSE/spacewalk/issues/26399
No ports, Uyuni only (the profiles are shared between all branches)
> Fix usage of Salt for Retail

- java/code/src/com/redhat/rhn/domain/action/salt/StateResult.java
- java/spacewalk-java.changes.mcalmer.Manager-5.0-fix-state-apply-result-formatting
Split takes a regex and the | is a regex symbol or "or". We were splitting at _ or - and not at the places where _|- appear
Port(s): https://github.com/SUSE/spacewalk/pull/26908 …
> fix state apply result formatting

- java/code/src/com/redhat/rhn/frontend/listview/PageControl.java
- java/code/src/com/suse/manager/model/hub/HubFactory.java
- java/code/src/com/suse/manager/model/hub/test/HubFactoryTest.java
This PR changes the way the dynamic query to extract the peripheral list is implemented. It replaces the current string concatenation approach with a `CriteriaQuery`. This is an attempt to fix the SonarCloud issue "Database queries should not be vulnerable to injection attacks" currently reported in https://github.com/uyuni-project/uyuni/pull/10118.
No difference. …
> ISSv3 - Use criteria query instead of concatenating strings

- java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
- java/spacewalk-java.changes.mcalmer.fix-query-for-server
Fix SQL query to resolve error:
```
2025-04-02 13:54:35,403 [salt-event-thread-4] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 42703
2025-04-02 13:54:35,403 [salt-event-thread-4] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - The column name clazz_ was not found in this ResultSet.
2025-04-02 13:54:35,403 [salt-event-thread-4] ERROR com.suse.manager.reactor.PGEventListener - Unexpected exception while executing a MessageAction
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute query
at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate5_hibernate-core.jar:5.3.25.Final]
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuer …
```
> Fix query for Server by machineId (bsc#1240409)

- java/buildconf/build-props.xml
Modifies file `build-props.xml` to correctly build commons-text library.
The jar file `commons-text.jar` is found under the directory `apache-commons-text/commons-text.jar`, so the scripts must be modified accordingly
No difference.
Issue(s): 
Port(s): **not backported: will be found only from version 5.1 on**
> fix: correctly building apache-commons-text

- testsuite/Rakefile
If the filter tests is empty, select all tests.
No difference.
- No tests
N/A …
> Test: fix filter tests when list is empty

- java/code/src/com/redhat/rhn/frontend/xmlrpc/errata/ErrataHandler.java
- java/spacewalk-java.changes.carlo.uyuni-fix-errata-severity-levels
errata.getDetails API call does not show severity levels, if they are not present.
During the investigation of this bug, several points were found and fixed:
1) API documentation was misaligned with the code
2) several other items in the API return structure were missing the "null" case:
cases like the following
if (errata.getSomething() != null) {
errataMap.put("something", StringUtils.defaultString(errata.getSomething().getLabel()));
}
were not issuing an empty value in case the if clause was failing.
No difference.
- API documentation corrected on the apidoc part of the method call
Issue(s): https://github.com/SUSE/spacewalk/issues/26781
Port(s): # **add upstream PR, if any** …
> Fix: severity levels are missing in API output of errata.getDetails (bsc#1240038)

- testsuite/features/secondary/srv_salt_git_pillar.feature
Skipping the Cucumber feature that validates the Git Pillar functionality, so this issue don't affect other tests.
This is related to this bug bsc#1240645
No difference.
- Cucumber tests were skipped
Related discussion in Slack: https://suse.slack.com/archives/C02D134507M/p1743598936398769
No ports. …
> Skip cucumber feature srv_salt_git_pillar

- .github/workflows/build_redis_container.yml
- testsuite/dockerfiles/redis/Dockerfile
- testsuite/dockerfiles/redis/README.md
- testsuite/podman_runner/run_redis.sh
Card: https://github.com/SUSE/spacewalk/issues/26907
This Docker container includes a **Redis** instance, which we will use to query information from the test **code coverage** map. This data is preloaded during the Docker **build** process by connecting to the Redis instance hosted on AWS.
No difference.
- README was created
- No tests
No ports
If you uncheck …
> Build a Redis docker container

- utils/spacewalk-utils.spec
Remove spacewalk-sync-setup also from the filelist in the spec file.
Follow-up  of https://github.com/uyuni-project/uyuni/pull/10163
No difference. …
> remove dropped tool spacewalk-sync-setup from filelist

- testsuite/features/build_validation/core/allcli_sanity.feature
- testsuite/features/build_validation/init_clients/amazon2023_minion.feature
- testsuite/features/build_validation/init_clients/amazon2023_ssh_minion.feature
- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/core/allcli_sanity.feature
- testsuite/features/support/constants.rb
- testsuite/features/support/env.rb
Add Amazon 2023 to BV testsuite
No difference.
No ports: only 5.1 and later.
> Add Amazon 2023 to BV testsuite

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/env.rb
Use download.nue.suse.com instead of download.suse.de. It's same site, but it's filtered differently by our firewalls.
**IMPORTANT NOTE**: I have searched other occurrences of download.suse.de in our test suite. There's quite a bit of them, but none should have an importance on the tests in SLC1.
In particular, in the Kiwi and Docker profiles, `download.suse.de` gets changed into the domain name of the closest mirror anyways.
No difference.
Cucumber tests were added
Port(s):
* 5.0: https://github.com/SUSE/spacewalk/pull/27022
* 4.3: https://github.com/SUSE/spacewalk/pull/27023
> download.suse.de is unreacheable from SLC1

- testsuite/features/secondary/min_change_software_channel.feature
- testsuite/features/step_definitions/navigation_steps.rb
This PR introduces a new method for checking and unchecking checkboxes to address an issue encountered on the `min_change_software_channels.feature` screen. The problem occurs when multiple checkboxes share the same base name with differing suffixes.
No difference.
Issue(s): None, something found during the rrtg tasks
Port(s): 
- Manager 5.0:
- Manager 4.3: …
> QE: Modifiying some problems in checking and unchecking checkboxes

- testsuite/features/secondary/buildhost_docker_auth_registry.feature
- testsuite/features/secondary/buildhost_docker_build_image.feature
The build of docker images in the buildhost takes longer than before. Could be that the performance of the buildhost is worse. Given the buildhost is not part of the product, we will just wait a bit more for the build to finish.
No difference.
- No tests …
> CI: fix buildhost docker tests

- rel-eng/uyuni-check-version
The default location of oscrc config file is `~/.config/osc/oscrc`. 
When running the `rel-eng/uyuni-check-version` validation script, search for a config at both `~/.config/osc/oscrc` and legacy path ``~/.oscrc``.
No difference.
- No tests: internal script used only by relengs
Issue(s): #
Port(s): NONE required …
> Read the oscrc config from default and legacy locations

- containers/proxy-tftpd-image/proxy-tftpd-image.changes.nadvornik.replace_fqdns
- containers/proxy-tftpd-image/tftp_wrapper.py
- java/code/src/com/redhat/rhn/manager/system/proxycontainerconfig/ProxyContainerConfigCreateGenerateFileMaps.java
- java/code/src/com/suse/proxy/test/ProxyConfigUpdateFileAcquisitorTest.java
- java/code/src/com/suse/proxy/update/ProxyConfigUpdateFileAcquisitor.java
- java/spacewalk-java.changes.nadvornik.replace_fqdns
- susemanager-utils/susemanager-sls/salt/proxy/apply_proxy_config.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.nadvornik.replace_fqdns
This PR adds `replace_fqdns` entry to proxy config and uses it to replace server fqdn in chained proxy configuration.
This is a forward-port of https://github.com/SUSE/spacewalk/pull/26299 with added new code for the simplified proxy onboarding.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26066
https://github.com/SUSE/spacewalk/issues/26279
https://bugzilla.suse.com/show_bug.cgi?id=1236166
Port(s):  https://github.com/SUSE/spacewalk/pull/26299 …
> Replace server hostname in chained proxy tftp container (bsc#1236166)

- web/html/src/manager/admin/setup/products/products-scc-dialog.module.scss
- web/html/src/manager/admin/setup/products/products-scc-dialog.tsx
- web/spacewalk-web.changes.eth.bsc1240131
The product page sidebar was not using the updated font due to being overwritten by the icon font styles.
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1240131
Fixes https://github.com/SUSE/spacewalk/issues/26808 …
> Fix layout issues in product page (bsc#1240131)

- testsuite/documentation/guidelines.md
Cucumber guidelines: avoid steps inside steps
No difference.
This is an internal documentation PR.
Doc only.
No ports to 4.3 nor 5.0, feeling too lazy.
> Avoid steps inside steps

- java/code/src/com/redhat/rhn/taskomatic/TaskomaticApi.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/migration/test/IssMigratorTest.java
- java/code/src/com/suse/manager/hub/test/HubManagerTest.java
- java/code/src/com/suse/manager/model/hub/HubFactory.java
- java/code/src/com/suse/manager/webui/controllers/admin/handlers/HubApiController.java
- java/code/src/com/suse/manager/webui/utils/SparkApplicationHelper.java
- java/spacewalk-java.changes.carlo.uyuni-fix-deregister
This PR fixes bugs when deregistering the peripheral servers.
They should be removed from the Hub's list of peripherals and, on their end, should no longer display the Hub's data in the Hub Configuration > Hub Details UI page.
The de-registering must be correctly been done both from the Hub and the Peripheral side
Substitutes closed PR (https://github.com/uyuni-project/uyuni/pull/10147)
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26845
Port(s): no backports (issv3) …
> Uyuni fix deregister

- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/SerializerRegistry.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ServerInfoJsonSerializer.java
- java/code/src/com/suse/manager/hub/DefaultHubInternalClient.java
- java/code/src/com/suse/manager/hub/HubController.java
- java/code/src/com/suse/manager/hub/HubInternalClient.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/code/src/com/suse/manager/hub/PeripheralRegistrationException.java
- java/code/src/com/suse/manager/hub/migration/IssMigrator.java
- java/code/src/com/suse/manager/hub/migration/test/IssMigratorTest.java
- java/code/src/com/suse/manager/hub/test/HubManagerTest.java
- java/code/src/com/suse/manager/model/hub/ServerInfoJson.java
- java/code/src/com/suse/manager/webui/controllers/admin/handlers/HubApiController.java
- java/code/src/com/suse/manager/xmlrpc/iss/test/HubHandlerTest.java
- java/spacewalk-java.changes.carlo.uyuni-fix-overregister
- schema/spacewalk/common/data/endpoint.sql
- schema/spacewalk/susemanager-schema.changes.carlo.uyuni-fix-overregister
- schema/spacewalk/upgrade/susemanager-schema-5.1.6-to-susemanager-schema-5.1.7/100-rbac-endpoint.sql
This fix avoid that peripherals already taken (subscribed to a hub) could be registered from a different hub.
Furthermore, it correctly deregister when a server is both hub and peripheral
Before:
After:
Issue(s): 
Port(s): 
> Fix: Correctly register and deregister with multiple roles

- java/code/src/com/redhat/rhn/common/hibernate/AnnotationRegistry.java
- java/code/src/com/redhat/rhn/manager/setup/MirrorCredentialsManager.java
- java/code/src/com/redhat/rhn/taskomatic/task/ForwardRegistrationTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/ForwardRegistrationTaskTest.java
- java/code/src/com/suse/manager/hub/test/ControllerTestUtils.java
- java/code/src/com/suse/scc/SCCEndpoints.java
- java/code/src/com/suse/scc/SCCSystemRegistrationManager.java
- java/code/src/com/suse/scc/client/SCCWebClient.java
- java/code/src/com/suse/scc/model/SCCSystemCredentialsJson.java
- java/code/src/com/suse/scc/proxy/SCCProxyFactory.java
- java/code/src/com/suse/scc/proxy/SCCProxyManager.java
- java/code/src/com/suse/scc/proxy/SCCProxyRecord.java
- java/code/src/com/suse/scc/proxy/SccProxyStatus.java
- java/code/src/com/suse/scc/proxy/SccProxyStatusEnumType.java
- java/code/src/com/suse/scc/registration/SCCSystemRegistration.java
- java/code/src/com/suse/scc/registration/SCCSystemRegistrationUpdateCachedItems.java
- java/code/src/com/suse/scc/test/SCCSystemRegistrationManagerTest.java
- java/code/src/com/suse/scc/test/SCCSystemRegistrationTest.java
- schema/spacewalk/common/tables/suseSccProxy.sql
- schema/spacewalk/common/tables/tables.deps
- schema/spacewalk/postgres/class/scc_proxy_status_t.sql
- schema/spacewalk/upgrade/susemanager-schema-5.1.6-to-susemanager-schema-5.1.7/600-create_suseSccProxy.sql
This is the upstream branch referred to https://github.com/uyuni-project/uyuni/pull/10229
SUSE Manager send data about registered systems to SCC. In a Hub scenario, the peripheral server should send the data to the Hub and the Hub should send it to SCC.
This PR puts the basis of having the Hub acting as a proxy to the SCC, in particular:
- Creates DB schema on the Hub to hold data send from peripheral server 
- Add endpoints to act as if it was an SCC:
PUT /connect/organizations/systems (create systems)
DELETE /connect/organizations/systems/:id (delete systems)
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/25350 …
> Issv3 scc metering

- java/code/src/com/suse/manager/hub/HubController.java
- java/spacewalk-java.changes.mcalmer.issv3-call-refresh
To finish a channel sync from hub to peripheral, we need to call the product refresh.
This PR schedule a refresh with a delay of 10 seconds to have all the changes comited to the DB.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27020 …
> call product refresh after the channel sync call

- python/spacewalk/satellite_tools/spacewalk-debug
- python/spacewalk/spacewalk-backend.changes.wtmpx.spacewalk-debug
Remove bootloader linux and initrd files from spacewalk-debug
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/27091 …
> Remove bootloader linux and initrd files from spacewalk-debug

- schema/spacewalk/common/data/endpoint.sql
- schema/spacewalk/common/data/endpointNamespace.sql
- schema/spacewalk/susemanager-schema.changes.cbbayburt.bsc1241893
- schema/spacewalk/upgrade/susemanager-schema-5.1.6-to-susemanager-schema-5.1.7/101-rbac-mappings.sql
This patch adds the missing RBAC mappings as found in the testsuite, including the one causing the mentioned bug.
https://bugzilla.suse.com/show_bug.cgi?id=1241893
> Add missing RBAC mappings (bsc#1241893)

- java/code/webapp/WEB-INF/nav/system_detail.xml
- java/spacewalk-java.changes.cbbayburt.bsc1241697
A typo in RBAC ACLs causes ISE on some system pages.
Fixes https://github.com/SUSE/spacewalk/issues/27069
https://bugzilla.suse.com/show_bug.cgi?id=1241697
> Fix typo in RBAC ACL 'authorized_for' in system details header (bsc#1241697)

- testsuite/features/step_definitions/setup_steps.rb
Currently, when running BV with slmicro6X minions, the add MU step is failing because the MU repositories for those minions are not signed by SUSE authority. (see: https://suse.slack.com/archives/C02CLBJ5RGF/p1744337596069169)
To solve this issue, uncheck the metadata check when we have a slmicro minion.
No difference.
Port(s):
- 4.3: https://github.com/SUSE/spacewalk/pull/27018
- 5.0: https://github.com/SUSE/spacewalk/pull/27017 …
> Bv fix issue add mu slmicro6x

- uyuni/uyuni-storage-setup/scripts/susemanager-storage-setup-functions.sh
- uyuni/uyuni-storage-setup/uyuni-storage-setup.changes.mackdk.5.0-fix-storage-setup-selinux
This PR adds a check to ensure that selinuxenabled before executing it. In fact, in SLE S it is not installed by default and this results on an error, even if the script works correctly.
Port of https://github.com/SUSE/spacewalk/pull/27014
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26982 …
> Ensure selinuxenabled exists before executing it (bsc#1241060)

- java/code/src/com/redhat/rhn/domain/server/Server.java
- java/code/src/com/redhat/rhn/frontend/action/systems/sdc/SystemChannelsAction.java
- java/code/src/com/redhat/rhn/frontend/dto/SystemCompareDto.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/manager/ssm/ChannelChangeAction.java
- java/code/src/com/redhat/rhn/manager/ssm/ChannelChangeDto.java
- java/code/src/com/redhat/rhn/manager/ssm/SsmManager.java
- java/code/src/com/redhat/rhn/manager/ssm/channelchange/AbstractChannelChange.java
- java/code/src/com/redhat/rhn/manager/ssm/channelchange/ChannelChange.java
- java/code/src/com/redhat/rhn/manager/ssm/channelchange/ChannelChangeFactory.java
- java/code/src/com/redhat/rhn/manager/ssm/channelchange/DefaultBaseChange.java
- java/code/src/com/redhat/rhn/manager/ssm/channelchange/ExplicitBaseChange.java
- java/code/src/com/redhat/rhn/manager/ssm/channelchange/OnlyChildChannelsChange.java
- java/code/src/com/redhat/rhn/manager/ssm/test/SsmManagerTest.java
- java/spacewalk-java.changes.mcalmer.improve-channel-change-performance
This PR improves the performance of the change channel operation. This was currently too slow when executed on many systems through SSM and it was causing issue in the UI.
Port of https://github.com/SUSE/spacewalk/pull/26720
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26642
If you …
> Improve change channel performance (bsc#1239154)

- containers/server-image/root/usr/bin/uyuni-configfiles-sync
- containers/server-image/server-image.changes.mcalmer.Manager-5.0-improve-uyuni-configfiles-sync
- No sync when a user modified file was not changed between 2 image versions
- No backup for files which would be replaced directly from RPM as well
Port(s): https://github.com/SUSE/spacewalk/pull/26737 …
> Improve uyuni configfiles sync

- .github/workflows/acceptance_tests_base.yml
This PR adds a GitHub Actions step to upload Cucumber JSON reports as a GitHub Actions Artifact after running PR acceptance tests. Having these reports uploaded as artifacts ensures we retain valuable test result data tied to specific code changes. This data is useful for long-term analysis and especially for the [AI-Driven Test Selection](https://github.com/openSUSE/mentoring/issues/244) project proposed for Google Summer of Code 2025.
No difference.
- No tests
No links. …
> Upload Cucumber JSON Reports For PR Acceptance Tests

- .github/workflows/acceptance_tests_base.yml
Give a unique name per cucumber report on the artifacts.
Otherwise we have this issue:  
```
Run actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
With the provided path, there will be 3 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
No difference.
- No tests
No ports …
> Give a unique name per cucumber report on the artifacts

- java/code/src/com/redhat/rhn/domain/kickstart/KickstartData.java
- java/spacewalk-java.changes.cbosdo.log-sanitizing
Fixes a Sonarcloud issue with potential user controlled data being logged, and that debug message isn't that useful.
No difference.
- No tests: logging removed
Issue(s): https://github.com/SUSE/spacewalk/issues/26928
Port(s): https://github.com/SUSE/spacewalk/pull/27026 https://github.com/SUSE/spacewalk/pull/27025
If you need to …
> Remove unneeded debug log message

- containers/server-image/Dockerfile
- containers/server-image/root/etc/krb5.conf.d
- containers/server-image/server-image.changes.cbosdo.5.0-krb-symlink
The /etc/krb5.conf.d/crypto-policies symlink being relative it doesn't work with the `/etc/rhn/krb5.conf.d` location. Using an absolute symlink to make everyone happy. bsc#1237938
Also fix a regression introduced with the move to the tarball files: /etc/rhn/krb5.conf.d should be a symlink to /etc/krb5.conf.d
No difference.
- No tests: AD integration is not automatically tested
Issue(s): https://github.com/SUSE/spacewalk/issues/26563
Port(s): https://github.com/SUSE/spacewalk/pull/26951
If you don't …
> Fix broken /etc/rhn/krb5.conf.d/crypto-policies symlink

- containers/server-image/Dockerfile
trailing && \ in RUN directive may break the docker image build.
No difference.
- No tests: build failure fix
Issue(s): # …
> Remove trailing && \ in server-image Dockerfile

- testsuite/features/support/constants.rb
Fine-tune timeouts measured experimentally on 5.0 BV.
Note: I changed rockylinux8 to rockylinux-8 and rockylinux9 to rockylinux-9. These are the channel names I see on 5.0.
There's a possibility that the channel names are slightly different between Manager and Uyuni. If that's the case, we will need them in double, one with a caret, and once without :-( .
No difference.
Cucumber tests were added
Port(s):
* 5.0: https://github.com/SUSE/spacewalk/pull/27108
* 4.3: https://github.com/SUSE/spacewalk/pull/27109
> Timeouts measured on 5.0 BV

- testsuite/features/build_validation/migration/salt_migration_minion_migration.feature
- testsuite/features/build_validation/migration/slemicro54_minion_migration.feature
- testsuite/features/build_validation/migration/slemicro54_ssh_minion_migration.feature
- testsuite/features/reposync/allcli_update_activationkeys.feature
Use the new names for the Manager tools instead of the old names.
No difference.
Cucumber tests were changed
Port(s): no ports, 5.1+ only!
> Use the new names for the Manager tools

- java/buildconf/test/rhn.conf.postgresql-example
- java/code/src/com/redhat/rhn/domain/notification/UserNotificationFactory.java
- java/code/src/com/redhat/rhn/domain/notification/test/NotificationFactoryTest.java
- java/spacewalk-java.changes.mcalmer.fix-notification-filter
Since we use Labeled class, name is different now.
To compare with the list of disabled notifications we need to use the "label".
No difference.
- Unit test added
Issue(s): https://github.com/SUSE/spacewalk/issues/27132
Port(s): none - only 5.1+ issue …
> Fix filtering of notification messages (bsc#1242141)

- java/code/src/com/suse/manager/ssl/SSLCertManager.java
- java/code/src/com/suse/manager/ssl/test/SSLCertManagerTest.java
- java/spacewalk-java.changes.cbosdo.no-rpm
- spacewalk/certs-tools/mgr-ssl-tool.sgml
- spacewalk/certs-tools/rhn_ssl_tool.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.cbosdo.no-rpm
- spacewalk/certs-tools/sslToolCli.py
- spacewalk/certs-tools/sslToolConfig.py
- utils/spacewalk-hostname-rename
- utils/spacewalk-utils.changes.cbosdo.no-rpm
Note that removing the options for --gen-ca is not yet possible since this RPM is used by the kiwi image building. bsc#1235696
No difference.
- No tests: code removal
Issue(s): https://github.com/SUSE/spacewalk/issues/26194 …
> Remove RPM options and feature in rhn-ssl-tool --gen-server

- java/code/src/com/redhat/rhn/frontend/servlets/AuthorizationFilter.java
- java/spacewalk-java.changes.cbbayburt.bsc1242069
As part of the filtering process, RBAC looks up requested URIs in Spark's route list. However, since saltboot `HEAD` requests are not handled by Spark or tomcat, but by apache, RBAC cannot find a corresponding Spark route and blocks access.
Saltboot URIs are unauthenticated, so RBAC can be bypassed for them.
This PR bypasses Spark route lookup for unauthenticated URIs.
https://bugzilla.suse.com/show_bug.cgi?id=1242069 …
> Fix saltboot endpoint access (bsc#1242069)

- containers/server-attestation-image/Dockerfile
- containers/server-attestation-image/server-attestation-image.changes.mcalmer.coco-fix
procps was removed from the base container. To use pgrep we need to install it now in our container.
This fix the health check
No difference.
- TBD
Port(s): https://github.com/SUSE/spacewalk/pull/27160
Check [How to …
> Fix the health check of the container (bsc#1240604)

- testsuite/features/step_definitions/command_steps.rb
This PR lets the redfish tests pass after these changes:
- https://github.com/uyuni-project/uyuni/pull/9622
- https://github.com/uyuni-project/uyuni-tools/pull/572
No difference.
Cucumber tests were modified.
No ports, needed only in HEAD.
> --no-rpm option has been removed from command rhn-ssl-tool

- testsuite/features/secondary/proxy_container_cobbler_pxeboot.feature
until it disappears
Changes a step for another one better for waiting for the disappearance of a text independently of how much time the product takes in doing a task
No difference.
Issue(s): None, somthing that was found during the RRTG task
Port(s): None, it happens in principle just in uyuni …
> QE: Swapping a step that checks if a text disappears for one that waits

- containers/server-image/Dockerfile
- containers/server-image/server-image.changes.deneb-alpha.bsc1240645_fix_pygit2
**this is an alternative version of #10112 for not installing at the same time both python3 and python311 versions of the package, ~but in any case, python311-pygit2 is not available for Multi-Linux Manager and this PR or the alternative one that I did can NOT be merged.~**
python311-pygit2:
* Head:Other: https://build.suse.de/request/show/372959
* 5.1: https://build.suse.de/request/show/372960 
**See:  also https://bugzilla.suse.com/show_bug.cgi?id=1240645#c1**
SUSE Linux Enterprise Server 15 SP7 uses Python3.11 Salt module version and there's now the need to configure which Python interpreter version we want to use for a given module. This PR introduces a new argument called USEPYTHON that can be controlled in the project config of the build service. The default value of this argument …
> Make the Python interpreter version configurable (bsc#1240645)

- testsuite/features/secondary/srv_reportdb.feature
- testsuite/features/step_definitions/command_steps.rb
The ReportDB tests must be adapted to the separated container situation.
No difference.
No ports, 5.1+ only.
> Fix ReportDB tests

- java/code/src/com/redhat/rhn/taskomatic/task/test/ForwardRegistrationTaskTest.java
- java/code/src/com/suse/scc/SCCEndpoints.java
Make sure that correct SCC proxy endpoints are set, when coming from the hub (e.g. "/hub/scc/connect/organizations/systems")
No difference.
Issue(s): # https://github.com/SUSE/spacewalk/issues/27055
Port(s): # no backports
> ISSv3: Set correct SCC proxy endpoints

- .github/workflows/external_pr_labeler.yml
This PR modifies the action to use a GitHub App installation key instead of a personal access token for authorization, as recommended by GitHub.
The API call in the action requires an additional permission (read org members). A GitHub app installation key is used to provide it.
See also: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow  …
> Fail the external PR labeler GH action if the API call fails

- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/suse/manager/hub/DefaultHubInternalClient.java
- java/code/src/com/suse/manager/hub/test/ControllerTestUtils.java
- java/code/src/com/suse/manager/hub/test/HubControllerTest.java
- java/spacewalk-java.changes.carlo.uyuni-ch-reassign-org-fix
Once a custom channel is assigned to a specific peripheral org, it cannot be just re-assigned to a different peripheral organization: this has to be avoided when making **an API call**
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27186
Port(s): no ports needed (ISSV3)
> fix ISSv3 channel sync API bug: a custom channel cannot be re-assigned to a different peripheral organization

- java/code/src/com/redhat/rhn/taskomatic/task/ForwardRegistrationTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/ForwardRegistrationTaskTest.java
- java/code/src/com/suse/scc/SCCSystemRegistrationManager.java
- java/spacewalk-java.changes.carlo.issv3-scc-proxy-register
Implements and tests the registration process of the hub towards the SCC
No difference.
Issue(s): # https://github.com/SUSE/spacewalk/issues/27057
Port(s): # no backports
> Issv3: Implement and test SCC proxy registration/deregistration from Hub towards SCC

- java/code/src/com/redhat/rhn/domain/action/salt/ApplyStatesActionDetails.hbm.xml
- java/code/src/com/redhat/rhn/domain/action/salt/ApplyStatesActionDetails.java
- java/code/src/com/redhat/rhn/manager/action/ActionManager.java
- java/code/src/com/suse/manager/reactor/messaging/ApplyStatesEventMessage.java
- java/code/src/com/suse/manager/reactor/messaging/ApplyStatesEventMessageAction.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/manager/webui/utils/salt/LocalCallWithExecutors.java
- susemanager-utils/susemanager-sls/salt/supportdata/init.sls
- susemanager-utils/susemanager-sls/src/modules/supportdata.py
- susemanager-utils/susemanager-sls/src/tests/test_module_supportdata.py
On transactional systems we need to run supportdata state in direct mode.
Bring back the direct mode implementation from 5.0 (db schema still exists)
and call supportdata state always in direct mode.
Exclude installation and update of the supportdata tool when we are running on a transactional system.
SL-Micro has supportutils as requires in its base pattern. So it should be available by default.
No difference.
- part of bigger test case
Port(s): no port needed …
> Supportdata fix transactional

- testsuite/features/secondary/proxy_container_cobbler_pxeboot.feature
- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/upload_files/copy-tftpboot-files.exp
There is an occurrence of the expect command for establish the communication between two machines for testing purposes. Therefore for removing the expect command from our testsuite a key exchange should be performed by sumaform to allow the communication between `build_host` and `server`.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27138
Port(s): None. It is just going to be applied in HEAD. …
> QE: Removing expect command from testsuite

- java/code/src/com/redhat/rhn/domain/scc/SCCCachingFactory.java
- java/code/src/com/redhat/rhn/taskomatic/task/ForwardRegistrationTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/test/ForwardRegistrationTaskTest.java
- java/code/src/com/suse/scc/SCCEndpoints.java
- java/code/src/com/suse/scc/SCCSystemRegistrationManager.java
- java/code/src/com/suse/scc/client/SCCClient.java
- java/code/src/com/suse/scc/client/SCCFileClient.java
- java/code/src/com/suse/scc/client/SCCWebClient.java
- java/code/src/com/suse/scc/model/SCCRegisterSystemItem.java
- java/code/src/com/suse/scc/model/SCCUpdateSystemItem.java
- java/code/src/com/suse/scc/proxy/SCCProxyFactory.java
- java/code/src/com/suse/scc/proxy/SCCProxyManager.java
- java/code/src/com/suse/scc/proxy/SCCProxyRecord.java
- java/code/src/com/suse/scc/registration/SCCSystemRegistrationContext.java
- java/code/src/com/suse/scc/registration/SCCSystemRegistrationCreateUpdateSystems.java
- java/code/src/com/suse/scc/registration/SCCSystemRegistrationSystemDataAcquisitor.java
- java/code/src/com/suse/scc/registration/SCCSystemRegistrationUpdateCachedItems.java
- java/code/src/com/suse/scc/test/SCCRegisterUpdateSystemItemTest.java
- java/code/src/com/suse/scc/test/SCCSystemRegistrationManagerTest.java
- java/code/src/com/suse/scc/test/SCCSystemRegistrationTest.java
- java/code/src/com/suse/scc/test/registration/SCCSystemRegistrationCreateUpdateSystemsTest.java
- java/code/src/com/suse/scc/test/registration/SCCSystemRegistrationSystemDataAcquisitorTest.java
- java/spacewalk-java.changes.carlo.issv3-update-last-seen
- schema/spacewalk/common/tables/suseSccProxy.sql
- schema/spacewalk/susemanager-schema.changes.carlo.issv3-update-last-seen
- schema/spacewalk/upgrade/susemanager-schema-5.1.7-to-susemanager-schema-5.1.8/100-add-updatelastseen-susesccproxy.sql
Implements and tests the update last seen mechanism when a hub is acting as an SCC proxy
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27058
> Issv3 SCC: Implement and test the update last seen mechanism when a hub is acting as an SCC proxy

- schema/spacewalk/susemanager-schema.changes.rjpmestre.bsc1243829
- schema/spacewalk/upgrade/susemanager-schema-5.1.6-to-susemanager-schema-5.1.7/200-proxy-server-group-members.sql
With the Simplified Proxy onboarding, we introduced a proxy entitlement that's automatically added for new proxies.
However, existing proxies (e.g., after an upgrade) were missing this entitlement. This PR fixes that, by ensuring all proxies are added to the proxy server group and also updates the group's member count.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27362
Port(s): 
If you …
> Add missing proxies entitlements on upgrade (bsc#1243829)

- susemanager-utils/susemanager-sls/salt/channels/gpg-keys.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.check-gpgkey-file-exists
When importing GPG keys which are defined with a file URL, check if the file exists.
If not, skip the key.
This is useful when the key file was renamed.
No difference.
Port(s): TBD
Check …
> For GPG keys using file URL, check if the file exists

- susemanager-utils/susemanager-sls/src/modules/sap.py
- susemanager-utils/susemanager-sls/src/tests/test_module_sap.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.vzhestkov.sap-workloads-list-speedup
In some deployments `sap` module could cause high IO workload in case of having large amount of directories inside the sap base path not related to sap instances.
No difference.
Tracks: https://github.com/SUSE/spacewalk/issues/27037 …
> Optimize sap module to prevent high IO workload (bsc#1241455)

- schema/spacewalk/common/data/endpoint.sql
- schema/spacewalk/susemanager-schema.changes.carlo.issv3-scc-rbac-endpoints
- schema/spacewalk/upgrade/susemanager-schema-5.1.7-to-susemanager-schema-5.1.8/200-rbac-endpoints-for-scc.sql
This PR adds missing RBAC entries for ISSv3 SCC endpoints
See https://github.com/uyuni-project/uyuni/pull/10325#discussion_r2120336776
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/25350 …
> Add Issv3 SCC missing rbac endpoint entries

- java/code/src/com/redhat/rhn/domain/product/SUSEProductFactory.java
- java/spacewalk-java.changes.cbbayburt.bsc1239907
In SLES for SAP, kernel packages are served across different products. This PR updates the DB query to show kernel versions from the base product too.
Port of: https://github.com/SUSE/spacewalk/pull/26956
Fixes https://github.com/SUSE/spacewalk/issues/26777
https://bugzilla.suse.com/show_bug.cgi?id=1239907 …
> Show full list of kernel versions in live-patching filter template form (bsc#1239907)

- testsuite/features/reposync/srv_create_bootstrap_repositories.feature
Removes the workaround that disables bootstrap repo creation on proxy, now the products are enabled in SCC and we can run this.
No difference.
Issue(s):  no issue, directly from testsuite review and partly https://github.com/SUSE/spacewalk/issues/25943#issuecomment-2930136463
Port(s): was only needed on head since that's where we have 5.1 only
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuy …
> Remove workaround from testsuite

- susemanager-utils/supportutils-plugin-susemanager-client/susemanagerclient
- susemanager-utils/supportutils-plugin-susemanager/susemanager
Replaces the obsolete `validate_rpm` function with `rpm_verify` provided by supportutils.
Replace the removed `check_service` function bsc#1216231
No difference.
- No tests
None …
> Fix old supportutils functions

- java/code/src/com/suse/oval/config/test/OVALConfigTest.java
During recent downtime of ftp.suse.com, a java_pgsql_tests task began failing due to live url health check against that host. We confirmed these checks do not drive any production logic or are reused. So for now we can remove them and stabilize the test suite.
No difference.
- No tests: adjusted tests …
> Remove real url health connectivity test

- python/spacewalk/common/suseLib.py
- python/spacewalk/spacewalk-backend.changes.meaksh.master-bsc1243460
- python/test/unit/spacewalk/common/test_suseLib.py
This PR prevents an issue in `spacewalk-repo-sync` when a HTTP Proxy is configured and the password for it contains a comma (`,`) as part of it:
```console
uyuni-server:/ # spacewalk-repo-sync -c mytestchannel
17:11:03 ======================================
17:11:03 | Channel: mytestchannel
17:11:03 ======================================
17:11:03 Sync of channel started.
17:11:05 Unexpected error: <class 'TypeError'>
17:11:05 Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 754, in sync
repo_checksum_type = plugin.get_md_checksum_type()
File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 1141, in get_md_checksum_type
if self._md_exists("repomd"):
File …
```
> reposync: allow commas a part of HTTP Proxy passwd (bsc#1243460)

- web/html/javascript/susemanager-setup-wizard-mirror-credentials.js
- web/spacewalk-web.changes.carlo.uyuni-bsc1243765-list-subscriptions
This PR fixes bug 1243765.
When entering correct credentials, and then clicking on `list subscriptions` for the entered credentials,  the first time the UI is misbehaving, not showing any information and giving a log error.
The UI is behaving correctly from the second time it's clicked
The error is in the code of the "list subscription button"
`<a href="javascript:void(0);" onCLick="initSubscriptions('<DB_ID>')" data-bs-toggle="modal" data-bs-target="#modal-list-subscriptions">
`
clicking on that button fires two function calls: the "onClick" one 
```
function initSubscriptions(id) {
subscriptionsId = id;
}
```
and the one fired when the modal is shown
```
jQuery('#modal-list-subscriptions').on('show.bs.modal', function() {
showSpinner("modal-list-subscriptions-body"); …
```
> Fix setup wizard organization credentials list subscriptions not showing correctly the first time (bsc#1243765)

- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.abid.use-env-varibale-for-hostname
This add the possibility to use the env variable for hostname, this will significantly improve the situation where users needs to have a bootstrap script for each proxy and some users have number of proxies in 4 digits
No difference.
- No documentation needed: I will create a PR for the visibility
- No tests:  Not covered
Issue(s): # …
> Use the env variables MGR_SERVER_HOSTNAME for the hostname

- java/code/src/com/redhat/rhn/manager/satellite/ConfigureSatelliteCommand.java
- java/code/src/com/redhat/rhn/manager/satellite/ProxySettingsConfigureSatelliteCommand.java
- java/code/src/com/redhat/rhn/manager/satellite/SystemCommandExecutor.java
- java/code/src/com/redhat/rhn/manager/setup/ProxySettingsDto.java
- java/code/src/com/redhat/rhn/manager/setup/ProxySettingsManager.java
- java/code/src/com/redhat/rhn/manager/setup/test/ProxySettingsManagerTest.java
- java/spacewalk-java.changes.carlo.uyuni-fix-store-proxy-passwd
- spacewalk/admin/rhn-config-satellite.pl
- spacewalk/admin/spacewalk-admin.changes.carlo.uyuni-fix-store-proxy-passwd
- spacewalk/config/etc/sudoers.d/spacewalk
- spacewalk/config/spacewalk-config.changes.carlo.uyuni-fix-store-proxy-passwd
The page SUSE Multi-Linux Manager>Admin>Setup Wizard>HTTP Proxy lets set the proxy hostname, username, and password. The result ends up into tomcat running a command like:
/usr/bin/sudo /usr/bin/rhn-config-satellite.pl --target=/etc/rhn/rhn.conf --option=server.satellite.http_proxy=DUMMYPROXYHOSTNAME:1 --option=server.satellite.http_proxy_username=DUMMYPROXYUSERNAME --option=server.satellite.http_proxy_password=DUMMYPROXYPASSWORD 2>&1 > /dev/null
unfortunately, since this is a sudo invocation , there appears a log entry into /var/log/messages like:
2025-06-04T16:07:21.003177+02:00 uyuni-server sudo:   tomcat : PWD=/usr/share/tomcat ; USER=root ; COMMAND=/usr/bin/rhn-config-satellite.pl --target=/etc/rhn/rhn.conf --option=server.satellite.http_proxy=DUMMYPROXYHOSTNAME:1 …
> Uyuni fix store proxy passwd  (bsc#1242148)

- containers/proxy-httpd-image/proxy-httpd-image.changes.meaksh.master-more-secure-randomness
- containers/proxy-httpd-image/uyuni-configure.py
- proxy/proxy/rhnProxyAuth.py
- proxy/proxy/spacewalk-proxy.changes.meaksh.master-more-secure-randomness
- python/spacewalk/server/rhnServer/server_certificate.py
- python/spacewalk/server/rhnServer/server_lib.py
- python/spacewalk/spacewalk-backend.changes.meaksh.master-more-secure-randomness
- susemanager-utils/susemanager-sls/modules/engines/mgr_events.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.meaksh.master-more-secure-randomness
This PR makes random generation more secure in certain parts of Python code, as warned by SonarQube analysis:
- https://sonarcloud.io/project/security_hotspots?id=uyuni-project_uyuni&hotspots=AYMYhbVO5TQr2KFg-1yn
- https://sonarcloud.io/project/security_hotspots?id=uyuni-project_uyuni&hotspots=AYMYhbVO5TQr2KFg-1yo
- https://sonarcloud.io/project/security_hotspots?id=uyuni-project_uyuni&hotspots=AYMYhb5p5TQr2KFg-2VI
- https://sonarcloud.io/project/security_hotspots?id=uyuni-project_uyuni&hotspots=AY1Basdxy5vaCD3iDu6p
- https://sonarcloud.io/project/security_hotspots?id=uyuni-project_uyuni&hotspots=AY1Barc9y5vaCD3iDu1i
No difference.
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the …
> Use more secure random generation in Python code

- testsuite/features/secondary/srv_password_restriction.feature
- testsuite/features/step_definitions/api_common.rb
- testsuite/features/step_definitions/common_steps.rb
- testsuite/features/step_definitions/navigation_steps.rb
- testsuite/features/support/navigation_step_helper.rb
- testsuite/run_sets/secondary.yml
Add new feature to test password policies
No difference.
Issue(s): #
Port(s):  Need port after validation …
> Add new password policy test

- testsuite/features/build_validation/smoke_tests/smoke_tests.template
- testsuite/features/step_definitions/navigation_steps.rb
Fix grafana dashboard test.
Use the url. I was not able to make the button and field working.
No difference.
Issue(s): #
Port(s): See if port needed
If you need …
> Fix grafana dashboard test.

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/support/remote_node.rb
During mgr-create-bootstrap-repo, the output can be truncated and create issue.
After investigation by @Bischoff, we found out the error was cause by podman known issue. (https://github.com/SUSE/spacewalk/issues/25605).
A solution to this error is to use the option -it. Using this command all the time is creating other issue so it's better to only use it when needed (eg: create bootstrap repo).
To do so:
- Add possibility to change mgrctl exec option
- Use -it option for mgr-create-bootstrap-repo
<details>
```hcl
I create all bootstrap repos with --with-custom-channels option
Scenario: Create the bootstrap repository for opensuse156arm_minion                                 # features/build_validation/create_bootstrap_repositories/opensuse156arm_minion_create_bootstrap_repository.feature:1 …
```
> Add possibility to change mgrctl exec option / Use -it option for mgr-create-bootstrap-repo

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/support/constants.rb
Sles12sp is now LTSS.
Add the product for BV testing.
No difference.
Issue(s): # …
> Add ltss product for sles12sp5

- testsuite/Rakefile
Fix wrong placed cucumber_opts in Rakefile
No difference.
- No tests
No ports. …
> Fix wrong placed cucumber_opts in Rakefile

- python/spacewalk/common/suseLib.py
- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes.mcalmer.Manager-5.0-fix-RHUI-mirrorlist-fetching
- python/test/unit/spacewalk/satellite_tools/test_yum_src.py
RHUI specify a CA bundle which does not include the Root CA, but only the intermediate CAs.
This seems to be valid as yum, zypp and curl successfully work with such a bundle.
But we use python requests to fetch the mirrorlist and look for the content type and this module fail to download the content without the Root CA in the bundle.
This is a re-write to change python requests into pycurl.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/27431
If you don't …
> Fix fetching the mirrorlist with a RHUI ca bundle (bsc#1243241)

- java/code/src/com/redhat/rhn/domain/channel/ChannelFactory.java
- java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
- java/code/src/com/redhat/rhn/manager/channel/test/ChannelManagerTest.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
- java/code/src/com/suse/manager/hub/HubManager.java
- java/spacewalk-java.changes.carlo.uyuni-fix-1244222-hub-sync-ch-before-parent
This PR allows correct sync of an original channel after the relative cloned channel has been synced, fixing bsc#1244222
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27457
Port(s): not backported to 4.3 nor to 5.0 (ISSv3 hub online sync)
> Uyuni fix hub sync ch before parent (bsc#1244222)

- testsuite/run_sets/secondary.yml
Removes min_deblike_openscap_audit feauture because it's not supported by ubuntu 24.
No difference.
- Cucumber tests were deleted
Issue(s): None.
Port(s): 
- Manager 5.0: https://github.com/SUSE/spacewalk/pull/27564/files …
> QE: Commenting min_deblike_openscap_audit feauture because openscap is not supported by ubuntu 24

- search-server/spacewalk-search/spacewalk-search.changes.cbosdo.oracle-driver-search
- search-server/spacewalk-search/src/config/search/rhn_search.conf
For some reason the config defaults of the search server were still Oracle. It didn't break anything until probably a cleanup forced those properties to be used.
Setting it to postgresql for good (bsc#1244934)
No difference.
- No tests: search server is not tested
Issue(s): https://github.com/SUSE/spacewalk/issues/27568 …
> Change the search server defaults to postgresql

- java/code/src/com/redhat/rhn/frontend/action/systems/SystemSearchHelper.java
- java/spacewalk-java.changes.welder.bsc1244298
This PR fixes an Internal Server Error (500) caused by a `ConcurrentModificationException` when removing items from a collection during iteration.
Replaced the manual for-each loop with a removeIf lambda expression, ensuring safe removal during iteration.
No difference.
- No tests
Issue(s): https://github.com/SUSE/spacewalk/issues/27461 …
> Fix ISE when using SSM in advanced search (bsc#1244298)

- client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes.mcalmer.cleanup-spacewalk-client-tools-deps
- client/rhel/spacewalk-client-tools/spacewalk-client-tools.spec
- client/tools/mgr-push/mgr-push.changes.mcalmer.cleanup-spacewalk-client-tools-deps
- client/tools/mgr-push/mgr-push.spec
- python/spacewalk/spacewalk-backend.changes.mcalmer.cleanup-spacewalk-client-tools-deps
- python/spacewalk/spacewalk-backend.spec
We dropped a lot of code from spacewalk-client-tools but never cleaned up the python dependencies in the RPM spec file.
As we dropped the registration part which did also provide hardware data, we can remove a lot of these dependencies:
- dbus
- dmidecode
- ethtool
- hwdata
- udev
- pygobject2
- hal
No difference.
Port(s): No ports - only 5.1 and later …
> Remove unused python dependencies

- containers/proxy-httpd-image/proxy-httpd-image.changes.mcalmer.adapt-container-cleanup
- containers/proxy-httpd-image/remove_unused.sh
Seems that perl is not installed anymore.
Now `rpm -e perl` report and error and let the container build fail.
We need to remove this.
No difference.
Port(s): Not needed
Check [How to …
> Remove perl from cleanup as it is not installed anymore by default

- testsuite/features/support/constants.rb
Creating an activation key using the API for debian 12 minions is failing.
The issue is caused by missing base channel declaration for debian 12
No difference.
Issue(s): # …
> Add missing base channel for debian12

- testsuite/features/support/env.rb
Explicitly sets the argument so that the spawned webdriver Chromium instances can correctly retrieve stored certs from the NSS database, when running in a Cloud environment.
No difference.
- Cucumber tests' setup was modified.
Issue(s):  https://github.com/SUSE/spacewalk/issues/26989
Port(s): 
- 5.0 (?): https://github.com/SUSE/spacewalk/pull/27342
> Set user-data-dir when in a Cloud environment

- testsuite/features/support/commonlib.rb
Raise an error if API system.search_by_name is empty.
This should contain the issue within the scope of the test framework and not show errors on the server.
No difference.
- No tests
Ports:
- Manager-5.0
- Manager-4.3
If you need …
> Raise an error if API system.search_by_name is empty

- testsuite/features/support/env.rb
This PR starts chrome with `--no-sandbox` `--disable-notifications`,
with the hope to remove the `Net::ReadTimeout` problem
No difference.
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/27767
* 5.0: https://github.com/SUSE/spacewalk/pull/27768
> Start chrome with --no-sandbox --disable-notifications

- testsuite/features/secondary/srv_maintenance_windows.feature
During the maintenance windows feature tests, we press the "Create" button while the main menu page is still downloading. We reach the new "create" page, but then it is replaced again by main menu when it finishes downloading!
The fix consists in waiting for the page to download before pressing the button.
This PR also does cosmetical changes in scenario names.
No difference.
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/27794
* 5.0: https://github.com/SUSE/spacewalk/pull/27795
> Wait for page to be downloaded before we press a button

- testsuite/features/secondary/srv_virtual_host_manager.feature
Wait for VHM page to finish downloading before pressing "Detete"
Tested on Head, 100% working after the change
No difference.
Cucumber tests were modified.
Issue(s): #27196
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/27805
* 5.0: https://github.com/SUSE/spacewalk/pull/27806
> Wait for VHM page to finish downloading before pressing "Delete"

- testsuite/features/support/env.rb
Disable GPU for Chrome in the hope of no "tab crashed" error.
No difference.
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/27834
* 5.0: https://github.com/SUSE/spacewalk/pull/27835
> Disable GPU for Chrome in the hope of no "tab crashed"

- spacecmd/spacecmd.changes
- spacecmd/spacecmd.changes.mcalmer.fix-build-spacecmd-on-ubuntu
- spacecmd/spacecmd.spec
On Ubuntu 24.04 python_sitelib was evaluating to "" (nothing) and spacecmd files were installed in /.
This cause import errors when calling spacecmd command.
No difference.
Issue(s): 
Port(s):  …
> Fix installation of python lib files on Ubuntu 24.04 (bsc#1246586)

- testsuite/features/support/env.rb
Revert commit cd768da530d00ef772d68fa630bf87d89593eb62
It did not help with `crashed tab` issue, and it even seemed to slow down the chrome renderer.
No difference.
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/27850
* 5.0: https://github.com/SUSE/spacewalk/pull/27851
> Revert --disable-gpu flag addition

- testsuite/features/support/env.rb
This PR fixes the maxumum Javascript heap size option:
* wrong: `--js-flags=--max_old_space_size=2048`
* correct:  `--js-flags=--max-old-space-size=2048`
Note: this bug had no practical effect, the default is 4096, and in practice the Javascript heap size never grew beyong 320 MiB.
This PR also does cosmetical changes for readability:
* add double dashes everywhere
* vertical array of options
Port(s):
* 4.3: https://github.com/SUSE/spacewalk/pull/27879
* 5.0: https://github.com/SUSE/spacewalk/pull/27878
> Maximum Javascript heap size option uses dashes

- java/code/src/com/redhat/rhn/frontend/servlets/LocalizedEnvironmentFilter.java
- java/spacewalk-java.changes.cbbayburt.bsc1244641
Remove the stale thread-local session ID to prevent cross-session leaks in remote command websocket handling.
Port of: https://github.com/SUSE/spacewalk/pull/27770
https://bugzilla.suse.com/show_bug.cgi?id=1246119 …
> Clean up stale sessions on websocket open (bsc#1246119)

- python/spacewalk/satellite_tools/download.py
- python/spacewalk/satellite_tools/repo_plugins/deb_src.py
- python/spacewalk/satellite_tools/repo_plugins/yum_src.py
- python/spacewalk/spacewalk-backend.changes.meaksh.Manager-5.0-bsc1245005
- python/test/unit/spacewalk/satellite_tools/test_yum_src.py
- testsuite/features/build_validation/core/srv_first_settings.feature
- testsuite/features/core/srv_first_settings.feature
- testsuite/features/step_definitions/command_steps.rb
This PR fixes an issue in `spacewalk-repo-sync` when a `/` is passed as part of an HTTP proxy password. This leads to an exception that logs sensitive data.
By default, the `quote` function has `safe = '/'`, which prevents the slash to be quoted, leading to breaking the URL format if `/` is used.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27588 …
> Do not expose sensitive data when breaking URL format (bsc#1245005)

- java/code/src/com/suse/manager/webui/controllers/admin/AdminViewsController.java
- java/spacewalk-java.changes.carlo.uyuni-fix-1244220-links-peripherals
Fixes behaviour of the URLs linking to the peripherals
Both URLs:
https://<SERVER>/rhn/manager/admin/hub/peripherals/<ANY_UNDEFINED-NUMBER>/ 
https://<SERVER>/rhn/manager/admin/hub/peripherals/<ANY_UNDEFINED-NUMBER>/sync-channels
now return "Peripheral not found" rather than "500 Internal Server Error"
No difference.
Issue(s):  https://github.com/SUSE/spacewalk/issues/27496
Port(s): not backported to 4.3 nor to 5.0 (ISSv3 hub online sync) …
> Fix ISSv3: Inconsistent behavior of the URLs linking to peripherals (bsc#1244220)

- java/code/src/com/redhat/rhn/frontend/action/ssm/ProvisioningRemoteCommand.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/spacewalk-java.changes.carlo.uyuni-fix-1243825-ssm-no-link-action-chain
When a remote command is scheduled for an action chain in the System Set Manager, the message in the "blue box" creates a link with the name of action chain the user can click on.
Before:
After:
Issue(s): https://github.com/SUSE/spacewalk/issues/27376
Port(s): https://github.com/SUSE/spacewalk/pull/27474, https://github.com/SUSE/spacewalk/pull/27475
> Fix action chain scheduled within SSM creates no link for the new action chain (bsc#1243825)

- java/code/src/com/redhat/rhn/frontend/action/satellite/BootstrapConfigAction.java
- java/code/src/com/redhat/rhn/frontend/action/satellite/test/BootstrapConfigActionTest.java
- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/manager/satellite/ConfigureBootstrapCommand.java
- java/code/src/com/redhat/rhn/manager/satellite/test/ConfigureBootstrapCommandTest.java
- java/code/webapp/WEB-INF/pages/admin/config/bootstrap.jsp
- java/spacewalk-java.changes.carlo.uyuni-fix-1244329-leftover-salt-checkbox
Removes "Bootstrap using Salt" checkbox in Admin>Manager Configuration>Bootstrap Script web page.
The only possible way to bootstrap a system in 5.1 is via Salt.
Before:
After:
- [x ] **DONE**
Issue(s): https://github.com/SUSE/spacewalk/issues/27506
Port(s): https://github.com/SUSE/spacewalk/pull/27520, not backported to 4.3 (traditional) …
> Leftover 'Bootstrap using Salt' checkbox in bootstrap script web page (bsc#1244329)

- java/code/src/com/redhat/rhn/domain/server/test/ServerFactoryTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/activationkey/test/ActivationKeyHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/admin/monitoring/test/AdminMonitoringHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/configchannel/test/ConfigChannelHandlerTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/image/profile/test/ImageProfileHandlerTest.java
- java/code/src/com/redhat/rhn/manager/action/test/ActionManagerTest.java
- java/code/src/com/redhat/rhn/manager/formula/test/FormulaManagerTest.java
- java/code/src/com/redhat/rhn/manager/system/VirtualInstanceManager.java
- java/code/src/com/redhat/rhn/taskomatic/core/SchedulerKernel.java
- java/code/src/com/suse/manager/xmlrpc/admin/test/AdminPaygHandlerTest.java
SonarCloud error reduction fix, rule java:S108 Nested blocks of code should not be left empty
An empty code block is confusing. It will require some effort from maintainers to determine if it is intentional or indicates the implementation is incomplete.
Removing or filling the empty code blocks takes away ambiguity and generally results in a more straightforward and less surprising code.
No difference.
Issue(s): https://github.com/uyuni-project/uyuni/issues/9878 …
> SonarCloud fix: java:S108 Nested blocks of code should not be left empty

- java/code/src/com/redhat/rhn/frontend/action/BaseSearchAction.java
- java/code/src/com/redhat/rhn/frontend/taglibs/list/ListTagUtil.java
- java/code/src/com/suse/manager/webui/utils/SparkApplicationHelper.java
SonarCloud error reduction fix, rule java:S1192 String literals should not be duplicated
Duplicated string literals make the process of refactoring complex and error-prone, as any change would need to be propagated on all occurrences.
Exceptions: To prevent generating some false-positives, literals having less than 5 characters are excluded.
No difference.
Issue(s): https://github.com/uyuni-project/uyuni/issues/9878
> SonarCloud fix: java:S1192 String literals should not be duplicated

- java/code/src/com/redhat/rhn/domain/contentmgmt/validation/ContentPropertiesValidator.java
- java/code/src/com/redhat/rhn/frontend/action/audit/scap/XccdfSearchAction.java
- java/code/src/com/redhat/rhn/frontend/action/errata/ErrataSearchAction.java
- java/code/src/com/redhat/rhn/frontend/action/kickstart/KickstartLocaleEditAction.java
- java/code/src/com/redhat/rhn/frontend/action/multiorg/OrgConfigAction.java
- java/code/src/com/redhat/rhn/frontend/action/user/UserEditActionHelper.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/activationkey/ActivationKeyHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/profile/ProfileHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/kickstart/profile/system/SystemDetailsHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/org/OrgHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ConfigRevisionSerializer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/serializer/ScriptResultSerializer.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/XmlRpcSystemHelper.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/config/ServerConfigHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/systemgroup/ServerGroupHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
- java/code/src/com/redhat/rhn/manager/action/ActionChainManager.java
- java/code/src/com/redhat/rhn/manager/contentmgmt/ContentManager.java
- java/code/src/com/redhat/rhn/manager/kickstart/KickstartOptionsCommand.java
- java/code/src/com/redhat/rhn/manager/kickstart/tree/TreeDeleteOperation.java
- java/code/src/com/redhat/rhn/manager/system/SystemManager.java
- java/code/src/com/suse/manager/api/HttpApiRegistry.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/webui/controllers/channels/ChannelsApiController.java
- java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java
- java/code/src/com/suse/manager/webui/services/subscriptionmatching/SubscriptionMatchProcessor.java
- java/code/src/com/suse/manager/webui/utils/LoginHelper.java
SonarCloud error reduction fix, rule java:S5411 Avoid using boxed "Boolean" types directly in boolean expressions
When boxed type java.lang.Boolean is used as an expression to determine the control flow (as described in [Java Language Specification §4.2.5 The boolean Type and boolean Values](https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.2.5)) it will throw a NullPointerException if the value is null (as defined in [Java Language Specification §5.1.8 Unboxing Conversion](https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.1.8)).
It is safer to avoid such conversion altogether and handle the null value explicitly.
Note, however, that no issues will be raised for Booleans that have already been null-checked or are marked @NonNull/@NotNull
No difference.
- …
> SonarCloud fix: java:S5411 Avoid using boxed "Boolean" types directly in boolean expressions

- java/code/src/com/redhat/rhn/common/db/datasource/ModeFactory.java
- java/code/src/com/redhat/rhn/common/security/acl/SystemAclHandler.java
- java/code/src/com/redhat/rhn/common/validator/StringConstraint.java
- java/code/src/com/redhat/rhn/frontend/action/kickstart/PowerManagementAction.java
- java/code/src/com/redhat/rhn/frontend/action/kickstart/ssm/test/SsmKSScheduleActionTest.java
- java/code/src/com/redhat/rhn/frontend/action/kickstart/test/PowerManagementActionTest.java
- java/code/src/com/redhat/rhn/frontend/action/ssm/test/PowerManagementConfigurationActionTest.java
- java/code/src/com/redhat/rhn/frontend/servlets/RhnHttpServletRequest.java
- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/content/test/ContentSyncManagerPaygTest.java
- java/code/src/com/redhat/rhn/taskomatic/task/ForwardRegistrationTask.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/CompressingDigestOutputWriter.java
- java/code/src/com/suse/manager/webui/services/ConfigChannelSaltManager.java
- java/code/src/org/cobbler/Profile.java
SonarCloud error reduction fix, rules:
[ java:S1110 Redundant pairs of parentheses should be removed](https://sonarcloud.io/organizations/uyuni-project/rules?open=java%3AS1110&rule_key=java%3AS1110)
[ java:S4349 write(byte[],int,int) should be overridden](https://sonarcloud.io/organizations/uyuni-project/rules?open=java%3AS4349&rule_key=java%3AS4349)
[ java:S1149 Synchronized class Vector should not be used](https://sonarcloud.io/organizations/uyuni-project/rules?open=java%3AS1149&rule_key=java%3AS1149)
[ java:S2696 Instance methods should not write to static fields](https://sonarcloud.io/organizations/uyuni-project/rules?open=java%3AS2696&rule_key=java%3AS2696)
[ java:S4719 StandardCharsets constants should be preferred](https://sonarcloud.io/organizations/uyuni-project/rules?open=java%3A …
> SonarCloud error reduction fix, rules 1110, 4349, 1149, 2696, 4719, 6213

- java/code/src/com/suse/manager/api/RouteFactory.java
- java/spacewalk-java.changes.mcalmer.fix-exceptions-for-restapi
Partly port of https://github.com/uyuni-project/uyuni/pull/10589
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27854
Port(s): https://github.com/SUSE/spacewalk/pull/27920 …
> return json also when exception is not a FaultException (bsc#1246452)

- java/code/src/com/redhat/rhn/domain/action/ActionFactory.java
- java/code/src/com/redhat/rhn/domain/action/Action_legacyUser.hbm.xml
- java/code/src/com/redhat/rhn/domain/action/VirtualInstanceRefreshAction.java
- java/code/src/com/redhat/rhn/taskomatic/task/gatherer/GathererJob.java
- java/code/src/com/redhat/rhn/taskomatic/task/matcher/MatcherJob.java
- java/code/src/com/suse/manager/reactor/messaging/ApplyStatesEventMessage.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/webui/services/SaltServerActionService.java
- java/code/src/com/suse/manager/webui/utils/salt/custom/VmInfoSlsResult.java
- java/spacewalk-java.changes.mcalmer.gather-virtualization-data
- schema/spacewalk/common/data/rhnActionType.sql
- schema/spacewalk/susemanager-schema.changes.mcalmer.gather-virtualization-data
- schema/spacewalk/upgrade/susemanager-schema-5.1.10-to-susemanager-schema-5.1.11/010-add-virt-refresh_list-actiontype.sql
- susemanager-utils/susemanager-sls/salt/hardware/virtprofile.sls
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.gather-virtualization-data
After removing the virtualization feature we need to take care to still get the virtual host <=> guest relation for
SCC reporting.
This PR use salt virt.vm_info execution module to get the virtual instances running on physical systems.
The gatherer taskomatic job execute this one time per day only on physical salt managed nodes to get up to date data.
No difference.
Issue(s): SUSE/spacewalk#25437
If you …
> get virtual instance info from physical hosts using salt virt.vm_info

- java/code/src/com/redhat/rhn/manager/system/proxycontainerconfig/ProxyContainerConfigCreateAcquisitor.java
- java/spacewalk-java.changes.cbosdo.5.0-proxy-fix
When creating the proxy configuration for an existing system we need to save the changes in the Server object to have them in the DB.
We also need to trigger an update of the systems list cache table for the changed server.
bsc#1239158
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/26643
Port(s): https://github.com/SUSE/spacewalk/pull/26950 …
> Save proxy info when converting a system to proxy

- java/code/src/com/redhat/rhn/common/conf/ConfigDefaults.java
- java/code/src/com/redhat/rhn/common/hibernate/AnnotationRegistry.java
- java/code/src/com/redhat/rhn/frontend/action/errata/test/ErrataDetailsSetupActionTest.java
- java/code/src/com/redhat/rhn/frontend/strings/java/StringResource_en_US.xml
- java/code/src/com/redhat/rhn/manager/channel/ChannelManager.java
- java/code/src/com/redhat/rhn/manager/errata/ErrataManager.java
- java/code/src/com/redhat/rhn/taskomatic/task/ErrataAdvisoryMapSync.java
- java/code/src/com/redhat/rhn/taskomatic/task/repomd/UpdateInfoWriter.java
- java/code/src/com/suse/manager/errata/ErrataParserFactory.java
- java/code/src/com/suse/manager/errata/SUSEAdvisoryMapErrataParser.java
- java/code/src/com/suse/manager/errata/advisorymap/ErrataAdvisoryMapManager.java
- java/code/src/com/suse/manager/errata/advisorymap/test/ErrataAdvisoryMapManagerTest.java
- java/code/src/com/suse/manager/errata/model/errata/ErrataAdvisoryMap.java
- java/code/src/com/suse/manager/errata/model/errata/ErrataAdvisoryMapFactory.java
- java/code/src/com/suse/manager/errata/test/BaseErrataTestCase.java
- java/code/src/com/suse/manager/errata/test/SUSEAdvisoryMapErrataParserTest.java
- java/conf/rhn_java.conf
- java/spacewalk-java.changes.carlo.uyuni-fix-1243808-suse-advisory-url
- schema/spacewalk/common/data/rhnTaskoBunch.sql
- schema/spacewalk/common/data/rhnTaskoSchedule.sql
- schema/spacewalk/common/data/rhnTaskoTask.sql
- schema/spacewalk/common/data/rhnTaskoTemplate.sql
- schema/spacewalk/common/tables/suseErrataAdvisoryMap.sql
- schema/spacewalk/postgres/data/reschedule.sql
- schema/spacewalk/susemanager-schema.changes.carlo.uyuni-fix-1243808-suse-advisory-url
- schema/spacewalk/upgrade/susemanager-schema-5.1.10-to-susemanager-schema-5.1.11/100-create-suseErrataAdvisoryMap.sql
- schema/spacewalk/upgrade/susemanager-schema-5.1.10-to-susemanager-schema-5.1.11/101-errata-advisory-map-taskomatic.sql
- schema/spacewalk/upgrade/susemanager-schema-5.1.10-to-susemanager-schema-5.1.11/102-errata-advisory-map-taskomatic-reschedule.sql
- susemanager-utils/testing/docker/scripts/pre_idempotency_test_query.sql
- susemanager-utils/testing/docker/scripts/schema_idempotency_test_pgsql.py
Given a SUSE errata advisory (e.g. "SUSE-15-SP6-2025-1733"), both the announcementID (e.g. "SUSE-RU-2025:1733-1") and the advisory url (e.g. "https://www.suse.com/support/update/announcement/2025/suse-ru-202501733-1/") were computed from the errata data, through the class SUSEErrataParser.
The numbering is not anymore following a rule, so the only option to get these data is to download once per day a file from https://ftp.suse.com/pub/projects/security/advisory-map.csv, collect this association data in a table and get the data from there
After:
- Documentation issue was created: https://github.com/uyuni-project/uyuni-docs/pull/4080
Issue(s): # https://github.com/SUSE/spacewalk/issues/27375
Port(s): https://github.com/SUSE/spacewalk/pull/27625, …
> Fix Vendor Advisory URL in SUSE Manager directing to error 404 not found (bsc#1243808)

- java/code/src/com/redhat/rhn/domain/action/rhnpackage/PackageRefreshListAction.java
- java/code/src/com/redhat/rhn/domain/entitlement/test/ContainerBuildHostEntitlementTest.java
- java/code/src/com/redhat/rhn/domain/server/Server.java
- java/code/src/com/redhat/rhn/domain/server/ServerConstants.java
- java/code/src/com/redhat/rhn/domain/server/test/ServerFactoryTest.java
- java/code/src/com/redhat/rhn/domain/server/test/ServerTest.java
- java/code/src/com/redhat/rhn/frontend/action/rhnpackage/LockPackageAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/ErrataSetupAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/audit/ScapSetupAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/audit/test/ScapSetupActionTest.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/test/SystemHandlerTest.java
- java/code/src/com/redhat/rhn/manager/distupgrade/DistUpgradeManager.java
- java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java
- java/code/src/com/suse/manager/reactor/messaging/test/JobReturnEventMessageActionTest.java
- java/code/src/com/suse/manager/webui/controllers/StatesAPI.java
As per https://github.com/uyuni-project/uyuni/pull/10564#discussion_r2200519431, the string representing SUSE os family has been made public and re-used also on other places where we check for os_family = Suse
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/13569 …
> Simplify action handling (step 4 - unifying os family constants) 

- java/code/src/com/redhat/rhn/frontend/strings/jsp/StringResource_en_US.xml
- java/code/webapp/WEB-INF/pages/systems/spmigration/spmigration-confirm.jsp
- java/code/webapp/WEB-INF/pages/systems/spmigration/spmigration-setup.jsp
- java/code/webapp/WEB-INF/pages/systems/spmigration/spmigration-target.jsp
- java/spacewalk-java.changes.bisht-richa.update-product-migration-page
- web/spacewalk-web.spec
- Added visual indicators with tooltips to disabled products to clearly explain their unavailability.
- Disabled "Dry Run" button with a tooltip, when the feature isn't supported.
- Hide the "Allow vendor change" checkbox on the previous page as it has no effect on RedHat systems.
No difference.
Before:
After:
Fixes: https://github.com/SUSE/spacewalk/issues/25566
Fixes: https://github.com/SUSE/spacewalk/issues/25143 …
> Update UI product migration page

- testsuite/features/build_validation/reposync/srv_sync_all_products.feature
- testsuite/features/reposync/allcli_update_activationkeys.feature
- testsuite/features/reposync/srv_sync_products.feature
partially reverts https://github.com/uyuni-project/uyuni/pull/10735 because the proxy 5.2 is not yet ready in SCC or sumatoolbox. It will come October or November and we can not wait until then. We will use proxy 5.1 until it's ready
No difference.
Issue(s): no issue directly from testsuite review and slack
Port(s): no ports, it's only for head, only that uses server 5.2 …
> Revert testsuite using proxy 5.2

- testsuite/features/support/commonlib.rb
split from https://github.com/uyuni-project/uyuni/pull/10531, specifically it's this commit https://github.com/uyuni-project/uyuni/pull/10531/commits/c87e27a8468f5f61bc6c7909a7158b772b08aeee to make it separate from openeuler because it seems it might not be needed in the BV. But this commonlib refactor is needed
No difference.
Issue(s): no issue directly from testsuite review
Port(s): 
5.0: https://github.com/SUSE/spacewalk/pull/27910
4.3: https://github.com/SUSE/spacewalk/pull/27911 …
> Refactor commonlib to match edge cases

- testsuite/features/step_definitions/command_steps.rb
- testsuite/features/upload_files/edit-deb822.awk
The previous version of edit-deb822.awk didn't enable/disable the suite, but just add a new component on the sources.
This script in addition to add the component, it will:
- Enable/Disable the correct suite
- Fix "Architectures" block, when it's empty
No difference.
Ports:
- Manager-4.3
- Manager-5.0
If …
> Fix AWK script to edit Debian/Ubuntu repos

- utils/spacewalk-common-channels.ini
After creation of the first Tumbleweed Uyuni Client Tools repos change spacewalk-common-channels.ini to use them
instead of the old saltbundle repo directly.
No difference.
Port(s): no ports …
> use new tumbleweed-client-tools repos

- spacecmd/spacecmd.changes.mczernek.mczernek-fsck-removal-fix
- spacecmd/src/spacecmd/utils.py
- spacecmd/tests/test_utils.py
In this PR, we remove pickle for internal spacecmd cache in favor of using basic JSON files.
Looking at https://github.com/m-czernek/uyuni/blob/edf004ebeee0e0d763bb1a3b906664c315b30b5f/spacecmd/src/spacecmd/misc.py#L137, I believe only errata, systems, and packages use this particular caching mechanism, which all seem to work.
An open question is Python 2.7, which I haven't tried. Spacecmd seems to be compatible with Py 2.7 in case it is execute from a client. Not sure if this is still a concern - if so, let me know, I'll have to do additional testing.
No difference.
- Documentation issue was created: [Link for SUSE Multi-Linux …
> Use JSON instead of pickle for spacecmd cache (bsc#1227579)

- python/spacewalk/satellite_tools/reposync.py
- python/spacewalk/server/importlib/packageImport.py
- python/spacewalk/server/rhnPackage.py
- python/spacewalk/server/rhnPackageUpload.py
- python/spacewalk/spacewalk-backend.changes.mczernek.prepend-dir-fix
We get sporadic reports of the following error during reposync:
```
14:19:13     6758/6758 : wkhtmltopdf-opt-0.12.4-3.el8.remi.x86_64.rpm
14:19:14 Filtering packages that failed to download
14:19:14 
14:19:14   Importing packages to DB:
14:19:14 PREPENDED_DIR
14:19:14 PREPENDED_DIR
```
This seems not directly reproducible (we have not determined root cause), but we suspect that this is the result of direct access to `CFG`, where one component doesn't properly close the namespace while another component accesses it with unexpected/incorrect namespace.
In this PR, we use the `cfg_component` context manager to force proper initCFG.
No difference.
Before:
After:
Issue(s): …
> Remove direct access to CFG when importing pkgs

- spacecmd/spacecmd.changes.mczernek.cache-fix-py27
- spacecmd/src/spacecmd/utils.py
- spacecmd/tests/test_utils.py
Spacecmd still supports python 2.7. In this PR, I'm removing Py 2.7 incompatible code. 
Porting of https://github.com/SUSE/spacewalk/pull/28219
Issue(s): Related to https://github.com/SUSE/spacewalk/issues/24760
Port(s): 
- 4.3: https://github.com/SUSE/spacewalk/pull/28219
- 5.0: https://github.com/SUSE/spacewalk/pull/28234
- 5.1: added the commit to still-open original PR at https://github.com/SUSE/spacewalk/pull/28184 …
> Make spacecmd code compatible with Py 2.7

- java/code/src/com/redhat/rhn/frontend/xmlrpc/channel/software/ChannelSoftwareHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/errata/ErrataHandler.java
- java/spacewalk-java.changes.mcalmer.Manager-5.0-doc-errata-api
API doc enhancement.
- API documentation added
- No tests: **only doc**
Port(s): https://github.com/SUSE/spacewalk/pull/28199
> enhance API documentation about errata cloning (bsc#1244519)

- susemanager-utils/testing/docker/scripts/reportdb_schema_idempotency_test_pgsql.py
- susemanager-utils/testing/docker/scripts/schema_idempotency_test_pgsql.py
New postgres 16.10 database changed the pg_dump command and add a \restrict \unrestrict with a unique token to the output. This let the test fail.
Use sed to remove the token to fix the migration tests
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/28241 …
> Fix schema migration tests

- testsuite/features/secondary/srv_maintenance_windows.feature
This PR contains 2 commits:
1. Wait until page has fully loaded before pressing button
I have tried very hard, but I have found no other way to make sure the page has fully loaded than to wait for 1 second.
Strangely enough, this affects only Uyuni. All other branches are okay with just waiting for some text to appear.
2. Rename button
For whatever reason, "Install Selected Packages" has become "Install Packages".
No difference.
No ports, Head only.
> Maintenance window waits

- spacecmd/spacecmd.changes.mczernek.py2-spacecmd
- spacecmd/src/spacecmd/utils.py
Fix build failures on Python 2.7.
With this change, the pkg finally builds for `systemsmanagement:Uyuni:Master:CentOS7-Uyuni-Client-Tools/spacecmd`
```
$ osc build
...
[    6s] + cd /home/abuild/rpmbuild/BUILD
[    6s] + cd spacecmd-git-507.8fccef7
[    6s] + /usr/bin/rm -rf /home/abuild/rpmbuild/BUILDROOT/spacecmd-5.2.0-0.x86_64
[    6s] + exit 0
[    6s] ... checking for files with abuild user/group
[    6s] 
[    6s] t14s finished "build spacecmd.spec" at Thu Sep  4 08:46:43 UTC 2025.
[    6s] 
/var/tmp/build-root/CentOS_7-x86_64/home/abuild/rpmbuild/SRPMS/spacecmd-5.2.0-0.src.rpm
/var/tmp/build-root/CentOS_7-x86_64/home/abuild/rpmbuild/RPMS/noarch/spacecmd-5.2.0-0.noarch.rpm
```
Issue(s): Related to https://github.com/SUSE/spacewalk/issues/24760
Port(s): …
> Do not re-raise exceptions in spacecmd

- schema/spacewalk/susemanager-schema.changes.mcalmer.fix-schema-migration-virt-removal
- schema/spacewalk/upgrade/susemanager-schema-5.1.0-to-susemanager-schema-5.1.1/003-virt-removal.sql
The action_type reference in rhnAction does not have a "ON DELETE CASCADE".
When we remove action types, we need to remove the actions manually before we can remove the types.
This change an old migration to fix the problem for all which execute this after updating to this version.
No difference.
- No tests: **manually**
Issue(s): https://bugzilla.suse.com/show_bug.cgi?id=1249178
Port(s): https://github.com/SUSE/spacewalk/pull/28292
If …
> delete actions which use a virtualization action type (bsc#1249178)

- java/code/src/com/redhat/rhn/common/conf/test/ConfigTest.java
- java/code/src/com/redhat/rhn/domain/server/ServerSnapshot.java
- java/code/src/com/redhat/rhn/frontend/action/audit/scap/XccdfSearchHelper.java
- java/code/src/com/redhat/rhn/frontend/action/channel/ChannelDetailsAction.java
- java/code/src/com/redhat/rhn/frontend/action/multiorg/OrgCreateAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/SPMigrationAction.java
- java/code/src/com/redhat/rhn/frontend/action/systems/provisioning/kickstart/SessionStatusAction.java
- java/code/src/com/redhat/rhn/frontend/action/user/CreateUserAction.java
- java/code/src/com/redhat/rhn/frontend/action/user/UserEditActionHelper.java
- java/code/src/com/redhat/rhn/frontend/dto/ChannelTreeNode.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/system/SystemHandler.java
- java/code/src/com/redhat/rhn/frontend/xmlrpc/user/UserHandler.java
- java/code/src/com/redhat/rhn/manager/audit/AuditChannelInfo.java
- java/code/src/com/redhat/rhn/manager/audit/CVEAuditManager.java
- java/code/src/com/redhat/rhn/manager/audit/CVEAuditManagerOVAL.java
- java/code/src/com/redhat/rhn/manager/audit/ErrataIdAdvisoryPair.java
- java/code/src/com/redhat/rhn/manager/audit/ServerChannelIdPair.java
- java/code/src/com/redhat/rhn/manager/content/ContentSyncManager.java
- java/code/src/com/redhat/rhn/manager/kickstart/KickstartScheduleCommand.java
- java/code/src/com/redhat/rhn/manager/setup/ProxySettingsDto.java
- java/code/src/com/suse/manager/maintenance/IcalUtils.java
- java/code/src/com/suse/manager/maintenance/MaintenanceManager.java
- java/code/src/com/suse/manager/model/gatherer/GathererModule.java
- java/code/src/com/suse/manager/reactor/hardware/HardwareMapper.java
- java/code/src/com/suse/manager/utils/SaltUtils.java
- java/code/src/com/suse/manager/webui/controllers/CVEAuditController.java
- java/code/src/com/suse/manager/webui/controllers/utils/ImagesUtil.java
- java/code/src/com/suse/manager/webui/services/SaltStateGeneratorService.java
- java/code/src/com/suse/manager/webui/utils/SparkApplicationHelper.java
- java/code/src/org/cobbler/CobblerObject.java
SonarCloud error reduction fix, rules:
[SonarCloud fix: java:S2184 Math operands should be cast before assignment](https://sonarcloud.io/organizations/uyuni-project/rules?open=java%3AS2184&rule_key=java%3AS2184)
[SonarCloud fix: java:S4034 Stream call chains should be simplified when possible](https://sonarcloud.io/organizations/uyuni-project/rules?open=java%3AS4034&rule_key=java%3AS4034)
[SonarCloud fix: java:S1126 Return of boolean expressions should not be wrapped into an if-then-else statement](https://sonarcloud.io/organizations/uyuni-project/rules?open=java%3AS1126&rule_key=java%3AS1126)
[SonarCloud fix: java:S1319 Declarations should use Java collection interfaces rather than specific implementation classes](https://sonarcloud.io/organizations/uyuni-project/rules?open=java%3AS1319&r …
> SonarCloud error reduction fix, miscellaneous 6 rules

- java/code/src/com/suse/manager/webui/services/subscriptionmatching/SubscriptionMatchProcessor.java
- java/code/src/com/suse/manager/webui/services/subscriptionmatching/test/SubscriptionMatchProcessorTest.java
[SonarCloud fix: java:S1874 Deprecated code should not be used](https://sonarcloud.io/organizations/uyuni-project/rules?open=java%3AS1874)
a local deprecated class Pair has been removed and substituted with org.apache.commons.lang3.tuple.Pair
No difference.
Before:
After:
Issue(s): https://github.com/uyuni-project/uyuni/issues/9878
Port(s):  …
> SonarCloud fix: java:S1874 Deprecated code should not be used

- java/code/src/com/suse/manager/webui/Router.java
- java/code/src/com/suse/manager/webui/controllers/admin/handlers/HubApiController.java
- java/spacewalk-java.changes.mcalmer.fix-scheduling-of-channel-sync
The Sync Channels button in Hub Details only create a Task Schedule, but does not create the quartz job.
This defines only the job, but does not execute it.
Using the taskomatic API to schedule the bunch works.
No difference.
Port(s): https://github.com/SUSE/spacewalk/pull/28274 …
> Fix scheduling of channel sync

- java/code/src/com/redhat/rhn/domain/token/Token.java
- java/spacewalk-java.changes.carlo.uyuni-1249059-configuration-channel-ranking
Fixes Bug 1249059 - L3: Changing Configuration Channel Ranking in Activation Key results in 'Internal Server Error'
The table `rhnRegTokenConfigChannels` contains 3 columns: `token_id`, `config_channel_id` and `position`.
There is a unique index defined on the pair  `(token_id, config_channel_id)`
> `CREATE UNIQUE INDEX rhn_regtok_confchan_t_cc_uq   ON rhnRegTokenConfigChannels (token_id, config_channel_id);`
This constraint creates trouble when the ranking (i.e. position) is changed, resulting in an error like:
> duplicate key value violates unique constraint "rhn_regtok_confchan_t_cc_uq"  Detail: Key (token_id, config_channel_id)=(1, 1) already exists.
the annotation in `Token` class solves the problem:
```
@org.hibernate.annotations.CollectionType(
type = …
```
> Bugfix L3: Changing configuration channel ranking in activation key results in internal server error (bsc#1249059)

- java/code/src/com/redhat/rhn/domain/reactor/SaltEvent.hbm.xml
- java/code/src/com/redhat/rhn/domain/reactor/SaltEventFactory.java
- java/code/src/com/redhat/rhn/domain/reactor/test/SaltEventFactoryTest.java
- java/spacewalk-java.changes.mcalmer.change-salt-queue-allocation
- susemanager-utils/susemanager-sls/modules/engines/mgr_events.py
- susemanager-utils/susemanager-sls/susemanager-sls.changes.mcalmer.change-salt-queue-allocation
With the current allocation algorithm we cannot say if we equally allocate the events over all queues.
It might happen that a few queues are fully loaded and events must wait, while others are empty.
The idea of a better allocation algorithm is, that we use for new minion ids the queue with the fewest entries.
If a minion id has already an event waiting to be handled in a queue, we add new events to the same queue.
No difference.
- No tests: manual tested
Issue(s): https://github.com/SUSE/spacewalk/issues/27713
Port(s): To be discussed …
> Change salt queue allocation

- java/code/src/com/redhat/rhn/domain/server/ServerFactory.java
- java/spacewalk-java.changes.mcalmer.Manager-5.0-fix-servergroup-assignment
fix was done before. This add the logging to be alligned with 5.1 and 5.0 branch
Port(s): https://github.com/SUSE/spacewalk/pull/28252
> fix assignment to servergroups

- testsuite/features/secondary/srv_salt_git_pillar.feature
This PR re-enables the acceptance tests for testing gitfs, that was disabled in the past for `Uyuni` and `Manager-5.1`.
NOTE: Theses tests are enabled in `Manager-5.0`.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/28381 …
> testsuite: re-enable tests for gitfs

- testsuite/features/secondary/allcli_system_group.feature
Related to https://github.com/SUSE/spacewalk/issues/27650
I think those issues may be caused by the fact that we schedule the patches to be applied but do not explicitly wait for the corresponding event to be completed.
So, the following tests may try to remove a patched package version that has not been installed yet at that point.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27650
Port(s): 
5.0 - https://github.com/SUSE/spacewalk/pull/28482
5.1 - https://github.com/SUSE/spacewalk/pull/28481
If you need …
> QE: wait event completion after applying patches through SSM

- web/html/src/manager/admin/password-policy/password-policy.tsx
- web/spacewalk-web.changes.bisht-richa.fix-password-policy-form
Input fields activate instantly when their options are checked in the Password Policy form.
Fix: https://github.com/SUSE/spacewalk/issues/27493
No difference.
Before:
After:
Issue(s): [27493](https://github.com/SUSE/spacewalk/issues/27493)
Port(s): [ 5.1](https://github.com/SUSE/spacewalk/pull/28477)
[ 5.0](https://github.com/SUSE/spacewalk/pull/28476) …
> Fix password policy form (bsc#1244430)

- schema/spacewalk/common/tables/rhnPackage.sql
- schema/spacewalk/common/tables/rhnServerNeededCache.sql
- schema/spacewalk/postgres/procs/update_system_overview.sql
- schema/spacewalk/susemanager-schema.changes.oholecek.optimize-system-overview
- schema/spacewalk/upgrade/susemanager-schema-5.2.0-to-susemanager-schema-5.2.1/400-add-missing-indexes.sql
- schema/spacewalk/upgrade/susemanager-schema-5.2.0-to-susemanager-schema-5.2.1/401-optimize-overview-function.sql
Optimize system overview table generation:
- added two missing indexes to prevent seq scans
- simplified two queries:
- computing of various erratas refactored from 3 queries to one. From ~2.7ms down to ~0.5ms
- changed extra pkg count from massive outer join to anti join. From ~20ms down to ~10ms
Currently one iteration for one server in my small system ( 14 servers, synced SL Micro 5.5, 6.0, 6.1; SLE 15 SP5, SP6, SLE 12 SP5 channels):
```
duration: 0.057 ms
duration: 0.087 ms
duration: 0.028 ms
duration: 0.021 ms
duration: 0.482 ms
duration: 0.525 ms
duration: 0.012 ms
duration: 0.027 ms
duration: 0.021 ms
duration: 0.022 ms
duration: 0.015 ms
duration: 0.043 ms
duration: 0.009 ms
duration: 0.003 ms
duration: 0.125 ms
duration: 0.069 ms
duration: 10.328 ms
duration: 0.045 ms
duration: …
```
> System overview generation optimizations

- python/uyuni-cobbler-helper/uyuni-cobbler-helper.spec
In contrast to the documentation in the packaging wiki [0], the compatibility shim is still required in Leap 15.6.
[0]: https://en.opensuse.org/openSUSE:Packaging_Python#Compatibility_shim
Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-bran …
> Fix building uyuni-cobbler-helper on Leap 15.6

- spacecmd/spacecmd.changes.cbbayburt.bsc1249532
- spacecmd/src/spacecmd/api.py
As part of the RBAC implementation, some API methods in the `api` namespace has been changed to not require authentication (see: b023419ebd4039e67164668088b95441d8da9292).
This PR fixes calls to these methods in `spacecmd`
Issue(s): https://github.com/SUSE/spacewalk/issues/28366 …
> Fix methods in api namespace in spacecmd (bsc#1249532)

- spacewalk/setup/bin/spacewalk-setup-cobbler
See title: fix setup failure introduced by the new cobbler templates python helper
No difference.
- No tests: setup broke
Issue(s): # …
> Fix cobbler setup: cheeta's whitelist is empty

- java/code/src/com/redhat/rhn/frontend/xmlrpc/BaseHandler.java
- java/spacewalk-java.changes.cbbayburt.bsc1250424
Fix RBAC authentication for search API methods that authenticate with raw session keys.
https://bugzilla.suse.com/show_bug.cgi?id=1250424
Issue(s): https://github.com/SUSE/spacewalk/issues/28435 …
> Fix authentication for spaceapi search module (bsc#1250424)

- spacecmd/spacecmd.changes.vzhestkov.fix-the-regex
- spacecmd/src/spacecmd/shell.py
Fixes the regession caused by https://github.com/uyuni-project/uyuni/commit/4bf8ea8684fc718991e87ae23c3c3aee1ea31d26 from https://github.com/uyuni-project/uyuni/pull/10330
There was an escape for `-` missing causing parsing a part of regexp as a range.
No difference.
Before:
After:
- No tests: already covered by testsuite
Issue(s): #
Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-pro …
> Fix the regex

- java/code/src/com/suse/manager/reactor/messaging/RegisterMinionEventMessageAction.java
- java/code/src/com/suse/manager/reactor/test/RegisterMinionActionTest.java
- java/spacewalk-java.changes.carlo.uyuni-1246035-bootstrap-script-profile-name-var
- spacewalk/certs-tools/rhn_bootstrap_strings.py
- spacewalk/certs-tools/spacewalk-certs-tools.changes.carlo.uyuni-1246035-bootstrap-script-profile-name-var
The bootstrap script has defined a variable named PROFILENAME to specify profilename for client systems. However later in the script, a variable named PROFILE_NAME is addressed. The variable name  has been changed to match the code by adding the underscore separator.
No difference.
Issue(s): https://github.com/SUSE/spacewalk/issues/27853
Port(s): 5.0: https://github.com/SUSE/spacewalk/pull/28535, 5.1: https://github.com/SUSE/spacewalk/pull/28536 …
> Fix bug 1246035: Correct PROFILE_NAME variable definition in bootstrap script

- client/rhel/spacewalk-client-tools/spacewalk-client-tools-rpmlintrc
- client/rhel/spacewalk-client-tools/spacewalk-client-tools.changes.meaksh.master-fix-builds-for-tumbleweed
- client/tools/mgr-push/__init__.py
- client/tools/mgr-push/mgr-push-rpmlintrc
- client/tools/mgr-push/mgr-push.changes.meaksh.master-fix-builds-for-tumbleweed
- python/rhn/rhnlib.changes.meaksh.master-fix-builds-for-tumbleweed
- python/rhn/rhnlib.spec
- python/rhn/setup.py.in
- python/uyuni/Makefile.defs
- python/uyuni/uyuni-common-libs.changes.meaksh.master-fix-builds-for-tumbleweed
- python/uyuni/uyuni-common-libs.spec
- spacecmd/spacecmd.changes.meaksh.master-fix-builds-for-tumbleweed
- spacecmd/src/spacecmd/system.py
This PR fixes some issues when building couple of packages for openSUSE Tumbleweed.
Additionally, it also fixes two syntax errors found in `spacecmd` and `mgr-push`, breaking syntax on Python 2.7, which is still used in some Client Tools channels (CentOS7 and SLE12).
No difference.
Issue(s): # …
> Fix issues building some packages for openSUSE Tumbleweed

- .devcontainer/dev/Dockerfile
- .devcontainer/dev/devcontainer.json
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/prebuilt_devcontainer.yml
- .vscode/settings.json
https://github.com/uyuni-project/uyuni/wiki/Working-with--Uyuni-Project-Using-DevContainers
No difference.
- (OPTIONAL) …
> Dev container with vscode/Intellij configuration 

- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_head/config.sh
- testsuite/features/profiles/Kiwi/POS_Image-JeOS7_uyuni/config.sh
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_head/config.sh
- testsuite/features/profiles/cloud_aws/Kiwi/POS_Image-JeOS7_uyuni/config.sh
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_head/config.sh
- testsuite/features/profiles/internal_nue/Kiwi/POS_Image-JeOS7_uyuni/config.sh
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_head/config.sh
- testsuite/features/profiles/internal_prv/Kiwi/POS_Image-JeOS7_uyuni/config.sh
This PR removes deprecated helpers from JeOS 7 profile.
This is needed for Kiwi 10. Kiwi 9 should continue working without them.
Reference: [Heads up deprecated config.sh methods](https://groups.google.com/g/kiwi-images/c/LJr0riSDPkY) from Marcus Schäfer on 2021-06-07.
No difference.
Cucumber tests were added
No ports, uyuni branch only, although those files are used by all 3 branches.
> Remove deprecated helpers from JeOS 7 profile
